### ISSUE TITLE
New CLI installation & Migration problem

### ISSUE THREAD

**Issue by madlybong** [directus/directus#23390] opened 2024-08-17 09:44 UTC
### While either creating a new project

Something went wrong while seeding the database:
[ER_INVALID_DEFAULT] alter table `directus_files` add `uploaded_on` timestamp - Invalid default value for 'uploaded_on'

### While upgrading and `npx directus bootstrap`

Error: alter table `directus_files` add `uploaded_on` timestamp - Invalid default value for 'uploaded_on'
    at Packet.asError (C:\xLab\anuvab\lawfy\api\node_modules\mysql2\lib\packets\packet.js:738:17)
    at Query.execute (C:\xLab\anuvab\lawfy\api\node_modules\mysql2\lib\commands\command.js:29:26)
    at Connection.handlePacket (C:\xLab\anuvab\lawfy\api\node_modules\mysql2\lib\connection.js:481:34)
    at PacketParser.onPacket (C:\xLab\anuvab\lawfy\api\node_modules\mysql2\lib\connection.js:97:12)
    at PacketParser.executeStart (C:\xLab\anuvab\lawfy\api\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\xLab\anuvab\lawfy\api\node_modules\mysql2\lib\connection.js:104:25)
    at Socket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  code: 'ER_INVALID_DEFAULT',
  errno: 1067,
  sqlState: '42000',
  sqlMessage: "Invalid default value for 'uploaded_on'",
  sql: 'alter table `directus_files` add `uploaded_on` timestamp'
}

### To Reproduce

1. create a new project via CLI
2. set Mysql as database and enter credentials

![image](https://github.com/user-attachments/assets/1168db5d-3979-41b9-a508-829bc2785e80)

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

10.4.11-MariaDB

**Comment by paescuj** [comment] 2024-08-17 12:23
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻
Please also note that MariaDB 10.4 reached end-of-life [^1] and and we therefore no longer support this version.

[^1] https://endoflife.date/mariadb

**Closed by paescuj** 2024-08-17 12:23 UTC

**Comment by rejhgadellaabsl** [comment] 2024-08-27 08:03
FWIW, the problem seems to be the `NO_ZERO_IN_DATE` and/or `NO_ZERO_DATE` value(s) for `sql_mode`:

```
sql_mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
```

You can check the value by running this query:

```
show variables like 'sql_mode' ;
```

Once I removed those values, the migrate command worked.

**Comment by teemzero** [comment] 2024-09-12 09:42
Wow @rejhgadellaabsl you're a life saver!
