### ISSUE TITLE
Version number mismatch in the GUI

### ISSUE THREAD

**Issue by maclm** [directus/directus#17492] opened 2023-02-11 14:45 UTC
### Describe the Bug

Directus version mismatch in GUI
Navigation Bar (left) reports `9.22.3` while Sidebar (right) shows `9.22.4`.

<img width="1124" alt="version-mismatch" src="https://user-images.githubusercontent.com/7873914/218263880-c3dc6195-1cc7-4954-92c4-08ee8327e8b2.png">

### To Reproduce

Install Directus using Docker Compose [as per the docs](https://docs.directus.io/self-hosted/docker-guide.html) with `image: directus/directus:latest`

### Errors Shown

None, as far as I can tell.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

SQLite 3.37.0

### What browser are you using?

Brave, Safari, Firefox

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment] 2023-02-11 18:04
Duplicate of #17115

**Closed by licitdev** 2023-02-11 18:04 UTC

**Comment by maclm** [comment] 2023-02-11 20:21
Good catch. Thank you.
