### ISSUE TITLE
Unable to Promote Version

### ISSUE THREAD

**Issue by Logrythmik** [directus/directus#22655] opened 2024-06-04 17:40 UTC
### Describe the Bug

We are unable to use the content versioning feature. For every item, attempting to promote a version results in the following error:

#### HTTP Error
<img width="591" alt="image" src="https://github.com/directus/directus/assets/137494/01233dd6-da2f-47d0-86d8-447c5ef0d556">

#### Logged Error
```
[17:30:57.792] ERROR: Cannot read properties of undefined (reading '0')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading '0')",
      "stack":
          
    }
```

This occurs wether we elect to delete or keep the existing version. 

We are on version 10.12. All migrations have run.

### To Reproduce

I don't know how to reproduce this without showing you the error within our instance.

For us, it's any version promotion. 

### Directus Version

v10.12

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL 5.7

**Comment by br41nslug** [comment] 2024-06-04 18:00
I am unable to reproduce this issue (test done with postgres)

https://github.com/directus/directus/assets/9389634/60c223f2-0f7b-4995-b80f-007969b74350

Could there be something else involved? extensions or flows perhaps?

Also MySQL 5.7 has been out extended support for 7 months and thus is no longer actively supported by our team either, you may want to consider upgrading https://endoflife.date/mysql

**Comment by Logrythmik** [comment] 2024-06-06 19:31
I can update MySQL, but I don't think that is the issue. I get that this isn't happening to anyone else, but I am certain I haven't made any customizations flows/extensions that could have interfered that could be causing it. 

My suspicion is the DB migration is faiing. When I run it, it has a spinner and then it ends without a success message or output. I am not sure if this is what is supposed to happen. Is there is a --verbose flag I can use to get detailed output to verify?

**Comment by rijkvanzanten** [comment] 2024-07-11 19:40
I haven't been able to reproduce this based on the information provided, so I'll have to close this for now. Happy to reopen if more information becomes available.

> My suspicion is the DB migration is faiing. When I run it, it has a spinner and then it ends without a success message or output. 

I'm not quite sure I understand what you're referring to. Migrations run from the CLI and don't have any spinners.

> Is there is a --verbose flag I can use to get detailed output to verify?

You can set the `LOG_LEVEL` environment variable to `trace` to get a full dump of all queries and logs made

**Closed by rijkvanzanten** 2024-07-11 19:40 UTC
Labels: :detective: Needs More Info, :elevator: Server
