### ISSUE TITLE
 [Error] Method implemented in the dialect driver - SQLite (Beta)

### ISSUE THREAD

**Issue by Natetronn** [directus/directus#3396] opened 2020-12-11 20:26 UTC
Note: I realize SQLite is still beta but, thought I'd share, nonetheless.

Can you please provide:

1) The issue and what you expected to happen
I expected the database to install when running the install script, instead it gave me the following error:

```
? Database File Path: /home/username/Code/directus-node/data.db
Something went wrong while seeding the database:
[Error] Method implemented in the dialect driver
Please try again
? Database File Path: (/home/username/Code/directus-node/data.db)
[Error] Database is already installed
```
repeats ^^^

Note: I see the data.db file was indeed created, however and it's filled with Directus tables.

2) Exact steps to reproduce this issue
   `npx create-directus-project directus-node`
then select SQLite (Beta) as db client

3) Your environment:
    Which DBMS are you using (MySQL 8, Postgres 12, ...). SQLIte
    Which deployment are you using (npx, Docker, ...). npx
    What browser are you using (Chrome 87, Safari 14, ...). Firefox Developer Editions 84.0b4 (64-bit) and Chromium

```
❯ node -v
v14.11.0
```

4) Any other relevant information we might need to reproduce this issue
    A SQL dump of the setup. I can send over the DB, if needed. Just let me know.
    What third party services you rely on (S3, managed database, ...). none

**Comment by Natetronn** [comment] 2020-12-11 20:32
Maybe related?

https://github.com/knex/knex/issues/2753

**Comment by rijkvanzanten** [comment] 2020-12-11 21:00
Duplicate of https://github.com/directus/directus/issues/2904

**Closed by rijkvanzanten** 2020-12-11 21:00 UTC

**Comment by Natetronn** [comment] 2020-12-11 21:07
@rijkvanzanten it's quite possible this is a duplicate, as it may very well be the same knex bug but, I did want to point out that I'm getting this on brand new fresh install, whereas that issue (duplicate) you mentioned appears to be on an update.

**Comment by rijkvanzanten** [comment] 2020-12-11 21:09
It's a duplicate. On a fresh install, Directus will run the migrations too. Those fail because of a missing method for SQLite specifically in Knex

**Comment by vtisnado** [comment] 2020-12-16 05:11
Hi @rijkvanzanten Im trying a fresh install in Ubuntu and after choosing SQLite (Beta) as db client I get the following errors:

```
success Installed "create-directus-project@9.0.0-rc.23" with binaries:
      - create-directus-project
? Choose your database client SQLite (Beta)

```

```
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create
SQLite3 Foreign & Primary keys may only be added on create

Something went wrong while seeding the database:

[Error] Sqlite does not support alter column.

Please try again
```

```
❯ node -v
v14.15.2
```

I tried installing with `npx` and `yarn` but always getting the same result.

**Comment by vtisnado** [comment] 2020-12-16 06:45
I just saw this is still in progress https://github.com/directus/directus/projects/8#card-51244365 an targeted to **v9.0.0-rc.24**

I will be waiting for that release.

**Comment by vtisnado** [comment] 2020-12-17 03:29
Hi @rijkvanzanten just to report that I'm getting the same error in **9.0.0-rc.24**

**Comment by rijkvanzanten** [comment] 2020-12-17 14:51
@vtisnado [Yes, see](https://github.com/directus/directus/issues/3396#issuecomment-743424545) https://github.com/directus/directus/issues/2904 🙂
