### ISSUE TITLE
Can't see translations in m2m modals

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#2586] opened 2020-02-12 18:13 UTC
# Bug Report

## Steps to Reproduce

1. Create a collection X with translations
2. Create another collection Y with a m2m field pointing to collection X
3. Contribute some rows for collection X and link them to collection Y
4. Go to collection Y, go to the m2m field and open up one of the rows

## Expected Behavior

You can see a preview of every field inside this modal

## Actual Behavior

The translations are blank

## Other Context & Screenshots

The m2m field
![image](https://user-images.githubusercontent.com/14786440/74363894-ca8a9100-4dcb-11ea-848e-6dd89902d03a.png)

The modal
![image](https://user-images.githubusercontent.com/14786440/74363872-bcd50b80-4dcb-11ea-9216-44d4204deb72.png)

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: [eg: Apache 2.4.37]
- PHP Version: [eg: 7.2.0]
- Database: [eg: MySQL 8.0.12]
- Directus Release Version: 8.5.5
- Install Method: docker

**Comment by andgar2010** [comment] 2020-02-12 18:18
@lluishi93 Which version of Directus used?

**Comment by lluishi93** [comment] 2020-02-12 18:19
@andgar2010 8.5.5, docker container

**Comment by rarora-trip** [comment] 2020-02-18 00:32
We are also facing similar issue for one to many relationship. If we create translations for many collection(example: article sections) and link them to one collection(eg. article). We can preview of many section but once we open it, translation section of many section(article section) remain empty.
We wanted to upgrade to latest version of directus and faced this issue.

**Comment by rijkvanzanten** [comment] 2020-02-18 14:43
Duplicate of https://github.com/directus/app/issues/2589

**Closed by rijkvanzanten** 2020-02-18 14:43 UTC
