### ISSUE TITLE
Unable to search or filter uuid field with non-uuid value

### ISSUE THREAD

**Issue by u12206050** [directus/directus#11940] opened 2022-03-03 19:00 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am unable to filter currently on the ID field but seems to be any string field that might contain numbers.
Am guessing that logic is testing if a number is being inputted in order to match on number even though the field is a string.

Uploading Screen Recording 2022-03-03 at 19.56.01.mov…

### To Reproduce

Create a collection with a string ID.
Add a new item with an id containing only numbers eg. 1234
Try and filter on the ID field and the value you entered. 1234

### Errors Shown

No errors, but no results either.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

osx

### How are you deploying Directus?

GCP

**Comment by licitdev** [comment] 2022-03-08 04:48
@u12206050 Thank you for your report. However, I was unable to reproduce the issue on mysql 8 using v9.6.0.

https://user-images.githubusercontent.com/26413686/157168099-fa40787f-74e1-4b90-a38d-ecb57d2eeb34.mov

> Uploading Screen Recording 2022-03-03 at 19.56.01.mov…

Do upload the video again. Please kindly update to v9.6.0 and confirm if the issue persists.

**Comment by u12206050** [comment] 2022-03-10 11:19
Hi, I have updated to v9.6.0 and the error still persists. What id do see is that I have the id field set to UUID. Could that be the issue, since I don't get an option for "contains" in the filter like you do, only equals

**Comment by rijkvanzanten** [comment] 2022-03-11 20:48
So you're trying to filter a UUID field with a number value? 🤔 Would you be able to share a DB dump with a minimal reproduction, or a schema snapshot for us to test with?

**Comment by u12206050** [comment] 2022-03-21 18:46
Actually it turns out you can't search or filter on a uuid field with a value that isn't in fact a uuid.
Meaning setting the value of a uuid field to something like `qwerty123` and then trying to find that item via search or filter doesn't work.

**Comment by rijkvanzanten** [comment] 2022-03-21 18:52
Ahh yes. That's by design. In databases where UUID is an actual type (like postgres or cockroachdb), using a LIKE where clause with a non-uuid value will throw an error. In order to still allow finding the item by it's UUID, it's using an equals check rather than a like check for UUID type IDs:

https://github.com/directus/directus/blob/e2eb2801c5884b5170af93c0cbb715aae11b80d7/api/src/utils/apply-query.ts#L588-L608

**Comment by rijkvanzanten** [comment] 2022-03-21 18:53
I'll close this for now, as it's technically working as it's supposed to. Happy to keep discussing tho!

**Closed by rijkvanzanten** 2022-03-21 18:53 UTC
Labels: Question

**Comment by u12206050** [comment] 2022-03-21 19:00
Our use case is that we have legacy data that used to use simple numeric ids, but we have switched to uuid. Unfortunately this means that if we can't search for those old types of IDs due to this we are unable to use the uuid field, which is kind of a bummer since every new item should generate its own uuid.

I can confirm by just removing the validate(searchQuery) on line 603 then it works exactly as I'd expect. Can I create a PR with that change? Doesn't actually make much sense validating that when you aren't even validating the previous two types?

**Comment by u12206050** [comment] 2022-03-21 19:02
Correction, it then works to search for the item by ID, ex.: `qwerty123` but filter on the ID still doesn't work. But it is probably just some other place in the code.

**Comment by rijkvanzanten** [comment] 2022-03-21 19:13
> I can confirm by just removing the && validate(searchQuery) on line 603 then it works exactly as I'd expect. Can I create a PR with that change? Doesn't actually make much sense validating that when you aren't even validating the previous two types?

No, that's to prevent other database drivers from crashing on searches, so we can't simply remove that.. 

In general, is it out of the question to migrate your existing items to UUIDs? Mixing the two ID types might cause various other issues (both in and out of Directus) as you can't expect a certain format coming from the items 🤔
