### ISSUE TITLE
GraphQL validation error

### ISSUE THREAD

**Issue by sawyerclick** [directus/directus#17247] opened 2023-01-19 23:03 UTC
### Describe the Bug

After months of inactivity, I've returned to a project with no changed variables or code to run into a `GraphQL validation error` when I try to access the data.

I have returned to work on a client project that uses the directus sdk (v^9.12.1) with a self-hosted directus instance (v9.12.2) on railway. When I try to access the graphql endpoint through the SDK or via a post request in Postman I receive endless `GraphQL validation error.` errors.

### To Reproduce

I'm not sure how to reproduce this bug.

### Errors Shown

```bash
GraphQL validation error.
Error: GraphQL validation error.
    at Transport.request (/Users/sawyerclick/repos/xxx/node_modules/@directus/sdk/dist/sdk.cjs.js:696:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Transport.post (/Users/sawyerclick/repos/xxx/node_modules/@directus/sdk/dist/sdk.cjs.js:725:16)
    at async GraphQLHandler.request (/Users/sawyerclick/repos/xxx/node_modules/@directus/sdk/dist/sdk.cjs.js:859:16)
    at async GraphQLHandler.items (/Users/sawyerclick/repos/xxx/node_modules/@directus/sdk/dist/sdk.cjs.js:866:16)
    at async Module.__vite_ssr_exports__.default (/src/lib/utils/client.js:25:14)
    at async get (/Users/sawyerclick/repos/xxx/src/routes/api/directus/index.json.js:27:19)
    at async render_endpoint (file:///Users/sawyerclick/repos/xxx/.svelte-kit/runtime/server/index.js:171:19)
    at async resolve (file:///Users/sawyerclick/repos/xxx/.svelte-kit/runtime/server/index.js:3303:11)
    at async respond (file:///Users/sawyerclick/repos/xxx/.svelte-kit/runtime/server/index.js:3248:20)```

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres (not exactly sure of version, that's on the client)

### What browser are you using?

Chrome, Safari, Firefox

### How are you deploying Directus?

Railway

**Comment by sawyerclick** [comment] 2023-01-19 23:14
It appears the changes to [authentication](https://docs.directus.io/reference/authentication.html) are forced upon older versions, but I'm not entirely sure why. I'm able to access the graphql endpoint if I use a static access token, but I'm no longer able to use the log in information I had previously. I was using this script to connect to the client

```js
import { Directus } from '@directus/sdk';
import 'dotenv/config';

const directus = new Directus(process.env.CZ_DIRECTUS_URL);

export default async () => {
	if (directus.auth.token) return directus;

	try {
		if (process.env.CZ_DIRECTUS_EMAIL && process.env.CZ_DIRECTUS_PASSWORD)
			await directus.auth.login({
				email: process.env.CZ_DIRECTUS_EMAIL,
				password: process.env.CZ_DIRECTUS_PASSWORD
			});
		else if (process.env.CZ_DIRECTUS_STATIC_TOKEN)
			await directus.auth.static(process.env.CZ_DIRECTUS_STATIC_TOKEN);
	} catch (err) {
		if (err.parent.code === 'ECONNREFUSED') {
			console.error(
				'Unable to connect to the Directus instance. Make sure the .env file is present and the CZ_DIRECTUS_URL variable is pointing the correct URL.'
			);
		}
	}

	return directus;
};

```

**Comment by sawyerclick** [comment] 2023-01-19 23:32
...after hours of battling this, it seems that email/password now finally works?

**Comment by azrikahar** [comment] 2023-01-20 09:49
> After months of inactivity, I've returned to a project with no changed variables or code to run into a `GraphQL validation error` when I try to access the data.

> It appears the changes to [authentication](https://docs.directus.io/reference/authentication.html) are forced upon older versions

I'm not sure how would that happen provided they are indeed still the same version, but can you confirm whether the SDK is `9.12.2` (because the sdk had a major version bump)?

> or via a post request in Postman

Can you share what was the graphQL query in that request?

> Is there a reason using email and password no longer works?

> ...after hours of battling this, it seems that email/password now finally works?

Could it be possible that it's (somehow) something to do with Railway? Would it be possible for you to test this with a local Directus instance?

**Comment by rijkvanzanten** [comment] 2023-01-20 15:40
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2023-01-20 15:40 UTC
Labels: GraphQL, Needs More Info, Can't Reproduce
