### ISSUE TITLE
Not clear error output for RECORD_NOT_UNIQUE

### ISSUE THREAD

**Issue by iksent** [directus/directus#5033] opened 2021-04-13 16:33 UTC
1. Create auto-translations for model
2. Create field with "Unique" option enabled inside the translations
3. Try to create translations with the same value of this field
4. **Get at error with weird text:**
```
There were validation errors for the following hidden fields:
 : validationError.undefined 
```
Network tab:
```
{"errors":[{"message":"Field \"undefined\" has to be unique.","extensions":{"code":"RECORD_NOT_UNIQUE","collection":"origin_translations_name_unique","invalid":"Test"}}]}
```

Interface:
![Снимок экрана 2021-04-13 в 21 28 43](https://user-images.githubusercontent.com/32956521/114588202-db6cb600-9c9f-11eb-8580-1406013d4a74.png)

---

### Project details
Directus Version: 9.0.0-rc.57
Environment: production
OS: Linux 5.4.0-66-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment] 2021-04-13 16:41
Duplicate of https://github.com/directus/directus/issues/4995

**Closed by rijkvanzanten** 2021-04-13 16:41 UTC
