### ISSUE TITLE
500 Error when filtering on Map geometry Fields

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#11909] opened 2022-03-02 01:03 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hey guys, having some issues to get filters to work for Maps. In general these 4 operators throw errors (intersects, doesn't intersect, intersects bounding box, doesn't intersect bounding box).

Additionally, it's not completely obvious what these 4 filters do (and by that I mean have no idea what they do 😆 )

### To Reproduce

1. Create a cloud demo instance.
2. Create a collection and create a Map field with the following configuration.

<img width="631" alt="Screen Shot 2022-03-01 at 6 57 19 PM" src="https://user-images.githubusercontent.com/62306630/156274309-309a7073-552b-497d-97ba-b8586216a957.png">

<img width="612" alt="Screen Shot 2022-03-01 at 6 57 35 PM" src="https://user-images.githubusercontent.com/62306630/156274314-3e164c0e-de32-4b63-a0d1-b3571d8b6817.png">

3. create an Item and apply some non-vector map tools (aka the lines and polygons).

4. Try to set a filter on the map with 
 - intersects
 - doesn't intersect
 - intersects bounding box
 - doesn't intersect bounding box

### Errors Shown

<img width="1728" alt="Screen Shot 2022-03-01 at 5 21 17 PM" src="https://user-images.githubusercontent.com/62306630/156274163-8e483073-1156-4b22-8147-f8956bb312b2.png">

<img width="1728" alt="Screen Shot 2022-03-01 at 5 21 53 PM" src="https://user-images.githubusercontent.com/62306630/156274170-7749213e-da63-4b2f-81de-d5233a7c5f83.png">

### What version of Directus are you using?

cloud

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

safari

### What operating system are you using?

Mac

### How are you deploying Directus?

cloud

**Comment by kostopravby** [comment] 2022-03-08 09:36
the same [10869](https://github.com/directus/directus/issues/10869)

**Comment by rijkvanzanten** [comment] 2022-03-11 23:14
Duplicate of #10869

**Closed by rijkvanzanten** 2022-03-11 23:14 UTC
Labels: API, Bug
