### ISSUE TITLE
Import / Export Collections

### ISSUE THREAD

**Issue by HerrHase** [directus/directus#2482] opened 2019-11-26 17:46 UTC
# Feature Request

## What problem does this feature solve?

There some Collections i use in different Projects, but i have to build them step by step. Why not export this Collections to import them in other Projects? Like a Blueprint to building a Collection.

## How do you think this should be implemented?

I would prefer JSON as a Format for import and export.

## Would you be willing to work on this?

I can try, but my knowledge about this software is limited.

**Comment by benhaynes** [comment] 2019-11-26 18:35
Definitely looking forward to this one!!

Duplicate of: https://github.com/directus/app/issues/765 and https://github.com/directus/app/issues/711 and https://github.com/directus/api/issues/31

**Closed by benhaynes** 2019-11-26 18:35 UTC
