### ISSUE TITLE
Secrets in Docker Compose aren't working correctly

### ISSUE THREAD

**Issue by SergioBlancoP** [directus/directus#17056] opened 2023-01-09 11:54 UTC
### Describe the Bug

I was using secrets in Docker Compose like you explained in your [documentation](https://docs.directus.io/self-hosted/config-options.html). As you said in "Environment Variables File", environment variable values can be imported from a file, by appending _FILE... But I have tried that and it doesn't works.

### To Reproduce

My Docker Compose looks like this (the commented lines are possible things I would like to include): 
```
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: 'directus'
    secrets:
      - db_password
      # - db_root_password

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055    
    networks:
      - directus
    depends_on:
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'     
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      #DB_PASSWORD: 'aaa'
      DB_PASSWORD_FILE: /run/secrets/db_password
      ADMIN_EMAIL: 'admin@example.com'
      # ADMIN_EMAIL_FILE: /run/secrets/db_email
      ADMIN_PASSWORD: 'aaa'
      # ADMIN_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
     #- db_email
secrets:
  db_password:
    file: db_password.txt
  #db_email:
    #file: db_email.txt
  #db_root_password:
    #file: db_root_password.txt
networks:
  directus:
```
db_password.txt is a file with the password:
`aaa`

### Errors Shown

```
directus    | [11:43:08.897] ERROR: Can't connect to the database.
directus    | [11:43:08.897] ERROR: password authentication failed for user "directus"
directus    |     err: {
directus    |       "type": "DatabaseError",
directus    |       "message": "password authentication failed for user \"directus\"",
directus    |       "stack":
directus    |           error: password authentication failed for user "directus"
directus    |               at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
directus    |               at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
directus    |               at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
directus    |               at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
directus    |               at Socket.emit (node:events:513:28)
directus    |               at addChunk (node:internal/streams/readable:324:12)
directus    |               at readableAddChunk (node:internal/streams/readable:297:9)
directus    |               at Readable.push (node:internal/streams/readable:234:10)
directus    |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus    |       "length": 104,
directus    |       "name": "error",
directus    |       "severity": "FATAL",
directus    |       "code": "28P01",
directus    |       "file": "auth.c",
directus    |       "line": "331",
directus    |       "routine": "auth_failed"
directus    |     }
directus exited with code 1
```

### What version of Directus are you using?

latest

### What version of Node.js are you using?

-

### What database are you using?

Postgres 13-master

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment] 2023-01-09 12:05
Secrets are only available for swarm services it looks like, are you running a docker swarm? https://docs.docker.com/engine/swarm/secrets/
> Note: Docker secrets are only available to swarm services, not to standalone containers. To use this feature, consider adapting your container to run as a service. Stateful containers can typically run with a scale of 1 without changing the container code.

**Comment by SergioBlancoP** [comment] 2023-01-09 15:08
Yes, I have docker swarm running and I have the same problem. 

docker-stack.yml:
```
version: "3.8"
services:
    directus:
        image: directus/directus:latest
        ports:
            - target: 8055
              published: 8055
              mode: ingress
        deploy:
            replicas: 1
            resources:
                 limits:
                    cpus: '3'
                    memory: 4G
            restart_policy:
                condition: on-failure
        environment:
            KEY: '<key>'
            SECRET: '<secret>'
            DB_CLIENT: 'pg'
            DB_HOST: 'db'
            DB_PORT: '5432'
            DB_DATABASE: 'db'
            DB_USER: 'directus'
            DB_PASSWORD_FILE: '/run/secrets/password_database'
            ADMIN_EMAIL: 'admin@example.es'
            ADMIN_PASSWORD_FILE: '/run/secrets/password_admin'
        user: 1000:1001
        volumes:
            - directus_uploads:/directus/uploads
        secrets:
            - source: webnowo_database_pass_pro
              target: password_database
            - source: password_directus_admin_pro
              target: password_admin
        
          <other services>

```
Why Docker Compose in Swarm mode doesn't work? Why can I use "_FILE" in Postgres Database correctly but inside the Directus part not? So... If you could show me an example where "_FILE" works or if you could try my code, I would appreciate it.

**Comment by br41nslug** [comment] 2023-01-09 16:24
> you dont use secrets btw

Indeed, i will need to set up a testing swarm to confirm the secrets part.

> It doesn't works again... I want "_FILE" in db_password and its exactly the same error:

The error would indicate that the contents of the file do not match your password, could there be an extra enter or tab character in the file?

**Comment by SergioBlancoP** [comment] 2023-01-09 16:29
No. As you can see postgres and directus are using the same password, so the problem is not an extra enter or tab.

**Comment by br41nslug** [comment] 2023-01-09 16:34
Oh you mention using the same for Postgres and i had absolutely read over this in your docker-compose but the `*_FILE` environments are a Directus specific feature. I dont think this works for postgres:
![image](https://user-images.githubusercontent.com/9389634/211359060-84cb4e45-4035-4c7f-aa23-f11d99b4e16f.png)
https://ilhicas.com/2019/01/26/Using-docker-secrets-postgres.html

**Comment by SergioBlancoP** [comment] 2023-01-09 16:45
The problem is not in postgres part... I'm here because my problem is with directus "_FILE" environments. And answering your last comment:
![imagen](https://user-images.githubusercontent.com/122268599/211361168-bc4ac752-bb3a-41c8-9658-d50b282cac06.png)
https://hub.docker.com/_/postgres
Yes, it works in postgres.

**Comment by br41nslug** [comment] 2023-01-09 16:48
Ah good to know that that is supported by Postgres 😄

**Comment by paescuj** [comment] 2023-01-09 18:03
@br41nslug Made a very good point:

> The error would indicate that the contents of the file do not match your password, could there be an extra enter or tab character in the file?

Can you please run `cat` against your secret file? It must not contain a newline at the end of the file!
Most likely a newline isn't a problem for the `postgres` image because the secret is interpreted in a different way, but no newline is a requirement for Directus.

**Comment by paescuj** [comment] 2023-01-11 21:18
I think this can be closed! It's very likely that a newline causes this issue. I've used / tested Directus with secrets in the past and it worked flawless.

**Comment by rijkvanzanten** [comment] 2023-01-11 21:19
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2023-01-11 21:19 UTC
Labels: Can't Reproduce

**Comment by SergioBlancoP** [comment] 2023-01-18 12:33
Hi again,
problem was as you said in the password file "an extra enter or tab character". I don't know why I couldn't see it using vim, nano or cat. 
I realized that there was that extra tab because I opened it with a text editor like VS Code. Otherwise I would never have found it.

Thank you.

**Comment by paescuj** [comment] 2023-01-18 13:58
Thanks for your response! I'm glad it's working for you now!
Here's a little tip: You can use `cat` with the following option to print all special chars contained in a file:
```bash
cat -A <your-filename>
```
