### ISSUE TITLE
Unable to save singleton "FAILED_VALIDATION"

### ISSUE THREAD

**Issue by Munkkeli** [directus/directus#5242] opened 2021-04-25 12:05 UTC
1) The issue and what you expected to happen
    I'm trying to create a "header" singleton, but whatever I do am unable to save data to it.
    I have tried to create it with a different name or with just a text field inside. No luck.
    The complete error it is giving me is:
```json
{
	"errors": [
		{
			"message": "\"data\" is required",
			"extensions": {
				"code": "FAILED_VALIDATION",
				"field": "data",
				"type": "required"
			}
		}
	]
}
```

Request:
```
PATCH: http://localhost:8055/items/header

{
	"asd": "sfdf"
}
```

Singleton:
![image](https://user-images.githubusercontent.com/1665684/115992684-97e74580-a5d7-11eb-881b-a3837f7297c8.png)

2) Exact steps to reproduce this issue
    Create a singleton. Try to save it.

3) Your environment:
    What version of Directus you are using: v9.0.0-rc.60
    Which DBMS are you using: SQLite
    Which deployment are you using: npx
    What browser are you using: Firefox 88.0 (64-bit)

4) Any other relevant information we might need to reproduce this issue
    What third party services you rely on: None

**Comment by rijkvanzanten** [comment] 2021-04-25 14:18
Duplicate of https://github.com/directus/directus/discussions/5237

**Closed** 2021-04-25 14:18 UTC
Labels: Duplicate
