### ISSUE TITLE
SSO users not created automatically on login when public registrations is allowed

### ISSUE THREAD

**Issue by BDive** [directus/directus#13438] opened 2022-05-20 09:25 UTC
### Describe the Bug

Even when public registration is enabled (set to true) and the right default role ID is used, no new SSO users are created when logging in. Keycloak was used (openid)

### To Reproduce

Spin up an instance of directus with the following auth config (.env)

## Auth Providers
AUTH_DISABLE_DEFAULT=false
AUTH_PROVIDERS="KC"
AUTH_KC_DRIVER="openid"
AUTH_KC_CLIENT_ID="direct"
AUTH_KC_CLIENT_SECRET="yoursecret"
AUTH_KC_ISSUER_URL="http://localhost/auth/realms/test/.well-known/openid-configuration"
AUTH_KC_IDENTIFIER_KEY="email"
AUTH_KC_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_KC_DEFAULT_ROLE_ID="877e42c2-cb25-4514-a4db-fe05fe0285dd" (use one of the existing role IDs in directus)

Once directus is running, log in to external provider with a user that does not exist in directus

### Errors Shown

Following error on console on redirect
![image](https://user-images.githubusercontent.com/28010132/169497075-95e43305-03e3-4c04-943e-398ee1fb7668.png)

With GET request on /auth/login/kc the following error is encountered
![image](https://user-images.githubusercontent.com/28010132/169497416-11cde378-bf60-4b53-97b4-75b9e3dd5345.png)

![image](https://user-images.githubusercontent.com/28010132/169497636-c2e99fc3-4e41-4593-8023-1409a64aa3aa.png)

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 10.10

### What browser are you using?

Chrome

### How are you deploying Directus?

running Locally

**Comment by aidenfoxx** [comment] 2022-05-20 12:53
Something is very weird here. Dynamic registration shouldn't be attempting to create a role. Are you using a custom extension to create roles when users are registered that might interfere with OpenIDs dynamic user registration?

**Comment by BDive** [comment] 2022-05-20 13:40
> Something is very weird here. Dynamic registration shouldn't be attempting to create a role. Are you using a custom extension to create roles when users are registered that might interfere with OpenIDs dynamic user registration?
>

Not using custom extension, just want the new users to be mapped to a default role in directus 

> EDIT: I also notice your role seems incorrectly formatted, using underscores instead of dashes. I believe it should be "877e42c2-cb25-4514-a4db-fe05fe0285dd".
> 
Apologies, I had changed that in config to test, PS: It fails using correct role id (dashes). Also tried using role name using ID with no luck

**Comment by azrikahar** [comment] 2022-05-20 13:51
> Do you happen to know @azrikahar if Directus does some magic when you give a relation ID that doesn't exist? Will Directus try and create a record for that relation? If so, that's probably why the error is being thrown.

Hmm I believe there is no such interaction that I know of 🤔

**Comment by aidenfoxx** [comment] 2022-05-20 13:54
Well then I'm stumped. The OpenID provider never attempts to create a role, so it feels like there is something else going on.

**Comment by BDive** [comment] 2022-05-21 07:17
I notice the problem has been flagged as "needs more information" - I believe the best course of action would be to reproduce it and walk through the code to understand what's going on.

**Comment by rijkvanzanten** [comment] 2022-05-23 20:55
> I notice the issue has been flagged as "needs more information" - I believe the best course of action would be to reproduce it and walk through the code to understand what's going on.

Yup!

I just tried this locally (through the `keycloak` container we have for debugging in our [docker-compose](https://github.com/directus/directus/blob/0c09c79b2e42af495825b7eed69db5f71a7db4f0/docker-compose.yml#L146-L154)) and it seems to be working as expected on my end. I'll close this for now, as I suspect this to be a configuration/environment specific problem. Happy to keep discussing though 👍🏻

**Closed by rijkvanzanten** 2022-05-23 20:55 UTC
Labels: Needs More Info

**Comment by pstuifzand** [comment] 2022-08-25 07:41
I'm having this same problem. When logging in using Google OpenID I get this error:

    Aug 25 07:23:10 ubuntu-s-1vcpu-2gb-intel-ams3-01 directus[1255039]: 07:23:10 ⚠️  insert into `directus_roles` (`id`) values ('0bc6e064-264a-4691-8f6b-32b02d904399') - ER_NO_DEFAULT_FOR_FIELD: Field 'name' doesn't have a default value
    Aug 25 07:23:10 ubuntu-s-1vcpu-2gb-intel-ams3-01 directus[1255039]: 07:23:10 ⚠️  [OpenID] Unexpected error during OpenID login

It seems the auth providers tries to create a role, at the same moment when it is creating the user. The strange thing is, is that the role id here is not the same as the default role id I provided in the config. I think that because the `id` `"obc6...` does not exist, that the service is trying to create that role.

That makes me think that the problem is that the default role id from the config is not used and a different role id is generated somewhere or that another default value is used.

**Comment by pstuifzand** [comment] 2022-08-25 07:55
I have fixed the problem now by converting my config from `.env` to `config.json`. This makes me think that somehow the quotes are interfering with value of role id configuration variable.
