### ISSUE TITLE
Can't delete a custom field created inside "Directus Files" from System Collections

### ISSUE THREAD

**Issue by janjos96** [directus/directus#13114] opened 2022-05-04 15:14 UTC
### Describe the Bug

After creating two custom fields inside the "Directus Files" on System Collections, I can't seem to delete them, getting this error:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/21311420/166712528-0cabd42d-1465-4a46-8921-b0388f1ec502.png">

```
 {
  "errors": [
    {
      "message": "DROP TABLE \"directus_files\" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

The fields are a Text Field and a Slider with Integers.

### To Reproduce

1. Go into Data Models > System Collections > Directus Files.
2. Create a custom Text Field for all files.
3. Try deleting them.

### Errors Shown

```
 {
  "errors": [
    {
      "message": "DROP TABLE \"directus_files\" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

Cloud, I don't know version

### What database are you using?

SQLite

### What browser are you using?

Firefox

### How are you deploying Directus?

Cloud

**Comment by azrikahar** [comment] 2022-05-04 16:56
This should be duplicate of #12393, and we were tracking it in #10842. Thankfully the issue has since be resolved in `9.10.0`, so we'll proceed to close this as resolved. 

This will be resolved for Cloud once it's updated (typically roughly a week or so after new version of Directus, and the reason why it was still on `9.7.1` despite the usual plan was unfortunately due to the same aforementioned issue) 👍

**Closed by azrikahar** 2022-05-04 16:56 UTC
Labels: Bug (Potential)
