### ISSUE TITLE
Tinymce v6 missing icons

### ISSUE THREAD

**Issue by berts83231** [directus/directus#18224] opened 2023-04-17 20:02 UTC
### Describe the Bug

v6 of tinymce not displaying icons correctly. See https://nimb.ws/zgw9yx

This issue is the same on existing installs and new installs.

It is a css issue. 

Modifying the buttons: Bold, Italic, Underline mostly fixes the issue. But the style looks slightly off.
<button class="tox-tbtn">  --> <button class="<button class="tox-tbtn"> </button> ">

I'm not sure if this needs to be fixed in Directus or upstream in Tinymce.

### To Reproduce

Install a clean version of Directus.

I used Docker https://docs.directus.io/self-hosted/quickstart.html

Tested in Chrome & Firefox.

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2023-04-17 20:07
This is a duplicate of #18184 and has been fixed in #18185.

**Closed** 2023-04-17 20:21 UTC
