### ISSUE TITLE
z-index problem with the import source popup when "Insert/Edit Image" in WYSIWYG

### ISSUE THREAD

**Issue by JeremDlcn** [directus/directus#4943] opened 2021-04-09 17:44 UTC
The popup to add an image from the Library or Drag and drop is behind the source panel when adding an image in the WYSIWYG in a Collection.
The problem is the z-index is lower so the popup is behind.

![directus-addimage-zindex](https://user-images.githubusercontent.com/44464165/114218618-ef47ad80-9969-11eb-9703-0143ebe1bc22.png)

The popup is behind so it's not possible to add an image without changing the z-index.

`
.tox.tox-tinymce-aux {
    z-index: 490;
}
`

If adding this the popup will be in front of the image panel.

![image](https://user-images.githubusercontent.com/44464165/114218200-6892d080-9969-11eb-8f96-4e9245f40118.png)

Directus version: v9.0.0-rc.56
Database: PostgresSQL
Deployment: Debian 9, npx and nginx
Chrome version: 89.0.4389.114

**Comment by rijkvanzanten** [comment] 2021-04-09 17:46
Duplicate of https://github.com/directus/directus/issues/4354

**Closed by rijkvanzanten** 2021-04-09 17:46 UTC
