### ISSUE TITLE
Closing custom permissions dialog looses group

### ISSUE THREAD

**Issue by madc** [directus/directus#5366] opened 2021-04-29 12:38 UTC
1) The issue and what you expected to happen
After opening the custom permission permissions dialog and closing it via the `X`-button, the group gets somehow lost. Closing the dialog via save does not cause this issue.

2) Exact steps to reproduce this issue
- Go to `Settings` -> `Roles & Permissions` -> `Public`. The path is now `/admin/settings/roles/public`.
- In the permissions table, click on any permission and select `Use Custom` -> the permissions dialog pops up from the right
- Close the dialog via the `X`-button -> the path is now `/admin/settings/roles/null`.

3) Your environment:
- Directus v9.0.0-rc.61 
- MySQL
- npx
- Tested w/ Firefox 88.0

**Comment by rijkvanzanten** [comment] 2021-04-29 14:29
Duplicate of https://github.com/directus/directus/issues/5298

**Closed by rijkvanzanten** 2021-04-29 14:29 UTC
