### ISSUE TITLE
Do not return an empty body on user creation via API endpoint /users/register

### ISSUE THREAD

**Issue by uzziellite** [directus/directus#23398] opened 2024-08-18 16:08 UTC
### Describe the Improvement

It will be better if the API endpoint **/users/register** would not return a 204 status but some data to indicate if the creation process was a success or if a duplicate user already exists. This is especially useful for applications that are using directus API as their backend. The 204 status makes it harder when registering new users since a developer has to make two requests to directus. The first one to check if the user email is present, then the second one to add the user if that email does not exist.

**Comment by hanneskuettner** [comment] 2024-08-18 16:25
The `/user/register` endpoint is also meant for public consumption, e.g. a website that doesn't have its own backend and can't store an access token securely on the backend.

The 204 status code for registrations where the user already exists is intended behavior, to not give more information away on the registered users of your application, also see https://github.com/directus/directus/issues/23230#issuecomment-2273324440

Closing this, as this behavior is intended and won't be changed.

**Closed by hanneskuettner** 2024-08-18 16:25 UTC
