### ISSUE TITLE
can view their items option

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1863] opened 2017-10-05 16:05 UTC
## Version Info
  - Directus version and branch: (Or commit hash)
0826c4970d22d1c4e2a84e4ba5816b384c10b630
  - PHP version: 
7.1
  - MySQL version: 
Amazon Aurora
  - Web server: (Ex. Apache, nginx or IIS?) 
apache
  - OS name and version: 
ubuntu 16.4 lts

## Expected Behavior
Items in tables that the user didn't create(can view only their items) shouldnt be visible to other users.
I added the user_created and user_modified columns to the table.

## Actual Behavior
But the show up.

## Steps to Reproduce
 1. Have a table e.g "products" with a column e.g "Name"
 2. Add User_created and user_modified interface as columns to the table products
 3. Create a new Users Group with a User and give it the permissions "can view their items"
 4. Create an item as Admin
 5. Login as the new created user and List the Products table, you will see the item created by admin

**Comment by MartinMekhaiel** [comment] 2017-10-05 16:32
i think i found the issue, somehow in my directus_tables some tables doesnt exist and thats why the option doesnt work, is it possible that the direcuts_tables wasnt availible in a previous release?

**Comment by MartinMekhaiel** [comment] 2017-10-05 16:53
it also seems that some tables doesnt get created in diretus_tables

**Comment by MartinMekhaiel** [comment] 2017-10-05 17:37
also when the table exists in directus_tables and i add the user_Created interface, i dont see the "columnname" in directus.tables.user_create_column etc.

**Comment by WellingGuzman** [comment] 2017-10-05 18:12
@MartinMekhaiel is it working or not after you added the `user_created` interface, even though is not set the value in `user_create_column`?

**Comment by MartinMekhaiel** [comment] 2017-10-05 18:19
No there Seem to be Serveral isssues 

1. Not all Tables are beeing created in directus_tables 

2. if i Add the User created Interface and Name the Column „user_created“ it’s Not set in the directus_tables.user_create_column

3. when i Add a missing table to directus tables and i set the user_create_column manually it Seems To work as Expected

**Comment by WellingGuzman** [comment] 2017-10-05 19:43
> 1. Not all Tables are being created in directus_tables

Not a bug, only table that the user . change information should be created into `directus_tables` everything else will fallback to default information.

> 2. if i Add the User created Interface and Name the Column „user_created“ it’s Not set in the directus_tables.user_create_column

Maybe the bug here is when there's not table information at first. Only this way is the `user_create_column` not being set? otherwise it's being set automatically?

**Comment by MartinMekhaiel** [comment] 2017-10-05 22:25
1. the table has to exist in directus tables , otherwise it doesnt seem to work.

2. i dont know what you mean exactly, maybe we can have a quick chat about this?

**Comment by WellingGuzman** [comment] 2017-10-06 02:39
Closed by https://github.com/directus/directus/commit/dfc5346b6fcd45d59fa03b6623a27d8a68774c53

**Closed by WellingGuzman** 2017-10-06 02:39 UTC
Labels: 3. Major, API, Bug
