### ISSUE TITLE
Creates profile in User Directory when email is invalid

### ISSUE THREAD

**Issue by vankodev** [directus/directus#15567] opened 2022-09-14 07:53 UTC
### Describe the Bug

When registering a user with invalid email it gives error as it should be. But Directus still creates a profile in the User Directory with the invalid email.

### To Reproduce

```
                await directus.users.createOne({
                    email: submit.email, 
                    first_name: submit.name,
                    password: submit.password, 
                    role: "f0398d6f-fff2-4bad-9733-e41615630663" 
                })
```

### Errors Shown

Error: "email" must be a valid email

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

v16.14.0

### What database are you using?

SQLite 5.0.11

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment] 2022-09-14 08:13
What version of the JS SDK are you using? This error should not be thrown anymore since the email requirement has been removed by the API nor the SDK.

**Comment by rijkvanzanten** [comment] 2022-09-14 19:25
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2022-09-14 19:25 UTC
Labels: Needs More Info, Can't Reproduce
