### ISSUE TITLE
Role update filters are not applied

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16025] opened 2022-10-17 09:27 UTC
### Describe the Bug

The filter set for Items the role can update is not applied

- No Access works
- All Access works
- But if you add a filter to allow only Items the role can update, all the items can still be updated

### To Reproduce

On a collection with a field `Name` for a role set an update filter on `Name Contains 'Fred'`.
Connect under the role. 

### Errors Shown

You can still update items that do not contain `Fred` in the field `Name`

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgresql 14

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment] 2022-10-17 10:12
Could be related to https://github.com/directus/directus/issues/14571

**Comment by azrikahar** [comment] 2022-10-17 10:39
> You can still update items that do not contain `Fred` in the field `Name`

Just to confirm, does the API correctly block said update in your case? This seems to be a duplicate of #13774 #11058, where the relevant item(s) aren't disabled when there's no edit permission, but the API still throws permission error in that case.

What I've tested:

https://user-images.githubusercontent.com/42867097/196157037-bf8e8b86-0dce-44b3-8f38-154d217ece57.mp4

Closing as duplicate for now, and tracking this in #11058.

**Closed by azrikahar** 2022-10-17 10:39 UTC

**Comment by Pachat** [comment] 2022-10-17 13:33
@azrikahar Thanks for your video. It confirms what I have and helps to be more precise:
Do you consider having an error message while doing a not allowed action to be of good UX?

In fact, and that's what I wanted to point out: if the user has no right to update a field, that field should be `read-only`.
That would give a much better UX and give confidence in the app, than letting do something and then only throw a "`Ha ha: you have done something forbidden`"

**Comment by Pachat** [comment] 2022-10-17 14:05
@azrikahar You are perfectly right. #11058 is exactly what we need. Thank you for your explanations.
