### ISSUE TITLE
Email validation on create/update user

### ISSUE THREAD

**Issue by Attacler** [directus/directus#11399] opened 2022-02-02 16:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Basicly whenever you create a user with an invalid email like below:
![image](https://user-images.githubusercontent.com/42644889/152199775-ff3d4a63-1f50-4b1e-94aa-dc5c39ffb992.png)
There is no verification if the emailadress is valid.
But when you fill in something like:
test.@gmail.com
It allows you to save but not to login.

So the issue is that some one can create an account with an invalid emailadress because no check happends.
But after that (s)he cannot login because then there is a check on a valid emailadress.

### To Reproduce

See above

### Errors Shown

```json
[
    {
        "message": "\"email\" must be a valid email",
        "extensions": {
            "code": "INVALID_PAYLOAD"
        }
    }
]
```

### What version of Directus are you using?

9.5

### What version of Node.js are you using?

14

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

PM2

**Comment by azrikahar** [comment] 2022-02-03 01:19
Technically this is a duplicate of #10723 with the discussions mentioned here being the solution: https://github.com/directus/directus/discussions/10738#discussioncomment-1879514, but I'll leave it up for now unless deemed otherwise 👍

**Comment by davidmach14** [comment] 2022-10-10 21:02
IMHO it's bug due to different behavior when inserting a new user and on the login form. 
[I found a discussion](https://github.com/directus/directus/discussions/4390) on this issue that is quite old and doesn't give a good picture of the project...

**Comment by rijkvanzanten** [comment] 2022-10-12 19:58
> https://github.com/directus/directus/discussions/4390 on this issue that is quite old and doesn't give a good picture of the project...

Note how that discussion says [✅ Implemented] in the top right 😉

**Comment by kadlinobit** [comment] 2022-11-04 13:37
Hi, just ran into this issue. I have created a user with email `hhh@hhh.hhh` and on login, I get the invalid email error. So I'm wondering, what kind of email check is actually performed on login? Because this fake email has correct email structure. Could someone point me where the email check is in Directus code? 

Thanks!

**Comment by rijkvanzanten** [comment] 2022-12-15 22:38
Linear: [ENG-272](https://linear.app/directus/issue/ENG-272/email-validation-on-createupdate-user)

**Comment by hepesu** [comment] 2023-01-13 00:18
> Hi, just ran into this issue. I have created a user with email `hhh@hhh.hhh` and on login, I get the invalid email error. So I'm wondering, what kind of email check is actually performed on login? Because this fake email has correct email structure. Could someone point me where the email check is in Directus code?
> 
> Thanks!

In file auth/drivers/local.js, method createLocalAuthRouter.

If someone has changed email into an invalid form, changing 'string().email().required()' into 'string().required()' in the corresponding file in dist folder can solve the issue.

**Comment by martijn-dev** [comment] 2023-07-19 07:19
We actually have a usecase wherein we don't use the email field on a user as an email. We just fill in a key.
That way we can use the whole authenication system with JWT validation using a key(email):secret(password) combination.
These key:secret 'users' don't need dashboard access, so we don't run intro the email validation on the frontend login page.

To me it's makes kinda sense to be able to create user entities in whatever format, since you might want to create users without an email (also for dashboard access).

In case we do gonna add email validation, it might be an idea to create a setting for this behaviour.

**Comment by martijn-dev** [comment] 2023-07-20 10:15
@rijkvanzanten Creating a custom `key` field to `directus_users` sounds like a plan. How would that work with the authentication endpoints?
Would we still be able to use the `POST /auth/login` endpoint with a `key:password` combination?

(Sorry for getting a bit of topic from this issue. I'll create a discussion for other questions)

**Comment by rijkvanzanten** [comment] 2023-07-24 16:54
> @rijkvanzanten Creating a custom `key` field to `directus_users` sounds like a plan. How would that work with the authentication endpoints? Would we still be able to use the `POST /auth/login` endpoint with a `key:password` combination?
> 
> (Sorry for getting a bit of topic from this issue. I'll create a discussion for other questions)

Hmm no the /auth/login endpoint would still require the `email` and `password` fields, as per usual. Login was never intended / designed to work with non-email login strings, so I'm a little torn on whether or not we should add an explicit opt-out to email validation 🤔

**Comment by martijn-dev** [comment] 2023-07-25 09:11
> > @rijkvanzanten Creating a custom `key` field to `directus_users` sounds like a plan. How would that work with the authentication endpoints? Would we still be able to use the `POST /auth/login` endpoint with a `key:password` combination?
> > (Sorry for getting a bit of topic from this issue. I'll create a discussion for other questions)
> 
> Hmm no the /auth/login endpoint would still require the `email` and `password` fields, as per usual. Login was never intended / designed to work with non-email login strings, so I'm a little torn on whether or not we should add an explicit opt-out to email validation 🤔

I'll leave the decisions up to you 😄. Just wanted to share a potential different way of using it. If validation will be added we will probably just change our keys to a `xxxx<key>xxxx@system.key` format to keep it valid. So it won't be a show stopper for us.

**Closed** 2023-09-25 13:54 UTC
Labels: Improvement, Package: directus
