### ISSUE TITLE
Batch editing can't nullify(deselect) M2M field

### ISSUE THREAD

**Issue by kostopravby** [directus/directus#12027] opened 2022-03-08 08:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using batch editing 1 or more items I can only select one or more items in m2m field. Directus don't update field if I want to clean all selected values.

### To Reproduce

Create collection with m2m field. Add one row and select one or more items in m2m field. select row and click edit. In modal window just check checkbox on m2m field and click save. Expecting behavior - clear m2m field, but the field stays as is.

### Errors Shown

No errors shown

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

PostgreSQL 10 with postgis

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment] 2022-03-11 23:39
I believe this is caused by https://github.com/directus/directus/issues/12099. 

Closed in favor of https://github.com/directus/directus/issues/12099

**Closed by rijkvanzanten** 2022-03-11 23:39 UTC
Labels: App, Bug
