### ISSUE TITLE
Conditions with Required option checked not working when updating an item

### ISSUE THREAD

**Issue by w3iw3i** [directus/directus#10859] opened 2022-01-05 09:17 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using conditions on a field with Required option checked and attempt to update an item that satisfy the condition rule, the update still went through despite leaving the required field blank.

### To Reproduce

Create a collection with two fields (name and title).
Create condition for name field with rule = title isn't null and check required option. Save it.
Create an item with name field blank and title field blank. Save the item.
Edit the item and input some characters in title field. At this point an asterisk should appear beside name field. Leave name field blank and save the changes, which will go through and the item get updated despite it being marked as required.

![image](https://user-images.githubusercontent.com/42484875/148191976-465ea21e-b99c-4f3c-a437-937e8deaaad6.png)

### Errors Shown

No error shown

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome 96.0.4664.110

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-01-05 16:41
Duplicate of https://github.com/directus/directus/discussions/10276#discussioncomment-1745224

**Closed by rijkvanzanten** 2022-01-05 16:41 UTC
Labels: App, Bug
