### ISSUE TITLE
A field inside a Detail Group is visible at start, even with Condition for Hidden on Detail

### ISSUE THREAD

**Issue by Pachat** [directus/directus#20023] opened 2023-10-13 13:03 UTC
### Describe the Bug

The Condition is not applied when creating a new item.

### To Reproduce

In a collection, create an Accordion with inside a Detail Group with inside a Notice.
Set the Notice Condition to 
`{"_and":[{"_or":[{"id":{"_nnull":true}},{"id":{"_null":true}}]}]}`
which is always met (just for the example).

The Notice will not be hidden when creating a new item.
Of course, IRW you would set a reasonable condition which

- will hide the notice at start
- and keep it hidden unless another field is set to a specific value.

### Directus Version

v10.2.6

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2023-10-13 15:43
Could you try with the latest version (currently 10.6.3)? IIRC some fixes landed in the past releases in this regard.

**Comment by Pachat** [comment] 2023-10-13 16:14
Sure, I'd very much like to. 
But because of https://github.com/directus/directus/issues/19327#issuecomment-1694219563 I'm still stuck to v10.2.6

And patiently* waiting for a full resolution to update the version
* as it appear "not a top priority at the moment." https://github.com/directus/directus/issues/19327#issuecomment-1759234874

**Comment by rijkvanzanten** [comment] 2023-10-13 16:18
Duplicate of https://github.com/directus/directus/issues/19571

**Closed by rijkvanzanten** 2023-10-13 16:18 UTC

**Comment by paescuj** [comment] 2023-10-13 16:37
> Sure, I'd very much like to. But because of [#19327 (comment)](https://github.com/directus/directus/issues/19327#issuecomment-1694219563) I'm still stuck to v10.2.6
> 
> And patiently* waiting for a full resolution to update the version
> 
>     * as it appear "not a top priority at the moment." [Update permissions still incorrect in 10.5.2 #19327 (comment)](https://github.com/directus/directus/issues/19327#issuecomment-1759234874)

With the fix provided in #19728 (released in [v10.6.2](https://github.com/directus/directus/releases/tag/v10.6.2)) it's effectively the same behavior as on v10.2.6, so there's no reason to stuck on this version!

**Comment by Pachat** [comment] 2023-10-13 16:48
@paescuj Yes, but as stated here https://github.com/directus/directus/issues/19327#issuecomment-1759223167 "the UI is not correctly displaying the permissions". That is what prevents me to upgrade.

**Comment by paescuj** [comment] 2023-10-14 13:57
> @paescuj Yes, but as stated here [#19327 (comment)](https://github.com/directus/directus/issues/19327#issuecomment-1759223167) "the UI is not correctly displaying the permissions". That is what prevents me to upgrade.

Yes, but as I wrote earlier, this is the same behavior on 10.2.6. Also evident from the following two comments:
- https://github.com/directus/directus/issues/19327#issue-1832603119
  > On v10.2.1 the frontend displays a popup error `[FORBIDDEN] You don't have permission to access this`. but after dismissing it, you can still update the item. After v10.3.0 the popup error is displayed and you can't edit the item after dismissing the error.
- https://github.com/directus/directus/issues/19327#issuecomment-1759223167
  > I am still able to do form changes, but it gives me now the following error message.
  >
  > ```json
  > {
  >  "message": "You don't have permission to access this.",
  >  "extensions": {
  >    "code": "FORBIDDEN",
  >    "stack": "..."
  >  }
  > }
  > ```

So there's really no reason stay on the old version 👍
