### ISSUE TITLE
YAML Config not loaded

### ISSUE THREAD

**Issue by jbmolle** [directus/directus#19744] opened 2023-09-20 12:19 UTC
### Describe the Bug

The YAML config file config.yaml is not loaded in v10.6.2
It was working correctly in v10.6.1

### To Reproduce

Install Directus v10.6.2 and set CONFIG_PATH to /directus/config.yaml

### Directus Version

v10.6.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-09-20 12:42
I was not able to reproduce this issue with the given information, please provide more detail about the issue or the setup. 

```bash
brainslug@Leela:/tmp/test$ cat package.json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "directus": "^10.6.2",
    "sqlite3": "^5.1.6"
  }
}
brainslug@Leela:/tmp/test$ npx directus start
[14:39:36.825] ERROR: "KEY" Environment Variable is missing.
brainslug@Leela:/tmp/test$ echo "KEY: 'something'" > config.yml
brainslug@Leela:/tmp/test$ npx directus start
[14:40:28.537] ERROR: "KEY" Environment Variable is missing.
brainslug@Leela:/tmp/test$ CONFIG_PATH=config.yml npx directus start
[14:40:39.005] ERROR: "SECRET" Environment Variable is missing.
```

Closing this for now until more information becomes available.

**Comment by jbmolle** [comment] 2023-09-20 13:13
No it's not loading the file as a YAML file.
In api/src/env.ts, processConfiguration function, it's going here:
```
return dotenv.parse(fs.readFileSync(configPath, { encoding: 'utf8' }));
```
Instead of returning a YAML object. Your example is working because both KEY is a string and so you won't have any difference between YAML and dotenv.

But on our infrastructure we are using Redis Sentinel for cache and we have a config like this:
```
REDIS_SENTINELS:
- host: myhost
  port: 26379
```
Directus could connect to the sentinel in 10.6.1 but not in 10.6.2. I've linked a pull request which should solve this bug.

**Comment by br41nslug** [comment] 2023-09-20 14:46
Closed by https://github.com/directus/directus/pull/19745

**Closed by br41nslug** 2023-09-20 14:46 UTC
Labels: Package: @directus/api, Bug

**Comment by patrostkowski** [comment] 2023-11-19 15:02
sorry for reviving an old issue, but is it really possible to use sentinel with Directus? From official Docs I have only found information about using a Redis instance, but no information regarding Sentinel.

**Comment by br41nslug** [comment] 2023-11-19 16:56
Not sure what sentinel is or how it relates to this YAML issue, but if its not in the docs you'll probably still have to build the integration. Feel free to ask around on [Discord](https://directus.chat/) for someone that has attempted the same or create a [feature request](https://github.com/directus/directus/discussions/categories/feature-requests) if appropriate
