### ISSUE TITLE
Insight panel doesn't work with filters that contains $<VARIABLES>

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#16064] opened 2022-10-19 20:59 UTC
### Describe the Bug

Panels that contains a filter with variable like $NOW crashes the entire dashboard in the user role session

![image](https://user-images.githubusercontent.com/102175921/196802725-bd7e25fd-c8d4-4769-a7fd-32d720e25865.png)

### To Reproduce

add a panel (any) on a dashboard that cotains a filter with $NOW and save, then visit that dashboard from a user session

### Errors Shown

{
  "errors": [
    {
      "message": "GraphQL schema validation error.",
      "extensions": {
        "code": "INVALID_PAYLOAD",
        "graphqlErrors": [
          {
            "message": "Syntax Error: Expected \":\", found \"(\".",
            "locations": [
              {
                "line": 1,
                "column": 142
              }
            ]
          }
        ]
      }
    }
  ]
}

### What version of Directus are you using?

9.18.1 - standard cloud

### What version of Node.js are you using?

standard cloud

### What database are you using?

standard cloud

### What browser are you using?

firefox and chrome

### How are you deploying Directus?

standard cloud

**Comment by rijkvanzanten** [comment] 2022-10-19 21:02
Duplicate of https://github.com/directus/directus/issues/15602

**Closed by rijkvanzanten** 2022-10-19 21:02 UTC
