### ISSUE TITLE
GraphQL file fields cannot be renamed since rc-94

### ISSUE THREAD

**Issue by Moeriki** [directus/directus#8422] opened 2021-09-29 14:17 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When I query a collection with a single file field I can no longer rename the field.

GraphQL returns.

> Cannot destructure property 'type' of 'field' as it is undefined.

### To Reproduce

Create a new collection `test` with a default id and add one "Single File" `file` field. You'd end up with something like this.

```sql
CREATE TABLE `test` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `file` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `test_file_foreign` (`file`),
  CONSTRAINT `test_file_foreign` FOREIGN KEY (`file`) REFERENCES `directus_files` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

You could add an item to the collection for easier debugging, but it isn't necessary to reproduce the issue.

Query the file field with permissions (or set public read access to the collection and `directus_files`).

Without renamed fields it works fine 👍

```graphql
{
  test {
    file { id }
  }
}
```

With a renamed field it returns an error ⚠️

```graphql
{
  test {
    renamedField: file { id }
  }
}
```

```json
{
  "errors": [
    {
      "message": "Cannot destructure property 'type' of 'field' as it is undefined.",
      "locations": [
        {
          "line": 1,
          "column": 17
        }
      ],
      "path": [
        "test"
      ]
    }
  ],
  "data": {
    "test": null
  }
}
```

This was not an issue in rc-93. The issue is producible in both rc-94 and rc-95.

I dug into the code and commits between those versions without success. If I have to guess I'd say it came with the Insight module changes.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

14.16.0

### What database are you using?

mysql:5.7

### What browser are you using?

Firefox Developer Edition

### What operating system are you using?

macOS

### How are you deploying Directus?

Jenkins

**Comment by rijkvanzanten** [comment] 2021-09-29 15:53
Duplicate of https://github.com/directus/directus/issues/8402 👍🏻

**Closed by rijkvanzanten** 2021-09-29 15:53 UTC
Labels: Bug (Potential)
