### ISSUE TITLE
Activate multiple inactive entries

### ISSUE THREAD

**Issue by RabbitMC** [directus/directus#1363] opened 2017-03-02 11:02 UTC
## Version Info
  - Directus version and branch: 6.3.8
  - PHP version: 7.1.2
  - MySQL version: 5.7
  - Web server:  Apache 2
  - OS name and version: Ubuntu 14.04

## Expected Behavior
After selecting 5 or more inactive entries, and clicking on "Active", I expect, that all the selected inactive entries turned to be active.

## Actual Behavior
Error shows up
Behavior for only 1 entry works!
Batch Edit works!

## Steps to Reproduce
 1. Import a lot of data as inactive
 2. Select 5 or more inactive entries
 3. Click on "Active" Button

## Logs or Screenshots
Error
Error: TypeError: model.toJSON is not a function. (In 'model.toJSON({changed: true})', 'model.toJSON' is undefined) File: https://<>/app/core/entries/EntriesCollection.js?bust=10a92a049d64f133c08fad16bdc81626938bb3cc Line:112

**Comment by WellingGuzman** [comment] 2017-03-04 07:05
Hey @RabbitMC,

I'm not able to reproduce, everything looks as expected, is there anything in particular in this table, I created a simple table with `id, active and title` as columns, and it worked.

**Comment by WellingGuzman** [comment] 2017-05-03 05:38
Hey @RabbitMC,

I'm closing this ticket as it seems to be working as expected, otherwise if you are still experiencing this issue please let us know.

**Closed by WellingGuzman** 2017-05-03 05:38 UTC
