### ISSUE TITLE
Upload file resulted in undefined binding when compiling update

### ISSUE THREAD

**Issue by lumintulogic-admin** [directus/directus#12920] opened 2022-04-21 09:35 UTC
### Describe the Bug

When adding new file using upload file GUI, there is an error when saving an item in a collection

### To Reproduce

1. Click upload file in a file upload field
2. Choose a file from local device
3. Click OK
4. File is not displayed in the files field
5. Click submit
6. Error message displays
{
  "message": "Undefined binding(s) detected when compiling UPDATE. Undefined column(s): [id] query: update `Report_files` set `Report_id` = ?, `directus_files_id` = ? where `id` in (?)",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}

### Errors Shown

{
  "message": "Undefined binding(s) detected when compiling UPDATE. Undefined column(s): [id] query: update `Report_files` set `Report_id` = ?, `directus_files_id` = ? where `id` in (?)",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

10.19.0

### What database are you using?

MariaDB 10.3.34

### What browser are you using?

Chrome

### How are you deploying Directus?

Local Installation of Linux Mint 20.3

**Comment by azrikahar** [comment] 2022-04-21 09:37
Thanks for opening this issue! However this is a duplicate of an existing issue #12812, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-21 09:37 UTC
Labels: Bug (Potential)
