### ISSUE TITLE
Cannot login "Unknow error. Please try again later"

### ISSUE THREAD

**Issue by Tynyndil** [directus/directus#2285] opened 2019-01-24 14:29 UTC
# Bug Report

I'm new to directus and to Headless CMS, I just can't log in whether it's with the users' information I provided (which give's me an Unknow error) or with the admin@exemple.com (which gives me a Wrong password error).

## Steps to Reproduce

1. mod_rewrite enabled and all other requirement checked
2. Install Directus with git clone in my local server
3. Go to localhost/directus/public/admin
4. Setup API and database
5. The database does set up correctly, a user is created in directus_users
6. Go back to localhost/directus/public/admin to log in, enter the admin user information previously created

## Expected Behavior

Log in and access to the back office

## Actual Behavior

Get an "Unknow error. Try again later."

## Other Context & Screenshots

**Console logs :** 
directus-sdk.umd.min.js:1 POST http://127.0.0.1:8080/edsa-Yukey/_/auth/authenticate 500 (Internal Server Error)

![image](https://user-images.githubusercontent.com/20043825/51684634-c20ebf00-1fec-11e9-883a-80f5c6141452.png)

No logs in the /logs folder.

## Technical Details

- Device: Omen laptop
- OS: Windows 10
- Web Server: Apache 2.4.25
- PHP Version: 7.1.3
- Database: 5.7.17
- Install Method: cloned master branch
- Using EasyPHP

**Comment by benhaynes** [comment] 2019-01-24 16:59
If you used the installer then you would have set the email/password ... you wouldn't necessarily be using our defaults. Did you confirm that your document root is set to the `/public` directory?

Also, if you _are_ using our defaults, I assume you used the correct email `admin@example.com` (with an "a") ... you posted here that you used `admin@exemple.com` (with an "e").

**Comment by Tynyndil** [comment] 2019-01-25 11:11
Yes, I did set an email and a password. I just wanted to show that I can't log in even with the defaults, I did use the correct email (admin@example.com) my apologize for the mistake in my previous message. And my document root is well set to the /public directory.

**Comment by benhaynes** [comment] 2019-01-25 18:02
Gotcha — no problem!

Would it be possible to (privately) share any log files and/or database dump with us? You can send it to us over Slack if there's private info: https://slack.getdirectus.com/

Thanks! I'd love to get this resolved for you!

**Comment by niknak88** [comment] 2019-01-29 21:09
If you find any solution, please share here, I have exactly the same problem.

thank you

**Comment by niknak88** [comment] 2019-01-29 21:23
Ok, I found the problem, php curl module was not installed.

So, for me problem solved

**Comment by adamjgrant** [comment] 2019-06-17 01:14
I'm also having this problem. I've followed all the instructions including the apache configuration.

Weird thing is, when I go to the resource that's causing this failure, it's just a 200 response but it's the root of the project. When I go there directly, it prints out PHP right in the browser:

~~~
<?php

$app = require __DIR__ . '/../src/web.php';

$app->run();
~~~

**Comment by rijkvanzanten** [comment] 2019-06-17 13:04
> When I go there directly, it prints out PHP right in the browser:

This sounds like a server setup problem @adamjgrant. Are you sure PHP runs in your Nginx environment?

**Comment by adamjgrant** [comment] 2019-06-17 19:21
@rijkvanzanten Yeah you beat me to it!

I'm feeling a little dumb about this one. I used the httpd docker container thinking it was basically a LAMP stack without the MySQL, but nope. No PHP. 

I instead used an actual LAMP stack for my container and got it working this way.

Would be great if the error messaging could be more specific though. Thanks for checking in and helping, sir.

**Comment by rijkvanzanten** [comment] 2019-06-17 19:24
I'm wondering if we can throw a more useful error if PHP doesn't run 🤔 Without the API being able to run, it's not able to provide any useful error either.

**Comment by nthtrung09it** [comment] 2019-06-20 04:26
If you've been using nginx and php-fpm and countered this login issue, you can use this below command to fix it:
`chown -R nginx:nginx /var/lib/php/`

**Comment by rijkvanzanten** [comment] 2019-06-20 12:44
I'm closing this issue as this very generic error message can have a multitude of origins all caused by different server configuration issues.

Feel free to open a new issue if there's a specific problem on a specific server env

**Closed by rijkvanzanten** 2019-06-20 12:44 UTC
Labels: not reproducible, transfer
