### ISSUE TITLE
Translation UI and API of rc.19

### ISSUE THREAD

**Issue by fabiankuhn** [directus/directus#3281] opened 2020-12-03 10:28 UTC
I created an "auto generated" translation in rc.19. While the setup and database work, the UI does not show the previously implemented (v8) language selector. Therefor the translation is not mapped and neither saved to the database, nor shown in the API. See the screenshots attached.

<img width="1139" alt="1  Translation" src="https://user-images.githubusercontent.com/34968622/100996861-e0836100-3559-11eb-8bdf-8f1b215e7131.png">
<img width="1140" alt="2  Translation Table" src="https://user-images.githubusercontent.com/34968622/100996857-df523400-3559-11eb-8cf9-8f65bf462efa.png">
<img width="1141" alt="3  Language Table" src="https://user-images.githubusercontent.com/34968622/100996849-dcefda00-3559-11eb-817e-ad180e05926f.png">
<img width="1340" alt="4  Item Detail" src="https://user-images.githubusercontent.com/34968622/100997677-dca40e80-355a-11eb-835f-40e9c3724746.png">
<img width="1117" alt="5  Api " src="https://user-images.githubusercontent.com/34968622/100997702-e62d7680-355a-11eb-9073-91b70021dcbb.png">
<img width="525" alt="6  sql" src="https://user-images.githubusercontent.com/34968622/100997710-ea599400-355a-11eb-9a42-9661eefed079.png">

---

### Project details
Directus Version: 9.0.0-rc.19
Environment: production
OS: Linux 5.4.39-linuxkit
Node: 14.15.1

**Comment by Fusseldieb** [comment] 2020-12-03 10:46
Similar to #3230

**Comment by fabiankuhn** [comment] 2020-12-03 11:27
Agreed, thanks @Fusseldieb. Just also tested with rc.18. The logic seems to work there. I very much preferred the language selector of v8 though. Thats another topic though...

<img width="614" alt="Screenshot 2020-12-03 at 12 25 41" src="https://user-images.githubusercontent.com/34968622/101011146-cb5f0000-3562-11eb-9f87-c2ef02190bf7.png">
<img width="999" alt="Screenshot 2020-12-03 at 12 25 50" src="https://user-images.githubusercontent.com/34968622/101011167-cc902d00-3562-11eb-9072-9def909ac7a5.png">

**Comment by rijkvanzanten** [comment] 2020-12-03 14:34
Duplicate of #3230

**Closed by rijkvanzanten** 2020-12-03 14:34 UTC
