### ISSUE TITLE
Can't delete Account

### ISSUE THREAD

**Issue by Lucas-Gruber** [directus/directus#17748] opened 2023-03-08 17:47 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When i try to delete a Account, i become this error:

![image](https://user-images.githubusercontent.com/72545889/223790073-0a07aeda-32c4-4b99-bab3-35cd8bb32b1e.png)

### To Reproduce

1. Select an account
2. Click on delete

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-03-09 12:53
Thanks for opening this issue! However this is a duplicate of an existing issue #9507, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #9507 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2023-03-09 12:53 UTC
