### ISSUE TITLE
All collapsible detail groups start closed, no matter the setting

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#12305] opened 2022-03-22 16:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When upgrading to 9.7.0 from 9.4.2, I noticed that all our detail groups start closed.

It doesn't matter what I choose in the setting (Start open / Start closed), they stay closed on refresh.

See video here:

https://user-images.githubusercontent.com/9347206/159534573-019c32b2-403b-42cb-90bd-b6b093acf090.mov

### To Reproduce

1. Create a detail group with some content
2. Set "Interface" -> "Start" to "Start open".
3. The group starts closed.

### Errors Shown

None

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-03-22 17:03
Duplicate of https://github.com/directus/directus/issues/12257

**Closed by rijkvanzanten** 2022-03-22 17:03 UTC
Labels: Bug (Potential)
