### ISSUE TITLE
Editing a translation field fails with error (and creates new translation tables)

### ISSUE THREAD

**Issue by madc** [directus/directus#9438] opened 2021-11-03 21:23 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a simple `Page` data model, that contains a translation field. The data model was created with `rc94` and since updating to `rc100` I can't edit the translation field anymore.

![Screenshot-20211103220737-846x406](https://user-images.githubusercontent.com/343392/140194258-9cf292c5-1f69-49e3-8a22-604d4d99dbb8.png)

Just opening the edit dialog and saving it again fails with this error message:
![Screenshot-20211103220250-1615x915](https://user-images.githubusercontent.com/343392/140193220-eb0e9e6a-2423-4b39-9846-8c25d8401383.png)

After trying this a couple of times, I noticed, that my data where gone and the console shows some errors:
![Screenshot-20211103220515-1615x916](https://user-images.githubusercontent.com/343392/140193631-0b705381-97d2-4f88-9772-2774babc8c5f.png)

The error messages are `TypeError: i.value is null` and below `TypeError: e.languageOptions is undefined`.

I than noticed that the reference to the translation table had changed (should be without `_10`):
![Screenshot-20211103220337-600x357](https://user-images.githubusercontent.com/343392/140193933-37f70dc6-b155-4eaa-92e4-466827b1b6ff.png)

and that the tables where created (1-9, but not 10):
![Screenshot-20211103220419-481x690](https://user-images.githubusercontent.com/343392/140194180-142703b1-8269-43a7-b05f-3a673eb0c6f1.png)

And now the really strange thing, after hard reloading the app, the collection shows the data again, but the connection is still shown with `_10`.

I hope it is possible to understand this issue.. let me know if I can provide more details.

### To Reproduce

- Create a translation field (with r94?)
- Update to r100?
- Open the edit dialog and save

### What version of Directus are you using?

r100

### What version of Node.js are you using?

v12.22.4

### What database are you using?

MySQL

### What browser are you using?

Firefox 94

### What operating system are you using?

Linux

### How are you deploying Directus?

Manually

**Comment by rijkvanzanten** [comment] 2021-11-03 21:26
Duplicate of https://github.com/directus/directus/issues/9315

**Closed by rijkvanzanten** 2021-11-03 21:26 UTC
Labels: Bug (Potential)
