### ISSUE TITLE
UI not updating on content pages within admin UI on client-side navigation

### ISSUE THREAD

**Issue by huntabyte** [directus/directus#17049] opened 2023-01-08 21:08 UTC
### Describe the Bug

Upon initial navigation to one of my content pages (hard refresh or direct navigation), the content loads as expected. However, when I attempt to navigate to another content page, the content isn't being rendered on the page. In order for it to actually render, I have to fully reload the page.

As seen in this [screenshare](https://www.loom.com/share/343d5aaf134547dbb2fa031dfe74a6bc), the fetch requests are being made and the browser does have the data, but the UI isn't updating until I hard refresh the browser.

I'm getting the same results on the following browsers:
- Chrome
- Edge
- Firefox

I currently have Directus deployed to my local machine via docker-compose and the database is hosted elsewhere.

It's also strange that navigating from any other admin menu and then to any content page works fine, this is only happening when navigating from one content page -> another content page.

### To Reproduce

1. Navigate to a content page directly (the content loads as expected)
2. Using the Admin UI navigation, navigate to another content page.
3. Observe that the data was in fact fetched via the Network tab of your browser dev tools.

### Errors Shown

There are no errors displayed in the browser's console or the terminal.

`docker compose logs -f` during navigation for reference:

![WindowsTerminal_BxWcMXules](https://user-images.githubusercontent.com/64506580/211219035-cfcdcfd1-b541-488c-ad0e-7dd65f1cfe71.png)

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 15.1

### What browser are you using?

Chrome, Firefox, Edge

### How are you deploying Directus?

Docker

**Comment by jasonfx13** [comment] 2023-01-08 21:24
I can confirm this is happening to me as well.

**Comment by freekrai** [comment] 2023-01-08 22:28
Duplicate of https://github.com/directus/directus/issues/16883, which was fixed and merged in https://github.com/directus/directus/pull/16881, just waiting for a release.

**Closed by freekrai** 2023-01-08 22:28 UTC
