### ISSUE TITLE
Deep parameters typing issue in SDK

### ISSUE THREAD

**Issue by stafyniaksacha** [directus/directus#19940] opened 2023-10-06 21:13 UTC
### Describe the Bug

Defining limit/sort on `deep` parameters on new SDK result in bad typings

### To Reproduce

```ts
directus.request(
  readItems('my_items', {
    fields: {
      {
        my_relations: ['*'],
      },
    },
    deep: {
      my_relations: {
        // here autocomplete works, it suggest _limit and so on,
        // but when a value is set, deep.my_relations has typing issue
        _limit: 1,
        _sort: '-date_created',
      }
    }
  }),
)
```

![image](https://github.com/directus/directus/assets/3911343/8e226dd4-f881-47ab-80b3-461519e680d7)

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-10-09 08:16
The typing error should disappear when using an array for `fields`:
```ts
directus.request(
  readItems('my_items', {
    fields: [
      {
        my_relations: ['*'],
      },
    ],
    deep: {
      my_relations: {
        // here autocomplete works, it suggest _limit and so on,
        // but when a value is set, deep.my_relations has typing issue
        _limit: 1,
        _sort: '-date_created',
      }
    }
  }),
)
```

Closing this for now, happy to re-open if this does not fix it 😄

**Closed by br41nslug** 2023-10-09 08:16 UTC

**Comment by stafyniaksacha** [comment] 2023-10-11 09:36
> The typing error should disappear when using an array for `fields`:
> Closing this for now, happy to re-open if this does not fix it 😄

Sorry, it was a typo for the issue, The issue exists when using arrays!

**Comment by br41nslug** [comment] 2023-10-11 09:57
> Sorry, it was a typo for the issue, The issue exists when using arrays!

Can you share the used schema for `my_items` then because i was unable to reproduce it with the given information.
