### ISSUE TITLE
Extensions do not auto reload when EXTENSIONS_AUTO_RELOAD=true

### ISSUE THREAD

**Issue by that1matt** [directus/directus#20169] opened 2023-10-24 16:00 UTC
### Describe the Bug

When building an extension, and setting `EXTENSIONS_AUTO_RELOAD=true` Directus no longer updates to reflect the changes.

### To Reproduce

1. Create new extensions (any type)
2. Run `directus-extension build -w --no-minify` in extension
3. Make change to extension
4. No changes are detected.

### Directus Version

10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-10-24 16:50
Is this a duplicate of https://github.com/directus/directus/issues/18721 perhaps? 🤔

**Comment by that1matt** [comment] 2023-10-24 16:52
> Is this a duplicate of #18721 perhaps? 🤔 Or is this an issue for all OS's now

The reloading was working on 10.6.4, and only recently broke with 10.7.0. 

I am on macOS Sanoma 14.0 (23A344) (M1) if that helps.

**Comment by Arood** [comment] 2023-10-24 20:51
I'm also experiencing this issue after updating to 10.7 (worked before), also on macOS Sonoma (M2) running in Docker. So it seems to be a new issue.

**Comment by stefanovalentegva** [comment] 2023-10-25 16:13
I'm also having the same problem after updating to version 10.7. I'm on a MacOS Sonoma (M1) running Docker.

**Closed** 2023-10-25 17:48 UTC
Labels: Package: @directus/api, Bug, Regression
