### ISSUE TITLE
Getting 403 when viewing a child instance for a many to any relationship

### ISSUE THREAD

**Issue by rbrown021** [directus/directus#17516] opened 2023-02-14 20:23 UTC
### Describe the Bug

Sometimes, when viewing a child instance joined via many-to-any relationship from the parent page, I get a 403 FORBIDDEN error message.

I can still view the child without issue.

### To Reproduce

Create 3 models:
1. go to settings > data model
2. create simple collection: example (no other starting fields)
3. add a name field to example (input)
4. create a simple collection: example_children (no other starting fields)
5. add a name field to example_children (input)
6. create a simple collection: example_grandchildren (no other starting fields)
7. add a name field to example_grandchildren (input)
8. go back to example collection, add a many to any field: descendants
9. use auto-generated junction collection with related collections = example_children and example_grandchildren
<img width="619" alt="Screen Shot 2023-02-14 at 2 26 25 PM" src="https://user-images.githubusercontent.com/54289447/218837411-e8a2dfc0-d2f3-480a-ab02-69f5b20032c2.png">

Add example data:
1. go to content > example
2. add new example
3. add descendants to the example of both types (example_children and example_grandchildren)
4. ssave.
5. Remove example descendants so the item of a different example_descendant no longer matches the id of an example_descentant and refresh directus.
For example: if I have example_descendants in my db as below:
```
id | item | collection
1  |  1      |  example_children
2 |  1      | example_grandchildren
```
I would remove example_descendant with id = 1
6. Click on the example you just created/modified 
7. Click on the example descendant where the item doesn't match any ids

currently: you see the FORBIDDEN error message when you try to view this.
if i dismiss the error, I still see the correct example descendant with all of the correct information, but this error is really annoying and misleading. It causes our users to lose trust in our product and creates a bunch of unnecessary support tickets.

note: I checked the logs and when i click to view a child, it does this:
```
admin_1    | [17:29:51] GET /items/{{junction_collection}}/{{item}} 403
admin_1    | [17:29:51] GET /items/{{junction_collection}}/{{id}}?fields=*,item.* 200
```

so if we have the following data:
```
id | item | collection
1  |  1      |  example_children
2 |  1      | example_grandchildren
3 |  4     | example_children
```

if you click on the descendent with id = 1 from the parent view, you don't get any issues.
logs:
```
admin_1    | [17:29:51] GET /items/example_descendants/1 200
admin_1    | [17:29:51] GET /items/example_descendants/1?fields=*,item.* 200
```

if you click on the descendent with id = 2 from the parent view, you don't see the error because there is an example descendant with id = 1, but this is getting the incorrect example_descendant. It does however, show the example_grandchildren instance, so this isn't a big deal, just not sure why it would need to get the example_descendant where id = item...
```
admin_1    | [17:29:51] GET /items/example_descendants/1 200
admin_1    | [17:29:51] GET /items/example_descendants/2?fields=*,item.* 200
```

if you click on the descendant with id = 3, then you get the FORBIDDEN error:
```
admin_1    | [17:29:51] GET /items/example_descendants/4 200
admin_1    | [17:29:51] GET /items/example_descendants/3?fields=*,item.* 200
```

I guess I don't really understand why it needs to call the example_descendant where id = item in the first place. this doesn't appear to have any effect on what shows up afterwards since it is calling the correct example_descendant with the correct id afterwards anyway, which also gets the correct related `item`. 

Something else to note: This is a very simplified example just easily get to a reproducible point.
I delete these connections periodically for various reasons (either, they aren't needed anymore or if I have some tables that are seeded with informational context only and we change the information, I will wipe the existing content and just re-seed rather than try to find and replace existing data. 

### Errors Shown

<img width="578" alt="Screen Shot 2023-02-14 at 2 15 00 PM" src="https://user-images.githubusercontent.com/54289447/218836358-bd6a1c8b-12c0-4ad3-ac64-2994f58957a2.png">

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

postgis/postgis:14-master

### What browser are you using?

chrome

### How are you deploying Directus?

locally inside a docker container, deployed to AWS (occurs both when i run the docker locally and when run on AWS)

**Comment by rijkvanzanten** [comment] 2023-02-14 20:26
Can you share a schema snapshot or database dump where this is happening?

**Comment by rbrown021** [comment] 2023-02-14 20:34
sure, here's a pgdump of the 4 tables (as described above)
[pan_dev-2023_02_14_15_31_02-dump.sql.zip](https://github.com/directus/directus/files/10736660/pan_dev-2023_02_14_15_31_02-dump.sql.zip)

**Comment by benosman** [comment] 2023-02-14 20:37
I've also encountered this error, but hadn't had a chance to work out how to reproduce it. Thanks @rbrown021 for taking the time to post this issue.

**Comment by rbrown021** [comment] 2023-02-14 20:38
> sure, here's a pgdump of the 4 tables (as described above) [pan_dev-2023_02_14_15_31_02-dump.sql.zip](https://github.com/directus/directus/files/10736660/pan_dev-2023_02_14_15_31_02-dump.sql.zip)

Btw, with this data, the one that has the issue is:
`Example Chilrden: 7`
<img width="857" alt="Screen Shot 2023-02-14 at 3 35 00 PM" src="https://user-images.githubusercontent.com/54289447/218856705-94ead3b3-e414-4ab6-8a1b-83f4f2a77edf.png">

when I click on it, these are the logs:
admin_1        | [20:34:44] GET /items/example_descendants/7 403 214ms
admin_1        | [20:34:44] GET /items/example_descendants/9?fields=*,item.* 200 263ms

I get the error because there is no example_descendants with id = 7
The 7 comes from the item field, related example_children.id = 7

**Comment by rijkvanzanten** [comment] 2023-02-14 20:52
> I've also encountered this error, but hadn't had a chance to work out how to reproduce it. Thanks @rbrown021 for taking the time to post this issue.

I've seen it pass by a couple times in the past as well, but I've never been able to reproduce it on the shared steps.. Glad to hopefully make some steps in the right direction now 🙂

**Comment by Modocosm** [comment] 2023-02-15 03:40
Ive been able to pretty consistently nuke postgres using M2a with 15+ children that have children that may have children.
on any version between 9.21.x -> 9.22.4 Starts with a few forbidden warnings
then directus_relations empties itself. then tables start to disappear or show up intermittently

**Comment by licitdev** [comment] 2023-02-15 04:24
Duplicate of #17108

**Closed by licitdev** 2023-02-15 04:24 UTC
Labels: App, Bug (Potential)

**Comment by xu4wang** [comment] 2023-02-23 09:08
I have the same 403 error.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/311397/220863942-576a553a-0fc4-4241-b884-88124f6fa908.png">
