### ISSUE TITLE
Cannot create Many to One field in Directus Cloud - and crashes viewing any item in collection

### ISSUE THREAD

**Issue by willemmulder** [directus/directus#14718] opened 2022-07-28 12:16 UTC
### Describe the Bug

I try to create a One to Many field with a foreign key set to an earlier created Many to One field. In other words: I want to display all the children items on the parent item. However I get this message

![image](https://user-images.githubusercontent.com/70933/181502142-def8b5fd-4a3f-4a77-ab23-b8695884d15a.png)

The field does get created, but now whenever I visit an item in the collection I get this message, even though the URL is definitely correct (https://b3339lek.directus.app/admin/content/common_influence_factors/9f083909-6184-4e6a-b754-9f133c8e088c) and worked before.

![image](https://user-images.githubusercontent.com/70933/181502317-85d58fd7-7c0f-4da7-bca6-ead00a4b845c.png)

When I delete the field (which I did honestly not expect to work, but it does - hooray) everything is back to normal. Viewing items in the collection resumes working as well.

### To Reproduce

Create a collection

Create a Many to One field (i.e. the field on the child side of the relation)

Create a One to Many field with that Many to One field as foreign key. 

Error pops up and and viewing items in the collection stops working.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

SQLite (Directus Cloud with free project... that's SQLite right?)

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by rijkvanzanten** [comment] 2022-07-28 21:39
> Create a Many to One field with that One to Many field as foreign key.

This feels incorrect to me. The one-to-many (o2m) "field" is an alias, not a column in the db, so doesn't hold any data itself. Once you create a o2m field, it will require that a m2o exists to use to hold the parent key. Also, many-to-one (m2o) fields don't require/allow you to set a foreign key 🤔 Did you mean those two to be reversed? 

Mind detailing exactly what the steps were you took to get to this point? For example:

1. Create collection `articles`
2. Create collection `comments`
3. Create o2m `articles.comments` with:
    ```
    Related Collection: articles
    Foreign Key: articles_id
    ```
4. etc..

That'd greatly help us figure out what's going on here 🙂 Groetjes!

**Comment by willemmulder** [comment] 2022-07-28 21:55
Whoops, yes I meant those in reverse. Sorry for the confusion :-)

1. create collection `categories`
2. create m2o field `parent category`
3. create o2m field 'child categories'

That's it. My guess would be the problem is somewhere in the combination of using a 'self-referential field' and SQLite, given my other problems around the same topic and with identical types of error messages ;-)

**Comment by rijkvanzanten** [comment] 2022-07-28 22:23
What was the exact configuration for the o2m field? What foreign key were you using?

**Comment by willemmulder** [comment] 2022-07-29 12:57
I have deleted the o2m field in the meantime, but it had 100% standard setup, except for its name and the foreign key, which pointed to the previously created m2o field.

**Comment by rijkvanzanten** [comment] 2022-12-15 22:37
Linear: [ENG-219](https://linear.app/directus/issue/ENG-219/cannot-create-many-to-one-field-in-directus-cloud-and-crashes-viewing)

**Comment by paescuj** [comment] 2023-02-03 10:04
I haven't been able to reproduce this issue (probably also due to the lack of information).
Therefore I'm going to close it for now.
If this is still a problem, please open a new bug report with a more precise reproduction.

**Closed by paescuj** 2023-02-03 10:04 UTC
Labels: API, Needs More Info
