### ISSUE TITLE
Migration Error - v9.0.0-rc.88 to v9.0.0-rc.100 and Beyond

### ISSUE THREAD

**Issue by sarthakgaur** [directus/directus#10899] opened 2022-01-07 04:17 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am trying to migrate from v9.0.0-rc.88 to v9.0.0-rc.100, but I am getting an error when I try to run the migrations. This also happens when we try to upgrade to any version beyond v9.0.0-rc.100.

### To Reproduce

It looks like only some people are having this issue who are on v9.0.0-rc.88. I created a [discussion](https://github.com/directus/directus/discussions/9348) on this a few months back.

### Errors Shown

```
$ npx directus database migrate:latest
18:26:03 ✨ Loaded extensions: link, tags
18:26:03 ✨ Running migrations...
18:26:03 ✨ Applying Add Auth Provider...
18:26:03 🚨 error alter table "directus_users" drop constraint "directus_users_email_unique" - constraint "directus_users_email_unique" of relation "directus_users" does not exist 
error: alter table "directus_users" drop constraint "directus_users_email_unique" - constraint "directus_users_email_unique" of relation "directus_users" does not exist
    at Parser.parseErrorMessage (/home/john/project/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/john/project/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/john/project/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/john/project/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

### What version of Directus are you using?

v9.0.0-rc.88

### What version of Node.js are you using?

v14.18.2

### What database are you using?

PostgreSQL 13.4

### What browser are you using?

Firefox

### What operating system are you using?

Fedora 34

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment] 2022-01-07 04:50
Seems like a duplicate of #9655, #8499, #8368.

Can you try adding the constraint manually and try migrating again? You can add it by running the following on your db:

```sql
ALTER TABLE directus_users ADD CONSTRAINT directus_users_email_unique UNIQUE(email);
```

[Reference](https://github.com/directus/directus/issues/9655#issuecomment-964980456)

**Closed by azrikahar** 2022-01-07 04:50 UTC
Labels: Bug (Potential)

**Comment by sarthakgaur** [comment] 2022-01-07 05:19
@azrikahar Thanks for the quick reply. I ran the SQL command that you have just mentioned and tried updating to the latest version (v9.4.2). It solves the previous error. However, now I get a new error message:

```
$ npx directus database migrate:latest
10:40:14 ✨ Loaded extensions: link, tags, filtered-collections, news, terms, dues, exams, mail, periods, schedule, users, filtered-collections, mail, schedule, terms
10:40:14 ✨ Running migrations...
10:40:14 ✨ Applying Add Insights...
10:40:15 ✨ Applying Add Required to Fields...
10:40:16 ✨ Applying Update Groups...
10:40:16 ✨ Applying Change Image Metadata Structure...
10:40:16 ✨ Applying Add Geometry Config...
10:40:16 ✨ Applying Remove Limit Column...
10:40:16 ✨ Applying Add Auth Provider...
10:40:16 ✨ Applying Webhooks Collections Not Null...
10:40:16 ✨ Applying Move Module Setup...
10:40:16 ✨ Applying Webhooks URL Not Null...
10:40:17 ✨ Applying Add Collection Organization...
10:40:17 ✨ Applying Replace Fields Group...
10:40:17 🚨 error alter table "directus_fields" drop constraint "directus_fields_group_foreign" - constraint "directus_fields_group_foreign" of relation "directus_fields" does not exist 
error: alter table "directus_fields" drop constraint "directus_fields_group_foreign" - constraint "directus_fields_group_foreign" of relation "directus_fields" does not exist
    at Parser.parseErrorMessage (/home/john/project/api/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/john/project/api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/john/partition/project/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/john/project/api/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

**Comment by azrikahar** [comment] 2022-01-07 05:55
that seems like this: https://github.com/directus/directus/issues/8369#issuecomment-955686079, so perhaps you can try https://github.com/directus/directus/issues/8369#issuecomment-956836925.

Just to clarify, the migration should have been straightforward, but I suspect the halfway migrations you have done (halfway as in not directly to current 9.4.2) might have ended up with old migrations that we have patched in later versions. That said, hope the above link helps to resolve your current issue.

**Comment by sarthakgaur** [comment] 2022-01-07 06:05
@azrikahar I am trying to upgrade directly from v9.0.0-rc.88 to v9.4.2. I earlier tried migrating in steps, I don't see any error messages on the console. But, I run into many issues like not being able to hide fields of a collection, unable to delete fields of a collection, not being able to add item to a collection with relationships, and many more issues. So, I am trying to avoid doing the migration in steps and just do it directly.

**Comment by azrikahar** [comment] 2022-01-07 06:53
totally understandable 👍 ideally migrations shouldn't cause issues you have mentioned, but there's no doubt always a possibility of certain edge case/setups having hiccups with the migrations (also proven by patches to migrations we had to do in the past!) since we support a number of platforms + databases.

**Comment by sarthakgaur** [comment] 2022-01-07 07:01
@azrikahar Thanks for understanding the issue, and for replying so quickly. Really appreciate your help! I think I have added all the context regarding this issue. If you need some additional information, please let me know. My team is currently stuck because we want to move to the latest version of Directus, but there is no clear path for us. It would be great if you can reopen this issue.

**Comment by azrikahar** [comment] 2022-01-07 07:12
If you are stuck on [this error](https://github.com/directus/directus/issues/10899#issuecomment-1007148459), can you try running the following statement and run the migrations again? with backup beforehand just in case of course.

```sql
ALTER TABLE directus_fields ADD CONSTRAINT directus_fields_group_foreign FOREIGN KEY (group) REFERENCES directus_fields (id);
```

**Comment by sarthakgaur** [comment] 2022-01-07 07:38
These are the commands that I ran:

1.
```
api=# \d directus_fields
                                        Table "public.directus_fields"
     Column      |         Type          | Collation | Nullable |                   Default                   
-----------------+-----------------------+-----------+----------+---------------------------------------------
 id              | integer               |           | not null | nextval('directus_fields_id_seq'::regclass)
 collection      | character varying(64) |           | not null | 
 field           | character varying(64) |           | not null | 
 special         | character varying(64) |           |          | 
 interface       | character varying(64) |           |          | 
 options         | json                  |           |          | 
 display         | character varying(64) |           |          | 
 display_options | json                  |           |          | 
 readonly        | boolean               |           | not null | false
 hidden          | boolean               |           | not null | false
 sort            | integer               |           |          | 
 width           | character varying(30) |           |          | 'full'::character varying
 group           | integer               |           |          | 
 translations    | json                  |           |          | 
 note            | text                  |           |          | 
 conditions      | json                  |           |          | 
Indexes:
    "directus_fields_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "directus_fields_group_fkey" FOREIGN KEY ("group") REFERENCES directus_fields(id)
Referenced by:
    TABLE "directus_fields" CONSTRAINT "directus_fields_group_fkey" FOREIGN KEY ("group") REFERENCES directus_fields(id)
```

2. `ALTER TABLE directus_fields DROP CONSTRAINT directus_fields_group_fkey;`

3. `ALTER TABLE directus_fields ADD CONSTRAINT directus_fields_group_foreign FOREIGN KEY("group") REFERENCES directus_fields(id);`

After doing that I ran `npx directus database migrate:latest` command. All the migrations ran successfully! I opened the browser and tested a few things. For now, I think it is working well. We never tried changing anything in the system tables. So, now that you are here. Can you please confirm what I did here was right? Most importantly was executing `ALTER TABLE directus_fields DROP CONSTRAINT directus_fields_group_fkey;` the right thing to do here?

**Comment by azrikahar** [comment] 2022-01-07 07:48
Seems right to me! But since your group column is now `integer` (do confirm this again before doing the following), I believe now you just need to do 1 last thing: https://github.com/directus/directus/issues/8675#issuecomment-940629829. You can also check this video which should hopefully clarify it further: https://github.com/directus/directus/issues/8675#issuecomment-940940506

Basically we need to re-run the Replace Fields Group migration, so that the group column should end up as `string` instead. Once you have done this, do verify whether it is now `string` type or not.

**Comment by sarthakgaur** [comment] 2022-01-07 08:46
@azrikahar The `group` column was an integer before the migrations, then I ran the following commands:

1. `ALTER TABLE directus_fields DROP CONSTRAINT directus_fields_group_fkey;`
2. `ALTER TABLE directus_fields ADD CONSTRAINT directus_fields_group_foreign FOREIGN KEY("group") REFERENCES directus_fields(id);`
3. `npx directus database migrate:latest`

This is the schema for `directus_fields` right now:

```
api=# \d directus_fields
                                        Table "public.directus_fields"
     Column      |         Type          | Collation | Nullable |                   Default                   
-----------------+-----------------------+-----------+----------+---------------------------------------------
 id              | integer               |           | not null | nextval('directus_fields_id_seq'::regclass)
 collection      | character varying(64) |           | not null | 
 field           | character varying(64) |           | not null | 
 special         | character varying(64) |           |          | 
 interface       | character varying(64) |           |          | 
 options         | json                  |           |          | 
 display         | character varying(64) |           |          | 
 display_options | json                  |           |          | 
 readonly        | boolean               |           | not null | false
 hidden          | boolean               |           | not null | false
 sort            | integer               |           |          | 
 width           | character varying(30) |           |          | 'full'::character varying
 translations    | json                  |           |          | 
 note            | text                  |           |          | 
 conditions      | json                  |           |          | 
 required        | boolean               |           |          | false
 group           | character varying(64) |           |          | 
Indexes:
    "directus_fields_pkey" PRIMARY KEY, btree (id)

```

The `group` column is a `string`. This is how it should be, right?

**Comment by azrikahar** [comment] 2022-01-07 08:48
@sarthakgaur yes that looks good to me 👍 glad this is sorted!

**Comment by sarthakgaur** [comment] 2022-01-07 08:50
@azrikahar Thanks a lot! Really appreciate your help. The developers/maintains are really helpful here. Again, thank you so much!
