### ISSUE TITLE
v9-rc.81 - Error: EACCES: permission denied

### ISSUE THREAD

**Issue by Mayccoll** [directus/directus#6552] opened 2021-06-28 22:25 UTC
### Describe the Bug

22:09:24 ✨ Initializing bootstrap...
22:09:24 ✨ Database already initialized, skipping install
22:09:24 ✨ Running migrations...
22:09:24 ✨ Done
[Error: EACCES: permission denied, mkdir '/directus/extensions/interfaces'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/directus/extensions/interfaces'
}

### To Reproduce

docker-compose up -d

### What version of Directus are you using?

v9-rc.81

### What version of Node.js are you using?

Docker version

### What database are you using?

mariadb:10.3

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by Mayccoll** [comment] 2021-06-28 22:34
happens when the volumes are local to a relative path, either running Docker as root or as sudo user.

**Comment by rijkvanzanten** [comment] 2021-06-28 22:49
Is this when upgrading from a previous version on Docker, or a fresh installation?

**Comment by rijkvanzanten** [comment] 2021-06-28 22:52
I believe this is a duplicate of https://github.com/directus/directus/discussions/6480. We can reopen if not 🙂

**Closed by rijkvanzanten** 2021-06-28 22:52 UTC
Labels: Bug (Potential), Docker, Extensions
