### ISSUE TITLE
User avatar field allows uploading or selecting any file

### ISSUE THREAD

**Issue by daawaan** [directus/directus#15449] opened 2022-09-07 12:00 UTC
### Describe the Bug

Title pretty much explains everything

### To Reproduce

1. Go to users page
2. Select avatar field
3. Drop/choose non-image files to upload

### Errors Shown

N/A

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.17.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

### Related

#11733 
#14457 
#12790 
#6097

**Comment by br41nslug** [comment] 2022-09-12 11:16
Im closing this for now as this is currently technically working as intended. Tracking this as a new feature to add mime-type filtering in either https://github.com/directus/directus/discussions/12790 or https://github.com/directus/directus/discussions/11733

**Closed by br41nslug** 2022-09-12 11:16 UTC
Labels: App, Bug
