### ISSUE TITLE
Skip directus version update check

### ISSUE THREAD

**Issue by the-other-dev** [directus/directus#22845] opened 2024-06-25 13:33 UTC
### Describe the Improvement

Is it possible to add an option to skip the directus version check in self-hosted environments, e.g. via environment variables?

*Background*
When the directus CLI starts up, it makes a call to the NPM registry to check for version updates.
In self-hosted environments where the communication to external servers is prohibited this request will run into a timeout (8 seconds).
This delays the startup phase of the directus instance unnecessarily.

**Comment by rijkvanzanten** [comment] 2024-06-25 13:49
Duplicate of https://github.com/directus/directus/issues/21884

**Closed by rijkvanzanten** 2024-06-25 13:49 UTC
