### ISSUE TITLE
It's impossible to set Groups Filters in Collection view

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11449] opened 2022-02-05 17:28 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The subsequent filters of an OR will not drag to the right
![Filter Groups](https://user-images.githubusercontent.com/13746133/152652144-d1922d6f-699e-41b5-81e6-71accd02d354.png)

### To Reproduce

1. In any collection, set a filter with an OR group
2. Set two other filters
3. Try to drag them to the right to make them belong to the group

### Errors Shown
The filters won't drag to the right

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-02-06 03:48
Seems to work on my end:

![kzlBs6IWNV](https://user-images.githubusercontent.com/42867097/152666906-39b3b804-231a-4853-9218-07e94e25eb6a.gif)

Can you share how are you dragging the elements?

Just to be clear, you should drag up slightly as well to signify you're nesting it into the AND/OR block, since dragging purely horizontally doesn't bring the element _into_ the parent, if that makes sense. This interaction should be same when you are ordering/moving folders & collections in the data model page.

I'll close this for now, but do let us know if it is not possible even when you are dragging _into_ the parent/group. In that case, it'll also be helpful if you can test on another browser or even another machine just so we can remove any possibilities of machine-specific issues which can be hard to reproduce in nature.

**Closed by azrikahar** 2022-02-06 03:48 UTC
Labels: Bug (Potential)

**Comment by Pachat** [comment] 2022-02-07 07:57
Got it! I was just trying to drag on the label, instead of the handle. Thanks
