### ISSUE TITLE
Sort is set to NULL for new items. Hence the manual order is not kept.

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11430] opened 2022-02-04 10:29 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After creating a new item, the Sort field is Null.
Therefore, after moving the item to another line, the order is not registered.

### To Reproduce

1. In a Collection with Sort field, add 3 items and set the order to Manual
2. Create a new item and save it.
3. Move that item to another row.
4. Go to another collection and come back to the sorted collection
5. BUG: The item you created is not at the right place

### Errors Shown

The item you created is not at the right place.

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-02-07 11:54
Seems like this is ended up being specific to SQLite, as I was initially unable to reproduce it on PostgreSQL, but it does have an odd interaction where it initially gets set as `N-1` in terms of sorting even when we put it as the last item. Performing it once again does however resolves it.

## SQLite (bugged)

![Qf6hy7N5TG](https://user-images.githubusercontent.com/42867097/152783358-b36b194a-d677-42a6-85ab-f9903f8f933b.gif)

## PostgreSQL (working)

![vAjRLlcdzE](https://user-images.githubusercontent.com/42867097/152783303-303db0b1-99f4-4241-a030-ef83de8520d9.gif)

**Comment by domdus** [comment] 2022-02-08 22:49
Hi, I was about to create an issue addressing almost the same.

Beside noticing the SQLite bug - why not setting an incremental sort on item creation? (highest-sort-value + 1, https://github.com/directus/directus/issues/4280#issuecomment-785961831)

From searching: Same has been implemented/fixed for the relations M2A sort (#4280), 
for O2M (#10657) and M2M (#6111)

Let me know if this should be in a separate ticket.

**Comment by Oreilles** [comment] 2022-02-14 03:54
This is not a problem specific to SQLite, it is a problem with the API sort logic. When you create a new item, its sort value is set to null by default. When you drag it at the end, the following happen in the sort logic:
1. All items with a null sort field are attributed an incremented value, starting from the highest found `last`.
2. Then the API compares the sort value of the items you dragged to the one of the item it was dragged over
3. The sort value of the previous last item is still equal to `last`
4. But the item created and dragged at the end now has a sort value of `last + 1` because of 1.
5. The API therefore thinks you want to drag *down* the created item from `last + 1` to `last`
6. Hence the unexpected result

This also isn't specific to dragging it at the end, dragging it to any position will result in the dragged item being placed before instead of after the expected position.

This problem doesn't happen in Postgres, since null values are placed at the end when sorting over a column in ascending order unlike every other vendor.

The only clean/consistent alternative I see would require resolving sort field inconsistencies (nulls & dupes) after every item creation/deletion in collections having a sort field instead of after each sort operation.

**Comment by domdus** [comment] 2022-02-15 11:06
@Oreilles: Thank you for the details.
I like the clean/consistent approach with resolving sort after every item creation.
It makes _most_ sense in case of multiple items being created at a time.

Thought I could improve my case by setting some "highest possible" integer (1000) as default value for the sort field, resulting in 3 new items (created) having sort 1000.
It technically does help to have these items at the end of a list when sorting, but you can already see it randomly mixes these 3 new items specifically.

(title / date created vs. sort)
<img width="417" alt="image" src="https://user-images.githubusercontent.com/67951828/154044807-827f164c-0c36-4b04-a31d-8e68856532f5.png">

The result is now equal to having 3x sort NULL for the 3 items created - it's random. (Editors do not always notice or even expect this.)
I use Postgres which (at least luckily) places NULLs at the end in ascending order - as you explained. 

Anyway I just wanted to point out the need of the clean/consistent approach and incremental sort (without d&d action performed)

**Comment by scolastico** [comment] 2022-03-30 11:11
Is there any update on this? I have exactly the same issue as domdus:

> Today I had the situation where the editors created 5 new items for an app view depending on sort. Without doing any d&d later, the editors found the current order of items to be okay an left it - while these items sort was still set to NULL. The API connected app later showed a random order of the newly created item which lead to confusion.

**Comment by benhaynes** [comment] 2022-03-30 13:30
I don't think anyone is tasked with this, so I have assigned to you... thank you for taking this on!! ❤️

**Comment by scolastico** [comment] 2022-03-30 13:33
np's <3

**Comment by scolastico** [comment] 2022-03-30 15:11
@benhaynes I'm currently studying the code and behavior of Directus as it handles POST/Create requests for M2A relationships. I'm not exactly sure about some names. So do I understand correctly that M2A requests are handled by the `proccessA2O` function in the [api/src/services/payload.ts](https://github.com/directus/directus/blob/6e8ab78c0eed83ba82c294ed0109178b05dadab7/api/src/services/payload.ts#L364) file?

**Comment by benhaynes** [comment] 2022-03-30 16:25
I'm afraid I won't be technical enough to help with that, but hopefully someone on @directus/team can provide some insight. :)

**Comment by robinbisping** [comment] 2022-05-13 13:12
Just to add to the other problems: When updating a row in Postgres, the modified row is placed at the bottom of the table (like removing the old row entirely and inserting a new modified row at the bottom). Thus, if the sort value of items is `null`, the order is changed each time an item is updated.

https://user-images.githubusercontent.com/4021583/168290298-bfa7a38a-c8ca-4568-aff8-6808424aa7a2.mp4

**Comment by mcharg** [comment] 2022-05-20 14:22
Is there an ETA for this fix? It's holding up our release.

**Comment by scolastico** [comment] 2022-05-20 19:35
@mcharg what do you mean exactly? The fix I suggested? (It's already written and just needs to be included in the main code) Or the bug from robinbisping? If you mean the second, I can't tell you, I've got a lot to do at the moment and I'm only doing this on a voluntary basis.

**Comment by mcharg** [comment] 2022-05-20 19:46
@scolastico I think your fix will fix our issue.

**Comment by scolastico** [comment] 2022-05-20 19:47
Yeah, then I think that it should be ready in a few days when you look into the pr and see that it has already been approved.

**Comment by YasienKashef** [comment] 2022-06-02 10:09
Hey, I'm totally new to the community and I hope I'm in the right issue discussion, but will it also fix the issue that when uploading new files (for e.g. an image gallery) the order isn't displayed directly and are only set to default null ?

The setup is as follows:

1. Create a Files Field in a collection_a.
2. On the newly created collection_a_files create a new field or sort (Input, type integer, default value 1, minimum value 1, steps 1, DO NOT allow null values) --> To my knowledge you must create a sort field, otherwise there is not sorting interface right ? Cause even if I set in the Relationship Pane the sort field to the automatically created file_id fields, it does NOT sort)
3. Set this manually created sort field as the Sort field for the collection_a_files as well as the sort field in the Relationship Pane in collection_a.
4. Now create an item in collection_a and upload some files.
5. It will display null. Only if you reorder the files it will display the order, BUT they still start with 0, even tho we defined default value as 1, minimum as 1 and step as 1.

**Closed** 2022-09-02 19:58 UTC
Labels: API, App, Bug
