### ISSUE TITLE
Deleting of a many to one field fails with error

### ISSUE THREAD

**Issue by isawk** [directus/directus#10032] opened 2021-11-24 17:21 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After creating a many to one field, deleting it fails to delete with error

### To Reproduce

Create two collections
Create a many to one related field
try to delete many to one field

### Errors Shown

{
  "errors": [
    {
      "message": "update \"directus_fields\" set \"group\" = $1 where \"group\" = $2 and \"collection\" = $3 - invalid input syntax for type integer: \"type\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v17.0.1

### What database are you using?

Postgres 13

### What browser are you using?

chrom

### What operating system are you using?

macOS 

### How are you deploying Directus?

Google Cloud App Engine

**Comment by Oreilles** [comment] 2021-11-24 22:26
Duplicate of #8655, #8675, #9092, #9194, #9896. Please follow instructions here: https://github.com/directus/directus/issues/8675#issuecomment-940629829. There's also a comment below that which should (hopefully) clarify things further 👍

**Closed** 2021-11-24 22:26 UTC
Labels: Duplicate
