### ISSUE TITLE
Graphql explorer bug

### ISSUE THREAD

**Issue by robsontenorio** [directus/directus#3796] opened 2021-01-24 03:07 UTC
1) The issue and what you expected to happen

![image](https://user-images.githubusercontent.com/118955/105620076-d5b9af80-5dd7-11eb-88b0-faef57945293.png)

2) Exact steps to reproduce this issue
    - Fresh install with docker-compose as suggested on docs.
    - First, login to admin panel
    - Then, http://localhost:8055/graphql
    - 
3) Your environment:
     - Postgres
     - Chrome 87
     - Docker

**Comment by robsontenorio** [comment] 2021-01-25 17:29
It is a random behavior... just got it working... but sometimes it crashs like screenshot.

**Comment by robsontenorio** [comment] 2021-01-26 16:00
I dont know how to reproduce exactly. It is random ... for now i am using a external graphql client like graphql-playground.

**Comment by theonlynexus** [comment] 2021-01-27 02:04
This happens to me when I try passing the auth token as a parameter in the URL, e.g.
`https://<server_host>/graphql?token=<token>`

**Comment by tstec-polypoly** [comment] 2021-01-28 14:06
I ran reproduce this with fresh docker instance of rc.32. It happens even on unauthenticated requests.

**Comment by robsontenorio** [comment] 2021-01-28 14:21
@rijkvanzanten  Maybe switch to graphql-playground as default client ? It is a nice option.

**Comment by rijkvanzanten** [comment] 2021-01-28 21:15
@tstec-polypoly how did you start the container? I just installed using the docker-compose file as per the docs, but i'm not able to reproduce this issue

**Comment by rijkvanzanten** [comment] 2021-02-24 14:35
Closed in favor of https://github.com/directus/directus/issues/4264

**Closed by rijkvanzanten** 2021-02-24 14:35 UTC
Labels: Needs More Info
