### ISSUE TITLE
Toggle folder display seems buggy

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#14892] opened 2022-08-05 21:02 UTC
### Describe the Bug

It seems the toggle doesn't work perfectly. Could be I'm trying to nav over "too fast" or something.

https://user-images.githubusercontent.com/62306630/183163046-d95b8594-b8ba-40ee-a95f-526e29d749e9.mov

### To Reproduce

watch video above

### Errors Shown

none

### What version of Directus are you using?

cloud

### What version of Node.js are you using?

cloud

### What database are you using?

cloud

### What browser are you using?

cloud

### How are you deploying Directus?

cloud

**Comment by rijkvanzanten** [comment] 2022-08-05 21:05
It remembers if you've already opened it. "Start Closed" will start closed on first load, but will remain open for the duration of your session once you've opened it 🙂

**Comment by rijkvanzanten** [comment] 2022-08-05 21:05
Oh wait scratch that, just noticed that the chevron disappeared near the end of the video

**Comment by JonathanSchndr** [comment] 2022-08-05 21:36
I think there are two errors here.
1. i always have to click twice on the folder to activate that everything should be open and lock
2. although it is open and locked, I can close it again with one click

I take a look at it

**Comment by JonathanSchndr** [comment] 2022-08-05 22:09
Testing:

1. I overlooked that there are really 3 statuses: open, closed and always open. I always thought it was a bug that you had to click twice - so point 1 has been resolved. 😃 
2. in the video you can see that the tree structure can be flipped open and closed, although it is lock. Unfortunately I could not recreate this locally or in the cloud. I think it is a loading error.

@erondpowell can you recreate the error after each reload? or does it only happen to you sometimes?

**Comment by erondpowell** [comment] 2022-08-06 00:27
Uploading Screen Recording 2022-08-05 at 7.24.50 PM.mov…

Always happens.... *well, today at least*

> just noticed that the chevron disappeared near the end of the video, that's not expected

that is happening whenever we go into the "always closed" mode... Also, I'm curious what's the point of a "always closed" button for a folder?

**Comment by JonathanSchndr** [comment] 2022-08-06 08:03
> Always happens.... *well, today at least*

Which Browser + Version and OS? I try to recreate this error.

**Comment by br41nslug** [comment] 2022-08-09 14:14
I cannot reproduce it on Chrome or Firefox (on windows) so it's presumably a problem isolated to Safari

**Comment by rijkvanzanten** [comment] 2022-08-09 14:19
<img width="282" alt="CleanShot 2022-08-09 at 10 18 44@2x" src="https://user-images.githubusercontent.com/9141017/183672913-f494f1d3-26dd-41bc-91b9-315193726102.png">

Wishful thinking for a future Directus project @erondpowell? 😉

**Comment by azrikahar** [comment] 2022-08-10 05:40
I can't seem to reproduce this either, but I'm only able to do similar tests as @br41nslug, so Safari might still potentially be the odd one out.

However seeing that the right chevron will only "disappear" when arrow placement is not set as `'after'`:

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/components/v-list-group.vue#L24-L30

and the only time arrow placement is _not_ `'after'` would be when `collection.meta?.collapse === 'locked'` (it is `'locked'` when we set it as Always Open):

https://github.com/directus/directus/blob/e9a02cdf85b81b13c850ee6aedb8ef784570b14e/app/src/modules/content/components/navigation-item.vue#L9-L10

It is odd that seemingly it's as if it's in both Always Open (so no chevron and can't open/close) and not Always Open (so we can open/close) states at once 🤔

**Comment by rijkvanzanten** [comment] 2022-08-10 14:42
> It is odd that seemingly it's as if it's in both Always Open (so no chevron and can't open/close) and not Always Open (so we can open/close) states at once 🤔

Or "Always Open" still allows you to close the folder (eg the disabled state isn't properly set)

**Comment by rijkvanzanten** [comment] 2022-08-10 15:03
@azrikahar Did some testing, I'm not able to reproduce this in Safari

**Comment by azrikahar** [comment] 2022-08-10 15:19
> @azrikahar Did some testing, I'm not able to reproduce this in Safari

We may need to chalk this up to cosmic rays then 😄 

in all seriousness, I do wonder what are the remaining avenues we have here to further attempt and reproduce this 🤔

**Comment by rijkvanzanten** [comment] 2022-08-10 15:24
Yeah.. I can't currently repro it on the cloud instance either. Lets close this for now, and circle back if we can accurately reproduce it 🙂

**Closed by rijkvanzanten** 2022-08-10 15:24 UTC
Labels: App, Bug
