### ISSUE TITLE
Searching for max length throws Integer out of range Error while default collection search

### ISSUE THREAD

**Issue by nikilmethew** [directus/directus#20731] opened 2023-12-13 10:34 UTC
### Describe the Bug

Hello everyone, 

I stumbled upon a problem while trying to search for some item value which is string type input in Directus(10.5.3).

Now i am try to search the sku value in search bar below 9 characters values are filtered and looks fine and showed like (searchResults.png). In case i type more then 9 characters getting out of range error (errorResults.png).

When i try to resolve this issue from my end i got this ticket #14638 and while trying this it fixes the error, but the values are not filtered further based on the typed values (Directus version 9.16.1 to 9.22.0).

There is  any fix for this issue scenario? It would be a great helpful for me.
Please feel free to share your thoughts.
Thank you! 

### To Reproduce

![searchResults1](https://github.com/directus/directus/assets/46815046/834cd173-5a28-4fcf-afc4-15d39514bf14)
![fieldType](https://github.com/directus/directus/assets/46815046/9d14a13e-e10c-4ef4-a74e-9f69004f3acf)
![errorResult](https://github.com/directus/directus/assets/46815046/60994965-888a-4147-8498-cfd2f3f977e5)

### Directus Version

v10.5.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2023-12-13 11:09
I believe this is a duplicate of #17946, as the error like isn't due to the _string_ SKU column itself, but the search is likely "too wide" and gets attempted on other integer column in the same table, thus causing this error to occur on PostgreSQL. We'll close this in favor of tracking it in the same ticket over there 👍

In the meantime, you may need to use [Filters](https://docs.directus.io/user-guide/content-module/filters.html) (The filter icon beside the search input) to specifically filter the items based on your SKU column.

**Closed by azrikahar** 2023-12-13 11:09 UTC
