### ISSUE TITLE
Unable to remove collection item after merging 2.4.0

### ISSUE THREAD

**Issue by AstralProgrammer** [directus/directus#2418] opened 2019-08-16 02:00 UTC
I recently merged 2.4.0 from upstream now any collection are returning an error when deleting or multi-selected.

![image](https://user-images.githubusercontent.com/8966692/63138337-aca2c600-c00c-11e9-93c8-4a5bdb64e3b2.png)

**Comment by rijkvanzanten** [comment] 2019-08-16 12:38
Duplicate of https://github.com/directus/app/issues/1934

**Closed by rijkvanzanten** 2019-08-16 12:38 UTC
