### ISSUE TITLE
Better error messages, for instance on resetting a new password

### ISSUE THREAD

**Issue by Pachat** [directus/directus#22847] opened 2024-06-25 20:21 UTC
### Describe the Improvement

Currently, if a password rule is set and the user provides a password that doesn't match the rule, the message is just `Unknown error`. A clearer message indicating what's wrong would show the user that the app knows what's going on and provide a better user experience.

**Comment by paescuj** [comment] 2024-06-26 22:38
Thanks for opening this issue! However this is a duplicate of an existing issue #21971, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #21971 for future updates.

**Closed by paescuj** 2024-06-26 22:38 UTC
