### ISSUE TITLE
Many to many interface shows emtpy template after selection

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#12070] opened 2022-03-10 10:48 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When selecting an element inside a many to many relation with a configured display-template the display stays empty.

After saving and re-visiting everything works as expected

![Bildschirmfoto 2022-03-10 um 11 46 17](https://user-images.githubusercontent.com/46492597/157646088-759f6e15-2f20-461a-9c51-44039f62bd23.png)

### To Reproduce

Create a m2m relation with a display template, create a test-item and select an relational item

### What version of Directus are you using?

9.6

### What version of Node.js are you using?

16.4

### What database are you using?

mySql8

### What browser are you using?

Chrome

### What operating system are you using?

macOs

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-03-10 11:36
Duplicate of #11963 and #10916. Currently we're consolidating and tracking this particular issue over at #10916 👍

**Closed by azrikahar** 2022-03-10 11:36 UTC
Labels: Bug (Potential)
