### ISSUE TITLE
MSSQL, error when trying to explore the table: "[INTERNAL_SERVER_ERROR] value.toISOString is not a function"

### ISSUE THREAD

**Issue by tmdoit** [directus/directus#12293] opened 2022-03-22 09:07 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to explore table data in Directus "Content" tab, I'm getting an error   "[INTERNAL_SERVER_ERROR] value.toISOString is not a function", screen attached
![Zrzut ekranu 2022-03-22 o 10 00 06](https://user-images.githubusercontent.com/85706044/159444565-1a79a83c-26e2-4fa6-ab27-bf5093810c38.png)

Are you trying to convert "TIMESTAMP" type to datetime? In MSSQL "TIMESTAMP" is eq to "ROWVERSION" (a new unique number across the database is generated and assigned to the column).

If you need some more details or tests, I'm here for you.

### To Reproduce

1. Use MSSQL
2. Create table using described schema in attached screenshot
3. Fill table with at least one record (to miss the information "No items")
4. Explore table content "Directus" > "Content" > <table name>

![Zrzut ekranu 2022-03-22 o 09 32 49](https://user-images.githubusercontent.com/85706044/159444920-d793b91e-f72b-4642-9c3e-c7046e14dceb.png)

### Errors Shown

Error from UI:
[INTERNAL_SERVER_ERROR] value.toISOString is not a function

Log error:
`directus | 08:33:23 🚨 value.toISOString is not a function directus | TypeError: value.toISOString is not a function directus | at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:236:48) directus | at PayloadService.processValues (/directus/node_modules/directus/dist/services/payload.js:142:14) directus | at runMicrotasks (<anonymous>) directus | at processTicksAndRejections (node:internal/process/task_queues:96:5) directus | at async run (/directus/node_modules/directus/dist/database/run-ast.js:42:21) directus | at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16) directus | at async ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:210:25) directus | at async /directus/node_modules/directus/dist/controllers/items.js:70:18 directus | 08:33:23 ✨ request errored GET 500 /items/Dic_Dictionaries?limit=25&fields[]=Id&fields[]=Name&fields[]=TS&fields[]=TranslationID&sort[]=Id&page=1&meta[]=filter_count&meta[]=total_count 93ms directus | 08:33:24 ✨ request completed PATCH 204 /users/me/track/page 142ms`

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MSSQL 2016 13.0.6300.2

### What browser are you using?

Brave

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker

**Comment by jaycammarano** [comment] 2022-06-14 17:54
I am not able to reproduce this. Were you using the "DateTime" option when making the timestamp column?
If you could post a schema snapshot following [this guide](https://docs.directus.io/reference/cli/#snapshot-the-data-model) that would be helpful.

**Comment by vahidreza** [comment] 2022-06-17 11:49
@jaycammarano hi, im having the same problem. in my case the column having issue has a type of 'timestamp'.
the table in my case was manually added to mssql first and then got recognized inside of directus.

[snapshot.yaml.zip](https://github.com/directus/directus/files/8927147/snapshot.yaml.zip)

<img width="1141" alt="directus error" src="https://user-images.githubusercontent.com/3737551/174292666-6774f73a-0e55-46b5-a212-172a6f338883.png">

**Comment by vahidreza** [comment] 2022-06-17 14:21
@rijkvanzanten you are right, its actually a little bit absurd the way its being used. in my case the database was created with an old lightswitch technology having a RowVersion field inside each collection so to have exactly what you described, a version which later would be used to check recent changes etc and since there are currently working clients we cannot just delete the field. so to sum-up its a version control mechanism mostly.

**Comment by vahidreza** [comment] 2022-06-28 16:16
hey @rijkvanzanten 
what's the status on this one? is there going to be any upcoming fix?

**Comment by rijkvanzanten** [comment] 2022-06-28 20:12
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by tmdoit** [comment] 2022-12-12 12:14
@rijkvanzanten I'm not using it, it's used by the ERP - I connected Directus to its database. [Here](https://learn.microsoft.com/en-us/answers/questions/238819/purpose-to-use-timestamp-datatype-in-sql-server.html) you can read about the type use case. The changed the type name from TIMESTAMP to ROWVERSION (since SQL Server 2005).

**Comment by rijkvanzanten** [comment] 2022-12-15 22:38
Linear: [ENG-265](https://linear.app/directus/issue/ENG-265/mssql-error-when-trying-to-explore-the-table-[internal-server-error])

**Comment by rijkvanzanten** [comment] 2023-06-23 03:10
Microsoft has explicitly marked the older `timestamp` syntax as outdated, and mentions it will be removed:

> The timestamp syntax is deprecated. This feature will be removed in a future version of Microsoft SQL Server. Avoid using this feature in new development work, and plan to modify applications that currently use this feature.

https://learn.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql

With that in mind, and seeing that Directus handles `datetime2` and `datetimeoffset` as expected, I'm going to consider this a Won't Fix.

**Closed by rijkvanzanten** 2023-06-23 03:10 UTC
Labels: Won't Fix
