### ISSUE TITLE
writing too fast in the items search box doesn't update the results

### ISSUE THREAD

**Issue by wc-matteo** [directus/directus#6093] opened 2021-06-05 14:40 UTC
![image](https://user-images.githubusercontent.com/10562635/120895225-4db4a380-c61c-11eb-9e46-9d4ffc0e1398.png)

it says `1 filtered item` but shows every item (pagination disappears tho). Writing slowly returns the correct results

---
```
mssql 2016 / v9.0.0-rc.73
```

**Comment by rijkvanzanten** [comment] 2021-06-05 14:42
It updates on a throttle. I'm assuming the last iteration isn't fired

**Comment by wc-matteo** [comment] 2021-06-05 14:42
should be debounced not throttled

**Comment by rijkvanzanten** [comment] 2021-06-05 16:41
Disagreed, throttle provides a better UX for this use case. Just gotta make sure that it fires the last input on a debounce

**Comment by paescuj** [comment] 2021-06-10 07:36
While I'm not able to provide a solution for this myself (not familiar with Vue), I think this needs a general review:
https://github.com/directus/directus/blob/11ea192368bbaf2fe501473ad753da4994e73e8a/app/src/composables/use-items/use-items.ts#L122-L138

The async function inside throttle is always called 3 times, even if I'm typing very fast or do a copy/paste! Is this a watch/throttle combination issue?

**Comment by paescuj** [comment] 2021-06-10 11:42
Also, I noticed that the search query is shared across the (whole?) app - the query which I typed in in the collection list was then displayed again in the list-o2m interface and even showed up again after I've cleared it and refereshed the page.

**Comment by jaycammarano** [comment] 2021-08-04 21:06
Can I get more information on the exact steps to reproduce? I wasn't able to reproduce this.

**Comment by rijkvanzanten** [comment] 2021-08-06 22:27
I think this might've been tweaked in a later version. We'll close this for now. If the problem persists, we can reopen and keep investigating 👍🏻

**Closed by rijkvanzanten** 2021-08-06 22:27 UTC
Labels: Needs More Info

**Comment by paescuj** [comment] 2021-08-09 08:31
> I think this might've been tweaked in a later version. We'll close this for now. If the problem persists, we can reopen and keep investigating 👍🏻

This still seems to be the case: https://github.com/directus/directus/issues/6093#issuecomment-858388892
Should I open up a separate issue for this?

**Comment by rijkvanzanten** [comment] 2021-08-09 13:25
@paescuj Yes please! That's unrelated to the OP 👍🏻

**Comment by wc-matteo** [comment] 2021-08-30 15:35
I'm running on rc.85 and I don't see the issue anymore. Could be related to latency, tho. Today it's very good (200-300 ms) but usually it's much worse (around 1 s).
