### ISSUE TITLE
Adding a field to a data model clears O2M fields

### ISSUE THREAD

**Issue by sebescudie** [directus/directus#10958] opened 2022-01-10 16:29 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a data model (`Product`) that has two O2M fields. I've already created a bunch of those products. 

I now want to add an `Image` field to this `Product` data model. Doing so clears all O2M fields in my existing products.

### To Reproduce

- Create a new "Product" data model that just has a "Name" text field
- Create a new "Version" data model that has a "Name" text field and a "Color" color field
- Add an O2M "Version" field to "Product"
- Create a bunch of "Product", each having a bunch of "Version"
- Edit "Product" to add an "Image" field to it
- Check your Content : your products now don't have "Version" items anymore. The items still exist in the DB but are not linked anymore. The raw value shows an empty array.

Here's a repro video :

https://user-images.githubusercontent.com/8690430/148801808-446a41eb-c726-4f0f-8821-005772fdf5f9.mp4

### Errors Shown

No

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.0

### What database are you using?

SQLite

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment] 2022-01-10 16:51
Duplicate of https://github.com/directus/directus/issues/10842

**Closed by rijkvanzanten** 2022-01-10 16:51 UTC
Labels: Bug (Potential)
