### ISSUE TITLE
URL stopped working for deployment behind proxy

### ISSUE THREAD

**Issue by aidenfoxx** [directus/directus#6250] opened 2021-06-14 11:09 UTC
We have Directus deployed behind a proxy which exposes Directus via the domain "http://ournetwork/directus-cms". This worked correctly in Directus rc74 and below when the `PUBLIC_URL` was set to `/directus-cms`.

This stopped working with version rc75, which does not prepend the `PUBLIC_URL` for assets in the admin. Directus tries to get assets on "http://ournetwork/admin/assets/logo-light.svg" which 404s. On previous versions it would query "http://ournetwork/directus-cms/admin/assets/logo-light.svg"

Our env:
- Directus rc75
- Docker/linux
- Nginx
- Any browser

**Comment by nickrum** [comment] 2021-06-14 12:19
Duplicate of #6192

**Closed by nickrum** 2021-06-14 12:19 UTC
