### ISSUE TITLE
Filters reset not working properly

### ISSUE THREAD

**Issue by peremp** [directus/directus#1710] opened 2017-07-26 09:45 UTC
## Version Info
  - Directus version and branch: 6.4.0 devel

## Steps to Reproduce
 1. Enter to a table list:

![1](https://user-images.githubusercontent.com/20085260/28614671-ec39115e-71f6-11e7-95ce-8462a1d376b3.png)

 2. Write something to filter. The filter is applied and the table list updated correctly:

![2](https://user-images.githubusercontent.com/20085260/28614795-4a67eb6a-71f7-11e7-8a5a-b56f06f7ffd3.png)

 3. Remove the filter. The filter is removed and the table list updated correctly:

![3](https://user-images.githubusercontent.com/20085260/28614833-6bdf9342-71f7-11e7-8567-f7ff3c0ee1bb.png)

 4. Click on some column to order the rows in the table.

## Expected behavior:
The items are ordered.

## Current behavior:
The order is applied but the items that appear are the same that appeared when the filter was active:

![4](https://user-images.githubusercontent.com/20085260/28614994-ec41738e-71f7-11e7-9217-ee0acd1b6e49.png)

**Comment by benhaynes** [comment] 2017-07-26 16:32
Hey @peremp – no one here is able to reproduce this one.

Can you send over more detailed steps? Are you clicking the "X" to clear the filter or deleting the text manually? Do you have a schema we can try with?

Also, when you get the incorrectly filtered listing, could you check your user's `directus_preferences` for that table and paste it here? I wonder if this is actually a bug in the code or some weird caching issue.

Thanks!

**Comment by benhaynes** [comment] 2017-08-06 15:09
If anyone is experiencing this issue please let us know (exact commit and steps to reproduce) – it should be easy to fix but we are unable to replicate the problem.

In the meantime, we're closing this because it's been a few weeks with no confirmation.

**Comment by peremp** [comment] 2017-08-21 15:15
Hey, just tested it on develop latest (98cfd46), and still happening to me.
Sorry for the delay, I was on vacation.

**Comment by benhaynes** [comment] 2017-08-21 20:12
Hey @peremp – thanks for checking back in! We've had several issues persist due to cache... even after it's been cleared. Could you give it a try in a different browser or incognito just to be sure?

Appreciate the help!

**Comment by peremp** [comment] 2017-08-22 07:57
Still happens. Tested on Firefox and Chrome.

I think that this issue is not related to https://github.com/directus/directus/issues/1708, because this happens even if I disable the cache.

I'll try to create an schema to reproduce this issue.

**Comment by benhaynes** [comment] 2017-08-25 19:45
Any luck with a schema @peremp? It'd be great to squash this bug...

**Comment by benhaynes** [comment] 2017-08-30 14:28
Also @peremp, a screencast might be good too so we can see exactly what you're seeing. Thank you very much for the help in getting this resolved!

**Comment by benhaynes** [comment] 2017-09-04 18:25
OK – we'll close this as "can not replicate" until we hear back.

**Closed by benhaynes** 2017-09-04 18:25 UTC
Labels: 4. Minor, 6. In-Progress, Can Not Duplicate
