### ISSUE TITLE
7.9.0 broke some functionality in the Backend

### ISSUE THREAD

**Issue by nashtu3000** [directus/directus#2421] opened 2019-08-21 21:25 UTC
Hello, it seems that the latest update has broken functionality of viewing some of the tables. Strangely, not all of them exhibit this error.

This is what I can see in the console:
```
chunk-vendors.53846b32.js:5 TypeError: Cannot read property 'field' of undefined
    at a.primaryKeyField (app.daaf2051.js:1)
    at nr.get (chunk-vendors.53846b32.js:5)
    at nr.evaluate (chunk-vendors.53846b32.js:5)
    at a.primaryKeyField (chunk-vendors.53846b32.js:5)
    at a.viewQuery (app.daaf2051.js:1)
    at nr.get (chunk-vendors.53846b32.js:5)
    at nr.evaluate (chunk-vendors.53846b32.js:5)
    at a.viewQuery (chunk-vendors.53846b32.js:5)
    at a.rd (app.daaf2051.js:1)
    at a.e._render (chunk-vendors.53846b32.js:5)
```
And a screenshot with the error: https://tppr.me/r8uJt

I have already run the update database script found in the admin.

**Comment by benhaynes** [comment] 2019-08-21 22:20
@rijkvanzanten @bjgajjar  — API I assume? Or could it be a config issue?

**Comment by nashtu3000** [comment] 2019-08-22 08:39
What can I do? I updated my live server and I have a project that's bound to start soon, and I'm afraid that I can't fix this until then :/

**Comment by nashtu3000** [comment] 2019-08-22 11:47
I have reverted to 190729A and it's working ok now. Will update again after this bug is squashed :-)

**Comment by bjgajjar** [comment] 2019-08-22 11:57
@nashtu3000 - It will be a great help to check this issue if you can send over a SQL dump of your setup. If it's private you can send over Slack

https://directus.chat

> API I assume

Need to verify once :)

**Comment by rijkvanzanten** [comment] 2019-08-22 14:10
Duplicate of https://github.com/directus/app/issues/1939

**Closed by rijkvanzanten** 2019-08-22 14:10 UTC
Labels: transfer
