### ISSUE TITLE
Multi-Select Dropdown with JSON does not permit filtering in the admin app 

### ISSUE THREAD

**Issue by m0rtis0** [directus/directus#12501] opened 2022-03-31 10:51 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When creating a new JSON Multi-Select Dropdown via the admin app and the trying to filter that field by anything no options are displayed except 'is null' or 'is not null'
![image](https://user-images.githubusercontent.com/65440078/161038397-bc6caf40-a145-45a6-a678-b39ec04f7db6.png)

### To Reproduce

- Create new Collection
- Create new Multi-Select Dropdown
- Try to filter in the Admin App

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

v14.17.5

### What database are you using?

Postgres 13.5

### What browser are you using?

Brave

### What operating system are you using?

Arch Linux

### How are you deploying Directus?

Remote Linux Server / Baremetal

**Comment by rijkvanzanten** [comment] 2022-04-01 17:12
Directus currently isn't capable of searching in the stored value of JSON fields, see https://github.com/directus/directus/discussions/7277 for the open feature request about that 👍🏻

Duplicate of https://github.com/directus/directus/issues/12496

**Closed by rijkvanzanten** 2022-04-01 17:12 UTC
Labels: Bug (Potential)
