### ISSUE TITLE
Can't manipulate folders in File Library anymore

### ISSUE THREAD

**Issue by andy1li** [directus/directus#15425] opened 2022-09-06 13:30 UTC
### Describe the Bug

Right-clicking folders doesn't bring up context menus anymore in the File Library.

### To Reproduce

Try right-clicking any folder in the File Library.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/1450947/188646947-4743a79e-df80-4a0f-b02f-a2175ef46327.png">

### Errors Shown

```
Uncaught TypeError: e.activate is not a function
    at HTMLLIElement.<anonymous> (index.a6745321.entry.js:1551:54863)
```

<img width="652" alt="image" src="https://user-images.githubusercontent.com/1450947/188647478-a372c86f-99a4-4633-9f9e-7c4bc0f7a007.png">

### What version of Directus are you using?

9.17.0

### What version of Node.js are you using?

16.16

### What database are you using?

mysql 8.0.28

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by br41nslug** [comment] 2022-09-06 13:32
Duplicate of https://github.com/directus/directus/issues/15375, and is fixed in 9.17.1 by https://github.com/directus/directus/pull/15376 😄

**Closed by br41nslug** 2022-09-06 13:32 UTC
Labels: Duplicate
