### ISSUE TITLE
Editing m2a relation broken in UI

### ISSUE THREAD

**Issue by helge000** [directus/directus#21984] opened 2024-03-26 17:19 UTC
### Describe the Bug

Currently it is not possible to reliably edit m2a relations via the web ui:

- Impossible to remove an existing relation
- Relations are added as duplicate 

[Screen recording 2024-03-26 18.09.09.webm](https://github.com/directus/directus/assets/13696924/6221e57f-e0d7-4d2e-91c9-177ed2f8f4c1)

Workaround:
- Use API
- Update directus realtions using SQL: 
   - `update directus_relations SET one_allowed_collections='<collection1>,<collection2>,<..>' where id=XX;`

### To Reproduce

1. Create a new m2a field and some collections
2. Edit the relations
3. Save
4. Try to remove or add more relations

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-03-26 17:29
Seems to indeed be a strange app error with selecting the array of many-to-any collections (renamed the mentions of m2m as that relation does not have this issue)

**Comment by paescuj** [comment] 2024-03-26 17:40
This is a duplicate of #21848

**Closed by paescuj** 2024-03-26 17:40 UTC
Labels: :cake: Bug, :cake: Regression
