### ISSUE TITLE
Unable to create Flow - ID generation/input validation bug 

### ISSUE THREAD

**Issue by colemahatmccreary** [directus/directus#13850] opened 2022-06-11 18:57 UTC
### Describe the Bug

First, congrats on launching Flows. Massive improvement that I imagine will convince a ton of people to start shifting to Directus.

In trying to create my first flow, I get an error stating that I didn't provide an ID value. There is no input field for ID provided so something must be off under the hood.

I'm currently using Standard Cloud, version 9.12.1

### To Reproduce

1. Select "Create Flow": provide name, description. Click continue
2. Select "non-blocking event hook on items.create" as the trigger type. Click continue.
3. See below for the error message

### Errors Shown

<img width="555" alt="Screen Shot 2022-06-11 at 11 48 43 AM" src="https://user-images.githubusercontent.com/40645344/173201319-6f87ed32-e586-4924-92b3-cb5ad3d3f457.png">

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

Whatever Standard Cloud uses

### What database are you using?

Whatever Standard Cloud uses

### What browser are you using?

Chrome

### How are you deploying Directus?

Standard Cloud

**Comment by colemahatmccreary** [comment] 2022-06-12 00:44
Just did some troubleshooting in the network tab/docs: looks the app's request is going to /flows?fields[]=id instead of the plain /flows endpoint

**Comment by azrikahar** [comment] 2022-06-13 04:55
I can't seem to reproduce this both locally and with a Community Cloud project. @joselcvarela could this somehow be specific to this project? 

@colemahatmccreary it would also be helpful if you can try and check whether this is present in a local installation (or any other projects you may have).

> Just did some troubleshooting in the network tab/docs: looks the app's request is going to /flows?fields[]=id instead of the plain /flows endpoint

It is correct (specifically POST request to `/flows`), it's just that the additional `fields` query param allows us to specify the returned fields when we successfully create a record, similar to when we are using `fields` for GET requests in general 👍

**Comment by joselcvarela** [comment] 2022-06-13 06:20
@colemahatmccreary since this seems to be only happening with your project, please head to our website https://directus.io and start a new chat so we can help you further. If you prefer contact via email, you can also use info@directus.io 👍

@azrikahar I also tested in another Cloud project the steps OP mentioned and didn't have the error mentioned. Feel free to close this one.

**Comment by azrikahar** [comment] 2022-06-13 06:23
Thanks for the prompt confirmation @joselcvarela!

**Closed by azrikahar** 2022-06-13 06:23 UTC
Labels: Needs More Info, Can't Reproduce
