### ISSUE TITLE
"Update files date fields" migration failed on MySQL

### ISSUE THREAD

**Issue by miauyo** [directus/directus#23647] opened 2024-09-12 09:05 UTC
### Describe the Bug

When I use mysql8 as database, I can't complete the data migration for Directus

### To Reproduce

Error: alter table `directus_files` add `uploaded_on` timestamp - Invalid default value for 'uploaded_on'
directus-1  |     at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.11.0/node_modules/mysql2/lib/packets/packet.js:738:17)
directus-1  |     at Query.execute (/directus/node_modules/.pnpm/mysql2@3.11.0/node_modules/mysql2/lib/commands/command.js:29:26)
directus-1  |     at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.11.0/node_modules/mysql2/lib/connection.js:481:34)
directus-1  |     at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.11.0/node_modules/mysql2/lib/connection.js:97:12)
directus-1  |     at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.11.0/node_modules/mysql2/lib/packet_parser.js:75:16)
directus-1  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.11.0/node_modules/mysql2/lib/connection.js:104:25)
directus-1  |     at Socket.emit (node:events:517:28)
directus-1  |     at addChunk (node:internal/streams/readable:368:12)
directus-1  |     at readableAddChunk (node:internal/streams/readable:341:9)
directus-1  |     at Readable.push (node:internal/streams/readable:278:10) {
directus-1  |   code: 'ER_INVALID_DEFAULT',
directus-1  |   errno: 1067,
directus-1  |   sqlState: '42000',
directus-1  |   sqlMessage: "Invalid default value for 'uploaded_on'",
directus-1  |   sql: 'alter table `directus_files` add `uploaded_on` timestamp'
directus-1  | }

### Directus Version

11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql8

**Comment by paescuj** [comment] 2024-09-12 09:15
This seems to be a duplicate of #23390. Please see https://github.com/directus/directus/issues/23390#issuecomment-2311833688 for a possible solution.

Nevertheless, I'll leave the issue open until further notice to see whether we can either adjust the migration or otherwise leave a notice about SQL Modes in the documentation.

**Closed** 2024-09-13 02:16 UTC
Labels: MySQL
