### ISSUE TITLE
Non-Nullable string is implicitly required

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#18596] opened 2023-05-14 22:55 UTC
### Describe the Bug

I have a `Pages` collection and each field has a `unique string field` called `slug`.
I expect this field also to be able to accept an `empty string` to specify a `home page`.

Since it is specified as `Non-Nullable` I expect the default value to be an empty string.
But when I want to submit a page without filling out the `slug` field, I get the error, that filling out this field is `required`.
But I don't specified this field as `required`.
So shouldn't the default behaviour now be that this field gets submitted with an empty string instead of getting an error?

### Alternative Solutions

I also tried to solve this by allowing the field to be `Nullable`.
But the problem here is that the `unique` property does not care about `Nullable` fields.
This allowed me to create many fields with a `null` slug.
But of course the field with a `null` slug should only be the home page.

### To Reproduce

1. Create a collection
2. Create a string field and specify it as `non-nullable`, `unique`.
3. Try to create an instance of that collection and keep the string field empty
4. It will not work.

### Directus Version

v10.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-05-16 13:55
> So shouldn't the default behaviour now be that this field gets submitted with an empty string instead of getting an error?

Ohh this quickly reaches opinions-territory doesn't it 😬 

If you set that a field isn't allowed to be "nothing" (null), and you don't add anything to the field, I personally would expect that to fail, as you didn't add anything to satisfy that "not nothing" constraint 🤔

**Comment by br41nslug** [comment] 2023-05-16 13:57
Reading a little between the lines here but sounds like the underlying issue here is "It is impossible to submit an empty string as default value"? 🤔

**Comment by rijkvanzanten** [comment] 2023-05-16 13:59
> Reading a little between the lines here but sounds like the underlying issue here is "It is impossible to submit an empty string as default value"? 🤔

I read this as the core "issue" (emphasis mine): 

> Since it is specified as Non-Nullable I **expect the default value to be an empty string**.

You should still be able to set an empty string as the explicit default, and therefore make this setup work as expected, but I'm not sure if I agree that the default value should implicitly be an empty string for text-based columns that are marked not null 🤔

**Comment by LasseRosenow** [comment] 2023-05-16 17:01
I don't mind on what you decide on the default behaviour :)

I only hope there would then be a way to make my use-case work, allowing me to have empty fields that are still always unique.

> You should still be able to set an empty string as the explicit default, and therefore make this setup work as expected
Do you mean this is possible as of now? Because I cannot see how to specify a empty string as the default value, because how do I set an empty string? If the default value field is empty, it is set to null 🤔

**Comment by LasseRosenow** [comment] 2023-05-16 17:04
I think to make it more easy the best solution is some checkmark or toggle to set what an empty field means, either null or empty string in the interface

**Comment by rijkvanzanten** [comment] 2023-05-16 17:53
> hope there would then be a way to make my use-case work, allowing me to have empty fields that are still always unique.

Oh this is an even trickier example! Cause `'' === ''`, so therefore the values aren't unique if they're kept empty 👀  (unique is currently done through a database unique index)

**Comment by LasseRosenow** [comment] 2023-05-16 18:08
> Oh this is an even trickier example! Cause '' === '', so therefore the values aren't unique if they're kept empty 👀

To make sure we don't misunderstand each other. By making them unique of course I want to not allow 2 entries that both have an empty value. So `'' === ''` This is good. I only want to allow one `home-page` of course If I go by the `slug` example I made

**Comment by LasseRosenow** [comment] 2023-05-16 18:09
Or do you mean, that the database unique query doesn't notice that there are 2 entries that both are empty string?

**Comment by rijkvanzanten** [comment] 2023-05-16 18:10
Ohh OK so just to confirm, in your use case there would only ever be one item with the value `''` saved?

**Comment by LasseRosenow** [comment] 2023-05-16 18:39
Yes exactly, this is what I would expect from a "unique" field, every possible value only once, including "empty" values :)

**Comment by rijkvanzanten** [comment] 2023-05-30 20:51
I'm gonna close this for now, as things are technically working as intended / expected, even though it might not be the ideal solution long term. Happy to continue this discussion in a new feature request 🙂

**Closed by rijkvanzanten** 2023-05-30 20:51 UTC
Labels: Package: @directus/app
