### ISSUE TITLE
Admin dashboard error "RECORD_NOT_UNIQUE: Field 'resolve' has to be unique." when adding new operations to middle of flow

### ISSUE THREAD

**Issue by paulleduc** [directus/directus#15486] opened 2022-09-08 21:12 UTC
### Describe the Bug

I get a "RECORD_NOT_UNIQUE" "Field \"resolve\" has to be unique." admin dashboard error when trying to update then save flows a lot of the time.

I think it may be related to unlinking existing operations, and linking new ones. The error happens when the Save button is clicked on the flow after making some edits.

A workaround that works for me: After you encounter the error, remove the links made to any new oeprations then save. It will save successfully, but your flow will now be broken. Click edit again and add the links back, then save again. It will save this time for some reason. That's why it probably has to do with linking new operations rather than existing ones only.

### To Reproduce

1. Create a new flow with a few linked operations and save it.
2. Edit the flow
3. Unlink one or more of the operations from each other
4. Add one or more new operations to the middle somewhere
5. Link all of the operations in sequence again
6. Click Save, this triggers the error

### Errors Shown

```
{
  "errors": [
    {
      "message": "Field \"resolve\" has to be unique.",
      "extensions": {
        "code": "RECORD_NOT_UNIQUE",
        "collection": "directus_operations",
        "field": "resolve",
        "invalid": "f77acc75-28aa-4149-a71f-92bf2de95a35"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

Directus Cloud

### What database are you using?

Directus Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment] 2022-09-08 22:20
Thanks for opening this issue! However this is a duplicate of an existing issue #14185, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #14185 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2022-09-08 22:20 UTC
