### ISSUE TITLE
Sleep flow operation does not accept operation_key as value

### ISSUE THREAD

**Issue by haniefss** [directus/directus#16949] opened 2022-12-29 04:58 UTC
### Describe the Bug

Hi, I tried to create a random sleep duration by generating some random integer, let's call this `random_int`. I use `{{random_int}}` as value (`milliseconds`) in the subsequent Sleep operation, and when I save the flow the `milliseconds` value turns to `null` instead of `{{random_int}}`. This way we can't use dynamic value for the Sleep operation. I think this is a bug because other operations accept {{operationKey}} as input.

### To Reproduce

1. Generate random integer in a Run Script operation.
2. Use operation key from # 1 as value (milliseconds) in Sleep operation.

### Errors Shown

n/a

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

16.17.1

### What database are you using?

Mysql 8

### What browser are you using?

Chrome

### How are you deploying Directus?

locally with remote db

**Comment by azrikahar** [comment] 2022-12-29 05:28
> and when I save the flow the milliseconds value turns to null instead of {{random_int}}

Can you share how are you inputting or saving the `{{random_int}}` in the Sleep operation's Milliseconds field? Did you click on the `{}` button beside Milliseconds field's label? Here's my attempt at reproducing this but it seems to work without any issue:

https://user-images.githubusercontent.com/42867097/209906946-cac94b25-b32d-4cdf-bab4-69cba68c032f.mp4

Closing this for now, but will re-open if this is actually reproducible reliably 👍

Note that the terminal output of `{ milliseconds: X }` is because I modified the source code for demo purpose, where I added `console.log({ milliseconds })` in the sleep operation:

https://github.com/directus/directus/blob/dc1a218c58110fc28ec58a43b817069ec72df173/api/src/operations/sleep/index.ts#L10-L12

**Closed by azrikahar** 2022-12-29 05:28 UTC
Labels: Can't Reproduce

**Comment by haniefss** [comment] 2022-12-29 05:37
> Did you click on the `{}` button beside Milliseconds field's label?

Aha that does it! I should have pay more attention. Thanks @azrikahar
