### ISSUE TITLE
When creating an extension inside a bundle using the cli, from the package.json the script session disappear.

### ISSUE THREAD

**Issue by brainrepo** [directus/directus#17578] opened 2023-02-20 22:16 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When adding a new extension inside an extension bundle the adding procedure deletes the script section from the package.json

### To Reproduce

1. Create a bundle extension using the cli
2. The package.json contains the script section
3. inside the extension folder, run `npm run add`
4. Create a new extension
5. The package.json does not contain the script section

### Hosting Strategy

Self-Hosted (Custom)

**Comment by brainrepo** [comment] 2023-02-20 22:17
I am happy to do a PR for fixing this bug.

**Comment by paescuj** [comment] 2023-02-21 08:43
Thanks for opening this issue! However this is a duplicate of an existing issue #17152, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #17152 has been fixed by #17179 which will be available with the next release.

**Closed by paescuj** 2023-02-21 08:43 UTC
