### ISSUE TITLE
Graphql api create input type requires id

### ISSUE THREAD

**Issue by shkreios** [directus/directus#5859] opened 2021-05-24 17:10 UTC
# Bug
The current GraphQL requires the input argument to include the `id` field, i.e. the example from docs [here](https://docs.directus.io/reference/api/items/#returns-4) does not work as the graphql validations fails. 
I think as the rest API does not require it it's just a misconfigured type. 
## Expected
```graphql
mutation {
	create_articles_items(
		data: [
			{ title: "Hello world!", body: "This is our first article" }
			{ title: "Hello again, world!", body: "This is our second article" }
		]
	) {
		id
		title
	}
}
```
## Error
```json
{
  "errors": [
    {
      "message": "GraphQL validation error.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_EXCEPTION",
        "graphqlErrors": [
          {
            "message": "Field \"create_articles_items.id\" of required type \"String!\" was not provided.",
            "locations": [
              {
                "line": 4,
                "column": 7
              }
            ]
          }
        ]
      }
    }
  ]
}  
```
## Actual
```graphql
mutation {
	create_articles_items(
		data: [
			{ id: 1, title: "Hello world!", body: "This is our first article" }
			{ id: 2, title: "Hello again, world!", body: "This is our second article" }
		]
	) {
		id
		title
	}
}
```
Thanks for thus awesome project.
Regards,
Simon 

---

### Project details
Directus Version: 9.0.0-rc.69
Environment: production
OS: Linux 5.4.0-73-generic
Node: 14.16.1

**Comment by rijkvanzanten** [comment] 2021-05-24 17:12
Duplicate of https://github.com/directus/directus/issues/5723

**Closed by rijkvanzanten** 2021-05-24 17:12 UTC
