### ISSUE TITLE
Unknown column 'NaN' in 'where clause' in nested permissions

### ISSUE THREAD

**Issue by micheleferraro** [directus/directus#14209] opened 2022-06-30 09:10 UTC
### Describe the Bug

After upgrading to 9.13 I got this error calling REST APIs.
Response is a generic "Unauthorized" message, log shows the attached exception.
This was working in 9.12.2 (and it works again after downgrading)
 

### To Reproduce

- upgrade to 9.13

### Errors Shown

![error](https://user-images.githubusercontent.com/39918028/176638590-440681be-102b-4d04-91bf-5578dfdad578.png)

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

14.19.3

### What database are you using?

MariaDB 10.5.15

### What browser are you using?

Chrome

### How are you deploying Directus?

manually

**Comment by licitdev** [comment] 2022-06-30 10:31
@micheleferraro Please assist to provide a minimal reproducible example for us to triage the issue. We will require information such as the data structure and the request body of your API request. Thank you.

**Comment by jdoig** [comment] 2022-06-30 10:56
I'm getting a NaN issue in a where cause also. 

I've documented as a comment on this bug as it's impacting a collection of ours that is already effected by an existing bug and the two might be related https://github.com/directus/directus/issues/13107
Also that bug was successfully reproduced so reproducing it may also reproduce this one when Direcuts 9.13 is used (though the collection structure may have changed in some minor way since I first logged the bug)

**Comment by micheleferraro** [comment] 2022-06-30 11:02
I found what caused my problem, but I think it may be worth a look.
Looks like the problem was in a filter added for a specific role.
I have this data structure:

- Collection A with a M2O relation with Users
- Collection B with a M2M relation with A

I had filters working in 9.12.2 defined like this:

- Collection A: `A -> Users -> ID equals $CURRENT_USER`
- Collection B: `B ID -> A -> Users -> ID equals $CURRENT_USER`

Defining filters without the last ID works in 9.13:

- Collection A: `A -> Users equals $CURRENT_USER`
- Collection B: `B ID -> A -> Users equals $CURRENT_USER`

I'm not sure if this was a bug and it's now solved or if it is a new bug...

**Comment by jdoig** [comment] 2022-06-30 11:16
Amazing thank you @micheleferraro this also fixes it for me. 
I'd rather it was also fixed in the code though as I don't want to have to go and update all the permissions across our environments :sweat_smile: it also seems a really easy bug for someone to fall over in the future when configuring permissions.

**Comment by Tapematch** [comment] 2022-07-12 13:30
I created a small dump of my Postgres database for easier troubleshooting.
It has the previously mentioned data structure and one test role.
That role has read permissions for collection B with the faulty filter and one user:

> test@example.com
> password: 12345678
> token: Xw9CCp3ljE9TWBSOgo48ohjSo8O4Dqwk

Retrieving items from collection b throws the following error:

```
error select "b"."id" from "b" where (("b"."id" in (select "b_a"."b_id" as "b_id" from "b_a" left join "a" as "ztpjh" on "b_a"."a_id" = "ztpjh"."id" left join "a_directus_users" as "ulnzn" on "ztpjh"."id" = "ulnzn"."a_id" left join "directus_users" as "wwwrz" on "ulnzn"."directus_users_id" = "wwwrz"."id" where "b_a"."b_id" is not null and "wwwrz"."id" = $1))) order by "b"."id" asc limit $2 - ungültige Eingabesyntax für Typ uuid: »NaN« 
error: select "b"."id" from "b" where (("b"."id" in (select "b_a"."b_id" as "b_id" from "b_a" left join "a" as "ztpjh" on "b_a"."a_id" = "ztpjh"."id" left join "a_directus_users" as "ulnzn" on "ztpjh"."id" = "ulnzn"."a_id" left join "directus_users" as "wwwrz" on "ulnzn"."directus_users_id" = "wwwrz"."id" where "b_a"."b_id" is not null and "wwwrz"."id" = $1))) order by "b"."id" asc limit $2 - ungültige Eingabesyntax für Typ uuid: »NaN«
    at Parser.parseErrorMessage (/home/philtaubert/Projekte/Tools/example-project/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/philtaubert/Projekte/Tools/example-project/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/philtaubert/Projekte/Tools/example-project/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/philtaubert/Projekte/Tools/example-project/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
```
curl --location --request GET 'http://localhost:8055/items/b' \
--header 'Authorization: Bearer Xw9CCp3ljE9TWBSOgo48ohjSo8O4Dqwk'
```

**Closed** 2022-07-21 18:37 UTC
Labels: API, Bug

**Comment by maxbritto** [comment] 2022-08-10 15:53
On 9.15.1 I have a similar issue, when using the API and filtering M2M relationship objects.
Example : 
Collection `Sessions` having a property `users` as an M2M to system collection `directus_users`.

When using this filter via the API : 
```json
{ "users": { "id" : { "_eq" : "2dd3e908-836b-4733-aaa9-3fa72c03d9a1" }}}
```
I get this error : 
```sql
select `Sessions`.`id`, `Sessions`.`start_date`, `Sessions`.`session_type`, `Sessions`.`max_user_count` from `Sessions` where `Sessions`.`id` in (select `Sessions_directus_users`.`Sessions_id` as `Sessions_id` from `Sessions_directus_users` where `Sessions_directus_users`.`Sessions_id` is not null and `Sessions_directus_users`.`id` = NaN) order by `Sessions`.`id` asc limit 100 

Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
```

Am I mistaking when thinking this is the same issue ?

Thanks

**Comment by rijkvanzanten** [comment] 2022-08-10 16:54
@maxbritto looks like that's https://github.com/directus/directus/issues/14944 🙂

**Comment by licitdev** [comment] 2022-08-12 02:26
@maxbritto As you're filtering on an `M2M` collection, the `id` that you're filtering on is from the junction table `Sessions_directus_users` which is an `integer`. Hence the `uuid` passed into the filter, results in the `NaN` when the filter is parsed.

Please refer to the following filter. Thanks!

```json
{ "users": { "directus_users_id": { "id" : { "_eq" : "2dd3e908-836b-4733-aaa9-3fa72c03d9a1" }}}}
```

**Comment by maxbritto** [comment] 2022-08-12 12:34
@licitdev : Thanks! Is this a workaround until the bug is fixed or is it the correct way to use filters on M2M ?

**Comment by licitdev** [comment] 2022-08-12 12:44
@maxbritto It is the correct way to use filters on M2M. Your filter was filtering for the `id` in the junction table.

**Comment by maxbritto** [comment] 2022-08-12 13:18
ok I did not know that, sorry about the confusion. I've created a PR to clarify the docs to help future users : https://github.com/directus/docs/pull/88
