### ISSUE TITLE
count filter broken after update to 9.15.0

### ISSUE THREAD

**Issue by eikaramba** [directus/directus#14882] opened 2022-08-05 14:24 UTC
### Describe the Bug

on 9.14.4 it was working, after upgrading and migrating to 9.15.0 counting a M2M relationship results in an server error

### To Reproduce

this is my query, but it also is not working in the Admin App (see screenshot below)
```js
await directus.items('foods').readByQuery({ fields:["id","name","date_created","ingredients.food","ingredients.food.name","ingredients.food.id","ingredients.food.translations.name","translations.name"],
        deep:{"translations":{"_filter":{"languages_id":{"_eq":$locale}}},
                               "ingredients":{"food":{"translations":{"_filter":{"languages_id":{"_eq":$locale}}}}}
             },
        filter:{
            _and:[
                {"count(ingredients)":{_neq:0}},
                {isCopy:{_eq:false}}
            ]},
            limit: -1 });
```

### Errors Shown

![grafik](https://user-images.githubusercontent.com/1320525/183097552-778edf6b-57bf-4ff5-bee9-072fc44e3ff7.png)

### What version of Directus are you using?

9.15.0

### What version of Node.js are you using?

16

### What database are you using?

sqlite

### What browser are you using?

FF

### How are you deploying Directus?

local

**Comment by eikaramba** [comment] 2022-08-05 14:31
this was introduced due to https://github.com/directus/directus/pull/14829

**Comment by br41nslug** [comment] 2022-08-05 14:32
I believe this to be a duplicate of #14780

**Comment by eikaramba** [comment] 2022-08-05 14:34
i don't think so as the number is not wrong, instead here we try to reference a undefined variable.

**Comment by br41nslug** [comment] 2022-08-05 14:34
yeah realized i was wrong after double checking 😄

**Comment by sevetseh28** [comment] 2022-08-05 14:45
I am getting 500 Resp code when doing a SEARCH with a field that doesn't exist. I would expect the response code to be 400. See the screenshot and logs:

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/13895313/183101364-55999c77-9797-41d2-9833-85b9fa5b89eb.png">

```typescript
14:38:10 ✨ request errored SEARCH 500 /items/Task 28ms
2022-08-05T14:38:26.018163600Z 14:38:26 🚨 Cannot read properties of undefined (reading 'type') 
2022-08-05T14:38:26.018379300Z TypeError: Cannot read properties of undefined (reading 'type')
2022-08-05T14:38:26.018421500Z     at addWhereClauses (/directus/node_modules/directus/dist/utils/apply-query.js:218:97)
2022-08-05T14:38:26.018454600Z     at applyFilter (/directus/node_modules/directus/dist/utils/apply-query.js:156:5)
2022-08-05T14:38:26.018512800Z     at applyQuery (/directus/node_modules/directus/dist/utils/apply-query.js:43:9)
2022-08-05T14:38:26.018548300Z     at getDBQuery (/directus/node_modules/directus/dist/database/run-ast.js:161:38)
2022-08-05T14:38:26.018576800Z     at run (/directus/node_modules/directus/dist/database/run-ast.js:36:25)
2022-08-05T14:38:26.018645900Z     at runMicrotasks (<anonymous>)
2022-08-05T14:38:26.018674000Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-05T14:38:26.018701100Z     at async runAST (/directus/node_modules/directus/dist/database/run-ast.js:30:16)
2022-08-05T14:38:26.018767800Z     at async ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:216:25)
2022-08-05T14:38:26.018794000Z     at async /directus/node_modules/directus/dist/controllers/items.js:70:18
```

**Comment by br41nslug** [comment] 2022-08-05 14:49
I believe you're running into 2 problems here @eikaramba 
- the count function is not functioning properly (im sure i've seen that as issue somewhere)
- because count is not processed properly it runs into a "non existing field" exception which is throwing this `cannot access type` error

**Closed** 2022-08-05 15:56 UTC
Labels: API, Bug
