### ISSUE TITLE
Folder Translations edit UI

### ISSUE THREAD

**Issue by jakubbartel** [directus/directus#11271] opened 2022-01-25 21:11 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Folder (Data Model) can't be renamed by Translation because UI shows a separate edit modal under the folder edit modal.

### To Reproduce

Create a new Folder in Data Model > Edit folder > Create new translation > click on the new translation's box to fill in a name > [side modal appears from the right and is placed under the folder edit modal, so no interaction is possible]

### Errors Shown

No

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.2

### What database are you using?

Directus Cloud

### What browser are you using?

Chrome

### What operating system are you using?

Linux 4.14.252-195.483.amzn2.x86_64

### How are you deploying Directus?

Directus Cloud

**Comment by rijkvanzanten** [comment] 2022-01-25 21:22
Duplicate of https://github.com/directus/directus/issues/10892

**Comment by jakubbartel** [comment] 2022-01-25 21:22
Sorry, it's a duplicate #11078 I accidentally searched just in open issues.

**Closed by rijkvanzanten** 2022-01-25 21:22 UTC
Labels: Bug (Potential)

**Comment by rijkvanzanten** [comment] 2022-01-25 21:24
No problem! #11078 itself was actually also a duplicate of #10892 😄
