### ISSUE TITLE
[INVALID PAYLOAD] Collection doesn't exist

### ISSUE THREAD

**Issue by ele-cren** [directus/directus#10627] opened 2021-12-21 12:30 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It is impossible to use the CMS because I can't create any collection.
When creating a collection, an error occurs.
It creates a folder instead of a collection and a "Database only" collection.

I tried to drop the database, delete the directus project and create everything from scratch but it doesn't change anything.
I had no problem 2 days ago.

### To Reproduce

Create a collection from the user interface

### Errors Shown

`{
  "errors": [
    {
      "message": "Collection \"Test\" doesn't exist",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}`

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL 8.0.27

### What browser are you using?

Chrome

### What operating system are you using?

WIndows 10 with WSL Ubuntu 20.04

### How are you deploying Directus?

running locally

**Comment by Oreilles** [comment] 2021-12-22 12:14
Duplicate of https://github.com/directus/directus/issues/10564.

**Closed by Oreilles** 2021-12-22 12:14 UTC
Labels: Bug (Potential)
