### ISSUE TITLE
10.7.2 new install: column "public_favicon" does not exist

### ISSUE THREAD

**Issue by kapuza** [directus/directus#20369] opened 2023-11-09 08:08 UTC
### Describe the Bug

Install new clear 10.7.2 directus version on postgresql.
When use API get error:
```
 [16:36:28.247] ERROR: select "project_logo", "public_background", "public_foreground", "public_favicon" from "directus_settings" limit $1 - column "public_favicon" does not exist
    err: {
      "type": "DatabaseError",
      "message": "select \"project_logo\", \"public_background\", \"public_foreground\", \"public_favicon\" from \"directus_settings\" limit $1 - column \"public_favicon\" does not exis>
      "stack":
          error: select "project_logo", "public_background", "public_foreground", "public_favicon" from "directus_settings" limit $1 - column "public_favicon" does not exist
              at Parser.parseErrorMessage (/home/directus/directus/dist/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
              at Parser.handlePacket (/home/directus/directus/dist/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
              at Parser.parse (/home/directus/directus/dist/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
              at Socket.<anonymous> (/home/directus/directus/dist/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:514:28)
              at addChunk (node:internal/streams/readable:324:12)
              at readableAddChunk (node:internal/streams/readable:297:9)
              at Readable.push (node:internal/streams/readable:234:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 114,
      "name": "error",
      "severity": "ERROR",
      "code": "42703",
      "position": "66",
      "file": "parse_relation.c",
      "line": "3638",
      "routine": "errorMissingColumn"
    }
```

In database no field "public_favicon" and use in [code](https://github.com/directus/directus/blob/fe1a059d0d541d038d99b4b187acaa22f77a4bf8/api/src/services/assets.ts#L46) 

### To Reproduce

Just install new directus with new postgresql database and use api.

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2023-11-09 09:46
Unfortunately I am not able to reproduce this with a fresh install on Postgres database. 

When we first install the latest Directus (`10.7.2` as of now), a migration called `Themes` should be executed:

![](https://github.com/directus/directus/assets/42867097/82964486-91c4-41ba-9b4d-e3d740942585)

and said migration should be added since `10.7.0`, as seen in the `20230927A-themes.ts` migration file:

https://github.com/directus/directus/blob/fe1a059d0d541d038d99b4b187acaa22f77a4bf8/api/src/database/migrations/20230927A-themes.ts#L27

Can you try to make sure all migrations are ran properly and/or review the logs of your new install to see what might've went wrong (maybe that migration is somehow missing or skipped in your setup)?

Proceeding to close this as not reproducible but will re-open once more info arises to make sure this is reproducible reliably.

**Closed by azrikahar** 2023-11-09 09:46 UTC
