### ISSUE TITLE
Missing Relationship tab editing M2A field

### ISSUE THREAD

**Issue by dwene** [directus/directus#7591] opened 2021-08-25 04:48 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Somehow I think some piece of data in my Directus tables got wonky and now I'm unable to edit the relationship information for my `page.sections` M2A field. I'm able to delete the field and re-create it, and it works fine when using it in the forms, but after I re-create it, the relationship tab is still missing so I can't edit it.
Notice no relationship tab shows here:
![image](https://user-images.githubusercontent.com/12628251/130727437-cbd8a62e-128c-4983-820b-c86e061a3739.png)

But when I create a new M2A on an entirely different collection (test_collection), it shows fine.
![image](https://user-images.githubusercontent.com/12628251/130727524-618b7530-d977-43e4-8f45-9a586798fb61.png)

Maybe if someone can point me to the vue code that decides whether or not to render that "Relationship" tab I can debug more from there?

Github won't let me upload JSON files, but here's google drive link to the payloads for the collections, fields, and relationships API. https://drive.google.com/drive/u/0/folders/1bSJAjcvWn1Pizn9wcRQRw86gRablnWSx

I wasn't immediately able to find the missing data comparing the payloads between my `test_collection.sections` field and `page.sections field`, but adding those here for context.

### To Reproduce

I'm unable to consistently reproduce the bug. 

### What version of Directus are you using?

RC-91

### What version of Node.js are you using?

Whatever is in the default docker image.

### What database are you using?

Mariadb latest

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker + Kubernetes

**Comment by chernandezweb** [comment] 2021-09-04 18:04
Hi, I just tested the rc92 and this issues seems to be fixed on my side on this release. Thnk you !

**Comment by rijkvanzanten** [comment] 2021-09-05 14:20
@chernandezweb I can't reproduce it on my end either, so lets close it 🙂

**Closed by rijkvanzanten** 2021-09-05 14:20 UTC
Labels: App, Needs More Info, Bug (Potential)

**Comment by dwene** [comment] 2021-09-08 16:32
Just wanted to also say it's working for me also!
