### ISSUE TITLE
Error when new user is created and role is left blank

### ISSUE THREAD

**Issue by robinsonjohn** [directus/directus#22488] opened 2024-05-14 06:04 UTC
### Describe the Bug

When a new user is created in the app, the role is not required. If a role is not chosen, the user is added to the database correctly, but a `can't convert undefined to object` error message is returned to the user.

### To Reproduce

Do not select a role when creating a new user:
![user-no-role-01](https://github.com/directus/directus/assets/24327848/addf9935-90af-431e-a4f9-c6a7651bcad7)

Unexpected error appears:
![user-no-role-02](https://github.com/directus/directus/assets/24327848/d80c3520-6018-4460-bc82-9039a1b8136b)

User is added without apparent incident:
![user-no-role-03](https://github.com/directus/directus/assets/24327848/d4f88169-b2e6-4ff8-b5b0-c857eb9f9a2b)

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

MySQL 8

**Comment by DanielBiegler** [comment] 2024-05-14 16:28
Just tested this, but under sqlite, and it works for me. Mh your response should also not be code 204 but a 200 since we do return the primary key of the created user(s), see:

https://github.com/directus/directus/blob/9a6e23639b10b49e96216d549e836018c42fcf7b/api/src/controllers/users.ts#L45-L53

**Comment by hanneskuettner** [comment] 2024-05-15 05:48
One possible reason I can see the `/users` request return a 204 is if the item service can not read the just created user by its `id`, causing a `ForbiddenError` that is silently transformed into a 204 response. 

I can replicate this issue if I set the permissions of the current user, that is creating the new user, to be too restrictive, such that they are not able to read the just created user. Do you have any permissions (on `directus_users`) set up for the role that are different from the standard minimal app permissions?

**Comment by robinsonjohn** [comment] 2024-05-15 11:38
Here are some steps I've taken:

- Disabled all flows
- Created a new role with full access permissions to CRUD to `directus_users` and full read permissions to `directus_roles` (see screenshot)
- Login as a user with that role
- Attempt to create a user, only entering the first name, email, and password
- `POST` to `/users` shows the request body of the three fields. A `204` status is returned along with `[UNKNOWN] can't convert undefined to object` error
- Docker console simply shows a `POST /users 204` with no other errors, even with log level of `debug` 

This only happens when a role is not selected from the non-required select input when creating a user. Strangely, when I follow the same steps as an admin, the user is created without incident, and no error is returned.

![Screenshot 2024-05-15 at 7 28 39 AM](https://github.com/directus/directus/assets/24327848/821d2f12-ee95-440e-9853-bfaccb8e273b)

**Comment by hanneskuettner** [comment] 2024-05-15 11:41
Any hooks that are run by any of your extensions?

**Comment by robinsonjohn** [comment] 2024-05-15 11:50
@hanneskuettner Good question, but no, I have no extensions loaded.

I agree it seems like a permissions issue, but the role was just created and the only thing modified are assigning full permissions to `directus_users`. Debugging Directus would be a whole lot easier if status codes weren't invisibly changed and meaningful error messages were at least outputted to the console...

I'll keep looking in to it and post back any findings.

**Comment by hanneskuettner** [comment] 2024-05-15 11:57
> Debugging Directus would be a whole lot easier if status codes weren't invisibly changed and meaningful error messages were at least outputted to the console...

As far as I can tell be your report, the `[UNKNOWN] can't convert undefined to object` error is actually a frontend only error, that is thrown because the create endpoint unexpectedly returns no content (which is an improvement all on it's own), but there aren't any errors in the API side of things, since it returns a successful 204 (just without the expected content).

**Comment by robinsonjohn** [comment] 2024-05-15 11:58
@hanneskuettner Thank you for all your insight on this issue. It's much appreciated. I'll be looking in to this further.

**Comment by hanneskuettner** [comment] 2024-08-15 07:08
Any news on this? 

I will close this issue, since we are unable to reproduce it, without reducing the permissions to a level where the error is somewhat expected. If you have new information I'm more than happy to reopen this!

**Closed by hanneskuettner** 2024-08-15 07:08 UTC
Labels: :cake: Bug, :kaaba: MySQL, :detective: Needs More Info, :file_folder: Authentication, :elevator: Server, :fire::fire:
