### ISSUE TITLE
When adding custom fields to the collection directus_users, the layout of the collection is messed up.

### ISSUE THREAD

**Issue by Lucas-Gruber** [directus/directus#21214] opened 2024-01-27 23:32 UTC
### Describe the Bug

If I add custom fields to the collection directus_users, the layout of the collection is messed up after a restart of the directus container. i have example 1 and example 2 below. the first one is a new directus instance where i have tested it again. The second example is my production instance where it is even worse. I have marked the default fields in red, all others are custom fields/groups 

layout example 1: (in red the default fields)
![image](https://github.com/directus/directus/assets/72545889/a4b7adf2-1f9b-4225-9fb6-7baed2f36cbc)

data model 1:
![image](https://github.com/directus/directus/assets/72545889/017f7435-48e5-4e1e-bb9c-8c304c288a94)

layout example 2: (in red the default fields)
![image](https://github.com/directus/directus/assets/72545889/8ab6b8c5-43ee-43ab-bd54-9f31c2339ea0)

data model 2:
![image](https://github.com/directus/directus/assets/72545889/1d3f9dd8-bd9b-4d0c-868c-a124cb69f928)

### To Reproduce

Add custom fields to directus_users and restart the instance.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-01-28 00:01
Thanks for opening this issue! However, this is a duplicate of #20894, which has been fixed in #20910. The fix will be available in the next release.

**Closed by paescuj** 2024-01-28 00:01 UTC
