### ISSUE TITLE
Disabled style on active WYSIWYG editor

### ISSUE THREAD

**Issue by nelolka** [directus/directus#3656] opened 2021-01-11 20:49 UTC
### Steps to reproduce
1. Login as non-admin user (role without admin access)
2. Open any item with the text-field and WYSIWYG interface. You must have rights to edit this field.
3. The style of the WYSIWYG is wrong. It looks like it is readonly.
4. Make sure you can edit it.

### From https://github.com/directus/directus/issues/2907#issuecomment-757555022
If you create a new item, the style is right. But if you edit an existing item, the style inside tinymce iframe is wrong (while the style of `iframe` is right). It looks like TinyMCE is simply overriding your styles.

![image](https://user-images.githubusercontent.com/24505418/104137177-a2bcf800-53a3-11eb-88e0-487d11f96eb3.png)

**Comment by nelolka** [comment] 2021-01-11 20:50
@MichaelNussbaumerGOWEST in https://github.com/directus/directus/issues/2907#issuecomment-723418846: So it might be a timing issue, that the tinymce is loaded before the parent field enabled?

**Comment by rijkvanzanten** [comment] 2021-01-11 21:13
Duplicate of #2907

**Closed by rijkvanzanten** 2021-01-11 21:13 UTC
