### ISSUE TITLE
Permissions Don't Retroactively Apply

### ISSUE THREAD

**Issue by kyleva** [directus/directus#19323] opened 2023-08-01 19:00 UTC
### Describe the Bug

I have existing users with a role assigned called **Website**. When creating new model(s) and updating the **Website** role to have read permissions for these new model(s) the existing users tokens aren't able to query the new model(s). When creating a new user with the same **Website** role I am able to query these models.

Have validated that two separate users with the same **Website** role have different query permissions via Apollo GraphQL Studio.

### To Reproduce

1. Have users (with tokens) assigned to role with existing read permissions for existing model(s)
2. Create new model
3. Update role to include read permission for new model
4. Attempt to query with existing user & token
5. Error is surfaced

### Directus Version

10.5.2

### Hosting Strategy

Directus Cloud

### Note

I have not attempted regenerating a token on an existing user and querying for new model(s) due to a concern about breaking implementations in remote environments leveraging -said- API keys.

**Comment by br41nslug** [comment] 2023-08-02 14:18
I suppose this would be due to `CACHE_PERMISSIONS` which is enabled by default however that cache should really be cleared when actually making changes to permissions.

**Comment by rijkvanzanten** [comment] 2023-08-07 16:35
@kyleva Are you still able to reproduce this issue? I haven't been able to reproduce this on my own instance

**Comment by kyleva** [comment] 2023-08-07 17:09
@rijkvanzanten Let's give it a shot!

<img width="430" alt="image" src="https://github.com/directus/directus/assets/1703822/0aa6ffd4-12ec-4473-b91f-737370eeb586">

Creating a test entity.

<img width="850" alt="image" src="https://github.com/directus/directus/assets/1703822/00629c30-aa28-4194-91ca-62cc7b46cad9">

Then a `name` field on the test entity.

<img width="800" alt="image" src="https://github.com/directus/directus/assets/1703822/de5aec70-9a81-4c5b-91b8-618e942e1309">


Setting **Allow All** read access for current token on test entity.

<img width="1678" alt="image" src="https://github.com/directus/directus/assets/1703822/067b3308-1958-4e65-951f-3cf49175b9ec">

Test entity is available to be queried with previously created token! Whereas, before, it was not there.

Looks like the issue is no long occurring!

**Comment by rijkvanzanten** [comment] 2023-08-07 17:45
Perfect! Thanks for confirming! I'll close this for now, so we don't end up chasing a ghost. Please don't hesitate to ping me here or open a new issue if the problem happens again 🙂

**Closed** 2023-08-07 17:45 UTC
Labels: Needs More Info
