### ISSUE TITLE
User invite call cannot handle a relational filter

### ISSUE THREAD

**Issue by martijn-dev** [directus/directus#12896] opened 2022-04-20 19:35 UTC
### Describe the Bug

I created a role with a custom permission on the directus_users table:

![image](https://user-images.githubusercontent.com/73393707/164295868-992f8bc6-c6aa-48d2-8191-80ac31372c9e.png)

So this role can create other users, but cannot give them admin access. 

This works quite ok. If I create a role it still shows the administrator role, but if I save it it gives a validation error. So far sweet!

But if I try to use the invite option, it gives an error, unrelated to what kind of role I would like to give the invited user.
The 400 error I get:
```
{
  "message": "\"role\" must be of type object",
  "extensions": {
    "code": "FAILED_VALIDATION",
    "field": "role"
  }
}
```

My guess would be that is has something to do with the relational rule that has been set here.
Because if I create a rule like this:
![image](https://user-images.githubusercontent.com/73393707/164307362-3fdee2e2-b7ed-41b0-9fd5-4db702073b8d.png)
Wherein I just check by id (of the administrator role), it works as expected.

I hope my description is clear enough, don't hesitate to ask :)

### To Reproduce

- Create a role with custom create permission on the directus_users table:
raw rule value:
```
{
	"_and": [
		{
			"role": {
				"admin_access": {
					"_neq": true
				}
			}
		}
	]
}
```
- Try to invite a new user with a user in this new role.

### Errors Shown

```
{
  "message": "\"role\" must be of type object",
  "extensions": {
    "code": "FAILED_VALIDATION",
    "field": "role"
  }
}
````

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13.3

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2022-04-20 20:55
The validation rules check against the submitted value, not against the object that the value references. For example, if you configure the validation to check for "Needs to be object where field `admin_access` equals `false`", then the value `773dc83d-5e73-4e30-aaac-b6b952f58442` doesn't pass. 

There's a couple other ongoing discussions around the same subject, debating good ways to solve for this. One idea is to have some sort of way to do a subquery, so you can say something like:

```
_or:
  when a new item is created, can't have "admin_access: false"
  has to be an existing ID from the subquery ({ where admin_access: true })
```

Duplicate of https://github.com/directus/directus/issues/7423, also ref https://github.com/directus/directus/discussions/11844 / https://github.com/directus/directus/discussions/7123

**Closed by rijkvanzanten** 2022-04-20 20:55 UTC
Labels: Bug (Potential)

**Comment by martijn-dev** [comment] 2022-04-20 21:20
Ah, now I understand these other issues as well. 
Thanks for the explanation!
