### ISSUE TITLE
New item in M2M relation isn't displayed

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#9977] opened 2021-11-22 12:30 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When creating a new item from a m2m interface, the item is registered but invisible. It will only be shown after save.  This bug seems to only occurs if the related table has a user-input `varchar` primary key rather than the default auto-increment `id`.
Demo:

https://user-images.githubusercontent.com/33065839/142861736-3daa1abc-0c27-49aa-8e5e-39446f378ea1.mov

Related: https://github.com/directus/directus/issues/9923

### To Reproduce

- Create a collection `available_languages` with primary key `code` varchar
- Create a collection `general`
- Create a M2M field related to `available_languages` in `general`
- Open the new item page for `general`
- Create a new `available_language` item from the m2m interface

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by joselcvarela** [comment] 2021-12-13 07:16
Hi @Oreilles 
I believe this was fixed in https://github.com/directus/directus/pull/10368
Since I cannot reproduce anymore, I am closing it.

**Closed by joselcvarela** 2021-12-13 07:16 UTC
Labels: App, Bug
