### ISSUE TITLE
Again not able to save logo in Global Settings

### ISSUE THREAD

**Issue by jameswill** [directus/directus#2252] opened 2018-11-24 07:09 UTC
# Bug Report

## Steps to Reproduce

1. Install Directus 7.0.9 Suite using zip package.
2. Login to admin panel -> Admin Settings -> Global settings
3. Upload any logo and try to save that

## Expected Behavior
Logo should be saved

## Actual Behavior
Giving error on clicking save button 
**Attempting to write an array as the value for field "value" in "directus_settings"**

logs also states same error
ERROR: Directus\Database\Exception\SuppliedArrayAsColumnValue: Attempting to write an array as the value for field "value" in "directus_settings" in {Path to Directs}/directus709/src/core/Directus/Database/TableGateway/BaseTableGateway.php:1737

I have also reported this in last version as well along with no color changing issue. However only one issue got resolved (color change) and uploading logo issue persists. 

## Technical Details

- OS: Linux
- Web Server: apache 2.2
- PHP Version: 7.1
- Database:  MySQL 5.5
- Install Method: zip package

**Comment by rijkvanzanten** [comment] 2018-11-24 15:03
This is a duplicate of (your own!) issue 
https://github.com/directus/app/issues/1140

**Closed** 2018-11-24 15:03 UTC
