### ISSUE TITLE
"Save as copy" does not copy relational fields

### ISSUE THREAD

**Issue by stouch** [directus/directus#9991] opened 2021-11-22 20:31 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

As mentioned https://github.com/directus/directus/issues/6963#issuecomment-975709592, and https://github.com/directus/directus/discussions/9910 I re-open this subject : 

When I duplicate (_save as copy_) an item which has O2M "related items" to one or several of its fields, these related items are not copied, they are just "moved": after *save as copy* is run, the initial item's o2m field will be empty.

The problem is worse for M2M relationships : When I copy an item with M2M fields, I'm not sure of what happens for its M2M fields, but it looks like the junction table rows AND related items are not copied.

### To Reproduce

- Create a collection A, with O2M fields, and a M2M field. 
- Create an item of A (let's call it `a.1`), with some related items in O2M and M2M fields.
- Select every duplication fields of A except `ID` (the result is same if you select every duplication fields except ID and recursively related collection ID's)
- Save the `a.1` item " as a copy ". Let's call this new item `a.2`.

Result : Some strange behavior happens. While I'm expecting than the `a.1` item is copied with all related items copied and linked to my new `a.2` item, it appears than some O2M items are just "moved" under `a.2` and so removed from `a.1`.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

latest

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by sebescudie** [comment] 2021-11-23 09:38
Hey there,

Observed the same behavior here. Using latest Directus (9.0.1 - locally hosted - W10) and an SQLite database.

**Comment by TomS-** [comment] 2021-11-23 14:54
Also experiences the same issue here with MySQL.

**Comment by koksikus** [comment] 2021-11-23 16:44
Same with MS SQL. Copies everything without a field with M2M relationship.

**Comment by Oreilles** [comment] 2021-11-23 19:45
This is not a bug, it is intended behavior: Imagine you have a `recipe` collection with a m2m relation to an `ingredient` collection. You wouldn't want to create duplicate ingredients each time you duplicate a recipe. This is just an example, but applies for most use case: a `group` having several `users`, an `article` having several `tags`, a `shopping_basket` having several `items`  etc.

**Comment by benhaynes** [comment] 2021-11-23 19:49
Just adding in that there is a "Duplication" section within each Collection Settings that controls what is duplicated during this process.

**Comment by Oreilles** [comment] 2021-11-23 20:14
I tried selecting everything in the collection duplication settings, but this does not change the behavior described in this issue.

**Comment by adanielyan** [comment] 2021-11-24 01:14
O2M duplication works fine for me. "Many" items are duplicated correctly when saving a copy of "One". This is my Duplication config:

![image](https://user-images.githubusercontent.com/861777/143153388-132f71dc-9bd7-4f24-a558-d02b6151daf3.png)

**Comment by stouch** [comment] 2021-11-24 09:46
Actually, it seems that O2M copy works this way  https://github.com/directus/directus/issues/9991#issuecomment-977355165

But I confirm that with M2M fields there is a strange behavior, even with the correct selection in duplication fields :  The related M2M items are "moved" to the duplicated item (and so the original one looses its related items)

**Comment by adanielyan** [comment] 2021-11-24 11:41
I wonder if it has to do with the fact that you have translations. Will try duplicating after enabling the translations later today.

**Comment by adanielyan** [comment] 2021-11-25 01:44
I enabled translations, but still have everything working correctly with O2M duplication. I even have the translations copied.

**Comment by stouch** [comment] 2021-11-26 14:35
@adanielyan  I'm on 9.0.1

I'm gonna try with latest...

https://user-images.githubusercontent.com/17531455/143596380-ce01fbd4-c9cf-4e86-bbba-90e326c1bc66.mov

**Comment by stouch** [comment] 2021-11-26 23:22
I still have the same problem with latest 9.1.2 .

I did not changed my config of duplication fields.

https://user-images.githubusercontent.com/17531455/143660788-cccf6190-0f93-4499-8a45-1a11ffa07b1f.mov

**Comment by koksikus** [comment] 2021-12-02 06:58
> Same with MS SQL. Copies everything without a field with M2M relationship.

"Just adding in that there is a "Duplication" section within each Collection Settings that controls what is duplicated during this process."
I was wondering what these fields were for. Now I know. I did not find it in the documentation, maybe I was looking for it wrong. After selecting the appropriate fields, they are actually copied. Thx

**Comment by rijkvanzanten** [comment] 2021-12-02 23:37
I just tried this in the latest version with a fresh installation, and things seem to behave as expected. Make sure to configure the "Item Duplication Fields" option under the collection settings to match the behavior you'd like to see. When working with one-to-many relationships, keep in mind not to copy the primary key or foreign key of the related item, as that will "move" it to the newly created item.

**Comment by stouch** [comment] 2021-12-05 18:09
In the screencast above, I made up the good config excluding foreign keys and IDs. Have you seen it ?  Thank you for your answer.

**Comment by stouch** [comment] 2021-12-05 18:20
Ok @rijkvanzanten  I've found the bug. You can reproduce by following this : 

The bug does not occur if you just open and modify some field (that are not O2M or M2M), and just Save as copy.

BUT, if you open the item, modify some field, AND open a O2M field, edit the content of the O2M item, and close, and then you Save as copy : then you will have the bug I encountered in my video screencast (the O2M edited field will be lost in the original item).

Have a nice day/week.

**Comment by log4shell** [comment] 2022-01-19 18:21
I just ran into the same issue mentioned here, e.g., using the "Save as copy" feature actually **deletes all relations on the original item** that was just supposed to be duplicated and not modified in any way. Looking forward to a fix for this to be released.

**Comment by joselcvarela** [comment] 2022-01-22 12:13
> I just ran into the same issue mentioned here, e.g., using the "Save as copy" feature actually **deletes all relations on the original item** that was just supposed to be duplicated and not modified in any way. Looking forward to a fix for this to be released.

Please check the activity of the issue before posting any comments 🙏
As you can see above, our colleague Azri already opened a PR to fix this issue. https://github.com/directus/directus/pull/10418

**Comment by stouch** [comment] 2022-02-24 20:59
@rijkvanzanten  @azrikahar  @benhaynes  Is there any news about the merging of the fix ?

**Comment by rijkvanzanten** [comment] 2022-02-24 21:01
> @rijkvanzanten @azrikahar @benhaynes Is there any news about the merging of the fix ?

[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

(ps, no need to tag any person in particular. We all have notifications enabled and watch the whole repo 👍🏻 )

**Comment by stouch** [comment] 2022-02-24 21:03
OK , I'll be patient! (I actually sponsor some of you guys, you do an excellent work anyway !)

**Comment by rijkvanzanten** [comment] 2022-02-24 21:08
Appreciate it @stouch 🙂 It's a tricky bug with a fix that needs proper reviewing, so it takes a bit. That being said, I it should be moving forwards soon, hopefully as soon as the next release, but certainly within the next cycle or two

**Comment by chris-saunders-rocketlab** [comment] 2022-03-04 03:07
@rijkvanzanten I'm waiting on this one too, so I thought I'd pull your branch and test.
The fix does successfully leave the original item 100% intact.
For me there was an issue with the duplicated item though, where its copied relational items (M2A in my case) are invalid:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/74514057/156691373-19bd532b-ff9f-4662-86d4-ce48a4038eda.png">
I can't access the invalid items to see why they may be invalid, but there are no newly created items in the related collection so that could be a clue.
If this is new info to you, hope it helps, if not please ignore!

**Comment by azrikahar** [comment] 2022-03-04 13:46
@chris-saunders-rocketlab assuming you meant the #10418 branch, it's most likely [this comment here](https://github.com/directus/directus/pull/10418#pullrequestreview-884629500) which pointed out the current does falter when it comes to nested relations. Will need to revisit the current solution to take that into account. Thanks for checking it out!

**Closed** 2022-03-05 00:50 UTC
Labels: App, Bug
