### ISSUE TITLE
Empty page when using useItems

### ISSUE THREAD

**Issue by chrney** [directus/directus#24060] opened 2024-11-19 07:41 UTC
### Describe the Bug

As soon as I, inside a custom module, use the useItems composable, there is no visible content rendered, even though the script outputs console.log's even after the useItems call. There is under a very short time a spinner visible but that disappears, leaving me with a completely white page -- no meny, no collections, nothing at all on the screen.

### To Reproduce

myModule.vue is attached.
[myModule.vue.txt](https://github.com/user-attachments/files/17811423/myModule.vue.txt)

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment] 2024-11-19 08:22
This is not a problem with Directus, but rather with your extension code. When you do this assignment `const data = items.value` you lose all reactivity of the `items` ref. 

I suggest you read up on Vue reactivity a bit to understand what it going on, eg. here https://vuejs.org/guide/essentials/reactivity-fundamentals.html

`items` is a `ref()` that is automatically updated once the request to the server has been performed. 

I will close this, as this is not a bug. If you have any more questions please head over to [our Community Discord Server](directus.chat)

**Closed by hanneskuettner** 2024-11-19 08:22 UTC
