### ISSUE TITLE
Change collation/character set "latin1" to utf8_general_ci

### ISSUE THREAD

**Issue by chrisbenjamin** [directus/directus#1799] opened 2017-09-09 18:06 UTC
Directus uses a db scheme where only the character set within latin1 will be displayed. This means foreign characters are not usable, for example words like "Niṣībīn" or "Aẖlaẖ".
I have created a table and added input fields (very basic, text as varchar).

I would recommend to change this. There is no need to limit the possibilities to save different kinds of languages.

Anybody an idea where this option is set? Couldn't find something within the code while searching for "latin1".

## Version Info
  - Directus version and branch: build-6.4.2.20170823180744
  - PHP version:  5.6.30-0+deb8u1
  - MySQL version: 5.0.11-dev
  - Web server: nginx/1.6.2
  - OS name and version: Debian GNU/Linux 8 (jessie)

## Expected Behavior
Display the characters correctly.

## Actual Behavior
Characters are not displayed correctly (tofu/question mark)

## Steps to Reproduce
 1. just save a word with characters like these: "Niṣībīn" or "Aẖlaẖ".

## Schema Dump, Logs, or Screenshots
<img width="736" alt="screen shot 2017-09-09 at 19 51 01" src="https://user-images.githubusercontent.com/569479/30242595-8f0e4500-9599-11e7-8b35-04838c61f84c.png">
This shows a dump of a directus-created table.

<img width="113" alt="screen shot 2017-09-09 at 19 50 26" src="https://user-images.githubusercontent.com/569479/30242597-99de44d0-9599-11e7-9aa4-64e10d3ae494.png">

**Comment by WellingGuzman** [comment] 2017-09-10 03:02
Does your database default character set is `latin1`?

**Comment by WellingGuzman** [comment] 2017-09-10 03:08
Making this clear, as Directus does not create the database, the user has to create a database first, they need to make sure to make the default charset whatever they want, on the other hand we do set the connection charset default to `utf8mb4` check the config file (`api/config.php`) `DB_CHARSET` constant.

We are open to discuss whether or not Directus should use the connection charset value to create any string column with this charset as well.

As this is not a bug, I'm closing this ticket, but I won't lock it, to continue discuss this, or perhaps if it's actually a bug that's I'm not getting yet,  I will re-open.

Thanks @chrisbenjamin

**Closed by WellingGuzman** 2017-09-10 03:08 UTC

**Comment by chrisbenjamin** [comment] 2017-09-10 16:32
Okay, I will tell you what I did and where I need some support.

First: You was right, my mysql configration was not right. So I changed all necessary variables to utf8.
Then I created within directus a new table and added an item. This was not working, because in the ROW of the text value, the collation was still latin1. 

What did the trick? I went into phpmyadmin and changed the collation of the row to "utf8_general_ci"

I don't think that this preset collation depends on the local mySql configuration. What do you think?

Answering your post: You said "we do set the connection charset default to utf8mb4 check the config file (api/config.php) DB_CHARSET constant." - This is right, but I was not able to change this to something else, because what I need is a different collation (additionally to the charset).

**Comment by WellingGuzman** [comment] 2017-09-10 17:22
@chrisbenjamin what I'm telling you is that if Directus is creating table and columns with `latin1` collation is because your database has `latin1` collation.

What mysql version are you using? this value should fallback to the database default.

What you have to do is change the database collation to `utf8_general_ci` then Directus will create any table and column with that collection, we do not support collection on table creation or column creation yet. so we rely on the database default.

I understand the problem you are talking about, and how you fixed they are all correct, but you have to change the database collection.

```
ALTER DATABASE <your-database-name> CHARACTER SET utf8 COLLATE utf8_general_ci;
```
