### ISSUE TITLE
Translations are not deleted when deleting an item entry

### ISSUE THREAD

**Issue by jojomillennium** [directus/directus#3197] opened 2020-11-25 10:54 UTC
v9-rc14
When having translations setup for a collection, the deletion of an item from that collection does not delete the corresponding translations in the translation collection.

**Comment by benhaynes** [comment] 2020-11-25 14:32
Thanks!

This is a duplicate of: https://github.com/directus/directus/issues/2942

**Closed by benhaynes** 2020-11-25 14:32 UTC
