### ISSUE TITLE
[New field flow][Regression] Broken O2M fields (and other ones ?)

### ISSUE THREAD

**Issue by stouch** [directus/directus#9315] opened 2021-11-01 17:11 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Since I've moved from rc99 to rc100 (because of "new field flow" ?), when I update an existing O2M field, it removes the existing relationship

### To Reproduce

From a <rc100 install, with an existing O2M field in a collection : 
- update to rc100
- update your collection O2M field (or just click on "edit" on it)
- the relationship tab does not load anymore

Maybe this happens with other types of collection fields.

### Errors Shown

![Capture d’écran 2021-11-01 à 18 06 28](https://user-images.githubusercontent.com/17531455/139711388-ed82b457-685f-48db-8328-6742c76181a6.png)

### What version of Directus are you using?

rc100

### What version of Node.js are you using?

latest

### What database are you using?

Mysql

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment] 2021-11-01 19:23
Duplicate of https://github.com/directus/directus/issues/9182

**Closed by Oreilles** 2021-11-01 19:23 UTC
Labels: App, Bug
