### ISSUE TITLE
Many To Many Display Template not showing properly

### ISSUE THREAD

**Issue by ClementRocket** [directus/directus#12487] opened 2022-03-30 16:57 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

With Many To Many field, Directus is not showing the custom Display Template of the related collection item.
I've been trying a lot of things but I can't resolve the issue by myself.
Any insights would be greatly appreciated.
Thanks a lot for the great work.

### To Reproduce

1. Create a new database and bootstrap directus
2. Create collection1
3. Create collection2
4. Create a field Input Type string for collection2 (e.g. key "label")
5.  Create an item with any valid string for label for collection2
6. Create a Many to Many field in collection1 with a Key (e.g. "collection2") and set the related collection to collection2
7. Create an item for collection2, go to collection1 and  click on "Add Existing" and pick the collection2 item you just created
Now by default directus is showing the id of the related item
![directus-issue-1](https://user-images.githubusercontent.com/48010623/160882247-3cf241ce-3a6e-4a8a-936c-7b6b48b940d1.jpg)
State of the directus_fields table in database
![directus-issue-2](https://user-images.githubusercontent.com/48010623/160883267-f4ae14c1-09bc-4c17-9e00-3483021a29af.jpg)
8 . In Settings->Data Model->Collection1 click on collection2 ->Interface and pick the Label field from Collection2 as Display Template
![directus-issue-3](https://user-images.githubusercontent.com/48010623/160888305-a51ac9f2-f996-4fe7-8c67-3200a047576b.jpg)
9 . Go back to Content->Collection1, create an Item and  click on "Add Existing" and pick the collection2 item
![directus-issue-4](https://user-images.githubusercontent.com/48010623/160889272-54ac2543-36fa-498c-9d6f-c70faddb96d4.jpg)
It is not showing the proper template.

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2022-03-31 05:45
Thanks for opening this issue! However this is a duplicate of an existing issue #10916, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #10916 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-03-31 05:45 UTC
Labels: Bug (Potential)

**Comment by ClementRocket** [comment] 2022-03-31 06:59
Damn that is the exact problem. Sorry for the duplicate and thank you for your answer. Have a nice day.
