### ISSUE TITLE
Error when creating a collection

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#10146] opened 2021-11-30 00:14 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

alter table `banner` add constraint `banner_user_created_foreign` foreign key (`user_created`) references `directus_users` (`id`) on delete SET NULL - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'user_created' and referenced column 'id' in foreign key constraint 'banner_user_created_foreign' are incompatible. 

### To Reproduce

Create a new collection arbitrarily, select `user_created` and `user_updated` as the default fields.

### Errors Shown

https://docs.directus.io/configuration/config-options/#database

DB_CHARSET | Charset/collation to use in the connection to MySQL/MariaDB | UTF8_GENERAL_CI
-- | -- | --

## .env

``` env
DB_CHARSET="UTF8MB4_GENERAL_CI"
```

Report error: 

```  mysql
create table `banner` (`id` char(36) not null, `status` varchar(255) not null default 'draft', `sort` int null, `user_created` char(36) null, `date_created` timestamp null, `user_updated` char(36) null, `date_updated` timestamp null) default character set UTF8MB4_GENERAL_CI - ER_UNKNOWN_CHARACTER_SET: Unknown character set: 'UTF8MB4_GENERAL_CI'
```

``` env
DB_CHARSET="UTF8MB4"
```

Report error: 

``` mysql
alter table `banner` add constraint `banner_user_created_foreign` foreign key (`user_created`) references `directus_users` (`id`) on delete SET NULL - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'user_created' and referenced column 'id' in foreign key constraint 'banner_user_created_foreign' are incompatible. 
```

It worked in the old version because I have created a lot of collections and added relationships to them.

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

mysql 8.0

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by Oreilles** [comment] 2021-11-30 09:43
Duplicate of #9097 #7572

**Closed by Oreilles** 2021-11-30 09:43 UTC
Labels: Bug (Potential)
