### ISSUE TITLE
Can edit an Insight item

### ISSUE THREAD

**Issue by supermx1** [directus/directus#8325] opened 2021-09-26 00:48 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Forgive me, I am bad at giving titles. Now If I create an Insight Metric or basically an Insight Type, it works all well and good but if I try to edit it, it basically opens up a new create Insight window, instead of showing me a window where I can edit an Insight. So I have to basically start every Insight item I create if I need to edit it. 

https://user-images.githubusercontent.com/9326922/134789399-8bdfe7c4-aea9-49af-bd23-9aed87427d46.mp4

### To Reproduce

same as above

### What version of Directus are you using?

RC.94

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2021-09-26 00:56
Duplicate of #8252

**Closed by azrikahar** 2021-09-26 00:56 UTC
Labels: Bug (Potential)
