### ISSUE TITLE
Webhooks send schema

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#6246] opened 2021-06-14 09:20 UTC
**1) The issue and what you expected to happen**
When creating a Webhook and selecting "data", the whole schema is also send. I think it should be at least an extra checkbox.

When activating the data checkbox I do not expect to share maybe sensitive data as the schema.

**2) Exact steps to reproduce this issue**
Create a webhook, activate the "data" checkbox and see the post.

**3) Your environment:**
Directus 9.0.0 rc.42
(tried to check the issues if if there have been any changes until now, but couldn't find some. If it's already changed I'm sorry)

**Comment by benhaynes** [comment] 2021-06-14 13:48
Love it!

@rijkvanzanten, could we use the same "Field Select Treeview" to allow granular control over what data gets sent with each webhook?

**Comment by rijkvanzanten** [comment] 2021-06-14 15:08
Yes, but keep in mind that you'd be picking the fields that would be included in a webhook (eg schema/payload/user/etc), not the fields of the data you've inserted/update etc itself.

**Comment by rijkvanzanten** [comment] 2021-06-14 15:09
Technically a duplicate of https://github.com/directus/directus/discussions/5973, but I agree that it's important enough to consider a problem 👍🏻

**Comment by benhaynes** [comment] 2021-06-14 16:04
> Yes, but keep in mind that you'd be picking the fields that would be included in a webhook (eg schema/payload/user/etc), not the fields of the data you've inserted/update etc itself.

Yeah, I think we should allow sending both, maybe scoped in the response?

**Comment by doodlemania2** [comment] 2021-06-16 02:40
We solved this by just ignoring the payload entirely and performing a secondary RESTful query against the ID that gets sent to us. Second trip, sure, but more controllable.

**Closed** 2021-06-17 15:13 UTC
Labels: API, Bug, Improvement
