### ISSUE TITLE
Translation issue - on English interface, user `active` status option was mistakenly set in Bulgarian rather than English 

### ISSUE THREAD

**Issue by minyangu-bgl** [directus/directus#7426] opened 2021-08-16 07:50 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

See below, the `active` option somehow displays in Bulgarian

![image](https://user-images.githubusercontent.com/49973259/129529333-ad49920d-93ae-467a-97a9-1f27455ffbfe.png)

### To Reproduce

Goto `User Directory` -> `Admin` -> `Admin Options` and open the dropdown for `Status`

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

16.6.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally using docker compose

**Comment by paescuj** [comment] 2021-08-16 08:03
Duplicate of #7362

**Closed** 2021-08-16 08:51 UTC
Labels: Bug (Potential)
