### ISSUE TITLE
Javascript error in Settings > Group Permissions

### ISSUE THREAD

**Issue by rmercader** [directus/directus#1157] opened 2016-05-13 13:30 UTC
To help us resolve your issue more quickly, please use the following template:

For feature requests please chat with us through [getdirectus.com](http://getdirectus.com).

## Version Info
  - Directus version: (Or commit hash) 3.0, Commit hash perhaps d4c5f7a
  - PHP version: 5.6.17
  - MySQL version: 5.7.9
  - Web server: (Ex. Apache, nginx or IIS?) WAMPSERVER, Apache 2.4.17
  - OS name and version: Windows 7

## Expected Behavior
List all table permissions

## Actual Behavior
Raises a javascript error: **Cannot read property 'split' of undefined**.
See screenshot for more details.

## Steps to Reproduce
 1. Select Setings
 2. Select Group Permissions
 3. Select Administrator item.

## Logs or Screenshots
![image](https://cloud.githubusercontent.com/assets/2795863/15249287/304e9c4e-18f5-11e6-943f-9cbdfe9d17fa.png)

**Comment by benhaynes** [comment] 2016-05-13 13:56
@WellingGuzman this seems similar to the issue you just resolved – could it be the same problem? That was caused by empty strings in the `directus_tables.primary column` instead of `NULL`, right?

**Comment by WellingGuzman** [comment] 2016-05-16 22:18
@benhaynes I'm not sure, and I don't think so. 

@rmercader thanks for reporting this I'm trying to replicate the issue.

**Comment by WellingGuzman** [comment] 2016-07-21 05:06
This issue was fixed by https://github.com/directus/directus/commit/b0fcc75ceb753f86b44a52cdf83f7d59f71c01dc and https://github.com/directus/directus/commit/cbbd2a8f57863c1cbd272b2ba528528452b5267c.

If this is not the case I will re-open the ticket.

**Closed by WellingGuzman** 2016-07-21 05:06 UTC
Labels: 2. Critical, Bug
