### ISSUE TITLE
Nested M2A relationship is 403 (Forbidden)

### ISSUE THREAD

**Issue by autr** [directus/directus#3754] opened 2021-01-19 21:59 UTC
Hello, really nice work with V9 so far. I've been using a lot of the new M2A, but come across a pretty tricky bug.

1) Description

Currently I have a nested M2A structure: a Page has M2A for Groups, and Groups have M2A for Text, Image, List etc. 

If I `Create New` Group, then `Create New` Text, then `Save` Text, `Save` Group, and finally `Save` Page ... I get a 403 / Forbidden error. This is with the default full-admin permissions. 

2) Exact steps to reproduce this issue

Create a data model which has an M2A relation to a data model which has an M2A relation to a data model.

3) Your environment:

Directus ^9.0.0-rc.30
Postgres ^8.5.1
Raspberry Pi OS (Linux 5.10.4-v7l+)
Brave / Chromium 87.0.4280.141

4) Other details

In the console, the nested Text and Group don't seem to be created when saved, so are queued for when the parent / grandparent is finally saved? Wondering if this is the cause.

**Comment by rijkvanzanten** [comment] 2021-01-29 15:46
@autr Would you be able to share a DB dump where this is happening? I just setup a m2a to m2a to collection and it seems to work as expected:


https://user-images.githubusercontent.com/9141017/106296076-35241f00-621f-11eb-85e1-59f0631feaa0.mp4

**Comment by autr** [comment] 2021-01-30 00:17
Hey, for sure - please find attached Postgres v13 DB exported from TablePlus: [gs.dump.zip](https://github.com/directus/directus/files/5896973/gs.dump.zip)

- create a new Event
- to the Event _Body (m2a)_ add a new Group
- to the new Group _Contents (m2a)_ add a new Text
- save Text, save Group, save Event

If each Event / Group / Text is being created then the final Event save button is unresponsive until another view is loaded (then will show Forbidden). And if the Event is being edited then it will immediately show Forbidden when saved.

**Comment by arladmin** [comment] 2021-08-10 16:30
Hi all. I've come across a similar issue, in the latest version (rc 89).

In my create item (POST) API call, i'm unable to set any value for the M2M field.
Error: ```403 - {"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}```

This is the format that i'm implementing: https://docs.directus.io/reference/api/introduction/#one-to-many-many-to-many

Error is received in both cases: 
1. Selecting an existing entry 
```
POST call with body: {"M2M_field": [2] }  //2 = id of existing relational item
```
2. Creating a new entry
```
POST call with body: {"M2M_field": [{"a":"b"}] }  
```

**Comment by rijkvanzanten** [comment] 2021-08-10 16:44
@arladmin That looks unrelated to the OP (which is a bug that happens when you nest a m2a into a m2a), and it looks like a usage problem. Mind opening a Q&A Discussion instead?

**Comment by rijkvanzanten** [comment] 2021-12-03 01:13
This was fixed in the big relationships overhaul of the RC90s but the issue wasn't closed. I just tried the dump on the latest version of Directus, and the steps to reproduce don't cause any issues 🙂

**Closed by rijkvanzanten** 2021-12-03 01:13 UTC
Labels: App, Bug
