### ISSUE TITLE
FORBIDDEN modifying 

### ISSUE THREAD

**Issue by smidolt** [directus/directus#22694] opened 2024-06-07 06:53 UTC
### Describe the Bug

In this case I am using a PostgreSQL database. I can create content, but after that I can't modify it because of FORBIDDEN error. 
If we create manual threads to modify it, it is still not possible.

### To Reproduce

![Screenshot 2024-06-07 at 8 41 10 am](https://github.com/directus/directus/assets/103376685/637b03ea-9af3-4744-ac39-16f5460e4d4d)
![Screenshot 2024-06-07 at 8 50 20 am](https://github.com/directus/directus/assets/103376685/bade0707-3927-4ea8-8e0d-c595bca2911d)
![Screenshot 2024-06-07 at 8 50 34 am](https://github.com/directus/directus/assets/103376685/18ce26e9-f34a-44c9-a5d5-d42a475ff3dc)

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL (DigitalOcean)

**Comment by hanneskuettner** [comment] 2024-06-07 08:28
Heya, this very much looks like a permissions configuration issue on your end. Do you see this error when using an admin user, or just with a user with reduced permissions? 

Also, can you provide detailed instructions on how to reproduce this very specific issue, otherwise it might be hard to verify this is an issue on our end.

**Comment by smidolt** [comment] 2024-06-07 08:57
I tried with owner permission. Ill attach all the info about it maybe I
missed something
[image: Screenshot 2024-06-07 at 10.47.42 am.jpg]
[image: Screenshot 2024-06-07 at 10.49.14 am.jpg][image: Screenshot
2024-06-07 at 10.53.03 am.jpg]
[image: Screenshot 2024-06-07 at 10.53.35 am.jpg]
[image: Screenshot 2024-06-07 at 10.53.50 am.jpg]
[image: Screenshot 2024-06-07 at 10.55.06 am.jpg]
[image: Screenshot 2024-06-07 at 10.55.35 am.jpg]
[image: Screenshot 2024-06-07 at 10.49.38 am.jpg]

**Comment by smidolt** [comment] 2024-06-07 09:37
![image](https://github.com/directus/directus/assets/103376685/e7226e08-c092-4717-a160-54a5c513b3e0)
![image](https://github.com/directus/directus/assets/103376685/880b8097-e343-466f-9010-19d7d333af45)
![image](https://github.com/directus/directus/assets/103376685/c9151b15-ccdb-45d1-85d1-71e64a72a9fa)
![image](https://github.com/directus/directus/assets/103376685/b19f6254-51ab-47c9-9a12-495e7534428f)
![image](https://github.com/directus/directus/assets/103376685/1fcf59e4-febb-4a9a-8f5d-207db4f25d6e)
![image](https://github.com/directus/directus/assets/103376685/1eb0894d-408c-4617-a6e7-13cc79d61547)
![image](https://github.com/directus/directus/assets/103376685/e40d9606-0471-41d3-8de2-e9a17595ea4b)
![image](https://github.com/directus/directus/assets/103376685/a46decd7-5ca2-4279-bcf3-1a8ef30269c9)

**Comment by hanneskuettner** [comment] 2024-06-07 09:43
Can you click the `Copy` icon, to copy the full error and share it here as well? Then we will see what the actual error is. 

Mind you, that a 403 Forbidden is also thrown when trying to read an item that does not exist. So please also check what network request actually fails and share that as well. 

Also, if you could quickly outline your collection setup (with what fields are related to which other collections) that might help track down the problem as well.

I also noticed that you're still on 10.10.7, which is about 1 1/2 months old at this point, so if you can, please update to the latest version as your problem might have been fixed in the meantime.

**Comment by smidolt** [comment] 2024-06-11 07:56
Updating helped thank you.

**Closed** 2024-06-11 07:56 UTC
Labels: :detective: Needs More Info
