### ISSUE TITLE
Preview URL nested fields not loading if nested within 2 deep group

### ISSUE THREAD

**Issue by triplecasquette** [directus/directus#23830] opened 2024-10-09 16:57 UTC
### Describe the Bug

All my nested fields are loading and there's no way to display. I tried to edit manually but it doesn't work

### To Reproduce

Add fields into groups then into accordion and try to access nested field in preview URL

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgresql

**Comment by hanneskuettner** [comment] 2024-10-09 17:03
Can you share more reproduction info? Any errors in the console / network tab? Are all related fields not working or just some types of relations? 

Because for me it works just fine, see attached video

https://github.com/user-attachments/assets/3d44939a-ec2c-498f-805d-f92eaefc9ac1

**Comment by triplecasquette** [comment] 2024-10-09 17:05
As it didn't work I delete the accordion and it works just fine.
So I have no more infos. I just wanted to help. :) Maybe it was not the issue. And i should close this one.

**Comment by hanneskuettner** [comment] 2024-10-09 17:08
I'm able to reproduce it the issue when nesting a raw group under an accordion, so that definitely seems like a bug and that was the missing piece of information.

![CleanShot 2024-10-09 at 19 08 10](https://github.com/user-attachments/assets/6455de79-4870-42d4-a03a-638e5e2570dd)

**Comment by hanneskuettner** [comment] 2024-10-09 17:39
Looks like this has been reported previously #23551. So I'll be closing this issue

**Closed by hanneskuettner** 2024-10-09 17:39 UTC
Labels: Bug
