### ISSUE TITLE
M2M interface not showing related collection description

### ISSUE THREAD

**Issue by massimoliani** [directus/directus#11244] opened 2022-01-24 20:17 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

M2M interface working perfect to choose releated collection items.
When selected and confirmed new added selection is not shwon with correct description, but just "---" some dashes.
If saving item and editing again all related field values are shown correctly with the right description.

### To Reproduce

Use a M2M relation in a collection (collection A) to an external collection (collection B) having a field description.
Choose from collection A one or more item of the related collection B, confirm selection.
In collection A form you'll see just "----" not the real description, save the item in collection A and edit it again, you can see the correct description.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.0.0

### What database are you using?

MySql 8

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-01-24 20:20
I believe this is a duplicate of https://github.com/directus/directus/issues/10476

**Closed by rijkvanzanten** 2022-01-24 20:20 UTC
Labels: Bug (Potential)

**Comment by massimoliani** [comment] 2022-01-24 20:23
Thank you, I'll wait for new release.
