### ISSUE TITLE
KnexTimeoutError on docker-compose up

### ISSUE THREAD

**Issue by Zyles** [directus/directus#19209] opened 2023-07-19 22:52 UTC
### Describe the Bug

I am trying to do a docker install following the docs but I am unable to connect to an external postgreSQL db.

PostgreSQL 13.11

```
docker-compose.yml:
version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/home/http/project/database
      - ./uploads:/home/http/project/uploads
    environment:
      KEY: 'xxxx'
      SECRET: 'xxxxxx'
      ADMIN_EMAIL: 'xxxxxx'
      ADMIN_PASSWORD: 'xxxxxxxx'
      DB_CLIENT: 'pg'
      DB_HOST: '123.123.123.13'
      DB_DATABASE: 'xxxx'
      DB_PORT: '5432'
      DB_USER: 'xxxx'
      DB_PASSWORD: 'xxxxx'
      DB_SSL: 'true'
      WEBSOCKETS_ENABLED: 'true'
```

`sudo docker-compose up`

Error:
```
directus_1  | [22:39:34.388] INFO: Initializing bootstrap...
directus_1  | [22:42:59.521] ERROR: Can't connect to the database.
directus_1  | [22:42:59.521] ERROR: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
directus_1  |     err: {
directus_1  |       "type": "KnexTimeoutError",
directus_1  |       "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
```

### To Reproduce

See above.

### Directus Version

latest docker

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-07-20 00:58
Closing this as it's not an issue with Directus, but one with the database.
Please see https://docs.directus.io/getting-started/support.html to see how you can get further help.

**Closed by paescuj** 2023-07-20 00:58 UTC

**Comment by Zyles** [comment] 2023-07-20 03:00
> Closing this as it's not an issue with Directus, but one with the database. Please see https://docs.directus.io/getting-started/support.html to see how you can get further help.

It's not a database issue.

The database is running in production and I can connect to it using DBeaver just fine from my desktop using the same credentials.

The docker instance with directus in it is unable to connect to it.

I'm not going to pay for enterprise support because you are unable to provide working documentation on how to get the software to run and instead have to be stumbling around in the dark.

I thought this software would be a time saver, but it wasted 5 hours of my time when I could have been writing raw SQL queries and already have my DB structure done.

**Comment by rijkvanzanten** [comment] 2023-07-20 03:30
> It's not a database issue.

It's not, it's an issue with how you're using docker compose at the moment.

Docker containers running within docker compose by default only have network access to the other containers within the compose stack for security reasons. You're database is on a host the docker container itself doesn't have any access to by default. I believe you can set the container's network_mode to "host" to have it use your local machines networking, at which point it should behave the same as your local dbeaver etc.

> I'm not going to pay for enterprise support because you are unable to provide working documentation on how to get the software to run and instead have to be stumbling around in the dark.

The documented examples work as documented. You just ran into an unexpected security measure of docker itself with your experiments in connecting to a database outside of the docker compose stack.

**Comment by gla23** [comment] 2024-01-16 10:36
In case this helps anyone, for me this was caused by the firewall. The Directus container IP had changed and I needed to allow the new IP.
