### ISSUE TITLE
directus-extension scaffold on 9.25.1 is broken

### ISSUE THREAD

**Issue by Igelkottegrodan** [directus/directus#18230] opened 2023-04-18 13:21 UTC
### Describe the Bug

You can no longer scaffold extensions.

```bash
import { inquirer } from 'inquirer';
         ^^^^^^^^
SyntaxError: Named export 'inquirer' not found. The requested module 'inquirer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'inquirer';
const { inquirer } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)

Node.js v19.8.1
```

Same goes for Node.js v18.15.

### To Reproduce

`npm init directus-extension`

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment] 2023-04-18 13:26
Duplicate of https://github.com/directus/directus/issues/18183

**Closed by rijkvanzanten** 2023-04-18 13:26 UTC

**Comment by ryanleung96** [comment] 2023-04-18 13:40
@rijkvanzanten any idea when this fix will release? 

I'm working with the main branch and keep encountering this issue. Seems there's an urgency to release this fix.

**Comment by rijkvanzanten** [comment] 2023-04-18 13:41
> I'm working with the main branch and keep encountering this issue

As-in, build from source on `main`, or using the latest published distribution?

**Comment by ryanleung96** [comment] 2023-04-18 13:43
> > I'm working with the main branch and keep encountering this issue
> 
> As-in, build from source on `main`, or using the latest published distribution?

I foked from the `main` brunch and work locally

**Comment by hanneskuettner** [comment] 2023-04-18 14:07
With that you should be able to add the resulting package to your package.json

```json
{
	"devDependencies": {
		"@directus/extensions-sdk": "../directus/packages/extensions-sdk"
	}
}
```

And then running `pnpm i` and `pnpm directus-extension build` will work again.

If you want to scaffold a new extension you can do so as well by running 

`pnpm directus-extension create <extension-type> <name>`

This will create a new directory with the scaffolded extension. 
There you will also have to replace the `^9.25.1` version of the `@directus/extensions-sdk` with the path to your local build.

Works like a charm for me.

**Comment by ryanleung96** [comment] 2023-04-18 14:37
> With that you should be able to add the resulting package to your package.json
> 
> ```json
> {
> 	"devDependencies": {
> 		"@directus/extensions-sdk": "../directus/packages/extensions-sdk"
> 	}
> }
> ```
> 
> And then running `pnpm i` and `pnpm directus-extension build` will work again.
> 
> If you want to scaffold a new extension you can do so as well by running
> 
> `pnpm directus-extension create <extension-type> <name>`
> 
> This will create a new directory with the scaffolded extension. There you will also have to replace the `^9.25.1` version of the `@directus/extensions-sdk` with the path to your local build.
> 
> Works like a charm for me.

@hanneskuettner that works, but I can't run the build command

```
ryanleung@Ryans-MacBook-Pro test-endpoint % npm run dev

> directus-extension-test-endpoint@1.0.0 dev
> directus-extension build -w --no-minify

node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/ryanleung/Desktop/directus/test-endpoint/node_modules/@directus/extensions-sdk/dist/esm/cli/run.js' imported from /Users/ryanleung/Desktop/directus/test-endpoint/node_modules/@directus/extensions-sdk/cli.js
```
