### ISSUE TITLE
items.create hook event is triggered when the item is not inserted in the database

### ISSUE THREAD

**Issue by Menganitou** [directus/directus#4558] opened 2021-03-16 14:05 UTC
Hi,

I am currently having some problemns with the custom API hooks. When I create a record of a collection(cart_items), within another collection(cart) that is related (O2M), the new record is not already created in the database when `items.create` event is triggered. Isn't it supposed that when the `items.create` event is fired the record should have already been created before?

![test_app](https://user-images.githubusercontent.com/10880950/111314623-dcd79e00-8661-11eb-9f89-3a302f3fd151.png)

Current scheme:

**carts**
- id
- total_items_count
- total_price
- cart_items (O2M)

**cart_items**
- id
- carts (M2O)
- products (M2O)

**products**
- id
- name

```
// /extensions/hooks/test/index.js
module.exports = function registerHook({ database }) {
	return {
		'items.create.before': async function (input) {
			console.log('************************');
			console.log('*  items.create.before *');
			console.log('************************');

			try {
				const results = await database('cart_items').count();
				console.log('*********************************');
				console.log('* items.create.before - results *');
				console.log('*********************************');
				console.log(results);
			} catch (error) {
				console.log(error);
			}

			return input;

		},
		'items.create': async function (input) {
			if (input.collection !== 'cart_items') return input;
			console.log('************************');
			console.log('*   items.create       *');
			console.log('************************');		

			//console.log('Waiting 500 milliseconds...');
			//waitFor = delay => new Promise(resolve => setTimeout(resolve, delay));
			//await waitFor(500);

			try {
				//const commitResults = await database.raw('COMMIT;');
				//console.log(commitResults);
				const results = await database('cart_items').count();

				console.log('********************************');
				console.log('* items.create - results       *');
				console.log('********************************');
				console.log(results);
			} catch (error) {
				console.log(error);
			}

			console.log('return_input');
			return input;

		}
	};
};
```

It seems to me that the PATCH method is what executes the insert. But im not 100% sure.

Normal execution without setTimeout. It says there is only 1 row when `items.create` triggers. Thats incorrect:

![image](https://user-images.githubusercontent.com/10880950/111314808-0a244c00-8662-11eb-9428-cc8e29c9dbed.png)

If we wait some time before executing the code(setTimeout), the PATCH method is executed before the `database.count()` sentence. So we get 2 rows correctly:

![image](https://user-images.githubusercontent.com/10880950/111315182-6a1af280-8662-11eb-85b9-9a172da0ffee.png)

After numerous tests. It only shows me the correct result if I force it to wait. I have also tried to execute a commit, before executing any statement, but not every time it shows the correct result.

It is worth mentioning that when I run the creation from the cart_items screen directly it shows the correct result. 

Thank you so much for your attention

---

### Project details
Directus Version: 9.0.0-rc.50
Environment: production
OS: Windows_NT 10.0.19041
Node: 12.16.2
PostgreSQL 13.2
npx local cli deployment

**Comment by rijkvanzanten** [comment] 2021-03-16 14:11
When you say

> the new record is not already created in the database when items.create event is triggered

_which_ new record are you referring too? 

FWIW the creates are in order based on the type of relationship. M2Os are done "bottom up" (related item is created first, resulting primary key is stored in parent), O2Ms are "top down" (parent is saved first, ID passed down to foreign key of O2M).

**Comment by Menganitou** [comment] 2021-03-16 15:03
> When you say
> 
> > the new record is not already created in the database when items.create event is triggered
> 
> _which_ new record are you referring too? 
> 
> FWIW the creates are in order based on the type of relationship. M2Os are done "bottom up" (related item is created first, resulting primary key is stored in parent), O2Ms are "top down" (parent is saved first, ID passed down to foreign key of O2M).

Hi @rijkvanzanten . Im referring to the cart_items. Im creating a cart_item in the carts collection screen (**not** directly in the cart_items screen).

So about what you said. I think this is a "top down" scenario. But im not sure how to proceed with that info

Thanks for your response

**Comment by rijkvanzanten** [comment] 2021-03-16 15:15
Ahh I think I know what the problem is here. The whole nested update tree is done in a single SQL Transaction (so the whole thing can be rolled back on auth/insertion problems anywhere in the tree. By doing the count outside of the transaction, while the transaction hasn't been committed yet, you end up counting the records that haven't been committed yet 🤔

**Comment by rijkvanzanten** [comment] 2021-03-16 15:16
A possible solution would be to move `{ database }` into the context of the hook itself, instead of on the "parent" level. That way, I can pass you the currently active transaction under `database`, which means you should be able to correctly query things in there

**Comment by Menganitou** [comment] 2021-03-16 15:46
> A possible solution would be to move `{ database }` into the context of the hook itself, instead of on the "parent" level. That way, I can pass you the currently active transaction under `database`, which means you should be able to correctly query things in there

Yesss, that sounds like a promising solution to me. It is worth mentioning that I also tried it with the ItemsService and the same thing happens to it. Maybe you should consider moving it to the hook context as well, although I don't know if it will break something

to clarify: currently it is not possible to obtain the `{ database }` directly from the hook function, right?. Are these the current allowed parameters?: https://docs.directus.io/guides/api-hooks/#event-handler-function

**Comment by rijkvanzanten** [comment] 2021-03-16 16:21
Correct, that's the change [improvement] that needs to be made 👍🏻

**Closed** 2021-03-18 02:08 UTC
Labels: API, Improvement
