### ISSUE TITLE
Date interface is displaying 1 day before

### ISSUE THREAD

**Issue by supermx1** [directus/directus#7383] opened 2021-08-12 20:04 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

So this is interesting, every date field is showing 1 day before. So if I select today 12 August 2021 as a date in the system and save it, when I view the data I see 11 August 2021, but if I check the DB, the correct date is saved there. 

https://user-images.githubusercontent.com/9326922/129262257-e359d84e-7297-4fe7-b11d-44534bc43ce0.mp4

### To Reproduce

Create a date field and enter a specific date, save and view the record. Also, check your DB.

### What version of Directus are you using?

RC.90

### What version of Node.js are you using?

14.15.3

### What database are you using?

10.4.17-MariaDB - Source distribution and MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Locally & Windows Server 2019 (Production)

**Comment by rijkvanzanten** [comment] 2021-08-12 20:06
> but if I check the DB, the correct date is saved there.

Does the API return the correct date? (eg is this a retrieval problem, or a display problem in-app)

**Comment by supermx1** [comment] 2021-08-12 20:18
Let me check using graphql

**Comment by supermx1** [comment] 2021-08-12 20:37
![Screen Shot 2021-08-12 at 9 36 10 PM](https://user-images.githubusercontent.com/9326922/129266089-e6b2942a-4372-4cc5-b25d-07dff3b60ea2.jpg)

Same with graphql

Wow.... What do we do?

**Comment by rijkvanzanten** [comment] 2021-08-12 20:38
What is the server timezone for your MariaDB installation, does it do any timezone conversions?

**Comment by supermx1** [comment] 2021-08-12 20:43
my MariaDB is localhost. So the timezone is set correctly. West Africa Time

![Screen Shot 2021-08-12 at 9 43 19 PM](https://user-images.githubusercontent.com/9326922/129267021-71087793-00e7-464c-821a-61479fecfe75.jpg)

**Comment by supermx1** [comment] 2021-08-12 21:59
Could it be?


![Screen Shot 2021-08-12 at 10 58 42 PM](https://user-images.githubusercontent.com/9326922/129275387-0b4b1133-14cc-4db3-ae51-753717434492.jpg)


/node_modules/mysql/lib/ConnectionConfig.js

**Comment by rijkvanzanten** [comment] 2021-08-12 22:11
<img width="761" alt="CleanShot 2021-08-12 at 18 11 14@2x" src="https://user-images.githubusercontent.com/9141017/129276509-a2bc2151-aad8-476b-b66c-45a2e9566f40.png">

Interesting! What is the timezone of where/how you run Node? Maybe those two aren't in sync 🤔

**Comment by supermx1** [comment] 2021-08-12 22:17
I am sorry, I don't. get the question. 

I run node on my local machine. MacBook Pro. My test copy of directus is running on my local system and it is using xampp to serve the MySQL DB. I have a production version running on Windows Server and the database is also being served by Xampp.

**Comment by supermx1** [comment] 2021-08-12 22:21
What is funny is that in the DB that date is correct. So if I am using the DB data directly and not passing through directus the date is fine. But once I use the API or the app, it displays -1day date.

**Comment by rijkvanzanten** [comment] 2021-08-12 22:45
@supermx1 I'm wondering if Node's timezone is the same as the database timezone. If the connection to MySQL is using a different timezone in the connection than the database is configured in, it might cause trouble in the conversion back and forth from MySQL to a Date object, as per that snippet of the `mysql` package docs 🤔 

Can you try setting `DB_TIMEZONE="+01:00"` to see what happens?

**Comment by supermx1** [comment] 2021-08-12 23:55
In MySQL or NodeJS? or that snippet in the mysql package docs?

**Comment by supermx1** [comment] 2021-08-13 00:17
Found this randomly

https://stackoverflow.com/questions/50270818/node-js-server-mysql-db-return-incorrect-date-value

**Comment by rijkvanzanten** [comment] 2021-08-13 00:18
> In MySQL or NodeJS? or .ENV or that snippet in the mysql package docs? Lol. I am lost.


In the .env file 👍🏻

**Comment by supermx1** [comment] 2021-08-13 00:19
Tried it now. Still same issue


![Screen Shot 2021-08-13 at 1 19 35 AM](https://user-images.githubusercontent.com/9326922/129285941-25336ca3-2dce-4629-bfab-58c43e1873d1.jpg)

**Comment by supermx1** [comment] 2021-08-13 00:21
Directus App
![Screen Shot 2021-08-13 at 1 20 20 AM](https://user-images.githubusercontent.com/9326922/129285987-7f26340c-a7aa-4ca6-b746-78b2fee45942.jpg)

MariaDB
![Screen Shot 2021-08-13 at 1 21 06 AM](https://user-images.githubusercontent.com/9326922/129286025-9d6c32c2-2533-4ee4-beff-eda325411ac7.jpg)

**Comment by supermx1** [comment] 2021-08-13 00:39
Now I set the timezone to
DB_TIMEZONE="+00:00"

Direct App

![Screen Shot 2021-08-13 at 1 37 29 AM](https://user-images.githubusercontent.com/9326922/129287020-73eaaf07-ccc5-4651-b09c-33a8dbc2834c.jpg)


MariaDB

![Screen Shot 2021-08-13 at 1 36 27 AM](https://user-images.githubusercontent.com/9326922/129286967-fd4de337-f7aa-4db5-a183-98eeecd28ed6.jpg)


This is more of a hack because the time is actually wrong. When I submitted this record the time was 1:35AM but in the DB it is now 12:35AM. So the date is correct but time is wrong.

**Comment by rijkvanzanten** [comment] 2021-08-13 00:53
Wait, are you using a date field or a timestamp/datetime? I thought we were talking about a date field 🤔

**Comment by supermx1** [comment] 2021-08-13 00:59
Date field. Now i will show you something weird. Lol. The date field reads the wrong date but the timestamp reads the correct date. so weird

**Comment by supermx1** [comment] 2021-08-13 01:16
https://exploringjs.com/impatient-js/ch_dates.html

**Comment by supermx1** [comment] 2021-08-13 01:45
I think DB_TIMEZONE="+00:00" worked out for me. I Will do further testing, Maybe in the future, we can add a field in project settings to include a timezone setting. Like to select a timezone. So the system enforces it.

**Comment by rijkvanzanten** [comment] 2021-08-13 01:49
> Date field. Now i will show you something weird. Lol. The date field reads the wrong date but the timestamp reads the correct date. so weird

That's because one stores with timezone information, and the other saves/retrieves date values as is—or rather, it should.

Not sure what you're trying to say with that link. I'm well aware of date madness in JS, especially when you throw in some non-utc server time zones, especially especially when you throw in some "helpful" automation by the database itself or it's connection library 🙅🏻‍♂️

**Comment by supermx1** [comment] 2021-08-13 01:56
Oh, I only shared the link as a reference. It got me confused because in the link that issue was mention. When one selects one date but another value is read. 

Mahn, you geniuses are on another level. This shattered my newbie mind and still is. Thanks for the help. Still don't know if it is a bug or something else

**Comment by rijkvanzanten** [comment] 2021-08-13 13:21
> I think DB_TIMEZONE="+00:00" worked out for me. I Will do further testing, Maybe in the future, we can add a field in project settings to include a timezone setting. Like to select a timezone. So the system enforces it.

This sounds like the correct solution to me. Without it, I _think_ the `mysql` package will do some magic under the hood to be "helpful".

I also had to add a similar thing to the `mssql` handler to disable it's magic for this:

https://github.com/directus/directus/blob/415f6d1a94c4cf01dec7bc6504024f4f512d1dc8/api/src/database/index.ts#L74-L78

I'll have to spend some time checking every database driver using different timezone configurations to document all these small differences (such a tedious task 😫 )

**Comment by rijkvanzanten** [comment] 2021-08-13 13:29
Also, I will leave this issue open as a reminder to see if we should hardcode `DB_TIMEZONE` to be `+00:00` at all times 🤔

**Comment by supermx1** [comment] 2021-08-13 19:26
Oh yes, I think different vendors handle timezone weirdly. You guys should consider making it a dropdown select or something of that nature where directus tries to guess or get your timezone, but if it can't get it accurately or for some reason you want you work with a different timezone, you the user can select or enter the desired timezone. Which then forces Directus to use the specified timezone.

**Comment by rijkvanzanten** [comment] 2021-08-13 19:28
@supermx1 The problem is... Directus itself doesn't handle any timezones on purpose. `datetime` / `date` fields are send to the database exactly the way they're entered, exactly to prevent this sort of weirdness :C 

In this particular case though, it seems like the default value for `timezone` in the `mysql` connection will make it automatically change these dates to be helpful

**Comment by neo7-studio-web** [comment] 2021-08-21 19:23
I have the exact same problem since 0.89 : date OK in database but one day less when saving. It wasn't the case in previous versions. Something changed in the app that is causing this issue. DB_TIMEZONE="+00:00" didn't work out for me. 1 full day offset problem doesn't sound like an timezone problem.

**Comment by m0rtis0** [comment] 2021-08-25 09:10
Same problem here, it is really bad because even if you don't change anything on the date itself, every time I save an item it Subtracts 1 from all date fields. I tried the `DB_TIMEZONE="+00:00"` but no avail, i am using postgres with Timezone set to Europe/Berlin, my local timezone. Any ideas? When I look at the database, the entry is still one day more than in directus, but it also gets decreased whenever I save in directus... WTF is going on xD

**Comment by m0rtis0** [comment] 2021-08-25 09:31
Could be this? https://stackoverflow.com/questions/31608368/nodes-postgres-module-pg-returns-wrong-date

**Comment by supermx1** [comment] 2021-08-25 09:32
> Same problem here, it is really bad because even if you don't change anything on the date itself, every time I save an item it Subtracts 1 from all date fields. I tried the `DB_TIMEZONE="+00:00"` but no avail, i am using postgres with Timezone set to Europe/Berlin, my local timezone. Any ideas? When I look at the database, the entry is still one day more than in directus, but it also gets decreased whenever I save in directus... WTF is going on xD



> Same problem here, it is really bad because even if you don't change anything on the date itself, every time I save an item it Subtracts 1 from all date fields. I tried the `DB_TIMEZONE="+00:00"` but no avail, i am using postgres with Timezone set to Europe/Berlin, my local timezone. Any ideas? When I look at the database, the entry is still one day more than in directus, but it also gets decreased whenever I save in directus... WTF is going on xD

You have to play around with the timezone to find the one that works for you. +01:00 upwards or even downwards.

**Comment by m0rtis0** [comment] 2021-08-25 09:33
Yeah will try

**Comment by m0rtis0** [comment] 2021-08-25 09:36
I tried from +11:00 to -11:00 with no result, it looks like the variable is not doing anything

**Comment by m0rtis0** [comment] 2021-08-25 09:36
Is `DB_TIMEZONE` even setup for Postgres?

**Comment by supermx1** [comment] 2021-08-25 09:45
You have to put it in the .env file and restart directus. Then everytime you tryout s née timezone, restart directus. I think another thing I kept checking was the date stored in the database, matching it with what directus displays. Then I created a test collection for this where I can just be adding items with various dates to check for consistency.

**Comment by m0rtis0** [comment] 2021-08-25 09:46
> You have to put it in the .env file and restart directus. Then everytime you tryout s née timezone, restart directus. I think another thing I kept checking was the date stored in the database, matching it with what directus displays. Then I created a test collection for this where I can just be adding items with various dates to check for consistency.

That is what I did, too.... Edit .env, restart, test. Again and again but nothing works

**Comment by supermx1** [comment] 2021-08-25 09:51
Can you screen record your process? So the core team can see you are going about your inputs and testing out the timezone adjustments

**Comment by m0rtis0** [comment] 2021-08-25 10:02
I think I found the problem! It was not the timezone all along, when I set the logging to trace and look at the query directus makes into revisions when I update the field, it is already wrong there!

**Comment by m0rtis0** [comment] 2021-08-25 10:13
Yeah will do

**Comment by rijkvanzanten** [comment] 2021-08-25 15:04
FWIW, `DB_TIMEZONE` comes from the `mysql` package options, so I can't guarantee that's the exact name for Postgres.

As a matter of fact, I believe `libpq` uses "TZ" as the option name, so maybe try `DB_TZ` ?

**Comment by KnowHowHere** [comment] 2021-08-30 04:01
Can I offer another cause/solution for this?

In my case I'm using MariaDB, the server timezone is Australia/Sydney and I'm using a DateTime field. I'm using DateTime over Timestamp because I want to set a specific DateTime (happens to be in UTC) and not have it change based on the timezone of an application reading it or the server, regardless of what you set @@GLOBAL.time_zone or SELECT @@SESSION.time_zone to.

However the API assumes that DateTime fields are always UTC (see services/payload.js::processDates).

ProcessDates does this wierd thing where when setting a DateTime value it translates what it assumes is a UTC DateTime into a Local DateTime for storage and then when reading the data back out it translates it back again.

This works ok for me (in a way, I'll get back to my main issue later) because I have created a custom datetime interface & display that works with UTC, so I'm sending into Directus a UTC DateTime and getting back a UTC DateTime. But I think the issue in this thread is that you are sending in a local DateTime and getting back a UTC DateTime.

For me, while this double shuffle works fine if I only access the data from Directus, it means that the value in the database isn't the value I set (in my case it’s 10 hours in advance for Sydney), so other services reading the database directly (BI/Analytics tools) can no longer assume that the value in this field is UTC, they have to know the location of my server and compensate.

It looks like this behaviour was partially introduced (arguably fixed) in commit #ce234f3 (read logic was updated to translate the DateTime back to UTC) but the main culprit I think was some way back further (I can't find the exact commit) where the set logic assume DateTime is UTC. This wasn’t an issue earlier in V9, it only cropped up for me when I recently did an update.

If I change processDates to simply work with Date (i.e replace value.getUTC* with value.get* in the read logic and remove Date.UTC in the set logic), everything works for me. If I set a local DateTime I get a local datetime, if I set a UTC DateTime I get one back and most importantly, what I set is what ends up in the database.

Can I please make a request that the API not make any assumptions about the timezone of Date or DateTime values (this issue also affects date which currently sets with a conversion to UTC but reads as local) being passed in and simply set/get the value supplied?

**Comment by rijkvanzanten** [comment] 2021-08-30 14:00
@KnowHowHere If you don't use `getUTC*` on the node side, it'll actually do the date conversion based on the timezone of the Node process itself, which causes issues in other DBs.

The main issue we're facing here is that different database driver packages (eg `mysql` vs `pg` vs `node-sqlite` vs `node-oracle` etc) handle date insertions differently. F.e. `tedious` for MS SQL used to always convert every inserted date to "UTC" (or rather what it thought UTC was supposed to be), which is different from other driver packages. It seems like MySQL as a database server itself does some conversion magic on the connection as well, which can be altered with the "DB_TIMEZONE" setting. 

> Can I please make a request that the API not make any assumptions about the timezone of Date or DateTime values (this issue also affects date which currently sets with a conversion to UTC but reads as local) being passed in and simply set/get the value supplied?

I wish it was this easy. The different databases use slightly different formats for DateTime as well, so we couldn't just pass on the input string (postgres is iso8601 compatible, mysql uses `yyyy-mm-dd hh:mm:ss`, oracle uses `30-AUG-21` etc).

The node driver packages for these databases all accept inputting a JS Date object from node, which abstracts away those differences, _however_ JS's Date does all sorts of unexpected things under the hood as well (for example that getUTC* vs get* difference). 

I think the next best approach will be to do a thing similar to the geometry types where we add helpers for the different DB types to format datetime/timestamp values into the respective string representation for the different databases. _However_, that might prove tricky as well, as you can often change the default date format that's used in the database. (We might be able to rely on string-to-date helper functions for that though, like `STR_TO_DATE`)

**Comment by KnowHowHere** [comment] 2021-08-30 23:28
Thanks @rijkvanzanten, does it really do a date conversion?  Date() *assumes* local when you create a date, but that's different to converting (it doesn't know the original TZ). Arguably it does a conversion if the server TZ is different to the user but I'll get to that later.

Here's the current logic in question:

```javascript
const [date, time] = value.split('T');
const [year, month, day] = date.split('-');
const [hours, minutes, seconds] = time.substring(0, 8).split(':');
payload[name] = new Date(Date.UTC(Number(year), Number(month) - 1, Number(day), Number(hours), Number(minutes), Number(seconds)));
```
This code still assumes the original string was local, but then does an explicit conversion to UTC.  I'm not sure that this conversion is helpful. Most importantly if the original string *was* UTC, this conversion via local and out to UTC actually changes it to something that is neither UTC nor the original TZ, nor the TZ of the server.

At least without the Date.UTC if the user supplied "2021-09-01T00:00:00" then that is what is saved (regardless of the original person's TZ or the server).

The most robust solution I think (which is what I've attempted to do with a custom datetime interface/display) is to always work with UTC dates.  With a custom interface you can convert to UTC in the browser because the browser (should) know the users TZ (hello Firefox anit-fingerprinting) and be able to convert to UTC. The same with the display extension in reverse.

For people using the API, it's just a matter of people being told that all dates sent in are expected to be UTC (or ISO datetime strings with timezones) and of course all dates coming out are UTC.

There is still an effort to work with different databases and the different implementations of DateTime vs Timestamp, so I'm not trying to trivialise the effort involved, but it would mean your DB logic always knew that what it was receiving was a UTC date. At the moment it's pretty non-deterministic what it's receiving.

Presently someone in TZ +8 sends the api a date such as "2021-09-01T00:00:00" which the server (in my case, Sydney) processes as though it's TZ +10 and with the present logic, takes 10 hours off and stores "2021-08-31T14:00:00" in the DB. At least if it stored the date as supplied it's understandable what you are looking at in the DB.

If the API only accepted UTC dates (or ISO datetime strings with timezones) and the interface and display extensions converted to/from UTC in the browser, then the job of setting the correct value in the DB is greatly simplified.

**Comment by jahead** [comment] 2021-09-27 09:12
@rijkvanzanten have you considered using 
https://moment.github.io/luxon/#/
to help normalize your dates/datetimes?

I just got burned with this, awkwardly, with being based sydney too ha.

Basic setup. 
* Azure SQL Server (stock settings) on Australia East (basically Sydney). 
* local host, clean new project (i'm Sydney based, so OS clock is sydney time)
* one collection with automatic created field.
* firefox admin view

Results. 
Admin view
![image](https://user-images.githubusercontent.com/5070464/134872963-629fcfdc-4d70-46f5-9285-e42eba906eb2.png)

export 
![image](https://user-images.githubusercontent.com/5070464/134873451-f850aa1a-b43e-4b72-970a-2fdfadce169b.png)

API
![image](https://user-images.githubusercontent.com/5070464/134873487-e6a180f4-cfd3-40cd-8ae3-8472ff2b984f.png)

database
![image](https://user-images.githubusercontent.com/5070464/134873553-3681c897-0e18-43fd-a4b3-44f86e65a367.png)

it's unclear from the docs how dates are currently handled. 
And I'm not sue how to fix this issue. (any recommendations?)
The date should either be saved at  2021-09-27T17:58:48.8266667+10:00 or 2021-09-27T09:58:48.8266667+00:00.

I'd expect the my automatic created_at fields to be at +Z, and/or agnostic to server location, directus(us)/directus(AusE) should have consistent created_at/updated_at if the servers clocks are in sync. 

I haven't looked at the code but I suspect the save isn't respecting the timezone properly, but the vue's relative time is, so it's been saved as a Z0, but the admin view is converting that Z0 to my locale which is set to Z10.

I haven't really seen these issues when doing my own API's on expressjs+typegoose/typeorm, or .net+entity framework (different world) but this shouldn't be so hard as it;s currently presenting itself, haha 🌵

**Comment by rijkvanzanten** [comment] 2021-09-27 14:08
> ) but this shouldn't be so hard as it;s currently presenting itself, haha 🌵

You'd be very surprised about that @jahead 😭  The issue isn't how we're handling dates in NodeJS, as like you correctly stated, that's easy enough to handle with a bit of help from luxon/moment/date-fns etc. The problem here is that every database handles dates slightly differently itself (some auto-convert TZ, some save everything as number-timestamps, some don't have TZ support at all), and to make matters worse, these differences can be configured on the _connection_ level, so different configuration flags for different DB connections makes things work differently too. My comment https://github.com/directus/directus/issues/7383#issuecomment-908367459 has a TL;DR

**Comment by jahead** [comment] 2021-09-28 04:04
@rijkvanzanten 

I understand your pain, and not trying to trivialize it, was more suggesting if there is any prior art in other ORM's/stacks that have solved this problem. 

Our main issue isn't the custom fields as we can force our internal services to use UTC time etc/whatever the solution, it's the *auotomatic* `date_created`/`date_updated` fields aren't working as expected. And was just giving you another bug 'report' on how this experience hasn't gone as expected. 

we don't mind in doing some configurations/custom extension/PR work in making the automatic fields behave in a way that's expected, we just couldn't find good documentation on how to do that for Azure SQL Server.

So if you have a suggestion/direction we can probably feel in the gaps/help out where appropriate.

**Comment by koksikus** [comment] 2021-10-29 19:25
Please help!!!

**Comment by koksikus** [comment] 2021-10-30 08:28
Can anyone help with displaying "the day before"?

**Comment by supermx1** [comment] 2021-10-30 19:53
> Can anyone help with displaying "the day before"?

Did you follow the above fix? 

Setting your env file... The fix I used applied to MYSQL, but I don't believe MSSQL will be any different

**Comment by koksikus** [comment] 2021-11-01 14:08
which solution? This with "start-directus.sh"... I don't know how to implement this solution, where to enter it.  Why has no changes been made in Directus?

**Comment by danilopolani** [comment] 2021-11-03 11:27
> which solution? This with "start-directus.sh"... I don't know how to implement this solution, where to enter it. Why has no changes been made in Directus?

Create a new file called `start-directus.sh` in your directus folder and paste into it:

```bash
#!/bin/sh
export TZ=UTC
npx directus start
```

 Basically it will set the server timezone to `UTC` and will start a directus instance.
Then, instead of running `npx directus start`, you must use `./start-directus.sh`. If it gives you error run `chmod +x start-directus.sh` to make it executable.

Note that I've removed `screen -S directus` because it requires you to have `screen` installed in your system (won't work on Windows) and, IMHO, it's better to manage it with PM2 to automatically restart it and monitor it since it's a Node app, instead of just putting it into a detached screen.

**Comment by domdus** [comment] 2021-11-04 00:03
I set node timezone right at the start script in `package.json` to fix it for postgres:

`"start": "TZ=UTC npx directus start",`

**Comment by jrvidotti** [comment] 2021-11-19 19:02
I my case my computer is set to GMT-4 and running Docker Postgres set to UTC. I had to set TZ="GMT-4" in .env file (or command line) to solve the problem. My dates (without time) are set correctly in DB and displayed correctly in Directus.

![image](https://user-images.githubusercontent.com/5623041/142677133-0c71e232-cc93-4537-9004-80055b2652d1.png)

**Comment by davidsandoz** [comment] 2021-12-29 16:03
On my end (MySQL), to make it work so that the date in the DB (type `DATE`) and the date shown in the UI match, I had to set `DB_TIMEZONE="Europe/Zurich"` (timezone of the server) in the `.env` file.

Setting `TZ=UTC` or `TZ=Europe/Zurich` before `npx directus start` didn't change anything.

Now, the only downside, is that the timestamps saved for `date_created` and `date_updated` on the items are always one hour before when the event happened.

**Comment by steponavichus** [comment] 2022-01-11 10:58
But the problem persists on the add record form

Default value is now()

On form value = empty

![image](https://user-images.githubusercontent.com/799781/148930534-1761cc78-27a4-45c6-84c6-723a16d75d67.png)

**Comment by KnowHowHere** [comment] 2022-01-12 05:38
While some people have had limited success forcing their servers to UTC or other specific timezones, I still maintain that the easiest way to avoid all the issues outlined in this thread is simply not to mess with the date. Just store what the API is given. Attempting to coerce the value through UTC will always result in something unexpected.

One of the great things about Directus is that you can use it over the top of an existing database and one that potentially has BI tools or other logic or interfaces querying or manipulating its data directly. If I pass a datetime such as "2022-01-12T00:00:00" to the API I need that data to be stored in the database as is. Otherwise querying the database directly from a BI application for example will result in different dates being returned than what was passed into the Directus API. There's no way for Directus to know what timezone I intended that date to be, so there's no way to reliably convert it to/from local/UTC.

If you treat it as a local datetime however, then when you convert it to a javascript date and back to a string for inserting into the database, the string will still be "2022-01-12T00:00:00".

In the case of mySQL/MariaDB the ORM will just format it like this: 'YYYY-MM-DD hh:mm:ss'

If the node server is in the same timezone as the database the above will work out of the box. If it isn't then we can handle that by setting the connection / session timezone rather than trying to manipulate the date itself. This is particularly important when using DateTime vs Timestamp as it still allows accurate storage of the original date in either field type.

I'm sure that @rijkvanzanten is right that this isn't as simple as it should be given the permutations of timezones (user, server, database) and DBMS and I fully admit I have limeted experience with DBMS other than mysql, mariadb and postgres, so I'm sure there are curly edge cases that need solving, but attempting to solve this by arbitrarily manipulating the input datetimes seems fraught.

While everyone will have different needs, the solution for me is (and this should work for any mariadb/mysql setup no matter what timezone your database, node server or user is in):

* Remove coercion through UTC (edit directus/api/src/services/payload.ts:processDates() to simply work with Date by replacing value.getUTC* with value.get* in the read logic and remove Date.UTC in the set logic)
* Use mysql DateTime instead of Timestamp (this is important)
* Always send UTC timestamps to the API

This way I always give the API a UTC datetime and I always get back a UTC datetime. Also the actual datetime I sent to the API is what's in the database so querying the db from other sources is also consistent.

**Comment by benhaynes** [comment] 2022-01-12 12:21
@KnowHowHere — I'm always a fan of flexibility, as long as it's warranted and doesn't sacrifice usability. I also agree that Directus needs to remain transparent and unopinionated regarding the database. Of course, I defer to @rijkvanzanten on the best course of action here, but I don't think it's unreasonable to add a configuration option to save _user_ dates "as-is" (system dates will still be stored in UTC for internal reasons). Not sure if this would be global (env file) or at the field/interface level... but the option to save WYSIWYG dates makes sense to me.

**Comment by rijkvanzanten** [comment] 2022-01-12 15:33
> ... simply not to mess with the date. Just store what the API is given. 

I agree, _but..._ we're not the only thing that interacts with those dates :| The database connection packages themselves _also_ do date transformation magic, which may or may not be configurable (eg `mysql` will handle dates differently from `tedious` (mssql), etc). This makes it impossible for the Directus API to ignore the values completely, as that would cause inconsistencies between the different DB vendors 🤔

**Comment by rijkvanzanten** [comment] 2022-01-12 15:33
In any case, @licitdev is on the case. He already put together a PR to implement your first point https://github.com/directus/directus/pull/10956

> Remove coercion through UTC (edit directus/api/src/services/payload.ts:processDates() to simply work with Date by replacing value.getUTC* with value.get* in the read logic and remove Date.UTC in the set logic)

so that's a good start 🙂

**Comment by loongmxbt** [comment] 2022-01-24 05:09
Same issue. Created on local time zone GTM+8, which date_created is "2022-01-24T05:02:03.019Z" right. But `date` choose 2022-01-24, when save and edit, it goes back to 2022-01-23. 
Same in both mysql5.7 and postgres14. 
```
{"data":[{"id":1,"status":"draft","sort":null,"user_created":"855f6b49-aed9-43eb-9d50-fbe5fe0c034b","date_created":"2022-01-24T05:02:03.019Z","user_updated":"855f6b49-aed9-43eb-9d50-fbe5fe0c034b","date_updated":"2022-01-24T05:02:21.386Z","name":"123","number":"123","date":"2022-01-23"}]}
```

**Comment by jaycammarano** [comment] 2022-01-24 14:05
> Same issue. Created on local time zone GTM+8, date_created is "2022-01-24T05:02:03.019Z", which is right. But in my `date` field I choose `2022-01-24`, when save and edit, it goes back to `2022-01-23`. Same in both mysql5.7 and postgres14.
> 
> ```json
> {"data":[{"id":1,"status":"draft","sort":null,
> "user_created":"855f6b49-aed9-43eb-9d50-fbe5fe0c034b",
> "date_created":"2022-01-24T05:02:03.019Z",
> "user_updated":"855f6b49-aed9-43eb-9d50-fbe5fe0c034b",
> "date_updated":"2022-01-24T05:02:21.386Z",
> "name":"123",
> "number":"123",
> "date":"2022-01-23"
> }]}
> ```

The fix is in the works! Hopefully it wont be too long until this is no longer an issue.

**Comment by nichols-green** [comment] 2022-02-24 23:06
My team is also experiencing this, specifically with SQL Server. Is there an update on the progress?

**Comment by azrikahar** [comment] 2022-02-25 07:13
> My team is also experiencing this, specifically with SQL Server. Is there an update on the progress?

@nichols-green there can be quite a few moving parts, particularly when there's multiple database vendors involved.

That being said, as https://github.com/directus/directus/issues/7383#issuecomment-1011167760 mentioned, there is PR in the works to tackle this issue 👍

---

[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by abdonrd** [comment] 2022-03-01 20:46
Following this issue, as we are also running into this issue!

**Closed** 2022-04-06 20:15 UTC
Labels: API, Documentation, Improvement

**Comment by zimmersi** [comment] 2022-04-07 16:02
hi,
I have set the mysqljs connection option dateStrings to true with a DB_ env variable. Seems that this solved it for me.
https://github.com/mysqljs/mysql#connection-options
