### ISSUE TITLE
Unable to import DB table as collection

### ISSUE THREAD

**Issue by rogersanick** [directus/directus#10287] opened 2021-12-03 20:18 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When adding an existing DB table as a Directus collection an error is displayed suggesting that I do not have appropriate permissions:

```[FORBIDDEN] You don't have permission to access this.```

I am signed in as an admin account and should have access to all documents. 

### To Reproduce

1. npm init directus-project my project
2. npx directus start
3. npm upgrade
4. npm install
5. npx directus database migrate:latest
6. npx directus start

7. Go to settings
8. Configure db table as collection
9. Go to modify collection 
10. Unable to access error is displayed

### Errors Shown

[FORBIDDEN] You don't have permission to access this.
content_copy

- vendor.c46e17d6.js:5 TypeError: Cannot read properties of null (reading 'field')
    at Proxy.TY (index.b5d16ba8.js:339)
    at d5 (vendor.c46e17d6.js:2)
    at _3.ut [as fn] (vendor.c46e17d6.js:2)
    at _3.run (vendor.c46e17d6.js:2)
  ...
Show 50 more frames

- vendor.c46e17d6.js:70 GET http://localhost:8055/items/governor_alpha_bravo_proposal?limit=25&page=1&meta[]=filter_count&meta[]=total_count 403 (Forbidden)

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

v14.18.0

### What database are you using?

Postgres 11.13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-12-03 20:41
@rogersanick Could you provide some information on the table that already existed that you're trying to use? A SQL query to create it would be most useful, as it allows us to test it with the exact schema you're using.

**Comment by rogersanick** [comment] 2021-12-03 21:02
| table\_catalog | table\_schema | table\_name                      | column\_name          | ordinal position | column\_default                                                                     | is\_nullable | data\_type               |
| -------------- | ------------- | -------------------------------- | --------------------- | ---------------- | ----------------------------------------------------------------------------------- | ------------ | ------------------------ |
| agora          | governance    | governor\_alpha\_bravo\_proposal | proposal\_id          | 3                | nextval('governance.governor\_alpha\_bravo\_proposal\_proposal\_id\_seq'::regclass) | NO           | bigint                   |
| agora          | governance    | governor\_alpha\_bravo\_proposal | framework\_id         | 4                |                                                                                     | NO           | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | asset\_slug           | 5                |                                                                                     | YES          | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | proposer\_address     | 6                |                                                                                     | NO           | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | contract\_address     | 7                |                                                                                     | NO           | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | state                 | 8                |                                                                                     | NO           | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | state\_history        | 9                |                                                                                     | YES          | json                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | eta                   | 10               |                                                                                     | YES          | timestamp with time zone |
| agora          | governance    | governor\_alpha\_bravo\_proposal | start\_block          | 11               |                                                                                     | YES          | bigint                   |
| agora          | governance    | governor\_alpha\_bravo\_proposal | end\_block            | 12               |                                                                                     | YES          | bigint                   |
| agora          | governance    | governor\_alpha\_bravo\_proposal | start\_timestamp      | 13               |                                                                                     | YES          | timestamp with time zone |
| agora          | governance    | governor\_alpha\_bravo\_proposal | end\_timestamp        | 14               |                                                                                     | YES          | timestamp with time zone |
| agora          | governance    | governor\_alpha\_bravo\_proposal | for\_votes            | 15               |                                                                                     | YES          | double precision         |
| agora          | governance    | governor\_alpha\_bravo\_proposal | against\_votes        | 16               |                                                                                     | YES          | double precision         |
| agora          | governance    | governor\_alpha\_bravo\_proposal | txn\_hash             | 17               |                                                                                     | NO           | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | targets               | 18               |                                                                                     | YES          | ARRAY                    |
| agora          | governance    | governor\_alpha\_bravo\_proposal | signatures            | 19               |                                                                                     | YES          | ARRAY                    |
| agora          | governance    | governor\_alpha\_bravo\_proposal | calldatas             | 20               |                                                                                     | YES          | ARRAY                    |
| agora          | governance    | governor\_alpha\_bravo\_proposal | description           | 21               |                                                                                     | YES          | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | title                 | 23               |                                                                                     | YES          | text                     |
| agora          | governance    | governor\_alpha\_bravo\_proposal | abstain\_votes        | 25               |                                                                                     | YES          | double precision         |
| agora          | governance    | governor\_alpha\_bravo\_proposal | framework\_type       | 26               |                                                                                     | YES          | USER-DEFINED             |
| agora          | governance    | governor\_alpha\_bravo\_proposal | normalized\_calldatas | 27               |                                                                                     | YES          | jsonb                    |
| agora          | governance    | governor\_alpha\_bravo\_proposal | last\_ingested\_date  | 28               | now()                                                                               | NO           | timestamp with time zone |
📋 Copy
Clear

**Comment by rogersanick** [comment] 2021-12-03 21:02
@rijkvanzanten - hope that helps^ that's the schema of the table as it is currently defined.

**Comment by rijkvanzanten** [comment] 2021-12-03 21:10
@rogersanick Thanks! Just to confirm, that column `proposal_id` also has the primary key constraint next to the auto increment default val?

**Comment by rogersanick** [comment] 2021-12-06 14:39
@rijkvanzanten - yep! That is the case.

**Comment by rogersanick** [comment] 2021-12-06 14:40
Apologies @rijkvanzanten - didn't mean to close this ticket. The three column schemas in question are screen shotted below. 

<img width="1002" alt="Screen Shot 2021-12-06 at 9 40 27 AM" src="https://user-images.githubusercontent.com/16504493/144865646-c8d29f19-052e-4b04-b431-2f4438718c2b.png">

**Comment by rogersanick** [comment] 2021-12-08 14:30
@rijkvanzanten - does this answer your question? Let me know if any more information is required?

**Comment by rijkvanzanten** [comment] 2021-12-08 15:32
Could you provide a SQL dump of the table? This screenshot shows effectively three "primary" keys on the same table (as nextval() is usually used for auto-increment ids), which might be the reason why Directus is failing (we don't support composite primary keys at this point)

**Comment by rijkvanzanten** [comment] 2021-12-14 16:22
Hi @rogersanick! Apologies, I'm looking for the SQL dump that creates the table schema, not the content of the table. Should've clarified that a bit more 🙂 

I think your original problem lies in the table schema rather than the content.

You should be able to extract that with

```
pg_dump -t governor_alpha_bravo_proposal > dump.sql
```

or using a GUI database administration tool

**Comment by rogersanick** [comment] 2021-12-17 01:00
Hey @rijkvanzanten - no problem at all. I very much appreciate your help and I'm enjoying exploring Directus. That makes sense to me, here is the sql dump from the GUI database admin tool, let me know if this helps. I can absolutely get one from the direct from the DB as well, it just might take a little longer:

`-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE governance.proposition (
    row_id bigint NOT NULL DEFAULT nextval('governance.proposition_row_id_seq'::regclass),
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    governing_body_id uuid NOT NULL REFERENCES governance.governing_body(id) ON DELETE CASCADE ON UPDATE CASCADE,
    snapshot_proposal_id text REFERENCES governance.snapshot_proposal(id) ON DELETE CASCADE ON UPDATE CASCADE,
    governor_alpha_bravo_proposal_id uuid REFERENCES governance.governor_alpha_bravo_proposal(id) ON DELETE CASCADE ON UPDATE CASCADE,
    importance proposition_importance_type NOT NULL,
    category text NOT NULL,
    sub_category text NOT NULL,
    title text NOT NULL,
    status text NOT NULL,
    resources jsonb,
    arguments jsonb,
    prelim_discussion_id uuid REFERENCES governance.prelim_discussion(id) ON DELETE CASCADE ON UPDATE CASCADE,
    dead_after_prelim_discussion boolean DEFAULT false,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    gnosis_safe_execution_id uuid REFERENCES governance.gnosis_safe_execution(id) ON DELETE CASCADE ON UPDATE CASCADE,
    snapshot_proposal_id2 text REFERENCES governance.snapshot_proposal(id) ON DELETE CASCADE ON UPDATE CASCADE,
    snapshot_proposal_id3 text REFERENCES governance.snapshot_proposal(id) ON DELETE CASCADE ON UPDATE CASCADE,
    details json,
    inception_date timestamp with time zone NOT NULL DEFAULT now(),
    key_community_argument_details json
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX proposition_pkey ON governance.proposition(id uuid_ops);`

**Comment by riscie** [comment] 2021-12-21 08:54
It seems like we are running into the same problem as @rogersanick. I was able to find out that the problem arrived after upgrading from `9.0.1` to `9.1.1` (newer versions don't fix the problem). The weird thing is, we only have this error on one specific collection. All other collections work.

Some more information:
- We are also using an existing database.
- When looking at the Data Model of the collection, no fields show up.
- We are alos using an admin user with all rights.

Let me know if I should provide further details and thank you in advance for any help.

**Comment by rijkvanzanten** [comment] 2022-01-25 00:08
I wasn't able to reproduce with your shared dump @rogersanick, as I'm missing a lot of the related tables and custom types (like `proposition_importance_type`). Could you confirm this problem still exists, and wasn't caused by the caches not having been flushed? 

@riscie Would you be able to share a SQL dump with the offending table for us to reproduce? Does your table use a custom type as well?

**Comment by rijkvanzanten** [comment] 2022-01-25 00:09
I'll close this for now, as none of our team have been able to reproduce this. We'll reopen and happily keep discussion this once more information arises 🙂

**Closed by rijkvanzanten** 2022-01-25 00:09 UTC
Labels: Needs More Info, Bug (Potential)

**Comment by jzebedee** [comment] 2022-04-06 23:28
> Could you provide a SQL dump of the table? This screenshot shows effectively three "primary" keys on the same table (as nextval() is usually used for auto-increment ids), which might be the reason why Directus is failing (we don't support composite primary keys at this point)

Please make this documented front and center. As of right now, loading a database with a composite PK will make loading the collection fail with an opaque permissions error and no other diagnostic information. It's not documented in the minimum requirements that schemas must be laid out with only a single PK.

**Comment by benhaynes** [comment] 2022-04-06 23:29
CC @erondpowell

**Comment by jzebedee** [comment] 2022-04-06 23:36
> I'll close this for now, as none of our team have been able to reproduce this. We'll reopen and happily keep discussion this once more information arises 🙂

I'd be happy to share a repro.

1. Download the attached 
[uscis.zip](https://github.com/directus/directus/files/8436326/uscis.zip) and extract the contained `uscis.db` SQLite DB to C:\downloads or a suitable temp folder, then update the volume information below
2. Start up with the latest docker image
3. View collections
4. Collections imported from tables with a single PK work (e.g., Forms, Offices), but tables that contain a composite PK do not (e.g., Processing Time)

```powershell
docker run `
  -p 8055:8055 `
  -e KEY=<blah> `
  -e SECRET=<blah> `
  -e ADMIN_EMAIL="admin@example.com" `
  -e ADMIN_PASSWORD="<blah>" `
  -e DB_CLIENT="sqlite3" `
  -e DB_FILENAME="/downloads/uscis.db" `
  --volume C:\downloads:/downloads `
  directus/directus
```

**Comment by jzebedee** [comment] 2022-04-06 23:49
I just noticed that this will also fail if a table has no PKs defined at all, like in tables that just use `rowid` as an implicit PK

**Comment by SiftOleksandrKorzhov** [comment] 2023-06-12 23:00
Head the same issue =(

@rijkvanzanten Advice please, is there any way to work with composite primary keys?
