### ISSUE TITLE
Flows: Read Data doesn't save collection when using "Toggle Raw Editor"

### ISSUE THREAD

**Issue by ched-dev** [directus/directus#18974] opened 2023-06-23 00:36 UTC
### Describe the Bug

When I create a Flow with a Read Data operation using a system collection, it does not save the flow with the correct collection if I use the "Toggle Raw Editor".

Note it works fine when using the "Edit Raw Value" from the dropdown options instead.

### To Reproduce

- On any existing flow, create a new Read Data operation
- In the Collection field, use the curly brace icon to "Toggle Raw Editor"
- Type in a system collection name (Ex: `directus_users`)
- Save the operation

Error: Saves without updating the Collection

Screen Recording:

https://github.com/directus/directus/assets/73146636/b2f8e799-6115-4d7f-98d5-6985a93ee272

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-06-23 08:18
Duplicate of https://github.com/directus/directus/issues/18315

**Closed by br41nslug** 2023-06-23 08:18 UTC
