### ISSUE TITLE
websocket seems to be broken in 11.1

### ISSUE THREAD

**Issue by aliemba** [directus/directus#23704] opened 2024-09-20 18:38 UTC
### Describe the Bug

When sending auth it does not return auth sucess. 

### To Reproduce

Send this
```
 ws.onopen = function (e) {
                 console.log("OPEN", e);
                 ws.send('{"type":"auth","email":"test@test.dk","password":"realpassword"}');
};

```
With a known good email/password : seems to be a success - I get no "auth" timeout annyway- but I det no auth sucess at all. Subsequent quereries are silent. ws i not disconnected

Sending af non valid email/pass returns correct

`{"type":"auth","status":"error","error":{"code":"AUTH_FAILED","message":"Authentication handshake `failed."}}`

### Directus Version

v11.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgress

**Comment by ComfortablyCoding** [comment] 2024-09-22 02:55
Thanks for opening this issue! However this is a duplicate of an existing issue https://github.com/directus/directus/issues/23661.

I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to https://github.com/directus/directus/issues/23661 for future updates.

**Closed by ComfortablyCoding** 2024-09-22 02:55 UTC
