### ISSUE TITLE
Custom role GUID issues (no admin access) since 9.11.1

### ISSUE THREAD

**Issue by aaron-manning** [directus/directus#13957] opened 2022-06-17 10:28 UTC
### Describe the Bug

Custom GUID's (eg 00000000-0000-0000-0000-000000000001) have worked up until  9.11.1 (confirmed working on 9.11.0)

The above no longer works on 9.11.1
Also tested 9.12.2 and doesn't work.

I have been using these as memorable identifiers for seed / test data.
It appears that something changed in 9.11.1 that no longer allows the following type of GUID's to work for roles

00000000-0000-0000-0000-000000000001
00000000-0000-0000-0000-000000000002
00000000-0000-0000-0000-100000000000
10000000-0000-0000-0000-000000000000
etc
These *should* be valid GUID's

### To Reproduce

Through some trial and error, the following DO work as GUID's for roles.

00000000-0000-1000-0000-000000000000
and
00000000-0000-2000-0000-000000000000

but other values do not work, eg.
00000000-0000-3000-0000-000000000000

They stop login functioning, and you are unable to edit the role in the app.

### Errors Shown

On login after migration: No App Access

Once logged in as a user with a role that doesn't have this issue (created a new admin role in the db) and then using the dashboard to view a role that has this issue:
http://localhost:8055/roles/00000000-0000-9000-0000-000000000000
{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

14.18.1

### What database are you using?

postgres 14.3.2

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by aaron-manning** [comment] 2022-06-17 10:40
This is a blocker for me to upgrade past 9.11.0

**Comment by azrikahar** [comment] 2022-06-17 10:42
Duplicate of #13564 #13538.

Just to offer more context, `9.11.1` included the PR #13276 which validates primary keys (including UUIDs). You can refer to the comments in #13538 for more elaborate answers/rationales.

> Through some trial and error, the following DO work as GUID's for roles.
>
> 00000000-0000-1000-0000-000000000000
> and
> 00000000-0000-2000-0000-000000000000
>
> but other values do not work, eg.
> 00000000-0000-3000-0000-000000000000

We are currently using the [uuid-validate](https://github.com/microsoft/uuid-validate) package for the UUID validations. In your tests above, seems like coincidentally you're matching the current logic to extract the UUID version as seen here:

https://github.com/microsoft/uuid-validate/blob/06554db1b093aa6bb429156fa8964e1cde2b750c/index.js#L89-L98

Hence when you moved to `3`, it uses an additional check here and deems it as not a valid UUIDv3 value: https://github.com/microsoft/uuid-validate/blob/06554db1b093aa6bb429156fa8964e1cde2b750c/index.js#L75-L79

**Closed** 2022-06-17 12:18 UTC
Labels: Duplicate

**Comment by aaron-manning** [comment] 2022-06-17 12:52
Thanks for explaining.
This should have been reported as a breaking change.

**Comment by benhaynes** [comment] 2022-06-17 13:45
That said, we are formalizing a more rigid SemVer and changelog practice that will better communicate changes like this so that developers are aware of potential changes that might influence any edge-cases.
