### ISSUE TITLE
Empty collection list after schema migration

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#8377] opened 2021-09-28 10:10 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I created a local collection with two fields:
1. slug (primary key, string, slugified)
2. name

After this I took a snapshot of this schema and applied it to our staging environment. That seemed to work and I can add data to that collection in staging. However, the collection data list in the app stays empty after adding more data (added two, see screenshot)

Locally the list shows up fine after adding data.

![CleanShot 2021-09-28 at 12 06 33](https://user-images.githubusercontent.com/4633876/135067770-04c702d6-f625-4cd8-b9a0-e89acb02389b.png)

### To Reproduce

see above

### What version of Directus are you using?

RC95

### What version of Node.js are you using?

14 lts

### What database are you using?

Postgres 13

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-09-28 20:46
Not able to reproduce this on my end..

1. Setup a new fresh installation
2. Added a collection `articles` with a "Manually entered string" for it's id named `slug`
3. Added a regular string field `name`
4. Created snapshot:

<details>
<summary>Snapshot</summary>

```yaml
version: 1
directus: 9.0.0-rc.95
collections:
  - collection: articles
    meta:
      collection: articles
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
    schema:
      name: articles
      schema: dbo
      catalog: directus
fields:
  - collection: articles
    field: slug
    type: string
    schema:
      table: articles
      name: slug
      data_type: nvarchar
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      default_value: null
      is_primary_key: true
      is_unique: true
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
      is_generated: false
      generation_expression: null
    meta:
      collection: articles
      field: slug
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      group: null
      translations: null
      note: null
      conditions: null
      required: false
  - collection: articles
    field: name
    type: string
    schema:
      table: articles
      name: name
      data_type: nvarchar
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      default_value: null
      is_primary_key: false
      is_unique: false
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
      is_generated: false
      generation_expression: null
    meta:
      collection: articles
      field: name
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      group: null
      translations: null
      note: null
      conditions: null
      required: false
relations: []
```

</details>

5. Applied snapshot on an empty installation

**Comment by dstoyanoff** [comment] 2021-09-29 05:48
It reproduces for me on the languages collection. I've managed to narrow down the issue. When the snapshot is taken, it saves the following properties for the PK field:
```
"is_unique": true,
"is_primary_key": true,
```

When you apply the schema, the field gets 2 keys - both primary key, as well as unique key. This is how the table SQL looks like:
**Postgres:**
```
create table languages
(
    code varchar(255) default NULL::character varying not null
        constraint languages_pkey
            primary key
        constraint languages_code_unique
            unique,
    name varchar(255) default NULL::character varying
);
```

MariaDB:
```
create table languages
(
    code varchar(255) not null,
    name varchar(255) null,
    constraint languages_code_unique
        unique (code)
);

alter table languages
    add primary key (code);
```

There is a little difference in how Directus handles all that. 

When using Postgres, Directus would throw the error in the original issue description. When using MariaDB/MySQL, what I get is two code fields in the UI:
![image](https://user-images.githubusercontent.com/5079334/135208751-3b3bdd60-fe4c-437b-8029-19b4f10ce77e.png)

I was able to reproduce it on a clean instance. Here is the snapshot:

<details>
  <summary>snapshot.json</summary>
  
```
{
  "version": 1,
  "directus": "9.0.0-rc.95",
  "collections": [
    {
      "collection": "languages",
      "meta": {
        "collection": "languages",
        "icon": "translate",
        "note": null,
        "display_template": null,
        "hidden": false,
        "singleton": false,
        "translations": null,
        "archive_field": null,
        "archive_app_filter": true,
        "archive_value": null,
        "unarchive_value": null,
        "sort_field": null,
        "accountability": "all",
        "color": null,
        "item_duplication_fields": null
      },
      "schema": { "name": "languages", "schema": "public", "comment": null }
    },
    {
      "collection": "test_collection",
      "meta": {
        "collection": "test_collection",
        "icon": null,
        "note": null,
        "display_template": null,
        "hidden": false,
        "singleton": false,
        "translations": null,
        "archive_field": null,
        "archive_app_filter": true,
        "archive_value": null,
        "unarchive_value": null,
        "sort_field": null,
        "accountability": "all",
        "color": null,
        "item_duplication_fields": null
      },
      "schema": { "name": "test_collection", "schema": "public", "comment": null }
    },
    {
      "collection": "test_collection_translations",
      "meta": {
        "collection": "test_collection_translations",
        "icon": "import_export",
        "note": null,
        "display_template": null,
        "hidden": true,
        "singleton": false,
        "translations": null,
        "archive_field": null,
        "archive_app_filter": true,
        "archive_value": null,
        "unarchive_value": null,
        "sort_field": null,
        "accountability": "all",
        "color": null,
        "item_duplication_fields": null
      },
      "schema": { "name": "test_collection_translations", "schema": "public", "comment": null }
    }
  ],
  "fields": [
    {
      "collection": "languages",
      "field": "code",
      "type": "string",
      "schema": {
        "name": "code",
        "table": "languages",
        "data_type": "character varying",
        "default_value": null,
        "generation_expression": null,
        "max_length": 255,
        "numeric_precision": null,
        "numeric_scale": null,
        "is_generated": false,
        "is_nullable": false,
        "is_unique": true,
        "is_primary_key": true,
        "has_auto_increment": false,
        "comment": null,
        "schema": "public",
        "foreign_key_schema": null,
        "foreign_key_table": null,
        "foreign_key_column": null
      },
      "meta": {
        "collection": "languages",
        "field": "code",
        "special": null,
        "interface": "input",
        "options": { "iconLeft": "vpn_key" },
        "display": null,
        "display_options": null,
        "readonly": false,
        "hidden": false,
        "sort": null,
        "width": "half",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        "required": false
      }
    },
    {
      "collection": "languages",
      "field": "name",
      "type": "string",
      "schema": {
        "name": "name",
        "table": "languages",
        "data_type": "character varying",
        "default_value": null,
        "generation_expression": null,
        "max_length": 255,
        "numeric_precision": null,
        "numeric_scale": null,
        "is_generated": false,
        "is_nullable": true,
        "is_unique": false,
        "is_primary_key": false,
        "has_auto_increment": false,
        "comment": null,
        "schema": "public",
        "foreign_key_schema": null,
        "foreign_key_table": null,
        "foreign_key_column": null
      },
      "meta": {
        "collection": "languages",
        "field": "name",
        "special": null,
        "interface": "input",
        "options": { "iconLeft": "translate" },
        "display": null,
        "display_options": null,
        "readonly": false,
        "hidden": false,
        "sort": null,
        "width": "half",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        "required": false
      }
    },
    {
      "collection": "test_collection",
      "field": "id",
      "type": "integer",
      "schema": {
        "name": "id",
        "table": "test_collection",
        "data_type": "integer",
        "default_value": "nextval('test_collection_id_seq'::regclass)",
        "generation_expression": null,
        "max_length": null,
        "numeric_precision": 32,
        "numeric_scale": 0,
        "is_generated": false,
        "is_nullable": false,
        "is_unique": true,
        "is_primary_key": true,
        "has_auto_increment": true,
        "comment": null,
        "schema": "public",
        "foreign_key_schema": null,
        "foreign_key_table": null,
        "foreign_key_column": null
      },
      "meta": {
        "collection": "test_collection",
        "field": "id",
        "special": null,
        "interface": "input",
        "options": null,
        "display": null,
        "display_options": null,
        "readonly": true,
        "hidden": true,
        "sort": null,
        "width": "full",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        "required": false
      }
    },
    {
      "collection": "test_collection_translations",
      "field": "id",
      "type": "integer",
      "schema": {
        "name": "id",
        "table": "test_collection_translations",
        "data_type": "integer",
        "default_value": "nextval('test_collection_translations_id_seq'::regclass)",
        "generation_expression": null,
        "max_length": null,
        "numeric_precision": 32,
        "numeric_scale": 0,
        "is_generated": false,
        "is_nullable": false,
        "is_unique": true,
        "is_primary_key": true,
        "has_auto_increment": true,
        "comment": null,
        "schema": "public",
        "foreign_key_schema": null,
        "foreign_key_table": null,
        "foreign_key_column": null
      },
      "meta": {
        "collection": "test_collection_translations",
        "field": "id",
        "special": null,
        "interface": null,
        "options": null,
        "display": null,
        "display_options": null,
        "readonly": false,
        "hidden": true,
        "sort": null,
        "width": "full",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        "required": false
      }
    },
    {
      "collection": "test_collection_translations",
      "field": "languages_id",
      "type": "string",
      "schema": {
        "name": "languages_id",
        "table": "test_collection_translations",
        "data_type": "character varying",
        "default_value": null,
        "generation_expression": null,
        "max_length": 255,
        "numeric_precision": null,
        "numeric_scale": null,
        "is_generated": false,
        "is_nullable": true,
        "is_unique": false,
        "is_primary_key": false,
        "has_auto_increment": false,
        "comment": null,
        "schema": "public",
        "foreign_key_schema": "public",
        "foreign_key_table": "languages",
        "foreign_key_column": "code"
      },
      "meta": {
        "collection": "test_collection_translations",
        "field": "languages_id",
        "special": null,
        "interface": null,
        "options": null,
        "display": null,
        "display_options": null,
        "readonly": false,
        "hidden": true,
        "sort": null,
        "width": "full",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        "required": false
      }
    },
    {
      "collection": "test_collection_translations",
      "field": "test_collection_id",
      "type": "integer",
      "schema": {
        "name": "test_collection_id",
        "table": "test_collection_translations",
        "data_type": "integer",
        "default_value": null,
        "generation_expression": null,
        "max_length": null,
        "numeric_precision": 32,
        "numeric_scale": 0,
        "is_generated": false,
        "is_nullable": true,
        "is_unique": false,
        "is_primary_key": false,
        "has_auto_increment": false,
        "comment": null,
        "schema": "public",
        "foreign_key_schema": "public",
        "foreign_key_table": "test_collection",
        "foreign_key_column": "id"
      },
      "meta": {
        "collection": "test_collection_translations",
        "field": "test_collection_id",
        "special": null,
        "interface": null,
        "options": null,
        "display": null,
        "display_options": null,
        "readonly": false,
        "hidden": true,
        "sort": null,
        "width": "full",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        "required": false
      }
    },
    {
      "collection": "test_collection",
      "field": "translations",
      "type": "translations",
      "schema": null,
      "meta": {
        "collection": "test_collection",
        "field": "translations",
        "special": ["translations"],
        "interface": "translations",
        "options": null,
        "display": null,
        "display_options": null,
        "readonly": false,
        "hidden": false,
        "sort": null,
        "width": "full",
        "group": null,
        "translations": null,
        "note": null,
        "conditions": null,
        "required": false
      }
    }
  ],
  "relations": [
    {
      "collection": "test_collection_translations",
      "field": "test_collection_id",
      "related_collection": "test_collection",
      "schema": {
        "table": "test_collection_translations",
        "column": "test_collection_id",
        "foreign_key_table": "test_collection",
        "foreign_key_column": "id",
        "foreign_key_schema": "public",
        "constraint_name": "test_collection_translations_test_collection_id_foreign",
        "on_update": "NO ACTION",
        "on_delete": "SET NULL"
      },
      "meta": {
        "many_collection": "test_collection_translations",
        "many_field": "test_collection_id",
        "one_collection": "test_collection",
        "one_field": "translations",
        "one_collection_field": null,
        "one_allowed_collections": null,
        "junction_field": "languages_id",
        "sort_field": null,
        "one_deselect_action": "nullify"
      }
    },
    {
      "collection": "test_collection_translations",
      "field": "languages_id",
      "related_collection": "languages",
      "schema": {
        "table": "test_collection_translations",
        "column": "languages_id",
        "foreign_key_table": "languages",
        "foreign_key_column": "code",
        "foreign_key_schema": "public",
        "constraint_name": "test_collection_translations_languages_id_foreign",
        "on_update": "NO ACTION",
        "on_delete": "SET NULL"
      },
      "meta": {
        "many_collection": "test_collection_translations",
        "many_field": "languages_id",
        "one_collection": "languages",
        "one_field": null,
        "one_collection_field": null,
        "one_allowed_collections": null,
        "junction_field": "test_collection_id",
        "sort_field": null,
        "one_deselect_action": "nullify"
      }
    }
  ]
}
```
</details>

**Comment by keesvanbemmel** [comment] 2021-09-29 07:58
Thanks for trying @dstoyanoff and @rijkvanzanten 

FYI, I posted my schema that has this issue in your personal discord inbox @rijkvanzanten

**Comment by rijkvanzanten** [comment] 2021-09-29 17:15
Ah gotcha. The missing piece was the database used! I was testing it on MS SQL which doesn't have this problem.

This is technically a duplicate of  https://github.com/directus/directus/issues/6204

**Closed by rijkvanzanten** 2021-09-29 17:15 UTC
Labels: Needs More Info
