### ISSUE TITLE
Cannot remove headers after they are sent to the client

### ISSUE THREAD

**Issue by samehhady** [directus/directus#15095] opened 2022-08-16 18:19 UTC
### Describe the Bug

When trying to fetch an asset that is hosted on S3 I get this error on second call, first call show up fine and show the image.

  This issue only appear when doing:
  http://domain.com/assets/4931236e-11da-4e27-aaca-a776c87489a0

### To Reproduce

- Use S3 to upload images
- try to access image with url: http://domain.com/assets/4931236e-11da-4e27-aaca-a776c87489a0
- First time it will load, second time app will crash with this error

### Errors Shown

`node:_http_outgoing:654
    throw new ERR_HTTP_HEADERS_SENT('remove');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at new NodeError (node:internal/errors:372:5)
    at ServerResponse.removeHeader (node:_http_outgoing:654:11)
    at ServerResponse.send (/home/ec2-user/front-office/node_modules/express/lib/response.js:214:10)
    at PassThrough.<anonymous> (/home/ec2-user/front-office/node_modules/directus/dist/controllers/assets.js:153:25)
    at PassThrough.emit (node:events:527:28)
    at PassThrough.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP_HEADERS_SENT'`

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-08-16 18:28
Duplicate of https://github.com/directus/directus/issues/14888

**Comment by licitdev** [comment] 2022-08-16 18:33
@samehhady Thank you for your report. I believe the refresh led to a status code of 304 in which express tries to remove headers in`.send()`. 
Ref: https://github.com/expressjs/express/blob/2c47827053233e707536019a15499ccf5496dc9d/lib/response.js#L213-L218

**Closed** 2022-08-16 18:35 UTC
Labels: Duplicate
