### ISSUE TITLE
Dropdown numerical sorting in a string

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1769] opened 2017-08-28 08:51 UTC
## Version Info
  - Directus version and branch: 6.4.1
  - PHP version: PHP 7.1.8
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS: Debian Jessie
  - Client OS: Windows 10

## Expected Behavior
Sorting by numerical values in decimal numeral system.

## Actual Behavior
Disregards the actual numerical value and sorts by char value order.
(1, 10, 11, 12, 13, ... 19, 110, 111, ... 119, 2, 20, 21, ... 29, 220, 221, 222, 3, 4, 5, ... 9)

## Steps to Reproduce
 1. Create a simple table (ID, Active). Create over 20 entries.
 2. In another table, create a _Many to One_ dropdown column, choosing previous table as _Related Table_, in _Interface Options_ set _Visible Column_ to `id` and _Visible Column Template_ to `{{id}}`. _Filter Type_: Dropdown.
 3. Create a new entry in the table with the dropdown, view selections in dropdown.
(Optionally, create a new string column in the related table, and set that as the Visible Column. Experiment with alphanumerical values. Something like `{{id}} - {{name}}` in the Visible Column Template.)

## Schema Dump, Logs, or Screenshots
![image](https://user-images.githubusercontent.com/2608781/29625938-ddec1e8e-8835-11e7-91c5-5f20a3c4054d.png)

**Comment by WellingGuzman** [comment] 2017-08-30 02:48
This is a expected behavior, not a bug, but we are going to add a feature to sort by the different columns and its data type.

We won't mark it as bug, but treat it as a feature request :)

**Comment by WellingGuzman** [comment] 2017-08-30 17:40
Closed by https://github.com/directus/directus/commit/49b5e89695d995f706abdce7defe700c924040cf

**Closed by WellingGuzman** 2017-08-30 17:40 UTC
Labels: 4. Minor, Interface, Question
