### ISSUE TITLE
After update to 9.22.4, Directus show it's version as 9.22.3

### ISSUE THREAD

**Issue by sekhuat** [directus/directus#17176] opened 2023-01-16 03:13 UTC
### Describe the Bug

I had performed an update from 9.22.1 to 9.22.4. After update, the Directus shows the version as 9.22.3 instead of 9.22.4.

### To Reproduce

Have existing working version of 9.22.1.

- Manually edit the package.json to change the directus version under the dependencies section from 9.22.1 to 9.22.4.
- Run `npm update`
- Run `npx directus database migrate:latest` to update the DB
- Start Directus as usual.

Under the Settings, the version number shown is 9.22.3.

![image](https://user-images.githubusercontent.com/13288516/212590782-f008ebfe-c782-4134-97fb-ddafb43cde26.png)

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.12.1

### What database are you using?

MySql

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2023-01-16 04:50
Duplicate of #17115

**Closed by azrikahar** 2023-01-16 04:50 UTC
