### ISSUE TITLE
Non-admin users cannot delete related objects properly 

### ISSUE THREAD

**Issue by Damras610** [directus/directus#3389] opened 2020-12-11 15:16 UTC
Hello,

I have a problem with the deletion of related objects (O2M or M2M interface - M2O seems to work) when I'm not an admin user. 

To illustrate, my screenshots are about one of my relations: it is a _M2M_ relation between _interactions_ and _contextelements_ objects.

**As an admin user**, I can CRUD these related elements, it works as expected. When I'm on the _interactions_ editing page, I can see the 'X' symbol to remove this _contextelement_ from my _interaction_ object (see screenshot 1).
![1](https://user-images.githubusercontent.com/3372312/101920469-22e91580-3bcc-11eb-813f-4a8f43770ffd.png)

However, **as a non-admin user**, this 'X' symbol is not present. (see screenshot 2). 
![2](https://user-images.githubusercontent.com/3372312/101920512-31373180-3bcc-11eb-9c18-9098426cfc00.png)
This non-admin user belongs to a group with full permissions on the related tables, including the junction table (see screenshot 3).
![3](https://user-images.githubusercontent.com/3372312/101920534-38f6d600-3bcc-11eb-8e80-7e762d5baef8.png)

To dismiss my relation, I can :
- clear the field or edit its raw value. But this does not destroy the entry in my junction table.
- go into my junction table and delete the entry manually (see screenshot 4).
![4](https://user-images.githubusercontent.com/3372312/101920549-3c8a5d00-3bcc-11eb-9bf4-d6633c9e7b75.png)

After posting this on discord, it seems it is a bug.
I can provide more info if need be.

Regards
Damras,

---

### Project details
Directus Version: 9.0.0-rc.20
Environment: production
OS: Linux 4.14.106-97.85.amzn2.x86_64
Node: 14.15.1

**Comment by rijkvanzanten** [comment] 2020-12-15 00:45
Seems to be a duplicate of https://github.com/directus/directus/issues/3265

**Closed by rijkvanzanten** 2020-12-15 00:45 UTC
Labels: App, Bug
