### ISSUE TITLE
Cannot create M2M Relationship

### ISSUE THREAD

**Issue by simpleauthority** [directus/directus#4243] opened 2021-02-23 09:13 UTC
I have two collections `Item` and `Mob`. 

A mob can drop many items, and an item can be dropped by many mobs. So, I want to make an M2M relationship. I go into Mob and press `Create Field` -> `Many to Many Relationship`. I fill in the name and the `Type` field is set to `Alias` and uneditable. I continue and fill out the relationship with `Item`. When pressing the final next button, I get this error:
![img](https://static.jacobandersen.dev/shared/🎈⚗️📠🍮😜.png)

It failed to create the `Corresponding Field` for some reason. Here is the request:
```
{"field":"dropped_by","collection":"item","meta":{"special":"m2m","interface":"many-to-many"}}
```

The response body (status is 400):
```
{"errors":[{"message":"\"type\" is required","extensions":{"code":"INVALID_PAYLOAD"}}]}
```

Could it be related to the fact that the `Type` field was set to `Alias` and uneditable?

---

### Project details
Directus Version: 9.0.0-rc.42
Environment: production
OS: Linux 4.15.0-20-generic
Node: 10.23.2

**Comment by simpleauthority** [comment] 2021-02-23 09:51
I believe the problem might be the `$` here, not sure tho. Gonna see if I can try it out. 

https://github.com/directus/directus/blob/b087967c29308ceb6a2c53003e5c34d617e87717/app/src/modules/settings/routes/data-model/field-detail/components/relationship-m2m.vue#L396

**Comment by simpleauthority** [comment] 2021-02-23 10:36
> 
> 
> I believe the problem might be the `$` here, not sure tho. Gonna see if I can try it out.
> 
> https://github.com/directus/directus/blob/b087967c29308ceb6a2c53003e5c34d617e87717/app/src/modules/settings/routes/data-model/field-detail/components/relationship-m2m.vue#L396

Nope, I am very wrong :-) I will leave it to the pros. Ha.

**Comment by rijkvanzanten** [comment] 2021-02-23 16:13
I think the problem might be that it wasn't able to grab the type of the related primary key for the foreign key field on the related collection. I'm not able to reproduce this on a "fresh" installation with new tables though..

Would you be able to share a database dump with a minimal reproduction where this is happening?

I'll close this for now, but we'll reopen once it's reproducible 👍🏻

**Comment by Mrmiffo** [comment] 2021-02-23 18:49
I have the same issue in rc42, fresh install. Steps:

1. Create a collection `product_variant`
2. Create a collection `order`
3. In `order` add a M2M relation to `product_variant` called order_lines, in Relationship uncheck Auto fill, set Junction collection to `order_line`, `order_id`, `product_id`. Set Related collection to `product_variant`. Check `Add Many-To-Many to "product_variant"`, call it `orders`.
4. Finish the setup.

When finalizing the setup the following error is displayed:
![image](https://user-images.githubusercontent.com/8545443/108891619-37f01500-760f-11eb-998b-c7c297742593.png)
```
{
  "errors": [
    {
      "message": "\"type\" is required",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```
In the console I get:
```
19:41:37 Ô£¿ request completed POST 400 /fields/product_variant 35ms
19:41:37 Ô£¿ request completed POST 200 /fields/order_line 539ms
19:41:37 Ô£¿ request completed POST 200 /fields/order_line 541ms
```
The `order_line` collection is created and the relation in `orders`, but the relationship in `product_variant` is not created.

[M2M Type missing.zip](https://github.com/directus/directus/files/6031198/M2M.Type.missing.zip)

**Closed** 2021-02-23 19:45 UTC
Labels: App, Bug

**Comment by simpleauthority** [comment] 2021-02-23 23:23
It's fixed! Thank you very much for the prompt attention.
