### ISSUE TITLE
Cannot create item with "file" field via GraphQL

### ISSUE THREAD

**Issue by SeanDylanGoff** [directus/directus#9257] opened 2021-10-30 16:42 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a table called "comments" with a field "image" of type file (m2o directus_files).

Running the following mutation

```
mutation {
  create_comments_item(data: {
      item: {
        id: 1
      },
      image: {
        id: "943f827f-5a66-41b5-a470-2ea01ea93fd1"
      }
  }) {id}
}
```

gives 4 errors like

`Field \"create_directus_files_input.storage\" of required type \"String!\" was not provided.`

So it seems like directus is trying to create the item instead of connecting the existing item.

```
mutation {
  create_comments_item(data: {
      item: {
        id: 1
      },
      image: "943f827f-5a66-41b5-a470-2ea01ea93fd1"
  }) {id}
}
```

Works, but ONLY if the user doesn't have access to directus_files (otherwise it gives an error that "image" should be of type create_directus_items_input, not string).

I think it's quite confusing anyways, that depending on the permissions of the user you HAVE to use  {id: xxx} vs just xxx, neither works in both cases.

### To Reproduce

Create schema with table "comments", M2O directus_files called "image"
Run above mentioned query.

### What version of Directus are you using?

rc.99

### What version of Node.js are you using?

-

### What database are you using?

mariadb

### What browser are you using?

chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

docker

**Comment by jaycammarano** [comment] 2021-10-30 16:44
It's probably related to this: https://github.com/directus/directus/issues/7237

**Comment by rijkvanzanten** [comment] 2021-10-30 17:01
Duplicate of #7237

**Closed by rijkvanzanten** 2021-10-30 17:01 UTC
Labels: Bug (Potential)
