### ISSUE TITLE
Can't define relationships interfaces after migration

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#5123] opened 2021-04-17 12:47 UTC
By using a migration I can't set the correct interface for relationships.
For instance if I have a column named `post_id` I can't set a `many-to-one` interface to that field, only numeric or text-input.

**Comment by rijkvanzanten** [comment] 2021-04-19 14:52
Duplicate of https://github.com/directus/directus/issues/3952

**Closed by rijkvanzanten** 2021-04-19 14:52 UTC
Labels: Duplicate
