### ISSUE TITLE
Admin Options Status translation has a bug

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#7367] opened 2021-08-12 00:04 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

For some reason the "Active" option is in bulgarian language I think:

![image](https://user-images.githubusercontent.com/10547444/129118789-05c9287d-d1b2-491a-86ac-4d8e3c95ae83.png)

### To Reproduce

Self explanatory

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

v14.17.2

### What database are you using?

MariaDB

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

On a remote Debian server

**Comment by rijkvanzanten** [comment] 2021-08-12 02:56
Duplicate of https://github.com/directus/directus/issues/7362

**Closed** 2021-08-12 02:56 UTC
Labels: Duplicate
