### ISSUE TITLE
Error applying schema snapshot from SQLite to Postgres

### ISSUE THREAD

**Issue by panz3r** [directus/directus#14677] opened 2022-07-26 17:01 UTC
### Describe the Bug

When trying to apply a schema snapshot from SQLite to Postgres with the following command
```sh
npx directus schema apply -y ./schema.yaml
```

the following error is thrown
```sh
TypeError: Cannot read properties of null (reading 'meta')
    at /app/node_modules/directus/dist/utils/apply-snapshot.js:110:139
    at Array.filter (<anonymous>)
    at /app/node_modules/directus/dist/utils/apply-snapshot.js:110:58
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

This might depend on the following line of code 
https://github.com/directus/directus/blob/ce01288307e1a6aa2a65ef1a8af7e83faa70db11/api/src/utils/apply-snapshot.ts#L135
where `lhs` might be `undefined` or `null`

### To Reproduce

1. Make a snapshot on a  SQLite database running 
```sh
directus schema snapshot ./schema.yaml --format yaml
```
2. Apply the snapshot on a Postgres database running
```sh
directus schema apply ./schema.yaml -y
```

### Errors Shown

TypeError: Cannot read properties of null (reading 'meta')
    at /app/node_modules/directus/dist/utils/apply-snapshot.js:110:139
    at Array.filter (<anonymous>)
    at /app/node_modules/directus/dist/utils/apply-snapshot.js:110:58
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

16.16.0

### What database are you using?

SQLite 3.37.0, Postgres 14.4

### What browser are you using?

any

### How are you deploying Directus?

locally, Heroku

**Comment by rijkvanzanten** [comment] 2022-07-26 17:47
Could you share a schema yaml file where this is happening?

**Comment by panz3r** [comment] 2022-07-26 18:36
Hi @rijkvanzanten ,

Here a sample `schema.yaml` file
[schema.yaml.txt](https://github.com/directus/directus/files/9192416/schema.yaml.txt)

Thanks

**Comment by azrikahar** [comment] 2022-07-27 06:50
@panz3r When applying the schema snapshot from SQLite to Postgres, was it the first time applying to a fresh Postgres database, or it's subsequent attempts applying the same snapshot again?

When I first apply it, it seems to work without any issue:

![WindowsTerminal_dA933J6iuR](https://user-images.githubusercontent.com/42867097/181180392-b137958f-4ad9-4527-bb0f-5597438bac74.png)

But when I do re-apply it without change anything, it is trying to delete 3 collections (which shouldn't happen), and causes this error:

![WindowsTerminal_WfLydwM8XO](https://user-images.githubusercontent.com/42867097/181180478-7c80797b-4501-4585-83e6-4396b0b3dbd5.png)

Based on the generated diff that it's trying to operate on:

<details>
<summary>snapshotDiff result</summary>

```json
[
    {
        "collection": "ref",
        "diff": [
            {
                "kind": "D",
                "path": [
                    "schema",
                    "comment"
                ],
                "lhs": null
            },
            {
                "kind": "D",
                "path": [
                    "schema",
                    "schema"
                ],
                "lhs": "public"
            },
            {
                "kind": "N",
                "path": [
                    "schema",
                    "sql"
                ],
                "rhs": "CREATE TABLE \"ref\" (`id` char(36) NOT NULL, `user_created` char(36) NULL, `date` date NULL, `ref_amount` float NULL, `ref_price` float NULL, `ref_quantity` float NULL, `remaining_price` float NULL, `estimated_price` float NULL DEFAULT null, `real_price` float null, PRIMARY KEY (`id`), CONSTRAINT `ref_user_created_foreign` FOREIGN KEY (`user_created`) REFERENCES `directus_users` (`id`))"
            }
        ]
    },
    {
        "collection": "ssync_configurations",
        "diff": [
            {
                "kind": "D",
                "path": [
                    "schema",
                    "comment"
                ],
                "lhs": null
            },
            {
                "kind": "D",
                "path": [
                    "schema",
                    "schema"
                ],
                "lhs": "public"
            },
            {
                "kind": "N",
                "path": [
                    "schema",
                    "sql"
                ],
                "rhs": "CREATE TABLE `ssync_configurations` (`id` char(36) not null, `user_created` char(36), `date_created` datetime, `user_updated` char(36), `date_updated` datetime, `description` varchar(255) not null, `source_playlist_id` varchar(255) not null, `source_playlist_name` varchar(255), `source_playlist_songs` integer, `destination_playlist_id` varchar(255) not null, `destination_playlist_name` varchar(255), `destination_playlist_songs` integer, `status` varchar(255) default 'TO_SYNC', foreign key(`user_created`) references `directus_users`(`id`), foreign key(`user_updated`) references `directus_users`(`id`), primary key (`id`))"
            }
        ]
    },
    {
        "collection": "ssync_credentials",
        "diff": [
            {
                "kind": "D",
                "path": [
                    "schema",
                    "comment"
                ],
                "lhs": null
            },
            {
                "kind": "D",
                "path": [
                    "schema",
                    "schema"
                ],
                "lhs": "public"
            },
            {
                "kind": "N",
                "path": [
                    "schema",
                    "sql"
                ],
                "rhs": "CREATE TABLE `ssync_credentials` (`id` char(36) not null, `user_created` char(36), `date_created` datetime, `user_updated` char(36), `date_updated` datetime, `access_token` varchar(255), `refresh_token` varchar(255) not null, foreign key(`user_created`) references `directus_users`(`id`), foreign key(`user_updated`) references `directus_users`(`id`), primary key (`id`))"
            }
        ]
    }
]
```

</details>

I believe this actually has the same root cause as https://github.com/directus/directus/issues/13383#issuecomment-1191238970, but we'll definitely also need to ensure `null` lhs won't trigger this error.

I think it shouldn't be `undefined` for kind 'D' diffs as noted in deep-diff's docs:

> `lhs` - the value on the left-hand-side of the comparison (undefined if kind === 'N')
> `rhs` - the value on the right-hand-side of the comparison (undefined if kind === 'D')

I've opened a new issue #14687 for this specific bug, so I'll close this in favor of tracking it over there 👍

**Closed by azrikahar** 2022-07-27 06:50 UTC
Labels: Needs More Info

**Comment by panz3r** [comment] 2022-07-27 18:27
@azrikahar Thanks for you quick feedback.
Yes, that's correct, the error is thrown when re-applying the schema.

My initial report was inaccurate regarding the reproduction steps, the error is shown when re-applying the schema whilst the first apply was completed successfully.

I'll keep track of the status on the new issue.
