### ISSUE TITLE
Show folders in the along with files in File Library.

### ISSUE THREAD

**Issue by Krishna2323** [directus/directus#19172] opened 2023-07-15 05:39 UTC
### Describe the Bug

Currently when we go to File Library we can see the existing files but we couldn't see the children folders inside it.

<img width="1709" alt="show_folders" src="https://github.com/directus/directus/assets/85894871/3be1f502-1978-4774-94f0-2ab00558d0db">

### To Reproduce

Create a folder inside any children folder or direct to File Library.

### Directus Version

10.5.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Krishna2323** [comment] 2023-07-16 16:54
hey @rijkvanzanten, I'm interested in working on this, can you pls assign if this seems valid to you. Thanks

**Comment by paescuj** [comment] 2023-07-17 09:37
Thanks for opening the issue! However this concern should be submitted as a feature request as it is intentional that the folders are displayed in the sidebar, while the main content is used for files only, so this is not a bug.
Kindly open a [new feature request](https://docs.directus.io/contributing/feature-request-process.html) instead in case this is still desired. I'll proceed to close this issue, thanks again!

**Closed by paescuj** 2023-07-17 09:37 UTC

**Comment by Krishna2323** [comment] 2023-07-17 09:45
@paescuj , thanks for guidance.

**Comment by paescuj** [comment] 2023-07-17 10:09
> @paescuj , thanks for guidance.

You're welcome!
