### ISSUE TITLE
no latest Tag availablle

### ISSUE THREAD

**Issue by jurrack** [directus/directus#4583] opened 2021-03-18 08:52 UTC
Hi, 

when trying to pull your current image it will fail:

```docker pull directus/directus ```

Its fails with:
``` 
Using default tag: latest
Error response from daemon: manifest for directus/directus:latest not found: manifest unknown: manifest unknown 
```

Seems like the latest tag is not set. When using a fixed version tag I works fine.

**Comment by benhaynes** [comment] 2021-03-18 13:44
@WoLfulus — do we have the `latest` tag yet? Any ETA on this?

**Comment by rijkvanzanten** [comment] 2021-03-18 13:47
Duplicate of https://github.com/directus/directus/issues/3661

**Closed by rijkvanzanten** 2021-03-18 13:47 UTC
