### ISSUE TITLE
Error in changing user password after account is created

### ISSUE THREAD

**Issue by altezza04** [directus/directus#5398] opened 2021-04-30 15:46 UTC
In RC61, deploy in Digital Ocean App platform with managed database in PG 12

1. Create a new admin user
2.Change the password of this user
3. Give this error [INTERNAL_SERVER_ERROR] Cannot read property 'startsWith' of null

<img width="541" alt="Screenshot 2021-04-30 at 11 45 22 PM" src="https://user-images.githubusercontent.com/59946405/116720101-6541b080-aa0e-11eb-8c9f-d1d4d703dac1.png">

Everything seem fine as if I update user password

**Comment by rijkvanzanten** [comment] 2021-04-30 15:51
Duplicate of https://github.com/directus/directus/issues/5310

**Closed by rijkvanzanten** 2021-04-30 15:51 UTC
