### ISSUE TITLE
Save as Copy error with M2M field

### ISSUE THREAD

**Issue by nazariydj** [directus/directus#4871] opened 2021-04-07 09:44 UTC
1. create a simple Collection (bug_test)
2. add M2M field (without working fine)
3. create an item and **Save**
4. change some data and click **Save as Copy**

nothing heppends and got error in console: 
`Failed to load resource: the server responded with a status of 500 ()`

Request Error:
```json
{"errors":[{"message":"insert into `bug_test` (`date_created`, `date_updated`, `name`, `sort`, `status`, `user_created`, `user_updated`) values ('2021-04-07 09:30:56.469', '2021-04-07T09:30:35Z', 'item 2', NULL, 'draft', 'b8739538-eefd-4c80-b3c2-ae7aee8b2395', 'b8739538-eefd-4c80-b3c2-ae7aee8b2395') - ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2021-04-07T09:30:35Z' for column 'date_updated' at row 1","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

---

### Project details
Directus Version: 9.0.0-rc.54
Environment: production
OS: Linux 3.10.0-957.el7.x86_64 - Docker
Node: 14.16.0

**Comment by Nitwel** [comment] 2021-04-07 11:45
looks like a duplicate of #4434

**Comment by rijkvanzanten** [comment] 2021-04-07 15:53
Duplicate of https://github.com/directus/directus/issues/3655 and #4434

**Closed by rijkvanzanten** 2021-04-07 15:53 UTC
