### ISSUE TITLE
App: Use `AUTH_<PROVIDER>_MODE` for auth requests

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21914] opened 2024-03-20 07:47 UTC
### Describe the Bug

In https://github.com/directus/directus/issues/21239 it was introduced a session mode which uses a cookie to keep user logged in.
Although this have broke some behaviour we had previously.
For example, when project is using [Seamless SSO](https://docs.directus.io/self-hosted/sso.html#seamless-sso) it may be using `cookie` for `AUTH_<PROVIDER>_MODE`.
But the user will not be able to use the App as it is strictly set to `session` mode.

In order to fix this, App should use the mode that is set on `AUTH_<PROVIDER>_MODE`

### To Reproduce

Setup some SSO mechanism and then set `AUTH_<PROVIDER>_MODE` to `cookie`.
Now it will not be possible to login into the App, using the SSO provider

### Directus Version

main (10.10.4)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2024-03-20 11:21
Duplicate of #21836, will be fixed with #21874 👍

**Closed by paescuj** 2024-03-20 11:21 UTC
Labels: :cake: Bug, :warning: Enterprise, :file_folder: Authentication
