### ISSUE TITLE
numeric "is between" filter producing chaotic gibberish after update to version 10

### ISSUE THREAD

**Issue by bamboowonder** [directus/directus#18786] opened 2023-05-31 19:15 UTC
### Describe the Bug

[directus-bug-between-filter-2023-05-31_12.09.46.webm](https://github.com/directus/directus/assets/15368570/c4536988-3b4a-4298-9b08-1a0aaf17f1be)

The video shows all.    Note that I only ever try to type 18 or 24 despite what actually shows up.
"Age" is a normal integer field from postgres 15.
When using a "is between" filter, the input is corrupted in chaotic and unpredictable ways.
This issue is showing up across different browsers, computers and networks.

### To Reproduce

Create a "is between" filter on an integer column and try to type anything into the value fields.

### Directus Version

v10.2.0

### Hosting Strategy

Self-Hosted NPM

**Comment by br41nslug** [comment] 2023-06-01 09:41
Duplicate of https://github.com/directus/directus/issues/18684

**Closed by br41nslug** 2023-06-01 09:41 UTC
Labels: Package: @directus/app, Bug, Good First Issue
