### ISSUE TITLE
Interface Bug on viewing and interface error

### ISSUE THREAD

**Issue by fballan93** [directus/directus#5481] opened 2021-05-05 08:36 UTC
Ill try to make my explanation clear as much as possible. 

assume that I have a sub collection with user_updated, user_created , and custom_Review_Date field, Remark Field

I added this sub collection into my main collection with M2M relation . Note that I have no field as required in any of my collections.

I can normally update the collection item as long as i dont reference the direct-us user via user_created field in interface . the moment i reference user First name or last name and want to update it will throw an error  

![CleanShot 2021-05-05 at 10 44 56](https://user-images.githubusercontent.com/9093101/117114772-eee9d900-ad94-11eb-8dcd-9e6af104b073.gif)

<img width="823" alt="CleanShot 2021-05-05 at 11 21 13@2x" src="https://user-images.githubusercontent.com/9093101/117114647-cbbf2980-ad94-11eb-97b0-92af6df0ef8a.png">

so I tried to investigate and added email in the interface and tried the same action again . update any item and the error has been changed . 

<img width="842" alt="CleanShot 2021-05-05 at 10 34 13@2x" src="https://user-images.githubusercontent.com/9093101/117114969-25bfef00-ad95-11eb-9cd7-f299448c3aa7.png">

Please note that im just fetching the data is the system user_created field and fetching the name from the repeater.  

Directions us 9.0.0rc62
MySQL 8 via Azure MySQL
deployed via npx in Azure Appservice
Using Chrome  
Storage : Azure Blobs

**Comment by fballan93** [comment] 2021-05-05 17:56
just to add . 

as long as my M2M interface is empty i can see the information when click on an item . 
<img width="843" alt="CleanShot 2021-05-05 at 20 55 23@2x" src="https://user-images.githubusercontent.com/9093101/117187162-4cf1dd00-ade4-11eb-884e-82ca31dca3b1.png">

<img width="878" alt="CleanShot 2021-05-05 at 20 55 28@2x" src="https://user-images.githubusercontent.com/9093101/117187193-567b4500-ade4-11eb-8f7e-029360782fe9.png">


If i added the information to be displayed in M2M interface it will not be visible when clicked individually

**Comment by rijkvanzanten** [comment] 2021-05-07 14:26
@fballan93 Could you share a DB dump where this is happening? It's a little difficult to reproduce just based on the information provided.

It also sounds like this could be a duplicate of https://github.com/directus/directus/issues/5538 just popping up in a different location 🤔

**Comment by fballan93** [comment] 2021-05-08 18:18
Of course . how you want it to be shared . you want t a link for the dump or should i uploaded it here .

**Comment by fballan93** [comment] 2021-05-08 18:58
> @fballan93 Could you share a DB dump where this is happening? It's a little difficult to reproduce just based on the information provided.
> 
> It also sounds like this could be a duplicate of #5538 just popping up in a different location 🤔

I think it is different  . the issue here is in interface . and can be summarized in two points :

- Adding any field from directus_users in M2M M2O O2M interface to display inside a collection item will result in a permission denied error while updating although im the admin . 
- Adding any item from another sub collection in the interface will not display when clicking on it 

-

**Comment by rijkvanzanten** [comment] 2021-05-10 13:46
> Of course . how you want it to be shared . you want t a link for the dump or should i uploaded it here .

Uploading it here is the most convenient! If it contains any private data, you can email it to me at rijk@directus.io

**Comment by fballan93** [comment] 2021-05-17 10:58
> just to add .
> 
> as long as my M2M interface is empty i can see the information when click on an item .
> <img alt="CleanShot 2021-05-05 at 20 55 23@2x" width="843" src="https://user-images.githubusercontent.com/9093101/117187162-4cf1dd00-ade4-11eb-884e-82ca31dca3b1.png">
> 
> <img alt="CleanShot 2021-05-05 at 20 55 28@2x" width="878" src="https://user-images.githubusercontent.com/9093101/117187193-567b4500-ade4-11eb-8f7e-029360782fe9.png">
> 
> If i added the information to be displayed in M2M interface it will not be visible when clicked individually

the email validation error has disappeared  when i upgraded to rc68 . just a quick note here that the display issue still presist

**Comment by rijkvanzanten** [comment] 2021-05-21 17:50
I believe you have your field set to `fill` width, which makes it grow as big as it can 👍🏻

**Closed by rijkvanzanten** 2021-05-21 17:50 UTC
Labels: API, Bug (Potential)
