### ISSUE TITLE
 insert into "directus_users"  - invalid input syntax for type uuid: "default"

### ISSUE THREAD

**Issue by anvarknian** [directus/directus#20466] opened 2023-11-17 18:05 UTC
### Describe the Bug

 I'm using the latest version of Directus DOCKER integrated with Microsoft Entry ID

```

[directus-directus] [2023-11-17 17:54:12] [17:54:11.980] WARN: insert into "directus_users" ("auth_data", "email", "external_identifier", "first_name", "id", "last_name", "provider", "role") values (DEFAULT, $1, $2, $3, $4, $5, $6, $7) returning "id" - invalid input syntax for type uuid: "default"
[directus-directus] [2023-11-17 17:54:12]     err: {
[directus-directus] [2023-11-17 17:54:12]       "type": "DatabaseError",
[directus-directus] [2023-11-17 17:54:12]       "message": "insert into \"directus_users\" (\"auth_data\", \"email\", \"external_identifier\", \"first_name\", \"id\", \"last_name\", \"provider\", \"role\") values (DEFAULT, $1, $2, $3, $4, $5, $6, $7) returning \"id\" - invalid input syntax for type uuid: \"default\"",
[directus-directus] [2023-11-17 17:54:12]       "stack":
[directus-directus] [2023-11-17 17:54:12]           error: insert into "directus_users" ("auth_data", "email", "external_identifier", "first_name", "id", "last_name", "provider", "role") values (DEFAULT, $1, $2, $3, $4, $5, $6, $7) returning "id" - invalid input syntax for type uuid: "default"
[directus-directus] [2023-11-17 17:54:12]               at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
[directus-directus] [2023-11-17 17:54:12]               at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
[directus-directus] [2023-11-17 17:54:12]               at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
[directus-directus] [2023-11-17 17:54:12]               at TLSSocket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
[directus-directus] [2023-11-17 17:54:12]               at TLSSocket.emit (node:events:517:28)
[directus-directus] [2023-11-17 17:54:12]               at addChunk (node:internal/streams/readable:335:12)
[directus-directus] [2023-11-17 17:54:12]               at readableAddChunk (node:internal/streams/readable:308:9)
[directus-directus] [2023-11-17 17:54:12]               at Readable.push (node:internal/streams/readable:245:10)
[directus-directus] [2023-11-17 17:54:12]               at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[directus-directus] [2023-11-17 17:54:12]       "length": 139,
[directus-directus] [2023-11-17 17:54:12]       "name": "error",
[directus-directus] [2023-11-17 17:54:12]       "severity": "ERROR",
[directus-directus] [2023-11-17 17:54:12]       "code": "22P02",
[directus-directus] [2023-11-17 17:54:12]       "where": "unnamed portal parameter $7 = '...'",
[directus-directus] [2023-11-17 17:54:12]       "file": "uuid.c",
[directus-directus] [2023-11-17 17:54:12]       "line": "133",
[directus-directus] [2023-11-17 17:54:12]       "routine": "string_to_uuid"
[directus-directus] [2023-11-17 17:54:12]     }
[directus-directus] [2023-11-17 17:54:12] [17:54:11.982] WARN: [OpenID] Unexpected error during OpenID login
[directus-directus] [2023-11-17 17:54:12]     err: {
[directus-directus] [2023-11-17 17:54:12]       "type": "DatabaseError",
[directus-directus] [2023-11-17 17:54:12]       "message": "insert into \"directus_users\" (\"auth_data\", \"email\", \"external_identifier\", \"first_name\", \"id\", \"last_name\", \"provider\", \"role\") values (DEFAULT, $1, $2, $3, $4, $5, $6, $7) returning \"id\" - invalid input syntax for type uuid: \"default\"",
[directus-directus] [2023-11-17 17:54:12]       "stack":
[directus-directus] [2023-11-17 17:54:12]           error: insert into "directus_users" ("auth_data", "email", "external_identifier", "first_name", "id", "last_name", "provider", "role") values (DEFAULT, $1, $2, $3, $4, $5, $6, $7) returning "id" - invalid input syntax for type uuid: "default"
[directus-directus] [2023-11-17 17:54:12]               at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:287:98)
[directus-directus] [2023-11-17 17:54:12]               at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:126:29)
[directus-directus] [2023-11-17 17:54:12]               at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/parser.js:39:38)
[directus-directus] [2023-11-17 17:54:12]               at TLSSocket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.0/node_modules/pg-protocol/dist/index.js:11:42)
[directus-directus] [2023-11-17 17:54:12]               at TLSSocket.emit (node:events:517:28)
[directus-directus] [2023-11-17 17:54:12]               at addChunk (node:internal/streams/readable:335:12)
[directus-directus] [2023-11-17 17:54:12]               at readableAddChunk (node:internal/streams/readable:308:9)
[directus-directus] [2023-11-17 17:54:12]               at Readable.push (node:internal/streams/readable:245:10)
[directus-directus] [2023-11-17 17:54:12]               at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
[directus-directus] [2023-11-17 17:54:12]       "length": 139,
[directus-directus] [2023-11-17 17:54:12]       "name": "error",
[directus-directus] [2023-11-17 17:54:12]       "severity": "ERROR",
[directus-directus] [2023-11-17 17:54:12]       "code": "22P02",
[directus-directus] [2023-11-17 17:54:12]       "where": "unnamed portal parameter $7 = '...'",
[directus-directus] [2023-11-17 17:54:12]       "file": "uuid.c",
[directus-directus] [2023-11-17 17:54:12]       "line": "133",
[directus-directus] [2023-11-17 17:54:12]       "routine": "string_to_uuid"
[directus-directus] [2023-11-17 17:54:12]     }
```

### To Reproduce

setting .env  and running with docker
```
AUTH_PROVIDERS=microsoft
AUTH_MICROSOFT_DRIVER=openid
AUTH_MICROSOFT_CLIENT_ID='xxx'
AUTH_MICROSOFT_CLIENT_SECRET= xxx
AUTH_MICROSOFT_ISSUER_URL=https://login.microsoftonline.com/xxx/v2.0/.well-known/openid-configuration
AUTH_MICROSOFT_SCOPE=openid profile email
AUTH_MICROSOFT_IDENTIFIER_KEY=sub
AUTH_MICROSOFT_ICON=microsoft
AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION=true
AUTH_MICROSOFT_DEFAULT_ROLE_ID=default
AUTH_MICROSOFT_AUTHORIZE_URL=https://login.microsoftonline.com/xxx/oauth2/v2.0/authorize
AUTH_MICROSOFT_ACCESS_URL=https://login.microsoftonline.com/xxx/oauth2/v2.0/token
```

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-11-20 13:33
This is because `AUTH_<PROVIDER>_DEFAULT_ROLE_ID` should be the UUID of an existing role. An example value of UUID would be `2a474305-2612-4373-b3c2-7285c83205fc`, instead of a value such as `default`. 

When viewing the access control for said role, You can either grab the UUID for the role via:

1. the URL
2. the Copy button for Primary Key field in the Information sidebar as seen here:

![](https://github.com/directus/directus/assets/42867097/6c3507e1-0328-4614-b171-83dbe6c0261f)

Hope that helps! Proceeding to close this as not a bug for now 👍

**Closed by azrikahar** 2023-11-20 13:33 UTC
