### ISSUE TITLE
`directus_permissions_role_foreign` missing when running migration from v10 -> v11

### ISSUE THREAD

**Issue by flayks** [directus/directus#23228] opened 2024-08-07 10:20 UTC
### Describe the Bug

I'm getting issues upgrading to v11.0.0 from v10.13.1 then 10.13.2 (using mysql)

```
[12:09:11.343] INFO: Running migrations...
[12:09:11.349] INFO: Applying Permissions Policies...
[12:09:11.813] ERROR: alter table directus_permissions drop foreign key directus_permissions_role_foreign - Can't DROP FOREIGN KEY directus_permissions_role_foreign; check that it exists
```

And then starting the admin:

```
[12:11:45.139] ERROR: select directus_policies.admin_access, directus_policies.app_access, directus_policies.ip_access from directus_access left join directus_policies on directus_policies.id = directus_access.policy where role in ('dac84e35-39b5-43af-b104-98a7228e5071') - Table 'housesof.directus_access' doesn't exist
```

I'm not really sure what is wrong with the setup but it all worked fine with v10.13.2 after upgrading from v10.13.1.

### To Reproduce

I just ran the migrations script using `npx directus database migrate:latest`

### Directus Version

v10.13.1/2

### Hosting Strategy

Self-Hosted (Custom)

### Database

MySQL (11.4.2-MariaDB)

**Comment by hanneskuettner** [comment] 2024-08-07 11:20
Closing this, as it turns out that the DB in question was modified, to a point where the foreign key constrained somehow was removed. 

To anyone reading along, in the end it has been fixed by running 

```sql
ALTER TABLE `directus_permissions`
  ADD CONSTRAINT `directus_permissions_role_foreign` FOREIGN KEY (`role`) REFERENCES `directus_roles` (`id`) ON DELETE CASCADE;
```

on the v10 DB and then performing the upgrade.

**Comment by flayks** [comment] 2024-08-07 11:22
Thank you again for investigating @hanneskuettner! Hopefully that helps other folks out there.

**Comment by arnediekmann** [comment] 2024-08-07 11:25
Hey, I have the same error without having tampered with the database before. However, I am running Directus in a clustered environment and if this is, perhaps, a race condition when instances start concurrently. I am now in the process of downgrading the instances back to v10 and will report if I can reproduce the error in other environments.

**Comment by hanneskuettner** [comment] 2024-08-07 11:27
Happy to re-open this if you have any findings @arnediekmann 

I'm trying to reproduce this locally and have had no luck so far. If it continues to be a problem we might have to make the migration a bit more error tolerant.

**Comment by arnediekmann** [comment] 2024-08-07 11:29
I didn't have any problems locally either, which is why I wonder if it might only affect clustered environments. I will let you know if and how this is reproducible.

**Comment by flayks** [comment] 2024-08-07 11:31
That might be what happened to me as well since I didn't really touch to the db either. I rather similarly use Directus with Docker connected to a dockerized mariadb install. Locally, just using npm and the latest version of Mariadb using homebrew.

**Comment by arnediekmann** [comment] 2024-08-07 11:55
After reverting the version to `10.13.2` and restoring the database with a dump from yesterday and then updating again, I get the following SQL error when the migrations are run by `11.0.0`:

```
directus-7f67c8f6f7-c4857 directus [11:50:58.185] INFO: Applying Permissions Policies...
directus-7f67c8f6f7-c4857 directus Error: alter table `directus_permissions` modify  `policy` char(36) not null  - Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'
directus-7f67c8f6f7-c4857 directus     at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packets/packet.js:728:17)
directus-7f67c8f6f7-c4857 directus     at Query.execute (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/commands/command.js:29:26)
directus-7f67c8f6f7-c4857 directus     at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:481:34)
directus-7f67c8f6f7-c4857 directus     at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:97:12)
directus-7f67c8f6f7-c4857 directus     at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packet_parser.js:75:16)
directus-7f67c8f6f7-c4857 directus     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:104:25)
directus-7f67c8f6f7-c4857 directus     at Socket.emit (node:events:517:28)
directus-7f67c8f6f7-c4857 directus     at addChunk (node:internal/streams/readable:368:12)
directus-7f67c8f6f7-c4857 directus     at readableAddChunk (node:internal/streams/readable:341:9)
directus-7f67c8f6f7-c4857 directus     at Readable.push (node:internal/streams/readable:278:10) {
directus-7f67c8f6f7-c4857 directus   code: 'ER_FK_COLUMN_CANNOT_CHANGE',
directus-7f67c8f6f7-c4857 directus   errno: 1832,
directus-7f67c8f6f7-c4857 directus   sqlState: 'HY000',
directus-7f67c8f6f7-c4857 directus   sqlMessage: "Cannot change column 'policy': used in a foreign key constraint 'directus_permissions_policy_foreign'",
directus-7f67c8f6f7-c4857 directus   sql: 'alter table `directus_permissions` modify  `policy` char(36) not null '
directus-7f67c8f6f7-c4857 directus }
```

The error appears to be quite similar but not the same to what @flayks initially reported 🤔

**Comment by arnediekmann** [comment] 2024-08-07 11:56
@hanneskuettner I will now test to restore the database and then execute the SQL statement before performing the update.

**Comment by hanneskuettner** [comment] 2024-08-07 12:00
Looks like a different error to me 🤔 

What DB vendor are you using? MariaDB as well?

**Comment by arnediekmann** [comment] 2024-08-07 12:22
The database used is a MariaDB Galera Cluster, but I don't have specifics because it is managed by someone else. I suppose there is no use in trying to execute the statement above in my case, since that was for the error that @flayks described. I will see if I can get this to work somehow...

**Comment by hanneskuettner** [comment] 2024-08-07 12:23
Can you open a new issue for you're problem with all the info you have so far, so we can track it properly?

**Comment by arnediekmann** [comment] 2024-08-07 12:34
Yes, will do. I am still trying out a few things to see if I can pinpoint the problem more accurately.

**Closed** 2024-08-08 10:16 UTC
Labels: :cake: Bug, :kaaba: MariaDB, :file_folder: Access Control, :elevator: Server, :fire::fire:

**Comment by leorott** [comment] 2024-08-27 17:09
Hi, 

I still get this error when upgrading from `10.10.2` to `11.0.2` with MySQL 8 as a Database.

```
directus-docker  | Error: alter table `directus_permissions` add constraint `directus_permissions_policy_foreign` foreign key (`policy`) references `directus_policies` (`id`) on delete CASCADE - Referencing column 'policy' and referenced column 'id' in foreign key constraint 'directus_permissions_policy_foreign' are incompatible.
directus-docker  |     at Packet.asError (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packets/packet.js:728:17)
directus-docker  |     at Query.execute (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/commands/command.js:29:26)
directus-docker  |     at Connection.handlePacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:481:34)
directus-docker  |     at PacketParser.onPacket (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:97:12)
directus-docker  |     at PacketParser.executeStart (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/packet_parser.js:75:16)
directus-docker  |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql2@3.10.0/node_modules/mysql2/lib/connection.js:104:25)
directus-docker  |     at Socket.emit (node:events:517:28)
directus-docker  |     at addChunk (node:internal/streams/readable:368:12)
directus-docker  |     at readableAddChunk (node:internal/streams/readable:341:9)
directus-docker  |     at Readable.push (node:internal/streams/readable:278:10) {
directus-docker  |   code: 'ER_FK_INCOMPATIBLE_COLUMNS',
directus-docker  |   errno: 3780,
directus-docker  |   sqlState: 'HY000',
directus-docker  |   sqlMessage: "Referencing column 'policy' and referenced column 'id' in foreign key constraint 'directus_permissions_policy_foreign' are incompatible.",
directus-docker  |   sql: 'alter table `directus_permissions` add constraint `directus_permissions_policy_foreign` foreign key (`policy`) references `directus_policies` (`id`) on delete CASCADE'
directus-docker  | }
```

It looks like the `directus_permissions_policy_foreign` foreign key is causing issues because the `policy` and `id` columns are incompatible. Any idea what might be going wrong?

Thanks!

**Comment by leorott** [comment] 2024-08-28 16:19
Nevermind, the Problem was that my tables collation was different from the db default collation.
