### ISSUE TITLE
Required fields on Junction table are not shown when selecting existing item from the list

### ISSUE THREAD

**Issue by CodeAndWeb** [directus/directus#5725] opened 2021-05-17 16:02 UTC
Required fields on Junction table are not shown when selecting existing item from the list.
The value in the Junction table are left empty and create and error when trying to save the item.

<img width="871" alt="2021-05-17_18-03-00" src="https://user-images.githubusercontent.com/716009/118520186-22841600-b73a-11eb-8773-84b1a9058dc4.png">

---

### Project details
Directus Version: 9.0.0-rc.68
Environment: production
OS: Linux 5.10.25-linuxkit
Node: 14.16.1

**Comment by rijkvanzanten** [comment] 2021-05-17 16:08
I'll consider this a duplicate of https://github.com/directus/directus/issues/5707, as the resolution is the same

**Closed by rijkvanzanten** 2021-05-17 16:08 UTC
