### ISSUE TITLE
rc.74 changing fields in collections (settings) affects order of fields --> only if collection contains one m2a relation

### ISSUE THREAD

**Issue by ludi81** [directus/directus#6223] opened 2021-06-12 07:28 UTC
If I change a field in a collection the order will be affected.
I think it has something to do with an m2a relation. 
1) it works if the collections contains only standard fields (including n:1)
2) the problem occurs, if one relation m2a is used in the collection

After removing the m2a relation the order will not be affected.

**Comment by rijkvanzanten** [comment] 2021-06-14 14:49
Duplicate of https://github.com/directus/directus/issues/6091

**Closed by rijkvanzanten** 2021-06-14 14:49 UTC
