### ISSUE TITLE
Items with validated fields are invisible

### ISSUE THREAD

**Issue by udf2457** [directus/directus#15118] opened 2022-08-17 11:58 UTC
### Describe the Bug

I stumbled across this bug by chance.  Its a weird one for sure !

Basically fields with a validation enabled which are saved, never get listed (but do get saved).

Reproduction steps below.   I think its best/easier if you follow them rather than me trying to write a rambling description.

EDIT TO ADD:

Just logged into Posgres and took a look there. I _think_ what is happening is that on validation fail, the page gets saved with Archive status and default view in the UI is "show active items".  This obviously also incorrect behaviour (both the saving despite validation fail behaviour, and also setting "archive" status behaviour since that abuses the meaning of the word archive !).

### To Reproduce

1. Create a data model and add an `input` field (for this example, I will call it `slug`)
2. Leave all the default settings as they are (for now)
3. Go to content list and add an item (**_OBSERVATION 1_**:  Normal behaviour, i.e. item gets saved, item visible on list)
4. Return to data model, edit `slug` and add validation condition `Matches RegExp` with value `[a-z-]` and specify not null + unique as constraints on the field.
5. Return to content list and add new item, using an obviously invalid input for `slug`, e.g. `CvE2-`
6. Save _(**OBSERVATION 2**:_ Incorrect behaviour, save is allowed despite invalid regex)
7. Return to content list _(**OBSERVATION 3**:_ Note how your saved item is not visible in the list !)
8. Return to content model and remove regex validation (leave not null and unique in place)
9. Return to content list _(**OBSERVATION 4**:_ Note how your saved item is _STILL_ not visible in the list !)
10. Attempt to add a new item with the same `slug` _(**OBSERVATION 5**:_ Note how you get informed of the unique constraint error, i.e. you are hitting the hidden item)

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16

### What database are you using?

Postres 14 

### What browser are you using?

Firefox 103.0.2

### How are you deploying Directus?

Running locally, simple dev environment with npx start as per quickstart docs

**Comment by rijkvanzanten** [comment] 2022-08-17 14:08
I think we need a couple more steps under reproduction, as "Create a data model" includes a lot of hidden settings 😁 I'm assuming you added the "system optional fields" `status`? If not, there's no "archive" in the first place 🙂

**Comment by br41nslug** [comment] 2022-08-22 11:30
I am unable to reproduce this issue and i believe the first 2 behaviors you're seeing is due to a too permissive regex 😬 The regex provided `[a-z-]` holds true if the string contains one lowercase letter or a minus anywhere in the string. If you want to only have `a-z` and `-` in your slugs you should go with something like `^[a-z-]+$` to match the full string.

**Comment by br41nslug** [comment] 2022-08-22 11:36
I am however unable to reproduce the further observations of missing records. This can due to a couple things like the App running into an error hydrating its data (which should be solved on refresh tho) or perhaps a filter rule or preset hiding records from your usual list.

**Comment by br41nslug** [comment] 2022-08-22 11:42
Closing this issue for now 😄 happy to re-open it when more information becomes available

**Closed by br41nslug** 2022-08-22 11:42 UTC
Labels: API, App, Needs More Info, Bug (Potential), Can't Reproduce
