### ISSUE TITLE
Misleading message for request-token error

### ISSUE THREAD

**Issue by EnricoMonese** [directus/directus#2099] opened 2018-03-19 17:58 UTC
When doing `/auth/request-token` for a user that has no _key_ the error message is "Email or password incorrect", but the issue is the missing token not the credentials. 

Is this by design?

Somewhat related to #1619

**Comment by rijkvanzanten** [comment] 2018-03-19 18:10
Hey @EnricoMonese!

This doesn't sound like intended behavior!

**Comment by WellingGuzman** [comment] 2018-03-19 21:41
Thanks for the report @EnricoMonese.

This has been fixed by https://github.com/directus/directus/commit/164c09556d60bb0b4b72f4610537c54e0a0d01e6 and will be part of Directus `6.4.9`

**Closed by WellingGuzman** 2018-03-19 21:41 UTC
Labels: 4. Minor, API, Bug
