### ISSUE TITLE
Collections will not show items list

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16912] opened 2022-12-24 11:16 UTC
### Describe the Bug

After updating from 9.21.0 to 9.22.1 collections' items' list will not show randomly when clicking in the module-nav column.
Revert to 9.21.2 makes the bug disappear

### To Reproduce

1. Upgrade to 9.22.1
2. Create a new collection
3. In the module-nav column, change to other collections back and forth

### Errors Shown

Some collection will not show their items' list.
You have to refresh the page to see them

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

19.0.1

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

**Comment by azrikahar** [comment] 2022-12-24 11:25
Duplicate of #16898 and #16883

**Closed by azrikahar** 2022-12-24 11:25 UTC
