### ISSUE TITLE
Validation fails on collection creation (collection sent but not recognized)

### ISSUE THREAD

**Issue by kattatzu** [directus/directus#14171] opened 2022-06-29 01:01 UTC
### Describe the Bug

When creating a new collection the server throws a validation error as if it had not received a value for the collection name, however the data was sent.

Data:
```json
{
  "collection":"Test",
  "meta": {
    "collection": "Test",
    "icon":" folder",
    "note": null,
    "color": null,
    "translations": [{ "language": "en-US" }]
  }
}
```

Response: 
```json
{
  "errors": [
    {
      "message":"\"collection\" is required",
      "extensions":{"code":"FAILED_VALIDATION",
        "field":"collection",
        "type":"required "
      }
    }
  ]
}
```

### To Reproduce

Install the docker version following the instructions in the documentation (https://docs.directus.io/self-hosted/installation/docker/)

I accessed the Data Model page and clicked on the "Create collection" button, filled in all the fields (including the name of the collection) and when submitting the form I got the aforementioned error.

### Errors Shown

[FAILED_VALIDATION] "collection" is required

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-06-29 01:55
I believe you didn't set the `Content-Type` header as `application/json`, hence the JSON body parser isn't recognizing/acknowledging your payload so it's technically correct that your data wasn't really "sent" from the API perspective.

I'll close this for now, but do let us know if that helps or we'll reopen if you are still facing this issue despite setting the right header.

**Comment by rijkvanzanten** [comment] 2022-06-29 02:13
@azrikahar Was this an api call or app use? The reproduction steps made me think the error was thrown in app? 🤔

> I accessed the Data Model page and clicked on the "Create collection" button, filled in all the fields (including the name of the collection) and when submitting the form I got the aforementioned error.

**Comment by kattatzu** [comment] 2022-06-29 02:18
@azrikahar the error occurred using the web application, not by API.
Cheers

**Comment by azrikahar** [comment] 2022-06-29 02:19
> @azrikahar Was this an api call or app use? The reproduction steps made me think the error was thrown in app? 🤔

This is a very good point, and I've missed it! However I've tested it both locally and on a VPS with docker 9.13.0 and I still can't reproduce this @kattatzu. Can you share a quick screen capture of this happening?

**Comment by kattatzu** [comment] 2022-06-29 02:26
Of course, how strange!
it may be some problem of my Mac with M1, but it is rare.

I send video.

![ezgif-4-8ca2cad7d2](https://user-images.githubusercontent.com/1023213/176337838-195c6924-1b01-4df8-be2c-e0776b6f0bfb.gif)

**Comment by azrikahar** [comment] 2022-06-29 02:32
Hmm that is odd indeed. Would you mind showing the Content-Type of the request headers? Can't quite see it from the video as you were highlighting the Response headers.

It'd also be helpful if you can try incognito mode (to rule out browser extensions interfering) or another different browser as well.

**Comment by kattatzu** [comment] 2022-06-29 02:36
Of course.

Header Request
<img width="796" alt="image" src="https://user-images.githubusercontent.com/1023213/176338783-46b30749-58ae-4218-90f6-ff9536931795.png">

Header Responser
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1023213/176338832-7f07f2b2-583f-49af-a567-93f2f6bfb2d8.png">

Payload
<img width="802" alt="image" src="https://user-images.githubusercontent.com/1023213/176338878-4a0166af-e557-4c23-85e2-78a9354176fa.png">

Response
<img width="603" alt="image" src="https://user-images.githubusercontent.com/1023213/176338901-f6d72940-13c2-4048-971d-e837e700d615.png">

**Comment by kattatzu** [comment] 2022-06-29 02:37
> Hmm that is odd indeed. Would you mind showing the Content-Type of the request headers? Can't quite see it from the video as you were highlighting the Response headers.
> 
> It'd also be helpful if you can try incognito mode (to rule out browser extensions interfering) or another different browser as well.

No, in Incognito mode it still fails.

**Comment by azrikahar** [comment] 2022-06-29 02:55
Interesting! I'm not sure how else can I replicate this on my end (Windows, Chrome) now, so I'll keep this open for now in hopes that others can attempt to reproduce this 🤔 Aside from OS, I'm not seeing any other glaring differences between what we tried.

The only odd thing is the error does resemble as if the payload was never sent, even though your devtools clearly shows they are sent:

https://user-images.githubusercontent.com/42867097/176340622-6604a75f-93b4-40ff-954c-2ec3437f607f.mp4

**Comment by licitdev** [comment] 2022-06-29 14:35
I'm also unable to reproduce the issue on an Intel Mac (chrome & safari) using the `docker-compose.yml` provided above. 🤔

**Comment by rijkvanzanten** [comment] 2022-06-29 15:05
@kattatzu Do you have any other "pieces" in between that might interfere? Any custom extensions, or updates to the docker image that was used, or any other variation that we might not account for here?? 🤔

**Closed by rijkvanzanten** 2022-06-29 15:05 UTC
Labels: Can't Reproduce

**Comment by lsotoj** [comment] 2023-04-13 17:30
I have still the issue, it ocurrs when I did a database restore.

I restore a Mysql database  ussing directus v9.14.1

**Comment by rijkvanzanten** [comment] 2023-04-13 17:31
@lsotoj mind opening a new issue? This one is close to a year old (which means the original cause is most likely long gone)

**Comment by lsotoj** [comment] 2023-04-13 18:43
Ok of course!

Thank you
