### ISSUE TITLE
The geographic field was saved incorrectly

### ISSUE THREAD

**Issue by hulinux** [directus/directus#16688] opened 2022-12-01 04:04 UTC
### Describe the Bug

When using a mapbox map as a geographic field input interface, an error message occurs:Cannot read properties of undefined (reading 'length').
The full error message is as follows:
{
    "message": "Cannot read properties of undefined (reading 'length')",
    "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
    }
}

### To Reproduce

1. Add geographical fields to a collection that is already pure;
2. Modifying the collection of any entry data;
3. Select a point or area in the geographical field;
4. Save modifications;

Also: Check the database log, no errors reported

### Errors Shown

directus       | [12:00:19] ERROR (40 on 1cf9c7e1a6c9): Cannot read properties of undefined (reading 'length')
directus       |     err: {
directus       |       "type": "TypeError",
directus       |       "message": "Cannot read properties of undefined (reading 'length')",
directus       |       "stack":
directus       |           TypeError: Cannot read properties of undefined (reading 'length')
directus       |               at module.exports (vm.js:2:54)
directus       |               at VM2 Wrapper.apply (/directus/node_modules/vm2/lib/bridge.js:485:11)
directus       |               at handler (/directus/node_modules/directus/dist/operations/exec/index.js:24:22)
directus       |               at async FlowManager.executeOperation (/directus/node_modules/directus/dist/flows.js:330:28)
directus       |               at async FlowManager.executeFlow (/directus/node_modules/directus/dist/flows.js:273:58)
directus       |               at async Emitter.emitFilter (/directus/node_modules/directus/dist/emitter.js:31:32)
directus       |               at async ItemsService.updateMany (/directus/node_modules/directus/dist/services/items.js:390:15)
directus       |               at async ItemsService.updateOne (/directus/node_modules/directus/dist/services/items.js:336:9)
directus       |               at async /directus/node_modules/directus/dist/controllers/items.js:139:31
directus       |     }
directus       | [12:00:19] PATCH /items/articles/f3fa4462-ddec-4b35-ba29-c6798b78c062 500 70ms

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.18.1

### What database are you using?

postgis 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-12-01 07:35
> directus | at VM2 Wrapper.apply (/directus/node_modules/vm2/lib/bridge.js:485:11)
directus | at handler (/directus/node_modules/directus/dist/operations/exec/index.js:24:22)
directus | at async FlowManager.executeOperation (/directus/node_modules/directus/dist/flows.js:330:28)

Unfortunately I was not able to reproduce this on my end. However judging from your error logs, I believe this is due to a misconfigured flow (`operations/exec/index.js` is the source code for Run Script operation, `vm2` is the underlying library used by Run Script).

Can you share the Run Script? or maybe what is the value you are passing to `FLOWS_EXEC_ALLOWED_MODULES` (in case that's the issue)? Closing this for now, but will re-open once more information is available.

**Closed by azrikahar** 2022-12-01 07:35 UTC

**Comment by hulinux** [comment] 2022-12-01 15:02
Yes, I forgot one detail, before my collection is written to the database, I added A filter type flow (create and update trigger), which is to calculate the collection field A and assign the value to field B, and then give the system to write the data, describing the phenomenon before editing the data and submitting the update.
