### ISSUE TITLE
Insert media modal appears underneath current insert/edit  image modal

### ISSUE THREAD

**Issue by Kainkainkain** [directus/directus#4765] opened 2021-03-31 02:28 UTC
Testing Directus for CMS usability. 
Editing article in demo build, 
In WYSIWYG
Click insert/edit image button 
Modal appears with source option. Click upload icon on right. 
New modal appears within the faded black underneath (lower z-index) current modal. Have to close current modal to access, which assumably ruins the callback and completion of the test task: add a new image to page. 

![image](https://user-images.githubusercontent.com/14058742/113082119-9b302100-9225-11eb-8236-9f1cde8a5715.png)

### Project details
Directus Version: 9.0.0-rc.50
Environment: production
OS: Linux 4.4.0
Node: 15.12.0

**Comment by Nitwel** [comment] 2021-03-31 07:41
Duplicate of #4354
There is already a PR that will fix this, it just has to get merged.

**Closed by Nitwel** 2021-03-31 07:41 UTC
