### ISSUE TITLE
Relation not shown correctly in RC.100

### ISSUE THREAD

**Issue by eXsiLe95** [directus/directus#9338] opened 2021-11-02 09:22 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In a collection, when having a relation and showing the relationship-step in the editor of this field, the relation is not shown correctly. The related collection will not show up, and when visiting the items of this collection, the field for this collection will not show up anymore since visiting the Relationship tab.

### To Reproduce

1. Create a collection "A"
2. Create a collection "B"
3.1. In collection "B" create a M2O relation on "A"
4. Create an item of collection "A"
5. Create an item of collection "B" and relate the previously created item
6. Go to collection > collection "B" > relation field
7. Check the "Relationship" tab: The related collection is not shown
8. Go to items > collection "B"
9. Check the created item: The relation field is not shown

![image](https://user-images.githubusercontent.com/31202904/139819515-355da12b-312e-46bb-9115-c09c34c87b92.png)

![image](https://user-images.githubusercontent.com/31202904/139820099-e2d33805-a801-405b-acd3-ed86ea1832ce.png)

### Errors Shown

See steps to reproduce (no errors shown in logs)

### What version of Directus are you using?

v9.0.0-rc.100

### What version of Node.js are you using?

v16.10.0

### What database are you using?

PostgreSQL 14.0 (Debian 14.0-1.pgdg110+1)

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally, Docker

**Comment by eXsiLe95** [comment] 2021-11-02 09:26
I could not recreate this issue in rc.99 (tested just now on the same system)

**Comment by azrikahar** [comment] 2021-11-02 09:38
Should be duplicate of #9182 #9250.

> I could not recreate this issue in rc.99 (tested just now on the same system)

Thanks for verifying 👍that should be correct since this bug were confirmed to be introduced in rc.100.

**Closed by azrikahar** 2021-11-02 09:38 UTC
Labels: Bug (Potential)
