### ISSUE TITLE
Error: Cannot find module '@directus/app/package.json'

### ISSUE THREAD

**Issue by lessborders** [directus/directus#15429] opened 2022-09-06 16:12 UTC
### Describe the Bug

Running `directus start` on latest version (plesk installation with passenger) throws an error.

Admin page is not accessible.

### To Reproduce

Follow all steps on official docs until 11)
https://docs.directus.io/self-hosted/installation/plesk.html#installation

### Errors Shown

```
App 12573 output: Error: Cannot find module '@directus/app/package.json'
App 12573 output: Require stack:
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/@directus/shared/dist/cjs/utils/node/resolve-package.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/@directus/shared/dist/cjs/utils/node/get-extensions.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/@directus/shared/dist/cjs/utils/node/index.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/extensions.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/services/graphql/index.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/services/index.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/middleware/respond.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/controllers/activity.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/app.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/server.js
App 12573 output: - /var/www/vhosts/lessborders.com/api.lessborders.com/index.js
App 12573 output: - /usr/share/passenger/helper-scripts/node-loader.js
App 12573 output:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
App 12573 output:     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
App 12573 output:     at resolvePackage (/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/@directus/shared/dist/cjs/utils/node/resolve-package.js:9:43)
App 12573 output:     at ExtensionManager.getSharedDepsMapping (/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/extensions.js:243:103)
App 12573 output:     at ExtensionManager.generateExtensionBundles (/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/extensions.js:215:46)
App 12573 output:     at ExtensionManager.load (/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/extensions.js:154:45)
App 12573 output:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
App 12573 output:     at async ExtensionManager.initialize (/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/extensions.js:93:13)
App 12573 output:     at async createApp (/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/app.js:108:5)
App 12573 output:     at async createServer (/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/server.js:45:38) {
App 12573 output:   code: 'MODULE_NOT_FOUND',
App 12573 output:   requireStack: [
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/@directus/shared/dist/cjs/utils/node/resolve-package.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/@directus/shared/dist/cjs/utils/node/get-extensions.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/@directus/shared/dist/cjs/utils/node/index.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/extensions.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/services/graphql/index.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/services/index.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/middleware/respond.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/controllers/activity.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/app.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/node_modules/directus/dist/server.js',
App 12573 output:     '/var/www/vhosts/lessborders.com/api.lessborders.com/index.js',
App 12573 output:     '/usr/share/passenger/helper-scripts/node-loader.js'
App 12573 output:   ]
:

```

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

MySQL MariaDB 10.4

### What browser are you using?

Chrome

### How are you deploying Directus?

Plesk (Passenger)

**Comment by rijkvanzanten** [comment] 2022-09-06 16:25
Duplicate of https://github.com/directus/directus/discussions/15091#discussioncomment-3573206

**Closed by rijkvanzanten** 2022-09-06 16:25 UTC
