### ISSUE TITLE
Unable to delete user

### ISSUE THREAD

**Issue by shankiflang** [directus/directus#13699] opened 2022-06-03 12:54 UTC
### Describe the Bug

I can't delete user because user have files

### To Reproduce

Create a user, upload an image, and try to delete user

### Errors Shown

{
  "errors": [
    {
      "message": "delete from \"directus_users\" where \"id\" in ($1) - update or delete on table \"directus_users\" violates foreign key constraint \"directus_files_uploaded_by_foreign\" on table \"directus_files\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

16

### What database are you using?

13

### What browser are you using?

chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-06-03 13:23
Thanks for opening this issue! However this is a duplicate of an existing issue #9507, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #9507 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-06-03 13:23 UTC
