### ISSUE TITLE
Can't delete M2O relations

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#12679] opened 2022-04-11 10:43 UTC
### Describe the Bug

Directus does not allow me to delete a M2O field.

### To Reproduce

1. Create collection A
2. Create collection B
3. Create M2O field in collection A pointing to B
4. Proceed to delete the previously created field

### Errors Shown

![image](https://user-images.githubusercontent.com/14786440/162723827-4ed33d33-1e4a-47f6-9972-32b772503b62.png)

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-04-11 10:55
Thanks for opening this issue! However this is a duplicate of an existing issue #12478, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #12478 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-11 10:55 UTC
Labels: Bug (Potential)
