### ISSUE TITLE
Gatsby source directus fails on build but fine on develop

### ISSUE THREAD

**Issue by unmaskz** [directus/directus#9812] opened 2021-11-15 14:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Using gatsby source directus and works fine on develop builds fine etc, but when it comes to build getting:

Cannot query field "directus" on type "Query".

Tried various versions to see if issue with a later version etc.

        "@directus/gatsby-source-directus": "9.0.0-rc.101",
        "gatsby": "^4.0.0",

### To Reproduce

Try build using the above dependencies.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.17.0

### What database are you using?

Running directus via docker

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Runnign locally

**Comment by azrikahar** [comment] 2021-11-16 03:25
This might be the same root cause with #9767. Can you try this here: https://github.com/directus/directus/issues/9767#issuecomment-968647490, and let us know how it goes?

I'll close this for now just so we can track this over the aforementioned issue, but feel free to update us in this issue regarding the workaround in the link above.

**Closed by azrikahar** 2021-11-16 03:25 UTC
Labels: Bug (Potential)

**Comment by jeffstahlnecker** [comment] 2021-11-19 21:27
I'm having this issue, and the workaround in the above link does not solve the problem.

**Comment by azrikahar** [comment] 2021-12-02 02:44
@jeffstahlnecker Thanks for the reminder. I haven't personally looked into it, and this may end up totally unrelated, but this might be something to do with the gatsby source package itself, as described here: https://github.com/directus/directus/issues/9903#issuecomment-975184045

Feels like most recent Gatsby related issues may stem from the depended gatsby source package since I believe there weren't any changes to the `@directus/gatsby-source-directus` package from our side for quite some time, except for the dependency updates.

**Comment by shi-rudo** [comment] 2021-12-08 18:58
directus: 9.2.1

same problem here with gatsby-source-directus 9.2.1 failing on production build, but running fine on development
```Cannot query field "directus" on type "Query".```

switching to gatsby-source-directus 9.0.0-rc.95 as workaround **DID NOT** solve the issue

note: as a temporary workaround I am using **gatsby-source-graphql**

**Comment by vhaguet** [comment] 2021-12-08 19:10
Alternatively, you can use gatsby-source-graphql `yarn add gatsby-source-graphql` with this code below for gatsby image :
```
// gatsby-node.js
exports.createResolvers = async ({
  actions,
  cache,
  createNodeId,
  createResolvers,
  store,
  reporter,
}) => {
  const { createNode } = actions;

  const resolvers = {
    DirectusData_directus_files: {
      imageFile: {
        type: "File",
        resolve: (source) => {
          // console.log(source.id);
          if (!source || !source.id) {
            return null;
          }
          const url = `${process.env.GATSBY_API_URL}/assets/${source.id}`;

          return createRemoteFileNode({
            url: encodeURI(url),
            store,
            cache,
            createNode,
            createNodeId,
            httpHeaders: {
              Authorization: `Bearer ${process.env.GATSBY_API_TOKEN}`,
            },
            reporter,
          });
        },
      },
    },
  };
  createResolvers(resolvers);
};
```

And configure like that : 
```
// gatsby-config.js
{
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "DirectusData",
        fieldName: "allDirectus",
        url: `${process.env.GATSBY_API_URL}/graphql`,
        headers: {
          Authorization: `Bearer ${process.env.GATSBY_API_TOKEN}`,
        },
        batch: true,
      },
}
```

**Comment by cdanny358** [comment] 2021-12-09 16:04
I'm fairly sure this issue has to do with Gatsby 4. In section 2 of their [v3 -> v4 plugin migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/), they state that you no longer can call `createRemoteFileNode` inside `createResolvers`, and offer an alternative means to create file nodes. Unfortunately, it means a fairly major rewrite of `gatsby-source-directus`. The existing plugin for some reason works in develop mode with Gatsby 4, but fails on build.
