### ISSUE TITLE
M2M Relationships throws 403 Error in Admin (wrong API call is made)

### ISSUE THREAD

**Issue by mirkoreichlin** [directus/directus#17314] opened 2023-01-26 19:28 UTC
### Describe the Bug

Logged in as Admin (all rights) and go to my Gallery collection. The collections contains a M2M relation to pictures. When I click on one of the added pictures, a 403 FORBIDDEN error is shown - even though everything works fine in the background. I dismiss the error and continue working.

I took me a minute to figure out what happens:
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/52787368/214929670-e15354a7-fd06-4084-8f4d-78391531f4f5.png">

The admin interface calls the following URL:
https://mirkoreichlin.ch/directus/items/galleries_files/c8ec11d9-99b2-4411-ad95-f558940d9

However, the right call would be something like:
https://mirkoreichlin.ch/directus/items/galleries_files/17

### To Reproduce

- Create Collection with M2M relation to files.
- Add item to collection and add a few images
- Save
- Open the collection item -> Error

### Errors Shown

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/52787368/214929670-e15354a7-fd06-4084-8f4d-78391531f4f5.png">

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

The version from your docker image

### What database are you using?

postgres:15.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by paescuj** [comment] 2023-01-26 19:42
Duplicate of #17108. This has been fixed by #17210 which will be available in the next release.

**Closed by paescuj** 2023-01-26 19:42 UTC

**Comment by mirkoreichlin** [comment] 2023-01-26 19:50
Awesome, thank you! And great product!

**Comment by fentonfentonfenton** [comment] 2023-01-31 09:34
@paescuj hey - would be great if this fix could be released :)
