### ISSUE TITLE
Custom Module / Process is not defined

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#4624] opened 2021-03-22 23:14 UTC
Trying to load custom module... Javascript ERROR in browser:

Couldn't load custom module "roman"
r @ app.bbbc045c.js:1
async function (async)
r @ app.bbbc045c.js:1
ju @ app.bbbc045c.js:1
cd49 @ app.bbbc045c.js:1
s @ app.bbbc045c.js:1
0 @ app.bbbc045c.js:1
s @ app.bbbc045c.js:1
a @ app.bbbc045c.js:1
(anonymous) @ app.bbbc045c.js:1
(anonymous) @ app.bbbc045c.js:1
app.bbbc045c.js:1 ReferenceError: process is not defined

---

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Windows_NT 10.0.18363
Node: 15.9.0

**Comment by rijkvanzanten** [comment] 2021-03-22 23:22
Are you using `process` anywhere in your custom module?

**Comment by ernst86913** [comment] 2021-03-22 23:37
No - I am using the demo module as described in the howto.

It seems it has something to do with the environment variable not being set in the rollout ?!

LG,
Roman

Von meinem iPhone gesendet

**Comment by rijkvanzanten** [comment] 2021-03-22 23:40
Yeah.. there have been some issues since the Vue-dependencies started slowly migrating from Vue 2 to Vue 3.. I'll close this as a duplicate of https://github.com/directus/directus/issues/4401 (/ https://github.com/directus/directus/issues/4564) for now

**Closed by rijkvanzanten** 2021-03-22 23:40 UTC
Labels: Needs More Info
