### ISSUE TITLE
App access users can't make bookmarks in rc44

### ISSUE THREAD

**Issue by vinksz** [directus/directus#4376] opened 2021-03-04 09:10 UTC
Users can't make bookmarks , says internal server error... are my permissions correct? (can make bookmarks from collection objects with admin access tho..)

![image_2021-03-04_110353](https://user-images.githubusercontent.com/73794103/109939005-4e663280-7cd9-11eb-94df-29da584e014f.png)

![image_2021-03-04_110653](https://user-images.githubusercontent.com/73794103/109939441-b9b00480-7cd9-11eb-85aa-8c5a84ef63c5.png)

---

### Project details
Directus Version: 9.0.0-rc.44
Environment: production
OS: Linux 5.4.0-66-generic (Ubuntu 18.04 oneclickinstall on digitalocean)
Node: 14.16.0

**Comment by rijkvanzanten** [comment] 2021-03-04 14:56
Duplicate of https://github.com/directus/directus/issues/4369

**Closed by rijkvanzanten** 2021-03-04 14:56 UTC
