### ISSUE TITLE
Foreign Key issues in SQLite

### ISSUE THREAD

**Issue by roelvan** [directus/directus#10842] opened 2022-01-04 12:51 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a few m2m fields in a singleton collection. Every time I create or delete another image field to this collection it removes all content in those m2m fields. Other fields in the same collection are not affected.

### To Reproduce

[Full video](https://cln.sh/qnL6Z7) on how to reproduce.

1. add items to a m2m field in a singleton collection
2. create or delete a new image field in this collection (not sure if it has to be an image field or just any field)
3. go to your singleton item and notice how the m2m fields are empty now

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

16.3.1

### What database are you using?

SQLite

### What browser are you using?

Firefox Dev Edition 96.0b9

### What operating system are you using?

macOS

### How are you deploying Directus?

deployed using CLI on an ubuntu instance

**Comment by roelvan** [comment] 2022-01-04 13:04
My DB table looks like this (the rows still exist but the relation to the singleton collection is being NULLED):
![CleanShot 2022-01-04 at 14 02 22@2x](https://user-images.githubusercontent.com/2583837/148063219-e2290387-482f-49d2-8dc9-2d7ce4602639.png)

**Comment by azrikahar** [comment] 2022-01-04 13:22
Thanks for the video and reproduction steps. Can confirm this happens on SQLite, but not PostgreSQL. May be related to SQLite having to technically re-create the table when the schema changes, thus "losing" or null-ing the related rows.

**Comment by rijkvanzanten** [comment] 2022-01-04 17:20
cc @nickrum

**Comment by roelvan** [comment] 2022-01-04 17:26
This is the automatically configured trigger for m2m relations:
<img width="852" alt="CleanShot 2022-01-04 at 18 22 35@2x" src="https://user-images.githubusercontent.com/2583837/148098642-d0fd9b87-ae10-4d45-8543-4f71aa164083.png">

Seems to stroke with what @azrikahar is saying.

**Comment by nickrum** [comment] 2022-01-04 17:40
This seems to be a duplicate of #10307 which has already been fixed in Knex. Let's keep this issue open until they release a new version.

**Comment by manufest** [comment] 2022-01-13 13:17
> This seems to be a duplicate of #10307 which has already been fixed in Knex. Let's keep this issue open until they release a new version.

Is there any way to get arround this bug? Can't wait for a release and had fatal data loss two times already.

**Comment by roelvan** [comment] 2022-01-13 13:37
> > This seems to be a duplicate of #10307 which has already been fixed in Knex. Let's keep this issue open until they release a new version.
> 
> Is there any way to get arround this bug? Can't wait for a release and had fatal data loss two times already.

The workaround is to relink your foreign keys since the related rows are still in your database. This would mean logging in to your server and run sqlite queries there.

**Comment by manufest** [comment] 2022-01-15 12:38
> The workaround is to relink your foreign keys since the related rows are still in your database. This would mean logging in to your server and run sqlite queries there.

I have so many deeply nested and related collections with additional translations and attached files in my project - any change to the data structure is like pure hell right now. Thanks @rijkvanzanten for bringing this up on the knex project!

**Comment by roelvan** [comment] 2022-01-18 10:52
Good news seems like knex shipped the fix in its v1 release: https://github.com/knex/knex/releases

**Comment by manufest** [comment] 2022-01-25 09:26
Did somebody try if this works with Directus? Any chance this will be included in the next release?

**Comment by rijkvanzanten** [comment] 2022-01-25 14:37
@manufest The knex v1 release includes another big change that swaps out Mapbox's node-sqlite in favor of vscode/sqlite by default. That's a good change on paper, but vscode's version doesn't include pre-built binaries, which may or may not cause issues when installing directus, as it would require you to have all the build dependencies for SQLite available on the system as well. 🤔

**Comment by roelvan** [comment] 2022-01-25 14:58
Losing a lot of data seems worse than having installation issues with sqlite?

**Comment by rijkvanzanten** [comment] 2022-01-25 15:04
@roelvan When you put it like that, certainly. 

If you put it like: _Prevent installing Directus completely regardless of database used because of an optional dependency that most likely won't build on your local environment._ it becomes a little more iffy 🙃

**Comment by eikaramba** [comment] 2022-04-01 12:40
it seems better-sqlite3 is also supported now https://github.com/knex/documentation/pull/369
It also bundles prebuilt binaries. Is that an option maybe?
others have quite some success switching to it https://github.com/backstage/backstage/issues/9912

**Comment by rijkvanzanten** [comment] 2022-04-01 13:24
@eikaramba I believe Knex switched their defaults to `@vscode/sqlite`, but I believe there were some issues with the prebuilt binaries there 🤔

**Comment by eikaramba** [comment] 2022-04-01 13:33
more infos on the binary part. https://github.com/microsoft/vscode-node-sqlite3/issues/16#issuecomment-1046059712

yes the default is @vscode but they will soon need to switch. i guess i should post an issue on knex.

**Comment by rijkvanzanten** [comment] 2022-04-01 13:37
Oh my, I didn't realize they were intending on removing that fork again 😨

**Comment by eikaramba** [comment] 2022-04-01 13:38
FYI: posted a issue on https://github.com/knex/knex/issues/5097

**Comment by NilsBaumgartner1994** [comment] 2022-04-12 13:42
Push, we also face this issue after migrating in production.

**Comment by joselcvarela** [comment] 2022-04-13 18:45
Keywords:
m2m existing data remove after o2m create new field sqlite junction table file image

**Comment by kibertoad** [comment] 2022-04-14 10:46
we are moving back to sqlite3 in 2.0.0 soon

**Comment by rijkvanzanten** [comment] 2022-04-14 16:05
> we are moving back to sqlite3 in 2.0.0 soon

Sweet! We can't wait 🙂 

This whole Sqlite forking adventure has become quite confusing, from Mapbox ignoring it, VS Code taking over, but then indicating to go back to upstream, to now Ghost officially taking over 🎊

**Comment by kibertoad** [comment] 2022-04-21 20:33
@rijkvanzanten 2.0.0 is out!

**Comment by rijkvanzanten** [comment] 2022-04-21 20:35
> @rijkvanzanten 2.0.0 is out!

You're a hero ❤️

**Comment by djmtype** [comment] 2022-04-23 18:58
Still getting this error with v9.9.1

**Closed** 2022-05-03 14:20 UTC
Labels: Bug, DB: SQLite, External
