### ISSUE TITLE
Directus SDK refresh auto not working.

### ISSUE THREAD

**Issue by TomS-** [directus/directus#9639] opened 2021-11-09 09:46 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Since updating the 9.0.0 I'm having issues with login persisting. For the login function I am doing:
```
await directus.auth.login(
            { email: email, password: password },
            { refresh: { auto: true } }
);
```
However, I get the following error after some time:
```
tslib.es6.js:74 Uncaught (in promise) Error: Token expired.
    at Transport.<anonymous> (index.js:1)
    at Generator.throw (<anonymous>)
    at rejected (tslib.es6.js:72)
```
In previous versions I would be kept logged in and the token would auto refresh as expected. 

### To Reproduce

Use the Javascript SDK and use `{ refresh: { auto: true } }` the token will not auto refresh. 

### Errors Shown

```
tslib.es6.js:74 Uncaught (in promise) Error: Token expired.
    at Transport.<anonymous> (index.js:1)
    at Generator.throw (<anonymous>)
    at rejected (tslib.es6.js:72)
```

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.17.6

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Digital Ocean

**Comment by joselcvarela** [comment] 2021-11-09 16:02
Hello @TomS- 
In fact our SDK was refactored. You can see what have changed here: https://github.com/directus/directus/pull/9080
But this could still be an issue. In order to triage, I need you to post how are you setting up the SDK, making the login and how are you fetching the items.

**Comment by joselcvarela** [comment] 2021-11-09 17:59
Also, what value has your `ACCESS_TOKEN_TTL`?

**Comment by TomS-** [comment] 2021-11-10 09:06
Hi @joselcvarela 

I'm setting up the SDK by:
```
import { Directus } from '@directus/sdk';
const directus = new Directus('https://portal.***.dev/');
```
I am then doing:
```
await directus.auth.login({
            email: email,
            password: password 
});
```
(Updated based on your link, auto-refresh is on by default, but the problem still persists)

I am fetching items by:
```
const printJobsItems = await directus.items('print_jobs').readMany({
            filter: {
                        id: { _in: salesOrder.print_production }
            }
});
```

My `.env` settings for access tokens are as follows:
```
ACCESS_TOKEN_TTL="15m"
REFRESH_TOKEN_TTL="7d"
REFRESH_TOKEN_COOKIE_SECURE=false
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"
```

**Comment by joselcvarela** [comment] 2021-11-10 09:26
Thank you @TomS- 
After the login, can you tell how much time has passed until the error is thrown?
My tests were similar to your configuration and didn't have issues.

Also, can you make the same requests using the API endpoints?
It could also be some misconfiguration or bug in API side.

**Comment by TomS-** [comment] 2021-11-10 09:57
Hi @joselcvarela

It does it exactly on 15 minutes. From what I can tell, if I inspect element and go to `Application > Cookies` there is no `refresh_token` set.

**Comment by joselcvarela** [comment] 2021-11-10 17:14
It seems to be something with your server because the SDK or any JS side has access to cookies.
Actually I am currently testing this. I already have test Nodejs and no problem found. And, right now, I am keeping a tab open making requests and also no problem found.

So, since you are no cookie set I believe there's some misconfiguration.
Can you check if `login` request has `Set-Cookie` on response headers? In fact, it would be useful to post a screenshot here. Maybe the domain on cookie could be misconfigured.

**Comment by joselcvarela** [comment] 2021-11-10 17:58
Just found an interesting scenario but it is totally expected.
So I was running SDK tests under Profile A on browser.
Also, I have opened the `/admin` under the same profile.

This can leads to unexpected behaviours like cookie not be present, because both will share the cookie.
Do you think you have done something similar?
If so, try with 
```js
const sdk = new Directus("http://localhost:8055", { auth: { mode: 'json' } });
```

Although this is not advised on browsers. Check here why: https://docs.directus.io/reference/sdk/#options.auth

**Comment by TomS-** [comment] 2021-11-11 09:45
> It seems to be something with your server because the SDK or any JS side has access to cookies. Actually I am currently testing this. I already have test Nodejs and no problem found. And, right now, I am keeping a tab open making requests and also no problem found.
> 
> So, since you are no cookie set I believe there's some misconfiguration. Can you check if `login` request has `Set-Cookie` on response headers? In fact, it would be useful to post a screenshot here. Maybe the domain on cookie could be misconfigured.

![image](https://user-images.githubusercontent.com/4595662/141275304-72ac1da5-cf29-42b8-b17a-a3f95a8e08a3.png)

"Set-Cookie header was blocked due to user prefernces."

Interestingly I haven't changed any of my preferences in Chrome. So I tried Firefox, and while Firefox doesn't report an error, it doesn't set the cookie either. 

![image](https://user-images.githubusercontent.com/4595662/141275995-06a20e51-ad46-4993-8e53-12ffa5f1d88e.png)

**Comment by joselcvarela** [comment] 2021-11-11 13:59
Are you running on `localhost`? Try `127.0.0.1` instead on Chrome and Firefox and check if that works.
I am moving this into a discussion since it seems there's no issue but a misconfiguration.

**Closed** 2021-11-11 13:59 UTC
Labels: Needs More Info, Package: sdk
