### ISSUE TITLE
Adding M2O field to system table throws error

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#12393] opened 2022-03-25 17:20 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When attaching a M2O field to system table, throws an error (see below).
Although the field is created but is misconfigured, because after I went to the user view it says `The relationship hasn't been configured correctly`

Also, when deleting the field causes the same error.

I tested both on SQLite and Postgres and it only happens on SQLite, but please be sure.

### To Reproduce

1. Create a collection `groups` with just `id` and `name` (input field)
2. Create M2O field `group` on `directus_users` pointing to `groups`
3. Field is created but Error is thrown
4. Delete the created field
5. Error is thrown

### Errors Shown

```
{
  "errors": [
    {
      "message": "DROP TABLE \"directus_users\" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```
<img width="420" alt="Screenshot 2022-03-25 at 17 09 49" src="https://user-images.githubusercontent.com/14039341/160169149-990b8126-da6e-4f72-a138-b57b52832296.png">

### What version of Directus are you using?

9.7.1 (Directus Community)

### What version of Node.js are you using?

Directus Community

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Directus Community

**Comment by rijkvanzanten** [comment] 2022-03-25 17:22
@joselcvarela is this a duplicate of https://github.com/directus/directus/issues/11906#issuecomment-1077365267 ?

**Comment by joselcvarela** [comment] 2022-03-25 17:26
@rijkvanzanten I just tested #11906 and have no issue so I think this is different

**Comment by colemahatmccreary** [comment] 2022-03-26 22:51
similar issue happening in standard cloud 9.7.1 when creating a m20 field on any normal (user generated) collection. for instance, when creating an subscription_id m20 field on a "payment" collection , saving the field throws the following error:

<img width="569" alt="Screen Shot 2022-03-26 at 11 06 49 AM" src="https://user-images.githubusercontent.com/40645344/160259518-13d07526-67ae-49e0-bfe8-f8c23bb8a04c.png">

The field then appears in the collection with the following notice:
<img width="658" alt="Screen Shot 2022-03-26 at 11 16 20 AM" src="https://user-images.githubusercontent.com/40645344/160259537-ce53d468-2781-4f90-80c6-3d62fd91a674.png">

Deleting the broken field causes it to disappear momentarily before reappearing, so you're basically stuck.

**Comment by alsherif-khalaf** [comment] 2022-04-08 09:46
Same or related issue 
when adding a field to users data model , it can't be removed 
I tried using v 9.7 , 9.8 

https://user-images.githubusercontent.com/73169053/162410819-aebc1cca-a231-4a2c-8fdc-ea47f335c081.mp4

**Comment by rijkvanzanten** [comment] 2022-04-08 13:49
@alsherif-khalaf Are you using SQLite too?

**Comment by alsherif-khalaf** [comment] 2022-04-09 19:24
> @alsherif-khalaf Are you using SQLite too?

yes

**Comment by rijkvanzanten** [comment] 2022-04-11 19:16
I believe this is a duplicate of #10842

**Closed by rijkvanzanten** 2022-04-11 19:16 UTC
Labels: API, Bug, DB: SQLite

**Comment by eikaramba** [comment] 2022-05-27 22:57
unfortunately this problem still exists in directus 9.11.1 :/ You can't add a M2O Field to the directus_users collection when using SQLite. https://github.com/directus/directus/issues/10842 didn't seemed to have helped for this particular issue here

**Comment by rijkvanzanten** [comment] 2022-05-31 15:51
@eikaramba Mind opening a new issue? Ty!

**Comment by eikaramba** [comment] 2022-05-31 21:46
@rijkvanzanten I spend a few hours and have to admit that it was my fault ;) there was code there to assign a role id which was not there on the test system. so all good from my side. sorry for that confusion. i also should have setup a clean project before saying that it does not work. i wasn't aware that this code was still there.
