### ISSUE TITLE
Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })

### ISSUE THREAD

**Issue by TLMondo** [directus/directus#21871] opened 2024-03-15 10:55 UTC
### Describe the Bug

I made the latest update to `10.10.4` after seeing that GraphQL calls were failing. No change. I was looking at the logs and the only thing that seems related is this entry every time I try and load the Insights dashboard (which is using graphql):
`[14:19:55.243] ERROR: TypeError[Profile_Use_Cases.Profile_id]: Definition object should contain 'type' property: Object({ type: undefined, resolve: [function resolve] })`

One of my coworkers say they continue to get internal server error replay from the graphql api too. Looking in the UI, there IS a type of Integer for the field... but because it’s a Relationship, shouldn’t it be Alias?

I have manually compared similar fields within the `directus.fields` table, and matched as much as I could.
- I've removed `hidden:true`
- I've set `special` to `m2o` as some others had
-  `interface:select-dropdown-m2o`
- `options:{"template": "{{profile_name}}"}`    (I also tried adding `type` into there with different values like `int`, `string`, `input`, `select`, `select-dropdown-m2o`)
- `display:related-values`

### To Reproduce

- Self-hosted Docker instance
- Migrate from `10.10.2` to `10.10.4` (i did 10.10.3 in between as a validation)
- Run `npx directus migrate:latest` from within container
- Logged in as Admin --> Any Insights dashboard

Same issue as the following tickets, but I'm not using Supabase:
- https://github.com/directus/directus/issues/14491
- https://github.com/directus/directus/issues/16836

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by TLMondo** [comment] 2024-03-15 10:56
<img width="1407" alt="image" src="https://github.com/directus/directus/assets/7502754/9afda2f3-b65c-485f-a7f4-92fd72be2232">

![image (1)](https://github.com/directus/directus/assets/7502754/35220eb4-344b-4dfb-8cd6-1960a20e10a4)
![image (2)](https://github.com/directus/directus/assets/7502754/290a83a9-1535-493b-955d-0de157c6aa8d)
![image (3)](https://github.com/directus/directus/assets/7502754/e53eb2e0-add8-48b8-81b4-e86c08ef0da9)
![image](https://github.com/directus/directus/assets/7502754/e4093585-93b9-4e50-85f8-055b6af276be)

**Comment by TLMondo** [comment] 2024-03-15 12:44
I now suspect this might be a problem with it traversing foreign keys. Somehow, someone managed to either link a bunch of tables to a table that didn't exist, or it got deleted. Hunting done the foreign keys, and worse Deleting/Altering them, is proving VERY complicated.

**Comment by wuservices** [comment] 2024-05-16 04:41
I had a similar issue. Your hint about foreign keys was right on. I was testing with a database with a ton of existing tables, some of which were excluded via env variable.

First, I had a table with a foreign key reference to another table I had excluded. Once I fixed that, I found a few instances of tables with multi-column foreign key references, which are presumably unsupported as I know that multi-key primaries aren't supported. Once I also excluded those tables, this error went away. Something more graceful like not crashing would be nice.

I was testing out `directus-sync`, which looks like it's just calling the same API via its CLI.

**Comment by rijkvanzanten** [comment] 2024-07-11 22:08
I haven't been able to reproduce this on a new installation, so it does indeed sound like the particular state of that database is what caused this. I'll have to close this for now as I can't reproduce it in isolation, but am happy to reopen and keep discussing if more information becomes available

**Closed by rijkvanzanten** 2024-07-11 22:08 UTC
Labels: :elevator: Server
