### ISSUE TITLE
conditions are not working properly

### ISSUE THREAD

**Issue by cpt-n3mo** [directus/directus#9552] opened 2021-11-06 14:50 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using conditions in a collection the conditions are not applying to the items.

### To Reproduce

Create a new collection,
Create a `checkbox` item, set default value to false,
Create a string with key `text`, go to conditions add a new rule choosing checkbox, setting value to false, tik `hide on details` and save the settings, got to the collection, text will still be there no matter what the value of the checkbox.

while doing the reverse does work, create checkbox with default value of true, add string item add a rule, checkbox set value to `false` , tik `hide on details`
now when browsing to the collection and one tiks the checkbox the rule does apply,

changing default of checkbox value to `false` will now make de rule not apply anymore
same for if default value is `true`, then rules do not apply,

this makes it very confusing when the rules apply and when not, it seems there is something wrong with Boolean interpretation, and or the rules are not loaded on browsing to the collection item,.. 

so to clarify,

while checkbox default is set to `true` and rules are set to `false` the rules apply.
while checkbox default is set to `true` and rules are set to `true` the rules do not apply.
while checkbox default is set to `false` and rules are set to `false` the rules do not apply.
while checkbox default is set to `false` and rules are set to `true` the rules do not apply

### Errors Shown

no errors are shown.

### What version of Directus are you using?

docker latest

### What version of Node.js are you using?

inside docker container

### What database are you using?

mariadb

### What browser are you using?

chrome, firefox, chromium

### What operating system are you using?

Arch Linux, 5.13.6-zen1-1-zen  x86_64 GNU/Linux

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment] 2021-11-09 13:03
Pushed a fix.

**Comment by joselcvarela** [comment] 2021-11-09 21:34
Hey @azrikahar 
Isn't this a duplicate of #8145 which have a linked PR #8154 submitted by you?
It seems very similar if not equal

**Closed** 2021-11-11 21:03 UTC
Labels: App, Bug
