### ISSUE TITLE
Sort order not being saved on a many to any fields

### ISSUE THREAD

**Issue by Piteraguayo** [directus/directus#3939] opened 2021-02-04 22:41 UTC
When creating a field "many to any" on a collection with items that are from a collection with sort field, it is expected that when editing the container collection, you can drag and drop to sort the items. This is working, we can drag and drop but when saving, the order is not saved. In the screenshot attached, I had dragged the item 1 to be the first and saved. When I come back to the saved item, the sort order looks as it was before, not with the new order. On the screenshot, the "many to any" collection expected to be sortable is "Pruebas" that has the sort field.

![sort_bug](https://user-images.githubusercontent.com/5360439/106964203-0b4c8a00-6742-11eb-9de5-fe62c18b67dd.png)

I guess that this is also happening with fields "one to many" and "many to many".

**Comment by rijkvanzanten** [comment] 2021-02-04 22:48
@Piteraguayo What version of Directus are you using? 

Please fill out the issue template next time, it's there for a reason 😉 


Duplicate of https://github.com/directus/directus/issues/3315

**Closed by rijkvanzanten** 2021-02-04 22:48 UTC
