### ISSUE TITLE
GraphQL filter argument no longer working on translations fields in rc55

### ISSUE THREAD

**Issue by AlexisWalravens** [directus/directus#4905] opened 2021-04-08 07:46 UTC
Hi since rc55 the filter argument is no longer working on translations fields.

When I query this:
```
{
  platforms {
    name,
    translations (filter:{ languages_code: { code: { _contains: "fr" }} }) {
      languages_code { code },
      title,
      description
    }
  }
}
```
I get this:
```

{
  "errors": [
    {
      "message": "GraphQL validation error.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_EXCEPTION",
        "graphqlErrors": [
          {
            "message": "Unknown argument \"filter\" on field \"platforms.translations\".",
            "locations": [
              {
                "line": 4,
                "column": 19
              }
            ]
          }
        ]
      }
    }
  ]
}
```
And it was working before in rc53

Also, I don't know if it's normal or not but, I have to make it a POST request, when used with GET I get this
```
{
  "errors": [
    {
      "message": "Must provide query string.",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```
Also while I'm here, this issue is still there in rc55: https://github.com/directus/directus/issues/4283#issuecomment-815558108

Directus rc55
MariaDB 10.5.x
Branch: npx

**Comment by rijkvanzanten** [comment] 2021-04-08 13:11
Duplicate of https://github.com/directus/directus/discussions/4889, fixed in 86d232c03cf988d6c4ebd53c4def10aa85e1c9da

**Closed by rijkvanzanten** 2021-04-08 13:11 UTC
