### ISSUE TITLE
No database created on install

### ISSUE THREAD

**Issue by khudia** [directus/directus#2250] opened 2018-11-22 07:37 UTC
No database created on clean install.
If just copy dump to db, so then i can't add user. And there is on admin@example.com but i don't know the password. What is default?

**Comment by shealavington** [comment] 2018-11-22 07:46
Password

**Comment by rijkvanzanten** [comment] 2018-11-22 14:56
Hey @khudia, can you share some more info on how to reproduce this? There must be something in your specific server setup that causes this issue, as I'm not able to reproduce it on my setup.

**Comment by RyanPrice-King** [comment] 2018-11-22 17:10
Are you positive you are running php 7?  I managed to replicate this problem when I installed php 5.4.

**Comment by benhaynes** [comment] 2018-11-22 17:11
Also, just to clarify requirements: we recently dropped support for older versions of PHP (since they are hitting EOL in a few weeks) so Directus requires PHP 7.1+ now.

**Comment by benhaynes** [comment] 2018-11-22 17:13
I'll close this one since the PHP version seems very likely to be the culprit... and the original issue should have included that info.

Also, I will be adding our GitHub Issue Bug Template to this repo now to avoid missing info in the future.

**Closed by benhaynes** 2018-11-22 17:13 UTC
Labels: help wanted, not reproducible
