### ISSUE TITLE
Cascade M2M delete not working

### ISSUE THREAD

**Issue by Pachat** [directus/directus#12334] opened 2022-03-23 18:30 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Deleting an M2M item in a parent collection does not delete the item

### To Reproduce

As Admin
1. Create `Parent_Collection` and `Related_Collection`
2. Add an `M2M_field` in `Parent_Collection` related to `Related_Collection`
3. Add an item in `Parent_Collection` with a related item in `M2M_field`
4. Save
5. Open the `Parent_Collection` item 
6. Click on the `X` at the right of the `M2M_field`
7. Save / Refresh
8. Reopen the `Parent_Collection` item 

### Errors Shown

The  `M2M_field` item is still there.

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-03-23 18:45
Duplicate of https://github.com/directus/directus/issues/12099

**Closed by rijkvanzanten** 2022-03-23 18:45 UTC
Labels: Bug (Potential)
