### ISSUE TITLE
Inviting new user, user-invitation.liquid not found

### ISSUE THREAD

**Issue by avatarbabe** [directus/directus#5713] opened 2021-05-17 07:37 UTC
When trying to invite a new user, I get the following error:
`{
  "message": "ENOENT: no such file or directory, open '/home/site/wwwroot/extensions/templates/user-invitation.liquid'",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}`

There doesn't seem to be a directory under extensions with the name 'templates'. I tried adding it + the user-invitation template but I still get the same error.

---

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Linux 5.4.0-1031-azure
Node: 14.15.1

**Comment by christianrr** [comment] 2021-05-17 08:57
Should be fixed in rc.65 by #5671. Can you try?

**Comment by avatarbabe** [comment] 2021-05-17 09:23
Thanks @christianrr , testing it now. Will get back to you with the results ASAP 👍

**Comment by benhaynes** [comment] 2021-05-17 10:49
We'll close this as fixed, let us know if it's still an issue and we'll reopen.

**Closed by benhaynes** 2021-05-17 10:49 UTC

**Comment by rijkvanzanten** [comment] 2021-05-17 14:19
Duplicate of https://github.com/directus/directus/issues/5555
