### ISSUE TITLE
InvalidQueryException when trying to use the `_contains` filter on a json field type

### ISSUE THREAD

**Issue by rhyst** [directus/directus#15049] opened 2022-08-12 15:57 UTC
### Describe the Bug

I get an InvalidQueryException when trying to use the `_contains` filter on a json field type. This works in `9.14.5` but does not in `9.15.x` so I think this exception is incorrect.

### To Reproduce

Run a 9.14.5 docker container:
```
docker run -it --rm -e KEY=test -e SECRET=test -e PUBLIC_URL=http://127.0.0.1 -p 8055:8055 directus/directus:9.14.5
```
In it create a collection "test" with a tags field. Create two items: one with tags set to "tag1" and the other with tags set to "tag2".

Get your access token and make filtered requests:
```
❯ curl -g 'localhost:8055/items/test?access_token=6eYY3-Btdkb6LxJQMHwE0wRxBczz6-Xx&filter[tags][_contains]=tag1'
{"data":[{"id":1,"tags":["tag1"]}]}⏎
❯ curl -g 'localhost:8055/items/test?access_token=6eYY3-Btdkb6LxJQMHwE0wRxBczz6-Xx&filter[tags][_contains]=tag2'
{"data":[{"id":2,"tags":["tag2"]}]}⏎
```

Run a 9.15.0 or 9.15.1 docker container:
```
docker run -it --rm -e KEY=test -e SECRET=test -e PUBLIC_URL=http://127.0.0.1 -p 8055:8055 directus/directus:9.15.0
```

In it create a collection "test" with a tags field (with type set to json). Create two items: one with tags set to "tag1" and the other with tags set to "tag2".

Get your access token and make filtered requests:
```
❯ curl -g 'localhost:8055/items/test?access_token=28fM8dOOZL_CrxH6-qjxervmwhka5hpJ&filter[tags][_contains]=tag1'
{"errors":[{"message":"\"json\" field type does not contain the \"_contains\" filter operator","extensions":{"code":"INVALID_QUERY"}}]}
```

Note that the same request now fails.

### Errors Shown

```
InvalidQueryException [Error]: "json" field type does not contain the "_contains" filter operator
    at validateFilterOperator (/directus/node_modules/directus/dist/utils/apply-query.js:256:23)
    at addWhereClauses (/directus/node_modules/directus/dist/utils/apply-query.js:219:21)
    at applyFilter (/directus/node_modules/directus/dist/utils/apply-query.js:157:5)
    at MetaService.filterCount (/directus/node_modules/directus/dist/services/meta.js:67:43)
    at /directus/node_modules/directus/dist/services/meta.js:24:29
    at Array.map (<anonymous>)
    at MetaService.getMetaForQuery (/directus/node_modules/directus/dist/services/meta.js:20:54)
    at /directus/extensions/endpoints/blog/index.js:79854:66
    at step (/directus/extensions/endpoints/blog/index.js:97:23)
    at Object.next (/directus/extensions/endpoints/blog/index.js:78:53) {
  status: 400,
  code: 'INVALID_QUERY',
  extensions: {}
```

```
{"errors":[{"message":"\"json\" field type does not contain the \"_contains\" filter operator","extensions":{"code":"INVALID_QUERY"}}]}
```

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

sqlite 

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment] 2022-08-12 16:04
Duplicate of https://github.com/directus/directus/issues/10635

**Closed by rijkvanzanten** 2022-08-12 16:04 UTC
