### ISSUE TITLE
EXTENSIONS_AUTO_RELOAD got stuck after invalid extension

### ISSUE THREAD

**Issue by amo42** [directus/directus#11321] opened 2022-01-28 14:09 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Once the EXTENSIONS_AUTO_RELOAD is set, changes on an extension are automatically reloaded as expected unless the extension itself is invalid. 

In case of an error like this:
```
pm_directus    | 13:32:25 ✨ Reloading extensions
pm_directus    | 13:32:25 ⚠️  Couldn't register hook "my-awesome-hook"
pm_directus    | 13:32:25 ⚠️  c is not defined
```

I made a typo in the file. After fixing the type and deploy the hook again, the same error is shown:

```
pm_directus    | 13:32:45 ✨ Reloading extensions
pm_directus    | 13:32:45 ⚠️  Couldn't register hook "my-awesome-hook"
pm_directus    | 13:32:45 ⚠️  c is not defined
```
After restarting the docker container, the same file from 13:32:45 could be loaded without any problem, and the hook works as expected.

It looks the error/file is kind of "cached".

Workaround: restart the server/docker container, but this is not the behavior the EXTENSIONS_AUTO_RELOAD should work.

Best regards
Andreas

### To Reproduce

1. Have clean Directus 9.5.0 setup (I used docker)
2. set the ENV `EXTENSIONS_AUTO_RELOAD` to `true`
3. deploy a working extension (a hook in my special case) --> loaded correctly, what is OK
4. re-deploy with a typo or undefined variable --> can not load the hook, what is still OK
5. fix the typo/js error and redeploy --> still can not load the hook, which it NOK

### Errors Shown

```
//… started docker
pm_directus    | 13:19:37 ✨ Initializing bootstrap...
pm_directus    | 13:19:37 ✨ Database already initialized, skipping install
pm_directus    | 13:19:37 ✨ Running migrations...
pm_directus    | 13:19:37 ✨ Done
pm_directus    | 13:19:41 ✨ Loaded extensions: my-awesome-hook
//… some time later 
pm_directus    | 13:32:25 ✨ Reloading extensions
pm_directus    | 13:32:25 ⚠️  Couldn't register hook "my-awesome-hook"
pm_directus    | 13:32:25 ⚠️  c is not defined
//… deployed the fixed hook
pm_directus    | 13:32:45 ✨ Reloading extensions
pm_directus    | 13:32:45 ⚠️  Couldn't register hook "my-awesome-hook"
pm_directus    | 13:32:45 ⚠️  c is not defined
//… restarting Docker …
pm_directus    | 13:33:14 ✨ Shutting down...
pm_directus    | 13:33:14 ✨ Database connections destroyed
pm_directus    | 13:33:14 ✨ Directus shut down OK. Bye bye!
pm_directus    | npm ERR! path /directus
pm_directus    | npm ERR! command failed
pm_directus    | npm ERR! signal SIGTERM
pm_directus    | npm ERR! command sh -c directus "start"
pm_directus    |
pm_directus    | npm ERR! A complete log of this run can be found in:
pm_directus    | npm ERR!     /home/node/.npm/_logs/2022-01-28T13_33_15_389Z-debug.log
pm_directus    | 13:33:19 ✨ Loaded extensions: my-awesome-hook
// … the same hook works now
pm_directus    | 13:33:19 ✨ Initializing bootstrap...
pm_directus    | 13:33:20 ✨ Database already initialized, skipping install
pm_directus    | 13:33:20 ✨ Running migrations...
pm_directus    | 13:33:20 ✨ Done
```

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

postgres:12

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by nickrum** [comment] 2022-01-28 21:39
I can't reproduce this when running Directus locally. Could you check if this is working for you without using Docker?

Also, are you using the extensions-sdk to build your extension or are you building it directly in CommonJS?

**Comment by amo42** [comment] 2022-01-31 07:56
Hi @nickrum,

I've tested it with Directus running locally. The exact same result occurs.

Please find attached the screen recording. I've used the following code: and "removed" the `exceptions` from imports

```
export default ({ filter, action }, {  services, exceptions, database: knex, getSchema }) => {
	const { ItemsService } = services;
	const  { InvalidPayloadException } = exceptions;

	filter('items.create', () => {
		console.log('Creating Item!');
	});

	action('items.create', () => {
		console.log('Item created!');
	});
};
```

https://user-images.githubusercontent.com/12328155/151757274-5c684c3f-50b2-45f3-a4eb-cd846120ae5e.mov

**Comment by nickrum** [comment] 2022-02-01 23:13
Thanks @amo42! In that case, this is probably a macOS-specific bug, as `chokidar`, which is the file-watcher library we are using, has a dedicated implementation for macOS.

**Comment by amo42** [comment] 2022-02-02 07:31
@nickrum sadly, I don't think this is related to a macOS specific library. 

Running Directus within Docker should use the library from Docker (base) image. Also, running this on my Ubuntu 20.04.2 server brings just the same behavior.

**Comment by amo42** [comment] 2022-02-10 12:11
As an update, the same happened also for other extensions e.g. custom endpoints

**Comment by rijkvanzanten** [comment] 2022-04-07 21:10
I see the same behavior on my end (local mac, no docker), buuuuuuuut i'm not sure if it's something we can control..

Whenever Chokidar alerts of a change in the file, we simply use `require()` again to reload the module. I think we're bumping into Node's internal module caching that is behaving funky, which is not something I think we can mess with too much 🤔 

I'll close this for now, as I don't think this is something we can do anything about on the Directus side of things, but I'm happily proven wrong 😁

**Closed by rijkvanzanten** 2022-04-07 21:10 UTC
Labels: Extensions, Can't Reproduce

**Comment by amo42** [comment] 2022-04-08 07:45
Hey @rijkvanzanten  thanks for letting me know, I agree it's nothing you can handle or change right now. But it's great to know it's not my fault :D (and even not yours)
