### ISSUE TITLE
API Environment Configuration Not Found

### ISSUE THREAD

**Issue by biofen** [directus/directus#2240] opened 2018-11-12 10:42 UTC
Hello,

I am having some issues making the API work. I've otherwise successfully installed Directus as I create records etc., I just can't query them via API. 

- Ubuntu 18.04
- PHP 7.2
- MySQL 5.7.24
- Apache 2.4.29

Steps taken:

`cd /var/www/html`
`git clone https://github.com/directus/directus.git`
Changed permission & group to www-data
`cd /etc/apache2/`
There I have inserted the following code fragment:
`<Directory />
    Options Indexes FollowSymLinks Includes ExecCGI
    AllowOverride All
    Require all granted
</Directory>`
`cd /etc/apache2/sites-available`
In here I have
`DocumentRoot /var/www/html/directus/public`
as well as a the block 
`<Directory /var/www/html/directus>
      AllowOverride All
</Directory>`
And finally a restart of Apache.

As mentioned I have no trouble accessing the UI and using it as intended which I can navigate to via `http://localhost/admin/`. Project name is Directus. However, when I try to use the API I get the following issues:
URL: `localhost/auth/authenticate` & 
Response:
`{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: auth"
    }
}`
URL: `localhost/Directus/auth/authenticate`
Response:
`{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: directus"
    }
}`

Similarly if I do:
URL: `localhost/api/_/collections`
I get
`{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: api"
    }
}`
URL: `localhost/api/Directus/collections`
I get
`{
    "error": {
        "error": 8,
        "message": "API Environment Configuration Not Found: api"
    }
}`

Not really sure where to go from here, I believe I've followed the installation instructions. Any help is appreciated, thanks :)

**Comment by benhaynes** [comment] 2018-11-12 16:08
Hey @biofen – if the App is working then the issue is most likely just the URL you're using to access the API.

If your app is at:
```
http://localhost/admin
```

Then the API would be located at:
```
# API
http://localhost/server/ping

# Default Project
http://localhost/_/collections

# Custom Project
http://localhost/custom-name/collections
```

I'll update the API Reference to be a little more clear about this directory. I'll close this since the App is working and I'm pretty confident this was just a URL misunderstanding... but let me know if it's still not working and we'll re-open and troubleshoot.

**Closed by benhaynes** 2018-11-12 16:08 UTC

**Comment by jesstucker** [comment] 2019-02-19 18:33
Just want to be clear:
if you want to access the **auth endpoint** for the default directus project, you'd go to something that looks like this:
http://localhost/_/auth/authenticate
I actually glossed over this. **Take note of the underscore**, followed by the auth endpoint /auth/authenticate

So an example curl POST request would look like this:
```
curl \
-d '{"email": "admin@project.com","password": "0s0s3cr37"}' \
-H "Content-Type: application/json" \
-X POST http://localhost/_/auth/authenticate
```
This will return your JWT token, for instance
