### ISSUE TITLE
Azure token invalid

### ISSUE THREAD

**Issue by DavidBlanchGit** [directus/directus#18336] opened 2023-04-27 08:33 UTC
### Describe the Bug

I generate a token with the azure Email that i have in directus, but when I try to use it for validation as bearer token it just say INVALID_CREDENTIALS and the error 401 like if the user dont exists or is not doing conexion with the log in.

### To Reproduce

In the .env

```env
AUTH_PROVIDERS="microsoft"
AUTH_MICROSOFT_DRIVER="openid"
AUTH_MICROSOFT_ICON="business"
AUTH_MICROSOFT_CLIENT_ID="XXXX"
AUTH_MICROSOFT_CLIENT_SECRET="XXXX"
AUTH_MICROSOFT_ISSUER_URL="https://login.microsoftonline.com/XXXX/v2.0/.well-known/openid-configuration"
AUTH_MICROSOFT_SCOPE="openid user.read mail.read"
AUTH_MICROSOFT_IDENTIFIER_KEY="email"
AUTH_MICROSOFT_REQUIRE_VERIFIED_EMAIL="false"
AUTH_MICROSOFT_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_MICROSOFT_DEFAULT_ROLE_ID="XXXX"
```

Then I generate a key with Python with the same Ids but dont work.

```python
import requests
import json

url = "https://login.microsoftonline.com/xxxx/oauth2/token"

client_id = "xxxx"
client_secret = "xxxx"

data = {
    "grant_type": "client_credentials",
    "client_id": client_id,
    "client_secret": client_secret,
    "resource": "https://graph.microsoft.com"
}

response = requests.post(url, data=data)

access_token = response.json()["access_token"]
print(access_token)

api_url = "http://localhost:8055/items/example"

headers = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}

response = requests.get(api_url, headers=headers)

print(response.json())

```

The code give me back the token but when I use the token in any method don't work, thanks for the help.

### Directus Version

v9.23.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2023-04-27 12:34
Thanks for opening this issue! However this is a duplicate of an existing issue #18304, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment.

**Closed by paescuj** 2023-04-27 12:34 UTC
