### ISSUE TITLE
Cannot delete field or collection containing M2M field

### ISSUE THREAD

**Issue by ArchOrn** [directus/directus#11355] opened 2022-01-31 14:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It is not possible to delete a field inside a new collection with a M2M relationship field.
Furthermore, it is not possible to delete the collection itself nor the M2M field nor the M2M collection. The same error message appears each time with a difference in the column name.

### To Reproduce

1. Create a new collection (primary uuid field "id", named "testest", select all premade fields except sort)
2. Add a date field (date/time format, mandatory, named "date")
3. Add a M2M files field (mandatory, named "images")
4. Delete the date field -> Error
5. Delete the "testest" collection -> Error
6. Delete the M2M collection -> Error

The mandatory option is not relevant in my further tests.

### Errors Shown

Error when deleting the date field
```
{
  "errors": [
    {
      "message": "update \"directus_fields\" set \"group\" = $1 where \"group\" = $2 and \"collection\" = $3 - invalid input syntax for type integer: \"date\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Error when deleting the collection
```
{
  "errors": [
    {
      "message": "update \"directus_fields\" set \"group\" = $1 where \"group\" = $2 and \"collection\" = $3 - invalid input syntax for type integer: \"testest_id\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

v9.5.0 (v9.4.3 at first)

### What version of Node.js are you using?

v16.13.2

### What database are you using?

PostgreSQL 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows, macOS

### How are you deploying Directus?

Debian 11

**Comment by azrikahar** [comment] 2022-01-31 15:16
This seems to be a duplicate of #9092. You should be able to resolve it by following the steps mentioned here: https://github.com/directus/directus/issues/8675#issuecomment-940629829 👍

There's also a clip related to it which hopefully makes it clearer: https://github.com/directus/directus/issues/8675#issuecomment-940940506

**Closed by azrikahar** 2022-01-31 15:16 UTC
Labels: Bug (Potential)
