### ISSUE TITLE
Translated fields don't display the corresponding language value in views

### ISSUE THREAD

**Issue by DamienMrtl** [directus/directus#17686] opened 2023-03-03 00:45 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When using translations. The field in table view doesn't adapt to the user language. But it works when adding the language code in the view.

[Capture_video_du_2022-12-21_20-38-10.webm](https://user-images.githubusercontent.com/7550391/222603029-cd86cc2f-4c90-493e-9f05-9af643c7a1d5.webm)

### To Reproduce

Create translated field and try to display it in the current user language.

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment] 2023-03-13 10:50
This is a duplicate of https://github.com/directus/directus/issues/17196. The fix https://github.com/directus/directus/pull/17395 has been merged and will be available with the next release.

**Closed by br41nslug** 2023-03-13 10:50 UTC
Labels: Duplicate
