### ISSUE TITLE
Create new collection raises an error message and no fields are created

### ISSUE THREAD

**Issue by KZ-Millennium** [directus/directus#16295] opened 2022-11-03 08:00 UTC
### Describe the Bug

I updated from 9.20.2 to 9.20.3 and tried to create a new collection when I found this bug.

Thank you for your work !

### To Reproduce

create a new collection and activate all common fields:
![image](https://user-images.githubusercontent.com/74610514/199670745-6f17b7aa-82d8-4698-b3f2-2ca1e1374e38.png)

The collection is still created despite the error message (see the first one in next section) but no fields are shown:

![image](https://user-images.githubusercontent.com/74610514/199671153-8c65bddf-2a2e-4920-a9d7-c0287bdc832f.png)

and when you try to add data:
![image](https://user-images.githubusercontent.com/74610514/199671212-dc5c12d8-022b-4bd2-b113-246fcf3f22bd.png)

### Errors Shown

{
  "errors": [
    {
      "message": "Collection \"test\" doesn't exist",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}

Then:

{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}

### What version of Directus are you using?

9.20.3

### What version of Node.js are you using?

v16.18.0

### What database are you using?

postgres (PostgreSQL) 11.13

### What browser are you using?

Firefox 106.0.1 (64 bits)

### How are you deploying Directus?

Kubernetes (with Dockerfile)

**Comment by licitdev** [comment] 2022-11-04 05:22
Closing this issue for now as I haven't been able to reproduce this issue when tested on PG 10 & PG 13. I believe this might be due to external issues such as DB permissions or proxy blocking certain requests.

Do feel free to provide more information on this thread, such as request logs from the app leading to the errors (eg: payload). Thank you.

https://user-images.githubusercontent.com/26413686/199895065-720c9384-fe37-49fd-9c84-15662d5cf0fd.mov

**Closed by licitdev** 2022-11-04 05:22 UTC
Labels: Can't Reproduce

**Comment by KZ-Millennium** [comment] 2022-11-04 06:42
I checked back today and nothing wrong... I don't know what happened. I'll check the payload next time.

Thank you for your time !

**Comment by KZ-Millennium** [comment] 2022-11-07 10:04
@licitdev  a dev told me he cannot create a collection today so I checked out and record the whole process.
I upgraded directus to 9.20.4 before recording it.

https://user-images.githubusercontent.com/74610514/200282567-c34d7722-1d7e-4b2e-89ec-a7a5b20217b1.mp4


Do you have enough info ?

**Comment by KZ-Millennium** [comment] 2022-11-07 13:39
it seems to be specific to this instance. I have another one for special test purpose on which I migrate db and files from the one with the issue and nothing wrong... Any idea ?

**Comment by licitdev** [comment] 2022-11-07 15:05
How many Directus nodes are you running? 
Is schema caching enabled?
Does the issue persist after restarting the Directus instance?

**Comment by KZ-Millennium** [comment] 2022-11-07 15:16
I'm running a single node.
The cache is enabled.
The issue persists after killing and recreating the pod.

here is the env if it can help:

ADMIN_EMAIL=XXX
ADMIN_PASSWORD=XXX
AUTH_MICROSOFT_CLIENT_ID=XXX
AUTH_MICROSOFT_CLIENT_SECRET=XXX
AUTH_MICROSOFT_DRIVER=openid
AUTH_MICROSOFT_EMAIL_KEY=email
AUTH_MICROSOFT_IDENTIFIER_KEY=email
AUTH_MICROSOFT_ISSUER_URL=XXX
AUTH_MICROSOFT_SCOPE=openid email
AUTH_PROVIDERS=microsoft
CACHE_AUTO_PURGE=true
CACHE_ENABLED=true
CACHE_REDIS=XXX
CACHE_STORE=redis
CACHE_TTL=30m
DB_CLIENT=pg
DB_DATABASE=directus
DB_FILENAME=/directus/database/database.sqlite
DB_HOST=directus-postgres-postgresql
DB_PASSWORD=XXX
DB_PORT=5432
DB_USER=directus
EMAIL_FROM=XXX
EMAIL_SMTP_HOST=XXX
EMAIL_SMTP_POOL=true
EMAIL_SMTP_SECURE=true
EMAIL_TRANSPORT=SMTP
EMAIl_SMTP_PORT=25
EXTENSIONS_PATH=/directus/extensions
HOME=/home/node
HOSTNAME=directus-deployment-6c849789f-s7qd7
KEY=XXX
LOG_LEVEL=trace
LOG_STYLE=pretty
NODE_VERSION=16.18.0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PORT=8055
PUBLIC_URL=https://cms-staging.millenniumapp.io
PWD=/directus
SECRET=XXX
SHLVL=2
STORAGE_LOCAL_ROOT=/directus/uploads
TERM=xterm
YARN_VERSION=1.22.19

**Comment by licitdev** [comment] 2022-11-07 15:50
The config does looks normal to me except for `DB_FILENAME` which should be removed as you're using PG. Additionally, maybe you could try clearing all keys in Redis. 🤔

**Comment by KZ-Millennium** [comment] 2022-11-08 08:08
@licitdev I clearly the cache from all keys and it's working again. I'll keep that in mind for the next time. Thank you for your help !
