### ISSUE TITLE
new add M2O relation error

### ISSUE THREAD

**Issue by kroawen** [directus/directus#5861] opened 2021-05-25 02:26 UTC
After update RC69, all model PK type display "unknow" and add M2O ralation can not save.
![image](https://user-images.githubusercontent.com/6927999/119430522-8793c900-bd43-11eb-8b1b-31ec5b985c8f.png)

 [INVALID_PAYLOAD] "type" must be one of [bigInteger, boolean, date, dateTime, decimal, float, integer, json, string, text, time, timestamp, binary, uuid, hash, csv, alias, o2m, m2m, m2a, files, translations, null]

**Comment by rijkvanzanten** [comment] 2021-05-25 02:33
Hiya! What database is this on?

**Comment by kroawen** [comment] 2021-05-25 06:02
@rijkvanzanten  database version: mysql  Ver 8.0.22

**Comment by rijkvanzanten** [comment] 2021-05-25 15:09
Did you setup this field in Directus, or directly in the database? Would you be able to share a database dump? I can't reproduce it on my end

**Comment by himko9** [comment] 2021-05-25 15:29
Similar issue here, same setup rc69 & MySQL 8
Using UUID as the primary key is fine
The problem seems to only occur when the primary key is "Auto-incremented integer"
https://user-images.githubusercontent.com/31000899/119524864-96fd2b80-bdb0-11eb-8c5f-0344ae291839.mp4

**Comment by kroawen** [comment] 2021-05-26 01:13
Hi, I created all field in Directus not in database.  

this is sql file export from database:

[app.zip](https://github.com/directus/directus/files/6543207/app.zip)

**Comment by kroawen** [comment] 2021-05-26 01:26
Using UUID as the PK, it  is fine, when the PK type is "Auto-incremented integer", it not work

**Comment by cteachworth** [comment] 2021-05-28 16:22
I’m experiencing the same issue with rc69 and mysql 8.0.25. UUID PKs work but auto incremented ints do not.

**Comment by rijkvanzanten** [comment] 2021-06-01 22:21
This was fixed in https://github.com/directus/directus/commit/933537240046e257d38b41692bffa2ad07c81831

**Closed by rijkvanzanten** 2021-06-01 22:21 UTC
Labels: App, Bug (Potential), Needs More Info
