### ISSUE TITLE
Error when deleting a user who has uploaded files

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#12449] opened 2022-03-29 05:13 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

A user who has uploaded files cannot be deleted.

### To Reproduce

1. Create new user
2. Upload file(s) with user
3. Try to delete user
4. Delete file(s)
5. Try to delete user

### Errors Shown

directus    | 04:47:55 🚨 error delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_foreign" on table "directus_files"
directus    | error: delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_foreign" on table "directus_files"
directus    |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
directus    |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
directus    |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
directus    |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
directus    |     at Socket.emit (node:events:526:28)
directus    |     at addChunk (node:internal/streams/readable:315:12)
directus    |     at readableAddChunk (node:internal/streams/readable:289:9)
directus    |     at Socket.Readable.push (node:internal/streams/readable:228:10)
directus    |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus    | 04:47:55 ✨ request errored DELETE 500 /users/03f369d9-3eda-48e9-b865-f58ddbc0e717 14ms

![image](https://user-images.githubusercontent.com/43739995/160535669-c2a1fda6-9f0b-4a48-8059-da120d1cd020.png)

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-04-01 02:05
Thanks for opening this issue! However this is a duplicate of an existing issue #9507, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #9507 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-01 02:05 UTC
Labels: Bug (Potential)
