### ISSUE TITLE
Getting "Cannot read property 'field' of undefined" error for all collection lists when I add one collection

### ISSUE THREAD

**Issue by medteck** [directus/directus#3561] opened 2021-01-03 13:50 UTC
# Bug description
Collection lists (files, users, custom collections) are loading infinitely and the console shows this error:
![Screenshot from 2021-01-03 08-44-32](https://user-images.githubusercontent.com/12381774/103480066-135e8600-4da0-11eb-884d-aba87a3e2d82.png).

Everything was working just fine before I added this collection:
![Screenshot from 2021-01-03 08-47-20](https://user-images.githubusercontent.com/12381774/103480117-56205e00-4da0-11eb-9059-8e28c8cf8a83.png)

# Environment
* DBMS: MySQL 8
* Deployed with npx
* Browser: Chrome 87
* No third party resource

**Comment by medteck** [comment] 2021-01-03 14:49
The bug suddenly "disappeared". I didn't change anything. Just stopped npx, forked the project to try to fix it. When I ran it again it was working fine. Weird.

**Comment by rijkvanzanten** [comment] 2021-01-03 18:10
Duplicate of https://github.com/directus/directus/issues/3322

**Closed by rijkvanzanten** 2021-01-03 18:10 UTC
