### ISSUE TITLE
Related value of a M2M field does not show after selection

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11963] opened 2022-03-05 13:04 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

`My Collection` has an M2M relationship with `My Collection2`. Interface and Display are related to `Name2` value.

When, in `My Collection` an existing `My Collection2` item is chosen, after Saving the choice, the field in `My Collection` is shown empty `--` until we save `My Collection`.

### To Reproduce

Follow this (the error appears at 40 s.)
![Select_M2M](https://user-images.githubusercontent.com/13746133/156884048-b0ec6dbd-2a2e-4ac9-a491-0fa620ca401c.gif)

### Errors Shown

The field shows `--` instead of the selected value.

Please note
1. with `Create New`, back in the parent collection, we see the value
2. with `Add Existing`, back in the parent collection, we see the raw value when no related value has bin parametrized.

So it's only on `Add Existing` with a related value in Interface/Display that we do not see the selected value

### What version of Directus are you using?

9.6.0  (the error was already present in the previous versions)

### What version of Node.js are you using?

v16.14.0

### What database are you using?

SQLite 3.37

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

locally

**Comment by HitomiTenshi** [comment] 2022-03-06 01:26
Duplicate of #10916

**Comment by azrikahar** [comment] 2022-03-06 11:26
@HitomiTenshi Thanks for pointing this out! (taking this opportunity to thank you again for all your detailed bug reports 👍)

**Closed by azrikahar** 2022-03-06 11:26 UTC
Labels: Bug (Potential)

**Comment by Pachat** [comment] 2022-03-07 07:09
@HitomiTenshi Sorry for my mistake. I did not intended to put any push here, 
just trying to contribute to make Directus the best source data platform. 
_I thougth #10916 was about `Create New` item which work correctly now (Thank you for that improvement)._

This issue was intended to mention that we still have a problem with `Add Existing` in 9.6.0
I'll follow your suggestion to look know at #10916 where i see that you closed it yesterday. Which is good news 👍
