### ISSUE TITLE
WYSIWYG toolbar styling

### ISSUE THREAD

**Issue by OliverSpeir** [directus/directus#21979] opened 2024-03-26 09:04 UTC
### Describe the Bug

When there are two rows of toolbar buttons and the screen is large enough that the editor is full size there is a line that overlaps the bottom row toolbar buttons 
<img width="807" alt="" src="https://github.com/directus/directus/assets/115520730/f683bf8e-ae1d-474f-bcc2-481411bd5210">

### To Reproduce

- add all the toolbar buttons by configuring the WYSIWYG input, interface -> toolbar 
- make window large enough so that WYSIWYG editor is max width

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-03-26 16:07
I am unable to reproduce this on either chrome or firefox in both light and dark mode.
![firefox](https://github.com/directus/directus/assets/9389634/a38f666e-9989-4678-928b-ff749ae80f92)
![chrome](https://github.com/directus/directus/assets/9389634/846e6665-84c7-4371-a999-d913c09070a5)

Do you have any custom CSS or theming in your instance?

Closing this issue for now, happy to re-open if we can get it reproducable 😄

**Closed by br41nslug** 2024-03-26 16:07 UTC

**Comment by OliverSpeir** [comment] 2024-03-26 22:55
No custom CSS and I am using arc browser

**Comment by OliverSpeir** [comment] 2024-03-27 00:41
@br41nslug I apologize it is only when there are two rows so my reproduction steps were wrong, to reproduce at 28 buttons only not all sorry

**Comment by br41nslug** [comment] 2024-03-27 12:14
Same result with 28 items im afraid
![image](https://github.com/directus/directus/assets/9389634/59ec8433-dcb9-4313-8c4e-3f98a0418b9d)
