### ISSUE TITLE
Error using v9.20.*

### ISSUE THREAD

**Issue by shankiflang** [directus/directus#16321] opened 2022-11-04 10:48 UTC
### Describe the Bug

When I put (on docker) Directus version to 9.20, I have a loading screen forever : 
![image](https://user-images.githubusercontent.com/32774804/199954852-1c992594-8174-41d7-a8d1-415545b51175.png)
With this error in chrome console :
![image](https://user-images.githubusercontent.com/32774804/199954913-243893c7-7195-4d69-918a-0206ae28e776.png)
as soon as I switch back to the previous version, the error disappears

### To Reproduce

Using the docker image 9.20

### What version of Directus are you using?

9.20

### What version of Node.js are you using?

16

### What database are you using?

postgres

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by azrikahar** [comment] 2022-11-04 11:19
Unfortunately I can't seem to reproduce this on my end:

https://user-images.githubusercontent.com/42867097/199959843-303c1b60-fa90-41c8-9b76-c54bc3cdb19a.mp4

so it might be difficult to know what's going on here 🤔 When you say switch back to previous version, can you share which exact version is that?

Additionally, this looks very similar to #10826 and #13226. Are you using Cloudflare CDN by any chance? If yes, can you try disabling Auto Minify as mentioned by this comment: https://github.com/directus/directus/issues/10826#issuecomment-1004372023?

Closing this for now as it seems to be same issue at first glance, but will re-open if it turns out to not be the case and when more detailed reproduction steps are subsequently provided.

**Closed by azrikahar** 2022-11-04 11:19 UTC

**Comment by shankiflang** [comment] 2022-11-04 11:42
> 

I have indeed removed the auto minify and it seems to work. Strange that it only happens on this version. The 9.18 and 9.19 work very well with it.

**Comment by azrikahar** [comment] 2022-11-04 11:51
> I have removed the auto minify and it seems to work. Strange that it only happens on this version. The 9.18 and 9.19 work very well with it.

Thanks for confirming! That's very strange indeed, particularly since #15869 for example reported this on `9.18.1` 🤔 

#10826 also dates back to `9.4.0`, so I personally have assumed the minify has always caused problem regardless of versions. Wondering if it's having trouble minifying certain newer methods such as `Array.prototype.at()` which was brought up in #15219, but then the reported version is for `9.16.0` instead... odd!
