### ISSUE TITLE
Timeseries show nothing for mysql

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [directus/directus#16578] opened 2022-11-23 07:54 UTC
### Describe the Bug

We create brand new directus project and give our mysql db credentials, then create a timeseries for a table but it does not show anything. Tried 2 totally different mysql databases. But works in our another posgresql db.

Check out the video below to have some visual understanding. (Unmute the audio too)

https://user-images.githubusercontent.com/15037839/203495480-e6821a07-b01e-44b1-ac6f-e5f10e233da6.mp4

### To Reproduce

No idea how to reproduce. But I would appreciate any directions so that I can debug this. Any files to add some console logs?

### Errors Shown

No errors, api returns incorrect data I believe

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

14.18.2

### What database are you using?

Mysql 8.0.22

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by licitdev** [comment] 2022-11-23 08:35
Duplicate of #16494

**Closed by licitdev** 2022-11-23 08:35 UTC
Labels: Duplicate

**Comment by OrkhanAlikhanov** [comment] 2022-11-23 14:07
Thanks! I see that the PR fixing this issue has been merged. So it will be available in the next release?

**Comment by licitdev** [comment] 2022-11-23 14:44
Yes! It will be available in the next release.
