### ISSUE TITLE
create directus at time of error

### ISSUE THREAD

**Issue by abdbodara** [directus/directus#7029] opened 2021-07-28 08:59 UTC
### Describe the Bug

I have created directus project at the run time of error.
link below check:
https://i.imgur.com/0EArIDh.png

### To Reproduce

https://i.imgur.com/0EArIDh.png

### What version of Directus are you using?

v9.0.0-rc.76

### What version of Node.js are you using?

v12.18.4

### What database are you using?

mysql workbanch

### What browser are you using?

chrome

### What operating system are you using?

ubuntu

### How are you deploying Directus?

.

**Comment by paescuj** [comment] 2021-07-28 10:13
Duplicate of #7024

@rijkvanzanten How about chaning the following text in the "Issue: Bug Report" template

> Before continuing, you must first have completed all Troubleshooting Steps
>
> Please confirm that an issue describing this problem doesn't exist already.

into two checkboxes?

**Closed** 2021-07-28 14:59 UTC
Labels: Duplicate
