### ISSUE TITLE
Can't install directus suite

### ISSUE THREAD

**Issue by alrick** [directus/directus#2238] opened 2018-11-09 09:13 UTC
Can't install directus suite on my webserver.
* Ubuntu 14.04
* PHP 5.6
* MySQL 5.5.60
* Apache

Steps :
* git clone https://github.com/directus/directus.git
* set up an alias + AllowOverride All in apache config
* set up permissions
* create an empty database with a new user
* go to myserver.com/directus/admin
* follow the prompts
* at the last step, I get a message "Trouble processing request. Try again after refreshing the page."

Here is the logs
```
[2018-11-09 09:54:07] api[_].ERROR: exception 'Directus\Exception\NotInstalledException' with message 'This instance of the Directus API has not been configured properly. Read More at: https://github.com/directus' in /var/www/directus/src/core/Directus/Application/ErrorHandlers/NotInstalledNotFoundHandler.php:21
Stack trace:
#0 /var/www/directus/vendor/slim/slim/Slim/App.php(530): Directus\Application\ErrorHandlers\NotInstalledNotFoundHandler->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#1 /var/www/directus/src/core/Directus/Application/Http/Middleware/CorsMiddleware.php(66): Slim\App->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#2 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#3 /var/www/directus/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Directus\Application\Http\Middleware\CorsMiddleware), Array)
#4 [internal function]: Slim\DeferredCallable->__invoke(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#5 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response), Object(Directus\Application\Application))
#6 /var/www/directus/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#7 /var/www/directus/vendor/slim/slim/Slim/App.php(406): Slim\App->callMiddlewareStack(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#8 /var/www/directus/vendor/slim/slim/Slim/App.php(314): Slim\App->process(Object(Directus\Application\Http\Request), Object(Directus\Application\Http\Response))
#9 /var/www/directus/src/core/Directus/Application/Application.php(161): Slim\App->run(false)
#10 /var/www/directus/public/index.php(5): Directus\Application\Application->run()
#11 {main} [] []
```

Any help is appreciated,
Thanks !

**Comment by alrick** [comment] 2018-11-09 12:33
I should have said that no tables are created, seems like the app can't access the database at all but I'm quiet sure the configuration is correct.
The error message is so generic, I don't really know where to investigate.

**Comment by shealavington** [comment] 2018-11-09 12:36
Oh, lol, yeah, that's useful info lol

If you want, you can try to manually install, head into the `./config/` and copy `api_sample.php` as `api.php` then manually add the config. If it still doesn't work, your info is probably incorrect.

**Comment by alrick** [comment] 2018-11-09 12:42
@shealavington 
Thanks for the suggestion but if I do this the setup is not triggered at all so no tables will be created in the database. Is there a way to manually trigger the tables creation ?

**Comment by shealavington** [comment] 2018-11-09 12:44
You can import the following schema: https://github.com/directus/directus/blob/master/src/schema.sql

**Comment by alrick** [comment] 2018-11-09 16:06
Had no success with the configure manually (enable to login).
So, I tried to reinstall in another server with the same configuration.

This time i'm stuck earlier, when I go to myserver.com/directus/admin I have a message "Couldn't reach API", nothing in logs (app or apache).
I get a 404 Not Found in the network tab of my browser for the ping file (https://myserver.com/directus/server/ping).

Any idea how to debug ?

**Comment by shealavington** [comment] 2018-11-11 18:15
> (https://myserver.com/directus/server/ping).

Is that the correct ping url? typically I believe it's `./install_location/public/server/ping`

**Comment by verbman** [comment] 2018-11-12 06:20
I am having issues also and I think it relates to this entry in the .gitignore file:
`/vendor`
Specifically the error I'm getting is on fresh install:
> Warning: include(D:\home\site\directus\vendor\composer/../monolog/monolog/src/Monolog/ResettableInterface.php): failed to open stream: No such file or directory in D:\home\site\directus\vendor\composer\ClassLoader.php on line 444

I checked the monolog changelog and it shows the file was added in their release 7 days ago.
I then tried to add the monolog latest release into my own directus fork and the .gitignore file blocked me. I'd assume this is what has happened during this release of directus.

**Comment by shealavington** [comment] 2018-11-12 07:45
@verbman as far as I'm aware, vendor files don't need to be committed, if it's causing you an issue, have you tried `composer install`? These also sound like two very different issues to me.

**Comment by alrick** [comment] 2018-11-12 08:11
> > (https://myserver.com/directus/server/ping).
> 
> Is that the correct ping url? typically I believe it's `./install_location/public/server/ping`

To clarify : https://myserver.com/directus is where my installation of directus is set up. I go to https://myserver.com/directus/admin to start the installation.

**Comment by shealavington** [comment] 2018-11-12 08:19
That confuses me as I would expect to see the directory `/public/` there too. It would make sense if you had a subdomain `directus.myserver.com/admin` pointing to the path, but typically it's `myserver.com/directusinstall/public/admin` youre not only keeping the public folder and putting that in your install are you, you're keeping the whole folder right? 

(I'm not being patronising I'm just trying to see if you might have missed anything)

**Comment by verbman** [comment] 2018-11-12 09:43
Thanks for your reply @shealavington I appreciate this could be a separate issue, but I'm still trying to get to the bottom of it. Your suggestion of `composer install` doesn't work with the `build` branch on API or the directus/directus *prebuild* version. They don't have a `composer.json` files. That step is supposed to already be done and by extension the /vendor folder should be up to date - which it appears not to be.

**Comment by alrick** [comment] 2018-11-12 10:39
So, I tried to install it with the tar instead of the recommended git method :
https://docs.directus.io/install.html#other-install-options

And got the same problem as @verbman 
Can someone confirm that he was able to install the directus suite with the last build and maybe give the steps followed ?

I updated the title of the ticket as it seems to be a more general issue.

**Comment by verbman** [comment] 2018-11-12 10:55
I have only succeeded by sidestepping the pre-built routes and going with:
git clone https://github.com/directus/api.git
cd api
curl -sS https://getcomposer.org/installer | php
php composer.phar install
Add web.config to api/public (I'm running on Azure)
Add api.php to api/config
(My database was already set up - the docs point you to the file you need to run for that)

**Comment by benhaynes** [comment] 2018-11-12 16:00
Thanks for the input everyone – we'll get this sorted in the next few days.

🔔 @rijkvanzanten @WellingGuzman

**Comment by sebj54** [comment] 2018-11-12 16:10
Same issue here! If someone has a workaround for the 7.0.6 version, I'm intersted :)
I thought to use composer to install the missing dependency, but I can't found a composer.json file in the bundled repo :/

**Comment by rijkvanzanten** [comment] 2018-11-14 14:29
This is a duplicate of https://github.com/directus/directus/issues/2238#issuecomment-437937471

**Closed by rijkvanzanten** 2018-11-14 14:29 UTC
Labels: duplicate
