### ISSUE TITLE
Cannot update identity  on MSSQL

### ISSUE THREAD

**Issue by feitzi** [directus/directus#4638] opened 2021-03-23 16:14 UTC
On a new directus installation with MSSQL the following error occurs if I want to edit a field:
```json
{
  "errors": [
    {
      "message": "update [directus_fields] set [id] = @p0, [collection] = @p1, [field] = @p2, [special] = @p3, [interface] = @p4, [options] = @p5, [display] = @p6, [display_options] = @p7, [readonly] = @p8, [hidden] = @p9, [sort] = @p10, [width] = @p11, [group] = @p12, [translations] = @p13, [note] = @p14 where [id] in (@p15);select @@rowcount - Cannot update identity column 'id'.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

Its a complete fresh installation of directus.

## Version:
* v9.0.0-rc.51
* MSSQL

**Comment by rijkvanzanten** [comment] 2021-03-23 17:24
Duplicate of https://github.com/directus/directus/issues/4594

**Closed by rijkvanzanten** 2021-03-23 17:24 UTC
