### ISSUE TITLE
DB_SEARCH_PATH doesn't apply on bootstraping phase in Docker container

### ISSUE THREAD

**Issue by doron-cohen** [directus/directus#4411] opened 2021-03-06 17:46 UTC
Hi,

I am running Directus using docker-compose. I am using Docker image `directus/directus:v9.0.0-rc.45`.
When I start the container I get this error:

```
admin       | error: create table "directus_collections" ("collection" varchar(64), "icon" varchar(30), "note" text, "display_template" varchar(255), "hidden" boolean not null default '0', "singleton" boolean not null default '0', "translations" json, "archive_field" varchar(64), "archive_app_filter" boolean not null default '1', "archive_value" varchar(255), "unarchive_value" varchar(255), "sort_field" varchar(64)) - no schema has been selected to create in
admin       |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:278:15)
admin       |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
admin       |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
admin       |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:10:42)
admin       |     at Socket.emit (events.js:315:20)
admin       |     at addChunk (internal/streams/readable.js:309:12)
admin       |     at readableAddChunk (internal/streams/readable.js:284:9)
admin       |     at Socket.Readable.push (internal/streams/readable.js:223:10)
admin       |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
admin       |   length: 120,
admin       |   severity: 'ERROR',
admin       |   code: '3F000',
admin       |   detail: undefined,
admin       |   hint: undefined,
admin       |   position: '14',
admin       |   internalPosition: undefined,
admin       |   internalQuery: undefined,
admin       |   where: undefined,
admin       |   schema: undefined,
admin       |   table: undefined,
admin       |   column: undefined,
admin       |   dataType: undefined,
admin       |   constraint: undefined,
admin       |   file: 'namespace.c',
admin       |   line: '491',
admin       |   routine: 'RangeVarGetCreationNamespace'
admin       | }
```

Looks like the bootstrapping phase ignores the passed `DB_SEARCH_PATH` env I am passing.

**Comment by rijkvanzanten** [comment] 2021-03-12 19:28
How are you passing the search path? The bootstrap command uses the same database instance as running Directus, which does seem to rely on the search path 🤔

**Comment by doron-cohen** [comment] 2021-03-14 20:36
I will try to reproduce this and will post the steps in the next few days.

**Comment by doron-cohen** [comment] 2021-03-15 20:45
@rijkvanzanten I think the issue here is when I pass multiple schema names to the Docker environment like `DB_SEARCH_PATH: 'array:tenant1,shared'` the bootstrap process takes both of them. So, the DB doesn't know where to create the tables hence the error:

**Comment by doron-cohen** [comment] 2021-03-15 20:47
So, a reproduction would just be to create a DB with 2 schemas and pass the names to the bootstrap process. I believe that it should just take the first one for table creation but it might be more complicated to solve.

**Comment by doron-cohen** [comment] 2021-03-15 21:02
After some digging I realized I didn't have `USAGE` permissions on the schema. Solving the issue revealed another one:
```
tenant2     | 20:59:45 ✨ Initializing bootstrap...
tenant2     | 20:59:45 ✨ Installing Directus system tables...
tenant2     | 20:59:45 ✨ Setting up first admin role...
tenant2     | TypeError: Cannot read property 'primary' of undefined
tenant2     |     at RolesService.<anonymous> (/directus/node_modules/directus/dist/services/items.js:60:73)
tenant2     |     at Generator.next (<anonymous>)
tenant2     |     at /directus/node_modules/directus/dist/services/items.js:27:71
tenant2     |     at new Promise (<anonymous>)
tenant2     |     at __awaiter (/directus/node_modules/directus/dist/services/items.js:23:12)
tenant2     |     at RolesService.create (/directus/node_modules/directus/dist/services/items.js:59:16)
tenant2     |     at Command.<anonymous> (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:38:45)
tenant2     |     at Generator.next (<anonymous>)
tenant2     |     at fulfilled (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:5:58)
tenant2     |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I solve this now by running the container with `DB_SEARCH_PATH=tenant2` and after bootstrap is done I rerun it with `DB_SEARCH_PATH=array:tenant2,shared`.

**Comment by doron-cohen** [comment] 2021-03-15 21:04
But when I open the tenant URL in browser I get a blank page and this error in the logs:
```
tenant1     | 20:58:54 🚨 Cannot read property 'columns' of undefined 
tenant1     | TypeError: Cannot read property 'columns' of undefined
tenant1     |     at /directus/node_modules/directus/dist/utils/get-ast-from-query.js:224:71
tenant1     |     at Generator.next (<anonymous>)
tenant1     |     at /directus/node_modules/directus/dist/utils/get-ast-from-query.js:11:71
tenant1     |     at new Promise (<anonymous>)
tenant1     |     at __awaiter (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:7:12)
tenant1     |     at getFieldsInCollection (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:223:20)
tenant1     |     at /directus/node_modules/directus/dist/utils/get-ast-from-query.js:154:50
tenant1     |     at Generator.next (<anonymous>)
tenant1     |     at /directus/node_modules/directus/dist/utils/get-ast-from-query.js:11:71
tenant1     |     at new Promise (<anonymous>)
tenant1     | 20:58:54 ✨ request errored GET 500 /server/info?limit=-1 19ms
```

**Comment by Aman-D** [comment] 2021-03-17 17:59
I am also stuck in the same situation. It works fine for one schema at a time in `DB_SEARCH_PATH`.

**Comment by doron-cohen** [comment] 2021-03-17 20:07
@rijkvanzanten if I can suggest something that _might_ solve this issue plus add some more flexibility to the database integration. I wish I could instruct Directus to serach for tables in a set of schemas and tell it in what schema the metadata tables are. I think it's a good approach that will allow some more flexibility.

**Comment by rijkvanzanten** [comment] 2021-04-08 21:30
@doron-cohen Yeah! That's the long-term plan (potential multi-data sources, which in turn means the directus_ tables will live in another table). 

For now, Directus only supports installing into a single database in a single schema

**Comment by rijkvanzanten** [comment] 2021-05-22 01:40
Closing this for now, as the OP is not a bug, but rather a (future) feature Directus doesn't currently support. We're tracking the discussion around multi-schema support here: https://github.com/directus/directus/discussions/5395

**Closed by rijkvanzanten** 2021-05-22 01:40 UTC
Labels: Invalid
