### ISSUE TITLE
Extension build fails after the latest update

### ISSUE THREAD

**Issue by TyrionFront** [directus/directus#18203] opened 2023-04-15 16:00 UTC
### Describe the Bug

Previously successfull build now fails after the latest update:

<img width="924" alt="Screenshot 2023-04-15 at 18 48 49" src="https://user-images.githubusercontent.com/18406903/232235614-d699cd5c-fdf2-4678-81fc-07b2c88076b4.png">

### To Reproduce

Just update directus related deps to the lates version. On my end those are:

`"@directus/extensions-sdk": "^9.25.1",
  "@directus/sdk": "^10.3.3",
  "directus": "^9.25.1",`
  
  

### Directus Version

9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-04-15 16:25
Thanks for opening this issue! However this is a duplicate of an existing issue #18178, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment.

**Closed by paescuj** 2023-04-15 16:25 UTC

**Comment by TyrionFront** [comment] 2023-04-15 16:30
@paescuj , thanks for quick response and sorry for replication of the existing problem. So when the fix will be published?

**Comment by paescuj** [comment] 2023-04-15 20:14
You're welcome & no worries! We can not give an exact schedule on this, but I expect it to happen over the next days 👍
