### ISSUE TITLE
Got locked out of app and Static Token stopped working. 

### ISSUE THREAD

**Issue by development-vargamarcel** [directus/directus#12583] opened 2022-04-05 13:36 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Got locked out of app and Static Token stopped working. 

### To Reproduce

1. Add many-to-one relation to directus_roles (user_created) table referencing directus_users (roles_created).
2. Refresh page / try to login to the app. 

### Errors Shown

No app access. 

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

Directus comunity cloud

### What database are you using?

Directus comunity cloud

### What browser are you using?

Opera

### What operating system are you using?

Windows/android (Directus comunity cloud) 

### How are you deploying Directus?

Directus comunity cloud

**Comment by rijkvanzanten** [comment] 2022-04-06 20:09
I believe this is a duplicate of https://github.com/directus/directus/issues/12393

**Closed by rijkvanzanten** 2022-04-06 20:09 UTC
Labels: Bug (Potential)
