### ISSUE TITLE
Typescript types for define function of extensions are broken in the release of extension sdk v12.1.0

### ISSUE THREAD

**Issue by ChappIO** [directus/directus#23916] opened 2024-10-24 12:58 UTC
### Describe the Bug

The types for the define functions are broken in the latest release (v12.1.0). A defined hooks extension using proper syntax is no longer accepted as a compatible extension. This also applies to the trivial example initially created using the extension sdk.

Example:

```
import { defineHook } from '@directus/extensions-sdk';

export default defineHook(({ filter, action }) => {
	filter('items.create', () => {
		console.log('Creating Item!');
	});

	action('items.create', () => {
		console.log('Item created!');
	});
});
```

Error: TS2345: Argument of type XXX is not assignable to parameter of type `{[x: string]: unknown}`. This is caused by the recent introduction of the `CustomConfig` type in the extension sdk.

<img width="562" alt="image" src="https://github.com/user-attachments/assets/7116a167-05c8-4352-bd08-c0be33e21a38">

### To Reproduce

1. Create a new hooks extension: `npx create-directus-extension@latest` and pick extension type hook and typescript yes
2. Make sure that `"@directus/extensions-sdk": "12.1.0",` in `package.json`
3. Run `npm i`
4. Open `src/index.ts` in a typescript enabled editor

### Directus Version

v12.1.0 (sdk)

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ChappIO** [comment] 2024-10-24 12:59
My current workaround is to NOT upgrade the sdk version. I have rolled back to `v12.0.2`.

**Comment by br41nslug** [comment] 2024-10-24 13:04
Duplicate of #23832 the fix has been merged and will be in the next release

**Closed by br41nslug** 2024-10-24 13:04 UTC
