### ISSUE TITLE
Increase limit of relationships shown in UI

### ISSUE THREAD

**Issue by rithu1998** [directus/directus#7767] opened 2021-09-01 23:32 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Within my data displayed using Directus, I have entries with 100+ relationships mapped to it but currently on the UI I can only see the first 100 relationships. Is there any way to increase this limit or have a feature to allow scrolling through the relationships since we currently cannot access the rest of the entries in the UI.

### To Reproduce

In order to reproduce, create an entry with more than 100 relationships to it (ex. 100+ M2M relationships) and verify on the UI whether or not you can see all of these relationships.
![Screen Shot 2021-09-01 at 4 31 35 PM](https://user-images.githubusercontent.com/27563697/131758616-1fe22fbc-130a-437b-99be-657bfa0e77f7.png)
![Screen Shot 2021-09-01 at 4 31 27 PM](https://user-images.githubusercontent.com/27563697/131758621-def887a4-56b9-4009-b09c-2cd2027b39d2.png)

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.15.4

### What database are you using?

MySql

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-09-01 23:35
Duplicate of https://github.com/directus/directus/issues/3889

**Closed by rijkvanzanten** 2021-09-01 23:35 UTC
Labels: Bug (Potential)
