### ISSUE TITLE
 Field: WYSIWYG, Locked

### ISSUE THREAD

**Issue by MoreauJonas** [directus/directus#19384] opened 2023-08-09 19:37 UTC
### Describe the Bug

Hello,
While using Directus, I have just noticed that when creating a WYSIWYG field (with "disable editing value" unchecked), 

I can fill it in my collection, but afterward, it becomes locked.

### To Reproduce

I create a WYSIWYG field, I ensure that the "disable editing value" option is unchecked, with only the "add links" tool available.
![image](https://github.com/directus/directus/assets/102809203/c5870563-08b1-47d2-ba98-dafccd2d65ae)

I go into my collection, fill out the field, and save.
When I go back for editing,
![image](https://github.com/directus/directus/assets/102809203/73b27c03-6866-4b5c-88d9-cb878156e69b)

it is locked.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-08-09 19:47
I believe this is a duplicate of https://github.com/directus/directus/issues/19314

**Closed by rijkvanzanten** 2023-08-09 19:47 UTC
