### ISSUE TITLE
Missing field/collection translations causes app to crash

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#11458] opened 2022-02-06 16:22 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We upgraded Directus from version 9.4.2 directly to 9.5.1.
After the login, every user (including Admins) see this screen:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/9347206/152690271-f0eb35d9-4376-449f-a91d-a9ee693a640a.png">

```
Cannot read properties of null (reading 'replace')
```

### To Reproduce

Upgrade Directus from 9.4.2 to 9.5.1

### Errors Shown

No errors in console

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-02-07 08:25
Unfortunately I can't seem to reproduce this on my end. Just curious, are there any cache enabled or possibly using redis for example? 

Would you also be able to test this with a fresh 9.4.2 container + db and upgrade to 9.5.1? Just so we can isolate whether it's related to existing data _somehow_ having issue after migration, or it's something inherent with Directus admin app regardless of existing data.

**Comment by LevinGermann** [comment] 2022-02-07 13:29
Hi @azrikahar, thanks for your response.
I was able to install a 9.4.2 version on a fresh db (but keeping our Directus configuration) and successfully upgrade to 9.5.1.
This means there shouldn't be anything wrong with our config, but rather 9.5.1 Directus is not okay with something in our data that Directus 9.4.2 was...
If I diff both database contents from 9.4.2 to 9.5.1, the only difference is the admin's last login date, so the update hasn't "corrupted" data.

We're not using Redis and I don't think this is neither a client nor server cache problem. (Tried private windows both times)

I noticed that if I copy the error from the prompt, there seems to be more info if that's helpful (?):

{
  "stack": "TypeError: Cannot read properties of null (reading 'replace')\n    at Proxy.parseField (https://content.explorial.com/admin/assets/index.7af4eb85.entry.js:32:417152)\n    at https://content.explorial.com/admin/assets/vendor.62e5a05d.js:9:2538\n    at Array.map (<anonymous>)\n    at Proxy.hydrate (https://content.explorial.com/admin/assets/index.7af4eb85.entry.js:32:416868)\n    at async Promise.all (index 1)\n    at async il (https://content.explorial.com/admin/assets/index.7af4eb85.entry.js:32:408358)\n    at async zo (https://content.explorial.com/admin/assets/index.7af4eb85.entry.js:32:409835)\n    at async Proxy.y (https://content.explorial.com/admin/assets/index.7af4eb85.entry.js:32:123582)",
  "message": "Cannot read properties of null (reading 'replace')"
}

**Comment by LevinGermann** [comment] 2022-02-07 13:34
I just tried to do incremental steps from 9.4.2 -> 9.4.3 -> 9.5.0 -> 9.5.1.
It only began to fail on 9.5.1

**Comment by azrikahar** [comment] 2022-02-07 14:02
Thank you very much for the detailed debugging, especially the incremental steps! Judging from the hints based on the error you shared such as `Proxy.parseField` and `Array.map ()\n at Proxy.hydrate`, I'm beginning to believe it's related to fields translations. #11287 was released in `v9.5.1`, and it does replace translations to prevent similar login-preventing-error due to users that uses certain special characters. However the logic there should imply translations wasn't null in the first place, so I'm curious what is happening here.

Would you mind sharing the rows in `directus_fields` where the `translations` column is not null? Provided if there's no privacy or sensitive info of course 👍 

Alternatively, assuming you don't mind testing (with backup beforehand) setting all those `translations` in `directus_fields` to NULL, that can also help test this current hypothesis as well.

---

Slightly unrelated: Just realized everything I typed might be totally moot if you don't have any field translations in the first place... so I'm hoping that's not the case 😅

**Comment by LevinGermann** [comment] 2022-02-07 14:22
That was it @azrikahar !
I noticed that at one place we have 
`[{"language":"en-US","translation":null}]`
(for whatever reason a 'null' ended in there, I never updated such configs directly in the DB... usually we have an empty string there as a work-around to not display some random "list" string on top of a M2O list)
After replacing that with
`[{"language":"en-US","translation":""}]`
everything was working again!

Thanks for your help and hints. :)

**Comment by azrikahar** [comment] 2022-02-07 14:49
Glad we can pinpoint it! I got curious and tested a scenario where a user _did_ choose a language to translate, but they just save it without entering any translation value. In this case, translation will 100% be null:

![image](https://user-images.githubusercontent.com/42867097/152808254-45fa0288-f385-4b89-9577-cb59b20bff6a.png)

So I've decided to just go the safer route and made a PR to handle this edge case.

Once again _thank you_ for the helpful debugging & troubleshooting on your end which helped immensely to find out the root cause so soon 😊

**Closed** 2022-02-16 14:31 UTC
Labels: App, Bug
