### ISSUE TITLE
Drag-drop fields in group result in error

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#8514] opened 2021-10-03 11:11 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In Data model, after creating a Field group, when trying to drag-n-drop another field in the group itself, this is what comes out:

```{
  "errors": [
    {
      "message": "update \"directus_fields\" set \"collection\" = $1, \"field\" = $2, \"sort\" = $3, \"group\" = $4 where \"id\" in ($5) - invalid input syntax for type integer: \"test_group\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

I tried creating a new collection (`test_table`) a new field (`test_field`) and a new group (`test_group`)

### To Reproduce

1. create new collection
2. create new field
3. create new group
4. drag a field into the group

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

the one delivered with docker

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by charlescatta** [comment] 2021-10-03 18:11
Same thing here!

deployment: docker
database: postgis/postgis:14-3.1
directus: directus/directus:9.0.0-rc.95
os: Windows 10
browser: Chrome 94.0

```json
{
  "errors": [
    {
      "message": "update \"directus_fields\" set \"collection\" = $1, \"field\" = $2, \"sort\" = $3, \"group\" = $4 where \"id\" in ($5) - invalid input syntax for type integer: \"field_group_test123\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

full log:
```sh
error update "directus_fields" set "collection" = $1, "field" = $2, "sort" = $3, "group" = $4 where "id" in ($5) - invalid input syntax for type integer: "field_group_test123"
cms_1  | error: update "directus_fields" set "collection" = $1, "field" = $2, "sort" = $3, "group" = $4 where "id" in ($5) - invalid input syntax for type integer: "field_group_test123"
cms_1  |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
cms_1  |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
cms_1  |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
cms_1  |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
cms_1  |     at Socket.emit (node:events:390:28)
cms_1  |     at addChunk (node:internal/streams/readable:315:12)
cms_1  |     at readableAddChunk (node:internal/streams/readable:289:9)
cms_1  |     at Socket.Readable.push (node:internal/streams/readable:228:10)
cms_1  |     at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
cms_1  | 18:07:58 ✨ request errored PATCH 500 /fields/test 27ms
```

**Comment by darioguarascio** [comment] 2021-10-03 18:32
I also noticed the appearence of an empty input field where it should be some sort of placeholder 
![image](https://user-images.githubusercontent.com/3661363/135766897-6e59b75d-5fc6-4944-82ff-9fda26ad592c.png)
![image](https://user-images.githubusercontent.com/3661363/135766904-78acd662-dc02-4b52-981f-9d763ba0df06.png)

**Comment by azrikahar** [comment] 2021-10-04 07:27
Technically this should be fixed by #8349 (released in rc.95), specifically

https://github.com/directus/directus/blob/fb815913573cfff3e724f34bf5102fb85f84f1ac/api/src/database/migrations/20210927A-replace-fields-group.ts#L21-L27

where we changed `group` column from integer to string. This is why the error `invalid input syntax for type integer` as your database is still using integer datatype for `group`.

however I can confirm the Docker container somehow does show it ran this migration, but it's not really applying this migration 🤔

|Before this migration | After this migration |
|---|---|
| ![chrome_6OHs5SE3zu](https://user-images.githubusercontent.com/42867097/135810194-e0931d3f-6326-42ff-9e81-efcb65670831.png) |  ![chrome_RwPDdFDXgu](https://user-images.githubusercontent.com/42867097/135810238-d762a666-a71b-4609-992c-a0bbd20e709b.png) |

@darioguarascio @charlescatta would you guys mind checking your `directus_settings` table and let us know what is the datatype of your `group` column? Just so we can be sure it's the migration issue.

**Comment by domdus** [comment] 2021-10-04 10:30
Coming in with the same issue. I have 4 projects, the Drag-drop in group feature only works in one of them (most recent install).

- All projects are on rc.95 and ran the migrations
- All on Postgres 13


@azrikahar: Checked the `directus_fields` table

**The working one:**
`SELECT "collection", "field", "group", pg_typeof("group") FROM directus_fields WHERE field = 'target_group';`

    collection     |    field     | group |     pg_typeof
-------------------+--------------+-------+-------------------
 startpage_teasers | target_group |       | character varying
(1 row)

**Not working one:**

`SELECT "collection", "field", "group", pg_typeof("group") FROM directus_fields WHERE field = 'target_group';`

    collection    |    field     | group | pg_typeof
------------------+--------------+-------+-----------
 app_home_teasers | target_group |       | integer
(1 row)

**Comment by dstoyanoff** [comment] 2021-10-04 12:05
Should be the same as #8369

**Comment by darioguarascio** [comment] 2021-10-04 15:34
@dstoyanoff thank you. There is still one issue tho.

```
postgres=# ALTER TABLE directus_fields DROP CONSTRAINT directus_fields_group_foreign;
ALTER TABLE
postgres=# ALTER TABLE directus_fields ALTER COLUMN "group" TYPE VARCHAR(64);
ALTER TABLE
postgres=# ALTER TABLE directus_fields ADD FOREIGN KEY ("group") REFERENCES directus_fields(field) ;
ERROR:  there is no unique constraint matching given keys for referenced table "directus_fields"
```
And I don't think it is possible to make `field` unique

**Comment by faridsaud** [comment] 2021-10-04 15:38
I followed @azrikahar instructions  https://github.com/directus/directus/issues/8514#issuecomment-933217449 and it worked. 

For anyone having this issue right now, you can create a custom migration (a file inside the migrations folder, with a date after the v95 release) that looks like this:
`
module.exports = {
    async up(knex) {
        
        await knex.schema.alterTable('directus_fields', (table) => { 
            table.dropColumn('group'); 
        }); 
         
        await knex.schema.alterTable('directus_fields', (table) => { 
            table.string('group', 64); 
        }); 
    },

    async down(knex) {
        await knex.schema.alterTable('directus_fields', (table) => {
            table.dropColumn('group');
        });
    
        await knex.schema.alterTable('directus_fields', (table) => {
            table.integer('group').references('id').inTable('directus_fields');
        });
    },
};
`
PD: This should be a temporary solution until the actual fix is addressed in the main branch/releases.

**Closed** 2021-10-04 15:46 UTC
Labels: API, Bug, Docker

**Comment by darioguarascio** [comment] 2021-10-04 16:44
Little follow up:
even without the foreing key, grouping now works. drag-n-drop works too in data model. 
The only leftover is a phantom field still showing up 
![image](https://user-images.githubusercontent.com/3661363/135890912-4ce81eca-ac5c-4ac3-a83a-68505ad200ca.png)

**Comment by azrikahar** [comment] 2021-10-05 03:01
@darioguarascio yea I meant `directus_fields`! Sorry for the misleading wrong table name 😅

> The only leftover is a phantom field still showing up

This might be a faulty row that still ended up in your `directus_fields` which is linked to this collection. You can try removing it (but definitely do a backup beforehand to be safe)

Alternatively, you can try setting `hidden` to true until you are sure you are targeting the exact phantom row before deleting it 👍
