### ISSUE TITLE
O2M relationship only showing first 100 M items on O items page in Admin

### ISSUE THREAD

**Issue by StephenGunn** [directus/directus#12572] opened 2022-04-04 21:35 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a collection that has a O2M relationship and that collection almost always has 100+ related items.

Any time I load the O item in the O2M relationship, the M items are cut off at 100. 

If I need to edit or add any items to the O item, I also have to re-add every item that is over 100. Since the M item pool is in the 1000s, this gets confusing really fast.

If I click "Add Existing" on the relationship interface, Items that I know are part of the relationship are not selected as they should be. Example:

![image](https://user-images.githubusercontent.com/7240548/161635529-c606095d-c475-4017-bdce-b1bedeef1046.png)

All of those unchecked items are in the realtionship. If you add a single item (item #101) and save, all the unchecked items will be removed from the relationship where they previously were added.

I think there is a hard limit set on the array length and that is messing me up. I have looked every where to see if there is a setting to get the full array length with no luck.

I hand counted the items in the interface and they are indeed capped at 100.

### To Reproduce

1. Create a O2M relationship
2. Go to the O item page
3. Add 101+ M items to the O item relationship interface
4. Save and re-enter the O item relationship page
5.  Notice how there are items missing from the relationship interface. 

### Errors Shown

No errors.

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

v16.13.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome / Firefox

### What operating system are you using?

Linux Ubuntu 18.04 (LTS) x64

### How are you deploying Directus?

Self install on Digital Ocean droplet with a managed DB instance

**Comment by t7tran** [comment] 2022-04-05 00:29
Affirmative. We are also affected by this bug. The danger is that if the parent record is saved, all unloaded related items are deleted. In our case, the save operation results in Network Error (see screenshot).

![image](https://user-images.githubusercontent.com/76130324/161653846-56188ae3-88a3-4171-b604-c4b028dafb96.png)

Steps to reproduce network error:

1. Create an O2M field named `addresses` in collection `Contact` referencing collection `Address` (`Address` is owned by `Contact`)
2. Create an M2O field named `currentAddress` in collection `Profile` referencing collection `Address`
3. Go to a `Contact` item page
4. Add 101+ `Address` items to the `addresses` relationship
5. Save and re-enter the `Contact` item page
6. Notice the missing 101th `Address` item in the list
7. Go to a `Profile` item page
8. Link `currentAddress` field to the missing 101th `Address` item noted in step 6
9. Save
10. Reopen the `Contact` item page, double check item 101th is still missing
11. Add a new 102th `Address` item into `addresses`
12. Save and notice `Network Error`
13. Check the log, it should mention something like: `delete from Address where id in ("id-of-101-address")`

**Comment by azrikahar** [comment] 2022-04-05 01:54
Thanks for opening this issue! However this is a duplicate of existing issues #12564 #10616 #3889, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #3889 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-05 01:54 UTC
Labels: Bug (Potential)
