### ISSUE TITLE
Admin redirect does not function well

### ISSUE THREAD

**Issue by BartTactick** [directus/directus#10670] opened 2021-12-24 10:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I just installed V9.3 and i got the following glitch/bugg:
i have a cloudflare worker that redirects requests to the right url:
https://connectickredirect.beheer5395.workers.dev/org/3/ <- goes to the Directus instance

https://connectickredirect.beheer5395.workers.dev/org/admin/org/3 <- is the /admin redirect that gets put in place by Directus
Expected url:
https://connectickredirect.beheer5395.workers.dev/org/3/admin

Public url that i use: https://connectickredirect.beheer5395.workers.dev/org/3/

### To Reproduce

Make Directus run behind a subpath. (reverse proxy or something similar)
Then go to the url and it will automaticly redirect you to the wrong path.
Please note that i have multiple slashes in the url.

### What version of Directus are you using?

9.3

### What version of Node.js are you using?

Docker

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by BartTactick** [comment] 2021-12-24 11:02
Same happends when you are already loggedin:
https://connectickredirect.beheer5395.workers.dev/org/3/admin/org/3/
instead of:
https://connectickredirect.beheer5395.workers.dev/org/3/admin

**Comment by rijkvanzanten** [comment] 2021-12-25 01:42
What is your configuration for `PUBLIC_URL` and `ROOT_REDIRECT`?

**Comment by rijkvanzanten** [comment] 2021-12-30 23:47
I can't reproduce this based on the shared information. Could you share your reverse proxy configuration and the values for `PUBLIC_URL` and `ROOT_REDIRECT`?

**Comment by rijkvanzanten** [comment] 2021-12-30 23:47
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-12-30 23:47 UTC
Labels: Can't Reproduce
