### ISSUE TITLE
M2A list not updating when in translations 

### ISSUE THREAD

**Issue by marcusand** [directus/directus#13665] opened 2022-06-01 14:45 UTC
### Describe the Bug

I am experiencing the same bug as described in this bug fix here https://github.com/directus/directus/pull/10617 but only when the M2A field is part of a "translations" field.  Meaning, changes to the items are not reflected in the list view until the item is saved and page is reloaded.

See video for demo:

https://user-images.githubusercontent.com/28539818/171428922-b7e50b72-a109-4123-9ae4-f173eda87e9e.mov

### To Reproduce

1. Create a translations field in a random data-model
2. Create a M2A field in the translations data-model with arbitrary related collections
3. Try adding/updating/deleting items in the M2A field

### Errors Shown

no errors in browser console or terminal

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

I guess its 16.15.0 (official latest docker image)

### What database are you using?

postgres 13

### What browser are you using?

vivaldi (chromium)

### How are you deploying Directus?

official docker image

**Comment by marcusand** [comment] 2022-06-01 14:50
additional note: it's not happening on a fresh item...only when the m2a field has been touched and saved at least once.

**Comment by azrikahar** [comment] 2022-06-01 15:00
Seems like this has the same root cause as #13551. Tested the linked PR and it does work:

## Before


https://user-images.githubusercontent.com/42867097/171435712-8a0d0e05-419d-4d17-a88f-e66c658bdde8.mp4


## After

https://user-images.githubusercontent.com/42867097/171435689-791caf73-77c5-49a5-8464-50093aa81da6.mp4

Will close this in the meantime to track in #13551 and wrap up said PR 👍 Thanks again for bug report as it helps to act as an additional confidence check on the solution used!

**Closed by azrikahar** 2022-06-01 15:00 UTC
Labels: Bug (Potential)

**Comment by marcusand** [comment] 2022-06-01 15:06
nice, thank you!
