### ISSUE TITLE
Inviting users gives Error: write EPIPE

### ISSUE THREAD

**Issue by damusix** [directus/directus#21373] opened 2024-02-08 16:00 UTC
### Describe the Bug

```
directus  | [15:56:25.194] ERROR: write EPIPE
directus  |     err: {
directus  |       "type": "Error",
directus  |       "message": "write EPIPE",
directus  |       "stack":
directus  |           Error: write EPIPE
directus  |               at afterWriteDispatched (node:internal/stream_base_commons:160:15)
directus  |               at writeGeneric (node:internal/stream_base_commons:151:3)
directus  |               at Socket._writeGeneric (node:net:962:11)
directus  |               at Socket._write (node:net:974:8)
directus  |               at writeOrBuffer (node:internal/streams/writable:392:12)
directus  |               at _write (node:internal/streams/writable:333:10)
directus  |               at Writable.write (node:internal/streams/writable:337:10)
directus  |               at LastNewline.ondata (node:internal/streams/readable:809:22)
directus  |               at LastNewline.emit (node:events:517:28)
directus  |               at addChunk (node:internal/streams/readable:368:12)
directus  |       "errno": -32,
directus  |       "code": "EPIPE",
directus  |       "syscall": "write"
directus  |     }
directus  | [15:56:25] POST /users/invite 500 85ms
```

### To Reproduce

- Launch new directus instance
- Go to Users -> Invite a user
- Add email and press send
- ```
    {
        "message": "write EPIPE",
        "extensions": {
            "code": "INTERNAL_SERVER_ERROR"
        }
    }
  ```

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-02-08 16:03
Looks like you're email configuration is incorrect. I suspect `sendmail` (the default) is missing or misconfigured, either way i recommend using a proper SMTP server for sending mails.

**Comment by damusix** [comment] 2024-02-08 16:16
@br41nslug Yeah just saw an old bug report on the same thing. I switched to SES because it's in a docker container and don't feel like going through the trouble of mounting the sendmail binary.

It's probably more appropriate to categorize this issue as a documentation ticket, if you'd want to address it at some point.

One solution (for docker) would be to mount volume: `- /usr/sbin/sendmail:/usr/sbin/sendmail`, and now the container will be able to access it. If gives linux permission issues, make `/usr/sbin/sendmail` 777 and docker should be able to execute it.

Haven't tried it, don't hold me to it!
Linked bug: https://github.com/directus/directus/issues/5135

**Comment by rijkvanzanten** [comment] 2024-02-08 22:08
> One solution (for docker) would be to mount volume

Assuming sendmail exists on the host machine! My recommendation would always be some SMTP service or mail provider. Sendmail might not exist, it might not be able to reach the internet, and if it can, there's a high chance the emails are flagged as spam. Getting an email to somebody's inbox is surprisingly difficult in 2024

**Comment by rijkvanzanten** [comment] 2024-07-12 19:01
I haven't been able to reproduce this based on the steps provided, so I'll close this for now. Happy to reopen if more information becomes available.

**Closed by rijkvanzanten** 2024-07-12 19:01 UTC
Labels: :file_folder: Documentation, :elevator: DX
