### ISSUE TITLE
A non-Admin user can attempt to change the role of another user

### ISSUE THREAD

**Issue by aschoijett** [directus/directus#3469] opened 2020-12-18 18:07 UTC
Hi,
I am totally new to directus so this may be more about my ignorance or a misconfiguration. 

Background: 
I have User0 defined as my Admin user (role Administrator). 

I then created a new role called Editor and a User1 with that role. 
To enable User1 to login, I learned that I had to reset the permissions to the system collections to their default values.  (BTW, please add this step to the future documents you guys are working on. )

When I login as User1, I am able to start the change of the role of other users, like the role of User0, even though the default permissions of the role Editor don't seem to allow users with that role to do that.   Do I have something wrongly configured?   Many thanks for your help!

Btw, the request to change the role actually fails, but given the permission list that I see as the default for the Editor, my expectation is that User1 won't have the option to **start** changing someone else's role - or hers for that matter.

Hope this helps,

Alex

**Comment by mcqueena9845** [comment] 2020-12-19 19:32
Somewhat related to this.  [https://github.com/directus/directus/issues/3454](https://github.com/directus/directus/issues/3454)

**Comment by rijkvanzanten** [comment] 2020-12-21 13:28
Duplicate of https://github.com/directus/directus/issues/2937

**Closed by rijkvanzanten** 2020-12-21 13:28 UTC

**Comment by aschoijett** [comment] 2020-12-22 01:49
Hi Rick

I trust you noticed that there are minor differences between the two
tickets, although the solution for one will likely fix the other.

Many thx!

**Comment by rijkvanzanten** [comment] 2020-12-22 01:52
@aschoijett Rijk*

> [...] the solution for one will likely fix the other.

Yes that's why I closed it as a duplicate. The symptom you describe is very similar, and has the same cause 👍

**Comment by aschoijett** [comment] 2020-12-22 01:55
Thx Rijk
