### ISSUE TITLE
Videos accessed via assets/ endpoint will not play on native iOS

### ISSUE THREAD

**Issue by MarkBurvs** [directus/directus#3848] opened 2021-01-29 16:49 UTC
I *think* this might be related to [#3640](https://github.com/directus/directus/issues/3640) or [#3510](https://github.com/directus/directus/discussions/3510).

When you upload a video file (I'm using .mp4 files) via directus, and then try and access it using the /assets/ endpoint, using AVFoundation on a native iOS app, it fails to load and the following error is returned in XCode:

`2021-01-29 15:52:36.910466+0000 vidtest3[2257:132333] [] [15:52:36.910] -[FigHTTPRequestSessionDataDelegate URLSession:dataTask:didReceiveResponse:completionHandler:] signalled err=-12939 (kFigHTTPRequestError_ServerDoesNotSupportByteRanges) (no content length/range with byterange request) at /Library/Caches/com.apple.xbs/Sources/EmbeddedCoreMedia_Sim/EmbeddedCoreMedia-2765.6/Prototypes/FigHTTP/FigHTTPRequestNSURLSession.m:1907`

Strangely, videos play okay on Android, although seeking does not work and causes the playback to stop and hang.

We're working around this for now by accessing the files directly using the file path (which works fine), but it's far from ideal as I don't really want to have to make them publicly accessible, and this is something I have to do manually for each video we add. So it's kind of blocking our project at the moment. :(

My setup is Directus v9.0.0-rc.24 running on a Digital Ocean droplet, deployed using npx, with MySQL database and storage on Digital Ocean Spaces.

To replicate, you can follow the [simple tutorial here for a simple video player](https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos), and try playing a video file via the assets/ endpoint.

**Comment by rijkvanzanten** [comment] 2021-01-29 17:03
Duplicate of #3640

**Closed by rijkvanzanten** 2021-01-29 17:04 UTC
