### ISSUE TITLE
"Type Not Assignable" When Fetching Nested Data with Directus SDK

### ISSUE THREAD

**Issue by Vahagn-Zaqaryan** [directus/directus#23604] opened 2024-09-08 21:18 UTC
### **Current Behavior**
When using the Directus SDK to fetch nested data with specific projections, I receive the following error from the TypeScript compiler:

> "Type '{ m2o: string[]; }' is not assignable to type '"*" | keyof Article'."

![Error Screenshot](https://github.com/user-attachments/assets/204afe82-1a66-4d5f-b9a1-5738d66b08ee)

### **Expected Behavior**
The nested data should be fetched without any TypeScript compilation errors.

### **Steps to Reproduce**
You can reproduce this issue using [this StackBlitz link](https://stackblitz.com/edit/vitejs-vite-dkw62f?file=src%2Fmain.tsan):

1. Create a new TypeScript project using version `5.5.3`.
2. Install the Directus SDK version `17.0.1`.
3. Copy and paste the following code:

   ```typescript
   import { createDirectus, rest, readItems } from '@directus/sdk';

   const directusUrl = 'url';

   interface ArticleNested {
     id: string;
     something: string;
   }

   interface Article {
     id: string;
     m2o: number | ArticleNested;
   }

   interface Schema {
     articles: Article[];
   }

   const directusClient = createDirectus<Schema>(directusUrl).with(rest());

   directusClient.request(
     readItems('articles', {
       fields: ['id', { m2o: ['something'] }],
     })
   );
   ```

4. You should see a TypeScript error on `{ m2o: ['something'] }`:

   ![TypeScript Error Screenshot](https://github.com/user-attachments/assets/fc8eb485-08d5-46af-8a4b-c5b4fed05ddd)

#### **Versions**
- `@directus/sdk`: 17.0.1
- `typescript`: 5.5.3

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by KataaM** [comment] 2024-10-06 03:07
Hey, any news on this, did you figured it out ?

**Comment by beakman** [comment] 2024-10-06 06:18
Hello! 

I had a similar issue and the problem was an incomplete Schema. You need to specify all model you use.

This is mine for example:

```
interface Schema {
  animals: Dogs;
  animals_translations: Array<DogTranslation>;
  animals_files: Array<DogsFile>;
  pages: Pages;
  positions: Position;
  pages_positions: Array<PagesPositions>;
  pages_translations: Array<PagesTranslation>;
  testimonials: Testimonials;
  testimonials_translations: Array<TestimonialTranslation>;
  globals: Global;
  globals_translations: Array<GlobalTranslation>;
  directus_files: Array<Image>;
}

```

**Comment by KataaM** [comment] 2024-10-06 23:18
Hey!

I'm having trouble understanding. Could you please provide more information on how you request data in Directus, and how your TypeScript structure compares to the data model in Directus?

Thanks

**Comment by GianniBuoni** [comment] 2024-10-09 20:01
Adding on to this, since I was struggling with it myself!

It does have something to do with an incomplete schema. 
In regards to the original issue this fixes the type error:

```ts
interface Schema {
  articles: Article[];
  article: ArticleNested;
}
```

**Comment by br41nslug** [comment] 2024-12-12 11:23
The issue here is indeed that the `NestedArticle` collection is missing from the root schema and thus is not recognized as relation.

**Reproduction of the error:**
![image](https://github.com/user-attachments/assets/09f13c81-b78a-4812-a53d-c04ed6d091aa)

**Fixed by adding to the schema:**
![image](https://github.com/user-attachments/assets/ca85185a-e86e-4c94-b5fc-fb698153b071)
https://www.typescriptlang.org/play/?ssl=26&ssc=3&pln=1&pc=1#code/JYWwDg9gTgLgBAbzgYygUwIYzQEWO5GAVwGcAaOdEmC9DAEwElsQS4BfOAMyghDgDkAAXr40hUgHoS9ANYCA3ACglyCADtqcUQWIkAqlAA2cALyCixxSuDrsULhmRo4AQVjBkRtADk01NHpEJTg4YHoALjhqKFsAc2VQkj40GAALeKiY+OV2Gzs0BycXdxhPb2DQ8KyYWPUEkLgQACYIKPUiEAAjQrgAHzcPL19-bHpc-PtHZzgAZWQ0tBAMSrgMIe8SKNLytABtAF1EtY20AH11UcDt078A+kOJ1Q0tHXE9AGEjYDQ7MxQ6Ng8LpSAAeeaLZYAPgAFG8JAZjABKAB0AHdgOkYVQYDCkUjlEp4Z9vr8YCj0ABHIijGGNOhMFgkGECdZlYYkAQUBCNUJcH5GehbOB7AThLmIJqtKKi5IgVIZeoCA4cA5kRrsJFKAlAA

**Closed by br41nslug** 2024-12-12 11:23 UTC
Labels: Bug, SDK
