### ISSUE TITLE
Logical "_and" filter doesn't work

### ISSUE THREAD

**Issue by renaudfractale** [directus/directus#13609] opened 2022-05-29 10:55 UTC
### Describe the Bug

With Postman, my request :
`{{rootURL}}items/SeancePhotos/?filter{"_and": [{ {"DateEnd" : {"_null": true}},{"Photographe" : {"_eq" :2 } }]}`
Return same data  of :
`{{rootURL}}items/SeancePhotos/?filter{"_or": [{ {"DateEnd" : {"_null": true}},{"Photographe" : {"_eq" :2 } }]}`

The resulat :
{
    "data": [
        {
            "id": 9,
            "user_created": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_created": "2022-05-27T04:24:48.284Z",
            "user_updated": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_updated": "2022-05-27T18:16:14.551Z",
            "DateStart": "2022-05-27T06:24:40",
            "DateEnd": "2022-05-28T12:00:00",
            "IdEvents": 1,
            "Photographe": 1,
            "SujetRoots": [
                7,
                9
            ],
            "idPhotos": [
                "053b905f-86d4-43be-b84f-7da8647f9eb2",
                "8f2f17aa-3801-471a-abf4-8e4bde179520"
            ]
        },
        {
            "id": 10,
            "user_created": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_created": "2022-05-27T21:57:55.597Z",
            "user_updated": null,
            "date_updated": null,
            "DateStart": "2022-05-27T23:57:52",
            "DateEnd": null,
            "IdEvents": 1,
            "Photographe": 2,
            "SujetRoots": [
                10,
                11
            ],
            "idPhotos": []
        },
        {
            "id": 11,
            "user_created": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_created": "2022-05-29T10:09:15.778Z",
            "user_updated": null,
            "date_updated": null,
            "DateStart": "2022-05-29T12:09:11",
            "DateEnd": null,
            "IdEvents": 1,
            "Photographe": 1,
            "SujetRoots": [],
            "idPhotos": []
        }
    ]
}

### To Reproduce

Use operator _and 

### Errors Shown

{
    "data": [
        {
            "id": 9,
            "user_created": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_created": "2022-05-27T04:24:48.284Z",
            "user_updated": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_updated": "2022-05-27T18:16:14.551Z",
            "DateStart": "2022-05-27T06:24:40",
            "DateEnd": "2022-05-28T12:00:00",
            "IdEvents": 1,
            "Photographe": 1,
            "SujetRoots": [
                7,
                9
            ],
            "idPhotos": [
                "053b905f-86d4-43be-b84f-7da8647f9eb2",
                "8f2f17aa-3801-471a-abf4-8e4bde179520"
            ]
        },
        {
            "id": 10,
            "user_created": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_created": "2022-05-27T21:57:55.597Z",
            "user_updated": null,
            "date_updated": null,
            "DateStart": "2022-05-27T23:57:52",
            "DateEnd": null,
            "IdEvents": 1,
            "Photographe": 2,
            "SujetRoots": [
                10,
                11
            ],
            "idPhotos": []
        },
        {
            "id": 11,
            "user_created": "9e9656c8-0df6-4edb-a0bf-cd82f8ad98b3",
            "date_created": "2022-05-29T10:09:15.778Z",
            "user_updated": null,
            "date_updated": null,
            "DateStart": "2022-05-29T12:09:11",
            "DateEnd": null,
            "IdEvents": 1,
            "Photographe": 1,
            "SujetRoots": [],
            "idPhotos": []
        }
    ]
}

### What version of Directus are you using?

image: directus/directus:latest

### What version of Node.js are you using?

image: directus/directus:latest

### What database are you using?

image: postgis/postgis:13-master

### What browser are you using?

PostMAN

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-05-29 11:37
I was not able to reproduce this locally:

- `_and`

   URL: `http://localhost:8055/items/photos?filter={"_and":[{"date_end":{"_null":true}},{"photographer":{"_eq":2}}]}`
   
   ![chrome_iRcfssovxj](https://user-images.githubusercontent.com/42867097/170865690-a16b734f-5eba-470f-91be-81d60f1970b6.png)


- `_or`

   URL: `http://localhost:8055/items/photos?filter={"_or":[{"date_end":{"_null":true}},{"photographer":{"_eq":2}}]}`

   ![chrome_NT07lTBETB](https://user-images.githubusercontent.com/42867097/170865694-61119dc7-bd71-40bf-918a-2bebcd93961a.png)

but I believe in your case, the filter isn't being used because of two potential issues I noticed:

- there is no `=` (equal sign) in your query (after `filter`) so it is not a valid URL query parameter

- there's an extra `{` bracket near "DateEnd" which is not a valid JSON

so you can try changing your current query to:

```diff
- items/SeancePhotos/?filter{"_and": [{ {"DateEnd" : {"_null": true}},{"Photographe" : {"_eq" :2 } }]}
+ items/SeancePhotos?filter={"_and": [{"DateEnd" : {"_null": true}},{"Photographe" : {"_eq" :2 } }]}
```

I'll close this for now since I believe it's an usage error rather than an actual bug, but do let us know if that's not the case.

**Closed by azrikahar** 2022-05-29 11:37 UTC
Labels: Bug (Potential)
