### ISSUE TITLE
Delete error when removing collection that previously had M2M relationship field

### ISSUE THREAD

**Issue by mathewdodds** [directus/directus#11918] opened 2022-03-02 20:39 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Despite removing the concerning M2M fields of both collections in the relationship, they both become non-removable

### To Reproduce

Create two collections. Create M2M relationship with a field in each collection. Remove the fields, try deleting either collection.

### Errors Shown

[INTERNAL_SERVER_ERROR] drop table "Community" - cannot drop table "Community" because other objects depend on it

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 13.5

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

VPS (ubuntu)

**Comment by azrikahar** [comment] 2022-03-03 05:18
Did you delete the junction table as well? I've tested on my end and it does show the same error when I've only deleted the field in both collection, but it works after deleting the junction table (since technically the junction table indeed has their foreign keys).

I'll close this for now, but do update us and we'll reopen if the error still pops up after you deleted the junction table 👍

**Closed by azrikahar** 2022-03-03 05:18 UTC
Labels: Bug (Potential)

**Comment by azrikahar** [comment] 2022-03-09 05:35
@stefan1968 did you delete the junction table beforehand? If it still persists after the junction table has been deleted, opening a new issue with a video clip and minimal reproduction steps would be great to help us understand what could be happening here 👍
