### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by asitemade4u** [directus/directus#2621] opened 2020-03-20 20:24 UTC
# Feature Request
I would love to be able to use PostgreSQL as a backend. MySQL is great but has severe limitations when dealing with geospatial data, which is precisely why I use PostgreSQL in conjunction with PostGis.
A Google search on the subject gives a somewhat hesitant set of responses from the developers of Directus.
What is the last stance on the subject?

## What problem does this feature solve?
Limitations of MySQL. PostgreSQL is wooed, and rightly so, as an outstanding database environment.

## Would you be willing to work on this?
Doc in English and French.
Testing (I live in BK)

**Comment by WoLfulus** [comment] 2020-03-20 20:42
The current codebase won't receive support for PostgreSQL, but as we're actually porting Directus to Laravel Framework, you can expect (by default) support for these new databases in the next few months.

-    MySQL 5.6+
-    PostgreSQL 9.4+
-    SQLite 3.8.8+
-    SQL Server 2017+

**Comment by asitemade4u** [comment] 2020-03-20 20:48
YESSS !

**Comment by rijkvanzanten** [comment] 2020-03-20 21:42
Duplicate of https://github.com/directus/api/issues/369

**Closed by rijkvanzanten** 2020-03-20 21:42 UTC
