### ISSUE TITLE
Error while initializing project with sqlite

### ISSUE THREAD

**Issue by cupcakearmy** [directus/directus#3320] opened 2020-12-05 14:39 UTC
```
npx create-directus-project my-project
```

Select sqlite.
You will be asked for a filename for the sqlite db. No matter if you simply press enter or insert a custom file the installier fails

```bash
npx create-directus-project my-project
npx: installed 46 in 3.429s
? Choose your database client SQLite (Beta)
? Database File Path: /****/my-project/data.db

Something went wrong while seeding the database:

undefined Method implemented in the dialect driver

Please try again

? Database File Path: ./test.db

Something went wrong while seeding the database:

undefined Method implemented in the dialect driver

Please try again
```

**Comment by myzinsky** [comment] 2020-12-06 20:45
Same here

**Comment by nickrum** [comment] 2020-12-06 21:18
This is a duplicate of #2904.
@rijkvanzanten has already created a PR against the knex.js repo (which is the database abstraction layer directus is using) so hopefully this will be fixed soon.

**Closed** 2020-12-06 21:20 UTC
Labels: Duplicate

**Comment by cupcakearmy** [comment] 2020-12-06 22:03
@nickrum Oh my bad then. Awesome that it's being worked on already 🥳

**Comment by nickrum** [comment] 2020-12-06 22:17
@cupcakearmy no worries! My issue wasn't exactly well named.
