### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by digitaltopo** [directus/directus#2268] opened 2018-12-23 04:28 UTC
# Bug Report
Unable to install Directus suite using given [Installation instructions](https://docs.directus.io/getting-started/installation.html#setup). 

Can you please clarify what's going on here? I'm never prompted to configure anything.

## Steps to Reproduce

1. Go to [Installation docs](https://docs.directus.io/getting-started/installation.html#setup)
2. Follow [Setup instructions](https://docs.directus.io/getting-started/installation.html#setup)
3. Clone git repo: `git clone https://github.com/directus/directus.git`
4. Navigate your browser to the App at /admin

## Expected Behavior
Display promts for [complete configuration](https://docs.directus.io/getting-started/installation.html#configure)
## Actual Behavior
Displays login screen and says api not found

## Technical Details

- Device: [eg: Desktop, iPhone6, etc]
- OS: [eg: MacOS 10.13.6, Windows 10.1803]
- Web Server: Apache
- PHP Version: 7.1
- Database: MySQL
- Install Method: `git clone https://github.com/directus/directus.git`

**Comment by shealavington** [comment] 2018-12-23 08:36
Have you been through the requirements and ensured you have all the required extensions? 

https://docs.directus.io/advanced/requirements.html

**Comment by digitaltopo** [comment] 2018-12-24 08:05
Problem is it doesn't look like the repo `https://github.com/directus/directus.git` includes everything in the first place... for example, there is no `api` directory. I'm thinking in the following example, that you're assuming we've installed the API at `var/wwww/api`?:

[Permissions requirements](https://docs.directus.io/advanced/requirements.html#permissions)

Here's what we actually have after cloning: 

`$ ls directus`:

```
bin     docker-compose.yml  migrations  src
config  LICENSE.md          public      vendor
docker  logs                README.md
```

`$ ls public`:

```
admin  extensions  index.php  thumbnail  uploads
```

It all seems very confusing when the docs don't reflect the actual install process. Has something changed but not been updated in docs?

It's not obvious what the docs are referring to here... does the [Directus Suite](https://docs.directus.io/getting-started/introduction.html#directus-suite) not include both the admin application and the api as it claims?

After cloning the [git repo](https://github.com/directus/directus.git), and visiting the `../public/admin` url:

![screenshot_2018-12-23_23-54-35](https://user-images.githubusercontent.com/1680796/50393903-226cc100-070e-11e9-8186-76999e41fb4a.png)

I see in the network tab that there is a request to: `http://mydomain.com/directus/public/server/ping`
Of course this directory does not exist.

Step 3 `Follow the prompts to complete configuration (see below)` from the docs on [Configure](https://docs.directus.io/getting-started/installation.html#configure) never happens. 

Could you please provide some clarification or a complete list of steps on how to install?

**Comment by shealavington** [comment] 2018-12-24 10:34
Everything you see is related to the API except the APP, this is inserted into `/public/admin`. I don't understand where you're stuck. 

Have you followed the manual configuration process? If not, what are you stuck on

**Comment by digitaltopo** [comment] 2018-12-26 22:45
> I don't understand where you're stuck, your install seems to mimic the repository fine, not sure what you mean about an API directory, that will just be wherever you've decided to install Directus.

What's not clear is if by installing the 'Directus Suite', the API ALSO gets installed??
`git clone https://github.com/directus/directus.git`

What I'm stuck on is that there doesn't seem to be an API after following the install instructions for Directus Suite.

**Comment by shealavington** [comment] 2018-12-26 22:49
The suite is basically just the API, but with the APP stuck under the public/admin folder.

**Comment by digitaltopo** [comment] 2018-12-26 23:05
> But by just saying I installed and it didn't work

I've documented everything in this thread, I'm literally following the instructions in the docs and the configure step does not work. I'm just looking for some help to try Directus out, not sure how my posts can be any clearer on what's wrong... I'd appreciate it if you could take a look at what I've posted so far as well.

Here's the instructions I'm following from the docs:
![screenshot_2018-12-26_14-56-40](https://user-images.githubusercontent.com/1680796/50459357-3c312280-091f-11e9-95c3-50cc1d0ed0cc.png)


Pasting from original bug report above: 

> [Steps to Reproduce](https://github.com/directus/directus/issues/2268#issue-393722188)
1. Go to Installation docs
1. Follow Setup instructions
1. Clone git repo: git clone https://github.com/directus/directus.git
1. Navigate your browser to the App at /admin

**PROBLEM:** Displays login screen and with message `api not found`. No configuration form.

![login-form](https://user-images.githubusercontent.com/1680796/50393903-226cc100-070e-11e9-8186-76999e41fb4a.png)

**Comment by shealavington** [comment] 2018-12-26 23:07
Okay, as you don't see an installer. Please try to proceed with a manual install.

https://docs.directus.io/advanced/api/configuration.html#configure-manually

**Comment by digitaltopo** [comment] 2018-12-26 23:08
Is it still PEBKAC though?

**Comment by benhaynes** [comment] 2018-12-26 23:13
Hey @digitaltopo — thanks for providing so much info on this issue. Could you perhaps also add this:

Device: [eg: Desktop, iPhone6, etc]
OS: [eg: MacOS 10.13.6, Windows 10.1803]

Are you installing locally or on a webserver? Did you try [pinging the API](https://docs.directus.io/api/reference.html#ping) manually?

Could you paste the two paths here? To me this seems like an issue with setting the public directory. You said:

> After cloning the git repo, and visiting the ../public/admin url:

**Comment by digitaltopo** [comment] 2018-12-26 23:20
@benhaynes thanks for your reply.

I'm installing on a web server. I have a subdomain `sub.domain.com` that is now pointing to `directus/public`. (previously was in another sub-dir but have changed it since)

I've just tried the [manual install steps using the scripts](https://docs.directus.io/advanced/api/configuration.html#configure-with-script)
which have created an `api.php` file in the `config` directory. It seems to have all the right info in it.

Still seeing the same error on login page.

**Comment by benhaynes** [comment] 2018-12-26 23:30
Thanks. Yes there is an [htaccess file](https://github.com/directus/directus/blob/master/public/.htaccess).

Manually creating the config won't fix this since that only configures the API... but your problem is that the App can't **find** the API. As I mentioned, this is likely due to the public redirect. If you have your server properly configured to point to the `/public` directory then your URLs would be:

* `sub.domain.com/admin` — App used to manage all projects
* `sub.domain.com` — Base API
* `sub.domain.com/_/` — Default Project for API, using `api.php`
* `sub.domain.com/_/ping` — Ping endpoint to make sure you have the routing working correctly. If this is not working then the issue is almost certainly your document root.

**Comment by digitaltopo** [comment] 2018-12-26 23:39
Yes, I see the `.htaccess` in the `/public` directory.

None of the urls except `/admin` work. When I go to any of the others I get a `500` from the server and see this in the apache error_log:

```
[Wed Dec 26 15:36:09.913965 2018] [:error] [pid 20074:tid 47743215118080] [client IP:PORT] SoftException in Application.cpp:261: File "/home/USER/directus/public/index.php" is writeable by group
[Wed Dec 26 15:36:09.914162 2018] [core:error] [pid 20074:tid 47743215118080] [client IP:PORT] End of script output before headers: index.php
[Wed Dec 26 15:36:09.960933 2018] [:error] [pid 20074:tid 47743215118080] [client IP:PORT] SoftException in Application.cpp:261: File "/home/USER/directus/public/index.php" is writeable by group
[Wed Dec 26 15:36:09.961146 2018] [core:error] [pid 20074:tid 47743215118080] [client IP:PORT] End of script output before headers: index.php
```

**Comment by benhaynes** [comment] 2018-12-26 23:42
Did you try updating the owner of your Directus directory?

```
sudo chown -R www-data:www-data /var/www/api```

https://docs.directus.io/advanced/requirements.html#permissions

**Comment by digitaltopo** [comment] 2018-12-27 00:06
Ok got past this step and now API is showing up.

Solution was to change permissions to 755 and 644 on directories and files respectively. After that the SuPHP `SoftException` error went away and endpoints show up.

**Closed** 2018-12-27 00:06 UTC

**Comment by benhaynes** [comment] 2019-01-21 16:49
@rijkvanzanten @WellingGuzman — do we want to add more specific permissions setup to our Docs? Anything we can improve in the Install Docs to make this more fool-proof?

**Comment by adamjgrant** [comment] 2019-02-01 22:55
Pro tip, you can also tail the directus logs in the directus directory with

~~~
tail -f logs/error.*.log 
~~~

I'm having this issue now and am now seeing it's a db connection issue.

**Comment by adamjgrant** [comment] 2019-02-02 00:07
Edited /etc/mysql/mysql.conf.d/mysqld.cnf after following instructions at https://dev.mysql.com/doc/refman/5.7/en/creating-ssl-files-using-openssl.html

I'm not sure if SSL is even required here.

Also tried https://github.com/directus/directus/issues/2197 and made the edits to the .htaccess file. Although I should point out there is no api directory in admin.
