### ISSUE TITLE
Settings / Flows - List Sort not working

### ISSUE THREAD

**Issue by ernst86913** [directus/directus#17389] opened 2023-02-03 11:22 UTC
### Describe the Bug

Column Sort does not work for List of Flows in the Settings 

### To Reproduce

Open Settings / Flows - try to sort based on Status / Name / Description... does not work....

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres 15

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment] 2023-02-03 11:24
Duplicate of  https://github.com/directus/directus/issues/17195 should be fixed with the next release

**Closed by br41nslug** 2023-02-03 11:24 UTC
Labels: Duplicate
