### ISSUE TITLE
Date showing wrong value

### ISSUE THREAD

**Issue by rfos** [directus/directus#12769] opened 2022-04-14 18:04 UTC
### Describe the Bug

I created a field to input only date (not DateTime) but when I choose the date from the picker date while I'm editing the entry it shows the previous day.

If I choose:
 "start_date": "2022-04-01"

It returns
 "start_date": "2022-03-31"

### To Reproduce

- Create a new Collection
- Create one field DateTime and change it to only date before saving the file (not DateTime) "start_date".
- Try to add an entry, when you choose the date using the date picker it's correct, but when you back in the list of all entries the value is -1, the day before you chose.
- The result in JSON is also -1 
 "start_date": "2022-03-31" instead of  "start_date": "2022-04-01"DateTime

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

MS SQL 

### What browser are you using?

Chrome

### How are you deploying Directus?

locally - Windows 10

**Comment by rfos** [comment] 2022-04-14 18:13
Strange things are happening here! In the database the value is correct.

**Comment by rijkvanzanten** [comment] 2022-04-14 18:16
Duplicate of https://github.com/directus/directus/issues/7383 🙂 

This was resolved in https://github.com/directus/directus/pull/10956 which will be released shortly 👍🏻

**Closed by rijkvanzanten** 2022-04-14 18:16 UTC
Labels: Bug (Potential)
