### ISSUE TITLE
In table view: Cannot read property 'primary' of undefined check

### ISSUE THREAD

**Issue by casey-chow** [directus/directus#6326] opened 2021-06-16 21:32 UTC
I have a collection named `user` in my Postgres database on Directus v9.0.0-rc.73, and have made a many-to-one field `user_id` in another collection, called `capture`. I've found that if I include `user_id` in the fields listed in the table view of the app, I get the following error:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'primary' of undefined",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

As part of debugging, I found that the issue came from the below line: https://github.com/directus/directus/blob/230060e5750a6131dc2f4f7aeb06578d96c64c5e/api/src/utils/get-ast-from-query.ts#L183

I found that the value `relatedCollection` in the erroring case was `'"user"'` rather than `'user'`, interestingly (seems like knex may be escaping it for Postgres?), and `user` is in the list of collections (but not `"user"`).

**Comment by rijkvanzanten** [comment] 2021-06-16 21:34
Try updating to the latest version, the double quoting should be fixed in 75+ 🙂 

Duplicate of https://github.com/directus/directus/issues/6149

**Closed by rijkvanzanten** 2021-06-16 21:34 UTC

**Comment by casey-chow** [comment] 2021-06-16 21:42
Thanks for the heads up! That issue did not show up when I searched...

**Comment by rijkvanzanten** [comment] 2021-06-16 21:44
> That issue did not show up when I searched...

Yeah, makes sense! 

Your comment:

> I found that the value relatedCollection in the erroring case was '"user"' rather than 'user'

rang a bell 🙂
