### ISSUE TITLE
O2M Drawer empty

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#15412] opened 2022-09-06 04:31 UTC
### Describe the Bug

When you open the drawer of an O2M interface, the form is missing. 
![Uploading image.png…]()

### To Reproduce

Open a drawer of an O2M interface

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

v14.19.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-09-06 04:52
Would you mind re-uploading the image (it's currently not uploaded properly)? Can you help provide a more concise reproducible steps? A screen capture would be much appreciated, but not compulsory. That said, I can't seem to reproduce this on my end:

https://user-images.githubusercontent.com/42867097/188549478-8230657e-1298-47e8-85ee-e59f69b49707.mp4

But I do wonder does this actually share the same root cause as #15407, assuming the behavior is the same which is missing form in drawers.

**Comment by MichaelNussbaumerGOWEST** [comment] 2022-09-06 04:57
[screen-capture (6).webm](https://user-images.githubusercontent.com/15796397/188550273-2575358c-0e87-435c-890b-5a015f2268fe.webm)

**Comment by azrikahar** [comment] 2022-09-06 05:15
Thanks for the screen capture! However I'm still unable to reproduce this issue on my end. Would you mind listing out the minimal reproducible steps on a new & fresh Directus instance? That'd be much appreciated.

**Comment by MichaelNussbaumerGOWEST** [comment] 2022-09-06 05:22
@azrikahar sorry my fault it is an O2M realtion not M2M.

**Comment by azrikahar** [comment] 2022-09-06 05:30
@MichaelNussbaumerGOWEST Thank you for clarifying swiftly! I can now confirm this does happen for O2M, and I've also verified that it shares the same root cause as #15407. 

Closing this in favor of tracking it over there, so feel free to subscribe to #15407 for future updates regarding this bug 👍

**Closed by azrikahar** 2022-09-06 05:30 UTC
Labels: App, Needs More Info, Bug (Potential), Can't Reproduce
