### ISSUE TITLE
Invalid Query. Invalid filter key \"admin_access\" on \"directus_roles\" When Using /users/me?fields=*.*

### ISSUE THREAD

**Issue by ahmadoji01** [directus/directus#23247] opened 2024-08-08 05:56 UTC
### Describe the Bug

Hi, I am reporting an issue where I tried to query to get the current user data using Directus 11. Previously, it worked fine. Only the latest version broke the query mentioned. Based on my experiment, it's caused by the `admin_access` key that prevents me from getting the details of the roles of the current user, which I need to manage my application. Other than that, it works great!

### To Reproduce

Using Postman, I did these things:
- Login with token
- Use the token to run the `/users/me` query without `fields` params. Works fine
- Add the `field=*`. Works fine too
- Then I change the `field=*` to `field =*.*`, the issue popped up
- I also tried to inquire using `field=role`, it works fine. But the second depth of the role, for example `fields=role.id`, causes the issue mentioned in the title

### Directus Version

v11.0.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

Postgres 14

**Comment by hanneskuettner** [comment] 2024-08-08 07:54
Do you have any extensions, flows or permissions that try to access the `role.admin_access` field? This field has been removed from the `directus_roles` table and moved to the `directus_policies` table, as part of the permissions rework in v11, see https://docs.directus.io/releases/breaking-changes.html#roles

**Comment by ahmadoji01** [comment] 2024-08-08 10:04
I do use flows, but I only get the data from the table I created related to the user to manage the permission. No `role.admin_access` is used in this case. Same goes with the permissions too, using table related to the user. As for the extensions, nothing I use so far. Since this is quite breaking the app, I am temporarily rolling back to version `10.13.1`. I am also investigating the matter myself and intend to upgrade later when this issue has been resolved from either party as I love how the update is useful for managing complicated permissions, one feature that I hugely need

**Comment by hanneskuettner** [comment] 2024-08-08 10:15
Mind double checking just to make sure that none of the permissions access `admin_access` on the role (since it occurs when you're accessing `role.id`, you also need to check the permissions in `directus_roles`). Same problem for `$CURRENT_ROLE.admin_access`.

**Comment by ahmadoji01** [comment] 2024-08-08 10:30
Yes, I will do it. Just to be exactly sure, I will try to make a clean project just to make sure that the issue isn't supposed to be there. If that's the case, then probably I messed up the update process somewhere when I was updating from `10.13.1` to `11.0.0`. I will come back later when I have tested it

**Comment by hanneskuettner** [comment] 2024-08-08 10:32
If the problem persists and you're not able to figure it out, maybe you can share a database dump with me at hannes[at]directus.io

**Comment by ahmadoji01** [comment] 2024-08-10 09:41
I can confirm the issue went away when I used the clean installation of Directus. I also encountered strange issues when I was installing Directus using NPM (Docker is still out of the question for now as I am developing locally and it's easier to correct mistakes and to rollback any changes should the latest version has breaking changes), the details how I correct the installation will follow at the end of the message. I tried to do the same thing how I produced the issue by the following:
- Create a new user, access policy, and role
- Includes the new user and role to the policy
- Do the `/users/me?fields=*` query. Works perfectly
- Change the `fields=*` to `fields=*.*`, it returns 200 code. However, the role field now is missing by default. I added the permission to read `directus_roles` collection and it's working perfectly now.

Possible Causes:
If you update from 10.13.xx, although I have run the database migration command, the `directus_role` collection possibly still contains `admin_access` field where in version 11, it's supposed to be on `directus_access` collection

PS for Error Fixes on NPM Installation on Ubuntu:
Although the installation wizard has asked you the questions of the database information, somehow the NPM still asks you to set your environment variables. In case someone encountered this issue, you can manually add these variables before you install Directus with NPM. (This is the sample case of Postgres)
```
DB_CLIENT=pg
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=postgres
DB_PASSWORD=postgres
DB_DATABASE=directus
```

**Comment by hanneskuettner** [comment] 2024-08-10 09:50
Heya! Thank you for coming back to us!

> If you update from 10.13.xx, although I have run the database migration command, the directus_role collection possibly still contains admin_access field where in version 11, it's supposed to be on directus_access collection

I don't think that was the root cause of the problem, as first, the migration would not have been successful, as removing the field is part of the migration, and second, the pure presence of the `admin_access` would not cause it to be present in any filters. I still think that was a setup issue caused by some hidden permission / flow that was trying to access add a filter on the `directus_roles.admin_access` field. But great to hear that his does not occur in a fresh installation for you!

> I also encountered strange issues when I was installing Directus using NPM

This is most likely related to this issue https://github.com/directus/directus/issues/23255 and will be fixed in an upcoming release.

I'll close this issue as we both can't seem to reproduce it anymore. If you or anyone encounters this issue again I'm more than happy to re-open this!

**Closed by hanneskuettner** 2024-08-10 09:50 UTC
Labels: :detective: Needs More Info, :file_folder: Access Control

**Comment by ahmadoji01** [comment] 2024-08-16 06:56
I'd like to just add additional information to this.

So, I just tried again to reproduce the issue by migrating from version 10.13.x to 11.0.x on another machine. I happened to encounter the same error. The context is that I made a custom role and restricts the admin access to it via Directus dashboard. This time, it's clear that something inside the `directus_roles` collection is the trouble as I directly made a request to `/roles` endpoint. Apparently, the restriction to access admin set via dashboard generates a rule `admin_access: false` when migrated. That's why the query to `directus_roles` always fails as it filters the non-existent `admin_access` field. Just in case someone encountered the same issue, I deleted the rule and it fixed the problem.

**Comment by hanneskuettner** [comment] 2024-08-16 07:05
What were the permissions you created for that custom role? Sounds like you were manually checking for `role.admin_access` or something?

**Comment by ahmadoji01** [comment] 2024-08-16 07:14
I don't create any special permission to the collections that belong to the system, only for the collections I created.

Also, not really sure before that I manually checked the `role.admin_access`. What I only did before I migrated to 11.0.x was that I don't want the custom role to access Directus admin dashboard is all and the 10.13.x dashboard provided the checklist to give the custom role to access/be restricted from the admin access. Somehow, this rule is carried into 11.0.x that has a new policy system and when I checked the `directus_roles` collections, I don't recall I manually, by inputting the rule field (not via checklist on the dashboard), added `admin_access:false` at all and somehow it was there.

**Comment by hanneskuettner** [comment] 2024-08-16 07:35
Did you use anything like `$CURRENT_ROLE.admin_acess` in any of your custom permissions?

Can you share the permission row you had to delete in order to get your project working again?

**Comment by ahmadoji01** [comment] 2024-08-16 07:59
I never use `$CURRENT_ROLE.admin_access` at all and what causes the trouble is only the rule `admin_access:false` that somehow, without me knowing, was added to `directus_roles`. You can see it on the SS below. It has completely fixed now. 

![Screenshot 2024-08-16 145417](https://github.com/user-attachments/assets/db75a3c9-2def-4f6d-9cf0-25c62c20a518)

But just as an insight, I have a table called `unit` where each user creation is assigned to it (no flow's used, I made sure my frontend app assigned the user for each creation/update). The permission I used is `$CURRENT_USER.unit.id`. But this isn't applied to any system collections except `directus_users`.

**Comment by hanneskuettner** [comment] 2024-08-16 08:07
And can you confirm that they permission rule was not there in your 10.13 database?

**Comment by ahmadoji01** [comment] 2024-08-16 08:10
I already migrated both my machines to 11.0.x. But I can try to confirm if the rule was there or not on version 10.13.x. I'll get back to you later when I have checked it

**Comment by hanneskuettner** [comment] 2024-08-16 08:15
Perfect thank you! I'd love to get to the bottom of that, and if it just is to confirm that there isn't an undiscovered issue in the automatic migrations
