### ISSUE TITLE
Cannot change user password when policy set to None

### ISSUE THREAD

**Issue by digitaljohn** [directus/directus#5527] opened 2021-05-07 00:31 UTC
When attempting to update a users password field while the password policy is set to "None - Not Recommended" causes an error:

```json
{
  "message": "Cannot read property 'startsWith' of null",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

This error appears to originate from here:
https://github.com/directus/directus/blob/044ab5e1f76686e08b1da9a0d7e94aadc7576264/api/src/services/users.ts#L74

Changing to any other password policy allows us to partially sidestep the issue.

---

### Project details
Directus Version: 9.0.0-rc.61
Environment: production
OS: Linux 4.4.0
Node: 14.16.1

**Comment by rijkvanzanten** [comment] 2021-05-07 03:43
Duplicate of https://github.com/directus/directus/issues/5310

**Closed** 2021-05-07 03:43 UTC
Labels: Duplicate
