### ISSUE TITLE
JSON field default value saved as a string

### ISSUE THREAD

**Issue by ArtemAstakhov** [directus/directus#16896] opened 2022-12-23 15:26 UTC
### Describe the Bug

The json field is saved as a string, but if you go into the created entity, the field will be displayed correctly

### To Reproduce

1. Create JSON field
2. Add default JSON
![image](https://user-images.githubusercontent.com/18442991/209359004-951d8f45-f374-41ed-9156-36db064650c8.png)

3. Save field
4. Default value saved as a string
![image](https://user-images.githubusercontent.com/18442991/209359098-b3c2a37f-1ca8-4ac6-8c32-f66bf32437cc.png)

5. Start creating new entity, default value is a string
![image](https://user-images.githubusercontent.com/18442991/209359213-70a889fc-b5f5-44a0-aa8c-9aa879f391e7.png)

6. Save entity and open it to edit, field is displayed correctly as JSON
![image](https://user-images.githubusercontent.com/18442991/209359331-6647ae28-79bd-47b0-8b4e-81d6bf464130.png)

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

16.4

### What database are you using?

MariaDB 10.6

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-12-23 15:33
Duplicate of https://github.com/directus/directus/issues/15351

**Closed by rijkvanzanten** 2022-12-23 15:33 UTC
