### ISSUE TITLE
Impossible relationship

### ISSUE THREAD

**Issue by com-pote** [directus/directus#18368] opened 2023-04-29 09:47 UTC
### Describe the Bug

{
  "errors": [
    {
      "message": "alter table `x` modify `y` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'x' and referenced column 'id' in foreign key constraint 'x_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### To Reproduce

I think this is due to creating a relationship between a table with a UUID and one with a simple integer ID. Because an integer can't be related to a string. It's logical but it's very frustrating when you create a whole database and you probably have to redo everything from the beginning, because of this simple thing ^^

### Directus Version

V9.25.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-05-01 08:48
Was this misconfigured relation created using the app or directly in the database? The app should definitely prevent this situation from happening. 

> you probably have to redo everything from the beginning

you shouldn't have to re-do everything, recreating the relation should have the desired effect.

Closing this for now as i cannot reproduce it, happy to re-open it when more information becomes available 😄

**Closed by br41nslug** 2023-05-01 08:48 UTC

**Comment by com-pote** [comment] 2023-05-01 14:59
Yes of course I create this relation using the app. This is why I was confused. I don't know what more i can share to help. :/ but this issue prevents me to translate some fields. So this is a bit annoying.

**Comment by br41nslug** [comment] 2023-05-01 15:19
@com-pote could you share a screenshot of the failing relation configuration and the involved fields?

Like so:
![image](https://user-images.githubusercontent.com/9389634/235475419-8849c555-2d9c-4f73-908d-e74198bdbf3d.png)

The way to fix this is to remove the foreignKey that is not an ID and then re-create the relation. Unfortunately it may be possible that the app won't let you do this due to the error in which case some direct SQL queries may be required.

**Comment by com-pote** [comment] 2023-05-03 06:55
Sorry @br41nslug I had a lot of work. I Really appreciate your help and your time spending. Here's one of the relations that return this error

![Capture d’écran 2023-05-03 à 08 52 29](https://user-images.githubusercontent.com/81014220/235849487-d8239cd6-a95c-4fdb-b56c-dbe553fe0a81.png)

**Comment by br41nslug** [comment] 2023-05-03 14:08
And which side of this M2M is throwing the error? M2M's are a double relationship both sides can be treated as it's own m2o/o2m

And you say "one of the relations that is erroring", that makes me wonder if you know how to reproduce the creation of these broken relations? We can manually fix it if it's a single weird thing that happened but that doesnt help if you this keeps happening.

**Comment by com-pote** [comment] 2023-05-03 19:12
The error occurs when I try to translate, for example, the location field (actually the relationship with the city), in the designer table. This is what it tells me when I validate the translation.

![Capture d’écran 2023-05-03 à 21 08 21](https://user-images.githubusercontent.com/81014220/236019510-77dc9d58-71d5-4898-b7f0-ec91c606c153.png)

I have debugged a few tables in pure mysql with directus because of a foreign key in the past. I don't know if this will help, but if it's just that, I'll try to tell more.

**Comment by com-pote** [comment] 2023-05-11 08:50
@br41nslug  I delete the location input and recreate it with a M2O relationship with my designer and the issue remain the same... :/
