### ISSUE TITLE
Container running 9.22.4 shows 9.22.3 under Settings

### ISSUE THREAD

**Issue by adminradio** [directus/directus#17371] opened 2023-02-01 13:56 UTC
### Describe the Bug

When running Directus from latest image 9.22.4 under settings in the admin frontend version 9.22.3 is shown.

### To Reproduce

Pull image 9.22.4 and run. View settings.

directus/directus:9.22.4
directus/directus@sha256:902f30a9d3068413ba1ab65b792ce89b7a3ef23d50d34ae897c68e46acd2fa08

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by paescuj** [comment] 2023-02-01 13:59
Duplicate of #17115

**Closed by paescuj** 2023-02-01 13:59 UTC
