### ISSUE TITLE
Can't open user profile in Directus app if role field is empty 

### ISSUE THREAD

**Issue by LevelUpGit** [directus/directus#19542] opened 2023-08-29 09:34 UTC
### Describe the Bug

If for some reason we don't set role field, user can't be opened in app, it's just a blank page.

### To Reproduce

Create user without role, and open it's profile inside of directus app.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-08-29 09:41
I am unable to reproduce this by creating an user without a role. Please provide more information about your situation like any failing request or console errors when opening the page.

https://github.com/directus/directus/assets/9389634/a27a7293-3afe-4764-9d3f-ffbcfc2759c8

Closing this for now but happy to re-open when more information becomes available :)

**Closed by br41nslug** 2023-08-29 09:41 UTC
Labels: Needs More Info
