### ISSUE TITLE
All content is deleted when field is added in main data model and not translation model

### ISSUE THREAD

**Issue by ivaivasileva** [directus/directus#9461] opened 2021-11-04 12:14 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [ ] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I try to add new field in the main data model that I have created and not in the module that is for the translations, because I don't want to translate for all languages this field(it has the same value for all languages), all of my content that is added till now in the translations is deleted and I can not revert it from the history.

### To Reproduce

1. Create data model 'Homepage' with the basic fields: 
![image](https://user-images.githubusercontent.com/23214023/140309027-41087982-2676-46c9-8f78-b5c118181ca6.png)
2. Create translation for the modul from step 1 with the default  translations settings 
3. Create new field in automatically created translation model and save
4. Go to the Collection tab
5. Select 'Homepage' model
5. Add value for this field in en-US and save
6. Go to Settings -> Data model
7. Select 'Homepage'
8. Add new field from type media -> image
9. Save
10. Go to the Collection tab
11. Select 'Homepage'
12. The value for the translation of the field for en-US is missing(deleted) 

### What version of Directus are you using?

^9.0.0-rc.100

### What version of Node.js are you using?

v12.22.1

### What database are you using?

SQLite ^5.0.2

### What browser are you using?

Chrome Version 95.0.4638.54 (Official Build) (64-bit)

### What operating system are you using?

Windows 10 Pro

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-11-04 18:43
I can't reproduce this on the latest version. I believe this was addressed in https://github.com/directus/directus/pull/9324. We can reopen this if the issues still exists in 101 👍🏻

**Closed by rijkvanzanten** 2021-11-04 18:43 UTC
Labels: Bug (Potential)

**Comment by ivaivasileva** [comment] 2021-11-04 18:57
yes on the new version is fixed, thx
