### ISSUE TITLE
Reordering new uploaded multiple assets creates duplicates

### ISSUE THREAD

**Issue by flayks** [directus/directus#10565] opened 2021-12-16 21:24 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When adding one or multiple files to a multiple assets field, it creates a duplicate. Additionally, when I try to reorder the files, it creates duplicates every single time – as seen on this screencast. This is quite odd :think

https://user-images.githubusercontent.com/273716/146450702-b88674ad-a47d-43a5-9597-4f0f9ed70581.mov

### To Reproduce

Add files to a multiple assets field and try to reorder it

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL

### What browser are you using?

Brave

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

locally

**Comment by flayks** [comment] 2021-12-16 21:25
Surely linked to https://github.com/directus/directus/issues/10542

**Comment by rijkvanzanten** [comment] 2021-12-16 21:33
@flayks i believe this is a duplicate of #10542, like you already mentioned yourself 🙂

**Closed by rijkvanzanten** 2021-12-16 21:33 UTC
Labels: Bug (Potential)
