### ISSUE TITLE
Boolean default value = false is not working

### ISSUE THREAD

**Issue by mihaon** [directus/directus#23472] opened 2024-08-24 15:55 UTC
### Describe the Bug

If you try to set default value = false for Toggle field then you will get null as default value.

### To Reproduce

1. Create "Toggle" field
2. Set "false" for default value
3. Save field
4. Open field for view the result

Expected result:
Default value is false

Actual result:
Default value is null

### Directus Version

11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16 (docker image postgis/postgis:16-3.4-alpine)

**Comment by hanneskuettner** [comment] 2024-08-24 17:59
Heya, looks like this is a duplicate of https://github.com/directus/directus/issues/23379 and is being addressed in https://github.com/directus/directus/pull/23436. I'll close this issue now and encourage you to follow along in the mentioned issue/PR.

**Comment by hanneskuettner** [comment] 2024-08-24 17:59
Duplicate of #23379

**Closed by hanneskuettner** 2024-08-24 17:59 UTC
