### ISSUE TITLE
Editing a field without altering order in M2A changes sort order of all M2A items

### ISSUE THREAD

**Issue by bt-atono** [directus/directus#24215] opened 2024-12-12 22:02 UTC
### Describe the Bug

M2A field items are reordered when _edited_ even though they are NOT reordered with _drag and drop_. 

If you add/remove/modify any item in the M2A field, it overwrites the sorting. So you lose sorting and sometimes this new re-ordering is not even displayed in the admin UI.

### Reproduction steps:

1. Create a collection named `richText` (with Primary Key Type == UUID).
2. Add a text field called `heading` to `richText` collection.
3. Create a collection named `blog_posts` (with Primary Key Type == UUID).
4. Add an M2A field named `sections` to `blog_posts` collection. Add `richText` to Related Collection.
5. In `blog_posts` collection, edit `sections` field and add `sort` under Sort Field.
6. Go to Content and create a new Blog Post.
7. In our Blog Post, in the Sections field, add 3 new Rich Text items with headings (for this example, call them RT1, RT2, RT3, etc). Ensure the _first_ (aka "top") item is RT1, the second is RT2, the third is RT3 and so on. Drag-n-drop into order if necessary. Save and exit the Blog Post.
8. Use GraphQL to query `blog_post`. EG: 
```
query TestQuery {
  blog_posts {
    sections {
      sort
      item {
        ... on richText {
          id
          heading
        }
      }
    }
  }
}
```
9. Note down the `sort` values on each `sections`.
10. Also note the actual order that `sections` are returned in (ASC by sort INT): The `sections` with RT1 has `sort`=1, RT2 has `sort`=2, etc.
![pre](https://github.com/user-attachments/assets/8515809e-da38-4d14-8d00-4658d71a6676)

11. Now, open our Blog Post again. 
12. Click into our _second_ Rich Text item (eg RT2) to edit the content. Change the Heading to from RT2 to RT002. At this point, the item may reorder itself to the bottom of the list but it doesn't always (see note **). Save the Rich Text item. 
13. Save and exit the Blog Post.
14. Run the GraphQL query again. Notice that RT002 now shows up _last_ in our query and it's `sort` value is higher than the other two items. 
![post](https://github.com/user-attachments/assets/53c94ce7-26d0-4633-9de1-91371476b416)

### **Expected Results:**
Since no items were reordered via drag-n-drop, the edited item (RT002) `sort` value does not change. 

### **Actual results:**
The edited item (RT002) `sort` value changed and went from correctly being sorted as the _second_ item to incorrectly being sorted as the _last_.

** Note: In the _Admin UI_, the item sometimes visually reorders immediately, sometimes only on page refresh, and sometimes not at all. Either way, it is a bug whether the undesired re-sorting change appears immediately, after the page is refreshed or only in a query of the data.

### Directus Version

v11.3.2

### Hosting Strategy

Directus Cloud

**Comment by paescuj** [comment] 2024-12-13 07:58
Thanks for opening this issue! However this is a duplicate of an existing issue #24163, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #24163 has been fixed by #24172 which will be available with the next release.

**Closed by paescuj** 2024-12-13 07:58 UTC
