### ISSUE TITLE
Primary index key skipping numbers

### ISSUE THREAD

**Issue by veryphatic** [directus/directus#22404] opened 2024-05-06 23:09 UTC
### Describe the Bug

I have two Directus 10.10.5 instances running; each instance has a collection where I use bigint as the primary key. 

The indexes for both these collections has skipped the sequential next number for the index. For example in one collection the indexes run up to 13, then restart again at 19; in the other collection the index runs to 14, then restarts at 24.

Looking at the event logs for each create request, I can confirm no additional entries were created or deleted (my users don't have delete permissions), while the database transactions also show the same.

The sequential nature of these indexes is important to me, as part of a legal requirement for our management plan.

### To Reproduce

I can only speak about my production systems; however these are the steps:

- Create a collection where the primary key is a big int.
- Create entries within the collection
- Indexes are skipped

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-05-07 06:28
Since I'm not seeing this problem on my local instance with the SQLite driver, I've got a few clarifying questions:

- What DB vendor and version are you using?
- You're talking about two instances, are you running Directus as a cluster or are you seeing the same problems on two individual instances?
- Can you share your configuration (without sharing any secrets are API keys) to help us reproduce this issue.

**Comment by veryphatic** [comment] 2024-05-07 07:39
You're talking about two instances, are you running Directus as a cluster or are you seeing the same problems on two individual instances?

- There are two individual instances

What DB vendor and version are you using?
Can you share your configuration (without sharing any secrets are API keys) to help us reproduce this issue.

**Instance 1**

- Azure App service
- Docker image: directus:10.10.5
- Azure Database for PostgreSQL 16.2 - Flexible Server
- DB_SSL: true

**Instance 2:  air gapped network**

- Ubuntu 22.04
- Postgres 16.2
- Docker image: directus:10.10.5
- DB_SSL: false

**Comment by hanneskuettner** [comment] 2024-05-07 07:44
And just to confirm, are you pointing both instances to the same DB instance or different ones as well?

**Comment by veryphatic** [comment] 2024-05-07 07:46
Different databases (Azure PG/Ubuntu PG)

(I also added detail above)

**Comment by veryphatic** [comment] 2024-05-07 07:56
Additionally, the M2O related collection also has bigint primary key

**Comment by hanneskuettner** [comment] 2024-05-07 08:12
After looking at how the auto increment is set up in Postgres I have to tell you that this is indeed expected behavior and won't be changed. The primary key is drawn from a `SEQUENCE` object and sequences are only guaranteed to be incrementing in nature but not gap-less.

> To avoid blocking concurrent transactions that obtain numbers from the same sequence, the value obtained by nextval is not reclaimed for re-use if the calling transaction later aborts. This means that transaction aborts or database crashes can result in gaps in the sequence of assigned values. That can happen without a transaction abort, too. For example an INSERT with an ON CONFLICT clause will compute the to-be-inserted tuple, including doing any required nextval calls, before detecting any conflict that would cause it to follow the ON CONFLICT rule instead. Thus, PostgreSQL sequence objects cannot be used to obtain “gapless” sequences.[^1]

As such I'll be closing this issue. If you need a strictly gapless ID for some reason (which to me seems like a weird requirement) you could resort to populating it after the fact in a flow (you would have to account for concurrent insert yourself then).

[^1]: https://www.postgresql.org/docs/current/functions-sequence.html

**Closed by hanneskuettner** 2024-05-07 08:12 UTC
Labels: :detective: Needs More Info
