### ISSUE TITLE
SVG doesn't show preview

### ISSUE THREAD

**Issue by danieljones97** [directus/directus#2096] opened 2018-03-13 16:29 UTC
When uploading SVG's files, the preview does not display, giving the impression the file was unsuccessfully loaded, however when clicking on the image to get an enlarged preview, it shows that the image has in fact been successfully uploaded. See screenshot below.

## Version Info
  - Directus version: 1.1
  - PHP version: 5.6.0
  - MySQL version: 5.5.55
  - Web server (Apache): 5.5.1

## Expected Behavior
Preview should be shown.

## Actual Behavior
No image is shown.

## Steps to Reproduce
Add a "Single File" field to a table and try to upload an SVG file.

## Schema Dump, Logs, or Screenshots
![screen shot 2018-03-13 at 16 25 38](https://user-images.githubusercontent.com/26255529/37355485-d288ce30-26db-11e8-8a92-a97c702928eb.png)

**Comment by rijkvanzanten** [comment] 2018-03-13 17:07
Hey @danieljones97! Thanks for the heads up. This is a duplicate of issue #2062

**Closed by rijkvanzanten** 2018-03-13 17:07 UTC
