### ISSUE TITLE
Schema snapshot is not taking foreign keys into account

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#9723] opened 2021-11-11 15:10 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When applying [this schema](https://gist.github.com/NecoHorne/55f57824e68083c9baaabfce1c2eb856) it fails with the following error:
```sh
08:25:32 🚨 Invalid foreign key in field "group".
Error: Invalid foreign key in field "group".
    at foreignKeyViolation (/Users/josevarela/workspace/directus/directus/api/src/exceptions/database/dialects/postgres.ts:116:9)
    at extractError (/Users/josevarela/workspace/directus/directus/api/src/exceptions/database/dialects/postgres.ts:28:11)
    at translateDatabaseError (/Users/josevarela/workspace/directus/directus/api/src/exceptions/database/translate.ts:28:27)
    at /Users/josevarela/workspace/directus/directus/api/src/services/items.ts:141:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

And the query associated:
```
  knex:query insert into "directus_collections" ("accountability", "archive_app_filter", "archive_field", "archive_value", "collapse", "collection", "color", "display_template", "group", "hidden", "icon", "item_duplication_fields", "note", "singleton", "sort", "sort_field", "translations", "unarchive_value") values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18) returning "collection" trx242 +2ms
  knex:bindings [
  knex:bindings   'all',
  knex:bindings   true,
  knex:bindings   'status',
  knex:bindings   'archived',
  knex:bindings   'open',
  knex:bindings   'docs',
  knex:bindings   null,
  knex:bindings   '{{title}} — {{status}}',
  knex:bindings   'sections',
  knex:bindings   false,
  knex:bindings   'school',
  knex:bindings   null,
  knex:bindings   'Documentation — Articles',
  knex:bindings   false,
  knex:bindings   1,
  knex:bindings   'sort',
  knex:bindings   null,
  knex:bindings   'draft'
  knex:bindings ] trx242 +2ms
  ```

### To Reproduce

- Download the above schema
- Apply it `npx directus schema apply ./snapshot.yaml`

### What version of Directus are you using?

9.0.0 (main)

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Edge

### What operating system are you using?

macOS

### How are you deploying Directus?

Locally

**Comment by joselcvarela** [comment] 2021-11-11 15:14
From what I've found:
`group` is a foreign key in `directus_collections` for itself.
In this case it is trying to refer to `sections` which should exist on `directus_collections` but it is not there yet.

**Comment by rijkvanzanten** [comment] 2021-11-11 19:50
Ahh interesting. It's a self-referencing foreign key constraint, so it doesn't insert them in the right order 👍🏻

**Comment by joselcvarela** [comment] 2021-11-12 05:47
I do not have an idea how we can handle the insertion order. Though we could disable foreign keys while the schema is being applied. But I am not sure if all databases supports this mechanism.

**Comment by Oreilles** [comment] 2021-11-12 12:48
I don't know how they're handled currently, but when migrating you usually want to do things in this order:
* Create table structure
* Insert data
* Add primary / unique keys
* Only then, add foreign key constraints
That way you avoid most issues with unmatched relations

**Comment by cpt-n3mo** [comment] 2021-11-12 14:12
> Ahh interesting. It's a self-referencing foreign key constraint, so it doesn't insert them in the right order 👍🏻

Indeed this seems to be the problem .. as when groups are set to null and is then applied, and then the original with groups is applied every thing will go smoothly

**Comment by nxmad** [comment] 2021-11-26 14:11
I had the same problem with groups, set all to null and it has gone.
Now I have another issue:
```
create table "categories" ("id" integer not null default 'nextval(''categories_id_seq''
::regclass)', "sort" integer null default null, "user_updated" uuid null default null, "date_updated" tim
estamptz null default null, "slug" varchar(255) not null default null, "game" integer null default null,
"parent" integer null default null, "is_region" boolean not null default '0') - invalid input syntax for
type integer: "nextval('categories_id_seq'::regclass)"
```
Looks like snapshots are not working atm.

**Comment by nxmad** [comment] 2021-12-09 09:08
This issue seems dead. But problem still exists.
How to reproduce:
1) Install latest Directus
2) npx directus bootstrap
3) npx directus schema apply -y ./schema.yaml
If there are non-null groups in your schema, you will got `Invalid foreign key in field "group".` error.

**Comment by rijkvanzanten** [comment] 2021-12-09 23:20
> This issue seems dead.

How so? The last activity on it was from yesterday

**Comment by mirino83** [comment] 2021-12-15 21:16
Looks like the order of applying collection changes is alphabetical.
For example: if you create a parent collection named "Shops" and then create child collection named "Books", the collection "Books" is trying to import first but will end up in error (Invalid foreign key in field "group". In this case group is "Shops"), because the collection "Shops" is not created yet.

Would be fine if applying collection changes would take some level info into account ...

**Comment by viters** [comment] 2022-01-14 16:43
As a workaround, based on @nxmad response, you can run (example for alpine):

```
apk add yq
yq e '.collections.[].meta.group = null' schema.yml > .schema.yml
npx directus schema apply /directus/extensions/.schema.yml -y
npx directus schema apply /directus/extensions/schema.yml -y
```

**Comment by iksent** [comment] 2022-02-10 06:30
Having exactly the same problem while trying to **apply** snapshot:

`npx directus schema apply --yes ./snapshot.yaml`

Result: 

```
...
06:25:54 🚨 Failed to create collection "docs_article_docs_group"
06:25:54 🚨 Invalid foreign key in field "group". 
Error: Invalid foreign key in field "group".
    at foreignKeyViolation (/project/path/node_modules/directus/dist/exceptions/database/dialects/mysql.js:133:12)
```

**Comment by martijn-dev** [comment] 2022-02-17 13:09
I'm experiencing the same issue while using the `directus schema apply` tool: `Invalid foreign key in field "group"`.
In my case it looks like it is related to the order where in the changes are applied. This `group` foreign key is a reference for the frontend hierarchy of the collections. In my case it is creating the child collection before the parent. The `group` foreign key is pointing to the the parent collection, which does not exist yet at that moment. This is causing an error. 

This is just my observation, I'm not quite sure how to solve it. Maybe it could be solved by giving control over the order where in the migration should go. 

The "workaround" @viters is suggesting works, since it is removing all `group` foreign key relations. But this also let you loose all collection hierarchies, which is not ideal.

**Comment by viters** [comment] 2022-02-18 09:23
@martijn-dev 
> The "workaround" @viters is suggesting works, since it is removing all group foreign key relations. But this also let you loose all collection hierarchies, which is not ideal.

Nah, it does not. It applies snapshot without `group` first, and with it afterwards.

**Comment by martijn-dev** [comment] 2022-02-18 09:27
@viters You're right! I read it wrong. Didn't saw you're still applying the "original" schema as well.

**Comment by PeeraJ** [comment] 2022-03-07 04:50
@rijkvanzanten seems like this issue still occurs to us. if you don't mind I might as well create a PR to fix it.

**Comment by fadlee** [comment] 2022-03-22 07:38
I have the same issue. Hope the fix will be released soon..

**Closed** 2022-05-09 20:49 UTC
Labels: Bug, Package: schema
