### ISSUE TITLE
Unable to build @directus/shared

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#8492] opened 2021-10-01 14:23 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Fresh clone of main repo.

`npm install`
`npm run build`

> > @directus/shared@9.0.0-rc.95 build:cjs
> > tsc --project ./tsconfig.json --module CommonJS --outDir ./dist/cjs
> 
> src/composables/use-items.ts(195,37): error TS2339: Property 'data' does not exist on type 'never'.
> src/composables/use-items.ts(215,36): error TS2339: Property 'data' does not exist on type 'never'.
> src/composables/use-items.ts(244,36): error TS2339: Property 'meta' does not exist on type 'never'.
> src/composables/use-items.ts(245,35): error TS2339: Property 'meta' does not exist on type 'never'.

Something failed after the [Filter interface PR](https://github.com/directus/directus/commit/4fd9f4c31c1ec3cf1789d55365bb4ad1a51ac170) ?

https://github.com/directus/directus/blob/main/packages/shared/src/composables/use-items.ts

### To Reproduce

See above.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

16

### What database are you using?

PG 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally / main repo clone

**Comment by rijkvanzanten** [comment] 2021-10-01 15:12
Not seeing any issues on my end 🤔 

<img width="601" alt="CleanShot 2021-10-01 at 11 10 24@2x" src="https://user-images.githubusercontent.com/9141017/135644339-76252b10-0edb-4716-b55d-0caabf049d74.png">

Also, all the CI's seem to build just fine as well, so I think we'll have to look for the cause on your local machine. 

Can you try removing all node modules recursively using `npx lerna clean -y`, removing the root node_modules, and running `npm install` in the root?

I'll close this for now as it's seems like it's not something in the repo itself we can fix at this point :

**Comment by rijkvanzanten** [comment] 2021-10-01 15:43
Scratch that! Turns out axios' update that just went out causes this to break. Just noticed PR #8483 that bumps that version breaks the run in the same way: https://github.com/directus/directus/pull/8483/checks?check_run_id=3765358650

**Closed** 2021-10-01 16:41 UTC
Labels: API, Bug
