### ISSUE TITLE
Upload File failed

### ISSUE THREAD

**Issue by miauyo** [directus/directus#23659] opened 2024-09-13 03:35 UTC
### Describe the Bug

[FAILED_VALIDATION] Validation failed for field "uploaded_on". Value is required.

### To Reproduce

When I upload a file
![image](https://github.com/user-attachments/assets/c2283c33-98ed-49df-acda-eb79d06df850)

### Directus Version

11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql8

**Comment by paescuj** [comment] 2024-09-13 09:17
I think that is a result of the failing migration in #23647, as the `uploaded_on` field is now missing.

You can either try to manually create the missing table column in your database

```sql
alter table directus_files add uploaded_on timestamp
```

or you could also run the migration again [^1]
```shell
# Create a database backup first!

# Repeat until the "Update files date fields" migration has been undone
npx directus database migrate:down

# Then repeat until all outstanding migrations have been applied again
npx directus database migrate:up
```

As I assume that this is the cause, I'll close this issue for now. Happy to keep discussing in this thread, and we'll reopen if it turns out to be a different problem 👍🏻

[^1]: https://docs.directus.io/self-hosted/upgrades-migrations.html#downgrading-a-project

**Closed by paescuj** 2024-09-13 09:17 UTC

**Comment by HemboPagi** [comment] 2024-09-30 12:48
i have the  _uploaded_on_ field present, but still getting this error

**Comment by mvillamizar74** [comment] 2024-10-11 06:01
Hi, I have just installed Directus 11.1.1 on MariaDB, it has field uploaded_on present, but I am getting the same error

**Comment by AKhateeb** [comment] 2024-10-11 17:17
Me too same error, anyone can help us resolving the issue :(

**Comment by paescuj** [comment] 2024-10-11 19:25
We couldn't reproduce this so far. In order for us to be able to help, we need a reproducible setup. Thanks!

---

The `compose.yaml` file used when trying to reproduce the issue:
```yaml
services:
  database:
    image: mariadb:11.5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "directus"
      MYSQL_PASSWORD: "directus"
      MYSQL_DATABASE: "directus"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s

  directus:
    image: directus/directus:11.1.1
    ports:
      - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
    depends_on:
      database:
        condition: service_healthy
    environment:
      SECRET: "replace-with-secure-random-value"

      DB_CLIENT: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"

      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
```

**Comment by mvillamizar74** [comment] 2024-10-11 22:12
I have 2 VM, one for Directus, and the second one for the db.

DB Server Info
DB type: MariaDB
Server connection: SSL is not being used
Server version: 10.6.18-MariaDB-cll-lve
Protocol version: 10
Collocation: latin1_swedish_ci

Directus Server Info
Ubuntu 22.04 lts, 1vCPU, 2GB RAM, 10GB SSD
Node 18.20.4
Directus 11.1.1

Directus was installed using npm on /home/usr/local/directus, the installation process went smoothly, no complications whatso ever, connection with db - OK, after I started to work on initial configuration, I noticed that I could not load images (small files 250k - 350k), so I try to chmod the upload folder to 775, but did not fix the problem, then I came around this case thread, I double check the uploaded_on field on directus_files table, and the field is present.

I really appreciate your help

**Comment by mvillamizar74** [comment] 2024-10-14 18:09
On [issue 23266](https://github.com/directus/directus/issues/23266) shows how to solve the issue, manually changing the default value for column uploaded_on; from 0000-00-00 00:00:00 -> current_timestamp(), I hope this may help. Happy coding!

**Comment by cesarkmelo** [comment] 2024-11-02 19:27
Can confirm the fix works. Thanks @mvillamizar74
