### ISSUE TITLE
"Unexpected error" incompatible foreign key constraint in translations

### ISSUE THREAD

**Issue by Mrmiffo** [directus/directus#6073] opened 2021-06-04 09:53 UTC
**The issue and what you expected to happen**
When running `npx directus bootstrap` after updating from rc69->rc71 we received an unknown internal server error for numerous relations, in particular to directus_files and languages relations. 

The same error can be recreated by trying to create a new translations field after the migration. The translations field appears to be successfully created, however, after dismissing the error, pressing cancel in the create translations dialog and refreshing the browser. But on closer inspection of the edit details page of the collection, the translations interface is not working (not showing any buttons to edit the translations).

![image](https://user-images.githubusercontent.com/8545443/120781814-b7a05080-c529-11eb-8531-3e51462b168a.png)
![image](https://user-images.githubusercontent.com/8545443/120781934-cf77d480-c529-11eb-9388-844c96e163ca.png)

From errors in the CMD it appears to be related to the MySQL 8 DB in use.

App Error:
```
{
  "errors": [
    {
      "message": "alter table `test_translations` add constraint `test_translations_languages_code_foreign` foreign key (`languages_code`) references `languages` (`code`) on delete SET NULL - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'languages_code' and referenced column 'code' in foreign key constraint 'test_translations_languages_code_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

CMD Error and stacktrace:
```
11:23:30 Ô£¿ request completed POST 200 /fields/test 80ms
11:23:30 ÔÜá´©Å  Transaction was implicitly committed, do not mix transactions and DDL with MySQL (#805)
11:23:31 ÔÜá´©Å  Transaction was implicitly committed, do not mix transactions and DDL with MySQL (#805)
11:23:31 ÔÜá´©Å  Transaction was implicitly committed, do not mix transactions and DDL with MySQL (#805)
11:23:31 Ô£¿ request completed POST 200 /collections 138ms
11:23:31 ÔÜá´©Å  Transaction was implicitly committed, do not mix transactions and DDL with MySQL (#805)
11:23:31 Ô£¿ request completed POST 200 /fields/test_translations 151ms
11:23:31 ÔÜá´©Å  Transaction was implicitly committed, do not mix transactions and DDL with MySQL (#805)
11:23:31 Ô£¿ request completed POST 200 /fields/test_translations 163ms
11:23:31 ­ƒÜ¿ alter table `test_translations` add constraint `test_translations_languages_code_foreign` foreign key (`languages_code`) references `languages` (`code`) on delete SET NULL - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'languages_code' and referenced column 'code' in foreign key constraint 'test_translations_languages_code_foreign' are incompatible. 
Error: UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'languages_code' and referenced column 'code' in foreign key constraint 'test_translations_languages_code_foreign' are incompatible.
    at Query.Sequence._packetToError (D:\oobcms-v9\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (D:\oobcms-v9\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (D:\oobcms-v9\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\oobcms-v9\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\oobcms-v9\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\oobcms-v9\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\oobcms-v9\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\oobcms-v9\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    --------------------
    at Protocol._enqueue (D:\oobcms-v9\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\oobcms-v9\node_modules\mysql\lib\Connection.js:198:25)
    at D:\oobcms-v9\node_modules\knex\lib\dialects\mysql\index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (D:\oobcms-v9\node_modules\knex\lib\dialects\mysql\index.js:120:12)
    at executeQuery (D:\oobcms-v9\node_modules\knex\lib\execution\internal\query-executioner.js:37:17)
    at Client_MySQL.query (D:\oobcms-v9\node_modules\knex\lib\client.js:134:12)
    at D:\oobcms-v9\node_modules\knex\lib\execution\transaction.js:363:24
    at new Promise (<anonymous>)
    at Client_MySQL.trxClient.query (D:\oobcms-v9\node_modules\knex\lib\execution\transaction.js:358:12)
11:23:31 Ô£¿ request errored POST 500 /relations 230ms
```

**Exact steps to reproduce this issue**
In an environment updated from <= rc69 -> rc71:
1. Update the application by updating the .env file and run `npx directus bootstrap` (errors will be displayed in the log for existing translations fields)
2. Create a new collection
3. Add a string input field called name
4. Add a translations field with Auto-Generate. The error is displayed

**Your environment:**
rc71 updated from rc69
MySQL 8
npx
Chrome

**Any other relevant information we might need to reproduce this issue**
Can't provide a DB dump as I can't recreate the exact same issue in a clean environment (see issue https://github.com/directus/directus/issues/6070)

**Comment by rijkvanzanten** [comment] 2021-06-04 16:15
I think this is a duplicate of https://github.com/directus/directus/issues/5999. Could you confirm the issue still exists on 72+ ?

**Closed by rijkvanzanten** 2021-06-04 16:15 UTC
