### ISSUE TITLE
Filter - is empty / isn´t empty for datetime error

### ISSUE THREAD

**Issue by nordcart** [directus/directus#4023] opened 2021-02-12 10:50 UTC
Filtering **empty**/**isn´t empty** for datetime-fields in presets/bookmarks/collections results in error. 

This happens when some datetime-fields are empty.

This happens with postgresql databases. MySQL works fine.

---

### Project details
Directus Version: 9.0.0-rc.36
Environment: production
OS: Linux 5.4.72-microsoft-standard-WSL2
Node: 14.15.5

**Comment by rijkvanzanten** [comment] 2021-02-12 14:53
Duplicate of https://github.com/directus/directus/issues/3747

**Closed by rijkvanzanten** 2021-02-12 14:53 UTC
Labels: App, Bug, DB: Postgres
