### ISSUE TITLE
Add directus-collections to CRUD flow operations

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#14187] opened 2022-06-29 15:15 UTC
### Describe the Bug

In the directus flow operations we can't select directus collections. 
Especially the files collection should be available in order to delete unneeded files (e.g delete all files in a folder that are older that 30 days).

I think users could be added too, but there's probably to much stuff that needs to be validated before in order to prevent unwanted side-effects.

### To Reproduce

![Bildschirmfoto 2022-06-29 um 17 14 29](https://user-images.githubusercontent.com/46492597/176472663-611091fa-0ed4-4657-bd37-c74423709de3.png)

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

/ (directusCloud)

### What database are you using?

SQLite (directus Cloud)

### What browser are you using?

Chrome

### How are you deploying Directus?

directus Cloud

**Comment by azrikahar** [comment] 2022-06-29 15:18
Duplicate of #13858 https://github.com/directus/directus/discussions/13716#discussioncomment-2880520

**Closed by azrikahar** 2022-06-29 15:18 UTC
