### ISSUE TITLE
Invalid Postgresql JSONB -> JSON cast

### ISSUE THREAD

**Issue by hiendaovinh** [directus/directus#18527] opened 2023-05-09 12:37 UTC
### Describe the Bug

Hi,
I have a column in jsonb with a gin index with it. I want to use Repeater `list` interface with it but every time I update repeater fields, it gives me an error
```
{
  "errors": [
    {
      "message": "alter table \"foo\" alter column \"bar\" type json using (\"bar\"::json) - data type json has no default operator class for access method \"gin\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

I think the problem here is Directus was trying to update my schema from jsonb to json which is total unnecessary and invalid. 

### To Reproduce

1. Use Postgresql
2. Create a table with a jsonb column and give it an index using GIN
3. Try to set up repeater interface for the column
4. Directus throwing errors

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hiendaovinh** [comment] 2023-05-11 10:32
Can we have an option to skip schema update?

**Comment by br41nslug** [comment] 2023-05-16 11:55
I can confirm this is happening for v10.0.0
However this issue seems to have been fixed on the `main` branch since then.

**Comment by br41nslug** [comment] 2023-05-16 12:08
After some testing this issue has been solved by https://github.com/directus/directus/pull/18579

**Closed by br41nslug** 2023-05-16 12:08 UTC
Labels: API, Bug
