### ISSUE TITLE
Unable to create a repeater field

### ISSUE THREAD

**Issue by nitruoc** [directus/directus#11487] opened 2022-02-07 17:44 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I can't add any subfield to a repeater field. If I try, Directus crash and I've get an error message in console.

### To Reproduce

1. Create a repeater field in a collection and save it
2. Trying to create a subfield inside it

### Errors Shown

```javascript
TypeError: e.value is null
    D http://localhost:8055/admin/assets/index.7af4eb85.entry.js:257
    g http://localhost:8055/admin/assets/index.7af4eb85.entry.js:257
    2 http://localhost:8055/admin/assets/index.7af4eb85.entry.js:257
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    cB http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    _ http://localhost:8055/admin/assets/index.7af4eb85.entry.js:43
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    r http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    Od http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    tV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    aV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    WE http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    promise callback*UE http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    T9 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    ot http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    F7 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    b5 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    effect http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    F7 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    b5 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    set value http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    P http://localhost:8055/admin/assets/index.7af4eb85.entry.js:257
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    cB http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    _ http://localhost:8055/admin/assets/index.7af4eb85.entry.js:43
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    r http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    Od http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    tV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    aV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
vendor.62e5a05d.js:5:1162
    wH http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    _0 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    cB http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    _ http://localhost:8055/admin/assets/index.7af4eb85.entry.js:43
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    r http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    (Asynchrone : EventListener.handleEvent)
    Od http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    tV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    aV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Re http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    WE http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    (Asynchrone : promise callback)
    UE http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    T9 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    ot http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    F7 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    b5 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    effect http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    F7 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    b5 http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    set value http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    P http://localhost:8055/admin/assets/index.7af4eb85.entry.js:257
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    cB http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    _ http://localhost:8055/admin/assets/index.7af4eb85.entry.js:43
    Nh http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    $1 http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    r http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    (Asynchrone : EventListener.handleEvent)
    Od http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    tV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    aV http://localhost:8055/admin/assets/vendor.62e5a05d.js:5
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    K http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    dt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    run http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    wt http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Xe http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Ye http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    M http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    ie http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
    Q http://localhost:8055/admin/assets/vendor.62e5a05d.js:2
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

MariaDB 10.4.10

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Locally

**Comment by jformela** [comment] 2022-02-07 19:26
Same here.
Can't either close or save form while adding a field into repeater.

**Comment by azrikahar** [comment] 2022-02-07 22:45
Duplicate of #11447, with an open PR #11453 👍

**Closed by azrikahar** 2022-02-07 22:45 UTC
Labels: Bug (Potential)
