### ISSUE TITLE
Can't move fields - Safari

### ISSUE THREAD

**Issue by Hinkolas** [directus/directus#20751] opened 2023-12-14 19:37 UTC
### Describe the Bug

When editing a data model in the settings tab you should be able to drag and drop the fields to change the order.

This works all fine in Chrome, but when using Safari it won't work.

https://github.com/directus/directus/assets/90035653/30671cc9-a89b-4552-bb1d-eda70262aff6

https://github.com/directus/directus/assets/90035653/00b7cac1-afd8-4d03-96b0-5e45ac34e337

### To Reproduce

**Safari versions:** 17.1.2 / 17.1
**MacOS versions:** 14.2 / 14.0

**Steps to reproduce:**
- Create a data model
- Create multiple fields
- Try moving them

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-12-15 02:14
Thanks for opening this issue! However this is a duplicate of an existing issue #20349, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #20349 for future updates.

**Closed by paescuj** 2023-12-15 02:14 UTC
