### ISSUE TITLE
Policies migration breaks public permissions

### ISSUE THREAD

**Issue by zentek-cintia-dewi** [directus/directus#23262] opened 2024-08-09 07:46 UTC
### Describe the Bug

**I'm not sure if i should call it a bug or a sloppy work.** 
After Directus Cloud "Access Control" has changed into "Access Policies", all of my current public access for many collection were ruined. It's causing error 404 on my company's production site!
I think what you were trying to do was to restore all of my public access records, but it was not done correctly. I had to spend some hours to review every single collection's public access and reassign the custom read access one by one. That's not good, Directus Team! 
I don't know if other Directus Cloud customers are also affected by this, if yes i hope the damage was not that serious.
Thanks

### To Reproduce

can't reproduce since the issue was fixed immediately in our directus cloud

### Directus Version

v11.0.1

### Hosting Strategy

Directus Cloud

**Comment by hanneskuettner** [comment] 2024-08-09 08:08
First of all, sorry to hear this impacted you! 

Can you reach out to our Support team through support@directus.io so we can figure out what went wrong when applying the migrations to the new policies based permissions.

I know this obviously should not have happened and won't help you in your situation now, but can you recall what had to be changed on your end in order to resolve the public permissions? This might us help remedy similar situations for other users of Directus.

**Comment by zentek-cintia-dewi** [comment] 2024-08-09 08:18
Hi, 

thank you for the prompt response. 
We had to review and reapply every single collection's read permission for the public role, since we're using custom read access for our collections fields. 

I haven't checked if other roles beside public are also affected. My team is currently reviewing them again.

**Comment by hanneskuettner** [comment] 2024-08-09 08:21
That sounds super weird, since the policy migrations have been tested extensively and are relatively straight forward as far as the actual permission migration is concerned. If you reach out to support we can have a detailed look at the exact migrations that happened in your case and we will try to understand what impacted your project, as it seems to be the only one impacted so far from a failed migration on the public permissions.

**Comment by hanneskuettner** [comment] 2024-08-09 08:22
If you don't mind I will be closing this issue now, as we don't have any reproduction steps at this point. But be assured we are looking into it as soon as you reach out and might reopen this issue once we have more information at our hands.

**Comment by zentek-cintia-dewi** [comment] 2024-08-09 08:22
Thank you i'll reach out the support asap.

**Closed by hanneskuettner** 2024-08-09 08:22 UTC
