### ISSUE TITLE
[INVALID_PAYLOAD] Alias type cannot be changed

### ISSUE THREAD

**Issue by andrii-bodnar** [directus/directus#16410] opened 2022-11-11 08:52 UTC
### Describe the Bug

Can't add new links to the component "Button Links", an error occurred

### To Reproduce

- Add the "Button Links" component to a collection.
- Add some links and save.
- Click "Edit field".
- Click "Interface".
- Click "Create New".
- Fill in values and save.
- Click save.
- See error.

Video:

https://user-images.githubusercontent.com/29282228/201302073-b2c47696-b1c1-45eb-971f-a4da0bb42a5c.mov

### Errors Shown

`{"errors":[{"message":"Alias type cannot be changed","extensions":{"code":"INVALID_PAYLOAD"}}]}`

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment] 2022-11-11 09:12
Duplicate of #16315

**Closed** 2022-11-11 09:12 UTC
Labels: Duplicate
