### ISSUE TITLE
M2M Handling in GraphQL is not 1:1 with API

### ISSUE THREAD

**Issue by verystack** [directus/directus#15451] opened 2022-09-07 12:57 UTC
### Describe the Bug

![2022-09-07 22_48_14-Post - Opera](https://user-images.githubusercontent.com/59302430/188882768-ff6e3c31-9b12-41a9-8855-f99b7d2dd967.png)

With the Rest API you can do this to update an M2M field with new ID values.

There is no equivalent in GraphQL when working with the parent 'document'.  You can create New 'linked' M2M items, but not link existing. The only way this seems to be possible is to directly create the 'Functional' linking document and then update the original document with this new ID.

### To Reproduce

-

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

-

### How are you deploying Directus?

Cloud

**Comment by azrikahar** [comment] 2022-09-08 04:15
Closing as duplicate of #7237

**Closed by azrikahar** 2022-09-08 04:15 UTC
