### ISSUE TITLE
Upgrade from 10.13.0 to 11.1.0 breaks access control (HTTP error! status: 403. Forbidden)

### ISSUE THREAD

**Issue by shi-rudo** [directus/directus#23610] opened 2024-09-09 08:02 UTC
### Describe the Bug

after upgrading to the latest version from directus/directus:10.13.0 to directus/directus:11.1.0, many of our queries are no longer possible. 
the api user is using the admin role. 

example error: 

```json
{
  "errors": [
    {
      "message": "You don't have permission to access field \"\" in collection \"directus_folders\" or it does not exist. Queried in \"folder\".",
      "extensions": {
        "reason": "You don't have permission to access field \"\" in collection \"directus_folders\" or it does not exist. Queried in \"folder\".",
        "code": "FORBIDDEN"
      }
    }
  ]
}

{
  "errors": [
    {
      "message": "You don't have permission to access field \"languages_code*\" in collection \"languages\" or it does not exist. Queried in \"article.translations.languages_code\".",
      "extensions": {
        "reason": "You don't have permission to access field \"languages_code*\" in collection \"languages\" or it does not exist. Queried in \"article.translations.languages_code\".",
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

migrations did run successfully:
2024-09-09 09:21:26 [07:21:26.934] INFO: Running migrations...
2024-09-09 09:21:26 [07:21:26.956] INFO: Applying Update Files Date Fields...
2024-09-09 09:21:27 [07:21:27.123] INFO: Applying Permissions Policies...
2024-09-09 09:21:28 [07:21:28.249] INFO: Applying Update Icon Fields Length...
2024-09-09 09:21:28 [07:21:28.349] INFO: Done

### To Reproduce

unfortunately not possible, as it is an internal system.

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by paescuj** [comment] 2024-09-10 09:32
Could you still provide a little more information? Would be helpful to know the data model and the associated permissions as well as the corresponding API queries, of course with the sensitive data redacted. Without that, it might be hard for us to reproduce the issue. Thank you!

**Comment by shi-rudo** [comment] 2024-09-10 10:27
this is one of the failing queries

```text
http://127.0.0.1:8883/items/recipe?access_token=__ADMIN_TOKEN__
&limit=-1
&filter%5Bstatus%5D%5B_eq%5D=published
&fields%5B%5D=*%2Carticle.*
&fields%5B%5D=*%2Carticle.translations.*
&fields%5B%5D=*%2Carticle.translations.languages_code.*
&fields%5B%5D=*%2Carticle.translations.languages_code.languages_code*
&fields%5B%5D=*%2Carticle.sources.sources_id.*
&fields%5B%5D=*%2Carticle.sources.sources_id.published_language.*
&sort%5B%5D=-date_created
```

fails with
```text
{
  "errors": [
    {
      "message": "You don't have permission to access field \"languages_code*\" in collection \"languages\" or it does not exist. Queried in \"article.translations.languages_code\".",
      "extensions": {
        "reason": "You don't have permission to access field \"languages_code*\" in collection \"languages\" or it does not exist. Queried in \"article.translations.languages_code\".",
        "code": "FORBIDDEN"
      }
    }
  ]
}
```

query example: 2
```text
 http://127.0.0.1:8883/files?access_token=__ADMIN_TOKEN__
 &limit=-1
 &fields%5B%5D=*.*
 &fields%5B%5D=*.%2Ctranslations.*
 &fields%5B%5D=*.%2Ctranslations.languages_code.*
 &filter%5Bid%5D%5B_eq%5D=__UNIQUE_ID__
```

response
```text
{
  "errors": [
    {
      "message": "You don't have permission to access field \"\" in collection \"directus_folders\" or it does not exist. Queried in \"folder\".",
      "extensions": {
        "reason": "You don't have permission to access field \"\" in collection \"directus_folders\" or it does not exist. Queried in \"folder\".",
        "code": "FORBIDDEN"
      }
    }
  ]
}
```


**information**:
* the field "languages_code" does exist on the data model (M2One to languages.code)
* every query with the languages_code relationship does fail
* if I downgrade to 10.13 the queries run without error. 

I'd be happy to give you more info if you let me know which one

**Comment by Dominic-Marcelino** [comment] 2024-09-10 14:39
Do you have an access filter on the relation? If so this could be related to #23526

**Comment by hanneskuettner** [comment] 2024-09-13 11:52
So, at least for the first example, I can tell you that it breaks because there is no field literally called `languages_code*` in `article.translations.languages_code`. Field wildcards are only allowed for full field names and not as a part of a field name. This check was less strict in v10 and is more strict now. Depending and what you're trying to achieve with that part of the query you could update it to e.g. `article.translations.languages_code.languages_code`. Though I don't know your expected result is.

For the second one I will try to reproduce it locally.

**Comment by david-plugge** [comment] 2024-09-13 13:10
Im also running into a weird issue. If i request a single item by id, i get back a 403 if the item does not exist. Shouldnt it result in a 404 instead?

**Comment by hanneskuettner** [comment] 2024-09-13 13:15
> Im also running into a weird issue. If i request a single item by id, i get back a 403 if the item does not exist. Shouldnt it result in a 404 instead?

403 is the expected response in order to not have different responses for items that don't exist vs the user does not have permission to. This is a security measure to avoid leaking any information the user is not entitled to.

**Comment by david-plugge** [comment] 2024-09-13 14:13
Alright, i though i did something wrong. Is this behaviour mentioned somewhere in the docs?

**Comment by hanneskuettner** [comment] 2024-09-13 14:14
Yes, see the info box in this section (under the table) https://docs.directus.io/reference/introduction.html#error-codes

**Comment by hanneskuettner** [comment] 2024-09-13 14:30
Ah! Good catch on the second one. I would not expect `*.,translations.*` to work, as that would resolve to `<any-field>.`, so an empty field at the end of you field query. Similarly you would not expect `folder.` to be a valid field key. 

I'm closing this, as it seems to have been incorrectly crafted queries, that are now correctly identified when checking for field existence.

**Closed by hanneskuettner** 2024-09-13 14:30 UTC
Labels: Bug
