### ISSUE TITLE
Error window appears under the deletion window

### ISSUE THREAD

**Issue by MarkoMestrovicShape** [directus/directus#9232] opened 2021-10-29 13:07 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When deleting an item from collection that is in One to Many relationship, the error message (Something can't wrong because deleting violates foreign key constraint) that it can't be deleted appears under the delete window.

### To Reproduce

Create Many to One relationship (one to many). Create connected items. Try to remove an item from the "One" side of the relationship.

### Errors Shown

[INTERNAL_SERVER_ERROR] delete from "one_collection" where "id" in ($1) - update or delete on table "one_collection" violates foreign key constraint "many_one_collection_foreign" on table "many". The one that appears under the delete message.
![deletebug](https://user-images.githubusercontent.com/92448298/139440053-ef3fc7fc-8e81-432b-85a4-f6d20a0bf0c1.png)
 

### What version of Directus are you using?

v9.0.0-rc.98

### What version of Node.js are you using?

v14.5.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-10-31 06:43
In case updating Directus (as the comment above suggested) didn't work, would you mind to test this in other browsers or even other devices if possible? 

---

Side note for potential fix: we may need to simply close the delete dialog when `unexpectedError` opens another dialog, which was what #8825 did. Which means adding `confirmDelete.value = false;` inside the catch block here:

https://github.com/directus/directus/blob/ded3d4b1412a4da711dfaa31e72a4fd4e7e31acc/app/src/modules/collections/routes/item.vue#L478-L486

This doesn't technically fix the "z-index" of the dialogs here (which is still weird since the delete dialog is higher up in the DOM), but probably still makes more sense in error-dialogs-flow perspective.

**Comment by MarkoMestrovicShape** [comment] 2021-11-02 10:01
I've now tested it on version 100, and I've tried to run it on both Firefox and Microsoft Edge and the window still appears under the deletion window.

**Comment by licitdev** [comment] 2021-11-16 12:14
@MarkoMestrovicShape I am unable to reproduce the issue from the latest release (v9.0.0+).

https://user-images.githubusercontent.com/26413686/141982783-2af14d76-ea91-4f00-b059-608ba2465b76.mov

**Comment by rijkvanzanten** [comment] 2021-12-03 00:52
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-12-03 00:52 UTC
Labels: Needs More Info
