### ISSUE TITLE
Deleting files loads the system

### ISSUE THREAD

**Issue by Enhed** [directus/directus#14528] opened 2022-07-20 13:37 UTC
### Describe the Bug

I have 1M+ files in local storage. It's mostly small pictures
![image](https://user-images.githubusercontent.com/36981278/179995411-f4036154-65c6-4ffe-9c22-268e9b3b22c1.png)  

when i execute deleting any one file i have load process:  
![image](https://user-images.githubusercontent.com/36981278/179995642-2b0674ba-03e6-497a-8f39-7f2e96cb8504.png)  
if i will try delete more than 1 file, load value cpu can be more than 2000%+

### To Reproduce

create 1M files and try to delete one/many files

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 12

### What browser are you using?

chrome

### How are you deploying Directus?

manual in docker

**Comment by azrikahar** [comment] 2022-07-20 13:43
Duplicate of #12248. This comment should help shed more light on what's happening: https://github.com/directus/directus/issues/12248#issuecomment-1074069150. This enhancement is currently discussed in #13559, so feel free to upvote and share your thoughts on the potential solutions discussed there as well. 👍

**Closed by azrikahar** 2022-07-20 13:43 UTC
