### ISSUE TITLE
App: M2A fields do not show on Item Duplication fields section

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#21242] opened 2024-01-29 22:25 UTC
### Describe the Bug

As title suggest, M2A fields do not appear on Item Duplication fields.
Although they are always included.
This causes this issue https://github.com/directus/directus/issues/21229 because I am not able to select what fields from M2A relationship I need.

### To Reproduce

Create A, B, C, D collections
Create M2A field on A and choose B, C, D as Related Collections.
Go to Item Duplication Fields and you will see that M2A field does not appear on the list.

### Directus Version

main (10.8.3)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment] 2024-04-17 14:15
I'm unable to reproduce this issue in version 10.10.5.

After creating said collection, adding the M2A field and refreshing the page I can see the M2A field in the Duplication section.

![Image](https://github.com/directus/directus/assets/4376726/34026f7c-7f5c-46ce-b38c-2df819fd1442)

I'm gonna close this issue, but feel free to re-raise this if it is still present on your end.

**Closed by hanneskuettner** 2024-04-17 14:15 UTC
Labels: :cake: Bug, :warning: Enterprise
