### ISSUE TITLE
Flow. Read Data. Paid plan doesn't work

### ISSUE THREAD

**Issue by modagavr** [directus/directus#16425] opened 2022-11-12 14:38 UTC
### Describe the Bug

cloud + free plan:
flow -> webhook -> read item. IDS = {{$trigger.query.toolId}}
works fine, url is ~/flows/trigger/[id]?toolId=abc

the same setup for cloud + paid plan:
doesn't work as it should, delays every call and shows toolId parameter from the last call, not current call 

### To Reproduce

flow -> webhook -> read item. IDS = {{$trigger.query.toolId}}

### What version of Directus are you using?

Cloud Standard 9.20.4

### What version of Node.js are you using?

Cloud Standard 

### What database are you using?

Cloud Standard (postgres i think)

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud Standard

**Comment by rijkvanzanten** [comment] 2022-11-14 18:09
The free and paid plan run the same version of Directus, so there shouldn't be any discrepancies there. Are you sure the two flows are configured identically?

Based on the information given, we're not able to reproduce this in the core of Directus, so I'll close this for now. Feel free to reach out to Cloud support through the chat on the Cloud Dashboard so the team can take a look at any problems caused by the setup 🙂

**Closed by rijkvanzanten** 2022-11-14 18:09 UTC
Labels: API, Bug (Potential)

**Comment by modagavr** [comment] 2022-11-15 04:04
I'm sure both flows are identical

To rule out the possibility of a mismatch, I deleted and re-created on different plans (community and standard)

My goal is to read one item from the collection and I use the query  `FLOW_URL?TOOL_ID=HELLO`

And I read it inside `{{$trigger.query.TOOL_ID}}`

Community – shows the item properly
Standard – shows the item with TOOL_ID from randomly chosen of the previous calls (3 calls ago for example)
