### ISSUE TITLE
Deleting a "JSON" field sets it to "Database Only" instead of actually deleting it

### ISSUE THREAD

**Issue by AaronBeaudoin** [directus/directus#17224] opened 2023-01-18 18:02 UTC
### Describe the Bug

I have a JSON field called `features_2`. I click "Delete Field" to remove it from the collection, therefore the column should be removed from the database table.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/26592486/213257514-bcf27982-655d-4baa-bab2-604c321c882a.png">

After clicking "Delete Field", the field disappears from the list. However, if I refresh the page, it has come back, but as "Database Only"! If I click "Delete Field" again, the same thing happens.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/26592486/213257894-d5bac879-3134-47e9-883c-92d2ec5f90a3.png">

### To Reproduce

1. Create a JSON field.
2. Now try to remove it.

### Errors Shown

N/A

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

Directus 9.22.4 Docker Image Node Version

### What database are you using?

Postgres 10.21

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2023-01-18 19:27
Unrelated question out of curiosity: why Postgres 10 instead of current LTS? Is there a third party DB provider that limits it to the older version?

**Comment by AaronBeaudoin** [comment] 2023-01-18 21:12
The Postgres instance is host to two databases, one for Directus, and one for any existing system we had already been using it for previously.

**Comment by marianhlavac** [comment] 2023-01-19 11:30
This doesn't seem to be limited to JSON fields only. While I was trying to create O2M field, it failed and is now displayed as  'database only'. Re-creating and deleting the fields doesn't help. Logs show absolutely nothing.

https://user-images.githubusercontent.com/3010503/213431151-e1589012-8557-48ca-8cd9-f55adf219aaa.mp4

**Comment by rijkvanzanten** [comment] 2023-01-19 15:36
@marianhlavac Postgres 10 as well?

**Comment by marianhlavac** [comment] 2023-01-19 15:38
@rijkvanzanten 13.7 actually

**Comment by paescuj** [comment] 2023-01-19 16:28
Hey @AaronBeaudoin I haven't been able to reproduce this yet. I've tested it with different version of Postgres (v10-v15).
Have you configured the field in a special way that differs from the default values?

**Comment by paescuj** [comment] 2023-01-19 16:40
@marianhlavac Hard to reproduce as well. Do you remember why the creation of the M2O field failed? Have you looked into both the browser and Directus log when trying to delete the field?

**Comment by marianhlavac** [comment] 2023-01-20 08:15
@paescuj Yes, I do, I was yesterday originally planning to open a new issue, as it doesn't seem too much relevant to this issue, but this might help. I'd eventually post the same video to the separate issue:

`[INVALID_PAYLOAD] Field "language" doesn't exist in collection "news_posts"`

https://user-images.githubusercontent.com/3010503/213647674-5ab130e7-2bba-45cc-950c-ec5bc7985264.mp4

The language collection is the default collection created by Directus when I started using translations.

I had to resort to creating the table in db manually and then configuring a collection (thank god Directus was designed this way), but it's inconvenient either way.

**Comment by paescuj** [comment] 2023-01-20 09:46
@marianhlavac Thanks for the explanation!

> I had to resort to creating the table in db manually and then configuring a collection (thank god Directus was designed this way), which worked, but it's inconvenient either way.

Do you mean the `language` or `news_posts` collection? Why was that necessary?

I'm still not able to reproduce this issue. Are you running Directus via Docker (with or without redis cache)? Any special configurations?

**Comment by marianhlavac** [comment] 2023-01-20 09:49
> Do you mean the language or news_posts collection? Why was that necessary?

@paescuj Sorry, I meant "field", not "table", my bad. Created the foreign key in the news_posts manually and then configured in the collection, which worked. But was unable to create the relation using Directus.

> Would you also be able to take a glance at the logs of PostgreSQL while trying to create that field? Thanks!

That I didn't checked, good idea. Will do.

**Comment by paescuj** [comment] 2023-01-20 10:05
> @paescuj Sorry, I meant "field", not "table", my bad. Created the foreign key in the news_posts manually and then configured in the collection, which worked. But was unable to create the relation using Directus.

No problemo! I see, thanks! So the error was always the same (`[INVALID_PAYLOAD] Field "language" doesn't exist in collection "news_posts"`) or was it a different problem in the beginning? 

> That I didn't checked, good idea. Will do.

Thanks! I'd appreciate that 👍

**Comment by marianhlavac** [comment] 2023-01-20 10:07
@paescuj It seems that now I'm not unable to reproduce the issue (retraced the exact steps in the video I posted), and that's probably because I had to clear the cache yesterday after some more direct changes to DB schema. Before clearing the cache the issue was reproducible every time, now it's gone.

Unfortunately historically we only log SQL statements that resulted in error on had otherwise non-standard execution, which means that the SQL query behind this error (the `Field "language" doesn't exist in collection "news_posts"`) was executed without error on Postgres or no query was made (cache).

Sorry I can't help further.

>  So the error was always the same ([INVALID_PAYLOAD] Field "language" doesn't exist in collection "news_posts") or was it a different problem in the beginning?

Yep, this was the initial issue which led to a problem where I was unable to delete the field in Directus.

**Comment by paescuj** [comment] 2023-01-20 12:42
@marianhlavac Thanks for the info! I already suspected that it has been a problem with the schema cache... Unfortunately it's not quite clear to me how the problem arose in the first place.

---

I've been able to partly reproduce the issue: If a database column is added during runtime (that is, when the schema cache is already initialized), it's getting displayed but cannot be deleted until the schema has been refreshed.

1. Start Directus instance and create a collection (e.g. `test`).
2. Manually add a column to the table:
    ```sql
    ALTER TABLE test ADD test_field varchar(255);
    ```
3. Refresh collection setting page, the new column is successfully detected and displayed because this info is directly fetched from the DB:
  https://github.com/directus/directus/blob/bb176c44fb06c7f95da6678f319d4575ddaea97b/api/src/services/fields.ts#L83-L86
4. Try to delete the unconfigured field. This won't succeed because the field isn't included in the schema yet: 
https://github.com/directus/directus/blob/bb176c44fb06c7f95da6678f319d4575ddaea97b/api/src/services/fields.ts#L553-L562
5. Refresh page and try to delete the field again. This time it will succeed because the schema has been updated due to the `deleteField` call.

I can think of the following two solutions to mitigate this issue:
* Update schema when a new unconfigured field has been detected, e.g. as part of the `readAll` method.
* Bypass schema check in `deleteField` method for unconfigured fields (not quite sure if this would be a safe solution).

@rijkvanzanten How do you think we can proceed here?

In both cases, the issue described in the OP as well as the issue described in https://github.com/directus/directus/issues/17224#issuecomment-1396832152, it seems like they somehow ended up in a similar situation and the schema cache is now preventing the deletion of the field.
However in the case of the former, it almost seems like there's another issue with the deletion at the database level.
@AaronBeaudoin Would you be able to take a look at the PostgreSQL log while deleting the field?

**Comment by paescuj** [comment] 2023-02-02 15:24
Unfortunately, we are not able to reproduce the original issue.
Therefore I'm closing this issue for now.
If this problem should occur again, please open a new issue including the exact steps that led to this.

**Closed by paescuj** 2023-02-02 15:24 UTC
