### ISSUE TITLE
[^9.14.2] image interface no longer respects PUBLIC_URL

### ISSUE THREAD

**Issue by andy1li** [directus/directus#14678] opened 2022-07-26 19:24 UTC
### Describe the Bug

The new image interface uses incorrectly formed src, disregarding PUBLIC_URL.

<img width="1178" alt="WeChat2d2605dad9657f3959c45da476aa48d9" src="https://user-images.githubusercontent.com/1450947/181091758-cd5f27db-42a5-4284-b830-17850cb47887.png">

### To Reproduce

1. Set PUBLIC_URL to anything other than the root. For example: `PUBLIC_URL="http://foobar.com/`**`api`"**.

2. Use directus version ^9.14.2. (9.14.1 was okay.)

3. Try to use the image interface. The sub-folder part would be incorrectly repeated: `http://foobar.com/`**`api`**`/`**`api`**`/assets/...`

### What version of Directus are you using?

9.14.2, 9.14.3, 9.14.4, 9.14.5

### What version of Node.js are you using?

16.16

### What database are you using?

mysql 8.0.28

### What browser are you using?

chrome

### How are you deploying Directus?

self-hosted

**Comment by rijkvanzanten** [comment] 2022-07-26 19:37
Duplicate of https://github.com/directus/directus/issues/14565

**Closed by rijkvanzanten** 2022-07-26 19:37 UTC
