### ISSUE TITLE
Let tableRow gets more room when content size needs it.

### ISSUE THREAD

**Issue by AMB-Informacio** [directus/directus#21062] opened 2024-01-12 11:25 UTC
### Describe the Improvement

Make the tableRow height not fixed from the var value and, instead, make this the minimum height to allow content claim more space.

The problem is that when we want to make a display that needs more than the default room provided when showing it in table row, it's cut.

<img width="737" alt="Captura de pantalla 2024-01-12 a les 11 36 05" src="https://github.com/directus/directus/assets/83698463/13e4665c-483c-4f24-9f1e-2695a5b9dd77">

Setting only the minimum height solves the problem:

<img width="796" alt="Captura de pantalla 2024-01-12 a les 11 50 10" src="https://github.com/directus/directus/assets/83698463/57dfbc8c-90b5-40e7-8a4a-6e90b4b2e313">

I think this is a side effect to the fix introduced in
[Fix thumbnail overflow in render-template #15115](https://github.com/directus/directus/pull/15115)
to solve some problem with large images. 

Specifically the change is to the app/src/components/v-table/table-row.vue
and change these styles to min-height:

```
.table-row {
	min-height: v-bind('cssHeight.tableRow');
(...)
:deep(.render-template) {
		min-height: v-bind('cssHeight.tableRow');

		img {
			min-height: v-bind('cssHeight.renderTemplateImage');
		}
	}
```

What do you think @azrikahar ?  It maintains the fix needed in 15115 or do you think it will broke that? I tested that with a large image and it seems ok.

@rijkvanzanten I can try to make my first pull request.

**Comment by paescuj** [comment] 2024-01-12 11:59
Hey @AMB-Informacio, thanks for opening the issue!

I'm afraid we cannot simply switch to `min-height`:
- We need to have some sort of limit in place, otherwise rows can grow indefinitely
- Thumbnails ("Image" display) will be 64px by default (would require another rule)

Do you think you could solve the cut off content in your custom display in a different way? For example you could hide the overflow but have a tooltip which shows the full content when hovering.

**Comment by AMB-Informacio** [comment] 2024-01-12 12:50
Hey,

Thank you for you fast answer.

I understand rows will grow only if his inner content grows. It will not happen in default provided displays. But each kind of content (display) can set their limits too. In general, it's better have the content shown and the container adapted. And not the other way around.

A possibility is to have and option to let tables apply height strictly or otherwise adapt (alongside the "comfy,compact..." option).

The solution "For example you could hide the overflow but have a tooltip which shows the full content when hovering." is one think we want to avoid because of the bad UX it provides. In fact, we have extended the related-fields display to allow the related contents to be visible directly on place (and choosing between single or multiple lines). This helps our client to have all meaningful information at a glance.

About the image size, I'm not sure if I understand it, but I suspect that the image itself gets this resolution (64px) and extending his frame to bigger image size makes it blurry. I can try to make a workaround about it. Besides, we can also set the size of the image as currently it is, regardless of having more room to grow. This will only happen if you mix in the same table content that needs more space with images.

An other thing to take into account is that we can always set a max-height to let the rows height grow but not in a decontrolled way. Put it at 200px... ?

For now, we are applying it to our Directus base image. But we will be happy to engage with you and provide feedback and improvements to the codebase.

Thank you!


Daniel Valls Estella
Tècnic Especialista
Via Laietana, 33, 4t 1a - 08003 Barcelona
Tel. (+34) 93 291 80 96
***@***.***
www.ambinformacio.cat
La informació inclosa en aquest correu electrònic és CONFIDENCIAL, i és per a ús exclusiu del destinatari. Si vostè llegeix aquest missatge i no n'és el destinatari, li informem que està totalment prohibida la divulgació, distribució o reproducció d'aquesta comunicació, i li demanem que ens ho notifiqui i ens retorni aquest missatge, i a més que l'esborri. Gràcies.
Abans d'imprimir aquest e-mail pensi en el medi ambient.
La información incluida en este correo electrónico es CONFIDENCIAL, siendo para uso exclusivo del destinatario. Si Vd. lee este mensaje y no es el destinatario, le informamos de que está totalmente prohibida la divulgación, distribución o reproducción de este comunicado y le agradeceríamos lo notificara y lo devolviera a la dirección arriba indicada, borrando el mensaje original. Gracias.
Antes de imprimir este e-mail piense en el medio ambiente.
This email and the information within are CONFIDENTIAL and it is intended exclusively for the addressee. If this message has been received in error, you are not entitled to use, disclose, distribute copy or rely on this email in any way. Please notify us immediately by email and delete it from your system.
Please consider the environment before printing this email. 
________________________________
De: Pascal Jufer ***@***.***>
Enviat el: divendres, 12 de gener de 2024 12:59
Per a: directus/directus ***@***.***>
A/c: informatica ***@***.***>; Mention ***@***.***>
Tema: Re: [directus/directus] Let tableRow gets more room when content size needs it. (Issue #21062)


Hey @AMB-Informacio<https://github.com/AMB-Informacio>, thanks for opening the issue!

I'm afraid we cannot simply switch to min-height:

  *   We need to have some sort of limit in place, otherwise rows can grow indefinitely
  *   Thumbnails ("Image" display) will be 64px by default (would require another rule)

Do you think you could solve the cut off content in your custom display in a different way? For example you could hide the overflow but have a tooltip which shows the full content when hovering.

**Comment by rijkvanzanten** [comment] 2024-02-01 16:46
Displays are currently designed / intended to be used inline. Allowing them to grow vertically to arbitrary limits means they will no longer be usable in various places displays are currently used (like inline in relational interface rows, page titles, etc).

I'm down to discuss a new "Inline" vs "Block" prop for displays overall we could use to make sure Displays can adapt to being rendered inline/block to allow this type of use case, but lets do that as a new feature request 🙂 

As for right now, this is working as intended so I'll close this issue.

**Closed by rijkvanzanten** 2024-02-01 16:46 UTC

**Comment by AMB-Informacio** [comment] 2024-02-02 15:40
Thank you @rijkvanzanten rijkvanzanten I see, as you mentioned, that the displays are supposed to be "small inline components". I was not paying attention to the constraints of "small" and "inline". I saw displays as the way you want to visually present item attributes (in general) when you display them. I saw displays as a counterpart to interfaces, where these are the way to present them with editing capabilities. 

In fact with this idea I miss a more general (or block enabled) display. I also think that many times when a field is not editable, for whatever reason, it could use it's associated display to be shown, rather than a blocked editable interface.

It links me to a broad vision I'm exploring last months: a way to not bind table data structures to a direct, implicit, and single fashion item editing presentation. I'm now a long way from the tiny request to let table rows show items that are higher than expected (for whatever reason that might be). But what I'm facing with my current work, trying to get Directus to do what we need, is that I may have to develop a custom module. And it also keeps a close relationship with enabling views, a requirement we mentioned as a priority when licensing the product, and this block displays.

I think we can imagine a new layer on top of collections and collection item editing, because those are too tied to the database. And when you edit an item, there is only one way to edit it. This new layer could consist of views (or data projections) that can combine different collections. Each view item can be displayed or presented by combining editable elements (interfaces) and read-only elements (block displays, yes ;) ) over a custom or regular grid. 

One objective is to decouple which data we can show to the user, how we show it, and how the user can edit from the underlying data model or structure.

In this new layer each View has configured one query to get a collection of view items,  and another one to get a single* item. A selection of attributes from the first query (CollectionViewQuery) are configured to constrain the second query (ItemViewQuery) (*the items query could in fact have more than one result,it’s not a problem really but I leave it here).
 A view collection shows the result of CollectionViewQuery in whatever layout (analogue to collections). Each element links to a view item (with the results of the contrained ItemViewQuery).

A view item is not bound to a single ID (because there is none) to make and update, but rather to a group of different collection item update calls that each view item interface element provides. Each field of the ItemViewQuery can provide a BlockDisplay and an EditableInterface the result of which is not a value for an item field but rather and intended update call. I supose that in a similar way that inner related elements work.

Sorry for being too long here. I will elaborate it better trying to figure out how could it could be done.

**Comment by rijkvanzanten** [comment] 2024-02-02 16:34
@AMB-Informacio You know what, @benhaynes and myself have actually discussed something very similar just the other day! The idea to decouple "views" or "forms" from the actual data model, and allow those "views" to have more presentation-only capabilities was exactly what we talked about! 

I think we should consider adding a "inline" vs "block" mode for displays, so you can use the "inline" flavor inside of layouts, and the "block" flavor inside of these new form "views". That'd should give you the best of both worlds 🤔 Maybe the tabular layout can then also have a way to say "Use the block version of displays instead of inline" so you get the growing rows you were talking about in your original post 🤔
