### ISSUE TITLE
Translations auto fills content from other language

### ISSUE THREAD

**Issue by gantich** [directus/directus#15821] opened 2022-09-30 07:23 UTC
### Describe the Bug

After filling one translations fields and switching to another language, just focusing one field and pressing ANY key all fields are filled with data inserted from the language before. Upon saving them, the data only appears in the second language rather than on both.

This behaviour didn't happen in 9.15.1 and appeared since updating to 9.17.4

### To Reproduce

1. Create a `test` collection
2. Add translations field (required)
3. Add fields to translations collection (required and not allow null values)
4. Create a new item in `test`collection
5. Fill fields in one language
6. Switch to a second language
7. Focus any field
8. Press any key
Result: Fields fill automatically with content from the previous language. Previous language that was filled has no data. Adding again that dissapeared data, checking all fields are filled, and saving returns a required error "The following fields have invalid values: answer: Value is required"

https://user-images.githubusercontent.com/16262919/193212428-6c86c0c4-9dea-48ac-9df8-cd966b403bcc.mov

### Errors Shown

The following fields have invalid values:

answer: Value is required

### What version of Directus are you using?

9.17.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

PostgreSQL 14

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-09-30 07:27
This should be duplicate of #15606 #15538 #15460. It has been fixed by #15500 and released in `9.18.0`, so do make sure to upgrade to the current latest version `9.18.1` to resolve this 👍

**Closed by azrikahar** 2022-09-30 07:27 UTC
