### ISSUE TITLE
Changing primary key causes issues 

### ISSUE THREAD

**Issue by toshi38** [directus/directus#1922] opened 2017-10-25 08:31 UTC
## Version Info
  - Directus version and branch: Directus docker aac9ec 6.4.3
  - PHP version: 
  - MySQL version: 
  - Web server: (Ex. Apache, nginx or IIS?) 
  - OS name and version: 

## Expected Behavior

Should be able to delete a primary key and set an existing column to be primary key. 
## Actual Behavior
Does not work, get error even though gui shows that there is a primary key, can not delete table.  If I create a new table then delete the primary key then add a new column as primary key it seems to work. 

## Steps to Reproduce
 1. Create a table and add some columns 
 2. Delete id primary key column
 3. Try to set one of your existing columns to be the primary key.  It could be that this is invalid for example if some rows don't have the primary key... That said the error is still wrong if this is the case.  After doing this you can't seem to delete the table anymore either...

**Comment by WellingGuzman** [comment] 2017-10-28 16:25
This may be an issue with the fact that you can't create a primary key if the column has already data, which may not be unique.

Maybe the error is not clear,  but this is a expected behavior of MySQL, and probably any other database engine.

What's the error you are getting? any logs or screenshot?

**Comment by WellingGuzman** [comment] 2017-10-29 02:49
I'm closing this, unless the issue is different from what I understood it is.

Basically MySQL, doesn't let you put a column that has already not unique data to be primary key.

**Closed by WellingGuzman** 2017-10-29 02:49 UTC

**Comment by toshi38** [comment] 2017-10-29 11:17
Thats reasonable... but perhaps the error should be clearer since it wasn't obvious how I should "remedy" the problem.

**Comment by WellingGuzman** [comment] 2017-10-29 13:37
@toshi38 sure that would make more sense having a clearer error. what error did you get?

Ref: #1237

**Comment by toshi38** [comment] 2017-10-30 10:08
I've torn down the instance :( so I can't reproduce it easily now.

**Comment by WellingGuzman** [comment] 2017-10-30 18:37
oh bummer. All good!
