### ISSUE TITLE
Cannot translate folder name

### ISSUE THREAD

**Issue by Myrmod** [directus/directus#11514] opened 2022-02-08 15:34 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

In the current version 9.5.1 I cannot translate the name of a folder. The problem is the overlay, where you can add a translation, is above the field where you write in your translation. You cannot click it currently.

### To Reproduce

- Use Directus version 9.5.1
- create a folder
- try to rename the folder

### Errors Shown

<img width="1268" alt="error" src="https://user-images.githubusercontent.com/44287502/153020428-b214654d-4f59-4d83-8a59-ff58ed1cee90.PNG">

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

mysql8

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows WSL2

### How are you deploying Directus?

local docker

**Comment by azrikahar** [comment] 2022-02-08 20:39
Duplicate of #11271, #11078, and #10892 (this is where we are tracking this issue 👍)

**Closed by azrikahar** 2022-02-08 20:39 UTC
Labels: Bug (Potential)
