### ISSUE TITLE
Unable to post-request to table with M2M-Alias

### ISSUE THREAD

**Issue by chrisbenjamin** [directus/directus#1800] opened 2017-09-10 21:04 UTC
I am not able to post-request to a table, which has an many-to-many alias. Maybe it's my fault, but I can't find any further information in the documentation or within the sources.

In total i have three tables (sql dumps below): 
- relationtest: the content type I use; where i want to add multiple items from table "regions"
- regions: a simple contenttype, where i have regions (a simple name)
- translation_region_junction: the relation table (many-to-many, see below and attachments)

relationtest:
- id
- name: varchar
- regions: many to many

regions:
- id
- name: varchar

translation_region_junction:
- id
- translation_id (id from relationtest)
- region_id (id from region)

In the directus ui, i can perfectly add data into relationtest and select data via m2m-button "choose existing"

(see attached images)

But I want to do that via JavaScript programmatically. I create a post-request on the relationtest table with that json body:

```
{
    "name": "hallo",
    "regions": [
                {
                    "translation_id": 17,
                    "region_id": 8
                },
                {
                    "translation_id": 17,
                    "region_id": 8
                }
    ]
      
}
```
But I get this error message in response
```
{
    "success": false,
    "error": {
        "message": "Undefined index: data"
    },
    "code": 8,
    "class": "ErrorException",
    "file": "/home/chris/fuckux/api/core/Directus/Database/TableGateway/RelationalTableGateway.php",
    "line": 588
}
```

## Version Info
- Directus version and branch: build-6.4.2.20170823180744
- PHP version: 5.6.30-0+deb8u1
- MySQL version: 5.0.11-dev
- Web server: nginx/1.6.2
- OS name and version: Debian GNU/Linux 8 (jessie)

## Expected Behavior
I'm expecting to add an entry to "relationtest" and within this request 0-n entries into the relation-table.

## Actual Behavior
Getting an error

## Steps to Reproduce
 1. create three tables like described above (two regular inputs + junction-table)
 2. create a post-request (e.g. with postman) to the relationtest-table, including a nested element, that should be passed to the aliased junction-table

## Schema Dump, Logs, or Screenshots

**table: relationtest**
<img width="561" alt="screen shot 2017-09-10 at 22 46 15" src="https://user-images.githubusercontent.com/569479/30252890-a0cb470c-967a-11e7-9619-29244d72408d.png">
<img width="596" alt="screen shot 2017-09-10 at 22 46 21" src="https://user-images.githubusercontent.com/569479/30252893-a6024d10-967a-11e7-8077-9cc22ab5acad.png">
<img width="497" alt="screen shot 2017-09-10 at 22 48 54" src="https://user-images.githubusercontent.com/569479/30252905-dbfae6ca-967a-11e7-90a2-036d7e89e4e7.png">

**table: regions**
<img width="460" alt="screen shot 2017-09-10 at 22 53 22" src="https://user-images.githubusercontent.com/569479/30252899-caf57674-967a-11e7-93ef-f9c83196d68c.png">
<img width="440" alt="screen shot 2017-09-10 at 22 53 12" src="https://user-images.githubusercontent.com/569479/30252900-caf812da-967a-11e7-9bed-db4e35eda538.png">

**table: translation_region_junction**
<img width="455" alt="screen shot 2017-09-10 at 22 54 39" src="https://user-images.githubusercontent.com/569479/30252908-f5ead266-967a-11e7-938a-ff138a0a5860.png">

**sql dumps**
[sql.zip](https://github.com/directus/directus/files/1290930/sql.zip)

**Comment by WellingGuzman** [comment] 2017-09-11 16:10
The related data must be inside a `data` key (internal Directus API key).

After seeing this issue, I'm started to think we probably should find a way to add the data this way if possible, we are going to take this as a suggestion.

I'm going to explain how this would work.

Ex: Non existing 

```
{
    "name": "hallo",
    "regions": [
			{
				data: {
					"name": "New Region A"
				}
			},
			{
				"data": {
					"name": "New Region B"
				}
			}
    ]
}
```

Ex: Existing 

You would be adding region id = 8 and 9.
```
{
    "name": "hallo",
    "regions": [
			{
				data: {
					"id": 8
				}
			},
			{
				"data": {
					"id": 9
				}
			}
    ]
}
```

Everything in the same level of `data` will be the junction table structure, such as `sorting` (if exists).

I will close this as this is not a bug.

**Closed by WellingGuzman** 2017-09-11 16:10 UTC

**Comment by WellingGuzman** [comment] 2017-09-11 16:16
Suggestion added to Feathub: https://feathub.com/directus/directus/+119

**Comment by chrisbenjamin** [comment] 2017-09-11 20:38
@WellingGuzman I have another feature recommendation/request. First: Thanks, this worked for me.

But my feature request would be something like this: 
- When you add an entry and this entry contains relational data (e.g. many to many, like above), this entry is stored. Let's say you have entry "test" with relational data e.g. sizes with ids 1 and 2
- Now, assume you want to edit this entry. You want to select different sizes, e.g. 1 and 3 (deselected id 2)
- What now happens is: sizes with ids 1 and 3 are added additionally to the database. ID 2 is still in there
- Okay, you could GET the entry, read the response, delete first with two requests the ids 1 and 2 and add then the new ids 1 and 3

In my opinion this is a real world example. Otherwise it wouldn't make much sense.

What do you think?
Hope the example was clear. If you wish I can open a new ticket for that.

Thanks
