### ISSUE TITLE
O2M relations are re-queried on every change in the document when using table layout

### ISSUE THREAD

**Issue by 8byr0** [directus/directus#23945] opened 2024-10-30 10:21 UTC
### Describe the Bug

Relation items (o2m) are queried again on every model change. 

Consequences:
- Useless network load on the server (relation data did not change)
- Flickering UI

While this may not be a big deal with a few items, a document with many relations configured triggers a lot of requests that could be avoided

### To Reproduce

Create a sample collection `CollectionA` with a text field `name`
![image](https://github.com/user-attachments/assets/8a43ab2f-e83b-43da-ac6c-1fe6d786bb68)

Create another collection `CollectionB` with a text field `name` and an o2m relation to `CollectionA`, using one-to-many interface and the table layout
![image](https://github.com/user-attachments/assets/77508b1e-5e91-4d5a-91f6-3da7eaa44ab5)
![image](https://github.com/user-attachments/assets/0d56f749-bb9b-45c3-8254-88c1082c7fc9)

Create a new entry in `CollectionB`, fill in `name` and save
![image](https://github.com/user-attachments/assets/9aa5b460-f539-4abe-b9ff-31ed030bdd70)

Open devtools to log network requests

Now type in `name` field. For every character typed (i.e. every model change), all the relations are queried again (each request of the screenshot is following a character typed)
![image](https://github.com/user-attachments/assets/bd8c4032-b598-4e0a-96fa-152cbbf26d33)

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres

**Comment by 8byr0** [comment] 2024-10-30 10:26
Tested also:
- m2o interface: works as expected without querying again
- m2m interface: same behaviour (request made on every change) if using the table layout (works properly with list layout)

**Comment by hanneskuettner** [comment] 2024-10-30 12:07
This is a duplicate of https://github.com/directus/directus/issues/23750. I will close this issue and continue to track the progress in the original issue.

**Closed by hanneskuettner** 2024-10-30 12:07 UTC
