### ISSUE TITLE
M2M relational data not showing in side bar drawer

### ISSUE THREAD

**Issue by w0kyj** [directus/directus#15290] opened 2022-08-27 15:35 UTC
### Describe the Bug

We have a parent collection called “Header”, which have a M2M relationship to the “Buildings” collection (“Buildings” has its own translations junction to the languages’ table.)

The problem is that if we enter from the parent collection to the building content, it doesn’t show the information (first screen cap) of the translation for that related item, even when in reality that item has translations (second screen cap)

This is an issue, since the content editors are entering information to the fields thinking it doesn’t exist (whey they really are)
<img width="1440" alt="Screen Shot 2022-08-27 at 9 30 38 AM" src="https://user-images.githubusercontent.com/40695629/187036924-a4c6383d-5fe5-4a3f-99b1-2a372d6e703a.png">
<img width="724" alt="Screen Shot 2022-08-27 at 9 31 39 AM" src="https://user-images.githubusercontent.com/40695629/187036955-f99d0c52-6e1b-4b18-b0a8-2eb40a5a954b.png">

### To Reproduce

Create Building Lists --> m2m --> Buildings --> translations --> buildings_translations --> languages

Any multi-level m2m seems to miss showing the relational data content in the side bar drawer.

### Errors Shown

No data shown, even though it exists.

### What version of Directus are you using?

9.16.1

### What version of Node.js are you using?

Cloud

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Standard & Enterprise Cloud

**Comment by w0kyj** [comment] 2022-08-27 15:36
Related past issues in case helpful:
https://github.com/directus/directus/issues/13018
https://github.com/directus/directus/issues/12836

**Comment by Nitwel** [comment] 2022-08-27 15:58
I was not able to reproduce this (see video below), so my guess is that it already got fixed on the current main branch. If I misunderstood the issue, let me know!

https://user-images.githubusercontent.com/22577866/187037966-fe41c111-8544-466c-887b-e3b47d8d01ca.mp4

**Comment by adiazc9** [comment] 2022-08-28 12:41
@Nitwel What Directus version are you using?

**Comment by azrikahar** [comment] 2022-08-29 07:29
@adiazc9 He's using the latest main branch, which means it'll have fixes that will be included in a future release!

That being said, I believe this issue is the same as #15208. I can confirm @Nitwel already swiftly fixed this in #15220 😄

I'll mark this issue as resolved, and I've attached additional clips as further verifications 👍

### Before #15220

https://user-images.githubusercontent.com/42867097/187146453-89441f6c-b09f-4c7d-a06f-3ce613ad3aad.mp4

### After #15220

https://user-images.githubusercontent.com/42867097/187146479-0142cb53-0e3c-4a3b-b85c-467163091712.mp4

**Closed by azrikahar** 2022-08-29 07:29 UTC
Labels: App, Needs More Info, Can't Reproduce
