### ISSUE TITLE
Creating a new condition for a field or opening an existing one freezes the page

### ISSUE THREAD

**Issue by VladDigitalOriginal** [directus/directus#19282] opened 2023-07-28 12:31 UTC
### Describe the Bug

Creating a new condition for a field or opening an existing one freezes the page
<img width="573" alt="image" src="https://github.com/directus/directus/assets/122997283/46caa067-819e-4e48-8603-4fccaabf4178">

### To Reproduce

1. Open the Field settings.
2. Go to the "Condition" tab.
3. Click on the "Create New" button or select an existing condition.

### Directus Version

v10.5.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-07-28 12:32
This is a duplicate of https://github.com/directus/directus/issues/19259 and has been resolved by https://github.com/directus/directus/pull/19271 :)

**Closed by br41nslug** 2023-07-28 12:32 UTC
