### ISSUE TITLE
Bug: Collection Sort

### ISSUE THREAD

**Issue by Lord-KalEl** [directus/directus#22399] opened 2024-05-06 14:13 UTC
### Describe the Improvement

"Tiny tweak"

I suggest a small adjustment or improvement. Some dropdown menus where users can specify collections are disorganized and lack a meaningful structure. While a search field has been added in some places, which is very helpful, overall, the collections could simply be sorted. This would allow users to search much faster and find the desired options more quickly.

![Screenshot_20240504-035102](https://github.com/directus/directus/assets/121204357/29d8abc6-cdc7-4cb0-b6c3-9c7e821c1550)
![Screenshot_20240504-034909](https://github.com/directus/directus/assets/121204357/d7d59adc-0f18-4c37-a5c3-05d2f4196988)
![Screenshot_20240504-034202](https://github.com/directus/directus/assets/121204357/bf8dfdf4-db9a-4db1-afed-0f258aa0267d)

**Comment by hanneskuettner** [comment] 2024-05-06 14:22
Heya, thanks for opening this issue. It looks like a duplicate of #21658 to me and I'll proceed to close this. 

After the fix lands, the collections in these lists should be sorted the same way as they are sorted (manually) in the Data Model section of the app.

**Closed by hanneskuettner** 2024-05-06 14:22 UTC
