### ISSUE TITLE
In app filtering - invalid filter key when using three or more condition levels

### ISSUE THREAD

**Issue by shipsides-sparknel** [directus/directus#16292] opened 2022-11-03 04:15 UTC
### Describe the Bug

With the new update 9.20.3 update, existing working filter presets are no longer working in the app.

The issue is on the third or above condition layer, in my case _or_ inside _and_ inside _or_.

I have verified this is in the web app only and not related to any field permission or a problem with the filter itself. Using the API to pull the preset filter, then doing a separate query for the returned filter with all direct and relational fields, the query worked as expected.

### To Reproduce

a simplified version of a filter that worked in 9.18:
![image](https://user-images.githubusercontent.com/106218118/199645713-81d327d5-3508-472f-95db-ac928b7c4e1d.png)

returns

`{
  "errors": [
    {
      "message": "Invalid filter key \"[Qualification][_null]\" on \"Employees\"",
      "extensions": {
        "code": "INVALID_QUERY"
      }
    }
  ]
}`

removing the final OR tier
![image](https://user-images.githubusercontent.com/106218118/199645762-3e0cf0b9-1c9c-4d82-b21d-04f2762d2cd9.png)
returns a valid result

using the API directly to retrieve either of the below works:
1st screenshot:
`{
  "_and": [
    {
      "_or": [
        {
          "Verification": {
            "_eq": "Unverified"
          }
        },
        {
          "Verification": {
            "_null": true
          }
        }
      ]
    },
    {
      "_or": [
        {
          "Date_of_Birth": {
            "_null": true
          }
        },
        {
          "_and": [
            {
              "Apprentice_Trainee_or_Cadet": {
                "_eq": "Cadet"
              }
            },
            {
              "_or": [
                {
                  "University_or_Education_Institute": {
                    "_null": true
                  }
                },
                {
                  "Qualification": {
                    "_null": true
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}`

2nd screenshot:
`{
  "_and": [
    {
      "_or": [
        {
          "Verification": {
            "_eq": "Unverified"
          }
        },
        {
          "Verification": {
            "_null": true
          }
        }
      ]
    },
    {
      "_or": [
        {
          "Date_of_Birth": {
            "_null": true
          }
        },
        {
          "_and": [
            {
              "Apprentice_Trainee_or_Cadet": {
                "_eq": "Cadet"
              }
            },
            {
              "University_or_Education_Institute": {
                "_null": true
              }
            },
            {
              "Qualification": {
                "_null": true
              }
            }
          ]
        }
      ]
    }
  ]
}`

### What version of Directus are you using?

9.20.3

### What version of Node.js are you using?

16.18.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

cloud

**Comment by Nitwel** [comment] 2022-11-09 15:00
I was not able to reproduce this, could you elaborate on how your table structure looks like?

**Comment by rijkvanzanten** [comment] 2022-11-09 15:27
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2022-11-09 15:27 UTC
Labels: App, Needs More Info, Can't Reproduce

**Comment by shipsides-sparknel** [comment] 2022-11-10 00:49
good point, i should have tested this on a different collection. on other collections i see or-and-or is working as expected.

i have found a way around this myself for this particular collection by removing some redundant filters so i can't spend any more time on this, but am happy to share the specific schema details if you dm me and this would help.

the table itself is actually quite basic - there are 41 fields with the bulk being alias messages, strings (mostly via dropdown) and integers. the only two "complex" fields are a M*1 for a category selector, and a M*M for a files upload interface. the files interface was not being used in the filter, and the M*1 was only being used for is null. in the stripped down version i provided above, the only field that wasn't a single line textbox was apprentice trainee cadet, and that was a string-dropdown interface.

even sticking to just the most basic string/integer fields and the most basic conditions of _eq or _null, i was still running into the or-and-or filter problem. even switching to other types like _in or _gt, i still found the same issue occur.
