### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by NextrekNet** [directus/directus#1725] opened 2017-08-08 21:48 UTC
## Expected Behavior
Directus should work correctly

## Actual Behavior
same column name on different table produce the issue. Internal server error 500

![capture](https://user-images.githubusercontent.com/22654128/29096148-01ce0ae0-7c94-11e7-8f71-d415bf743320.PNG)
![capture2](https://user-images.githubusercontent.com/22654128/29096147-01ca0436-7c94-11e7-817d-438836d6bde7.PNG)

## Steps to Reproduce
 1. name 1 column dropdown in a table
 2. same name 1 column dropdown in other table

**Comment by WellingGuzman** [comment] 2017-08-09 00:58
Hey @NextrekNet, can you please share your logs in `api/logs`?

Thanks

**Comment by benhaynes** [comment] 2017-08-09 19:48
@NextrekNet – we'll also need a little more detail. Could you tell us what page you go to to get the error? Do you have a schema (SQL dump) you can share? We have tables with the same name working fine on our side so we'll need more insight to get this fixed.

Thanks!

**Comment by WellingGuzman** [comment] 2017-08-19 07:48
I see MariaDB in the error, maybe is only related to MariaDB, I will be installing MariaDB tomorrow and see if I can reproduce this issue.

That kind of information need to be specified so we know what environment you are on.

I will give you an update as soon as I get this running!

**Comment by WellingGuzman** [comment] 2017-08-20 22:22
Due to lack of information and inactivity this ticket will be closed until a steps to reproduce this is provided.

**Closed by WellingGuzman** 2017-08-20 22:22 UTC
Labels: 3. Major, Bug, Can Not Duplicate

**Comment by benhaynes** [comment] 2017-08-20 23:40
@WellingGuzman – Were you able to test on Maria?

**Comment by WellingGuzman** [comment] 2017-08-21 03:53
Yes, I did test it on MariaDB 10.1 10.2 (Ubuntu 14.04 LEMP), I don't know which http server or OS @NextrekNet was using.
