### ISSUE TITLE
Not possible to change the display for translations interface

### ISSUE THREAD

**Issue by danieljwestman** [directus/directus#5452] opened 2021-05-04 13:51 UTC
macOS Big Sur (M1)
Directus 9.0.0-rc.61
PG 12
Node v15.14.0

--

I can't get this to work... I try to change the display for the translations interface. Seems to be some kind of bug here.

**Before:**

<img width="484" alt="Skärmavbild 2021-05-04 kl  15 44 43" src="https://user-images.githubusercontent.com/20950568/117013553-45510c00-acf0-11eb-8c98-b3adfc69fc06.png">

**Languages:**

<img width="520" alt="Skärmavbild 2021-05-04 kl  15 45 40" src="https://user-images.githubusercontent.com/20950568/117013594-4d10b080-acf0-11eb-9bb0-184e5c46dac3.png">

**Changing interface display:**

<img width="1255" alt="Skärmavbild 2021-05-04 kl  15 45 13" src="https://user-images.githubusercontent.com/20950568/117013640-569a1880-acf0-11eb-80a6-9fe9a792b275.png">

**After:**

<img width="669" alt="Skärmavbild 2021-05-04 kl  15 45 59" src="https://user-images.githubusercontent.com/20950568/117013673-5dc12680-acf0-11eb-957a-9246dd787a88.png">

Same thing with all properties (not only "Code").

**Comment by danieljwestman** [comment] 2021-05-05 10:30
Is this really fixed with #5467?

I've tried now with the same result. The language name isn't shown as the display (just as an example)... Logged in as Admin.

Am I missing something?

<img width="705" alt="Skärmavbild 2021-05-05 kl  12 30 02" src="https://user-images.githubusercontent.com/20950568/117128410-a682e900-ad9d-11eb-9510-2633f2a4075c.png">

<img width="1284" alt="Skärmavbild 2021-05-05 kl  12 29 19" src="https://user-images.githubusercontent.com/20950568/117128405-a4208f00-ad9d-11eb-9070-2dfad5d251b8.png">

**Comment by rijkvanzanten** [comment] 2021-05-05 14:09
No it wasn't! Must've made a typo in that `fixes xxx` on the pr... my bad!

**Comment by rijkvanzanten** [comment] 2021-05-05 14:15
That being said, this does seem to be a duplicate to https://github.com/directus/directus/issues/3432, so re-closing it again 🙂

**Closed by rijkvanzanten** 2021-05-05 14:15 UTC
Labels: App, Bug, Good First Issue

**Comment by danieljwestman** [comment] 2021-05-05 14:26
@rijkvanzanten Hm, I'm not that sure about that. Issue #3432 doesn't seem to be about the same problem. In that issue **_it is_** possible to set a display value...

<img width="752" alt="Skärmavbild 2021-05-05 kl  16 23 52" src="https://user-images.githubusercontent.com/20950568/117156840-5f592000-adbe-11eb-9637-439a1881db08.png">

**Comment by rijkvanzanten** [comment] 2021-05-05 15:21
@danieljwestman They're noting that you can't display the actual value of the translation in the interface, this issue is that the options for the interface are from the "translations" collection perspective, but the value is rendered as if it's the "languages" collection perspective, which means that the values in the template don't exist. Solving #3432 also solves this, as the end result is the same for both 🙂 Not the exact same symptom, but caused by the same underlying problem and has the same underlying solution

**Comment by danieljwestman** [comment] 2021-05-05 17:06
Hm, okay I'm not sure I understand that correctly, maybe we are misunderstanding each other... 😬

How do I accomplish what _benwalch_ is doing? In other words, how do I make the interface display Name (Code) like he does? From what I can see it's not working anymore..? See my screenshots above.

**Comment by rijkvanzanten** [comment] 2021-05-05 18:45
Yup! That's broken as you correctly mentioned in this issue. I'm saying that by fixing #3432, we also fix this issue, as they're related to the same underlying feature 👍🏻

**Comment by danieljwestman** [comment] 2021-05-05 18:46
Aha, okay 👍🏻
