### ISSUE TITLE
Reading bigger amount of data

### ISSUE THREAD

**Issue by rokdd** [directus/directus#20096] opened 2023-10-20 13:51 UTC
### Describe the Bug

We run into some trouble because our collections are growing in the number of items. We are querying around 65000 items and got problems with knex / postgresql. I tried to put the connections to max 1 like some threads are suggesting but it did not help. What I did at the end is to write a loop and chunk the request. Pity is that for the API it is not very comfortable to get data in small chunks and "waiting" for the end.

The error message:
```
$67569, $67570, $67571, $67572, $67573, $67574, $67575, $67576, 
$67577, $67578, $67579, $67580, $67581, $67582, $67583, $67584, $67585, $67586, $67587, $67588, $67589, $67590, $67591, $67592, $67593, 
$67594, $67595, $67596, $67597, $67598, $67599, $67600, $67601, $67602, $67603, $67604, $67605, $67606, $67607, $67608, $67609, $67610, 
$67611, $67612, $67613, $67614, $67615, $67616, $67617, $67618, $67619, $67620, $67621, $67622, $67623, $67624, $67625, $67626, $67627, 
$67628, $67629, $67630, $67631, $67632, $67633, $67634, $67635, $67636, $67637, $67638, $67639, $67640, $67641, $67642, $67643) order by "collection_xyz"."id" asc limit $67644 - bind message has 2108 parameter formats but 0 parameters
    at Parser.parseErrorMessage (C:\....\fdk-directus-dupli\node_modules\pg-protocol\dist\parser.js:287:98)       
    at Parser.handlePacket (C:\....\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\....\node_modules\pg-protocol\dist\parser.js:39:38)
    at TLSSocket.<anonymous> (C:\....\node_modules\pg-protocol\dist\index.js:11:42)
    at TLSSocket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 121,
  severity: 'ERROR',
  code: '08P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1690',
  routine: 'exec_bind_message'
}
```

I know that the fields are very greedy, the problem is that we need them later to understand the connections of the item to other collections. I am also not sure whether the error is really coming from the size of the item and not even by the number of items?

### To Reproduce

```
await item_service.readByQuery({
	"filter": {
		"vers": "WORK",
	},
	"limit": -1,
	"fields": [
		"*.*.*",
		"*.vers.id"
	]
});
```

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment] 2023-10-23 10:08
For that amount of data I would paginate over it instead of getting everything via `limit=-1`

> Pity is that for the API it is not very comfortable to get data in small chunks and "waiting" for the end.

What do you mean? You can either make your own pagination via the `offset` parameter or even simpler use `page` which is very convenient.

> An alternative to offset. Page is a way to set offset under the hood by calculating limit * page. Page is 1-indexed.

A single while loop is all you need to retrieve everything.

Per [the docs](https://docs.directus.io/reference/query.html#page)

**Comment by rokdd** [comment] 2023-10-23 10:21
Well we use directus as a backend.. So the frontend need to be changed to gather informations by loop now.

However we have also problems that the UI of directus is freezing at certain collections. We try to found out more, I assume there is a connection between somehow.

**Comment by rokdd** [comment] 2023-10-23 10:24
Update: Downgrading to 10.6.2 resolved immediately all problems.

**Comment by DanielBiegler** [comment] 2023-10-24 10:13
@rokdd could you confirm that it crashes due to usage of nested groups? There might be a related issue #20145

**Comment by rokdd** [comment] 2023-10-25 08:01
> @rokdd could you confirm that it crashes due to usage of nested groups? There might be a related issue #20145

@DanielBiegler : That looks like this.. it is the only collection with a nested accordion

We are just trying to understand the problem with the amount of data.. but it will need some time. If you know already what you need tell me what details I can share..

**Comment by DanielBiegler** [comment] 2023-10-25 10:04
Alright, thanks for confirming, we're on it. The nested groups was reproduced and will be fixed soon. :+1: 

Secondly:

Your query might be problematic due to the `"*.vers.id"` maybe but also like I said probably even more importantly, at some point you really have to paginate over your data. This is not directly related to Directus but just databases themselves, we also have a warning for that in [the docs](https://docs.directus.io/reference/query.html#limit). I'll close this issue for now since this sounds to me like a usage problem and we use GitHub issues to keep track of bugs in Directus itself. Happy to reopen in case this turns out to be an actual bug.

**Closed by DanielBiegler** 2023-10-25 10:04 UTC
Labels: Package: @directus/api, Needs More Info

**Comment by br41nslug** [comment] 2023-10-25 10:09
> Well we use directus as a backend.. So the frontend need to be changed to gather informations by loop now.

Since you're fetching this information in an extension, im presuming an endpoint, you can also do this paginated looping inside the extension and return the fetched data as long as your server has plenty of resources to keep it all in memory.

**Comment by rokdd** [comment] 2023-10-25 13:14
> > Well we use directus as a backend.. So the frontend need to be changed to gather informations by loop now.
> 
> Since you're fetching this information in an extension, im presuming an endpoint, you can also do this paginated looping inside the extension and return the fetched data as long as your server has plenty of resources to keep it all in memory.

True thats what I did inside of the extension. But we use also standard API Endpoints of directus and these we cannot change.
