### ISSUE TITLE
M2M and O2M relational links disappearing

### ISSUE THREAD

**Issue by mebushnell** [directus/directus#13936] opened 2022-06-16 14:29 UTC
### Describe the Bug

I have a collection (call it 'main') that is linked to three other collections using a M2M relation in two cases and a O2M relation in the remaining case.  Everytime I link entries between the main collection and the three others, the links eventually disappear and require re-entry.  The actual entries in the collections do not disappear, but their relationship to entries in the main collection do.  As far as I can tell, this is more likely to happen after I add or delete fields in the main collection.

### To Reproduce

1. Go to main collection ('Miniatures') and click on an entry,
2. Under that entry go to either 'Exhibitions', 'References', or 'Micrographs'.
3. Click add existing and select entries.
4. Save changes.
5. Go to Settings > Miniatures
6. Add an unrelated field than delete it.
7. Go back to the entry in Miniatures that you previously edited.
8. In my experience, the field that you added entries to (either 'Exhibitions', 'References', or 'Micrographs') will no longer have those entries recorded.

### Errors Shown

There are no errors.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.1

### What database are you using?

I am not sure - potentially none.

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud

**Comment by rijkvanzanten** [comment] 2022-06-16 15:49
Is this using a Community project or a Standard project?

**Comment by mebushnell** [comment] 2022-06-16 15:52
Community project.

**Comment by I-is-as-I-does** [comment] 2022-06-16 22:17
Hi,
I've experienced the same phenomenon, with any kind of relationship fields.
The only difference is that I'm running Directus locally. Database is SQLite.
The disappearing actually seems pretty random. 
If I can help investigating the issue, please let me know!

**Comment by mebushnell** [comment] 2022-06-17 13:43
Yes thanks - any help would be welcome!

In my case, I have a lot of M2O relationships set up and those seem to work fine and are stable.  It is only the M2M and O2M ones.

**Comment by I-is-as-I-does** [comment] 2022-06-18 20:35
I suspect an apparently unrelated bug regarding thumbnails to be causing the issue, at least in my case.
M2O and M2M relationships _systemically_ disappears on tables that have **files or images fields**.
There's a bunch of 403 forbidden errors in the console.

`GET http://localhost:8055/assets/undefined?key=system-small-cover&access_token=... 403 (Forbidden)`
`Failed to load resource: the server responded with a status of 403 (Forbidden)`

Is that the case for you too?

**Comment by mebushnell** [comment] 2022-06-20 10:24
Yes, my tables have image fields, and I have gotten similar 403 errors in the console.

**Comment by mebushnell** [comment] 2022-06-20 15:33
I get the 403 error only when I am changing the data model.  I tend to not use files, only images.

**Comment by rowild** [comment] 2022-06-20 16:11
Same observation: #13991 
Further updates will happen here as @azrikahar told me.

**Comment by I-is-as-I-does** [comment] 2022-06-20 16:44
`Is this when changing the data model, or in general?`

Changing the data model definitively breaks all relationship fields, even if the changes are unrelated to those fields.
Sadly for me, it also seems to happen in general, *if thumbnails are involded*.

`make sure that wherever you're hosting Directus doesn't rely on ephemeral storage`

Indeed, but that's not the case here. The 403 errors seem to get triggered by thumbnails; files are not actually missing.

Thank you for your time!

**Comment by bopetkovic404** [comment] 2022-06-29 12:13
> `GET http://localhost:8055/assets/undefined?key=system-small-cover&access_token=... 403 (Forbidden)` `Failed to load resource: the server responded with a status of 403 (Forbidden)`

I have this problem only when image is null or not selected. Is there an issue opened for these thumbnail problems or should I create new issue?

**Comment by PauloMFJ** [comment] 2022-07-13 11:18
Experiencing similar issues. Steps to reproduce (running on cloud `v9.13.0`):

1. Create `Builder (M2A)` field, and populate field with any types / content
2. Add a new field in same data modal
3. Save and exit data modal, return and delete the new field
4. All populated fields are now unlinked in the `Builder (M2A)`

We're a paying customer with several projects running on Directus, but in its current state this feels very unstable and not production ready. By simply deleting an unrelated field, we are currently losing links to all relational data. This is approaching a deal breaker for us.

Are there any updates when this may be resolved by?

**Comment by br41nslug** [comment] 2022-07-13 12:11
Are you running into this on community cloud or standard/enterprise @PauloMFJ ? This ticket seems to be isolated to SQLite (which community cloud runs) but there have been a couple of m2a related issues that have been resolved with the 9.14 release.

**Comment by PauloMFJ** [comment] 2022-07-13 13:07
> Are you running into this on community cloud or standard/enterprise @PauloMFJ ? This ticket seems to be isolated to SQLite (which community cloud runs) but there have been a couple of m2a related issues that have been resolved with the 9.14 release.

This build is currently running `Community Cloud`.

**Closed** 2022-07-21 18:44 UTC
Labels: API, Bug, DB: SQLite
