### ISSUE TITLE
Filtering users does not work with NULL values

### ISSUE THREAD

**Issue by ngjoni** [directus/directus#11671] opened 2022-02-16 15:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you filter attributes like IDs from the user collection by NULL values, it does not show them. Only with a proper value.

### To Reproduce

Here is a quick demo:

https://user-images.githubusercontent.com/49320058/154292047-883976a5-2f5d-46e7-8227-e7f317bd5be9.mov

### Errors Shown

No results in the admin panel.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

v16

### What database are you using?

PG 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by jaycammarano** [comment] 2022-02-16 18:55
So, I can't reproduce this but I think I'm not following your instructions correctly. Is this only with the system user table?

**Comment by ngjoni** [comment] 2022-02-16 23:00
@jaycammarano It happened only for the system user table

**Comment by licitdev** [comment] 2022-02-19 13:10
This issue lies with M2M relationships. There is no issue with the `_null` filtering as it does the check correctly should the m2m field be populated. So if the m2m field is empty, no field will be returned as there is no m2m item that can matches `_null` on the m2m's field.  

Hence, I think that the correct operator for use should be `_empty` instead of `_null`, which is not currently available for use with m2m in the app & api. 

Tested through the API with `_empty` but an error was thrown: `no such column: m2m_field._empty`.

For the use of `_empty`, it should be on the top level field of the relationship, which is currently unsupported in the app. eg: allow selection of `m2m_field` instead of `m2m_field.id`

**Comment by azrikahar** [comment] 2022-04-05 08:50
#12488 (released in `v9.8.0`) allows us to filter using count function, so doing `count of Directus Users equals 0` in your scenario now properly yields the expected outcome of this issue:

https://user-images.githubusercontent.com/42867097/161716433-46275085-a8ec-4c82-8857-4d7a9fbad9d5.mp4

Closing this as resolved 👍

**Closed by azrikahar** 2022-04-05 08:50 UTC
Labels: API, App, Improvement
