### ISSUE TITLE
Field property count display malfunction

### ISSUE THREAD

**Issue by eduardoPinto12** [directus/directus#11650] opened 2022-02-15 14:23 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi, I'm sorry  in advance if this is a repeated issue, but I couldn't find anything on closed or open issues.

My team migrated from v8 to v9 just recently, and we had a list (now repeater) counter display, when trying to do something similar in v9, when there's only one item, it doesn't display anything, as you can see below:

![count](https://user-images.githubusercontent.com/45365656/154079178-41741c42-207b-4c4d-b5ca-62dbf5012e14.png)

when I think it should display "1 Item", but I could be wrong here :sweat_smile:, if so just please let me know, but I think it's a UI bug

### To Reproduce

1. As admin, go to **Settings**;
2. Select **Data Model**;
3. Pick a collection;
4. Select a Repeater field (if there isn't one just create a new one);
5. Click on **Display**
6. On **Display Template** just type `{{ field.count }}`

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13

### What browser are you using?

Firefox, Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally, and deploying on Docker as well, same result

**Comment by azrikahar** [comment] 2022-02-16 02:56
> when I think it should display "1 Item", but I could be wrong here

You are right! PR coming right up.

> On Display Template just type `{{ field.count }}`

Just to clarify, Display Template in this case should directly be the field in your repeater item, we don't have to include `field` prefix 👍

So if we have a repeater that looks like this:

![image](https://user-images.githubusercontent.com/42867097/154187086-cfc41a13-0e8b-49f3-80dc-64b1dde6fe81.png)

and the raw value is:

```json
[
	{
		"name": "Item 1"
	},
	{
		"name": "Item 2"
	}
]
```

we should configure the display template like so:

![image](https://user-images.githubusercontent.com/42867097/154187189-d71cd491-84da-4852-9e08-33b293f8dede.png)

that way it'll display the "name" field when we click on it:

![image](https://user-images.githubusercontent.com/42867097/154187261-b1bcd3a7-eed4-41e2-a50a-4cc5465383fb.png)

Hope that helps to avoid any confusion with repeaters 👍

**Comment by azrikahar** [comment] 2022-02-16 03:03
Update:

Turns out you'll just need to follow the steps I shared to setup the display properly, since there's a logic used to show the 1st item if it's only 1 item:

https://github.com/directus/directus/blob/40ec3229983f22ddf478d6bc191df4dd45ba4500/app/src/displays/formatted-json-value/formatted-json-value.vue#L21-L23

Closing this as it's confirmed to be a display template misconfiguration.

**Closed by azrikahar** 2022-02-16 03:03 UTC
Labels: App, Bug, Documentation

**Comment by eduardoPinto12** [comment] 2022-02-16 11:38
Thanks for the assistance and clarification @azrikahar :+1:
