### ISSUE TITLE
Bug: Date input doesn't seem to update value

### ISSUE THREAD

**Issue by flayks** [directus/directus#8313] opened 2021-09-25 12:01 UTC
### Preflight Checklist

- [x] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When changing the value of a date input, whatever value (day, month or year) is being changed, it is not applied for some reason

https://user-images.githubusercontent.com/273716/134770858-6c350a86-b3c3-40a3-8a71-4faa93019f47.mov

### To Reproduce

Just change the value of a date input

### What version of Directus are you using?

v9-rc94

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Brave

### What operating system are you using?

macOS 11.5.2

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2021-09-25 12:32
Thanks for the detailed description. It's actually a duplicate of #8250, and it's fixed by #8256, slated for upcoming `9.0.0rc.95`.

**Closed by azrikahar** 2021-09-25 12:32 UTC
Labels: Bug (Potential)
