### ISSUE TITLE
Source button on inserting image in Wysiwyg not working correctly

### ISSUE THREAD

**Issue by VanjaRadovanovic** [directus/directus#4410] opened 2021-03-06 14:01 UTC
### Project details
Directus Version: 9.0.0-rc.45
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.15.4

After clicking the Source button the window for selecting image from local machine appears in the back of the current window not allowing me to upload files like shown in image below. I found out that in order to work as intended you need to change z-index below 500 on the .tox.tox-tinymce-aux 

![image](https://user-images.githubusercontent.com/69380881/110209176-40581380-7e8b-11eb-901c-696ef967b3e9.png)

**Comment by rijkvanzanten** [comment] 2021-03-07 16:34
Duplicate of https://github.com/directus/directus/issues/4354

**Closed by rijkvanzanten** 2021-03-07 16:34 UTC
