### ISSUE TITLE
@directus/sdk Read items have wrong type for O2M

### ISSUE THREAD

**Issue by reedoso** [directus/directus#23617] opened 2024-09-10 08:46 UTC
### Describe the Bug

Hello there
Type inference is not working properly for selected fields. 
Look at this example

```
interface Schema {
    root: Root[]
    child: Child[]
}

interface Root {
    id: number;
    // Look here. 
    // This is number[] if it  selected without "deep" fields
    // This is Child[] is it  selected like "deep" fields
    child: number[] | Child[]
}

interface Child {
    id: number;
}
```

`const data = await client.request(readItems('root', {fields: ['id','child']}))`
**Expected type:**  
```
{
  id: number
  child: number[]
}
```
**Type from code**
```
{
  id: number
  child: number | Child[] 
}
```
Look at my query, child selected without deep object.  So it must be just array of numbers.

![image](https://github.com/user-attachments/assets/15b5dd43-60f5-409e-a6fd-1e3e76797403)

### To Reproduce

1) Copy this code or clone this repo
https://github.com/reedoso/broken-inference-directus-sdk/tree/main
```
import { createDirectus, readItems, rest, staticToken } from "@directus/sdk";


interface Schema {
    root: Root[]
    child: Child[]
}

interface Root {
    id: number;
    // Look here. 
    // This is number[] if it  selected without "deep" fields
    // This is Child[] is it  selected like "deep" fields
    child: number[] | Child[]
}

interface Child {
    id: number;
}



const client = createDirectus<Schema>('')
    .with(staticToken('ff'))
    .with(rest())

const data = await client.request(readItems('root', {fields: ['id','child']}))
data[0].
```
2) Look at data[0].child type

### Directus Version

"@directus/sdk": "^17.0.1"

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

It doesnt matter

**Comment by br41nslug** [comment] 2024-09-20 15:13
Duplicate of #22746

**Closed by br41nslug** 2024-09-20 15:13 UTC
Labels: Bug
