### ISSUE TITLE
content pages not loading

### ISSUE THREAD

**Issue by n0script22** [directus/directus#16916] opened 2022-12-24 14:52 UTC
### Describe the Bug

First time i go to content page the entries are showing in table. If i switch between 2 collections the page doesnt show entries any more. The fetch request looks good tho and has data according to the collection. If i reload page entries are showing up.

### To Reproduce

- create new local project
- login and create 2 collections (no matter what fields or config)
- go to content page
(- switching collections already indicate broken page because "NO ITEMS" message is missing)
- create entries on each collection
- switch between collections

### Errors Shown

empty page

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

sqlite3

### What browser are you using?

chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-12-24 17:09
Duplicate of https://github.com/directus/directus/issues/16883

**Closed by rijkvanzanten** 2022-12-24 17:09 UTC
