### ISSUE TITLE
Cannot install Directus anymore using npm init directus-project 

### ISSUE THREAD

**Issue by Pachat** [directus/directus#20146] opened 2023-10-24 07:31 UTC
### Describe the Bug

`npm init directus-project test` runs but ends with
`Error: The server does not support SSL connections`

That was working before.

### To Reproduce

Under Windows 10, 

1. Create a new folder `testdirectus`
2. Add env variables
```
SET DB_CLIENT="pg"
SET DB_HOST="127.0.0.1"
SET DB_PORT="5432"
SET DB_DATABASE="test"
SET DB_USER="postgres"
SET DB_PASSWORD="mypwd"
SET DB_SSL__REJECT_UNAUTHORIZED="false"
SET DB_SSL="false"

```
3. Inside this folder run the CLI: `npm init directus-project test`
4. It ends with `Error: The server does not support SSL connections`
and the preexisting DB `test` stays empty

### Directus Version

Any version

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment] 2023-10-24 09:53
Hey there @Pachat ! :)

I dont use Windows so I tested on my Linux machine but I cant reproduce this.

```bash
$ DB_CLIENT="pg" DB_HOST="127.0.0.1" DB_PORT="5432" DB_DATABASE="test" DB_USER="postgres" DB_PASSWORD="mypwd" DB_SSL__REJECT_UNAUTHORIZED="false" DB_SSL="false" npm init directus-project test
? Choose your database client PostgreSQL / Redshift
? Database Host: 127.0.0.1
? Port: 5432
? Database Name: test
? Database User: postgres
? Database Password: *****
? Enable SSL: No

Create your first admin user:

? Email admin@example.com
? Password *****

Your project has been created at /tmp/test/test.

The configuration can be found in /tmp/test/test/.env

Start Directus by running:
  cd /tmp/test/test
  npx directus start
```

Everything just runs through correctly. Have you made sure to deny this prompt?:

```
? Enable SSL: No
```

**Comment by Pachat** [comment] 2023-10-24 12:42
In Windows, it does not ask nay of the questions `? Choose your database....`
Instead it says `ERROR: "DB_HOST" Environment Variable is missing.`
So, I pass all the DB variables as stated in the OP
But `npm init directus-project` test ends with
```
Error: The server does not support SSL connections
    at Socket.<anonymous> (C:\Direcv10.2.1\test\node_modules\pg\lib\connection.js:77:37)
    at Object.onceWrapper (node:events:629:26)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12)
    at readableAddChunk (node:internal/streams/readable:349:9)
    at Readable.push (node:internal/streams/readable:286:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
× Installing Directus
Error: undefined
npm ERR! code 1
npm ERR! path C:\Direcv10.2.1
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c cdp test

npm ERR! A complete log of this run can be found in: C:\Users\user\AppData\Local\npm-cache\_logs\2023-10-24T12_33_58_104Z-debug-0.log 
```
It looks like that the config passed to `node_modules\pg\lib\connection.js` does not take in account 
`SET DB_SSL="false"` and tries to connect with SSL.

**Comment by adacadabrafr** [comment] 2023-10-25 09:50
Same problem using a VPS running **Ubuntu and node v20.4.0** and also tried and faced the same problem ona VPS running on **Debian with node v18.18.2**

Hope it helps

**Comment by rijkvanzanten** [comment] 2023-10-25 19:43
@adacadabrafr Was it the exact `The server does not support SSL connections` error, or did you run into a more generic problem of it not working in general?

**Comment by adacadabrafr** [comment] 2023-10-25 21:54
```
"DB_CLIENT" Environment Variable is missing.
✖ Installing Directus
Error: undefined
npm ERR! code 1
npm ERR! path /home/cubwolf/agency
npm ERR! command failed
npm ERR! command sh -c create-directus-project agency

npm ERR! A complete log of this run can be found in: /home/cubwolf/.npm/_logs/2023-10-25T09_26_50_082Z-debug-0.log```

**Comment by rijkvanzanten** [comment] 2023-10-26 15:29
Ahh that problem was fixed as part of https://github.com/directus/directus/issues/20166 @adacadabrafr 🙂

**Comment by adacadabrafr** [comment] 2023-10-26 15:38
Yeaaah I will now be able to test the new 10.7 but have To go to family's home for at least a week. 🤔 I'd test it anyway 😜

Thanks for the info 😊

**Comment by eiskalteschatten** [comment] 2023-10-27 12:20
I have exactly the same error. When will the fix be released?

**Comment by Pachat** [comment] 2023-10-27 15:59
@br41nslug I completely understand the open source point of view and adhere to it.
So I'm not asking for anything that I unfortunately can't afford to sponsor even if I'm a modest sponsor.

But I just warn you that because of Directus regressions in successive updates (version x fixes bug A but brings bug B, then version y fixes bug B, but brings bug C, etc. for not saying that version 10.7 is just uninstallable on Self Hosted Custom), the only version I can count on is 16 versions back.

As an excuse, I have a heavy project with many collections with many fields, multiple roles, deep filters and many extensions.
Well, all thanks to the power of Directus for real-world applications.

I would love to take advantage of all the wonderful features that were introduced during your wonderful Leap Week.

All that to say that I will wait patiently for as long as necessary, but really hope to join the lead car anytime soon.

**Comment by rijkvanzanten** [comment] 2023-10-27 16:06
The reason this one bug hasn't been looked at yet is that's it's very likely it's specific to your environment, especially around the networking and database server configuration. The error `Error: The server does not support SSL connections` tells me that there's something going wrong in between the connection on your exact server and your exact database, rather than it being a bigger bug with the init script itself. 

The bug that @adacadabrafr mentioned above would affect people across the board which was resolved and released immediately https://github.com/directus/directus/issues/20166 👍🏻

**Comment by adacadabrafr** [comment] 2023-10-28 10:17
@Pachat you should realize that we have a wonderful tool for free with an incredible community that answer to our problems every time, quickly. In comparison here in France I always had to pay for these kind of services. As an example for my VPS if I want some support I need to pay a minimum of hundred € monthly...

So for free it's a wonderful tool and service. :) 

Then your problem probably comes from the usage of window. I use or Ubuntu or Debian and never face similar issue.

Have you tried on vps or even on macOS if it's local?

And if you think there's an issue try to go deeper in the code and make a pull request. That way you can help the community a way that I can't 😅

Hope you will find a solution :)

**Comment by rijkvanzanten** [comment] 2023-10-31 13:43
@Pachat Seeing your comment on the other issue (https://github.com/directus/directus/issues/20159#issuecomment-1786469841) are you still having this database SSL issue?

**Comment by rijkvanzanten** [comment] 2023-10-31 14:02
I'll close this for now as I believe https://github.com/directus/directus/issues/20159#issuecomment-1786469841 confirms this was resolved, but happy to reopen if that's not the case

**Closed by rijkvanzanten** 2023-10-31 14:02 UTC
Labels: DB: Postgres, Needs More Info

**Comment by Pachat** [comment] 2023-10-31 14:55
@rijkvanzanten No more database SSL issue here.
It happened because when the dialogs where not present it fired Y instead of N.
Thanks for the correction.
