### ISSUE TITLE
Initial Startup Error: relation "geometry_columns" does not exist at character 42

### ISSUE THREAD

**Issue by nathanhere** [directus/directus#7587] opened 2021-08-24 23:35 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Error upon initial docker compose startup of RC91:

```
✨ Applying Add Geometry Config...

ERROR:  relation "geometry_columns" does not exist at character 42
STATEMENT:
WITH geometries as (
	select * from geometry_columns
	union
	select * from geography_columns
)
SELECT f_table_name as table_name
	, f_geometry_column as column_name
	, type as data_type
FROM geometries g
JOIN information_schema.tables t
ON g.f_table_name = t.table_name
AND t.table_type = 'BASE TABLE'
WHERE f_table_schema in ($1)
```

### To Reproduce

`docker compose up`

### What version of Directus are you using?

RC91

### What version of Node.js are you using?

14.17.4

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker Compose

**Comment by shi-rudo** [comment] 2021-08-25 12:36
same here, happened on upgrade from RC90 to RC91. since this is a production system, i can unfortunately not running example.

```console
2021-08-25 12:31:07.128 UTC [739] STATEMENT:
postgres |       WITH geometries as (
postgres |         select * from geometry_columns
postgres |         union
postgres |         select * from geography_columns
postgres |       )
postgres |           SELECT f_table_name as table_name
postgres |         , f_geometry_column as column_name
postgres |         , type as data_type
postgres |           FROM geometries g
postgres |           JOIN information_schema.tables t
postgres |             ON g.f_table_name = t.table_name
postgres |             AND t.table_type = 'BASE TABLE'
postgres |           WHERE f_table_schema in ($1)
postgres |
```

**Comment by Oreilles** [comment] 2021-08-31 18:35
@nathanhere does the error occur before the migrations complete ?
Have you tried running migrations first, then starting the server ?

**Comment by nathanhere** [comment] 2021-09-01 04:23
@Oreilles here's a fuller log:

```
database  | 2021-09-01 04:21:21.988 UTC [1] LOG:  database system is ready to accept connections
directus  | 04:21:28 ✨ Initializing bootstrap...
directus  | 04:21:28 ✨ Installing Directus system tables...
directus  | 04:21:30 ✨ Running migrations...
directus  | ✨ Applying Remove Collection Foreign Keys...
directus  | ✨ Applying Remove System Relations...
directus  | ✨ Applying Remove System Collections...
directus  | ✨ Applying Remove System Fields...
directus  | ✨ Applying Add Cascade System Relations...
directus  | ✨ Applying Change Webhook URL Type...
directus  | ✨ Applying Add Relations Sort Field...
directus  | ✨ Applying Remove Locked Fields...
directus  | ✨ Applying Webhooks Collections Text...
directus  | ✨ Applying Add Refresh Interval...
directus  | ✨ Applying Make Filesize Nullable...
directus  | ✨ Applying Add Collections Accountability...
directus  | ✨ Applying Remove Files Interface...
directus  | ✨ Applying Rename Interfaces...
directus  | ✨ Applying Restructure Relations...
directus  | ✨ Applying Add Foreign Key Constraints...
directus  | ✨ Applying Add System Fk Triggers...
directus  | ✨ Applying Add Collections Icon Color...
directus  | ✨ Applying Add Deep Clone Config...
directus  | ✨ Applying Change Filesize Bigint...
directus  | ✨ Applying Add Conditions to Fields...
directus  | ✨ Applying Add Default Folder...
directus  | ✨ Applying Replace Groups...
directus  | ✨ Applying Add Required to Fields...
directus  | ✨ Applying Update Groups...
directus  | ✨ Applying Change Image Metadata Structure...
directus  | ✨ Applying Add Geometry Config...
database  | 2021-09-01 04:21:32.060 UTC [83] ERROR:  relation "geometry_columns" does not exist at character 42
database  | 2021-09-01 04:21:32.060 UTC [83] STATEMENT:
database  | 			WITH geometries as (
database  | 				select * from geometry_columns
database  | 				union
database  | 				select * from geography_columns
database  | 			)
database  | 	        SELECT f_table_name as table_name
database  | 				, f_geometry_column as column_name
database  | 				, type as data_type
database  | 	        FROM geometries g
database  | 	        JOIN information_schema.tables t
database  | 		        ON g.f_table_name = t.table_name
database  | 		        AND t.table_type = 'BASE TABLE'
database  | 	        WHERE f_table_schema in ($1)
database  |
directus  | 04:21:32 ✨ Setting up first admin role...
directus  | 04:21:32 ✨ Adding first admin user...
directus  | 04:21:32 ✨ Done
directus  | 04:21:38 ⚠️  PUBLIC_URL is not a valid URL
directus  | 04:21:39 ✨ Server started at port 8055
```

**Comment by Oreilles** [comment] 2021-09-01 16:01
Is you database deployed from within your docker-compose file ? Could you provide the compose file you're using ? Here's a sample one that works fine:

```yml
version: '3.2'
services:
  directus-cache:
    container_name: directus-cache
    image: redis:6
  
  directus-database:
    container_name: directus-database
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres

  directus:
    container_name: directus
    image: directus/directus:9.0.0-rc.91
    depends_on:
      - directus-cache
      - directus-database
    ports:
      - '80:80'
    environment:
      PORT: '80'
      PUBLIC_URL: 'http://localhost/'
      KEY: A3720CC3-2901-49CA-AED4-6E0FAD114EB9
      SECRET: yyUN4HXpSCxV2uwz7QWbhlylPqcfB6PE
      CACHE_ENABLED: 'true'
      CACHE_STORE: redis
      CACHE_REDIS: redis://directus-cache:6379
      DB_CLIENT: pg
      DB_HOST: directus-database
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
```

**Comment by rijkvanzanten** [comment] 2021-09-01 16:03
@nathanhere @shi-rudo It looks like that error is logged from the _database_, not Directus itself. It could be that Directus is trying that query in a try/catch, and handling the error just fine. From what I can tell in the logs printed by Directus, everything went through as expected. Does this issue prevent Directus from running?

**Comment by shi-rudo** [comment] 2021-09-01 19:10
> @nathanhere @shi-rudo It looks like that error is logged from the _database_, not Directus itself. It could be that Directus is trying that query in a try/catch, and handling the error just fine. From what I can tell in the logs printed by Directus, everything went through as expected. Does this issue prevent Directus from running?

there doesn't seem to be any major problems. 

i do have a problem that a collection can't be opened (page not found). although everything exists in the postgres database. However, at the moment I can't say for sure if these two issues are related.

**Comment by nathanhere** [comment] 2021-09-01 22:36
@rijkvanzanten As far as I can tell, Directus is running fine. I guess a slight concern I had is the potential for background side-effects, under the right conditions, as a result of the initial start up error.

**Comment by nathanhere** [comment] 2021-09-01 22:38
@Oreilles docker compose file below:

```
version: '3.8'

services:

  database:
    container_name: database
    image: postgres:13
    restart: always
    volumes:
      - ./database/13:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"

  cache:
    container_name: cache
    image: redis:6
    restart: always
    networks:
      - directus

  directus:
    hostname: directus
    container_name: directus
    image: directus/directus:9.0.0-rc.91
    restart: always
    ports:
      - 8055:8055
    volumes:
      # By default, Directus images writes uploads to /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume When using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: 'f2159a87-3d84-4ba3-a555-406031634af7'
      SECRET: '483aa980-9a1b-4332-925c-5e797fd08d30'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      CACHE_ENABLED: 'false'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'
      CACHE_AUTO_PURGE: "true"
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'

networks:
  directus:
    name: directus
```

**Comment by nathanhere** [comment] 2021-09-03 15:37
It seems I am getting this error upon deletion actions as well:

```
directus  | 15:33:55 ✨ request completed DELETE 200 /collections/blog_nav 885ms
database  | 2021-09-03 15:33:55.482 UTC [468] ERROR:  relation "geometry_columns" does not exist at character 42
database  | 2021-09-03 15:33:55.482 UTC [468] STATEMENT:
database  | 			WITH geometries as (
database  | 				select * from geometry_columns
database  | 				union
database  | 				select * from geography_columns
database  | 			)
database  | 	        SELECT f_table_name as table_name
database  | 				, f_geometry_column as column_name
database  | 				, type as data_type
database  | 	        FROM geometries g
database  | 	        JOIN information_schema.tables t
database  | 		        ON g.f_table_name = t.table_name
database  | 		        AND t.table_type = 'BASE TABLE'
database  | 	        WHERE f_table_schema in ($1)
database  |
directus  | 15:33:56 ✨ request completed GET 200 /collections?limit=-1 621ms
directus  | 15:33:59 ✨ request completed DELETE 200 /collections/blog_nav_blogs_1 121ms
database  | 2021-09-03 15:34:00.043 UTC [464] ERROR:  relation "geometry_columns" does not exist at character 42
database  | 2021-09-03 15:34:00.043 UTC [464] STATEMENT:
database  | 			WITH geometries as (
database  | 				select * from geometry_columns
database  | 				union
database  | 				select * from geography_columns
database  | 			)
database  | 	        SELECT f_table_name as table_name
database  | 				, f_geometry_column as column_name
database  | 				, type as data_type
database  | 	        FROM geometries g
database  | 	        JOIN information_schema.tables t
database  | 		        ON g.f_table_name = t.table_name
database  | 		        AND t.table_type = 'BASE TABLE'
database  | 	        WHERE f_table_schema in ($1)
database  |
directus  | 15:34:00 ✨ request completed GET 200 /collections?limit=-1 527ms
database  | 2021-09-03 15:34:14.073 UTC [30] WARNING:  could not open statistics file "pg_stat_tmp/global.stat": Operation not permitted
```

**Comment by dstoyanoff** [comment] 2021-09-27 08:25
I am getting this error on trying to use the new migrations functionality. Using the old approach works just fine, but enabling the new schema migration breaks. Directus is not able to run the migration, thus the instance is empty afterwards. 

This seems to be the cause for: #8311 #8176

**Comment by rijkvanzanten** [comment] 2021-09-27 22:36
Fixed in https://github.com/directus/directus/pull/8335

**Closed by rijkvanzanten** 2021-09-27 22:36 UTC
Labels: DB: Postgres, Docker, Needs More Info
