### ISSUE TITLE
Bookmarks from Admin Panel Issue

### ISSUE THREAD

**Issue by JREAM** [directus/directus#1683] opened 2017-07-11 13:59 UTC
## Version Info
  - Directus version and branch: master (6.4)
  - PHP version: 7.0
  - MySQL version:  Percona 5.7 (strict mode disabled)
  - Web server: (Ex. Apache, nginx or IIS?)  Apache
  - OS name and version: Ubuntu 16.04 x64

## Expected Behavior
- Take me to the correct Bookmark
- Do not popup missing page, I am the Admin.

## Actual Behavior
- **Part 1 Below** - Bookmark returns one to the same URI even if changed
- **Part 2 Below** - No Permissions/Does not Exist Bookmark for existing area.

## Steps to Reproduce
**Part 1**

1: Create a bookmark for Global Settings
2: `You don't have permission to view that page or it doesn't exist`

Same Topic, this way fails if you get a bookmark to work anywhere from the Admin panel sections:

**Part 2**

1: Go to Admin Settings > Users
2: Create a Bookmark, call it `Admin`
3: Delete the Bookmark
4: Go to Admin Settings (But not Users)
5: Create Bookmark, call it `Admin`
6: Problem: It seems to take you to the first bookmark.

*Problem:* It seems like Bookmarks are ONLY for the Tables or it's redirecting there. It would be nice to have `Admin Settings` Always available or Bookmarkable.

**Comment by WellingGuzman** [comment] 2017-07-11 17:58
Hey @JREAM, when you say "Admin Settings > Users" you mean `/users` page?

**Comment by benhaynes** [comment] 2017-07-20 03:42
I think he means `/settings/permissions/1` ... i get the error too

**Comment by WellingGuzman** [comment] 2017-08-04 20:35
Closed by https://github.com/directus/directus/commit/457e0a28fd4561fefc004f876adbe7ebadd09b89

**Comment by hybridvision** [comment] 2017-08-15 10:46
@WellingGuzman: Thanks for the fix but I don't think it is fully working - after upgrading I can bookmark some settings pages but if I try to bookmark `/settings` with the name of `Admin` for example, the link doesn't work - it takes me to a table view.

Strangely, if I bookmark `settings/permissions`, it works but if I bookmark `settings/tables`, it doesn't work.

I've also noticed that the `active` class is sometimes applied to the wrong link in the sidebar (ie. not the bookmark link I just clicked on). This only seems to happen on the bookmark links that work correctly... I've tested this on the latest build and also the latest develop branch and it's the same. It seems quite buggy but maybe there's something I'm missing in my setup.

**Comment by hybridvision** [comment] 2017-08-15 11:48
I did some more testing and it seems that when I have a space in the bookmark name, it doesn't work correctly: eg. `Tables Admin` for `settings/tables` fails but `Tables_Admin`as the name makes the link work.

For the `active` class being applied incorrectly, it seems to be when you have multiple bookmark references under the same path - eg. `settings/tables`and `settings/permissions`.

**Comment by WellingGuzman** [comment] 2017-08-15 22:03
Hey @hybridvision can you share your schema? it works for me with or without space.

What I am working on is the active part, which always enabled the first one if they start with the same path.

**Comment by hybridvision** [comment] 2017-08-17 14:09
Hi @WellingGuzman, sorry I missing your message earlier. My schema is the default from a fresh install of Directus into an empty database. I don't have access to that computer at the moment but I can try to share it when I get back.

I'm wondering if it is somehow related to OS/DB server version because I don't see these bookmark problems here on a newer OS (but older DB server version). It's similar to the difference in behaviour described here: https://github.com/directus/directus/issues/1741#issuecomment-323081213

**Comment by WellingGuzman** [comment] 2017-08-24 05:40
Hey @hybridvision, I tried with MariaDB 10.2 on Ubuntu 14.04 x64, and it's working as expected.

Do you have any specific steps to reproduce this or an exact OS/DB to reproduce this issue?

**Comment by benhaynes** [comment] 2017-08-30 14:12
Hey @hybridvision – let us know about this one when you have a chance! Since it seems to be related to an older OS version we can't seem to replicate. I'm going to close this until we have specific OS/DB versions to reproduce – also, these versions should be new enough to warrant a fix ;)

**Closed by benhaynes** 2017-08-30 14:12 UTC
Labels: Can Not Duplicate
