### ISSUE TITLE
Updated info won't reflect immediately on display , but update is ok  . 

### ISSUE THREAD

**Issue by kstang** [directus/directus#14176] opened 2022-06-29 08:17 UTC
### Describe the Bug

When update from master record in 1 to many , then  many to 1 relation , the updated information cannot be reflected properly 

**Here are my relations :** 

**Sclient (Client Information)** 
	1 to many Scclient Contact 
	1 to many Scclient Address
	
**Sclient Contact (Client Contact )** 
	many to 1 sccode 
	
**Sclient Address (Client Address)** 
	many to 1 sccode 
	
**Sccode (Contact and Address Type )** 

when I attempt to update the Sclient -> Sclient Contact -> Scode , after I back to the Sclient screen , the update info cannot reflect in the sclient screen immediately . 

Please find my attached video for details . 

https://user-images.githubusercontent.com/8650432/176386256-8e3f0355-9df2-4cd3-88e7-1c7d2e542810.mp4
 

 

### To Reproduce

simple schema below can verify : 

master_test <-> master_info_test (1 to many ) 
master_info_test <-> master_info_type (many to 1 ) 

CREATE TABLE public.master_test (
	clientid varchar(255) NOT NULL,
	status varchar(255) NOT NULL DEFAULT 'draft'::character varying,
	sort int4 NULL,
	user_created uuid NULL,
	date_created timestamptz NULL,
	user_updated uuid NULL,
	date_updated timestamptz NULL,
	client_name varchar(255) NULL,
	CONSTRAINT master_test_pkey PRIMARY KEY (clientid),
	CONSTRAINT master_test_user_created_foreign FOREIGN KEY (user_created) REFERENCES public.directus_users(id),
	CONSTRAINT master_test_user_updated_foreign FOREIGN KEY (user_updated) REFERENCES public.directus_users(id)
);

CREATE TABLE public.master_info_test (
	id serial4 NOT NULL,
	status varchar(255) NOT NULL DEFAULT 'draft'::character varying,
	sort int4 NULL,
	user_created uuid NULL,
	date_created timestamptz NULL,
	user_updated uuid NULL,
	date_updated timestamptz NULL,
	address varchar(255) NULL,
	clientid varchar(255) NULL,
	info_type int4 NULL,
	CONSTRAINT master_info_test_pkey PRIMARY KEY (id),
	CONSTRAINT master_info_test_clientid_foreign FOREIGN KEY (clientid) REFERENCES public.master_test(clientid) ON DELETE SET NULL,
	CONSTRAINT master_info_test_info_type_foreign FOREIGN KEY (info_type) REFERENCES public.master_info_type(id) ON DELETE SET NULL,
	CONSTRAINT master_info_test_user_created_foreign FOREIGN KEY (user_created) REFERENCES public.directus_users(id),
	CONSTRAINT master_info_test_user_updated_foreign FOREIGN KEY (user_updated) REFERENCES public.directus_users(id)
);

 

CREATE TABLE public.master_info_type (
	id serial4 NOT NULL,
	status varchar(255) NOT NULL DEFAULT 'draft'::character varying,
	sort int4 NULL,
	user_created uuid NULL,
	date_created timestamptz NULL,
	user_updated uuid NULL,
	date_updated timestamptz NULL,
	"name" varchar(255) NULL,
	value varchar(255) NULL,
	CONSTRAINT master_info_type_pkey PRIMARY KEY (id),
	CONSTRAINT master_info_type_user_created_foreign FOREIGN KEY (user_created) REFERENCES public.directus_users(id),
	CONSTRAINT master_info_type_user_updated_foreign FOREIGN KEY (user_updated) REFERENCES public.directus_users(id)
);

### Errors Shown

No

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 13

### What browser are you using?

chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2022-06-29 13:05
Duplicate of https://github.com/directus/directus/issues/10647

**Closed by rijkvanzanten** 2022-06-29 13:05 UTC
