### ISSUE TITLE
[Insights]: when Group Precision is day, the statistics data do not match the corresponding time.

### ISSUE THREAD

**Issue by zhujiageng** [directus/directus#18809] opened 2023-06-04 10:14 UTC
### Describe the Bug

when Group Precision is hour, the statistics data match the corresponding time.
![image](https://github.com/directus/directus/assets/103102265/313f8d03-4bda-4ca5-8626-1f9bc0302bec)

when Group Precision is day, the statistics data do not match the corresponding time.
The first user entered at 10pm on Thursday, but the statistical data shows that there were already 103 users at 8am on Thursday morning.
![image](https://github.com/directus/directus/assets/103102265/f03385d9-d023-409d-a3ad-a1071025a46a)

### To Reproduce

insert data at 10:00 PM, then set Group Precision to day

### Directus Version

10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-07-09 15:24
Are you using a `datetime` or `timestamp` field for that data?

**Comment by zhujiageng** [comment] 2023-07-10 06:08
@rijkvanzanten yes, i use the default date_created field, it is timestamp.

**Comment by rijkvanzanten** [comment] 2023-07-10 09:28
The insights panels currently use `vue-i18n`'s `d` function to format the date for that usage, which will show the values in your local timezone. That's where the difference comes from. It says "2 AM" for saved values of 00:00, as I'm currently in the +2 timezone (CEST).

Closing this as I believe it's working as intended, but happy to reopen if I'm wrong! Feel free to open a new feature request if support for non-local values is something you'd like to see 🙂

**Comment by zhujiageng** [comment] 2023-07-11 07:01
Thank you, I think what you said is reasonable.

**Comment by zhujiageng** [comment] 2023-08-05 12:15
I'd like to make a request. Can we calculate daily data based on the local time zone? Our suppliers produce daily reports based on their local time zone, while Directus generates daily reports in UTC. As a result, the data from both sides don't match. My local time zone is UTC+8, so the data from Directus is from 4 PM local time to 4 PM the next day, not from midnight to midnight local time.

**Comment by zhujiageng** [comment] 2023-08-05 12:20
The same problem also occurs on the collection page. When I query data for the 2nd, I want to see the data for that day in the local time zone. But actually, the data I get is for the 2nd in the UTC time zone. Since I'm in the UTC+8 zone, the results also include some data before 8 AM on the 3rd local time. This doesn't seem quite right. Is it possible to query based on the local time zone?

**Comment by rijkvanzanten** [comment] 2023-08-07 17:58
Feel free to [open a new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) @zhujiageng! A semi-related bug report isn't really the right place to discuss that 🙂

**Closed by rijkvanzanten** 2023-08-07 17:58 UTC
