### ISSUE TITLE
npx schema ERROR: Cannot read properties of null (reading 'meta')

### ISSUE THREAD

**Issue by co2nunes** [directus/directus#18805] opened 2023-06-02 16:28 UTC
### Describe the Bug

After creating a snapshot on a development server, I moved the file into staging and run
npx directus schema apply ./path/to/snapshot.yaml
npx directus schema apply --yes ./path/to/snapshot.yaml
npx directus schema apply --dry-run ./path/to/snapshot.yaml

I am using Docker. Should I do $ **docker exec** _npx directus schema apply_?

````
ERROR: Cannot read properties of null (reading 'meta')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'meta')",
      "stack":
          TypeError: Cannot read properties of null (reading 'meta')
              at filterCollectionsForCreation (file:///home/user/.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/api/dist/utils/apply-diff.js:101:43)
              at Array.filter (<anonymous>)
              at file:///home/user/.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/api/dist/utils/apply-diff.js:122:58
              at /home/user/.npm/_npx/ebcc468e2b0f2b61/node_modules/knex/lib/execution/transaction.js:221:22
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
````

### To Reproduce

`$ npx directus schema snapshot --yes ./snapshot.yaml

`Use Docker Compose
node -v
v18.12.1

Run any of the 3 commands above

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-06-05 09:31
Duplicate of #18774

**Closed by br41nslug** 2023-06-05 09:31 UTC
