### ISSUE TITLE
Directus custom layout extension not accessible / selectable / viewable

### ISSUE THREAD

**Issue by bryantcarlos** [directus/directus#6648] opened 2021-07-04 17:38 UTC
### Describe the Bug

After creating, building, and placing the generated index.js file from the dist folder into the /extensions/layouts/custom directory, followed by starting Directus, the custom layout cannot be accessed even though there is a log that says the custom layout has already loaded.

However, there is this log, just before the loaded extension log -
'D:Projectsplaygroundextensionslayoutscustomindex.js' is imported by virtual:entry, but could not be resolved – treating it as an external dependency

![directus_logs](https://user-images.githubusercontent.com/59461140/124395889-3fe86000-dd39-11eb-80d9-9855f99c4628.png)

### To Reproduce

1) Follow these exact steps from the doc below, until the very end -
https://docs.directus.io/guides/layouts/
- The contents of index.js and layout.vue are exactly the same as the example in the docs

2) Start up Directus with npx directus start
 - Log is shown that custom layout has been recognized and loaded

3) Access http://localhost:8055/, and login into an account with full privileges

4) Navigate into a collection

5) Clicking on the Layout Options, and then Layout dropdown on the right side panel

6) The built in layouts are listed, but the custom layout is not listed

### What version of Directus are you using?

Directus version 9.0.0-rc.83

### What version of Node.js are you using?

Node.JS version 14.17.0

### What database are you using?

MySQL version 8.0.25

### What browser are you using?

Chrome build version 91.0.4472.124

### What operating system are you using?

Windows 10 build version19043.1052

### How are you deploying Directus?

Running locally

**Comment by nickrum** [comment] 2021-07-04 19:19
Duplicate of #6550

**Closed by nickrum** 2021-07-04 19:19 UTC
Labels: Bug (Potential)
