### ISSUE TITLE
Default Boolean is String 

### ISSUE THREAD

**Issue by Penderis** [directus/directus#16023] opened 2022-10-16 15:13 UTC
### Describe the Bug

When I create a new user via the api I exclude the default Muted field which is a boolean. 
If I review it in the interface then it shows up as TRUE (something exists)
My returned user from the create looks like this: 
![image](https://user-images.githubusercontent.com/3405854/196042932-7ba930c9-4f18-4329-95ef-edd595b67c71.png)
<br>

For now, I am just explicitly setting the field when creating via API but there is not way to have it be default false in the interface without going back to unchecking it. 

### To Reproduce

This is not limited to API because creating the user without checking the muted field will also fill a string which makes it TRUE instead of the default FALSE <br>
![image](https://user-images.githubusercontent.com/3405854/196043056-afe17136-3f41-4991-b593-f9f8c31f7263.png)
<br>
![image](https://user-images.githubusercontent.com/3405854/196043122-9d825c5b-07b2-48b8-95d6-b3e44d1cc0b9.png)
<br>

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16 LTS

### What database are you using?

SQlite 3 Latest

### What browser are you using?

Brave - Chromium

### How are you deploying Directus?

node with PM2 behind Nginx

**Comment by licitdev** [comment] 2022-10-17 04:28
What's the value of `special` in `directus_fields` of `Muted`?
Did you create the field in the database directly or through the Data Studio?

There should be a value of `cast-boolean`. The issue you've faced may be related to https://github.com/directus/directus/issues/15335. You'll have to manually populate the `special` column if the value is missing.

**Comment by azrikahar** [comment] 2022-10-17 04:42
I believe this is the same issue as #14356 where the root cause stems from Knex's sqlite3 dialect 👍 Closing this in favor of said issue.

**Closed by azrikahar** 2022-10-17 04:42 UTC
Labels: API, DB: SQLite, Needs More Info, Bug (Potential)
