### ISSUE TITLE
Unhiding field with an OR conditional based on other dropdown field does not work

### ISSUE THREAD

**Issue by JosephCarrington** [directus/directus#18072] opened 2023-04-05 18:30 UTC
### Describe the Bug

If you want to only show a field if another dropdown field has a value from a list of values, the OR condition does not appear to fire, so the field does not unhide.

### To Reproduce

1. Fresh instance
2. Create a new collection type
3. Add a dropdown field named fooBarOrBaz, with the following values (Foo, Bar, Baz)
4. Add an input field named conditionallyHiddenField, marked as hidden
5. To the input field, add a condition
6. To the condition, add an OR group
7. Under the or grouping, add a filter for fooBarOrBaz equals Foo
8. Under the or grouping, add a filter for fooBarOrBaz equals Bar 
9. To the condition, make the `hide field` checkbox unchecked (no mark, neither a check or a dash)

Now, when you go to create a new record, you will see that no value of `fooBarOrBaz` unhides `conditionallyHiddenField`

### Hosting Strategy

Directus Cloud

**Comment by koksikus** [comment] 2023-04-05 18:56
Duplicate of #17242??

**Comment by JosephCarrington** [comment] 2023-04-05 21:02
No groups are involved in my bug, FWIW

**Comment by paescuj** [comment] 2023-04-19 11:25
We haven't been able to reproduce this with the latest version (9.25.1), which could mean that the issue has been solved in the meantime and that the fix will also be available in Directus Cloud with the next update in the coming days.
Therefore, I'll close this for now but if you think this is actually still an issue with the latest version, then please do not hesitate to comment.

**Closed by paescuj** 2023-04-19 11:25 UTC
