### ISSUE TITLE
Date change in collection wont trigger the update action 

### ISSUE THREAD

**Issue by fballan93** [directus/directus#5264] opened 2021-04-26 20:07 UTC
When updating date element in any collection and submit the changes it wont accept it and the check mark button wont take the changes 

Exact steps to reproduce this issue:
1- create a collection with  data model of a string field and Date field e.g. posting Date and Remark collection named comments 
2- add this collection(comments) into another collection with M2M relation e.g posts collection
3  - adding a new comment items in posts collection will work normally 
4- open that item of posts again and edit the Posting date and click on the checkmark to apply the edits 
5- The item will not update and the check mark( submit) button will load with no feedback or redirect 

Directus v9.0 rc60
Azure app service instance 
MySQL DB
npx deployment

Update 27/04/2021
<img width="807" alt="CleanShot 2021-04-27 at 13 42 59@2x" src="https://user-images.githubusercontent.com/9093101/116228922-94ca9180-a75e-11eb-8942-d4c8b86a0f58.png">

This is the error i face when i try to replicate the scenario mentioned above

**Comment by rijkvanzanten** [comment] 2021-04-27 21:32
Duplicate of https://github.com/directus/directus/issues/5070

**Closed by rijkvanzanten** 2021-04-27 21:32 UTC
Labels: Duplicate
