### ISSUE TITLE
SQLite login error "Invalid foreign key."

### ISSUE THREAD

**Issue by w7shdev** [directus/directus#4489] opened 2021-03-11 16:20 UTC
Hi, 😄 
I created a new project and the DB type is SQLite and The login did not work.  When I  started the directus but I could not login so I got a meesage of ` Unexpected Error `. Then I used insomnia to get the access token and it return back an error seems to be related to SQL query. 

![sqlite](https://user-images.githubusercontent.com/60617324/110818851-16498b80-82a7-11eb-9656-6705c7c50c34.jpg)

3) Your environment:
OS :  Windows 10 Home version 1909
    What version of Directus you are using. ` "directus": "^9.0.0-rc.48",`
    Which DBMS are you using (Sqlite) 
    Which deployment are you using npx
    What browser are you using (Edge `Version 89.0.774.45`).

**Comment by rijkvanzanten** [comment] 2021-03-12 19:55
This is the foreign key constraint from `directus_activity` to `directus_collections` that isn't properly deleted by Knex in migration `20201028A`. This is caused by https://github.com/knex/knex/issues/4369.

Closed in favor of https://github.com/knex/knex/issues/4369

**Comment by rijkvanzanten** [comment] 2021-03-14 16:29
I'll leave this open for visibility, even if it's not something we can fix in directus itself

**Comment by w7shdev** [comment] 2021-03-14 18:57
@rijkvanzanten  I had a previous version installed v9.0.0-rc.45, the SQLite and it's working. 
I hope this will give some insight to identify the issue, BTW thanks

**Comment by rijkvanzanten** [comment] 2021-03-15 00:36
> I had a previous version installed v9.0.0-rc.45, the SQLite and it's working.
> I hope this will give some insight to identify the issue, BTW thanks

Yeah! Primary key support wasn't enabled explicitly in sqlite, so the error didn't surface before, as SQLite wasn't checking the keys to begin with..

**Comment by rijkvanzanten** [comment] 2021-04-08 21:05
This has since been fixed and released in knex ✨

**Closed by rijkvanzanten** 2021-04-08 21:05 UTC
Labels: API, Bug, DB: SQLite
