### ISSUE TITLE
Token authentication fails with @directus/sdk (auth.static method only)

### ISSUE THREAD

**Issue by Toilal** [directus/directus#12644] opened 2022-04-08 15:04 UTC
### Describe the Bug

I just upgrade to lastest directus server and @directus/sdk library, but token authentication fails to authenticate properly when using `auth.static(token)` method.

### To Reproduce

Configure a token on a user, and run this script.

```typescript
const sdk = new Directus('http://localhost:8080')
await sdk.auth.static('token')
await sdk.activity.readByQuery({
      limit: 1,
      sort: ['-timestamp'],
      filter: { _and: filters },
      fields: ['action', 'collection', 'timestamp', 'user.first_name', 'user.last_name'],
      meta: 'total_count'
    })
```

### Errors Shown

You don't have permission to access this.

### What version of Directus are you using?

v9.8.0

### What version of Node.js are you using?

v16.14.2

### What database are you using?

PostgreSQL 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by Toilal** [comment] 2022-04-08 15:10
It seems the proper way to authenticate with token is through constructor, `auth.static` method doesn't work properly. Is it expected ?

```typescript
// This work using options from constructor
sdk = new Directus(config.url, {
  auth: {
    staticToken: config.token
  }
})
```

**Comment by azrikahar** [comment] 2022-04-08 15:46
> Is it expected, maybe it should be removed ?

Granted I haven't look into this yet, but I'm pretty sure it's not expected. Could be linked to #12399.

Out of curiosity and this question may end up not being relevant at all, are you running the script server side or client side?

**Comment by Toilal** [comment] 2022-04-08 19:26
I'm running this in NodeJS v16.

**Comment by azrikahar** [comment] 2022-04-11 12:32
I tested this locally but it seems to work (without using constructor etc):

https://user-images.githubusercontent.com/42867097/162739430-410c8c5a-6143-47bb-b990-ea6785ecf008.mp4

Are you able to reproduce this reliably even with a fresh Directus instance? or is this only happening to your specific instance?

**Comment by azrikahar** [comment] 2022-04-11 12:35
Oh and would you mind sharing the `filter` you are using? It'd also be helpful if you can try running it _without_ the filter! 

There is a possibility that it is related to a recent filter issue since I can't seem to reproduce it, but my test is _without_ the filter in your code 🤔

**Comment by rijkvanzanten** [comment] 2022-04-11 13:39
I'm seeing the same behavior as @azrikahar on my end, so I'll close this for now. Happy to keep discussing/debugging tho!

**Closed by rijkvanzanten** 2022-04-11 13:39 UTC
Labels: Needs More Info, Package: sdk, Can't Reproduce

**Comment by dougwithseismic** [comment] 2022-09-03 22:28
> Oh and would you mind sharing the `filter` you are using? It'd also be helpful if you can try running it _without_ the filter!

Just hit this where using a filter causes the same permission error using SDK (I also had to use a constructor).
```javascript
    const { data } = await directus.items('stores').readByQuery({
      filter: {
        slug: {
          _eq: slug
        }
      }
    })
```
