### ISSUE TITLE
SDK: Remove `directus.relations.createMany` method

### ISSUE THREAD

**Issue by paescuj** [directus/directus#5988] opened 2021-06-02 08:04 UTC
With the introduction of https://github.com/directus/directus/pull/5615 it seems like creating multiple relations at once isn't supported anymore.
While this is not a problem in itself, the SDK method `directus.relations.createMany` should be removed.
I've used this method which now returns:
`{"errors":[{"message":"\"value\" must be of type object","extensions":{"code":"INVALID_PAYLOAD"}}]}`

**Comment by rijkvanzanten** [comment] 2021-06-02 13:21
Duplicate of https://github.com/directus/directus/issues/5914

**Closed by rijkvanzanten** 2021-06-02 13:21 UTC
