### ISSUE TITLE
Wrong query being generated after migration

### ISSUE THREAD

**Issue by Kminkjan** [directus/directus#6205] opened 2021-06-11 09:05 UTC
1) The issue and what you expected to happen
    Hello! I've ran the migration tool to migrate from v8 to v9. Most of the API calls are working just fine but I got some 500 INTERNAL_SERVER_ERRORs. It seems to me that some of the queries might nog be generated the right way.

2) Exact steps to reproduce this issue
    I don't know what exactly causes this error, might have something to do with the migration.

3) Your environment:
    What version of Directus you are using.
    v9.0.0-rc.69
    Which DBMS are you using (MySQL 8, Postgres 12, ...).
    MariaDB v10.4.18
    Which deployment are you using (npx, Docker, ...).
    NPX
    What browser are you using (Chrome 87, Safari 14, ...).
    Using postman to do the API calls

4) Any other relevant information we might need to reproduce this issue
``where (`organisation`.`id` in (select *))`` might be causeing some problems?

    ```{
    "errors": [
        {
            "message": "select `organisation_settings`.`id`, `organisation_settings`.`status`, `organisation_settings`.`sort`, `organisation_settings`.`owner`, `organisation_settings`.`created_on`, `organisation_settings`.`modified_by`, `organisation_settings`.`modified_on`, `organisation_settings`.`organisation`, `organisation_settings`.`background_image`, `organisation_settings`.`extenden_config`, `organisation_settings`.`role`, `organisation_settings`.`available_translations`, `organisation_settings`.`organisation_image` from `organisation_settings` where (`organisation_settings`.`id` in (select *)) order by `organisation_settings`.`id` asc limit 100 - ER_NO_TABLES_USED: No tables used",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
   }
And another one
```{
"errors":
 [
        {
            "message": "select `organisation`.`id`, `organisation`.`status`, `organisation`.`sort`, `organisation`.`owner`, `organisation`.`created_on`, `organisation`.`modified_by`, `organisation`.`modified_on`, `organisation`.`organisation_name`, `organisation`.`organisation_group`, `organisation`.`oid`, `organisation`.`database` from `organisation` where (`organisation`.`id` in (select *)) order by `organisation`.`id` asc limit 100 - ER_NO_TABLES_USED: No tables used",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}```

**Comment by rijkvanzanten** [comment] 2021-06-11 14:01
Would you be able to share a database dump, either here or through rijk@directus.io? There's most likely something a little funny with the exact schema either caused by the migration tool, or from a discrepancy in v8 that surfaces this issue in v9 🤔

**Comment by rijkvanzanten** [comment] 2021-06-14 19:16
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-06-14 19:16 UTC
Labels: Needs More Info
