### ISSUE TITLE
Cannot delete a collection using the drop down menu

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11152] opened 2022-01-19 10:35 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Nothing happens when clicking on "Delete collection" in the dropdown menu of the collection in the Data Model's list.
(the Delete button on top of the Detail form of the collection works)

### To Reproduce

Click on "Delete collection" in the dropdown menu of the collection in the Data Model's list

### Errors Shown

No deletion

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-01-19 11:50
Duplicate of #11082

**Closed by azrikahar** 2022-01-19 11:50 UTC
Labels: Bug (Potential)
