### ISSUE TITLE
Files type thumbnail size?

### ISSUE THREAD

**Issue by marshallhenhawke** [directus/directus#24150] opened 2024-12-04 20:13 UTC
### Describe the Improvement

Is there a way to increase the size of a thumbnail in the files field? It currently displays very tiny. For something like a property listing page with many photos it's very hard to see which one I am moving. I have attached a screenshot of what I mean.

Maybe I am missing how to do this? Is it possible to create an extension for this? Any help would be appreciated, I tried the discord but got nothing.

![Screenshot 2024-12-04 at 3 04 42 PM](https://github.com/user-attachments/assets/a44bdff6-6979-4781-89eb-510d41a68658)

**Comment by rijkvanzanten** [comment] 2024-12-04 23:00
Heya! The rows in the a o2m / m2m interface can't be altered in size at the moment. Feel free [to open a new feature request](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) for a more dedicated multiple-images interface, or indeed [create a custom extension](https://docs.directus.io/extensions/creating-extensions.html) .

I'll close this for now as it's not a bug in the platform itself. Thanks!

**Closed by rijkvanzanten** 2024-12-04 23:00 UTC
