### ISSUE TITLE
Error registering extensions if there are too many 

### ISSUE THREAD

**Issue by philipkaiser** [directus/directus#19247] opened 2023-07-26 08:57 UTC
### Describe the Bug

We've run into a not really informative error when adding extensions to our existing system:
```
/directus/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/PendingOperation.js:25
        this.reject(new Error('aborted'));
                    ^

Error: aborted
    at PendingOperation.abort (/directus/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/PendingOperation.js:25:21)
    at /directus/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/Pool.js:208:25
    at Array.map (<anonymous>)
    at /directus/node_modules/.pnpm/tarn@3.0.2/node_modules/tarn/dist/Pool.js:207:53
    at async Client_SQLite3.destroy (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.11.0_sqlite3@5.1.6_tedious@16.1.0/node_modules/knex/lib/client.js:338:9)
    at async Command.bootstrap (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/cli/commands/bootstrap/index.js:37:5)
    at async Command.parseAsync (/directus/node_modules/.pnpm/commander@10.0.1/node_modules/commander/lib/command.js:935:5)

Node.js v18.17.0
```

The error seems to occur when starting the container and there are too many extensions to load. We currently have integrated 7 endpoints and 3 hooks, so 10 total extensions. While trying to integrate another hook the error was thrown. 
However it seems to have nothing to do with the hook itself, as it is registered and working properly if I just remove any other extension. 
So if `hook-one`, `hook-two`, `hook-three` are present in the `extensions/hooks` directory, trying to register `hook-four` throws this error. But if I remove e.g. `hook-three`, `hook-four` can be registered properly and the system runs as expected. If I try to register `hook-three` after that, the error is thrown. It doesn't matter which extension I try to register, as soon as the total amount of extensions hits 11 (in our specific case), it fails. 
On top of that the error only occurs when starting the container after it was stopped. If I put the new extension into the `extensions` directory while the container is running, it will be registered as expected and the info `reloading extensions` gets logged - the hook will also work as expected. Restarting the container after that leads to the error above again. I tried image versions v10.1.0, v10.4.3, v10.5.0. All show the same behavior.

### To Reproduce

Sadly I was not able to create a minimal demo to reproduce the error. If I put many extensions into a fresh directus container, the error does not occur. However the error does occur if I put all of our extensions into the `extensions` directory of a freshly setup container.
As the project where I encountered this issue is a work project for my company I am not allowed to share our extensions to provide reproductive steps.
If I can do anything to make investigating the issue easier, please let me know.

### Directus Version

v10.5.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-07-26 09:16
I suspect this is more caused by what the extensions do than how many there are 🤔

**Comment by br41nslug** [comment] 2023-07-26 11:48
I did run into the following errors while copy pasting a bunch of hooks into my instance
> 2023-07-26 13:38:06 (node:8) MaxListenersExceededWarning: (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit. Event name: before.

Could you check how many `action`/`filter`/`init` hooks are present in these extensions?

**Comment by br41nslug** [comment] 2023-07-26 12:06
Awesome, glad you found the cause 😄 will close this issue then as i dont think we can solve that from our end and rather is a connection limit issue

**Closed by br41nslug** 2023-07-26 12:06 UTC
Labels: Extensions, Needs More Info
