### ISSUE TITLE
Cannot install on new SQL Server database

### ISSUE THREAD

**Issue by aletome** [directus/directus#8454] opened 2021-09-30 12:20 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Installing with the CLI (npx create-directus-project my-project) on a new SQL Server database I get the error:
`sql
[EREQUEST] ALTER TABLE [directus_users] ALTER COLUMN [email] nvarchar(128) null - ALTER TABLE ALTER COLUMN email failed because one or more objects access this column.
`

### To Reproduce

Run
`npx create-directus-project my-project`

### What version of Directus are you using?

latest

### What version of Node.js are you using?

12.22.1

### What database are you using?

SQL Server

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by joselcvarela** [comment] 2021-09-30 12:33
Hello @aletome 
I am closing this since it is a duplicate of https://github.com/directus/directus/issues/8368
Also this is already fixed and will be released on rc96.

**Closed by joselcvarela** 2021-09-30 12:33 UTC
Labels: Bug (Potential)
