### ISSUE TITLE
Manual flow run successfully when actually it failed with error

### ISSUE THREAD

**Issue by grefrit** [directus/directus#18897] opened 2023-06-14 10:55 UTC
### Describe the Bug

When running manual (not async) flow and throw error inside Run Script (it just an example, it relates to other operations too) it shows that "run was successful".

### To Reproduce

Create manual flow and throw error inside any operation, flow will "run successfully"

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-06-14 10:58
Duplicate of #17964

**Closed by br41nslug** 2023-06-14 10:58 UTC
