### ISSUE TITLE
User is unable to do anything if invite token expires

### ISSUE THREAD

**Issue by SeanDylanGoff** [directus/directus#17255] opened 2023-01-20 17:10 UTC
### Describe the Bug

If a user lets their invite link/token expire, they aren't able to re-register with the same E-Mail Address because userService.inviteUser fails with `RECORD_NOT_UNIQUE`.
Resetting password is also not possible, because the user is still in state "invited".

I think the most logical behaviour would be to create a new token and send a new E-Mail whenever someone tries to register with an E-Mail address that is already in state "invited".

### To Reproduce

Invite a user, then try to invite again.

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

-

### What database are you using?

mariadb

### What browser are you using?

chrome

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment] 2023-01-20 18:47
> I think the most logical behaviour would be to create a new token and send a new E-Mail whenever someone tries to register with an E-Mail address that is already in state "invited".

Not that I'm against it, but if we go that route, we might as well not have an expiration time on the invite token at all 🤔 I'm curious what the security implications are for an infinite invite window (if any!).

**Comment by SeanDylanGoff** [comment] 2023-01-20 21:08
> > I think the most logical behaviour would be to create a new token and send a new E-Mail whenever someone tries to register with an E-Mail address that is already in state "invited".
> 
> Not that I'm against it, but if we go that route, we might as well not have an expiration time on the invite token at all 🤔 I'm curious what the security implications are for an infinite invite window (if any!).

As it's a JWT it cannot be revoked afaik (except by changing the secret). That would have to be documented at least.

However, 2 things:
1. It doesn't really solve the problem because the reason I encountered it was the E-Mail got filtered/deleted by user.
2. I don't think having >7 days that it currently is would be a benefit in general - but that's just an opinion

**Comment by rijkvanzanten** [comment] 2023-01-20 21:13
It sounds to me like the invite token itself could be valid forever, but the moment it's used it needs to be compared to whether or not the invite is still open. That way, the invite link can be used as long as needed, but the invite can be rescinded, at which point the token no longer works.

**Comment by rijkvanzanten** [comment] 2023-01-20 21:14
Just for your information:

> As it's a JWT it cannot be revoked afaik (except by changing the secret)

In this case it's slightly different; the JWT is used to know _which_ user is requested to be made active, and whether or not the token was generated by the same API. The moment the token is used however, the user will still be retrieved from the database to validate the invite status; if that status is no longer invited, or the user no longer exists, the token won't do anything either (so it can be considered "revoked" even though the token itself is technically still "valid"). Hope that makes sense!

**Comment by SeanDylanGoff** [comment] 2023-01-20 22:55
> Just for your information:
> 
> > As it's a JWT it cannot be revoked afaik (except by changing the secret)
> 
> In this case it's slightly different; the JWT is used to know _which_ user is requested to be made active, and whether or not the token was generated by the same API. The moment the token is used however, the user will still be retrieved from the database to validate the invite status; if that status is no longer invited, or the user no longer exists, the token won't do anything either (so it can be considered "revoked" even though the token itself is technically still "valid"). Hope that makes sense!

If that's how it is (which is what I suspected anyways) - then I guess the correct (and logical) action would be to just delete or archive all invited users when not wanting to offer public registration anymore.
So I guess unlimited life would be ok. But as I said, there's still the part about users deleting the invite E-Mails (or Spam filters). Happened a lot on a certain project recently 😅

**Comment by ComfortablyCoding** [comment] 2024-01-05 15:40
I am unable to reproduce this issue on the latest version with the reproducible steps listed. Closing this for now as it looks like it was fixed by (#18147). Happy to re-open the issue if more information becomes available. 

P.S. Users can be re-invited via the API or the bulk invite functionality on the users page.

**Closed by ComfortablyCoding** 2024-01-05 15:40 UTC
Labels: Package: @directus/api, Bug
