### ISSUE TITLE
Problem Installing Directus with SQLlite

### ISSUE THREAD

**Issue by carlskii** [directus/directus#4122] opened 2021-02-17 10:18 UTC
Hi, Im using `npx create-directus-project my-project` to create a new Directus project for testing and trying to use the beta SQLite database. However, I'm getting the following error: 

```
npx: installed 53 in 2.657s
? Choose your database client SQLite (Beta)
? Database File Path: /Users/cbourne/development/directus/my-project/data.db

Something went wrong while seeding the database:

[Error] Sqlite does not support alter column.

Please try again
```

```
node -v
v14.15.5

sqlite3 -version
3.32.3 2020-06-18 14:16:19 02c344aceaea0d177dd42e62c8541e3cab4a26c757ba33b3a31a43ccc7d4aapl

OSX 11.1
```

**Comment by benhaynes** [comment] 2021-02-17 15:46
Duplicate of: https://github.com/directus/directus/issues/2948

**Closed by benhaynes** 2021-02-17 15:46 UTC
