### ISSUE TITLE
Relational Triggers are not saved

### ISSUE THREAD

**Issue by admin-navigaite** [directus/directus#17679] opened 2023-03-02 12:18 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

After setting relational triggers on M2O or M2M items they are not saved.
I did change it, hit the checkmark, did a page reload and opened the item again. Fields are always empty and even the database directus_relations didn't change.

Related issue: #9601 

https://user-images.githubusercontent.com/124139327/222426676-0eea3109-81da-4fc3-ac3a-0d1c4f0f943f.mov

### To Reproduce

Create a data model with M2O or M2M item and try to change the relational trigger.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Nitwel** [comment] 2023-03-07 14:52
I was not able to reproduce this. Pease add detailed steps on how to reproduce this and the way you configured directus. I'll close this for now but will open it again if we are able to reproduce it with more information.

**Closed by Nitwel** 2023-03-07 14:52 UTC
Labels: Can't Reproduce

**Comment by admin-navigaite** [comment] 2023-03-11 08:37
I am a little bit confused that you just close obvious bug reports.
I am on the latest version of directus connected to a MariaDB. Maybe that is the problem.

It still exists. The changes are not saved. Even the relation tables in the DB show no changes.
Please reopen!!!

**Comment by Nitwel** [comment] 2023-03-12 16:12
We don't just close obvious bug reports, we close bug reports that we can't reproduce, which often get caused by inproper configuration. As I already said, if you can provide detailed steps on how we can reproduce this bug and we manage to reproduce it, we will start working on a fix for it, but until then, it doesn't make sense for us to have an open issue floating around that might not even exist. 😄

**Comment by admin-navigaite** [comment] 2023-03-12 16:36
What information do you need?
