### ISSUE TITLE
Unable to create new items because of "date_updated" field problems

### ISSUE THREAD

**Issue by PostPollux** [directus/directus#12058] opened 2022-03-09 17:10 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Creating new items of a collection with "date_updated" field fails (with user interface). It just seems to do nothing, when hitting the green checkmark in the top right. 

When I create a collection WITHOUT the "date_updated" field, everything works as expected. No problems with adding new items through the user interface. Also "date_created" has no problems.

### To Reproduce

1. create a collection that has the "date_updated" field.
2. Create an arbitrary field for that collection. e.g. an input field.
3. In the userinterface go to the collection and click on the plus to add your first item to the collection
4. Fill in the data and click on the checkmark button.

### Errors Shown

I get a 400 BadRequest and this is in the response body of the request:

```json
{
   "errors":[
      {
         "message":"\"date_updated\" is required",
         "extensions":{
            "code":"FAILED_VALIDATION",
            "field":"date_updated",
            "type":"required"
         }
      }
   ]
}
```

### What version of Directus are you using?

9.6 (error also happens in 9.5.1)

### What version of Node.js are you using?

probably the one which is shipped with the docker container

### What database are you using?

MariaDB 10.5 but also tried MariaDB 10.7

### What browser are you using?

Firefox 97.0.2, Chrome 99.0.48444.51 (happens with both)

### What operating system are you using?

Windows 10 and Linux Manjaro (happened with both)

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-03-10 03:29
This might be duplicate of or related to #11676 and #10693. Would you mind trying either https://github.com/directus/directus/issues/11676#issuecomment-1050649559 or https://github.com/directus/directus/issues/10693#issuecomment-1001438404 and see whether that resolves it for you?

**Comment by rijkvanzanten** [comment] 2022-04-07 21:25
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2022-04-07 21:25 UTC
Labels: Needs More Info, Bug (Potential)
