### ISSUE TITLE
Unrelated unique error when saving related record through owner because directus is attempting to wrongly update a deep related record

### ISSUE THREAD

**Issue by sxsws** [directus/directus#13466] opened 2022-05-21 07:08 UTC
### Describe the Bug

I have three collections, 
- inventory_movement, 
- inventory_movement_lineitem, 
- inventory_condition_types. 

The tables are:
- Many line items to movement,
- a line item has two conditions, one for the start of the movement and one for the end with each being a m2o so the line item stores the condition id. 
- The conditions table consist of a unique code field and a unique title (2 unique keys, one for each field).

- I can successfully create a movement line item by itself and assign to a movement. In the line items collection view, I can click on the record and edit the start and end condition on the line item successfully.  The display template for the conditions display fine here when it's in the main view. I want to disable the line item creation directly by hiding the collection though.
- I can create a movement and add a new movement line item from the movement form in the side panel. The movement and line item successfully saves. 

However, if I go to the movement to edit by choosing it from the movements collection view, click the relevant o2m line item relation so it opens in the side panel, I see the start and end conditions where one has a broken display template (one of the code or title fields of the condition omitted for a display template of `code: title`). I can choose a different condition on the line item record and click save so the side panel slides out, but when I click save on the movement record I get the error:
```
The following fields have invalid values:

    title: Value has to be unique
```

The only title field in the relations hierarchy is `conditions.title`. There are no unique constraints on movement line item concerning the item conditions.

The data being sent in the patch request which results in a 400:

```
{
	"lineItems": {
		"create": [],
		"delete": [],
		"update": [
			{
				"id": 3,
				"itemConditionEnd": {
					"title": "Used – Poor"
				},
				"itemConditionStart": 5,
				"productCode": "12345",
				"quantity": 2
			}
		]
	}
}
```

For the above request, I updated the itemConditionStart only - it should not be sending a title for the item condition end record! Strangely, it should neither be sending the productCode or quantity as these weren't changed.

This only happens when editing in the side panel through the movement relation.

### To Reproduce

As above.

### Errors Shown

One 400 Patch to an item_movements item page with the data sent as above. Response is the unique title error.

### What version of Directus are you using?

9.10

### What version of Node.js are you using?

12.22.5

### What database are you using?

mariadb

### What browser are you using?

firefox

### How are you deploying Directus?

local

**Comment by br41nslug** [comment] 2022-05-23 07:24
This is a duplicate of #12881 and should be resolved with PR #13151 
If this still persists after updating to 9.11.0 we can reopen this ticket 👍

**Closed by br41nslug** 2022-05-23 07:24 UTC
Labels: Bug (Potential)
