### ISSUE TITLE
`sort` operation doesn't trigger caches auto-purge

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#18788] opened 2023-06-01 08:25 UTC
### Describe the Bug

As you can see in the video below, manual sorting is not working. It seems like the sort value is not saved. This makes it impossible to use.

https://github.com/directus/directus/assets/2291224/27202193-1488-4571-aa04-b3420adc4deb

### To Reproduce

Create a collection with a sort field. Add new items to it and try to manually reorder them.

https://github.com/directus/directus/assets/2291224/82d502af-20e2-4aa1-9aff-1cf99c73a259

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by jaads** [comment] 2023-06-07 13:06
Locally it works fine for me. 

Can you have a look in the network tab in your browsers dev tools and so see what's going on there when you do the sorting?

**Comment by paescuj** [comment] 2023-06-08 13:15
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

Seeing the phpMyAdmin interface I assume you're using MySQL. If the issue still persists, can you add some more information about the database you're using and maybe also the browser?

**Comment by JonathanDoelan** [comment] 2023-06-08 13:42
@paescuj Yes, the issue still persists. My MySQL Version is `5.7`. I’ve tried to reproduce the bug with a postgres database, but with postgres there is no issue. So it must be an issue with `MySQL`?

Please reopen this issue!

**Comment by paescuj** [comment] 2023-06-08 13:55
I'm still not able to reproduce with MySQL 5.7. Which browser are you using?

**Comment by JonathanDoelan** [comment] 2023-06-08 14:39
@paescuj I’ve figured out that it has nothing to do with the database choice, but with the redis cache! As soon as I disable (`CACHE_ENABLED=false`) the cache, sorting works fine (with any db)!

To reproduce use these cache configs:

```.env
CACHE_ENABLED=true
CACHE_STORE=redis
CACHE_REDIS=redis://cache:6379
CACHE_AUTO_PURGE=true
CACHE_TTL=1d
```

So if we look at the docs for the [Cache config options](https://docs.directus.io/self-hosted/config-options.html#cache) we find this line
> CACHE_AUTO_PURGE[2] … Automatically purge the data cache on **create**, **update**, and **delete** actions.

For me it makes totally sense that it does not work `on sort`. Because it seems like the [sort action does not trigger an update](https://docs.directus.io/extensions/hooks.html#action-events). (In other words: it seems like **cache auto purge** is triggered on **create**, **update** and **delete**, but not on **sort**)

So this is a bug and Directus should also auto purge on `sort` or trigger the `update` action on `sort`.

Is there a workaround for now? Can we write an action hook on `(<collection>.)items.sort` and trigger `update` or purge the cache via this hook?

**Comment by rasco** [comment] 2023-06-16 11:54
this is happening to me too. and i'm also using Redis for caching.

**Comment by KayhanB** [comment] 2023-06-22 10:45
same with local cache

**Comment by adiazc9** [comment] 2023-07-10 17:03
It also happens to me in v10.2.1

**Closed** 2023-07-11 08:33 UTC
Labels: Package: @directus/api, Bug, Good First Issue
