### ISSUE TITLE
Value for field \"id\" in collection \"directus_fields\" has to be unique.

### ISSUE THREAD

**Issue by sambitraze** [directus/directus#23355] opened 2024-08-14 14:26 UTC
### Describe the Bug

```json
{
  "errors": [
    {
      "message": "Value for field \"id\" in collection \"directus_fields\" has to be unique.",
      "extensions": {
        "collection": "directus_fields",
        "field": "id",
        "code": "RECORD_NOT_UNIQUE"
      }
    }
  ]
}
```

### To Reproduce

while creating a field in existing model, this error happens

### Directus Version

v11.0.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres

**Comment by rijkvanzanten** [comment] 2024-08-14 19:29
`directus_fields.id` is an auto-increment ID. Seeing you're using Postgres, I'm pretty sure this error is caused by the sequence in postgres not being equal to the highest id currently used in the actual table. This occurs when you import the data from another database without importing the sequence values. 

You can use the following snippet to generate sql that resets the sequence values of auto increment IDs to the latest used values in all tables to resolve this issue:

```sql
SELECT 'SELECT SETVAL(' ||
       quote_literal(quote_ident(PGT.schemaname) || '.' || quote_ident(S.relname)) ||
       ', COALESCE(MAX(' ||quote_ident(C.attname)|| '), 1) ) FROM ' ||
       quote_ident(PGT.schemaname)|| '.'||quote_ident(T.relname)|| ';'
FROM pg_class AS S,
     pg_depend AS D,
     pg_class AS T,
     pg_attribute AS C,
     pg_tables AS PGT
WHERE S.relkind = 'S'
    AND S.oid = D.objid
    AND D.refobjid = T.oid
    AND D.refobjid = C.attrelid
    AND D.refobjsubid = C.attnum
    AND T.relname = PGT.tablename
ORDER BY S.relname;
```

I'll close this as I don't think it's a bug in Directus itself. Happy to reopen and keep discussing if this turns out to be something else 🙂

**Closed** 2024-08-14 19:29 UTC

**Comment by furkankinyas** [comment] 2024-09-29 22:54
ALTER SEQUENCE directus_activity_id_seq1 RESTART WITH NUMBER;
ALTER SEQUENCE directus_revisions_id_seq1 RESTART WITH NUMBER;
ALTER SEQUENCE directus_fields_id_seq1 RESTART WITH NUMBER;

**Comment by gokaybiz** [comment] 2024-10-11 15:07
> `directus_fields.id` is an auto-increment ID. Seeing you're using Postgres, I'm pretty sure this error is caused by the sequence in postgres not being equal to the highest id currently used in the actual table. This occurs when you import the data from another database without importing the sequence values.
> 
> You can use the following snippet to generate sql that resets the sequence values of auto increment IDs to the latest used values in all tables to resolve this issue:
> 
> ```sql
> SELECT 'SELECT SETVAL(' ||
>        quote_literal(quote_ident(PGT.schemaname) || '.' || quote_ident(S.relname)) ||
>        ', COALESCE(MAX(' ||quote_ident(C.attname)|| '), 1) ) FROM ' ||
>        quote_ident(PGT.schemaname)|| '.'||quote_ident(T.relname)|| ';'
> FROM pg_class AS S,
>      pg_depend AS D,
>      pg_class AS T,
>      pg_attribute AS C,
>      pg_tables AS PGT
> WHERE S.relkind = 'S'
>     AND S.oid = D.objid
>     AND D.refobjid = T.oid
>     AND D.refobjid = C.attrelid
>     AND D.refobjsubid = C.attnum
>     AND T.relname = PGT.tablename
> ORDER BY S.relname;
> ```
> 
> I'll close this as I don't think it's a bug in Directus itself. Happy to reopen and keep discussing if this turns out to be something else 🙂

For automatic execution:
`DO $$ 
DECLARE
    setval_query text;
BEGIN
    FOR setval_query IN
        SELECT 'SELECT SETVAL(' ||
               quote_literal(quote_ident(PGT.schemaname) || '.' || quote_ident(S.relname)) ||
               ', COALESCE(MAX(' ||quote_ident(C.attname)|| '), 1) ) FROM ' ||
               quote_ident(PGT.schemaname)|| '.'||quote_ident(T.relname)|| ';' AS setval_query
        FROM pg_class AS S,
             pg_depend AS D,
             pg_class AS T,
             pg_attribute AS C,
             pg_tables AS PGT
        WHERE S.relkind = 'S'  -- S stands for sequences
          AND S.oid = D.objid
          AND D.refobjid = T.oid
          AND D.refobjid = C.attrelid
          AND D.refobjsubid = C.attnum
          AND T.relname = PGT.tablename
        ORDER BY S.relname
    LOOP
        -- Execute each generated SETVAL query
        EXECUTE setval_query;
    END LOOP;
END $$;
`
