### ISSUE TITLE
Drag-and-drop uses resize cursor

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1843] opened 2017-09-28 16:04 UTC
## Version Info
  - Directus version and branch: Develop latest

## Expected Behavior
Hovering a draggable item uses a `grab` cursor. While dragging that changes 

## Actual Behavior
Hovering uses a `resize` cursor, while dragging returns to the default

## Steps to Reproduce
 1. Reorder some items on the list view

## Schema Dump, Logs, or Screenshots
![2017-09-28 11_59_07](https://user-images.githubusercontent.com/9141017/30977295-271b7c46-a445-11e7-8555-cc558b99db39.gif)

**Comment by WellingGuzman** [comment] 2017-10-02 04:53
To clarify where this styles are located to make easier to new contributors to understand, the css is using `row-resize` instead of `drag` or `move` cursor.

The table data-cell is located here:

https://github.com/directus/directus/blob/d3df3475c76b3eadc78c0956b8765d40b27a0dd3/app/templates/tables/table-body.handlebars#L7

The cursor name is located here:

https://github.com/directus/directus/blob/d3df3475c76b3eadc78c0956b8765d40b27a0dd3/assets/sass/_tables.scss#L633

---

Now that we are here, this is also happening in some other places, will be nice if someone can look into the other places such as columns reordering in `Settings > Tables & Input`.

I can give another place where this is happening and is the reordering of columns in table listing right pane (`/tables/<table-name>`).

The css for this columns cursor are located here:

https://github.com/directus/directus/blob/d3df3475c76b3eadc78c0956b8765d40b27a0dd3/assets/sass/_sidebar.scss#L567-L578

And the templates are located here:

https://github.com/directus/directus/blob/d3df3475c76b3eadc78c0956b8765d40b27a0dd3/app/templates/modules/tables/table-right-pane.handlebars#L21-L26

This will be getting a hint where things are and get you started.

**Comment by GarretLefler** [comment] 2017-10-04 06:01
I'm new, but am interested in helping out.

**Comment by rijkvanzanten** [comment] 2017-10-04 16:31
Awesome @GarretLefler! Highly appreciated 😄

Hopefully the above info is enough to get you started.
If you need any other info or help you are very welcome to join us over on Slack: https://slack.getdirectus.com 🙂

**Comment by WellingGuzman** [comment] 2017-10-05 03:51
Thanks @GarretLefler, that would be great, can't wait.

**Comment by GarretLefler** [comment] 2017-10-19 19:31
It's been a while and I have changed the style on the cursor in CSS, but the issue isn't fixed.  I am having trouble troubleshooting and understanding all the code involved with dragging an element.  So, I don't know where I need to change the cursor to move and when to return the cursor back to default.

**Comment by WellingGuzman** [comment] 2017-10-19 19:32
You can read more about in the comment above https://github.com/directus/directus/issues/1843#issuecomment-333440624.

**Comment by WellingGuzman** [comment] 2017-10-25 03:47
Closed by https://github.com/directus/directus/commit/b15fc1c157a79aecc6c9c0a3961e1ea8411d2a06

**Closed by WellingGuzman** 2017-10-25 03:47 UTC
Labels: 5. Trivial, Beginner, good first issue, Hacktoberfest, Interface, Optimization
