### ISSUE TITLE
Unable to update primary key column, succeeds without error but no update applied

### ISSUE THREAD

**Issue by JonasGruenwald** [directus/directus#21101] opened 2024-01-16 13:04 UTC
### Describe the Bug

When trying to update an entry in a collection with the primary key column set up as "manually entered string", the operation appears to succeed (directus shows no error) but the primary key column is not changed.

### To Reproduce

* Set up directus with the latest version as described here: https://docs.directus.io/self-hosted/quickstart.html#create-a-docker-compose-file
* Create a collection `test` with the primary key field (id) set to "Manually entered string"
* Create an entry in test, set `id` to `foo`
* Edit the entry, change `id` to `bar`, click save
* The entry appears to save successfully but the id of the entry is still `foo` (note if there are other fields in the entry, they are updated correctly)

I have no problems updating the primary key column of the same table with a regular SQL query like

```
UPDATE "test" SET id='bar' WHERE "id"='foo';
```

So it does not appear to be an issue/constraint with the database or schema.

I understand that directus may not want to allow updating primary keys for some internal reason, but I think in that case an error message should be show, as the current behaviour is confusing since the edit seems to succeed but does not 

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by mahendraHegde** [comment] 2024-01-18 00:48
@br41nslug  is there a reason to exclude pk while updating? or as a part of this fix should we allow updating PK as long as its not auto increment/generated
https://github.com/directus/directus/blob/5984a32992c8a07f18d18f133340199aa436893c/api/src/services/items.ts#L670

**Comment by br41nslug** [comment] 2024-01-18 16:41
> is there a reason to exclude pk while updating?

If it was i would have closed the issue instead of marking it as issue.

**Comment by ComfortablyCoding** [comment] 2024-01-19 14:25
This is a duplicate of https://github.com/directus/directus/issues/16472, per https://github.com/directus/directus/issues/16472#issuecomment-1660460080 we do not allow updating the PK at this time for the reasons stated there.

**Closed** 2024-01-19 14:25 UTC
Labels: Package: @directus/api, Bug, Regression
