### ISSUE TITLE
triggered to filter the data and then insert it ?

### ISSUE THREAD

**Issue by jinxiaoman** [directus/directus#22445] opened 2024-05-09 07:03 UTC
### Describe the Bug

Please teach how to control the data of the new interface through the process, want to achieve the effect is: 1. call rest api, 2, process intercept, rewrite payload, 3. modify and then insert.
Currently using items.create can be triggered to filter the data and then inserted, will see that two data have been inserted. If the data is updated, the process will be triggered repeatedly, because the listener is items.create. Is there a solution?

### To Reproduce

<img width="1090" alt="image" src="https://github.com/directus/directus/assets/30037936/85e7d3cb-d989-4810-8302-4b8b813bb66d">

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-05-09 07:07
Heya, since this is a question on how to use Directus and not a bug report nor improvement request I'll proceed to close this. Please head over to our [Community Discord Server](https://directus.chat) to as your question over there.

**Closed by hanneskuettner** 2024-05-09 07:07 UTC
