### ISSUE TITLE
Flow  Webhook / Request URL - Error when passing null body in request

### ISSUE THREAD

**Issue by floux-digital** [directus/directus#22146] opened 2024-04-09 21:33 UTC
### Describe the Bug

When making a simple GET request to OpenAI, I am receiving the invalid request message because the body is being passed as null.

It's worth saying that the body in this case is not expected, and generally not even for a GET request where you can use query strings.

It would be interesting to make sending the body optional for this type of request to avoid problems like I'm encountering.

```
"data": {
    "error": {
      "message": "Invalid request to GET /v1/threads/thread_hBTUpmI/runs/run_0D1MRR. You provided a body with this GET request. Either submit a POST request, or pass your arguments in the query string.",
      "type": "invalid_request_error",
      "param": null,
      "code": null
    }
}
```

### To Reproduce

- Create a flow and a Webhook/Request URL step
- Add required values to make a GET to OpenApi services keeping the body empty

### Directus Version

v10.10.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-04-10 09:07
I couldn't reproduce this on my end.
Are you sure the value for the body is indeed empty and doesn't contain any spaces or similar?
It should look like this (placeholder should be shown):
<img width="283" src="https://github.com/directus/directus/assets/5363448/20fd3dc7-22ee-4871-b4a0-c4aba6b464e0">

I'll close this issue for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by paescuj** 2024-04-10 09:07 UTC
Labels: :detective: Needs More Info
