### ISSUE TITLE
Directus keep deleting relations when creating a new relation

### ISSUE THREAD

**Issue by abenz1267** [directus/directus#14487] opened 2022-07-18 11:02 UTC
### Describe the Bug

Directus keeps deleting previously assigned relations when a new relation-field is being added.

### To Reproduce

Following components:

- A
- B
- C

Now A has a one-to-many with B, field "parent_a". I create a new A with a new B. 
Now i create a new relation C one-to-many B, field "parent_b".
The connection between A and B is gone, i now have to re-assign B to A.

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

14.19

### What database are you using?

sqlite

### What browser are you using?

chrome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment] 2022-07-18 11:46
Thanks for opening this issue! However this is a duplicate of an existing issue #13936, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #13936 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-07-18 11:46 UTC
Labels: Duplicate
