### ISSUE TITLE
GraphQL API Access Requires "App Access" or "Admin Access"

### ISSUE THREAD

**Issue by ddcollins** [directus/directus#4738] opened 2021-03-29 22:32 UTC
After bumping Directus version from `rc.44` to `rc.51` our API user no longer has access to the GraphQL API. We had to enable "App Access" on the role the user is assigned to to allow the user to connect again. (Previously only had collection read access)

Was this intentional? Or is there another way to grant GraphQL API access without having to grant the user access to Directus tables (as required by "App Access")?

### Project details
Directus Version: 9.0.0-rc.51
Environment: production
OS: Linux 5.4.0-52-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment] 2021-03-29 22:34
Duplicate of https://github.com/directus/directus/issues/4433, will be tweaked in https://github.com/directus/directus/pull/4625

**Closed by rijkvanzanten** 2021-03-29 22:34 UTC
