### ISSUE TITLE
OAS endpoint generates invalid spec

### ISSUE THREAD

**Issue by NickUfer** [directus/directus#16183] opened 2022-10-26 16:24 UTC
### Describe the Bug

It is impossible to generate valid api clients with the spec which is generated, because it is invalid. 

![image](https://user-images.githubusercontent.com/11254522/198080306-8d741bc2-d9c7-41d0-a685-7560079a8535.png)

I don't know where this is coming from or who didn't read the spec, but this has to be moved to schemas. https://swagger.io/specification/#components-object No generator can do anything with that without 100 workarounds and disabling of validity checks.

```
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 14, Warning count: 0
Errors: 
	-attribute paths.'/utils/export/{collection}'(post).requestBody.content.'application/json'.schema.required is not of type `array`
	-attribute paths.'/users'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/files'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/flows'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/utils/export/{collection}'(post).requestBody.content.'application/json'.schema.#/components/definitions/Query is missing
	-attribute paths.'/presets'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/utils/hash/generate'(post).requestBody.content.'application/json'.schema.required is not of type `array`
	-attribute paths.'/folders'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/utils/hash/verify'(post).requestBody.content.'application/json'.schema.required is not of type `array`
	-attribute paths.'/items/blogs'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/activity'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute components.definitions is unexpected
	-attribute paths.'/permissions'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing
	-attribute paths.'/roles'(get).responses.200.content.'application/json'.schema.#/components/x-metadata is missing

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:604)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:631)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:457)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

I'm sorry to be passive aggressive here but it is just tiresome. Excuse me, I now have to go to the next project, the actual OAS generator, to file at least 3 issues there too or fix them myself directly.

### To Reproduce

Just call /server/specs/oas with any user who has access to this endpoint

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

irrelevant

### What database are you using?

irrelevant

### What browser are you using?

irrelevant

### How are you deploying Directus?

irrelevant

**Comment by rijkvanzanten** [comment] 2022-10-27 02:02
I believe this is a duplicate of and/or tightly related to https://github.com/directus/directus/issues/14869.

> I don't know where this is coming from or who didn't read the spec, but this has to be moved to schemas.

Sorry to be passive aggressive back, but feel free to open a pull request 👍🏻

**Closed by rijkvanzanten** 2022-10-27 02:02 UTC

**Comment by NickUfer** [comment] 2022-10-27 09:04
@rijkvanzanten will do that later 👍🏼 As I know otherwise stuff like this would never get fixed.
