### ISSUE TITLE
Translations bugs

### ISSUE THREAD

**Issue by iksent** [directus/directus#8811] opened 2021-10-15 08:21 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hello, team!
Thank you: this new translations interface is great, it's much more comfortable to use, when you see field value and not "2 items" select.

My scheme:
- Articles M2M Categories
- Articles have Translations (name, slug, ...)
- Categories have Translations (name, and NOT slug)

### To Reproduce

**Bug №1:**
1. Changing categories for articles
2. Can't select Language indicator field "Name" or "Code" for translations (PS: slug is not translatable):
<img width="550px" src="https://user-images.githubusercontent.com/32956521/137455199-d6ed1ffc-9f47-46a7-8f8d-bf563885105a.png"></img>
3. So strange values for default language:
<img width="550px" src="https://user-images.githubusercontent.com/32956521/137455331-c4906e8f-24e4-4d7c-b5d6-fa0aa5f09e36.png"></img>
4. And the result is not so perfect:
![Снимок экрана 2021-10-15 в 13 12 48](https://user-images.githubusercontent.com/32956521/137455377-aa9dc938-4634-45ca-94d1-d1b30ca32d80.png)

**Bug №2:**
1. There are 2 indicators in the list. These are red:
![2021-10-15_13-13-11](https://user-images.githubusercontent.com/32956521/137455828-ba3cd91d-e0d0-44b7-b7f5-bbd703b838a6.jpg)
2. But if you open this article, there are green:
![Снимок экрана 2021-10-15 в 13 13 37](https://user-images.githubusercontent.com/32956521/137455856-0592b967-cf33-4268-9466-96ef1819cdc9.png)

### What version of Directus are you using?

RC97

### What version of Node.js are you using?

14.17.5

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally (production)

**Comment by iksent** [comment] 2021-10-18 06:05
@Nitwel, thanks for the fix for m2m, but there is a problem now:
1) I can't switch back to "related values" for m2m, that has "translations" display:
![Снимок экрана 2021-10-18 в 11 03 06](https://user-images.githubusercontent.com/32956521/137677243-6ee25b83-ac7f-4dc6-8074-f0fd9a3486f6.png)
2) There are no such toggles:
![Снимок экрана 2021-10-18 в 11 02 58](https://user-images.githubusercontent.com/32956521/137677273-c3284a71-3baa-4938-973f-408222a5e9a7.png)

**Comment by iksent** [comment] 2021-10-18 06:08
> You shouldn't be able to select the translations display on a m2m

Another question is why there are no support for translations display for m2m? This is very cool feature.

**Comment by iksent** [comment] 2021-10-18 06:18
And there are another bug with filling translations fields for m2m:

Please take a look at this video:
https://user-images.githubusercontent.com/32956521/137678657-007c25fb-57c1-4443-be16-99cd20984012.mov
- Category has translations for name field
- But name field is empty, when you open category from article (m2m)

**Comment by iksent** [comment] 2021-10-18 06:20
> But I wasn't able to reproduce the progress bar difference. Could you give more insight on how you got this? Eg. exact steps to reproduce + db structure.

Sorry, I can't send you database right now, because it's a bug from production. I'll try to send another DB later.

**Comment by Nitwel** [comment] 2021-10-18 08:46
Problem is that the translation interface doesn't make a lot of sense in the context of m2m, especially the dropdown. But this could be an Option in the related values display for sure.

**Comment by rijkvanzanten** [comment] 2022-01-24 22:34
Hi @iksent! I know this has been a while, but are you still facing issue №3? I wasn't able to reproduce based on the information above, and the video unfortunately doesn't / no longer works.

I'll close this for now, as I believe 1 and 3 are no longer an issue. No.2 is tracked in #9358 👍🏻  Please let me know if No.3 still exists in the latest version, and we'll reopen and (actively) resolve the issue 🙂

**Closed by rijkvanzanten** 2022-01-24 22:34 UTC
Labels: App, Bug, Needs More Info

**Comment by AdamDudley** [comment] 2022-02-04 16:03
Hi, Bug 3 is still there in Version 9.5 of Directus.

[as an aside, I know a lot of people are 'confused' by the way you've done translations, in our bespoke apps, this is exactly how we translate the data also, but we make the 'code/language' column a composite primary key with the fk from the parent table on the _translation table]

Here is my setup, starting with a database diagram
RED: BUG, YELLOW: not tested, GREEN: Working as expected.
![image](https://user-images.githubusercontent.com/2750375/152559994-1250d158-6296-4751-8f4e-eb7df270c354.png)

index page
![image](https://user-images.githubusercontent.com/2750375/152560320-d763ceaf-cd29-4459-a3d3-397450b61740.png)

Details page
![image](https://user-images.githubusercontent.com/2750375/152560478-16e09e91-469c-44a9-9278-d39bf01f35ad.png)


Display and interface  templates setup correctly from what I can see:
![image](https://user-images.githubusercontent.com/2750375/152560898-e34641ae-0a4d-47af-b88c-77da72d1696e.png)


If you have any more questions, just let me know. happy to share. Great job on this app BTW.

incase it helps, the app does load the values correctly when you 'click' on the drop down.
![image](https://user-images.githubusercontent.com/2750375/152561605-e56ad492-c8f3-4bf7-8b80-59e53ee65ea9.png)

**Comment by iksent** [comment] 2022-02-07 06:43
@rijkvanzanten, I just checked the latest Directus (9.5.1) and can confirm, that bug №3 is yet presents :(

And video link from my previous comment is works, please try to download it again:
https://user-images.githubusercontent.com/32956521/137678657-007c25fb-57c1-4443-be16-99cd20984012.mov

**Comment by azrikahar** [comment] 2022-02-07 07:02
@AdamDudley thanks for the detailed write up! I believe this is the same issue reported in #11385, and admittedly some other issues (#9751) before that. 

The general gist of the current problem is the when we are selecting translations relationally, it is attempting to display `translations.title` which is wrong because `translations` is an array, hence it should actually do `translations[i].title` with `i` being the language of choice or default language ideally. This will hopefully be resolved when #9560 gets implemented. 

As for bug no.3, do refer the response below.

---

@iksent I believe it is also reported in #11259 (let me know if it isn't!), and it has been resolved in #11431 just few days ago so it's not released yet 👍 In case you're wondering when would the release be, feel free to check it over here: https://github.com/directus/directus/milestones

**Comment by iksent** [comment] 2022-02-07 07:06
@azrikahar, #11259 is very similar, but I can't say for sure if this will solve my problem. Can you verify this with your latest fixes?

**Comment by azrikahar** [comment] 2022-02-07 07:21
@iksent Yup just verified locally with `articles` ---M2M---> `categories` (with translations): 

![image](https://user-images.githubusercontent.com/42867097/152742541-dba43bc0-5918-4d55-805c-e9ef4c0124d0.png)

**Comment by iksent** [comment] 2022-02-07 07:24
Cool, thanks!
But seems like there is some bug with line at bottom?
No margin like before:
![image](https://user-images.githubusercontent.com/32956521/152743075-6d432581-5eee-4af3-a840-27898cac0474.png)

**Comment by azrikahar** [comment] 2022-02-07 07:58
Nice catch! Found out it was overridden by the following CSS which was added when #8467 got merged recently: 

https://github.com/directus/directus/blob/b8c4317cb1cd9a8ed0eeb1ad4db35f8771588624/app/src/components/v-form/v-form.vue#L355-L357

Submitted a fix at #11469. Thanks again for spotting it 🙌
