### ISSUE TITLE
ROBOTS_TXT environment variable is not working

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#22062] opened 2024-04-03 13:39 UTC
### Describe the Bug

I know https://github.com/directus/directus/pull/17448 should allow edit the `robots.txt` (documented [here](https://docs.directus.io/self-hosted/config-options.html#general:~:text=%2D1-,ROBOTS_TXT,-What%20the%20/robots)), but I think it is not working well.

### To Reproduce

✅ When I don't configure anything:
<img width="831" alt="Screenshot 2024-04-03 at 09 33 28" src="https://github.com/directus/directus/assets/1007051/d86ad599-ceb2-468f-be0e-2498cafcec3c">

❌ When I try the default value: `User-agent: *\nDisallow: /`
<img width="831" alt="Screenshot 2024-04-03 at 09 32 35" src="https://github.com/directus/directus/assets/1007051/d6e9f2be-0504-4694-a5d6-96cca2425efd">

❌ When I try to escape the slash: `User-agent: */\nDisallow: /`
<img width="831" alt="Screenshot 2024-04-03 at 09 34 44" src="https://github.com/directus/directus/assets/1007051/70f9c182-fb00-4cf2-8a56-4a9444bb72e3">

❌ When I try to escape the slash: `User-agent: *\\nDisallow: /`:
<img width="831" alt="Screenshot 2024-04-03 at 09 35 59" src="https://github.com/directus/directus/assets/1007051/aeff4510-a8c6-454d-91f9-7e3c8d294fd2">

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-04-03 14:09
closing the issue for now, but happy to re-open if we can make it reproducable

**Comment by abdonrd** [comment] 2024-04-03 14:27
In the `docker-compose.yml`:

```
    environment:
      # ...
      ROBOTS_TXT: 'User-agent: *\nDisallow: /'
```

**Comment by abdonrd** [comment] 2024-04-03 14:32
Same behavior in Cloud:

<img width="535" alt="Screenshot 2024-04-03 at 10 27 32" src="https://github.com/directus/directus/assets/1007051/40a44731-39c2-4509-a5d4-e0faa618ded3">

**Comment by alexreid** [comment] 2024-04-03 14:35
> In the `docker-compose.yml`:
> 
> 
> 
> ```yml
> 
>     environment:
> 
>       # ...
> 
>       ROBOTS_TXT: 'User-agent: *\nDisallow: /'
> 
> ```
> 
> 

Just FYI, in YAML single quotes disable all escape sequences, so your `\n` won't be processed by YAML. Have you tried double quotes?

**Comment by abdonrd** [comment] 2024-04-03 14:38
It has been that. Now it works. Thanks to both!

```yml
    environment:
      # ...
      ROBOTS_TXT: "User-agent: *\nDisallow: /"
```

**Comment by br41nslug** [comment] 2024-04-03 14:43
@alexreid thanks just confirmed the same on my end aswell. Re-opening the ticket as this does need to be fixed for Cloud as it looks like they are using single quotes there.

**Closed** 2024-04-03 15:01 UTC
