### ISSUE TITLE
DatabaseError - value is out of range for type integer

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#20002] opened 2023-10-11 16:49 UTC
### Describe the Bug

This bug already exists for a good while, but I only decided to report it now. Still exists in the latest (at time of writing) Directus 10.6.3.

I have a table with some barcodes (saved as String) and some other fields (saved as other types), but when I paste any barcode in the Directus search bar, the database errors out.

<img src="https://github.com/directus/directus/assets/4715129/b7da3929-6ea1-417b-bac0-4c5082660e94" height="400px">

Database is PostgreSQL 15. Issue exists on both Windows and Ubuntu.

### To Reproduce

1. Create a table as shown:
<img src="https://github.com/directus/directus/assets/4715129/00428367-5289-4d87-bacc-7ec34e09306a" height="300px">

2. Add some random content to the table (a barcode, description, brand, etc)
3. Search for a barcode in the search field
4. Errors out as shown above and produces following error in the console:
```
[0] [13:37:15.721] ERROR: select count("almoxarifado"."id") as "countDistinct->id" from "almoxarifado" where (("almoxarifado"."id" = $1) or ("almoxarifado"."sort" = $2) or LOWER("almoxarifado"."barcode") LIKE $3 or LOWER("almoxarifado"."description") LIKE $4 or LOWER("almoxarifado"."brand") LIKE $5 or ("almoxarifado"."qty" = $6) or LOWER("almoxarifado"."brand2") LIKE $7) limit $8 - value "7893946004064" is out of range for type integer
[0]     err: {
[0]       "type": "DatabaseError",
[0]       "message": "select count(\"almoxarifado\".\"id\") as \"countDistinct->id\" from \"almoxarifado\" where ((\"almoxarifado\".\"id\" = $1) or (\"almoxarifado\".\"sort\" = $2) or LOWER(\"almoxarifado\".\"barcode\") LIKE $3 or LOWER(\"almoxarifado\".\"description\") LIKE $4 or LOWER(\"almoxarifado\".\"brand\") LIKE $5 or (\"almoxarifado\".\"qty\" = $6) or LOWER(\"almoxarifado\".\"brand2\") LIKE $7) limit $8 - value \"7893946004064\" is out of range for type integer",
[0]       "stack":
[0]           error: select count("almoxarifado"."id") as "countDistinct->id" from "almoxarifado" where (("almoxarifado"."id" = $1) or ("almoxarifado"."sort" = $2) or LOWER("almoxarifado"."barcode") LIKE $3 or LOWER("almoxarifado"."description") LIKE $4 or LOWER("almoxarifado"."brand") LIKE $5 or ("almoxarifado"."qty" = $6) or LOWER("almoxarifado"."brand2") LIKE $7) limit $8 - value "7893946004064" is out of range for type integer
[0]               at Parser.parseErrorMessage (C:\Users\Valentino\Desktop\Directus\node_modules\pg-protocol\dist\parser.js:287:98)
[0]               at Parser.handlePacket (C:\Users\Valentino\Desktop\Directus\node_modules\pg-protocol\dist\parser.js:126:29)
[0]               at Parser.parse (C:\Users\Valentino\Desktop\Directus\node_modules\pg-protocol\dist\parser.js:39:38)
[0]               at Socket.<anonymous> (C:\Users\Valentino\Desktop\Directus\node_modules\pg-protocol\dist\index.js:11:42)
[0]               at Socket.emit (node:events:513:28)
[0]               at addChunk (node:internal/streams/readable:324:12)
[0]               at readableAddChunk (node:internal/streams/readable:297:9)
[0]               at Readable.push (node:internal/streams/readable:234:10)
[0]               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[0]       "length": 151,
[0]       "name": "error",
[0]       "severity": "ERROR",
[0]       "code": "22003",
[0]       "where": "unnamed portal parameter $1 = '...'",
[0]       "file": "numutils.c",
[0]       "line": "229",
[0]       "routine": "pg_strtoint32"
[0]     }
```

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2023-10-11 22:21
Thanks for opening this issue! However this is a duplicate of an existing issue #17946, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #17946 for future updates.

**Closed by paescuj** 2023-10-11 22:21 UTC
