### ISSUE TITLE
Status role setting does not work

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#9561] opened 2021-11-06 20:51 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### To Reproduce

create collection `article` and `article_comments`

### article filed:

- status: system default
- comments: one to many `article_comments`

### article_comments filed

- status: system default
- article_id: many to one `article`
- contents: text

1. Go to Roles & Permissions> public
2. Set user custom permissions for article and article_comments:

![image](https://user-images.githubusercontent.com/8030134/140622638-348e476d-bc9c-4ffe-9778-6d1087027aa6.png)

3. Set the role under the Item Permissions option: status equals published

![image](https://user-images.githubusercontent.com/8030134/140622658-2132bee7-4b37-4cec-abfc-38a2bb3569ec.png)

4. Select all fields under the Field Permissions option.

![image](https://user-images.githubusercontent.com/8030134/140622969-4e1f7a12-31f9-4ca4-833f-b6e85f754454.png)

``` javascript
import { Directus } from '@directus/sdk';
const directus = new Directus('http://localhost:8080');

async function start() {
    const articles = await directus.items('articles').readMany({
        limit: 5,
        page: 1,
        fields: [
            'status',
            'comments.content'
        ]
    });
}
start();
```

Response:

```
{"data":[{"comments": null}]}
```

Add deep:

``` javascript
import { Directus } from '@directus/sdk';
const directus = new Directus('http://localhost:8080');

async function start() {
    const articles = await directus.items('articles').readMany({
        limit: 5,
        page: 1,
        fields: [
            'status',
            'comments.content',
        ],
        deep: {
            version: {
                _filter: {
                    _status: {
                        _eq: "published"
                    }
                }
            },
        }
    });
}
start();
```

Response:

```
{"data":[{"comments": null}]}
```

When I set it to All access, everything works:

![image](https://user-images.githubusercontent.com/8030134/140623159-c751565d-5d65-4b71-ba88-990fb9980097.png)

```
{
    "data": [{
        "comments": [{
            "contents": "test"
        }]
    }]
}
```

### What version of Directus are you using?

v9.0.0 rc100

### What version of Node.js are you using?

16.12.0

### What database are you using?

mysql 8.0

### What browser are you using?

chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by joselcvarela** [comment] 2021-11-07 16:35
Hello @cdwmhcc 
I cannot reproduce this issue. 
I believe you have some misconfiguration because you were not coherent on your setup. Look:
- You said to create `article` collection but you are fetching `articles`. It will always return 403, because `articles` does not exist;
- Also, you mention to create `article_comments` collection with field `contents` but then you are requesting `content`.

Please be ensure your client is coherent with your data model.
I am closing this one, but if you still think this is an issue, we can reopen it.

**Closed by joselcvarela** 2021-11-07 16:35 UTC
Labels: Bug (Potential)

**Comment by cdwmhcc** [comment] 2021-11-07 17:35
> Hello @cdwmhcc I cannot reproduce this issue. I believe you have some misconfiguration because you were not coherent on your setup. Look:
> 
> * You said to create `article` collection but you are fetching `articles`. It will always return 403, because `articles` does not exist;
> * Also, you mention to create `article_comments` collection with field `contents` but then you are requesting `content`.
> 
> Please be ensure your client is coherent with your data model. I am closing this one, but if you still think this is an issue, we can reopen it.

Sorry, I missed the 's' in the issue description and it has been corrected. I confirm that the problem persists for me.

**Comment by tylerforesthauser** [comment] 2021-11-07 17:44
I, too, am experiencing this issue.

**Comment by joselcvarela** [comment] 2021-11-08 04:45
Do you mind to share a snapshot?
I still cannot reproduce this issue.

**Comment by tylerforesthauser** [comment] 2021-11-08 16:23
> Do you mind to share a snapshot? I still cannot reproduce this issue.

Hopefully [this](https://drive.google.com/file/d/1vwFBrSVBSGXHDWkVTKFJDlJ-jRoiDyTd/view?usp=sharing) can offer some insight.
