### ISSUE TITLE
Can't create relationship to directus_collections

### ISSUE THREAD

**Issue by elliottloxley** [directus/directus#19028] opened 2023-06-29 12:50 UTC
### Describe the Bug

Creating any relationship to the system collection "directus_collections" results in an empty screen when the user goes to add values.

The collection does not show up in the dropdown when selecting the collection for the relationship, however you can write in "directus_collections" manually and receive no error. Field suggestions are also shown correctly in the display template section.

The field will save successfully, but when you go to add collections to the relationship, an empty screen pops up.

### Item can be created successfully and also shows display suggestions

![2023-06-29 - 13-37-13 - Dynamic Route](https://github.com/directus/directus/assets/28651797/69ea03f4-bb65-45d3-97b6-ea44f3e1c7e0)

### However trying to add items to the relationship results in blank screen

![2023-06-29 - 13-39-43 - Creating Item in Dynamic Route](https://github.com/directus/directus/assets/28651797/cd8e1b51-59a1-44d5-bed3-871524d6099d)

### To Reproduce

1. Create a new relationship in a collection
2. For the "collection" field, manually type "directus_collections"
3. Save the field
4. Navigate to the "content" section of the app and try to add items to the new field.

### Directus Version

v10.3.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-07-09 14:25
This is correct and currently behaves as expected. Directus Collections differs from other regular collections in that it combines raw schema information with the directus_collections metadata. This in turn means it doesn't behave the same as the other system endpoints.

The same limitation applies to `directus_fields` and `directus_relations` 👍🏻 

Feel free to open a new feature request to adjust that, but I'll close this issue for now as it's working as intended.

**Closed by rijkvanzanten** 2023-07-09 14:25 UTC
