### ISSUE TITLE
O2M required not being checked properly, not nullable not giving a warning 

### ISSUE THREAD

**Issue by MarkoMestrovicShape** [directus/directus#11835] opened 2022-02-24 10:00 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When there's a o2m relationship between two collections, and I'm trying to create an element in M collection from O collection, if there is a required field that is left empty, the field will be created after saving the O item. If a field is not nullable and it's left empty it won't save but it also won't give any kind of notification or warning.

In neither case will there be any kind of notification.

### To Reproduce

Create two collections in o2m, make one field required, make another required and not nullable in M collection.
From O collection screen click on Create new and create a field without nullable and required field. 

### Errors Shown

No errors shown.

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

v14.5.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-02-24 10:24
Should be duplicate of #9006, but we are currently tracking this in #9176 (revolves around the "create new" form not validating in general regardless of relationships) 👍

**Closed by azrikahar** 2022-02-24 10:24 UTC
Labels: Bug (Potential)
