### ISSUE TITLE
permission error when uploading file

### ISSUE THREAD

**Issue by ghezeli** [directus/directus#8080] opened 2021-09-16 16:03 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hi
When I install a new Directus with the Docker method
The file upload section does not work properly

**Docker Compost file:**
directus:
    image: directus/directus:latest
    volumes:
      - /home/test/directus/extensions:/directus/extensions
      - /home/test/directus/database:/directus/database
      - /home/test/directus/uploads:/directus/uploads

**Error in web panel:**
[SERVICE_UNAVAILABLE] Couldn't save file 0424d79f-367b-4118-9898-2ddadaf180e5.jpg

**Error in log when restart container:**
15:52:30 ⚠️  Upload directory (/directus/uploads) is not read/writeable!

**Error when i try to upload file:**
Error: EACCES: permission denied, open '/directus/uploads/5523f81f-ea0b-4fbe-9c12-c8758b94bc70.png',
Original stack:,
Error code: EACCES,
15:54:18 ⚠️  E_UNKNOWN: An unknown error happened with the file 5523f81f-ea0b-4fbe-9c12-c8758b94bc70.png.,
15:54:18 ⚠️  Couldn't save file 5523f81f-ea0b-4fbe-9c12-c8758b94bc70.png,
15:54:18 ✨ request errored POST 503 /files 41ms

### To Reproduce

1. Install new with docker compose
2. try to upload file

### What version of Directus are you using?

9.0.0-rc.92

### What version of Node.js are you using?

docker

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

unbuntu

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-09-17 01:25
Would you mind trying to run `sudo chown -R 1000:1000 /home/test/directus/uploads`? I understand this is a workaround atm, but we'll try to look into this and see is there a more permanent resolution.

**Comment by ghezeli** [comment] 2021-09-17 10:12
thanks a lot
Temporarily fixed
What should be done for the correct method?

**Comment by rijkvanzanten** [comment] 2021-09-17 20:03
@ghezeli Is this a new installation, or an upgraded from an older version? 

Starting in rc.71, the Docker image uses the "node" user for the folder's owner permissions. This feels like a very similar problem. Can you try https://github.com/directus/directus/discussions/6480#discussioncomment-917708 ?

**Comment by rijkvanzanten** [comment] 2021-09-27 22:35
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-09-27 22:35 UTC
Labels: Needs More Info

**Comment by jwnukoski** [comment] 2023-01-12 17:29
Wouldn't a better solution be to allow us to pass an arbitrary user for ownership?
I also get errors when trying to create my own image off of the directus/directus image, because its not executing as root.
