### ISSUE TITLE
Sqlite migration directus v9.7.0 to v9.8.0 fails

### ISSUE THREAD

**Issue by roelvan** [directus/directus#12529] opened 2022-04-02 08:02 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When running `npx directus database migrate:latest`

![CleanShot 2022-04-02 at 09 57 35@2x](https://user-images.githubusercontent.com/2583837/161373197-cb7eb164-8246-44f3-a418-83ca8b302800.jpg)

```
DROP TABLE "directus_users" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
```

### To Reproduce

Install directus v9.7.0 with sqlite. Then migrate using `npx directus database migrate:latest`.

### Errors Shown

```
DROP TABLE "directus_users" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed
```

### What version of Directus are you using?

9.0.7

### What version of Node.js are you using?

16.14.2

### What database are you using?

SQLite that comes with npm package "sqlite3": "^5.0.2"

### What browser are you using?

Chrome

### What operating system are you using?

ubuntu

### How are you deploying Directus?

locally

**Comment by Pachat** [comment] 2022-04-02 10:01
I confirm this bug.

Also, if, let say after some housekeeping such as 	`sqlite3 data.db "VACUUM"`;  `sqlite3 data.db "PRAGMA integrity_check"` you rerun `npx directus database migrate:latest` you get another error 
>`Error: alter table `directus_settings` add column `default_language` varchar(255) not null default 'en-US' - SQLITE_ERROR: duplicate column name: default_language`

meaning that `npx directus database migrate:latest` is not aware of the work already done by the first try.

**Comment by mattbisme** [comment] 2022-04-03 02:54
> Also, if, let say after some housekeeping such as `sqlite3 data.db "VACUUM"`; `sqlite3 data.db "PRAGMA integrity_check"` you rerun `npx directus database migrate:latest` you get another error
> 
> > `Error: alter table `directus_settings`add column`default_language` varchar(255) not null default 'en-US' - SQLITE_ERROR: duplicate column name: default_language`
> 
> meaning that `npx directus database migrate:latest` is not aware of the work already done by the first try.

I am running into the exact same thing on macOS.

**Comment by eikaramba** [comment] 2022-04-03 03:59
i also get this. sqlite, was on version 9.7.1 before. win64.

i suppose it is kind of related to the general sqlite problems when updating schemas https://github.com/directus/directus/issues/12397

at least i had the exact same permission problem last time when upgrading to 9.7.1 - although the actual migration was successful (maybe the migration from 9.7.1 -> 9.8.0 needed to do more stuff now and did trigger this bug)

**Comment by roelvan** [comment] 2022-04-05 08:11
I also lost a lot of s3 uploaded images and had map geo JSON data issues (cannot read startsWith from undefined) after running this failed migration.

**Comment by rijkvanzanten** [comment] 2022-04-05 14:55
This is a duplicate of https://github.com/directus/directus/issues/10842. We'll take a look what we can do on the knex side of the equation, as this is clearly causing a lot of issues within Directus :C

**Closed by rijkvanzanten** 2022-04-05 14:55 UTC
Labels: API, Bug, DB: SQLite
