### ISSUE TITLE
DB Migration 20210626A-change-filesize-bigint.ts fails on oracledb

### ISSUE THREAD

**Issue by sflepp** [directus/directus#6738] opened 2021-07-09 15:19 UTC
### DB Migration 20210626A-change-filesize-bigint.ts fails on oracledb

Hello everyone,

I am unable to setup a new instance of Directus with Oracle DB. The setup process fails on the DB migration file `20210626A-change-filesize-bigint.ts`.

Following log is displayed when running the setup process:
```
Automatically generated name "directus_fields_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_activity_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_folders_parent_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_files_uploaded_by_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_files_modified_by_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_permissions_autoinc_trg" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_permissions_role_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_permissions_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_presets_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_relations_many_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_relations_one_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_activity_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_parent_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_project_logo_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_public_foreground_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_public_background_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
✨ Applying Remove Collection Foreign Keys...
Automatically generated name "directus_fields_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_activity_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_permissions_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_presets_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_relations_one_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_relations_many_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_collection_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
✨ Applying Remove System Relations...
✨ Applying Remove System Collections...
✨ Applying Remove System Fields...
✨ Applying Add Cascade System Relations...
Automatically generated name "directus_files_uploaded_by_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_files_uploaded_by_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_files_modified_by_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_files_modified_by_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_folders_parent_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_folders_parent_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_permissions_role_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_permissions_role_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_activity_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_activity_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_parent_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_parent_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_project_logo_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_project_logo_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_public_foreground_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_public_foreground_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_public_background_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_settings_public_background_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
✨ Applying Change Webhook URL Type...
✨ Applying Add Relations Sort Field...
✨ Applying Remove Locked Fields...
✨ Applying Webhooks Collections Text...
✨ Applying Add Refresh Interval...
✨ Applying Make Filesize Nullable...
✨ Applying Add Collections Accountability...
✨ Applying Remove Files Interface...
✨ Applying Rename Interfaces...
✨ Applying Restructure Relations...
✨ Applying Add Foreign Key Constraints...
✨ Applying Add System Fk Triggers...
Automatically generated name "directus_permissions_role_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
Automatically generated name "directus_revisions_activity_foreign" exceeds 30 character limit for Oracle. Using base64 encoded sha1 of that name instead.
✨ Applying Add Collections Icon Color...
✨ Applying Add Deep Clone Config...
✨ Applying Change Filesize Bigint...

Something went wrong while seeding the database:

[Error] alter table "directus_files" modify "filesize" number(20, 0) default null null - ORA-01451: column to be modified to NULL cannot be modified to NULL

Please try again
```

Regards
Simon

### To Reproduce

1. Setup an Oracle DB
2. `npx create-directus-project example-project`
3.  Choose Oracle Database (Alpha) and insert DB settings
4. Setup runs until `Applying Change Filesize Bigint...` and fails

### What version of Directus are you using?

9.0.0-rc.83

### What version of Node.js are you using?

16.0.0

### What database are you using?

Oracle DB 19.3

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by nickrum** [comment] 2021-07-09 15:31
Duplicate of #6721

**Closed by nickrum** 2021-07-09 15:31 UTC
Labels: Bug (Potential)

**Comment by aidenfoxx** [comment] 2021-07-09 15:42
@sflepp You can use rc82 for the time being. Just update the `package.json` in your project to directus-rc82, remove your `node_modules` and `npm install`. Then run `npx directus bootstrap` to set the project up against the older version.
