### ISSUE TITLE
SDK doesn't handle empty type definitions

### ISSUE THREAD

**Issue by WoLfulus** [directus/directus#19772] opened 2023-09-23 02:11 UTC
### Describe the Bug

SDK will break all type definitions if there's an empty collection type. 

### To Reproduce

https://tsplay.dev/NBBGzN

### Directus Version

10.6.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by WoLfulus** [comment] 2023-09-23 02:11
@Sandros94

**Comment by br41nslug** [comment] 2023-09-25 09:04
I can confirm that empty types on the schema do not work. I am however leaning towards calling this unsupported instead of a bug 🤔 I don't currently see an usecase for having empty types on the root schema representing an empty collection and besides that empty types tend to behave unexpectedly https://www.totaltypescript.com/the-empty-object-type-in-typescript

Im closing this issue for now.

**Closed by br41nslug** 2023-09-25 09:04 UTC

**Comment by WoLfulus** [comment] 2023-09-25 11:33
I'd expect it to at least don't break other type definitions, which is why I submitted it as a bug.

**Comment by br41nslug** [comment] 2023-09-25 11:46
The reason why it breaks is because the root schema object is used as lookup table for relations and empty types `{}` match anything except undefined/null (see the link above). Because of this behavior any field of any type is considered to be a relation because the empty type matches all of them. 

I don't think i can prevent this without significant engineering time which i currently dont think is worth it for this edge-case without a valid usecase to support it 😬 

In my opinion empty types should generally be avoided in typescript and be prevented using eslint.

**Comment by WoLfulus** [comment] 2023-09-25 11:55
I didn't mention on the previous comment but I'm completely fine with it, just wanted to add why I filled it as a bug :P 

I also don't expect people to write empty interfaces in the schema, I just saw this because I'm generating all the type definitions - for now I just added a check to skip the empty interfaces and it's fine now.
