### ISSUE TITLE
Collections tables are not shown

### ISSUE THREAD

**Issue by GianlucaChiarani** [directus/directus#17092] opened 2023-01-11 16:44 UTC
### Describe the Bug

Sometimes, collections tables are not shown.

![immagine](https://user-images.githubusercontent.com/26008534/211865071-aed348f1-2c90-4eb5-ad2e-c44ef533e2fa.png)

### To Reproduce

- create at least 3 collections;
- browse collections in the left menu (layout must be tabular and no filters must be applied).

### Errors Shown

No errors in console or logs. In network, I noticed that collection preset is not loaded.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.13.0

### What database are you using?

MySql 8.0.31

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2023-01-11 16:46
Seems to be duplicate of #16883. You can update to the latest `9.22.2` which has patched this bug 👍

**Closed by azrikahar** 2023-01-11 16:46 UTC
