### ISSUE TITLE
Auto update for updated_by/updated_on seems to break SQL statement

### ISSUE THREAD

**Issue by Jan0707** [directus/directus#23032] opened 2024-07-16 14:15 UTC
### Describe the Bug

I have a reproducible situation where the update of a single item fails, because the underlying SQL statement seems to be incorrect, or rather the placeholder values seem to be filled incorrectly. 

Apparently, there is a mismatch and one of the updated values is being used as the ID instead of the ID originally provided to the `updateOne` statement.

This happens within an extension (action) that is listening to updates on the item (`action('podcasts.items.update')`).

### To Reproduce

```
        logger.info(`${HOOK_NAME} hook: Updating podcast item with id "${itemKey}" and data: ${JSON.stringify(updateData)}`)

        // If update data contains something, update podcast item
        await podcastItemsService.updateOne(itemKey, updateData)
```

Output of the log statement: 
> [programmierbar-cms] [2024-07-16 14:06:08] [14:06:08.155] INFO: buzzsprout hook: Updating podcast item with id "285594c1-54e0-4e01-9cf8-395408f8b55e" and data: {"buzzsprout_id":1234,"audio_file":"https://www.buzzsprout.com/123/file.mp3"}

Received error from the `updateOne` statement:
> Error: update "podcasts" set "audio_file" = $1, "buzzsprout_id" = $2, "updated_by" = $3, "updated_on" = $4 where "id" in ($5) - invalid input syntax for type uuid: "https://www.buzzsprout.com/123/file.mp3"

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

PostgreSQL

**Comment by rijkvanzanten** [comment] 2024-07-16 19:20
What is `updateData` and what's in it? 4 of those 5 parameters could be the offending one, and those are all set in the `updateData`

**Comment by Jan0707** [comment] 2024-07-17 18:28
My thought exactly, which is why I added the above log statement
```
logger.info(`${HOOK_NAME} hook: Updating podcast item with id "${itemKey}" and data: ${JSON.stringify(updateData)}`)
```

Which gave me
```
INFO: buzzsprout hook: Updating podcast item with id "285594c1-54e0-4e01-9cf8-395408f8b55e" and data: {"buzzsprout_id":1234,"audio_file":"https://www.buzzsprout.com/123/file.mp3"}
```

Because in the action I only set these two values. The others are added by the system (because it handles the updates to `updated_by/updated_on`)

Did I get your question alright?

**Comment by rijkvanzanten** [comment] 2024-07-22 20:56
@Jan0707 How are you calling that update? It's a bit strange that the update data contains `"audio_file":"https://www.buzzsprout.com/123/file.mp3"`. The error seems to indicate that that's the offending UUID. I'm assuming `audio_file` is a m2o field but is getting the wrong value somehow 🤔

**Comment by Jan0707** [comment] 2024-07-23 11:34
@rijkvanzanten Exactly as shown in the example above:
```
await podcastItemsService.updateOne(itemKey, updateData)
```

And the `podcastItemsService` itself is pretty straightforward as well:

```
const podcastItemsService = new ItemsService('podcasts', {
    accountability: context.accountability,
    schema: context.schema,
})
```

Also, `audio_file` is a string (even though the name suggests otherwise) but it is simply a pointer to where we host our podcast files. So the value per-se is fine, why it ends up in the wrong place in the prepared SQL statement ... beats me ... that's why I showed up here 😅

**Comment by Jan0707** [comment] 2024-07-23 11:36
Might be noteworthy that this behaviour seems to have appeared only _after_ our upgrade from Directus 10.1.1 to 10.12.1

**Comment by rijkvanzanten** [comment] 2024-07-23 15:04
@Jan0707 Can you share the full custom code you're using and the schema this is operating against? I've not been able to reproduce this against my own schema and tests yet

**Comment by Jan0707** [comment] 2024-07-23 15:22
It's all available here: https://github.com/programmierbar/website (It's a monorepo, for our backend and frontend, you can find all the directus related code in `/directus-cms`)

And the particular line shown above can be found here: https://github.com/programmierbar/website/blob/2df609ac0080609ecf2be02cff38c41e4978f909/directus-cms/extensions/directus-extension-programmierbar-bundle/src/buzzsprout/handlers/handlePodcastAction.ts#L115

The schema of the `main` branch should contain all recent changes to every item that is relevant to this part of our setup. It can be found here: https://github.com/programmierbar/website/blob/2df609ac0080609ecf2be02cff38c41e4978f909/directus-cms/schema.json

_(You can also find me with the same username on the directus discord if there is anything else I can do)_

**Comment by rijkvanzanten** [comment] 2024-07-23 18:51
I haven't fired up the full repo or schema yet, but from looking at the shared repo I'm 87.2% sure the problem is that `audio_file` in your datamodel is a UUID, but you're setting it to a URL string:

https://github.com/programmierbar/website/blob/2df609ac0080609ecf2be02cff38c41e4978f909/directus-cms/schema.json#L10984-L10987

https://github.com/programmierbar/website/blob/2df609ac0080609ecf2be02cff38c41e4978f909/directus-cms/extensions/directus-extension-programmierbar-bundle/src/buzzsprout/handlers/handlePodcastAction.ts#L103-L104

I believe you might have mistaken it for `audio_url` which is a string in your hook logic?

```diff
-updateData.audio_file = buzzsproutData.audio_url
+updateData.audio_url = buzzsproutData.audio_url
```

I'll close this for now, but happy to reopen and keep discussing if this is indeed a bug in Directus itself 🙂

**Closed by rijkvanzanten** 2024-07-23 18:51 UTC
Labels: :detective: Needs More Info

**Comment by Jan0707** [comment] 2024-07-24 06:56
Hi @rijkvanzanten,

This is beyond embarrassing 😫
Not sure how that change got in there but probably as part of the bigger extensions refactoring in the v10.10 migration.

Thank you _very much_ and **so sorry** to have wasted your time on this ...
