### ISSUE TITLE
Non admin user can't update singleton collection since migration

### ISSUE THREAD

**Issue by benjaminbours** [directus/directus#8527] opened 2021-10-04 08:56 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I was previously on the rc-88 without issue. I just migrated to rc-95 and I have trouble with the non admin roles. They are not able to perform the tasks they could do before the migration.

Here is what they see in the admin app:
![2021-10-04_10-50](https://user-images.githubusercontent.com/8804297/135821795-05106b81-ef65-4797-9a88-a3f32326fd26.png)

and here is what is in the logs:
![2021-10-04_10-45](https://user-images.githubusercontent.com/8804297/135821529-ffa23ea2-4642-4ae0-93ea-040a16b42491.png)

It seems to happen only with singleton collection. And only with non admin user.

### To Reproduce

- Setup a singleton collection on rc-88 with some fields.
- Create non admin role to perform all operation on thr collection.
- Create user with this role.
- Migrate from rc-88 to rc-95.
- Try to update using the user you create

It should fails.

### What version of Directus are you using?

9.0.0-rc-95

### What version of Node.js are you using?

I'm using docker, so the one in your docker file.

### What database are you using?

Postgres 12.7

### What browser are you using?

Chrome

### What operating system are you using?

Linux Ubuntu 20.04

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-10-04 09:43
Unfortunately I can't seem to reproduce this on my end. Can you share more detail on your Docker setup? Perhaps the content of `docker-compose.yml` file, or the full `docker run` command used if you're not using docker compose? 

> They are not able to perform the tasks they could do before the migration.
Can you elaborate more on the said tasks? That would be very helpful to confirm that our reproduction steps are the exact same. I did update a field of a singleton collection as the new non-admin user without without any issue.

> What version of Directus are you using?
> 9.0.0-rc-85

Can you verify whether this is a typo? You did migrated from rc.88 right?

**Comment by benjaminbours** [comment] 2021-10-04 10:00
> > What version of Directus are you using?
> > 9.0.0-rc-85
> 
> Can you verify whether this is a typo? You did migrate from rc.88, not rc.85 right?

Indeed it was a typo sorry, the version I'm now using is rc-95.

> Can you elaborate more on the said tasks? That would be very helpful to confirm that our reproduction steps are the exact same. I did update a field of a singleton collection as the new non-admin user without without any issue.

Well basically its updating text values in translations fields, or updating a file in an input file. Basic admin stuff.

Here is the failing request returning an 500 error code:

```
curl 'https://origin/items/models_template' \
  -X 'PATCH' \
  -H 'authority: origin' \
  -H 'sec-ch-ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'authorization: Bearer token' \
  -H 'content-type: application/json' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36' \
  -H 'cache-control: no-store' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'origin: https://origin' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://origin/admin/collections/models_template' \
  -H 'accept-language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'cookie: directus_refresh_token=TOKEN' \
  --data-raw $'{"translations":[1,2,3,4,{"id":5,"models_template_id":1,"languages_code":"de-DE","seo_title":"Die 3 Coverseal-Modelle für Ihr Schwimmbad, Ihren Teich oder Ihr Wasserspiels","seo_description":"Schwimmbad, Jacuzzi, Naturbecken. Entdecken Sie die automatischen, halbautomatischen und manuellen Modelle und ihre technischen Informationen.","main_title":"Coverseal-Modelle","main_paragraph":"<p>Da jedes Projekt einzigartig ist, muss die Abdeckung in Bezug auf Gr&ouml;&szlig;e, Farbe und Technik v&ouml;llig individuell gestaltet werden. Um all Ihren Bed&uuml;rfnissen gerecht zu werden, haben wir drei verschiedene Modelle entwickelt, die sich perfekt an Ihr Nutzungsprofil anpassen lassen.</p>","technical_information_title":"Technische Informationen","technical_info_file_text":"Datenblatt","configurator_link_text":"Individualisierung","achievements_link_text":"Dieses Modell bei unseren Kunden entdecken","customization_title":"Eine Individuell anpassbare Schwimmbadabdeckung.","customization_paragraph":"<p><span style=\\"font-weight: 400;\\">Eine Coverseal </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">rm&ouml;glicht </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">s Ihnen, </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">ie Harmonie Ihres Schwimmbades </span><span style=\\"font-weight: 400;\\">z</span><span style=\\"font-weight: 400;\\">u </span><span style=\\"font-weight: 400;\\">b</span><span style=\\"font-weight: 400;\\">ewahren, </span><span style=\\"font-weight: 400;\\">i</span><span style=\\"font-weight: 400;\\">ndem </span><span style=\\"font-weight: 400;\\">s</span><span style=\\"font-weight: 400;\\">ie </span><span style=\\"font-weight: 400;\\">s</span><span style=\\"font-weight: 400;\\">ich </span><span style=\\"font-weight: 400;\\">b</span><span style=\\"font-weight: 400;\\">is </span><span style=\\"font-weight: 400;\\">i</span><span style=\\"font-weight: 400;\\">ns </span><span style=\\"font-weight: 400;\\">k</span><span style=\\"font-weight: 400;\\">leinste Detail </span><span style=\\"font-weight: 400;\\">p</span><span style=\\"font-weight: 400;\\">erfekt </span><span style=\\"font-weight: 400;\\">a</span><span style=\\"font-weight: 400;\\">n </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">ie Umgebung </span><span style=\\"font-weight: 400;\\">a</span><span style=\\"font-weight: 400;\\">npasst</span>.</p>","customization_configurator_link_text":"Ihre Coverseal Konfigurieren","membrane_title":"Die Membrane","membrane_paragraph":"<p><span style=\\"font-weight: 400;\\">Alle </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">nsere Abdeckungen </span><span style=\\"font-weight: 400;\\">w</span><span style=\\"font-weight: 400;\\">erden </span><span style=\\"font-weight: 400;\\">m</span><span style=\\"font-weight: 400;\\">a&szlig;geschneidert </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">nd </span><span style=\\"font-weight: 400;\\">l</span><span style=\\"font-weight: 400;\\">assen </span><span style=\\"font-weight: 400;\\">s</span><span style=\\"font-weight: 400;\\">ich </span><span style=\\"font-weight: 400;\\">i</span><span style=\\"font-weight: 400;\\">ndividuell </span><span style=\\"font-weight: 400;\\">a</span><span style=\\"font-weight: 400;\\">npassen.&nbsp;</span></p>\\n<p><span style=\\"font-weight: 400;\\">Eine </span><span style=\\"font-weight: 400;\\">g</span><span style=\\"font-weight: 400;\\">anze Palette </span><span style=\\"font-weight: 400;\\">v</span><span style=\\"font-weight: 400;\\">on </span><span style=\\"font-weight: 400;\\">F</span><span style=\\"font-weight: 400;\\">arben </span><span style=\\"font-weight: 400;\\">f</span><span style=\\"font-weight: 400;\\">&uuml;r </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">ie Membrane </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">rm&ouml;glicht </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">s </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">nserer Abdeckung, </span><span style=\\"font-weight: 400;\\">s</span><span style=\\"font-weight: 400;\\">ich </span><span style=\\"font-weight: 400;\\">p</span><span style=\\"font-weight: 400;\\">erfekt </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">nd </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">nauff&auml;llig </span><span style=\\"font-weight: 400;\\">i</span><span style=\\"font-weight: 400;\\">n </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">ie Umgebung Ihres Schwimmbades </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">inzuf&uuml;gen.</span></p>","dressing_title":"Die Verkleidung","dressing_paragraph":"<p><span style=\\"font-weight: 400;\\">F&uuml;r </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">ie Verkleidung </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">xistieren </span><span style=\\"font-weight: 400;\\">m</span><span style=\\"font-weight: 400;\\">ehrere Versionen. Von Seitenw&auml;nden </span><span style=\\"font-weight: 400;\\">a</span><span style=\\"font-weight: 400;\\">us Edelstahl </span><span style=\\"font-weight: 400;\\">b</span><span style=\\"font-weight: 400;\\">is </span><span style=\\"font-weight: 400;\\">z</span><span style=\\"font-weight: 400;\\">um </span><span style=\\"font-weight: 400;\\">p</span><span style=\\"font-weight: 400;\\">ulverbeschichteten </span><span style=\\"font-weight: 400;\\">A</span><span style=\\"font-weight: 400;\\">luminiumgeh&auml;use </span><span style=\\"font-weight: 400;\\">i</span><span style=\\"font-weight: 400;\\">n </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">er Farbe Ihrer Wahl (Ral K7 Classic, </span><span style=\\"font-weight: 400;\\">a</span><span style=\\"font-weight: 400;\\">u&szlig;er </span><span style=\\"font-weight: 400;\\">f</span><span style=\\"font-weight: 400;\\">luoreszierend) </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">rf&uuml;llt </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">ieses </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">inzigartige Produkt </span><span style=\\"font-weight: 400;\\">a</span><span style=\\"font-weight: 400;\\">lle Ihre W&uuml;nsche </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">nd Bed&uuml;rfnisse.</span></p>","options_title":"Optionen","options_paragraph":"<p><span style=\\"font-weight: 400;\\">Ihre Schwimmbadabdeckung </span><span style=\\"font-weight: 400;\\">k</span><span style=\\"font-weight: 400;\\">ann </span><span style=\\"font-weight: 400;\\">m</span><span style=\\"font-weight: 400;\\">it </span><span style=\\"font-weight: 400;\\">v</span><span style=\\"font-weight: 400;\\">erschiedenen </span><span style=\\"font-weight: 400;\\">z</span><span style=\\"font-weight: 400;\\">us&auml;tzlichen Optionen </span><span style=\\"font-weight: 400;\\">a</span><span style=\\"font-weight: 400;\\">usgestattet </span><span style=\\"font-weight: 400;\\">w</span><span style=\\"font-weight: 400;\\">erden. So </span><span style=\\"font-weight: 400;\\">g</span><span style=\\"font-weight: 400;\\">ibt </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">s </span><span style=\\"font-weight: 400;\\">z</span><span style=\\"font-weight: 400;\\">um Beispiel</span><span style=\\"font-weight: 400;\\">&nbsp;</span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">ine </span><span style=\\"font-weight: 400;\\">s</span><span style=\\"font-weight: 400;\\">pezielle Stromversorgung </span><span style=\\"font-weight: 400;\\">f</span><span style=\\"font-weight: 400;\\">&uuml;r Abdeckungen </span><span style=\\"font-weight: 400;\\">i</span><span style=\\"font-weight: 400;\\">nnenliegender Schwimmbecken, </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">en Einbau </span><span style=\\"font-weight: 400;\\">v</span><span style=\\"font-weight: 400;\\">on Zylindern, </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">m </span><span style=\\"font-weight: 400;\\">g</span><span style=\\"font-weight: 400;\\">r&ouml;&szlig;ere Hindernisse </span><span style=\\"font-weight: 400;\\">z</span><span style=\\"font-weight: 400;\\">u </span><span style=\\"font-weight: 400;\\">&uuml;</span><span style=\\"font-weight: 400;\\">berwinden </span><span style=\\"font-weight: 400;\\">o</span><span style=\\"font-weight: 400;\\">der </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">m </span><span style=\\"font-weight: 400;\\">d</span><span style=\\"font-weight: 400;\\">ie Wasserdichtigkeit </span><span style=\\"font-weight: 400;\\">u</span><span style=\\"font-weight: 400;\\">nd &Auml;sthetik </span><span style=\\"font-weight: 400;\\">z</span><span style=\\"font-weight: 400;\\">u </span><span style=\\"font-weight: 400;\\">o</span><span style=\\"font-weight: 400;\\">ptimieren </span><span style=\\"font-weight: 400;\\">e</span><span style=\\"font-weight: 400;\\">tc. </span></p>","options_items":[{"option_name":"Zylinder","option_text":"Die automatisch aktivierten Zylinder ermöglichen die Überwindung größerer Hindernisse und sorgen für eine perfekte Ausführung.  Die Verkleidung wird dann am Ende ihres Weges sanft auf dem Boden abgesetzt."},{"option_name":"Zusätzliche Fotovoltaik-Paneele","option_text":"In bestimmten stark beschatteten Gebieten oder in Regionen der Welt mit wenig Sonnenlicht können 2 zusätzliche Fotovoltaik-Paneele angebracht werden, um das Licht optimal zu nutzen."},{"option_name":"Spezifische Stromversorgung für Hallenbäder","option_text":"Im Falle eines Hallenbades wird ein Ladegerät installiert, das Ihre Batterien versorgt."}],"last_configurator_link_text":"Erstellen Und Visualisieren Sie Mit Unserem Konfigurator Ihre Coverseal","scroll_down_link_text":"Und Schon Geht‘s Los\u0021","user_manual_file_text":"Manuel d\'utilisation","opengraph_description":"Schwimmbad, Jacuzzi, Naturbecken. Entdecken Sie die automatischen, halbautomatischen und manuellen Modelle und ihre technischen Informationen."},6]}' \
  --compressed
```
This give you an idea of the collection, the different fields created, the translation collection, the kind of content.

I think there is nothing uncommon in my docker-compose.yml

**Comment by azrikahar** [comment] 2021-10-05 03:27
I tried to reproduce again from scratch based on your descriptions, and there doesn't seem to be any on my end, so it might be hard to pinpoint the issue here.

Is there any rules applied to item/field permissions or field validations? I understand you mentioned all operations are enabled, but perhaps you can double check it in case somehow the migration affected something there.

Alternatively, would you mind providing a schema snapshot of your Directus instance so that we can try to make the environment as close as possible for the reproduction steps? The schema snapshot steps are documented here: https://docs.directus.io/reference/command-line-interface/#migrate-schema-to-a-different-environment

> I think there is nothing uncommon in my docker-compose.yml

Can you perhaps share what are the volumes or bind mounts for Directus in the docker compose file?

**Comment by joselcvarela** [comment] 2021-10-05 05:37
Hello @benjaminbours 
This could happen because this https://github.com/directus/directus/issues/8142#issuecomment-922629561

So my suggestion is to inspect your `directus_users` table and check if the `role` is not missing.
If is, try to manually update this table with the appropriate roles.

**Comment by rijkvanzanten** [comment] 2021-10-05 13:36
@joselcvarela That was specifically on SQLite though, due to that knex bug. This is on Postgres so shouldn't be affected 🤔

**Comment by rijkvanzanten** [comment] 2021-12-01 01:10
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-12-01 01:10 UTC
Labels: Needs More Info
