### ISSUE TITLE
Stuck at a simple item creation

### ISSUE THREAD

**Issue by mhdaouas** [directus/directus#8090] opened 2021-09-16 21:04 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I created a simple model with the following structure :

![directusModel](https://user-images.githubusercontent.com/3736107/133684674-65b5b157-7b3c-44cd-a612-9f08ebfd1204.png)

When I try to create an item based on that model, I get stuck at the creation page and the item is not saved:
![unlimitedLoading](https://user-images.githubusercontent.com/3736107/133684682-64385ff9-d645-4018-8da5-64ecd1976277.png)

### To Reproduce

- Create a model with the above structure
- Create an item based on that model

### What version of Directus are you using?

9

### What version of Node.js are you using?

v14.17.5

### What database are you using?

PostgreSQL

### What browser are you using?

Chrome

### What operating system are you using?

Linux Manjaro (Arch Linux)

### How are you deploying Directus?

running locally on Visual Code

**Comment by rijkvanzanten** [comment] 2021-09-16 21:13
I believe this might be a duplicate of https://github.com/directus/directus/issues/8083. Could you check if any of your fields has conditional fields (mis)configured?

**Comment by rijkvanzanten** [comment] 2021-09-16 21:18
I believe it's the same problem, as the symptom is identical 👍🏻 We can reopen if not

**Closed by rijkvanzanten** 2021-09-16 21:18 UTC
Labels: Needs More Info
