### ISSUE TITLE
M2M interface "Display Template" incorrect until item is saved

### ISSUE THREAD

**Issue by AaronBeaudoin** [directus/directus#12901] opened 2022-04-20 20:30 UTC
### Describe the Bug

I have 3 collections:

- Products
- Product Taxonomies
- Product Taxonomy Values

I might have a product taxonomy of "Sport". And it have a O2M relation to some taxonomy values, maybe "Tennis", "Baseball", "Basketball", etc...

Products in the product table have a M2M relationship with taxonomy values. The M2M field has a "Display Template" with a raw value like so `{{product_taxonomy_values_id.taxonomy.name}} — {{product_taxonomy_values_id.name}}`. So if a product is suitable for basketball, the added relation would have a display template like "Sport — Basketball".

The issue is that when I am on the product form view and I use "Add Existing" to add a taxonomy value to the product, it only seems to grab `product_taxonomy_values_id.name`. The other field in the display template, `product_taxonomy_values_id.taxonomy.name` doesn't render until the product has been saved.

![image](https://user-images.githubusercontent.com/26592486/164316850-060c7b2b-7615-4fc5-a89f-2fa8a6bedf90.png)

Above is an example of what I mean. In this case, the parent taxonomy for the value is "Body Part". When the product is saved, it then looks like this:

![image](https://user-images.githubusercontent.com/26592486/164317028-86e311cf-f720-4b4b-b07a-1f943bd01d8d.png)

### To Reproduce

Not 100% sure, but I suspect this is due to the fact that the admin UI doesn't realize it needs to fetch the nested data under the `product_taxonomy_values_id.taxonomy` field in order to actually display `product_taxonomy_values_id.taxonomy.name`.

If this is the case, then to reproduce the issue you just need to have some parent collection with a O2M relation to another collection containing children. Then from a third collection, make a M2M to the children. Finally, try to create a display template using a field value from the related child's "parent" collection.

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

Whatever version the Directus Docker image is using.

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-04-20 20:34
Duplicate of https://github.com/directus/directus/issues/10647

**Closed by rijkvanzanten** 2022-04-20 20:34 UTC
Labels: Bug (Potential)
