### ISSUE TITLE
Date functions stopped working with the latest release

### ISSUE THREAD

**Issue by martinomg** [directus/directus#16531] opened 2022-11-19 13:29 UTC
### Describe the Bug

Latest directus version broke the date functions. This broke a lot of things for me  😬

### To Reproduce

1. Apply a date function to any date field, for example the default date_created, and get null.

I tried with different collections
<img width="1010" alt="Screenshot 2022-11-19 at 10 21 59" src="https://user-images.githubusercontent.com/5248081/202852920-039b7582-d265-45fa-a678-3d9fb55ab5fa.png">

2. Apply the same date function to any previous directus version, and get the correct result.
<img width="1004" alt="Screenshot 2022-11-19 at 10 23 31" src="https://user-images.githubusercontent.com/5248081/202852971-06afdf70-a47f-4c78-9d1e-3bfe7a451386.png">

3. Here there's more tests with other kind of date fields

<img width="998" alt="Screenshot 2022-11-19 at 10 37 31" src="https://user-images.githubusercontent.com/5248081/202853423-00def9dc-f509-4577-b5d1-b8a8e97bda29.png">

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.17.0

### What database are you using?

Mysql

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by licitdev** [comment] 2022-11-19 13:45
Duplicate of #16494

@martinomg Possible to help test the following SQL query if it returns the correct values instead of `null`?
Replace `organization` with your table name.
```sql
select
	`organization`.`date_created`,
	YEAR(CONVERT_TZ(`organization`.`date_created`, @@GLOBAL.time_zone, '+00:00')) AS `date_created_year`,
	MONTH(CONVERT_TZ(`organization`.`date_created`, @@GLOBAL.time_zone, '+00:00')) AS `date_created_month`,
	DAYOFMONTH(CONVERT_TZ(`organization`.`date_created`, @@GLOBAL.time_zone, '+00:00')) AS `date_created_day`,
	`organization`.`id`
from
	`organization`
order by
	`organization`.`id` asc
```

**Closed by licitdev** 2022-11-19 13:45 UTC
Labels: Duplicate

**Comment by martinomg** [comment] 2022-11-19 14:23
That worked ok

<img width="1103" alt="Screenshot 2022-11-19 at 11 22 37" src="https://user-images.githubusercontent.com/5248081/202855501-cde5ff6f-0882-4c85-9c97-bb82000edfd8.png">

**Comment by licitdev** [comment] 2022-11-19 14:31
Thank you @martinomg for helping to confirm that the query from #16499 resolves the issue. 🙏

**Comment by martinomg** [comment] 2022-11-22 18:16
Just as a comment this is also affecting the insights sections.
