### ISSUE TITLE
Import/export tool

### ISSUE THREAD

**Issue by Linguisto** [directus/directus#2601] opened 2020-02-25 21:36 UTC
# Feature Request
Add collection export/import tool into the admin

## What problem does this feature solve?
Allows to easily back up and migrate data between the application instances for the end user, so that their data ain't gonna be lost.

### Data
All collection data is stored inside the xml or json files.

### Import
A form in the admin panel that allows to upload a zip archive with the collection data (xml/json files) inside.

### Export
A button in the admin panel which triggers download of the zip archive with the collection data.

## Would you be willing to work on this?
Yes, I would like to but I'm not sure if I actually can, taking into account my very tight schedule for the moment.

**Comment by rijkvanzanten** [comment] 2020-02-26 14:39
Duplicate of https://github.com/directus/api/issues/31

**Closed by rijkvanzanten** 2020-02-26 14:39 UTC

**Comment by rijkvanzanten** [comment] 2020-02-26 14:40
> Allows to easily back up and migrate data between the application instances for the end user, so that their data ain't gonna be lost.

For reference, the data in the DB isn't stored in any proprietary format or anything, so migrating data between databases is already a very "copy paste" kinda operation. That being said, having the ability to download an export in any format through the GUI is definitely a highly sought after feature
