### ISSUE TITLE
Deleting of Fields in Data Model is not Possible

### ISSUE THREAD

**Issue by myzinsky** [directus/directus#7061] opened 2021-07-28 22:11 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

<img width="618" alt="image" src="https://user-images.githubusercontent.com/1970554/127402453-50b3d2f6-8f3d-4d3a-a0ab-d07cca0c5000.png">

Deleting a field is not possible. It still stays there and says "only in database, click to configure"

Seams that deleting the fields does not work, since in the database they still exist.

### To Reproduce

Delete a table in the app.

### What version of Directus are you using?

v9RC83

### What version of Node.js are you using?

v16.4.1

### What database are you using?

Postgres 12.5

### What browser are you using?

Chrome, Safari

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-07-29 14:10
> Deleting a **field** is not possible. It still stays there and says "only in database, click to configure"
> 
> Seams that deleting the **fields** does not work, since in the database they still exist.
> 
> ## To Reproduce
> 
> **Delete a table** in the app.

Just to confirm, are you deleting the _table_ or are you deleting the _field_ in the table? It sounds like the latter, but wanted to double check 🙂

**Comment by rijkvanzanten** [comment] 2021-07-29 15:52
I can't seem to reproduce this on my end

**Comment by myzinsky** [comment] 2021-07-29 17:29
It seams deleting the reds cache solves the problem. It was really strange. Directus behaviour was completely off.

**Comment by rijkvanzanten** [comment] 2021-07-29 18:47
Is it still showing the same problem now that the cache was cleared once? Eg is it a reproducible problem?

**Comment by rijkvanzanten** [comment] 2021-08-03 22:48
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-08-03 22:48 UTC
Labels: Needs More Info

**Comment by ruihildt** [comment] 2021-08-30 16:35
@rijkvanzanten I can't reproduce this, but I have a collection with a field I can't delete, but I can try to provide a video and a full SQL dump.

I tried turning on and off again. 😄

**Comment by rijkvanzanten** [comment] 2021-08-30 17:03
Sure thing! Can you share it here, or does it contain private data? (In case of the second, you can email it to rijk@directus.io)

**Comment by ruihildt** [comment] 2021-08-31 16:16
No private/sensitive data, but it's bigger than the limit of chars here, so I sent the SQL dump by email.

Forgot to mention in the email that `code_produit` is the field I can't delete.

**Comment by ruihildt** [comment] 2021-09-01 06:50
@rijkvanzanten What would be the right way to fix this bug?

**Comment by rijkvanzanten** [comment] 2021-09-01 23:47
@ruihildt Thanks! I just imported the dump and tried it out, and... it deleted just as expected 🙃 

What version of Directus are you on? I just tested in on RC92 (the next patch release at time of writing)

**Comment by ruihildt** [comment] 2021-09-02 07:26
@rijkvanzanten I'm on RC91.

I will duplicate the whole environment, and try to empty the Redis cache, as suggested by OP, and see how that goes.

**Comment by ruihildt** [comment] 2021-09-02 15:51
I can confirm flushing redis cache solved the issue.

Is there anything else that would be helpful for you to debug this?

**Comment by rijkvanzanten** [comment] 2021-09-02 17:47
Ahh that makes sense. The API will flush those caches on schema changes, but apparently it fails to do so somewhere in this flow, which makes the field show up again 🤔
