### ISSUE TITLE
Rerouting flows can cause 'Field "resolve" has to be unique.' error

### ISSUE THREAD

**Issue by DigNZ** [directus/directus#15411] opened 2022-09-06 02:21 UTC
### Describe the Bug

When changing the connections between flows and then saving the flow you can get a popup with an error and the changes do no save.

### To Reproduce

Create three operations in a flow and connect them together and save. Then edit the flow and remove the connection between the operations and reconnect them in a different order, on save the error will be shown. 

For example if you had

trigger -> operation 1 -> operation 2 -> notification

Saved and edited it to be:

trigger -> operation 2 -> operation 1 -> notification

The error will be shown.

Note that this only happens when the operations change connections, breaking the connection:

trigger -> operation 1 -> operation 2       notification

or adding a new operation:
trigger -> operation 1 -> operation 2 -> notification -> operation 3

Will not trigger this error.

### Errors Shown

{
  "errors": [
    {
      "message": "Field \"resolve\" has to be unique.",
      "extensions": {
        "code": "RECORD_NOT_UNIQUE",
        "collection": "directus_operations",
        "field": "resolve",
        "invalid": "4bf42c42-97fb-44c0-9b6a-035fa3033558"
      }
    }
  ]
}

### What version of Directus are you using?

9.17.1 docker

### What version of Node.js are you using?

in the docker iamge

### What database are you using?

postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-09-06 02:28
Closing as duplicate of #14185, feel free to subscribe to it for future updates 👍 Thanks for the detailed reproduction steps!

**Closed by azrikahar** 2022-09-06 02:28 UTC

**Comment by DigNZ** [comment] 2022-09-06 02:29
I did search first I promise! Thanks for the link - I'll follow that other issue.
