### ISSUE TITLE
Email invite link not working 

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#8307] opened 2021-09-25 02:36 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Invite link in invite email not working 

### To Reproduce

1) Open directus admin panel
2) Invite user by email in Users tab
3) Check mail link in the mail

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

16.9.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

docker-compose

**Comment by rijkvanzanten** [comment] 2021-09-25 02:44
Duplicate of https://github.com/directus/directus/issues/8163

**Closed by rijkvanzanten** 2021-09-25 02:44 UTC
Labels: Bug (Potential)
