### ISSUE TITLE
Fatal error : headers already sent

### ISSUE THREAD

**Issue by nervusdm** [directus/directus#14968] opened 2022-08-09 08:35 UTC
### Describe the Bug

In a collection with a filed, sometimes I have this weird problem, forcing the node js to crash. 

### To Reproduce

Using a collection with a field.
Open the edit page.

### Errors Shown

10:31:53 ✨ request completed PATCH 204 /users/me/track/page 46ms
10:31:53 ✨ request completed GET 200 /items/hub_ha_files?fields[]=directus_files_id.id&fields[]=directus_files_id.type&fields[]=directus_files_id.title&fields[]=id&filter=%7B%22hub_ha_id%22:%221%22%7D&page=1&limit=15 69ms
_http_outgoing.js:590
    throw new ERR_HTTP_HEADERS_SENT('remove');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at ServerResponse.removeHeader (_http_outgoing.js:590:11)
    at ServerResponse.send (/var/www/hpsdirectus/node_modules/express/lib/response.js:214:10)
    at ReadStream.<anonymous> (/var/www/hpsdirectus/node_modules/directus/dist/controllers/assets.js:153:25)
    at ReadStream.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

6

### What database are you using?

mysql

### What browser are you using?

Edge

### How are you deploying Directus?

distant server

**Comment by azrikahar** [comment] 2022-08-09 08:36
Thanks for opening this issue! However this is a duplicate of an existing issue #14888, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #14888 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-08-09 08:36 UTC

**Comment by nervusdm** [comment] 2022-08-09 08:40
This is not the same thing. It's all about "file field".

**Comment by azrikahar** [comment] 2022-08-09 08:56
Although the trigger may be different, I'm pretty sure this specific error started to happen since https://github.com/directus/directus/commit/8085b0d7881b9ef60073774d2a85f73d5a553a5a which is included in 9.15.1, so it's more so about the same root cause rather the same issue 👍 If this is reproducible on 9.15.0, do let us know and we'll reopen this. Unfortunately this issue has been rather hard to reproduce reliably with the info we have at hand.

**Comment by rijkvanzanten** [comment] 2022-08-09 14:51
> Although the trigger may be different, I'm pretty sure this specific error started to happen since [8085b0d](https://github.com/directus/directus/commit/8085b0d7881b9ef60073774d2a85f73d5a553a5a) which is included in 9.15.1, so it's more so about the same root cause rather the same issue 👍 If this is reproducible on 9.15.0, do let us know and we'll reopen this. Unfortunately this issue has been rather hard to reproduce reliably with the info we have at hand.

The trigger is identical. A file field in the app uses `/assets` for the thumbnail, therefore making this a symptom of the exact same underlying issue
