### ISSUE TITLE
Numeric input issues (trailing 0, Safari decimal numbers)

### ISSUE THREAD

**Issue by mslonina** [directus/directus#10243] opened 2021-12-02 21:27 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When creating float fields (using provided input interface), I cannot enter decimal points (nor the dot itself) on Safari. I tested:

- creating a float field with the basic interface
- creating a float field with the advanced interface
- changing step interval to null or zero
- changing floating point precision and scale 

On Firefox it looks to work.

### To Reproduce

1. Create a content containing a simple float-type field.
2. Try to enter a number starting with 0 - you should be able to enter decimals after the dot
3. Try to enter a number starting with 1 - you cannot add decimals (and the dot)

### What version of Directus are you using?

9.1

### What version of Node.js are you using?

16.3

### What database are you using?

Sqlite

### What browser are you using?

Safari 14.1.1

### What operating system are you using?

macOS 11.4

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-12-02 21:53
Interesting! This seems to be a difference how Safari / Vue (or both) handles changes to the `value` prop while there's a different value already in the input. Chrome and Firefox both seem to ignore the change to the `value` prop, where Safari's is overwritten.

Not too sure if this is a bug in Directus or Vue tbh!

**Comment by mslonina** [comment] 2021-12-03 21:43
Actually, I cannot enter numbers wider than 10 digits (including dot and a sign), for example: 

 -2148960.7659

is rounded to

 -2148960.8

Even if I paste the number, and looks fine, after saving the entry, it gets rounded no matter what I set in the field settings. I've tested different floating point number precision and scale, trying to set i.e. precision to 32 and scale 16, with no success.  

This happens on Firefox, Chrome and Safari.

**Comment by licitdev** [comment] 2021-12-05 16:34
> I cannot enter decimal points (nor the dot itself) on Safari

Safari triggers input update when typing `.` in a number input, whereas other browsers which simply ignores the `.`
The issue can be fixed by adding `props.modelValue !== Number(value)` to https://github.com/directus/directus/blob/cf09f6cd218eedb002727ed651ad7fcb7c071685/app/src/components/v-input/v-input.vue#L234


> Actually, I cannot enter numbers wider than 10 digits (including dot and a sign)

I am unable to replicate this issue in a fresh sqlite db. No issue with saving `-2148960.7659` as precision and scale are not for sqlite. 

However, tested that this issue exists on Postgres, where the column's data type within DB is `real` instead of the selected `float`. https://github.com/knex/knex/issues/2945

**Comment by mslonina** [comment] 2021-12-05 17:05
> I am unable to replicate this issue in a fresh sqlite db. No issue with saving -2148960.7659 as precision and scale are not for sqlite.

@licitdev confirmed, I have another instance of Directus running on postgres, and apparently I used that instead of sqlite. 

I noticed another issue here - I cannot put zeros after the non-zero digit, i.e. 0.017 will work, but 0.017089 will suffer when entering third zero (both on Safari and Firefox, I have to put the 89 part and then move back the cursor to enter 0).

**Comment by licitdev** [comment] 2021-12-05 17:40
> I noticed another issue here - I cannot put zeros after the non-zero digit, i.e. 0.017 will work, but 0.017089 will suffer when entering third zero (both on Safari and Firefox, I have to put the 89 part and then move back the cursor to enter 0).

Thank you for your reports! Tested the above posted fix resolving this issue as well.

@rijkvanzanten How should we proceed with the issue on postgres where Knex saves `float` as `real`?

**Comment by rijkvanzanten** [comment] 2021-12-06 19:36
> @rijkvanzanten How should we proceed with the issue on postgres where Knex saves float as real?

Very good question. In typical Knex fashion, the issue is dismissed with 

> [...] I cannot think of any situation why one would like to use any other size of floats [...]

and closed with

> documentation issue

So there isn't much we can do about that at this point. We could disable the configuration of precision / scale for Float types (and leave that on for Decimal), but i'm not sure if that'd make sense for the other database vendors 🤔

**Comment by madsh93** [comment] 2021-12-13 19:08
> hould we

@rijkvanzanten adding decimals with zeros e.g. 3.06 or 4.504 won't work. The dashboard does not allow to insert a zero. The solution is currently to enter 3.6 and then move the cursor before the 6 and enter a 0.

Is there an issue created for this?

**Comment by rijkvanzanten** [comment] 2021-12-13 19:14
@madsh93 That's caused by the same underlying issue as the problem in the OP, so lets treat this issue as the consolidated issue to track issues around numeric inputs 👍🏻

**Comment by rijkvanzanten** [comment] 2021-12-14 15:10
OP was fixed in https://github.com/directus/directus/pull/10491. Lets track the float vs real vs decimal discussion in a new issue 👍🏻

**Closed by rijkvanzanten** 2021-12-14 15:10 UTC
Labels: App, Bug

**Comment by mslonina** [comment] 2021-12-17 20:47
Thanks a lot, confirmed putting zeroes works on 9.3.0!
