### ISSUE TITLE
Bug when typing in a 2nd-depth-level O2M modal translation field

### ISSUE THREAD

**Issue by stouch** [directus/directus#9510] opened 2021-11-05 08:31 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I've got : 
Collection A : 
- field A (O2M) -> Collection B : 
-- field B (O2M) -> Collection C : 
--- field C -> Collection C translations : 
---- field D

In the DIrectus dashboard, from a Collection A item, when I open the sub-sub-modal of Collection C translations, when I start to type in the field D for one of my languages, the focus is systematically blurred.

### To Reproduce

1. From a setup with : 
Collection A : 
- field A (O2M) -> Collection B : 
-- field B (O2M) -> Collection C : 
--- field C -> Collection C translations : 
---- field D

2. Open the 2nd-depth modal to edit field D from the field A.

3. Try to edit the field D

### Errors Shown

https://user-images.githubusercontent.com/17531455/140481333-1e4cfc16-8c48-4ec9-9b08-7bbeacc83c70.mov

### What version of Directus are you using?

v9.0.0 (latest)

### What version of Node.js are you using?

latest

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by stouch** [comment] 2021-11-05 09:03
Actually, the bug occurs for all the translation fields, not only for O2M translation fields..

**Comment by azrikahar** [comment] 2021-11-08 03:24
Seems like this bug was introduced in #9333. Reverting that change does fix it, but will probably need to explore the intended fix of that PR.

**Comment by jawngee** [comment] 2021-11-08 03:30
Related to #9547?

**Comment by azrikahar** [comment] 2021-11-08 03:32
@jawngee yes you are correct. Was just going to provide some detail before closing it, but since you've noticed it then all good 😄

**Comment by stouch** [comment] 2021-11-12 10:44
For the record, I still have this problem in 9.0.1

**Comment by faridsaud** [comment] 2021-11-12 16:38
I can confirm this is happening on 9.0.1

**Comment by nintra** [comment] 2021-11-14 21:12
Bug still exists at v9.0.1. making translation inputs unusable.

**Closed** 2021-11-24 21:17 UTC
Labels: App, Bug
