### ISSUE TITLE
A 403 error is thrown in selfreferenced many-to-many

### ISSUE THREAD

**Issue by emimagnanimiraclesdev** [directus/directus#17433] opened 2023-02-07 18:08 UTC
### Describe the Bug

I have a collection that references itself in a many-to-many relation.

When I try to edit a child from the parent I get a 403 error.

The error is thrown because it calls the intermediate table with the child id.

For example `/collection_collection/5` instead of `/collection/5`.

If I downgrade to 9.22.1 it doesn't throw any error and call the right endpoint

### To Reproduce

Create a collection and add a many-to-many relation to itself. Then add an item with at least a child and try to edit it from its parent.

### Errors Shown

[FORBIDDEN] You don't have permission to access this.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.12.1

### What database are you using?

MySql8

### What browser are you using?

Chrome

### How are you deploying Directus?

locally with node

**Comment by licitdev** [comment] 2023-02-07 18:45
Duplicate of #17108

**Closed by licitdev** 2023-02-07 18:45 UTC
