### ISSUE TITLE
Multiple file field re-ordering broken on unsaved item.

### ISSUE THREAD

**Issue by Bodom78** [directus/directus#5948] opened 2021-05-29 14:02 UTC
1) The issue and what you expected to happen
    Multiple files field reordering does not work on an unsaved item.
    I add some files and reorder, I expect them to hold the order.
    What happens is after the first reorder, all items are duplicated in the list.
    Second reorder just removes all items except the item dragged.

2) Exact steps to reproduce this issue
    Create a multiple files field and set an order field.
    Create a new item and attempt to add and reorder files prior to saving the content item.
    The same result with adding or selecting existing files.

3) Your environment:
    v9.0.0-rc.69
    10.3.23-MariaDB
    Running on Win10 npx
    Latest FireFox 88.0.1 and Chrome 91.0.4472.77

4) Any other relevant information we might need to reproduce this issue
    File Library is using S3 to host files.

Example video here: https://www.loom.com/share/c57a480f09f74f85be7f70fe8e1335d6

**Comment by rijkvanzanten** [comment] 2021-06-01 14:18
Duplicate of https://github.com/directus/directus/issues/3721

**Closed by rijkvanzanten** 2021-06-01 14:18 UTC
