### ISSUE TITLE
Directus Blocks

### ISSUE THREAD

**Issue by hugopvl** [directus/directus#15051] opened 2022-08-12 16:13 UTC
### Describe the Bug

Hello guys, lately directus has been blocking, and the only thing I can do is restart so that it works again. I still can't figure out what causes the error, but in the logs I get the following information:
can someone help me?

node:_http_outgoing:654
    throw new ERR_HTTP_HEADERS_SENT('remove');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.removeHeader (node:_http_outgoing:654:11)
    at ServerResponse.send (/root/design/node_modules/express/lib/response.js:214:10)
    at ReadStream.<anonymous> (/root/design/node_modules/directus/dist/controllers/assets.js:153:25)
    at ReadStream.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP_HEADERS_SENT'

### To Reproduce

i dont know

### Errors Shown

node:_http_outgoing:654
    throw new ERR_HTTP_HEADERS_SENT('remove');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.removeHeader (node:_http_outgoing:654:11)
    at ServerResponse.send (/root/design/node_modules/express/lib/response.js:214:10)
    at ReadStream.<anonymous> (/root/design/node_modules/directus/dist/controllers/assets.js:153:25)
    at ReadStream.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_HTTP_HEADERS_SENT'

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

MSSQL

### What browser are you using?

chrome

### How are you deploying Directus?

locally. on debian server

**Comment by licitdev** [comment] 2022-08-12 16:22
Duplicate of #14888.

**Closed by licitdev** 2022-08-12 16:22 UTC
