### ISSUE TITLE
Docker secrets available without _FILE syntax

### ISSUE THREAD

**Issue by kuuroo3** [directus/directus#12876] opened 2022-04-20 12:02 UTC
### Describe the Bug

It is documented, that if using secrets one should append "_FILE" the property name. ADMIN_EMAIL and ADMIN_PASSWORD also work without that.

So just like:
```
directus:
  ...
  secrets:
      - ADMIN_PASSWORD
      - ADMIN_EMAIL
      
secrets:
  ADMIN_PASSWORD:
    file: ./secrets/admin_password.txt
  ADMIN_EMAIL:
    file: ./secrets/admin_user.txt
```

This should be mandatory, I guess
```
      ADMIN_EMAIL_FILE: '/run/secrets/ADMIN_EMAIL'
      ADMIN_PASSWORD_FILE: '/run/secrets/ADMIN_PASSWORD'
```

refer to the discord discussion: https://discord.com/channels/725371605378924594/760886871965433877/966282012669390850

### To Reproduce

1. Create .txt file with your admin email as content
2. In the secrets section add 
```
ADMIN_EMAIL:
     file: ./secrets/admin_user.txt
```
3. In your directus service add a secrets section
```
    secrets:
      - ADMIN_EMAIL
```
4. Rebuild docker and run

### Errors Shown

None

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 12

### What browser are you using?

Vivaldi

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-04-20 12:47
The reason why `ADMIN_EMAIL` and `ADMIN_PASSWORD` _seemed_ like they work without adding `ADMIN_EMAIL_FILE` and `ADMIN_PASSWORD_FILE` respectively is because they will not throw errors when missing, but rather fallback to generate a random value as seen here:

![WindowsTerminal_1vx2m2IakY](https://user-images.githubusercontent.com/42867097/164233109-79e198d4-3a38-4203-9161-3b2516209f62.png)

So they are not actually being used.

Tested and confirmed locally where adding `ADMIN_EMAIL_FILE=/run/secrets/ADMIN_EMAIL` (after setting the secret as `ADMIN_EMAIL` of course) shows the correct outcome:

![WindowsTerminal_3OJHzDZUBm](https://user-images.githubusercontent.com/42867097/164233353-ca225336-5307-42aa-9b74-ecf79e415a7f.png)

Where the secrets `ADMIN_EMAIL` is now really being used. Closing this as things seems to be working as epected 👍

Further reference in Discord: https://discord.com/channels/725371605378924594/760886871965433877/966317261507919912

**Closed by azrikahar** 2022-04-20 12:47 UTC
Labels: Bug (Potential)
