### ISSUE TITLE
Auto generated translations seem not being set up correctly

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#6620] opened 2021-07-02 11:46 UTC
### Describe the Bug

The auto generated translations fields seem not being set up correctly from RC-82 (in RC-81 works fine)

![image](https://user-images.githubusercontent.com/14786440/124270061-f67ef180-db3b-11eb-8f66-9b31ea239bc1.png)
![image](https://user-images.githubusercontent.com/14786440/124269441-2bd70f80-db3b-11eb-9a5c-2a7269bb2d74.png)

### To Reproduce

Use RC-82 or RC-83, create a collection and auto-generate a translations field for it. Check that it doesn't preview the "There are X fields on this translations collection" (not working neither with 0 or 1 field in the translations collection)

### What version of Directus are you using?

RC-82

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Linux Mint

### How are you deploying Directus?

Locally

**Comment by wc-matteo** [comment] 2021-07-02 14:00
duplicate of: https://github.com/directus/directus/issues/6582

**Closed** 2021-07-02 14:01 UTC
Labels: Duplicate
