### ISSUE TITLE
Another field with a photo in the collection

### ISSUE THREAD

**Issue by koksikus** [directus/directus#13488] opened 2022-05-23 16:46 UTC
### Describe the Bug

When I create another field with a photo, an error appears. I created a discussion #13356 as I thought I was doing something wrong, but today I had a different problem with creating relationships. Having collection A and collection B, I could not create an O2M relationship between collection B and A, but in collection A I created a relationship M2O with collection B. The errors that appeared were the same as in the discussion.

### To Reproduce

Create another field for a single photo in the same collection. 
You can also try with two collections where the main key is the id created when the collection was created.

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

16.15

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-05-23 18:52
This is because MS SQL can't have multiple foreign key constraint triggers to the same related table. The field creation works if you set the relational trigger to "Prevent the deletion" or if you use the same field for the "Foreign key" when setting up the O2M field 🙂 

![CleanShot 2022-05-23 at 14 52 40@2x](https://user-images.githubusercontent.com/9141017/169887167-6ff1dd54-87bd-4ac2-bfbc-08a766441c1b.png)

**Comment by rijkvanzanten** [comment] 2022-05-23 18:53
(Duplicate of https://github.com/directus/directus/discussions/13356)

**Closed by rijkvanzanten** 2022-05-23 18:52 UTC
Labels: Bug (Potential)
