### ISSUE TITLE
Admin App: Alignment of half-width fields in detail group

### ISSUE THREAD

**Issue by jofmi** [directus/directus#20445] opened 2023-11-16 13:04 UTC
### Describe the Improvement

When having only half width fields in a detail group, the alignment seems to be wrong.

![grafik](https://github.com/directus/directus/assets/57440945/aa9f1433-0c13-4abf-85bf-3bc2f0ce32a9)

Directus Self Hosted v10.7.2 on Firefox

**Comment by br41nslug** [comment] 2023-11-16 14:49
I am unable to reproduce this issue in Firefox so "tiny tweak" is not the appropriate template here. Please elaborate on the issue following the issue template with reproduction steps etc.


https://github.com/directus/directus/assets/9389634/064e7a61-0a53-47f8-959f-41575419bd06


Closing this for now but happy to re-open if more information becomes available.

**Comment by sailrite** [comment] 2023-11-16 16:59
We also noticed this in Chrome.

![image](https://github.com/directus/directus/assets/134299342/6aec44c7-2802-4c33-aafa-0d040accf8d0)

**Comment by jofmi** [comment] 2023-11-16 17:20
@br41nslug, sorry for using the wrong format. I had to play around a bit until i could reproduce it on a fresh installation of directus - and managed with the following steps:

- Create two detail groups in directus_users
- Create three fields in each of the detail groups

![grafik](https://github.com/directus/directus/assets/57440945/de153ef1-08ff-44df-b643-806f4bd5bb50)

**Comment by br41nslug** [comment] 2023-11-16 17:31
Ah I see, I am indeed able to reproduce this with 2 or more detail groups 😄

**Comment by Seinnd** [comment] 2023-11-17 13:17
I also stumbled across this some time ago (_I think even pre 10.7._), but I thought it was intentional behaviour, that groups don't reset the grid index when creating the field view.

FYI @jofmi 
I just added this line of custom CSS:
```
@media (min-width: 960px) {
    .v-form > .half-right:first-child {
        grid-column: start/half!important;
    }
}
```
If this ever get fixed, this rule wouldn't inherit any more, so no drawbacks for using it.

**Closed** 2023-11-28 17:43 UTC
Labels: Package: @directus/app, Bug, Good First Issue
