### ISSUE TITLE
Change Password

### ISSUE THREAD

**Issue by rjbobeles** [directus/directus#5412] opened 2021-05-02 04:22 UTC
1. When a user changes password his/her password, the form gives out a pop-up showing:
 
`{
  "message": "Cannot read property 'startsWith' of null",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}`

2. Go to your profile and change the password

3. Directus: v9.0.0-rc.61
    MySQL: 10.5.9-MariaDB - Homebrew
    Deployment: npx
    Browser: Brave

4. Video: https://youtu.be/VAqeoXaQMJQ

**Comment by Cruze** [comment] 2021-05-03 08:04
I have the same issue 
Directus: v9.0.0-rc.61
MySQL version 5.7.33

**Comment by rijkvanzanten** [comment] 2021-05-03 13:40
Duplicate of https://github.com/directus/directus/issues/5310

**Closed by rijkvanzanten** 2021-05-03 13:40 UTC
