### ISSUE TITLE
edit items make some fields blink

### ISSUE THREAD

**Issue by KZ-Millennium** [directus/directus#9743] opened 2021-11-12 08:02 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a simple collection with a translation collection with a title (simple string output) and a description (markdown)

When I write something in one of these fields, all fields are blinking and sometimes characters are not written

![bug directus blink](https://user-images.githubusercontent.com/74610514/141433190-9596cdfb-1d14-4f6c-84a8-e154eeaa5611.gif)

### To Reproduce

Create a new collection with an input field and a translation

Add a field as an input string and a markdown field in the translation

Create an item in the collection

Edit it

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgres 11.3

### What browser are you using?

Firefox 93.0

### What operating system are you using?

Linux 5.4.0-1059-azure

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-11-12 08:29
Duplicate of #9547, which is a duplicate of #9510 (currently where this is tracked as they are caused by the same bug).

**Closed by azrikahar** 2021-11-12 08:29 UTC
Labels: Bug (Potential)
