### ISSUE TITLE
Hooks don't get triggered on item import from Directus app

### ISSUE THREAD

**Issue by hermanndettmann** [directus/directus#20339] opened 2023-11-06 12:04 UTC
### Describe the Bug

Hi,

I built a bundle extension with some hooks that manipulates some input data when importing items using the import functionality in the admin but since updating to `10.7.x` all those `items.create`, `items.update` filters and actions doesn't get triggered anymore.

I also have some hooks that run on creation and update to build slugs and they seem to work when editing and creating items in the admin. But on import they seem to get skipped entirely.

I'm not sure if that really is a bug or maybe some change on purpose but I would be happy for some feedback why this is not working anymore.

Thanks for your help!

### To Reproduce

Create a hook extension and add a `console.log` to `filter` or `action` for `items.create` or `items.update` events. Start a CSV import on your collection from the Directus app.  

### Directus Version

10.7.x

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2023-11-06 12:07
Thanks for opening this issue! However this is a duplicate of an existing issue #20284, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #20284 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2023-11-06 12:07 UTC

**Comment by hermanndettmann** [comment] 2023-11-06 12:09
Thanks @azrikahar ! I'll subscribe to https://github.com/directus/directus/issues/20284.
