### ISSUE TITLE
Collection Order in Role (Access Control) is not sorted

### ISSUE THREAD

**Issue by pfb93** [directus/directus#23128] opened 2024-07-30 07:06 UTC
### Describe the Bug

In earlier versions all Collections were sorted alphabetically when you select the rights in a role. However, now it seems to be completely mixed.

### To Reproduce

Create Collections and a Role and look at the order of the collections

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostrgeSQL

**Comment by hanneskuettner** [comment] 2024-07-31 08:38
This is a duplicate of https://github.com/directus/directus/issues/21658. I will be closing this issue and encourage you to follow along in https://github.com/directus/directus/issues/21658.

**Comment by hanneskuettner** [comment] 2024-07-31 08:38
Duplicate of #21658

**Closed by hanneskuettner** 2024-07-31 08:38 UTC
