### ISSUE TITLE
[UNKNOWN] Request failed with status code 413

### ISSUE THREAD

**Issue by ThijsCatwise** [directus/directus#18384] opened 2023-05-02 13:46 UTC
### Describe the Bug

When I upload an image bigger than 1MB I get the error: [UNKNOWN] Request failed with status code 413
I tried to change the MAX_PAYLOAD_SIZE in my docker-compose env but didn't fix it.

Someone knows how to fix this error?

### To Reproduce

When I upload an image bigger than 1MB I get the error: [UNKNOWN] Request failed with status code 413
I tried to change the MAX_PAYLOAD_SIZE in my docker-compose env but didn't fix it.

Someone knows how to fix this error?

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-05-02 18:50
As we've discussed on Discord, this is most likely caused by Nginx' default max body size on uploads 🙂 Closing this for now 👍🏻

**Closed by rijkvanzanten** 2023-05-02 18:50 UTC
