### ISSUE TITLE
Session expiring while being active

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#8856] opened 2021-10-16 18:20 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

While normally operating on the CMS, at random intervals the session expires and I have to log in again

### To Reproduce

No particular steps, I guess it is a timeout not working properly?

### Errors Shown

Token expired message 

### What version of Directus are you using?

9.0.0-rc.97

### What version of Node.js are you using?

16.11.1

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.11.0-37-generic

### How are you deploying Directus?

Docker

**Comment by benhaynes** [comment] 2021-10-16 18:33
Try upgrading to version 98, I believe this is fixed.

**Comment by darioguarascio** [comment] 2021-10-16 19:29
@benhaynes you guys are great, i can't keep up with releases.

**Comment by rijkvanzanten** [comment] 2021-10-16 19:55
This should be resolved in 98. Lemme know if the problem still persists for you after upgrading @darioguarascio  🙂

**Comment by rijkvanzanten** [comment] 2021-10-16 19:55
(Also duplicate of https://github.com/directus/directus/issues/8808)

**Closed by rijkvanzanten** 2021-10-16 19:55 UTC
Labels: Bug (Potential)

**Comment by darioguarascio** [comment] 2021-10-17 07:59
@rijkvanzanten doesn't look like happening again. I'll keep you posted

**Comment by darioguarascio** [comment] 2021-10-17 08:07
@rijkvanzanten it just happened again, but strange thing is that hitting F5 and refreshing the whole page did not log me out

**Comment by rijkvanzanten** [comment] 2021-10-17 13:13
@darioguarascio do you have a clearer idea of when it's happening to you now? It's a little difficult to debug and fix without knowing how to get it to show up on my end 😔
