### ISSUE TITLE
Installation is broken for PostgreSQL

### ISSUE THREAD

**Issue by fairhat** [directus/directus#5734] opened 2021-05-17 19:45 UTC
1) The issue and what you expected to happen
    The application can be installed, however on opening the website nothing is loaded, and the system logs prints:
    ```
    this_1.parseDefaultValue is not a function
    TypeError: this_1.parseDefaultValue is not a function
    ```

2) Exact steps to reproduce this issue

   * Create a directus app with admin user
   * Connect to postgres db
   * open localhost:8055

3) Your environment:
    What version of Directus you are using: rc68
    Which DBMS are you using (MySQL 8, Postgres 12, ...): PostgreSQL 13
    Which deployment are you using (npx, Docker, ...): NPX
    What browser are you using (Chrome 87, Safari 14, ...): All

4) Any other relevant information we might need to reproduce this issue
    This is related to the @directus/schema package.
    File: dialects/postgres.ts line 71 "this.parseDefaultValue"
    Which is related to knex-schema-inspector which had a few seemingly breaking commits today (05/17/2021)

Hope this is helpful

**Comment by rijkvanzanten** [comment] 2021-05-17 19:50
Duplicate of https://github.com/directus/directus/issues/5733

**Closed by rijkvanzanten** 2021-05-17 19:50 UTC
