### ISSUE TITLE
Sqlite installation failure

### ISSUE THREAD

**Issue by nightlyworker** [directus/directus#3278] opened 2020-12-02 23:40 UTC
```sh
 martin@vivo  ~/lab/directus/9  npx create-directus-project my-project        
? Choose your database client (Use arrow keys)
? Choose your database client SQLite (Beta)
? Database File Path: /home/martin/lab/directus/9/my-project/data.db

Something went wrong while seeding the database:

undefined Method implemented in the dialect driver

Please try again

? Database File Path: data1.db

Something went wrong while seeding the database:

undefined Method implemented in the dialect driver

Please try again

? Database File Path: ./data3.db

Something went wrong while seeding the database:

undefined Method implemented in the dialect driver

Please try again

? Database File Path: /home/martin/lab/directus/9/my-project/data4.db

Something went wrong while seeding the database:

undefined Method implemented in the dialect driver

Please try again

? Database File Path: (/home/martin/lab/directus/9/my-project/data.db) 
```
Ctrl+c
```sh
Couldn't seed the database. Exiting.
(node:176535) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (/home/martin/.config/yarn/global/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/martin/.config/yarn/global/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.create (/home/martin/.config/yarn/global/node_modules/create-directus-project/lib/index.js:73:2)
(node:176535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:176535) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rijkvanzanten** [comment] 2020-12-03 01:19
Duplicate of https://github.com/directus/directus/issues/2904

**Closed by rijkvanzanten** 2020-12-03 01:19 UTC

**Comment by nightlyworker** [comment] 2020-12-03 01:48
Oh sorry, didn't know is related. I was trying the beta 9 and it was working for me. What you see above is fresh new install with stable 9 (as of today).

**Comment by nightlyworker** [comment] 2020-12-03 01:50
And thanks! Sorry in rush.
