### ISSUE TITLE
File uploading/creation ignores certain fields

### ISSUE THREAD

**Issue by andy1li** [directus/directus#14975] opened 2022-08-09 10:36 UTC
### Describe the Bug

When uploading a file using the local adapter, fields such as `'filename_disk'` or `'filename_download'` cannot be set.

### To Reproduce

Try setting `'filename_disk'` and `'filename_download'` along with some other fields, when uploading a file.

<img width="455" alt="image" src="https://user-images.githubusercontent.com/1450947/183625750-e7b9ae7e-2302-4200-b2ac-91af64979814.png">

Additional info:

1. `'title'` and `'folder'` can be set correctly.
2. Permission is `'All Access'`

<img width="623" alt="image" src="https://user-images.githubusercontent.com/1450947/183626551-9fe117a7-b3f4-4aa4-bed3-aa3b91652f2e.png">

### Errors Shown

- `'filename_disk'` would be the same as the file id.
- `'filename_download'` would just be `blob`.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/1450947/183627341-92393b5d-de9b-40cd-8a6d-6ddbea9c5c2f.png">

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16

### What database are you using?

mysql 8.0.28

### What browser are you using?

chrome

### How are you deploying Directus?

self-hosted

**Comment by azrikahar** [comment] 2022-08-09 12:31
Seems to be due to those two properties are being overridden in these logic respectively:

- `filename_download` overrides the `payload.filename_download`:
 
   https://github.com/directus/directus/blob/ed82a01c2c93eb74df91385b554692d2e3ea3caa/api/src/controllers/files.ts#L80-L81
   
- `filename_disk` always get hardcoded here:

   https://github.com/directus/directus/blob/ed82a01c2c93eb74df91385b554692d2e3ea3caa/api/src/services/files.ts#L65

**Comment by andy1li** [comment] 2022-08-09 12:58
Thank you @azrikahar for the reply!

I wonder whether the documentation on uploading files could be improved slightly? (Because I can't know for sure whether there are bugs involved.)

Specifically, it would be nice to have more clarify on the minimal permissions that have to be set for fields (regarding uploading files).

I need to grant as little field permissions as possible. Since I can't find anything in the docs, a little trial and error yielded that these field permissions must be checked, otherwise 403 when uploading files.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1450947/183652009-cbcb3b7d-46cb-409a-bf2e-f64d48339901.png">

Sure, `title` is necessary, otherwise the file library would be impossible to navigate.

However, `storage` and `mime_type` don't seem necessary (at least to me).

And `filename_download` can't even be set right now.

**Comment by azrikahar** [comment] 2022-08-09 13:10
> I wonder whether the documentation on uploading files could be improved slightly? (Because I can't know for sure whether there are bugs involved.)
>
> Specifically, it would be nice to have more clarify on the minimal field permissions that have to be set (regarding uploading files).

@andy1li That's a very good question! The need for minimal field permissions for files definitely makes sense. Apart from documenting it, perhaps an alternative would be to do something similar that's already done to `directus_users`, where some fields _are_ the minimal fields by default.

This way it's more obvious that certain fields are integral for files to function properly:

![chrome_bTTAdu8n8D](https://user-images.githubusercontent.com/42867097/183655094-272bbc6b-0064-496c-ba4e-65ca184619b2.png)

**Comment by rijkvanzanten** [comment] 2022-08-09 14:22
That's currently by design. You can't set the filename_disk, as Directus adjusts the filename before saving it to disk, so setting that manually will cause various conflicts. Filename download is intended to match the original filename on upload. Happy to discuss improvements on this setup on a Discussion, but closing this for now as it's working as intended

**Closed by rijkvanzanten** 2022-08-09 14:22 UTC
Labels: API, Bug
