### ISSUE TITLE
Use `NestedPartial` for `item` argument in `createItem` function

### ISSUE THREAD

**Issue by hawaiiH** [directus/directus#21315] opened 2024-02-05 16:23 UTC
### Describe the Improvement

Directus offers a great feature for creating items and their related items. However, there are some issues with the current type implementation. Specifically, the fields in related items are marked as required, even when they are not necessary. This can lead to unnecessary complications.

I propose using a `NestedPartial` type for the `item` argument in the `createItem` function. This change would allow for more flexibility and accuracy in type definitions, especially for nested structures.

#### Current Implementation:
```ts
declare const createItem: <...>(collection: Collection, item: Partial<UnpackList<Schema[Collection]>>, query?: TQuery | undefined) =>  ... ;
```
#### Suggested Change 
```ts
declare const createItem: <...>(collection: Collection, item: NestedPartial<Schema[Collection]>, query?: TQuery | undefined) => ...;
```

**Comment by rijkvanzanten** [comment] 2024-02-05 16:26
Duplicate of https://github.com/directus/directus/issues/21212 🙂

**Closed by rijkvanzanten** 2024-02-05 16:26 UTC
