### ISSUE TITLE
Copy Shared link works locally but does not work on server

### ISSUE THREAD

**Issue by Pachat** [directus/directus#14360] opened 2022-07-11 09:25 UTC
### Describe the Bug

Sorry to reopen this #14702. But it looks like the reproduction tests were made locally (where indeed it works).
But on a server, Copy shared link is not working (the clipboard stays unchanged) 

### To Reproduce

1. On a detail, create a shared link
2. Empty the clipboard
3. Copy the link

### Errors Shown

The clipboard is still empty

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

v16.14.0

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

**Comment by rijkvanzanten** [comment] 2022-07-11 12:49
Duplicate of https://github.com/directus/directus/issues/14072

**Closed by rijkvanzanten** 2022-07-11 12:49 UTC
Labels: App, Bug (Potential)
