### ISSUE TITLE
Paste text into search box won't trigger filter

### ISSUE THREAD

**Issue by jianliao** [directus/directus#3948] opened 2021-02-05 21:58 UTC
When I type in text in search input, table will start filtering. But if I paste text into it, filter would not be triggered.
![Feb-05-2021 13-54-46](https://user-images.githubusercontent.com/1207520/107093481-2529b380-67ba-11eb-8845-1319ea6bbeef.gif)
v9.0.0-rc.34

**Comment by rijkvanzanten** [comment] 2021-02-05 22:39
Duplicate of https://github.com/directus/directus/issues/3792

**Closed by rijkvanzanten** 2021-02-05 22:39 UTC
