### ISSUE TITLE
multiple Many to One relation Elements

### ISSUE THREAD

**Issue by addagudisanjay** [directus/directus#16855] opened 2022-12-19 16:16 UTC
### Describe the Bug

I am trying to use use many to one element in my table and using the delete cascade function I am getting the internal server error because of Foreign key constraint. For the first Many to one relation element there is no issue but from the second many to one relation element, I am getting the internal server error.

Directus Version:9.21.2
Database: Microsoft SQL

### To Reproduce

Create Multiple many to one relation elements with latest directus version and mssql as Database.

### Errors Shown

![image (1)](https://user-images.githubusercontent.com/120687605/208470411-e1bfd980-a149-40bc-bec6-6a5a3ddf1e4a.png)
![image](https://user-images.githubusercontent.com/120687605/208470417-38225e25-3a5b-46f8-ae6c-dcf847fa962d.png)

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

*

### What database are you using?

Microsoft SQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment] 2022-12-19 16:39
Duplicate of #16620

**Closed by licitdev** 2022-12-19 16:39 UTC
