### ISSUE TITLE
Editing Data Model gives error "Invalid payload".

### ISSUE THREAD

**Issue by geantas** [directus/directus#4092] opened 2021-02-16 13:12 UTC
I have created a data model (A) which has a many-to-many relationship with other model (B). Initially, I could not select which B model's fields I could see when adding an item to collection. I can create new items by following the model A with no problem, I just don't see the ID and Title of the model B.
Then, I do edit the model A's many-to-many relationship to model B. I can select which fields I'd like to use/see when creating items in the A's collection. However, when I save the changes, I am getting error: 
```
{
  "errors": [
    {
      "message": "\"type\" must be one of [bigInteger, boolean, date, dateTime, decimal, float, integer, json, string, text, time, timestamp, binary, uuid, hash, csv]",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```
Looking into Network tab on DevTools, I notice the request to update the model is issued, but it's a Bad Request (400) error. The `type` is `null` there. If I go to Schema tab, I can see type selected as "Alias" and I cannot change that.

My workaround: open Insomnia & make a new request with the same body + type set & it works this way. But it would be awesome to see this fixed anyways.

I am using Directus 9 with MySQL & npx:
```
  "dependencies": {
    "directus": "^9.0.0-rc.37",
    "mysql": "^2.18.1"
  }
```

![image](https://user-images.githubusercontent.com/34267171/108067202-bd4c5600-7060-11eb-89cf-112f29409980.png)
![image](https://user-images.githubusercontent.com/34267171/108067263-d2c18000-7060-11eb-9721-e71d33a8150f.png)

**Comment by sercanvirlan** [comment] 2021-02-16 14:48
i confirm this issue. this is my payload. type field -which is disabled- is null.

```
{
	"field": "videos",
	"type": null,
	"meta": {
		"id": 82,
		"collection": "series",
		"field": "videos",
		"special": ["m2m"],
		"interface": "many-to-many",
		"options": {
			"fields": ["video_id.title"]
		},
		"display": null,
		"display_options": {
			"template": "{{video_id.images}}{{video_id.title}}"
		},
		"locked": false,
		"readonly": false,
		"hidden": false,
		"sort": 4,
		"width": "full",
		"group": null,
		"translations": [{
			"language": "en-US",
			"translation": "Videos"
		}],
		"note": null
	}
}
```

**Comment by rijkvanzanten** [comment] 2021-02-16 18:57
Duplicate of https://github.com/directus/directus/issues/4048, fixed in https://github.com/directus/directus/pull/4061

**Closed by rijkvanzanten** 2021-02-16 18:57 UTC
