### ISSUE TITLE
App shows non-editable fields as editable in update

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16834] opened 2022-12-15 21:19 UTC
### Describe the Bug

On a collection with an input field, with a permission to update for the user_created only, others can still edit the field.
They get an error on saving.

### To Reproduce

1. A collection with (id, user_created, input_field)
2. The regular role has all access on the collection, except for Update where permission item is

```
{
	"_and": [
		{
			"user_created": {
				"_eq": "$CURRENT_USER"
			}
		}
	]
}

```
3. Create an item

4. Connect with an another user account

### Errors Shown

- You can still edit the input of the item creator (that you are not)
- On saving, you get 
```
{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}

```
=> Better not allow any editing of the fields that you are not allowed to edit.

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

19.0.1

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

**Comment by rijkvanzanten** [comment] 2022-12-15 22:34
Linear: [ENG-106](https://linear.app/directus/issue/ENG-106/update-permission-filter-not-correctly-applied)

**Comment by Pachat** [comment] 2023-03-08 15:10
I hope this will have a resolution in the next version.
Because right now the end user who is redirected to `admin/content/:collection/ec1c0f9f-ab71-4bc0-939e-b16620435084` will see all editable fields but when not allowed to edit , will receive an error message only when saving .
Better to allow him to see the fields but not to modify them.

**Comment by hanneskuettner** [comment] 2024-04-23 14:33
I'm unable to reproduce this in v10.10.7 and will close this issue. Feel free to comment on this issue if the error happens to persist in the current version!

**Closed by hanneskuettner** 2024-04-23 14:33 UTC
Labels: :cake: Bug, :file_folder: Forms
