### ISSUE TITLE
Open Api Spec can't be validated -> client code gen ends in broken client

### ISSUE THREAD

**Issue by cf-ts** [directus/directus#16474] opened 2022-11-16 15:33 UTC
### Describe the Bug

If you take the open api spec from a fresh directus install and put it into https://editor.swagger.io, you see that there are some structural errors... Most have to do with wrong syntax for required properties, which (only) leads to missing required info on that fields. But a wrong syntax in the components section, leads to a complete broken client when generated out of this spec, because references are missing.

### To Reproduce

- Install directus
- get open api file
- validate the file (i.e. on https://editor.swagger.io)
=> see errors

### Errors Shown

Most significant error:

Structural error at components
should NOT have additional properties additionalProperty: definitions
Jump to line 5735

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.18.0

### What database are you using?

mysql

### What browser are you using?

irrelevant

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-11-16 15:38
Duplicate of https://github.com/directus/directus/issues/14869

**Closed by rijkvanzanten** 2022-11-16 15:38 UTC
