### ISSUE TITLE
I did exactly as you have said and i get an error 403 vorbidden.  The image gets saved to files in directus and i get the image response and saved the id to this.form.images. Please what can be the problem.

### ISSUE THREAD

**Issue by Mbengparis** [directus/directus#5092] opened 2021-04-16 06:20 UTC
Ans: 
""" You can't use multipart/form-data to submit to a regular item. Upload the files first using the POST /files endpoint, and save the resulting UUIDs under images in the POST /items/collection """""

<-------------Problem------------->

I did exactly as you have said and i get an error 403 vorbidden.  The image gets saved to files in directus and i get the image response and saved the id to this.form.images. Please what can be the problem.

In directus my field is a multiple file field, meaning i can save either one or many images. But when i do manual upload in directus, everything works perfect which means its not a permission problem i guess.

Here is an example of what you said:
<--Html code-->

form:{
title: '',
description: ''
images: []
}

const formData = new FormData();

formData.append('file', image);

 axios.post(`http://localhost/files/?access_token=${token}`, formData, 
  {
    headers:{
    'Content-Type': 'multipart/form-data; charset=utf-8; boundary=__X_BOUNDARY__',
  }
  })
.then((res) =>{
 
/// on response I pushed the image id from my files to my form image

this.form.images.push(res.data.data.id)
 
   
  axios.post(`http://localhost/items/collection?access_token=${token}`, this.form) 

/// Here on response i get 403 error
}

_Originally posted by @Mbengparis in https://github.com/directus/directus/discussions/5077#discussioncomment-618895_

**Comment by rijkvanzanten** [comment] 2021-04-16 13:42
Duplicate of https://github.com/directus/directus/discussions/5077

(Please don't cross-post)

**Closed by rijkvanzanten** 2021-04-16 13:42 UTC
