### ISSUE TITLE
Replace-File: Performance issues in combination with shared network storage (e.g. AWS EFS)

### ISSUE THREAD

**Issue by schlensen** [directus/directus#17429] opened 2023-02-07 13:29 UTC
### Describe the Bug

Currently as I can see the mentioned functionality of replacing a file / image is implemented as follows (https://github.com/directus/directus/blob/main/api/src/services/files.ts#L61):

- Get the contents / all files of the uploads-directory
- Filter the files where filename_disk begins with primaryKey (for catching thumbnails)
- Delete each found file (original file which should be replaced and related thumbnails)

The more the uploads-directory grows the more this implementation will slow down.
In our case we use a shared network storage using AWS Elastic File System. 
Starting around 200 (image-) files the replace-operation slows down, at around 800 files we measure values between 8 and 12 seconds, getting worse the more files we upload. 
The only snippet that slows down is the iteration and deletion (removed the snippet and repeated the test):

```
const disk = storage.location(payload.storage);

for await (const filepath of disk.list(String(primaryKey))) {
    await disk.delete(filepath);
}
```

Replacing the snippet with something different / native to delete the original file including thumbnails, e.g. (ugly):

```
var command = 'rm -f /directus/uploads/' + primaryKey + '*';
execSync(command).toString();
```

the operation speeds up massively.

As I can see the main problem is that there is no option to get information about thumbnails from the database.
If we could have the exact filenames from a directus_files-item for each thumbnail (with connection to the original file) we could just delete those items without searching / iterating over each file in the uploads-directory. This should speed up the whole process but requires storing each thumbnail-combination in a dedicated directus-file, probably with relation to the original-file.

### To Reproduce

- Setup directus using a network attached storage for files, e.g. AWS Elastic File System
- Upload a bunch of files, around 1000
- Open a file, hit the "replace file" button and upload a new file
- The operation should take some time

Note: If there are no changes in the uploads-directory the content of the directory seems to get cached (by Linux itself?) after listing the directory once. But in a highly frequented system this is not an option.

### Errors Shown

No errors.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

v18.13.0

### What database are you using?

Postgres10

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2023-02-07 14:49
Duplicate of https://github.com/directus/directus/discussions/13559

**Closed by rijkvanzanten** 2023-02-07 14:49 UTC
