### ISSUE TITLE
sort does not populate when manual toggled

### ISSUE THREAD

**Issue by udf2457** [directus/directus#15129] opened 2022-08-17 18:42 UTC
### Describe the Bug

Whilst I accept the (potential) argument that `sort` is `null` when `Toggle Manual Sorting` is **_not_** activated in the UI, I would suggest it is a bug that when `Toggle Manual Sorting` **_is_** activated that the value is still `null`.

At present, `sort` is not populated unless the user actually moves an item in the UI.  However I feel that `sort` should be populated the instant that manual sorting is enabled

### To Reproduce

Create collection.
Toggle manual sorting (but *DO NOT* move items)
Note that value is still `null` in REST
Move items
Note values now populated in rest

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16

### What database are you using?

Postgres 14

### What browser are you using?

Firefox

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment] 2022-08-17 19:36
Duplicate of https://github.com/directus/directus/issues/11430

**Closed by rijkvanzanten** 2022-08-17 19:36 UTC
