### ISSUE TITLE
[Insights] Panels doesn't respect the size when save

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#13480] opened 2022-05-23 10:29 UTC
### Describe the Bug

The panels doesn't respect the size:

https://user-images.githubusercontent.com/1007051/169800184-5a7535d3-7595-4708-a2ae-403a79c00917.mov

### To Reproduce

⬆️

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

16

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by azrikahar** [comment] 2022-05-23 10:36
I can't seem to reproduce this locally on 9.11.0:

https://user-images.githubusercontent.com/42867097/169800783-b7f4535f-4a6f-410a-90a3-bfaa56a6af49.mp4

Is this consistently happening? Were you able to replicate this behavior on a different device and/or different browser? Can you try incognito or disabling all browser extensions? I'm not quite sure what else could be the potential cause here 🤔

I'll close this for now, but happy to debug further or re-open once more information is available for us to reliably reproduce this issue.

**Closed by azrikahar** 2022-05-23 10:36 UTC
Labels: Bug (Potential)

**Comment by abdonrd** [comment] 2022-05-23 10:44
Just tried with Chrome incognito with the same behavior.

**Comment by azrikahar** [comment] 2022-05-23 10:57
Hmm can you try checking the PATCH request right after you resize and hit save? For example, here mine shows it as width `20` (since I resized it to 20 if we observe the top right corner of the panel):

https://user-images.githubusercontent.com/42867097/169804599-19ca3f35-3be2-4281-8c55-2985fe10b440.mp4

---

Another additional thought I have is could this somehow be related to cache? 🤔 i.e. you're (somehow) getting the old width. But let's see what do you see first from the devtools upon saving before we jump to any conclusions here.

**Comment by abdonrd** [comment] 2022-05-23 11:06
> Hmm can you try checking the PATCH request right after you resize and hit save? For example, here mine shows it as width `20` (since I resized it to 20 if we observe the top right corner of the panel)

Yeah, the PATCH request is right!

**Comment by abdonrd** [comment] 2022-05-23 11:08
In fact, when I enter the first time (so the view mode) the size is wrong.
But just with click on the Edit panels button, it changes to the right size.

**Comment by azrikahar** [comment] 2022-05-25 11:47
That does sounds like it's oddly some form of cache (or state). Were you able to reproduce this if you clear all cache and/or restart Directus?

**Comment by abdonrd** [comment] 2022-07-04 08:44
> That does sounds like it's oddly some form of cache (or state). Were you able to reproduce this if you clear all cache and/or restart Directus?

How can I clear the cache?
(we have deployed with a Docker image)

**Comment by azrikahar** [comment] 2022-07-05 02:32
> How can I clear the cache? (we have deployed with a Docker image)

You can use the `/utils/cache/clear` endpoint as an admin user: https://docs.directus.io/reference/system/utilities/#clear-the-internal-cache 👍

Not entirely sure will this matter, but do try to clear the cache _after_ you resize but _before_ you hit save. Let us know whether it helped! Seems like another user reported a very similar issue with height resizing in #14281, so it is more likely this is not an isolated incident after all.

**Comment by abdonrd** [comment] 2022-07-05 08:06
> > How can I clear the cache? (we have deployed with a Docker image)
> 
> You can use the `/utils/cache/clear` endpoint as an admin user: https://docs.directus.io/reference/system/utilities/#clear-the-internal-cache 👍
> 
> Not entirely sure will this matter, but do try to clear the cache _after_ you resize but _before_ you hit save. Let us know whether it helped! Seems like another user reported a very similar issue with height resizing in #14281, so it is more likely this is not an isolated incident after all.

Thanks @azrikahar!
I just tried, but it didn't work. 😕

**Comment by abdonrd** [comment] 2022-07-22 09:23
@azrikahar We should re-open the issue, right?

**Comment by azrikahar** [comment] 2022-07-22 09:26
> @azrikahar We should re-open the issue, right?

Let's track this in #14281, as they feel like the same thing 🙂
