### ISSUE TITLE
Improve Delete REST API status code

### ISSUE THREAD

**Issue by alishi973** [directus/directus#17463] opened 2023-02-09 10:50 UTC
### Describe the Bug

I was working as a hobby on a small project with Directus.
I tried this delete API to delete one of the defined items in the products collection, but the status code that comes from this API is confusing because it will return `204` at all times, even when the item is completely deleted.
Because I expect to receive a `404` status code when trying to delete something that has not to exist. Or I expect something other than `204` on a successful delete attempt (maybe `200` for a successful delete attempt)

### To Reproduce

It's so simple, just create a project with predefined data, then use post-man or anything else like this to make a request on this URL to the project:

`DELETE /items/:collection/:id`

which returns `204` with an empty body (as described on [document](https://docs.directus.io/reference/items.html#rest-api-6))

then try again with the same item and it will return `204` again which means `NO CONTENT`

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.14.2

### What database are you using?

Default for PaaS

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by rijkvanzanten** [comment] 2023-02-10 19:57
Heya! This is currently working as expected, so I'll close this as it's not a bug. Feel free to open a new Feature Request to improve this, or upvote / expand on one that's very similar: https://github.com/directus/directus/discussions/4368

**Closed by rijkvanzanten** 2023-02-10 19:57 UTC
