### ISSUE TITLE
Post of a product forbidden

### ISSUE THREAD

**Issue by jasazupancic123** [directus/directus#23031] opened 2024-07-16 12:52 UTC
### Describe the Bug

I posted a product and it was posted ok. I only posted the product, nothing else. Then i deleted it and wanted to post it again, but then i get the response from the server, saying "You don't have permission to access this." and "code: 'FORBIDDEN'". The bug is not in the permissions

### To Reproduce

Post a product, then delete it, then try to post it again

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2024-07-16 13:17
I'm not able to reproduce this based on the limited information shared, so I'll close this for now. What does your data model look like? Anything in the API logs? Happy to reopen when more information becomes available

**Closed by rijkvanzanten** 2024-07-16 13:17 UTC
