### ISSUE TITLE
API calls running slow (~4 seconds)

### ISSUE THREAD

**Issue by jroxendal** [directus/directus#1575] opened 2017-06-14 10:47 UTC
## Version Info
  - Directus version and branch: version/6.4 e98001a7
  - PHP version: 5.6.23
  - MySQL version: Ver 15.1 Distrib 10.0.23-MariaDB
  - Web server: (Ex. Apache, nginx or IIS?) Apache

## Expected Behavior
Since the underlying SQL query only takes milliseconds, I'd expect to see the resulting JSON from the `/rows` endpoint equally fast. 

## Actual Behavior
`/rows` takes about 4 seconds. If I filter out only the columns I need I can bring it down to 1.6s, compared to 40 ms when asking the db directly. 

My sysadmin installed [webgrind](https://github.com/jokkedk/webgrind) and tells me that `flatKey` in `api/core/Directus/Util/ArrayUtils.php` is doing most of the processing. 

 Any idea of how to speed up the API?

**Comment by WellingGuzman** [comment] 2017-06-14 14:56
Hey @jroxendal,

Thanks for reporting this, can you share an example schema to reproduce this?

**Comment by benhaynes** [comment] 2017-07-25 03:09
@WellingGuzman – could this be related to the Interface Gallery taking so long to load the listing page?

**Comment by WellingGuzman** [comment] 2017-07-25 03:21
@benhaynes it's related in a way with the long fix (fetching all columns issue) could have some effect, which now will take less to load, but still need to figure it out where `flatKey` helper is taking long to process. I will try tomorrow.

@jroxendal can you confirm if the request is taking a less time to load now after some fixes we did recently?

**Comment by jroxendal** [comment] 2017-07-26 10:45
I'm on a European-style long vacation right now, I'll have to get back to you mid August or so!

**Comment by MartinMekhaiel** [comment] 2017-09-12 16:19
i have the same issue #1807

**Comment by MartinMekhaiel** [comment] 2017-09-12 21:25
is there a bugfix planned soon? otherwise the api is not really usable for the web with 5s response time?

**Comment by benhaynes** [comment] 2017-09-12 22:24
We're researching and working on the root cause over the next few days. We also have a parallel workstream for caching that will (optionally) speed things up.

**Comment by MartinMekhaiel** [comment] 2017-09-13 02:02
okay, is there a way to try the caching that out?

**Comment by WellingGuzman** [comment] 2017-09-13 02:07
The caching layer is currently under development, there's no way to try it out now, sorry.

**Comment by jroxendal** [comment] 2017-09-13 08:35
For what it's worth, I'm at around three seconds when querying the `rows` endpoint now, so perhaps some improvement has occurred over the summer. Filtering out a single item using an `[eq]` filter takes 1.1s. These are till orders of magnitude beyond direct mysql queries. 

`/rows` using `curl -w "%{time_connect} + %{time_starttransfer} = %{time_total}`:
0,005889 + 2,641796 = 2,818171

**Comment by WellingGuzman** [comment] 2017-10-16 23:00
We took another path and just avoid flatting the whole thing, because why we do that if we are only looking for one value. The slowness is noticeable when you try to get data from a big array.

Implementing cache after this will be a big hit, but for now this will be faster than before.

Closed by https://github.com/directus/directus/commit/71cdaf04363918ffc7ce7d0ea85c5d6002cb9e88

**Closed by WellingGuzman** 2017-10-16 23:00 UTC
Labels: 3. Major, API, Help Wanted, Optimization
