### ISSUE TITLE
Inconsistent version reporting

### ISSUE THREAD

**Issue by jtlindsey** [directus/directus#17534] opened 2023-02-15 14:20 UTC
### Describe the Bug

Version details under "Request Feature" under Settings > Directus report `Directus
9.22.3`

![image](https://user-images.githubusercontent.com/7409277/219051760-64763675-4088-4cff-98a7-39db0f558622.png)

Version details in the information panel under Settings > Project Settings > Information report `Directus Version
9.22.4`

![image](https://user-images.githubusercontent.com/7409277/219052186-62c61c16-a3d0-4eeb-8c01-79852253e3e3.png)

### To Reproduce

Follow steps from quick start for self-hosted docker. https://docs.directus.io/self-hosted/quickstart.html and using [docker example](https://docs.directus.io/self-hosted/docker-guide.html#docker-compose). Note image is ` image: directus/directus:latest`

### Errors Shown

No errors

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.13.0

### What database are you using?

Postgres

### What browser are you using?

Safari

### How are you deploying Directus?

Local docker

**Comment by paescuj** [comment] 2023-02-15 14:57
Thanks for opening this issue! However this is a duplicate of an existing issue https://github.com/directus/directus/issues/17115, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to https://github.com/directus/directus/issues/17115 for future updates.

**Closed by paescuj** 2023-02-15 14:57 UTC
