### ISSUE TITLE
Error: Illegal mix of collations

### ISSUE THREAD

**Issue by iksent** [directus/directus#4461] opened 2021-03-10 16:10 UTC
1. I have Categories and Tags for Articles - they are very similar.
2. No errors, when trying to retrieve categories
3. But getting weird error, when trying to retrieve tags

```
"select `tag_translations`.`name`, `tag_translations`.`tag_id`, `tag_translations`.`id` from `tag_translations` left join `languages` as `s342E2On` on `tag_translations`.`languages_code` = `s342E2On`.`code` where `s342E2On`.`code` = 'ru-RU' and `tag_translations`.`tag_id` in (1) - ER_CANT_AGGREGATE_2COLLATIONS: Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='"
```

GraphQL:

```
query articles {
  items {
    article {
      categories { <<< NO ERROR
        category {
          id
          translations(filter: {languages_code: {code: {_eq: "ru-RU"}}}) {
            name
          }
        }
      }
      tags { <<< PRODUCES ERROR
        tag {
          id
          translations(filter: {languages_code: {code: {_eq: "ru-RU"}}}) {
            name
          }
        }
      }
    }
  }
}
```

MariaDB dump: [dump-2.sql.zip](https://github.com/directus/directus/files/6117263/dump-2.sql.zip)

### Project details
Directus Version: 9.0.0-rc.45
Environment: production
OS: Linux 5.4.0-65-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment] 2021-03-10 16:14
Strange! For whatever reason, your two tables in the DB have a different collation, which causes MariaDB to throw an error about it 🤔 

Did you create one table directly in the db instead of in Directus? Or did you change something after the fact in collation configuration of your database/tables maybe?

**Comment by iksent** [comment] 2021-03-10 16:43
All tables were created from Directus.
1. I created quite all tables except "Tags" from my local machine
2. Then transferred the table to the test server
3. And then created Tags table there

I see, that Tags don't have collation at all:

```
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `tag` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `sort` int(11) DEFAULT NULL,
  `user_created` char(36) DEFAULT NULL,
  `date_created` timestamp NULL DEFAULT NULL,
  `user_updated` char(36) DEFAULT NULL,
  `date_updated` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
```

Other tables have it:

```
DROP TABLE IF EXISTS `languages`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `languages` (
  `code` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
```

**Comment by rijkvanzanten** [comment] 2021-03-10 16:50
Is there a difference in default-collation settings on the database locally vs remote? (That sounds like the likely culprit here)

**Comment by iksent** [comment] 2021-03-10 16:59
That's likely the problem! We are trying to investigate the default collation on remote. I'll respond, when we change it and recreate tables.

**Comment by rijkvanzanten** [comment] 2021-03-10 17:03
FWIW, Directus itself doesn't set/control/does anything with collations, so I'm gonna close this for now as I'm pretty sure it's caused by a difference in config between the two MariaDB instances 👍🏻

**Closed by rijkvanzanten** 2021-03-10 17:03 UTC
Labels: Needs More Info

**Comment by iksent** [comment] 2021-03-10 17:57
We have changed default collation, recreated the table and there is no error now.
Thanks, @rijkvanzanten!
