### ISSUE TITLE
Custom Translations break after viewing the data-model page

### ISSUE THREAD

**Issue by alexvdvalk** [directus/directus#22362] opened 2024-05-02 19:57 UTC
### Describe the Bug

If using custom translations, the translation display breaks after you view or edit fields of any other collection.

### To Reproduce

Navigate to /admin/content/[your collection with custom translations]
note that translated fields display correctly.
Right click and edit any collection. 
Navigate back to the Content 
Note that custom translation display no longer display correctly.

https://github.com/directus/directus/assets/21194068/b3cad0f1-d67a-4174-b39a-8e5aaa9eff4c

### Directus Version

10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-05-03 06:32
This is actually a duplicate of #22256 which has been fixed in #22263 and will be available in the next release :)

**Closed by hanneskuettner** 2024-05-03 06:32 UTC
Labels: :cake: Bug
