### ISSUE TITLE
Conditions not working as expected for m2o fields

### ISSUE THREAD

**Issue by MarkoMestrovicShape** [directus/directus#10952] opened 2022-01-10 13:23 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Setting condition rule with a relational field, such as:
collectionO->key equals 3 doesn't work consistently.

### To Reproduce

Create two collections. Give them m2o relationship. In the M collection choose one field and give it condition that includes checking value of O field. 

For example:

collection_M->key equals KEY_VALUE

Checkbox the Hidden on Detail option.

The field never becomes hidden no matter which O field is selected.

### Errors Shown

None

### What version of Directus are you using?

v9.4.3

### What version of Node.js are you using?

v14.5.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by Oreilles** [comment] 2022-01-10 15:26
Closing as duplicate of https://github.com/directus/directus/issues/8228

**Closed by Oreilles** 2022-01-10 15:26 UTC
Labels: Bug (Potential)
