### ISSUE TITLE
Create new item in the M2M field for a different collection in the main collection. Not saving the entire item list. 

### ISSUE THREAD

**Issue by koksikus** [directus/directus#10213] opened 2021-12-02 10:56 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a strange error while saving the record. In the Process collection I have a field is M2M that contains a list of tools. If I have it set, "add an existing one" and "add a new one item" button, then when I click on the "add new one item" button, I fill it with data, I also add the existing one from the collection of tools and click close, the process does not save this list in the process collection. If I only add through "add existing ones" button, it saves perfect. I got rid of the add new button. And I go into the collection of tools and add new ones there, and then into the process and select the existing ones.
Perhaps important information in the collection of tools are also M2M fields that pertain to other collections. I have not set the duplication fields, because I am creating a new item - I do not copy records. Maybe I set something wrong. So I am asking for help.

### To Reproduce

Create two or even more collections. In the first, create an M2M field in which you select items from the second collection. In the second collection there is a field from the first collection as well as there are M2M fields relating to the next collection and it has information from that collection. In the settings of the first collection, set the possibility of creating an item and adding an existing one. Mix these, add new ones with the existing ones. Maybe important information in the second collection are the next M2M fields relating to the next collections. Maybe it is also important, users cannot see this next collection, but the conditions indicate that the value may be null.

### Errors Shown

There are no errors like you don't have permissions etc, it just fails. 

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

Sql server 2017

### What browser are you using?

Edge

### What operating system are you using?

Debian 11.1

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment] 2021-12-02 19:32
Can you check if this is a duplicate of https://github.com/directus/directus/issues/9977 ?

**Comment by koksikus** [comment] 2021-12-02 19:40
Hi it's not the same. I am adding more items. It shows a longer and longer list, but when I want to save a record in the main collection, it saves all the data except the created list from the selected and added items.

**Comment by Oreilles** [comment] 2021-12-03 15:26
I see that this issue was submitted while you were on `v9.0.1`. As indicated in the second checkbox you have to confirm your issue is present in the latest version (now `v9.1.2`) before submitting an issue:
- [x] I'm on the latest version of Directus.

Please upgrade and tell us if you're still facing your issue.

**Comment by koksikus** [comment] 2021-12-08 07:52
I know the core of the problem. (In process in filed M2M we add item to another collection). If we add a new item and we do not fill in the required field, we do not receive information about it. It only shows in the list that the item was added, but didn't really create it because it was not as intended. With the latest version it won't let you save, but the user won't know why.

**Comment by koksikus** [comment] 2021-12-18 10:34
In the right side panel (after clicking create a new one item) . Without filling in the required fields, it allows you to close this side panel whitout any error pops up. When saving the record in main collection still no error pops up why the item was not created...
![Zrzut ekranu 2021-12-18](https://user-images.githubusercontent.com/90528895/146637861-69b91472-ce9b-47c2-9bd4-6bd128da862e.jpg)

**Comment by azrikahar** [comment] 2021-12-20 05:35
Seems like this turns out to be a duplicate of #9176. Will reopen if it ended up being different.

**Closed by azrikahar** 2021-12-20 05:35 UTC
Labels: Needs More Info
