### ISSUE TITLE
Custom permissions for policy by fails on `roles -> policy Contains ...` rule

### ISSUE THREAD

**Issue by RawmanGrey** [directus/directus#23640] opened 2024-09-11 16:52 UTC
### Describe the Bug

Setting custom permission on reading `directus_users` items as following `{"_and":[{"role":{"policies":{"_contains":"given-policy-uuid-string"}}}]}` leads to below error shown to affected user trying to access `/admin/content`:
```
{
  "errors": [
    {
      "message": "Invalid query. \"uuid\" field type does not contain the \"_contains\" filter operator.",
      "extensions": {
        "reason": "\"uuid\" field type does not contain the \"_contains\" filter operator",
        "code": "INVALID_QUERY"
      }
    }
  ]
}
```

### To Reproduce

Create new policy with Application access enabled, choose directus_users table `Read`, click `Use custom` and set  `{"_and":[{"role":{"policies":{"_contains":"REPLACE_ME_WITH_POLICY_UUID"}}}]}` filter. 

Assign policy to user and try to login using his account.

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by hanneskuettner** [comment] 2024-10-03 08:55
The reason you get this error is that the `_contains` operator is not supported for the `uuid` type. For `uuid`s you can only use the `_eq,_neq,_in,_nin,_null,_nnull` operators. I'm closing this, as this is expected behaviour.

**Closed** 2024-10-03 08:55 UTC

**Comment by burka** [comment] 2024-10-03 09:36
It would be great if the UI could reflect such constraints as it is not intuitive and that error appears only later on while using it, possibly for another role you would need to test.
