### ISSUE TITLE
Directus does not mirror db properly when change a m2m junction table field name

### ISSUE THREAD

**Issue by beta-interfaces** [directus/directus#6842] opened 2021-07-15 21:44 UTC
### Describe the Bug

I have a m2m field that relates the collections inquiries and answers (on the junction table, the relationship fields are inquiries_id and answers_id). It works normally.

On the db, I renamed the fields inquiries_id and answers_id to inquiry_id and answer_id, and then I cannot access the collection anymore. I get this error:

{
  "errors": [
    {
      "message": "select \"knowledge_base\".\"id\", \"knowledge_base\".\"inquiries_id\" from \"knowledge_base\" where \"knowledge_base\".\"inquiries_id\" in ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) order by \"knowledge_base\".\"id\" asc - column knowledge_base.inquiries_id does not exist",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### To Reproduce

1. On Directus, create a m2m field that relates the collections inquiries and answers
2. Add an item to the inquiries collection, including one answer
2. On the db, rename the fields inquiries_id and answers_id to inquiry_id and answer_id
3. Access the collection on Directus to get the error

### What version of Directus are you using?

v9.0.0-rc.83

### What version of Node.js are you using?

v15.11.0

### What database are you using?

postgres 13.2

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-07-15 21:53
Duplicate of https://github.com/directus/directus/discussions/6803

**Closed by rijkvanzanten** 2021-07-15 21:53 UTC
Labels: Bug (Potential)
