### ISSUE TITLE
App breaks when going offline

### ISSUE THREAD

**Issue by sabinehoi** [directus/directus#4700] opened 2021-03-27 00:34 UTC
Hi guys, great work with Directus, really enjoying using it.

An issue my clients complain about is that when going offline while filling a form, the app does a weird thing where after ~5 minutes it resets all styles and shows a "page not found" - causing data loss. When you go back online, you are faced with the login page.

![image](https://user-images.githubusercontent.com/80796687/112704843-01b6e700-8e94-11eb-87ee-1257170bf7c1.png)

I think this issue happens when it requests the refresh token while offline

Directus Version: 9.0.0-rc.51
Database: Postgresql 9.6
Node: 14.15.4
OS: Windows 10

**Comment by joeinnes** [comment] 2021-03-28 17:43
If I'm reading properly here, there are two timeouts set:

1. Line 94 - if the token is valid for more than 10 seconds from now. This timeout will run 10 seconds before the expiresAt time - now, which will normally be 10 seconds before the token is due to expire. This seems to be potentially introducing a bug as it will pass a negative value in case the expiry time has already passed or is less than 10 seconds from now. https://stackoverflow.com/questions/43358029/settimeout-does-not-work-with-medium-sized-negative-numbers/43358488, and negative values can produce positive timeout values (although I don't actually think this is the issue here)

2. Line 136, which is set to trigger 10 seconds before the expiry. What's interesting is that on line 122, the promise is rejected, so the timeout on line 136 is not set.

This leads to the conclusion that if the refresh fires normally, the first timer one line 93 will not be set (because there will be 10s or less until expiry, but the second timeout does not get set because the refresh call on line 110 results in an error, is caught, but then rethrown without setting a new timer.

I think that the logical thing to do would be to include between line 121 and the throw on line 122 a new timeout that periodically retries to refresh the token. For example:

````
if (this.autoRefresh) {
  this.autoRefreshTimeout = setTimeout(() => this.refresh(false), 10000);
}
````

Any thoughts on this?

**Comment by rijkvanzanten** [comment] 2021-03-29 14:07
@joeinnes That's all correct. The only main thing to keep in mind here is that the app doesn't actually use the JS SDK for it's auth management, so this isn't relevant to the OPs issue 🙂 

@WoLfulus already updated the SDK in https://github.com/directus/directus/pull/4510 with a fixed auth flow included 👍🏻

**Comment by joeinnes** [comment] 2021-03-29 14:36
Good exercise for my fingers then :) Great to hear the auth flow in the SDK is already updated.

Seems as though a similar (although not exactly the same) thing is happening here:

https://github.com/directus/directus/blob/706dca1740cede473ae0ef6c23eaebed099336ba/app/src/auth.ts#L45

When the refresh fails, it's caught and the user is logged out.

**Comment by rijkvanzanten** [comment] 2021-03-29 16:13
> When the refresh fails, it's caught and the user is logged out.

Exactly! This was originally by design, as I was working under the assumption that a failed refresh indicated a change in the users status (eg session destroyed / user suspended / account destroyed etc). However, we should make an exception to that rule for a temporary "lapse" in internet, and then try the refresh once when the internet comes back online.

I think a proper solution for this might also resolve https://github.com/directus/directus/issues/3940 🤔 

Any thoughts @joeinnes?

**Comment by joeinnes** [comment] 2021-03-29 16:48
If the user is online, log them out as above. Otherwise, listen to the 'online' event, and try a refresh.

Something like the below?

````
if (navigator && navigator.onLine) {
  await logout({ navigate, reason: LogoutReason.SESSION_EXPIRED });
} else {
  window.addEventListener('online', function(e) { refresh(); }, { once: true });
}
````

**Comment by rijkvanzanten** [comment] 2021-03-29 16:52
Makes sense to me! Do you happen to know if that `onLine` is triggered for "paused" background tabs? 🤔

**Comment by joeinnes** [comment] 2021-03-29 19:35
To be honest, although I haven’t found anything better, I’m not convinced that there’s consistent, cross-browser support for detecting offline even in foreground tabs, let alone background.

Maybe it’s best to explicitly listen for a 401 or a 403, otherwise retry.

**Comment by rijkvanzanten** [comment] 2021-08-04 20:19
This should've been fixed in https://github.com/directus/directus/pull/7177

**Closed by rijkvanzanten** 2021-08-04 20:19 UTC
Labels: App, Improvement
