### ISSUE TITLE
mainElement in tabular and cards layout is null

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#8767] opened 2021-10-13 17:28 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

On page change, this code is supposed to scroll the page to the top.

https://github.com/directus/directus/blob/aff49835eeae46a50cf4429f6ba9382b1c81ed59/app/src/layouts/tabular/index.ts#L137-L140

It used to work, but since the rework of the layout architecture `mainElement` just stays null, so this is never called.

### To Reproduce

Use the tabular or cards layout and change navigate to another page.

### What version of Directus are you using?

rc.96

### What version of Node.js are you using?

16

### What database are you using?

PostgreSQL

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

local

**Comment by nickrum** [comment] 2021-10-14 15:57
This is caused by the layout wrapper component wrapping the `private-view`, where the `mainElement` is provided. Providing a value only exposes it to the children of a component, so the wrapper can't see the `mainElement`.
This can be fixed by moving the `inject('main-element')` call to the actual layout component.

**Closed** 2021-10-15 14:55 UTC
Labels: App, Bug
