### ISSUE TITLE
GraphQL aliases don't work on "flat" fields

### ISSUE THREAD

**Issue by cdanny358** [directus/directus#8332] opened 2021-09-26 19:25 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

In Directus 0.0.0-rc.94, GraphQL aliases always return null. This worked properly in rc.93 and below. For example, this query in GraphiQL returns `null` for `composer` and `body_text`. Remove the aliases and it works fine, returning the proper values for `title` and `description`.

```
query {
    featured_concert {
        url
        composer: title
        body_text: description
    }
}
```

### To Reproduce

Unfortunately, I have no easy way of providing reproduction steps without moving my MySQL database and Directus setup to a public repository somewhere.

### What version of Directus are you using?

9.0.0-rc.94

### What version of Node.js are you using?

16.9.1

### What database are you using?

MySQL 5.7.32

### What browser are you using?

Any (doesn't require a browser)

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2021-09-27 06:02
Hi, unfortunately I'm unable to reproduce this bug. Would you mind reviewing what I did and see is there any noticeable difference? Or perhaps can you try doing what I did and see whether the bug is still present for you?

1. Create new local Directus project with version 9.0.0-rc.94.
1. Create a collection called `Concerts` with 2 additional fields, namely `title` (string) and `description` (string).
2. Open read permission for collection `Concerts`.
  ![chrome_wmDSLw5p71](https://user-images.githubusercontent.com/42867097/134852733-babccd73-c53e-489d-98c9-100b93b68f36.png)
  
3. Use typical graphql query to get items from `Concerts`:
  ![Insomnia_KGwK9pJLBu](https://user-images.githubusercontent.com/42867097/134852695-86351851-303f-4943-abf0-676adec7e67a.png)
  
4. Use aliases (`composer` and `body_text`) to get items from `Concerts`:
  ![Insomnia_nW2cxCniVl](https://user-images.githubusercontent.com/42867097/134852718-b8416513-8728-4849-8158-5a164b72df05.png)

**Comment by rijkvanzanten** [comment] 2021-09-27 19:13
Seems to work as expected on my end as well 🤔 

<img width="1052" alt="CleanShot 2021-09-27 at 15 12 02@2x" src="https://user-images.githubusercontent.com/9141017/134970369-ddf11087-e9b2-481c-84df-a36e7a0ca447.png">

**Comment by rijkvanzanten** [comment] 2021-09-27 21:45
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-09-27 21:45 UTC
Labels: Needs More Info

**Comment by cdanny358** [comment] 2021-09-30 17:15
This seems to still be an issue, but only when you create a GraphQL alias to a many-to-one field -- it works fine on standard, simple fields. I can send you a SQL dump of my file if that helps.

**Comment by rijkvanzanten** [comment] 2021-09-30 17:17
@cdanny358 Somebody else reported it 2 days ago, so we're tracking the relational alias problem here: https://github.com/directus/directus/issues/8402 🙂
