### ISSUE TITLE
Update hook fired instead of delete

### ISSUE THREAD

**Issue by Radiergummi** [directus/directus#1585] opened 2017-06-16 15:32 UTC
## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 7.0.8
  - MySQL version: 14.14 5.5.54
  - Web server: nginx 1.10.3
  - OS name and version: Debian 8

## Expected Behavior
- `Table.update:after` fires when records in tables have their field values changed
- `Table.delete:after` fires when records from tables are being deleted

## Actual Behavior
- `Table.update:after` fires for both deletions and updates
- `Table.delete:after` is never fired at all

## Steps to Reproduce
 1. Add hooks for `Table.update:after` and `Table.delete:after` with the content:

````php
# Shell commands because I modified my existing code to test, ignore this
  'table.update' => function ($table, $record) {
    $recordData = json_encode($record);
    shell_exec("bash -c 'echo \"$(date): Table $tableName updated with $recordData\n\" >> test.log'");
  },
  'table.delete' => function ($tableName) {
    shell_exec("bash -c 'echo \"$(date): Record deleted from table $tableName\n\" >> test.log'");
  }
````

 2. Tail -f log file
 3. Modify tables in Directus

**Comment by benhaynes** [comment] 2017-06-16 15:57
My assumption here is that you're using the status column and this is a "soft-delete"... is that correct? In that case I understand that this would _technically_ be an update... though the system should treat it as a delete.

**Comment by WellingGuzman** [comment] 2017-06-16 16:31
Yeah, that must be a `soft-delete`, deleting a item with status column will trigger the `update`.

As ben said it should be treated as delete at least on events, but maybe with a flag that was a soft delete?

Let's discuss a proper solution for this one.

**Comment by Radiergummi** [comment] 2017-06-16 17:47
Yep, `soft-delete`. (*On a sidenote, a big thumbs up to you guys for being so quick to answer*)

**Comment by benhaynes** [comment] 2017-06-17 13:13
Thanks! I like the idea of `purge` instead of making an assumption about which event was intended for soft-delete. What do you think @WellingGuzman?

**Comment by Radiergummi** [comment] 2017-06-18 13:09
On the other hand, I just thought it might make more sense to introduce an event called `Table.trash` for soft-deletes, preserving delete for real deletions. Would be more CRUD-like, too.

**Comment by WellingGuzman** [comment] 2017-06-18 15:50
I do like the event name `trash`, to me makes more sense than `purge`, what do you think @benhaynes?

**Comment by benhaynes** [comment] 2017-06-18 16:13
Hmm, Purge is more of an event/action... Trash is more of a noun. I say Purge

**Comment by WellingGuzman** [comment] 2017-06-18 16:18
I was thinking the grammar will bite me, any word that resembles more trashing event? otherwise done deal! 🔨

**Comment by Radiergummi** [comment] 2017-06-18 16:44
Well, according to [Urban Dictionary](http://www.urbandictionary.com/define.php?term=Thrashing), trash can be used as a verb 🙃 (Maybe the context there might be slightly different)

**Comment by wittwerch** [comment] 2017-06-19 05:01
For me personally having a flag on the delete event would be the obvious option.

Soft Delete = delete
Hard Delete = purge

That would mean on a table without soft delete the events fired would be: create/read/update/purge. That's weird.. :)
So I think we either find a good verb for soft-deletion, so that we can use the _delete_ verb for hard deletes, or we should stick to a flag.

**Comment by benhaynes** [comment] 2017-07-25 03:14
So, are these the options?

1. Both are considered `delete` but they come with a flag for soft/hard
2. Soft Delete = `remove` & Hard Delete = `delete`

**Comment by WellingGuzman** [comment] 2017-07-25 03:40
Having `delete` and `remove` could be confusing, at least to me. Is there a word that represent the "soft delete"? probably will trigger both with a flag?

```
'table.items.delete' => function (\Directus\Hook\Payload $payload) {
    if ($payload->attribute('hard_delete')) {
        // hard delete
    } else {
        // some delete
    }
},
```

An option, in case we don't find a good two word, or if everyone agree those two words can be used without any confusion, I'm all on board.

**Comment by benhaynes** [comment] 2017-07-25 03:49
I like the flag approach – that seems cleaner. I think we should have a `soft` flag... no need to call it `soft_delete` because we're already in the delete event.

**Comment by WellingGuzman** [comment] 2017-07-25 03:51
So it will end up like these:

```php
'table.items.delete' => function (\Directus\Hook\Payload $payload) {
    if ($payload->attribute('soft')) {
        // soft delete
    } else {
        // hard delete
    }
},
```

**Comment by benhaynes** [comment] 2017-07-25 03:52
Perfect. Let's do this!

**Comment by WellingGuzman** [comment] 2017-08-02 23:38
I was thinking about this now, what happens with older developers that has this set for `hard-delete` okay I will recommend creating a new name for it `remove` and we pass it whether is soft delete or not. so we don't break old/current codes.

**Comment by WellingGuzman** [comment] 2017-08-27 05:50
Closed by https://github.com/directus/directus/commit/1f190e59160f29b9fd64c1667db4ed75619a8173

**Closed by WellingGuzman** 2017-08-27 05:50 UTC
Labels: 4. Minor, Help Wanted, Question
