### ISSUE TITLE
Accepting invitation with password validation error shows unexpected error

### ISSUE THREAD

**Issue by robinsonjohn** [directus/directus#22051] opened 2024-04-02 15:23 UTC
### Describe the Bug

During the process of creating a password when accepting an invitation, if the password fails the password validation, the user is shown "Unexpected Error" instead of the error which was received (validation error).

This does not allow the user to understand the error and modify their password.

### To Reproduce

- Create auth password policy: `Settings > Auth Password Policy`
- Invite new user: `Users > Invite user`
- Visit accept link and attempt to create password which fails the password policy (i.e. length too short)

Browser console shows that the validation error was returned, but the user is simply shown "Unexpected Error".

![Screenshot 2024-04-02 at 11 20 01 AM](https://github.com/directus/directus/assets/24327848/e5f28cd9-c3f6-4cae-8caf-942e72871742)
![Screenshot 2024-04-02 at 11 13 07 AM](https://github.com/directus/directus/assets/24327848/77f33a72-badb-445c-962d-f59895e9c3c6)

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-04-02 15:34
Duplicate of #21971

**Closed by br41nslug** 2024-04-02 15:34 UTC
