### ISSUE TITLE
[Directus API] Can not sort by count (aggregate)

### ISSUE THREAD

**Issue by ken1901** [directus/directus#18725] opened 2023-05-25 11:40 UTC
### Describe the Bug

Hi, I am developing a Directus extention. I tried the aggregate[count] with `order by` the count but could not manage to make it work:
With this query:
```
let data = await commentService.readByQuery({ 
      group: ['object_id'],
      aggregate: { 'count': ['object_id'] },
      alias: { object_id: 'count' },
      sort: ['count->object_id']  
 }
```

It results:
```
"code": "ER_BAD_FIELD_ERROR",
      "errno": 1054,
      "sqlMessage": "Unknown column 'svxk_jcomments.count->object_id' in 'order clause'",
      "sqlState": "42S22",
      "index": 0,
      "sql": "select `svxk_jcomments`.`object_id`, count(`svxk_jcomments`.`object_id`) as `count->object_id` from `svxk_jcomments` group by `svxk_jcomments`.`object_id` order by `svxk_jcomments`.`count->object_id` asc limit 100"
```

(or calling in the API endpoint returned the same result:
![image](https://github.com/directus/directus/assets/3941497/adde1b0f-b74c-403b-a0ef-034e0693a8a7)
)

(I tried to change to `sort: ['count']` . `sort: ['count[object_id]']` but neither of them work. )

### **Other thoughts:**

When I tried to run query directly in MySQL: 
```
select `svxk_jcomments`.`object_id`, count(`svxk_jcomments`.`object_id`) as `count->object_id` from `svxk_jcomments` group by `svxk_jcomments`.`object_id` order by `count->object_id` asc limit 100"
```
 (do not have the `svxk_jcomments`. in the `order by` clause) , it works! 

So I think if we can get rid of "`table_name`." part in the `ORDER BY` , it will work. How can I do it?

Any helps are much appreciated!!!

Regards,

Ken
```

MariaDB version: 10.7.8-MariaDB-1:10.7.8


### To Reproduce

1. Setup Directus with Mariadb (latest version)
2. Setup a collection with columns: id, name, object_id
3. Make some records with different names, object_ids (some of them have same object_ids)
4. Try to get the 2 object_ids which have most of records.

### Directus Version

v10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-05-30 14:44
While `sort` does support relational fields using the dot notation `sort: ['relation.field']` I don't think sorting on aggregated values is supported at this time.

Closing this as "technically working as intended" but definitely create a feature request to support this in the platform 😄

**Closed by br41nslug** 2023-05-30 14:44 UTC
