### ISSUE TITLE
Validation errors doesn't appears in drawer

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#17109] opened 2023-01-12 01:16 UTC
### Describe the Bug

Validation errors doesn't appears in drawer.
When editing item in content module all seems to work correctly.

### To Reproduce

1. Click on item in m2a, m2m, or m2o interfaces. The drawer will be opened.
2. Try to set an invalid value at least to one field.
3. Save button will do nothing. The validation errors won't be shown.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

v17.9.0

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment] 2023-01-12 16:12
Duplicate of https://github.com/directus/directus/issues/16091

**Closed by rijkvanzanten** 2023-01-12 16:12 UTC
