### ISSUE TITLE
Installation is on mac

### ISSUE THREAD

**Issue by chrisformula** [directus/directus#1352] opened 2017-02-20 07:56 UTC
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for slim/slim 2.3.2 -> satisfiable by slim/slim[2.3.2].
    - slim/slim 2.3.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
  Problem 2
    - slim/slim 2.3.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - slim/extras dev-develop requires slim/slim >=2.0.0 -> satisfiable by slim/slim[2.3.2].
    - Installation request for slim/extras dev-develop -> satisfiable by slim/extras[dev-develop].

How do I solve this?

**Comment by rijkvanzanten** [comment] 2017-02-20 09:51
It is possible to install mcrypt on the default PHP on MacOS, but I highly recommend checking out MAMP for local PHP development.

If you're already using MAMP and still getting this issue; make sure you use php version 5.x.x instead of 7.x.x and run Composer through MAMP's php instead of the default.

**Comment by WellingGuzman** [comment] 2017-02-20 16:52
I would recommend using MAMP as well.

In other hands as there may be different way to install the extension, you can google it how to install it on Mac, or probably try using `brew` (homebrew), as I don't want to confirm any successful step by step.

Please let us know how it goes. I will close it as this is not directly related to Directus, but we can keep the conversion open :)

**Closed by WellingGuzman** 2017-02-20 16:52 UTC

**Comment by chrisformula** [comment] 2017-02-21 07:47
Hi Welling

Ok Im a tad confused now, so I don't need to go through the composer rout to install the CMS?

**Comment by WellingGuzman** [comment] 2017-02-21 17:01
Hello @chrisformula, when are you getting 500 error? anything on your logs (`/api/logs` directory)

**Comment by chrisformula** [comment] 2017-02-22 06:40
I only seem to have README files in my log.

This is the exact error I get out of terminal when trying to install composer:

composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for slim/slim 2.3.2 -> satisfiable by slim/slim[2.3.2].
    - slim/slim 2.3.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
  Problem 2
    - slim/slim 2.3.2 requires ext-mcrypt * -> the requested PHP extension mcrypt is missing from your system.
    - slim/extras dev-develop requires slim/slim >=2.0.0 -> satisfiable by slim/slim[2.3.2].
    - Installation request for slim/extras dev-develop -> satisfiable by slim/extras[dev-develop].

**Comment by WellingGuzman** [comment] 2017-02-22 08:22
Oh, that means you still does not have the php extension `mcrypt` installed on your machine.

You have to install it and install the composer dependencies.

**Comment by chrisformula** [comment] 2017-02-22 10:01
Ok so that does not install it when running composer?

**Comment by chrisformula** [comment] 2017-02-22 10:05
And how do I install that?

**Comment by chrisformula** [comment] 2017-02-22 10:23
Woohoo I managed to install mcrypt and its working now!, Thanks for the help guys!!!

**Comment by rijkvanzanten** [comment] 2017-02-22 10:50
@WellingGuzman Maybe we could add local installation instructions for Mac somewhere? I've run into this problem myself as well (on two occasions..).

**Comment by chrisformula** [comment] 2017-02-22 10:52
Yeah just to add that step, that was my only hiccup but now its running smoothly

**Comment by WellingGuzman** [comment] 2017-02-22 18:04
@rijkvanzanten That's true, that's something that happened to me a lot. I will try to add some instruction on how to install it.

Would you mind to share how did you install it @chrisformula?

**Comment by chrisformula** [comment] 2017-02-24 14:00
Sure!
These steps are based on MAMP installed on OS X El Capitan

Below are the steps that I followed to get the issue sorted:

Firstly install:

brew install rbenv ruby-build

# Add rbenv to bash so that it loads every time you open a terminal
echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
source ~/.bash_profile

# Install Ruby
rbenv install 2.4.0
rbenv global 2.4.0
ruby -v

Add the required gem for rails:

gem install rails -v 5.0.1
rbenv rehash

Then run:
rails -v
result should be: # Rails 5.0.1

Then you have to make mcrypt available on you MAMP:

First check your PHP version:
php -v

#PHP 5.5.28 (cli) (built: Apr 10 2014 17:49:22)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies 

Secondly open up your nano .profile in terminal:
nano .bash_profile

Then simply point to your MAMP PHP instance:
export PATH="/Applications/MAMP/bin/php/php5.5.38/bin:$PATH"

Save it and that's it. Problem solved!

**Comment by JKdreaming** [comment] 2018-12-27 16:38
I've followed the install instructions on the documentation. I have yet to get this to work locally or on my shared server account at A2hosting. Is there a way to potentially add a local install set of instructions on MAMP for the V7 of directus? The current steps say to download it and run it and the install will roll basically and I haven't been able to get it moving to the install set. I then just tried to set it up manually. That didn't work so I figured it's a php extension issue and I'm stuck there locally as Mamps documentation and interface for enabling php extensions is mediocre at best. Could we get some help with some clear step by step instructions on local setup? I'd love to use this software as it is just awesome!

Thanks in advance,
Joshua Kincheloe

**Comment by shealavington** [comment] 2018-12-27 17:33
Have you looked at the requirements and ensured they're met? https://docs.directus.io/advanced/requirements.html

**Comment by JKdreaming** [comment] 2018-12-27 17:39
Yes. I had it running on a dev server earlier. The thing is I looked all
over the net and couldn’t find one simple video or article on how to get V7
running locally so I’m asking. The headless movement is really cool and I’m
looking for the one that anyone can use without needing to learn too many
new technologies. This was a great start for me with my background. I just
wish I wasn’t having so much trouble.

Untitled Document
[image: alt_text] <https://jkdreaming.com>

Thank you,
JKDreaming.com <http://joshk.me/>
joshua@jkdreaming.com <joshua@jkdreamingl.com>
513-309-1619 ​
*Disclamer:* This message and/or any attachments are confidential and/or
legally privileged information and are intended for use only by the
intended addressee. If you are not the intended addressee, you are not
authorized to disclose, download, reproduce, or distribute the contents of
this message and/or the contents posted to any and all referenced domains
and/or FTP sites, nor are you authorized to take action based on
information contained herein. If this e-mail is received in error, please
notify the sender immediately and delete the e-mail and any remnants of the
message from your system immediately.

​

On December 27, 2018 at 9:33:05 AM, Shea (notifications@github.com) wrote:

Have you looked at the requirements and ensured they're met?
https://docs.directus.io/advanced/requirements.html

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/directus/directus/issues/1352#issuecomment-450196881>,
or mute the thread

**Comment by shealavington** [comment] 2018-12-27 17:49
IMO, the install documentation is fairly straight forward, therefore any issue is possibly an edge case with your install.

Would you be able to share where you're up to, what do you see, are you getting any errors?

**Comment by JKdreaming** [comment] 2018-12-27 18:47
Quick question. I'm getting errors no doubt due to my .htaccess setup as
I'm missing path info in every file trying to load. This is what I have to
push the url to the public folder, but what am I missing?

RewriteEngine on
RewriteBase /

RewriteCond %{REQUEST_URI} !^/public/

# Rewrites all URLS [Replace "example" with the actual domain, without the
TLD (.com, .net, .biz, etc)]
RewriteCond %{HTTP_HOST} ^(www\.)?headless.\jkdev\.

# Rewrite all those to insert /folder
RewriteRule ^(.*)$ /public/$1 [L]


[image: alt_text] <https://jkdreaming.com>

Thank you,
JKDreaming.com <http://joshk.me/>
joshua@jkdreaming.com <joshua@jkdreamingl.com>
513-309-1619

*Disclamer:* This message and/or any attachments are confidential and/or
legally privileged information and are intended for use only by the
intended addressee. If you are not the intended addressee, you are not
authorized to disclose, download, reproduce, or distribute the contents of
this message and/or the contents posted to any and all referenced domains
and/or FTP sites, nor are you authorized to take action based on
information contained herein. If this e-mail is received in error, please
notify the sender immediately and delete the e-mail and any remnants of the
message from your system immediately.

**Comment by JKdreaming** [comment] 2018-12-27 18:48
Also thanks for taking the time to help me. Happy Holidays!

**Comment by mtedwards** [comment] 2019-07-08 23:00
> Also thanks for taking the time to help me. Happy Holidays!

Did anyone manage to sort this out? I am running into the same issue and can't quite work out which option here managed to fix it.

**Comment by JKdreaming** [comment] 2019-07-09 01:44
Thanks!
[image: alt_text] <https://jkdreaming.com>

Thank you,
JKDreaming.com <http://joshk.me/>
joshua@jkdreaming.com <joshua@jkdreamingl.com>
513-309-1619

*Disclamer:* This message and/or any attachments are confidential and/or
legally privileged information and are intended for use only by the
intended addressee. If you are not the intended addressee, you are not
authorized to disclose, download, reproduce, or distribute the contents of
this message and/or the contents posted to any and all referenced domains
and/or FTP sites, nor are you authorized to take action based on
information contained herein. If this e-mail is received in error, please
notify the sender immediately and delete the e-mail and any remnants of the
message from your system immediately.
