### ISSUE TITLE
Filter equals operator is not strict when used with integer

### ISSUE THREAD

**Issue by johnkmzhou** [directus/directus#20007] opened 2023-10-12 00:59 UTC
### Describe the Bug

When you have a integer value for your filter, it makes `_eq` act more like `_starts_with`.

### To Reproduce

Create a collection that contains a string column called `name`. Create two items with the name "2023 A" and "2023 B". When you use the endpoint, `/items/form?filter={"name":{"_eq":2023}}`, it will return both items.

### Directus Version

10.6.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-10-12 07:27
I am unable to reproduce this, using the `_eq: 2023` returns me no results for the proposed data model.
![image](https://github.com/directus/directus/assets/9389634/004febfc-25bc-4cbc-ad4f-eefe2e196617)

Is it a specific database for which this is happening?

Closing this issue for now until more info becomes available.

**Closed by br41nslug** 2023-10-12 07:27 UTC

**Comment by johnkmzhou** [comment] 2023-10-13 03:07
> I am unable to reproduce this, using the `_eq: 2023` (both as number and as string) returns me no results for the proposed data model. ![image](https://user-images.githubusercontent.com/9389634/274516173-004febfc-25bc-4cbc-ad4f-eefe2e196617.png)
> 
> Is it a specific database for which this is happening?
> 
> Closing this issue for now until more info becomes available.

Your hunch is right. After some investigation, technically this is a MySQL issue. This is the sql statement that Directus is executing `select test_eq.id, test_eq.name from test_eq where (test_eq.name = ?) order by test_eq.id asc limit ? [2023, 100]` which will return "2023 A" and "2023 B". When comparing a string with a number, MySQL will perform implicit casting that will cause it to behave like `like`.
