### ISSUE TITLE
No images are displayed in the fields

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1804] opened 2017-09-12 07:43 UTC
## Version Info
  - Directus version and branch: devel
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu16.04

## Actual Behavior
No images are displayed in the fields. Devel branch.
![default](https://user-images.githubusercontent.com/4669992/30313705-eca53ad4-97a6-11e7-84f8-52cfa96f22ee.png)

## Schema Dump, Logs, or Screenshots
[test.zip](https://github.com/directus/directus/files/1295104/test.zip)

**Comment by MartinMekhaiel** [comment] 2017-09-12 16:18
i have the same issue #1808

**Comment by WellingGuzman** [comment] 2017-09-12 22:38
Closed by https://github.com/directus/directus/commit/a3aa81e6b3489e514b65ce9eb46a962367edad97

**Closed by WellingGuzman** 2017-09-12 22:38 UTC
Labels: 3. Major, API

**Comment by MartinMekhaiel** [comment] 2017-09-14 03:04
still not working for me?

**Comment by WellingGuzman** [comment] 2017-09-14 03:10
@MartinMekhaiel which commit are you on?

if you go to `/api/1.1/files` what the output looks like?

**Comment by MartinMekhaiel** [comment] 2017-09-14 12:30
im on 4dd466d69374627ee1782892c65010f385f4038d

thats basically the result when i go to api/1.1/files

{
    "meta": {
        "table": "directus_files",
        "type": "collection",
        "total": 12,
        "Published": 12,
        "Deleted": 0,
        "Draft": 0,
        "total_entries": 12
    },
    "data": [
        {
            "id": 1,
            "status": 1,
            "name": "00000000001.jpg",
            "title": "Mountain Range",
            "location": "Earth",
            "caption": "A gorgeous view of this wooded mountain range",
            "type": "image/jpeg",
            "charset": "binary",
            "tags": "trees,rocks,nature,mountains,forest",
            "width": 1800,
            "height": 1200,
            "size": 602058,
            "embed_id": null,
            "user": 1,
            "date_uploaded": "2017-09-11T19:21:09-04:00",
            "storage_adapter": "local",
            "url": "/directus/storage/uploads/00000000001.jpg",
            "thumbnail_url": "/directus/storage/uploads/thumbs/1.jpg",
            "old_thumbnail_url": "/directus/storage/uploads/thumbs/00000000001-jpg-160-160-true.jpg",
            "html": null
        },
]}

**Comment by WellingGuzman** [comment] 2017-09-14 16:50
The output seems correct, would you care to share a schema, if possible, that we can use to reproduce this issue?

**Comment by MartinMekhaiel** [comment] 2017-09-14 18:59
sure, can i send you a private message with the schema?

**Comment by WellingGuzman** [comment] 2017-09-14 18:59
Absolutely @MartinMekhaiel

**Comment by MartinMekhaiel** [comment] 2017-09-14 19:02
uhm, how can i send it on github ?

**Comment by WellingGuzman** [comment] 2017-09-14 19:03
I don't think that's possible. I was thinking on [Directus Slack](https://slack.getdirectus.com)
