### ISSUE TITLE
Invite user - timeout

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#5239] opened 2021-04-24 20:51 UTC
The invite users feature fail after 20 seconds looping. During this time main app thread is locked. At the end following error is received : 
`{
  "errors": [
    {
      "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

To reproduce: enter one email address and submit the form. 
Starting from rc.56 to rc.60 I have the same issue. 
Please note it is working well in rc-55

I'm using following envs and using mailtrap.io
`
EMAIL_FROM="from@example.com"
EMAIL_TRANSPORT="smtp"
EMAIL_SMTP_HOST="smtp.mailtrap.io"
EMAIL_SMTP_PORT="2525"
EMAIL_SMTP_USER="user"
EMAIL_SMTP_PASSWORD="pwd"
EMAIL_SMTP_SECURE="false"
`

Environment:
    Directus: ^9.0.0-rc.56
    DBMS: Sqlite

**Comment by rijkvanzanten** [comment] 2021-04-24 21:09
Duplicate of https://github.com/directus/directus/issues/5229

**Closed by rijkvanzanten** 2021-04-24 21:09 UTC
