### ISSUE TITLE
Add new user is broken.

### ISSUE THREAD

**Issue by nithinga** [directus/directus#1638] opened 2017-06-29 13:34 UTC
## Version Info
  - Directus version and branch: version/6.4 - 80b1acf048b930a63d5503eb415d98a2e61471fc
  - PHP version: 7.1
 - MySQL version: 5.7
 - Web server: Apache
 - OS name and version: Docker ( Ubuntu )

## Logs or Screenshots
![screenshot from 2017-06-29 18 37 31](https://user-images.githubusercontent.com/18306604/27690017-bf4aae4a-5cfd-11e7-842b-30c0c0f47bd7.png)

**Comment by benhaynes** [comment] 2017-06-29 13:35
Thanks @nithinga – we appreciate you reporting this!

@WellingGuzman (our lead developer) is away on vacation this week, but we'll catch-up on all of this in a few days when he's back.

**Comment by nithinga** [comment] 2017-06-29 13:49
@benhaynes It was due to a recent change, it was working before d11056dc1792dc9e7bbee89e011e2838ca925f52

**Comment by benhaynes** [comment] 2017-06-29 13:50
Ahh, thanks! We'll see if we can find the root cause – if you come across it first just send over a PR! :)

**Comment by nithinga** [comment] 2017-06-29 14:56
@benhaynes This commit is causing issue, https://github.com/directus/directus/commit/8d7c38203965856488d75b7c98bbfd8f03d2d324

**Comment by rijkvanzanten** [comment] 2017-06-30 15:10
Thanks for the heads up @nithinga! I'll fix it asap

**Comment by rijkvanzanten** [comment] 2017-06-30 15:36
Fixed by https://github.com/directus/directus/commit/98886594dbfce16342fda3434a9af0b2b1497764. Please re-open if this didn't solve it for you

**Closed by rijkvanzanten** 2017-06-30 15:36 UTC
Labels: 2. Critical, Beta
