### ISSUE TITLE
In 9.16.0 O2M ALL Create Item Not Working Anymore!

### ISSUE THREAD

**Issue by drnachio** [directus/directus#15167] opened 2022-08-19 12:14 UTC
### Describe the Bug

After the update:

- The interface is empty
- The console displays an error on accept

![image](https://user-images.githubusercontent.com/5763165/185615990-38b55c0b-b6f5-46f1-8520-d932a752a80a.png)

### To Reproduce

Add a new child record

### Errors Shown

runtime-core.esm-bundler.e3d5f5b7.js:4 TypeError: Cannot read properties of undefined (reading 'meta')
    at index.69857a47.entry.js:127:79947
    at Jo (runtime-core.esm-bundler.e3d5f5b7.js:4:19838)
    at Proxy.ewe (index.69857a47.entry.js:127:79861)
    at Zt (runtime-core.esm-bundler.e3d5f5b7.js:4:4358)
    at gn.T [as fn] (runtime-core.esm-bundler.e3d5f5b7.js:4:38243)
    at gn.run (runtime-core.esm-bundler.e3d5f5b7.js:1:4887)
    at c.update (runtime-core.esm-bundler.e3d5f5b7.js:4:38509)
    at te (runtime-core.esm-bundler.e3d5f5b7.js:4:38535)
    at we (runtime-core.esm-bundler.e3d5f5b7.js:4:37399)
    at K (runtime-core.esm-bundler.e3d5f5b7.js:4:37192)

### What version of Directus are you using?

9.16.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

CockroachDB

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-08-19 12:14
Duplicate of #15157.

**Closed by azrikahar** 2022-08-19 12:14 UTC
