### ISSUE TITLE
Insight: List Panel error when use filter with Datetime function

### ISSUE THREAD

**Issue by khunsatant** [directus/directus#16495] opened 2022-11-18 04:28 UTC
### Describe the Bug

When use Filter with Datetime function the List Panel (Insight module), error will shown "GraphQL schema validation error.".
I tested in version 9.20.4 and 9.21.0, same error.  also not work in Metric Panel.

### To Reproduce

1. Create List Panel in Insight module.
2. Choose collection that have datetime fields and set display template.
3. Add filter with any datetime function e.g. Year (Date Created)
4. Save then error will appear

### Errors Shown

`{
  "errors": [
    {
      "message": "GraphQL schema validation error.",
      "extensions": {
        "code": "INVALID_PAYLOAD",
        "graphqlErrors": [
          {
            "message": "Syntax Error: Expected \":\", found \"(\".",
            "locations": [
              {
                "line": 1,
                "column": 79
              }
            ]
          }
        ]
      }
    }
  ]
}`

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

16.17.0

### What database are you using?

Mysql 8.0.29

### What browser are you using?

Brave

### How are you deploying Directus?

running locally

**Comment by licitdev** [comment] 2022-11-18 04:32
Duplicate of #15602

**Closed by licitdev** 2022-11-18 04:32 UTC
Labels: Duplicate
