### ISSUE TITLE
Objects Inconsistency between versions

### ISSUE THREAD

**Issue by ricricucit** [directus/directus#21538] opened 2024-02-23 17:21 UTC
### Describe the Bug

NOTE: `Builder` object returned in

### `main` Version of Page ID1
http://localhost:8055/items/Pages/1?fields=*,Builder.*&version=main
```
{
	"data": {
		"id": 1,
		"status": "published",
		"sort": 1,
		"user_created": "4fb227fd-3c1a-4624-acff-3e0c3164ac92",
		"date_created": "2023-02-28T18:12:01.408Z",
		"user_updated": "1287606b-a584-4a0f-87a3-a1e33d4d9a2f",
		"date_updated": "2024-02-23T16:38:11.308Z",
		"parent_id": null,
		"title": "Homepage",
		"preview_lang": "en-US",
		"SEO": null,
		"Builder": [
			{
				"id": 19,
				"Pages_id": 1,
				"item": "13",
				"collection": "Components",
				"sort": 1
			},
			{
				"id": 8,
				"Pages_id": 1,
				"item": "14",
				"collection": "Components",
				"sort": 2
			},
			{
				"id": 13,
				"Pages_id": 1,
				"item": "12",
				"collection": "Components",
				"sort": 3
			}
		]
	}
}
```

### `flippy` Alternative Version of Page ID1
http://localhost:8055/items/Pages/1?fields=*,Builder.*&version=flippy
```
{
	"data": {
		"id": 1,
		"status": "published",
		"sort": 1,
		"user_created": "4fb227fd-3c1a-4624-acff-3e0c3164ac92",
		"date_created": "2023-02-28T18:12:01.408Z",
		"user_updated": "1287606b-a584-4a0f-87a3-a1e33d4d9a2f",
		"date_updated": "2024-02-23T16:38:11.308Z",
		"parent_id": null,
		"title": "Homepage",
		"preview_lang": "it-IT",
		"SEO": null,
		"Builder": {
			"create": [],
			"update": [
				{
					"sort": 1,
					"id": 8,
					"collection": "Components",
					"item": {
						"id": 14
					}
				},
				{
					"sort": 2,
					"id": 19,
					"collection": "Components",
					"item": {
						"id": 13
					}
				},
				{
					"sort": 3,
					"id": 13,
					"collection": "Components",
					"item": {
						"id": 12
					}
				}
			],
			"delete": []
		}
	}
}
```

you can see that there are 2 different objects generated (unexpectedly), and the "second version `Builder` obj" includes extra wrapping attributes like `create`, `update` and `delete`...is this expected?

### To Reproduce

1. create an entry with an M2A component with 1 or more elements attached to it on (Directus v10.9.2) today: LATEST.
2. create 2 or more versions of this entry
3. got to http://localhost:8055/items/YOUR-NEW-ENTRY/1?fields=*&version=[A-VERSION]
4. got to http://localhost:8055/items/YOUR-NEW-ENTRY/1?fields=*&version=[ANOTHER-VERSION]
5. see that the object attributes between point nr.3 and 4 of this list, will be inconsistent

### Directus Version

10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-02-23 17:34
Thanks for opening this issue! However this is a duplicate of an existing issue #20890, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #20890 for future updates.

**Closed by paescuj** 2024-02-23 17:34 UTC
