### ISSUE TITLE
Issues regarding relationship management between two tables.

### ISSUE THREAD

**Issue by abdbodara** [directus/directus#6183] opened 2021-06-10 12:22 UTC
---
Hello Directus,
I want to inform you that I am facing issues when I manage the relationship between 2 tables then it shows me an error. It error occurs when I set id as auto-increment.  But it works fine when I insert the id value manually then it works fine. But as per my requirements, I want id as auto-increment. Also when I have imported my database to the directus platform then we have to verify those tables. but when I do verification then It gives me an error.

So would you please give instruction on how I can manage the relationship between 2 tables with auto-increment Id?
Also would you please show me the steps for that?
I have attached the screenshot error I am facing. Would you please give reply me as soon as possible on an urgent note?

Screenshot:-
https://i.imgur.com/VtboGk8.png
https://i.imgur.com/QEL4pKT.png
https://i.imgur.com/6zEPDJe.png

### Project details
Directus Version: 9.0.0-rc.74
Environment: production
OS: Linux 5.10.0-1029-oem
Node: 12.18.4

**Comment by supermx1** [comment] 2021-06-10 12:55
I have a similar issue

**Comment by abdbodara** [comment] 2021-06-11 03:50
It is MySQL database.

**Comment by rijkvanzanten** [comment] 2021-06-11 12:57
@abdbodara Can you confirm the collation/character set used in the different tables?

**Comment by abdbodara** [comment] 2021-06-12 04:38
Can you confirm the collation/character set used in the different tables?
yes, I have a relationship table but Directus is not showing in the relationship  the table

Screenshot:-
https://i.imgur.com/gnWIDAN.png

**Comment by rijkvanzanten** [comment] 2021-06-14 15:16
@abdbodara Can you share a database dump where this is happening? I can't reproduce it on my end 👍🏻

**Comment by rijkvanzanten** [comment] 2021-06-14 15:16
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-06-14 15:16 UTC
Labels: Needs More Info

**Comment by abdbodara** [comment] 2021-06-15 06:11
I have provided dumped, you can check this file. 
[hometable.zip](https://github.com/directus/directus/files/6653239/hometable.zip)

**Comment by abdbodara** [comment] 2021-06-17 04:10
I need a quick solution as soon as this fixed issue.
I have provides the zip file at the dump database

please check this zip file:-
[hometable.zip](https://github.com/directus/directus/files/6667308/hometable.zip)

**Comment by abdbodara** [comment] 2021-06-17 11:49
I am working on the table of upload multiple images. then after data destroy then after the reference page  not found errors are displayed. sending all the error pictures and after email and password uncorrected login display messages. 

Screenshot:-
https://prnt.sc/15p9r0k

**Comment by rijkvanzanten** [comment] 2021-06-17 15:41
How can I reproduce this issue in a fresh installation? For example:

1) Create table `x`
2) Add field `y`
3) Add relationship `z` from `x` -> `directus_files`

etc
