### ISSUE TITLE
"Unexpected error" after upgrading to 9.0.0-rc.67

### ISSUE THREAD

**Issue by sagerio** [directus/directus#5696] opened 2021-05-15 09:54 UTC
After upgrading to the latest 9.0.0-rc.64, migrating the database with `directus database migrate:latest` and restarting directus, an unexpected error appears when trying to reach the Admin page:

```
INTERNAL_SERVER_ERROR] select `directus_relations`.`id`, `directus_relations`.`many_collection`, `directus_relations`.`many_field`, `directus_relations`.`one_collection`, `directus_relations`.`one_field`, `directus_relations`.`one_collection_field`, `directus_relations`.`one_allowed_collections`, `directus_relations`.`junction_field`, `directus_relations`.`sort_field`, `directus_relations`.`one_deselect_action`, `directus_relations`.`many_primary`, `directus_relations`.`one_primary` from `directus_relations` order by `directus_relations`.`id` asc - SQLITE_ERROR: no such column: directus_relations.many_primary
```

**Comment by hsingh56** [comment] 2021-05-15 10:45
same issue, had to downgrade migration

**Comment by neo7-studio-web** [comment] 2021-05-15 12:21
May be duplicate of https://github.com/directus/directus/issues/5691

**Comment by sagerio** [comment] 2021-05-15 13:00
> same issue, had to downgrade migration

How did you do this?

**Comment by planetmcd** [comment] 2021-05-15 13:40
I followed the directions online to try out and got this same error in both postgresql and sqlite.

**Comment by rijkvanzanten** [comment] 2021-05-15 13:58
Duplicate of #5691

**Comment by martinemmert** [comment] 2021-05-15 13:58
Let us please continue here: https://github.com/directus/directus/issues/5691 and don't split those issues up.

**Closed by rijkvanzanten** 2021-05-15 13:58 UTC

**Comment by hsingh56** [comment] 2021-05-15 14:00
> > same issue, had to downgrade migration
> 
> @hsingh56 How did you do this?

please read here: https://docs.directus.io/reference/command-line-interface/#bootstrap-a-project
