### ISSUE TITLE
Cannot install on Mac Os Monterey (M1 MBP)

### ISSUE THREAD

**Issue by jfoucher** [directus/directus#16088] opened 2022-10-20 19:53 UTC
### Describe the Bug

Cannot install Directus

### To Reproduce

Run `npm init directus-project directus` on an M1 Macbook on Macos Monterey 12.5.1

### Errors Shown

npm init directus-project directus
✖ Installing Directus
npm WARN config production Use `--omit=dev` instead.
npm WARN deprecated @types/cssnano@5.1.0: This is a stub types definition. cssnano provides its own type definitions, so you do not need this installed.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated keyv-memcache@1.3.3: This project has been renamed to @keyv/memcache which will be updated moving forward.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fastify-warning@0.2.0: This module renamed to process-warning
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Users/jonathan/Sites/directus/node_modules/argon2
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jonathan/Sites/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/Users/jonathan/Sites/directus/node_modules/argon2/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.10
npm ERR! node-pre-gyp info using node@16.16.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/jonathan/Sites/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.28.7/argon2-v0.28.7-napi-v3-darwin-arm64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.7/argon2-v0.28.7-napi-v3-darwin-arm64-unknown.tar.gz
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for argon2@0.28.7 and node@16.16.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp)
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.7/argon2-v0.28.7-napi-v3-darwin-arm64-unknown.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.16.0 | darwin | arm64
npm ERR! gyp info ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.16.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.10.6 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
npm ERR! gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jonathan/Sites/directus/node_modules/argon2/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jonathan/Library/Caches/node-gyp/16.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jonathan/Library/Caches/node-gyp/16.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jonathan/Library/Caches/node-gyp/16.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/jonathan/Sites/directus/node_modules/argon2',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/jonathan/Sites/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/Users/jonathan/Sites/directus/node_modules/argon2/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
npm ERR! gyp ERR! cwd /Users/jonathan/Sites/directus/node_modules/argon2
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok
npm ERR! node-pre-gyp ERR! build error
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/jonathan/Sites/directus/node_modules/argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/Users/jonathan/Sites/directus/node_modules/argon2/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jonathan/Sites/directus/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/jonathan/Sites/directus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Users/jonathan/Sites/directus/node_modules/argon2
npm ERR! node-pre-gyp ERR! node -v v16.16.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathan/.npm/_logs/2022-10-20T19_46_53_605Z-debug-0.log
npm ERR! code 1
npm ERR! path /Users/jonathan/Sites
npm ERR! command failed
npm ERR! command sh -c create-directus-project "directus"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jonathan/.npm/_logs/2022-10-20T19_46_51_955Z-debug-0.log

### What version of Directus are you using?

N/A

### What version of Node.js are you using?

v16.16.0

### What database are you using?

N/A

### What browser are you using?

N/A

### How are you deploying Directus?

N/A

**Comment by ConnorSimply** [comment] 2022-10-20 20:13
Do you have any information on your development environment? It is hard to reproduce or troubleshoot with just logs. Directus runs for me on MBP Monterey and Ventura and am interested to know how you have yours set up.

Im marking this as can't `repro/needs more info` until we can identify if there is an issue with the repo.

**Comment by jfoucher** [comment] 2022-10-20 20:28
What information do you need exactly ? Does Directus have any specific requirements ?

**Comment by rijkvanzanten** [comment] 2022-10-20 21:35
There's a known issue right now if you don't have Rosetta 2 installed that argon2 won't install. This is a tracked in https://github.com/directus/directus/issues/15900 which was fixed in https://github.com/directus/directus/pull/15928. I'm sure Connor and I didn't notice this before as we both have an M1 with Rosetta 2 already installed 👍🏻

**Closed by rijkvanzanten** 2022-10-20 21:35 UTC
Labels: Needs More Info

**Comment by jfoucher** [comment] 2022-10-21 09:39
I do have Rosetta 2 installed though...

**Comment by rijkvanzanten** [comment] 2022-10-21 15:07
@jfoucher Interesting! How did you install NodeJS? I'm using `tj/n`, and everything seems to work as expected 🤔

**Comment by jfoucher** [comment] 2022-10-21 21:11
I used `n` as far as I recall.

**Comment by rowild** [comment] 2023-02-28 07:13
Same problem here on M2, Rosetta installed.
What is `tj/n`?

**Comment by rowild** [comment] 2023-03-20 21:33
This error also appears on DigitalOcean on a Droplet with Ubuntu 22.04, where I uses ` npm init directus-project .`. I got this error message:

```sh
  % npm init directus-project .  
✖ Installing Directus
Error: npm WARN config production Use `--omit=dev` instead.
npm ERR! code 1
npm ERR! path /var/www/jvds.scores-catalog.org/html
npm ERR! command failed
npm ERR! command sh -c create-directus-project .

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rowild/.npm/_logs/2023-03-20T20_51_03_636Z-debug-0.log
```

The whole error log:

```
  % cat 2023-03-20T20_51_03_636Z-debug-0.log 
0 verbose cli /home/rowild/.nvm/versions/node/v18.15.0/bin/node /home/rowild/.nvm/versions/node/v18.15.0/bin/npm
1 info using npm@9.6.2
2 info using node@v18.15.0
3 timing npm:load:whichnode Completed in 2ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/rowild/.nvm/versions/node/v18.15.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/var/www/jvds.scores-catalog.org/html/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/rowild/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/rowild/.nvm/versions/node/v18.15.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 12ms
17 timing npm:load:configload Completed in 13ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm init directus-project .
21 verbose argv "init" "directus-project" "."
22 timing npm:load:setTitle Completed in 2ms
23 timing config:load:flatten Completed in 4ms
24 timing npm:load:display Completed in 5ms
25 verbose logfile logs-max:10 dir:/home/rowild/.npm/_logs/2023-03-20T20_51_03_636Z-
26 verbose logfile /home/rowild/.npm/_logs/2023-03-20T20_51_03_636Z-debug-0.log
27 timing npm:load:logFile Completed in 14ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 38ms
31 silly logfile start cleaning logs, removing 1 files
32 silly logfile done cleaning log files
33 timing arborist:ctor Completed in 1ms
34 http fetch GET 200 https://registry.npmjs.org/create-directus-project 965ms (cache revalidated)
35 timing arborist:ctor Completed in 0ms
36 timing arborist:ctor Completed in 0ms
37 timing command:init Completed in 265377ms
38 verbose stack Error: command failed
38 verbose stack     at ChildProcess.<anonymous> (/home/rowild/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
38 verbose stack     at ChildProcess.emit (node:events:513:28)
38 verbose stack     at maybeClose (node:internal/child_process:1091:16)
38 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
39 verbose cwd /var/www/jvds.scores-catalog.org/html
40 verbose Linux 5.19.0-35-generic
41 verbose node v18.15.0
42 verbose npm  v9.6.2
43 error code 1
44 error path /var/www/jvds.scores-catalog.org/html
45 error command failed
46 error command sh -c create-directus-project .
47 verbose exit 1
48 timing npm Completed in 265578ms
49 verbose code 1
50 error A complete log of this run can be found in:
50 error     /home/rowild/.npm/_logs/2023-03-20T20_51_03_636Z-debug-0.log
```

Running `sh -c create-directus-project .` seems to be the culprit:

```sh
% sh -c create-directus-project . 
.: 1: create-directus-project: not found
```

**Comment by rijkvanzanten** [comment] 2023-03-20 21:36
@rowild I can't really help with individual hosting problems especially if they're not using the recommended deployment strategies.. I'd highly recommend using Docker for this purpose so you don't run into environment specific issues like we're seeing here 👍🏻 See https://docs.directus.io/self-hosted/quickstart.html for a quickstart on that

**Comment by rowild** [comment] 2023-03-20 21:38
@rijkvanzanten I wasn't expecting help. I just posted, because above you ask somebody else, which environment he was using. Thought this might help.
I know about the recommended Docker-way. But that one does not seem to work, when 3 installations on 3 sub domains are needed. Therefore I try to go with the npm-way.

**Comment by rijkvanzanten** [comment] 2023-03-20 22:09
> I know about the recommended Docker-way. But that one does not seem to work, when 3 installations on 3 sub domains are needed. Therefore I try to go with the npm-way.

Docker shouldn't prevent you from running multiple subdomains. All the env vars are the same, so you can still run multiple instances as multiple containers with individual ports (as you would with NPM), and reverse proxy them individually the same way 👍🏻

**Comment by rowild** [comment] 2023-03-20 22:27
@rijkvanzanten Thanks for your reply! And sorry – I didn't want to kickoff a different discussion here. I will post a question about that on Discord sometime this week. 
However – if I may –: I would love to know why "sh -c create-directus-project ." is a "platform specific" problem? Wasn't that once the way to install Directus? `npx create-directus-project .`? Or is my memory playing tricks on me?

**Comment by rijkvanzanten** [comment] 2023-03-20 22:33
> I may –: I would love to know why "sh -c create-directus-project ." is a "platform specific" problem? Wasn't that once the way to install Directus? `npx create-directus-project .`? Or is my memory playing tricks on me?

I believe in this case it's because `npm init directus-project` is a shorthand for `npx create-directus-project`: what npm does is globally install the `create-directus-project` package, then link the `bin` of that package globally, and then try executing the linked command with `sh` (the `sh -c create-directus-project` bit). For some reason, in this particular environment, that global linking of `create-directus-project` must've failed for reasons unknown, which means that the `sh` execution of the bin fails. I did spot that you're using `nvm` to install node, which AFAIK symlinks the globally installed packages differently from "plain node", which in turn might cause issues like these. Long story short.. while we haven't confirmed this exact hypothesis for this exact environment, it has been a very similar problem in very similar situations before, which leads me to believe it's something env specific here too. This type of annoyance is the reason why we're now solely focussed on containerized deployments, as that makes it way more doable for me to help debug unexpected problems as any problem is theoretically caused by Directus itself or the image we provide, rather than weird incompatibilities in the infinite permutations of environments node could theoretically run on 🙂
