### ISSUE TITLE
"Update Multiple Items" endpoint not working

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#6577] opened 2021-06-30 11:40 UTC
### Describe the Bug

When trying to update multiple items using the corresponding endpoint, the API retrieves an error like this:

```json
{
    "errors": [
        {
            "message": "select `c_cta`.`id`, `c_cta`.`created_by`, `c_cta`.`created_on`, `c_cta`.`variant`, `c_cta`.`name`, `c_cta`.`category_page`, `c_cta`.`new_tab`, `c_cta`.`no_follow`, `c_cta`.`is_external_url`, `c_cta`.`material_page`, `c_cta`.`glossary_pages`, `c_cta`.`landing`, `c_cta`.`policies_page`, `c_cta`.`attachment`, `c_cta`.`show_policy_as_modal`, `c_cta`.`faq_page`, `c_cta`.`anchor_id`, `c_cta`.`job_trigger` from `c_cta` where `c_cta`.`id` = 1444, 1591 order by `c_cta`.`id` asc limit 100 - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' 1591 order by `c_cta`.`id` asc limit 100' at line 1",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

I think the error relies in the *WHERE* clause, that's using equals (=) instead of IN.

### To Reproduce

Create a collection, create some items for it and try to update them by using the multi-update endpoint:
```json
{
    "keys": [1444, 1591],
    "data": {
        "job_trigger": true
    }
}
```

### What version of Directus are you using?

RC.82

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Linux Mint

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-07-15 00:26
I can't reproduce this on a new installation. Could you share the schema of this particular collection?

**Comment by rijkvanzanten** [comment] 2021-07-26 23:37
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-07-26 23:37 UTC
Labels: Needs More Info
