### ISSUE TITLE
Cannot deselected all o2m/m2m related items

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#8738] opened 2021-10-12 16:53 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Cannot delete the linked translations using the "clear value" translations popover
![Capture](https://user-images.githubusercontent.com/1532438/136997214-a7638089-2135-4bd5-8703-8a67d8a81eb5.PNG)
.

It is triggering well a Patch that is emptying the translations field.
```
PATCH items/administratives_areas/6b2dea83-70fe-49fc-b5a5-9371a67ad8bb
{
    "translations": null
}
```
But it doesn't delete the translations and they are returned back.
Patch response
```
{
  "id": "6b2dea83-70fe-49fc-b5a5-9371a67ad8bb",
  "short_code": "fr",
  "translations": [
    28,
    29,
    30,
    31
  ],
}
```

### To Reproduce

Add a translations field using the default workflow to let it create the junction table.

Configure Cascade delete so that on Deselect translations it should trigger a delete of the translation.

![](https://user-images.githubusercontent.com/1532438/136989687-d7d27b88-c4cc-4ff6-be93-f17a4d22607e.PNG)

### What version of Directus are you using?

9.0.0-rc.96

### What version of Node.js are you using?

14

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by gkielwasser** [comment] 2021-11-17 17:17
@rijkvanzanten Do you have any inputs about this error ? In case it helps, I can still reproduce with Directus v9.0.1 despite the resolution of https://github.com/directus/directus/issues/8907

**Comment by azrikahar** [comment] 2021-11-22 09:29
@gkielwasser just to clarify, the linked issue was not resolved, but closed as duplicate of this issue instead, so it does make sense for it to still be present here.

**Closed** 2022-03-25 17:42 UTC
Labels: App, Bug

**Comment by gkielwasser** [comment] 2022-04-04 12:19
@rijkvanzanten Just tested on v9.8.0, it works well. Thanks !
