### ISSUE TITLE
Unable to Update Directus in Digital Ocean

### ISSUE THREAD

**Issue by mosabalrsaheed** [directus/directus#22675] opened 2024-06-05 16:25 UTC
### Describe the Bug

Description
I am encountering issues while trying to update Directus in Digital Ocean. Below are the details and error messages observed:

Environment
Node.js Version: 18.20.3
NPM Version: 10.7.0 (noticed update available to 10.8.1)
Platform: Linux (linux-x64)
Error Messages
 
```
node:6) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
/workspace/node_modules/@directus/api/node_modules/sharp/lib/sharp.js:114
  throw new Error(help.join('\n'));
        ^

Error: Could not load the "sharp" module using the linux-x64 runtime
ERR_DLOPEN_FAILED: libvips-cpp.so.42: cannot open shared object file: No such file or directory
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
    yarn add sharp --ignore-engines
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=linux --cpu=x64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/workspace/node_modules/@directus/api/node_modules/sharp/lib/sharp.js:114:9)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/workspace/node_modules/@directus/api/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
```

### To Reproduce

Steps to Reproduce
Attempt to update Directus in a Digital Ocean environment.

### Directus Version

10.12.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2024-06-05 16:35
Heya, since this is a question and not a bug report, I'll proceed to close this. Please head over to our [Community Discord Server](https://directus.chat/) to ask your question there. Thank you!

**Closed by paescuj** 2024-06-05 16:35 UTC

**Comment by br41nslug** [comment] 2024-06-05 16:56
FWIW the error is pretty clear about possible solutions to try and resolve the system dependency that failed to install/load (solution 3 would be my first attempt then 4). We also recommend using `docker` so you wont run into such system specific library issues.
