### ISSUE TITLE
column width in collection view can not be changed in Firefox

### ISSUE THREAD

**Issue by foss-** [directus/directus#2588] opened 2020-02-13 15:27 UTC
# Bug Report

Firefox 73.0 (chrome and safari work as expected)
Directus 8.5.4
8.5.5 changelog does not seem to include an item referring to this issue

## Steps to Reproduce

1. Go to 'Collections'
2. Try to grab the column divider to change column width

## Expected Behavior

Width should be adjusted and saved. This works as expected in Safari and Chrome.

## Actual Behavior

While mouse pointer changes on mouseover indicating width can be changed, when dragged, width is not changed.

## Other Context & Screenshots

whenever the mouse oves to the side I was dragging the divider with no result:
![column width firefox issue](https://user-images.githubusercontent.com/5708172/74449740-4a246880-4e7d-11ea-947b-d468e0acfa8a.gif)

## Technical Details

- Firefox 73.0
- macOS 10.15.3
- Directus: 8.5.4

**Comment by rijkvanzanten** [comment] 2020-02-13 15:28
Duplicate of https://github.com/directus/app/issues/2090

**Comment by rijkvanzanten** [comment] 2020-02-13 15:29
The good news is that I already finished a new table component, including working resizing on Firefox. I'm actively updating the app to use this new one now 🙂 

https://storybook.directus.io/?path=/story/components-table--resizable

**Closed by rijkvanzanten** 2020-02-13 15:28 UTC
Labels: duplicate
