### ISSUE TITLE
Untouched Translation Fields Cannot be Duplicated

### ISSUE THREAD

**Issue by joelamltc** [directus/directus#15605] opened 2022-09-16 05:09 UTC
### Describe the Bug

Textarea and Wysiwyg as translation fields cannot be duplicated if the field is untouched.

### To Reproduce

1. create a collection
2. create a translation relationship
3. add input, textarea, wysiwyg field to the translation
4. go back to the collection and make the translation fields checked in the Duplication settings
5. create an item and filled with values for all translatable field
6. open the newly created item, change textarea / wysiwyg value, and click "Save as Copy"
7. you can only see the modified field is duplicated to the new item

### Errors Shown

No error shown

### What version of Directus are you using?

v9.17.4

### What version of Node.js are you using?

v14.18.3

### What database are you using?

mysql  Ver 15.1 Distrib 10.5.5-MariaDB, for osx10.15 (x86_64) using readline 5.1

### What browser are you using?

Chrome Version 104.0.5112.101 (Official Build) (x86_64)

### How are you deploying Directus?

Running locally

**Comment by licitdev** [comment] 2022-09-16 21:17
Duplicate of #14744

**Closed by licitdev** 2022-09-16 21:17 UTC
Labels: Duplicate
