### ISSUE TITLE
Custom module problem with directus v9.0.0-rc.45 following the documentatioon

### ISSUE THREAD

**Issue by hermesalvesbr** [directus/directus#4447] opened 2021-03-09 14:46 UTC
![image](https://user-images.githubusercontent.com/379850/110487168-10e41980-80cc-11eb-840b-41dc98cdc445.png)

**1) The issue and what you expected to happen**
I´m following this tutorial: https://docs.directus.io/guides/modules/  and the terminal show me a problem with  `<private-view title="My Custom Module">Content goes here...</private-view>`.

It does not recognize the private-view or even a simple div inside custom.vue, In rc.44 it worked normally.

**2) Exact steps to reproduce this issue**
 Exact steps: https://docs.directus.io/guides/modules/ 

**3) Your environment:**
v9.0.0-rc.45
MySQL
npx
Chrome and Firefox

**COMMAND**

````
npx rollup -c

src/index.js → ./index.js...
[!] (plugin commonjs) SyntaxError: Unexpected token (2:1) in C:\softagon\modificado\extensions\modules\custom\src\custom.vue?vue&type=template&id=7b01c00a&lang.js
src\custom.vue?vue&type=template&id=7b01c00a&lang.js (2:1)
1:
2:   <private-view title="My Custom Module">Content goes here...</private-view>
     ^
SyntaxError: Unexpected token (2:1) in C:\softagon\modificado\extensions\modules\custom\src\custom.vue?vue&type=template&id=7b01c00a&lang.js
    at Object.pp$4.raise (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:15559:13)       
    at Object.pp.unexpected (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:13251:8)     
    at Object.pp$3.parseExprAtom (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:14958:10)
    at Object.pp$3.parseExprSubscripts (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:14761:19)
    at Object.pp$3.parseMaybeUnary (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:14738:17)
    at Object.parseMaybeUnary (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:19464:29)  
    at Object.pp$3.parseExprOps (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:14673:19)    at Object.pp$3.parseMaybeConditional (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:14656:19)
    at Object.pp$3.parseMaybeAssign (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:14624:19)
    at Object.pp$3.parseExpression (C:\softagon\modificado\extensions\modules\custom\node_modules\rollup\dist\shared\rollup.js:14590:19)

npm ERR! code 1
npm ERR! path C:\softagon\modificado\extensions\modules\custom
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c rollup -c

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hermes Alves.ANINHA\AppData\Local\npm-cache\_logs\2021-03-09T14_37_46_614Z-debug.log
````

**Comment by rijkvanzanten** [comment] 2021-03-09 14:57
I think this is a duplicate of https://github.com/directus/directus/issues/4401

**Closed by rijkvanzanten** 2021-03-09 14:57 UTC
