### ISSUE TITLE
No o2m field reaction to conditions. 

### ISSUE THREAD

**Issue by boo-code** [directus/directus#14453] opened 2022-07-15 12:37 UTC
### Describe the Bug

When condition is set on o2m field, Directus is ignoring it.

### To Reproduce

Set conditions, check the UI.

Field:
![image](https://user-images.githubusercontent.com/65190196/179223619-80f61221-29ae-423b-8350-7f9f465afea0.png)

Default interface values:

![image](https://user-images.githubusercontent.com/65190196/179223044-8e76a9d5-edf9-4a04-888a-47a5ee3a2fce.png)

![image](https://user-images.githubusercontent.com/65190196/179223091-0b14875d-30af-4a2b-be11-1e99c3716e56.png)

Condition:

![image](https://user-images.githubusercontent.com/65190196/179225125-d2aa8744-c9da-45c5-b907-f0ed4482a4e3.png)

Condition should enable the field editing and make "Create new" button visible, but it doesn't.

![image](https://user-images.githubusercontent.com/65190196/179223370-4f105ff3-1a66-44c7-9eeb-03357035dc90.png)

### Errors Shown

none

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

18.4.0

### What database are you using?

Postgress

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-07-15 13:48
Duplicate of https://github.com/directus/directus/issues/14285

**Closed by rijkvanzanten** 2022-07-15 13:48 UTC
