### ISSUE TITLE
Not able to create collection within a group if the parent table already exists

### ISSUE THREAD

**Issue by IanPirro** [directus/directus#13922] opened 2022-06-15 23:51 UTC
### Describe the Bug

When applying a snapshot, if there is a collection that needs to be created which has a group name but the parent table already exists it will not create it and fail when trying to create its fields.

I believe it was introduced here https://github.com/directus/directus/commit/e47502e11fc173f7cb9524fc6e853de548dd8389#diff-107cb4550c24bd18d2bcd0567a8b49abbac22d748009e143be98c5b9f6622a20 with the new way they are created recursively.

I was able to fix this locally with a fix like.
```ts
// api/src/utils/apply-snapshot.ts

// Finds all collections that need to be created
const filterCollectionsForCreation = ({ diff }: { collection: string; diff: Diff<Collection | undefined>[] }) => {
	const isNewCollection = diff[0].kind === 'N';
	const groupName = (diff[0] as DiffNew<Collection>).rhs.meta?.group;
	// Is new, has no group
	if (isNewCollection && groupName === null) {
		return true;
	}
	const parentExists =
		typeof groupName === 'string' && current.collections.find((c) => c.collection === groupName) !== undefined;
	// Is new, has group, but parent is not new
	if (isNewCollection && parentExists) {
		return true;
	}
	return false;
};

// create top level collections (no group) first, then continue with nested collections recursively
await createCollections(snapshotDiff.collections.filter(filterCollectionsForCreation));
```

Happy to submit a pr if you'd like.

### To Reproduce

1. Create two dbs with the same schema (db1, db2)
2. Connect directus ui to db1
3. Create a new new collection and nest it under an existing collection
4. Save snapshot
5. Apply snapshot to db2

### Errors Shown

```
<TIMESTAMP> 🚨 Failed to create field "<collection_name>.id"
Default
<TIMESTAMP> 🚨 Cannot read properties of undefined (reading 'fields')
Error
<TIMESTAMP>TypeError: Cannot read properties of undefined (reading 'fields') at FieldsService.createField
```

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Local / Docker

**Comment by rijkvanzanten** [comment] 2022-06-16 13:49
Duplicate of https://github.com/directus/directus/issues/13894

> Happy to submit a pr if you'd like.

A PR is more than welcome ❤️

**Closed by rijkvanzanten** 2022-06-16 13:49 UTC
