### ISSUE TITLE
Schema apply produces pointless updates

### ISSUE THREAD

**Issue by terion-name** [directus/directus#11241] opened 2022-01-24 18:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If you run `schema apply` multiple times you will see each time a bunch of updates in foreign keys that should not be there (because this schema was already applied). Like this:

```
 The following changes will be applied:
Fields:
  - Update about_blocks.image
    - Set foreign_key_column to id
    - Set foreign_key_table to directus_files
  - Update about_translations.about_id
    - Set foreign_key_column to id
    - Set foreign_key_table to about
...
```

### To Reproduce

Run `schema apply` multiple times

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v16.12.0

### What database are you using?

mysql

### What browser are you using?

brave

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-01-25 00:15
What version of MySQL are you using? Would you be able to share the offending snapshot? I'm not able to reproduce this locally on MySQL 8.0.27 (or Postgres 13.5) on Directus 9.5.

**Comment by tchai81** [comment] 2022-01-25 02:22
I'm also having this issue.  

I realised that this will happens only when I keep executing yaml file generated from other ppl. 
After applying yaml from others, and generating my own set, applying my own yaml will not have the messages. 

Directus version 9.4.2
Databse: MySQL
Node: v14.16.1

Sample Output:-
`? The following changes will be applied:
Fields:
  - Update admission_discount_details.user_created
    - Set data_type to char
  - Update admission_discount_details.user_updated
    - Set data_type to char
  - Update attendance_class_statuses.user_created
    - Set data_type to char
  - Update attendance_class_statuses.user_updated
    - Set data_type to char
  - Update attendance_classes.member
    - Set foreign_key_column to id
    - Set foreign_key_table to members
  - Update attendance_classes.sell_course_class
    - Set foreign_key_column to id
    - Set foreign_key_table to sell_course_classes
  - Update attendance_classes.user_created
    - Set data_type to char
  - Update attendance_classes.user_updated
    - Set data_type to char
  - Update business_blocks.user_created
    - Set data_type to char
  - Update business_blocks.user_updated
    - Set data_type to char
  - Update cancel_reasons.user_created
    - Set data_type to char
  - Update cancel_reasons.user_updated
    - Set data_type to char
  - Update consumption_taxes.user_created
    - Set data_type to char
  - Update consumption_taxes.user_updated
    - Set data_type to char
  - Update contract_amounts.user_created
    - Set data_type to char
  - Update contract_amounts.user_updated
    - Set data_type to char
  - Update contract_details.user_created
    - Set data_type to char
  - Update contract_details.user_updated
    - Set data_type to char
  - Update contract_history.user_created
    - Set data_type to char
  - Update contract_history.user_updated
    - Set data_type to char
  - Update contract_mediums.user_created
    - Set data_type to char
  - Update contract_mediums.user_updated
    - Set data_type to char
  - Update contract_statuses.user_created
    - Set data_type to char
  - Update contract_statuses.user_updated
    - Set data_type to char
  - Update contract_term_history.user_created
    - Set data_type to char
  - Update contract_term_history.user_updated
    - Set data_type to char
  - Update contracts.user_created
    - Set data_type to char
  - Update contracts.user_updated
    - Set data_type to char
  - Update course_categories.user_created
    - Set data_type to char
  - Update course_categories.user_updated
    - Set data_type to char
  - Update course_levels.user_created
    - Set data_type to char
  - Update course_levels.user_updated
    - Set data_type to char
  - Update course_menus.user_created
    - Set data_type to char
  - Update course_menus.user_updated
    - Set data_type to char
  - Update courses.user_created
    - Set data_type to char
  - Update courses.user_updated
    - Set data_type to char
  - Update discount_packages.user_created
    - Set data_type to char
  - Update discount_packages.user_updated
    - Set data_type to char
  - Update discount_support_items.user_created
    - Set data_type to char
  - Update discount_support_items.user_updated
    - Set data_type to char
  - Update discount_types.user_created
    - Set data_type to char
  - Update discount_types.user_updated
    - Set data_type to char
  - Update discounts.user_created
    - Set data_type to char
  - Update discounts.user_updated
    - Set data_type to char
  - Update dissolution_memos.user_created
    - Set data_type to char
  - Update dissolution_memos.user_updated
    - Set data_type to char
  - Update dissolution_penalties.user_created
    - Set data_type to char
  - Update dissolution_penalties.user_updated
    - Set data_type to char
  - Update dissolution_reasons.user_created
    - Set data_type to char
  - Update dissolution_reasons.user_updated
    - Set data_type to char
  - Update dissolution_states.user_created
    - Set data_type to char
  - Update dissolution_states.user_updated
    - Set data_type to char
  - Update dissolutions.user_created
    - Set data_type to char
  - Update dissolutions.user_updated
    - Set data_type to char
  - Update equipments.user_created
    - Set data_type to char
  - Update equipments.user_updated
    - Set data_type to char
  - Update ingredients.user_created
    - Set data_type to char
  - Update ingredients.user_updated
    - Set data_type to char
  - Update instructions.user_created
    - Set data_type to char
  - Update instructions.user_updated
    - Set data_type to char
  - Update license_exams.user_created
    - Set data_type to char
  - Update license_exams.user_updated
    - Set data_type to char
  - Update licenses.user_created
    - Set data_type to char
  - Update licenses.user_updated
    - Set data_type to char
  - Update max_reserve_categories.user_created
    - Set data_type to char
  - Update max_reserve_categories.user_updated
    - Set data_type to char
  - Update measurement_units.user_created
    - Set data_type to char
  - Update measurement_units.user_updated
    - Set data_type to char
  - Update medium_categories.user_created
    - Set data_type to char
  - Update medium_categories.user_updated
    - Set data_type to char
  - Update mediums.user_created
    - Set data_type to char
  - Update mediums.user_updated
    - Set data_type to char
  - Update member_access_histories.user_created
    - Set data_type to char
  - Update member_access_histories.user_updated
    - Set data_type to char
  - Update member_no_history.user_created
    - Set data_type to char
  - Update member_no_history.user_updated
    - Set data_type to char
  - Update member_passport_history.user_created
    - Set data_type to char
  - Update member_passport_history.user_updated
    - Set data_type to char
  - Update members.user_created
    - Set data_type to char
  - Update members.user_updated
    - Set data_type to char
  - Update menu_equipments.user_created
    - Set data_type to char
  - Update menu_equipments.user_updated
    - Set data_type to char
  - Update menu_recipes.user_created
    - Set data_type to char
  - Update menu_recipes.user_updated
    - Set data_type to char
  - Update nutritions.user_created
    - Set data_type to char
  - Update nutritions.user_updated
    - Set data_type to char
  - Update online_lessons.user_created
    - Set data_type to char
  - Update online_lessons.user_updated
    - Set data_type to char
  - Update passport_issue_types.user_created
    - Set data_type to char
  - Update passport_issue_types.user_updated
    - Set data_type to char
  - Update recipe_ingredients.user_created
    - Set data_type to char
  - Update recipe_ingredients.user_updated
    - Set data_type to char
  - Update recipe_instructions.user_created
    - Set data_type to char
  - Update recipe_instructions.user_updated
    - Set data_type to char
  - Update recipes.user_created
    - Set data_type to char
  - Update recipes.user_updated
    - Set data_type to char
  - Update sales.user_created
    - Set data_type to char
  - Update sales.user_updated
    - Set data_type to char
  - Update sell_course_classes.user_created
    - Set data_type to char
  - Update sell_course_classes.user_updated
    - Set data_type to char
  - Update sell_course_discounts.user_created
    - Set data_type to char
  - Update sell_course_discounts.user_updated
    - Set data_type to char
  - Update sell_course_reserve_rules.user_created
    - Set data_type to char
  - Update sell_course_reserve_rules.user_updated
    - Set data_type to char
  - Update sell_course_support_items.user_created
    - Set data_type to char
  - Update sell_course_support_items.user_updated
    - Set data_type to char
  - Update special_discount_types.user_created
    - Set data_type to char
  - Update special_discount_types.user_updated
    - Set data_type to char
  - Update staff_positions.user_created
    - Set data_type to char
  - Update staff_positions.user_updated
    - Set data_type to char
  - Update staff_studio_history.user_created
    - Set data_type to char
  - Update staff_studio_history.user_updated
    - Set data_type to char
  - Update staff_types.user_created
    - Set data_type to char
  - Update staff_types.user_updated
    - Set data_type to char
Relations:
  - Update courses.user_created
    - Set on_update to RESTRICT-> directus_users
  - Update courses.user_updated
    - Set on_update to RESTRICT-> directus_users
  - Update ingredients.user_created
    - Set on_update to RESTRICT-> directus_users
  - Update ingredients.user_updated
    - Set on_update to RESTRICT-> directus_users
  - Update instructions.user_created
    - Set on_update to RESTRICT-> directus_users
  - Update instructions.user_updated
    - Set on_update to RESTRICT-> directus_users`

[schema.inc.yml.zip](https://github.com/directus/directus/files/7930109/schema.inc.yml.zip)

**Comment by rijkvanzanten** [comment] 2022-04-07 21:01
@tchai81 I wasn't able to reproduce this locally unfortunately :C 

What do you mean exactly by:

> After applying yaml from others, and generating my own set, applying my own yaml will not have the messages.

? Do these others use the same version of Directus? What is the diff between yours and the other schema snapshots?

I'll close this for now, but happy to keep discussing 👍🏻

**Closed by rijkvanzanten** 2022-04-07 21:01 UTC
Labels: Can't Reproduce
