### ISSUE TITLE
When trying to edit a relational item, it appears as creating a new one, instead of editing it

### ISSUE THREAD

**Issue by u12206050** [directus/directus#13106] opened 2022-05-04 06:36 UTC
### Describe the Bug

On one of my M2O fields the template fields for interface and display don't show properly, even though the raw value is valid.

![template_issue](https://user-images.githubusercontent.com/6641242/166632013-abde6e42-6945-43e6-8457-fbc78ae51727.gif)

I also notice the same issue happens on the collection settings but only for the "Persons" collection.

![template_issue_settings](https://user-images.githubusercontent.com/6641242/166632836-fcddd4bf-44d4-4168-8aaa-80a21f7529cf.gif)

### To Reproduce

Not sure, although the schema is based on the same one I emailed you in regards to another issue.

### Errors Shown

None

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

edge

### How are you deploying Directus?

GCP

**Comment by u12206050** [comment] 2022-05-04 06:41
Possibly another side affect that might be the same issue: When trying to edit an item on the "Persons" collection via a relationship, it comes up as wanting to create a new one, instead of editing it. Only the fields, that were apart of the display template are loaded into the form:

![edit_m2o_relation issue](https://user-images.githubusercontent.com/6641242/166633377-c729c7cf-9d4a-4f9f-8dc3-d71bef4c6cd2.gif)

**Comment by u12206050** [comment] 2022-05-04 06:46
More info:

Can confirm all was working in 9.8.0

**Comment by azrikahar** [comment] 2022-05-04 11:25
> #13111 Could be related, I do seem to have problems with the template field on 9.8.0, although the relationship is able to update on correctly on 9.8.0 but not on 9.9.0-9.10.0

Yeah I believe the original reported issue here is the same as #13111, as I was able to reproduce based on the steps shared over there reliably. As for the relationship issue, I believe it should be related to the overall relational rework in `9.9.0` since you have verified that as the version where it stopped working as expected.

Would you mind updating this issue to focus on the relationship bug? Thanks again for the constant updates!

**Comment by br41nslug** [comment] 2022-05-09 11:44
I believe the relational issue here might be the same as  #12881 and could be fixed by the PR open for that ticket

**Comment by rijkvanzanten** [comment] 2022-05-09 15:19
> I believe the relational issue here might be the same as #12881 and could be fixed by the PR open for that ticket

I believe you're right!

Lets track this as part of #12881

Duplicate of #12881

**Closed by rijkvanzanten** 2022-05-09 15:19 UTC
Labels: App, Bug (Potential)
