### ISSUE TITLE
Can not delete m2o field

### ISSUE THREAD

**Issue by laszlokorte** [directus/directus#6080] opened 2021-06-04 13:56 UTC
Directus v9 rc73, sqlite

create collection `day`
create collection `timeslot`
create m2o field day_id for `timeslot`

set one of those:
- Nullable: no and On Delete: Nullfiy
- Nullable: yes and On Delete: Cascade
- Nullable: yes and On delete: prevent

now delete the field again. (even without creating a row)

expected: fields get deleted
actual: error showing the foreign key can not be created

It seems like the foreign key is tried to be re-created even if the field is already deleted.

Additional suggestion: The On Delete Triggers should only be able to be set to `nullify` and `set to default` if null values are allowed and a default value is configured respectively.

![grafik](https://user-images.githubusercontent.com/26493/120811729-969d2700-c54c-11eb-83ee-1bf8dd5fd0f3.png)

```
{
  "errors": [
    {
      "message": "CREATE TABLE \"_knex_temp_alter983\" (`uuid` char(36) NOT NULL, `start_time` time NULL, `end_time` time NULL, PRIMARY KEY (`uuid`), CONSTRAINT timeslot_day_foreign FOREIGN KEY (`day`) REFERENCES `day` (`uuid`) ON DELETE SET NULL) - SQLITE_ERROR: unknown column \"day\" in foreign key definition",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Comment by rijkvanzanten** [comment] 2021-06-04 16:40
> Additional suggestion: The On Delete Triggers should only be able to be set to nullify and set to default if null values are allowed and a default value is configured respectively.

Why? Cascade and restrict are still perfectly usable options even if you have a default value?

**Comment by laszlokorte** [comment] 2021-06-07 12:21
> 
> 
> > Additional suggestion: The On Delete Triggers should only be able to be set to nullify and set to default if null values are allowed and a default value is configured respectively.
> 
> Why? Cascade and restrict are still perfectly usable options even if you have a default value?

yes cascade and restrict are valid options,
but set-to-null makes no sense if the field is not nullable,
and set to default makes no sense if the field has no default value

**Comment by rijkvanzanten** [comment] 2021-06-07 13:20
Ohhhhhh now I get what you're saying, I read this wrong:

> The On Delete Triggers should only be able to be set to nullify and set to default if null values are allowed and a default value is configured respectively.

My brain just read that as "The On Delete Triggers should only be able to be set to nullify and set to default" and conveniently skipped over the important bit ^^

**Comment by rijkvanzanten** [comment] 2021-06-14 20:02
This is caused by a problem in Knex itself: https://github.com/knex/knex/issues/4524

**Comment by rijkvanzanten** [comment] 2021-08-06 21:45
Closing this as it's not a bug in Directus itself. Keep an eye on the referenced issue above for more information.

**Closed by rijkvanzanten** 2021-08-06 21:45 UTC
Labels: API, Bug, DB: SQLite

**Comment by joselcvarela** [comment] 2021-09-02 14:38
Deleting either foreign columns or referenced tables fires an error. This is caused by Knex.
But our lovely friend @nickrum made a PR https://github.com/knex/knex/pull/4648 fixing this.
We need to wait for a new knex release

**Comment by joselcvarela** [comment] 2021-09-04 06:05
For those interested, this will be fixed on rc93 https://github.com/directus/directus/pull/7819
