### ISSUE TITLE
Nil pointer dereference on outdated cached schema

### ISSUE THREAD

**Issue by andres-torres-epam** [directus/directus#16110] opened 2022-10-21 15:18 UTC
### Describe the Bug

Directus services fail to execute item CRUD operations when called within an action hook context. This problem is caused because the action hook gets executed before the service clears the cached schema, therefore, within the action hook context the SchemaOverview is outdated.

### To Reproduce

Create an action hook (collections.create) that creates a field, relation or other item (related to the new collection) when executed using one of the Directus services exposed by the extensions context.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by licitdev** [comment] 2022-10-21 17:37
Duplicate of #11421

**Closed by licitdev** 2022-10-21 17:37 UTC
Labels: Duplicate
