### ISSUE TITLE
SDK read Role Public

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [directus/directus#23703] opened 2024-09-20 15:05 UTC
### Describe the Improvement

Maybe i am missing something but i cant find in the docs how to get the public role in the sdk?

**Comment by br41nslug** [comment] 2024-09-20 15:11
This would need to be implemented on the API first for it to be possible in the SDK. Looks like you may have to query the access junction table directly at the moment to get that info 🤔

**Comment by NilsBaumgartner1994** [comment] 2024-09-20 15:14
I mean now with the polices I need a way to know which policy is for the public role xD

**Comment by br41nslug** [comment] 2024-09-20 15:22
Unless manually changed the public policy will be created using the `abf8a154-5b1c-4a46-ac9c-7300570f4f17` ID

**Comment by NilsBaumgartner1994** [comment] 2024-09-20 16:16
Okay thanks, this might help me atleast for now :-) But i think this would be something which could be added.

**Comment by NilsBaumgartner1994** [comment] 2024-09-21 13:21
Okay current solution is:

read all policies
```ts
const policies = await directus.request<DirectusPolicies[]>(readPolicies({
			fields: ['*', "permissions.*", "roles.*"]
		}));
```

then get all policies ids for current role:
```
static getAllPoliciesIdsForCurrentRole(currentRole: DirectusRoles | null, policiesDict: Record<string, DirectusPolicies | null | undefined> | null | undefined, rolesDict: Record<string, DirectusRoles | null | undefined> | null | undefined, alreadyVisitedRoles: string[] = []): string[]{
        const currentRoleId = currentRole?.id;
        const poliesForRole = []
        for(let policyId in policiesDict){
            const policy = policiesDict[policyId];
            let rolesRelationsForPolicy: DirectusAccess[] = policy?.roles || [];
            for(let roleRelation of rolesRelationsForPolicy){
                const roleRelationRole = roleRelation.role as string | null | undefined;
                if(roleRelationRole===currentRoleId){
                    poliesForRole.push(policyId);
                }
            }
        }

        if(!!currentRoleId){
            alreadyVisitedRoles.push(currentRoleId);
        }
        let parentRoleId: string | null | undefined = null;
        const currentRoleParent = currentRole?.parent;
        if(currentRoleParent){
            if(typeof currentRoleParent === "string") {
                parentRoleId = currentRoleParent;
            } else {
                parentRoleId = currentRoleParent.id;
            }
        }
        if(!!parentRoleId && !alreadyVisitedRoles.includes(parentRoleId)){
            const parentRole = rolesDict?.[parentRoleId];
            if(!!parentRole){
                const poliesForParentRole = PermissionHelper.getAllPoliciesIdsForCurrentRole(parentRole, policiesDict, rolesDict, alreadyVisitedRoles);
                for(let policyId of poliesForParentRole){
                    poliesForRole.push(policyId);
                }
            }
        }

        return poliesForRole;
    }
```

or directly save the policy in the list

and then get the list of all permissions.

**Comment by pomeh** [comment] 2024-10-04 08:54
Hello,

As far as I understand, this problem may be caused by this root issue in REST API https://github.com/directus/directus/issues/23781

**Comment by NilsBaumgartner1994** [comment] 2024-10-04 09:54
Well Kind off.Beste Grüße,Nils BaumgartnerAm 04.10.2024 um 10:54 schrieb Romain Guerin ***@***.***>:﻿
Hello,
As far as I understand, this problem may be caused by this root issue in REST API #23781

**Comment by br41nslug** [comment] 2024-10-08 14:47
Closing this issue in favor of https://github.com/directus/directus/issues/23781
Once the public role gets exposed in the API it will also be available in the SDK without code changes.

**Closed by br41nslug** 2024-10-08 14:47 UTC
