### ISSUE TITLE
The following fields have invalid values:  ID: Value can't be null

### ISSUE THREAD

**Issue by eqqi2021** [directus/directus#17399] opened 2023-02-03 19:15 UTC
### Describe the Bug

When I try to create a new category (CATEGORY table, not CATEGORIES), I will get the following error: "The following fields have invalid values:
ID: Value can't be null"

### To Reproduce

Go to CATEGORY table (NOT CATEGORIES table), create a new category by pressing '+' sign, fill the "Titel" field with some value; try to save => error will show up.

<img width="904" alt="Screenshot 2023-02-03 at 20 19 03" src="https://user-images.githubusercontent.com/82907634/216688901-9efd43c5-f05a-481b-ab80-f31aca07ea8f.png">

### Errors Shown

no console errors

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

16.18.1

### What database are you using?

cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

cloud

**Comment by eqqi2021** [comment] 2023-02-03 19:17
<img width="846" alt="Screenshot 2023-02-03 at 20 16 27" src="https://user-images.githubusercontent.com/82907634/216688515-53ee6e75-d2b0-45e0-94b6-af89fd694006.png">

**Comment by Nitwel** [comment] 2023-02-06 10:05
Please provide detailed steps to reproduce this like what steps did you take to create your data model and so on.

**Comment by rijkvanzanten** [comment] 2023-02-06 20:59
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2023-02-06 20:59 UTC
Labels: Needs More Info, Can't Reproduce

**Comment by stephan-schmidt** [comment] 2023-08-14 16:52
Just because I came across this error myself. recently migrated and merged content into one Directus instance and this M2M field was given me the same error 
![image](https://github.com/directus/directus/assets/1506096/a9e5f1da-6035-4470-8338-eea44ee5ad4e)

I figured if I set the deselect relationship option from nullify to delete I could deselect and save the item/singleton collection
![image](https://github.com/directus/directus/assets/1506096/d497ff86-bdb6-46dd-9339-c77fbdb026e1)
