### ISSUE TITLE
Custom field order for directus_users wrong in app

### ISSUE THREAD

**Issue by simonflick** [directus/directus#21260] opened 2024-01-31 11:09 UTC
### Describe the Bug

I have noticed that the custom fields for `directus_users` are in the wrong order in my dev environment (10.8.3). In production (10.8.2) the order is still correct.

![Zwischenablagebild](https://github.com/directus/directus/assets/19348971/67369bf0-bfe6-439f-8243-8293e143c708)
![Zwischenablagebild2](https://github.com/directus/directus/assets/19348971/127fd9d7-49df-4c04-a855-4dafa26e89ad)

I tried to fix it by adding a new extra field (divider) and change the ordering a few times. But it only made it worse. Both the divider and the field group got interweaved into the existing fields like this: 

1. `first_name`
2. custom divider
3. `last_name`
4. custom field group
5. rest of the built in fields

### To Reproduce

Not sure if this is a bug caused by migration. Maybe it does show up simply by adding a few extra fields to `directus_users` in a fresh 10.8.3 installation. But I haven't tested that.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-01-31 11:30
Duplicate of https://github.com/directus/directus/issues/20894 this will be resolved in the next release 😄

**Closed by br41nslug** 2024-01-31 11:30 UTC

**Comment by simonflick** [comment] 2024-01-31 12:39
> Duplicate of #20894 this will be resolved in the next release 😄

I skimmed the issues list and missed it, sorry 😀

**Comment by br41nslug** [comment] 2024-01-31 12:41
Nothing to apologize for 😄 we'd rather see duplicates than having things not getting reported 🚀
