### ISSUE TITLE
Version `CXXABI_1.3.8' not found on 'npx directus start'

### ISSUE THREAD

**Issue by anthonycibin** [directus/directus#5025] opened 2021-04-13 09:33 UTC
Hi, 
I encountered this error on 'npx directus start'

I use cPanel with Node js v12.19.1

<img width="1630" alt="Schermata 2021-04-13 alle 11 32 59" src="https://user-images.githubusercontent.com/81036840/114531236-01686b00-9c4c-11eb-8019-75e95413a52f.png">

**Comment by rijkvanzanten** [comment] 2021-04-13 14:10
Duplicate of your own issue two days ago https://github.com/directus/directus/issues/4983 that was moved to a Q&A discussion here: https://github.com/directus/directus/discussions/4998.

**Closed by rijkvanzanten** 2021-04-13 14:10 UTC
