### ISSUE TITLE
Bookmark Order

### ISSUE THREAD

**Issue by FutureBuddha** [directus/directus#22576] opened 2024-05-26 16:39 UTC
### Describe the Improvement

I love the bookmarks feature in Directus. However, there's a small enhancement that would make them even better.

Currently, when I have multiple bookmarks for a collection, they are always ordered alphabetically. While I can adjust the order by prefixing with numbers or special characters, it would be far more efficient to have a sort function or priority setting for bookmarks. This way, I can set the order of bookmarks independently of their names.

Proposal for Improvement

 Sort Function:

- Implement a drag-and-drop sort functionality for bookmarks, allowing users to rearrange them as needed.

**OR**

Priority Function:

- Add a priority setting for bookmarks, enabling users to set their preferred order without relying on alphabetical sorting.

One of these additions would greatly enhance the usability of bookmarks, making it easier to organize and access them based on user preference.

Thank you for considering this request.

**Comment by hanneskuettner** [comment] 2024-05-28 08:23
Heya! Thank you for opening this improvement request. However, this is a duplicate of the currently open feature request #21141. I'll be closing this to track it over there.

**Closed by hanneskuettner** 2024-05-28 08:23 UTC
