### ISSUE TITLE
Translations in content as [object Object] when exporting as CSV

### ISSUE THREAD

**Issue by u12206050** [directus/directus#22374] opened 2024-05-03 07:21 UTC
### Describe the Bug

Translation displays are being exported as `[object Object],[object Object]` instead of the intended translated text that we see in the content view. Works on collections where the translations are on the current collection itself, however does not work via relationships

From this:
![Screenshot 2024-05-03 at 09 07 59](https://github.com/directus/directus/assets/6641242/f299b73c-eebb-41e1-9cbc-4ab45ffa365b)

To this:
![Screenshot 2024-05-03 at 09 08 22](https://github.com/directus/directus/assets/6641242/5df43c06-f882-4141-ba88-53ea29bf7c0b)

### To Reproduce

So set up two collections so you have (A) M2O (B) where B has a translations field with title.

Then add some items to both collections and export collection (A) making sure that the translation field from (B) is one of the columns.

eg. 
![Screenshot 2024-05-03 at 09 20 06](https://github.com/directus/directus/assets/6641242/8821c31c-2d7f-4a46-a384-6affa8e7bc60)

to

![Screenshot 2024-05-03 at 09 21 12](https://github.com/directus/directus/assets/6641242/8526fac8-294c-46f7-b436-81bff2fdde4a)

### Directus Version

10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-05-03 13:12
Can you elaborate on how you're exporting and with what settings.

Closing the issue for now since I have not been able to reproduce it using any of the following means:
1. the export page as csv function
   ![image](https://github.com/directus/directus/assets/9389634/4811c804-7e98-4f91-94fc-acaa6d061baf)
   returning:
   ```
   "ID","M2O","Test","M2O -> Translations"
   1,1,"aaa","[{""id"":1,""test_b_id"":1,""title"":""enenenen"",""languages_id"":{""code"":""en-US""}},{""id"":2,""test_b_id"":1,""title"":""dededede"",""languages_id"":{""code"":""de-DE""}}]"
   2,1,"bbb","[{""id"":1,""test_b_id"":1,""title"":""enenenen"",""languages_id"":{""code"":""en-US""}},{""id"":2,""test_b_id"":1,""title"":""dededede"",""languages_id"":{""code"":""de-DE""}}]"
   ```
2. using the export items feature
   ![image](https://github.com/directus/directus/assets/9389634/1277f8d3-09fe-4e1e-8e5c-7bb8482e3221)
   returning (without the latest field in the screenshot):
   ```
   "id","test","m2o.translations"
   1,"aaa","[1,2]"
   2,"bbb","[1,2]"
   ```
   or (from the screenshot)
   ```
   "id","test","m2o.translations"
   1,"aaa","[{""title"":""enenenen""},{""title"":""dededede""}]"
   2,"bbb","[{""title"":""enenenen""},{""title"":""dededede""}]"
   ```

**Closed by br41nslug** 2024-05-03 13:12 UTC

**Comment by u12206050** [comment] 2024-05-04 08:08
Could it be the display setting of the Translations field, ie, setting the display of the M2O field to `Related Values` and then selecting the translation field of the M2O table as the value to display. I do get it working if I in my example select event.event_translations as a column, but we would like the column to just be event.

![Screenshot 2024-05-04 at 10 04 49](https://github.com/directus/directus/assets/6641242/896f3e84-c212-4fe0-ae62-85058daf6abc)

![Screenshot 2024-05-04 at 10 07 43](https://github.com/directus/directus/assets/6641242/7a386a2a-bf5d-4e8b-932b-62bcf8d73cd4)

**Comment by u12206050** [comment] 2024-05-06 07:08
@br41nslug so could we reopen this or is it still unclear?

**Comment by br41nslug** [comment] 2024-05-06 12:41
I have not been able to reproduce it yet. Nor have i seen an answer to my question of how are you exporting considering there are multiple ways.

Will see if i can repro this specifically on mysql when i find some time.

**Comment by u12206050** [comment] 2024-05-06 14:01
Sorry, I export it using the "Download page as CSV"
