### ISSUE TITLE
Viewing translation fields on a singleton model break Directus.

### ISSUE THREAD

**Issue by rol-jimmyg** [directus/directus#12928] opened 2022-04-21 13:39 UTC
### Describe the Bug

Viewing a singleton with a translation field results in a internal server error, making the client unresponsive until reloading on another page.

### To Reproduce

Done with a fresh install using SQLite:

1. Add a new singleton model.
2. Add a translation field to the model.
3. Go to the content module page for the model.

### Errors Shown

```
"message": "Cannot convert undefined or null to object",
"extensions": {
        "code": "INTERNAL_SERVER_ERROR"
}
```

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

SQLite 5.0.4

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment] 2022-04-21 13:39
Thanks for opening this issue! However this is a duplicate of an existing issue #12831, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. [^1]

[^1]:This is an automated response.

**Comment by rijkvanzanten** [comment] 2022-04-21 13:39
Duplicate of https://github.com/directus/directus/issues/12910

**Closed** 2022-04-21 13:39 UTC
Labels: Bug (Potential)
