### ISSUE TITLE
Error apply snapshot - 'COLUMN_TYPE' of undefined 

### ISSUE THREAD

**Issue by geryla** [directus/directus#10398] opened 2021-12-08 16:35 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After several changes in my database schema on localhost, I tried to generate snapshot and deploy it on my server, where run my live application with production database.

After deploy and install same version of Directus, I got issue with apply snapshot..

My snapshot is here: https://codeshare.io/DZvE0Z

### To Reproduce

1. Make changes in local DB.
2. Generate snapshot by  npx directus schema apply ./snapshot.yaml
3. Deploy snapshot on server
4. Run npx directus schema snapshot ./snapshot.yaml
5. Got error

### Errors Shown

```
Cannot read property 'COLUMN_TYPE' of undefined 
TypeError: Cannot read property 'COLUMN_TYPE' of undefined
    at rawColumnToColumn (/var/www/vhosts/skoleni365.cz/cms.skoleni365.cz/node_modules/knex-schema-inspector/dist/dialects/mysql.js:53:30)
    at MySQL.<anonymous> (/var/www/vhosts/skoleni365.cz/cms.skoleni365.cz/node_modules/knex-schema-inspector/dist/dialects/mysql.js:241:47)
    at step (/var/www/vhosts/skoleni365.cz/cms.skoleni365.cz/node_modules/knex-schema-inspector/dist/dialects/mysql.js:44:23)
    at Object.next (/var/www/vhosts/skoleni365.cz/cms.skoleni365.cz/node_modules/knex-schema-inspector/dist/dialects/mysql.js:25:53)
    at fulfilled (/var/www/vhosts/skoleni365.cz/cms.skoleni365.cz/node_modules/knex-schema-inspector/dist/dialects/mysql.js:16:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

![Snímek obrazovky 2021-12-08 v 17 34 36](https://user-images.githubusercontent.com/74047050/145246720-17e13202-d052-4c79-ad21-df365e979e6d.png)

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

14.18.2

### What database are you using?

MariaDB 13.3.28

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Plesk

**Comment by rijkvanzanten** [comment] 2021-12-14 19:02
Reuploaded schema file here for archival reasons:
[Dec 08 9_18 AM.txt](https://github.com/directus/directus/files/7714123/Dec.08.9_18.AM.txt)

**Comment by jaycammarano** [comment] 2022-01-26 22:28
In 9.5/MariaDB I'm getting:
> 23:16:19 🚨 Failed to create collection "contacts"
> 23:16:19 🚨 Invalid foreign key in field "group". 
which I also saw [here](https://github.com/directus/directus/issues/11153#issuecomment-1022539327)

**Comment by rijkvanzanten** [comment] 2022-04-07 20:57
I'm not able to reproduce this unfortunately..

@geryla Would you be able to share a database dump of the database where this problem is happening? 

I'll close this for now, but happy to keep discussing/debugging 👍🏻

**Closed by rijkvanzanten** 2022-04-07 20:57 UTC
