### ISSUE TITLE
Installation fails with yarn and npx

### ISSUE THREAD

**Issue by thoeynck** [directus/directus#7251] opened 2021-08-06 15:18 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Dear Directus Team,

I was last able to build and deploy Directus CM on June 23rd but my most recent build two days ago fails with the following message:

```
[4/4] Building fresh packages...
success Installed "create-directus-project@9.0.0-rc.88" with binaries:
      - create-directus-project
      - cdp
- Installing Directus
/lib64/libc.so.6: version `GLIBC_2.25' not found (required by /builds/zd-it-sap-dev/patientenportal.cms/my-project/node_modules/argon2/lib/binding/napi-v3/argon2.node)
✖ Installing Directus
Error: undefined
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-directus-project
Arguments: my-project
Directory: /builds/zd-it-sap-dev/patientenportal.cms
Output:
verbose 32.560996706 Error: Command failed.
Exit code: 1
Command: /usr/local/bin/create-directus-project
Arguments: my-project
Directory: /builds/zd-it-sap-dev/patientenportal.cms
Output:
    at ProcessTermError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/usr/lib/node_modules/yarn/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:25888:17)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

Previously I had already enountered and solved the GLIBC version mismatch, which I had solved with the help of https://github.com/directus/directus/issues/6071#issuecomment-854638766

In the process of debugging I tried both npx and yarn as installation methods - with yarn I at least managed to get some debugging output. Can you please assist me in this matter?

Thanks so much!!

### To Reproduce

On my freshly spawned build agent I execute: 

```
yarn --verbose create directus-project my-project
```

### What version of Directus are you using?

v9.0.0-rc.88

### What version of Node.js are you using?

12

### What database are you using?

MSSQL - not sure about the version (not relevant for build)

### What browser are you using?

FF/Chrome (not relevant for build)

### What operating system are you using?

CentOS7

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-08-06 15:23
Duplicate of #6071 / https://github.com/directus/directus/issues/3810 / https://github.com/directus/directus/discussions/6222

I'm afraid I can't really help you out with this beyond what's already shared in those tickets. `argon2` requires a more up-to-date version of GLIBC then you have installed on your machine. You might be able to circumvent this by rebuilding argon2 from source with the `--build-from-source` option. Other than that, you will have to update your CentOS7 installation of GLIBC. If the `--build-from-source` option doesn't help during the `create-directus-project` step, try installing manually (https://docs.directus.io/guides/installation/manual/) and install directus by running `npm install directus --build-from-source`)

**Closed by rijkvanzanten** 2021-08-06 15:23 UTC
Labels: Duplicate
