### ISSUE TITLE
Could not see the other fields of the M2O dropdown list

### ISSUE THREAD

**Issue by gnh1201** [directus/directus#2284] opened 2019-01-24 08:27 UTC
When using M2O, only field values that are not helpful in my selection are shown. (I am using 7 fields  but only 4 fields are displayed.) There seems to be no separate setting. Seems to need improvement.

Screenshot: https://imgur.com/MgDeEAW

**Comment by benhaynes** [comment] 2019-01-24 17:07
Hey @gnh1201 — did you setup the "Listing View Preferences"? THat's exactly what that option is for — choosing the modal's layout/columns/sort/order/etc

In other news, we're working on a big refactor that will make this more intuitive — but please bear with us as we get that released (lots going on).

**Comment by benhaynes** [comment] 2019-01-24 17:09
I'm going to close this one since it's not a bug... but will reference it here so we can track the UX issue:

https://github.com/directus/app/issues/1254

Thanks for creating the detailed ticket!

**Closed by benhaynes** 2019-01-24 17:09 UTC
Labels: enhancement, invalid
