### ISSUE TITLE
MS SQL Server, Error trying to create collections and update project "FAILED_VALIDATION id is required"

### ISSUE THREAD

**Issue by helderhernandez** [directus/directus#4491] opened 2021-03-11 18:33 UTC
Greetings Directus family 🐇
I am happy to test Directus with MS SQL Server 🤓.
The directus tables have been seeded perfectly in SQL Server (I have also been able to create users and upload files locally ⭐)

I have run into a problem when I try:

Create collections ❌
Update project information ❌

When I want to save, the following message appears:

![ERROR](https://user-images.githubusercontent.com/47677287/110835975-1c1e7d00-8265-11eb-813e-12d9df910f7b.png)

---

### Project details
Directus Version: 9.0.0-rc.48
Environment: local
OS: Windows_NT 10.0.19042
Node: 14.15.4
SQL Server: 15.0.2000.5

**Comment by rijkvanzanten** [comment] 2021-03-11 19:15
Interesting!

I _think_ it's because the API doesn't correctly recognize that the `directus_fields.id` column has a primary key configured.

This has to be updated:

https://github.com/directus/directus/blob/7bd5dc5c9f2d5f778f15aab1b14393c594b03f52/packages/schema/src/dialects/mssql.ts#L48

**Comment by martijnboland** [comment] 2021-03-11 21:34
I think this was already fixed in https://github.com/directus/directus/pull/3498/commits/e22db66318e281f2f5c040af8ea5c27ddfed9d0c and also in the PR that also contained the nasty cascade triggers (and was not merged eventually). I'll have a look at it.

**Comment by rijkvanzanten** [comment] 2021-03-11 22:47
@martijnboland I had to strip out the `AUTO_INCREMENT` part from `knex-schema-inspector`, as it's Directus proprietary, but failed to re-add it to the linked position above 🙈

**Closed** 2021-03-11 23:09 UTC
Labels: API, Bug, DB: SQL Server, Good First Issue

**Comment by helderhernandez** [comment] 2021-03-12 17:30
#4494  is wonderful ⭐ thank you so much @martijnboland @rijkvanzanten

I have a question guys, I think I have found an error (related to the UNIQUE CONSTRAINT), is it necessary to open another number? Or can I continue in this thread?

**Comment by rijkvanzanten** [comment] 2021-03-12 17:38
@helderhernandez If it's a different problem than mentioned above, a new issue is easier to track 🙂 

Also, make sure that your issue isn't a duplicate of https://github.com/directus/directus/issues/4481 😉
