### ISSUE TITLE
Translation previews was broken in v9.12.2

### ISSUE THREAD

**Issue by miagg** [directus/directus#13841] opened 2022-06-10 15:45 UTC
### Describe the Bug

After updating to v9.12.2 I immediately noticed that I can no longer see translation previews
![previews](https://user-images.githubusercontent.com/6439071/173101918-18e79fbc-ab60-4c10-840a-3d048164153f.png)

I rolled back to v9.12.1 and previews were restored.
![previews_fixed](https://user-images.githubusercontent.com/6439071/173102170-d19782e6-2c3d-45e3-8ccf-fc2dd3cd95ad.png)

### To Reproduce

Add `translations ` O2M alias field on any table and then set the display to `Preview Translations` like so:
![translations](https://user-images.githubusercontent.com/6439071/173102564-4ac0a104-6536-41d1-b935-4fb3c3905356.png)

### Errors Shown

No visible errors on app or console.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.5.1 (LTS)

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-06-10 16:36
Duplicate of https://github.com/directus/directus/issues/13836#issuecomment-1152414322

**Closed by rijkvanzanten** 2022-06-10 16:36 UTC
Labels: Duplicate
