### ISSUE TITLE
Adding m2m to files breaks file upload

### ISSUE THREAD

**Issue by Dumpstar56** [directus/directus#13117] opened 2022-05-04 16:16 UTC
### Describe the Bug

Upon creating a new relational field for multiple files (m2m) and adding the corresponding m2m field in files, the file upload to the File Directory throws the error that the column added (the corresponding m2m field) does not exist. The File Directory still shows the table of contents, but when clicking on an item, the displayed message says that there is nothing there.

### To Reproduce

create a collection. add a multiple files field in advanced mode. add the corresponding m2m field in files as part of field creation. Go to File Directory and upload a file.

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

v14.18.1

### What database are you using?

Postgres 10.14

### What browser are you using?

Firefox

### How are you deploying Directus?

AWS EC2, pm2 for app management, nginx reverse proxy.

**Comment by azrikahar** [comment] 2022-05-04 16:43
Thanks for opening this issue! However this is a duplicate of an existing issue #11719, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #11719 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-05-04 16:43 UTC
Labels: Bug (Potential)

**Comment by autr** [comment] 2022-05-31 14:00
In 9.11.1 I still get this error but can get around it by doing it in reverse.

❌ Steps to reproduce are:

- Add Files field to a collection
- Check "Add M2M to directus_files collection" box
- Goto to view any directus_files item in GUI or API endpoint and _INTERNAL_SERVER_ERROR_
- In the log there no junction column found in directus_files 

✅ A temporary fix is:

- Add a M2M field to directus_files pointing to your collection
- Check "Add M2M to collection" box
- Optionally also edit M2M in your collection for the sort field

**Comment by rijkvanzanten** [comment] 2022-05-31 14:02
@autr Mind opening a new issue? Thanks!
