### ISSUE TITLE
After 8.15 Reate Create New in One to Many relationships is not working anymore 

### ISSUE THREAD

**Issue by drnachio** [directus/directus#15012] opened 2022-08-10 16:15 UTC
### Describe the Bug

When I'm in a questions and I add a new option to the question:

![image](https://user-images.githubusercontent.com/5763165/183959636-baa2b154-66ef-4218-a048-74927c6ca1b6.png)

It creates the interface, but the associated record is not set since v 8.15:

![image](https://user-images.githubusercontent.com/5763165/183959871-5f0e5193-b2b2-42d6-9788-b5c67799abc4.png)

It happens with all the relations in the system.

I can not generate any dependent record because the field is required:

![image](https://user-images.githubusercontent.com/5763165/183960402-b33f6cc3-bb1f-498b-9821-80f05c403d54.png)

### To Reproduce

Create a One to Many relation and create a new related record from the interface of the "One" record.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

CockroachDB

### What browser are you using?

Google Chrome

### How are you deploying Directus?

Docker & Kubernetes

**Comment by rijkvanzanten** [comment] 2022-08-10 16:53
Duplicate of https://github.com/directus/directus/issues/14992

**Closed by rijkvanzanten** 2022-08-10 16:53 UTC
