### ISSUE TITLE
Healthcheck fails when CACHE_ENABLED set

### ISSUE THREAD

**Issue by syphernl** [directus/directus#19203] opened 2023-07-19 12:46 UTC
### Describe the Bug

We're running Directus on ECS. We're trying to add caching (using ElastiCache Redis 6.2) 

The following env vars have been set for the container (besides the `DB_` and security related ones):

```env
LOG_LEVEL = trace
CACHE_ENABLED = true
CACHE_STORE = redis
CACHE_TTL = 5m
REDIS = redis://:PASSWORD@HOST:6379/0
```

The container starts, seems to be doing stuff but then gets reaped by our the loadbalancer for failing too many healthchecks (against `/server/ping`).

The logs of the container are not providing any insights unfortunatly:

```txt
2023-07-19 14:38:19[12:38:19.440] TRACE: [2.315ms]
2023-07-19 14:38:19SELECT
2023-07-19 14:38:19rel.relname AS name
2023-07-19 14:38:19FROM
2023-07-19 14:38:19pg_class rel
2023-07-19 14:38:19WHERE
2023-07-19 14:38:19rel.relnamespace IN ('public'::regnamespace)
2023-07-19 14:38:19AND rel.relkind = 'r'
2023-07-19 14:38:19AND rel.relname = $1
2023-07-19 14:38:19ORDER BY rel.relname
2023-07-19 14:38:19[directus_collections]
2023-07-19 14:38:19[12:38:19.447] TRACE: [2.557ms] select "version" from "directus_migrations" []
2023-07-19 14:38:19[12:38:19.437] TRACE: [3.624ms] select "oid" from "pg_proc" where "proname" = $1 [postgis_version]
2023-07-19 14:38:19[12:38:19.426] TRACE: [20.629ms] SELECT 1 []
2023-07-19 14:38:09╭───────────────────────────────────────────────────╮
2023-07-19 14:38:09│ │
2023-07-19 14:38:09│ Update available! │
2023-07-19 14:38:09│ │
2023-07-19 14:38:09│ 10.4.2 → 10.4.3 │
2023-07-19 14:38:09│ 1 version behind │
2023-07-19 14:38:09│ │
2023-07-19 14:38:09│ More information: │
2023-07-19 14:38:09│ https://github.com/directus/directus/releases │
2023-07-19 14:38:09│ │
2023-07-19 14:38:09╰───────────────────────────────────────────────────╯
2023-07-19 14:38:07[12:38:07.218] INFO: Running migrations...
2023-07-19 14:38:07[12:38:07.232] TRACE: [5.286ms] select * from "directus_migrations" order by "version" asc []
2023-07-19 14:38:07[12:38:07.243] INFO: Done
2023-07-19 14:38:07[12:38:07.213] TRACE: [18.553ms] SELECT 1 []
2023-07-19 14:38:07[12:38:07.218] TRACE: [2.996ms]
2023-07-19 14:38:07SELECT
2023-07-19 14:38:07rel.relname AS name
2023-07-19 14:38:07FROM
2023-07-19 14:38:07pg_class rel
2023-07-19 14:38:07WHERE
2023-07-19 14:38:07rel.relnamespace IN ('public'::regnamespace)
2023-07-19 14:38:07AND rel.relkind = 'r'
2023-07-19 14:38:07AND rel.relname = $1
2023-07-19 14:38:07ORDER BY rel.relname
2023-07-19 14:38:07[directus_collections]
2023-07-19 14:38:07[12:38:07.218] INFO: Database already initialized, skipping install
2023-07-19 14:38:07[12:38:07.113] INFO: Initializing bootstrap...
2023-07-19 14:37:56╭───────────────────────────────────────────────────╮
2023-07-19 14:37:56│ │
2023-07-19 14:37:56│ Update available! │
2023-07-19 14:37:56│ │
2023-07-19 14:37:56│ 10.4.2 → 10.4.3 │
2023-07-19 14:37:56│ 1 version behind │
2023-07-19 14:37:56│ │
2023-07-19 14:37:56│ More information: │
2023-07-19 14:37:56│ https://github.com/directus/directus/releases │
2023-07-19 14:37:56│ │
2023-07-19 14:37:56╰───────────────────────────────────────────────────╯
```

If Directus can't connect to Redis, I expect some kind of error here? 

I have tried to set the health check grace period to `300s` hoping to see if it is simply the connection to Redis timing out before the health check is working but this does not seem to be the case.

Strangely, setting `CACHE_ENABLED = true` seems to result in the same behavior.

### To Reproduce

* Setup Redis 6.2
* Configure Directus to use it with the above env vars
* Start Directus
* See that the `/server/ping` is not working

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-07-24 17:02
> If Directus can't connect to Redis, I expect some kind of error here?

My guess is that the timeout for ECS' healthcheck is bigger than Redis' connection timeout, which in turn means that ECS will kill the container before Redis has connected 🤔 

Generally speaking, this setup should work (as it's exactly how I'm running Directus in prod right now). Can you confirm that the network configuration within AWS allows traffic from the Directus container to the elasticache server? Unexpected timeouts that hang a long time without any news smells like AWS Security Groups to me (I've shot myself in the foot with that gun a couple times in the past)

**Comment by rijkvanzanten** [comment] 2023-07-24 17:02
I'll close this for now, as I haven't been able to reproduce this. Happy to reopen if it turns out to be a bug in Directus 👍🏻

**Closed by rijkvanzanten** 2023-07-24 17:02 UTC

**Comment by syphernl** [comment] 2023-07-25 06:29
> > If Directus can't connect to Redis, I expect some kind of error here?
> 
> My guess is that the timeout for ECS' healthcheck is bigger than Redis' connection timeout, which in turn means that ECS will kill the container before Redis has connected thinking

Not sure what the default Redis timeout is, but I did set the ECS health check to 5 minutes.

> Generally speaking, this setup should work (as it's exactly how I'm running Directus in prod right now). Can you confirm that the network configuration within AWS allows traffic from the Directus container to the elasticache server? Unexpected timeouts that hang a long time without any news smells like AWS Security Groups to me (I've shot myself in the foot with that gun a couple times in the past)

That was also my initial thought, but it appears to be all fine. The setup follows the very same one we have for RDS for instance, which works fine. I will look into it again. 
@rijkvanzanten Are you using the same format of the Redis connection string as well?

**Comment by rijkvanzanten** [comment] 2023-07-25 13:58
> @rijkvanzanten Are you using the same format of the Redis connection string as well?

No, I use `REDIS_HOST` and `REDIS_PORT`, that should behave the same though 🤔

**Comment by syphernl** [comment] 2023-07-26 11:58
@rijkvanzanten I have confirmed that my ECS Service can reach my Redis instance:
![image](https://github.com/directus/directus/assets/639906/1ac9c8f4-fa7d-4a2f-a702-dd9078673a9f)

So ISTM it must be something configuration (or app) related preventing Directus from working

**Comment by rijkvanzanten** [comment] 2023-07-27 18:13
Very strange indeed.. I'm having some trouble figuring out how to help debug this, as it's a typical case of _Works on my machine!™️_. Just to confirm, when you said:

> Strangely, setting CACHE_ENABLED = true seems to result in the same behavior.

did you mean removing the redis configuration completely, and only enabling that cache environment variable?
