### ISSUE TITLE
Extensions - Endpoints ROUTE_NOT_FOUND after update

### ISSUE THREAD

**Issue by NecoHorne** [directus/directus#20250] opened 2023-10-30 11:15 UTC
### Describe the Bug

After updating to to v10.7.1 from v10.7.0 custom endpoints are all throwing ROUTE_NOT_FOUND errors. 

The endpoint shows as loaded on project startup
![image](https://github.com/directus/directus/assets/30078491/6100e4db-2919-457c-90db-89917bb8b723)

But trying to call any of them throws the error and returns 404
![image](https://github.com/directus/directus/assets/30078491/2447a21d-7e24-42ee-b969-b993ab1a4797)

I downgraded back to v10.7.0 and they worked again. I did not see any breaking changes for extensions in the latest release notes so I am assuming its a bug. 

dev environment: Windows + MySQL

### To Reproduce

Update to v10.7.1 and call custom endpoints

### Directus Version

v10.7.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-10-30 11:17
Duplicate of #20223 will be resolved with the next release.

**Closed by br41nslug** 2023-10-30 11:17 UTC
