### ISSUE TITLE
Unable to upload files to "root" directory

### ISSUE THREAD

**Issue by dwene** [directus/directus#6403] opened 2021-06-21 14:37 UTC
1) The issue and what you expected to happen
After upgrading Directus v9.0.0-rc.76, I can no longer upload files into the "root" directory. I am able to upload files into folders.

I receive a 400 error with this message:
```
{
  "errors": [
    {
      "message": "Invalid foreign key in field \"folder\".",
      "extensions": {
        "code": "INVALID_FOREIGN_KEY",
        "collection": "directus_files",
        "field": "folder",
        "invalid": "'grayscale-photography-of-people-raising-hands-2014775-copy 1.png', 'null', '20ce2a60-1508-4258-97c7-728bca676a41', 'S3', 'Grayscale Photography of People Raising Hands 2014775 Copy 1', 'image/png', 'a00dcffd-a40f-4e14-b9e0-d48af689168f'"
      }
    }
  ]
}
```

2) Exact steps to reproduce this issue
- Login to directus admin ui on RC-76
- Go to files section
- Try to upload an image or other file into the root directory
- Notice the error message

Video: https://www.loom.com/share/f058a673dce4435299f7c6c01336d98e

3) Your environment:
    Directus v9.0.0-rc.76
    MariaDB 
    Docker + Kubernetes
    Brave Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (x86_64)

4) Any other relevant information we might need to reproduce this issue
   I'm using S3 for storage, but this appears to happen with local storage also.

**Comment by rijkvanzanten** [comment] 2021-06-21 14:39
Duplicate of #6310

**Closed by rijkvanzanten** 2021-06-21 14:39 UTC
