### ISSUE TITLE
OpenID Login: Empty .update() call detected!

### ISSUE THREAD

**Issue by Lucas-Gruber** [directus/directus#18612] opened 2023-05-15 22:22 UTC
### Expected behavior

Log In should work

### Actual behavior

It redirects to Login Page with Error: **Unexpected Error**

In Console comes following error:
```bash
[00:20:05.781] WARN: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.
    err: {
      "type": "Error",
      "message": "Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.",
      "stack":
          Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.
              at QueryCompiler_PG._prepUpdate (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:1354:13)
              at QueryCompiler_PG.update (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/dialects/postgres/query/pg-querycompiler.js:51:29)
              at QueryCompiler_PG.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:73:29)
              at QueryBuilder_PostgreSQL.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querybuilder.js:83:44)
              at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
              at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:300:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:30:19)
              at async file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/items.js:471:21
    }
[00:20:05.782] WARN: [OpenID] Unexpected error during OpenID login
    err: {
      "type": "Error",
      "message": "Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.",
      "stack":
          Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.
              at QueryCompiler_PG._prepUpdate (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:1354:13)
              at QueryCompiler_PG.update (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/dialects/postgres/query/pg-querycompiler.js:51:29)
              at QueryCompiler_PG.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:73:29)
              at QueryBuilder_PostgreSQL.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querybuilder.js:83:44)
              at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
              at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:300:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:30:19)
              at async file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/items.js:471:21
    }
```

### To Reproduce

1. Create Microsoft Azure OpenID as Auth Provider
2. Register an Account with Public Registration
3. Logout
4. Try to Log In again

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-05-15 22:34
Thanks for opening this issue! However this is a duplicate of an existing issue #18595, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #18595 has been fixed by #18607 which will be available with the next release.

**Closed by paescuj** 2023-05-15 22:34 UTC
