### ISSUE TITLE
The entries of extension in Settings -> Modules disappeared

### ISSUE THREAD

**Issue by delai** [directus/directus#23842] opened 2024-10-11 12:16 UTC
### Describe the Bug

I used to be able to see the entries of extension in Settings -> Modules, but now it's gone. I've checked the logs and everything seems normal, and there's no corresponding entry in the left sidebar.

![image](https://github.com/user-attachments/assets/df8b82f6-ac3c-4d4b-97ac-5e25f06de8b2)
<img width="897" alt="image" src="https://github.com/user-attachments/assets/8cd7d6f2-4e5b-43f9-9930-bd010e4d6a48">
<img width="954" alt="image" src="https://github.com/user-attachments/assets/6d1e2ede-7576-4f1c-8470-1853a70d0d14">

### To Reproduce

I'm unsure if this is related to the [directus-extension-flow-manager extension](https://github.com/baguse/directus-extension-flow-manager) I installed via npm. Everything was working fine initially, including the [directus-extension-flow-manager extension](https://github.com/baguse/directus-extension-flow-manager). However, after some time, the entries for both the [SEO extension](https://github.com/codihaus/directus-extension-seo#readme)  and the [directus-extension-flow-manager extension](https://github.com/baguse/directus-extension-flow-manager) mysteriously disappeared from the left sidebar and the page Settings-> Modules.

I've documented everything I've done here: https://github.com/baguse/directus-extension-flow-manager/issues/15#issuecomment-2407122262 , but even after deleting everything and reinstalling extension like [SEO extension](https://github.com/codihaus/directus-extension-seo#readme), the menu entry still doesn't appear.

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-10-11 13:24
Are you seeing any errors in the browser console?

**Comment by delai** [comment] 2024-10-11 14:16
> Are you seeing any errors in the browser console?

no error.

I didn't do anything, I just refreshed the page and it came back.

![image](https://github.com/user-attachments/assets/c4c9af0a-c29a-4746-9509-02b03c5b2152)

**Comment by br41nslug** [comment] 2024-10-11 14:36
Then it may been an issue with cache or loading the extensions in the browser that first load.

I'll close the issue for now, as it seems to have been resolved after refresh and I am unable to reproduce the bug on my end at the moment.

**Closed by br41nslug** 2024-10-11 14:36 UTC
