### ISSUE TITLE
Relational interfaces are not rendering fields with default value after item was created

### ISSUE THREAD

**Issue by d1rOn** [directus/directus#15763] opened 2022-09-26 18:35 UTC
### Describe the Bug

If I press **Create New** button on relational interface, fill form and leave some fields blank (like a Toggle with the default value) and press **Save**, the relational interface will not be able to render this field (if it is included in template).

If after that I'll click **Save** on parent object, the relational interface will be able to render item template correctly.

https://user-images.githubusercontent.com/26179694/192355343-839d05f6-23be-4a07-b3e9-4605ddd79335.mp4

It happens because the program does not including such properties in result object and `render-template` can't find this property with `lodash.get`.
I'll add a fix to #15736.

### To Reproduce

1. Create collection `B` with field `toggle` (Toggle interface, default to false; Boolean display).
2. Create collection `A` with field `relation` (O2M to `B`; Display template `{{ toggle }}`)).
3. Try to create a new `A` item.
4. Press **Create New** button, leave form untouched, press **Save**.
5. You can see that item display template is not rendered.

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

v17.9.0

### What database are you using?

SQLite 3

### What browser are you using?

Chrome

### How are you deploying Directus?

Locally

**Comment by br41nslug** [comment] 2022-10-10 14:44
Duplicate of issue https://github.com/directus/directus/issues/15569

**Closed by br41nslug** 2022-10-10 14:44 UTC
Labels: App, Duplicate, Bug (Potential)
