### ISSUE TITLE
GraphQL should return file object for single files

### ISSUE THREAD

**Issue by eXaminator** [directus/directus#3457] opened 2020-12-17 21:21 UTC
I'm not 100% sure if this is a bug (I think it is), or if it is a feature request.

When adding a file field for a single file (or image in my case) and requesting that field via GraphQL, it only returns the UUID of the file instead of the actual file reference (which is the case for multiple file fields and what I'd actually expect).

Edit: I seem to have one field where it works as expected and another one where it doesn't. I'll have to see what the difference is between both of them.

**Comment by eXaminator** [comment] 2020-12-17 21:29
Ok, I think I found the problem:
I have newly created the first field, which works as expected. When I duplicate that field, it does not receive an entry in directus_relations and thus is handled like a normal UUID field.

**Comment by rijkvanzanten** [comment] 2020-12-17 21:29
Duplicate of https://github.com/directus/directus/issues/3239

**Closed by rijkvanzanten** 2020-12-17 21:29 UTC
