### ISSUE TITLE
Data Model: Folders - system completely crashes when put collection in a folder

### ISSUE THREAD

**Issue by canomatt** [directus/directus#14774] opened 2022-08-01 10:07 UTC
### Describe the Bug

I created a new Folder in the Data Model. I then tried to drag an existing collection under that Folder.
Every time I tried this the system went slow, became unresponsive - and then when came back online the collection had not been moved. One time the system completely stopped.

I would expect to be able to put collections under the folder.

### To Reproduce

See above

### Errors Shown

System completely stopped one time

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

n/a

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by br41nslug** [comment] 2022-08-01 10:21
I am unable to reproduce this locally or in a cloud app. Can you elaborate on the situation to reproduce this? For instance do you have an exorbitant amount of collections or multiple levels of folder nesting.

**Comment by rijkvanzanten** [comment] 2022-08-01 13:32
We haven't been able to reproduce this based on the given information. Closing this for now, but happy to keep discussing. We'll reopen once more information becomes available 👍🏻

**Comment by canomatt** [comment] 2022-08-03 17:15
We have around 60 collections - all on one flat level at the top. There are also some hidden collections (~25). Hope that helps.

**Comment by rijkvanzanten** [comment] 2022-08-03 18:02
Thanks! It does 🙂

**Comment by azrikahar** [comment] 2022-08-10 07:19
Closing as I believe #14833 intended to fix this, but the PR wasn't linked to this issue.

**Comment by rijkvanzanten** [comment] 2022-08-10 14:32
@azrikahar #14833 certainly helps, but isn't the real solution to this particular issue 🙂 

To fix this, we should add a `updateBatch` method to the `CollectionsService` and then do the full update in a single request

**Closed** 2022-10-18 19:19 UTC
Labels: API, Bug
