### ISSUE TITLE
directus schema apply does not work when using groups

### ISSUE THREAD

**Issue by cpt-n3mo** [directus/directus#9718] opened 2021-11-11 13:06 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

when one hes a few data models, and one wants to export these via cli `npx directus schema snapshot` 
the export goes without a problem but the import using `npx directus schema apply`  fails when the data modele contains groups, 
when one removes the groups from the data models, the data gets imported without a problem,
then if one applies the snapshot with the groups it adds them as a update model does get the groups but the cli tool gives a error..  

### To Reproduce

1) create data models that contains groups.
2) export models via cli tool.
3) apply export to clean database

### Errors Shown

error when running `npx directus schema apply file.json' with groups
```
02:42:56 🚨 Invalid foreign key in field "group".
Error: Invalid foreign key in field "group".
    at foreignKeyViolation (/directus/node_modules/directus/dist/exceptions/database/dialects/mysql.js:133:12)
    at extractError (/directus/node_modules/directus/dist/exceptions/database/dialects/mysql.js:31:20)
    at translateDatabaseError (/directus/node_modules/directus/dist/exceptions/database/translate.js:47:53)
    at /directus/node_modules/directus/dist/services/items.js:95:68
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
and this is the error it gives when first its imported without groups, "working like a charm" and then one imports again with groups to update..

```
Would you like to continue? Yes
/directus/node_modules/directus/dist/services/relations.js:371
        const m2oFieldDBType = this.schema.collections[relation.collection].fields[relation.field].dbType;
                                                                            ^

TypeError: Cannot read properties of undefined (reading 'fields')
    at RelationsService.alterType (/directus/node_modules/directus/dist/services/relations.js:371:77)
    at TableBuilder._fn (/directus/node_modules/directus/dist/services/relations.js:205:26)
    at TableBuilder.toSQL (/directus/node_modules/knex/lib/schema/tablebuilder.js:47:16)
    at SchemaCompiler_MySQL.build (/directus/node_modules/knex/lib/schema/compiler.js:143:23)
    at SchemaCompiler_MySQL.alterTable (/directus/node_modules/knex/lib/schema/compiler.js:164:13)
    at SchemaCompiler_MySQL.toSQL (/directus/node_modules/knex/lib/schema/compiler.js:97:26)
    at SchemaBuilder.toSQL (/directus/node_modules/knex/lib/schema/builder.js:35:45)
    at ensureConnectionCallback (/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (/directus/node_modules/knex/lib/execution/runner.js:272:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

doing some tracing

`node_modules/directus/dist/services/relations.js`
```
/**
     * MySQL Specific
     *
     * MySQL doesn't accept FKs from `int` to `int unsigned`. `knex` defaults `.increments()` to
     * `unsigned`, but defaults regular `int` to `int`. This means that created m2o fields have the
     * wrong type. This step will force the m2o `int` field into `unsigned`, but only if both types are
     * integers, and only if we go from `int` to `int unsigned`.
     *
     * @TODO This is a bit of a hack, and might be better of abstracted elsewhere
     */
    alterType(table, relation) {
        const m2oFieldDBType = this.schema.collections[relation.collection].fields[relation.field].dbType;
        const relatedFieldDBType = this.schema.collections[relation.related_collection].fields[this.schema.collections[relation.relate
        if (m2oFieldDBType !== relatedFieldDBType && m2oFieldDBType === 'int' && relatedFieldDBType === 'int unsigned') {
            table.specificType(relation.field, 'int unsigned').alter();
        }
    }
```

### What version of Directus are you using?

9.0.0rc101 | latest

### What version of Node.js are you using?

inside docker container

### What database are you using?

mariadb

### What browser are you using?

chrome, firefox, chromium

### What operating system are you using?

Arch Linux, 5.13.6-zen1-1-zen  x86_64 GNU/Linux

### How are you deploying Directus?

docker

**Comment by Nitwel** [comment] 2021-11-11 13:39
This seems to be a duplicate of #8443

**Closed by Nitwel** 2021-11-11 13:39 UTC
Labels: Bug (Potential)

**Comment by cpt-n3mo** [comment] 2021-11-12 02:30
Good day!

I pulled the latest release 9.0.1 and the second bug (error) from my post is solved but the first one is not, its still not possible to import snapshots that contain groups.
i made a small and somewhat dirty script to get around it. as described above. for the ppl who have the same problem for the time being this is a workaround,.. 

just export a snapshot as usual and import it using the script.
[applySnapshot.js](https://github.com/cpt-n3mo/directus_scripts/blob/master/applySnapshot.js)

kind regards

**Comment by joselcvarela** [comment] 2021-11-12 05:45
Hello @cpt-n3mo 
I also experienced the `group` problem. Here is an open PR about it https://github.com/directus/directus/issues/9723
Let's track that specific issue there and thanks for posting a workaround 👍
