### ISSUE TITLE
Drop Many to One field fails

### ISSUE THREAD

**Issue by pascal-lauener-livinguard** [directus/directus#12211] opened 2022-03-17 12:24 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a Many to One field. If I try to delete the field I got the following Error Message:

```
{
  "errors": [
    {
      "message": "ALTER TABLE [Products] DROP COLUMN [color] - ALTER TABLE DROP COLUMN color failed because one or more objects access this column.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

What can I do? Can I delete the field directly on the SQL (Azure) Database? But I assume then I have to refresh the schema somewhere?

thank you for help

Pascal

### To Reproduce

Create a Many to One field
Try to Delete

### Errors Shown

{
  "errors": [
    {
      "message": "ALTER TABLE [Products] DROP COLUMN [color] - ALTER TABLE DROP COLUMN color failed because one or more objects access this column.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

N/A

### What database are you using?

Azure SQL

### What browser are you using?

Chrome

### What operating system are you using?

Mac

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-03-17 12:35
Should be duplicate of #11510. The error is slightly different, but I assume that is just the different error message from different db vendors (MS SQL in your case).

> Can I delete the field directly on the SQL (Azure) Database? But I assume then I have to refresh the schema somewhere?

If you would like to have a more in-app way of deleting it successfully without accessing the database directly, you can try downgrading to `v9.5.0` as this bug happens in `v9.5.1` onwards.

However if you would like to try it via database, It should work, but here's a checklist off the top of my head just to be sure: 

⚠ Disclaimer: Do make sure to back up beforehand as this can be a "at your own risk" type of action here.

- remove the column from the database (you'll likely need to drop the foreign key constraint as well)
- remove said field from `directus_fields`
- restart Directus just in case the schema is cached ([which is on by default](https://docs.directus.io/configuration/config-options/#cache) but customizable via `CACHE_SCHEMA` env variable)

**Closed by azrikahar** 2022-03-17 12:35 UTC
Labels: Bug (Potential)
