### ISSUE TITLE
mod_rewrite

### ISSUE THREAD

**Issue by gavinappleby** [directus/directus#889] opened 2015-07-20 12:53 UTC
Trying to get Directus set up on a 1and1 server but having issues with mod_rewrite using .htccess I have turned it on but the pre install check is showing as not enabled.

Has anybody else reported any similar issues? If I click install the page just turns blank and I have to the clear my computer cache in order to access the install page again.

Gav

**Comment by WellingGuzman** [comment] 2015-07-20 12:59
Hi @gavinappleby,

First I'd recommend not sharing real server information for security reason.

Ok, so let's go to the issue, is this a apache or nginx server? are you using mod_php, php_fpm,etc?

All similar issues was reported before was somehow related with the type of server setup. can you give me more information about your server?

Thanks!

**Comment by gavinappleby** [comment] 2015-07-20 13:01
Bugger uploaded wrong screen shot >_<

Server is Apache, server info is here:

http://sandpit.weare32.co.uk/emjplastics/iceberg/my_info.php

Think it might be the Server API causing the issue.

**Comment by WellingGuzman** [comment] 2015-07-20 13:09
@gavinappleby as far as I'm concern, using `Server API: CGI/FastCGI` would display mod_rewrite with a red question mark, but on fastCGI we can't use `apache_get_modules()` function, but it should still work with any problem.

Did you double check if `mod_rewrite` is actually enabled?

anyways, I'd take a look on a CGI/FastCGI server to see if I can replicate your issue.

**Comment by gavinappleby** [comment] 2015-07-20 13:38
I have a feeling that the mod_rewrite module is not actually enabled now :(

**Comment by gavinappleby** [comment] 2015-07-20 14:08
I think it might be that now I look at it a bit more, the .htaccess file is looking for the module mod_rewrite to then initiate RewriteEngine On. I think the module is missing from the server which is what is causing the issue.

The thing that confuses me is that I am using RewriteEngine on other sites hosted on the same server and they seem to follow the rules no problem. I am going to try uploading the files to within one of those directories and see what happens.

**Comment by gavinappleby** [comment] 2015-07-20 14:42
Hmm ok (sorry for messages) I have created a new .htaccess file in a folder on the server with the contents:

Options +FollowSymLinks -MultiViews 

RewriteEngine On
RewriteBase /

RewriteRule ^this-is-a-test/$ /result.php [L]

Then added the copy test to the results.php file http://sandpit.weare32.co.uk/this-is-a-test/

That does work which would suggest that mod_rewrite is actually on!

Will keep playing.

**Comment by WellingGuzman** [comment] 2015-07-20 17:17
Can you show me the blank page that it display when you click install?
Can you check the browser console, and screenshot any warning or error that may show up?
Are you using master branch?

I wonder what this may be, because it should work fine as far as I'm concerned, I install it on different machines with php-fpm and apache and I couldn't replicate your problem.

**Comment by gavinappleby** [comment] 2015-07-21 08:21
Yes using the master branch, below is a screen shot of the page after I click install. Nothing appearing in the console.

![screen shot 2015-07-21 at 09 16 30](https://cloud.githubusercontent.com/assets/13417801/8795997/59f16a5a-2f89-11e5-9977-147b9d2e4282.png)

It's very strange!

**Comment by WellingGuzman** [comment] 2015-07-21 18:29
Oh I wonder, does `api/config.php` gets created?, what's was the value of _Project Path_ in the Project Info step. (image below) or in `api/config.php` file what's the value of _DIRECTUS_PATH_ ( `define('DIRECTUS_PATH', '/');`)?

![screen shot 2015-07-21 at 2 24 08 pm](https://cloud.githubusercontent.com/assets/1531291/8809008/ec84a038-2fb3-11e5-8c7e-a7a9c141ede7.png)

I'm asking because someone reported and error before and it was because _DIRECTUS_PATH_ wasn't set correctly. In your case it should be **/emjplastics/iceberg/**

**Comment by gavinappleby** [comment] 2015-07-22 08:09
No the config.php file does not get created. The project path is set up as below:

![screen shot 2015-07-22 at 09 02 52](https://cloud.githubusercontent.com/assets/13417801/8820877/0b5cb1b0-3051-11e5-9bac-3756e984b7a9.png)

Is it possible to just copy and rename the config_sample.php file and enter the into into there and the just import schema.sql into the database manually?

**Comment by WellingGuzman** [comment] 2015-07-22 14:38
> Is it possible to just copy and rename the config_sample.php file and enter the into into there and the just import schema.sql into the database manually?

Yes, absolutely you could also do that.

This is something I'd like to fix, but I'm out of questions.

This is something we do not ask, but as me, I'd like to give your installation a try, if you don't mind, just let me know.

**Comment by gavinappleby** [comment] 2015-07-22 14:59
More than happy to help Directus 5 has really helped me massively when it comes to developing websites.

I will set you up as a user and give you access, do you have an email address I can send the info to?

**Comment by WellingGuzman** [comment] 2015-07-22 15:03
I'm glad, Of course you can send me the details to `hola (at) wellingguzman.com` I'd love to help  you solve this problem.

**Comment by benhaynes** [comment] 2015-09-02 01:56
@WellingGuzman Does this relate to the other mod_rewrite issue we're seeing here? https://github.com/RNGR/Directus/issues/994

**Comment by WellingGuzman** [comment] 2016-04-22 18:32
I don't recall if we get to solve this issue before. @gavinappleby did you solve your problem?

@benhaynes let's close this ticket we have been fixing lots of tickets since, so the problem still happening please open a new ticket or comment here.

**Comment by benhaynes** [comment] 2016-04-22 18:44
Sounds good.

**Comment by Vienneww** [comment] 2016-09-27 02:52
I am also having the same problem. When I check the loaded modules in phpinfo, mod_rewrite is in it but in pre-check step of installation in Directus appears to be like: 
Mod_Rewrite Enabled (Learn More)	No

I also check the DIRECTUS_PATH in config.php, which is the same path of index.php.

**Comment by WellingGuzman** [comment] 2016-09-27 03:45
@Vienneww what OS are you using? apache or nginx? how are you trying to install Directus? From the master branch, the build branch?

**Comment by WellingGuzman** [comment] 2016-09-27 03:47
@Vienneww another question if you go and click install will it work?

**Comment by Vienneww** [comment] 2016-09-27 04:22
Im using Apache, i downloaded it from https://github.com/directus/directus/tree/build.
When I click install, I get HTTP ERROR 500.

**Comment by WellingGuzman** [comment] 2016-09-27 04:31
@Vienneww Thanks for the info. What operative system are you using?

**Comment by Vienneww** [comment] 2016-09-27 04:38
Im using amazon linux ec2.
Thanks so much for the help!

**Comment by WellingGuzman** [comment] 2016-09-27 04:41
Thanks for the info, _I checking off item from the list_, another question how your `api/config.php` looks like, you can remove any sensitive data like your server host and database user and password. and share the rest.

**Comment by Vienneww** [comment] 2016-09-27 04:48
Here is my api/config.php after clicking INSTALL. Thanks~
[config.docx](https://github.com/directus/directus/files/494590/config.docx)

**Comment by WellingGuzman** [comment] 2016-09-27 04:57
I will keep asking bunch of questions here, so I've seen so far everything have been all good.
PHP Version: ?
Apache Version: ?
Anything on php/apache logs about the HTTP 500 error?

We've been informed about this issue before, and we couldn't replicate it, it will be helpful we can help each other here to fix it.

**Comment by Vienneww** [comment] 2016-09-27 05:13
About HTTP 500 ERROR, I got this log updated
[accesslog.docx](https://github.com/directus/directus/files/494627/accesslog.docx)

**Comment by WellingGuzman** [comment] 2016-09-27 05:30
Really appreciate the help, It seems the mod_rewrite is not actually enabled, OR there's a issue creating the endpoint.

On your phpinfo what `Server API` and `Loaded Modules` says?

**Comment by Vienneww** [comment] 2016-09-27 05:42
Server API: Apache 2.0 Handler
Loaded Modules: 
core mod_so http_core mod_rewrite mod_access_compat mod_actions mod_alias mod_allowmethods mod_auth_basic mod_auth_digest mod_authn_anon mod_authn_core mod_authn_dbd mod_authn_dbm mod_authn_file mod_authn_socache mod_authz_core mod_authz_dbd mod_authz_dbm mod_authz_groupfile mod_authz_host mod_authz_owner mod_authz_user mod_autoindex mod_cache mod_cache_disk mod_cache_socache mod_data mod_dbd mod_deflate mod_dir mod_dumpio mod_echo mod_env mod_expires mod_ext_filter mod_filter mod_headers mod_include mod_info mod_log_config mod_logio mod_macro mod_mime_magic mod_mime mod_negotiation mod_remoteip mod_reqtimeout mod_request mod_setenvif mod_slotmem_plain mod_slotmem_shm mod_socache_dbm mod_socache_memcache mod_socache_shmcb mod_status mod_substitute mod_suexec mod_unixd mod_userdir mod_version mod_vhost_alias mod_watchdog mod_dav mod_dav_fs mod_dav_lock mod_lua prefork mod_proxy mod_lbmethod_bybusyness mod_lbmethod_byrequests mod_lbmethod_bytraffic mod_lbmethod_heartbeat mod_proxy_ajp mod_proxy_balancer mod_proxy_connect mod_proxy_express mod_proxy_fcgi mod_proxy_fdpass mod_proxy_ftp mod_proxy_http mod_proxy_hcheck mod_proxy_scgi mod_proxy_wstunnel mod_cgi mod_php5

mod_rewrite actually exists. Thanks so much!

**Comment by WellingGuzman** [comment] 2016-09-27 05:49
Thanks again, so you are good there then, you should check your apache configuration. and see if you have `AllowOverride All` under `<Directory>`?

**Comment by Vienneww** [comment] 2016-09-27 07:14
Sorry for the late. Yes, in my httpd.conf under <Directory>, it is:
<Directory />
    #AllowOverride none
    AllowOverride All
    Require all denied
</Directory>

**Comment by WellingGuzman** [comment] 2016-09-27 07:39
@Vienneww Thanks for the info, isn't there another `<Directory>` that looks like `<Directory "/var/www/html">` with a path to your public path or directus path?

Ex:
```
<Directory "/var/www/html">
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>
```

Can you do this to make sure .htaccess is working?

1. Create a new directory `test`.
2. Create a new `.htaccess` file inside `test` directory with the content below:

```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteRule ^.*$ mod_rewrite.php
</IfModule>
```

3. Create a new php file `mod_rewrite.php` inside `test` with the content below:
```php
<?php
var_dump($_SERVER['REQUEST_URI']);
```

4. Go to your browser and access the `test` directory `yourhost.com/test/non-existing`

5. If `mod_rewrite` is enabled and you added `AllowOverride All`  you should see the value `/non-existing` being dump.

**Comment by Vienneww** [comment] 2016-09-27 08:05
In httpd.conf, now its like this:
`<Directory />`
    AllowOverride All
    Require all denied
`</Directory>`

`<Directory "/var/www">`
    AllowOverride All
    # Allow open access:
    Require all granted
`</Directory>`

`<Directory "/var/www/html">`
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
`</Directory>`

`<Directory "/var/www/cgi-bin">`
     AllowOverride All
    Options None
    Require all granted
`</Directory>`

I followed your steps, and in my browser accessing `yourhost.com/test/non-existing`, I get this:
string(18) "/test/non-existing"

Does it mean mod_rewrite is enabled?

Another thing I'd like to mention is that, 
when api/config.php hadn't been generated, I could still access the installation page in browser. However after I clicked INSTALL, api/config.php was generated and I could not access the installation page anymore. What I get instead is the content in this file

[pageText.docx](https://github.com/directus/directus/files/494895/pageText.docx)

, no matter what I add in the link after myhost.com(`yourhost.com/xxxxxxxx`).
If I delete that api/config.php, I am able to access the installation page again.

**Comment by WellingGuzman** [comment] 2016-09-27 08:56
> I followed your steps, and in my browser accessing yourhost.com/test/non-existing, I get this:
string(18) "/test/non-existing"

That means that `mod_rewrite` is enabled. still the installation saying "no" on mod_rewrite?

> However after I clicked INSTALL, api/config.php was generated and I could not access the installation page anymore. What I get instead is the content in this file

This is probably because the `api/config.php` is wrong. We are working on display better errors messages.

We are here to help. @Vienneww were you able to install Directus now?

**Comment by Vienneww** [comment] 2016-09-27 09:05
No, still cannot install, I'm still getting HTTP 500 ERROR.
But here's what it went through,
1. going to myhost.com on browser
2. filling info and in last step, Mod_Rewrite Enabled (Learn More): Yes
3. click INSTALL
5. HTTP 500 ERROR
6. going to myhost.com on browser
7. Mod_Rewrite Enabled (Learn More): No

So, is that currently the problem is my `api/config.php`?

**Comment by WellingGuzman** [comment] 2016-09-27 09:08
I do not think that the HTTP 500 ERROR problem is related to `api/config.php`, is there a log file inside `api/logs/`? or even your php/apache logs (beside access.log)?

**Comment by Vienneww** [comment] 2016-09-27 09:19
in /etc/httpd/logs:
[error_log.docx](https://github.com/directus/directus/files/495058/error_log.docx)
in api/logs:
[2016-09-27log.docx](https://github.com/directus/directus/files/495063/2016-09-27log.docx)

Thanks~

**Comment by WellingGuzman** [comment] 2016-09-27 09:23
@Vienneww it seems the user you are using doesn't have the right to `INSERT` granted.

> INSERT command denied to user

Can you confirm and give the user the right permissions or use another user with enough privileges?

**Comment by Vienneww** [comment] 2016-09-27 10:23
Thanks so much~ I think the major cause is the permission of the DB user, I'll report here soon when the problem is resolved. Much Appreciated!

**Comment by WellingGuzman** [comment] 2016-09-27 17:21
@Vienneww thanks, we will work on checking for permissions and give the users a better error message.

**Comment by WellingGuzman** [comment] 2016-09-27 23:49
I will close the ticket as the `mod_rewrite` was resolved.

**Closed by WellingGuzman** 2016-09-27 23:49 UTC
Labels: 3. Major, Docs

**Comment by Vienneww** [comment] 2016-09-28 09:10
yes, giving the db user permission solved the problem. Mod_rewrite is shown enabled in installation page now and It was installed successfully. Thanks a lot!

**Comment by WellingGuzman** [comment] 2016-09-28 22:49
@Vienneww glad that the problem was solve. Anything else just let us know, we are here to help.
