### ISSUE TITLE
Column names in each table must be unique. Column name 'id' in table 'directus_extensions' is specified more than once

### ISSUE THREAD

**Issue by woeterman94** [directus/directus#21876] opened 2024-03-15 13:16 UTC
### Describe the Bug

2024-03-15T13:08:16.332840555Z RequestError: ALTER TABLE [directus_extensions] ADD [id] uniqueidentifier null, [folder] nvarchar(255), [source] nvarchar(255), [bundle] uniqueidentifier - Column names in each table must be unique. Column name 'id' in table 'directus_extensions' is specified more than once.
2024-03-15T13:08:16.332882355Z     at RequestTokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/handler.js:287:21)
2024-03-15T13:08:16.332889155Z     at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
2024-03-15T13:08:16.332894455Z     at Readable.emit (node:events:517:28)
2024-03-15T13:08:16.332898455Z     at addChunk (node:internal/streams/readable:368:12)
2024-03-15T13:08:16.332902355Z     at readableAddChunk (node:internal/streams/readable:341:9)
2024-03-15T13:08:16.332907055Z     at Readable.push (node:internal/streams/readable:278:10)
2024-03-15T13:08:16.332910955Z     at next (node:internal/streams/from:98:31)
2024-03-15T13:08:16.332915455Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-03-15T13:08:16.332919855Z   code: 'EREQUEST',
2024-03-15T13:08:16.332923955Z   number: 2705,
2024-03-15T13:08:16.332927755Z   state: 4,
2024-03-15T13:08:16.332931455Z   class: 16,
2024-03-15T13:08:16.332935155Z   serverName: 'myserver',
2024-03-15T13:08:16.332938855Z   procName: '',
2024-03-15T13:08:16.332942555Z   lineNumber: 1
2024-03-15T13:08:16.332946155Z }
2024-03-15T13:12:28.277217421Z ConnectionError: Login failed for user 'admin'.
2024-03-15T13:12:28.277366721Z     at Login7TokenHandler.onErrorMessage (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/handler.js:187:19)
2024-03-15T13:12:28.277437322Z     at Readable.<anonymous> (/directus/node_modules/.pnpm/tedious@17.0.0/node_modules/tedious/lib/token/token-stream-parser.js:18:33)
2024-03-15T13:12:28.277450222Z     at Readable.emit (node:events:517:28)
2024-03-15T13:12:28.277455522Z     at addChunk (node:internal/streams/readable:368:12)
2024-03-15T13:12:28.277460422Z     at readableAddChunk (node:internal/streams/readable:341:9)
2024-03-15T13:12:28.277465322Z     at Readable.push (node:internal/streams/readable:278:10)
2024-03-15T13:12:28.277470222Z     at next (node:internal/streams/from:98:31)
2024-03-15T13:12:28.277475122Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-03-15T13:12:28.277480122Z   code: 'ELOGIN'

### To Reproduce

Spin up a directus container for the first time in an Azure App Service
Fyi: I'm starting from an empty database. 

### Directus Version

10.10.4 (trying to downgrade to see if that one doesn't cause the issue)

### Hosting Strategy

Self-Hosted (Custom)
Azure App Service (Docker Image)
MSSQL database

**Comment by michas90** [comment] 2024-03-18 13:04
I have the same issue.

**Comment by rijkvanzanten** [comment] 2024-03-18 16:47
Duplicate of https://github.com/directus/directus/issues/21828

**Closed by rijkvanzanten** 2024-03-18 16:47 UTC

**Comment by woeterman94** [comment] 2024-03-18 17:32
What do you mean by not planned? Any workarounds for this issue?

**Comment by rijkvanzanten** [comment] 2024-03-18 17:55
@woeterman94 The issue was already reported previously in https://github.com/directus/directus/issues/21828, we only keep 1 open issue for each "todo" in the project, otherwise things quickly get lost / out of control 🙂 Doesn't mean the issue doesn't exist or won't get fixed, just means we're tracking the details and status over in the original bug report https://github.com/directus/directus/issues/21828
