### ISSUE TITLE
[OAUTH2][OPENIDC] Call End-Session-Endpoint from IAM-Server

### ISSUE THREAD

**Issue by alexanderwolz** [directus/directus#12127] opened 2022-03-12 17:16 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I use openid-connect authentication and have disabled internal default provider (AUTH_DISABLE_DEFAULT: "true") so all logins will be handled by my IAM server, which in fact works quite well.

I can successfully log in with my user but on logout, the IAM server's end session endpoint is not called, so the SSO cookie is not terminated . This leads to straight logging in the current user from the IAM cookie again and there is no chance to switch the user. If I call the logout endpoint directly, IAM server terminates the cookie and Directus triggers the SSO login page again. 

I use Keycloak 17 as IAM server and set the AUTH_XXX_ISSUER_URL, which points to the openidc-well-known configuration. That config in fact also provides the end-session-endpoint.
E.g. ```"end_session_endpoint":"https://myauthserver.com/realms/myrealm/protocol/openid-connect/logout"```

Shouldn't that endpoint be called if users click the "logout" button in the directus app?

### To Reproduce

1. Install Keycloak and add a client with protocol "openid-connect" 
2. Set Keycloak env configs in docker-compose (use ```openid``` driver)
3. login at Directus app using "Login with Keycloak"
4. I change that users group to admin in the database, so I can access the Directus app
5. Logout from Directus app.
6. Login again (no redirect to IAM server login screen, redirects straight into directus app with previously logged in user)

-> Same user logged in again

that's my config:
```      AUTH_DISABLE_DEFAULT: "true"
      AUTH_PROVIDERS: keycloak
      AUTH_KEYCLOAK_DRIVER: openid
      AUTH_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      AUTH_KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      AUTH_KEYCLOAK_ISSUER_URL: ${KEYCLOAK_CONFIG_URL}
      AUTH_KEYCLOAK_REQUIRE_VERIFIED_EMAIL: "true"
      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "email"
      AUTH_KEYCLOAK_SCOPE: "openid email"
```

Logs from "logout":
```
17:05:39 ✨ request completed POST 204 /auth/logout 11ms
17:05:39 ✨ request completed GET 200 /server/info?limit=-1 10ms
17:05:39 ✨ request completed GET 200 /auth 7ms
```

### Errors Shown

There are no errors

### What version of Directus are you using?

directus/directus:9.6.0

### What version of Node.js are you using?

16.14.0 (provided by docker image directus/directus:9.6.0)

### What database are you using?

mariadb:10.7.1

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by aidenfoxx** [comment] 2022-03-12 19:31
This is by design. It's more convenient for most users to be automatically logged in after this first time they approve Directus as an authenticated platform. If you want to force users to select their profile when logging in with an oauth/openid provider you can simply define `AUTH_<PROVIDER>_PARAMS__PROMPT="consent"`. Hopefully this solves your issue?

**Comment by alexanderwolz** [comment] 2022-03-12 19:44
I have added ```AUTH_KEYCLOAK_PARAMS__PROMPT: "consent"``` to my docker-compose config but I don't see any change in behavior.
Maybe It would be considerable to provide some kind of flag such as "AUTH_PROVIDER_LOGOUT_SESSION=true" that actively triggers session logout if desired?

**Comment by aidenfoxx** [comment] 2022-03-12 19:49
The config option should force the user to select their account when logging in via keycloak. You can also try "login" or "select_account". See section "3.1.2.1.  Authentication Request" under "prompt" https://openid.net/specs/openid-connect-core-1_0.html

If this is an acceptable alternative I would prefer it to implementing the "revoke" or "logout" endpoints to the logout process.

**Comment by alexanderwolz** [comment] 2022-03-12 20:14
Okay, I do see changes using ```AUTH_KEYCLOAK_PARAMS__PROMPT: "login"``` (other values did not trigger anything), but it brings up a prompt every time I revisit the page, which is kind of annoying. As long as I have not logged out or my refresh token did not expire, I wish not to be prompted. A custom flag to trigger end-session-endpoint would be nice though.

**Comment by aidenfoxx** [comment] 2022-03-12 21:53
@alexanderwolz How do you mean it brings up a prompt every time you revisit the page? As long as your Directus session it valid you shouldn't be asked to re-authenticate via keycloak unless you logout, or as you say, if your "refresh_token" expires or in invalidated.

**Comment by aidenfoxx** [comment] 2022-03-12 21:58
It is possible your "refresh_token" just has a short lifetime. By default keycloak will use the smallest of the following values as the token lifetime: "SSO Session Idle", "Client Session Idle", "SSO Session Max" and "Client Session Max". So make sure you have appropriate values for those.

**Comment by alexanderwolz** [comment] 2022-03-13 07:21
Hi @aidenfoxx 
I indeed have very short expiration times but I testet it all within the time frame. It's hard to explain by text, so I did some screenshots to show the user journey (blacked out staging info of course) - this is what I mean by "revisit" the page:


### Step 1: login to directus with keycloak (IAM server)
<img width="1377" alt="Step1" src="https://user-images.githubusercontent.com/84812593/158049312-3ec67019-5ad9-4a33-a964-3951ce279d49.png">

### Step 2: Authenticate at IAM server
<img width="1377" alt="Step2" src="https://user-images.githubusercontent.com/84812593/158049314-e59ef3fd-2001-4f2f-b8b5-0c8fcf22f95b.png">

### Step 3: Use Directus App as intendenden
Here you can refresh, load settings, content, etc. and no OAuth2 flow is triggerd. Works as intended.
<img width="1377" alt="Step3" src="https://user-images.githubusercontent.com/84812593/158049319-8a377b56-47ad-4085-ae2d-3db64a4093c9.png">

### Step 4: Switch to any other page e.g. google
<img width="1377" alt="Step4" src="https://user-images.githubusercontent.com/84812593/158049320-e90a1ee8-deb7-4ef0-8882-6ce75dd7bb02.png">

### Step 5: Head back to directus
 User has NOT logged out but only changed page, Welcome/Login page is shown.
<img width="1377" alt="Step5" src="https://user-images.githubusercontent.com/84812593/158049322-b0e321d4-408b-407b-9f28-744782d380a6.png">

### Step 6: Reauthenticate
Reauthentication flow is triggered due to ```AUTH_KEYCLOAK_PARAMS__PROMPT: "login"```
<img width="1377" alt="Step6" src="https://user-images.githubusercontent.com/84812593/158049324-25987d47-6067-4066-8b1a-e8ab51e9bfbd.png">

### Step 7: Back at Directus app again
<img width="1377" alt="Step7" src="https://user-images.githubusercontent.com/84812593/158049326-e77222ff-e24a-46a0-a2db-a43f4e2e64b8.png">

**Comment by aidenfoxx** [comment] 2022-03-13 07:29
That doesn't seem to be a bug with the oauth implementation, but an issue with Directus sessions. After you log in via Keycloak the session should be handled by Directus there after, assuming keyclock is giving the refresh token a reasonable lifetime. 🤔

**Comment by alexanderwolz** [comment] 2022-03-13 07:37
I have the feeling that the oauth/openidc flow works as designed, but the session handling gets mixed up.

For our user journey I would wish for a customizable way to let the logout trigger a session termination. At least other web applications that we host provide this feature or are built-in (example: Portainer terminates the session, Jenkins OIDC plugin has an option to terminate if desired)

Wouldn't that be a call for a feature request? Let's say something like ```AUTH_PROVIDER_END_SESSION_ON_LOGOUT: "true"```

**Comment by aidenfoxx** [comment] 2022-03-13 07:44
Terminating the oauth session wouldn't really provide and benefit in this situation as sessions are handled almost completely by Directus (with only a check in the oauth flows to verify the authentication hasn't been revoked). Directus should already terminate its own session on logout which should have the same effect. Unless I'm missing something?

But I agree that there is likely some issues with the session handling looking at the behaviour you describe. I know there have been similar issues in the past.

**Comment by aidenfoxx** [comment] 2022-03-13 07:48
If oauth session termination is something you want as a feature because you believe it would bring value, I'd encourage you to start a discussion post outlining why it would be useful. 😄

I think we should reserve this ticket for identifying and fixing the session handling issue on returning to Directus.

**Comment by alexanderwolz** [comment] 2022-03-13 08:20
> Directus should already terminate its own session on logout which should have the same effect. Unless I'm missing something?

But if the openidc session is terminated, your internal session would check that revocation and trigger the login web flow of the IAM server again, right? (Then I could login as another user without that prompt config).

If I compare that logout-flow with the one e.g at GitHub here, it does not log me in again after sign-out but triggers the login web flow again. So a session termination makes complete sense to me :)

**Comment by aidenfoxx** [comment] 2022-03-13 08:55
Your are correct. But adding revocation on logout would add additional code complexity and require an addition config variable (`AUTH_PROVIDER_END_SESSION_ON_LOGOUT="true"`) when you could achieve the same result with   `AUTH_KEYCLOAK_PARAMS__PROMPT="login"`. The result being that the user always has to login via the keycloak page.

Obviously what I'm describing assumes the bug you're experiencing with your Directus session disappearing is fixed!

I think it would be more valuable to clarify in the docs how to configure this via the "promp" param. But we can discuss it more in the new thread. I'm probably missing something. 😄

**Comment by alexanderwolz** [comment] 2022-03-13 09:40
I started discussion https://github.com/directus/directus/discussions/12132. 
Happy to get any thoughts about that :)

And yes, the params flags should be added to the documentation :)

**Comment by alexanderwolz** [comment] 2022-03-16 08:37
My setup runs on a containerized NGINX reverse-proxy (single node setup) that redirects straight to the directus container on port 8055 such as this:

```
  location /path {	
	  return 301 https://$host/api/;
  }

  location ~* ^/path(/.*)$ {
    set                   $upstream directus:8055;
    proxy_pass            http://$upstream$1$is_args$args;
  }
  ```
 
 Well I can see that the issue seems to be dependent to the ```AUTH_KEYCLOAK_PARAMS__PROMPT: "login"``` flag. The Directus App itself has a cookie:

<img width="1377" alt="Bildschirmfoto 2022-03-16 um 09 31 29" src="https://user-images.githubusercontent.com/84812593/158549304-b7becbfe-ce99-4e6f-bc25-e6edcf9c79f4.png">

**Comment by aidenfoxx** [comment] 2022-03-16 16:59
If the issue is coming only happening when using `AUTH_KEYCLOAK_PARAMS__PROMPT: "login"` then the problem almost certainly isn't on the Directus side. The only way that flag could affect Directus behavior is if Keycloak returns a `refresh_token` that expires almost immediately causing, the auth refresh call to fail with a "grant_error" (you can verify this in your logs if you enable trace logging).

If the same problem happens on hard refresh after logging in with `AUTH_KEYCLOAK_PARAMS__PROMPT: "login"` (`CTRL + SHIFT + R`) then we're probably getting a dud token from Keycloak.

**Comment by aidenfoxx** [comment] 2022-03-16 18:11
Okay, so I've installed Keycloak locally and configured Directus to work against it using `AUTH_KEYCLOAK_PARAMS__PROMPT: "login"` and I experience no issues. This makes me believe you have a configuration issue on your side? I'm using the default openid configuration with "Access Type" "confidential". My Directus configuration is:

```
AUTH_KEYCLOAK_DRIVER="openid"
AUTH_KEYCLOAK_ISSUER_URL="http://localhost:8080/realms/Directus/.well-known/openid-configuration"
AUTH_KEYCLOAK_CLIENT_ID="directus-test"
AUTH_KEYCLOAK_CLIENT_SECRET="8e...oZ"
AUTH_KEYCLOAK_PARAMS__PROMPT="login"
AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION="true"
AUTH_KEYCLOAK_DEFAULT_ROLE_ID="d6...ad"
```

I am able to leave Directus, browse elsewhere and return, and my session is still valid.

**Comment by alexanderwolz** [comment] 2022-03-21 08:01
Hi @aidenfoxx 
Did you try your setup with MacOS and Safari?
I experience a different behavior when using Safari vs Google Chrome on macOS 12.3:

<img width="384" alt="Bildschirmfoto 2022-03-21 um 08 52 41" src="https://user-images.githubusercontent.com/84812593/159222220-58346b9f-e6c6-4f1c-8c5f-290b8d654d9d.png">

Safari somehow loses the cookie sporadically, where Chrome seems to recognize it after all location changes.
I also checked my reverse-proxy and don't see any issue there.

I can also see that Safari sometimes is able to show me the "sign-In" form but very often loses the OAUTH info and redirects to the login-flow - even though the user did not sign out.

Do you have any idea?

**Comment by aidenfoxx** [comment] 2022-03-21 11:10
I did not test Safari, though through prior experience I know it's notoriously finicky about cookie handling. But I just want to clarify that Safari won't be losing oauth information, but the Directus session, since post-login we hand off session handling to Directus.

It would be really good for debugging if you could try and reproduce this issue with the regular username/password flow since then we'll know it's an issue with the core session handling?

**Comment by rijkvanzanten** [comment] 2022-04-07 21:23
> Okay, so I've installed Keycloak locally and configured Directus to work against it using `AUTH_KEYCLOAK_PARAMS__PROMPT: "login"` and I experienced no issues. This makes me believe you have a configuration issue on your side?

Same here.. Haven't been able to reproduce this locally 🤔 (on macOS with Safari)


I'll close this for now, but as always down to keep discussing / debugging this in the thread below 🙂

**Closed by rijkvanzanten** 2022-04-07 21:23 UTC
Labels: Needs More Info
