### ISSUE TITLE
Login toggle gets pushed off the screen

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#21178] opened 2024-01-24 12:41 UTC
### Describe the Improvement

When enabling LDAP a new toggle appears on the login page. This toggle however gets pushed partly off the screen when using a long translated title.

In Firefox:
![image](https://github.com/directus/directus/assets/9389634/ab542ce9-dfe6-45c7-b57d-3eb9f68aa500)

Chrome seems to handle it better although it does it does still look somewhat funky:
![image](https://github.com/directus/directus/assets/9389634/11e5d315-7a71-4bb4-abf0-76383b933e47)

Looking at the screenshots perhaps the Login button should be limited in its max width too.

**Comment by w-augustin** [comment] 2024-01-31 16:53
Hey, I can work on this issue

**Comment by w-augustin** [comment] 2024-02-08 16:11
Hey where is this issue in the src file?

**Comment by rijkvanzanten** [comment] 2024-02-08 22:10
I think it'll be `/app/src/routes/login/components/login-form/login-form.vue`

**Comment by u5r0** [comment] 2024-03-16 09:09
I couldn't reproduce this, seems to be fixed :white_check_mark:

**Comment by Julias0** [comment] 2024-09-23 02:11
I can take this up! Can you assign this to me

**Comment by Julias0** [comment] 2024-09-24 10:28
I am hitting a error during local setup

```
Lockfile is up to date, resolution step is skipped
Packages: +2286
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 2286, reused 2282, downloaded 0, added 0, done
node_modules/.pnpm/sharp@0.33.5/node_modules/sharp: Running install script...
node_modules/.pnpm/isolated-vm@4.7.2/node_modules/isolated-vm: Running install script, failed in 1.7s
.../node_modules/isolated-vm install$ prebuild-install || (node-gyp rebuild --release -j max && node-gyp clean)
│ prebuild-install warn install No prebuilt binaries found (target=18.20.4 runtime=node arch=arm64 libc= platform=dar…
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@8.4.1
│ gyp info using node@18.20.4 | darwin | arm64
│ gyp info find Python using Python version 3.12.4 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
│ gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
│ gyp info spawn args [
│ gyp info spawn args   '/Users/aiyushdhar/projects/directus/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/…
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/aiyushdhar/projects/directus/node_modules/.pnpm/isolated-vm@4.7.2/node_modules/isolat…
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/aiyushdhar/projects/directus/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/…
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/aiyushdhar/Library/Caches/node-gyp/18.20.4/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/aiyushdhar/Library/Caches/node-gyp/18.20.4',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/aiyushdhar/projects/directus/node_modules/.pnpm/node-gyp@8.4.1/node_mo…
│ gyp info spawn args   '-Dnode_lib_file=/Users/aiyushdhar/Library/Caches/node-gyp/18.20.4/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/aiyushdhar/projects/directus/node_modules/.pnpm/isolated-vm@4.7.2/n…
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ Traceback (most recent call last):
│   File "/Users/aiyushdhar/projects/directus/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/gyp_main.py…
│     import gyp  # noqa: E402
│     ^^^^^^^^^^
│   File "/Users/aiyushdhar/projects/directus/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/_…
│     import gyp.input
│   File "/Users/aiyushdhar/projects/directus/node_modules/.pnpm/node-gyp@8.4.1/node_modules/node-gyp/gyp/pylib/gyp/i…
│     from distutils.version import StrictVersion
│ ModuleNotFoundError: No module named 'distutils'
│ gyp ERR! configure error 
│ gyp ERR! stack Error: `gyp` failed with exit code: 1
│ gyp ERR! stack     at ChildProcess.onCpExit (/Users/aiyushdhar/projects/directus/node_modules/.pnpm/node-gyp@8.4.1/…
│ gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
│ gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
│ gyp ERR! System Darwin 23.3.0
│ gyp ERR! command "/Users/aiyushdhar/.nvm/versions/node/v18.20.4/bin/node" "/Users/aiyushdhar/projects/directus/node…
│ gyp ERR! cwd /Users/aiyushdhar/projects/directus/node_modules/.pnpm/isolated-vm@4.7.2/node_modules/isolated-vm
│ gyp ERR! node -v v18.20.4
│ gyp ERR! node-gyp -v v8.4.1
│ gyp ERR! not ok 
└─ Failed in 1.7s at /Users/aiyushdhar/projects/directus/node_modules/.pnpm/isolated-vm@4.7.2/node_modules/isolated-vm
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by hanneskuettner** [comment] 2024-09-24 12:02
@Julias0 see https://stackoverflow.com/questions/77251296/distutils-not-found-when-running-npm-install for a potential solution. 

```sh
python3 -m pip install setuptools
```

or 

```sh
brew install python-setuptools
```

**Closed** 2024-10-14 09:55 UTC
Labels: Bug, ⭐️ Good First Issue
