### ISSUE TITLE
Directus 6.4RC1 being too opinionated about the schema for table primary keys

### ISSUE THREAD

**Issue by twoSeats** [directus/directus#1529] opened 2017-05-29 11:16 UTC
## Version Info
  - Directus version and branch: 6.4 RC1
  - PHP version: 7.1.4
  - MySQL version: 10.0.29-MariaDB
  - Web server: Caddy
  - OS name and version: Ubuntu 16.04.1

The following is regarding preexisting tables not created by directus:

## Expected Behavior
as happens in 6.3.6
If a table has an integer type id primary key column it is assigned a primary key interface by Directus without user intervention & no attempts to modify the column types & attributes of that column.

## Actual Behavior
Directus 6.4 RC1 appears to be very picky about what qualifies as a primary key compared to directus 6.3.6. Also doesn't automatically apply a Primary Key interface to table primary keys like directus 6.3.6 did.

in 6.4 RC1 if a table has an integer type primary key column it is not automatically assigned the primary key interface.
attempting to apply a primary key interface will result in an error if the integers in question are unsigned & the column in said table has relationships attached to it due to the fact that Directus attempts to modify the column being given the primary key interface to be signed & not auto-incrementing.

## Steps to Reproduce
 1. create database tables outside of Directus with id as unsigned integer & auto-incrementing primary key
 2. choose to manage resultant table in Directus

### Case 1, id column is a unsigned auto-incrementing integer that has relationships
assigning a primary key interface fails because the column cannot be modified due to the relationship constraints.

![schema-unchanged-6 4rc1](https://cloud.githubusercontent.com/assets/536306/26547554/d520cc96-446f-11e7-8eed-5b8fc68b0eed.jpeg)

### Case 2, id column is a unsigned auto-incrementing integer that doesn't have relationships.
assigning a primary key interface will succeed but the column will be modified with the type being made a signed integer and the auto-incrementing attribute removed.
 
![schema-changed-6 4rc1](https://cloud.githubusercontent.com/assets/536306/26547555/d5dfbeee-446f-11e7-8e35-5a09ebfeef5a.jpeg)

**Comment by WellingGuzman** [comment] 2017-05-29 17:31
Hey @twoSeats,

Thanks for the well explained ticket, I will be working on this today.

What should happen here is that the primary key interface should be set by default when you create the table yourself, and be able to change any numeric field to primary key interface.

Although upgrading the database on automatically create the desired interfaces for the primary key.

**Comment by WellingGuzman** [comment] 2017-05-29 22:19
Hey @twoSeats,

In the first case, how is the relationship of the table looks like? do you have an schema that we can use to reproduce the issue?

**Comment by WellingGuzman** [comment] 2017-05-30 01:09
Hey @twoSeats, can you share what constraints does your primary have?

the second case should be fixed now.

**Comment by twoSeats** [comment] 2017-05-30 16:15
Hi @WellingGuzman; apologies, I was offline for a bit. I'll get you that info soon as I have a chance.

**Comment by WellingGuzman** [comment] 2017-05-30 17:14
@twoSeats no a problem, let us know when you got the chance

**Comment by twoSeats** [comment] 2017-05-31 22:07
@WellingGuzman here we go, the database I was using for my tests is in this gist: https://gist.github.com/twoSeats/3c50ec3a20b9fc8ef720466f1036cf40

It was just to test the error i was getting; otherwise all the primary keys should be unsigned & auto incrementing. You'll see that some tables are and some are not; this was intentional for my tests.

**Comment by WellingGuzman** [comment] 2017-06-01 03:21
Hey @twoSeats,

did you try to see if the error keep showing up after these commits: https://github.com/directus/directus/commit/d57db3d91d3b225c26aa18a0d809071570376400 and  https://github.com/directus/directus/commit/325be196600d190b711e968f5d6d2fff9cc732d4?

I tried your schema, and changing the primary key numeric interface to primary key and it worked without errors.

Let me know how it goes.

**Comment by twoSeats** [comment] 2017-06-02 11:39
@WellingGuzman I've just tried it and things look great now! awesome work, thanks!

**Closed** 2017-06-02 13:28 UTC
Labels: 3. Major, Beta, UI
