### ISSUE TITLE
Cannot add image using Rich content editor

### ISSUE THREAD

**Issue by andriusign** [directus/directus#4508] opened 2021-03-12 18:53 UTC
**Steps to reproduce**:
Create any item with Richcontent editor. Try to add image.
Insert/Edit Image dialog opens, click upload icon on the right. Select file dialog opens under then Insert/Edit Image dialog.
Then close Insert/Edit Image dialog so that actual file select dialog is visible. Try to upload or add an image from gallery and save.

**Actual**: After dialog closes content stays empty, no image is added.
**Expected**: image is added to Richcontent editor.

![1](https://user-images.githubusercontent.com/14263959/110985292-f6809900-8374-11eb-9e59-f3ad3523c8a4.png)
![2](https://user-images.githubusercontent.com/14263959/110985297-f84a5c80-8374-11eb-8774-abced63bf826.png)
![3](https://user-images.githubusercontent.com/14263959/110985303-faacb680-8374-11eb-8b84-2b359d418f90.png)
![4](https://user-images.githubusercontent.com/14263959/110985304-fb454d00-8374-11eb-8bf1-4249a0081cb2.png)

---

### Project details
Directus Version: 9.0.0-rc.49
Environment: production
OS: Linux 4.15.0-29-generic
Node: 14.16.0

**Comment by rijkvanzanten** [comment] 2021-03-12 19:09
> Then close Insert/Edit Image dialog so that actual file select dialog is visible.

The moment that dialog is closed, TinyMCE stops listening for the file event, so this is to be expected..

The behind-the-modal problem is a duplicate of https://github.com/directus/directus/issues/4354

**Closed by rijkvanzanten** 2021-03-12 19:09 UTC
