### ISSUE TITLE
`module_bar` in settings doesn't really take an array.

### ISSUE THREAD

**Issue by hamzace** [directus/directus#22816] opened 2024-06-21 10:51 UTC
### Describe the Bug

Hey everyone,

I'm trying to enable/disable modules using the SDK, according to the [doc](https://docs.directus.io/reference/system/settings.html)  I should fill up the `module_bar` field using an array of `{ type, id, enabled }` objects. However this doesn't compile.

When looking at the code, I see that it is supposed to take a `"json" | null`

I'm not sure how I can perform this, any lead is appreciated.

### To Reproduce

When updating the settings using the SDK, I update the module_bar this way:

```
const modules = [
    { enabled: true, id: `guide-form`, type: `module` },
    { enabled: true, id: `users`, type: `module` },
  ];

await client.request(
    updateSettings({
      module_bar: modules,
    }),
  );
```

This doesn't compile with `Type '{ enabled: boolean; id: string; type: string; }[]' is not assignable to type '"json"'.`

### Directus Version

16.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ComfortablyCoding** [comment] 2024-07-04 14:38
Thanks for opening this issue! However this is a duplicate of an existing issue #21599, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #21599 for future updates.

**Closed by ComfortablyCoding** 2024-07-04 14:38 UTC
Labels: :cake: Bug, :file_folder: SDK
