### ISSUE TITLE
Adding a new M2O relation to a data model removes already existing O2M

### ISSUE THREAD

**Issue by sagerio** [directus/directus#7011] opened 2021-07-27 20:40 UTC
### Describe the Bug

I've added a new M2O relation (simple "created by" to a user data model") via "Create field -> M2O relation" to a data model.
This works, but immediately after the already existing O2M relation in this data model is cleared.
This is reproducible, happens every time I try this. 

### To Reproduce

Have a data model with an existing O2M relation with data.
Try to add a new M2O relation to this data model.

### What version of Directus are you using?

9.0.0-rc.86

### What version of Node.js are you using?

14.15.1

### What database are you using?

SQLite 3.31.1

### What browser are you using?

Microsoft Edge 92.0.902.55

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Directus on NAS, Client locally

**Comment by rijkvanzanten** [comment] 2021-07-27 20:49
What was the original O2M field? Did you use the same collection/field names? Did you try adding a M2O on top of an existing O2M?

**Comment by sagerio** [comment] 2021-07-27 20:56
The original O2M field is still there.
Of course I used another name.
Yes, I tried adding a M2O on top of an existing O2M, but both have different "targets".

**At this moment I realise that there is also an M2M field in this model which is pointing to the same model the M2O should do, I think this is the problem?**

**Comment by rijkvanzanten** [comment] 2021-07-27 20:57
> Of course I used another name.

Less obvious than you might think! 😄 

What are the names of the collections / fields? Eg what does your schema look like? 

> At this moment I realise that there is also an M2M field in this model which is pointing to the same model the M2O should do, I think this is the problem?

Could be! Hard to tell with the available informaiton

**Comment by sagerio** [comment] 2021-07-27 21:02
If it's possible to export the schema as json or something, I can post it?

**Comment by rijkvanzanten** [comment] 2021-07-27 21:21
Most importantly is just the naming of all these, as I believe that's where the issue lies, so a step-by-step:

1) Add collection `articles`
2) Add collection `authors`
3) Add o2m-field `articles` on `author` where `articles.author`->`authors.id`
4) Add m2o-field `author` on `articles` with relation `articles.author` -> `authors.id`
5) o2m field disappeared 🐛 💥 

Would be ideal.

Alternatively, a full DB dump is also very welcome, though I'd still need to know what the offending column name was 🙂

**Comment by sagerio** [comment] 2021-07-28 06:06
I've removed the mass of the data and provided the db.sqlite file here: https:/static.sager.io/db.minimal.sqlite.gz
What I wanted to do is adding a M2O relation to "biergaerten" which is pointing to "users".
Hope this helps

**Comment by rijkvanzanten** [comment] 2021-07-28 15:11
[db.minimal.sqlite.gz](https://github.com/directus/directus/files/6894158/db.minimal.sqlite.gz)

reuploading here for archiving reasons

**Comment by rijkvanzanten** [comment] 2021-08-03 23:05
@sagerio What is the name of the field you're adding, and what is the name of the field that disappeared?

I just added a new `biergaerten.user <- users.id` field without problems.

I'll close this for now, as it sounds like it's a configuration issue, and not a bug in Directus per se. We can reopen later if needed

**Closed by rijkvanzanten** 2021-08-03 23:05 UTC
Labels: Needs More Info
