### ISSUE TITLE
Images manual sort bugged

### ISSUE THREAD

**Issue by vinksz** [directus/directus#4380] opened 2021-03-04 11:20 UTC
When you drag you can manually sort, but when u click it... and then try to short it, it actually removes images from the list, leaving only 1 image... (maybe somekind of conflict with Sort option enabled when you create a collection? )
![toggle](https://user-images.githubusercontent.com/73794103/109955982-c89fb280-7ceb-11eb-975b-17ba7e130bc9.png)

---

### Project details
Directus Version: 9.0.0-rc.44
Environment: production
OS: Linux 5.4.0-66-generic
Node: 14.16.0

**Comment by Nitwel** [comment] 2021-03-29 12:24
> but when u click it... and then try to short it, it actually removes images from the list

What do you mean by this?

Could you provide steps on how to reproduce this?

**Comment by rijkvanzanten** [comment] 2021-03-29 15:57
@Nitwel I think they're talking about editing the file first (by clicking on a row and making edits), and _then_ sorting that same item 🤔

**Comment by domdus0** [comment] 2021-04-08 10:17
Went into the same problem - (multiple) files field with sort.

1. Create a collection with files field
2. Create/Edit a collection item
3. Upload/Select multiple files and you'll get this:
![image](https://user-images.githubusercontent.com/73621574/114002353-12d10200-985d-11eb-9692-cd1700e5fe21.png)
4. Now before saving the item - drag/sort e.g. "Image 4" to the top position and it will show:
![image](https://user-images.githubusercontent.com/73621574/114002852-8bd05980-985d-11eb-8c08-889b55c41340.png)

However it's a UI (sort) issue at this point. When saving the item, the files field keeps the 4 different images - not 4x "Image 4", which is not wanted anyway.
5. Save item and open it again - All 4 files where added and are shown with probably initial sorting:
![image](https://user-images.githubusercontent.com/73621574/114004091-993a1380-985e-11eb-9071-981060aebf46.png)

**Comment by domdus0** [comment] 2021-04-08 11:54
Maybe I can add a part 2 here related to the sort option for the files field - the setup is not consistent for me. On one project it just worked (started on rc.39?), on another project I just don't get sorting to work. (v9.0.0-rc.55)

1. Create a collection
2. Add multiple files field called "images" + sort field:
![image](https://user-images.githubusercontent.com/73621574/114018932-1751e680-986e-11eb-999a-9638b128fbcb.png)
3. Finish the setup - "images" files field is created and junction collection exists including sort:
![image](https://user-images.githubusercontent.com/73621574/114019191-63049000-986e-11eb-8a09-a4fe93bb916a.png)
Now check the "images" field config again. I can already see that the sort field hasn't been select for some reason.
![image](https://user-images.githubusercontent.com/73621574/114019586-e3c38c00-986e-11eb-83aa-6b38146ff7ca.png)
It recommends me the sort field, but even after clicking it the input field it empty. (When I save I can see the "sort" value for a split second which is weird)
![image](https://user-images.githubusercontent.com/73621574/114019946-4e74c780-986f-11eb-8db7-8537655619e9.png)
When it is in this state, I can repeat the process as much as I want - it does not select the sort field.

This is what it should look like (another project where it just works):
![image](https://user-images.githubusercontent.com/73621574/114020633-17eb7c80-9870-11eb-948e-52fa92a56d3e.png)

Without the sort field being correctly configured, the actual sorting of files sets obviously can not work. I will try to test on older rc

**Comment by the-yamiteru** [comment] 2021-05-02 14:45
If I try to sort images in a new and unsaved item their names change to the same name. It's just a UI bug.

**Comment by rijkvanzanten** [comment] 2021-05-03 14:02
Now that the files interface has been merged with the m2m, I'll close this as a duplicate of https://github.com/directus/directus/issues/3721

**Closed by rijkvanzanten** 2021-05-03 14:02 UTC
Labels: App, Bug, Needs More Info
