### ISSUE TITLE
Cannot read updated schema inside operation extension

### ISSUE THREAD

**Issue by AlaaL** [directus/directus#20332] opened 2023-11-06 06:29 UTC
### Describe the Bug

Hi, I am creating a custom operation where i create a new collections in it using the collection service, then i want to create a relation between the two collections using the relation service, but when I am creating the relations I get an error that the schema doesn't contain the newly created collections, so i thought i would fetch the new schema using the getSchema function 

```
export default {
    id: 'operation-create-collection',
    handler:  async ({ json }, { services, database, getSchema, accountability }) => {
    const schema = await getSchema();

    -- create collections,
   -- fetch new schema 
      const newSchema = await getSchema();
   -- then create RelationService from newSchema
  const relations_service  = new RelationsService({ schema: newSchema , accountability });
```

the code is just an example of what i am doing.
but it returns the old schema not the updated schema
I also tried this and did not work

`const updatedSchema = await getSchema({bypassCache: true}); `

I even tried using the UtilsService to clear cache 
```

    utils_service.clearCache();

    const newSchema = await getSchema();

    console.log(newSchema);
    
    const relations_service  = new RelationsService({ schema: newSchema, accountability });
    
```
and still the newSchema doesn't contain the new collection

### To Reproduce

1- Create custom operation extension
2- Create instance of CollectionService
3- Create a new collection using createOne function from collection service.
4- Create a second collection using createOne function from collection service.
5- Create instance of RelationService.
6- Create new relation between the two collections

you get an error the collections does not exists.

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2023-11-06 09:48
I was able to reproduce this if an outdated schema is passed to `RelationsService` (which is expected), but once I made sure to re-fetch it _after_ the collections were created, it works without any issue so I'll proceed to close this for now.

Possibilities that might be the issue in your scenario:

- it seems like you didn't await `utils_service.clearCache();`, which is a promise, so it might just be the cache wasn't cleared yet when your relationsService tried to create the relation.
- The accountability may not have sufficient permissions. In my example below, I intentionally omitted it so that the `CollectionsService` and `RelationsService` has elevated permissions (eg. as the system, not as any user/role). I recommend omitting it first as a trial run to rule out any accountability related problems, then you can add it back to suit your needs afterwards.

## Example Custom Operation

Here's the example custom operation that I've tried. I used a webhook Flow, passed `$trigger.body.name` to the custom operation, and it works from on my end.

### Screenshot of the flow

![](https://github.com/directus/directus/assets/42867097/34a0cc4e-e365-4644-8479-5e2223133766)

### `app.js`

```js
export default {
	id: 'my-operation',
	name: 'My Operation',
	icon: 'box',
	description: 'Automatically generate 2 collections with a relation between them',
	overview: ({ name }) => [
		{
			label: 'Name',
			text: name,
		},
	],
	options: [
		{
			field: 'name',
			name: 'Name',
			type: 'string',
			meta: {
				width: 'full',
				interface: 'input',
				options: {
					dbSafe: true,
					font: 'monospace',
				},
			},
		},
	],
};
```

### `api.js`

(I've inlined the `await getSchema` as a simplification, but feel free to separate it out like you did)

```js
export default {
	id: 'my-operation',
	handler: async ({ name }, { services, database, getSchema }) => {
		const { CollectionsService, RelationsService } = services;

		if (!name) {
			throw new InvalidPayloadError({ reason: `"name" is required` });
		}

		const collectionsService = new CollectionsService({ schema: await getSchema({ database }) });

		const firstCollectionName = `${name}_a`;
		const secondCollectionName = `${name}_b`;

		const firstCollection = await collectionsService.createOne({
			collection: firstCollectionName,
			meta: { singleton: false },
			schema: {},
			fields: [
				// primary key
				{
					field: "id",
					type: "integer",
					meta: {
						hidden: true,
						readonly: true
					},
					schema: {
						is_primary_key: true,
						has_auto_increment: true
					}
				},
				// field for relation
				{
					field: secondCollectionName,
					type: 'integer',
					meta: {
						interface: "select-dropdown-m2o",
						special: ["m2o"]
					},
					schema: {}
				}
			]
		});
		const secondCollection = await collectionsService.createOne({
			collection: secondCollectionName,
			meta: { singleton: false },
			schema: {},
			fields: [
				// primary key
				{
					field: "id",
					type: "integer",
					meta: {
						hidden: true,
						readonly: true
					},
					schema: {
						is_primary_key: true,
						has_auto_increment: true
					}
				},
			]
		});

		// using `getSchema` again to make sure we get the updated schema
		const relationsService = new RelationsService({ schema: await getSchema({ database }) });

		await relationsService.createOne({
			collection: firstCollectionName,
			field: secondCollectionName,
			related_collection: secondCollectionName,
			meta: { on_delete: "SET NULL" }
		});

		// just as an example response, feel free to tweak this
		return { status: 'ok' };
	},
};
```

**Closed by azrikahar** 2023-11-06 09:48 UTC

**Comment by AlaaL** [comment] 2023-11-06 09:54
Thank you for the response and example, I am executing the flow as administrator so i don't think it's an accountability issue.
But from your example i see you pass the database to the getSchema and i don't could that be this issue ? i will give it a try anyway

**Comment by AlaaL** [comment] 2023-11-06 10:38
I tried many things and still stuck at the same issue, I am using Mysql and what i am trying to do exactly is to create a collection and it's related translation collection, i will post full code maybe there is something i am missing 

```
import Field from './fields/Field';

export default {
	id: 'operation-create-collection',
	handler:  async ({ json }, { services, database, getSchema, accountability }) => {

    const schema = await getSchema({database});    
    const kuic_request_id = json.data.keys[0];
   
    const {
      ItemsService, 
      CollectionsService, 
      RelationsService,
      UtilsService 
    } = services;

    const collection_service  = new CollectionsService({ schema, accountability });
    const utils_service  = new UtilsService ({ schema, accountability });
    const kuic_items_service  = new ItemsService('kuic_requests', { schema, accountability });
            
    const kuic_request = await kuic_items_service.readOne(kuic_request_id, 
      {
      fields: ['*', 'fields.*', 'fields.item.*'],
    });

    const {
      agent, // agent id
      name, // kuic name
      fields: kuic_request_fields // the kuic field "fields" (many to any)
    } = kuic_request

    const lowerCaseName = name.toLowerCase();
    
    // formatting the field object with its meta and type
    let collection_fields = [];

    for (let i in kuic_request_fields) {
      const item = kuic_request_fields[i];
      let fieldMeta  = Object.assign(new Field(item.collection), item.item);
  
      collection_fields.push(fieldMeta.getMeta());
    }

    const translationCollectionName = lowerCaseName + "_translations";

    await collection_service.createOne({
      collection: lowerCaseName,
      fields: [
        {
          field: 'id',
          type: 'integer',
          meta: {
            hidden: true,
            interface: 'numeric',
            readonly: true,
          },
          schema: {
            is_primary_key: true,
            has_auto_increment: true,
          },
        },
        {
          field: 'ikun',
          type: 'integer',
          meta: {
            hidden: false,
            interface: 'select-dropdown-m2o',
            readonly: false,
            singleton: false,
          },
          special: ["m2o"],
          options: {
            template: "{{ikun}}",
            enableSelect: false
          },
        },
        {
          field: 'translations',
          type: 'alias',
          meta: {
            interface: 'translations',
          },
          special: ["translations"],
          options: {
            defaultLanguage: "en",
            languageField: "name",
          },
        },
        ...collection_fields
      ],
      schema: {
        name: lowerCaseName,
        comment: null
      },
      meta: {
        collection: lowerCaseName,
        hidden: false,
        singleton: false, 
        sort_field: null,
        archive_field: null,
        group: 'Kuics',
      }, 
    });
  
    const transCollection = await collection_service.createOne({
      collection: translationCollectionName,
      fields: [
        {
          field: "id",
          type: "integer",
          schema: {
              has_auto_increment: true
          },
          meta: {
              hidden: true
          }
        },
        {
          field: lowerCaseName + "_id",
          type: "integer",
          schema: {
          },
          meta: {
              hidden: true
          }
        },
        {
          field: "languages_code",
          type: "string",
          schema: {
          },
          meta: {
              hidden: true
          }
        },
      ],
      meta: {
        hidden: true,
        icon: "import_export",
        collection: translationCollectionName,
      },
      schema: {
        name: translationCollectionName
      },
    });

    await utils_service.clearCache();

    const updatedSchema = await getSchema({database});

    console.log(updatedSchema);

    const relations_service  = new RelationsService ({ schema: updatedSchema, accountability });

    if (transCollection) {
      await relations_service.createOne({
        collection: translationCollectionName,
        field: "languages_code",
        related_collection: "languages",
        meta: {
            one_field: null,
            sort_field: null,
            one_deselect_action: "nullify",
            junction_field: lowerCaseName + "_id"
        },
        schema: {
            on_delete: "SET NULL"
        }
      });

      await relations_service.createOne({
        collection: translationCollectionName,
        field: lowerCaseName + "_id",
        related_collection: lowerCaseName,
        meta: {
            one_field: "translations",
            junction_field: "languages_code"
        },
        schema: {
            on_delete: "SET NULL"
        }
      });
  }
 
    let collection = await collection_service.readOne(lowerCaseName);
    
    return collection;
	},
};

```

And the error i get is
{
  "name": "DirectusError",
  "message": "Invalid payload. Collection \"col08_translations\" doesn't exist."
}

**Comment by azrikahar** [comment] 2023-11-06 12:44
That odd indeed. Couple of thoughts/questions:

- Would you be able to give my custom example a try? Just wondering it might be easier to rule out potential root causes since that example is slightly simpler with less "moving parts" 👍
- Can you try removing all the usage of `accountability` in your code (i.e. _not passing_ accountability) just as a test?
- Based on the hosting strategy `Self-Hosted (Custom)` in your bug report, would it be okay for you to describe it detail? Without sensitive info of course. Just particularly curious about whether there's multiple instances at play (eg. potentially out-of-sync schema), caching strategy used, `CACHE_` related environment variables and so on).

**Comment by AlaaL** [comment] 2023-11-06 18:07
Hi @azrikahar, 

- I will give your example a try for sure.
- I tried removing the accountability before when you posted and i got `You don't have permission to access these`, but i just remembered that i saw somewhere in your code base to pass accountability as system you pass an object with `{ admin: true}`  or something similar and it worked for me in another project not this, so i will try both.
- My hosting is still my localhost PC, windows 11 environment, MySQL database, I installed Directus using `create-directus-project` 
and these are my environment variables
```

####################################################################################################
#
# These values set environment variables which modify core settings of Directus.
#
# Values in square brackets are the default values.
#
# The following options are not all possible options. For more, see
# https://docs.directus.io/self-hosted/config-options/
#
####################################################################################################
####################################################################################################

### General

# IP or host the API listens on ["0.0.0.0"]
HOST="0.0.0.0"

# The port Directus will run on [8055]
PORT=8055

# The URL where your API can be reached on the web. It is also used for things like OAuth redirects,
# forgot-password emails, and logos that needs to be publicly available on the internet. ["/"]
# PUBLIC_URL="/"
PUBLIC_URL="http://localhost:8055"

# What level of detail to log. [info]
# "fatal", "error", "warn", "info", "debug", "trace", "silent"
# LOG_LEVEL="info"

# Render the logs human readable (pretty) or as JSON (raw), [pretty]
# "pretty", "raw"
# LOG_STYLE="pretty"

# Controls the maximum request body size. Accepts number of bytes, or human readable string ["1mb"]
# MAX_PAYLOAD_SIZE="1mb"

# Where to redirect to when navigating to /. Accepts a relative path, absolute URL, or false to disable ["./admin"]
# ROOT_REDIRECT="./admin"

# Whether or not to serve the Admin App under /admin. [true]
# SERVE_APP=true

# Whether or not to enable GraphQL Introspection [true]
# GRAPHQL_INTROSPECTION=true

# Limit the maximum amount of items that can get requested in one query.
# QUERY_LIMIT_DEFAULT=100
# QUERY_LIMIT_MAX=Infinity

# The maximum number of items for batch mutations when creating, updating and deleting. ["Infinity"]
# MAX_BATCH_MUTATION="Infinity"

# Shared Redis server for things like caching, rate limiting, container synchronization, etc
# REDIS="redis://@127.0.0.1:6379"

####################################################################################################
### Database

# All DB_* environment variables are passed to the connection configuration of a Knex instance.
# Based on your project's needs, you can extend the DB_* environment variables with any config
# you need to pass to the database instance.

DB_CLIENT="mysql"
DB_HOST="127.0.0.1"
DB_PORT="3306"
DB_DATABASE="directus2"
DB_USER="root"
DB_PASSWORD=""



# These match the databases defined in the docker-compose file in the root of this repo

## Postgres
# DB_CLIENT="pg"
# DB_HOST="localhost"
# DB_PORT=5432
# DB_DATABASE="directus"
# DB_USER="postgres"
# DB_PASSWORD="secret"

## CockroachDB
# DB_CLIENT="cockroachdb"
# DB_HOST="localhost"
# DB_PORT=26257
# DB_DATABASE="directus"
# DB_USER="root"
# DB_PASSWORD=""

## MySQL 8
# DB_CLIENT="mysql"
# DB_HOST="localhost"
# DB_PORT=3306
# DB_DATABASE="directus"
# DB_USER="root"
# DB_PASSWORD="secret"

## MariaDB
# DB_CLIENT="mysql"
# DB_HOST="localhost"
# DB_PORT=3306
# DB_DATABASE="directus"
# DB_USER="root"
# DB_PASSWORD="secret"

## MS SQL
# DB_CLIENT="mssql"
# DB_HOST="localhost"
# DB_PORT=1343
# DB_DATABASE="directus"
# DB_USER="sa"
# DB_PASSWORD="Test@123"

## OracleDB
# DB_CLIENT="oracledb"
# DB_CONNECT_STRING="localhost:1521/XE"
# DB_USER="secretsysuser"
# DB_PASSWORD="secretpassword"

## SQLite Example
# DB_CLIENT="sqlite3"
# DB_FILENAME="./data.db"

## MySQL 5.7
# DB_CLIENT="mysql"
# DB_HOST="localhost"
# DB_PORT=3306
# DB_DATABASE="directus"
# DB_USER="root"
# DB_PASSWORD="secret"

####################################################################################################
### Rate Limiting

# Whether or not to enable rate limiting on the API [false]
RATE_LIMITER_ENABLED=false

# Where to store the rate limiter counts [memory]
# memory, redis
RATE_LIMITER_STORE=memory

# The amount of allowed hits per duration [50]
RATE_LIMITER_POINTS=25

# The time window in seconds in which the hits are counted [1]
RATE_LIMITER_DURATION=1

####################################################################################################
### Caching

# Whether or not caching is enabled. [false]
CACHE_ENABLED=false

# How long the cache is persisted ["5m"]
# CACHE_TTL="30m"

# How to scope the cache data ["directus-cache"]
# CACHE_NAMESPACE="directus-cache"

# Automatically purge the cache on create, update, and delete actions. [false]
# CACHE_AUTO_PURGE=true

# List of collections that prevent cache purging when `CACHE_AUTO_PURGE` is enabled. ["directus_activity,directus_presets"]
# CACHE_AUTO_PURGE_IGNORE_LIST="directus_activity,directus_presets"

# memory | redis
CACHE_STORE=memory

# How long assets will be cached for in the browser. Sets the max-age value of the Cache-Control header ["30d"]
ASSETS_CACHE_TTL="30d"

####################################################################################################
### File Storage

# A CSV of storage locations (eg: local,digitalocean,amazon) to use. You can use any names you'd like for these keys ["local"]
STORAGE_LOCATIONS="local"
STORAGE_LOCAL_DRIVER="local"
STORAGE_LOCAL_ROOT="./uploads"

## S3 Example (location name: DigitalOcean)
# STORAGE_DIGITALOCEAN_DRIVER="s3"
# STORAGE_DIGITALOCEAN_KEY="abcdef"
# STORAGE_DIGITALOCEAN_SECRET="ghijkl"
# STORAGE_DIGITALOCEAN_ENDPOINT="https://ams3.digitaloceanspaces.com"
# STORAGE_DIGITALOCEAN_BUCKET="my-files"
# STORAGE_DIGITALOCEAN_REGION="ams3"

## Google Cloud Storage Example (location name: Google)
# STORAGE_GOOGLE_DRIVER="gcs"
# STORAGE_GOOGLE_KEY_FILENAME="abcdef"
# STORAGE_GOOGLE_BUCKET="my-files"


## A comma-separated list of metadata keys to collect during file upload. Use * for all
# Extracting all metadata might cause memory issues when the file has an unusually large set of metadata
# [ifd0.Make,ifd0.Model,exif.FNumber,exif.ExposureTime,exif.FocalLength,exif.ISO]
# FILE_METADATA_ALLOW_LIST=

####################################################################################################
### Security

KEY="dbbffdef-06c9-4c8f-80e9-bcf2da9c16e9"
SECRET="G6a7QAkdCbXWTyHqlT41pitpQ3Vz_F9r"


# Unique identifier for the project
# KEY="xxxxxxx-xxxxxx-xxxxxxxx-xxxxxxxxxx"

# Secret string for the project
# SECRET="abcdef"

# The duration that the access token is valid ["15m"]
ACCESS_TOKEN_TTL="15m"

# The duration that the refresh token is valid, and also how long users stay logged-in to the App ["7d"]
REFRESH_TOKEN_TTL="7d"

# Whether or not to use a secure cookie for the refresh token in cookie mode [false]
REFRESH_TOKEN_COOKIE_SECURE=false

# Value for sameSite in the refresh token cookie when in cookie mode ["lax"]
REFRESH_TOKEN_COOKIE_SAME_SITE="lax"

# Name of refresh token cookie ["directus_refresh_token"]
REFRESH_TOKEN_COOKIE_NAME="directus_refresh_token"

# Which domain to use for the refresh cookie. Useful for development mode.
# REFRESH_TOKEN_COOKIE_DOMAIN

# The duration in milliseconds that a login request will be stalled for,
# and it should be greater than the time taken for a login request with an invalid password [500]
# LOGIN_STALL_TIME=500

# Whether or not to enable the CORS headers [false]
CORS_ENABLED=true

# Value for the Access-Control-Allow-Origin header. Use true to match the Origin header, or provide a domain or a CSV of domains for specific access [false]
CORS_ORIGIN=true

# Value for the Access-Control-Allow-Methods header [GET,POST,PATCH,DELETE]
CORS_METHODS=GET,POST,PATCH,DELETE

# Value for the Access-Control-Allow-Headers header [Content-Type,Authorization]
CORS_ALLOWED_HEADERS=Content-Type,Authorization

# Value for the Access-Control-Expose-Headers header [Content-Range]
CORS_EXPOSED_HEADERS=Content-Range

# Whether or not to send the Access-Control-Allow-Credentials header [true]
CORS_CREDENTIALS=true

# Value for the Access-Control-Max-Age header [18000]
CORS_MAX_AGE=18000

####################################################################################################
### Argon2

# How much memory to use when generating hashes, in KiB [4096]
# HASH_MEMORY_COST=81920

# The length of the hash function output in bytes [32]
# HASH_HASH_LENGTH=32

# The amount of passes (iterations) used by the hash function. It increases hash strength at the cost of time required to compute [3]
# HASH_TIME_COST=10

# The amount of threads to compute the hash on. Each thread has a memory pool with HASH_MEMORY_COST size [1]
# HASH_PARALLELISM=2

# The variant of the hash function (0: argon2d, 1: argon2i, or 2: argon2id) [2]
# HASH_TYPE=2

# An extra and optional non-secret value. The value will be included B64 encoded in the parameters portion of the digest []
# HASH_ASSOCIATED_DATA=foo

####################################################################################################
### Auth Providers

# A comma-separated list of auth providers []
AUTH_PROVIDERS=""
# AUTH_PROVIDERS="github"

# AUTH_GITHUB_DRIVER="oauth2"
# AUTH_GITHUB_CLIENT_ID="73e...4b"
# AUTH_GITHUB_CLIENT_SECRET="b9...98"
# AUTH_GITHUB_AUTHORIZE_URL="https://github.com/login/oauth/authorize"
# AUTH_GITHUB_ACCESS_URL="https://github.com/login/oauth/access_token"
# AUTH_GITHUB_PROFILE_URL="https://api.github.com/user"
# AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION=true
# AUTH_GITHUB_DEFAULT_ROLE_ID="82424427-c9d4-4289-8bc5-ed1bf8422c90"
# AUTH_GITHUB_ICON="github"
# AUTH_GITHUB_LABEL="GitHub"
# AUTH_GITHUB_EMAIL_KEY="email"
# AUTH_GITHUB_IDENTIFIER_KEY="login"

####################################################################################################
### Extensions

# Path to your local extensions folder ["./extensions"]
EXTENSIONS_PATH="./extensions"

# Automatically reload extensions when they have changed [false]
EXTENSIONS_AUTO_RELOAD=true

####################################################################################################
### Email

# Email address from which emails are sent ["no-reply@directus.io"]
EMAIL_FROM="no-reply@directus.io"

# What to use to send emails. One of
# sendmail, smtp, mailgun, sendgrid, ses.
EMAIL_TRANSPORT="sendmail"
EMAIL_SENDMAIL_NEW_LINE="unix"
EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"

## Email (Sendmail Transport)

# What new line style to use in sendmail ["unix"]
# EMAIL_SENDMAIL_NEW_LINE="unix"

# Path to your sendmail executable ["/usr/sbin/sendmail"]
# EMAIL_SENDMAIL_PATH="/usr/sbin/sendmail"

## Email (SMTP Transport)
# EMAIL_SMTP_HOST="localhost"

# Use SMTP pooling
# EMAIL_SMTP_POOL=true
# EMAIL_SMTP_PORT=465
# EMAIL_SMTP_SECURE=false # Use TLS
# EMAIL_SMTP_IGNORE_TLS=false
# EMAIL_SMTP_USER="username"
# EMAIL_SMTP_PASSWORD="password"

## Email (Mailgun Transport)
# EMAIL_MAILGUN_API_KEY="key-1234123412341234"
# EMAIL_MAILGUN_DOMAIN="a domain name from https://app.mailgun.com/app/sending/domains"

## Email (SendGrid Transport)
# EMAIL_SENDGRID_API_KEY="key-1234123412341234"

IMPORT_IP_DENY_LIST=

```

**Comment by AlaaL** [comment] 2023-11-06 20:13
Your example runs successful without errors and the collections are created, but i noticed that the created releation is not configured correctly in the image there should be relation tab to configure the relation, anyway this might be another issue.
So i will try to build from your example and see how things are going.
I also noticed my extension SDK version 10.1.9 i will also try to upgrade it to latest version.
![image](https://github.com/directus/directus/assets/5410074/a7c051aa-0e67-4cec-9a46-02c6ef50284b)

**Comment by AlaaL** [comment] 2023-11-07 12:44
I thought i was going crazy :D.
After i tried your operation extension which i was triggering it manually just for testing, and i did all we discussed about like eliminating the accountability in my extension and etc, I tried moving my logic complete logic to your extension and it worked!! and i never knew why i though i might be losing it :D.

The final step for me was to make the Flow as i want to trigger by action, `items.update` and baam the error appeared again, so the problem occur when the trigger is action and event `items.update` and does not appear it is a webhook or manual

So this flow causes the error collection not found
![image](https://github.com/directus/directus/assets/5410074/505aca4e-56d8-41fe-9001-e84296c71901)

And this working like a charm and i only changed the trigger the custom operation extension is the same in both examples

![image](https://github.com/directus/directus/assets/5410074/4d3eb3f5-2c1c-49b9-80ed-561124b99c70)

**Comment by AlaaL** [comment] 2023-11-08 06:50
Hi @azrikahar, Can you confirm if it's a bug or not ?

**Comment by azrikahar** [comment] 2023-11-08 15:36
> The final step for me was to make the Flow as i want to trigger by action, items.update and baam the error appeared again, so the problem occur when the trigger is action and event items.update and does not appear it is a webhook or manual

Interesting find! Thanks again for narrowing it down.

> Can you confirm if it's a bug or not ?

Unfortunately I am still unable to reproduce this, both on MySQL and Postgres. I have the following flow set up using my custom operation that I shared here previously, which looks like:

![](https://github.com/directus/directus/assets/42867097/352d8413-50cf-4c63-bb1f-8813a46b0cc3)

with `generator` being a collection with a `name` field:

![](https://github.com/directus/directus/assets/42867097/e8cfd6f2-a320-42ad-97aa-ec82b6cfce83)

Would you be able to try my approach as well just so we can try to narrow it down further? Which should be:

1. Load up my custom operation in your Directus instance
2. Create collection called `generator` with a string field called `name`
3. Create a event hook flow of type `action`, scope `items.update`, and select `generator` as one of the collections. Afterwards connect it to my custom operation, with the value of `{{$trigger.payload.name}}` (which is whenever the `name` field in `generator` collection gets updated)
4. Create a item in `generator` collection
5. Go back into the new item, and update the `name` field and hit save.

**Comment by AlaaL** [comment] 2023-11-09 12:19
Thank you for your effort in inspecting the issue, I will try what you said and get back to you.
