### ISSUE TITLE
A group which fields don't have read permission should not show it's label within an accordion

### ISSUE THREAD

**Issue by Pachat** [directus/directus#15976] opened 2022-10-13 05:56 UTC
### Describe the Bug

A group containing fields that don't have read permission should not show it's label within an accordion

### To Reproduce

1. In a collection add an accordion with 2 raw groups containing each a notice (for instance)
2. For a regular role give access to the second notice only

### Errors Shown

The label of the first group shows despite the fact that none of its fields are allowed to read for the regular role

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgresql 14

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by ConnorSimply** [comment] 2022-10-13 20:24
I believe this is expected behavior because the raw group is still there, it doesn't hide itself if it has no children. **If you prevent read permission on the raw group, it will not show up.**

For the following data model...
![image](https://user-images.githubusercontent.com/12714889/195702361-5f40822b-1530-4da7-b726-8521ccdd7af4.png)

Set the following permissions to hide `raw_group_1` and `one_name` from the accordian.

![image](https://user-images.githubusercontent.com/12714889/195702790-51d6db08-0998-4acd-a4f4-079b6a7a0db0.png)

However I will defer to @nickrum to confirm this.

**Comment by Pachat** [comment] 2022-10-13 20:38
You are right. I just missed to uncheck also `Raw Group 1`

**Comment by ConnorSimply** [comment] 2022-10-13 21:04
Then I will go ahead and close this!

**Closed by ConnorSimply** 2022-10-13 21:04 UTC
