### ISSUE TITLE
Mention in comment sends [INTERNAL_SERVER_ERROR] Maximum call stack size exceeded

### ISSUE THREAD

**Issue by uebmaster** [directus/directus#10198] opened 2021-12-01 16:39 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When i submit a mention in a comment i got the next error:

![image](https://user-images.githubusercontent.com/5565506/144274235-3b9e3b92-05d9-43b8-8aae-71595b541d19.png)

### To Reproduce

1. browse to one collection
2. open an item
3. type @ and select some user to mention
4. submit the comment

### Errors Shown

![image](https://user-images.githubusercontent.com/5565506/144274729-adf64c5d-22f8-42d5-bc48-bbcb02460542.png)

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

14.18.1

### What database are you using?

Postgres12.9

### What browser are you using?

Opera

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-12-01 23:03
I'm fairly sure this is a duplicate of https://github.com/directus/directus/issues/10056. We can reopen if the problem persists in 9.1.3+ 🙂

**Closed by rijkvanzanten** 2021-12-01 23:03 UTC
Labels: Duplicate
