### ISSUE TITLE
"Unexpected Error" after second github log in

### ISSUE THREAD

**Issue by alexey-yarmosh** [directus/directus#18742] opened 2023-05-26 10:25 UTC
### Describe the Bug

After user was Logged in using github, then clicked "Sign Out" and logged in with the same account again, sign in page shows "Unexpected Error".

### To Reproduce

1. Start a directus with github Log In configured
2. Configure default gh role to have App Access (not Admin Access) and Recommended Defaults permissions
3. Log in with the github account
4. Click "Sign Out"
5. Log in with the same github account again
6. Result:
<img width="601" alt="image" src="https://github.com/directus/directus/assets/16905445/dfb01066-12c2-40f8-850d-91e07336f69e">

 Logs:
```
dashboard-directus-1  | [10:17:10] GET /auth/login/github?redirect=http%3A%2F%2Flocalhost%3A8055%2Fadmin%2Flogin%3Freason%3DSIGN_OUT%26continue%3D 302 19ms
dashboard-directus-1  | [10:17:11] GET /auth/login/github/callback?code=xxx&state=xxx 302 1s
dashboard-directus-1  | [10:17:11] GET /admin/login?reason=UNKNOWN_EXCEPTION 200 1ms
dashboard-directus-1  | [10:17:12] GET /extensions/sources/index.js 200 22ms
dashboard-directus-1  | [10:17:12] POST /auth/refresh 400 21ms
dashboard-directus-1  | [10:17:12] GET /auth 304 26ms
dashboard-directus-1  | [10:17:12] GET /server/info?limit=-1 304 40ms
dashboard-directus-1  | [10:17:11.959] WARN: [OAuth2] Unexpected error during OAuth2 login
dashboard-directus-1  |     err: {
dashboard-directus-1  |       "type": "Error",
dashboard-directus-1  |       "message": "Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.",
dashboard-directus-1  |       "stack":
dashboard-directus-1  |           Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.
dashboard-directus-1  |               at QueryCompiler_MySQL._prepUpdate (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:1354:13)
dashboard-directus-1  |               at QueryCompiler_MySQL.update (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/dialects/mysql/query/mysql-querycompiler.js:91:26)
dashboard-directus-1  |               at QueryCompiler_MySQL.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:73:29)
dashboard-directus-1  |               at Builder.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querybuilder.js:83:44)
dashboard-directus-1  |               at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
dashboard-directus-1  |               at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:300:20)
dashboard-directus-1  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
dashboard-directus-1  |               at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:30:19)
dashboard-directus-1  |               at async file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/items.js:471:21
dashboard-directus-1  |     }
```

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by licitdev** [comment] 2023-05-26 11:10
Duplicate of #18595 which was fixed in #18607

**Closed by licitdev** 2023-05-26 11:10 UTC
