### ISSUE TITLE
Add "this will generate..." labels to relational field setup

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#3223] opened 2020-11-27 20:53 UTC
When entering a non-existing field/collection as value for the relational setup, it'll generate those collections/fields automatically. We should show a notice stating what will be generated

**Comment by benhaynes** [comment] 2021-02-11 18:01
Duplicate of https://github.com/directus/directus/issues/2913

**Closed by benhaynes** 2021-02-11 18:01 UTC
Labels: App, Good First Issue, Improvement
