### ISSUE TITLE
Asset whitelist key is disabled

### ISSUE THREAD

**Issue by gianniskarmas** [directus/directus#2602] opened 2020-02-26 00:37 UTC
![image](https://user-images.githubusercontent.com/3495993/75300523-098afe80-5830-11ea-8342-216483c985ff.png)

I think it happened after latest 8.5.5 update but I may be wrong.

**Comment by benhaynes** [comment] 2020-02-26 03:40
@directus/team Where is this going?

**Comment by hemratna** [comment] 2020-02-26 06:28
@gianniskarmas 
We fix this https://github.com/directus/api/issues/1728 with https://github.com/directus/api/pull/1753 PR
Can you please check with latest https://github.com/directus/api

**Comment by gianniskarmas** [comment] 2020-02-26 12:44
Thank you all,
While I've been only using directus combined app since the beginning I am not familiar with where the api resides within the app.
Can you please share more information of how to replace current api inside directus (without running two separate instances) so I can test?
It would be better though if you updated the combined directus with the fixes.
Many Thanks.

**Comment by rijkvanzanten** [comment] 2020-02-26 13:58
Duplicate of https://github.com/directus/api/issues/1728

@gianniskarmas directus/directus is a repo with the build versions of the app/api combined. The API has the exact same structure, so you should be able to patch the changes of the mentioned PR above into your running app. 

We'll release a new version of the platform with that patch applied later this week

**Comment by egel** [comment] 2020-04-27 00:34
Hey @directus/team, is there any progress patch for this issue?

**Comment by benhaynes** [comment] 2020-04-27 12:41
Due to our limited resources, our whole team is working on v9 and v10 at the moment.

We try to keep these threads updated when there's news to share, unfortunately, there are no updates for this ticket at the moment. Our small open-source team is busy with core stability and other priority fixes, so the best way to get tickets pushed through is to [sponsor bug fixes](https://docs.directus.io/getting-started/supporting-directus.html#sponsored-bugs) or [commission feature requests](https://docs.directus.io/getting-started/supporting-directus.html#commissioned-features). Thanks for understanding! 🙂

**Comment by rijkvanzanten** [comment] 2020-04-28 18:38
@egel This was fixed in a later version. It's working as expected on the latest version (8.6.2)

**Closed by rijkvanzanten** 2020-04-28 18:38 UTC
Labels: duplicate
