### ISSUE TITLE
Sort field not working for M2M and M2A

### ISSUE THREAD

**Issue by abertay-university** [directus/directus#7124] opened 2021-08-02 13:54 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When sort is enabled on a new M2M and M2A field, the items don't sort correctly and sometimes visually duplicates the item dragged.

The issue happens because the collection for the joiner table doesn't have the sort field selected when it was created. Once I set the sort field to the sort column it all works. I suspect it's a missing step when creating the joiner table.

**Collection Sort field not defined**
![image](https://user-images.githubusercontent.com/31690037/127871780-4b537718-5e4f-49b7-b196-918bb4457821.png)

**Expected sort field to automatically be configured**
![image](https://user-images.githubusercontent.com/31690037/127871857-f779c406-69d0-4d8e-a435-b0e50727ff26.png)

**Relation settings on field**
![image](https://user-images.githubusercontent.com/31690037/127872275-d335aa90-2468-4af1-b15c-b5ed210ee324.png)

### To Reproduce

1. Create a new M2M field or M2A field
2. Choose the collection(s) 
3. Leave auto setting enabled
4. Type a column name in the sort field (I call it sort)
5. Finish completing the field

Test issue by creating a new row
1. Add more than on entry in the new field
2. Try sorting the items
3. Check joiner table collection has the sort field selected

### What version of Directus are you using?

9.0.0r87

### What version of Node.js are you using?

14

### What database are you using?

MySQL

### What browser are you using?

Chrome, Safari, Firefox

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2021-08-03 22:43
Duplicate of https://github.com/directus/directus/issues/3721

**Closed by rijkvanzanten** 2021-08-03 22:43 UTC
Labels: Bug (Potential)
