### ISSUE TITLE
docker install cannot create POST /users REST or GRAPHQL

### ISSUE THREAD

**Issue by staminna** [directus/directus#17875] opened 2023-03-22 00:45 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Me:
I am using Directus 9 in Docker, but my /users POST request returns 200 OK except that all the data I send returns null except for the user ID which is automatically generated by Directus. Same result in Postman, CURL or Insominia, aswell as REST API or GRAPHQL. Any ideas?

It sounds like the request is being processed successfully, but the data you're sending isn't being properly parsed by Directus. Here are a few things to check:

Check your request payload: Make sure that you're sending the correct data in your request payload. Double-check the names and types of the fields you're sending to ensure they match the schema of your Directus project.

Check your API key permissions: Make sure that the API key you're using to authenticate your requests has the proper permissions to create users. You can check this in the Directus admin interface under "Users & Roles".

Check your Docker configuration: Make sure that your Docker configuration is correct and that you're exposing the correct ports. If Directus is running in Docker, make sure that the container is properly mapped to the host port you're using for your requests.

Check your Directus version: Make sure that you're running the latest version of Directus. Some older versions may have bugs or issues with the user creation process.

Check your request headers: Double-check the headers you're sending with your request. Make sure that you're including the "Content-Type" header with a value of "application/json" to ensure that Directus properly parses your request payload.

If none of these suggestions solve your issue, you may need to provide more details about your setup, including your Directus configuration, Docker configuration, and the payload you're sending with your request.

Me:
1. Yes I am using the required ones from the official documentation. 
3. I am using Administrator key and also tried another user and set permissions to allow write on every table. 
4. GET request works perfectly except for POST with the same settings, 
4. Latest version and 
5 "Content-Type"
<img width="1168" alt="Captura de ecrã 2023-03-22, às 00 37 49" src="https://user-images.githubusercontent.com/515180/226772470-e7f29066-b588-475b-81cc-802fc710546b.png">
 yes I set to application/json.

### To Reproduce

1. Install latest docker version from dockerhub
2. run setup ( I am using Postgres Database )
3. create a Role and a custom input string field on users table ( in my case is domain )

```
curl --request POST \
  --url 'http://localhost:8055/users?email=jorge%40test.pt&password=001password&role=622533f6-64a1-4b61-81e0-673065109c7c&domain=outsource&first_name=Freed&last_name=Baggins&location=Portugal' \
  --header 'Authorization: Bearer (the-admin-token)' \
  --header 'Content-type: application/json'

{"data":{"id":"a9623f40-d754-4b00-89cc-39010d945133","first_name":null,"last_name":null,"email":null,"password":null,"location":null,"title":null,"description":null,"tags":null,"avatar":null,"language":null,"theme":"auto","tfa_secret":null,"status":"active","role":null,"token":null,"last_access":null,"last_page":null,"provider":"default","external_identifier":null,"auth_data":null,"email_notifications":true,"domain":null}}% 
```

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-03-22 02:31
When making a POST request for any API requests, make sure to send the data (email, password, role etc) as the **request body**, not query parameters. Please kindly refer to the docs: https://docs.directus.io/reference/system/users.html#request-body

Here's a quick screen capture where I'm using Insomnia for further clarification:

https://user-images.githubusercontent.com/42867097/226786360-01deec78-bc9c-4b89-92ee-6cb5f33e91ef.mp4

As I believe this is not a bug, I'll proceed to close this issue as a question. We'll re-open if it's confirmed otherwise.

**Closed by azrikahar** 2023-03-22 02:31 UTC
