### ISSUE TITLE
 Item permissions do not work when updating and deleting

### ISSUE THREAD

**Issue by info-sapphire** [directus/directus#19043] opened 2023-06-30 11:07 UTC
### Describe the Bug

Since version 10.3.0 - 10.4.0, item permissions for updating and deleting have ceased to work in the rules of which there are nested collections.

This results in fields being read only it seems and can't be edited.

related bugs:
From #18898 
From #19039 

this works great in v10.2.1 and below

### To Reproduce

in my case i create collections
1. Organizations
2. Clinic
3. Appointments

organization has relation one to many with clinic and relation many to many system collection **directus_role**

![1](https://github.com/directus/directus/assets/43640647/3c49febd-26d6-4437-a35d-4411e7cf8b7c)
![2](https://github.com/directus/directus/assets/43640647/cd0312ef-7310-4e31-b3a4-d5fb55b5bd1b)
![3](https://github.com/directus/directus/assets/43640647/2b2cb427-1f61-4565-80c9-5dab168ef003)

Appointments has relation many to one with clinic

![4](https://github.com/directus/directus/assets/43640647/ce329e68-6c4a-4c18-b171-d977858317b5)

i am trying to filter access by $CURRENT_ROLE
important: in organization i added role for example manager

![6](https://github.com/directus/directus/assets/43640647/2618b7a3-a328-450c-807c-d39f501792ef)

when user with role manager try to edit appointment, he can't do it, because fields being read only

![7](https://github.com/directus/directus/assets/43640647/0a841aa5-27ba-4912-9308-88726f5ef403)

but admin, has access ...

![5](https://github.com/directus/directus/assets/43640647/b931266f-d0bc-4111-986b-1e1db6920d52)

i also try to create another simple collection "discount" without relation and filtering access by $CURRENT_ROLE 

![image_2023-06-30_13-50-46](https://github.com/directus/directus/assets/43640647/60498d03-a31c-4d88-a512-3efdfdf51832)

and this doesn't work to ...

and so I thought, what if i use my role GUID and i try it

![image_2023-06-30_13-52-16](https://github.com/directus/directus/assets/43640647/015961af-8a2c-496b-aad4-0e066a95c0e4)

and it doesn't work to, user can't edit and delete

![image_2023-06-30_13-53-45](https://github.com/directus/directus/assets/43640647/491b246e-f087-47c1-9fc0-cdf55fa6dffc)

I confirm that it works in the v10.2.1 and below

### Directus Version

v10.3.0 - v10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by shipsides-sparknel** [comment] 2023-07-04 05:43
if another example is needed, this one is as straightforward as it comes. Role edit permission on directus_users :
```
{
	"role": {
		"_eq": "d4646492-750a-43f0-bf3b-392204471523"
	}
}
```
works

```
{
	"role": {
		"id": {
			"_eq": "d4646492-750a-43f0-bf3b-392204471523"
		}
	}
}
```

does not

**Comment by rijkvanzanten** [comment] 2023-07-09 14:23
Duplicate of https://github.com/directus/directus/issues/18898

**Closed by rijkvanzanten** 2023-07-09 14:23 UTC
