### ISSUE TITLE
Many-to-many list ui bug

### ISSUE THREAD

**Issue by blexo** [directus/directus#15971] opened 2022-10-12 20:17 UTC
### Describe the Bug

When you create a many to many relationship between 2 objects...  and 2 items in one collection are linked to 1 item in the second...  if the list view showing the 2 items includes the related item as a display field...  it will show a comma in one the records.

### To Reproduce

create 2 entities in one related collection
create 1 entity in the other related collection
connect the 2 entities to the 1
add a field to the list of items in the first collection for the 2nd collection items
a comma will appear in that column in one of the entities on the list

<img width="593" alt="Screen Shot 2022-10-12 at 3 16 53 PM" src="https://user-images.githubusercontent.com/15165568/195439493-c6f29829-0c34-457a-82d6-f14071673254.png">

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.17.0

### What database are you using?

cloud

### What browser are you using?

firefox

### How are you deploying Directus?

cloud

**Comment by br41nslug** [comment] 2022-10-13 08:29
I am not able to reproduce this by following the steps unfortunately. It looks like there may be an invalid record dangling on the junction table of your m2m relation 🤔 
![image](https://user-images.githubusercontent.com/9389634/195544083-3365fea5-0cad-41b7-9047-3ac5b752b478.png)

**Comment by blexo** [comment] 2022-10-13 12:55
Huh…. Odd.  Well - thank you for looking into it so quickly.

I wonder how the dangling record happened…. I may experiment some more and
see if I can figure it out if I have time today.

**Comment by rijkvanzanten** [comment] 2022-10-15 01:41
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2022-10-15 01:41 UTC
Labels: App, Needs More Info, Bug (Potential), Can't Reproduce
