### ISSUE TITLE
GraphQL does not find new collections anymore

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#3610] opened 2021-01-07 20:40 UTC
It seems graphql does not find new collections anymore. Any new collection will not be available in the /graphql explorer. I also tried to restart the node server, but this does not solve the problem. There is also no possibility to delete a cache.

---

### Project details
Directus Version: 9.0.0-rc.28
Environment: production
OS: Linux 4.19.0-13-amd64
Node: 14.15.3

**Comment by sensedrive** [comment] 2021-01-07 20:47
Additional comment. I recently updated from rc.23 to rc.28

**Comment by rijkvanzanten** [comment] 2021-01-07 21:38
@sensedrive Are you authenticated? If not, does your public role have read access to those collections?

**Comment by sensedrive** [comment] 2021-01-08 10:23
Thank you for the quick response @rijkvanzanten. I am authenticated as admin.

I tried another approach and this worked actually. The POST request including the admin token works, whereas the GraphiQL request fails /graphql (also logged in as admin), respectively does not offer the new item collections in the explorer.

**Comment by rijkvanzanten** [comment] 2021-01-08 16:37
How are you authenticating the GraphiQL page? Are you adding the `access_token` query param in the URL? Sounds like the auth info doesn't go through to the API somehow

**Comment by robsontenorio** [comment] 2021-01-24 02:49
Same issue on rc31. This is a fresh install using docker-compose as suggested on docs.

- http://localhost:8055
- Just logged in on admin page
- Create some collection and items
- http://localhost:8055/graphql

![image](https://user-images.githubusercontent.com/118955/105619854-6fcc2880-5dd5-11eb-89e0-0ec4203c9012.png)

**Comment by theonlynexus** [comment] 2021-01-27 02:09
I don't know exactly what is going on, but I can't access the data via either REST or GraphQL.

For REST requests I always get empty sets (I am passing the auth token and the user has the Administrator role) and for GraphQL I end up with the bug described in #3796

**Comment by rijkvanzanten** [comment] 2021-01-27 14:58
@theonlynexus sounds like there's a different cause here than in the OP. Can you open a new issue detailing everything so we can reproduce it?

**Comment by benhaynes** [comment] 2021-02-10 16:52
What info do we need here to reproduce this? Has anyone else confirmed this issue?

**Comment by rijkvanzanten** [comment] 2021-02-24 19:00
I'll close this for now. The GraphQL setup has seen quite a lot of changes since rc.2x, and it doesn't seem like anybody else has ran into this since 🤔

**Closed by rijkvanzanten** 2021-02-24 19:00 UTC
Labels: Needs More Info
