### ISSUE TITLE
M2M items in display are coming as blank. The pop-up that showed previously has gone away.

### ISSUE THREAD

**Issue by ravi-2912** [directus/directus#13843] opened 2022-06-10 17:23 UTC
### Describe the Bug

For two tables having M2M relations, the M2M field in list display apears blank if it configured to display related values. If it is not configured then items if configured to show raw values apper as array string like [1,2]. But when configuring it show related values in the list display, the M2M field is blank and no pop up  appears on clicking.

### To Reproduce

Create 2 tables.
Create M2M relationship.
Configure how the M2M field is shown in the display.
View the display. It comes blank

### Errors Shown

No errors

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-06-10 18:46
Duplicate of https://github.com/directus/directus/issues/13836

**Closed by rijkvanzanten** 2022-06-10 18:46 UTC
