### ISSUE TITLE
Impossible to edit field "default value" after creation "ALTER COLUMN TYPE is not supported inside a transaction"

### ISSUE THREAD

**Issue by EddiePiazza** [directus/directus#23594] opened 2024-09-06 11:16 UTC
### Describe the Bug

I am getting this disclamer error when trying to add a "default value"

{
  "errors": [
    {
      "message": "alter table \"restaurant_cart_item_price\" alter column \"restaurant_item_price_type\" type varchar(255) using (\"restaurant_item_price_type\"::varchar(255)) - unimplemented: ALTER COLUMN TYPE is not supported inside a transaction",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### To Reproduce

create a dropdown object or similar.
edit the created object and try to add a default value.

### Directus Version

11.0.2

### Hosting Strategy

Self-Hosted (Custom)

### Database

cockroachdb

**Comment by paescuj** [comment] 2024-09-09 13:00
Duplicate of #18252.

Unfortunately, this is a limitation of CockroachDB, that means we can't do anything here at the moment. See https://www.cockroachlabs.com/blog/alter-column-type/#Current-Limitations-and-Future-Work.

**Closed by paescuj** 2024-09-09 13:00 UTC
