### ISSUE TITLE
WYSIWIG field toolbar buttons are broken

### ISSUE THREAD

**Issue by adminradio** [directus/directus#18244] opened 2023-04-19 05:58 UTC
### Describe the Bug

Some of the buttons in the toolbar of the WYSIWYG editor are broken. There are at least two problems:

1. broken display of inline SVG elements (red and blue line in the screenshot)
2. cutting text from the buttons with an ellipse "...", (green line), but this may be a flow problem coming from the broken inline SVG 

![Screenshot with marks](https://user-images.githubusercontent.com/2880143/232977585-2d81ceb5-bbd6-4e90-b83e-757789f8e10b.png)

### To Reproduce

Running on 9.25.1:

1. create a collection/data model
2. add a wysiwyg field
3. add an item to the collection

This error occurs (at least) on Chrome and Safari on macOS. No zoom is applied to the browser canvas.

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2023-04-19 06:15
This is a duplicate of #18184, fixed in #18185 and will be fixed in the next release.

**Closed** 2023-04-19 06:20 UTC
