### ISSUE TITLE
GraphQL create mutation returns the wrong row

### ISSUE THREAD

**Issue by zenati** [directus/directus#5094] opened 2021-04-16 09:02 UTC
1) The issue and what you expected to happen
    Creating a row using a mutation should create + return the created row.
    But it created the row ✅ , and returns another not related row 🚫 .

2) Exact steps to reproduce this issue

![Screenshot 2021-04-16 at 11 00 04](https://user-images.githubusercontent.com/5849907/115000523-21de3280-9ea3-11eb-908d-42bd1fea4156.png)

3) Your environment:
    npx
    v9.0.0-rc.59
    PgSQL

**Comment by rijkvanzanten** [comment] 2021-04-16 14:49
@zenati I just tried this on a fresh PG installation and everything seems to work as expected 🤔 

In your example, it uses a generated UUID for the primary key, which means that [it pulls the primary key to retrieve from the submitted payload](https://github.com/directus/directus/blob/main/api/src/services/items.ts#L102) which should prevent any racing conditions or things like that.

Do you have any extensions enabled that might cause havoc? Does this consistently happen on every collection, or only one? In case of the latter, could you share a minimal reproduction in a SQL dump?

**Comment by rijkvanzanten** [comment] 2021-04-16 14:53
I'll close this for now. We'll reopen and investigate if a 
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by rijkvanzanten** [comment] 2021-04-16 14:53
I'll close this for now. We can reopen / investigate if a way to reproduce is available 🙂

**Comment by rijkvanzanten** [comment] 2021-04-26 22:43
The reason this is happening is because this table is using a Postgres function outside of Directus to populate the "default value" of the primary key field (`gen_random_uuid()` in this case). This in turn means Directus is unaware of the primary key, and has to resort to trying to fetch the last inserted row from the DB, which in this case fails.

You can fix this by telling Directus to use a UUID for this ID under Data Model settings 👍🏻

**Comment by rijkvanzanten** [comment] 2021-04-26 22:45
I'll close this for now, as the situation is caused by a configuration mismatch with Directus. I've opened a new feature request to natively support these alternative primary key generation methods in the future: https://github.com/directus/directus/discussions/5267

**Closed by rijkvanzanten** 2021-04-26 22:45 UTC
Labels: API, Bug (Potential)
