### ISSUE TITLE
SyntaxError in the @directus/sdk-js 9.0.0-rc.32

### ISSUE THREAD

**Issue by Pilskalns** [directus/directus#3818] opened 2021-01-26 17:31 UTC
Using authentication through @directus/sdk-js throws this following SyntaxError:

```
C:\......\node_modules\@directus\sdk-js\dist\sdk-js.cjs.js:251
        return this.axios.defaults.headers?.Authorization?.split(' ')[1] || null;
                                           ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:872:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\dev\test-directus\directus-hugo-driver\index.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
```

I tried around bunch of SDK versions, seems the first broken one is `9.0.0-rc.24`

Environment:
**Directus/SDK-JS 9.0.0-rc.32**
Node v12.10.0
MySQL 8
Windows 10

**Comment by rijkvanzanten** [comment] 2021-01-26 17:51
Duplicate of https://github.com/directus/directus/pull/3646

**Closed by rijkvanzanten** 2021-01-26 17:51 UTC
