### ISSUE TITLE
if unique field entry cannot be created again after deleting

### ISSUE THREAD

**Issue by Wendenburg** [directus/directus#2468] opened 2019-11-19 10:41 UTC
# Bug Report

## Steps to Reproduce

- create collection -> add text entry and make it unique, add more fields if needed
- add first entry to collection
- delete this first entry again from collection
- add new entry to collection with the same value for the unique field
- even though the first entry was deleted from collection, the unique field can not have the same value again

## Expected Behavior
if entry was deleted it should be possible to create it again

## Actual Behavior
sql error

## Other Context & Screenshots

+----+---------+------------+---------------------+--------+
| id | status  | created_by | created_on          | domain |
+----+---------+------------+---------------------+--------+
|  5 | deleted |          3 | 2019-11-18 17:34:27 |      2 |
+----+---------+------------+---------------------+--------+
it is not possible to create a new entry with domain = '2'

## Technical Details

- Device: desktop
- OS: Mac OS 10.13.6
- Web Server: Apache, Mamp
- PHP Version: 7.3.8
- Database: 5.7.26
- Install Method: both, cloned master branch and docker container

**Comment by benhaynes** [comment] 2019-11-19 13:39
Hey @Wendenburg — this is likely expected behavior. I can see you have a `status` field on that collection, and yours is setup to use the "soft delete" option: `deleted`. Soft deleted items are not removed from the database, they are simply not returned in normal API calls. However the `unique` flag for a column uses actual SQL, so it validates on _all_ items... even soft deleted ones. You can get around this issue by _hard_ deleting items (updating your `status` field options).

I'll close this as it's not something we can really fix — and will update the docs to be more clear on the subject.

**Closed by benhaynes** 2019-11-19 13:39 UTC

**Comment by benhaynes** [comment] 2019-11-19 13:49
Note added here: https://docs.directus.io/guides/status.html#soft-delete

**Comment by Wendenburg** [comment] 2019-11-19 14:16
technically right, but, sorry to say so, from a user's perspective a fail, as he will never understand whats going on. So - if soft_delete is enabled - there should be no unique option at all. 

However, thanks for updating the docs. But  - i may be stupid - where do i find these options?

**Comment by benhaynes** [comment] 2019-11-19 14:20
I agree that it's confusing... but it's also makes sense from a SQL perspective (as long as you understand what soft-delete is doing). We can't disable `unique` because it is set _before_ you get to interface options in the Field Setup flow. And as far as I know, interface options don't have a way to react to other field settings. Do they @rijkvanzanten ?

All I can think of for now is to add a note on the status options warning users about this conflict. My worry is that the whole App could easily get filled with warnings if we start moving the Docs into the App. This is a tricky one.

**Comment by Wendenburg** [comment] 2019-11-19 14:25
looks like a tricky one indeed. I connected to the container, installed mariaDB and deleted that row manually. Not sure if this is the best way neither ;)

**Comment by benhaynes** [comment] 2019-11-19 14:30
One other thing to throw in the mix would be a different way of handling soft-delete... where we relocate those deleted items **to a mirrored table**, so they no longer break the unique constraint. This is _far_ more complex, though... so I think we'd say it's not 80/20 and let users create this workflow themselves (for now, at least).

**Comment by Wendenburg** [comment] 2019-11-19 14:45
ok... but again, is there any way to configure a hard delete from the admin interface? Did not find a setting like this....

**Comment by benhaynes** [comment] 2019-11-19 14:52
Yes, a few ways:

If you update your `status` mapping (Field > Interface Options), you'll see that there is a `"soft_delete":true` value for the `deleted` option. If you set that to false, then it is still in the system (Admin App) and is just another normal status.

Another option would be to remove the `deleted` status option... so that `active` and `draft` are the status options... and you use the red delete button for hard-deleting. This decouples status and delete.

Lastly, if you delete the `status` field altogether (and users have permission to `delete`), then it will hard delete the items.

**Comment by Wendenburg** [comment] 2019-11-19 15:24
thanks, that was helpful. You should maybe add this also to the docs, as it is quite hidden in the Status Mapping...

**Comment by benhaynes** [comment] 2019-11-19 15:40
Updated in the Docs!
