### ISSUE TITLE
CACHE_VALUE_MAX_SIZE ignored

### ISSUE THREAD

**Issue by martinsotirov** [directus/directus#20500] opened 2023-11-22 13:40 UTC
### Describe the Bug

I'm hosting Directus on Digital Ocean app platform and I'm using Upstash Redis cache which has 1 MB max file size limit. In my env variables for Directus I Have `CACHE_VALUE_MAX_SIZE` set to `1048576` and `CACHE_AUTO_PURGE` is set to `true`. Whenever I try to update content, I get the error:

```
{
  "message": "ERR max request size exceeded. Limit: 1048576 bytes, Actual: 5241200 bytes. See https://upstash.com/docs/redis/troubleshooting/max_request_size_exceeded for details",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
```

### To Reproduce

Set up Directus 10.2.1 on Digital Ocean App platform and try using Upstash as Redis provider.

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-11-22 15:34
Can you try configuring `CACHE_SCHEMA` and/or `CACHE_PERMISSIONS` to `false` ("and/or" because it would be very helpful if you can try permutations of them as well so we may be able to narrow it down) to see whether the error still occurs for you?

Do note that we also require bug reports to be tested on the current latest version (`10.8.1` as of now) if possible. I'll close this for now as per said policy while we gather more info, but happy to re-open once we figure out the root cause here 👍

**Comment by martinsotirov** [comment] 2023-12-06 10:24
@azrikahar should I create a new issue for this problem or do you want to look into it within this ticket?

**Comment by azrikahar** [comment] 2023-12-06 11:27
> should I create a new issue for this problem or do you want to look into it within this ticket?

Thanks for following up! I'll reopen this ticket for further research 👍

> I tried setting `CACHE_SCHEMA` and `CACHE_PERMISSIONS` to false but no combination of those helps.

Hmm I was under the impression that either the permissions cache or especially the schema cache to be the one that's amounting to roughly 5MB from the error you shared. That's odd indeed.

> The only way to not get the error is if I disable the cache completely or at least the auto purge.

Just to be sure on the `at least the auto purge` part, do you mean enabling cache & setting _only_ `CACHE_AUTO_PURGE` to false actually resolved it for you? (as that does potentially lead more towards schema cache being a possible root cause, especially since you also mentioned it happens whenever you update content, and said action should purge the schema cache if you have it enabled)

---

That being said, would you mind sharing the schema snapshot of your setup? Alternatively, you also just share how many collections and fields you have, as I assume that would help approximate the size of the schema.

**Comment by martinsotirov** [comment] 2024-01-05 10:58
@azrikahar sorry I took so long. Here is an updated snapshot of our schema:

[2024-01-04-snapshot-1704370484.yaml.zip](https://github.com/directus/directus/files/13841110/2024-01-04-snapshot-1704370484.yaml.zip)

**Closed** 2024-03-13 01:48 UTC
Labels: :detective: Needs More Info
