### ISSUE TITLE
Primary Key property is initially equal to "+" in custom interface extensions

### ISSUE THREAD

**Issue by ymc-sise** [directus/directus#21372] opened 2024-02-08 15:37 UTC
### Describe the Bug

I experience still the same behaviour as described here: https://github.com/directus/directus/issues/14574

I try to build a custom interface according to the tutorial here https://docs.directus.io/guides/extensions/interfaces-relational-dropdown.html.

I try to read `props.primaryKey` but the request is done with a `+`:  `/items/accountings?filter[id][_eq]=%2B&fields[]=status`.

My console logs are `+` as well.

```js
<template>
  <div v-for="status in results">
    {{ status }}
  </div>
</template>

<script>
import { ref, computed } from 'vue';
import { useApi, useStores } from '@directus/extensions-sdk';

export default {
  props: {
    collection: {
      type: String,
      required: true,
    },
    primaryKey: {
      type: String
    },
    value: {
      type: String,
      default: null,
    },
    width: {
      type: String,
      default: 'full'
    }
  },
  emits: ['input'],
  setup(props, { emit }) {
    const api = useApi();
    const { useCollectionsStore, useRelationsStore, useFieldsStore } = useStores();
    const fieldsStore = useFieldsStore();
    const collectionsStore = useCollectionsStore();

    let awaitingSearch = false;
    const results = ref([]);

    async function fetchResults() {
      try {
        console.log(props.primaryKey) // -> + ??
      
        const response = await api.get(
          `/items/${props.collection}`, {
            params: {
              filter: {
                id: {
                  _eq: props.primaryKey
                }
              },
              fields: [
                'status',
              ]
            },
          }
        );

        results.value = response.data.data;
      } catch (err) {
        console.warn(err);
      }
    }

    fetchResults();

    return { results };
  }
};
</script>
```

### To Reproduce

Generate a new custom interface and use the code above.

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-02-08 16:01
That is correct when creating a new item the primaryKey placeholder in the App is `"+"` which you will need to check for and handle appropriately if that is applicable to your extension.

So in this situation you will need to check for the `+` and not do the api call because no item exists yet until you save.

Closing this for now as working as intended.

**Closed by br41nslug** 2024-02-08 16:01 UTC

**Comment by ymc-sise** [comment] 2024-02-08 16:19
@br41nslug I don't create a new item. In Directus I open the detail view of the item.

If I do a `console.log(props.primaryKey)` after `        results.value = response.data.data;` in my code, the primarey key is returned correctly but not before `        const response = await api.get(`

**Comment by br41nslug** [comment] 2024-02-08 16:27
> I don't create a new item. In Directus I open the detail view of the item.

You still need to check for new item creation as that is the only way for the interface to know whether you're updating or creating an item. In you're case it looks like you're trying to load data before Directus is done loading/hydrating the data. I recommend adding a watch to the `primaryKey` prop so you can properly re-initialize the interface once the primaryKey has changed (this can also happen when switching between items)

**Comment by ymc-sise** [comment] 2024-02-09 10:40
@br41nslug Thx! It's good to know that Directus needs some time to hydrate the data. I assumed `props.primaryKey` would already be hydrated before starting the first lifecycle `setup` in Vue, and that the `+` is a bug. Other `props`, like `props.collection`, are hydrated correctly at the start of `setup` when doing a `console.log(props.collection)` as the first command in `setup`.

A `watch` on `primaryKey` helps indeed if anyone else is facing the same problem:

```
    watch(
      () => props.primaryKey,
      () => {
        fetchResults();
      }
    );
```
