### ISSUE TITLE
No preview of selected image in an M2A field.

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17125] opened 2023-01-12 19:17 UTC
### Describe the Bug

When using a M2A field and there is an image preview, the image only appears after saving the item. If unsaved a folder icon appears.

### To Reproduce

Create a collection (let’s say `projects`) with a M2A field (`slides`). For the junction table create a collection called `projects_slides` and for the relation a collection called `projects_slides_images`. The `projects_slides_images` has an image field. Create a new item in the projects collection and add a new image to the slides. A folder icon appears in the M2A field instead of the preview thumbnail.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

Latest

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2023-01-12 20:00
Duplicate of https://github.com/directus/directus/issues/10647

**Closed by rijkvanzanten** 2023-01-12 20:00 UTC

**Comment by JonathanDoelan** [comment] 2023-01-12 20:05
@rijkvanzanten What does “closing this as not planned” mean? That the bug won’t be fixed? Or will directus move in a different direction? Are we able to contribute a solution?

**Comment by rijkvanzanten** [comment] 2023-01-12 20:06
@JonathanDoelan This is a duplicate of #10647, so this particular issue can be closed in favor of tracking the other one 🙂 No need for having two different tickets floating around describing the same problem 👍🏻

**Comment by JonathanDoelan** [comment] 2023-01-12 20:09
@rijkvanzanten I’m sorry, i’m already tired today … I did not see, that #10647 is still open … haha
