### ISSUE TITLE
Block editor in Translations field overwriting content for other language when editing

### ISSUE THREAD

**Issue by SubOrbit** [directus/directus#19041] opened 2023-06-30 10:15 UTC
### Describe the Bug

If you use a Block editor field inside Translations field, when editing the content, the content of the block editor for second language gets overwritten if you try to edit both (multiple) languages at a time and only then save the changes.
If you edit first language and then **save**, then after saving, switch language and edit the content for second language, it works OK.

### To Reproduce

Create a collection (lets say named `pages`) with `Translations` type field. This generates new collection named `pages_translations`.
In `pages_translations` collection, add field of type `Block editor` (lets say named `content`).

Now, go to `Content module` and edit the `Pages` collection.
Input some content in the `Content` field, now switch language, and the `Content` field for second language now is of same value as content for the primary language (it got overwritten).

If on the other hand, you input some content in the `Content` field for the primary language, **then click Save**, and only then switch language, it works as expected.

### Directus Version

v10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by SubOrbit** [comment] 2023-06-30 10:41
Additionaly, I have found that adding an image to the block editor prevents loading content for other language completely. No matter if I save the content for one language before switching to another language, as soon as one of the blocks is an image block, that value of the block editor is shown in all language variants.

**Comment by DanielBiegler** [comment] 2023-08-17 15:37
Hi there! :) Thank you for the clear reproduction steps - I tried it out but have to report that I cant reproduce this on the latest version, it might have been fixed in the meantime, I see you mentioned you were on v10.4.0.

I tried out a couple of combinations with images/order of opening languages/new items, etc - in both the up to date dev build AND production build with tag @v10.5.3

Heres a short video with a couple of tries:

[Screencast from 17.08.2023 17:30:32.webm](https://github.com/directus/directus/assets/14810858/9a5c3b70-b059-4337-ba69-a97c9deea920)

Could you try updating and reporting back? Thanks :)

**Comment by rijkvanzanten** [comment] 2023-08-17 17:09
@DanielBiegler Could it be related to https://github.com/directus/directus/issues/19234#issuecomment-1669697631 ?

**Comment by DanielBiegler** [comment] 2023-08-17 17:59
@rijkvanzanten I (currently) don't think so - Just took another look and judging by my quick testing now #19234 seems to be related to editorjs' own `onChange` debouncing/batching - we use that function to emit the `input` event in order to update the state. But like I said, editorjs does batching and delays calling of `onChange`, hence the "quickly input changes" dont get saved.

Found it in their source: https://github.com/codex-team/editor.js/blob/b39996616c33de90bb82e3d7a009c865cf2b0f0c/types/configs/editor-config.d.ts#L91-L96

Tested it now while inspecting the `onChange` callback and it indeed doesnt fire fast enough! Yay, found the cause - at least for #19234 ! :)

But for this issue I tried both dev and prod builds and couldnt reproduce, I think it might be something different.

**Comment by mlippai** [comment] 2023-08-17 19:41
Hi @DanielBiegler 
according to your video you're toggling split view, and not switching the languages. Have you tried reproducing the issue by switching languages and not using split view?

**Comment by DanielBiegler** [comment] 2023-08-18 08:02
@mlippai This is why I like including videos, thank you! :rocket:

The language switching indeed does NOT update the editor instance and leads to overwriting the wrong key i.e. the wrong language. Really nice find, I will investigate.

**Comment by DanielBiegler** [comment] 2023-08-18 08:55
Identified the root cause:

We stop clearing the content of the editor early when there have been changes, in order to avoid overwriting i.e. losing your locally made changes. See the first if guard here:

https://github.com/directus/directus/blob/54777f56580ed45d7c4e789bb4859f367ce46628/app/src/interfaces/input-block-editor/input-block-editor.vue#L121-L124

**Closed** 2023-09-07 11:15 UTC
Labels: Package: @directus/app, Bug
