### ISSUE TITLE
"npx create-directus-project my-project" throwing error

### ISSUE THREAD

**Issue by awnish-npg** [directus/directus#7037] opened 2021-07-28 14:15 UTC
### Describe the Bug

Dear Team,

The recent release "v9.0.0-rc.86" is not stable and unable to run a fresh installation of Directus. 
![image](https://user-images.githubusercontent.com/60690093/127337693-9e7e87a8-c5fc-49a0-9980-8ecb2937b8ed.png)

### To Reproduce

Running the CLI npx create-directus-project my-project

### What version of Directus are you using?

v9.0.0-rc.86

### What version of Node.js are you using?

14.16

### What database are you using?

MySQL 8.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

CLI

**Comment by rijkvanzanten** [comment] 2021-07-28 14:17
Duplicate of https://github.com/directus/directus/issues/7024

**Closed by rijkvanzanten** 2021-07-28 14:17 UTC
Labels: Bug (Potential)
