### ISSUE TITLE
Cant delete collection

### ISSUE THREAD

**Issue by resultatum** [directus/directus#19738] opened 2023-09-19 18:38 UTC
### Describe the Bug

Hi!
Guys, I need help. Cant delete collection/

[UNKNOWN] Request failed with status code 504

"<!DOCTYPE html>\n\n\n\n <html class=\"no-js\" lang=\"en-US\"> \n<head>\n\n\n<title>resultatum.ru | 504: Gateway time-out</title>\n<meta charset=\"UTF-8\" />\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\" />\n<meta name=\"robots\" content=\"noindex, nofollow\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<link rel=\"stylesheet\" id=\"cf_styles-css\" href=\"/cdn-cgi/styles/main.css\" />\n\n\n</head>\n<body>\n<div id=\"cf-wrapper\">\n    <div id=\"cf-error-details\" class=\"p-0\">\n        <header class=\"mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8\">\n            <h1 class=\"inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2\">\n              <span class=\"inline-block\">Gateway time-out</span>\n              <span class=\"code-label\">Error code 504</span>\n            </h1>\n            <div>\n               Visit <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=resultatum.ru\" target=\"_blank\" rel=\"noopener noreferrer\">cloudflare.com</a> for more information.\n            </div>\n            <div class=\"mt-3\">2023-09-19 18:34:38 UTC</div>\n        </header>\n        <div class=\"my-8 bg-gradient-gray\">\n            <div class=\"w-240 lg:w-full mx-auto\">\n                <div class=\"clearfix md:px-8\">\n                  \n<div id=\"cf-browser-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    \n    <span class=\"cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    \n  </div>\n  <span class=\"md:block w-full truncate\">You</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    \n    Browser\n    \n  </h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-cloudflare-status\" class=\" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=resultatum.ru\" target=\"_blank\" rel=\"noopener noreferrer\">\n    <span class=\"cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    </a>\n  </div>\n  <span class=\"md:block w-full truncate\">Tokyo</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    <a href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=resultatum.ru\" target=\"_blank\" rel=\"noopener noreferrer\">\n    Cloudflare\n    </a>\n  </h3>\n  <span class=\"leading-1.3 text-2xl text-green-success\">Working</span>\n</div>\n\n<div id=\"cf-host-status\" class=\"cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center\">\n  <div class=\"relative mb-10 md:m-0\">\n    \n    <span class=\"cf-icon-server block md:hidden h-20 bg-center bg-no-repeat\"></span>\n    <span class=\"cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4\"></span>\n    \n  </div>\n  <span class=\"md:block w-full truncate\">resultatum.ru</span>\n  <h3 class=\"md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3\">\n    \n    Host\n    \n  </h3>\n  <span class=\"leading-1.3 text-2xl text-red-error\">Error</span>\n</div>\n\n                </div>\n            </div>\n        </div>\n\n        <div class=\"w-240 lg:w-full mx-auto mb-8 lg:px-8\">\n            <div class=\"clearfix\">\n                <div class=\"w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What happened?</h2>\n                    <p>The web server reported a gateway time-out error.</p>\n                </div>\n                <div class=\"w-1/2 md:w-full float-left leading-relaxed\">\n                    <h2 class=\"text-3xl font-normal leading-1.3 mb-4\">What can I do?</h2>\n                    <p class=\"mb-6\">Please try again in a few minutes.</p>\n                </div>\n            </div>\n        </div>\n\n        <div class=\"cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300\">\n  <p class=\"text-13\">\n    <span class=\"cf-footer-item sm:block sm:mb-1\">Cloudflare Ray ID: <strong class=\"font-semibold\">8093ea50edb4af93</strong></span>\n    <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    <span id=\"cf-footer-item-ip\" class=\"cf-footer-item hidden sm:block sm:mb-1\">\n      Your IP:\n      <button type=\"button\" id=\"cf-footer-ip-reveal\" class=\"cf-footer-ip-reveal-btn\">Click to reveal</button>\n      <span class=\"hidden\" id=\"cf-footer-ip\">141.105.50.51</span>\n      <span class=\"cf-footer-separator sm:hidden\">&bull;</span>\n    </span>\n    <span class=\"cf-footer-item sm:block sm:mb-1\"><span>Performance &amp; security by</span> <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_504&utm_campaign=resultatum.ru\" id=\"brand_link\" target=\"_blank\">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById(\"cf-footer-item-ip\"),c=a.getElementById(\"cf-footer-ip-reveal\");b&&\"classList\"in b&&(b.classList.remove(\"hidden\"),c.addEventListener(\"click\",function(){c.classList.add(\"hidden\");a.getElementById(\"cf-footer-ip\").classList.remove(\"hidden\")}))}var a=document;document.addEventListener&&a.addEventListener(\"DOMContentLoaded\",d)})();</script>\n</div>\n\n\n    </div>\n</div>\n</body>\n</html>\n"

### To Reproduce

Latest 10.6.0

Create collection and try to delete. Postgres

### Directus Version

10.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-09-19 19:08
This seems to be related to Cloudflare, not Directus. Furthermore, we aren't able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by paescuj** 2023-09-19 19:08 UTC

**Comment by resultatum** [comment] 2023-09-20 01:42
> This seems to be related to Cloudflare, not Directus. Furthermore, we aren't able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

Ok. I try to delete collection without any cloudflare. I go directly to my IP adress and port with Directus, but still cant delete collection.
![image](https://github.com/directus/directus/assets/142282971/8fca9a34-c6ea-490e-a8d8-741f29ed7432)

No any reaction on this command. Nothing in logs. Nothing in frontend.

**Comment by resultatum** [comment] 2023-09-20 01:43
![image](https://github.com/directus/directus/assets/142282971/8de71952-7257-4a8c-a0d3-786d13ffdbdf)

**Comment by resultatum** [comment] 2023-09-20 01:46
So, after that collection was deleted successfully. But it goes unusual way

**Comment by resultatum** [comment] 2023-09-20 04:22
![image](https://github.com/directus/directus/assets/142282971/4f62136f-fee6-497f-a36b-d0cf52ea5baf)

but with another collection its doesnt work

**Comment by paescuj** [comment] 2023-09-20 09:15
It seems like the table was already deleted. Did you manually delete it on the connected database instance?

**Comment by resultatum** [comment] 2023-09-20 09:52
> It seems like the table was already deleted. Did you manually delete it on the connected database instance?

No, I dont use any database agents, Directus only.
I gues collections remove slowly for some reason. So in my domain it looks like server error (not responding long time). When I delete it with direct connection (from IP) it command runs 10-15 minutes. With empty collection without any relations.

**Comment by paescuj** [comment] 2023-09-20 09:59
Hmm that sounds strange.
Which version of PostgreSQL do you use and do you use the default PostgreSQL configuration? Is the connection between Directus and the database reliable (e.g. on the same host)?
Is caching activated on this Directus instance?

**Comment by resultatum** [comment] 2023-09-20 10:09
> Hmm that sounds strange. Which version of PostgreSQL do you use and do you use the default PostgreSQL configuration? Is the connection between Directus and the database reliable (e.g. on the same host)? Is caching activated on this Directus instance?

Yep, its default docker setup on one server. I use Postgresql 13 and cache too.
![image](https://github.com/directus/directus/assets/142282971/382491b6-ea70-4bb3-b5f0-46f0eea1f2bb)

**Comment by br41nslug** [comment] 2023-09-20 11:13
Sounds like the schema was cached and it took 10-15mins for the cache to clear
