### ISSUE TITLE
Postgres table names with upper case characters not working

### ISSUE THREAD

**Issue by samuliasmala** [directus/directus#3213] opened 2020-11-27 06:53 UTC
If the Postgres database contains a table which have one or more upper case characters in its name I get "INTERNAL_SERVER_ERROR" when trying to login. Below is the error message from the console.

Steps to reproduce:
1. Create an empy database `CREATE DATABASE test;`
2. Create and initialize project 
```bash
npx create-directus-project directus-test
cd directus-test
npx directus start
```
3. Login, works nicely
4. Create table with upper case characters `CREATE TABLE public."TestTable"(ID INT PRIMARY KEY NOT NULL, NAME text NOT NULL);`
5. Restart server and try to login --> internal server error with the error message below

```
error: select "c"."column_name", "c"."table_name", "c"."data_type", "c"."column_default", "c"."character_maximum_length", "c"."is_nullable", "c"."numeric_precision", "c"."numeric_scale", "c"."table_schema", (select 'YES' from "pg_index" inner join "pg_attribute" on "pg_attribute"."attrelid" = "pg_index"."indrelid" and pg_attribute.attnum = any(pg_index.indkey) where pg_index.indrelid = c.table_name::regclass and pg_attribute.attname = c.column_name and pg_index.indisprimary) as "is_primary", (select pg_catalog.col_description(pg_catalog.pg_class.oid, c.ordinal_position:: int) from "pg_catalog"."pg_class" where pg_catalog.pg_class.oid = (select('"' || c.table_name || '"'):: regclass:: oid) and "pg_catalog"."pg_class"."relname" = $1) as "column_comment", pg_get_serial_sequence(c.table_name, c.column_name) as serial, "ffk"."referenced_table_schema", "ffk"."referenced_table_name", "ffk"."referenced_column_name" from information_schema.columns c
        LEFT JOIN (
          SELECT
            k1.table_schema,
            k1.table_name,
            k1.column_name,
            k2.table_schema AS referenced_table_schema,
            k2.table_name AS referenced_table_name,
            k2.column_name AS referenced_column_name
          FROM
            information_schema.key_column_usage k1
            JOIN information_schema.referential_constraints fk using (
              constraint_schema, constraint_name
            )
            JOIN information_schema.key_column_usage k2 ON k2.constraint_schema = fk.unique_constraint_schema
            AND k2.constraint_name = fk.unique_constraint_name
            AND k2.ordinal_position = k1.position_in_unique_constraint
        ) ffk ON ffk.table_name = c.table_name
        AND ffk.column_name = c.column_name
       where "c"."table_schema" in ($2) - relation "testtable" does not exist
    at Parser.parseErrorMessage (/home/asmala/directus-plain/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/asmala/directus-plain/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/asmala/directus-plain/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/asmala/directus-plain/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

I think the issue is related to two c.table_name variables which are not properly quoted.:

`pg_get_serial_sequence(c.table_name, c.column_name) as serial`
and
`pg_index.indrelid = c.table_name::regclass`

In both situations the `c.table_name` should probably be replaced with `quote_ident(c.table_name)`.

Any advices how to start digging deeper on this?

**Comment by rijkvanzanten** [comment] 2020-11-27 14:20
@samuliasmala Sounds like you found the cause already! Wanna open a PR for that?

**Comment by samuliasmala** [comment] 2020-11-27 21:05
I'd be happy to do that but is there any instructions how to set up the development environment? [The instructions I found](https://docs.directus.io/advanced/source.html) are referring to archived (api) or removed (app) repositories.

**Comment by benhaynes** [comment] 2020-11-27 21:11
Maybe this is what you're looking for? These are the v9 contributor docs...

https://github.com/directus/directus/blob/main/docs/getting-started/contributing.md#development-workflow

**Comment by rijkvanzanten** [comment] 2020-11-28 00:31
@samuliasmala You were spot on in the error here ✨ 

I went ahead and pushed the fix 👍

**Closed by rijkvanzanten** 2020-11-28 00:31 UTC
Labels: API, Bug, DB: Postgres

**Comment by samuliasmala** [comment] 2020-11-28 07:41
@benhaynes thanks for the link! I was able to set up the dev environment with that.

@rijkvanzanten thanks for the quick fix! A bit off-topic but how did you find the correct file to fix the issue? I'm wondering if there is a way to make the event emitter stack traces more helpful.

**Comment by rijkvanzanten** [comment] 2020-11-28 15:00
@samuliasmala The real answer is that I kinda "just know" at this point 😬

Seeing I built most of it, I remember where this call is made, and am therefore able to find it immediately.

I'm down to discuss ways to improve this! Probably easiest to hit me up [on Discord](https://directus.chat) 🙂 

I'd imagine we'd have to throw in a couple more try/catch blocks here and there to re-wrap errors to add more contextual information, but lets explore our options!
