### ISSUE TITLE
Non-English text (Активен) for the "Active" option in User: Admin Options: Status

### ISSUE THREAD

**Issue by chrisbartley** [directus/directus#7531] opened 2021-08-20 22:06 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The Admin Options: Status popup menu has non-English text (Активен) for the "Active" option. See screenshot.

![image](https://user-images.githubusercontent.com/86031/130297506-a09f06b9-0175-4858-8e3e-6c195eeaf7d3.png)

### To Reproduce

New Directus install (v9.0.0-rc.90). First thing I did after logging in was edit the admin user creating during project setup. Scrolling down, I noticed the (Russian?) text for the "Active" status isn't English.

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

v14.17.5

### What database are you using?

MySQL (Ver 14.14 Distrib 5.7.35, for Linux (x86_64))

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-08-21 00:22
Duplicate of https://github.com/directus/directus/issues/7426, which is a duplicate of https://github.com/directus/directus/issues/7362

**Closed by rijkvanzanten** 2021-08-21 00:22 UTC
Labels: Bug (Potential)
