### ISSUE TITLE
Unexpected error during login

### ISSUE THREAD

**Issue by AnmSaiful** [directus/directus#22493] opened 2024-05-14 18:46 UTC
### Describe the Bug

When I try to log in with the **correct** username and password, it says, **"Unexpected Error"**.

Here's a screenshot:

![Screenshot 2024-05-15 at 00 36 00](https://github.com/directus/directus/assets/204376/50b85e4f-6969-4b47-b312-dff66ee5f197)

But if I try to log in with the **incorrect** credentials, it says, **"Wrong username or password"**

### To Reproduce

I suspected this was happening because I used a **port** to access the site.

For example, I access this site with a URL like `http://example.com:10300`.

Also, I'm using Traefik as a proxy server. So, the request made to  `http://example.com:10300` was actually received at `http://{CONTAINER_IP}:8055`

Please note that I've provided `http://example.com:10300` as the value for the `PUBLIC_URL` environment variable.

`:10300/auth/refresh` is reporting:

```json
{
  "errors": [
    {
      "message": "Route /auth/refresh doesn't exist.",
      "extensions": {
        "code": "ROUTE_NOT_FOUND",
        "path": "/auth/refresh"
      }
    }
  ]
}
```

And, `:10300/auth/refresh` is reporting:

```json
{
  "errors": [
    {
      "message": "Route /auth/login doesn't exist.",
      "extensions": {
        "code": "ROUTE_NOT_FOUND",
        "path": "/auth/login"
      }
    }
  ]
}
```

### Directus Version

10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-05-14 19:13
Heya!

Just to confirm on your second endpoint that you're listing, seems to be a type? You're listing `:10010/auth/refresh` but the response is talking about `/auth/login`. Also you've previously talked about `:10300` and not `10010`.

Any logs on your container? Any logs / info on the failed requests in your browser? Can you query the endpoints from your container host and make sure those work? Just some initial thoughts before I can try and replicate this. Mind sharing your traefik config to reproduce this? 

Normally, during development we run directus with a port and a public URL like `http://localhost:8055`, so that shouldn't be a problem and more something with your personal setup.

**Comment by AnmSaiful** [comment] 2024-05-14 20:19
Hi @hanneskuettner ,

Thanks for your prompt response.

Yes, that port was a typo, and I fixed it.

I've **reinstalled** the container, and the container logs are as follows:

```log
[19:58:40.179] INFO: Initializing bootstrap...
[19:58:40.180] INFO: Database already initialized, skipping install
[19:58:40.180] INFO: Running migrations...
[19:58:40.186] INFO: Done
2024-05-14T19:58:40: PM2 log: Launching in no daemon mode
2024-05-14T19:58:40: PM2 log: App [directus:0] starting in -cluster mode-
2024-05-14T19:58:41: PM2 log: App [directus:0] online
[19:58:41.954] WARN: PostGIS isn't installed. Geometry type support will be limited.
[19:58:41.980] INFO: Server started at http://0.0.0.0:8055
```

I've created a **cURL** container within the same Docker network and executed `curl -L http://{container-name}:8055`, which returns the expected HTML.

And when I execute `curl -L http://{container-name}:8055/auth/refresh` and `curl -L http://{container-name}:8055/auth/login`, both return the same output shared in the first comment.

So, it is not the port issue.

Please let me know if you need more information on the investigation and debugging.

Thank you so much for your attention and participation.

**Comment by hanneskuettner** [comment] 2024-05-15 04:59
The curl errors you're seeing are because both endpoints are `POST` endpoints, rather than `GET`, which is what you're requesting them with.

Do you have any custom hooks or flows that hook into the login / refresh logic?
Can you share the result of the `/auth/refresh` call, that is being returned by the server? Since it is a 400 there should be some info in there on what is failing.

**Comment by AnmSaiful** [comment] 2024-05-15 08:41
@hanneskuettner, just so you know, I created a separate service to examine the issue more closely.

I started with the following **Docker Compose** entry, and it worked:

```yaml
services:
  test-cms:
    container_name: test-cms
    image: directus/directus:10.11.0
    restart: always

    environment:
      ADMIN_EMAIL: test@example.com
      ADMIN_PASSWORD: x123456
      SECRET: x123456
      DB_CLIENT: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: test
      PUBLIC_URL: http://localhost:10300

    ports:
      - "10300:8055"

    profiles:
      - test
  ```

Afterwards, I integrated **Traefik**, and it also worked:

```yaml
services:
  test-cms:
    container_name: test-cms
    image: directus/directus:10.11.0
    restart: always

    environment:
      ADMIN_EMAIL: test@example.com
      ADMIN_PASSWORD: x123456
      SECRET: x123456
      DB_CLIENT: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: test
      PUBLIC_URL: http://localhost:10300

    ports:
      - "10300:8055"

    profiles:
      - test
```

I'm working on the original service to figure out why it's raising that error.

I'll keep you posted here.

**Comment by hanneskuettner** [comment] 2024-05-15 08:44
So I'm going to close this for now, as it seems unrelated to Directus, and more of a setup thing. But if it turns out to be an actual problem of Directus, please comment below and I'll happily reopen this issue!

**Closed by hanneskuettner** 2024-05-15 08:44 UTC
Labels: :detective: Needs More Info

**Comment by AnmSaiful** [comment] 2024-05-15 10:56
@hanneskuettner, how can I enable debugging?

Currently, I'm receiving the following response from `/auth/login`:

```json
{
    "errors": [
        {
            "message": "An unexpected error occurred.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

How can I get the reason for the error or trace it?

FYI, I set `NODE_ENV` to `development`.

**Comment by AnmSaiful** [comment] 2024-05-15 11:01
@hanneskuettner I can see the following error in the container logs:

```log
[10:55:15.388] ERROR: secretOrPrivateKey is not valid key material
    err: {
      "type": "Error",
      "message": "secretOrPrivateKey is not valid key material",
      "stack":
          Error: secretOrPrivateKey is not valid key material
              at module.exports [as sign] (/directus/node_modules/.pnpm/jsonwebtoken@9.0.2/node_modules/jsonwebtoken/sign.js:121:24)
              at AuthenticationService.login (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/services/authentication.js:163:33)
              at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/auth/drivers/local.js:70:56
      "extensions": {
        "stack":
            Error: secretOrPrivateKey is not valid key material
                at module.exports [as sign] (/directus/node_modules/.pnpm/jsonwebtoken@9.0.2/node_modules/jsonwebtoken/sign.js:121:24)
                at AuthenticationService.login (file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/services/authentication.js:163:33)
                at async file:///directus/node_modules/.pnpm/@directus+api@file+api_@aws-sdk+client-sso-oidc@3.569.0_@aws-sdk+client-sts@3.569.0_@types+no_odrjvwlnfqlgyznoalys6xyvne/node_modules/@directus/api/dist/auth/drivers/local.js:70:56
      }
    }
```

**Comment by AnmSaiful** [comment] 2024-05-15 11:03
Finally, I was able to figure out the error. I was using a secret key which contains only numbers. I added an alphanumeric letter, and it worked.

Is it expected to work like this?

**Comment by hanneskuettner** [comment] 2024-05-15 11:13
Glad you're able to solve it! That probably has something to do with the way we parse environment variables. 

Also, one note for future reference. Please refrain from tagging any core maintainers, as this just generates additional noise for us. Thank you! :)

**Comment by AnmSaiful** [comment] 2024-05-15 11:47
That's no problem. I'll remember this in the future. Thank you so much for your help.

Should I leave this **open**, or do you want to keep the restriction of using the `KEY` config? If so, I recommend mentioning this in the **config doc** so that it will help others prevent themselves from going through the same experience, especially during the **development**.

**Comment by azrikahar** [comment] 2024-05-15 16:54
> Should I leave this open

@AnmSaiful seems like this is the same as #20485, but the actual root cause (env vars are automatically casted as numbers) are currently being tracked in #9521 so I think we can leave this one as closed 👍 fully understand your thought to help prevent others from coming across the same issue though!
