### ISSUE TITLE
Feature request: Let a user be in multiple groups

### ISSUE THREAD

**Issue by wittwerch** [directus/directus#1704] opened 2017-07-20 13:38 UTC
In Directus a user can be assigned to one group. For simple use cases this fits well, but as soon as you start to build a larger system you have the need to assigne multiple roles (aka groups) to a user.   

## Proposal
We therefore propose extend Directus to support multiple groups per user. 

Multi group select
Introduce a new join table _directus_users_groups_ and replace the dropdown with a multi select element in the user profile page.

Table level permissions
If a user in multiple groups with different table level permissions, we can easily merge both permissions to the _highest_ level. It is possible in all cases like Add/Edit/View/Delete/Column Read Blacklist/Column Write Blacklist.

IP Whitelist
If a user persist in multiple groups, we can merge the ip addresses of the whitelist of both groups and then display according to that.

Nav Blacklist
If a user persist in multiple groups, we can merge Nav Blacklist of both groups and then display according to that

Nav Override
The navigation override could be challenging. The question is how do we merge these entries when they conflict. Maybe the order of the groups assigned to a user could define how we merge.

**Comment by benhaynes** [comment] 2017-07-22 12:12
Thank you for drafting this up @wittwerch – everything but the nav override makes sense to me. Is this just a general feature request or is this something that you are interested in submitting a PR for? I see this change as an improvement – but one that would likely take some time and would almost certainly introduce many tangential changes/bugs.

_I'll try to start compiling a list of Group related things here:_
* Send Messages: You can send messages to groups – no problem (conceptually) here though
* User Directory: Shows your group overlaying the avatar – not a big deal, but this would have to change
* _I'll try to think of others..._

**Comment by benhaynes** [comment] 2017-08-04 13:43
Hey @wittwerch – just checking in on this. Would this be something you would be interested in submitting a PR for? If not, we'll want to close this and move it to FeatHub since it's a feature request and not a bug.

Let me know, and thanks for drafting this change!

**Comment by benhaynes** [comment] 2017-08-04 23:03
Hey @wittwerch – let me know if you're thinking of creating a PR. In the meantime, I have migrated this to FeatHub so the community can vote for it alongside the other requests.

http://feathub.com/directus/directus/+115

**Closed by benhaynes** 2017-08-04 23:03 UTC
Labels: Help Wanted, New-Feature, Schema-Change
