### ISSUE TITLE
None of the documents showing

### ISSUE THREAD

**Issue by adrianhajdin** [directus/directus#2923] opened 2020-11-13 21:51 UTC
Directus 9.0.0-rc.13

None of the documents are showing, no visible errors though. In the console, I get: "Cannot read property 'field' of undefined"

**Comment by rijkvanzanten** [comment] 2021-01-12 22:50
Duplicate of https://github.com/directus/directus/issues/3322

**Closed by rijkvanzanten** 2021-01-12 22:50 UTC
Labels: Needs More Info
