### ISSUE TITLE
Redis not caching GraphQL requests

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#13571] opened 2022-05-26 12:38 UTC
### Describe the Bug

Redis is not caching GrapQL apparently.

We're starting to implement GraphQL requests to Directus in our project and we've seen that these requests are not being cached. We set up the `CACHE_STATUS_HEADER: "X-Directus-Cache-Status"` environment variable to see if cache was hit.

We noticed that these response cache header appears for the REST API calls that we already implemented, but not for the graphQL ones. Also the response time for the second ones are slower even when their overall response size is significantly smaller.

### To Reproduce

Set up an environment (docker compose is fine) with Directus and Redis (don't forget to set the `CACHE_STATUS_HEADER` envvar) and try to make two API calls, one with REST and the other with GraphQL.

Check that the second one never has the cache status header in its response.

### What version of Directus are you using?

9.9.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-05-26 12:45
Should be duplicate of #11418

**Closed by azrikahar** 2022-05-26 12:45 UTC
Labels: Bug (Potential)
