### ISSUE TITLE
Collection page is empty

### ISSUE THREAD

**Issue by santhosh-sk** [directus/directus#3595] opened 2021-01-06 11:55 UTC
The collection list page should display data.

<img width="1437" alt="Screenshot 2021-01-06 at 12 41 04" src="https://user-images.githubusercontent.com/4300016/103765635-c7207980-501d-11eb-9c11-c5fa814edf91.png">

Steps to reproduce:
1. Create a collection and add some fields
2. Create items in the collection.

Expected: The items should be displayed in the collection page
Actual: The items are displayed in the collection page

Project details:
Directus Version: 9.0.0-rc.28
Environment: production
OS: macOS Mojave (10.14)
Node: 14.15.4
Database: Mysql 8
Browsers: Chrome 87.0.4280.88, Firefox 84.0.1

Other info:
1. The data is present in the API response, as can be seen in the screenshot.
2. The data is also present in exported csv

**Comment by benhaynes** [comment] 2021-01-06 14:04
That's odd. Can you confirm that there are fields "on" in the Layout Options?

**Comment by santhosh-sk** [comment] 2021-01-07 09:47
> That's odd. Can you confirm that there are fields "on" in the Layout Options?

They are not hidden 
<img width="1095" alt="Screenshot 2021-01-07 at 10 42 22" src="https://user-images.githubusercontent.com/4300016/103877330-31e0bc00-50d5-11eb-9ae3-8bb9be3a5a7d.png">

**Comment by santhosh-sk** [comment] 2021-01-07 10:48
Another weird behavior. I re-arranged the layout of the fields, and went back to the collection page and the items magically appeared. But disappeared again after page re-load.

**Comment by benhaynes** [comment] 2021-01-07 12:58
Thanks, though I meant the Layout Options on the browse items page sidebar.

**Comment by santhosh-sk** [comment] 2021-01-07 13:29
> Thanks, though I meant the Layout Options on the browse items page sidebar.

Yes! The fields are present in the Layout Options in the sidebar 
<img width="274" alt="Screenshot 2021-01-07 at 14 28 22" src="https://user-images.githubusercontent.com/4300016/103898126-c9093c00-50f4-11eb-95dd-94192bd4e6af.png">

**Comment by rijkvanzanten** [comment] 2021-01-07 19:52
Duplicate of https://github.com/directus/directus/issues/3322

**Closed by rijkvanzanten** 2021-01-07 19:52 UTC
Labels: App, Bug

**Comment by santhosh-sk** [comment] 2021-01-13 20:00
@rijkvanzanten https://github.com/directus/directus/issues/3322 has been closed, but I still face this issue with rc.28

**Comment by rijkvanzanten** [comment] 2021-01-13 20:05
@santhosh-sk it's included in rc.29, which isn't out yet
