### ISSUE TITLE
M2M relations: deleted shared property values after adding a new relational item

### ISSUE THREAD

**Issue by dba-io** [directus/directus#8982] opened 2021-10-20 18:43 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a many2many relation between two collections (collectionA and collectionB).
I have given the shared collection (collectionA_B) a property.

When I add a new item to the relation, the values from the property of the shared collection are deleted in the other items.
Just deleting an item does not cause this error, only adding new items.

### To Reproduce

Create to collections and add a m2m relation.
 Add a new property to the shared collection.
Add a new relational item to one of the two collections. 
Add a value to the shared collection property to this relational item.
Add another item to the relation.
Look and the first item you added – the property value disappears.

### Errors Shown

No errors.

### What version of Directus are you using?

v9 rc.96

### What version of Node.js are you using?

v16.11.1

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-10-21 03:07
Should be a duplicate of #8409. Closing in favor of tracking this over there 👍

**Closed by azrikahar** 2021-10-21 03:07 UTC
Labels: Bug (Potential)
