### ISSUE TITLE
/schema/apply returns Cannot read properties of null (reading 'meta')

### ISSUE THREAD

**Issue by ithan** [directus/directus#18787] opened 2023-06-01 08:09 UTC
### Describe the Bug

When trying to migrate 1 snapshot from prod to stage, I get Cannot read properties of null (reading 'meta')

I'm using a 'copy-paste' of the code in https://docs.directus.io/guides/migration/node.html#migrate-your-data-model-with-node-js

I can't share the yml that I need to import due to company policies, but here is a simplified version:

```yml
hash: ~
diff:
  collections:
    - collection: test_collection
      diff:
        - kind: 'N'
          path:
            - meta
            - preview_url
          rhs: null
  fields:
    - collection: test_groups_test
      field: id
      diff:
        - kind: E
          path:
            - schema
            - has_auto_increment
          lhs: false
          rhs: true
  relations:
    - collection: test_extra_properties
      field: test_id
      related_collection: test
      diff:
        - kind: 'N'
          path:
            - schema
          rhs:
            table: test_extra_properties
            column: test_id
            foreign_key_table: test
            foreign_key_column: id
            constraint_name: test_extra_properties_test_id_foreign
            on_update: NO ACTION
            on_delete: SET NULL

```

I'm using directus 10.2.1 dockerized 

### To Reproduce

Create 2 instances of directus with some differences on them, and try to migrate the most up to date one to the previous one  using /schema/apply following the instructions from https://docs.directus.io/guides/migration/node.html#migrate-your-data-model-with-node-js

### Directus Version

10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-06-01 09:39
Duplicate of https://github.com/directus/directus/issues/18774

**Closed by br41nslug** 2023-06-01 09:39 UTC

**Comment by joselcvarela** [comment] 2023-11-14 07:38
For us, we were missing `preview_url` column from `directus_collections` for some reason.
I don't see any bug reported regarding it, so not sure if that was made by us.
Our fix was to create that field manually:
```sql
alter table "directus_collections" add column "preview_url" varchar(255);
```

**Comment by andrew-frank** [comment] 2024-01-13 18:49
I'm missing this column as well, thanks @joselcvarela for the hint! 

I did notice that `preview_url: null` line was deleted in the schema snapshot.. several times in the past. I assumed it was part of a migration and ignored as everything continued to work. 

Before I was using `npx directus` as suggested by the docs, which was pointing to an old `9.x` version, while having my app way beyond `10.x` version. 

Just recently migrated the code using the latest versions and changed the script to use locally locked api and got this error.
