### ISSUE TITLE
Multi select is not working if more than 15 items are selected in directus.(Many-to-Many relation)

### ISSUE THREAD

**Issue by Evankirthi** [directus/directus#17582] opened 2023-02-21 07:14 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I have created a new collection called trainee and many to many relationship exists between user collection and trainee collection. When i try to map multiple trainee with user, its not allowing me to add more than 15 users. For first 15 items its showing the value, for remaining items no value is shown in UI. Even I tried to change the pagination, it's still not working.
I have added the video below to reproduce the issue.

### To Reproduce

https://user-images.githubusercontent.com/86964716/220273776-7b5dfa68-a8d9-49fc-8f8a-9cbc18749eb8.mp4

### Hosting Strategy

Directus Cloud

**Comment by azrikahar** [comment] 2023-02-21 08:23
Closing this as duplicate of #17580, which seems to be exactly identical so it might be an unintentional repeated issue. 👍

**Closed by azrikahar** 2023-02-21 08:23 UTC
