### ISSUE TITLE
Cannot save item in rc.100

### ISSUE THREAD

**Issue by dijs** [directus/directus#9251] opened 2021-10-30 09:32 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/1774430/139527602-fb4f4833-85d9-4648-9927-276d5e677c4e.png)

In this *one* data model type I have, when clicking on the `save` icon in the "new item" user interface, nothing happens.

I can go to an existing item and change data and save just fine. 

Also, I can add other types of items without issue.

While debugging, I noticed that there were *no* network requests when trying to click the save icon.

### To Reproduce

I am not sure how you can reproduce it honestly. Since it could be related to my exact data model structure. But I am happy to share the structure if needed.

### Errors Shown

No errors in console.

### What version of Directus are you using?

rc100

### What version of Node.js are you using?

v14.17.3

### What database are you using?

Postgres

### What browser are you using?

Chrome & Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Heroku

**Comment by azrikahar** [comment] 2021-11-01 11:42
Not sure if this is related, but my scenario is "editing a field & saving it" doesn't work. Here's an example:

https://user-images.githubusercontent.com/42867097/139665545-dc61e509-ab5d-435a-a654-e533639030d3.mp4

> While debugging, I noticed that there were no network requests when trying to click the save icon.

This is the same for my scenario.

Some preliminary investigation leads to this emitted `save` event does get emitted (verified via Vue DevTools), but it isn't triggering the actual save function.

https://github.com/directus/directus/blob/ded3d4b1412a4da711dfaa31e72a4fd4e7e31acc/app/src/modules/settings/routes/data-model/field-detail/field-detail-advanced/field-detail-advanced-actions.vue#L8

This `@save` in <field-detail-advanced> may also be stale since it doesn't really emits save event.

https://github.com/directus/directus/blob/ded3d4b1412a4da711dfaa31e72a4fd4e7e31acc/app/src/modules/settings/routes/data-model/field-detail/field-detail.vue#L18

**Comment by nickvenne** [comment] 2021-11-01 22:48
This happens for all settings in the "Advanced field settings" for me. Like you were saying it saves the first time via Vue, but theres no request that goes to the server to save.

![error_directus](https://user-images.githubusercontent.com/68240042/139751885-9e74cfb8-89de-4d80-beae-27cec13e9401.jpg)
For example, I create a test collection, which as we can see sends a POST request to the server. Then using the new field flow, I create a field which does also send a POST request. Then go to edit the field using the advanced field flow, changed any settings and tried to save. As you can see there were PATCH request to the audit tracking but no PATCH / POST to update the field settings. Hope this helps!

**Comment by rijkvanzanten** [comment] 2021-11-01 22:53
@nickvenne That particular problem was resolved in https://github.com/directus/directus/pull/9324 🙂


 > I am not sure how you can reproduce it honestly. Since it could be related to my exact data model structure. But I am happy to share the structure if needed.

That would be very helpful @dijs

**Comment by dijs** [comment] 2021-11-02 06:15
![image](https://user-images.githubusercontent.com/1774430/139795488-8350e92d-b8a9-41c1-a1aa-7fb59d542b42.png)

@rijkvanzanten

**Comment by azrikahar** [comment] 2021-11-02 06:47
@dijs thanks for sharing! Just as a side note, we can also do schema snapshots (basically creates a yaml/json format of what you shared) so that we can apply it in one go 😄 Reference: https://docs.directus.io/reference/cli/#migrate-schema-to-a-different-environment

With that said, this screenshot is more than enough for us to attempt to reproduce this. Thanks again 👍

**Comment by rijkvanzanten** [comment] 2021-11-02 19:21
One additional thing would be helpful to add to that @dijs:

What rows in directus_fields / directus_collections / directus_relations apply to this same collection? It could be the configuration for a particular field causing issues

**Comment by supermx1** [comment] 2021-11-02 23:05
I have this issue too. It only occurs when I have a conditional field. Now let's say I have 2 fields, A and B... and if A, if an option in A is selected the field B, will be hidden. Now if I try to save, it will not save. It doesn't even show errors. But then if I don't use the condition i.e. I don't click any option with A and I hit save, it saves... Only when I use the conditional options set within Field A from Field B does it trigger this error

**Comment by u12206050** [comment] 2021-11-03 14:30
This occurs for me on all collections on every field. Try to add hints to the field it just doesn't persist the data to the backend.

**Comment by dijs** [comment] 2021-11-06 09:03
@supermx1 I agree, this only applies to data models with conditions it seems. I have tried every permutation that I can think of with my object, but it will not save... :/

**Comment by rijkvanzanten** [comment] 2021-11-06 20:15
@dijs Can you share your directus_fields column? That'd help tremendously in debugging this 👍🏻

**Comment by dijs** [comment] 2021-11-08 08:39
@rijkvanzanten 
![image](https://user-images.githubusercontent.com/1774430/140710074-3f68301e-27e9-44b2-bb4c-34e34ba30811.png)

Here you are

**Comment by dijs** [comment] 2021-11-08 08:44
@rijkvanzanten I just realized, you probably wanted the values.... 

| id  | collection | field | special | interface | options | display | display_options | readonly | hidden | sort | width | group | translations | note | conditions | required |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 7   | message | id  | NULL | input | NULL | NULL | NULL | true | true | 1   | full | NULL | NULL | NULL | NULL | false |
| 8   | message | sort | NULL | input | NULL | NULL | NULL | false | true | 2   | full | NULL | NULL | NULL | NULL | true |
| 9   | message | date_created | date-created | datetime | NULL | datetime | {"relative":true} | true | true | 3   | half | NULL | NULL | NULL | NULL | false |
| 10  | message | date_updated | date-updated | datetime | NULL | datetime | {"relative":true} | true | true | 4   | half | NULL | NULL | NULL | NULL | false |
| 11  | message | type | NULL | select-dropdown | {"choices":\[{"text":"Text","value":"text"},{"text":"Image","value":"image"},{"text":"Video","value":"video"}\],"icon":"announcement"} | raw | NULL | false | false | 5   | half | NULL | NULL | NULL | NULL | true |
| 12  | message | text | NULL | input-rich-text-html | {"toolbar":\["bold","italic","underline","removeformat","customLink","bullist","numlist","h2","h3","code","fullscreen"\]} | formatted-value | {"formatTitle":true,"bold":true} | false | true | 8   | full | NULL | NULL | NULL | \[{"name":"is\_text","rule":{"type":{"\_eq":"text"}},"hidden":false}\] | false |
| 13  | message | active | boolean | boolean | {"iconOn":"check"} | boolean | {"labelOn":"Active","labelOff":"Inactive"} | false | false | 6   | half | NULL | NULL | NULL | NULL | false |
| 14  | message_tag | id  | NULL | input | NULL | NULL | NULL | true | true | NULL | full | NULL | NULL | NULL | NULL | false |
| 15  | message_tag | sort | NULL | input | NULL | NULL | NULL | false | true | NULL | full | NULL | NULL | NULL | NULL | false |
| 16  | message_tag | name | NULL | NULL | NULL | raw | NULL | false | false | NULL | full | NULL | NULL | NULL | NULL | false |
| 17  | message | tags | m2m | list-m2m | {"template":"{{message\_tag\_id.name}}"} | related-values | {"template":"{{message\_tag\_id.name}}"} | false | false | 7   | full | NULL | NULL | NULL | NULL | false |
| 18  | message\_message\_tag | id  | NULL | NULL | NULL | NULL | NULL | false | true | NULL | full | NULL | NULL | NULL | NULL | false |
| 19  | message\_message\_tag | message_id | NULL | NULL | NULL | NULL | NULL | false | true | NULL | full | NULL | NULL | NULL | NULL | false |
| 20  | message\_message\_tag | message\_tag\_id | NULL | NULL | NULL | NULL | NULL | false | true | NULL | full | NULL | NULL | NULL | NULL | false |
| 21  | message | image\_source\_url | NULL | input | {"placeholder":"https://www.host.com/yourimg.jpg","iconLeft":"link"} | raw | {}  | false | true | 9   | full | NULL | NULL | Please type a link here or upload an image | \[{"name":"is\_image","rule":{"type":{"\_eq":"image"}},"hidden":false}\] | false |
| 22  | message | image_upload | NULL | file-image | NULL | image | {"circle":true} | false | true | 10  | full | NULL | NULL | This will be implemented with paid servers only | \[{"name":"is\_image","rule":{"type":{"\_eq":"image"}},"hidden":false}\] | false |

**Comment by dijs** [comment] 2021-11-08 08:45
@rijkvanzanten And last thing, the bug still exists in the new v9 release

**Comment by dijs** [comment] 2021-11-17 14:20
Any update on this? Or possibly a hack to force the saving of an item until we can get this fixed?

**Comment by dijs** [comment] 2021-11-19 16:12
After doing more research into this, it seems to be related to the `SORT` column. This column used to be autofilled when creating a new collection item. It is now NOT autofilling and since the value is **required**, the item would never save, and a proper error was never shown.

@rijkvanzanten

**Comment by rijkvanzanten** [comment] 2021-11-22 20:04
Thanks for the added information @dijs! That makes it the same underlying issue as https://github.com/directus/directus/issues/9176 / https://github.com/directus/directus/issues/9006.  I'll close this as a duplicate 👍🏻

**Closed** 2021-11-22 20:04 UTC
Labels: Duplicate
