### ISSUE TITLE
Existing M2M relationships disappear when adding new relationship field to collection

### ISSUE THREAD

**Issue by log4shell** [directus/directus#11296] opened 2022-01-26 17:03 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I update the data model for an existing collection to add a new M2O relationship, all existing M2M relationships on that collection disappear. I can see from the other end of the M2M relationship that there's still a link from that side to the joining table, but the connection to the modified collection is broken and the relationship is therefore lost.

I have verified that just adding a new text input field does not break the existing M2M relationships, but adding a new M2O relationship to another collection does. Likewise, deleting a M2O relationship from a collection also clears any unrelated M2M relationship on that collection.

### To Reproduce

1. Create three collections, e.g., "A", "B", and "C".
2. In collection "A", add a M2M relationship with collection "B" (and in advanced mode, check the box to automatically create the corresponding M2M relationship in "B" as well)
3. Create one or more items in each collection
4. For an item in collection "A", populate the M2M relationship with an item from collection "B" and save the changes.
5. Navigate to the corresponding item in collection "B" and confirm that it links back to "A" as expected.
6. Update the data model for collection "A" to add a M2O relationship pointing to "C"
7. Navigate back to the items referred to in step 4 & 5 and observe that the M2M relationship between "A" and "B" is broken, i.e., they are no longer linked to each other.
8. Repeat step 4/5 to re-establish the M2M relationship between an item in "A" and "B"
9. Update the data model for collection "A" to remove the previously added M2O relationship pointing to "C"
10. Navigate back to the items referred to in step 8 and observe that the M2M relationship between "A" and "B" is broken again, i.e., they are no longer linked to each other.

### Errors Shown

No errors shown in browser console or server-side logs

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v14.18.3

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

Server: Ubuntu Linux, Client: Windows

### How are you deploying Directus?

Running locally using pm2

**Comment by rijkvanzanten** [comment] 2022-01-26 18:12
Duplicate of https://github.com/directus/directus/issues/10842

**Closed by rijkvanzanten** 2022-01-26 18:12 UTC
Labels: Bug (Potential)
