### ISSUE TITLE
Action events via relationship

### ISSUE THREAD

**Issue by u12206050** [directus/directus#11885] opened 2022-02-28 07:46 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When adding a new registration in my case, via the user, which has a O2M relationship to registrations, the context I use in this hook `action('registrations.items.create', onCreate)` seems to already be used. Ie. `Transaction query already complete`

### To Reproduce

Set up two collections with a O2M relationship between them. Allow inserting a the **Many collection** from the **One collection**

Setup an action on `items.create` for the Many collection whereby you use the given context to make an select and update or something similar.

Create a new item in the **One collection**, and then edit that new item by creating a **Many collection** item through the interface, ie(the drawer on the right should open up)

Once you save the **Many collection item** I don't believe it is actually created just yet until you actually save the **One collection item**

There are now errors, except when I checked the logs. See below.

### Errors Shown

![Screenshot 2022-02-28 at 08 36 30](https://user-images.githubusercontent.com/6641242/155942739-0fc34f7f-0e82-4122-853c-3bb24c6e2758.png)

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

linux

### How are you deploying Directus?

GCP

**Comment by rijkvanzanten** [comment] 2022-02-28 16:05
Action hooks fire "asynchronously" (meaning that we don't `await` for them to be done before saving the item to the database), so it sounds like there's a timing issue here. The actions shouldn't rely on the current transaction, as it isn't guaranteed that it is still active

**Comment by rijkvanzanten** [comment] 2022-02-28 18:50
I believe this is very similar, if not the same as https://github.com/directus/directus/issues/11885. The fix will be the same for both, so lets treat this as a duplicate of https://github.com/directus/directus/issues/11885

**Closed by rijkvanzanten** 2022-02-28 18:50 UTC
Labels: API, Bug (Potential)

**Comment by gkielwasser** [comment] 2022-03-01 16:50
> I believe this is very similar, if not the same as #11885. The fix will be the same for both, so lets treat this as a duplicate of #11885

Didn't you meant #11172 ?

**Comment by rijkvanzanten** [comment] 2022-03-01 17:35
> > I believe this is very similar, if not the same as #11885. The fix will be the same for both, so lets treat this as a duplicate of #11885
> 
> Didn't you meant #11172 ?

yes I did!

**Comment by u12206050** [comment] 2022-04-11 15:01
So seems like this issue is popping back up.

Do I just not make use of the current context when using an action event or?

**Comment by u12206050** [comment] 2022-04-11 15:23
@rijkvanzanten It seems that the context being sent to the action has a database transaction that is already completed.

```
action('registrations.items.create', onCreate)

filter('registrations.items.create', beforeCreate)
```

This  is the output with `DEBUG=knex:tx`

```
knex:tx trx14: Starting top level transaction +16s
  knex:tx trx15: Starting nested transaction +9ms
  knex:tx trx16: Starting nested transaction +1ms
  knex:tx trx17: Starting nested transaction +23ms
  knex:tx trx17: releasing connection +1ms
  knex:tx trx16: releasing connection +1ms
  knex:tx trx15: releasing connection +0ms
  knex:tx trx18: Starting nested transaction +1ms
  knex:tx trx19: Starting nested transaction +1ms
  knex:tx trx19: releasing connection +3ms
  knex:tx trx18: releasing connection +0ms
  knex:tx trx20: Starting nested transaction +8ms
  knex:tx trx21: Starting nested transaction +1ms
  knex:tx trx21: releasing connection +1ms
  knex:tx trx20: releasing connection +1ms
  knex:tx trx14: releasing connection +1ms
  knex:tx trx15: Transaction completed: select `regist………
 …
 Error: Transaction query already complete, run with DEBUG=knex:tx for more info

```

**Comment by rijkvanzanten** [comment] 2022-04-11 16:07
@u12206050 Sounds like it! Lets keep discussing that on https://github.com/directus/directus/issues/11172 🙂
