### ISSUE TITLE
Please more documentation for Extensions - Example not working correctly

### ISSUE THREAD

**Issue by chrisbenjamin** [directus/directus#1823] opened 2017-09-16 18:18 UTC
Hey Team, in my opinion there should be some more documentation for building and using extensions. The example shipped with directus (within customs/extensions folder) doesn't work propperly (see screenshot 1) - that's not the matter.

I know the information you provide
- This is not enough to understand
https://docs.getdirectus.com/6.4.0/#Extensions
- This tutorial/extension also doesn't work and make directus freeze
https://medium.com/directus/how-to-setup-a-custom-extension-770d6ea48551

And also i don't know how to create a custom end point I can reach from outside (like other api endpoints). I tried to reach the example like this:
`http://example.com/api/extensions/example?access_token=token`
But you get a 404.

Some important topics are:
- How can I create an extension, I can reach from outside with Access Token
- How can I manipulate tables from within my extension 

## Version Info
Directus version and branch: develop-branch (today, 11:19 CET)
PHP version: 7.1.9
MySQL version: 5.0.11-dev
Web server: nginx/1.6.2
OS name and version: Debian GNU/Linux 8 (jessie)

## Schema Dump, Logs, or Screenshots
Screenshot 1

<img width="1753" alt="bildschirmfoto 2017-09-16 um 20 08 56" src="https://user-images.githubusercontent.com/569479/30514723-05edff40-9b1b-11e7-8071-f2eefb5715c8.png">

**Comment by WellingGuzman** [comment] 2017-09-16 18:21
How exactly are you creating the endpoints? You can jump into Slack to ask us question or using the `directus` tag on stackoverflow, OR create a ticket in the documentation repo.

This seems more of a question than a bug report. I'm closing it this unless it's an actual bug, I will re-open with proper steps to reproduce.

**Closed by WellingGuzman** 2017-09-16 18:21 UTC

**Comment by rijkvanzanten** [comment] 2017-09-18 14:30
Hi there @chrisbenjamin! Author of the tutorial article here

While I agree the docs are a little sparse (that's already a WIP), I can't reproduce your issues with the two provided examples.

Have you followed every step separately or just downloaded [the example code from GitHub](https://github.com/rijkvanzanten/creating-custom-extensions-example)?

Please let me know if you have any additional info on why [the Medium article](https://medium.com/directus/how-to-setup-a-custom-extension-770d6ea48551) didn't work out for you, as I'd love to get it 💯
