### ISSUE TITLE
ERROR UNCAUGHT TYPEERROR: E.REPLACE IS NOT A FUNCTION ON ONE2MANY RELATION

### ISSUE THREAD

**Issue by horngperng-pxs** [directus/directus#2118] opened 2018-04-11 23:57 UTC
## Version Info : 6.4.8
  - PHP version:  7.1
  - MySQL version:  
  - Web server: (Ex. Apache, nginx or IIS?) : Apache
  - OS name and version: WIndow server running WAMP

Abouts table has relation of O2M with Blocks table. WHen i add new item of Blocks though tables/abouts/new, i got a Uncaught Typeerror e.replace Following is the ss...

1. CREATE NEW ABOUTS
<img width="1379" alt="screen shot 2018-04-12 at 7 49 22 am" src="https://user-images.githubusercontent.com/32503897/38648990-c8db180e-3e26-11e8-9c8d-9135c1a4e63f.png">

2. PRESS ADD NEW ITEM OF BLOCKS
<img width="849" alt="screen shot 2018-04-12 at 7 49 31 am" src="https://user-images.githubusercontent.com/32503897/38648999-d1814b86-3e26-11e8-831d-c6fdc1d88aaa.png">

3. FIELD IN ALL ADD NEW ITEM OF BLOCKS FIELD
<img width="1730" alt="screen shot 2018-04-12 at 7 49 46 am" src="https://user-images.githubusercontent.com/32503897/38649022-eb709100-3e26-11e8-88c1-cbcdcdc88256.png">

4. PRESS SUBMIT AND THIS HAPPENED
<img width="1714" alt="screen shot 2018-04-12 at 7 50 03 am" src="https://user-images.githubusercontent.com/32503897/38649025-f0f4b28c-3e26-11e8-8555-74bb5a5ffc6e.png">

**Comment by rijkvanzanten** [comment] 2018-04-12 00:12
Duplicate of #1906 I've reopened that one

**Closed by rijkvanzanten** 2018-04-12 00:12 UTC
