### ISSUE TITLE
Create an Item GraphQL requires manual ID input.

### ISSUE THREAD

**Issue by RageBrahimi** [directus/directus#5931] opened 2021-05-28 12:02 UTC
Hi! 

It seems that when using mutation on GraphQL it requires an assigned ID although I've selected `Generated UUID` when creating a new Collection

Request:
```
mutation {
  create_articles_item(data: { title: "Hello world!", body: "This is our first article" }) {
    id
    title
  }
}
```

Response:
```
{
  "errors": [
    {
      "message": "GraphQL validation error.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_EXCEPTION",
        "graphqlErrors": [
          {
            "message": "Field \"create_articles_input.id\" of required type \"String!\" was not provided.",
            "locations": [
              {
                "line": 2,
                "column": 29
              }
            ]
          }
        ]
      }
    }
  ]
}
```
I'm not too sure if that's the expected behaviour. Tried the usual with the REST endpoint, works just fine.

**Comment by rijkvanzanten** [comment] 2021-05-28 13:58
Duplicate of https://github.com/directus/directus/issues/5723

**Closed by rijkvanzanten** 2021-05-28 13:58 UTC
