### ISSUE TITLE
6.4.0-beta - new install - Zend error - "Unknown column 'DT.allowed_listing_views'"

### ISSUE THREAD

**Issue by jimborogers** [directus/directus#1414] opened 2017-04-22 20:51 UTC
## Version Info
  - Directus version and branch: 6.4.0-beta
  - PHP version: 5.6.25
  - MySQL version: 5.7.14
  - Web server: Apache 2.4.23
  - OS name and version: Windows Server 2012 R2

## Expected Behavior
Checkout 6.4.0-beta, install, use.

## Actual Behavior
Having following the installation steps at https://docs.getdirectus.com/6.3.6/#Installation, upon requesting the homepage, the attached error relating to Zend occurs:

[directus-zend-error.txt](https://github.com/directus/directus/files/949267/directus-zend-error.txt)

For what it's worth, this is my first time using Directus.

## Steps to Reproduce
 1. Checkout tag 6.4.0-beta
 2. Follow installation instructions at https://docs.getdirectus.com/6.3.6/#Installation
 3. Request Directus homepage

**Comment by WellingGuzman** [comment] 2017-04-22 21:05
Hey @jimborogers, I'm not able to reproduce this error.

Can you share the schema the installation created?

try running `bin/directus db:upgrade` it seems the schema installed is outdated.

**Comment by jimborogers** [comment] 2017-04-23 13:34
Hi @WellingGuzman ,

Here is the schema created:

[directus.txt](https://github.com/directus/directus/files/949743/directus.txt)

I have just tried running `bin/directus db:upgrade` and got the following error:

`db:setup - directus_schema_migrations table created
db:migrate - InsertSystemTableUserColumn - Error executing 'query' with:
INSERT INTO `directus_tables` (`table_name`,`hidden`,`single`,`footer`,`allowed_
listing_views`,`column_groupings`,`primary_column`,`user_create_column`,`user_up
date_column`,`date_create_column`,`date_update_column`) VALUES ('directus_bookma
rks',1,0,0,NULL,NULL,NULL,'user',NULL,NULL,NULL);

Reason: Unknown column 'allowed_listing_views' in 'field list'`

**Comment by WellingGuzman** [comment] 2017-04-23 17:31
I pushed a fix for the migration upgrade.

Although, based on your schema, it seems you installed directs using 6.3.x schema instead of 6.4.x, the table `directus_ui` was deprecated in 6.4.x but your schema has it.

Can you use you the upgrade again, or reinstall accordingly using the 6.4-beta branch?

**Comment by jimborogers** [comment] 2017-04-24 16:46
@WellingGuzman , I created the database schema by running api/schema.sql (https://github.com/directus/directus/blob/version/6.4/api/schema.sql)

This script still includes the `directus_ui` table. Should I be creating my database schema by a different means? Thanks.

**Comment by xorander00** [comment] 2017-04-27 00:07
Running into the same issue.  Looking for the right schema.sql to use, but the most recent one seems to be in version/6.4 branch?

**Comment by WellingGuzman** [comment] 2017-04-27 00:11
Hey. @jimborogers and @xorander00, I forgot to update the `schema.sql` file, please meanwhile install using the installation wizard, or, the CLI (https://docs.getdirectus.com/6.3.6/#Directus_CLI)

I will update the `schema.sql` later today!

**Comment by jimborogers** [comment] 2017-04-27 08:00
Hi @WellingGuzman , using the CLI commands to install the database worked. Please update this issue when schema.sql has been updated and I will happily close it. Many thanks for your help.

**Comment by xorander00** [comment] 2017-04-28 02:17
Got it working with the CLI, thanks!  I'm still getting 404s, but I can tackle that later.  I got a 404 on the previous version when logging in because it would redirect to /user.  However, if I manually chopped that off, it would load fine.  I suspect it might be something in the nginx config, but not sure.  I think it's the same as the sample config in the repo.

The new version isn't loading after a successful login, but that might be because of missing assets?  require.js is complaining, which leads me to believe some assets aren't built.  I'm running gulp build right now.  Let me know what else I should look at, thanks.

**Comment by xorander00** [comment] 2017-04-28 02:24
Heads up, figured out what the 404 issue is.  It's a case-sensitivity issue.

The front-end requests: /app/core/modal.js?bust={cache_busting_random_uuid}

The actual file on the server is: /app/core/Modal.js

Adding ~* to the config didn't fix it because it's caught with the main location block (location / { try_files ... }).  For now I'm going to just find -exec it to lower case, but should have a more permanent fix to this.

**Comment by WellingGuzman** [comment] 2017-04-30 07:11
Hey @xorander00, let me know if this [commit](https://github.com/directus/directus/commit/0c0d3ed7989bdd5c21cce87985256db7d720ee49) fixes it for you?

Also @jimborogers, I updated the `schema.sql`

**Closed by WellingGuzman** 2017-04-30 07:11 UTC
