### ISSUE TITLE
Disappearing entries in the search field

### ISSUE THREAD

**Issue by koksikus** [directus/directus#16615] opened 2022-11-25 09:08 UTC
### Describe the Bug

When I type too quickly in the search field, the numbers or letters I typed disappear, when I delete it too quickly, they show up again. You have to type slowly, not naturally. This is related to refreshing the searched data. Perhaps a better solution would be that when entering data, it must end with pressing the enter key. No error pops up in the console.
However, pasting data is no problem. 
This problem has always occurred to me (in every version of Directus) I do not know what it is related to, maybe some environment variable has not been set correctly.
**I enter numbers from 1 to 9 one by one and then erases.**
### To Reproduce

https://user-images.githubusercontent.com/90528895/203942550-f0fe5ec0-2d86-42e6-bda9-cf3d02d72acc.mp4

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.18.1

### What database are you using?

MS SQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by paescuj** [comment] 2022-11-25 11:32
Cannot reproduce this on Firefox 107.0. Maybe this is an Edge thing?

**Comment by br41nslug** [comment] 2022-11-25 11:58
I have seen this on Firefox and Chrome but it is a hard one to reproduce reliably (harder the faster your pc is)

**Comment by br41nslug** [comment] 2022-11-25 12:34
However i am not able to reproduce this again with throttling and big collections enabled :( This should have been fixed in `9.21.0` so perhaps my testing was on older version too https://github.com/directus/directus/issues/13157 
Closing this issue for now until we can reliably reproduce this on the latest version

**Closed by br41nslug** 2022-11-25 12:34 UTC
Labels: App, Bug

**Comment by paescuj** [comment] 2022-11-25 12:41
> However i am not able to reproduce this again with throttling and big collections enabled

I've just tried the exact same thing 😄 

> his should have been fixed in 9.21.0 so perhaps my testing was on older version too https://github.com/directus/directus/issues/13157

Ah, right! 👍  Haven't noticed that @koksikus was using 9.18.1...
