### ISSUE TITLE
SQL error during creation of entry not handled properly

### ISSUE THREAD

**Issue by dreerr** [directus/directus#15713] opened 2022-09-22 17:42 UTC
### Describe the Bug

I have a SQL table with a unique index which was generated with the command `CREATE UNIQUE INDEX unique_names ON Akteure(lastName,firstName);` 

When trying to enter a duplicate item the Directus backend properly replies with at 400 error on the POST 

In the frontend this error is not reflected, the form is stuck and the following is logged in the browser
<img width="623" alt="Bildschirmfoto 2022-09-22 um 19 12 26" src="https://user-images.githubusercontent.com/1454661/191814762-39f9063c-41b5-436e-9391-ac77c01fb07c.png">

### To Reproduce

* Create an unique index on one or more fields
* Try to input duplicate data

### What version of Directus are you using?

9.18.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

 10.5.12-MariaDB

### What browser are you using?

Safari 15.6

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-09-23 03:33
Seems like this is the same issue as #15033, where the error from MySQL/MariaDB doesn't return the corresponding field causing said error, hence the app isn't "recognizing" the error in order to show it, as mentioned by this comment: https://github.com/directus/directus/issues/15033#issuecomment-1213201936

Closing this as duplicate of #15033, feel free to subscribe to it for future updates 👍

**Closed by azrikahar** 2022-09-23 03:33 UTC

**Comment by azrikahar** [comment] 2022-09-23 03:36
Just to add on a potential workaround in the meantime, you can refer to this comment here: https://github.com/directus/directus/issues/15063#issuecomment-1214528061

**Comment by dreerr** [comment] 2022-09-23 07:56
Great that workaround works, sorry for not having found the duplicated issue!
