### ISSUE TITLE
file upload/select function missing in the wysiwyg 'add/edit link' tool

### ISSUE THREAD

**Issue by stealthsepa** [directus/directus#13022] opened 2022-04-26 21:02 UTC
### Describe the Bug

WYSIWYG editor > add/edit link > V8 had the ability to upload or select a file, in V9 its missing?!

**V8 screenshot**
![image](https://user-images.githubusercontent.com/25691075/165391111-a23440f6-c641-4795-9fe5-d79de4027ca5.png)

**V9 screenshot**
![image](https://user-images.githubusercontent.com/25691075/165390935-a98ccb08-25bb-4693-93c1-ab408a0a167c.png)

### To Reproduce

in V9 create a wysiwyg field > when editing use the 'add/edit link' tool in the wysiwyg toolbar

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

?

### What database are you using?

mysql

### What browser are you using?

brave

### How are you deploying Directus?

virtual server

**Comment by rijkvanzanten** [comment] 2022-04-26 21:07
Duplicate of https://github.com/directus/directus/discussions/6605

**Closed by rijkvanzanten** 2022-04-26 21:07 UTC
Labels: Bug (Potential)
