### ISSUE TITLE
Can't apply snapshot on "dirty" db

### ISSUE THREAD

**Issue by GalynaDemchenko** [directus/directus#16418] opened 2022-11-11 17:07 UTC
### Describe the Bug

I have very strange but upsetting problem. Our product is based on adonisjs. We included directus there. And if moving to another env it doesnt apply snapshots.

If we try to apply snapshot (collections from adonis and from directus) to empty db it works well. But if on already changed db - it doesn't applies. And no error.

I'll be very thankful for any idea/suggestion

### To Reproduce

1. Migrate adonis
2. Add directus
3. Create snapshot (it contains collections from adonis and from directus)
4. Create new environment
5. Migrate adonis' migrations on new env.
6. Try to apply directus snapshot to that new db - zero result

### Errors Shown

No errors

### What version of Directus are you using?

9.10.4

### What version of Node.js are you using?

16.18.0

### What database are you using?

Postgres v14

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2022-11-12 00:50
Duplicate of https://github.com/directus/directus/discussions/16417

**Closed by rijkvanzanten** 2022-11-12 00:50 UTC
