### ISSUE TITLE
SQLite doesn't support Directus Map field

### ISSUE THREAD

**Issue by dbelyaeff** [directus/directus#21597] opened 2024-02-27 09:55 UTC
### Describe the Bug

It seems like Directus Map field isn't compatible with Map field.

### To Reproduce

1. Latest Directus image from Docker Hub (10.9.2).
2. SQLite database.
3. New collection "Events" created.
4. Field type "Map" added to collection. With basic settings, no tuning.
5. Trying to open collection in Directus Studio (admin/content/events) and got error:
```
{
  "errors": [
    {
      "message": "select `events`.`datetime`, `events`.`description`, st_astext(`events`.`map`) as `map`, `events`.`title`, `events`.`id` from `events` order by `events`.`sort` asc limit 25 - SQLITE_ERROR: no such function: st_astext",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### Directus Version

10.9.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-02-27 10:15
Duplicate of #10648, see also https://github.com/directus/directus/issues/13271#issuecomment-1125803515

Side notes:
- If Spatialite isn't installed, a warning is logged on server startup:
  ```console
  WARN: Spatialite isn't installed. Geometry type support will be limited.
  ```
- The easiest way to get geospatial data support is by using the PostGIS image as documented here: https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose

**Closed by paescuj** 2024-02-27 10:15 UTC
