### ISSUE TITLE
Existing item added in M2M field does not show display value

### ISSUE THREAD

**Issue by kaziller** [directus/directus#10479] opened 2021-12-13 16:21 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

On 9.2.2:
After adding an existing item in a M2M field, the added item does not show the correct display value set in the configuration.
This bug does not occur, when a new item is created with "Create New".

https://user-images.githubusercontent.com/23482966/145847171-d8b017a7-2b30-48b2-b193-a7e07bbceb1e.mp4

### To Reproduce

- Create a collection `available_languages` with primary key `id` uuid and some string inputs (in my example `code` and `name`)
- Use advanced creation mode: Create a collection `general`
- Create a M2M field related to `available_languages` in `general` 
- Go to Interface and choose `code` as Display Template -> Save
- Create some items in `available_languages`
- Try creating a new `general` item, using the M2M field to add existing `available_languages` to it

### Errors Shown

No errors are shown.

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by ilijaNL** [comment] 2021-12-13 16:32
duplicate of #10476

**Comment by joselcvarela** [comment] 2021-12-13 17:58
Thank you @kaziller  but @ilijaNL already opened an issue regarding this. Let's follow there #10476

**Closed by joselcvarela** 2021-12-13 17:58 UTC
Labels: Bug (Potential)
