### ISSUE TITLE
Presentation & Aliases  - Field translation not used

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#5921] opened 2021-05-28 04:05 UTC
The `Presentation & Aliases` field translations are not used / useless.

If I create a divider for example, the Title of the Divider is not translateable (the field translation isn't used), so I don't have the possibility to properly use the `Presentation & Aliases` fields for a multi language interface.

**Comment by benhaynes** [comment] 2021-05-28 13:28
@rijkvanzanten — should we use the Field Name/Key instead of the Interface Option (`title`) for this? Might be a bit simpler and provide i18n support. Any downside to using the field name... other than being a breaking change?

**Comment by rijkvanzanten** [comment] 2021-05-28 14:05
This is the discussion of making interface option values translatable, like input placeholders, divider titles, note body contents, etc etc (https://github.com/directus/directus/discussions/3075).

Right now, it already kinda works by adding a `$t:` prefixed value as key, but that's not the most user friendly / scalable. 

Duplicate of https://github.com/directus/directus/discussions/3075

**Closed by rijkvanzanten** 2021-05-28 14:05 UTC
Labels: App, Extensions, Improvement, Question
