### ISSUE TITLE
conditional fields do not work when use file field object

### ISSUE THREAD

**Issue by laekem34** [directus/directus#10365] opened 2021-12-07 10:20 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using filters on field which uses a file field property, filter doesn't work.

### To Reproduce

- Add a file field on a data model
- add another field/notice on the same data model and add condition filter like `File->Type Mime equal application/pdf` . Make the field hidden if condition is true
- Go on "Content" and create an item. At this step you should see the both fields
- Add a pdf file to the first field
- The other field will not disapear

### Errors Shown

No error logged

### What version of Directus are you using?

9.2.0

### What version of Node.js are you using?

15.0.1

### What database are you using?

sqlite3@5.0.2

### What browser are you using?

chrome

### What operating system are you using?

Windows_NT 10.0.19042

### How are you deploying Directus?

npx directus start

**Comment by cpt-n3mo** [comment] 2021-12-09 15:07
Good day..
this seems to also happen with other conditionals.. it does not seem to save the actual condition, as in if something is equal to x,
x is never stored and so conditions will never run..

regards

**Comment by azrikahar** [comment] 2021-12-13 09:18
Duplicate of #9740. For more info on why it's not working: https://github.com/directus/directus/issues/9740#issuecomment-967133704. Let's close this while we consolidate this issue over there.

**Closed by azrikahar** 2021-12-13 09:18 UTC
Labels: App, Bug
