### ISSUE TITLE
Logical operators to filter service data isn't working after upgrade

### ISSUE THREAD

**Issue by TarekTolba1** [directus/directus#22805] opened 2024-06-20 08:49 UTC
### Describe the Bug

I've a custom endpoint that uses ItemsService with a filter that includes "and" logical operator to fetch some data. This used to work on 9.18.1 but after upgrading to 10.12.1 it's not working anymore with an error thrown.

Code:
```
      const filter = {
        transfer_languages: {
          _and: [
            {
              language: { _eq: transferLang },
            },
            {
               publishing_status: { _eq: "published" },
             },
          ],
        },
      };
   const courses = await courseService.readByQuery({
        filter,
        fields,
      });
```

Error:
```
database      | 2024-06-20 07:48:01.888 UTC [50] ERROR:  invalid input syntax for type integer: "{"NaN","NaN"}"
database      | 2024-06-20 07:48:01.888 UTC [50] CONTEXT:  unnamed portal parameter $1 = '...'
database      | 2024-06-20 07:48:01.888 UTC [50] STATEMENT:  select "course"."id", "course"."translated_title", "course"."translated_subtitle" from "course" inner join (select distinct "course"."id", "course"."id" as "sort_rxhvt" from "course" left join "transfer_language" as "ijycw" on "course"."id" = "ijycw"."course" where "ijycw"."id" = $1 order by "course"."id" asc limit $2) as "inner" on "course"."id" = "inner"."id" order by "inner"."sort_rxhvt" asc
directus      | [07:48:01.890] ERROR: select "course"."id", "course"."translated_title", "course"."translated_subtitle" from "course" inner join (select distinct "course"."id", "course"."id" as "sort_rxhvt" from "course" left join "transfer_language" as "ijycw" on "course"."id" = "ijycw"."course" where "ijycw"."id" = $1 order by "course"."id" asc limit $2) as "inner" on "course"."id" = "inner"."id" order by "inner"."sort_rxhvt" asc - invalid input syntax for type integer: "{"NaN","NaN"}"
directus      |     err: {
directus      |       "type": "DatabaseError",
directus      |       "message": "select \"course\".\"id\", \"course\".\"translated_title\", \"course\".\"translated_subtitle\" from \"course\" inner join (select distinct \"course\".\"id\", \"course\".\"id\" as \"sort_rxhvt\" from \"course\" left join \"transfer_language\" as \"ijycw\" on \"course\".\"id\" = \"ijycw\".\"course\" where \"ijycw\".\"id\" = $1 order by \"course\".\"id\" asc limit $2) as \"inner\" on \"course\".\"id\" = \"inner\".\"id\" order by \"inner\".\"sort_rxhvt\" asc - invalid input syntax for type integer: \"{\"NaN\",\"NaN\"}\"",
directus      |       "stack":
directus      |           error: select "course"."id", "course"."study_course", "course"."translated_title", "course"."translated_subtitle" from "course" inner join (select distinct "course"."id", "course"."id" as "sort_rxhvt" from "course" left join "transfer_language" as "ijycw" on "course"."id" = "ijycw"."course" where "ijycw"."id" = $1 order by "course"."id" asc limit $2) as "inner" on "course"."id" = "inner"."id" order by "inner"."sort_rxhvt" asc - invalid input syntax for type integer: "{"NaN","NaN"}"
directus      |               at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
directus      |               at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:122:29)
directus      |               at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:35:38)
directus      |               at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/index.js:11:42)
directus      |               at Socket.emit (node:events:517:28)
directus      |               at addChunk (node:internal/streams/readable:368:12)
directus      |               at readableAddChunk (node:internal/streams/readable:341:9)
directus      |               at Readable.push (node:internal/streams/readable:278:10)
directus      |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus      |       "length": 151,
directus      |       "name": "error",
directus      |       "severity": "ERROR",
directus      |       "code": "22P02",
directus      |       "where": "unnamed portal parameter $1 = '...'",
directus      |       "file": "numutils.c",
directus      |       "line": "320",
directus      |       "routine": "pg_strtoint32"
directus      |     }
```

If the _and operator is removed and only one of the two conditions is used, the execution works properly
```
      const filter = {
        transfer_languages: {
            language: { _eq: transferLang },
        },
      };
```

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 14.5

**Comment by hanneskuettner** [comment] 2024-06-20 08:59
Judging from the DB error it looks like your `transferLang` is not an integer but rather an object? Mind checking what the value of `transferLang` is and reporting back?

**Comment by TarekTolba1** [comment] 2024-06-20 11:17
transferLang is a String (language iso-code, ex. "EN"). While transfer_languages.language is a collection with iso_code (String) is the primary key as well

**Comment by TarekTolba1** [comment] 2024-06-26 21:38
@hanneskuettner Also I am getting an error for this filter:
```   const filter = {
        transfer_languages: {
          _or: [
            {
              publishing_status: { _eq: "published" },
            },
            {
              publishing_status: { _eq: "available_for_testing" },
            },
          ],
        },
      };
 ```
 ```
 error: select "course"."id", "course"."translated_title", "course"."translated_subtitle" from "course" inner join (select distinct "course"."id", "course"."id" as "sort_zvhbf" from "course" left join "transfer_language" as "avopt" on "course"."id" = "avopt"."course" where "avopt"."id" = $1 order by "course"."id" asc limit $2) as "inner" on "course"."id" = "inner"."id" order by "inner"."sort_zvhbf" asc - invalid input syntax for type integer: "{"NaN","NaN"}"
directus      |               at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
directus      |               at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:122:29)
directus      |               at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:35:38)
directus      |               at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/index.js:11:42)
directus      |               at Socket.emit (node:events:517:28)
directus      |               at Socket.emit (node:domain:489:12)
directus      |               at addChunk (node:internal/streams/readable:368:12)
directus      |               at readableAddChunk (node:internal/streams/readable:341:9)
directus      |               at Readable.push (node:internal/streams/readable:278:10)
directus      |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
directus      |       "length": 151,
directus      |       "name": "error",
directus      |       "severity": "ERROR",
directus      |       "code": "22P02",
directus      |       "where": "unnamed portal parameter $1 = '...'",
directus      |       "file": "numutils.c",
directus      |       "line": "320",
directus      |       "routine": "pg_strtoint32"
directus      |     }

**Comment by hanneskuettner** [comment] 2024-06-26 21:50
The filter you posted does not seem to correspond to the query cited in the error message as the whole where clause of the filter seems to be missing. Is that still the same service you're calling? Can you provide more detail on the whole course collection? Are there any filter hooks or flows manipulating the query before it hit's the database? 

It looks like the first parameter of the query, so the one that is used in the `where "avopt"."id" = $1` part  (which correlates to `transfer_language.id = $1`), fails because it receives an object instead of an integer?

**Comment by TarekTolba1** [comment] 2024-06-26 23:45
@hanneskuettner I created this minimal example project and I was able to reproduce the issue there.
https://github.com/TarekTolba1/filter-example
Hopefully, you will be able to apply the schema without any issues.

Please check it and let me know if you are able to reproduce the issue on your side

**Comment by hanneskuettner** [comment] 2024-06-27 05:37
Thank you for the reproduction. That definitely helped me debug the issue. 

I'm afraid to tell you, that the problem here is the filter itself. I don't know if that changed from v9 but as it stand logical filter operators are not allowed to be nested in filter rules, see https://docs.directus.io/reference/filter-rules.html#logical-operators

So the correct filter syntax for your case is 

```js
{
    _or: [
    	{
    		transfer_languages: {
    			publish_status: { _eq: 'published' },
    		},
    	},
    	{
    		transfer_languages: {
    			publish_status: { _eq: 'available_for_testing' },
    		},
    	},
    ],
}
```

Hope this helps! 

I'm gonna close this issue now, but I will open another one since I think there needs to be an error message if you are attempting to nest logical operators within filter operations.

**Closed by hanneskuettner** 2024-06-27 05:37 UTC
Labels: :detective: Needs More Info

**Comment by TarekTolba1** [comment] 2024-06-27 08:05
Thank you, that definitely help! 
This is different from how it was in v9, but now it works perfectly 🚀
