### ISSUE TITLE
[9.21.0] directus schema apply doesn't work

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#16604] opened 2022-11-24 15:30 UTC
### Describe the Bug

After update to `9.21.0`, the directus schema apply doesn't work:

<img width="1256" alt="Screenshot 2022-11-24 at 10 26 06 AM" src="https://user-images.githubusercontent.com/1007051/203820416-5ca3c197-eba9-4708-ab7b-be9a2293d238.png">

Also with `LOG_STYLE=raw` because of https://github.com/directus/directus/issues/16284:

<img width="1521" alt="Screenshot 2022-11-24 at 10 34 22 AM" src="https://user-images.githubusercontent.com/1007051/203821640-d06e5498-efaf-4e72-b8dc-a1d144e5aca9.png">

We run: `npx directus schema apply schema.yaml --yes` and it never ends.

It works if we go back to `9.20.4`.

### To Reproduce

Just run:

`npx directus schema apply schema.yaml --yes`

### What version of Directus are you using?

9.21.0

### What version of Node.js are you using?

18

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by licitdev** [comment] 2022-11-24 15:43
Duplicate of #16503

**Closed by licitdev** 2022-11-24 15:43 UTC
Labels: Duplicate
