### ISSUE TITLE
WYSIWYG Insert/edit image no image chooser

### ISSUE THREAD

**Issue by AndreyKindin** [directus/directus#3178] opened 2020-11-24 14:06 UTC
Hi,
in WYSIWYG under Insert/edit image there is only the possibility to enter file source but not to select an image from the file library.

### Project details
Directus Version: 9.0.0-rc.17
Environment: production
Node: 14.11.0

**Comment by benhaynes** [comment] 2020-11-24 14:25
Duplicate of: https://github.com/directus/directus/issues/3160

**Closed by benhaynes** 2020-11-24 14:25 UTC
