### ISSUE TITLE
Main color changed

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#11985] opened 2022-03-06 10:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

App interface became pink instead of classic green when updated to the last version.
![pink](https://user-images.githubusercontent.com/18073828/156920117-4789c99a-ff95-4b72-83c2-2fde770e0826.jpg)

### To Reproduce

- Log in
- Interface color changed
- No setting gives the ability to change main color

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

14.16.1

### What database are you using?

MySQL 5.7.14

### What browser are you using?

Firefox

### What operating system are you using?

Linux CentOs

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-03-06 11:19
This is actually a change in #11952 and not a bug. It is to align with the new branding which are already present as seen in https://directus.io and https://docs.directus.io.

That said, there is plan to add theming/color customizations to make things easier via app settings as mentioned here: https://github.com/directus/directus/discussions/11969#discussioncomment-2300691. Feel free to share your thoughts on it as well!

In the meantime, you can definitely change them to fit your preference via Custom CSS 👍 Here's a snippet to change the navigation icon color as an example: https://github.com/directus/directus/pull/11952#issuecomment-1059930445

I'll proceed to close this as it's not an actual bug here.

**Closed by azrikahar** 2022-03-06 11:19 UTC
Labels: Bug (Potential)

**Comment by neo7-studio-web** [comment] 2022-03-06 19:42
I'm so sorry... that was a brutal change to me and I must say... I'm not a huge fan of this new color for dark mode, but it's a world of infinite tastes.
Thanks for the info about changes coming and what can be done already, I appreciate !

**Comment by benhaynes** [comment] 2022-03-06 19:56
I get it @neo7-studio-web!! We wanted to use the same `primary` for Dark Mode, but the contrast was horrendous. We're actively working on a theme builder that we were _hoping_ would be ready for this release... but it wasn't. Should be out soon though. Thanks for bearing with us!

**Comment by neo7-studio-web** [comment] 2022-03-06 20:15
> I get it @neo7-studio-web!! We wanted to use the same `primary` for Dark Mode, but the contrast was horrendous. We're actively working on a theme builder that we were _hoping_ would be ready for this release... but it wasn't. Should be out soon though. Thanks for bearing with us!

No worry Ben, you guys are doing such a great job. With the simple above instructions I managed to get back the previous green theme for dark mode, that's fine ! Thank you

**Comment by chernandezweb** [comment] 2022-03-07 01:50
You can add something like this in the custon CSS box to change it ;)

body.dark{
--primary: #299b8b !important;
}

**Comment by neo7-studio-web** [comment] 2022-03-07 07:38
Actually I managed to get the previous green aspect by applying what is mentioned here in the CSS box :
https://github.com/directus/directus/discussions/11969#discussion-3917735

(replacing blue by green, also works with yellow, purple...)

**Comment by sensedrive** [comment] 2022-03-08 09:43
> This is actually a change in #11952 and not a bug. It is to align with the new branding which are already present as seen in https://directus.io and https://docs.directus.io.
> 
> I'll proceed to close this as it's not an actual bug here.

I think you really should not push such a change, without a "real" possibility to change the color through the settings. This sounds like a nogo for me. Just upgraded to 9.6.0 and the layout looks right messy for the customer right now.

Well ... thank you for your help anyway.

**Comment by benhaynes** [comment] 2022-03-08 14:53
@sensedrive — I understand the frustration, but there is a "real" way to make that change. We included the code template directly in the CSS override for easier access.

When you say the layout looks "messy", what do you mean? Are you saying the color changing from green made the whole layout messy?

**Comment by sensedrive** [comment] 2022-03-08 15:01
@benhaynes It's just the colores. Sometimes enough to get a call.

> @sensedrive — I understand the frustration, but there is a "real" way to make that change. We included the code template directly in the CSS override for easier access.

Sounds like a very good solution. Many thanks!
