### ISSUE TITLE
Project Logo / Favicon return 403 after update to 10.9.0

### ISSUE THREAD

**Issue by danhstevens** [directus/directus#21377] opened 2024-02-08 18:24 UTC
### Describe the Bug

When specifying a custom image for the Project Logo and Favicon (and perhaps background / foreground) the image no longer displays in the UI and a `403 Forbidden` error is returned from the server:

```json
{
	"errors": [
		{
			"message": "You don't have permission to access this.",
			"extensions": {
				"code": "FORBIDDEN"
			}
		}
	]
}
```

Deleting and re-uploading the assets do not appear to help

![image](https://github.com/directus/directus/assets/1061040/4aa46a44-6653-4aae-9daf-40aac07078c6)
Image displays in the Appearance Settings window, and in the file library

![image](https://github.com/directus/directus/assets/1061040/a80ab274-d895-4f40-abe6-e5f6f916b9dc)
But is absent in the logo section of the UI and is the result of a `403` response from the server

### To Reproduce

- Upgrade a project that has a custom logo / favicon from v10.8.3 to v10.9.0 (perhaps optional)
- Try to view the custom logo / favicon in the UI

### Directus Version

v10.9.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2024-02-08 18:25
Duplicate of https://github.com/directus/directus/issues/21359
A fix has been merged and will be available on the next release

**Closed by br41nslug** 2024-02-08 18:25 UTC
