### ISSUE TITLE
Server error when editing an item from a M2M overlay

### ISSUE THREAD

**Issue by peremp** [directus/directus#1752] opened 2017-08-21 15:02 UTC
## Version Info
  - Directus version and branch: Devel latest.

## Steps to Reproduce
 1. Edit an item that has a M2M column.
 2. Click on a related item to edit it.
 3. Edit the item (overlay).
 4. Save (overlay)
 5. Save (main item)

## Expected Behavior
Item is saved. You are redirected to the /table/xxxx list view.

## Actual Behavior
Item is saved. You are not redirected, and the following error appears:
```Attempted to load new record post-insert with empty result. Lookup via row id:```

Looks like directus is trying to redirect to an empty row id.

**Comment by WellingGuzman** [comment] 2017-08-21 17:34
Hey @peremp,

How does your related (m2m) table looks like? does it have relational column? can you share an schema that help us reproduce this issue?

**Comment by peremp** [comment] 2017-08-22 09:38
I'll send you the schema via Slack

**Comment by peremp** [comment] 2017-09-05 10:48
Trying to make a new schema to you, I realized that this problem is easy to reproduce (at least on 6.4.2). 

You just need 3 tables:
- problems (id, title, status)
- solutions (id, title, status)
- use_cases (id, problem_id, solution_id)

Then:
- Add a M2M to both, problems and solutions, using `use_cases` as junction.
- create a problem
- create a solution
- edit the problem and relate the created solution to the problem.

The error `Attempted to load new record post-insert with empty result. Lookup via row id:` appears.

**Comment by WellingGuzman** [comment] 2017-09-05 16:08
Thanks @peremp I will give it a shot this time.

**Comment by peremp** [comment] 2017-09-06 07:20
Update for this issue:

Following the previous schema, I found that when I create an item (a problem or a solution), and I go to edit it, an empty item appears on the M2M list:

![scrn1](https://user-images.githubusercontent.com/20085260/30098779-ab7dcd90-92e3-11e7-8812-d0a707891e70.png)


When I add another item to the list and save, the error appears:

![lookup-error](https://user-images.githubusercontent.com/20085260/30098792-b9ba13d2-92e3-11e7-980a-ff2d543179d4.png)

**BUT** if I remove the empty item, it works.


The error also appears if I add an item on creation.

![scrn2](https://user-images.githubusercontent.com/20085260/30098922-3ac582ae-92e4-11e7-9158-c28c3e3a2f54.png)

In this case, the problem is created but without the related solution. Maybe the error here is the same... the collection have an "empty" value, that makes it crash.

**Comment by peremp** [comment] 2017-09-07 09:33
More info about the error:
The error comes from the backend when doing the PATCH: `http://localhost:8282/api/1.1/tables/probs/rows/6) 500 (Internal Server Error)`

And this is the API response:

```
{
  "success":false,
  "error":{
    "message":"Attempted to load new record post-insert with empty result. Lookup via row id: "
  },
  "code":0,
  "class":"RuntimeException",
  "file":"\/var\/www\/html\/api\/core\/Directus\/Database\/TableGateway\/RelationalTableGateway.php",
  "line":193
}
```

**Comment by WellingGuzman** [comment] 2017-09-07 09:43
Hey @peremp, can you share the payload JSON?

**Comment by peremp** [comment] 2017-09-07 12:57
```
{"problems":[{"meta":{"table":"use_cases","type":"collection","total":0,"Draft":1,"Deleted":0,"Published":0,"total_entries":1},"data":{}},{"data":{"id":1}}]}
```

**Comment by WellingGuzman** [comment] 2017-09-07 20:21
Hey @peremp is that the request payload/body?

**Comment by peremp** [comment] 2017-09-08 07:12
yep, it's the request payload

**Comment by WellingGuzman** [comment] 2017-09-10 03:14
I'd really need the schema that we can use to reproduce this issue, there shouldn't any way that the meta data was sent as payload data. This may be a rare bug.

**Comment by WellingGuzman** [comment] 2017-09-10 03:14
Please note, that I've used the schema you shared with us before, but it's working as expected, so maybe there's something missing.

**Comment by benhaynes** [comment] 2017-09-13 23:08
Hey @peremp – any schema we can take a look at to reproduce? :)

**Comment by peremp** [comment] 2017-09-14 08:18
Sure, I'll send it to @WellingGuzman via Slack

**Comment by WellingGuzman** [comment] 2017-09-16 05:11
After looking at this carefully I fixed this bug.

Closed byhttps://github.com/directus/directus/commit/e17d1f5b2cb438bef3ec68485aeae458371c07fe

@peremp please confirm, otherwise I will reopen.

**Closed by WellingGuzman** 2017-09-16 05:11 UTC
Labels: 3. Major, Bug, Interface, Relational
