### ISSUE TITLE
null required values produce a 500 when posting

### ISSUE THREAD

**Issue by ghost** [directus/directus#4332] opened 2021-03-01 10:48 UTC
When POSTing a new /item/ to the REST API, if the item includes string fields that are marked "required" but are null, the API will throw a 500 (rather than the expected 400 with validation errors in the body).

Project Details:
Directus Version: 9.0.0-rc.44
Database: Postgresql 9.6
Node: 14.15.4
OS: Windows 10

**Comment by rijkvanzanten** [comment] 2021-03-04 00:01
I just setup a new collection in a fresh installation, with a single text field marked as "Required":

![CleanShot 2021-03-03 at 19 00 32@2x](https://user-images.githubusercontent.com/9141017/109889109-c0476900-7c52-11eb-8932-feb53c43e651.png)

However, when posting `null` as the value:

```json
{
  "required": null
}
```

it correctly returns a 400 error:

```json
{
  "errors": [
    {
      "message": "\"required\" contains an invalid value",
      "extensions": {
        "field": "required",
        "type": "nnull",
        "code": "FAILED_VALIDATION"
      }
    }
  ]
}
```

---

@adam-axis Would you be able to share a DB dump where this is happening?

**Comment by adam-axis** [comment] 2021-03-13 06:07
Oddly I can no longer reproduce this as a 500 error. However, for string fields using the text input interface with "save empty values as null" set to false, the it is still producing nulls.

This means the API returns the "NOT_NULL_VIOLATION" error rather than "FAILED_VALIDATION", which breaks the v-form validation errors system.

**Comment by nickrum** [comment] 2021-03-15 13:22
The name of the "save empty values as null" option is unfortunately a bit misleading. It only changes the value submitted to the API from `NULL` to an emtpy string when you delete the content from a text input field.

**Comment by benhaynes** [comment] 2021-04-02 18:23
Do we still need more info on this or can we replicate it? The OP account is gone, so we're on our own here!

**Comment by rijkvanzanten** [comment] 2021-04-02 19:06
Seeing the OP is gone, and couldn't reproduce the original issue themselves either, we'll have to consider it not a problem 🤷🏻

**Closed by rijkvanzanten** 2021-04-02 19:06 UTC
Labels: Needs More Info
