### ISSUE TITLE
Unable to add images to an image field after update to 9.12.2

### ISSUE THREAD

**Issue by TomSmedley** [directus/directus#14139] opened 2022-06-27 16:48 UTC
### Describe the Bug

https://www.loom.com/share/3d801cec7a3841fda42970b8d81c9c44

I am no longer able to add images to the CMS image field after update. Uploading a file will in fact work, but it will not store within the field.

### To Reproduce

I'm assuming not everyone has this issue as it will be widely reported and quickly patched. I'm using PostgreSQL so I'm unsure if that has anything to do with it. 

### Errors Shown

No error is shown, or console logged.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

NPM

**Comment by josias-r** [comment] 2022-06-28 08:20
Beautiful website 😄

**Comment by rijkvanzanten** [comment] 2022-06-28 20:11
What exact version of Chrome are you using? It seems to work as expected on my end on Chrome 103.0.5060.53, Edge 103.0.1264.37, Firefox 103.0b1

**Comment by rijkvanzanten** [comment] 2022-06-28 21:05
I'll close this for now, as we're not able to reproduce this, and it doesn't seem to happen to others. Happy to keep discussing and we'll obv reopen if more info becomes available 🙂

**Closed by rijkvanzanten** 2022-06-28 21:05 UTC
Labels: Can't Reproduce
