### ISSUE TITLE
Wrong ID used when trying to access parent related content using UUIDs as PK

### ISSUE THREAD

**Issue by eXsiLe95** [directus/directus#9713] opened 2021-11-11 09:21 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using a M2M relation and having two parents on an item, which both have uuids as PK (instead of increasing ids), you cannot access those via the link shown in the items view. Instead of using the uuid of the related item, a int id is used in order to redirect to the related item's page.

### To Reproduce

1. Create a model and use uuids as PK
2. Create another model and use uuids as PK
3. Inside one of the models, create a M2M relation on the other model
4. Create two parent items
5. Create one child item and relate the two parent items
6. Go to item view and show the related items
7. Click on the "Show related item" button next to the related content's uuid

![image](https://user-images.githubusercontent.com/31202904/141271507-8fc10f11-d437-45ca-a351-5a1aac3f644d.png)

### Errors Shown

As you can see in the screenshot above, directus will redirect you to to the table which connects the two models. Here, nothing is shown.

I would expect directus to redirect me to the related content using the related content's uuid.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgis/postgis:13-master

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker (using docker-compose)

**Comment by azrikahar** [comment] 2021-11-11 09:43
This should be a duplicate of #9451. Confirmed that the PR addressing that issue also solves this particular issue 👍

**Closed by azrikahar** 2021-11-11 09:43 UTC
Labels: Bug (Potential)
