### ISSUE TITLE
Collection Navigation Broken

### ISSUE THREAD

**Issue by Slations** [directus/directus#9498] opened 2021-11-04 23:09 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I can create folders in the Data Model without a problem but they no longer appear when your editing permissions on roles so users cannot see them and also cannot view anything in them meaning I've had to remove them.

I have also setup the Collection Navigation at the bottom of the roles but these don't work anymore either meaning you cannot group data anymore making it difficult to use.

On a side note please bring back the old group design with the title and line rather than folders as it just looks really confusing :/ 

### To Reproduce

Create collections then put them in a folder and login with a user on a non admin role.

### Errors Shown

N/A

### What version of Directus are you using?

v9.0.0-rc.101

### What version of Node.js are you using?

16.6.1

### What database are you using?

MariaDB

### What browser are you using?

Edge (Chrome)

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by rijkvanzanten** [comment] 2021-11-05 00:22
Duplicate of https://github.com/directus/directus/issues/9207

**Closed by rijkvanzanten** 2021-11-05 00:22 UTC
Labels: Bug (Potential)
