### ISSUE TITLE
Error when running create with SQLite

### ISSUE THREAD

**Issue by jroxendal** [directus/directus#3207] opened 2020-11-26 10:38 UTC
Running `yarn create directus-project my-project` and picking SQLite causes this error:

```
Something went wrong while seeding the database:

undefined Method implemented in the dialect driver

Please try again
```

SQLite version is the MacOS Catalina one: `3.28.0`

**Comment by rijkvanzanten** [comment] 2020-11-26 14:39
Duplicate of https://github.com/directus/directus/issues/2904

**Closed by rijkvanzanten** 2020-11-26 14:39 UTC
Labels: Bug, DB: SQLite
