### ISSUE TITLE
WYSIWYG field - filtering for special characters

### ISSUE THREAD

**Issue by ksawery-brzeski** [directus/directus#22555] opened 2024-05-23 16:23 UTC
### Describe the Bug

I have discovered that search for WYSIWYG fields is somewhat flawed. If you add some special character via the editor, it will be escaped in the actual html of the WYSIWYG. 

When filtering you are not able to search for this value. Looks like the search treats the generated HTML as text

### To Reproduce

1. Create a collection
2. Add a WYSIWYG field to it
3. Create a record.
4. In the WYSIWYG field, insert some value with a special character, say ` < 2` and save the record
5. Filter for records containing ` < 2` - no records will be returned
6. Filter for `<p>&nbsp;&lt; 2</p>` - the record will be filtered

### Directus Version

v10.10.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-05-23 16:29
Duplicate of https://github.com/directus/directus/issues/19777

**Closed by br41nslug** 2024-05-23 16:29 UTC
