### ISSUE TITLE
Values not shown on edit for m2o

### ISSUE THREAD

**Issue by TonyWar** [directus/directus#7478] opened 2021-08-18 08:18 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a Todo collection with m2m relation to Todo Data, in Todo Data I have a m2o relation to Event Type.
When I want to Edit m2m item, the m2o field is empty (even if It has some value).
![image](https://user-images.githubusercontent.com/35558401/129862890-00c77d65-d1bb-4e1f-b941-a5a151019054.png)
![image](https://user-images.githubusercontent.com/35558401/129862924-45b97778-37c7-4341-8a9b-1d40b408f144.png)
![image](https://user-images.githubusercontent.com/35558401/129862941-3a2f26e5-6435-4b59-8e74-b7543f675898.png)

### To Reproduce

1. Create a collection, which you will use for m2o relation (event_type with string field)
2. Create a collection with m2o relation with previous one (ex. todo_data)
3. Create a collection with m2m relation (ex. todo)
4. Add some item to m2m relation in item of todo collection
5. Try to edit it

### What version of Directus are you using?

9.0.0-rc.90

### What version of Node.js are you using?

16.4.0

### What database are you using?

Postgress 12

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-08-19 22:17
I believe this is a duplicate of https://github.com/directus/directus/issues/6293

**Closed by rijkvanzanten** 2021-08-19 22:17 UTC
Labels: Bug (Potential)
