### ISSUE TITLE
Cannot create anchor tags in WYSIWYG field

### ISSUE THREAD

**Issue by marcmojave** [directus/directus#20335] opened 2023-11-06 09:54 UTC
### Describe the Bug

I am unable to create anchor tags in a WYSIWYG field. The dropdown to allow anchor tag creation is not appearing. Normally when i type `hash` symbol a dropdown with potential anchor candidates appear. Has this functionality been changed or removed?

I am reticent about upgrading to latest as we have a busy schedule. Would just like to know if this is an issue & if it has been fixed? I have asked already on the Discord general help but no reply. Thank you.  

Expected behaviour:
v **9.0.0-rc.30**

https://github.com/directus/directus/assets/25531999/5d1bc413-fff7-468a-a1aa-f39fd9944766

Observed:
v **9.26.0**

https://github.com/directus/directus/assets/25531999/fd327952-c7ea-495b-985c-e519279bd71f

### To Reproduce

1. Edit a WYSIWYG field
2. add a bullet point line with text
3. add a H2 heading
4. Highlight the bullet point line & click `Link` icon
5. In the URL field, type hash symbol

Expected: 
Dropdown menu containing the the H2 text.

Observed:
Nothing happens.  

### Directus Version

9.26.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-11-06 10:31
Seems like is technically due to #4309 over 2 years ago, released in `v9.0.0-rc.57`, where the "native" TinyMCE modals such as links, images, code etc were replaced by custom modals. This means the "dropdown with potential anchor candidate" indeed no longer exists as of now.

It does seem to be a very useful feature, so perhaps you can open a feature request so that we can look into the approach necessary to implement this in the current custom modal as well as help us gauge the community's interest on it.

Proceeding to close this as it is technically not a bug.

**Closed by azrikahar** 2023-11-06 10:31 UTC

**Comment by marcmojave** [comment] 2023-11-06 10:57
> Seems like is technically due to #4309 over 2 years ago, released in `v9.0.0-rc.57`, where the "native" TinyMCE modals such as links, images, code etc were replaced by custom modals. This means the "dropdown with potential anchor candidate" indeed no longer exists as of now.
> 
> It does seem to be a very useful feature, so perhaps you can open a feature request so that we can look into the approach necessary to implement this in the current custom modal as well as help us gauge the community's interest on it.
> 
> Proceeding to close this as it is technically not a bug.

Ok, thanks for the reply. So are we saying that currently there is no way to create anchor links or is there some workaround that can be done?

**Comment by azrikahar** [comment] 2023-11-06 11:47
> is there some workaround that can be done?

Based on what I can observe via [TinyMCE's demo](https://www.tiny.cloud/docs/demo/full-featured/), I believe once you click the auto-suggested heading and save the auto-generated id, it will add it as an actual `id` attribute to that heading as seen via the source code. 

That would mean the current workaround would be to manually go to the source code view in Directus' WYSIWYG interface, and add a random id `href="#<your-id>"` to the link of your choice, and add the corresponding `id="<your-id>"` attribute to target heading/text.

I've added a quick screen capture to show what I described about TinyMCE, hopefully it'll be a clearer reference:

https://github.com/directus/directus/assets/42867097/59d1af0d-4ec7-46ea-a37a-f16d89efd80a

**Comment by marcmojave** [comment] 2023-11-06 11:52
Ok, thanks for the help Azri. That was a very handy feature. I will add a feature request.
