### ISSUE TITLE
Unable to upload files with TUS & GCS enabled

### ISSUE THREAD

**Issue by u12206050** [directus/directus#24014] opened 2024-11-08 13:27 UTC
### Describe the Bug

Due to another bug we had to enable TUS to have Directus 11.2.1 working.
However now we get another issue:

![image (3)](https://github.com/user-attachments/assets/4e3697cd-d16b-4dc8-b4d6-73ee48da103d)

### To Reproduce

Enable tus and use GCS as storage.
CHUNK_SIZE=1024kb

Try uploading a large file

### Directus Version

11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql

**Comment by u12206050** [comment] 2024-11-08 13:31
Actually seems it might be this issue. https://github.com/directus/directus/issues/24011 Works for admin, but not for other roles.

**Comment by ComfortablyCoding** [comment] 2024-11-08 15:37
I cannot reproduce this with `create`,`read`,`update` permissions via policy on the non-admin user or policy via role assigned to the non-admin user. The full upload works fine for both the `POST` and the subsequent patches.

Can you share the error shown in the server terminal as well as minimal example permissions that trigger this issue?

**Comment by sn** [comment] 2024-11-09 13:41
I upgraded an existing instance to v11.2.1 running in Docker with a large number of files stored in Cloud Storage and attempting to access any files via the Directus API results in this: 

```json
{"errors":[{"message":"Invalid chunkSize provided","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

No TU-related configuration has been set and the env vars only currently include:

```
gcloud run deploy $SERVICE_NAME \
--image gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ vars.SERVICE_NAME }} \
--region ${{ vars.REGION }} \
--platform managed \
--allow-unauthenticated \
--update-secrets=DB_HOST=DB_HOST:latest \
--update-secrets=DB_PORT=DB_PORT:latest \
--update-secrets=DB_CLIENT=DB_CLIENT:latest \
--update-secrets=DB_PASSWORD=DB_PASSWORD:latest \
--update-secrets=DB_USER=DB_USER:latest \
--update-secrets=DB_SSL__REJECT_UNAUTHORIZED=DB_SSL__REJECT_UNAUTHORIZED:latest \
--update-secrets=DB_SSL=DB_SSL:latest \
--update-secrets=DB_DATABASE=DB_DATABASE:latest \
--update-secrets=KEY=KEY:latest \
--update-secrets=SECRET=SECRET:latest \
--update-secrets=ADMIN_EMAIL=ADMIN_EMAIL:latest \
--update-secrets=ADMIN_PASSWORD=ADMIN_PASSWORD:latest \
--update-secrets=STORAGE_LOCATIONS=STORAGE_LOCATIONS:latest \
--update-secrets=STORAGE_GCS_DRIVER=STORAGE_GCS_DRIVER:latest \
--update-secrets=STORAGE_GCS_KEY_FILENAME=STORAGE_GCS_KEY_FILENAME:latest \
--update-secrets=STORAGE_GCS_BUCKET=STORAGE_GCS_BUCKET:latest \
--update-secrets=STORAGE_GCS_CREDENTIALS=STORAGE_GCS_CREDENTIALS:latest \
--update-secrets=PRESSURE_LIMITER_ENABLED=PRESSURE_LIMITER_ENABLED:latest \
--update-secrets=ACCESS_TOKEN_TTL=ACCESS_TOKEN_TTL:latest \
--update-secrets=DB_POOL__MIN=DB_POOL__MIN:latest \
--update-secrets=DB_POOL__MAX=DB_POOL__MAX:latest \
--service-account=${{ vars.SERVICE_ACCOUNT_NAME }}
```

Error Log: 

<img width="1156" alt="Screenshot 2024-11-09 at 15 38 30" src="https://github.com/user-attachments/assets/82a39c6a-c719-49bb-8a10-b952daffceae">

**Comment by hanneskuettner** [comment] 2024-11-09 15:22
@sn 

You should be able to circumvent this incorrect error message by just setting `TUS_CHUNK_SIZE` to `1mb` for example, without actually enabling TUS upload, see #24001

**Comment by sn** [comment] 2024-11-09 16:00
> @sn
> 
> You should be able to circumvent this incorrect error message by just setting `TUS_CHUNK_SIZE` to `1mb` for example, without actually enabling TUS upload, see #24001

Can confirm that works - thanks @hanneskuettner !

**Comment by ComfortablyCoding** [comment] 2024-11-11 17:31
> Permissions: <img alt="Screenshot 2024-11-08 at 20 48 20" width="789" src="https://private-user-images.githubusercontent.com/6641242/384506970-c63e50a5-0db5-41f6-ac5c-b93a194a1504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDYzMzcsIm5iZiI6MTczMTM0NjAzNywicGF0aCI6Ii82NjQxMjQyLzM4NDUwNjk3MC1jNjNlNTBhNS0wZGI1LTQxZjYtYWM1Yy1iOTNhMTk0YTE1MDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMTcyNzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWQxYzBlZDk3OWUyMmFjNzk2ZDIzZGQ1NWMyN2NjMWViNTM3NDU5MzY2ZjU1NTZmNzg3MTBlMDZkMDExNDYwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.x9CMBXCC9Pa80YPYs4sny4sZ_NvxjgaGoFFqEpinkoY">
> 
> READ rule: `{"_and":[{"_or":[{"uploaded_by":{"_eq":"$CURRENT_USER"}},{"folder":{"name":{"_in":["banners","logos","tutorials","public"]}}}]}]}` fields: *
> 
> UPDATE rule: `{"_and":[{"uploaded_by":{"_eq":"$CURRENT_USER"}}]}` fields: *
> 
> DELETE rule: `{"_and":[{"uploaded_by":{"_eq":"$CURRENT_USER"}}]}`
> 
> Full error:
> 
> ```
> {
>   "stack": "Error: tus: unexpected response while creating upload\n    at e.value (https://admin.event.bcc.no/admin/assets/index.BMYaiyJh.entry.js:65:8383)\n    at https://admin.event.bcc.no/admin/assets/index.BMYaiyJh.entry.js:65:10008",
>   "message": "tus: unexpected response while creating upload, originated from request (method: POST, url: /files/tus, response code: 500, response text: Something went wrong with that request\n, request id: n/a)",
>   "originalRequest": {},
>   "originalResponse": {},
>   "causingError": null
> }
> ```

Thank you for the additional information, unfortunately I still cannot reproduce the issue with the permissions outlined above. See recording below demonstrating the proposed setup with both the `POST` and `PATCH` working for TUS and GCS. Due this I will be closing this issue for now, happy to reopen if a reproducible example can be provided.

https://github.com/user-attachments/assets/e107781b-36c5-4784-bb3e-22998c290075

**Closed by ComfortablyCoding** 2024-11-11 17:31 UTC
Labels: Needs Info
