### ISSUE TITLE
"Require value to be set" option not properly populated upon editing field

### ISSUE THREAD

**Issue by chrisbartley** [directus/directus#7551] opened 2021-08-23 19:22 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When editing a field, the "Require value to be set" option is always unchecked, regardless of its true state in `directus_fields`.

### To Reproduce

Create a new table, then create a field with the "Require value to be set" option checked (see screenshot for table `categories` and field `name`).  Save, then go back in and edit the field.  The "Require value to be set" option is unchecked.

However, inspecting the field in the `directus_fields` table reveals that it is indeed saves as required (see second screenshot). It's merely the front end which isn't rendering the field as such.

![image](https://user-images.githubusercontent.com/86031/130502083-256edd0e-d1a7-45ce-beb5-456a57456372.png)
![image](https://user-images.githubusercontent.com/86031/130502118-5320afa7-7591-4419-a87e-4196f5f1ced5.png)

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

v14.17.5

### What database are you using?

MySQL (Ver 14.14 Distrib 5.7.35, for Linux (x86_64))

### What browser are you using?

Brave and Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-08-23 19:31
Duplicate of https://github.com/directus/directus/issues/7356

**Closed by rijkvanzanten** 2021-08-23 19:31 UTC
Labels: Bug (Potential)

**Comment by chrisbartley** [comment] 2021-08-23 19:32
Heck, sorry.  I swear I'm searching for dupes before posting.  I guess I need to up my search skills 🤦‍♂️

**Comment by rijkvanzanten** [comment] 2021-08-23 19:41
@chrisbartley No problem! Definitely helps if you've read every issue on this repo at least once (I have an unfair advantage when it comes to finding duplicates 😉 )
