### ISSUE TITLE
Records with custom permission are not available in the API.

### ISSUE THREAD

**Issue by leorott** [directus/directus#22747] opened 2024-06-13 12:27 UTC
### Describe the Bug

We use Directus as a CMS and use custom permissions to schedule content.  We have a Collection called `News` with the following fields:

- `status`: String
- `date_published`: Date

Then we use a custom permission with the following rules:

- `status` Equals "published" 
- `date_published` Less than or equal to $NOW
<img width="400" alt="image" src="https://github.com/directus/directus/assets/89790550/661dfbe3-2d72-40d5-b1b9-5da37428475b">

This approached worked well, until we updated from `directus:9.26.0` to `directus:10.10.5`. Since then, the pre-scheduled records won't appear in the API on the publishing date.  However, if we create a record and schedule it for today, it works perfectly. Also, if we set the `date_published` to yesterday, it works.  Further, when we open the item permissions and save them again, everything suddenly works. 

Could it be that this is a problem with the caching? We saw that you added caching to the GraphQL API recently (#19664 https://github.com/directus/directus/pull/21783)

### To Reproduce

1. Created a collection with the following fields:
      - `status`: String
      - `date_published`: Date

2. Create a custom permission for public read access and set the following rules:
      - `status` Equals "published" 
      - `date_published` Less than or equal to $NOW

3. Create a new record with the following values:
     - `status` = "published"
     -  `date_published` = tomorrows date

4. Wait until tomorrow and look if the is available through the API.
 

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql:5.7.38

**Comment by hanneskuettner** [comment] 2024-06-15 08:44
Looks like it might indeed be cache related, an there is already an issue tracking this bug, that's tracked in #22492.

I'll close this issue and we'll continue tracking it over there.

Duplicate of #22492

**Comment by hanneskuettner** [comment] 2024-06-15 08:45
Duplicate of #22492

**Closed by hanneskuettner** 2024-06-15 08:44 UTC
