### ISSUE TITLE
one collection list block in blank and get one error

### ISSUE THREAD

**Issue by kroawen** [directus/directus#3385] opened 2020-12-11 01:22 UTC
console.error display:
--------------
    TypeError: Cannot read property 'field' of undefined
    at a.i (app.5e1f3b78.js:1)
    at chunk-vendors.8f64b78c.js:28
    at be (chunk-vendors.8f64b78c.js:28)
    at a.t.render (chunk-vendors.8f64b78c.js:28)
    at a.e._render (chunk-vendors.8f64b78c.js:113)
    at a.r (chunk-vendors.8f64b78c.js:113)
    at nr.get (chunk-vendors.8f64b78c.js:113)
    at nr.run (chunk-vendors.8f64b78c.js:113)
    at Qn (chunk-vendors.8f64b78c.js:113)
    at Array.<anonymous> (chunk-vendors.8f64b78c.js:113)
--------------------
Version: 9.0.0-rc.22
Node: 14.15.1

**Comment by shlaing** [comment] 2020-12-11 04:13
Duplicate issue to https://github.com/directus/directus/issues/3322

**Comment by shlaing** [comment] 2020-12-11 04:14
@kroawen , Can you describe your DBMS and version?

**Comment by kroawen** [comment] 2020-12-11 07:31
@shlaing 

DB:
`mysql Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)`

OS:
`CentOS Linux release 7.9.2009 (Core)`

**Comment by rijkvanzanten** [comment] 2020-12-11 14:36
Duplicate of #3322

**Closed by rijkvanzanten** 2020-12-11 14:36 UTC
