### ISSUE TITLE
Incorrect type-cast for boolean config values

### ISSUE THREAD

**Issue by the-other-dev** [directus/directus#22343] opened 2024-04-30 09:35 UTC
### Describe the Bug

For config options there is an automatic type-casting (https://docs.directus.io/self-hosted/config-options.html#type-casting-and-nesting). In the code, the relevant parts are in the _env_ package [`lib/cast.ts`](https://github.com/directus/directus/blob/main/packages/env/src/lib/cast.ts) and [`utils/guess-type.ts`](https://github.com/directus/directus/blob/main/packages/env/src/utils/guess-type.ts).

When using an actual boolean value in the config options, the parsed value turns into `0` instead of `false` or `1` instead of `true`.

I believe that this issue is there since version v10.9.0 when the _env_ package was introduced.

### To Reproduce

Add an option with the type boolean to the `config.json`, e.g. `"MY_VARIABLE": false`.
Retrieve the parsed value via:

```typescript
const env = useEnv();
console.log(env['MY_VARIABLE']); // Prints 0 instead of false
```

The current work-around is to define the option as a string `"MY_VARIABLE": "false"` (returns `false` in the application).

Also, here are two test cases for `guess-type.test.ts` that currently fail due to the issue:

```typescript
test('Returns boolean if value is boolean true', () => {
    expect(guessType(true)).toBe('boolean'); // Fails because it returns "number" currently
});

test('Returns boolean if value is boolean false', () => {
    expect(guessType(false)).toBe('boolean'); // Fails because it returns "number" currently
});
```

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-04-30 09:49
Heya! Thank you for opening this issue, as it turns out, this looks like a duplicate of #21744. I'll proceed to close this issue. You can follow along in #21744 on the progress.

**Closed by hanneskuettner** 2024-04-30 09:49 UTC
Labels: :cake: Bug

**Comment by the-other-dev** [comment] 2024-04-30 09:51
Thanks! My bad, I did not see that one!
