### ISSUE TITLE
Edit or Copy raw Filter in Presets shows [object Object]

### ISSUE THREAD

**Issue by Pachat** [directus/directus#16309] opened 2022-11-03 21:17 UTC
### Describe the Bug

Editing or Copying raw filter in Presets shows [object Object]

### To Reproduce

In a preset, set a filter. Then Edit or Copy the raw value

### Errors Shown

You get [object Object] instead of the JSON

### What version of Directus are you using?

9.20.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-11-03 21:27
Thanks for opening this issue! However this is a duplicate of an existing issue #16216, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #16216 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2022-11-03 21:27 UTC
