### ISSUE TITLE
Error using dynamic variables and filter functions in "insights" (dashboards)

### ISSUE THREAD

**Issue by pzehle** [directus/directus#17719] opened 2023-03-06 22:59 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I have a collection, in which, by requirements of the customer, need to save month, year and number of "api calls", because we are using an external API and he wants just to store the information there.

Now that we have insights (I am a Directus 8 user) it is super cool how we can show information. However, in this case, I just want to show something like:

![Screenshot 2023-03-06 at 23 56 12](https://user-images.githubusercontent.com/27866874/223275328-81768e40-d510-4c76-a88d-deb5db921a58.png)

And my logic tells me, to add filters (so I don't have to manually change month and year) and just show the current month AND the current year from that collection. The problem is, that $NOW is not working, and also (according to [here](https://docs.directus.io/reference/query.html#functions) and [here](https://docs.directus.io/reference/filter-rules.html) I should be able to do something like `year($NOW)` but it doesn't work, not even using normal $NOW.

Here how I have it:

![Screenshot 2023-03-06 at 23 53 11](https://user-images.githubusercontent.com/27866874/223275630-29be62b7-2c44-44eb-a7ab-dffcb5b401bd.png)
**(Notice that I can also just do $NOW and result is the same)**

And exploring the network tab, it returns this:

![Screenshot 2023-03-06 at 23 53 26](https://user-images.githubusercontent.com/27866874/223275741-0a540b0c-b2d1-458b-8d24-80cb89069523.png)

Which means that is not being applied. And of course, as you can see in the first attachment, I just get "No data".

Am I doing something wrong? How can I achieve this?

### To Reproduce

Add a filter to any collection, specially one that needs a month or year from $NOW, and try to extract from it, as described in the docs.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by pzehle** [comment] 2023-03-06 23:00
Doesn't matter if I remove the `_and`, if I just use month or year. It just doesn't retrieve the data and according to the network tab, it is not working.

**Comment by Nitwel** [comment] 2023-03-08 17:13
There are several things wrong with the way you're trying to accomplish things.
1. The And/Or operator are a group that applies the type to everything inside the group, meaning, that if you remove the And group from you filter, you are basically done as the top level combinator is also an And operator.
2. Functions can only be applied to fields, meaning, that if you have a date field and want to filter for march, you could do something like `{"month(date)":{ "_eq": 2 }}` but you can't apply it to a value. 

There is nothing going wrong though as far as I'm seeing, so I'll close this issue for now. Have a look at global variables in insights, that will probably help you find what you're trying to do.

**Closed by Nitwel** 2023-03-08 17:13 UTC

**Comment by pzehle** [comment] 2023-03-08 17:57
Thanks for the response. Yes I know about the AND filters, I was just testing some stuff out and forgot to remove it before the screenshot.

So imagine if I wanted to have a filter that matched "today" as the date, and the field is a `DateTime` field; I am not able to use: `{"date": {"_eq": $NOW}`?

**Comment by whis** [comment] 2023-03-10 22:54
I also find this buggy or at least very confusing. It's possible to use `"date_created": { "_gt": "$NOW(-1 year)" }` to get entries for last year, but I cannot use the `"year(date_created)": { "_eq": "year($NOW)" }` to get the current year. Is that the expected behavior?

**Comment by pzehle** [comment] 2023-03-10 23:13
@whis yeah, I don't think this is the expected behavior.

Don't get me wrong, I love Directus, but it seems now it's only about 1 comment and directly close the issue without having any further details.

I couldn't get a direct answer for my specific issue; but reading you, I guess this in fact is buggy and not expected.

@Nitwel could you please remove the invalid tag and reopen the issue so we can continue debugging and get to a solution? Thanks.

**Comment by Nitwel** [comment] 2023-03-11 01:53
This is all working as intended right now, so there is no bug to fix. The docs clearly state that functions can only be used by `wrapping a field key` not a comparison value or equal. What you're suggesting is an improvement to the way how current functions work, not that something is broken.

![grafik](https://user-images.githubusercontent.com/22577866/224458659-f5dd510f-5c50-41a7-b41b-12ecd387388f.png)

But feel free to open a discussion on GitHub on that improvement as it could be a nice addition to the current implementation of functions.

**Comment by whis** [comment] 2023-03-11 08:50
@Nitwel Thanks for the clarification. In my honest opinion, this should have been in place since the feature was introduced. As far as I know, it would be the only way to filter the data by the current year/month/day, which is essential to Insights. So, I'd like to encourage the Directus team to implement it.

@pzehle Since you are the OP, please open the discussion to push this feature request through. I will add my vote to it.
