### ISSUE TITLE
Setting multiple field presets for role not working

### ISSUE THREAD

**Issue by NickSettler** [directus/directus#10782] opened 2021-12-31 02:20 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I am trying to make something kind of register. So I gave custom create permissions for the public role on directus_users collection. But when trying to set multiple field presets it's not working. I'm setting the field presets in a such way 

```json
{
    "status": "active",
    "role": "54303c36-facc-4323-8eee-469f3afe2900"
}
```

But as the result, when I'm using endpoint for users creation, there's only status field set in a new user. Role field is empty. And it doesn't changes if I change the order of presets

### To Reproduce

1) Install a clean Directus 
2) Make a role like User
3) Make users creation api endpoint public and set field presets including role and something else
4) Try to create a user without authorization using endpoint
5) Check the user's role and other fields should be filled by preset

### Errors Shown

When I'm trying to login into this users right after I've created it using api, I see the following error from login endpoint. And as i realized this happens because the role is not set from the preset

```json
{
    "errors": [
        {
            "message": "Invalid user credentials.",
            "extensions": {
                "code": "INVALID_CREDENTIALS"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.4.1

### What version of Node.js are you using?

14.18.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

docker-compose

**Comment by NickSettler** [comment] 2021-12-31 02:57
I suppose that this issue #10576 and the related commited might be the reason why now it works in some incorrect way

**Comment by azrikahar** [comment] 2022-01-03 07:47
Hmm #10576 should just be concerning the App, not the API (when you are creating item with presets), so I believe it's not really related to it.

Seems like rather than that commit causing issue, it's more so it _didn't_ resolve this completely, since the `parseFilter` wasn't removed on the API side over here:

https://github.com/directus/directus/blob/78ba63414da8d5d94e7b30900d5c09363a8ed3cc/api/src/utils/get-permissions.ts#L197

Definitely an oversight. I've just tested removing that line and your issue will be resolved 👍

---

That said, removing the parsing flat out will remove the possibility of [using dynamic variables instead as stated here](https://github.com/directus/directus/pull/10576#issuecomment-1003481572), so we'll probably need to tackle that aspect together when fixing this. Perhaps an offshoot of parseFilter, maybe `parsePresets` which uses parseDynamicVariables only? 🤔 That way we can add it to the App side as well. paging @rijkvanzanten @licitdev for thoughts on this

**Comment by rijkvanzanten** [comment] 2022-01-03 19:55
@azrikahar Yeah agreed on that. We should extract the logic that handles the actual replacement of those variables though, so we can re-use it between the two functions 👍🏻

**Comment by brandnewx** [comment] 2022-01-10 03:56
I believe Directus need a lot more new unit tests to make sure that we won't see bug regressions. Unit tests will ensure that things that work will stay working, after new code are added and there are accidental oversights. Without unit tests, things will randomly break here and there.

**Comment by benhaynes** [comment] 2022-01-10 16:28
We agree! We're actively working on tests... but it's slow going with our small team. We'd love an extra set of hands if you're interested in contributing!

**Comment by scouech** [comment] 2022-01-25 08:35
@rijkvanzanten no way around that at the moment? Right now users created don't get the right role added, so they don't get the right privileges which is quite a problem for a user based app 🤓

**Comment by RANSoftRA** [comment] 2022-01-26 15:54
I can confirm the issue on 9.5.0 as well.

**Comment by RANSoftRA** [comment] 2022-01-27 11:22
In our case (when a user registers =public role, then the user should be assigned to the role "Customer") we were able to overcome this issue by creating a custom Hook on `users.create` action:

Example:


`[directus-root]/extensions/hooks/custom/index.js`

```javascript
module.exports = function registerHooks({action}, {services, exceptions}) {

    const {UsersService} = services;

    action('users.create', async ({payload}, {schema}) => {

        const defaultRole = '<your-role-id-here>';

        // set default role if not provided
        if (!payload.role) {
            ...
            console.log('Setting role for ' + payload.email + ' to default role');
            const userService = new UsersService({schema: schema});
            await userService.updateByQuery({
                filter: {
                    'email': {
                        '_eq': payload.email
                    }
                }
            }, {
                'role': defaultRole
            });
           ...
        }
    });
};
```
In this case we just assign a defaultRole, if no role was specified.

**Closed** 2022-02-04 00:29 UTC
Labels: API, Bug
