### ISSUE TITLE
SVGs not uploading / displaying properly

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#7318] opened 2021-08-10 14:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Im not sure if it is since the latest release, because I only use Direcuts since a few weeks, but since I did an update yesterday, I noticed, that the media library and everything regarding uploading files is somewhat broken.

Sometimes I can upload files and it works finde, but at some times I upload a file and its behaving extremely strange.
So I upload a file and for some reason the entry gets created, but its incomplete.

### Library
On the right hand side you can see an old image, that is working finde, but on the left hand side there are images i just uploaded and those seem to be incomplete. 

![image](https://user-images.githubusercontent.com/10547444/128887318-7ef94785-8cac-48b4-a6a2-0e38e6d23f7d.png)

### Database
They don't work and there are some columns that are "null" in the database.

![image](https://user-images.githubusercontent.com/10547444/128887430-a3b5ce15-8e14-40be-be1c-1b0aac4e0172.png)

Also there is this weird behaviour, that at some point when I upload a svg, it corrupts I think the last image I uploaded before.

So I just uploaded a file called Workflow.jpg properly and everything is working fine.
Now I upload an SVG called hall.svg and it breaks. Somehow I now have 2 hall entries. And one contains the new svg and one does not contain anything. And the old Workflow.jpg is gone.

### Before
![image](https://user-images.githubusercontent.com/10547444/128889626-6ebb29c7-acfc-43fa-bac4-a9d92e21919a.png)

### After
![image](https://user-images.githubusercontent.com/10547444/128889695-18336438-8839-450f-8a0f-ea198167a4ef.png)

### To Reproduce

I guess uploading a few files to the media library and refreshing the page a few times should do it.

I have uploaded jpg and svg files, if that makes a difference.

I also played around with folders at the same time as updating ... so maybe that did some damage? But I removed all the folders and changed all models to be using the root library again. So that would be weird.

### What version of Directus are you using?

v9.0.0-rc.89

### What version of Node.js are you using?

v14.17.2

### What database are you using?

MariaDB

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

On a remote Debian server

**Comment by rijkvanzanten** [comment] 2021-08-10 14:59
Do you have a more specific set of steps that triggers this accurately? I tried

> I guess uploading a few files to the media library and refreshing the page a few times should do it.

but can't reproduce it based on that..

What are your settings for caching? What storage adapter are you using?

**Comment by kapilvats** [comment] 2021-08-10 16:57
I am also facing same issue after updating to the latest release.

I am using azure storage.

**Comment by rijkvanzanten** [comment] 2021-08-10 17:25
@LasseRosenow Just to confirm, are you seeing the same thing on both MariaDB and SQLite, or only SQLite?

**Comment by LasseRosenow** [comment] 2021-08-10 17:27
Its the same on both. I just used SQLite for the reproduction, as it was easier to setup quickly

**Comment by rijkvanzanten** [comment] 2021-08-10 17:34
Gotcha, thanks! Reason I wasn't seeing it on my end is because I was testing on the latest `main` before, which already includes the fix 🙂 

Fixed in https://github.com/directus/directus/pull/7312

**Closed by rijkvanzanten** 2021-08-10 17:34 UTC
Labels: Needs More Info

**Comment by Nzent** [comment] 2022-12-12 20:47
Have the same issue Can't upload images,
hosted on Ubuntu vps
return 502 error
But when I check the upload folder image is uploaded not linked to db
![Screenshot from 2022-12-13 01-40-34](https://user-images.githubusercontent.com/26079832/207151190-f845b476-961d-479a-b3da-c21ebbbfeb40.png)
