### ISSUE TITLE
Not having PostGIS enabled breaks schema apply

### ISSUE THREAD

**Issue by infomiho** [directus/directus#8176] opened 2021-09-20 22:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Using a docker compose with Directus rc.93 and vanilla Postgres. 

Applying a snapshot results with the following outputs:
```
docker-compose exec directus npx directus schema apply ./schemas/schema.yml   
22:35:59 ✨ Loaded extensions: picker, test-hook, banners
? The following changes will be applied:



Fields:
  - Delete test.new

Would you like to continue? Yes
22:36:02 🚨 error 
        SELECT c.table_name
          , c.column_name
          , c.column_default as default_value
          , c.data_type
                                        , c.character_maximum_length as max_length
          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity
          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable
        FROM
          information_schema.columns c
        LEFT JOIN information_schema.tables t
          ON c.table_name = t.table_name
        WHERE
          t.table_type = 'BASE TABLE'
          AND c.table_schema IN ($1);
       - current transaction is aborted, commands ignored until end of transaction block 
error: 
        SELECT c.table_name
          , c.column_name
          , c.column_default as default_value
          , c.data_type
                                        , c.character_maximum_length as max_length
          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity
          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable
        FROM
          information_schema.columns c
        LEFT JOIN information_schema.tables t
          ON c.table_name = t.table_name
        WHERE
          t.table_type = 'BASE TABLE'
          AND c.table_schema IN ($1);
       - current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:394:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```
In the Postgres logs I see this:
```
database    | 2021-09-20 22:35:59.327 UTC [45] ERROR:  relation "geometry_columns" does not exist at character 42
database    | 2021-09-20 22:35:59.327 UTC [45] STATEMENT:  
database    |                   WITH geometries as (
database    |                           select * from geometry_columns
database    |                           union
database    |                           select * from geography_columns
database    |                   )
database    |           SELECT f_table_name as table_name
database    |                           , f_geometry_column as column_name
database    |                           , type as data_type
database    |           FROM geometries g
database    |           JOIN information_schema.tables t
database    |                   ON g.f_table_name = t.table_name
database    |                   AND t.table_type = 'BASE TABLE'
database    |           WHERE f_table_schema in ($1)
database    |         
database    | 2021-09-20 22:35:59.529 UTC [44] ERROR:  function postgis_version() does not exist at character 8
```

### To Reproduce

1. Running Directus in Docker Compose with fresh Postgres and taking a snapshot with CLI
2. Adding a new field called "new"
3. Try to apply the previous snapshot

Note: After I tried running the same steps with a different Docker image `postgis/postgis`, it just works.

### What version of Directus are you using?

9.0.0-rc.93

### What version of Node.js are you using?

v12.20.2

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-09-20 23:34
@infomiho I'm wondering if those two errors are related! 

Are you by any chance using groups in your data model? It could be a duplicate of https://github.com/directus/directus/issues/8113.

**Comment by dstoyanoff** [comment] 2021-09-21 09:20
This looks like the problem I had - https://discord.com/channels/725371605378924594/725817819882586132/888435498903814155

I wasn't able to narrow it down to anything though, good catch to check PG logs. I didn't have time to experiment further on this, so I can't really give an advise or confirm it's the same issue, but the error seems to be similar.

**Comment by infomiho** [comment] 2021-09-21 09:26
@rijkvanzanten No groups were created before taking the snapshot, and also no groups were created before applying the snapshot.

```
version: 1
directus: 9.0.0-rc.93
collections:
  - collection: test
    meta:
      collection: test
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
    schema:
      name: test
      schema: public
      comment: null
fields:
  - collection: test
    field: id
    type: integer
    schema:
      name: id
      table: test
      data_type: integer
      default_value: nextval('test_id_seq'::regclass)
      generation_expression: null
      max_length: null
      numeric_precision: 32
      numeric_scale: 0
      is_generated: false
      is_nullable: false
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      id: 1
      collection: test
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: null
      width: full
      group: null
      translations: null
      note: null
      conditions: null
      required: false
  - collection: test
    field: name
    type: string
    schema:
      name: name
      table: test
      data_type: character varying
      default_value: null
      generation_expression: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_generated: false
      is_nullable: true
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      comment: null
      schema: public
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      id: 2
      collection: test
      field: name
      special: null
      interface: null
      options: null
      display: null
      display_options: null
      readonly: false
      hidden: false
      sort: null
      width: full
      group: null
      translations: null
      note: null
      conditions: null
      required: false
relations:
  - collection: topology.layer
    field: topology_id
    related_collection: topology
    schema:
      table: topology.layer
      column: topology_id
      foreign_key_table: topology
      foreign_key_column: id
      foreign_key_schema: topology
      constraint_name: layer_topology_id_fkey
      on_update: NO ACTION
      on_delete: NO ACTION
    meta: null
  - collection: directus_settings
    field: storage_default_folder
    related_collection: directus_folders
    schema:
      table: directus_settings
      column: storage_default_folder
      foreign_key_table: directus_folders
      foreign_key_column: id
      foreign_key_schema: public
      constraint_name: directus_settings_storage_default_folder_foreign
      on_update: NO ACTION
      on_delete: SET NULL
    meta: null

```

**Comment by keesvanbemmel** [comment] 2021-09-26 08:20
So after testing a bunch of setups (for issue #8311) I concur that having postgis installed and enabled makes this issue disappear.

**Closed** 2021-09-27 20:35 UTC
Labels: API, Bug
