### ISSUE TITLE
Server Error Call to a member function getOptions() on null

### ISSUE THREAD

**Issue by Sirjoseph94** [directus/directus#1785] opened 2017-09-03 16:31 UTC
.

## Version Info
  - Directus version and branch: v6.4.2 (Ruby Rabbit)
  - PHP version: 7.1
  - MySQL version: 10.1.24-MariaDB-cll-lve
  - Web server: Apache
  - OS name and version: linux

## Expected Behavior
Upload and store picture in a table

## Actual Behavior
getting `Server Error Call to a member function getOptions() on null`

## Steps to Reproduce
 1.Upload a picture in the single file row in the table
 2. or upload a picture file through the file upload

## Schema Dump, Logs, or Screenshots
![screencapture-localhost-ncgc-admin-tables-babic_speakers-1-1504455846044](https://user-images.githubusercontent.com/21038634/30004811-bbb44896-90cd-11e7-8c9d-fa058b188fd3.png)

**Comment by jvmejias** [comment] 2017-09-03 17:33
I had the same problem recently:
https://github.com/directus/directus/issues/1770
You probably need to update the database schema.

**Comment by Sirjoseph94** [comment] 2017-09-03 18:01
Thanks
but how do i update the Schema

**Comment by jvmejias** [comment] 2017-09-03 18:13
Using git, run the following command:
`$ bin/directus db:upgrade`
https://docs.getdirectus.com/6.4.0/#Versions_&_Updating

**Comment by Sirjoseph94** [comment] 2017-09-03 18:32
am sorry am still a newbie
can you please be a bit more descriptive?
thanks

**Comment by Sirjoseph94** [comment] 2017-09-03 19:03
fixed it. thanks

**Comment by rijkvanzanten** [comment] 2017-09-03 19:07
Hi @Sirjoseph94! 

I'm glad you figured it out!

This is indeed a duplicate of #1770.

Thanks for the help @jvmejias!

**Closed by rijkvanzanten** 2017-09-03 19:07 UTC
