### ISSUE TITLE
No files after upgrading to V8

### ISSUE THREAD

**Issue by pgegenfurtner** [directus/directus#2487] opened 2019-12-04 17:33 UTC
After upgrading to V8 (from v8-rc2) files are not loading.
When I go to the file browser, no thumbnails are shown and when I click on a file the screen goes blank.

The api seems to return incomplete data. The data object in the files response looks like this:

The `url` and `full_url` properties are completely missing.

```
embed: null
thumbnails: [{url: "http://101-interness-api:8888/_/assets/?key=card", relative_url: "/_/assets/?key=card",…},…]
0: {url: "http://101-interness-api:8888/_/assets/?key=card", relative_url: "/_/assets/?key=card",…}
dimension: "200x200"
height: 200
relative_url: "/_/assets/?key=card"
url: "http://101-interness-api:8888/_/assets/?key=card"
width: 200
1: {url: "http://101-interness-api:8888/_/assets/?key=avatar", relative_url: "/_/assets/?key=avatar",…}
dimension: "100x100"
height: 100
relative_url: "/_/assets/?key=avatar"
url: "http://101-interness-api:8888/_/assets/?key=avatar"
width: 100
```

For new uploaded files, the thumbnails are visible, but I can't go into the detail view of a file.

The files are all present in the correct folder and the database table seems complete.
With v8-rc2 it was working normally.

**Comment by rijkvanzanten** [comment] 2019-12-04 17:35
Duplicate of https://github.com/directus/api/issues/1520

**Comment by rijkvanzanten** [comment] 2019-12-04 17:36
It's because the `private_hash` column in `directus_files` is empty for these files. I'll push a new release later today that will set one for all files that don't have one yet

**Closed by rijkvanzanten** 2019-12-04 17:35 UTC

**Comment by pgegenfurtner** [comment] 2019-12-04 17:37
Perfect, thanks!

(With new v8, are issues still separated into app and api?)

**Comment by rijkvanzanten** [comment] 2019-12-04 17:58
Yeah! We're keeping the codebases separate as they're very separated codebases (.. woa)

The app and api are in different languages, and there's an easy to spot difference between bugs happening in the app vs the api. To make dev life easier, it's more convenient for us to keep them separated 🙂
