### ISSUE TITLE
Bookmark Page - Redirecting to main content 

### ISSUE THREAD

**Issue by alisaitteke** [directus/directus#22436] opened 2024-05-08 17:43 UTC
### Describe the Bug

On pages created using the bookmark feature, clicking the "Save and Exit" button redirects to the main content page, which does not include the bookmark parameter in the URL. I have managed to resolve this issue simply in my local environment. If permitted, I would like to create a Pull Request (PR) to address this issue.

### To Reproduce

1. Open the file app/src/modules/content/routes/item.vue.
2. Locate the router.push method.
3. Add the missing parameter to the router.push method that relates to bookmarking.

### Directus Version

v10.11.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-05-08 18:04
Duplicate of #22187

**Closed by br41nslug** 2024-05-08 18:04 UTC
