### ISSUE TITLE
V-List items after 4th item always refers to the 4th item

### ISSUE THREAD

**Issue by TheAzack9** [directus/directus#7010] opened 2021-07-27 20:28 UTC
### Describe the Bug

When creating a one-to-many relation in the app it seems that every element after the fourth one always refers to the fourth element. It is a bit tricky to explain 😅 See attached video for example.

https://user-images.githubusercontent.com/2140448/127222701-a309904e-f9fd-4ef2-b2e2-5e0e6fa8c3e0.mp4

### To Reproduce

Create two collections, make a o2m relation from one to the other. Create more than 4 elements and the last element should have the same behaviour :)

### What version of Directus are you using?

v9.0.0-rc.86

### What version of Node.js are you using?

Not sure, the one in the latest docker image

### What database are you using?

MySql 8.0 (i think, but i don't think it matters)

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker (through azure ;) )

**Comment by rijkvanzanten** [comment] 2021-07-27 20:40
Can you send over a DB dump either here or [on Discord](https://directus.chat)? I just setup a fresh instance with a new O2M instance and everything seems to behave 🤔 

https://user-images.githubusercontent.com/9141017/127224297-bf7f14e4-5241-4ada-85c9-d8c410894ed6.mp4

**Comment by rijkvanzanten** [comment] 2021-08-03 22:48
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-08-03 22:48 UTC
Labels: Needs More Info
