### ISSUE TITLE
Project Logo, Foreground, Background and Favicon not showing the data studio

### ISSUE THREAD

**Issue by Abdallah-Awwad** [directus/directus#21379] opened 2024-02-08 22:17 UTC
### Describe the Bug

When I tried to add project logo in a new instance of 10.9.0 version it didn't show
![image](https://github.com/directus/directus/assets/129249191/93b7e833-b95b-41da-b500-6ff1ba3c863e)

That what I get in the console:
`{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}`

**Solution:** When I gave access control to the collection `directus_files` to the public role images worked totally fine.

### To Reproduce

Create a new instance with Version 10.9.0 and try to add a `Project Logo` or `Public Foreground`, `Public Background`, `Public Favicon`

### Directus Version

10.9.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2024-02-08 22:22
Duplicate of https://github.com/directus/directus/issues/21359

**Closed by rijkvanzanten** 2024-02-08 22:22 UTC
