### ISSUE TITLE
Empty collection page

### ISSUE THREAD

**Issue by chris-lsn** [directus/directus#17052] opened 2023-01-09 02:30 UTC
### Describe the Bug

The collection page is empty when switching from the navbar, it works if refreshing the tab.

![Bug](https://user-images.githubusercontent.com/9113255/211232367-6b3f6142-b903-4113-ba69-7dd6ba11af95.gif)

### To Reproduce

Create multiple collections and switch them from the navbar

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 14.6

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by freekrai** [comment] 2023-01-09 02:31
Duplicate of https://github.com/directus/directus/issues/16883, which was fixed and merged in https://github.com/directus/directus/pull/16881, just waiting for a release.

**Closed by freekrai** 2023-01-09 02:31 UTC
