### ISSUE TITLE
Access control

### ISSUE THREAD

**Issue by semorur** [directus/directus#22156] opened 2024-04-10 08:39 UTC
### Describe the Bug

in access control if there is "all access" active (green tick) and I go to "use custom". I can't change field permissions (can't unselect fields).

To make it work I need to change to "no access", then I can go to "use custom" and select fields in field permissions.

it is not very convenient, because if there were some filters after selecting "no access" I need to do everything from beginning.

### To Reproduce

1. go to "access control"
2. find any green tick or press "all access" (I tried it on create, read and change)
<img width="297" alt="ac" src="https://github.com/directus/directus/assets/152224102/7afecda6-b71b-4af2-a9c6-e0cf3902920e">

3. go to "use custom" - "field permissions"
<img width="852" alt="fp" src="https://github.com/directus/directus/assets/152224102/ec581ea3-5769-44f0-8bf4-4ae2c58d6476">

4. try to unselect fields. You will not be able to do it.

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-04-10 08:46
Duplicate of #22132

**Closed by paescuj** 2024-04-10 08:46 UTC
