### ISSUE TITLE
Single Object error with new translations logic

### ISSUE THREAD

**Issue by jekuer** [directus/directus#8186] opened 2021-09-21 06:28 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After migrating to v93 from v92, I experience an error on single object collections, where translations are present.

`{
  "errors": [
    {
      "message": "select \"general_translations\".\"id\", \"general_translations\".\"general_id\", \"general_translations\".\"languages_code\", \"general_translations\".\"default_description\", \"general_translations\".\"default_title\", \"general_translations\".\"default_keywords\" from \"general_translations\" where \"general_translations\".\"general_id\" = $1 order by \"general_translations\".\"id\" asc - invalid input syntax for integer: \"+\"",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

### To Reproduce

Create a single object collection with translations.

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

What you have at the Docker file

### What database are you using?

Postgres 11

### What browser are you using?

Edge, Chrome, Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-09-21 06:32
Should be duplicate of #8173, and it's fixed in #8174 👍

**Closed by azrikahar** 2021-09-21 06:32 UTC
Labels: Bug (Potential)

**Comment by jekuer** [comment] 2021-09-21 06:52
Ah, damn. I just checked the still open issues. Sorry for that.

**Comment by azrikahar** [comment] 2021-09-21 06:56
No worries 😉
