### ISSUE TITLE
M2M "You don't have permission to access this."

### ISSUE THREAD

**Issue by ThisMushroom** [directus/directus#17332] opened 2023-01-28 18:14 UTC
### Describe the Bug

With m2m collection. 
Whenever you try to open item it pops  "You don't have permission to access this."
However it actually opens desired related item and you are able to edit it and save.
If you will take a look into the console, you can observe a request like "https://MYDOMAIN/items/places_galleries/876263a3-1e9c-43d5-96cd-9ad72dd30185" returning 403
876263a3-1e9c-43d5-96cd-9ad72dd30185 - is id from Places (not an id from a junction places_galleries

Same appear within other m2m from different sides of relation.

### To Reproduce

1. Take a snapshot - [snapshot2.zip](https://github.com/directus/directus/files/10527934/snapshot2.zip)
2. Go to Galleries
3. Create a new Item and  a Place within
4. Save
5. Go back to the Item created
6. Click on Place in the list
7. Observe

### Errors Shown

{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

16.19.0

### What database are you using?

Postgres 14.5

### What browser are you using?

Chrome

### How are you deploying Directus?

npm

**Comment by licitdev** [comment] 2023-01-28 19:17
Duplicate of #17108

**Closed by licitdev** 2023-01-28 19:17 UTC
