### ISSUE TITLE
Several actions in WYSIWYG full leads to an error

### ISSUE THREAD

**Issue by Alekshar** [directus/directus#1906] opened 2017-10-16 14:21 UTC
## Version Info
  - Directus version and branch: release 6.4.3 zipped
  - OS name and version: Windows 7
  - Browser : Chrome 61

## Expected Behavior
As I am trying to use the WYSIWYG full editor, many operations are failing by throwing the same error
"Error: Uncaught TypeError: e.replace is not a function
File: http://localhost:8081/directus/app/directus.min.js?bust=pg7e04e6c0p4sj47i5ol8pa7s7
Line:32"

Underline, define table width or create lists (both dotted and numeric) are affected by this error.

**Comment by rijkvanzanten** [comment] 2017-10-16 14:46
Hey @Alekshar! Could you maybe try out the non-zipped non-pre-built version from the master branch here on github? I'm curious if this is an issue in the actual source code or something is wrong in the buildchain 👍

**Comment by Alekshar** [comment] 2017-10-17 07:40
@rijkvanzanten the version from the master branch works well, thanks :smile: 

Not sure if my second question is related or requires a new issue but the image selector in the editor does not contains the browsing icon as it is in the tinyMCE demo.

**Comment by rijkvanzanten** [comment] 2017-10-20 17:38
Hi @Alekshar!

The image-selector-browsing-icon is not an issue, but a not-yet-implemented feature: https://request.getdirectus.com/r/119.

It's a nice feature to have, but I'm afraid it won't get implemented soon, since it requires us to write a [custom TinyMCE file browser](https://www.tinymce.com/docs-3x/howto/TinyMCE3x@How-to_implement_a_custom_file_browser/) and we have our hands full with more pressing issues.....

We'd love a PR with this implementation of course 😄

**Comment by rijkvanzanten** [comment] 2017-10-20 17:39
@WellingGuzman Could you checkout the bundling script? Seems like there is something missing

**Comment by WellingGuzman** [comment] 2017-10-20 20:46
Sure, on it!

**Comment by michlschmitt** [comment] 2018-01-23 11:29
Any improvements on this? Still getting the error "TypeError: e.replace is not a function" in Firefox, Chrome, Safari, when inserting a list.

**Comment by WellingGuzman** [comment] 2018-01-23 13:42
I'm sorry, there's not improvements yet, as far as I remember this happens only on the `build` version, my suggestion for now, not a good one, but use the non-build version.

I had some issue figuring out why some plugins works where other, such as  `underline`, does not work.

**Comment by rijkvanzanten** [comment] 2018-03-20 13:52
@WellingGuzman Any updates on this? Has it been "officially" solved in later builds? 

I'll close this for now as I'm not able to reproduce it on the latest version. If anyone else runs into this issue, please let us know and we'll reopen the issue

**Comment by widness** [comment] 2018-04-03 07:28
Hi @rijkvanzanten,
I've got the "TypeError: e.replace is not a function" error again when I wanted to use the "Numbered list" on chrome.

**Comment by rijkvanzanten** [comment] 2018-04-03 13:24
Ughh this minification vs tinymce weirdness is driving me crazy! We use a completely reworked builchain in the next major version of Directus, so at least it (should) (be/)is fixed there.

**Comment by benhaynes** [comment] 2018-10-25 18:08
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/11)

**Closed by benhaynes** 2018-10-25 18:08 UTC
Labels: 5. Trivial, 6. In-Progress, Interface, v6
