### ISSUE TITLE
Email sends lines longer than 75 characters

### ISSUE THREAD

**Issue by Fx4-X** [directus/directus#6074] opened 2021-06-04 10:29 UTC
User invite Email corrupt.

![image](https://user-images.githubusercontent.com/37863084/120786914-69e90f80-c54c-11eb-9eeb-c5ae138e542d.png)

if I looks at the email source, I get this. 

Edit : file attached 
[email.txt](https://github.com/directus/directus/files/6597825/email.txt)

the invite link is not working even if the email open in browser. The link as well corrupt,

Most of the long lines have a "="+CR in between.

---

### Project details
Directus Version: 9.0.0-rc.72
Environment: production
OS: Linux 3.10.0-1160.24.1.el7.x86_64 (Docker)
Node: 14.17.0

**Comment by rijkvanzanten** [comment] 2021-06-04 16:14
The links are most likely because your `PUBLIC_URL` value is set to `http://example.com`. The line length is an interesting quirk that I wasn't aware of. Apparently, outlook and some other email software requires a maximum line-length of 75 characters, and will inject a `=` and a line break if the line exceeds that 🤔 Haven't seen that in any other modern email software (like macOS's mail.app or Gmail)

**Comment by Fx4-X** [comment] 2021-06-15 15:08
Thanks @rijkvanzanten for the quick attention,

however the lines still get truncated, (rc76)

`<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.=
org/TR/html4/strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="viewport" content="width=device-width=
">
<meta name="format-detection" content="telephone=no">`

**Comment by Fx4-X** [comment] 2021-06-15 18:56
I had a look at the other emails received and there are email with 264 charter long lines and they are rendered correctly.
only the directus emails get truncated.

I played around little but with the HTML header, to check if that's make a difference. but no luck.
The html string after the prettier still have the long url with 259 character long, don't known if that's the issue.

**Comment by rijkvanzanten** [comment] 2021-06-17 14:02
> I had a look at the other emails received and there are email with 264 charter long lines and they are rendered correctly.
only the directus emails get truncated.

This is very strange! What exact email software do you use? What sort of email server is in between? 

> I played around little but with the HTML header, to check if that's make a difference. but no luck.

This would be my guess as well! There must be a certain flag somewhere in the flow directus->outlook(?) that causes it to go haywire 🤔

**Comment by rijkvanzanten** [comment] 2021-08-03 22:51
Could you check what settings you have enabled in Outlook as per https://www.lifewire.com/wrap-long-lines-automatically-1165688 ?

I can't reproduce this on my end, and from what I can tell Directus sends emails according to the rules..

I'll close this for now, we can reopen once more information on the problem/potential solution becomes available

**Closed by rijkvanzanten** 2021-08-03 22:51 UTC
Labels: API, Bug, Needs More Info

**Comment by filiphanes** [comment] 2023-01-13 16:53
=CRLF is used by [quoted printable encoding](https://en.wikipedia.org/wiki/Quoted-printable)
When email client sends html it encodes it to MIME part, some clients choose quopri, some base64.
It should not matter how log lines html contains. It even could be one long line.

Quoted printable is used for mostly text content since it doesn't has so much overhead as base64 encoding.
Nodemailer should do this encoding before sending it to SMTP server.

I think this transformation is unnecessary or at least not based on correct assumptions
https://github.com/directus/directus/blob/24f1e539ba0f28b822b0d18da199eb6060e3186c/api/src/services/mail/index.ts#L69-L73
