### ISSUE TITLE
Default value is not send by trigger in flow

### ISSUE THREAD

**Issue by battosai30** [directus/directus#16074] opened 2022-10-20 13:20 UTC
### Describe the Bug

1. You set a default value for a field (tested with string, don't know if other types are impacted)
2. You have a flow which trig on items.create (don't know if other trigger or event are impacted)
3. You create a new item
4. In flow, the trigger doesn't send the value in payload (other values are transmitted). You have to modify it to be taken account.

### To Reproduce

Follow steps describing the bug

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

14.20.1

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Running binaries in Alpine

**Comment by azrikahar** [comment] 2022-10-20 13:23
Duplicate of #15237. The answer here should provide more clarification on what's happening by design: https://github.com/directus/directus/discussions/15246#discussioncomment-3469153

Feel free to share further thoughts and potential approaches on this topic over in #15246 👍

**Closed by azrikahar** 2022-10-20 13:23 UTC

**Comment by battosai30** [comment] 2022-10-20 13:28
Arf sorry for duplicate :s 

Thanks for quick answer ;)
