### ISSUE TITLE
Auth problem.

### ISSUE THREAD

**Issue by Attacler** [directus/directus#7822] opened 2021-09-03 21:34 UTC
@Attacler Are you sure you have the same problem? If you see in this thread, there was a very specific subset of variables in order to get the problem to show up (and subsequently resolve). It's probably best to open a new issue 👍🏻

_Originally posted by @rijkvanzanten in https://github.com/directus/directus/issues/3139#issuecomment-912818479_

I have an issue with Auth.
For some reason if i work in 2 Tabs (chrome) it sometimes expires the other tab.

I have RC90 installed right now.
It happends when i duplicate the tab, do some stuff there (for example open a record) and go back to the other tab.

The error i get inside networking tab is about invalid credentials while i never changed those during the session.
The PUBLIC_URL is filled in correctly.
It might have to do with missing ENV variables and it happend after updating from RC69.

**Comment by rijkvanzanten** [comment] 2021-09-03 22:31
Can you try updating to the latest version?

What version of Chrome? What is the exact way to accurately reproduce it?


(Next time, please fill out the full issue template. There's a lot of useful information in there we need to debug issues 🙂 )

**Comment by emrahnazif** [comment] 2021-09-05 15:58
This comment will not be very helpful but I confirm the issue.
If I have 2 tabs open, I am having Auth problem and SESSION_EXPIRED. Also when I login after a while (some times a few days), I am not able to login (as admin) maybe in my first 5-10 tries
I got this (with admin login):
<img width="545" alt="Screenshot 2021-09-05 at 17 45 19" src="https://user-images.githubusercontent.com/33692017/132132907-73bff2fd-4b9c-40ef-9b0e-88cbad562178.png">
After a few moment and many attempts, I can login again. 

console.log = Failed to load resource: the server responded with a status of 400 auth/refresh 
I also suspect If I leave the page from admin settings, this error shows up more frequently.

Almost same:
https://github.com/directus/directus/issues/3139#issuecomment-912818479

Sorry for not very helpful comment but right now it has been 15-20 mins that I am trying to login, still trying...

Chrome: Version 92.0.4515.159 (Official Build) (x86_64)
directus: v9.0.0-rc.90
postgre db

**Comment by emrahnazif** [comment] 2021-09-22 21:23
Update:
after updating directus to v9.0.0-rc.93, this is solved for me.
Still don't know what was the origin of the issue.

**Comment by emrahnazif** [comment] 2021-09-22 21:24
> Can you try updating to the latest version?
> 
> What version of Chrome? What is the exact way to accurately reproduce it?
> 
> (Next time, please fill out the full issue template. There's a lot of useful information in there we need to debug issues 🙂 )


Update:
after updating directus to v9.0.0-rc.93, this is solved for me.
Still don't know what was the origin of the issue.

**Comment by Attacler** [comment] 2021-09-24 11:28
I have this issue due to SDK auth i think.
Basicly things work fine as long as i use only directus in incognito.
If i try to use the SDK, it sometimes mixes sessions and gives weired feedback like logged out ect.

Also, when restarting directus, sometimes my whole screen gets white or my session is timed out and i have to login again.

**Comment by joselcvarela** [comment] 2021-09-24 13:05
So if you are using SDK (https://docs.directus.io/reference/sdk/#javascript-sdk) you are integrating this with your own app.
Am I right?

If that's the case you need to understand you are using two instances of the SDK.
That being said, you could take advantage of cookies, since they are shared by domain.
Here is how you configure cookies with SDK https://docs.directus.io/reference/sdk/#options

**Comment by rijkvanzanten** [comment] 2021-09-24 13:08
I'll close this for now, as it doesn't sound like there's a problem in Directus (or the SDK) that we can fix right now. We can continue the discussion here. If it turns out that a bug in the SDK is causing problems, we'll reopen and keep investigating 👍🏻

**Closed by rijkvanzanten** 2021-09-24 13:08 UTC
Labels: App, Needs More Info, Bug (Potential)

**Comment by Attacler** [comment] 2021-09-24 20:25
@rijkvanzanten this one can be opened again.

I have this too with a Directus only app (without the SDK).
Seems like it happends when something is updating and if you switch tabs before the update has been made, it will log you out.
![issue](https://user-images.githubusercontent.com/42644889/134735582-868d11c9-0072-411f-ab0e-ffc6e2fe03f3.gif)

**Comment by emrahnazif** [comment] 2021-09-24 20:28
> @rijkvanzanten this one can be opened again.
> 
> I have this too with a Directus only app (without the SDK).
> Seems like it happends when something is updating and if you switch tabs before the update has been made, it will log you out.
> ![issue](https://user-images.githubusercontent.com/42644889/134735582-868d11c9-0072-411f-ab0e-ffc6e2fe03f3.gif)

Info for my case: I was not using SDK as well. 
Can you try to update your directus? at least v9.0.0-rc.93

**Comment by rijkvanzanten** [comment] 2021-09-24 20:29
@Attacler can you open a new issue and fill out the issue form? The more specific the reproduction steps are the better 👍🏻

**Comment by Attacler** [comment] 2021-09-24 20:33
I`ve done it #8302
