### ISSUE TITLE
Accessing `Roles & Permission` causes crash

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#10062] opened 2021-11-25 17:34 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Accessing `Roles & Permission` causes crash. 
![image](https://user-images.githubusercontent.com/3661363/143483423-483503f6-ddfc-4806-b195-85d49f2847ce.png)

### To Reproduce

After updating from 9.0.1 to 9.1.1
Accessing settings > Roles & permissions

### Errors Shown

```
{
  "errors": [
    {
      "message": "select * from (select \"directus_users\".\"role\", count(\"directus_users\".\"id\") as \"count->id\" from \"directus_users\" where \"directus_users\".\"role\" = $1 order by \"directus_users\".\"id\" asc limit $2) as \"foo\" union all select * from (select \"directus_users\".\"role\", count(\"directus_users\".\"id\") as \"count->id\" from \"directus_users\" where \"directus_users\".\"role\" = $3 order by \"directus_users\".\"id\" asc limit $4) as \"foo\" union all select * from (select \"directus_users\".\"role\", count(\"directus_users\".\"id\") as \"count->id\" from \"directus_users\" where \"directus_users\".\"role\" = $5 order by \"directus_users\".\"id\" asc limit $6) as \"foo\" - column \"directus_users.role\" must appear in the GROUP BY clause or be used in an aggregate function",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.1.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgres:13

### What browser are you using?

Chrome

### What operating system are you using?

Linux 5.11.0-40-generic

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-11-25 17:35
Duplicate of https://github.com/directus/directus/issues/10047

**Closed by rijkvanzanten** 2021-11-25 17:35 UTC
Labels: Bug (Potential)
