### ISSUE TITLE
cannot use any map field with the directus docker image 

### ISSUE THREAD

**Issue by torstenhoegel** [directus/directus#9296] opened 2021-11-01 11:37 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I'm hosting directus instances with docker images. I'm passing an mapbox apikey to every instance, but I just discovered this error after adding a map field to a model.

```JSON
{
  "errors": [
    {
      "message": "select `ok`.`ll`, st_astext(`ok`.`map`) as `map`, `ok`.`status`, `ok`.`id` from `ok` where not `ok`.`status` = 'archived' order by `ok`.`id` asc limit 25 - SQLITE_ERROR: no such function: st_astext",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

This happens. on all docker based instances I created with v98-100. (haven't tested it with prior versions, though I guess its the same thing)

As found in the Docker Image it uses a SQLite 3 DB which may need some additional config?

`ENV DB_CLIENT=sqlite3 DB_FILENAME=/directus/database/database.sqlite EXTENSIONS_PATH=/directus/extensions STORAGE_LOCAL_ROOT=/directus/uploads`

### To Reproduce

pull directus docker image and run it

### What version of Directus are you using?

v9.0.0-rc.100

### What version of Node.js are you using?

NODE_VERSION=16.13.0

### What database are you using?

DB_CLIENT=sqlite3

### What browser are you using?

chrome/safari/brave

### What operating system are you using?

macOS IOS / error is directus related not client side

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-11-01 11:48
Duplicate of #7625. This comment should shed some light on this: https://github.com/directus/directus/issues/7625#issuecomment-906493651

Alternatively since you are using docker, you can opt to use [postgis/postgis](https://registry.hub.docker.com/r/postgis/postgis/) Docker image which is a PostgreSQL db with PostGIS extensions installed so you can get up and running without any manual modifications 👍

**Closed by azrikahar** 2021-11-01 11:48 UTC
Labels: Bug (Potential)
