### ISSUE TITLE
Sorting disappears

### ISSUE THREAD

**Issue by aliemba** [directus/directus#13769] opened 2022-06-07 10:34 UTC
### Describe the Bug

In a O2M relation with sorting active; when you reach x numbers of items it shows page 2 ect. (pagination)
![image](https://user-images.githubusercontent.com/44196248/172358487-83cec9aa-5965-4a4a-8163-f6b221866169.png)

This results in
- The sorting order ignored
- No ability to sort

I have no idea if this is by design - but the fact that i looses the sorting order makes it a bug?

Quick fix could  be to add a configurable parameter where you enter how many items "before pagination"
Also just making sure it honors the sorting field on multiple pages would help. 

### To Reproduce

Make a O2M relation + configure with sorting. Add a couple of items. Confirm sorting words. Now add as many items so that the "pages" are shown. 

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

v12.22.9

### What database are you using?

mysql  Ver 8.0.29

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-06-07 10:46
> I have no idea if this is by design - but the fact that i looses the sorting order makes it a bug?

It is technically by design (at the moment since the relational interfaces rework in 9.9.0) and not a bug, but understandably it's not ideal from a user perspective. This was brought up before in #12818, and this answer should shed some light on why sorting is "disabled"/hidden once pagination occurs: https://github.com/directus/directus/discussions/12818#discussioncomment-2585113

> Quick fix could be to add a configurable parameter where you enter how many items "before pagination"

I reckon this could be a quick fix indeed! But feel free to chime in on that discussion so that we can flesh out the potential short-term and/or long-term solutions for this scenario before executing it.

Closing in favor of the discussion as a feature request.

**Closed by azrikahar** 2022-06-07 10:46 UTC
