### ISSUE TITLE
Flows can't use create/update data operation on system collections

### ISSUE THREAD

**Issue by inovosel** [directus/directus#24161] opened 2024-12-06 14:40 UTC
### Describe the Bug

In flow, when adding Create, Update, Read or Delete Data operation, only user's collections are available in the dropdown menu. Because of that it is impossible to modify system collections (collections starting with "directus", for example directus_users).
It should be possible to select system collections just as it is possible now when creating a new Event Hook flow.

As a workaround, you can manually enter the name of the collection by typing collection name, for exampe `directus_users`.

### To Reproduce

Create a new flow, add new read, delete, create or update data node and under Collection try to select one of collections starting with "directus_".

### Directus Version

v11.3.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2024-12-06 15:29
Thanks @inovosel! I believe this is a duplicate of https://github.com/directus/directus/issues/20379 so I'll close this for now.

The reason the system ones aren't listed is because the operation uses the `ItemsService`, meaning that it skips any system operations that you'd expect to happen for those collections. For example if you'd create a collection record using the operation now, it wouldn't actually create a table in the database. The solve here is to upgrade the operation itself to select the correct service to use based on the call, but we can discuss that back on the original issue. Thanks!

**Closed by rijkvanzanten** 2024-12-06 15:29 UTC
