### ISSUE TITLE
Files & storage - large image duplication

### ISSUE THREAD

**Issue by drennvinn** [directus/directus#18339] opened 2023-04-27 15:01 UTC
### Describe the Bug

I have a problem with large duplicate images in the uploads folder. I realized that my uploads folder on the server was overloaded with useless copies. so i tried on a fresh project and it's the same. 
Here is a video of my problem: 

https://user-images.githubusercontent.com/18407632/234900596-a96f4548-3912-4a67-84c9-1c843fa3d3ab.mov

as you can see, after each navigation or page reload, it creates a new copy in my uploads folder.

this was not a problem for me until now but my clients have been using the platform a lot in the last few days and that's when I realized that the uploads folder was abnormally large (almost 10000 items for less than 100 images uploaded)

### To Reproduce

just install a new directus project locally and test it like in my video

### Directus Version

10.0.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by hanneskuettner** [comment] 2023-04-27 15:04
Looks like this could be a duplicate of #18301 and is fixed in #18316?

**Comment by azrikahar** [comment] 2023-04-27 15:25
@hanneskuettner is right on the money here! #18316 was merged _after_ the v10 release, so the fix is not released yet. 

Proceeding to close this as duplicate of #18301 for now, unless it's still reproducible in the future after the next release with said fix 👍

**Closed by azrikahar** 2023-04-27 15:25 UTC
