### ISSUE TITLE
The translation field type can no longer be used when its default name 'translation' is modified during its creation.

### ISSUE THREAD

**Issue by wazo** [directus/directus#4890] opened 2021-04-07 17:27 UTC
Hi,

The translation field type can no longer be used when its default name 'translation' is modified during its creation.
you just have to modify it to see that it is looking for a 'translation' reference, its behavior is immediately unstable.

Point to reproduce it is:

- The creation of a collection
- The creation of a translation field in modifiable its name by default with autogenerate. For example 'abc translation'
- then we edit the 'abc translation' field that we just created. We see that it is editing a field which is not the correct one, we see 'translation'.
- We also find that it is impossible to add recordings.

Directus Version v9.0.0-rc.54
Version de PHP | 7.4.16
Version de MySQL | 5.7.30
Chrome Version 89.0.4389.114 
I have to ask my network administrator how he installed directus

**Comment by Mrmiffo** [comment] 2021-04-15 11:16
This looks similar to issue https://github.com/directus/directus/issues/3361

**Comment by rijkvanzanten** [comment] 2021-04-15 14:51
Duplicate of #3361

**Closed by rijkvanzanten** 2021-04-15 14:51 UTC
Labels: Bug
