### ISSUE TITLE
Checkbox Tree interface is unstable inside Field Groups

### ISSUE THREAD

**Issue by emmett-exrx** [directus/directus#7414] opened 2021-08-14 02:27 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

The checkbox tree interface (both CSV and JSON) behaves erratically when inside a field group. Some options are not de-selectable, some external fields (if applicable) appear to refresh/reload their data.

### To Reproduce

1. Add a field group to a collection
2. Add/move a CSV or JSON field (using the checkbox tree interface) inside the group
   - Create a moderately complex tree (multiple levels, multiple children per level)
3. Create an item inside the collection
4. Try to edit the checkbox tree, selecting and de-selecting random items.

### What version of Directus are you using?

v9.0.0-rc.90

### What version of Node.js are you using?

v14.17.0

### What database are you using?

MariaDB 10.4.20

### What browser are you using?

Firefox

### What operating system are you using?

Linux (Fedora 33)

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-08-19 20:10
Duplicate of https://github.com/directus/directus/issues/7291

**Closed by rijkvanzanten** 2021-08-19 20:10 UTC
Labels: Bug (Potential)

**Comment by emmett-exrx** [comment] 2021-08-20 15:48
While #7291 is very similar, it's worth noting that this case doesn't involve conditions.
