### ISSUE TITLE
A folder containing a collection errors when applied to clean Directus install

### ISSUE THREAD

**Issue by amcnaughton** [directus/directus#12524] opened 2022-04-01 18:03 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I can add a folder to the navbar and put collections under it. I then dump the schema and apply it to a clean install. This fails with an `invalid foreign key` error.

```
13:54:29 🚨 Failed to create collection "feature_flags"
13:54:29 🚨 Invalid foreign key in field "group". 
Error: Invalid foreign key in field "group".
    at foreignKeyViolation (/Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/exceptions/database/dialects/postgres.js:101:12)
    at extractError (/Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/exceptions/database/dialects/postgres.js:29:20)
    at translateDatabaseError (/Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/exceptions/database/translate.js:51:56)
    at /Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/services/items.js:97:68
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I also posted this in Discord https://discord.com/channels/725371605378924594/741330910594465823/959478939812765796

### To Reproduce

Here's my `schema.yaml`

```
version: 1
directus: 9.7.1
collections:
  - collection: feature_flags
    meta:
      collection: feature_flags
      icon: null
      note: null
      display_template: null
      hidden: false
      singleton: true
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: 1
      group: lookups
      collapse: open
    schema:
      schema: pinky
      name: feature_flags
      comment: null
  - collection: lookups
    meta:
      collection: lookups
      icon: folder
      note: null
      display_template: null
      hidden: false
      singleton: false
      translations: null
      archive_field: null
      archive_app_filter: true
      archive_value: null
      unarchive_value: null
      sort_field: null
      accountability: all
      color: null
      item_duplication_fields: null
      sort: 1
      group: null
      collapse: open
    schema: null
fields:
  - collection: feature_flags
    field: id
    type: integer
    schema:
      name: id
      table: feature_flags
      schema: pinky
      data_type: integer
      is_nullable: false
      generation_expression: null
      default_value: nextval('feature_flags_id_seq'::regclass)
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: 32
      numeric_scale: 0
      is_unique: true
      is_primary_key: true
      has_auto_increment: true
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: feature_flags
      field: id
      special: null
      interface: input
      options: null
      display: null
      display_options: null
      readonly: true
      hidden: true
      sort: 1
      width: full
      translations: null
      note: null
      conditions: null
      required: false
      group: null
  - collection: feature_flags
    field: user_updated
    type: uuid
    schema:
      name: user_updated
      table: feature_flags
      schema: pinky
      data_type: uuid
      is_nullable: true
      generation_expression: null
      default_value: null
      is_generated: false
      max_length: null
      comment: null
      numeric_precision: null
      numeric_scale: null
      is_unique: false
      is_primary_key: false
      has_auto_increment: false
      foreign_key_schema: null
      foreign_key_table: null
      foreign_key_column: null
    meta:
      collection: feature_flags
      field: user_updated
      special:
        - user-updated
      interface: select-dropdown-m2o
      options:
        template: '{{avatar.$thumbnail}} {{first_name}} {{last_name}}'
      display: user
      display_options: null
      readonly: true
      hidden: true
      sort: 3
      width: half
      translations: null
      note: null
      conditions: null
      required: false
      group: null
relations: []
```

Then run `npx directus schema apply ./schema.yaml`

### Errors Shown

```
13:54:26 ✨ Loaded extensions: tree, morning_consult
? Collections:
  - Create feature_flags
  - Create lookups
? Collections:
  - Create feature_flags
  - Create lookups
? Collections:
  - Create feature_flags
  - Create lookups

Fields:
  - Create feature_flags.id
  - Create feature_flags.user_updatedThe following changes will be applied:

Collections:
  - Create feature_flags
  - Create lookups

Fields:
  - Create feature_flags.id
  - Create feature_flags.user_updated

Would you like to continue? Yes
13:54:29 🚨 Failed to create collection "feature_flags"
13:54:29 🚨 Invalid foreign key in field "group". 
Error: Invalid foreign key in field "group".
    at foreignKeyViolation (/Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/exceptions/database/dialects/postgres.js:101:12)
    at extractError (/Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/exceptions/database/dialects/postgres.js:29:20)
    at translateDatabaseError (/Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/exceptions/database/translate.js:51:56)
    at /Users/Allan.McNaughton/dev/pinky/node_modules/directus/dist/services/items.js:97:68
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

v16.14.0

### What database are you using?

Postgres 12.4

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-04-01 18:06
Duplicate of https://github.com/directus/directus/issues/9723

**Closed by rijkvanzanten** 2022-04-01 18:06 UTC
Labels: Bug (Potential)
