### ISSUE TITLE
O2M not working with SQLite

### ISSUE THREAD

**Issue by Pachat** [directus/directus#10979] opened 2022-01-11 18:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It's impossible to add an item in the detail collection

### To Reproduce

- Create a parent collection : Countries (Name)
- Create a detail collection : Cities (Name)
- Add a O2M to Countries (Cities of the country)
- Add a country in Countries (USA) leave the O2M field (Cities of the country) empty
- Add a city in Cities : see Error on saving

### Errors Shown

```json
{
  "message": "Invalid foreign key.",
  "extensions": {
    "code": "INVALID_FOREIGN_KEY"
  }
}
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-01-11 21:49
I can't reproduce this on a fresh installation on SQLite with the reproduction steps. Could you share a copy of a sqlite database where this is happening?

The error sounds to me like the many to one field on the "cities" item was filled with a wrong value. Can you confirm if there's any other fields on `cities` you might be setting when you're running into this problem?

I'll close this for now, as the steps to reproduce seems to work as expected. We can reopen if new info comes up 👍🏻

**Comment by Pachat** [comment] 2022-01-12 06:25
Thanks for your try.
I ran with a fresh install, following exactly the steps above and reproduced the same bug
Here is the copy of the data.db: [data.zip](https://github.com/directus/directus/files/7852178/data.zip)  with `Username=Password=admin-directus-local@localhost.com`
To raise the bug, try to add a city (/admin/content/cities/+)


.

**Comment by Pachat** [comment] 2022-01-17 09:05
Same message error when trying to create a `Tree View` with SQLite

**Comment by joselcvarela** [comment] 2022-01-17 14:54
Hello @Pachat 
This database is misconfigured. If you inspect your database you would see that the `name` of `cities` is pointing to `id` in `countries`. That's why you will have always an error.
To create an O2M relationship you would need to create a M2O first
https://docs.directus.io/configuration/relationships/#one-to-many-o2m

**Closed by joselcvarela** 2022-01-17 14:54 UTC
Labels: DB: SQLite, Bug (Potential)

**Comment by Pachat** [comment] 2022-01-17 17:26
Yes indeed it works.
What I missed is that I could type a new foreign key directly in the Foreign Key box for I focused on it's drop-down
![Foreign Key](https://user-images.githubusercontent.com/13746133/149814146-3c0660d8-d023-4ff9-b0e9-dba4932f6538.png)

Thank you for your time.

**Comment by joselcvarela** [comment] 2022-01-17 17:38
No problem 👍
@benhaynes don't know if it worths take a look on how we show that dropdown 👀
Maybe on focus, we could open automatically the list. 🤔

**Comment by benhaynes** [comment] 2022-01-17 17:51
Maybe as simple as changing the placeholder to say `New or existing key...`?

**Comment by Pachat** [comment] 2022-01-17 18:05
Good idea.
Expanding maybe : `Type new key or lookup existing one`   (may be shorten. The idea is to show the word `Type`)

**Comment by benhaynes** [comment] 2022-01-17 19:18
That is more descriptive and should fit in the input, we just need to be careful about translations. Longer text translations can sometimes be _much_ longer... and not at all fit as placeholders (without scrolling).
