### ISSUE TITLE
Detail view not working for newly created user in 10.5.2

### ISSUE THREAD

**Issue by rowild** [directus/directus#19371] opened 2023-08-08 06:44 UTC
### Describe the Bug

When a new user is created In 10.5.2, and its detail view is called, the detail view disappears. This does NOT happen for already existing users (that is: users that existed before the update to 10.5.2).

I experience this behaviour on local Docker instances and on DigitalOcean.

Here is a video that shows the behaviour:
https://dl.rowild.at/directus-creating-users-in-10.5.2-detail-view-not-working.mp4

This feature works fine in 10.5.1 and before.

### To Reproduce

- in a v10.5.2 instance create a new user
- click on it to open the detail page

### Directus Version

10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-08-08 09:07
Duplicate of #19303, fixed in #19308.

**Closed by paescuj** 2023-08-08 09:07 UTC

**Comment by rowild** [comment] 2023-08-08 13:38
@paescuj Thank you! Didn't see #19303 - sorry for the duplication!
