### ISSUE TITLE
Related Collections dropdown of Builder M2A relation does not work - duplicates relations

### ISSUE THREAD

**Issue by andreiwow2** [directus/directus#22468] opened 2024-05-12 07:09 UTC
### Describe the Bug

When using the Builder (M2A) component, only when creating it the first time can I choose the relations, and as I see, even then, it creates a duplicate. But even afterwards, trying to edit the component, the dropdown doesnt work as expected, it duplicates random relations not related to what I select.

Here is a video of the issue
https://www.awesomescreenshot.com/video/27583150?key=0ea44bb72e46fa7612f130ebe13dfecf

### To Reproduce

Just create a collection and add a Builder (M2A) to it, I don't have anything extra or plugins to my instance and it happens each time. I have to edit the relations through database manually, the dropdown doesnt work at all.

Also, apparently it happens only when trying to remove a collection that is already selected, adding more collections to the Builder have no issue.

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-05-12 09:05
Heya! Thanks for opening this issue, I am, however, unable to reproduce this issue on the most recent version (v10.11.0). 
Do you have the chance to update to the most recent version and test again on your end? I'm gonna close this issue now, but I'm happy to re-open if you can confirm that this issue still persists in the most recent version.

**Closed by hanneskuettner** 2024-05-12 09:05 UTC
