### ISSUE TITLE
Image flashes when editing text under it

### ISSUE THREAD

**Issue by sandrosc** [directus/directus#14149] opened 2022-06-28 10:05 UTC
### Describe the Bug

When editing an entity with a image and text and the image is an SVG, the image flashes while typing in the text field.

### To Reproduce

- Create a data model, with image and translation fields.
- Add a Text input field to the generated translations data model.
- Create another data model with a many to many field that maps to the first data model, use it as a singleton.
- Click create new and add the SVG image and some text.
- Edit the list item and type something in the text input field.

Image: <img src="https://user-images.githubusercontent.com/12650063/176145351-ef7178ce-ba8a-4d69-b2be-7b47bbfa1f98.svg" width="100px" />

### Errors Shown

Movie of the bug: 

https://user-images.githubusercontent.com/12650063/176139971-c44b0947-b82f-4c93-8c49-f07d6a3c6e0a.mov

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

v16.14.2

### What database are you using?

PostgreSQL 13.7

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-06-28 15:51
@sandrosc Could you reupload the video? It's not loading / showing for me 🤔

**Comment by rijkvanzanten** [comment] 2022-06-28 21:04
I believe this was resolved by https://github.com/directus/directus/pull/14035. Could you verify on your end @sandrosc? We can reopen if not 🙂

**Comment by sandrosc** [comment] 2022-06-30 08:07
Still happening with Directus 9.13.0, please reopen.

**Comment by br41nslug** [comment] 2022-06-30 11:05
I have re-opened the ticket but i am not able to reproduce it so far using the given reproduction steps (tested on `9.12.2`, `9.13.0` in both `firefox` and `chrome`).
Are there other things in the setup that could be crucial for this like conditions or permissions?
https://www.loom.com/share/e110026f5bd643b8a009b102d230c929

**Comment by sandrosc** [comment] 2022-06-30 13:15
Thanks for trying to reproduce it. Please try the following steps and lmk if it works:

- create a few items
- save the entity
- reopen the entity
- click on an item you generated before
- try editing the text now

**Comment by rijkvanzanten** [comment] 2022-06-30 13:16
@sandrosc Can you share a database dump with a reproduction of this setup? 🤔

**Comment by azrikahar** [comment] 2022-08-18 10:59
I've attempted to reproduce this on Directus `9.15.1` with the following steps:

- Create a data model `posts`, with image and translations fields.
- Add a string input field to the generated translations data model.
- Create another data model `homepage` with a many to many field that maps to the first data model, use it as a singleton.
- Click create new and add the SVG image and some text.
- Edit the list item and type something in the text input field.

But unfortunately I was still not able to reproduce it:

https://user-images.githubusercontent.com/42867097/185378837-5fa9edfc-5fb6-4a4e-a907-3a20647cdd7d.mp4

Hence I'll be closing this for now, while we await for the database dump to investigate this further 👍

**Closed by azrikahar** 2022-08-18 10:59 UTC
Labels: App, Needs More Info, Bug (Potential), Can't Reproduce
