### ISSUE TITLE
users.me.read() return 401 on reload

### ISSUE THREAD

**Issue by altezza04** [directus/directus#3411] opened 2020-12-14 09:02 UTC
After successfully login, using the Javascript SDK users.me.read() return 401 on reload.

{"errors":[{"message":"Invalid user credentials.","extensions":{"code":"INVALID_CREDENTIALS"}}]}

**Comment by rijkvanzanten** [comment] 2020-12-14 13:46
Please read and fill out the issue template next time.

Duplicate of https://github.com/directus/directus/issues/3313

**Closed by rijkvanzanten** 2020-12-14 13:46 UTC
