### ISSUE TITLE
Directus SDK Slow Update

### ISSUE THREAD

**Issue by aazucena** [directus/directus#11176] opened 2022-01-20 02:04 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Whenever I either add, update, or delete an item from the Directus API with the SDK, it doesn't immediately take in affect to update the data. The framework I am using for this is with Gastby with React JS

My Code: 
```javascript
   /// File: components/records/index.js
    
import { readItemsByCollections, getCurrentUser, redirect } from 'services'
    ...
    // Initially adds data when mount
    componentDidMount = async() => {
        this.mounted = true
        // function for directus.users.me.read()
        const user = await getCurrentUser()

        // function for directus.items(this.name).readMany(this.params)
        const items = await readItemsByCollections(this.name,  { ...this.params, sort: 'id', filter: { grower: { _eq: user.grower ?? 1 }}, limit: 10, page: this.state.current + 1 })
       
        //Filters data based on year
        const filtered = items.data?.filter(_ => parseInt(_.date.substring(0, 4)) === this.year)
        
        ...

        // set state for data
        this.setState({ items: filtered, grower: user.data?.grower ?? 1, totalPages: Math.ceil((filtered.length)/10) })
    }
    //Updates data if either the component's state values or prop values are changed 
    componentDidUpdate = async(prevProps, prevState) => {
        if(prevState.current !== this.state.current) {
        this.mounted = true
        // function for directus.users.me.read()
        const user = await getCurrentUser()

        // function for directus.items(this.name).readMany(this.params)
        const items = await readItemsByCollections(this.name,  { ...this.params, sort: 'id', filter: { grower: { _eq: user.grower ?? 1 }}, limit: 10, page: this.state.current + 1 })
       
        //Filters data based on year
        const filtered = items.data?.filter(_ => parseInt(_.date.substring(0, 4)) === this.year)
        
        ...
        
        // set state for data
        this.setState({ items: filtered, grower: user.data?.grower ?? 1, totalPages: Math.ceil((filtered.length)/10) })
        }
    }
   /// File: components/records/edit.js
   import { updateItem, storage, redirect } from 'services'
  
   ...
   // submit event for submitting changed items to Directus and create message notification
    onSubmit = async(event) => {
        (event) && event.preventDefault()
        // function that capitalize the names and replace '_' with spaces
        const format = s => s.replaceAll("_", " ").toLowerCase().split(' ').map((_) => _.charAt(0).toUpperCase() + _.substring(1)).join(' ')
        await updateItem(this.id, this.name, this.state.items)
            .then(() => localStorage.set('message', 
                JSON.stringify({ title: 'Success', message: `Editing ${format(this.name)} Record`, response: this.state.items })))
            .then(_ => redirect(`/${this.name}`))
            .catch(e => localStorage.set('message', 
                JSON.stringify({ title: 'Fail', message: `[Editing ${format(this.name)} Record] - ${e}`, response: this.state.items })))
    }

   /// File: services/index.js

   //initialize directus with the url from .env file (different between development and production mode)
   const directus = new Directus(`${process.env.PUBLIC_URL}`)
   // export Directus' localStorage
   export const storage = directus.storage
   ...
   // get current user from directus
    export async function getCurrentUser() {
      return await directus.users.me.read()
        .catch(async(e)=> {
	        redirect(`/login`) // redirects to login page if function fails
        })
    }
   // get all items from a specific collection based on the parameters given
    export async function readItemsByCollections(name, params) {
	    return await directus.items(name).readMany(params ?? {})
    }
    //update an item from a specific collection based on the parameters given
    export async function updateItem(id, name, params) {
	    return await directus.items(name).updateOne(id, params)
    }
  
```

### To Reproduce

https://user-images.githubusercontent.com/43855657/150248760-d1ce838c-f860-4245-9048-35fd3bb09ec9.mp4

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.3.1

### What database are you using?

MySQL 5.7.35

### What browser are you using?

Brave/Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by joselcvarela** [comment] 2022-01-20 06:21
Can you provide a more simple example?
Try to just to use create-react-app and SDK to show this behaviour.

It seems to me that you are not rerendering the component after the submit.
React is trying to reuse the same component and since you didn't update the state or the props, it just shows the same information.

I am closing this for now since I believe there's an issue on your end.
But if you can provide a minimal setup to reproduce this issue we can look into it again 👍

**Closed by joselcvarela** 2022-01-20 06:21 UTC
Labels: Invalid, Needs More Info
