### ISSUE TITLE
Not possible to add new Item in Table

### ISSUE THREAD

**Issue by jopi2016** [directus/directus#1982] opened 2017-12-04 13:26 UTC
Hi,
I am trying to add a new item to a table which is not possible.
What I see is the following:
![grafik](https://user-images.githubusercontent.com/17023802/33554668-f7781d4e-d8fd-11e7-8611-e0f6ce0c2cb8.png)

Firefox 52.1.1. Developer Console shows the following:
Synchrone XMLHttpRequests am Haupt-Thread sollte nicht mehr verwendet werden, weil es nachteilige Effekte für das Erlebnis der Endbenutzer hat. Für weitere Hilfe siehe http://xhr.spec.whatwg.org/  directus.min.js:7:8633
XML-Verarbeitungsfehler: "Junk" nach Dokument-Element
Adresse: http://192.168.1.140/directus_v/app/templates/navbar.handlebars
Zeile Nr. 5, Spalte 1:  navbar.handlebars:5:1
XML-Verarbeitungsfehler: Nicht übereinstimmendes Tag. Erwartet: </hr>.
Adresse: http://192.168.1.140/directus_v/app/templates/tabs.handlebars
Zeile Nr. 30, Spalte 5:  tabs.handlebars:30:5
XML-Verarbeitungsfehler: Nicht übereinstimmendes Tag. Erwartet: </hr>.
Adresse: http://192.168.1.140/directus_v/app/templates/bookmarks-list.handlebars
Zeile Nr. 48, Spalte 3:  bookmarks-list.handlebars:48:3
XML-Verarbeitungsfehler: "Junk" nach Dokument-Element
Adresse: http://192.168.1.140/directus_v/app/templates/header/header.handlebars
Zeile Nr. 11, Spalte 1:  header.handlebars:11:1
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: http://192.168.1.140/directus_v/app/templates/core/widgets/save-widget.handlebars
Zeile Nr. 1, Spalte 98:  save-widget.handlebars:1:98
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: http://192.168.1.140/directus_v/app/templates/core/widgets/button.handlebars
Zeile Nr. 1, Spalte 9:  button.handlebars:1:9
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: http://192.168.1.140/directus_v/app/core/interfaces/_system/primary_key/input.handlebars
Zeile Nr. 1, Spalte 37:  input.handlebars:1:37
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: http://192.168.1.140/directus_v/app/core/interfaces/numeric/input.handlebars
Zeile Nr. 1, Spalte 133:  input.handlebars:1:133
XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: http://192.168.1.140/directus_v/app/templates/interface-container.handlebars
Zeile Nr. 1, Spalte 1:  interface-container.handlebars:1:1
XML-Verarbeitungsfehler: "Junk" nach Dokument-Element
Adresse: http://192.168.1.140/directus_v/app/core/interfaces/_system/status/input.handlebars
Zeile Nr. 66, Spalte 1:  input.handlebars:66:1

The content of eg. navbar.handlebars is 
[navbar.handlebars.txt](https://github.com/directus/directus/files/1527196/navbar.handlebars.txt)

tabs.handlebars contains
[tabs.handlebars.txt](https://github.com/directus/directus/files/1527203/tabs.handlebars.txt)

## Version Info
  - Directus version and branch: v6.4.4 (Ruby Rabbit) (problem also occurred with current head)
  - PHP version: PHP Version 7.1.9
  - MySQL version:  Server-Typ: MariaDB, Server-Version: 10.1.26-MariaDB
  - Web server: XAMPP
  - OS name and version: Windows 7, 64-bit

## Expected Behavior
Item can at least be named

## Actual Behavior
Item can not be named, only its status can be changed

## Steps to Reproduce
 1. Download version 6.4.4
 2. Go through installation script
 3. Add a table and try to add an item inside of the table

**Comment by WellingGuzman** [comment] 2017-12-04 17:49
What does the error actually means? It seems odd to me that inserting a new item you get issues with the handlebars files.

Can you share your database dump?

**Comment by jopi2016** [comment] 2017-12-05 08:21
for sure, please find the database dump in the following file
[sql-dump.txt](https://github.com/directus/directus/files/1530219/sql-dump.txt)

**Comment by jopi2016** [comment] 2017-12-05 08:23
well, the errors basically mean that something in the xml-structure is wrong:
- xml not well formed
- wrong tag, other tag expected
etc.

**Comment by WellingGuzman** [comment] 2017-12-05 16:27
I'm not being able to reproduce this, I will guess that this has to do with your server, probably intercepting static files.

What modules have you apache install? if it's possible, can you give us a url that we can use and see this issue for ourself?

**Comment by jopi2016** [comment] 2017-12-15 15:09
Hi, thanks for your feedback.
According to <?php print_r(apache_get_modules()); ?> I have the following apache modules:
`Array
(
    [0] => core
    [1] => mod_win32
    [2] => mpm_winnt
    [3] => http_core
    [4] => mod_so
    [5] => mod_access_compat
    [6] => mod_actions
    [7] => mod_alias
    [8] => mod_allowmethods
    [9] => mod_asis
    [10] => mod_auth_basic
    [11] => mod_authn_core
    [12] => mod_authn_file
    [13] => mod_authz_core
    [14] => mod_authz_groupfile
    [15] => mod_authz_host
    [16] => mod_authz_user
    [17] => mod_autoindex
    [18] => mod_cgi
    [19] => mod_dav_lock
    [20] => mod_dir
    [21] => mod_env
    [22] => mod_headers
    [23] => mod_include
    [24] => mod_info
    [25] => mod_isapi
    [26] => mod_log_config
    [27] => mod_cache_disk
    [28] => mod_mime
    [29] => mod_negotiation
    [30] => mod_proxy
    [31] => mod_proxy_ajp
    [32] => mod_rewrite
    [33] => mod_setenvif
    [34] => mod_socache_shmcb
    [35] => mod_ssl
    [36] => mod_status
    [37] => mod_version
    [38] => mod_php7
)
`

I'm sorry but as it's a local installation I can provide you with an url.

**Comment by CarlLindsay** [comment] 2017-12-19 15:25
I'm receiving the same issue, using the docker container version.

Did you find a solution or the problem @jopi2016 ?

**Comment by jopi2016** [comment] 2017-12-20 11:49
Unfortunately I didn't find a solution to my problem.

**Comment by rijkvanzanten** [comment] 2018-02-02 04:42
@WellingGuzman Is there anything we can do to fix / debug this? I haven't been able to reproduce as well..

**Comment by adbutler123** [comment] 2018-03-17 06:54
@jopi2016, I feel so stupid reaching out like this but I don't know how to move forward if I don't. I'm familiar with the macbook rather than windows, if that makes any since after I finish.

How in the world did you get directus to install on windows using an *amp program in the first place? I've gotten as far as establishing the database connection, and after that, all else fails. For me, the instructions have not been intuitive or self-explanatory. 

I'm trying to learn development on my own, and sometimes it's like pulling teeth trying to make things work, and half the time, you realize they _shouldn't_ work at all.

I hope I'm not the only one experiencing this problem...

**Comment by adbutler123** [comment] 2018-03-17 07:29
@WellingGuzman, I edited the conf-sample.php file that is in the API folder to match my database credentials. Then I go to https://demo.getdirectus.com/directus (I saved the directus folder as "directus" in htdocs), and I attempt to sign in with both my email and database credentials. Neither work. Seems like I'm missing a huge chunk of info here, and I'm working with windows so I only have Command Prompt (as opposed to Terminal).

**Comment by adbutler123** [comment] 2018-03-17 07:30
Oh, also, I did save the edited conf-sample.php file as conf.php.

**Comment by adbutler123** [comment] 2018-03-17 07:32
"Wrong username and/or password"

**Comment by WellingGuzman** [comment] 2018-03-17 07:38
You need to change `config_sample.php` and `configuration_sample.php` and set `DIRECTUS_PATH` to `/directus/` in `config.php` if you set directus inside a subdirectory named `directus`.

and do these steps in your terminal/command prompt: https://github.com/directus/docs/blob/master/developer-guide/cli.md#install-module

Or forget about the renaming the config and go to `yourdirectus.local/installation` Head over to slack or stackoverflow and use our tag `directus` to stop spamming this ticket with other issue.

**Comment by rijkvanzanten** [comment] 2018-03-20 14:09
Hey @adbutler123!

Feel free to join us [over on Slack](https://slack.getdirectus.com) if you keep having troubles installing the platform or have any other questions! As we all know, trying to learn webdev & learning the ins and outs of a new platform can be quite a bumpy ride.

I'll close this issue seeing it's not a bug or issue in the platform itself. We're hard at work on a complete rewrite of the platform (v7.0) which also comes with completely rewritten docs, so while it doesn't help right away, it should make installing the platform an easier process!

**Closed by rijkvanzanten** 2018-03-20 14:09 UTC
Labels: Can Not Duplicate
