### ISSUE TITLE
Grouped fields not displaying in 9.14.x

### ISSUE THREAD

**Issue by claytongulick** [directus/directus#14462] opened 2022-07-15 18:36 UTC
### Describe the Bug

On forms with grouped fields in 9.14.x (verified issue in both 9.14.0 and 9.14.1) the fields don't render:
<img width="1440" alt="Screen Shot 2022-07-15 at 1 33 59 PM" src="https://user-images.githubusercontent.com/695284/179288885-4d26a949-0ec2-4cdf-86bd-31a4f15266d3.png">

Downgrading to 9.13 fixes the issue:
<img width="1440" alt="Screen Shot 2022-07-15 at 1 35 18 PM" src="https://user-images.githubusercontent.com/695284/179289114-c163c597-72a1-4426-8392-dfff0be10b58.png">

### To Reproduce

Create a grouped field section in 9.14.x, add a raw group to it, and add fields to the raw group.

in 9.14.x the fields won't display, in 9.13 they do.

### What version of Directus are you using?

9.14.x

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

local

**Comment by rijkvanzanten** [comment] 2022-07-15 21:59
I believe this is a duplicate of https://github.com/directus/directus/issues/14349, which was resolved in https://github.com/directus/directus/pull/14369 🙂

**Closed by rijkvanzanten** 2022-07-15 21:59 UTC
