### ISSUE TITLE
Validation error in O2M relationship

### ISSUE THREAD

**Issue by ilFuma** [directus/directus#3929] opened 2021-02-04 16:31 UTC
Hi team,
 I have an error while trying to create (or adding an existing) an item in a O2M relationship using the admin UI.

Let me give you some context:
- I created two collections: Product_Lines and Products.
- The collection Products has a M2O relationship with Product_Lines
- The collection Product_Lines has a O2M relationship with Products

If I try to create a new product directly from the product_lines detail i get the following error
![image](https://user-images.githubusercontent.com/1921876/106921140-ff45d580-670b-11eb-9859-6ce862a59da1.png)

Here a screen recording: https://drive.google.com/file/d/1CPZYKB91yElYFIehTAKKdLNsvS0vxya6/view?usp=sharing

I'm currently using Directus 9.0.0-rc.34, MySql 5.7, Npx

**Comment by Nitwel** [comment] 2021-02-19 11:30
Hmm, I tried to replicate this but it worked for me totally fine. Does this still happen to you?

**Comment by Nitwel** [comment] 2021-02-24 13:25
Okay, so the problem seems to be in the Api.
This gets send to the Api which then throws this error.
`PATCH { "products": [ 1, 2, { "name" : "Product 3", "productline" : 1 } ] }`
Even though productline is set to 1, it still throws an error that it can't be null.

**Comment by hubalt** [comment] 2021-04-03 18:12
+1, although while using the "Add Existing" option and not "Create New". I believe I was using the latest - rc 53. I've already torn down the instance so cannot provide more info but looks like this has already been root caused?

**Comment by rijkvanzanten** [comment] 2021-05-22 02:57
Fixed in https://github.com/directus/directus/pull/5615

**Closed by rijkvanzanten** 2021-05-22 02:57 UTC
Labels: API, Bug
