### ISSUE TITLE
Custom group permissions can't edit users

### ISSUE THREAD

**Issue by u12206050** [directus/directus#2051] opened 2018-02-07 11:02 UTC
## Version Info
  - Directus version and branch: 1.1
  - PHP version: 7.0.27
  - MySQL version: 10.1.30-MariaDB
  - Web server: apache
  - OS name and version: CENTOS 7

## Expected Behavior
Edit all users, (possibly with the exception of administrators)

## Actual Behavior
I can view all users, but I can only edit myself.

## Steps to Reproduce
**As Admin**
 1. Create a new permissions group (eg. Manager)
 2. Set the permissions for `directus_users` to 2,2,2,2 (Full view, edit, add and delete)
 3. Add a user to the permissions group
 4. Login as that user and check user directory
 5. Notice you can view all other users, but can only edit the current logged in user

**Comment by rijkvanzanten** [comment] 2018-02-19 15:56
@WellingGuzman Is this expected behavior?

**Comment by WellingGuzman** [comment] 2018-02-25 21:05
This is an expected behavior, but this is a mid-done feature as I can see now.

This was intended at first that the admin were the only group to edit users information, but any other group will be allowed to only edit their info.

I will take this limitation was it doesn't make sense because the group has actually permission to edit that any user information if the permission is granted.

**Comment by WellingGuzman** [comment] 2018-02-25 21:16
Closed by https://github.com/directus/directus/commit/f3b6c17cf72be18cb8962dc76083659b5798a363

**Closed by WellingGuzman** 2018-02-25 21:16 UTC
Labels: 3. Major, API, Bug
