### ISSUE TITLE
Docker Issue Migrating to v9.0.0-rc.93

### ISSUE THREAD

**Issue by bfnsga** [directus/directus#8142] opened 2021-09-19 12:45 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Started with Docker image v9.0.0-rc.85. Currently using SQLite as the database that is automatically created by Directus when selected as the Environmental Variable in the Dockerfile.

Migrating to v9.0.0-rc.93 causes an issue on login. Admin user is no longer recognized and leads to a "No App Access" page. Did not experience this issue for any of the other incremental updates (v9.0.0-rc.85 - v9.0.0-rc.92).

None of the Environmental Variables have changed except for the Docker image tag. The database is connected via a Docker volume. I have tried upgrading directly from v9.0.0-rc.85 to v9.0.0-rc.93 as well as upgrading incrementally (v9.0.0-rc.85 to v9.0.0-rc.86 to v9.0.0-rc.87, etc.) with the same result.

I am not entirely sure how to further go about troubleshooting this issue since it seems to be related to the Docker image itself. Any help on further steps to troubleshoot / debug would be appreciated!

### To Reproduce

1) Stop running Docker container with previous image of Directus (i.e. v9.0.0-rc.85 - v9.0.0-rc.92)
2) Remove Docker container
3) Build new Directus image with or without --no-cache flag (doesn't work either way)
4) Start new Docker container with updated Directus image

### What version of Directus are you using?

v9.0.0-rc.93

### What version of Node.js are you using?

N/A

### What database are you using?

SQLite (packaged with Directus)

### What browser are you using?

Chrome / Firefox

### What operating system are you using?

Ubuntu 20.04.3

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-09-20 02:34
Hi thanks for the detailed description. I just tested using rc.85, removed it, updated to rc93 directly, and I was still able to login successfully. Would you mind providing further detail for the following:

- You mentioned in your reproduction step 3:  `Build new Directus image with or without --no-cache flag (doesn't work either way)`, so I gather you are using a Dockerfile with additional steps? If you do have a Dockerfile, can you share it here?
- Are you able to replicate this issue with a fresh Directus with fresh sqlite database? (while keeping your existing one backed up of course)
- Is there any particular error/warning logs shown for your Directus container?

**Comment by joselcvarela** [comment] 2021-09-20 04:25
Hey I am having this issue too,
The bug here is that the user loses the role on running migration latest. Even though in migrations code, I couldn't find anything related to it.

As workaround @bfnsga you could go to sqlite database directly and update the role of the users.
`update directus_users set role = (select id from directus_roles where name = 'Admin' limit 1);`

**Comment by joselcvarela** [comment] 2021-09-20 05:00
This  happened with existing database but I have tried to replicate locally with new database and I got it by doing the follow:
1.
1. Checkout to a rc.91
2. Run `npm run cli bootstrap --workspace=api`
3. Use SQLite and fill the user and password
4. Checkout to main
5. Run `npm run cli bootstrap --workspace=api` again (to run migrations)
6. Start api and app and try to login with previously created user in 3.

**Comment by azrikahar** [comment] 2021-09-20 05:33
Can confirm the bug on my end as well. I modified the env file but was running another docker-compose with env variables hardcoded in it 😅 Sorry for that @bfnsga 

> As workaround @bfnsga you could go to sqlite database directly and update the role of the users.
update directus_users set role = (select id from directus_roles where name = 'Admin' limit 1);

@joselcvarela I believe this will update all users to admin right? maybe we'll need to beware on whether they have many other users that does not have admin role in their current db before running it

**Comment by joselcvarela** [comment] 2021-09-20 05:52
@azrikahar yes you're right, I have only shared what I've done on my side to fix the issue.
I hope users know what they do with their data 😅

**Comment by rijkvanzanten** [comment] 2021-09-21 16:23
@bfnsga @azrikahar @joselcvarela How are you persisting the volume for the sqlite file? As soon as you replace the container, the whole database will be gone 🤔

**Comment by joselcvarela** [comment] 2021-09-21 19:01
In my case I was not using docker 😕

**Comment by azrikahar** [comment] 2021-09-28 08:03
Between rc.92 and rc.93, there's two additional migrations done, namely `Webhooks Collections Not Null` and `Move Module Setup`. However, since Move Module Setup drops a column on `directus_roles`:

https://github.com/directus/directus/blob/51148c11d6496b16a8be29860c6afa3ee4b942ba/api/src/database/migrations/20210910A-move-module-setup.ts#L4-L6

This causes Sqlite to recreate the table of a limitation with Sqlite itself, which then turns users `role` into `NULL` as they lost reference to it.

> SQLite has limited ALTER TABLE support that you can use to add a column to the end of a table or to change the name of a table. If you want to make more complex changes in the structure of a table, you will have to recreate the table.
> Source: https://www.sqlite.org/faq.html

_Thanks to @joselcvarela for bringing this up!_

### User has role in rc.92

![DB_Browser_for_SQLite_qI8RcoQW6c](https://user-images.githubusercontent.com/42867097/135047348-085e6785-a653-4318-9e13-52696acd8012.png)

### User lost role in rc.93 after migration

![DB_Browser_for_SQLite_PTKzccJJQP](https://user-images.githubusercontent.com/42867097/135047410-b59c5bfb-cfd0-4888-ac2e-db48929a767e.png)

After we turn off the foreign key support for SQLite in our migration process (Knex), users properly retain their roles:

![DB_Browser_for_SQLite_Bcm3tWznJN](https://user-images.githubusercontent.com/42867097/135047628-2696ec91-1958-486f-9d64-ef469c67be55.png)

This seems to be covered by #8367 now, so it should solve this issue as well as it's dealing with the same phenomenon.

**Comment by rijkvanzanten** [comment] 2021-09-28 12:44
@nickrum this looks like an unfortunate side effect of the alter table implementation we did on SQLite. When the table is dropped in the replace operation, the FK constraints kick in and cascade the drop 😳

**Comment by joselcvarela** [comment] 2021-09-28 14:30
@rijkvanzanten @nickrum this also happens when modifying an existent field which is a relation. In my case, I am using an O2M field and when setting it to readonly, it removes all the references from database related to that field.

**Comment by rijkvanzanten** [comment] 2021-09-28 22:55
This is a bug in knex that should be solved in knex (https://github.com/knex/knex/issues/4155). @nickrum already has a in-works poc PR to get that resolved, so I think we'll close this in favor of the linked issue/pr 🤔

**Closed by rijkvanzanten** 2021-09-28 22:55 UTC
Labels: API, Bug
