### ISSUE TITLE
Image-file interface not rendering

### ISSUE THREAD

**Issue by jesusgp22** [directus/directus#9631] opened 2021-11-09 04:00 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

After migrating from rc-94 to 9.0.0 stable the image interface doesn't work for PNG/JPG images but it does for SVG

At first it loads the squeleton but shortly after the interface is just empty 

<img width="1599" alt="Screen Shot 2021-11-08 at 10 52 58 PM" src="https://user-images.githubusercontent.com/2547899/140858979-b6b92547-9c3b-4529-b6ad-4c4a18452097.png">

If you select an SVG it works properly 

<img width="946" alt="Screen Shot 2021-11-08 at 10 53 47 PM" src="https://user-images.githubusercontent.com/2547899/140859064-41e8772d-a90f-414a-ae07-7052c8cdcc37.png">

It also works properly if you select the file interface

<img width="910" alt="Screen Shot 2021-11-08 at 10 54 35 PM" src="https://user-images.githubusercontent.com/2547899/140859130-b0a9e145-0492-4f1a-a209-bf6c33271ae1.png">

Database dump:
SELECT * FROM directus_fields where collection='test_page';
```
id  | collection |  field   | special | interface | options | display | display_options | readonly | hidden | sort | width | translations | note | conditions | required | group 
-----+------------+----------+---------+-----------+---------+---------+-----------------+----------+--------+------+-------+--------------+------+------------+----------+-------
 278 | test_page  | id       |         | input     |         |         |                 | t        | t      |      | full  |              |      |            | f        | 
 279 | test_page  | my_photo | file    | file      |         | image   |                 | f        | f      |      | full  |              |      |            | f        | 
```

SELECT * FROM test_page;
```
 id |               my_photo               
----+--------------------------------------
  1 | 104f92fb-f7ad-4bad-ad00-bfcb1601007a
```
  
  SELECT * FROM directus_files WHERE id='104f92fb-f7ad-4bad-ad00-bfcb1601007a';
  ```

                    id                  | storage |              filename_disk               | filename_download |    title     |     type      | folder | uploaded_by |     uploaded_on     | modified_by |     modified_on      | charset | filesize | width | height | duration | embed | description | location | tags | metadata 
--------------------------------------+---------+------------------------------------------+-------------------+--------------+---------------+--------+-------------+---------------------+-------------+----------------------+---------+----------+-------+--------+----------+-------+-------------+----------+------+----------
 104f92fb-f7ad-4bad-ad00-bfcb1601007a | amazon  | 104f92fb-f7ad-4bad-ad00-bfcb1601007a.svg | icon-medidas.svg  | Icon Medidas | image/svg+xml |        |             | 2021-10-21 20:44:25 |             | 53776-04-21 04:25:35 |         |     2997 |       |        |          |       |             |          |      | 
```
  

  

### To Reproduce

- Migrate from rc-94 to 9.0.0 
- Create an Image field
- Set the interface to Image
- Go to a collection and create an item
- Select or upload an image,

After that the photo is removed 

### Errors Shown

```
vendor.299bc11c.js:formatted:4113 SyntaxError: 14
    at B5 (vendor.299bc11c.js:formatted:6298)
    at Og (vendor.299bc11c.js:formatted:7467)
    at B9 (vendor.299bc11c.js:formatted:7687)
    at jA (vendor.299bc11c.js:formatted:7658)
    at vendor.299bc11c.js:formatted:7899
    at ft (vendor.299bc11c.js:formatted:7874)
    at er (vendor.299bc11c.js:formatted:7899)
    at _3.fn (index.eae14d77.js:72)
    at _3.run (vendor.299bc11c.js:formatted:504)
    at QF.get value [as value] (vendor.299bc11c.js:formatted:1090)
```

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.17,5

### What database are you using?

psql (PostgreSQL) 12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)

### What browser are you using?

Chrome latest

### What operating system are you using?

macOS Big Sur

### How are you deploying Directus?

Running on ubuntu LTS

**Comment by joselcvarela** [comment] 2021-11-11 00:17
Hello @jesusgp22,
I can see you are using amazon driver.
Is it possible to try with local driver to be ensure the problem is with interface and not with the driver implementation?

**Comment by gurumark** [comment] 2021-11-11 13:58
I have the same problem using the local driver. The images are not rendered in the editor. One other issue is the images do not have extension. Because of that we have to do complex Regex replacements. 

![Screenshot](https://user-images.githubusercontent.com/1859151/141310272-91dae002-566b-4a69-9aa9-e016f73a4ace.png)

Is it possible to fix this issue as well?

**Comment by joselcvarela** [comment] 2021-11-11 15:36
Hey @gurumark 
That is not an issue. It is that way by design.
But requesting an asset with extension should work as it was implemented here https://github.com/directus/directus/commit/c3c1337346adafabd5f5ba9b5a799a8eef9b62f4

**Comment by gurumark** [comment] 2021-11-11 15:53
@joselcvarela we push to content to create a static website. When HTML files are created based on the content, the images do not show because they don't have any extensions. So before pushing the content we have use regex replacement to change every img src attribute link with the corresponding file on disk.
I understand that it is by design but I was wondering if it breaks things if you add an file extension to the end. Thank you.

**Comment by joselcvarela** [comment] 2021-11-11 16:04
Hey @gurumark,
I understand that could be an obstacle. 
What I could suggest is to extract all images from your content, then ask directus for those files (https://docs.directus.io/reference/files/#retrieve-a-file) in order to obtain the mimetype.

About the feature request, check how we handle those here: https://docs.directus.io/reference/files/#retrieve-a-file

**Comment by joselcvarela** [comment] 2021-11-11 16:07
Hello @jesusgp22 
I have went into rc94 created an image field, back to 9.0.0 create a new image field and everything went OK.

I can see your `my_photo` in `test_page` is configured as `file` for `interface`, while I have `file-image`.
My suggestion is to double check your interface and see if is configured as `File` or `Image`.

Closing, since can't replicate.

**Closed by joselcvarela** 2021-11-11 16:07 UTC
Labels: Needs More Info

**Comment by gurumark** [comment] 2021-11-11 20:41
I got "Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID" error on the image file. That's the reason I could not see the image.
