### ISSUE TITLE
Assets have long TTFB

### ISSUE THREAD

**Issue by Attacler** [directus/directus#5902] opened 2021-05-26 19:47 UTC
1) The issue and what you expected to happen
    Basicly i expect less TTFB when i want to load an asset from within a browser.

2) Exact steps to reproduce this issue
    Upload a file
    Open the file as localhost:8055/assets/IDHERE
    Open your network tab and hover over the waterfall thing
    For some assets its upto 500ms
    
    Example: https://webscoped.nl/
    Take a look at the network tab and search for: aaa28b2f-06b1-462e-a0de-10f1be11f750
    (if you reload make sure to disable cache)
    This file is only around 10kB so it should not take that long (200 ms TTFB as of writing this)
    Looks like there is also a small cache (or maybe DB connection that is active?) so it can be faster sometimes
    Feel free to also take a look at the other images (all are compressed ofc)
    
3) envoirment
    Im using npm start (directus start) for localhost and for the example, i use the docker version. I use the local storage provider.

**Comment by FantaMagier** [comment] 2021-05-26 19:51
same issue. Everything is very fast but assets takes so long.
![image](https://user-images.githubusercontent.com/21313268/119722350-80b4a580-be6c-11eb-8a43-5db54603d986.png)

**Comment by rijkvanzanten** [comment] 2021-05-26 19:52
@FantaMagier Mind profiling the actual network time in the browser console? Your example doesn't really show anything..

Keep in mind that downloading large files can take a while, and that generating new thumbnails will take some time the first time as well.

**Comment by rijkvanzanten** [comment] 2021-05-26 19:53
@Attacler Do you have a way to reproduce the issue in a test environment? Your live example doesn't really help, as there's so much network / service overhead that's adding noise to what's going on 🤔

**Comment by Attacler** [comment] 2021-05-26 20:01
> @Attacler Do you have a way to reproduce the issue in a test environment? Your live example doesn't really help, as there's so much network / service overhead that's adding noise to what's going on 🤔

Sorry for that but it's literally uploading an asset and trying to load it in.

**Comment by rijkvanzanten** [comment] 2021-05-26 20:53
> Sorry for that but it's literally uploading an asset and trying to load it in.

Yeah, I hear what you're saying, but in that seemingly simple process, there's a million little variables that can cause different behavior 🙂 In order for me to investigate what's going on, and improve that bit, I need to get as close as I can get to your exact setup and experiment.

Things that might affect this:

* File type
* File size (kb/mb)
* File dimensions (width/height)
* Are you using docker
* Are you on windows/Mac
* Does your computer have an SSD
* What kind of CPU does your computer have
* Where is your database hosted
* Does your database have a large schema
* What sort of permissions do you use for files
* Are you accessing it from an admin user

Etc etc etc

On my end, just with [a random JPEG pulled from unplash.com](https://unsplash.com/photos/Sr3bhcYqftA), running on my M1 MacBook Air w/ `npm run dev` using the admin user `http://localhost:8080/assets/7049c174-4060-4745-b254-478d883c5b6d?access_token=admin` I'm getting the following:

<img width="536" alt="Screen Shot 2021-05-26 at 4 51 59 PM" src="https://user-images.githubusercontent.com/9141017/119729502-bc3a7a00-be42-11eb-9377-20b85233861f.png">

which is exactly what I would expect, and is about the same as every other endpoint 🤷🏻

**Comment by rijkvanzanten** [comment] 2021-05-26 20:55
Just as a random example, by running Directus locally on a Mac using Docker, you immediately lose a bunch of performance in file reads, which will directly affect the /assets endpoint (https://github.com/docker/for-mac/issues/77).

**Comment by Attacler** [comment] 2021-05-27 19:28
File type: PNG
File size (kb/mb): 10KB
File dimensions (width/height): 280x80
Are you using docker: yes
Are you on windows/Mac: linux docker
Does your computer have an SSD: yes
What kind of CPU does your computer have: its a server with a Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Where is your database hosted: same machine (docker compose setup like the docs describe)
Does your database have a large schema: No, around 200 records (including revision and activity)
What sort of permissions do you use for files: the public role has all read permissions.
Are you accessing it from an admin user: the image is loaded from the public role with all permissions (READ)

**Comment by Attacler** [comment] 2021-05-27 19:28
@rijkvanzanten

**Comment by rijkvanzanten** [comment] 2021-06-01 19:07
@Attacler Could you do me a favor, and try it without relying on either Docker, or the local storage adapter. I feel like the added latency of the file download is caused by the syncing of volumes between Linux and Docker, and isn't something we can tackle within Directus itself

**Comment by rgonzlz** [comment] 2021-06-01 21:16
I'm using GCS as storage but I think 300-400 ms is too much. What do you think?

![image](https://user-images.githubusercontent.com/7152452/120390333-ddf99c80-c32d-11eb-8eb7-cf9aa02ec031.png)
![image](https://user-images.githubusercontent.com/7152452/120391050-ca026a80-c32e-11eb-8cfb-548fd15eba0a.png)

**Comment by rijkvanzanten** [comment] 2021-06-02 13:24
@rgonzlz See my previous post, there's so many different things that can affect this that it's hard to conclusively say if this is expected or not. For example, just based on the geographical location of your GCS instance compared to your Directus instance compared to your computer, this number can be negatively affected anywhere from 0 to 5 seconds 🤷🏻

**Comment by rgonzlz** [comment] 2021-06-02 13:38
Ofc, Im not an expert in these things, but I understand your point and this its normal in my case.

**Comment by Attacler** [comment] 2021-06-02 17:23
> @Attacler Could you do me a favor, and try it without relying on either Docker, or the local storage adapter. I feel like the added latency of the file download is caused by the syncing of volumes between Linux and Docker, and isn't something we can tackle within Directus itself

I have checked and basicly the TTFB is around 10% faster than the actual content download. (86ms TTFB/92ms total download)
I will make an endpoint real quick (so we dont have the DB hassle) to see how quick that will be compaired to the /assets one.

**Comment by Attacler** [comment] 2021-06-02 17:28
After some testing, the calls take around 20ms+- difference (TTFB) from a endpoint with a .sendFile, however its faster than in docker.

Is there a good way to do this an other way to improve it?

**Comment by rijkvanzanten** [comment] 2021-06-04 03:42
I'll close this for now, as it's not clear whether or not the asset read performance is related to Directus, or external factors. Once there is a clearly reproducible example that's caused by Directus overhead beyond acceptable margins, we can reopen and keep investigating

**Closed by rijkvanzanten** 2021-06-04 03:42 UTC
Labels: Needs More Info
