### ISSUE TITLE
o2m creates relationship, instead of updating existing one

### ISSUE THREAD

**Issue by herrwitzi** [directus/directus#4245] opened 2021-02-23 10:32 UTC
1) The issue and what you expected to happen
    * the grahphql endpoint doesnt type the relation correctly
    * if i try to fetch the data i get the following error:
`{
  "errors": [
    {
      "message": "String cannot represent value: [{ discover_screen_test: 1, id: 80 }]",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "items",
        "discover_screen",
        "test"
      ]
    }
  ],
  "data": {
    "items": {
      "discover_screen": {
        "test": null
      }
    }
  }
}`

    * the wired thing is it worked before and now it doesnt work at all anymore
    * o2m relations generated before are still working
    * and it only happens in one project, in another project it still works fine

2) Exact steps to reproduce this issue
    * create two data models
    * add many to one relation on one model
    * add one to many relation on the other model
    * try to fetch graqhql

3) Your environment:
    What version of Directus you are using: v9.0.0-rc.42 but had the same issue with rc.28
    Which DBMS are you using: mariadb
    Which deployment are you using: npx
    What browser are you using: Chrome 88

**Comment by rijkvanzanten** [comment] 2021-02-23 16:03
It sounds like either a permissions issue for your current user, or a corruption in directus_relations

> the wired thing is it worked before and now it doesnt work at all anymore

Did anything change when it stopped working?

> and it only happens in one project, in another project it still works fine

Could you confirm if there's any differences in `directus_relations`?

---

I'm not able to reproduce this on my end with a new o2m setup, so I'll close this for now. If possible, could you share a database dump with a minimal reproduction where this is happening?

**Comment by herrwitzi** [comment] 2021-02-24 08:30
It shouldn't be a permission issue, because i try to access the data with my admin access_token.

> Did anything change when it stopped working?

I created a few relations that worked, and than i created more relations and all of a sudden they stopped working, it was all in one session.

> Could you confirm if there's any differences in directus_relations?

i couldnt discover anything that looks different, but i attached the csv for both, maybe you can detect a corruption
[directus_relations.zip](https://github.com/directus/directus/files/6034468/directus_relations.zip)

**Comment by rijkvanzanten** [comment] 2021-02-25 15:30
@herrwitzi 

These are suspicious, yeah:

<img width="805" alt="CleanShot 2021-02-25 at 10 27 01@2x" src="https://user-images.githubusercontent.com/9141017/109175668-07fe5a00-7754-11eb-81cb-0057d090d86c.png">

Note how there's two different relationships describing the same field. At some point during the field setup, it must've accidentally created a new relational row instead of updating the existing one 🤔

Do you happen to remember the exact order in which you setup this `image_text_card` to `discover_screen` relationship..? 😬

**Comment by mstingl** [comment] 2021-02-26 09:34
We resolved the problem by deleting the first instance of the duplicate entries using the following query
```sql
DELETE FROM directus_relations WHERE id IN (
    SELECT min(id) from directus_relations GROUP BY many_collection, many_field, many_primary, one_collection HAVING COUNT(*) > 1
)
```

I suggest adding a combined unique constraint on those fields so this kind of data corruption cannot happen anymore.
At least the operation would then fail when it accidently creates new records instead of updating the existing.

(I would create a PR for that change, but I'm not familiar with the code of directus 😅)

**Comment by herrwitzi** [comment] 2021-02-26 09:39
@rijkvanzanten 

but that is the case for all relations i generated, even those that work just fine (everything above line 99 (id: 105) works correctly)
And in the project without the bug it has the same behaviour. 

> Do you happen to remember the exact order in which you setup this image_text_card to discover_screen relationship..? 

yes, i first created a m2o on the `image_text_card` and then created the o2m manually on the `discover_screen`

so "manually" sounds like the keyword here, because as i tested now if i check the checkbox "add field to related collection" it only creates one entry as can be seen in the new database dump [here](https://github.com/directus/directus/files/6048689/directus_relations_2.zip)

as my coworker above suggested we fixed it for now by deleting the dublicated relations

**Comment by rijkvanzanten** [comment] 2021-02-26 15:11
> yes, i first created a m2o on the image_text_card and then created the o2m manually on the discover_screen
> 
> so "manually" sounds like the keyword here, because as i tested now if i check the checkbox "add field to related collection" it only creates one entry as can be seen in the new database dump here

Yeah I believe this is key. There is some specific order of operations in settings that fails to recognize the existing relationship 🙂 

Sounds like creating the m2o first and then retroactively applying the o2m as a "new field" causes this issue 👍🏻

**Closed** 2021-05-19 16:29 UTC
Labels: App, Bug
