### ISSUE TITLE
Validation NOT working for nested items

### ISSUE THREAD

**Issue by andriusign** [directus/directus#4415] opened 2021-03-07 12:03 UTC
Project details
Directus Version: 9.0.0-rc.44 (Docker)
Environment: production
OS: Linux 4.15.0-29-generic
Node: 14.16.0

**Model setup** (ignore export class since this has been copied from Angular). This should be enough to give a context where the problem is happening.:

export class User {
  id: string;
  email: string;
  password: string;
  first_name?: string;
  last_name?: string;
  avatar?: string;
  location?: string;
  title?: string;
  description?: string;
  role: string;
  last_access?: string;
  username?: string;
  language?: string;
  background?: string;
  authors?: Author[];
}

export class Author {
  name: number;
  image: string;
  donate: string;
  content: string;
  link_social: string;
  order: number;
  id: number;
  user_id: string;
}

export class Article {
  id: number;
  title: string;
  content: string;
  tags: string[];
  video: string;
  video_url: string;
  download_url: string;
  image: string;
  author_id: Author;
  date_created: string;
  date_updated: string;
  date_published: string;
  comments: Comment[];
  votes?: Vote[];
  status: string;
}

export class Comment {
  id: number;
  content: string;
  article_id: number;
  ip?: string;
  user_created: User;
  date_created?: string;
  parent_id?: number;
  replies?: Comment[];
  votes?: Vote[];
}

export class Vote {
  id: number;
  value: number;
  user_created: string;
  article_id: number;
  comment_id: number;
}

Comments have three levels. Article has comment, comment has reply, reply has reply. 3 levels max.

I need some back-end validation to delete comments and votes, but this is not working. Validation is failing with 403 forbidden error.

Delete Votes valdiation:

```
{
    "_or": [
        {
            "article_id": {
                "author_id": {
                    "user_id": {
                        "id": {
                            "_eq": "$CURRENT_USER"
                        }
                    }
                }
            }
        },
        {
            "comment_id": {
                "user_created": {
                    "_eq": "$CURRENT_USER"
                }
            }
        },
        {
            "comment_id": {
                "parent_id": {
                    "user_created": {
                        "_eq": "$CURRENT_USER"
                    }
                }
            }
        },
        {
            "comment_id": {
                "parent_id": {
                    "parent_id": {
                        "user_created": {
                            "_eq": "$CURRENT_USER"
                        }
                    }
                }
            }
        }
    ]
}

```
Delete Comments validation:

```
{
    "_or": [
        {
            "article_id": {
                "author_id": {
                    "user_id": {
                        "id": {
                            "_eq": "$CURRENT_USER"
                        }
                    }
                }
            }
        },
        {
            "user_created": {
                "_eq": "$CURRENT_USER"
            }
        },
        {
            "parent_id": {
                "user_created": {
                    "_eq": "$CURRENT_USER"
                }
            }
        },
        {
            "parent_id": {
                "parent_id": {
                    "user_created": {
                        "_eq": "$CURRENT_USER"
                    }
                }
            }
        }
    ]
}
```

Can someone please help? Or is it not possible to achieve this with Directus at all?

**Comment by rijkvanzanten** [comment] 2021-03-07 16:39
Duplicate of Duplicate of https://github.com/directus/directus/issues/4373

**Closed by rijkvanzanten** 2021-03-07 16:39 UTC
