### ISSUE TITLE
Many-to-many count fails

### ISSUE THREAD

**Issue by seanmars** [directus/directus#3433] opened 2020-12-16 15:37 UTC
On many-to-many to collections when select the on A collection, then unselect on B collection.
The A collection on display still showing 'one item with empty content'.

**Comment by rijkvanzanten** [comment] 2021-01-27 15:53
Ref https://github.com/directus/directus/issues/3719

**Comment by Nitwel** [comment] 2021-02-24 17:16
Isn't this a duplicate of #2942 then?
Please reopen this when I'm wrong!

**Closed by Nitwel** 2021-02-24 17:16 UTC
Labels: App, Bug
