### ISSUE TITLE
Can't access Assets from Admin app or assets endpoint

### ISSUE THREAD

**Issue by Lucas-Gruber** [directus/directus#17917] opened 2023-03-24 11:39 UTC
### Describe the Bug

I can't access my old Assets via the Admin App or with the Assets Endpoint.

But all Files are listed in the Admin App but i think it can't access the local Files. But when i view into the Docker all Files are in the "uploads" folder.

When i upload new Files it works perfectly but all my 3k+ old Files not working.

File List example:
![image](https://user-images.githubusercontent.com/72545889/227511279-b0dc6a7d-d0c7-4d84-9ab3-3f917aa2bdb0.png)

File Detail View:
![image](https://user-images.githubusercontent.com/72545889/227511324-23f65615-afed-4ab3-ab0c-24969a58f5a6.png)

Asset Endpoint:
![image](https://user-images.githubusercontent.com/72545889/227511378-da31fefd-03de-44c3-bc44-c4f258d18c8b.png)

ps: I think it happens with the newest update but i'm not 100% sure. But a few days ago it works perfectly and i haven't done anything in the App except the update.

### To Reproduce

Try to access local files.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-03-24 13:53
Duplicate of #17907

**Closed by rijkvanzanten** 2023-03-24 13:53 UTC
