### ISSUE TITLE
Parent input field should not show in drawer when adding item in o2m-list

### ISSUE THREAD

**Issue by tenebrius** [directus/directus#15390] opened 2022-09-04 04:26 UTC
### Describe the Bug

When adding a new item in a o2m list, the field list in drawer includes the parent. The field is empty. The dropdown cannot is opened but the 'add new' + button can be clicked. The creation of the item is successful with no errors. Optimally the field itself should not be shown as the child item will automatically be assigned to the parent anyway

![Screenshot 2022-09-04 121523](https://user-images.githubusercontent.com/3369571/188297373-005654b5-b73d-4e80-a7d4-13fa69d6db98.png)

### To Reproduce

Create a 'Book' collection
Create a related 'Chapter' collection as many-to-one relations
Create a new book
Within the book creation page, add a new chapter in the o2m list
In the drawer,  the 'Book' field in shown

### What version of Directus are you using?

9.17

### What version of Node.js are you using?

18

### What database are you using?

postgres

### What browser are you using?

chrome

### How are you deploying Directus?

locally

**Comment by licitdev** [comment] 2022-09-04 07:49
The following block sets the circular relational field as `readonly`.
Should it be set as `hidden`?

https://github.com/directus/directus/blob/8f7d2f8c5d5734c8bd05aaf87e81f97a73272e91/app/src/views/private/components/drawer-item.vue#L164-L170

**Comment by Nitwel** [comment] 2022-09-04 09:43
I would prefer to look into fixing the disabled prop so that the field looses all interactivity.

**Comment by licitdev** [comment] 2022-09-04 09:47
>  the field looses all interactivity

@Nitwel the field is currently "disabled" using `readonly` and has no interactivity. 
But it is visible.

**Comment by Nitwel** [comment] 2022-09-04 09:51
> The dropdown cannot is opened but the 'add new' + button can be clicked. 

This is a bug, that the field is read only is on purpose. This would have to be moved into a discussion to discuss if we should hide or disable it.

**Comment by azrikahar** [comment] 2022-09-04 09:55
I believe this shares the same root cause as #15053 (and the linked PR may or may not be the further point for discussion), closing this as duplicate 👍

**Closed by azrikahar** 2022-09-04 09:55 UTC
Labels: App, Improvement

**Comment by licitdev** [comment] 2022-09-04 10:13
>  This would have to be moved into a discussion to discuss if we should hide or disable it.

Sure. Thank you!

IIRC, the parent field wasn't visible before. I suppose the behavior has been changed to fix certain issues. 👍

**Comment by Nitwel** [comment] 2022-09-04 10:15
This was introduced by this PR: #14834
