### ISSUE TITLE
Notification count update in real time

### ISSUE THREAD

**Issue by UPSxACE** [directus/directus#23752] opened 2024-09-27 11:37 UTC
### Describe the Improvement

Notifications are a great feature, but in my opinion they are extremely unreliable if the notification count doesn't refresh soon after receiving them.

It's really weird to expect the user to refresh the page to receive a notification. Directus already got an auto-refresh feature that can be enabled for data models pages, so i think it wouldnt be that hard to use similar logic in the notification bell in the sidebar. Having to wait 1/2/5 minutes until it is refreshed is okay! Having to wait until the user decides to refresh the page is not!

It's honestly one of those very small yet really impactful things that I wish Directus would improve on

**Comment by br41nslug** [comment] 2024-09-27 13:52
Closing this as duplicate of the pre-existing "Real-Time Notification Updates" Feature Request  https://github.com/directus/directus/discussions/21302

**Closed by br41nslug** 2024-09-27 13:52 UTC
