### ISSUE TITLE
Display Template for M2O relationship can't be customized

### ISSUE THREAD

**Issue by David-Lor** [directus/directus#5687] opened 2021-05-14 21:21 UTC
When editing the Display Template on a M2O Relationship, I was expecting that arbitrary characters could be placed in the Display Template, to format multiple fields:

![expected](https://user-images.githubusercontent.com/17401854/118332854-02224480-b50b-11eb-9c03-37858552e4f7.png)

However, after saving the field, the Display Template rolls back to this:

![actual](https://user-images.githubusercontent.com/17401854/118332788-f2a2fb80-b50a-11eb-959f-6327410c6326.png)

The effect on the frontend is that both fields are shown together, with nothing splitting them, making it difficult and ugly to read.

Directus version: directus:v9.0.0-rc.64 (docker)

**Comment by rijkvanzanten** [comment] 2021-05-14 21:26
Duplicate of https://github.com/directus/directus/issues/5416

**Closed by rijkvanzanten** 2021-05-14 21:26 UTC
