### ISSUE TITLE
Auto refresh Kanban layout not working

### ISSUE THREAD

**Issue by Danhhoa** [directus/directus#22276] opened 2024-04-22 07:59 UTC
### Describe the Bug

Auto refresh in Kanban layout not working

- I'm using version 10.10.5

### To Reproduce

- Use Kanban layout to manage collection
- Turn on auto refresh after 10 seconds

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-04-22 08:59
Thanks for opening this issue! However this is a duplicate of an existing issue #22274, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #22274 for future updates.

**Closed by hanneskuettner** 2024-04-22 08:59 UTC
