### ISSUE TITLE
Type fields tags and multiselect displayed not correct

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1828] opened 2017-09-19 13:55 UTC
## Version Info
  - Directus version and branch: devel
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: ubuntu16.04

## Actual Behavior
1)when many tags fields, in display items, dublicated first tags column
2)field multiselect display value not text.

![default](https://user-images.githubusercontent.com/4669992/30595260-5fda2de0-9d59-11e7-9fe3-3439b6574be4.png)

![default](https://user-images.githubusercontent.com/4669992/30595803-eb49171e-9d5a-11e7-83c1-ca17623bcb8f.png)

## Schema Dump, Logs, or Screenshots
[test.zip](https://github.com/directus/directus/files/1314424/test.zip)

**Comment by rijkvanzanten** [comment] 2017-09-19 16:38
Hi @dsivokhin! Good catch. Just for the record, do the values get saved correctly? Or does it only save the values of the tags no.1 multiple times?

**Comment by dsivokhin** [comment] 2017-09-19 17:06
Hi @rijkvanzanten, `tags` save correctly, but display not correctly. 
Type `multiselect ` values save correctly, but in settings checked `Display text`  and `Options` : 
{
	"value1": "Option One1",
	"value2": "Option One1",
	"value3": "Option Three3"
} 
Expect to see in table display `Option One1`,`Option One1`,`Option Three3`

**Comment by rijkvanzanten** [comment] 2017-09-19 19:25
Hey @dsivokhin! Both these issues should've been fixed by my last two commits on the develop branch. Could you please confirm this on your end?

**Comment by dsivokhin** [comment] 2017-09-20 07:31
Thank you @rijkvanzanten, now when create new item or when try display all items, where one `tags` field is empty (in DB value `Null`)
e.g.
![default](https://user-images.githubusercontent.com/4669992/30631715-de291384-9ded-11e7-86cf-d1f6509cdbb9.png)

I see this error 
![default](https://user-images.githubusercontent.com/4669992/30631664-a9ce9d84-9ded-11e7-9dd6-b1de32b44e71.png)


And when DB value='', I see 
![default](https://user-images.githubusercontent.com/4669992/30631912-c644500c-9dee-11e7-9aaa-85b29eaf4829.png)

**Comment by dsivokhin** [comment] 2017-09-20 08:41
And I catch another issue with `single_file` component.

![default](https://user-images.githubusercontent.com/4669992/30632850-348aec58-9df2-11e7-8643-a04211f8e361.png)
![default](https://user-images.githubusercontent.com/4669992/30632888-525552c8-9df2-11e7-8f69-0ae35f09490a.png)

 I need create new issue ?

**Comment by rijkvanzanten** [comment] 2017-09-21 02:25
@dsivokhin I think opening a new issue would be best so we won't get confused with the already resolved other problem in this one.

Please do include as much specific information as you can, as I'm currently not able to reproduce this error..

**Closed by rijkvanzanten** 2017-09-21 02:25 UTC
Labels: 4. Minor, Bug, Interface
