### ISSUE TITLE
problem with uploading images for setup using docker-compose

### ISSUE THREAD

**Issue by jbFeDev** [directus/directus#7098] opened 2021-07-30 15:47 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I've installed Directus 9 (latest) using the official docker-compose.yaml (https://docs.directus.io/guides/installation/docker/#docker-compose)

When I try to upload, I get following error in the frontend:
<img width="539" alt="Screenshot 2021-07-30 at 17 39 42" src="https://user-images.githubusercontent.com/57177305/127677371-2b0c7aac-8863-4988-bb45-8def71a232cf.png">

... with following error in the backend:
![Screenshot 2021-07-30 at 17 41 52](https://user-images.githubusercontent.com/57177305/127677673-4b22d741-9ece-43ea-817b-33a0bb6936f4.png)

It probably has something to do with permissions, but can anybody tell me how to fix this in docker-compose?

### To Reproduce

1. Install Directus using Docker compose: https://docs.directus.io/guides/installation/docker/#docker-compose
2. In Directus, try to change a user image (avatar) by uploading a file from your local device

### What version of Directus are you using?

latest

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres:12

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-07-30 15:49
Is this a fresh installation, or a totally new pull on the latest version?

**Comment by rijkvanzanten** [comment] 2021-07-30 15:50
Duplicate of https://github.com/directus/directus/issues/6946

**Closed by rijkvanzanten** 2021-07-30 15:50 UTC
Labels: Bug (Potential)

**Comment by jbFeDev** [comment] 2021-07-30 15:51
> Is this a fresh installation, or a totally new pull on the latest version?

A pull from 2 days ago

**Comment by rijkvanzanten** [comment] 2021-07-30 15:52
Did you already have an older directus installation in that same folder?

**Comment by jbFeDev** [comment] 2021-07-30 15:54
> Did you already have an older directus installation in that same folder?

No, fresh installation. The only thing I did, was removing the /data folder often when trying to sync databases.

**Comment by rijkvanzanten** [comment] 2021-07-30 15:55
> The only thing I did, was removing the /data folder often when trying to sync databases.

Ah that's the most likely culprit then. The docker image creates the `data` folder using the `node` user instead of root for security reasons. This manual change might've caused the ownership to change?

@t7tran I get the security benefits, but that particular change is causing _a lot_ of issues and confusion. I might have to revert that particular change, unless we can come up with a solution that works a little better (cc @paescuj)

**Comment by jbFeDev** [comment] 2021-07-30 15:57
> > The only thing I did, was removing the /data folder often when trying to sync databases.
> 
> Ah that's the most likely culprit then. The docker image creates the `data` folder using the `node` user instead of root for security reasons. This manual change might've caused the ownership to change?
> 
> @t7tran I get the security benefits, but that particular change is causing _a lot_ of issues and confusion. I might have to revert that particular change, unless we can come up with a solution that works a little better (cc @paescuj)

Maybe I can remove all containers (but leave the data folder), and do a fresh install without losing the database contents?

**Comment by rijkvanzanten** [comment] 2021-07-30 15:58
You should be able to reset the folder ownership by following https://github.com/directus/directus/discussions/6480#discussioncomment-917708 🤔 (I'm no docker user myself, so i'm not too familiar with all this)

**Comment by arladmin** [comment] 2021-07-30 16:00
> You should be able to reset the folder ownership by following [#6480 (comment)](https://github.com/directus/directus/discussions/6480#discussioncomment-917708) 🤔 (I'm no docker user myself, so i'm not too familiar with all this)

I tried this a few hours ago. Wouldn't recommend it. My directus instance went kapoot and couldn't access anything (database, cache) anymore. The container simply kept crashing as soon as started.

**Comment by jbFeDev** [comment] 2021-07-30 16:10
> You should be able to reset the folder ownership by following [#6480 (comment)](https://github.com/directus/directus/discussions/6480#discussioncomment-917708) 🤔 (I'm no docker user myself, so i'm not too familiar with all this)

That solution does not seem to work to me. If I leave the data-folder, and just do a fresh install using docker-compose, I still should be able to keep my data?

**Comment by t7tran** [comment] 2021-07-31 00:19
@rijkvanzanten man, you're such a nice person. I mean it.

Please do not revert the change after some discussion. The solution should not be security compromise. Seriously, I don't see any issue with the current approach following best practices. Worst case scenarios, we provide a sample `docker-compose.yaml` with `user: root` instruction so those people can take their own risk, not the whole community. Let me know if this is needed, I can provide one.

Now, let try to understand why some has run into this "permission" related category. The OP mentioned he reset `/data` folder for every fresh installation. Could you please post the sample of your `docker-compose.yaml` file? I should be able to provide a solution.

PS: why is this closed now?

**Comment by arladmin** [comment] 2021-07-31 00:23
> @rijkvanzanten man, you're such a nice person. I mean it.
> 
> Please do not revert the change after some discussion. The solution should not be security compromise. Seriously, I don't see any issue with the current approach following best practices. Worst case scenarios, we provide a sample `docker-compose.yaml` with `user: root` instruction so those people can take their own risk, not the whole community. Let me know if this is needed, I can provide one.
> 
> Now, let try to understand why some has run into this "permission" related category. The OP mentioned he reset `/data` folder for every fresh installation. Could you please post the sample of your `docker-compose.yaml` file? I should be able to provide a solution.
> 
> PS: why is this closed now?

Hi @t7tran , you could check out my example:
https://github.com/directus/directus/issues/6946#issuecomment-889976173

**Comment by rijkvanzanten** [comment] 2021-07-31 00:45
> @rijkvanzanten man, you're such a nice person. I mean it.

Thank you ❤️

> Please do not revert the change after some discussion. The solution should not be security compromise. Seriously, I don't see any issue with the current approach following best practices. Worst case scenarios, we provide a sample docker-compose.yaml with user: root instruction so those people can take their own risk, not the whole community. Let me know if this is needed, I can provide one.

I don't want to! It definitely sounds like this is the way to go. Just wondering if there's anything else we can do to alleviate some of these pain points 🤔 Just nuking the whole thing by using root everywhere isn't really a solution of course. I'll at least put your comment in that linked discussion thread on the main docs website, but I'm wondering if there's anything we can do in the dockerfile to make check the permissions of that folder on startup and fix it on the fly, or maybe show an error and exit the process 🤔🤔 

I'd love to hear your thoughts!

**Comment by rijkvanzanten** [comment] 2021-07-31 00:46
> PS: why is this closed now?

Cause it's technically a duplicate of the other times this same error popped up

**Comment by t7tran** [comment] 2021-07-31 01:07
That's exactly what I thought it would be. It's probably related to how you `reset` that `/data` folder. If by `rm -rf /data/*` then it definitely causes permission issues. This is how Docker operates, you would get the same issue with all containers running as non-root, not just Directus.

Try to reset using the steps below (assuming the path is absolute under root, i.e. `/data`; and you don't care about data underneath that path; and you use `bash`).

```
rm -rf /data/{extensions,uploads,database}/*
sudo chown -R 1000:1000 /data/{extensions,uploads,database}
```

**Comment by t7tran** [comment] 2021-07-31 01:23
Yes, @rijkvanzanten. I was going to suggest that check on entrypoint but it slipped thru. Let's put our comments in #7111.

**Comment by arladmin** [comment] 2021-07-31 01:29
> @arladmin That's exactly what I thought it would be. It's probably related to how you `reset` that `/data` folder. If by `rm -rf /data/*` then it definitely causes permission issues. This is how Docker operates, you would get the same issue with all containers running as non-root, not just Directus.
> 
> Try to reset using the steps below (assuming the path is absolute under root, i.e. `/data`; and you don't care about data underneath that path; and you use `bash`).
> 
> ```
> rm -rf /data/{extensions,uploads,database}/*
> sudo chown -R 1000:1000 /data/{extensions,uploads,database}
> ```

Just tried entering the directus container's ```bash``` to execute this, ```docker exec -it directus bash```.

But see an error:
```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown
```

**Comment by t7tran** [comment] 2021-07-31 01:48
Of course, there's no `bash` in the container. The commands need to be executed on your machine as the volumes' paths are local.

**Comment by arladmin** [comment] 2021-07-31 01:59
@t7tran Thanks, it finally works now!

Could you also kindly tell me what exactly is it that we've done here? (Have only limited understanding of docker)

- Also, what would be a long-term solution for this, as resetting the ```/data``` is not really preferable for any running instance, or even new (migrated) instance ? 
- And could i just re-upload the backed up version of ```/data/{extensions,uploads,database}``` once the ownership changes have been made?

**Comment by jbFeDev** [comment] 2021-07-31 10:06
@arladmin exactly, if there is a temporary fix by removing the `/data`, and resetting the permissions, we have to make sure we can put the original data back. Otherwise we have to manually configure the collections, and put the data back. 

If there is a solid solution on backing up the SQL and putting everything back without problems due to constrains violations (relations, cascade,..), I would love to hear it!
