### ISSUE TITLE
Insight timeseries panel timezone differs

### ISSUE THREAD

**Issue by domdus** [directus/directus#15443] opened 2022-09-07 09:22 UTC
### Describe the Bug

Timeseries panels seem to add 2 hours to the actual `date_created` of my data points. The items date_created time does match the timezone correctly.
I'm trying to display visits of the past 30 minutes, here is the data with correct date time:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/67951828/188836992-92b049a3-32c2-45fb-ab2c-2db89f332883.png">

Last data was written at 10:48 (:17 sec).
However in timeseries panel 2 hours are added to the values and displayed as 12:48
<img width="575" alt="image" src="https://user-images.githubusercontent.com/67951828/188838415-238c6a9a-05f5-4b67-98be-3b813b58dabe.png">

Also on any of my time series panels with group precision set to `day`, the day ends at 02:00 AM, not at midnight?:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/67951828/188841761-a564335d-9e5d-4761-81ef-100536e3601b.png">

Tried to play with `TZ=UTC npx directus start`, but no effect.

### To Reproduce

Create time series panel with config:
<img width="522" alt="image" src="https://user-images.githubusercontent.com/67951828/188838895-ad5d6579-98a2-4399-9cdb-b2f28e6c1862.png">
<img width="524" alt="image" src="https://user-images.githubusercontent.com/67951828/188839006-4e497eaf-e4f6-42de-b5aa-6a58c523c592.png">

### What version of Directus are you using?

9.17.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by licitdev** [comment] 2022-09-14 09:48
@domdus Kindly provide a screenshot of `date_created`'s schema. Here's an example for your reference.
![image](https://user-images.githubusercontent.com/26413686/190120454-315861d2-84f3-455e-aa7a-2f6cb01283be.png)

**Comment by domdus** [comment] 2022-09-14 21:25
Sure I can do looks the very same here:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/67951828/190261652-b6f1c6c6-3164-41f3-8f4c-d3cb316f6eaa.png">

As described above the data that is written does have correct `date_created` values.

Some more thougths and info:

**My timezone is:** Europe/Berlin
Right now it is: Wed Sep 14 2022 23:21:08

**Server time:** `$ date`
Wed 14 Sep 2022 11:21:36 PM CEST

**Node  env time:** `$ node` > Date() 
Welcome to Node.js v16.14.0.
Type ".help" for more information.
> Date()
'Wed Sep 14 2022 23:22:08 GMT+0200 (Central European Summer Time)'

https://webbrowsertools.com/timezone/
<img width="656" alt="image" src="https://user-images.githubusercontent.com/67951828/190265466-b2e6a10f-adee-46ff-a251-d2514f6eef33.png">

**Comment by licitdev** [comment] 2022-09-18 23:36
Yes, I agree that it's likely to be due to the timezone, due to the 2h difference, but I'm still unable to reproduce the issue. 🤔 
A similar issue was fixed in https://github.com/directus/directus/pull/13701.

What's the timezone of your PG instance? 
It can be retrieved by running `SELECT current_setting('TIMEZONE');`.

Additionally, it'll be really useful to have a recording or screenshots from the dev tools showing the details of requests and responses with the server.

Thank you for your report and your assistance in debugging this issue. 🙏

**Comment by domdus** [comment] 2022-09-19 15:49
Hi @licitdev,
according to `SELECT current_setting('TIMEZONE');` of PG is "Europe/Berlin".

Will try to capture some screens where possible (sensitive customer data here and there).
Maybe I need to sort out some confusion I introduced in the first shot. :)
There is the difference in the actual DB data / API response (zulu time) and "presentation value".

**Reduced example with a single data set (in `visits` collection):**

**Collection view:**
1. We have a data set written, with correct `date_created` (2022 2:26:20 PM) for "presentation" via app. (considers GMT+0200)
<img width="347" alt="image" src="https://user-images.githubusercontent.com/67951828/191041509-1f69dbca-3151-4422-abfb-f4171266dcdf.png">

2. The API at this point returns zulu time `{date_created: "2022-09-19T12:26:20.818Z", ...}` from DB
<img width="260" alt="image" src="https://user-images.githubusercontent.com/67951828/191042766-7596b2d4-021d-4f4a-adfc-e6dfbe96f1db.png">

-------------------------------------

**Insight view:**
I created a new dashboard and added 1x metric, 1x list, 1x timeseries. Now it gets interresting:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/67951828/191052299-db7ec454-9c20-48de-b88b-b5caabb23ded.png">

- metric shows the raw data (zulu time), not date GMT+0200
- list displays the sort of "presetation date" (GMT+0200), which is the corrent display that `date_created` fields have throughout the app
- timeseries does weird things now. It shows a date where GMT+0200 is added twice? (considering zulu time from DB)

Graphql request (filters added to only pick single data set):
`query { query_29182706: visits (limit: 1, sort: "-date_created", filter: {}) { id date_created } query_5ebcfdcd: visits (limit: 1, sort: "-date_created") { date_created } query_3af8a8bc: visits_aggregated (limit: -1, filter: {_and: [{_and: [{date_created: {_gt: "$NOW(-3 hours)"}}]}, {date_created: {_gte: "$NOW(-4 hours)"}}, {date_created: {_lte: "$NOW"}}]}, groupBy: ["year(date_created)", "month(date_created)", "day(date_created)", "hour(date_created)", "minute(date_created)"]) { count { user_created } group } }`

Response:
`{data: {,…}}
data
: 
{,…}
query_3af8a8bc
: 
[{count: {user_created: 1},…}]
0
: 
{count: {user_created: 1},…}
count
: 
{user_created: 1}
group
: 
{date_created_year: "2022", date_created_month: "9", date_created_day: "19", date_created_hour: "14",…}
date_created_day
: 
"19"
date_created_hour
: 
"14"
date_created_minute
: 
"26"
date_created_month
: 
"9"
date_created_year
: 
"2022"
query_5ebcfdcd
: 
[{date_created: "2022-09-19T12:26:20.818Z"}]
0
: 
{date_created: "2022-09-19T12:26:20.818Z"}
date_created
: 
"2022-09-19T12:26:20.818Z"
query_29182706
: 
[{id: "2c61a266-97ef-499b-8a2c-db781026f765", date_created: "2022-09-19T12:26:20.818Z"}]
0
: 
{id: "2c61a266-97ef-499b-8a2c-db781026f765", date_created: "2022-09-19T12:26:20.818Z"}
date_created
: 
"2022-09-19T12:26:20.818Z"
id
: 
"2c61a266-97ef-499b-8a2c-db781026f765"`

-------------------------------------------------

Screenshots - panel config:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/67951828/191058740-b8ae319b-840e-41c2-96d2-8362656c94d1.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/67951828/191058813-788f685c-6e47-42a8-811f-d36190ca4ac4.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/67951828/191058881-1d7286cb-bf76-4a21-8455-9b9a83854f7a.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/67951828/191059075-053fad84-8dca-4893-b434-9fb5a3fbddc4.png">

**Closed** 2022-11-14 14:38 UTC
Labels: API, Bug
