### ISSUE TITLE
Directus does not show the text while adding a relationship

### ISSUE THREAD

**Issue by shankiflang** [directus/directus#13467] opened 2022-05-21 10:47 UTC
### Describe the Bug

I have a problem with my relationship between several tables. When I create a new entry, the panel doesn't display anything and when I click on the Save button and come back to it, it displays them well.

I put the right data in the interface and in the display so I don't understand. It looks like it doesn't "cache" the new entry and therefore can't display the relationships until it is created. Which makes sense. But it does display the "value" so it's still caching something.

Do you know if I have misconfigured something or if Directus is the problem?

Thanks for your help!

### To Reproduce

Create a multiple m2o relationship and create an entry

### Errors Shown

Yo can see the gif of my problem here : https://s8.gifyu.com/images/Desktop-2022.05.21---11.56.29.01-1-1.gif

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

16

### What database are you using?

Postgre13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by ChrisGV04** [comment] 2022-05-22 03:54
Yeah, I'm having the same problem. I'm new to Directus and I thought it was something I didn't set up correctly but I haven't been able to fix it.

**Comment by azrikahar** [comment] 2022-05-23 06:50
This should be a duplicate of #12901 #10647. We are currently tracking it in #10647 👍

**Closed by azrikahar** 2022-05-23 06:50 UTC
Labels: Bug (Potential)
