### ISSUE TITLE
Duplicated result when filtering by nested O2M collections

### ISSUE THREAD

**Issue by j-kia** [directus/directus#16225] opened 2022-10-29 09:09 UTC
### Describe the Bug

I'm doing a search for items in one of my collections based on one of its M2O fields by combined filters with `_or`, but the returned items will be duplicated as shown in the image below:
![image](https://user-images.githubusercontent.com/92907785/198816085-d0a865e0-2e69-4382-993b-53fa256f7aba.png)

#### Collections:
`update`
`business`
`tag`
`category`

#### Relations:
`update` has a M2O relation with `business` ( field name `business_id` )
`business` has a M2O relation with `category` ( field name `category` )
`business` has a O2M relation with `tag` ( field name `tags` )

#### Item in update collection:
```
{
    "id": "3ec4206f-e48f-48f6-9c34-8228e9942006",
    "title": "Highlight 1",
    "business_id": {
        "id": "0cc104b8-236b-426f-a6f1-a2e3c1c77681",
        "name": "Business 1",
        "category": {
            "id": "5e034c5b-3c1d-4ba7-b8ce-948c280d3da3",
            "title": "Arts & Crafts"
        },
        "tags": [
            {
                "title": "art"
            },
            {
                "title": "tag 1"
            },
            {
                "title": "tag 2"
            }
        ]
    }
}
```

#### API to read items from update collection:
```
GET /items/update?filter={"_or":[{"business_id":{"tags":{"title":{"_contains":"art"}}}},{"business_id":{"name":{"_contains":"art"}}},{"business_id":{"category":{"title":{"_contains":"art"}}}}]}&fields=id,title
```

### Errors Shown

Using API:
```
{
    "data": [
        {
            "id": "3ec4206f-e48f-48f6-9c34-8228e9942006",
            "title": "Highlight 1"
        },
        {
            "id": "3ec4206f-e48f-48f6-9c34-8228e9942006",
            "title": "Highlight 1"
        },
        {
            "id": "3ec4206f-e48f-48f6-9c34-8228e9942006",
            "title": "Highlight 1"
        }
    ]
}
```
In app:
![image](https://user-images.githubusercontent.com/92907785/198818722-099772fb-b88b-4017-899c-07633be92fe5.png)

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.18.0

### What database are you using?

mysql

### What browser are you using?

Chrome, Postman

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-10-29 19:58
Duplicate of https://github.com/directus/directus/issues/13107

**Closed by rijkvanzanten** 2022-10-29 19:58 UTC
