### ISSUE TITLE
Getting "Error: XMLHttpRequest is not defined" when doing requests in Node

### ISSUE THREAD

**Issue by aldoprogra** [directus/directus#23669] opened 2024-09-15 10:18 UTC
### Describe the Bug

as described here I have a similar problem #8079. I am not using XMLHttpRequest, but when I receive the hook in my extension endpoint I upload a file to firestore. the error say 

/dist/index.js?t=1726395100952:18820
        this.xhr_ = new XMLHttpRequest();
                        ^

ReferenceError: XMLHttpRequest is not defined     
    at new XhrConnection (file:///C:/Users/Admin.AR-WUM0009/workspace/MrBackend/extensions/whatsapp-get-hooks/dist/index.js?t=1726395100952:18820:25)

If I look for this compiled file I find the problem is in the network layer 
/**
 * Network layer for browsers. We use this instead of goog.net.XhrIo because
 * goog.net.XhrIo is hyuuuuge and doesn't work in React Native on Android.
 */
class XhrConnection {
    constructor() {
        this.sent_ = false;
        this.xhr_ = new XMLHttpRequest();
        this.initXhr();
        this.errorCode_ = ErrorCode.NO_ERROR;
        this.sendPromise_ = new Promise(resolve => {
            this.xhr_.addEventListener('abort', () => {
                this.errorCode_ = ErrorCode.ABORT;
                resolve();
            });
            this.xhr_.addEventListener('error', () => {
                this.errorCode_ = ErrorCode.NETWORK_ERROR;
                resolve();
            });
            this.xhr_.addEventListener('load', () => {
                resolve();
The problem is that I am not in the browser but in directus backend?

### To Reproduce

  I do not know how to trigger the problem, but has to be related with the promises in my function:

export async function uploadFile({ file, messageId, roomId, currentUserId }) {
  let type = file.extension || file.type;
  if (type === 'svg' || type === 'pdf') {
      type = file.type;
  }

  try {
      // Start the upload task
      const uploadTask = storageService.uploadFileTask(currentUserId, messageId, file, type);

      // Wait for the upload to complete
      await new Promise((resolve, reject) => {
          uploadTask.on(
              'state_changed',
              null, // No progress callback needed
              (uploadError) => {
                  console.error('Upload failed:', uploadError);
                  reject(uploadError); // Reject the promise if upload fails
              },
              async () => {
                  // Upload completed successfully
                  try {
                      const url = await getFileDownloadUrl(uploadTask.snapshot.ref);

                      // Update Firestore with the new file URL
                      const message = await firestoreService.getMessage(roomId, messageId);
                      message.files.forEach((f) => {
                          if (f.url === file.localUrl) {
                              f.url = url;
                          }
                      });

                      await firestoreService.updateMessage(roomId, messageId, {
                          files: message.files,
                      });

                      resolve(true); // Resolve the promise if upload succeeds
                  } catch (error) {
                      console.error('Error getting file download URL:', error);
                      reject(error); // Reject the promise if getting the URL fails
                  }
              }
          );
      });

      return true; // Return true on success
  } catch (error) {
      console.error('Error uploading file:', error);
      return false; // Return false on error
  }
}

### Directus Version

v11.0.0

### Hosting Strategy

Self-Hosted (Custom)

### Database

postgres railway

**Comment by br41nslug** [comment] 2024-09-23 09:24
Directus itself does make use of `XMLHTTPRequests` because NodeJS indeed does not support this API 🤔 My assumption that this is done by the dependency used to "upload a file to firestore".

I recommend either:
1. making use of the NodeJS compatible version of firestore https://firebase.google.com/docs/firestore/quickstart#node.js
2. attempting to polyfill XHR requests for compatibility https://www.npmjs.com/package/xmlhttprequest

Closing this issue for now as i do not think this is caused by the Directus platform

**Closed by br41nslug** 2024-09-23 09:24 UTC
