### ISSUE TITLE
pagination does not work correctly if limit is less than 25.

### ISSUE THREAD

**Issue by wisteria-hill-technologies** [directus/directus#21177] opened 2024-01-24 10:39 UTC
### Describe the Bug

If I call api endpoints like below:
/items/quotations?sort=-quotation_status&fields=id&limit=10&page=1
/items/quotations?sort=-quotation_status&fields=id&limit=10&page=3
It will return duplicate items.

I think this is a bug.  Pagination seems to work normally if the mimimum limit is set to 25.  But, if I set the limit to less than that (e.g. 10), the pagination return some duplicates.

I have observed this bug for both v9 and v10.

### To Reproduce

Make some collection with data and call endpoints like below:
/items/your-collection?sort=-quotation_status&fields=id&limit=10&page=1
/items/your-collection?sort=-quotation_status&fields=id&limit=10&page=3

### Directus Version

v10 & v9

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2024-01-24 12:14
I am not able to reproduce this on 10.8.3, please elaborate on your setup and reproduction steps that are used to cause this.
![image](https://github.com/directus/directus/assets/9389634/5b22f722-64ce-4098-9619-3feef9e8f379)
![image](https://github.com/directus/directus/assets/9389634/e3ee75ea-4d91-493d-a71b-89042483159b)
![image](https://github.com/directus/directus/assets/9389634/73fd0290-c072-4aa6-a9e6-a40ebd13903a)

Closing this issue for now but happy to re-open when enough information becomes available to reproduce this 😄

**Closed by br41nslug** 2024-01-24 12:14 UTC
