### ISSUE TITLE
Failed to set 'Default Language' to 'Chinese'

### ISSUE THREAD

**Issue by yisheng** [directus/directus#16217] opened 2022-10-28 04:51 UTC
### Describe the Bug

On version 9.19.2, the app failed to save and reload after setting the `Default Language` to `Chinese` (`zh-CN`).

- English and other languages work fine on V9.19.2
- Chinese language works fine on V9.18.1

![15741666932030_ pic](https://user-images.githubusercontent.com/352986/198504972-f257b7d9-1d64-4224-a24b-bc78caf2159e.jpg)

### To Reproduce

1. Install a brand new Directus [manually](https://docs.directus.io/self-hosted/installation/manual.html) or [by CLI](https://docs.directus.io/self-hosted/installation/cli.html)
2. Login → Setting → Project settings
3. Change `Default Language` to `Chinese`

### Errors Shown

```
SyntaxError: 9 (at vue-i18n.df8d89e7.entry.js:9:510)
    at Ge (vue-i18n.df8d89e7.entry.js:9:510)
    at I (vue-i18n.df8d89e7.entry.js:10:1031)
    at ge (vue-i18n.df8d89e7.entry.js:10:5264)
    at Ee (vue-i18n.df8d89e7.entry.js:10:6751)
    at Object.Ie [as nextToken] (vue-i18n.df8d89e7.entry.js:10:7328)
    at p (vue-i18n.df8d89e7.entry.js:10:10265)
    at C (vue-i18n.df8d89e7.entry.js:10:11363)
    at Object.y [as parse] (vue-i18n.df8d89e7.entry.js:10:11525)
    at Bn (vue-i18n.df8d89e7.entry.js:11:465)
    at Ca (vue-i18n.df8d89e7.entry.js:19:6549)
```

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

MySQL 8.0.27

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by azrikahar** [comment] 2022-10-28 04:53
Thanks for opening this issue! However this is a duplicate of an existing issue #16151, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #16151 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2022-10-28 04:53 UTC
