### ISSUE TITLE
In app docs - Glossary toc links are broken

### ISSUE THREAD

**Issue by adminradio** [directus/directus#14940] opened 2022-08-08 10:15 UTC
### Describe the Bug

The links in the TOC at `${HOST}/admin/docs/getting-started/glossary` are linking to a wrong location.

For example, the topic **API** should link to `${HOST}/admin/docs/getting-started/glossary#api` bit currently it links to `${HOST}/admin/#api` - which is of course wrong.

That is for all elements in the toc of the glossary.

### To Reproduce

Just go to the glossary and hover over the toc elements, or even click them.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.16.0

### What database are you using?

Postgres 13 (Postgis)

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-08-08 10:35
Seems like this is the same as #12752. Although it was closed as resolved by #14234, the "wrong link" behavior is still present.

Tested and confirmed on 9.15.1 docker image (since this is not reproducible on dev environment).

**Comment by JonathanSchndr** [comment] 2022-08-18 18:04
I have looked at the problem. It is actually relatively simple. In DEV mode the `<base>` tag (HTML Head) has no href, so all `<a href="#xy">` are executed relative to the current URL and the router gets the current path + hash. In production mode the `<base>` tag href is changed to /admin/ in the Vite Config and so we have `<base href="/admin/">`. Subsequently, all relative domains are run on this base and I end up with /admin/#xy. Although in the router createWebHistory is defined with the path, this is not used if there is a `<base>` tag with href.

The following solutions exist:

1. it is checked, why the base tag in the vite is set in productive, or if possible this is removed.
2. a vanilla JavaScript EventListener for click on A, which returns false and only executes a scroll (`document.querySelectorAll('a[href^="#"]')`)
3. all A tags are replaced by a `<router-link>`

**Comment by rijkvanzanten** [comment] 2022-08-18 19:04
> it is checked, why the base tag in the vite is set in productive, or if possible this is removed.

We can't remove the `<base>` tag in production 👍🏻

**Comment by JonathanSchndr** [comment] 2022-08-18 19:18
> > it is checked, why the base tag in the vite is set in productive, or if possible this is removed.
> 
> 
> 
> We can't remove the `<base>` tag in production 👍🏻 

I think the cleanest solution would be solution 3. Maybe we can simply replace a Tag with Nuxt Link when loading Docs.

Where is Base in Production used?

**Comment by rijkvanzanten** [comment] 2022-08-18 19:20
> Maybe we can simply replace a Tag with Nuxt Link when loading Docs.

Nuxt isn't used for the app, but a vue-router link might work 🙂 

> Where is Base in Production used?

It allows sub-path deployments to function, by setting the base path to the configured public url 👍🏻

**Comment by JonathanSchndr** [comment] 2022-08-19 08:03
@rijkvanzanten I have now tried it locally once as DEV and as production. The changes are as follows:

Vite Config:
```
- base: process.env.NODE_ENV === 'production' ? '' : '/admin/'
+ base: '/admin/',
```

In DEV it takes '/admin/', then the DOCS work, because in index.html it doesn't change the href of base and so it remains empty. Whereas in Production it changes it to a '' and thus takes the Base href from `history: createWebHistory(getRootPath() + 'admin/'),` and changes it to /admin/.

For the "trick" I still changed the index.html. With an empty string in the href we block that override in Production. Why it always overwrites it in Production and not in DEV, I don't understand either - maybe a vite bug or a static file case.
```
- <base />
+ <base href="" />
```

To run Directus in the subfolder, it should actually be sufficient in the createWebHistory(getRootPath() + 'admin/') to include the parameter, since this is only taken if there is no base tag. So at least the docs from Vite.

If you like the approach and want to test it yourself, I can create a PR. If this approach is too "hacky" - I can gladly implement solution 2 as well.

**Comment by rijkvanzanten** [comment] 2022-08-19 14:41
@JonathanSchndr Did you confirm that production use with subfolder routing (like `example.com/my-installation/admin`) still works with that setup? 🤔

**Comment by JonathanSchndr** [comment] 2022-08-21 03:21
> @JonathanSchndr Did you confirm that production use with subfolder routing (like `example.com/my-installation/admin`) still works with that setup? 🤔

Hey Rijk, I have now tested very intensively with my own Docker containers (https://hub.docker.com/r/jonathanschndr/directus/tags). Basically, the fix also works and solves the problem of relative paths. Unfortunately, with a sub-directory installation, CSS and JS paths are also relative and the base tag is needed again. Theoretically you could add an ENV (SUBDIRECTORY_PATH) to the vite base: `base: process.env.'SUBDIRECTORY_PATH || '/admin/'` - but probably the easiest way is just not to use relative or auto replace <a href=""> anymore :D Too bad!

**Comment by JonathanSchndr** [comment] 2022-08-24 10:36
Okay, I'm out of ideas. I think something needs to be fundamentally changed here. have validated the following points:

1. Change Base: Doesn't work, because then unfortunately also the relative JS and CSS files are not found, because subdirectory installations are needed
2. Replace A with router-link: Does not work, because there is no scroll, respectively we can't push an object as value :to="{hash: 'xy'}"
3. Implementing the scroll with JavaScript works theoretically, but is then blocked by the production policy (Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src-attr 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present).

Info:
For the JavaScript solution I already extended the plugin markdown-it-table-of-contents in the background (needed for the TOC), so you can add more attributes e.g. an onClick. There was already a PR for this, but the developer probably didn't want to merge it. (https://github.com/cmaas/markdown-it-table-of-contents/pull/59). If my solution is needed, I will of course provide it.

I am curious about your ideas and suggestions :D

**Comment by rijkvanzanten** [comment] 2022-12-15 22:37
Linear: [ENG-212](https://linear.app/directus/issue/ENG-212/in-app-docs-glossary-toc-links-are-broken)

**Comment by Nitwel** [comment] 2023-02-08 14:12
#17434 Removed in-app documentation so this issue is more or less resolved by that.

**Closed by Nitwel** 2023-02-08 14:12 UTC
Labels: App, Bug
