### ISSUE TITLE
Cannot delete collection field

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#9896] opened 2021-11-17 18:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Cannot delete collection input field.

### To Reproduce

- Create a collection
- Create an input field

Try to delete the input field. The input field cannot be deleted and a popup exception trigger.

This has been reproduced without any custom hooks active.

### Errors Shown

Stack trace.
`
18:49:23 ­ƒöì [10.568ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [40282324-0275-4012-97c3-eafb4fae7714, 1]
18:49:23 ­ƒöì [9.083ms] select "archive_field", "sort_field" from "directus_collections" where "collection" = $1 limit $2 [Stories, 1]
18:49:23 ­ƒöì [9.120ms] select "collection", "field" from "directus_fields" where "collection" = $1 and "field" = $2 limit $3 [Stories, job, 1]
18:49:23 ­ƒÜ¿ error update "directus_fields" set "group" = $1 where "group" = $2 and "collection" = $3 - invalid input syntax for type integer:
"job"
error: update "directus_fields" set "group" = $1 where "group" = $2 and "collection" = $3 - invalid input syntax for type integer: "job"
    at Parser.parseErrorMessage (D:\...\node_modules\pg-protocol\dist\parser.js:287:98)
    at Parser.handlePacket (D:\...\node_modules\pg-protocol\dist\parser.js:126:29)    at Parser.parse (D:\...\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (D:\...\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:131:17)
18:49:23 Ô£¿ request errored DELETE 500 /fields/Stories/job
`

Stack trace image
![tempsnip](https://user-images.githubusercontent.com/1532438/142256424-0466d843-e184-4408-a2cf-2fe3aa641dd6.png)
e

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.17.6

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows_NT 10.0.19042

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment] 2021-11-17 22:59
Duplicate of #9092 and #8675. Please follow instructions here: https://github.com/directus/directus/issues/8675#issuecomment-940629829. There's also a comment below that which should (hopefully) clarify things further 👍

**Closed by Oreilles** 2021-11-17 22:59 UTC
Labels: Duplicate
