### ISSUE TITLE
High CPU usage when running in Cluster & Fork modes with PM2

### ISSUE THREAD

**Issue by deounix** [directus/directus#18771] opened 2023-05-29 19:01 UTC
### Describe the Bug

when Directus is launched directly via Node.js or with PM2 in a single instance, the CPU usage remains relatively low, ranging from 0.2% to 2%. However, when running Directus with PM2 in cluster and fork modes, the CPU usage spikes significantly, reaching levels between 100% and 150%.

Directus v10.2.1
Hosted: Self via CLI
OS: Rocky Linux
PM2: v5.3.0

### To Reproduce

# PM2 Config

```
module.exports = {
  apps: [
    {
      name: "crm",
      script: "npx",
      args: "directus start",
      restart_delay: 500,
      instances: 10,
      max_memory_restart: "1G",
    },
  ],
};
```

# PM2 1 INSTANCE

![Screenshot 2023-05-29 212920](https://github.com/directus/directus/assets/17798647/64b219aa-d6a6-4a1f-a412-8a03d1361123)

# PM2 10 INSTANCES

![Screenshot 2023-05-29 214348](https://github.com/directus/directus/assets/17798647/bd853dbf-b60d-4dfb-b1e1-97016aca38b6)

![Screenshot 2023-05-29 214527](https://github.com/directus/directus/assets/17798647/44b97dfc-fcbd-40de-9406-735398babf52)

I thought maybe it's a initializing issue so I waited 1 hour and it's looks the same

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by rijkvanzanten** [comment] 2023-05-30 16:17
I'm wondering if this is a directus issue or a pm2 issue 🤔 The only difference between the two is that the first one uses `bin` / the cli to start the server, but the logic is mostly the same afaict

**Comment by rijkvanzanten** [comment] 2023-05-30 16:19
Oh actually, it could be the usage of `npx` as well 🤔 

@deounix mind trying changing that `npx directus start` to `node node_modules/directus/cli.js start` to see if that changes the behavior?

**Comment by deounix** [comment] 2023-06-02 13:03
@rijkvanzanten Yes, it works fine with the : `node node_modules/directus/cli.js`

**Comment by rijkvanzanten** [comment] 2023-07-09 15:28
I'll have to close this for now, as the only difference between `npx directus start` and `node node_modules/directus/cli.js start` is the usage of `npx`. The `bin` of `directus` is just `cli.js` with nothing else, meaning that the difference in CPU usage is solely caused by `npm` / `npx` usage 🤔

**Closed by rijkvanzanten** 2023-07-09 15:28 UTC
