### ISSUE TITLE
Keycloak 21.1.0 gives "Invalid token"

### ISSUE THREAD

**Issue by timnis** [directus/directus#18304] opened 2023-04-24 11:50 UTC
### Describe the Bug

I upgraded Keycloak to 21.1.0 version and after that when I try to login to directus I get error "Invalid token". 
(With Keycloak 21.0.2 I can login.)

In docker logs
```
directus  | [11:07:31.156] WARN: Invalid token
directus  |     err: {
directus  |       "type": "InvalidTokenException",
directus  |       "message": "Invalid token",
directus  |       "stack":
directus  |           Error: Invalid token
directus  |               at handleError (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/auth/drivers/openid.js:208:20)
directus  |               at OpenIDAuthDriver.refresh (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/auth/drivers/openid.js:198:23)
directus  |               at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus  |               at async AuthenticationService.login (file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/services/authentication.js:110:13)
directus  |               at async file:///directus/node_modules/.pnpm/file+api/node_modules/@directus/api/dist/auth/drivers/openid.js:273:28
directus  |       "status": 403,
directus  |       "code": "INVALID_TOKEN",
directus  |       "extensions": {}
directus  |     }
```

I suspect it related to to this keycloak changes: 
"Default Client ID mapper of Service Account Client has been changed. Token Claim Name field value has been changed from clientId to client_id. client_id claim is compliant with OAuth2 specifications:"

See more [https://www.keycloak.org/2023/04/keycloak-2110-released.html](https://www.keycloak.org/2023/04/keycloak-2110-released.html)

### To Reproduce

1. Upgrade keycloak to version 21.1.0
2.  try to login to directus via keycloak

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by aidenfoxx** [comment] 2023-04-24 17:22
The issue is actually caused by this PR change, where "refresh_token" is no longer being updated on user on login, causing the now invalid "refresh_token" in your DB to trigger an error. The "refresh_token" should be merged into the `updatedUserPayload`, but it's not.

https://github.com/directus/directus/commit/b2204138191f00e4c81acc8e3efe39b78ba2e199#diff-249d6560e108f61fab7c1b235ece9adcf3880369803d990f7771a680888fb408L145

**Comment by dmitrygribenchuk** [comment] 2023-04-25 14:23
Hello. Have the same issue

**Comment by dmitrygribenchuk** [comment] 2023-04-25 14:29
Hello. Have the same issue after clean install 9.25.2
And another one after an update to 9.25.x

**Comment by rijkvanzanten** [comment] 2023-04-26 20:51
Fixed in https://github.com/directus/directus/pull/18310

**Closed by rijkvanzanten** 2023-04-26 20:51 UTC
Labels: API, Bug, Regression
