### ISSUE TITLE
Two map fields crash stalls site

### ISSUE THREAD

**Issue by u12206050** [directus/directus#7773] opened 2021-09-02 07:30 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

As soon as you have two map fields within a collection, or even two spread across two related collections than are connected then it triggers this maximum call stack exceeded

Have gotten this error with only one map field. Don't know if is related:
![Screenshot 2021-09-02 at 09 32 16](https://user-images.githubusercontent.com/6641242/131801749-00358a48-87ac-47fe-bd44-8113addc9d5a.png)

### To Reproduce

Create a collection with two map fields
eg. Map1 and map2
In my case I chose Point in both the options.

Try to add a new item or add a preset with the new collection.

### What version of Directus are you using?

9.0.0-rc.91

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql 8

### What browser are you using?

chrome

### What operating system are you using?

m1 mac osx

### How are you deploying Directus?

locally

**Comment by u12206050** [comment] 2021-09-02 07:42
Turns out if I remove my own mapbox token and any styles then it does seem to work with two map fields.

**Comment by u12206050** [comment] 2021-09-02 07:43
Although it still hangs and crashes when editing the preset.

**Comment by TomThats** [comment] 2021-09-02 11:54
I have the same problem with just one map field when I change collections within the app.

![directus call stack size map bug](https://user-images.githubusercontent.com/3465653/131838862-542cedc3-42c8-417c-8739-ce90e1e2bc35.png)

The server log shows nothing but this over and over again:
"request completed PATCH 200 /presets/10 20ms"

**Comment by rijkvanzanten** [comment] 2021-09-03 01:45
@u12206050 Could you share those custom styles that might trigger this?

I can't reproduce this locally, I think this might've already be fixed by https://github.com/directus/directus/pull/7602/files. I'm pushing out a release now, could you let me know if 92 fixed it for you?

**Closed by rijkvanzanten** 2021-09-03 01:45 UTC
Labels: Bug (Potential)

**Comment by TomThats** [comment] 2021-09-03 07:02
@rijkvanzanten 
I just updated to .92 and can't reproduce this bug anymore. Well done!
