### ISSUE TITLE
Fields starting with underscore not working

### ISSUE THREAD

**Issue by franklaboris** [directus/directus#21528] opened 2024-02-23 00:53 UTC
### Describe the Bug

Among my tables and fields, I have a few starting with a single underscore (_). When I try to use them in a filter, an error is triggered:

```json
{
  "filter": {
    "_fivetran_deleted": {
      "_eq": true
    }
  }
}

Result:
{
  "errors": [
    {
      "message": "Invalid query. The filter value for \"_fivetran_deleted\" has to be a string, number, or boolean.",
      "extensions": {
        "code": "INVALID_QUERY",
        "reason": "The filter value for \"_fivetran_deleted\" has to be a string, number, or boolean"
      }
    }
  ]
}
```

### To Reproduce

Set up a collection (entity) containing at least one field starting with an underscore. Use Graphql to query the collection using that field as part of the filter

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment] 2024-02-26 11:46
Yes thats right, we currently use the leading underscore to differentiate between filter operations and keys.

For someone looking into this its located in: `validate-query.ts`

```ts
...
for (const [key, nested] of Object.entries(filter)) {
	if (key === '_and' || key === '_or') {
		nested.forEach(validateFilter);
	} else if (key.startsWith('_')) {
...
```

I'd love to rework the filters but its not a tiny change and effects basically everything in Directus and then also extensions that people built, etc. :sweat:

**Comment by br41nslug** [comment] 2024-02-26 11:47
Duplicate of https://github.com/directus/directus/issues/16189

**Closed by br41nslug** 2024-02-26 11:47 UTC
Labels: Needs Research
