### ISSUE TITLE
Field Value required even if value is set, and permissions allowed to all access

### ISSUE THREAD

**Issue by sksar** [directus/directus#17305] opened 2023-01-26 03:44 UTC
### Describe the Bug

While trying to create records in a collection with full access, certain fields are showing Value is required, even when the field permissions are set to not required (but the database is set to not allow null values).
But the weird part is that the value is set, but stills says to be required.

Also even I even tried to upgrade it to version 9.22.4 (or the latest), but no matter how many times I run the npm update (from the server terminal), it does not update to 9.22.4 and is only updating to 9.22.3 (or that is what it shows in the Directus version in the Directus admin app)

![Screenshot 2023-01-26 at 09 06 05](https://user-images.githubusercontent.com/11752260/214753995-37f83fac-04b1-41b9-8c2f-ad21e836ca73.jpg)

### To Reproduce

Install version 9.22.3 or install any previous version such as 9.11.0, and npm upgrade it and migrate the database.
Then try to make changes to a particular collection, from a non-admin user. (With only CRU permissions)

Note that all fields do not have the same problem, and only a few of them does.

### What version of Directus are you using?

9.22.3

### What version of Node.js are you using?

16.15.1

### What database are you using?

mysql

### What browser are you using?

Chrome

### How are you deploying Directus?

pm2

**Comment by br41nslug** [comment] 2023-01-26 10:20
I was unable to reproduce this using the given reproduction steps.

> Note that all fields do not have the same problem, and only a few of them does.

Could you provide a snapshot or dump of the collection that is problematic for you? Judging from the screenshot "First name" is throwing a required error without being required (no star on the form) could there be extra validation or an extension throwing this error?

**Comment by rijkvanzanten** [comment] 2023-01-26 19:51
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2023-01-26 19:51 UTC
Labels: Needs More Info, Can't Reproduce

**Comment by sksar** [comment] 2023-01-27 05:46
@br41nslug Yes, it is not required. But is set to Not allow null from the schema level. The weird thing is that when all of the above fields are set to not required (from the schema level) the save goes through, and also shows up in the revision.
But when we read it, it does not show anything, basically it shows it all null.

I can share the snapshot, but I don't think that would solve the problem. The dump would be I guess more better, but then I need to share it with someone privately. If you could provide your email address.
