### ISSUE TITLE
Permissions - You lack privileges for 'XXXXX' on table create.

### ISSUE THREAD

**Issue by PolywickStudio** [directus/directus#1308] opened 2016-12-07 06:34 UTC
- Directus version and branch: (Or commit hash) - latest version./master branch
  - PHP version: 7.1
  - MySQL version: 7.16
  - Web server: (Ex. Apache, nginx or IIS?) XMP
  - OS name and version: Windows 2012 standard.

## Expected Behavior
Click create table, then click somewhere else, it then says:
You lack privileges for 'XXXXX' on table create.

## Actual Behavior
You should have default table to be '<something> instead of <denied> or "not enabled".

## Steps to Reproduce
 1. Add a new table.
 2. Click somewhere else.
 3. Go back to the same table., and you get an error.

**Comment by WellingGuzman** [comment] 2016-12-07 20:43
Thanks @PolywickStudio I will on a fix today.

**Comment by WellingGuzman** [comment] 2016-12-08 22:01
Hey @PolywickStudio, does by any change the table you are creating has capital letter?

**Comment by PolywickStudio** [comment] 2016-12-12 00:42
I'm not sure. I think they are. Is there an issue with case-sensitivity?

Can there be an option to make it all lower-case when enter into database?

**Comment by WellingGuzman** [comment] 2016-12-12 00:50
@PolywickStudio we have being peacefully arguing this recently, but some people like using Uppercases and lowercase combine in a table name, and how the database allow it, I think we should. The issue is with MySQL though, but should've a fix for it soon enough.

You can try using lowercase and letting me know if that works for you, so I can be certainly sure the issue is with the table name (uppercase/lowercase)

**Comment by PolywickStudio** [comment] 2016-12-12 01:56
Is there a way how to make it like a setting?

For instance, when enter into field, the thing converts to lower-case automatically, or uppercase, then convert " "(space) to "_" (underscore). That would help to remove data entry issues.

**Comment by benhaynes** [comment] 2016-12-13 16:18
@PolywickStudio – That's exactly what we have planned in the next version – yes. You can check out the static template preview here:

http://preview.getdirectus.com/settings/tables/new

You can see the table name at the top has a checkbox to toggle "strict naming" and if you click to create a new column the same checkbox is present.

Is this what you mean? Then we could maintain "proper" casing/formatting by default, but allow for people to override that if they want.

**Comment by PolywickStudio** [comment] 2016-12-15 06:24
I mean, have a combobox to allow:

0) full lowercase names - this will result in full lower-case names for tables.
1) full uppercase names - this will result in full lower-case names for tables.
2) mixed case names - this will result in any-case names for tables.

default = 0.

**Comment by benhaynes** [comment] 2016-12-15 16:51
True – but there's more potential auto-formatting that that: eg entering an Underscore vs Space vs Dash.

Might be best to have one option where WE auto-format to help keep things standard by default – or an override option where you can do anything (if you _know_ what you're doing, that is).

**Comment by benhaynes** [comment] 2016-12-15 16:51
Going to close this since it has been addressed in the next version design. Thanks @PolywickStudio!

**Closed by benhaynes** 2016-12-15 16:51 UTC
Labels: 3. Major, Bug

**Comment by davidbwaters** [comment] 2017-03-02 01:34
Hey, I was experiencing this also.  Just to note, if an inaccessible capitalized table is created and fields are added, creating a table with the same name lowercase let's you access the original.
