### ISSUE TITLE
Server crash when exception is thrown from async hook

### ISSUE THREAD

**Issue by claytongulick** [directus/directus#17601] opened 2023-02-22 20:29 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

We have a hook on item create. In the hook, I'm writing to a different collection. I'd forgotten to sync my schema with another developer, so that collection doesn't exist, and an error is thrown. This is to be expected.

The issue is that it caused a hard server crash, which is unexpected.

The hook is an async function:
```
action("patient_availability.items.create", async (meta, context) => {
        const { key } = meta;
        const { database, schema, accountability } = context;

        const directus_opts = {
            accountability,
            schema,
            knex: database,
        };

        await createCareEvent(key, "patient_availability", directus_opts, services);
    });
```

The exception is thrown in:

```
 await createCareEvent(key, "patient_availability", directus_opts, services);
```

Which causes the server crash.

### To Reproduce

Throw an exception in an async handler for a hook.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2023-02-23 17:40
Thanks for opening this issue! Can you provide some more information on this, for example the logic inside `createCareEvent`? Actually errors thrown inside hooks are caught so I assume the error which leads to the crash is happening somewhere else (e.g. in services?).

**Comment by claytongulick** [comment] 2023-02-23 18:57
Sure, I'm using the items service to create a record, but in this case the collection I was referencing doesn't exist:

```
const careEventItemService = new ItemsService("care_event_item", directus_opts);
        const careEventService = new ItemsService("care_event", directus_opts);
        const care_event_item_data = await careEventItemService.readByQuery({
            filter: {
                item: {
                    _eq: item_id,
                }
            },
        });
```

This threw, which bubbled up to the async hook and caused the crash.

**Comment by paescuj** [comment] 2023-02-24 10:06
I'm still not able to reproduce this. In my tests the error was successfully intercepted and thus did not lead to a server crash.

Example log excerpt:
```console
WARN: An error was thrown while executing action "patient_availability.items.create"
WARN: Cannot read properties of undefined (reading 'primary')
````

Since we haven't been able to reproduce this based on the given information, I'll close the issue for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by paescuj** 2023-02-24 10:06 UTC
