### ISSUE TITLE
Fields Don't Respond to Conditions Set In M2O Fields

### ISSUE THREAD

**Issue by supermx1** [directus/directus#11920] opened 2022-03-02 22:16 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

https://user-images.githubusercontent.com/9326922/156459070-7b4ba81c-eb64-486f-8a69-d9477a468138.mp4

### To Reproduce

See above video

### Errors Shown

None

### What version of Directus are you using?

9.5.2

### What version of Node.js are you using?

14

### What database are you using?

MySQL

### What browser are you using?

Chrome, Brave

### What operating system are you using?

MacOS, Ubuntu 20.08LTS

### How are you deploying Directus?

Digital Ocean Cloud

**Comment by azrikahar** [comment] 2022-03-03 04:46
Duplicate of #10952, and we are currently tracking this in #8228 so feel free to follow the notification over there 👍

Just as a summary, the general issue with M2O condition revolves around the condition set is actually:

```json
{
    "m2o_field": {
        "id": {
            "_eq": 2
         }
    }
}
```

but when we are _selecting_ an item of m2o field, the condition that is actually expected by the app is:

```json
{
    "m2o_field": {
        "_eq": 2
    }
}
```

hence the condition couldn't match properly.

**Closed by azrikahar** 2022-03-03 04:46 UTC
Labels: Bug (Potential)

**Comment by ulvidamirli** [comment] 2022-04-09 21:05
> Duplicate of #10952, and we are currently tracking this in #8228 so feel free to follow the notification over there 👍
> 
> EDIT: See also #11844 for most recent related discussion.
> 
> Just as a summary, the general issue with M2O condition revolves around the condition set is actually:
> 
> ```json
> {
>     "m2o_field": {
>         "id": {
>             "_eq": 2
>          }
>     }
> }
> ```
> 
> but when we are _selecting_ an item of m2o field, the condition that is actually expected by the app is:
> 
> ```json
> {
>     "m2o_field": {
>         "_eq": 2
>     }
> }
> ```
> 
> hence the condition couldn't match properly.

I try this with the latest version (9.8.0) but it doesn't work. My problem is the same as the OP

**Comment by rijkvanzanten** [comment] 2022-04-11 19:15
@ulvidamirli You already posted in #8228 too, so lets keep the conversation in there 👍🏻
