### ISSUE TITLE
ERROR: "articles.date_created_func" is not a relational field 

### ISSUE THREAD

**Issue by development-vargamarcel** [directus/directus#14809] opened 2022-08-03 08:12 UTC
### Describe the Bug

Making a request with **QUERY 1**,directus responds with _**ERROR: "articles.date_created_func"**_ is not a relational field.
Making a request with QUERY 2, ALL WORKS FINE.

Note that QUERY 1B uses the same [syntax (click to view what syntax i am reffering to)](https://dgraph.io/docs/graphql/queries/and-or-not/#nesting) as QUERY 1,BUT WORKS.

**QUERY 1**:
```
query MyQuery {
  articles(filter:{_and:[{date_created_func:{year:{_lte:"2022"}}}]}){
id
  }
}
```
QUERY 2:
```
    query MyQuery {
  articles(filter:{date_created_func:{year:{_lte:"2022"}}}){
id
  }
}
```

QUERY 1 B:
```
    query MyQuery {
  articles(filter:{_and:[{date_created:{_lte:"2022-08-03T08:04:00.000Z"}}]}){
id
  }
}
```

### To Reproduce

Create a demo directus comunity project and make the folowing query:
```
query MyQuery {
  articles(filter:{_and:[{date_created_func:{year:{_lte:"2022"}}}]}){
id
  }
}
```

### Errors Shown

`"articles.date_created_func" is not a relational field `

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

Community Cloud

### What database are you using?

Community Cloud

### What browser are you using?

opera

### How are you deploying Directus?

Community Cloud

**Comment by licitdev** [comment] 2022-08-03 09:10
Closing as duplicate of https://github.com/directus/directus/issues/14698.
Thank you.

**Closed by licitdev** 2022-08-03 09:10 UTC
Labels: Duplicate
