### ISSUE TITLE
Content creation date not showing correctly

### ISSUE THREAD

**Issue by Vprasannaakumar** [directus/directus#11448] opened 2022-02-05 16:39 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Whenever I make new entry , new entry **creation date** showing wrongly and also same for entry update. I tried to get data from api also, it giving wrong time stamp. I created at 9:50 PM IST and checked immediately , but it giving results as shown in below screenshots.

![image](https://user-images.githubusercontent.com/32242696/152649874-48e10598-6853-40aa-92b8-16fd7db2ff8a.png)

![image](https://user-images.githubusercontent.com/32242696/152649913-e7ff016b-3fff-4b72-aa93-7cbe368ac43a.png)

### To Reproduce

1 .Create new schema ex: Post
2. add new entry
3. Set table view to see all entries and also select Date created field under fields 
4. It shows "about 6 hours ago" 
5. If you query through API, Create Date will be wrong

### Errors Shown

NO

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

Windows_NT 10.0.19044

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2022-02-06 07:34
Duplicate of #7383. Just to describe the issue further, since IST is UTC +5:30, the `date_created` ended up dating _back_ 5 and a half hours. You did mention it's created at 9.50pm, but I can only assume it's 9.43pm to be exact.

With that in mind, `9.43 pm` - `5 hours 30 minutes` = `4.13 pm`, which is the `date_created` value shown in your API 👍 We'll keep track of this over there since it's one of the pinned issues here.

**Closed by azrikahar** 2022-02-06 07:34 UTC
Labels: Bug (Potential)
