### ISSUE TITLE
Import does not work with string input primary key

### ISSUE THREAD

**Issue by DerSkillBaumApfel** [directus/directus#19948] opened 2023-10-08 11:29 UTC
### Describe the Bug

Hi guys!

Upon importing a m2m nested collection, json child objects are not correctly resolved.
The import itself passes and related items will be linked/junction table entries will be created, but the referenced item does not exist/is not created.

This happens if the primary key of the related collection is set to "manually entered string", and "id" is renamed to something other than "id". 

Observations:
- If "id" is kept as "id", there will be a "forbidden" error upon import. Which does not really make sense, if an admin user is trying to import something.
- If "id" is renamed, the import will succeed. But after importing, the referenced items are not created like with "auto-incremented integer" or "generated uuid" if they do not exist.

If relevant:
DB-provider: postgis/postgis:13 (docker image)
Cache: redis:6 (docker image)

A more detailed explaination of my findings is contained in the "steps to reproduce" section.

### To Reproduce

1. Create collection1 (does not have to have any special settings, just proceed through the dialog)
2. Create collection2 with "primary key field" set to "manually entered string" and rename "id" to "name".
3. Add a "many-to-many" relationship from collection1 to collection2 named "collection2_ref".
4. Create a json file containing the following:
`
[
  {
    "collection2_ref": [
      {
        "name": "Hello"
      },
      {
        "name": "World"
      },
      {
        "name": "! :)"
      }
    ]
  }
]
`

5. Navigate to "Content -> Collection 1 -> Import/Export" and import the json file from step 4.
6. There should now be 3 references in collection1/the generated junction table like on the following image:
![resulting_collection](https://github.com/directus/directus/assets/25012675/c49dc716-e5d4-458a-b7b4-f468db730876)

... but no existing item in collection2
![existing_collection_2_items](https://github.com/directus/directus/assets/25012675/bb63c820-55ed-417c-b963-b940e7854ee0)

**Side note:** 
If the primary key field is not renamed/kept as "id" in Step 2, there will be a 403 FORBIDDEN Error that is thrown.
`
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}
`

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Sohailsaifi** [comment] 2023-10-08 17:05
Can I attempt this?

**Comment by azrikahar** [comment] 2023-10-09 05:23
> The import itself passes and related items will be linked/junction table entries will be created, but the referenced item does not exist/is not created.

I believe this is due to the payload used only contains the junction table and not the related collection 👍

Currently the payload being:

```json
[
	{
		"collection2_ref": [
			{ "name": "Hello" },
			{ "name": "World" },
			{ "name": "! :)" }
		]
	}
]
```

This would mean it'll be creating items in `collection2_ref` (i.e. the junction table) with `name` property. However since the junction table itself doesn't have the field/column called `name`, it'll end up being 3 empty items in the junction table.

In order to create items in the related collection, you'll need to go 1 level deeper, such as:

```json
[
	{
		"collection2_ref": [
			{ "collection2_id": { "name": "Hello" } },
			{ "collection2_id": { "name": "World" } },
			{ "collection2_id": { "name": "! :)" } }
		]
	}
]
```

with `collection2_id` being the assumed name for the foreign key (field/column) in the _junction table_ pointing towards `collection2`. Feel free to change it to the actual name if my assumption was incorrect!

I'll be closing this issue for now as not a bug, but do let us know if it is still not working on your end and we can investigate further.

> Can I attempt this?

@Sohailsaifi thanks for being interested in tackling this! Unfortunately I believe this is not an actual bug and proceeded to close this for now, but do feel free to check out other issues, especially ones that are confirmed to be a bug 👍

**Closed by azrikahar** 2023-10-09 05:23 UTC
