### ISSUE TITLE
Every other load causes FORBIDDEN error on newly created collections

### ISSUE THREAD

**Issue by TomSmedley** [directus/directus#14211] opened 2022-06-30 10:19 UTC
### Describe the Bug

Since 9.13, when creating a new collection and adding it so public have permission, I'm getting a FORBIDDEN or it comes through fine depending on reload. 
1st - it doesn't work
2nd - it works
3rd - it doesn't work
4th - it works

See: https://www.loom.com/share/f66bda368cd54879ba27889892b690d9

### To Reproduce

Create a new collection
Set it so public can see
Hit the API

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

NPM

**Comment by br41nslug** [comment] 2022-06-30 11:23
I am unable to reproduce this and is most likely a hosting issue unfortunately. Closing the ticket for now until there is more info to get to the bottom of this problem :)

**Closed by br41nslug** 2022-06-30 11:23 UTC

**Comment by azrikahar** [comment] 2022-06-30 11:32
Just to chime in on this, this "every other load" does seem like it's very likely you are having multiple instances of Directus (typically via Kubernetes or PM2 when reported in the past) and it's round-robin bouncing between one that has the new collection, vs another one that doesn't.

Do make sure to use a shared cache store such as Redis to prevent this problem if that's the case 👍
