### ISSUE TITLE
Issue with User Visibility and Tagging After Updating to Version 10.8 or 10.8.1

### ISSUE THREAD

**Issue by dvpnc** [directus/directus#20496] opened 2023-11-21 21:24 UTC
### Describe the Bug

I've encountered an issue related to user visibility and the ability to tag users, which seems to have arisen following an update from version 10.7.2 to either 10.8 or 10.8.1

### To Reproduce

In version 10.7.2, all users were able to view the list of other users and tag them using the '@' symbol. However, after updating to version 10.8 or 10.8.1, this functionality appears to be restricted. Now, only admin users are able to view the full user list and tag other users.

Steps to Reproduce:
1. Set up a Docker container with version 10.7.2
2. Add at least two users to the system.
3. Verify that all users can view each other and use the '@' tagging feature.
4. Update the system to version 10.8 or 10.8.1.
5. Observe that non-admin users can no longer view the full user list or use the '@' tagging feature.

This change in functionality has significant impacts on user interaction within the system. Any insights or solutions to restore the previous user visibility and tagging capabilities would be greatly appreciated.

Thank you!

### Directus Version

v10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-11-22 16:43
Thanks for reporting this, it seems to be a regression with "full permissions" on users and roles. I have created a new issue to address the root cause for the various reports we received about this.
I am closing this issue in favor of tracking this issue over here https://github.com/directus/directus/issues/20504

Currently there is a workaround with custom permissions to get it working again in the short term as screenshot for that can be found here https://github.com/directus/directus/issues/20492#issuecomment-1820862724

**Closed by br41nslug** 2023-11-22 16:43 UTC
