### ISSUE TITLE
Invite Users

### ISSUE THREAD

**Issue by ViniciusGrippe** [directus/directus#5654] opened 2021-05-13 15:12 UTC
I trying to invite a user and i got this error:

`{
  "message": "ENOENT: no such file or directory, open '/Users/viniciusgrippe/Downloads/sojalegal-painel/extensions/templates/user-invitation.liquid'",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}`

I see on [https://github.com/directus/directus/issues/5555](#5555) is a bug after v.59, so how can I change the version of my app to v.59 (Actually my app is v.64) and use the same database? That is possible?
I changed version on package.json but doesnt work.

**Comment by rijkvanzanten** [comment] 2021-05-13 18:38
Duplicate of https://github.com/directus/directus/issues/5555

>  and use the same database? That is possible?

Yeah, you can use `npx directus database migrate:down` to rollback database migrations 👍🏻

**Closed by rijkvanzanten** 2021-05-13 18:38 UTC
