### ISSUE TITLE
Invalid rediret url - Configuring Google OAuth for Directus

### ISSUE THREAD

**Issue by ssiva89** [directus/directus#24020] opened 2024-11-10 21:43 UTC
### Describe the Bug

configured environment variable for  google oauth integration with directus 11.1.2.
i'm getting this below response when i try to login using google.

```
{
  "errors": [
    {
      "message": "Invalid payload. URL \"http://localhost:8055/admin/login?continue=\" can't be used to redirect after login.",
      "extensions": {
        "reason": "URL \"http://localhost:8055/admin/login?continue=\" can't be used to redirect after login",
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

Environment variables configured:

```
AUTH_PROVIDERS: "google"
AUTH_GOOGLE_DRIVER: "openid"
AUTH_GOOGLE_CLIENT_ID: "XXXXXXXX" # Replace XXXX with the Client ID from Step 6
AUTH_GOOGLE_CLIENT_SECRET: "XXXXX" # Replace XXXX with the Client Secret from Step 6
AUTH_GOOGLE_ISSUER_URL: "https://accounts.google.com"
AUTH_GOOGLE_IDENTIFIER_KEY: "email"
AUTH_GOOGLE_ICON: "google"
AUTH_GOOGLE_LABEL: "Google"
AUTH_GOOGLE_REDIRECT_ALLOW_LIST: "http://localhost:8055/admin/login"
AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION: "true" # This allows users to be automatically created on logins. Use "false" if you want to create users manually
AUTH_GOOGLE_DEFAULT_ROLE_ID: "XXXXXX" 
      
```

### To Reproduce

install docker 
create docker compose file with necessary environment variable (as mentioned above)
Configuring Google OAuth for Directus (steps mentioned here : https://docs.directus.io/self-hosted/sso.html)   
start the container 
Hit "localhost:8055"
click on the "login with google"

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by ComfortablyCoding** [comment] 2024-11-11 17:40
The `PUBLIC_URL` env must be set in addition to the above configuration, see https://github.com/directus/directus/issues/19331

**Comment by ComfortablyCoding** [comment] 2024-11-11 19:14
> @ComfortablyCoding , yes. tried as below,
> 
> PUBLIC_URL: "http://localhost:8055"

Can you confirm the instance was re-started after the env was added? I cannot reproduce this issue with the provided information, once the `PUBLIC_URL` is added it works with no issue for me

**Comment by ssiva89** [comment] 2024-11-11 19:46
@ComfortablyCoding 
it worked now. thanks

**Comment by ComfortablyCoding** [comment] 2024-11-11 20:04
Glad that worked. In terms of the new error I believe it is due to the `AUTH_GOOGLE_DEFAULT_ROLE_ID` being incorrect/invalid. As the original reported issue has been resolved I will go ahead and close this issue.

**Closed by ComfortablyCoding** 2024-11-11 20:04 UTC
Labels: Needs Info
