### ISSUE TITLE
Collections inside menu groups do not show content

### ISSUE THREAD

**Issue by micheleferraro** [directus/directus#17027] opened 2023-01-05 17:56 UTC
### Describe the Bug

In the Contents section, the pages of the collections that were placed in a group in the menu do not display the content.
If you select a collection outside of a group and then the collection again within the group, the content is displayed correctly.
If you refresh the page, the content is displayed correctly.

I'm experiencing the same problem in all my directus instances.

### To Reproduce

If I load a collection at first level I always see contents:
![1](https://user-images.githubusercontent.com/39918028/210846626-4d045ac2-1b23-4f07-a07d-b3a4c777465f.png)

The first time I load a collection inside a group everything is fine:
![2](https://user-images.githubusercontent.com/39918028/210846942-9354f4b1-ef40-4875-a1fd-92f1f761a108.png)

Then if I try to load another collection inside a group I don't see the content:
![3](https://user-images.githubusercontent.com/39918028/210847135-b938a0b4-6fa8-46d8-98a7-cf24379efe5d.png)

To view the content, I have to refresh the page or load a collection outside of the groups first (even if the collection has no items):
![4](https://user-images.githubusercontent.com/39918028/210847274-b15db956-af24-40b6-9877-ec9dd74eb030.png)

### Errors Shown

No error is displayed, not even in the JavaScript console.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

MariaDB 10.5.15

### What browser are you using?

Chrome

### How are you deploying Directus?

Running locally

**Comment by azrikahar** [comment] 2023-01-06 07:32
Duplicate of #16883

**Closed by azrikahar** 2023-01-06 07:32 UTC
