### ISSUE TITLE
Reusable components - M2A relationship in video has holders to move the order of items

### ISSUE THREAD

**Issue by Hell0XD** [directus/directus#19351] opened 2023-08-04 14:11 UTC
### Page

https://docs.directus.io/guides/headless-cms/reusable-components.html

### Describe the Inaccuracy

M2A relationship in video has holders to move the order of items. That is behaviour I was expecting when it's advertised as builder for defined blocks. Without it I would have to removed all the blocks to make change in middle block.

But sadly this is not the case.
<img width="1040" alt="Screenshot 2023-08-04 at 16 09 52" src="https://github.com/directus/directus/assets/45717402/087a8713-e587-4711-8b7d-9678aa4e33a7">

As you can see I can not move them, as indicated in the docs video.
<img width="447" alt="Screenshot 2023-08-04 at 16 11 02" src="https://github.com/directus/directus/assets/45717402/7f20e999-4aad-4b0c-ae89-7dfd99e8b905">

To Reproduce
Just follow the [article](https://docs.directus.io/guides/headless-cms/reusable-components.html).

Directus Version
v10.5.2

Hosting Strategy
Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-08-04 14:25
Thanks for opening this issue! However this is a duplicate of an existing issue #19334, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #19334 for future updates.

**Closed by paescuj** 2023-08-04 14:25 UTC
Labels: Documentation
