### ISSUE TITLE
Webhook action in Flows breaks after updating 10.8 to 10.9

### ISSUE THREAD

**Issue by davay42** [directus/directus#21423] opened 2024-02-14 05:33 UTC
### Describe the Bug

I have a perfectly working manual trigger Flow, that sends collected emails to Klaviyo. After upgrading Directus to 10.9.1 I get the error 
```
{
  "name": "Error",
  "message": "Requested URL \"undefined\" resolves to a denied IP address"
}
```

### To Reproduce

Here is the 10.8.3 flow log. All ok.

<img width="837" alt="Screenshot 2024-02-14 at 12 30 27" src="https://github.com/directus/directus/assets/6184449/634fba05-0f47-435b-b1b6-550de25e252d">

Here is the configuration for the Webhook action in question

![image](https://github.com/directus/directus/assets/6184449/73ce8352-7dfb-47d1-91f1-70d392785bc2)

Here is the error that happens after the 10.9.1 update.

![image](https://github.com/directus/directus/assets/6184449/2819458b-1a0a-46f6-93e0-433921d43a21)

No idea how to debug it...

### Directus Version

10.9.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-02-14 08:43
Thanks for opening this issue! However this is a duplicate of an existing issue #21351, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #21351 for future updates.

**Closed by paescuj** 2024-02-14 08:43 UTC
