### ISSUE TITLE
It is possible to delete images that are used in a collection

### ISSUE THREAD

**Issue by LasseRosenow** [directus/directus#10923] opened 2022-01-08 15:31 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Usually when I try to delete an image from the media library, I get an error message if that image is used somewhere.
When deleting an image that is used inside a single instance collection, this is still the case, but when I try to delete an image that is used inside a multi instance collection, it just works and I get error messages when I open the collection instance that uses the deleted image.

Actually after playing a bit more around it I also managed to delete an image that was used by a single instance collection, so it seems to be somewhat random?

### To Reproduce

1. Create a multi instance collection
2. Add a image field
3. Upload an image
4. Save collection
5. Go to the media library and delete the image

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

On a remote Debian server

**Comment by Oreilles** [comment] 2022-01-10 19:30
It is expected that you are able to delete images regardless of whether they are being referenced or not.
But what you mean by "multi instance collection" ?

**Comment by LasseRosenow** [comment] 2022-01-10 19:33
multi instance collection is just a normal collection sorry for the confusion.

Hm that is interesting, because sometimes I get error messages that I cannot delete images, when I try to, because it is used in some relation 🤔

**Comment by LasseRosenow** [comment] 2022-01-10 19:34
But in general: Don't you think it would be better anyways to prevent the user from deleting data, that is used somewhere?

**Comment by Oreilles** [comment] 2022-01-10 19:37
This is possible with other relational data with the `on_delete` rule, but I don't believe that ever were the case for file relations 🤔 Can you pin down the exact situation where you getting an error preventing you to delete images referenced elsewhere ?

**Comment by LasseRosenow** [comment] 2022-01-10 19:42
I try to find an example, though it is really random for whatever reason 😅

**Comment by LasseRosenow** [comment] 2022-01-10 19:44
![image](https://user-images.githubusercontent.com/10547444/148828909-7ac9419d-de40-404b-bc99-5d6270a05104.png)

This is the error message I am getting

**Comment by LasseRosenow** [comment] 2022-01-10 19:46
Uh I think the problem is, that the image field can not be null maybe?

**Comment by Oreilles** [comment] 2022-01-10 19:46
Could you please share a shema snapshot ?

**Comment by LasseRosenow** [comment] 2022-01-10 19:48
[cwb0.zip](https://github.com/directus/directus/files/7841502/cwb0.zip)

**Comment by LasseRosenow** [comment] 2022-01-10 19:56
> Uh I think the problem is, that the image field can not be null maybe?

But I did some more testing and I am 100% certain, that this is the case.
I can not delete images, when they are used in a field that is non nullable, but I can delete images, that are used in fields that are nullable.


SO now the question is: Is it desirable to be able to delete images in the gallery, that may be used basically anywhere?
I think this is not desirable.

**Comment by Oreilles** [comment] 2022-01-10 20:28
Are you suggesting to remove the ability to delete images from the gallery ?

**Comment by LasseRosenow** [comment] 2022-01-10 20:32
I am only suggesting to display an error message if you try to delete an image from the gallery that is used somewhere.

All images that are not used anywhere should still be possible to delete.

Another approach would be to display a nice formatted message that lists all the places where the image is currently used, but still providing the ability to delete it anyway.

I think I like the first one more, but I would be finde with both. I only know that I don't want to be able to delete something somewhere and causing side effects without noticing it ;)

**Comment by Oreilles** [comment] 2022-01-10 20:50
We won't be able to find whether an image is reference somewhere before trying to delete it, because that would be a massive overhead (you'd have to iterate over every row of collection to find out whether a file field references the corresponding image).

I agree however that being able to pick the correct `on_delete` behaviour (`prevent deletion`, `cascade`, or `set null`) for file/image fields, just like it is the case for other `m2o` fields, might be a useful, but since it is not a bug in itself I'll leave it up to you to open a new Discussion if that is something you would want. 👍

A better error message would be nice too - but since there doesn't appear to be an actual bug here (the database only prevented a forbidden null value), I will close this issue.

**Closed by Oreilles** 2022-01-10 20:50 UTC
Labels: Needs More Info

**Comment by LasseRosenow** [comment] 2022-01-10 21:11
But for the better error message, that would state, that the image is used somewhere, it would still be needed to check all collections, which is too much overhead as you stated before. Did I get that right?

**Comment by benhaynes** [comment] 2022-01-10 23:42
I'm curious if the failing foreign key constraint could be caught so we can say the image is used somewhere, instead of searching all file-fields throughout collections. Still, I am curious how much overhead would be involved in finding those actual uses. It's a `id=[x]` on all file fields... maybe it can be an async background check? Just thinking out loud... ;)

I've wanted this feature for a while... where you can see all the places a file (or any relational item) is used throughout the system. Other platforms show this, and I find it useful.

@rijkvanzanten, any thoughts on all this?

**Comment by azrikahar** [comment] 2022-01-10 23:54
I believe this is related to (or essentially covered by) #9507, with this comment https://github.com/directus/directus/issues/9507#issuecomment-961913172 being the gravitated approach, at least at that point in time 👍

**Comment by benhaynes** [comment] 2022-01-11 00:03
> I believe this is related to (or essentially covered by) #9507, with this comment [#9507 (comment)](https://github.com/directus/directus/issues/9507#issuecomment-961913172) being the gravitated approach, at least at that point in time 👍

Exactly! Thanks, Azri...

**Comment by rijkvanzanten** [comment] 2022-01-11 22:01
> I agree however that being able to pick the correct on_delete behaviour (prevent deletion, cascade, or set null) for file/image fields, just like it is the case for other m2o fields, might be a useful, but since it is not a bug in itself I'll leave it up to you to open a new Discussion if that is something you would want. 

Added this in https://github.com/directus/directus/pull/10985 @Oreilles 👍🏻
