### ISSUE TITLE
Custom permissions not working after update from rc94 to rc96

### ISSUE THREAD

**Issue by u12206050** [directus/directus#8794] opened 2021-10-14 13:15 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

So after updating to rc96 and running migrations non admin users can not update items as the previously could.

It seems custom permissions are being parsed different now than before.

The following is a very common filter rule I use on a lot of my collections and it used to work on rc94.
```
{
	"group": {
		"users": {
			"user": {
				"_eq": "$CURRENT_USER"
			}
		}
	}
}
```

I even have a more advanced one that also used to work be it only on update but not on create:

```
{
	"group": {
		"users": {
			"user": {
				"_eq": "$CURRENT_USER"
			},			
			"role": {
				"_eq": "author"
			}
		}
	}
}
```

### To Reproduce

Setup a `groups` collection that has a many to many relationship to `directus_users` called `users`
Note, I called the foreign column `user`
Optionally to test with a role and a string field called `role` to the pivot table

Setup a different collection such as `registrations` with a M2O relationship with `groups`

Add users to groups and attach a group to a registration.

Create a role with the permissions above on the registrations Update and View

Now login with a user that has that role and try viewing and updating a registration.

### What version of Directus are you using?

9.0.0-rc.96

### What version of Node.js are you using?

16.4.0

### What database are you using?

mysql

### What browser are you using?

chrome

### What operating system are you using?

osx

### How are you deploying Directus?

Locally

**Comment by u12206050** [comment] 2021-10-14 15:36
It seems the `_and` condition as you use it doesn't match the $CURRENT_USER with the `role = admin` it just checks that ANY user is the `$CURRENT_USER` and that ANY user's role is `admin`

```
{
	"group": {
		"users": {
			"_and": [
				{
					"user": {
						"_eq": "$CURRENT_USER"
					}
				},
				{
					"role": {
						"_eq": "author"
					}
				}
			]
		}
	}
}
```

**Comment by Prochy20** [comment] 2021-10-20 17:11
Hey. I have almost the same behavior:

1) When I set in app I want to allow edit only for user who's ID is equal to $CURRENT_USER i get this in my DB:

`{"_and": [{"user_created": {"id": {"_eq": null}}}]}`

2) When I replace null in DB for $CURRENT_USER it still does not work (user is not allowed to edit)

This is what I set to DB
`{"_and": [{"user_created": {"id": {"_eq": "$CURRENT_USER"}}}]}`

I am using v9.0.0-rc.98

**Comment by Skywrath-Mage** [comment] 2021-10-20 23:39
> 1. When I set in app I want to allow edit only for user who's ID is equal to $CURRENT_USER i get this in my DB:

I think is not supported, because it's a dynamic value. 
https://github.com/directus/directus/discussions/2993

**Comment by Prochy20** [comment] 2021-10-21 06:47
@Skywrath-Mage It used to work in previous release. Now it does not :(

**Comment by joselcvarela** [comment] 2021-11-03 18:37
Hello @u12206050 
I am not able to reproduce this anymore. Maybe this is already fixed.

Also @valdeirpsr,
That seems to be fixed now:
https://github.com/directus/directus/blob/c298942a1da9142ca10bdfeb68f740aa688a1844/app/src/interfaces/_system/system-filter/input-component.vue#L114-L115

I am going to close it for now, but if you think this is still an issue we can reopen.

**Closed by joselcvarela** 2021-11-03 18:37 UTC
Labels: App, Bug
