### ISSUE TITLE
Dropdown select don't work correctly if choice values a numbers

### ISSUE THREAD

**Issue by massimans** [directus/directus#14062] opened 2022-06-23 13:06 UTC
### Describe the Bug

i updated a dropdown field with the api (huge list i didn't want to write by hand) where changed the interface and display choices, notice that the values are numbers.
```json
{
    "meta": {
        "options": {
            "choices": [
                {
                    "text": "Adrar",
                    "value": 1
                },
                {
                    "text": "Aïn Defla",
                    "value": 44
                }
                // there is more removed for clarity
            ]
        },
        "display_options": {
            "choices": [
                {
                    "text": "Adrar",
                    "value": 1
                },
                {
                    "text": "Aïn Defla",
                    "value": 44
                }
                // there is more removed for clarity
            ]
        }
    }
}
```
after that you can properly choose one of those options, but ones you save it the display and the interface can't retrieve the text representation ("Adrar" for example ) and display the numerical value (1in the example).
making the value string solved it completely
```json
{
    "meta": {
        "options": {
            "choices": [
                {
                    "text": "Adrar",
                    "value": "1"
                },
                {
                    "text": "Aïn Defla",
                    "value": "44"
                }
                // there is more removed for clarity
            ]
        },
        "display_options": {
            "choices": [
                {
                    "text": "Adrar",
                    "value": "1"
                },
                {
                    "text": "Aïn Defla",
                    "value": "44"
                }
                // there is more removed for clarity
            ]
        }
    }
}
```

### To Reproduce

juste update a dropdown select field with the example given above as the payload minus the comments

### Errors Shown

no error is shown

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

16.15.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-06-23 14:00
> i updated a dropdown field with the api

Hi! Would you mind sharing more detail on this process? Is it via a particular API client, what was the payload (particular important for the string vs number difference), what was the response of said request?

**Comment by azrikahar** [comment] 2022-06-24 12:04
Thanks for the additional info! I believe this turns out to be "by design", as your dropdown field _is_ created as `string` field, not `integer`, as seen in the type:

```js
{
    "data": {
        "collection": "order",
        "field": "wilaya",
        "type": "string", // <-- this is a string, not an integer field
        // rest of shared payload
    }
}

### When creating it as a string field, it is saved as a string on the database, hence `"1"` does not match `1` which is actually how the database should behave.

https://user-images.githubusercontent.com/42867097/175530157-0001a8ef-8505-42b0-a74d-1f46e15078fd.mp4

### When creating it as an integer field, it works as you were expecting.

https://user-images.githubusercontent.com/42867097/175530319-afcacc4b-66c9-40db-b02b-857fe74966c1.mp4

---

I'll close this as resolved now as I believe this turns out to not be an inherent bug, but rather a configuration that is different from the intended expectation. 👍

**Closed by azrikahar** 2022-06-24 12:04 UTC
Labels: Needs More Info

**Comment by massimans** [comment] 2022-06-24 12:44
my bad i didn't know the field was supposed to do strict comparison hence my confusion,thanks for your feedback

**Comment by azrikahar** [comment] 2022-06-24 13:12
No worries! Totally understand how this little difference wasn't apparent at first, even when I initially looked at it 😄
