### ISSUE TITLE
Files O2M: upload file not possible

### ISSUE THREAD

**Issue by stefanke** [directus/directus#2497] opened 2019-12-10 19:26 UTC
# Bug Report

## Steps to Reproduce

1. Go to Directus Demo Site, click on "Tickets", click on any entry, go down to "Attachments", click "Add New", upload any file from local disc either via drop-field or via Icon.  
2. Click on 'Save'
3. See error: "filename_disk: This value should not be blank. filename_download: This value should not be blank. uploaded_on: This value should not be blank." 
4. A new but empty line appears in the files menu, but if you click on it the modal window says "File preview can only be used on directus_files.".

## Expected Behavior
The file should be uploaded and a new line with the link should appear

## Actual Behavior
The file does not seem to be uploaded and therefore can not be displayed. But the link is created.

## Other Context & Screenshots
<img width="331" alt="Bildschirmfoto 2019-12-10 um 20 10 41" src="https://user-images.githubusercontent.com/15725888/70561524-e0d95e00-1b8a-11ea-9de9-0011cafb09c6.png">

This also happens on our local test-installation (Centos7/ version 8.2.0).

## Technical Details

- Device: Desktop
- OS: MacOS 10.14.6
- Web Server: Demo-Site
- PHP Version: Demo-Site
- Database: Demo-Site
- Directus Release Version: Demo-Site - 8.2.0
  - App Version: Demo-Site
  - API Version: Demo-Site
- Install Method: Demo-Site

**Comment by rijkvanzanten** [comment] 2019-12-10 19:44
Duplicate of https://github.com/directus/app/issues/2308

**Closed** 2019-12-10 19:44 UTC
Labels: duplicate
