### ISSUE TITLE
10.6.1 shows as 10.6.0 in Data Studio

### ISSUE THREAD

**Issue by BlackDahlia313** [directus/directus#19591] opened 2023-09-05 14:44 UTC
### Describe the Bug

Just redeployed to update my DB settings and did a fresh build. Running 10.6.1 but it shows as 10.6.0 in data studio.

### To Reproduce

Upgrade 10.6.0 to 10.6.1

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-09-05 14:46
Are you sure the image was updated properly? because my docker container does say `10.6.1` as expected 🤔 
![image](https://github.com/directus/directus/assets/9389634/29738c50-ae79-424d-8777-46c58a4f75a9)

**Comment by paescuj** [comment] 2023-09-06 07:47
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by paescuj** 2023-09-06 07:47 UTC
Labels: Needs More Info

**Comment by BlackDahlia313** [comment] 2023-09-07 12:43
> Oh, I hope you're feeling better now!
> 
> I guess it's using the cached `latest` image on DO so you might want to explicitly define the version in your `Dockerfile`:
> 
> ```dockerfile
> FROM directus/directus:10.6.1
> ```

Actually last night turned into cold sweats and fever. Im now starting to feel better.

Thats the first time DO ever did that. I'll reach out to them to see whats going on. Ill define it in the docker file this time and check.

**Comment by BlackDahlia313** [comment] 2023-09-07 21:27
> Oh, I hope you're feeling better now!
> 
> I guess it's using the cached `latest` image on DO so you might want to explicitly define the version in your `Dockerfile`:
> 
> ```dockerfile
> FROM directus/directus:10.6.1
> ```

well... this is gonna have to go to DO support. Ill report back. even after explicitly calling for 10.6.1 it still installs 10.6.

I'm honestly baffled

**Comment by BlackDahlia313** [comment] 2023-09-09 12:17
Well... DO support dug through the deployment logs and sure enough:

![image](https://github.com/directus/directus/assets/44903742/c6f11ec5-aad4-424e-8e2a-752d51e0f92a)

But still 10.6.0 is what deploys. 

They are still looking but wow haha. I'm at a loss

**Comment by paescuj** [comment] 2023-09-11 12:50
Okay, just to be sure, is there any proxy in between which could have cached or maybe even the browser cache that interferes?

**Comment by BlackDahlia313** [comment] 2023-09-11 12:55
> Okay, just to be sure, is there any proxy in between which could have cached or maybe even the browser cache that interferes?

As far a I am aware I don't think the app platform has one. I know they keep a node alive until the redeploy is finished. I have def deletd browser cache and tried a new browser as well. Even incognito.

I just sent them the build ids to look at the others one as well.

**Comment by BlackDahlia313** [comment] 2023-09-19 18:59
Thank you! After the lastest release, https://github.com/directus/directus/pull/19711 is working great for DO and updated properly.

**Comment by paescuj** [comment] 2023-09-19 19:01
> Thank you! After the latest release (10.6.2), #19711 is working great for DO and updated properly.

Great! 🎉 Thanks for your confirmation! ❤️
