### ISSUE TITLE
Local storage: Exception after upgrading docker image from 9.21.2 to 9.22.1

### ISSUE THREAD

**Issue by adminradio** [directus/directus#17037] opened 2023-01-06 15:07 UTC
### Describe the Bug

When we change directus image from 9.21.2 to 9.22.1 an exception is thrown. If we roll back to 9.21.2 everything is fine again.

Docker host is a Linux Debien 11 with docker 20.10.22 and docker compose plugin.

You'll find the anonymised `docker-compose.yml` here:
https://gist.github.com/adminradio/017272bae126e54b9658deb3a413da4f

This compose file is working perfectly fine, when we use `9.21.2` as `${DIRECTUS_IMAGE_VERSION}`.

### To Reproduce

1. install directus as docker container `v9.21.2` with a bind mounted local storage for `uploads` via `docker-compose.yml`
2. after first start bring down the stack and set docker image to `v9.22.1`
3. after starting the stack, an exception will be thrown

### Errors Shown

```
zwm-cms-dev-directus  | [14:42:01.593] INFO: Server started at http://0.0.0.0:8055
zwm-cms-dev-directus  | node:events:491
zwm-cms-dev-directus  |       throw er; // Unhandled 'error' event
zwm-cms-dev-directus  |       ^
zwm-cms-dev-directus  |
zwm-cms-dev-directus  | Error: ENOENT: no such file or directory, open '/directus/uploads/health-X1IaF'
zwm-cms-dev-directus  | Emitted 'error' event on ReadStream instance at:
zwm-cms-dev-directus  |     at emitErrorNT (node:internal/streams/destroy:151:8)
zwm-cms-dev-directus  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
zwm-cms-dev-directus  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
zwm-cms-dev-directus  |   errno: -2,
zwm-cms-dev-directus  |   code: 'ENOENT',
zwm-cms-dev-directus  |   syscall: 'open',
zwm-cms-dev-directus  |   path: '/directus/uploads/health-X1IaF'
zwm-cms-dev-directus  | }
zwm-cms-dev-directus  |
zwm-cms-dev-directus  | Node.js v18.12.1
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

postgis/postgis:14-3.3-alpine

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment] 2023-01-06 15:28
Duplicate of https://github.com/directus/directus/issues/16904 the PR just got merged and will be available with the next release.

**Closed by br41nslug** 2023-01-06 15:28 UTC
