### ISSUE TITLE
In a image field an svg file will show as unsupported.

### ISSUE THREAD

**Issue by VincentKempers** [directus/directus#23083] opened 2024-07-23 13:28 UTC
### Describe the Bug

When uploading a svg it will show up fine in the files table and will be showing up in the preview.
When you select or upload the svg to an image field in any collection. The preview ill say it's an unsupported image. While you can edit the svg image you can't see the preview as it claims to be unsupported. You can save this and it's retrieveable.

<img width="901" alt="image" src="https://github.com/user-attachments/assets/eed7af4a-ff9b-472a-8429-cf6b1e9a08c4">
<img width="991" alt="image" src="https://github.com/user-attachments/assets/2db104fd-6940-4b14-86fb-0c6e6efce6de">
<img width="2209" alt="image" src="https://github.com/user-attachments/assets/43f20466-9dba-4578-8fb1-4321d9dda78f">

### To Reproduce

- Have a simple SVG.
- Upload it to your directus instance.
- Have a collection with an image field.
- Select your svg file to your collection.
- The Image preview will say it's an unsupported file.
- When clicking the edit image you will see your svg is working fine.

This is quite confusing.

Test checkmark svg 👇🏽 
![check](https://github.com/user-attachments/assets/17aef8d6-115c-42cc-b874-1307dddaf96e)

### Directus Version

v10.13.0

### Hosting Strategy

Directus Cloud

### Database

Postgres 13

**Comment by paescuj** [comment] 2024-07-23 13:34
Duplicate of #22461

**Closed by paescuj** 2024-07-23 13:34 UTC

**Comment by rijkvanzanten** [comment] 2024-07-23 15:01
✅
