### ISSUE TITLE
Flow breaks if I try to return an array from a Run Script operation

### ISSUE THREAD

**Issue by smurflo2** [directus/directus#18840] opened 2023-06-07 23:11 UTC
### Describe the Bug

Just upgraded directus/directus from 9.23.4 to 10.2.1 and one of my flows broke in a weird way. The Flow A is triggered by Flow B. In the logs for Flow B it shows Flow A returning `{}`. Flow A does not include any logs from the call, it looks like it was just never called.

I dug deeper into flow A, basically short circuiting it and returning dummy data until I found where it broke. The problem operation seems to be a Run Script operation that tries to return an array inside of an object.

I simplified it down to this
```
module.exports = async function(data) {
	const text = {{ $trigger }}.text;

	// works...
	//const test = { text };

	// breaks the whole flow...
	//const emptyArray = [];
	//const test = { text, emptyArray };

	// breaks the whole flow...
	const someArray = [ 'hey' ];
	const test = { text, someArray };

	return test;
}
```

### To Reproduce

1. Create a flow with a manual trigger
2. Add a Run Script operation that looks like this
```
module.exports = async function(data) {
    const text = 'hello';

    const someArray = [ 'hey' ];
    const test = { text, someArray };

    return test;
}
```
3. Run the flow

When I do this I get
```
{
  "errors": [
    {
      "message": "[object Array] could not be cloned.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-06-08 06:13
Thanks for opening this issue! However this is a duplicate of an existing issue #18751, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #18751 has been fixed by #18777 which will be available with the next release.

**Closed by paescuj** 2023-06-08 06:13 UTC
