### ISSUE TITLE
Validation rules on "create" doesn't work across relation

### ISSUE THREAD

**Issue by adrianofoschi** [directus/directus#12600] opened 2022-04-06 11:22 UTC
### Describe the Bug

I defined a permission for "create" action on one collection.
The permission check the value of a related collection, it doesn't work on save it shows a validation error.

### To Reproduce

1. Create three collections:

- persona
- cliente
- scadenzario

2. Create these relations:

- a many to one relation "cliente" --> "persona"
- a many to one relation "scadenzario" ---> "persona"

![s0](https://user-images.githubusercontent.com/4822527/161963576-ac020dc9-daf8-4e7b-a813-23694fe59a82.png)

![s1](https://user-images.githubusercontent.com/4822527/161963396-b09c5ad7-0463-48b0-bc1f-a832bca996ac.png)

3. Create a group with permission rule on the "scadenzario" collecion.
The rule defines that the users of this group can create a "scadenzario" item where the person.client.id is equal to "somevalue".

![s2](https://user-images.githubusercontent.com/4822527/161963726-6ff8e5e5-a2fd-4093-9135-eeadaa50e503.png)

![s3](https://user-images.githubusercontent.com/4822527/161963742-898282f8-9d64-43f9-ae19-10202996d4ec.png)

4. Go to collection "scadenzario" and try to create a new item selecting a "persona".
It doesn't work, it shows a validation error on save on field "persona".

### Errors Shown

```
The following fields contain invalid values:
    Persona: validationError.undefined
```

![s4](https://user-images.githubusercontent.com/4822527/161963776-c0f849e0-65ae-4e82-8288-1bf82cca56da.png)

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### How are you deploying Directus?

docker-compose

**Comment by azrikahar** [comment] 2022-04-06 11:27
Thanks for opening this issue! However this is a duplicate of an existing issue #11775, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #11775 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-06 11:27 UTC
Labels: Bug (Potential)
