### ISSUE TITLE
Interface Display Template not showing correctly for new entries in "Many to Many" fields

### ISSUE THREAD

**Issue by radiowavesurfer** [directus/directus#7984] opened 2021-09-12 17:45 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When using a display template to show fields from the related record, some fields don't display any value until the record has been saved.

### To Reproduce

Here is the simplest set of collections that I can come up with to reproduce the issue. The basic idea is that a user wants to create an "order", the order consists of multiple "order_items", and each order item contains a product and a quantity.

- Collection: products
  - id - auto-incrementing integer
  - product_name - standard field, string

- Collection: order_items
  - id - auto-incrementing integer
  - product - many-to-one, related to products.id
  - qty - standard field, float

- Collection: orders
  - id - auto-incrementing integer
  - items - many-to-many, related to order_items.id (via auto-created junction table)
    - In the interface tab, a display template of: "qty - product_name" (as shown in screenshot below)

![1 items display template](https://user-images.githubusercontent.com/1526443/132997096-ee70a554-aa3f-499e-ac24-6c3b77e0afed.png)

The products collection needs to be populated with some items. In mine, I've created a product called "Notebook".

User steps:

1. User browses to the Orders collection, and clicks "Create Item" button.
2. User clicks "Create New" button to add an "order_item" to their order.
3. User chooses a product, and sets a quantity. (Screenshot below.)
![2 Creating order line](https://user-images.githubusercontent.com/1526443/132997168-a5d3442a-34a1-446e-bff1-e830a04afa05.png)

4. User clicks Save.

**Problem:** Now user is back at the screen "Creating Item  in Orders", but the display template for the newly added item doesn't show the product name. (Screenshot below, underlined in red.)
![3 Creating item incorrect display](https://user-images.githubusercontent.com/1526443/132997233-3450ee48-0c4d-44b3-82d4-36418f8ea9db.png)

5. If the user saves this record, returns to the list of orders, and then goes back to edit the order, **then** it displays correctly. (Screenshot below, underlined in green.)
![4 Editing items correct display](https://user-images.githubusercontent.com/1526443/132997287-4c1a4095-8d78-4dbc-ae07-5127c4fea782.png)

Thanks.

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

14.17.6

### What database are you using?

Postgres 12

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

"npx create-directus-project" inside of Ubuntu 20.04 LXC container.

**Comment by rijkvanzanten** [comment] 2021-09-13 16:44
Duplicate of https://github.com/directus/directus/issues/6293

**Closed by rijkvanzanten** 2021-09-13 16:44 UTC
Labels: Bug (Potential)
