### ISSUE TITLE
Bug: Unable to navigate away from Details page, in one of the Collections

### ISSUE THREAD

**Issue by arladmin** [directus/directus#7961] opened 2021-09-10 03:07 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When editing/viewing details of a record, it is not possible to navigate away from the page, in all the case:
- editing & saving 
- editing & not-saving
- not-editing and trying to go back

An unnecessary prompt appears that then doesn't even function properly.
![image](https://user-images.githubusercontent.com/64059154/132792697-9a269cf5-9d0c-4cd5-a001-4ba016f57287.png)

Note: No error is shown in the console either. Also, all required fields have data in them.

How to figure out what's the issue?

### To Reproduce

These are the details of theat particular collection:
```
{
  "collection": "emails",
  "meta": {
    "collection": "emails",
    "icon": "mail",
    "note": null,
    "display_template": "{{message_id}}",
    "hidden": false,
    "singleton": false,
    "translations": null,
    "archive_field": null,
    "archive_app_filter": true,
    "archive_value": null,
    "unarchive_value": null,
    "sort_field": null,
    "accountability": "all",
    "color": null,
    "item_duplication_fields": null,
    "item_count": null
  },
  "schema": {
    "name": "emails",
    "schema": "public",
    "comment": null
  }
}
```

The fields in this collection:

```
[
  {
    "collection": "emails",
    "field": "id",
    "type": "integer",
    "schema": {
      "name": "id",
      "table": "emails",
      "data_type": "integer",
      "default_value": "nextval('emails_id_seq'::regclass)",
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": 32,
      "numeric_scale": 0,
      "is_generated": false,
      "is_nullable": false,
      "is_unique": true,
      "is_primary_key": true,
      "has_auto_increment": true,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 1,
      "collection": "emails",
      "field": "id",
      "special": null,
      "interface": "input",
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "user_created",
    "type": "uuid",
    "schema": {
      "name": "user_created",
      "table": "emails",
      "data_type": "uuid",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": "public",
      "foreign_key_table": "directus_users",
      "foreign_key_column": "id"
    },
    "meta": {
      "id": 2,
      "collection": "emails",
      "field": "user_created",
      "special": [
        "user-created"
      ],
      "interface": "select-dropdown-m2o",
      "options": {
        "template": "{{avatar.$thumbnail}} {{first_name}} {{last_name}}"
      },
      "display": "user",
      "display_options": null,
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "half",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "date_created",
    "type": "timestamp",
    "schema": {
      "name": "date_created",
      "table": "emails",
      "data_type": "timestamp with time zone",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 3,
      "collection": "emails",
      "field": "date_created",
      "special": [
        "date-created"
      ],
      "interface": "datetime",
      "options": null,
      "display": "datetime",
      "display_options": {
        "relative": true
      },
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "half",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "user_updated",
    "type": "uuid",
    "schema": {
      "name": "user_updated",
      "table": "emails",
      "data_type": "uuid",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": "public",
      "foreign_key_table": "directus_users",
      "foreign_key_column": "id"
    },
    "meta": {
      "id": 4,
      "collection": "emails",
      "field": "user_updated",
      "special": [
        "user-updated"
      ],
      "interface": "select-dropdown-m2o",
      "options": {
        "template": "{{avatar.$thumbnail}} {{first_name}} {{last_name}}"
      },
      "display": "user",
      "display_options": null,
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "half",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "date_updated",
    "type": "timestamp",
    "schema": {
      "name": "date_updated",
      "table": "emails",
      "data_type": "timestamp with time zone",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 5,
      "collection": "emails",
      "field": "date_updated",
      "special": [
        "date-updated"
      ],
      "interface": "datetime",
      "options": null,
      "display": "datetime",
      "display_options": {
        "relative": true
      },
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "half",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "account",
    "type": "integer",
    "schema": {
      "name": "account",
      "table": "emails",
      "data_type": "integer",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": 32,
      "numeric_scale": 0,
      "is_generated": false,
      "is_nullable": false,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": "public",
      "foreign_key_table": "accounts",
      "foreign_key_column": "id"
    },
    "meta": {
      "id": 24,
      "collection": "emails",
      "field": "account",
      "special": null,
      "interface": "select-dropdown-m2o",
      "options": {
        "template": "{{email_address}}"
      },
      "display": "related-values",
      "display_options": {
        "template": "{{email_address}}"
      },
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "headers",
    "type": "json",
    "schema": {
      "name": "headers",
      "table": "emails",
      "data_type": "json",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 46,
      "collection": "emails",
      "field": "headers",
      "special": [
        "json"
      ],
      "interface": null,
      "options": null,
      "display": "raw",
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "body",
    "type": "json",
    "schema": {
      "name": "body",
      "table": "emails",
      "data_type": "json",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 47,
      "collection": "emails",
      "field": "body",
      "special": [
        "json"
      ],
      "interface": null,
      "options": null,
      "display": "raw",
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "priority",
    "type": "integer",
    "schema": {
      "name": "priority",
      "table": "emails",
      "data_type": "integer",
      "default_value": 1,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": 32,
      "numeric_scale": 0,
      "is_generated": false,
      "is_nullable": false,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 83,
      "collection": "emails",
      "field": "priority",
      "special": null,
      "interface": "input",
      "options": {
        "min": "1",
        "max": "5"
      },
      "display": "rating",
      "display_options": {
        "simple": true
      },
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "date",
    "type": "timestamp",
    "schema": {
      "name": "date",
      "table": "emails",
      "data_type": "timestamp with time zone",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 84,
      "collection": "emails",
      "field": "date",
      "special": null,
      "interface": "datetime",
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "path",
    "type": "string",
    "schema": {
      "name": "path",
      "table": "emails",
      "data_type": "character varying",
      "default_value": null,
      "generation_expression": null,
      "max_length": 255,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 85,
      "collection": "emails",
      "field": "path",
      "special": null,
      "interface": null,
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "message_id",
    "type": "string",
    "schema": {
      "name": "message_id",
      "table": "emails",
      "data_type": "character varying",
      "default_value": null,
      "generation_expression": null,
      "max_length": 255,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": true,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 86,
      "collection": "emails",
      "field": "message_id",
      "special": null,
      "interface": null,
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "size",
    "type": "bigInteger",
    "schema": {
      "name": "size",
      "table": "emails",
      "data_type": "bigint",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": 64,
      "numeric_scale": 0,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 87,
      "collection": "emails",
      "field": "size",
      "special": null,
      "interface": null,
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "subject",
    "type": "string",
    "schema": {
      "name": "subject",
      "table": "emails",
      "data_type": "character varying",
      "default_value": null,
      "generation_expression": null,
      "max_length": 255,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 88,
      "collection": "emails",
      "field": "subject",
      "special": null,
      "interface": null,
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "has_attachments",
    "type": "boolean",
    "schema": {
      "name": "has_attachments",
      "table": "emails",
      "data_type": "boolean",
      "default_value": false,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": false,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 89,
      "collection": "emails",
      "field": "has_attachments",
      "special": [
        "boolean"
      ],
      "interface": null,
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "html",
    "type": "text",
    "schema": {
      "name": "html",
      "table": "emails",
      "data_type": "text",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 135,
      "collection": "emails",
      "field": "html",
      "special": null,
      "interface": "input-rich-text-html",
      "options": {
        "toolbar": [
          "bold",
          "italic",
          "underline",
          "removeformat",
          "customLink",
          "bullist",
          "numlist",
          "blockquote",
          "h1",
          "h2",
          "h3",
          "customImage",
          "customMedia",
          "hr",
          "code",
          "fullscreen",
          "strikethrough",
          "superscript",
          "subscript",
          "aligncenter",
          "alignjustify",
          "alignleft",
          "alignnone",
          "alignright",
          "forecolor",
          "backcolor",
          "h4",
          "h5",
          "h6",
          "indent",
          "outdent",
          "table"
        ]
      },
      "display": null,
      "display_options": null,
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": true
    }
  },
  {
    "collection": "emails",
    "field": "plain",
    "type": "text",
    "schema": {
      "name": "plain",
      "table": "emails",
      "data_type": "text",
      "default_value": null,
      "generation_expression": null,
      "max_length": null,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 136,
      "collection": "emails",
      "field": "plain",
      "special": null,
      "interface": null,
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": true
    }
  },
  {
    "collection": "emails",
    "field": "labels",
    "type": "csv",
    "schema": {
      "name": "labels",
      "table": "emails",
      "data_type": "character varying",
      "default_value": null,
      "generation_expression": null,
      "max_length": 255,
      "numeric_precision": null,
      "numeric_scale": null,
      "is_generated": false,
      "is_nullable": true,
      "is_unique": false,
      "is_primary_key": false,
      "has_auto_increment": false,
      "comment": null,
      "schema": "public",
      "foreign_key_schema": null,
      "foreign_key_table": null,
      "foreign_key_column": null
    },
    "meta": {
      "id": 137,
      "collection": "emails",
      "field": "labels",
      "special": [
        "csv"
      ],
      "interface": null,
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": true,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "tags",
    "type": "m2m",
    "schema": null,
    "meta": {
      "id": 36,
      "collection": "emails",
      "field": "tags",
      "special": [
        "m2m"
      ],
      "interface": "list-m2m",
      "options": {
        "template": "{{tags_id.title}}"
      },
      "display": "related-values",
      "display_options": {
        "template": "{{tags_id.title}}"
      },
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "contact",
    "type": "m2m",
    "schema": null,
    "meta": {
      "id": 55,
      "collection": "emails",
      "field": "contact",
      "special": [
        "m2m"
      ],
      "interface": "list-m2m",
      "options": null,
      "display": null,
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  },
  {
    "collection": "emails",
    "field": "attachments",
    "type": "files",
    "schema": null,
    "meta": {
      "id": 146,
      "collection": "emails",
      "field": "attachments",
      "special": [
        "files"
      ],
      "interface": "list-m2m",
      "options": {
        "template": "{{directus_files_id.title}}"
      },
      "display": "raw",
      "display_options": null,
      "readonly": false,
      "hidden": false,
      "sort": null,
      "width": "full",
      "group": null,
      "translations": null,
      "note": null,
      "conditions": null,
      "required": false
    }
  }
]
```

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by arladmin** [comment] 2021-09-10 04:14
Upon inspecting the network tab in the browser's Developer tools, i noticed that when i'm on the Details page of an Email item, and i click on any of the other collections in the Sidebar, the corresponding network request just doesn't get made.

**Comment by domdus** [comment] 2021-09-10 06:17
Hi, this sounds very related to #6957.

**Comment by rijkvanzanten** [comment] 2021-09-10 12:22
Duplicate of https://github.com/directus/directus/issues/6957

**Closed** 2021-09-17 15:41 UTC
Labels: Duplicate
