### ISSUE TITLE
Deep not working

### ISSUE THREAD

**Issue by abasse** [directus/directus#4788] opened 2021-03-31 19:09 UTC
Hi,

I have two tables, a table with products(product) and a table with countries(country). Each product can have one country assigned. When I try to filter all products from a particular country, **the deep query/filter returns all entries.** The only difference is, that the "matched" products shows the country name, all other products show null for the country.

**Query string:**
`http://localhost:8055/items/products/?fields=name,country.name&deep[country][_filter][name][_eq]=Italy`

**Result:**
` {"data":[{"name":"Tesla Model X","country":null},
{"name":"Skoda Kodiaq","country":null},
{"name":"Riva","country":{"name":"Italy"}},
{"name":"BMW R NineT","country":null}]}`

----

_For reference, all entries:
` {"data":[{"name":"Tesla Model X","country":{"name":"USA"}},{"name":"Skoda Kodiaq","country":{"name":"Czech Republic"}},{"name":"Riva","country":{"name":"Italy"}},{"name":"BMW R NineT","country":{"name":"Germany"}}]}`_

Directus:
v9.0.0-rc.53

**Comment by rijkvanzanten** [comment] 2021-03-31 19:31
Just to be clear, you're trying to filter `products` based on the nested country right? Not filter the nested related countries themselves?

If so, use `filter[country][name][_eq]=Italy` 🙂

**Comment by abasse** [comment] 2021-04-01 06:52
Here is the relationship:
![image](https://user-images.githubusercontent.com/3475978/113254716-39c08e80-92c7-11eb-881a-213a7bee1787.png)

So name field is in the country collection, a country is linked via the id to the product. - My underastanding was I need to use the deep filter to filter on country, which than filter the product related to the country.

Your suggestion:
`http://localhost:8055/items/products/?fields=name,country.name&filter[country][name][_eg]=Italy`

returns all products:
`{"data":[{"name":"Tesla Model X","country":{"name":"USA"}},{"name":"Skoda Kodiaq","country":{"name":"Czech Republic"}},{"name":"Riva","country":{"name":"Italy"}},{"name":"BMW R NineT","country":{"name":"Germany"}}]}`

**Comment by rijkvanzanten** [comment] 2021-04-27 21:38
<img width="891" alt="CleanShot 2021-04-27 at 17 37 33@2x" src="https://user-images.githubusercontent.com/9141017/116315969-4bd70500-a77f-11eb-8faa-b653b8ac701d.png">

<img width="968" alt="CleanShot 2021-04-27 at 17 37 50@2x" src="https://user-images.githubusercontent.com/9141017/116315973-4da0c880-a77f-11eb-8b23-78db9249f871.png">

I've reproduced your setup based on the description you gave, and everything seems to be working as expected. Can you try it on the latest version and confirm if it's still not working as expected?

**Comment by rijkvanzanten** [comment] 2021-04-27 21:38
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-04-27 21:38 UTC
Labels: Bug (Potential)
