### ISSUE TITLE
Token invalid

### ISSUE THREAD

**Issue by slavayssiere** [directus/directus#5250] opened 2021-04-26 11:52 UTC
Since go to rc60, I cannot connect to my Directus.

I try with a Google Login and with Directus admin user.

Display is "{
  "errors": [
    {
      "message": "Token invalid.",
      "extensions": {
        "code": "INVALID_CREDENTIALS"
      }
    }
  ]
}"

In the log I find : 

11:47:45 ✨ request completed GET 302 /auth/oauth/google/callback?code=***&scope=email%20https://www.googleapis.com/auth/userinfo.email%20openid&authuser=1&hd=s***&prompt=none 34ms
11:47:45 ✨ request completed GET 302 /?error=**Grant%3A%20missing%20session%20or%20misconfigured%20provider** 1ms
11:47:45 ✨ request completed GET 304 /admin 1ms
11:47:45 ✨ request completed GET 304 /admin/css/chunk-vendors.2b987c5b.css 1ms
11:47:45 ✨ request completed GET 304 /admin/js/chunk-vendors.ec007636.js 1ms
11:47:45 ✨ request completed GET 304 /admin/js/interface-wysiwyg.fab4dcd8.js 1ms
11:47:45 ✨ request completed GET 304 /admin/manifest.webmanifest 1ms
11:47:45 ✨ request completed GET 304 /admin/js/markdown.acb1f1ae.js 1ms

To configure my provider I have 4 env var : 

- OAUTH_PROVIDERS 'google'
- OAUTH_GOOGLE_SCOPE 'openid email'
- OAUTH_GOOGLE_KEY
- OAUTH_GOOGLE_SECRET

No change except rc59 to rc60.

It seems to be a Directus Token issue ?

**Comment by slavayssiere** [comment] 2021-04-26 12:34
I temporary solve this issue : I decrease the replica number of directus to one.

Directus doesn't scalable righ now on v9 ?

**Comment by rijkvanzanten** [comment] 2021-04-26 14:40
Duplicate of https://github.com/directus/directus/issues/3814

**Closed by rijkvanzanten** 2021-04-26 14:40 UTC
