### ISSUE TITLE
M2M relation table showing empty labels

### ISSUE THREAD

**Issue by EFJunior** [directus/directus#17559] opened 2023-02-16 17:28 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

The M2M interface is showing empty labels when adding new items to the list.

### To Reproduce

- Create 3 collections: articles, destinations and articles_destinatiosn.
- In the destinations collection, create a string field called name.
- Create one item in the destinations collections with name "Europe".
- In the articles_destinations collection create the two many-to-one fields as follows:

<img width="819" alt="image" src="https://user-images.githubusercontent.com/13688152/219427523-9b28d178-7456-44d2-8664-25fc175c7de1.png">

<img width="828" alt="image" src="https://user-images.githubusercontent.com/13688152/219427816-a84faef2-9582-4620-9791-93686cf2a427.png">

- In the articles collection, create a one-to-many field calles "destinations" as follows:
 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/13688152/219428954-074a091e-3f29-4698-a3cb-473b6e548ca3.png">

- Set the interface of the "destinations" field created in the previous step to show the destination name as follows:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/13688152/219429795-3b528482-a01d-495c-9c5f-c6643f70b85f.png">

- Try to create an item in the Article collection, and check that when selecting a destination in the relationship, the label in the list will be "--" as shown in the video:

https://user-images.githubusercontent.com/13688152/219442202-3d653cc5-5e26-4c4a-a1e7-1c76685d9c8d.mov

"

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-02-16 21:54
Thanks for opening this issue! However this is a duplicate of an existing issue #10647, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #10647 for future updates.

**Comment by EFJunior** [comment] 2023-02-17 09:28
The issue #10647 theoretically was fixed on https://github.com/directus/directus/pull/15549. So It seems to be another problem.

**Comment by paescuj** [comment] 2023-02-17 09:37
> The issue #10647 theoretically was fixed on #15549. So It seems to be another problem.

That's right but it hasn't been released yet.

**Comment by EFJunior** [comment] 2023-02-17 10:03
But the fix is in main branch, the one I used to reproduce the error.
I'm currently on commit #c2082867

**Comment by paescuj** [comment] 2023-02-17 10:17
> But the fix is already merged to the main branch, the one I used to reproduce the error. I'm currently on commit #c2082867

I see, thanks! In that case it indeed seems like another problem.

**Comment by EFJunior** [comment] 2023-02-28 15:00
Just to manage expectations: Does the possibility of checking this issue in the close future exists ?

**Comment by paescuj** [comment] 2023-02-28 15:37
This has been added to our backlog but you have to understand that we can not give an exact time frame. For that I'd like to refer to our standard answer:

> [Unfortunately, we can not provide estimates on features or fixes](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍

**Comment by Nitwel** [comment] 2023-03-17 13:55
This is not a bug but just a side effect on how you configured your data model.
The name can't be initially fetched as it doesn't exist in the local changes, as you're selecting an existing item from destinations. We also can't fetch it from the api as the junction item in `articles_destinations` doesn't exist yet on the api side.

The proper way to implement this schema would be to use the m2m relational interface. Is there a reason why you didn't use that interface?

**Closed by Nitwel** 2023-03-17 13:55 UTC
Labels: App, Won't Fix

**Comment by EFJunior** [comment] 2023-03-19 09:57
@Nitwel I just simplified in the example, but in the articles_destinations table, I have a "is_primary" boolean column. And if i use the m2m interface, I wouldn't be able to set that field when creating an article because when I click the "create new" form button in the m2m interface, it shows as if I wanted to create a new destination and not an article_destination.

**Comment by EFJunior** [comment] 2023-03-27 15:28
@Nitwel ?

**Comment by EFJunior** [comment] 2023-04-10 11:49
That's the reason @Nitwel
