### ISSUE TITLE
SDK fields use * wildcards and filter M2M relationships, ts reports an error

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#20210] opened 2023-10-26 22:14 UTC
### Describe the Bug

```
TS2322: Type
{   posts_categories: {     name: {       _eq: string;     };   }; }
is not assignable to type
WrapRelationalFilters<Merge<{ id?: FilterOperators<number> | undefined; post?: WrapRelationalFilters<Merge<{ id?: FilterOperators<string> | undefined; status?: FilterOperators<"published" | "draft" | "archived"> | undefined; ... 19 more ...; categories_count?: FilterOperators<...> | undefined; } | undefined, {}, { ....
Type
{   posts_categories: {     name: {       _eq: string;     };   }; }
is missing the following properties from type
Merge<{ id?: FilterOperators<number> | undefined; post?: WrapRelationalFilters<Merge<{ id?: FilterOperators<string> | undefined; status?: FilterOperators<"published" | "draft" | "archived"> | undefined; ... 19 more ...; categories_count?: FilterOperators<...> | undefined; } | undefined, {}, { ...; } | undefined, {}>...
:  id, post 
```

```
TS2820: Type  'categories.*'  is not assignable to type
'*' | keyof Posts | QueryFieldsRelational<AppSchema, Posts> | 'count(categories)'
```
![image](https://github.com/directus/directus/assets/8030134/fb89d407-0c65-4d39-9ae5-6090920a2eee)

### To Reproduce

``` ts
import { createDirectus, rest, readItems } from "@directus/sdk"

const client = createDirectus<AppSchema>("/").with(rest())
const results = await client.request(
  readItems("posts", {
    filter: {
      categories: {
        posts_categories: {
          name: {
            _eq: "test",
          },
        },
      },
    },
    fields: ["id", "categories.*"],
  }),
)
```

### Directus Version

10.7.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2023-10-26 23:39
Regarding `filter`, this is a duplicate of #20147 which has been fixed in #20200 and will be available with the next release.

For the correct usage of `fields`, see https://docs.directus.io/guides/sdk/getting-started.html#read-nested-fields.

**Closed by paescuj** 2023-10-26 23:39 UTC

**Comment by cdwmhcc** [comment] 2023-10-26 23:43
> Regarding `filter`, this is a duplicate of #20147 which has been fixed in #20200 and will be available with the next release.
> 
> For the correct usage of `fields`, see https://docs.directus.io/guides/sdk/getting-started.html#read-nested-fields.

I had applied the fix #20200 locally before I submitted the issue, and it only fixed the filters required issues.

**Comment by paescuj** [comment] 2023-10-26 23:46
> For the correct usage of `fields`, see https://docs.directus.io/guides/sdk/getting-started.html#read-nested-fields.

😃

**Comment by cdwmhcc** [comment] 2023-10-27 00:07
> > For the correct usage of `fields`, see https://docs.directus.io/guides/sdk/getting-started.html#read-nested-fields.
> 
> 😃

The example in the document works, and I have always used it this way, but it feels a bit disconnected from the API: https://docs.directus.io/reference/query.html#fields

I applied the fix from #20200 and it did fix the required errors for filters, but filters M2M relationships still reported errors.In addition to reporting errors, it also fails to correctly type-hint

``` ts
import { createDirectus, rest, readItems } from "@/packages/sdk"

const client = createDirectus<AppSchema>("/").with(rest())
const results = await client.request(
  readItems("posts", {
    filter: {
      categories: {
        posts_categories: {
          ???
        },
      },
    },
    fields: ["id", "title"],
  }),
)
```

![image](https://github.com/directus/directus/assets/8030134/4edda3a5-51cc-4544-bc20-0110d8978ee8)
![image](https://github.com/directus/directus/assets/8030134/726aea4b-a267-43f3-9d7e-2ef5e67767ba)


``` ts
export type AppSchema = {
  posts: Posts[];
  posts_categories: PostsCategories[];
  posts_middle_categories: PostsMiddleCategories[];
};

export type Posts = {
  id: string;
  status: "published" | "draft" | "archived";
  sort?: number;
  date_created?: string;
  date_updated?: string;
  title?: string;
  description?: string;
  tags?: string[];
  slug?: string;
  subtitle?: string;
  content?: string;
  icon?: Files;
  categories: PostsMiddleCategories[];
  categories_count: number;
}

export type PostsMiddleCategories = {
  id: number;
  post?: Posts;
  posts_categories?: PostsCategories;
}

export type PostsCategories = {
  id: number;
  sort?: number;
  name?: string;
  alias?: string;
  parent?: PostsCategories;
  children: PostsCategories[];
  children_count: number;
  posts: PostsMiddleCategories[];
  posts_count: number;
}
```

![image](https://github.com/directus/directus/assets/8030134/26aa332c-f850-4dfb-9be3-8ff9a450b697)

**Comment by stx-chris** [comment] 2023-11-10 09:18
We have version `10.7.2` and I just made the following observations:

**Working**
`readItems` with nested fields filter criteria `fields: ["id", "nested.name"]`, although against the SDK spec.

**Not working**
- `readItem` with nested fields filter criteria `fields: ["id", "nested.name"]`, although against the SDK spec.
- `readItems` with nested fields filter criteria `fields: ["id", {nested: ["name"]}]`, although **according** to SDK spec.
- `readItem` with nested fields filter criteria `fields: ["id", {nested: ["name"]}]`, although **according** to SDK spec.

Our current workaround with fields filter is to always use `readItems` and dot notation until this gets resolved.

**Comment by paescuj** [comment] 2023-11-10 09:23
> We have Directus version `10.7.2` with SDK `13.0.1` and I just made the following observations:
> 
> **Working** `readItems` with nested fields filter criteria `fields: ["id", "nested.name"]`, although against the SDK spec.
> 
> **Not working**
> 
>     * `readItem` with nested fields filter criteria `fields: ["id", "nested.name"]`, although against the SDK spec.
> 
>     * `readItems` with nested fields filter criteria `fields: ["id", {nested: ["name"]}]`, although **according** to SDK spec.
> 
>     * `readItem` with nested fields filter criteria `fields: ["id", {nested: ["name"]}]`, although **according** to SDK spec.
> 
> 
> Our current workaround with fields filter is to always use `readItems` and dot notation until this gets resolved.

If you feel like this is a bug, can you please open a new issue? Thank you!

**Comment by stx-chris** [comment] 2023-11-10 09:37
> > We have Directus version `10.7.2` with SDK `13.0.1` and I just made the following observations:
> > **Working** `readItems` with nested fields filter criteria `fields: ["id", "nested.name"]`, although against the SDK spec.
> > **Not working**
> > 
> > * `readItem` with nested fields filter criteria `fields: ["id", "nested.name"]`, although against the SDK spec.
> > * `readItems` with nested fields filter criteria `fields: ["id", {nested: ["name"]}]`, although **according** to SDK spec.
> > * `readItem` with nested fields filter criteria `fields: ["id", {nested: ["name"]}]`, although **according** to SDK spec.
> > 
> > Our current workaround with fields filter is to always use `readItems` and dot notation until this gets resolved.
> 
> If you feel like this is a bug, can you please open a new issue? Thank you!

never mind, turned out to be a permission issue. But since no error was returned, it seemed that it had to do with the recent fixes. On that note, if a nested field is specifically requested to which no permission is granted, why does the functions still return data but just leave out the nested field without failing?

**Comment by br41nslug** [comment] 2023-11-10 11:03
> why does the functions still return data but just leave out the nested field without failing?

Not sure what function you're referring to exactly but the API only returns the valid existing/readable fields as a security measure.

**Comment by stx-chris** [comment] 2023-11-10 11:24
My bad @br41nslug , by "functions" I meant `readItem`, `readItems`, `readUser` and the like. I totally get the security argument, but even in that case I had hoped for an indication to the caller that this requested field could not be retrieved. 

Right now there are three possible interpretations for lacking field data:
- this field does not exist
- you have no permission to this field
- a recent update in the SDK or Directus caused a lookup error

Debugging with the SDK has always been a challenge with server-side environments like Next.js, but a certain info like "This field is either not available or you lack permissions` to the console would reveal nothing about the field´s existence, yet would help fix development typos and permission issues. Maybe by enabling a `DEBUG` flag in the SDK somewhere?

**Comment by br41nslug** [comment] 2023-11-10 11:55
Development typo's are exactly what TS types are supposed to limit 🤔 And it should be very doable to verify if something is not matching your expectations on the API or an issue in the SDK by doing the same API call without the SDK.

> Maybe by enabling a DEBUG flag in the SDK somewhere?

Sounds like a good idea however the SDK is not aware of any of this currently so it is not something we can "enable" but rather a new feature to build. It should already be possible to write this function for your project that checks the requested fields versus the returned fields to catch errors in your development workflow :)
