### ISSUE TITLE
Context Menu of folders broken

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#15414] opened 2022-09-06 07:25 UTC
### Describe the Bug

Right click on folder throws an JS error: 
![image](https://user-images.githubusercontent.com/15796397/188572626-6ca58a78-55c3-4683-adb1-6bfa701f6327.png)

### To Reproduce

Go to file module (/admin/files) and try to right click on a folder.

### What version of Directus are you using?

9.17.0

### What version of Node.js are you using?

v14.19.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Linux VPS

**Comment by azrikahar** [comment] 2022-09-06 07:31
Duplicate of #15375, and this should be fixed in `9.17.1` by #15376 👍

**Closed by azrikahar** 2022-09-06 07:31 UTC
