### ISSUE TITLE
New pull of docker container fails to start

### ISSUE THREAD

**Issue by DieselTech** [directus/directus#19454] opened 2023-08-16 22:38 UTC
### Describe the Bug

First time running of the docker container fails to start. This is a brand new install and not an upgrade. 

```
[22:23:22.875] INFO: Initializing bootstrap...
[22:23:47.926] ERROR: Can't connect to the database.
[22:23:47.926] ERROR: SQLITE_CANTOPEN: unable to open database file
    err: {
      "type": "Error",
      "message": "SQLITE_CANTOPEN: unable to open database file",
      "stack":
          Error: SQLITE_CANTOPEN: unable to open database file
      "errno": 14,
      "code": "SQLITE_CANTOPEN"
    }
```

I followed the compose file provided in the [quickstart](https://docs.directus.io/self-hosted/quickstart.html)

My own compose looks like:

```compose
version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - /volume1/Docker/container-data/directus/database:/directus/database
      - /volume1/Docker/container-data/directus/uploads:/directus/uploads
    environment:
      KEY: 'fcdde1a6-3c7a-11ee-be56-0242ac120002'
      SECRET: '5fce32e1-374f-4ef4-8986-11405b428898'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: true
```

As you can see I'm using volume mounts so that it creates the files / folders as needed. Nothing existed previously. 

### To Reproduce

Fresh pull the container and attempt to run it. 

### Directus Version

directus/directus:latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-08-16 23:02
Thanks for opening this issue! However this is a duplicate of an existing issue #19156, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #19156 for future updates.

**Closed by paescuj** 2023-08-16 23:02 UTC
