### ISSUE TITLE
/lib64/libc.so.6: version 'GLIBC_2.25' not found

### ISSUE THREAD

**Issue by kroawen** [directus/directus#10066] opened 2021-11-26 02:10 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Just updated from9.1.1 to 9.1.2

OS: Centos 7.9
First run` npm update` to update, can auto update complete.
But when running npx directus bootstrap :
/lib64/libc.so.6: version `GLIBC_2.25' not found (required by ./../../node_modules/_argon2@0.28.3@argon2/lib/binding/napi-v3/argon2.node).

### To Reproduce

when I try to run ` npm rebuild argon2 --build-from-source` or `npm install argon2 --build-from-source`, it didn't work and get error:

  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
g++: error：unrecognized command line option ‘-std=c++17’
make: *** [Release/obj.target/argon2/src/argon2_node.o] 错误 1
make: 离开目录“/var/www/di9/node_modules/_argon2@0.28.3@argon2/build”
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Linux 3.10.0-1160.31.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/var/www/di9/node_modules/_argon2@0.28.3@argon2/lib/binding/napi-v3/argon2.node" "--module_name=argon2" "--module_path=/var/www/di9/node_modules/_argon2@0.28.3@argon2/lib/binding/napi-v3" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /var/www/di9/node_modules/_argon2@0.28.3@argon2
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/di9/node_modules/_argon2@0.28.3@argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/var/www/di9/node_modules/_argon2@0.28.3@argon2/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/di9/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 3.10.0-1160.31.1.el7.x86_64
node-pre-gyp ERR! command "/usr/local/bin/node" "/var/www/di9/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /var/www/di9/node_modules/_argon2@0.28.3@argon2
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.7
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/di9/node_modules/_argon2@0.28.3@argon2/lib/binding/napi-v3/argon2.node --module_name=argon2 --module_path=/var/www/di9/node_modules/_argon2@0.28.3@argon2/lib/binding/napi-v3 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.28.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.28.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

### What version of Directus are you using?

9.1.1 to 9.1.2

### What version of Node.js are you using?

14.15.1

### What database are you using?

10.3.23-MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

Centos 7.9

### How are you deploying Directus?

local

**Comment by azrikahar** [comment] 2021-11-26 02:21
Duplicate of #6071.

You can try the solution recommended here: https://github.com/directus/directus/issues/6071#issuecomment-922356209. Technically this is more so an issue with node argon2 and CentOS/RHEL rather than Directus itself, but hopefully the aforementioned solution works for you 👍

**Closed by azrikahar** 2021-11-26 02:21 UTC
Labels: Bug (Potential)
