### ISSUE TITLE
Impossible to build a custom operation.

### ISSUE THREAD

**Issue by CherniyIrtish** [directus/directus#18378] opened 2023-05-01 17:38 UTC
### Describe the Bug

After merge PR #18134 impossible to create custom operations with updated Docker image with package.json "type": "module".

### To Reproduce

After merge PR #18134
directus/package.json was added with "type": "module"
https://github.com/directus/directus/pull/18134/files#diff-c2668aac8694811789f9e136c83610f684984b9317c6050b29cc8fa0d6e28d30
We use Directus Docker image.
Based on docs we build custom operation with next command: "directus-extension build". Although` tsconfig.json` contains `"target": "ES2019"`  in the end we get dist folder with api.js file which includes "require" function. When I try to start server I have an error:

```
WARN: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/Users/com/Documents/workspace/coignite/directus-cms-extensions/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    err: {
      "type": "ReferenceError",
      "message": "require is not defined in ES module scope, you can use import instead\nThis file is being treated as an ES module because it has a '.js' file extension and '/Users/com/Documents/workspace/coignite/directus-cms-extensions/package.json' contains \"type\": \"module\". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.",
      "stack":
          ReferenceError: require is not defined in ES module scope, you can use import instead
          This file is being treated as an ES module because it has a '.js' file extension and '/Users/com/Documents/workspace/coignite/directus-cms-extensions/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
              at file:///Users/com/Documents/workspace/coignite/directus-cms-extensions/extensions/operations/test/api.js?t=1682961823442:2:15
              at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
              at async Promise.all (index 0)
              at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
              at async ExtensionManager.registerOperations (file:///Users/com/Documents/workspace/coignite/directus-cms-extensions/node_modules/@directus/api/dist/extensions.js:339:43)
              at async ExtensionManager.load (file:///Users/com/Documents/workspace/coignite/directus-cms-extensions/node_modules/@directus/api/dist/extensions.js:184:9)
              at async ExtensionManager.initialize (file:///Users/com/Documents/workspace/coignite/directus-cms-extensions/node_modules/@directus/api/dist/extensions.js:81:13)
              at async createCli (file:///Users/com/Documents/workspace/coignite/directus-cms-extensions/node_modules/@directus/api/dist/cli/index.js:21:5)
    }
```
Is it possible to build es modules with "directus-extension"?

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-05-01 23:01
Thanks for opening this issue! However this is a duplicate of an existing issue #18285, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. 
There's also a pending pull request (#18351) which adds support to the extensions SDK for building API extensions to ESM.

**Closed by paescuj** 2023-05-01 23:01 UTC
