### ISSUE TITLE
Docker: error when running migrations with rc95

### ISSUE THREAD

**Issue by bcartier** [directus/directus#8390] opened 2021-09-28 14:17 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Ran into a problem deploying rc95 via docker. Here's the error message:

13:45:11 ✨ Initializing bootstrap...
13:45:11 ✨ Database already initialized, skipping install
13:45:11 ✨ Running migrations...
13:45:11 ✨ Applying Replace Fields Group...
Error: ER_DROP_INDEX_FK: Cannot drop index 'directus_fields_group_foreign': needed in a foreign key constraint
    at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/directus/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/directus/node_modules/mysql/lib/Connection.js:198:25)
    at /directus/node_modules/knex/lib/dialects/mysql/index.js:126:18
    at new Promise (<anonymous>)
    at Client_MySQL._query (/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)
    at executeQuery (/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
    at Client_MySQL.query (/directus/node_modules/knex/lib/client.js:134:12)
    at Runner.query (/directus/node_modules/knex/lib/execution/runner.js:130:36)
    at Runner.queryArray (/directus/node_modules/knex/lib/execution/runner.js:224:21)
    at ensureConnectionCallback (/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19) {
  code: 'ER_DROP_INDEX_FK',
  errno: 1553,
  sqlMessage: "Cannot drop index 'directus_fields_group_foreign': needed in a foreign key constraint",
  sqlState: 'HY000',
  index: 0,
  sql: 'alter table `directus_fields` drop `group`'
}

### To Reproduce

Have an rc94 project with field groups. Update to rc95 via Docker. Error occurs when running migrations. 

### What version of Directus are you using?

rc94 updating to rc95

### What version of Node.js are you using?

14.18

### What database are you using?

MySQL 

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker via Rancher

**Comment by rijkvanzanten** [comment] 2021-09-28 14:18
Duplicate of #8369

**Closed by rijkvanzanten** 2021-09-28 14:18 UTC
Labels: Bug (Potential)
