### ISSUE TITLE
Migrating from rc91 to rc100: Unknown character set: 'utf8mb4_general_ci'

### ISSUE THREAD

**Issue by justrealmilk** [directus/directus#9264] opened 2021-10-30 19:53 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Migrating from rc91 to rc100 leads to a database character set error

### To Reproduce

Migrate from rc91 to rc100

```yaml
  directus-...:
    container_name: directus-...
    image: directus/directus:latest
    restart: always
    ports:
      - 8055:8055
    volumes:
      - /...
    networks:
      - directus
    depends_on:
      - directus-cache
    environment:
      CACHE_SCHEMA: 'false'
      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: 20000
      # LOG_LEVEL: 'trace'

      DB_CLIENT: 'mysql'
      DB_HOST: '...'
      DB_PORT: '3306'
      DB_DATABASE: 'directus_tc01'
      DB_USER: 'directus'
      DB_PASSWORD: '...'
      DB_CHARSET: 'utf8mb4_general_ci'
```

I've tried various character sets. Directus tables use the collation `utf8mb4_0900_ai_ci` (which I've also tried). I have two other Directus containers running with the same config but I wisely left them on rc91 while attempting to test rc100.

### Errors Shown

19:47:51 ✨ Initializing bootstrap...
19:47:51 ✨ Database already initialized, skipping install
19:47:51 ✨ Running migrations...
19:47:51 ✨ Applying Add Insights...
Error: ER_UNKNOWN_CHARACTER_SET: Unknown character set: 'utf8mb4_general_ci'
    at Query.Sequence._packetToError (/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)

### What version of Directus are you using?

rc100

### What version of Node.js are you using?

14.17.3

### What database are you using?

MySQL 8.0.24

### What browser are you using?

-

### What operating system are you using?

Docker

### How are you deploying Directus?

Docker

**Comment by jaycammarano** [comment] 2021-10-30 19:54
seems related to this https://github.com/directus/directus/issues/9215

Can you try setting the DB_CHARSET environment variable to either latin1 or utf8mb4, restart your server and see which work ?

**Comment by azrikahar** [comment] 2021-10-31 06:35
Hi, would you mind trying their corresponding charset instead of collation and see how it goes?

If you're looking to try collation `utf8mb4_general_ci`, use `DB_CHARSET: 'utf8mb4' instead. 

Here's a reference of the charset - collation list: https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html

**Comment by justrealmilk** [comment] 2021-10-31 06:37
`DB_CHARSET: 'utf8mb4'` works - I just wish I understood why and why collations worked on previous versions

**Comment by azrikahar** [comment] 2021-10-31 07:00
@justrealmilk Thanks for confirming! Honestly I wondered the exact same thing over here with some investigation: https://github.com/directus/directus/issues/9097#issuecomment-953453360

I don't think we did any changes on Directus side of thing (I could be very wrong here), so this is indeed something weird.

With that said, I'll proceed to close this issue as it is technically solved, but hopefully we can get to the bottom of this over at that particular open issue.

**Closed by azrikahar** 2021-10-31 07:00 UTC
Labels: Needs More Info

**Comment by benhaynes** [comment] 2021-10-31 13:24
There seems to be a lot of confusion around character sets and collation, would it be possible to add a section into the docs around how this should be set, and acceptable values? Some guidance here might be useful.

**Comment by azrikahar** [comment] 2021-11-01 03:41
> There seems to be a lot of confusion around character sets and collation, would it be possible to add a section into the docs around how this should be set, and acceptable values? Some guidance here might be useful.

Unfortunately this seems to be caused by a recent update from the mysql package, since characters sets & collations both worked in the past as OP mentioned, as well as from what I recall @rijkvanzanten used to recommend to other users, hence the currently documentation using `UTF8_GENERAL_CI`.

With that said, if the fix can't be made over at the mysql package, then we'll definitely need to add this section to clarify the past behavior does not work anymore.
