### ISSUE TITLE
v9: Clicking into Recent Files results in nonfunctional Directus across two browsers

### ISSUE THREAD

**Issue by Brian-Myers-Bose** [directus/directus#4180] opened 2021-02-19 15:04 UTC
We have a Directus cloud test env setup by RS for v9.  I signed in on Chrome (Mac), went into my File Library, and noted the names of our files that had been moved over weren't accurate (which is beside the point).  Clicked on My Files and received no content, which is correct.  I'm not responsible for any of those files.  I clicked on Recent Files, and that's all she wrote
First result was the interface hanged.  Eventually, I received the "Page Unresponsive" popup.  Neither Exit Page or Wait will rescue the session.
No other actions are possible on the screen.  Killing the tab, opening another one, and coming back through various starting addresses go straight back to this state.
I switched to the Safari browser, logged in, and I'm right back to this state in Safari, though the interaction with the user is different.  Safari doesn't timeout to a Page Unresponsive screen.  Instead, the wheel next to our name just spins, and the content of the page just gives the left to right moving gradient for 6 file-like objects.

Once one gets into this state in one browser, Directus becomes nonfunctional across multiple browsers.

**Comment by rijkvanzanten** [comment] 2021-02-19 16:19
What version of Directus is this on?

**Comment by Brian-Myers-Bose** [comment] 2021-02-19 16:23
Whatever version guys set up for us at Bose to test out v9.  I'd attempt to discover it for you, but the interface isn't functional now

**Comment by rijkvanzanten** [comment] 2021-02-19 16:41
Duplicate of https://github.com/directus/directus/issues/3942

**Closed by rijkvanzanten** 2021-02-19 16:41 UTC
Labels: Needs More Info
