### ISSUE TITLE
Cannot apply Directus schema.yml file from Postgres schema

### ISSUE THREAD

**Issue by co2nunes** [directus/directus#19000] opened 2023-06-26 17:42 UTC
### Describe the Bug

Cannot apply Directus schema.yml file from Postgres schema database from development server to staging: 

```
$ node -v
v20.2.0
Docker: 
$ docker version
Client:
 Version:           20.10.23
 API version:       1.41
 Go version:        go1.19.8
 Git commit:        7155243
 Built:             Mon May  1 21:07:11 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.23
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       6051f14
  Built:            Wed Apr 19 00:00:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.5
  GitCommit:        f19387a6bec4944c770f7668ab51c4348d9c2f38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

Server EC2: uname -a
Linux eu-xxxx-.compute.internal amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Jun  6 00:47:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

Should you require more information, I'll be happy to assist you.

### To Reproduce

npx directus schema snapshot ./snapshot.yaml
git commit, push and pull on development
npx directus schema apply ./path/to/snapshot.yaml

error: 

````
ERROR: Cannot read properties of null (reading 'meta')
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of null (reading 'meta')",
      "stack":
          TypeError: Cannot read properties of null (reading 'meta')
              at filterCollectionsForCreation (file:///home//.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/api/dist/utils/apply-diff.js:101:43)
              at Array.filter (<anonymous>)
              at file:///home//.npm/_npx/ebcc468e2b0f2b61/node_modules/@directus/api/dist/utils/apply-diff.js:122:58
              at /home//.npm/_npx/ebcc468e2b0f2b61/node_modules/knex/lib/execution/transaction.js:221:22
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    }
````

### Directus Version

v10.3.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-06-28 10:57
Duplicate of https://github.com/directus/directus/issues/18774 this should have been fixed with the last release. Please update and check again, happy to re-open the issue if it persists

**Closed by br41nslug** 2023-06-28 10:57 UTC
