### ISSUE TITLE
I created collection but when i create collection inside fields i got this issues

### ISSUE THREAD

**Issue by raselmiazi** [directus/directus#22330] opened 2024-04-29 06:18 UTC
### Describe the Bug

 i got the error message
![image](https://github.com/directus/directus/assets/163228495/f65f2894-1288-4ceb-8a62-599ee7f4b4e5)

here is my code

```js
const client = createDirectus(process.env.DIRECTUS_HOST).with(rest());

// Collection schemas
const collectionSchemas = {
    "about_us": {
        meta: {
            collection: 'about_us',
            icon: 'supervised_user_circle',
            note: null,
            display_template: null,
            hidden: false,
            singleton: false,
            translations: null,
            archive_field: null,
            archive_app_filter: true,
            archive_value: null,
            unarchive_value: null,
            sort_field: null,
            accountability: 'all',
            color: null,
            item_duplication_fields: null,
            sort: null,
            group: null,
            collapse: 'open',
            preview_url: null,
            versioning: false
        },
        schema: {
            schema: 'public',
            name: 'about_us',
            comment: null,
            fields: {
                "id": "integer NOT NULL",
                "status": "character varying(255) DEFAULT 'draft'::character varying NOT NULL",
                "user_created": "uuid",
                "date_created": "timestamp with time zone",
                "user_updated": "uuid",
                "date_updated": "timestamp with time zone",
                "Page_name": "character varying(255)",
                "Browser_title": "character varying(255)",
                "Disclaimer": "boolean",
                "Sitemap": "boolean",
                "Page_URL": "character varying(255)",
                "Meta_description": "character varying(255)",
                "Keywords": "character varying(255)"
            }
        }
    },
    "ESG_info_page": {
        meta: {
            collection: 'ESG_info_page',
            icon: 'supervised_user_circle',
            note: null,
            display_template: null,
            hidden: false,
            singleton: false,
            translations: null,
            archive_field: null,
            archive_app_filter: true,
            archive_value: null,
            unarchive_value: null,
            sort_field: null,
            accountability: 'all',
            color: null,
            item_duplication_fields: null,
            sort: null,
            group: null,
            collapse: 'open',
            preview_url: null,
            versioning: false
        },
        schema: {
            schema: 'public',
            name: 'ESG_info_page',
            comment: null,
            fields: {
                "id": "integer NOT NULL",
                "status": "character varying(255) DEFAULT 'draft'::character varying NOT NULL",
                "user_created": "uuid",
                "date_created": "timestamp with time zone",
                "user_updated": "uuid",
                "date_updated": "timestamp with time zone",
                "Page_name": "character varying(255)",
                "Browser_title": "character varying(255)",
                "Disclaimer": "boolean",
                "Sitemap": "boolean",
                "Page_URL": "character varying(255)",
                "Meta_description": "character varying(255)",
                "Keywords": "character varying(255)"
            }
        }
    },
    "AMC_info_page": {
        meta: {
            collection: 'AMC_info_page',
            icon: 'supervised_user_circle',
            note: null,
            display_template: null,
            hidden: false,
            singleton: false,
            translations: null,
            archive_field: null,
            archive_app_filter: true,
            archive_value: null,
            unarchive_value: null,
            sort_field: null,
            accountability: 'all',
            color: null,
            item_duplication_fields: null,
            sort: null,
            group: null,
            collapse: 'open',
            preview_url: null,
            versioning: false
        },
        schema: {
            schema: 'public',
            name: 'AMC_info_page',
            comment: null,
            fields: {
                "id": "integer NOT NULL",
                "status": "character varying(255) DEFAULT 'draft'::character varying NOT NULL",
                "user_created": "uuid",
                "date_created": "timestamp with time zone",
                "user_updated": "uuid",
                "date_updated": "timestamp with time zone",
                "Page_name": "character varying(255)",
                "Browser_title": "character varying(255)",
                "Disclaimer": "boolean",
                "Sitemap": "boolean",
                "Page_URL": "character varying(255)",
                "Meta_description": "character varying(255)",
                "Keywords": "character varying(255)"
            }
        }
    }
};





// Create collections using Directus SDK

(async () => {
    try {
        for (const collectionName in collectionSchemas) {
            console.log(`Creating fields for collection ${collectionName}...`);
           
            // Extract fields for the collection
            const { schema } = collectionSchemas[collectionName];
            const fields = collectionSchemas[collectionName].schema.fields;
            console.log(fields);
            console.log(schema);
            await client.request(
                withToken(
                    process.env.ADMIN_TOKEN,
                    createCollection({
                        collection: collectionName,
                        schema: {
                            fields: schema.fields
                        },
                        meta: {
                            schema: schema
                        }
                    })
                )
            )

            // Iterate over each field and create it
            for (const fieldName in fields) {
                const fieldType = fields[fieldName];
                console.log(fieldName)

                // Create the field with the admin token
                await client.request(
                    withToken(
                        process.env.ADMIN_TOKEN,
                        createField({
                            field: fieldName,
                            type: fieldType,
                            // field_field: value,
                        })
                    )
                );

                // console.log(`Field ${fieldName} created successfully.`);
            }

            console.log(`All fields for collection ${collectionName} created successfully.`);
        }
    } catch (error) {
        console.error('Error creating fields:', error);
    }
})();
```

### To Reproduce

![image](https://github.com/directus/directus/assets/163228495/3150c63e-341c-4992-a8dc-213b1f4ec664)

### Directus Version

10.4.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-04-29 06:58
Before we have a look at this, can you please first trace down in what part of your code the error happens and which collection / field creation fails and the exact call you're making at that point? Having this information would go a long way of understanding this error.

**Comment by raselmiazi** [comment] 2024-04-29 07:51
This part i got error 
 await client.request(
                    withToken(
                        process.env.ADMIN_TOKEN,
                        createField({
                            field: fieldName,
                            type: fieldType,
                            // field_field: value,
                        })
                    )
                );

**Comment by hanneskuettner** [comment] 2024-04-29 08:01
Please have a look at the documentation of the `createFields` function. The first Parameter should be the `collectionName`. https://docs.directus.io/packages/@directus/sdk/rest/functions/createField.html
Let me know if that helps you. I'll close this issue now as it seems to be no bug in Directus itself, but rather in you're code. If you can I'd recommend switching to Typescript for your project, as that would have caught the error early on.

For future issues, please share as much information as you can upfront, such that the issue can either be reproduced as easily as possible, also include what you have tried so far and where the errors happen. This saves the time of maintainers and helps us move along as easily as possible. Thank you!

PS: You can format your code to look like code and be more easily readable by using the [code block](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) syntax.

**Closed by hanneskuettner** 2024-04-29 08:01 UTC
Labels: :detective: Needs More Info

**Comment by raselmiazi** [comment] 2024-04-29 08:29
Error creating field: {
  errors: [
    {
      message: "You don't have permission to access this.",
      extensions: [Object]
    }
  ],
