### ISSUE TITLE
Cannot upload content to Directus

### ISSUE THREAD

**Issue by jacob-cso** [directus/directus#20480] opened 2023-11-20 13:27 UTC
### Describe the Bug

{
  "stack": "g@https://admin.aiteachassist.com/admin/assets/index-6b4bef17.js:1:21648\n@https://admin.aiteachassist.com/admin/assets/index-6b4bef17.js:3:4416",
  "message": "Network Error",
  "name": "AxiosError",
  "code": "ERR_NETWORK",
  "config": {}
}

### To Reproduce

Add any type of image under file library. 

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-11-20 13:32
I am unable to reproduce this. Please elaborate on the setup/configuration for which this issue is occurring.
- Can you inspect the actual request in the browser to see what error is being returned?
- Have you set any configuration for files/assets?
- Any errors in the server logs?

Closing this for now as there is not enough information to triage but happy to re-open the issue when more information becomes available to reproduce this 😄

**Closed by br41nslug** 2023-11-20 13:32 UTC
