### ISSUE TITLE
Error whilst cropping

### ISSUE THREAD

**Issue by Slations** [directus/directus#4391] opened 2021-03-05 01:28 UTC
I was trying to crop and image using the built-in image editor and the following error keeps coming up when trying to save any idea of what's going on as I can't make much sense of this error :) 

```
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file e6383aba-9e38-4888-8e49-55349b6ef1e6.\n\nError code: undefined\nOriginal stack:\nTypeError: fs_1.promises.opendir is not a function\n    at LocalFileSystemStorage._flatDirIterator (/var/www/vhosts/domain.org.uk/cms.domain.org.uk/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:218:45)\n    at _flatDirIterator.next (<anonymous>)\n    at FilesService.<anonymous> (/var/www/vhosts/domain.org.uk/cms.domain.org.uk/node_modules/directus/dist/services/files.js:51:103)\n    at Generator.next (<anonymous>)\n    at fulfilled (/var/www/vhosts/domain.org.uk/cms.domain.org.uk/node_modules/directus/dist/services/files.js:5:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

---

### Project details
Directus Version: 9.0.0-rc.44
Environment: production
OS: Linux 5.4.0-52-generic
Node: 10.19.0

**Comment by rijkvanzanten** [comment] 2021-03-05 15:14
Different issue, but same cause:

Duplicate of https://github.com/directus/directus/issues/3998

**Closed by rijkvanzanten** 2021-03-05 15:14 UTC
Labels: Duplicate

**Comment by rijkvanzanten** [comment] 2021-03-05 15:16
I believe this might be solved by using a more recent version of Node (in this case v12.12+). I would recommend doing that anyways, seeing that Node v10 is no longer supported by either Directus or [the Node foundation](https://nodejs.org/en/about/releases/) starting in April 2021
