### ISSUE TITLE
Interface display in editting item mode

### ISSUE THREAD

**Issue by phuocson-cty** [directus/directus#22820] opened 2024-06-22 03:44 UTC
### Describe the Bug

Hi team,

I found this bug on version v10.12.1

The problem is in the editting mode of an item, the display of field is cropped (please see image attached for better explanation)
![image](https://github.com/directus/directus/assets/73568342/803072c4-2bb0-4ca2-b1a0-300cb9150ecd)

Please let me know if I configure something wrong here or it is a bug?

Thanks team

### To Reproduce

To reproduce this, first we need a relational field in a collection, then configure the interface display as the relational display.

### Directus Version

v10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by hanneskuettner** [comment] 2024-06-22 05:55
Duplicate of #22160

**Closed by hanneskuettner** 2024-06-22 05:55 UTC
