### ISSUE TITLE
Typing in translated field 'blurs' the input after every character written

### ISSUE THREAD

**Issue by avatarbabe** [directus/directus#9653] opened 2021-11-09 14:35 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [x] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When inputting a single character in a translated field, either a simple text field or the rich text editor, all the fields blink and I lose focus of the input. Resulting in that I can only type one character, then I need to click the field again to input another character. Fields that are not translated work fine. 

### To Reproduce

I just upgraded to 9.0.0, just go to any translated text-field and try typing something.

### Errors Shown

I don't see any error in the console when this happens, only when loading the item I get several of the following error:
`TypeError: Cannot read properties of null (reading 'deactivate')`

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14.15.1

### What database are you using?

MySQL 5.7.32

### What browser are you using?

Microsoft Edge (Chromium based version)

### What operating system are you using?

Linux 5.4.0-1031-azure

### How are you deploying Directus?

Azure, but happens locally aswell

**Comment by azrikahar** [comment] 2021-11-09 14:47
Duplicate of #9510.

> , only when loading the item I get several of the following error:
TypeError: Cannot read properties of null (reading 'deactivate')

This was a regression introduced in another unrelated PR (it's for navigation, not translations), but it's also being addressed by an open PR now 👍

**Closed by azrikahar** 2021-11-09 14:47 UTC
Labels: Bug (Potential)
