### ISSUE TITLE
No UI notice that a required translation field is empty

### ISSUE THREAD

**Issue by iksent** [directus/directus#11468] opened 2022-02-07 07:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

There are no notice at UI that a required translation field is empty

### To Reproduce

1. Create a model
2. Create a translations for this model
3. Create 2 or more non-nullable fields in translations
![image](https://user-images.githubusercontent.com/32956521/152738950-bb0419ab-c635-4354-bc88-4b48f669d80f.png)
4. Go to item creation, fill one of required fields and skip other translation fields
5. Try to save item
6. There will be an error at fetch request (400), but there will be no notice at UI, so the moderator/admin can't understand what is wrong
![Снимок экрана 2022-02-07 в 11 53 16](https://user-images.githubusercontent.com/32956521/152739387-1d619341-eee6-4213-8a09-5c1e15c5c300.png)
7. And also please pay attention, that there are no required indicators for fields, like red asterisks. Why so? This is very uncomfortable for admins.

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.17.0

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2022-02-07 07:10
Should be duplicate of #9176 and #9119. Thanks for submitting an issue nonetheless.

**Closed by azrikahar** 2022-02-07 07:10 UTC
Labels: Bug (Potential)
