### ISSUE TITLE
More than 100 items in o2m do not save correctly

### ISSUE THREAD

**Issue by Dumpstar56** [directus/directus#10616] opened 2021-12-20 15:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When creating items in a o2m from the parent collection where the child collection has 100 related items, it is only possible to create the 101st item. When creating the 102nd, the 101st is deleted and a total of 101 child items remains. (The field in the parent collection form also does not list more than 100 child items). 
It is possible to create more than 100 items in the child collection when establishing the relation to the parent collection from the child collection item. However, once you create another child item from the parent collection (as above), it deletes all items above the total of 100 child items.

### To Reproduce

Create collection A and collection B. Create o2m relation between A and B with A as parent. Create one item in A and 100 items in B that are related to the item in A. Then open the item in collection A and create the 101st and 102nd child item in B.

### What version of Directus are you using?

9.3.0.

### What version of Node.js are you using?

v14.18.1

### What database are you using?

Postgres 10.14

### What browser are you using?

Firefox

### What operating system are you using?

Windows 10

### How are you deploying Directus?

AWS EC2, pm2 for app management, nginx reverse proxy.

**Comment by rijkvanzanten** [comment] 2021-12-20 18:19
Duplicate of https://github.com/directus/directus/issues/3889

**Closed by rijkvanzanten** 2021-12-20 18:19 UTC
Labels: Bug (Potential)

**Comment by fabien-lg** [comment] 2022-01-20 08:44
@rijkvanzanten 
Hello! I wonder if it's really a duplicate? I'm asking because #3889 is about displaying the values, but @Dumpstar56 issue (and I have the same) is that values are actually removed from the collection.

**Comment by rijkvanzanten** [comment] 2022-01-20 18:44
Yeah it's the same underlying issue. #3889 is about adding pagination support in both read and write operations. The current O2M uses the API's "simple" structure for related items (eg sending up the values as a flat array of primary keys), which inherently has an upper ceiling to how much you can upsert at once. The referenced issue requests redesigning the core engine for relational interfaces to rely on the `{ create: [], update: [], delete: [] }` syntax for nested relational updates, which in turn allows for related datasets of any size 👍🏻
