### ISSUE TITLE
Broken rc.94->rc.95 migration with directus_fields/directus_fields_group_foreign

### ISSUE THREAD

**Issue by flayks** [directus/directus#8376] opened 2021-09-28 09:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I get this error when trying to migrate to rc.95 from rc.94:

```
> npx directus database migrate:latest
11:55:29 ✨ Running migrations...
11:55:29 ✨ Applying Add Auth Provider...
11:55:30 ✨ Applying Webhooks URL Not Null...
11:55:30 ✨ Applying Replace Fields Group...
11:55:30 🚨 alter table `directus_fields` drop `group` - ER_DROP_INDEX_FK: Cannot drop index 'directus_fields_group_foreign': needed in a foreign key constraint
Error: ER_DROP_INDEX_FK: Cannot drop index 'directus_fields_group_foreign': needed in a foreign key constraint
```

### To Reproduce

Running the migration command `npx directus database migrate:latest`

### What version of Directus are you using?

v9-rc.95

### What version of Node.js are you using?

16

### What database are you using?

MariaDB

### What browser are you using?

Brave

### What operating system are you using?

macOS 11.5.2

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2021-09-28 10:50
Duplicate of #8369

**Closed by azrikahar** 2021-09-28 10:50 UTC
Labels: Bug (Potential)
