### ISSUE TITLE
GraphQL – Creating a new item with m2o relationship field issues

### ISSUE THREAD

**Issue by taylorbourne** [directus/directus#21496] opened 2024-02-21 04:13 UTC
### Describe the Bug

Hello! I'm having some trouble with creating a new item that has an m2o relationship field using GraphQL. For example, an item collection "Projects" has a field labeled "Client ID" that essentially links the project to a user using the primary key (id) of the user.

The goal with the following query would be to create a new project linked to an existing user primary key. The goal is to associate the project with a specific client (Directus user).
```
mutation(
      $name: String, 
      $client_id: ID, 
    ) {
      create_projects_item(
        data: { 
          name: $name, 
          client_id: { id: $client_id }, 
      }) {
        slug
      }
    }
```
Where `$client_id` is passed in as the unique id of a Directus user.

The result is a new "Projects" item (with no name, mind you) _and_ a new entry in `directus_users`. an

### To Reproduce

1. Create a collection with a m2o field linked to directus_users
2. Using graphql, attempt to create a new entry with the new collection
3. See new user it added instead of existing user updated
4. 
<img width="855" alt="Screen Shot 2024-02-20 at 6 41 05 PM" src="https://github.com/directus/directus/assets/6217194/fad90ebb-0460-47be-aa15-10d38e86f499">

### Directus Version

9.22.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2024-02-21 08:44
This should be a duplicate of #7237 as a GraphQL bug indeed, where the related item is currently being created rather than being updated (as in associating it to an existing user).

**Closed by azrikahar** 2024-02-21 08:44 UTC

**Comment by taylorbourne** [comment] 2024-02-21 23:05
@azrikahar I'm kind of confused.. so is there no way for me to create this item or update this field using graphql or the rest API? 🤔
