### ISSUE TITLE
Formatted value display text overflow issue

### ISSUE THREAD

**Issue by nazariydj** [directus/directus#11293] opened 2022-01-26 14:16 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

https://user-images.githubusercontent.com/17914536/151176160-69833afa-c7b6-414b-b0a0-abbf2185ddd2.mp4

### To Reproduce

seems to work correctly when changing CSS display param form **inline-block** to **inline** here: 
https://github.com/directus/directus/blob/e0b2a99b62fbd2e5a716aa34ca2fd685a1eccac5/app/src/displays/formatted-value/formatted-value.vue#L213-L214

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

Linux 3.10.0-957.el7.x86_64

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-01-26 14:34
Duplicate of https://github.com/directus/directus/issues/11270

**Closed by rijkvanzanten** 2022-01-26 14:34 UTC
Labels: Bug (Potential)
