### ISSUE TITLE
API delete is operatial for permition read

### ISSUE THREAD

**Issue by batosai** [directus/directus#5266] opened 2021-04-26 22:41 UTC
Actions admin is ok.
Action API delete for all collection is accessible if permition read is settter

---

### Project details
Directus Version: 9.0.0-rc.60
Environment: production
OS: Linux 5.11.0-7612-generic
Node: 14.15.4
Database: SQLite

**Comment by rijkvanzanten** [comment] 2021-04-26 22:48
Duplicate of https://github.com/directus/directus/issues/5257, fixed in https://github.com/directus/directus/commit/ad9ffb46477b2da63b83851582871f8150a789d7

**Closed by rijkvanzanten** 2021-04-26 22:48 UTC
Labels: Duplicate
