### ISSUE TITLE
POST /users throws 500 instead of 400 with invalid payload

### ISSUE THREAD

**Issue by miteyema** [directus/directus#6948] opened 2021-07-24 10:52 UTC
### Describe the Bug

API response
````json
{
    "errors": [
        {
            "message": "An unexpected error occurred.",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
````

console
````
TypeError: Cannot read property 'toLowerCase' of undefined
    at UsersService.createOne (/node_modules/directus/dist/services/users.js:86:34)
    at /node_modules/directus/dist/controllers/users.js:27:35
    at scoped (/node_modules/directus/dist/utils/async-handler.js:5:60)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)
    at next (/node_modules/express/lib/router/index.js:275:10)
````

### To Reproduce

- install of Directus using `npx create-directus-project`
- `POST http://localhost:8055/users` request without any authentication (e.g. via Postman)

### What version of Directus are you using?

v9.0.0-rc.85

### What version of Node.js are you using?

v12.22.3

### What database are you using?

Postgres

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by aidenfoxx** [comment] 2021-07-24 13:24
This should be fixed in #6942.

**Comment by rijkvanzanten** [comment] 2021-07-26 16:32
What's the payload that you posted?

> POST http://localhost:8055/users request without any authentication (e.g. via Postman)

Did you send `email` and `password`?

**Comment by aidenfoxx** [comment] 2021-07-26 16:46
I assume it was without an email address? In that case it's not a bug per-se since you're not able to create a user without an email address in Directus anyway, since the database forbids it. But it's quite an unfriendly way to find out.

**Comment by miteyema** [comment] 2021-07-27 01:59
@aidenfoxx  rijkvanzanten Indeed, no email/password, but I would expect to see a more friendly error. 
I understand, when looking at the console, the 500 error because of `toLowerCase` on a `null` value. 
But I think the request should have been checked and validated before, so the server would respond with a bad request 4xx error, making it more obvious to the user that it's actually his fault and not the fault of the server.

**Comment by rijkvanzanten** [comment] 2021-07-27 13:35
Yeah definitely, just making sure we're looking at the same problem here 🙂

**Comment by rijkvanzanten** [comment] 2021-07-28 17:54
Another one cherry picked from the PR 😁

**Closed** 2021-07-28 17:55 UTC
Labels: API, Bug, Good First Issue
