### ISSUE TITLE
Translations interface reloads on every key stroke

### ISSUE THREAD

**Issue by christianrr** [directus/directus#9761] opened 2021-11-12 14:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When editing existing translations, the translations interface is reloading on every keystroke. This makes translations nearly unusable in the current version.

https://user-images.githubusercontent.com/10274479/141487257-493dfe7b-eb08-4c45-9510-503a08b9718f.mov

Maybe related to #8417, please close if it's a duplicate.

### To Reproduce

- Create table `test`
- Add translations field
- Add input field `title` to Test Translations
- Create item in test with translations for `title`
- Reopen item and try to change `title`

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

12.2

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2021-11-12 15:11
Duplicate of #9510 👍

**Closed by azrikahar** 2021-11-12 15:11 UTC
Labels: Bug (Potential)
