### ISSUE TITLE
Cannot delete programatically created field

### ISSUE THREAD

**Issue by AndonMitev** [directus/directus#11645] opened 2022-02-15 13:00 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Cannot delete programatically created field

### To Reproduce

Create a field using the API:

1. Make post request against `fields/:collection`
2. Use for body:
```
    {
        "field": "trait#2",
        "type": "string"
    }
```

Actual result: Field is created successfully but when i try to delete it, it disappear but after refresh is still there

Expected result: Field to be removed forever after delete

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

Postman

### What database are you using?

MongoDB

### What browser are you using?

Brave

### What operating system are you using?

macOS

### How are you deploying Directus?

manually

**Comment by AndonMitev** [comment] 2022-02-15 13:21
@mcarlson @smashwilson  @Moeriki  @tim-smart

**Comment by AndonMitev** [comment] 2022-02-15 13:21
@[azrikahar](https://github.com/azrikahar)

**Comment by jaycammarano** [comment] 2022-02-15 20:10
Hello!
I believe the issue is due to the `#` in the field name. When I tested with the field `isthisvalid` it was able to delete successfully. Also, in the app when I go to configure it to not be database only it changes the title to "trait". It is still not able to delete "trait#2" at this point because it tried to delete "trait".

**Comment by rijkvanzanten** [comment] 2022-04-07 21:21
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2022-04-07 21:21 UTC
Labels: Needs More Info, Can't Reproduce
