### ISSUE TITLE
[Error] Sqlite does not support alter table

### ISSUE THREAD

**Issue by trogmaniac** [directus/directus#3586] opened 2021-01-05 14:41 UTC
I'm trying Directus for the first time.

I'm using the CLI install method with:
`npx create-directus-project test`

This goes fine until the DB selection. After choosing "sqlite" and accepting the default DB path, i get the following error:

> [Error] Sqlite does not support alter table

I tested this under Windows 7 (Node 10), Windows 10 (Node 12) and Ubuntu 20.10 (Node 12), i get the same error everywhere.

**Comment by floodedcodeboy** [comment] 2021-01-07 15:52
I had the same experience.. 

```
> npx create-directus-project directus-project
npx: installed 54 in 5.038s
? Choose your database client SQLite (Beta)
? Database File Path: /Users/username/workspace/directus-project/data.db

Something went wrong while seeding the database:

[Error] Sqlite does not support alter column.

Please try again

? Database File Path: /Users/username/workspace/directus-project/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

? Database File Path: /Users/username/workspace/directus-project/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

? Database File Path: /Users/username/workspace/directus-project/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

? Database File Path: /Users/username/workspace/directus-project/data.db

Something went wrong while seeding the database:

[Error] Database is already installed

Please try again

Couldn't seed the database. Exiting.
(node:70659) UnhandledPromiseRejectionWarning: Error: Command failed with exit code 1: npx directus init
    at makeError (/Users/username/.npm/_npx/70659/lib/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/username/.npm/_npx/70659/lib/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Command.create (/Users/username/.npm/_npx/70659/lib/node_modules/create-directus-project/lib/index.js:73:2)
(node:70659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:70659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Tested on:
OS: OSX Catalina (10.15.7)
npm: 6.13.4
node: 12.14.1

**Comment by rijkvanzanten** [comment] 2021-01-07 19:16
Duplicate of https://github.com/directus/directus/issues/2948

**Closed by rijkvanzanten** 2021-01-07 19:16 UTC
Labels: API, Bug, DB: SQLite
