### ISSUE TITLE
Error when editing a junction item in the drawer

### ISSUE THREAD

**Issue by mullinsmikey** [directus/directus#18677] opened 2023-05-21 08:49 UTC
### Describe the Bug

An error is thrown when trying to edit a junction item; doesn't seem to affect the logic, only UX.

I'm aware that this should've been fixed by #17210 but it's still happening due to the field configuration.

Actual result:
A 403 error is being thrown with the following stack (simplified): `validateKeys < ItemsService.readOne`

The respecting HTTP request is `GET PUBLIC_URL/items/events/%2B?fields[]=name&fields[]=id`.

**Expected result:**
The drawer is opened with additional context for the "circular field" to eliminate the error.

### To Reproduce

* Create a collection (A) or use an existing one, e.g. `directus_users`
* Create a collection (B) with an m2m field (C)
* Set up the junction collection
  * Make the field (D) for the collection B visible
  * Set the interface for the field D to m2o
  * Set its display template so that it reflects a value from the item B
* Create an item in the collection B, click "Add existing" to select a related item

### Directus Version

10.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-05-22 09:08
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by paescuj** 2023-05-22 09:08 UTC

**Comment by mullinsmikey** [comment] 2023-05-22 16:55
Hi @paescuj, I sure hope this [db dump](https://github.com/directus/directus/files/11533781/db_dump-18677.sql.zip) and the video would help a lot.

Use `pg_restore` to apply this dump with the following options: `--format=c --no-owner --no-privileges`.

Also, please unzip the dump as GitHub doesn't allow sql files to be uploaded.

[](https://github.com/directus/directus/assets/8100939/2a4f284a-30c7-4363-a72f-218f92124ce1)

**Comment by mullinsmikey** [comment] 2023-05-26 04:54
Hi @rijkvanzanten, would you mind taking a look? I've attached a video and a db dump.

**Comment by adanielyan** [comment] 2023-06-14 19:33
This issue was reported many times, it is strange you cannot reproduce it...
