### ISSUE TITLE
Sort is done before deep filters

### ISSUE THREAD

**Issue by miguelBinpar** [directus/directus#21404] opened 2024-02-12 15:29 UTC
### Describe the Bug

Looks like sort phase is being execured before deep phase during queries.

Right now there's no way to sort results based on filtered values in `deep` property.

I'm not sure if this is a bug or it's working as expected and this should be a feature request. If that's the case, I'm sorry about that, just let me know if that's the case and you need me create a new issue.

### To Reproduce

You need a model with two related collections. Something like this:

> **Book** (books)
> id: string;
> title: string
> userInfos => bookUserInfos
> 
> **BookUserInfo** (bookUserInfos)
> book: string => books.id
> user: string;
> lastAccess: string (Date);

Imagine you want to show books based on user's last access, then I'd like to query books like this:

```ts
readItems('books', {
  deep: {
    userInfos: {
      _filter: {
        user: userId,
      },
    },
  },
  sort: ['-userInfos.lastAccess'],
})
```

Right now this is sorting results **before** deep filter, meaning results will be sorted based on **any user** information related to books instead of specific user info.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-02-13 08:05
Thanks for opening this issue! However this is a duplicate of an existing issue #19397, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #19397 for future updates.

**Closed by paescuj** 2024-02-13 08:05 UTC

**Comment by miguelBinpar** [comment] 2024-02-13 08:15
> Thanks for opening this issue! However this is a duplicate of an existing issue #19397, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #19397 for future updates.

I'm not sure it's the same problem. In my case order is correct before deep. In the example of that issue, order is just not right... anyway, I'll keep an eye on that issue. Thanks.
