### ISSUE TITLE
500 error accessing images

### ISSUE THREAD

**Issue by cheshirrrcat** [directus/directus#23618] opened 2024-09-10 09:46 UTC
### Describe the Bug

When I try to get images uploaded to the collection, I get a 500 error (internal server error) for some of them.

![image](https://github.com/user-attachments/assets/11151fd9-d1b2-4ea8-b1ed-3ee66840fc6d)
![tg_image_2260569717](https://github.com/user-attachments/assets/ceda1712-5ec2-4eb2-9743-764ff6560009)
![image](https://github.com/user-attachments/assets/5ed4cfda-597e-4525-bb30-8dc9fde2171b)

### To Reproduce

I don't quite understand what needs to be written here, because the error is obviously on the Directus server side.

### Directus Version

v.11.1.0

### Hosting Strategy

Directus Cloud

**Comment by cheshirrrcat** [comment] 2024-09-12 09:59
Four hours ago, server problems stopped occurring.
Had this problem for about 7 days (since last Friday evening), and suddenly stopped happening.
Strange behavior.

**Comment by br41nslug** [comment] 2024-09-20 14:54
Closing this issue as it seems hosting related not a bug in the platform itself 🤔 If this happens again please do contact cloud support to have the cause investigated on your cloud instance

**Closed by br41nslug** 2024-09-20 14:54 UTC

**Comment by cheshirrrcat** [comment] 2024-09-20 15:25
> Closing this issue as it seems hosting related not a bug in the platform itself 🤔 If this happens again please do contact cloud support to have the cause investigated on your cloud instance

But our Directus is hosted by you, I indicated this in the ticket.

**Comment by br41nslug** [comment] 2024-09-20 15:34
Correct which is what cloud support is for, they have access to the server to debug the issue for you. So please do contact them for cloud hosting related issues 😄 Github issues are meant for bugs in the Directus software itself, without server logs or reproduction steps there is little I can do to resolve this issue
