### ISSUE TITLE
Can't change the green primary colour 

### ISSUE THREAD

**Issue by ghost** [directus/directus#4523] opened 2021-03-13 07:16 UTC
There is a new green primary colour in the app that cannot be changed through custom CSS, even setting `--primary` or any other colours as part of custom CSS. This has not always been the case, I'd say only since about 9.0.0-rc.44.

You can see the color by hovering over or clicking any header in the right sidebar. It is also the color of filled sliders or ticked toggles. In previous releases it used to be a light blue which IMO was less distracting.

Project Details:
Directus Version: 9.0.0-rc.50
Database: Postgresql 9.6
Node: 14.15.4
OS: Windows 10

**Comment by rijkvanzanten** [comment] 2021-03-13 14:23
I'm fairly sure this still works as expected 🤔 What are you using for custom css?

```css
#app {
  --primary: red;
}
```

seems to work as expected on my end

**Comment by xl-1200** [comment] 2021-03-14 00:23
Setting exactly that CSS for me doesn't remove the green highlights (eg. try hovering over a header in the right sidebar after).

![image](https://user-images.githubusercontent.com/77377747/111053429-86990e00-845b-11eb-9e01-06c91df80930.png)

**Comment by rijkvanzanten** [comment] 2021-03-14 14:21
@benhaynes where there any naming changes here in the last styling change updates?

**Comment by benhaynes** [comment] 2021-03-14 20:02
No. `--primary` is still the variable, this seems to be a CSS scoping issue. Looking in dev tools shows that the variable is set correctly, but it's not being passed to the alias variables. Could even be a browser issue, since clicking on the `primary` reference under `--sidebar-detail-color-active` **takes** you to the red variables in dev tools.


![Screen Shot 2021-03-14 at 4 00 48 PM](https://user-images.githubusercontent.com/522079/111082407-7c6c2380-84de-11eb-91c0-9eb708fe6b31.png)

![Screen Shot 2021-03-14 at 4 00 55 PM](https://user-images.githubusercontent.com/522079/111082412-8130d780-84de-11eb-935d-7f6d20385326.png)

**Comment by benhaynes** [comment] 2021-03-14 20:04
In any event, this is not an issue with the variable itself, and users can always update the codebase itself to change the color. I'll close this and we can wait for the feature request for themes: https://github.com/directus/directus/discussions/4204

**Comment by xl-1200** [comment] 2021-03-14 23:26
FWIW, I've noticed the same when looking at the CSS in my browser (FF) too - seemed pretty odd. I can confirm this issue wasn't there before rc40 too.

**Comment by benhaynes** [comment] 2021-03-15 14:46
Seems to be a specificity issue... since adding `!important` fixes it:

```
*, body, #app {
  --primary: red !important;
}
```

If anyone wants to take a look at this that would be awesome!

**Comment by benhaynes** [comment] 2021-04-02 18:21
I've updated the example for this, and since it's more of an inconvenience than an issue, I'll close this for now.

https://github.com/directus/directus/blob/main/docs/guides/styles.md#example

**Closed by benhaynes** 2021-04-02 18:21 UTC
Labels: App, Good First Issue, Improvement
