### ISSUE TITLE
extensions-sdk v9.25.1 is broken

### ISSUE THREAD

**Issue by Bulkman** [directus/directus#18191] opened 2023-04-14 16:13 UTC
### Describe the Bug

![download](https://user-images.githubusercontent.com/3801995/232098834-55ad8a6c-012e-4d1d-9b53-c6feb7ca3a47.png)

### To Reproduce

Install @directus/extensions-sdk v9.25.1 and try to build extension.

### Directus Version

v9.25.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-04-14 16:14
Duplicate of https://github.com/directus/directus/issues/18178

**Closed by br41nslug** 2023-04-14 16:14 UTC
