### ISSUE TITLE
Refresh Token is not working anymore

### ISSUE THREAD

**Issue by dokime7** [directus/directus#16192] opened 2022-10-27 08:32 UTC
### Describe the Bug

After 15 min the access token expires and the user is redirected to the login page with `SESSION_EXPIRED` message.

We can see at this moment that the `POST /auth/refresh` is requested with the refresh token in `directus_refresh_token` cookie but HTTP 401 is received
```
{message: "Token expired.", extensions: {code: "TOKEN_EXPIRED"}}
```

### To Reproduce

- Logon on Directus
- Wait 15 min
- Clic on something in the interface
=> Redirection on login page with `SESSION_EXPIRED` message instead of just stay connected

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

?

### What database are you using?

postgis 13

### What browser are you using?

Brave

### How are you deploying Directus?

Docker

**Comment by dokime7** [comment] 2022-10-27 08:36
This issue appear some days ago without changing anything except update Directus to latest version.
There is the same problem with calling refresh token API from an external app.

**Comment by br41nslug** [comment] 2022-10-27 08:37
Duplicate of https://github.com/directus/directus/issues/16188 lets track the issue there

**Closed by br41nslug** 2022-10-27 08:37 UTC
