### ISSUE TITLE
Checkbox problem while creating/editing new field

### ISSUE THREAD

**Issue by iksent** [directus/directus#11543] opened 2022-02-09 12:19 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Can't unselect checkbox while creating new image field

### To Reproduce

1. Create or edit `Image` field
2. Go to "Display" and select "Image":
![image](https://user-images.githubusercontent.com/32956521/153199398-7967c78d-50d4-4f5c-86d8-96fb737b7064.png)
3. Check the "Circle" checkbox:
![image](https://user-images.githubusercontent.com/32956521/153199446-b836a7be-8d0c-4d06-a362-d55b8bb2ab6b.png)
4. Try to uncheck it: **no effect**
5. Try to click on "Reset to default": **no effect**
6. Try to click on "Clear value": **it goes to "indeterminate" state**
![image](https://user-images.githubusercontent.com/32956521/153199625-1053d78f-1d80-4f5d-986e-2a9e9c1f4b48.png)

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.17.5

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2022-02-10 03:31
Duplicate of #11442, with the open PR #11467 confirmed to resolve this issue:

![YO3VsRZRFm](https://user-images.githubusercontent.com/42867097/153331931-c7538818-c1b9-4ac5-bb0a-e31d31eb4143.gif)

**Closed by azrikahar** 2022-02-10 03:31 UTC
Labels: Bug (Potential)
