### ISSUE TITLE
Cannot delete user who owns a file

### ISSUE THREAD

**Issue by dorianim** [directus/directus#9299] opened 2021-11-01 12:34 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I want to delete the user who uploaded the background wallpaper, but this is not possible due to a key constrain.

### To Reproduce

1. Create a new user
2. Login with this user
3. Upload a new background wallpaper
4. Login with a different user
5. Delete the user from 1

### Errors Shown

![image](https://user-images.githubusercontent.com/30153207/139672023-a41b0152-af1e-4b9a-b1b6-0af0fd614940.png)

```
[INTERNAL_SERVER_ERROR] delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_files_uploaded_by_foreign" on table "directus_files"
```

### What version of Directus are you using?

v9.0.0-rc.100

### What version of Node.js are you using?

8.1.0 (Docker image)

### What database are you using?

PostgreSQL 12.8 (Docker image)

### What browser are you using?

Firefox

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-11-01 12:56
Duplicate of #8650

**Closed by azrikahar** 2021-11-01 12:56 UTC
Labels: Bug (Potential)
