### ISSUE TITLE
Missing validation error message inside the overlay panel

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17093] opened 2023-01-11 18:49 UTC
### Describe the Bug

There is no validation message, when adding a new item in the overlay panel of an relational field (O2M, M2M, …). So when a field is required (or has any other validation) nothing happens after clicking the save button. There should be an error message.

### To Reproduce

Create a collection with a O2M field. The related collection must have a field (let’s say input field) that is required or any other validation. Then create a new item via the O2M field and hit save in the overlay panel — nothing happens.

### Errors Shown

no :(

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

Latest

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2023-01-11 20:55
Duplicate of https://github.com/directus/directus/issues/16091

**Closed by rijkvanzanten** 2023-01-11 20:55 UTC
