### ISSUE TITLE
API search query returns "error 500", when searching for number with more than 10 digits

### ISSUE THREAD

**Issue by pyderman** [directus/directus#18466] opened 2023-05-03 18:13 UTC
### Describe the Bug

I am querying a Directus collection for a 13 digit barcodes (set up as a string) from Postman and Flutterflow (same result) -> Error 500

This happens in 2 different independent collections. In another I query for another 13 digit number set up as string

Query without search parameter: Fine
<img width="1189" alt="Query_no_search" src="https://user-images.githubusercontent.com/50204122/236006456-6bc6a069-2ee0-449b-ae69-759a6e4136d8.png">

Query with 10 characters: Fine
<img width="1189" alt="Query_search_10digits" src="https://user-images.githubusercontent.com/50204122/236006464-4bc72b88-fe0f-4184-a454-9f501aaf6d79.png">

Query with 11 characters that match a result (correct digit added in the front): Error 500
<img width="1189" alt="Query_search_11digits" src="https://user-images.githubusercontent.com/50204122/236006472-e56fbce5-4c21-421e-b2f6-88940e4f8a39.png">

Query with 11 characters that do not match any result (not matching digit added in the end): Empty list
<img width="1189" alt="query_search_no_match" src="https://user-images.githubusercontent.com/50204122/236006803-fa128270-653e-4a0e-a333-c95660d2db7f.png">

### To Reproduce

Try a search query for a field with a number with more than 10 digits.

### Directus Version

v9.25.2

### Hosting Strategy

Directus Cloud

**Comment by shipsides-sparknel** [comment] 2023-05-04 03:06
@pyderman do you also have one or more integer fields in the same collection? 

i encounter the same issue but my long number is stored as bigint instead of string. dissecting the error message i get, it is something to do with how the search api translates itself into an SQL query. if you search for 2147483647 (max int value for postgres and 10 digits) it works, but as soon as you flick it to 2147483648 the query breaks despite still being 10 digits

this is an edited version of the error message i get

`{
  "errors": [
    {
      "message": "select
"collection"."bigintfield",
"collection"."string",
"collection"."integer",
...... etc .....
value \"75657862765\" is out of range for type integer",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

**Comment by paescuj** [comment] 2023-05-04 08:38
Thanks for opening this issue! However this is a duplicate of an existing issue #17946, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #17946 for future updates.

**Closed by paescuj** 2023-05-04 08:38 UTC
