### ISSUE TITLE
Input lag and screen flicker when editing translated fields on previously created items

### ISSUE THREAD

**Issue by jawngee** [directus/directus#9547] opened 2021-11-06 02:15 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When editing translated fields, the API gets hammered with a request for each keystroke.  The admin screen will flicker and causes serious input lag to the point of being unusable (keystrokes go missing).  This doesn't seem to happen when creating an item initially, only when you go back to edit an existing item.

![2021-11-06 09 11 46](https://user-images.githubusercontent.com/44449/140594402-44ebc2a8-0463-4510-b0c9-694cf0a8be96.gif)

### To Reproduce

1. Create a new project via `npm init directus-project translation-demo`
2. Create a posts table
3. Add a translation field
4. Add a title and text input to the translation collection
5. Create a new post
6. Save post
7. Edit post

### Errors Shown

No errors shown.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.3

### What database are you using?

sqlite

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

local

**Comment by JeremieLeblanc** [comment] 2021-11-07 22:51
I am also having this exact issue. It skips every other keystroke, making it impossible to use.

**Comment by azrikahar** [comment] 2021-11-08 03:33
Duplicate of #9510.

Note: Slight difference is here it won't unfocus, but that's just the nature of WYSIWG input. They're the same bug & can be fixed by reverting a change, as mentioned here: https://github.com/directus/directus/issues/9510#issuecomment-962779091

**Closed by azrikahar** 2021-11-08 03:33 UTC
Labels: Bug (Potential)
