### ISSUE TITLE
Translation (relations) data in the preview returns an object in the URL

### ISSUE THREAD

**Issue by YannickArmspach** [directus/directus#21869] opened 2024-03-15 09:31 UTC
### Describe the Bug

Hello,

When we use a translation relationship and its associated data in the preview URL, we receive the data as an object.

We can use the configuration of the default translation field to display only the correct value? Or use a shortcode like {{mytranslations.myvalue[0]}} And as a fallback the first value for all other case ?

![Image 2024-03-15 10-04-59](https://github.com/directus/directus/assets/1702221/d4dff9a7-47d4-47a7-b16c-2e067a38be2c)

### To Reproduce

- Create a translation field.
-  Create a field inside the translation.
-  Use this new field data inside the preview URL.

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2024-03-15 09:37
Thanks for opening this issue! However this is a duplicate of an existing issue #19637, in which the conclusion was that this should be submitted as [new feature request](https://github.com/directus/directus/discussions/new?category=feature-requests) instead. I'll proceed to close this issue, thanks again!

**Closed by paescuj** 2024-03-15 09:37 UTC
