### ISSUE TITLE
Saving table settings shows nothing changed message

### ISSUE THREAD

**Issue by rijkvanzanten** [directus/directus#1871] opened 2017-10-09 14:02 UTC
## Version Info
  - Directus version and branch: [develop latest](https://github.com/directus/directus/commit/9d3263c89cabc7bbba64433ccdd195725ae81c2c)
  - PHP version: 7.1.6
  - MySQL version: 5.6.35
  - Web server: Apache (MAMP Pro)
  - OS name and version: macOS High Sierra v10.13.1 Beta (17B25c)

## Expected Behavior
Saving the table settings by pressing the save button saves the settings and returns to the overview page

## Actual Behavior
Since the table settings are saved on change, pressing the save button doesn't actually save anything new and therefor shows the `Nothing changed, nothing saved` message

## Steps to Reproduce
 1. Alter some table settings
 2. Press the save button in the top right

## Additional info
We could remove the save button al together, or hide the nothing changed message to make it feel like it saved successfully.

**Comment by WellingGuzman** [comment] 2017-10-10 04:03
> Since the table settings are saved on change, pressing the save button doesn't actually save anything

What do you mean by this? the only thing save "automatically" is all columns related, that you don't have to click save, as they are saved as soon as you made the change (`on change`), the rest need to be changed and saved manually (clicking save button)

**Comment by benhaynes** [comment] 2017-10-10 14:02
The problem is (as Welling Mentioned) that only one "field" on this page autosaves – albeit a very complicated one. So we can't remove the SAVE button because it's used for everything else on the page. I think the better option would be to (eventually) try to find a way to get these complex permissions/column-options to use the SAVE button too.

While this is a nice improvement – it's a big can of worms and there are many higher priority items at the moment. In the meantime, we could add "Saved" notifications whenever you change those autosaving items.

**Comment by WellingGuzman** [comment] 2017-10-10 16:51
It seems that the warning saying `Nothing changed, nothing saved` are okay, because adding, removing and updating column throws a notification which makes the user clear that something happened, but as soon as you click the save button it will say that nothing has changed, so nothing saved.

**Comment by benhaynes** [comment] 2017-10-20 17:31
@rijkvanzanten @WellingGuzman @airbenich – any thoughts on a good resolution for this? The notification is correct... and this is the result of a much more complex issue (saving for two sections of the CMS is instant).

**Comment by rijkvanzanten** [comment] 2017-10-20 17:45
Let's just hide the notification on this particular page. It's not a real bug as it doesn't influence the actual saving, but it feels a bit weird from a UX perspective. I changed something -> hit save -> I get told nothing changed -> it has saved

**Comment by WellingGuzman** [comment] 2017-10-20 20:46
But if you change something in the column it show a notification that something changed. then if you hit save, what are you saving? nothing cause it was already save. so it seems clear to me. What do you all think?

**Comment by WellingGuzman** [comment] 2017-10-22 05:29
This is not an actual issue, i'm closing this, but we can still discuss what are we going to do to avoid the confusion, but to me, it seems clear, but I'm open to suggestion, but hiding only for columns could be also weird and confusing.

**Closed by WellingGuzman** 2017-10-22 05:29 UTC
Labels: 4. Minor, Interface, Question
