### ISSUE TITLE
Text Pasting Issues with Headings

### ISSUE THREAD

**Issue by KoenBrave** [directus/directus#22860] opened 2024-06-27 08:46 UTC
### Bug Description:

- **Environment**:
  - Device: MacBook Air
  - Operating System: macOS 14.4.1 (23E224)
  - Processor: Apple M1
  - Software: Directus 10.10.4

- **Issue**:
  - **Copy-Pasting Text with Headings**: When copying and pasting text that includes a heading, Directus exhibits unusual behavior.
  - **Example**:
    - Simple text without a heading (e.g., "Just plain text with no heading in it.") works fine.
    - Text with a heading (e.g., "### A Header\nThis is normal text") causes problems.

- **Problems Observed**:
  - **Undo Functionality**: After pasting text with a heading, using the CMD + Z shortcut to undo the paste action does not work.
  - **Cursor Placement**: The cursor is incorrectly positioned before the word “This” in the pasted text instead of after the last word.

### Steps to Reproduce:

1. Copy the following text that includes a heading:
   ```
   ### A Header
   This is normal text
   ```
2. Paste this text into a Directus editor.
3. Observe the cursor placement – it will be positioned before “This” instead of after “text”.
4. Press CMD + Z to undo the paste action.
5. Notice that the undo action does not work as expected.

### Expected Behavior:

- The cursor should be positioned after the last word of the pasted text.
- CMD + Z should correctly undo the paste action, removing the pasted text.

### Actual Behavior:

- The cursor is placed incorrectly before the word “This”.
- CMD + Z does not undo the paste action.

### Directus Version

10.10.4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2024-07-01 19:45
Hi @KoenBrave! What interface are you using for this field?

**Comment by KoenBrave** [comment] 2024-07-02 09:09
Hoi @rijkvanzanten , we are using Block Editor.
![Screenshot from 2024-07-02 11-05-04](https://github.com/directus/directus/assets/133883522/febcfc93-fb80-4d5c-8bfd-7ff6800bc90f)

**Comment by br41nslug** [comment] 2024-07-03 15:20
This issue is a duplicate of #20655 and a know issue of editorjs where if you paste something that creates a new block then you cannot undo it with `ctrl/cmd + Z`

**Closed by br41nslug** 2024-07-03 15:20 UTC
Labels: :detective: Needs More Info
