### ISSUE TITLE
Migration from 10.6 to 10.7 error on Content Versioning : "Foreign key constraint is incorrectly formed" (MySQL)

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#20316] opened 2023-11-03 11:46 UTC
### Describe the Bug

Running migration as usual from 10.6 to 10.7.2, I had this error : 
![image](https://github.com/directus/directus/assets/18073828/66d2422a-772f-44f6-8a76-4d28e36ae38c)
Namely : 
```
Can't create table `aimerdieu`.`directus_versions` (errno: 150 "Foreign key constraint is incorrectly formed")
sql: 'alter table `directus_versions` add constraint `directus_versions_collection_foreign` foreign key (`collection`) references `directus_collections` (`collection`) on delete CASCADE'
```

### To Reproduce

Migrate from 10.6 to 10.7.2, run : 
```
sudo npm update directus;
sudo npx directus bootstrap;
```

Ubuntu, MySQL (MariaDB 10.6), node 18.12

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2023-11-03 13:01
Unfortunately I was not able to reproduce this based on the reproduction steps shared (with MariaDB 10.6 running as a docker container) as seen in the video below:

Notes:

- The upgrade to `10.7.2` took a while in the video, so feel free to skip from `00:42` to `02:13`.
- Although there's the default collation warning at the end, that should be a separate discussion at #18470 and shouldn't be related to your reported issue 👍 (your error _might_ be due to differing collations, but as my video shown, the `collection` column in `directus_collections` doesn't seem to be affected in my case)

https://github.com/directus/directus/assets/42867097/65959f42-406e-47a7-af9e-db9eb42c4478

Was there any other custom migrations or changes to the database tables outside of these Directus migrations? Closing as can't repro based on the current information for now, but will re-open once we are able to reproduce this reliably 👍

**Closed by azrikahar** 2023-11-03 13:01 UTC

**Comment by neo7-studio-web** [comment] 2023-11-04 15:12
Thank you for the complete test. 
> Was there any other custom migrations or changes to the database tables outside of these Directus migrations?
Nope. I'll investigate on my side. Maybe someone will have the same issue.

**Comment by neo7-studio-web** [comment] 2023-11-04 15:37
More info : 
```
------------------------
LATEST FOREIGN KEY ERROR
------------------------
2023-11-04 16:24:19 0x7fce54a52640 Error in foreign key constraint of table `aimerdieu`.`directus_versions`:
Alter  table `aimerdieu`.`directus_versions` with foreign key `directus_versions_collection_foreign` constraint failed. Field type or character set for column 'collection' does not match referenced column 'collection'.
```
Definitely it sounds like a collation type problem. I keep investigating.

**Comment by neo7-studio-web** [comment] 2023-11-04 17:33
Finally... This migration was soooo painful 😭
I write my solution here for the community in case someone faces the same issue.
I had to **manually set collation** of all existing columns where id/pk is not a number but a char/varchar to **utf8mb4_general_ci** before migrating.
Then I could run the migration with no error. I hope there will be no collateral problem but for the moment everything looks fine.

**Comment by azrikahar** [comment] 2023-11-08 15:43
> I had to **manually set collation** of all existing columns where id/pk is not a number but a char/varchar to **utf8mb4_general_ci** before migrating. 

Thank you for sharing the solution! Wish it wasn't so tedious for you. I know this is after the fact you completed said migration, but would you be able to share what are the affected columns, and what was their collection _before_ you updated them to `utf8mb4_general_ci`?

**Comment by neo7-studio-web** [comment] 2023-11-09 13:09
Sure.

The tables.columns are :

directus_collections.collection (PK is varchar)
directus_dashboard.id (char)
directus_extensions.name (varchar)
directus_files.id (char)
directus_flows.id (char)
directus_folders.id (char)
directus_operations.id (char)
directus_panels.id (char)
directus_roles.id (char)
directus_shares.id (char)
directus_translations.id (char)
directus_users.id (char)
directus_versions.id (char)

Their collection was **latin1_swedish_ci** before the migration.
