### ISSUE TITLE
Directus can't use an existing SQLite DB using STRICT tables

### ISSUE THREAD

**Issue by bbkane** [directus/directus#12414] opened 2022-03-27 02:28 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I thought I'd try out Directus by using a SQLite DB created by my little CLI [starghaze](https://github.com/bbkane/starghaze/blob/master/sqlite_migrations/2022-01-19-21.08.47_init.sql). Starghaze is using the new [STRICT tables](https://www.sqlite.org/stricttables.html) support in SQLite 3.37.0 for its DB.

Trying to seed Directus with my 
[database](https://github.com/directus/directus/files/8356702/data.db.zip) (zipped so GitHub will accept it) results in the following error:

```
[SQLITE_CORRUPT] select * from sqlite_master where type = 'table' and name = 'directus_collections' - SQLITE_CORRUPT: malformed database schema (Repo) - near "STRICT": syntax error
```
 

### To Reproduce

Unzip the attached SQLite database.

```
$ npm init directus-project starghaze
Need to install the following packages:
  create-directus-project
Ok to proceed? (y) y
? Choose your database client SQLite
? Database File Path: /Users/bbkane/Code/Directus/starghaze/data.db  # replace with your path

Something went wrong while seeding the database:

[SQLITE_CORRUPT] select * from sqlite_master where type = 'table' and name = 'directus_collections' - SQLITE_CORRUPT: malformed database schema (Repo) - near "STRICT": syntax error

Please try again
```

### Errors Shown

```
Something went wrong while seeding the database:

[SQLITE_CORRUPT] select * from sqlite_master where type = 'table' and name = 'directus_collections' - SQLITE_CORRUPT: malformed database schema (Repo) - near "STRICT": syntax error
```

### What version of Directus are you using?

`$ npx create-directus-project --version` shows `9.7.1`

### What version of Node.js are you using?

`$ node --version` shows `v16.14.2`

### What database are you using?

SQLite 3.37.2 (created via https://pkg.go.dev/modernc.org/sqlite@v1.14.5#pkg-overview )

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2022-03-28 06:40
> What database are you using?
SQLite 3.37.2

Judging from issues such as https://github.com/mapbox/node-sqlite3/issues/1546, I believe it is not actually using 3.37+ in your setup here. To be fair this should be more so something to do with said dependency with pre-compiled binaries which does not cover this newer version, rather than Directus itself. 

Perhaps you can try [building from source](https://github.com/mapbox/node-sqlite3#source-install) and make sure it uses the sqlite you had installed on your machine to see does that work?

**Comment by bbkane** [comment] 2022-03-28 14:04
I don't work much with Node/NPM, but yes, I can try to build `node-sqlite` from source using your linked instructions to see if building it with my local version of SQLite (>= 3.37 ) can handle a query with STRICT tables. It might take me a couple of days to get the time :)

**Comment by rijkvanzanten** [comment] 2022-04-07 20:51
Closing this for now, as it's not a bug in Directus itself, but an outdated dependency issue. We're already tracking the upgrade of knex + a switch to better-sqlite as part of #10842, so lets keep the dependency upgrade discussion consolidated there 🙂

**Closed by rijkvanzanten** 2022-04-07 20:51 UTC
Labels: Needs More Info, Bug (Potential), External

**Comment by nickrum** [comment] 2022-04-07 20:55
One thing to keep in mind is that we also have to add support for the `STRICT` keyword to the `CREATE TABLE` parser in Knex.

**Comment by bbkane** [comment] 2022-04-07 21:43
Yes, I never got around to testing anyway. I'll subscribe to that issue.
