### ISSUE TITLE
[schema apply] Changing primary key field tries to re-create the primary key

### ISSUE THREAD

**Issue by BenoitAverty** [directus/directus#17864] opened 2023-03-21 13:44 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Hello,

I'm using the `directus schema apply command` to automate my deployments.

In my latest deployment, I have a collection with a `guid` field which is the primary key. This field has changed position, so its `sort` column has changed value (in `directus_fields`). When I run the migration command, i have the following output : 

```
? The following changes will be applied:



Fields:
  - Update article.guid
    - Set sort to 1
  - Update article.photo
    - Set group to content
    - Set sort to 3
  <etc.>
Would you like to continue? Yes
```

But when I accept, I have the following error : 

```
[13:38:06.177] ERROR: Failed to update field "article.guid"
[13:38:06.178] ERROR: alter table `article` add primary key `article_pkey`(`guid`) - ER_MULTIPLE_PRI_KEY: Multiple primary key defined
    err: {
      "type": "Error",
      "message": "alter table `article` add primary key `article_pkey`(`guid`) - ER_MULTIPLE_PRI_KEY: Multiple primary key defined",
      "stack":
          Error: ER_MULTIPLE_PRI_KEY: Multiple primary key defined
              at Query.Sequence._packetToError (/tmp/directus-francelive/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
              at Query.ErrorPacket (/tmp/directus-francelive/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
              at Protocol._parsePacket (/tmp/directus-francelive/node_modules/mysql/lib/protocol/Protocol.js:291:23)
              at Parser._parsePacket (/tmp/directus-francelive/node_modules/mysql/lib/protocol/Parser.js:433:10)
              at Parser.write (/tmp/directus-francelive/node_modules/mysql/lib/protocol/Parser.js:43:10)
              at Protocol.write (/tmp/directus-francelive/node_modules/mysql/lib/protocol/Protocol.js:38:16)
              at Socket.<anonymous> (/tmp/directus-francelive/node_modules/mysql/lib/Connection.js:88:28)
              at Socket.<anonymous> (/tmp/directus-francelive/node_modules/mysql/lib/Connection.js:526:10)
              at Socket.emit (node:events:513:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
              --------------------
              at Protocol._enqueue (/tmp/directus-francelive/node_modules/mysql/lib/protocol/Protocol.js:144:48)
              at Connection.query (/tmp/directus-francelive/node_modules/mysql/lib/Connection.js:198:25)
              at /tmp/directus-francelive/node_modules/knex/lib/dialects/mysql/index.js:132:18
              at new Promise (<anonymous>)
              at Client_MySQL._query (/tmp/directus-francelive/node_modules/knex/lib/dialects/mysql/index.js:126:12)
              at executeQuery (/tmp/directus-francelive/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
              at Client_MySQL.query (/tmp/directus-francelive/node_modules/knex/lib/client.js:146:12)
              at /tmp/directus-francelive/node_modules/knex/lib/execution/transaction.js:363:24
              at new Promise (<anonymous>)
              at Client_MySQL.trxClient.query (/tmp/directus-francelive/node_modules/knex/lib/execution/transaction.js:358:12)
              at Runner.query (/tmp/directus-francelive/node_modules/knex/lib/execution/runner.js:123:36)
              at Runner.queryArray (/tmp/directus-francelive/node_modules/knex/lib/execution/runner.js:217:21)
              at Runner.queryArray (/tmp/directus-francelive/node_modules/knex/lib/execution/runner.js:269:31)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at async Runner.ensureConnection (/tmp/directus-francelive/node_modules/knex/lib/execution/runner.js:300:14)
              at async Runner.run (/tmp/directus-francelive/node_modules/knex/lib/execution/runner.js:30:19)
      "code": "ER_MULTIPLE_PRI_KEY",
      "errno": 1068,
      "sqlMessage": "Multiple primary key defined",
      "sqlState": "42000",
      "index": 0,
      "sql": "alter table `article` add primary key `article_pkey`(`guid`)"
    }
```

it seems that directus tries to recreate the primary key, even though only the field's sort has changed. MySQL fails at this step and the entire schema apply command fails.

### To Reproduce

Create a collection with a primary key, export the schema (`directus schema snapshot`), change the fieklds order in the app and try to re-apply the schema (`directsu schema apply`)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by BenoitAverty** [comment] 2023-03-21 14:04
I had a similar problem with other fields. The "sort" was changed (or translations for example), and the migration script tried to re-set the type of the column in MySQL even though it had not changed. In some cases it passes (the request is idempotent after all), but in other cases MySQL rejected the change because the column is used in a foreign key constraint for example.

**Comment by Dominic-Marcelino** [comment] 2023-03-21 18:22
Running into the same problem. Have changed some meta-fields (and also the only changes for the ID field) and the CLI tries to create a new primary key.

Did you found any workaround?

**Comment by miagg** [comment] 2023-03-27 14:08
Same problem. Even a small change to a field that is a primary key causes `npm run apply` to fail. Had to revert back to 9.22.3

**Comment by paescuj** [comment] 2023-03-29 15:30
Duplicate of #17820, tracking it over there 👍

**Closed by paescuj** 2023-03-29 15:30 UTC
