### ISSUE TITLE
Can't load custom module

### ISSUE THREAD

**Issue by ilamarche** [directus/directus#5002] opened 2021-04-12 15:52 UTC
Since 9.0.0-rc.57, custom modules can be load. Its work in 9.0.0-rc.56 version.
They just have a warning and modules not appear in navbar

### Project details
Directus Version: 9.0.0-rc.57
Environment: production
OS: Linux 4.15.0-136-generic
Node: 15.9.0

**Comment by ilamarche** [comment] 2021-04-12 16:22
All right my bad, i have make a mistake.
Modules need index.js in root directory of module and dist build index.js file.....

**Comment by rijkvanzanten** [comment] 2021-04-13 21:26
Duplicate of https://github.com/directus/directus/issues/4902

**Closed by rijkvanzanten** 2021-04-13 21:26 UTC
Labels: App, Bug (Potential)
