### ISSUE TITLE
Fast search fails when inserting big number-like value

### ISSUE THREAD

**Issue by miguelBinpar** [directus/directus#18524] opened 2023-05-09 08:32 UTC
### Describe the Bug

We have books in our data model. Books have "EAN", consisting in 13 digits.
When using fast search in this collection... we get an error.
Looks like Directus is trying to cast value to number to search in properties of that type but value it's too big for an integer.

This is the full error in my case:

```
{
  "errors": [
    {
      "message": "select \"productVariants\".\"isbn\", \"productVariants\".\"format\", \"productVariants\".\"externalId\", \"productVariants\".\"id\", \"productVariants\".\"product\" from \"productVariants\" inner join (select distinct \"productVariants\".\"id\", \"productVariants\".\"externalId\" as \"sort_odajm\" from \"productVariants\" left join \"collections_productVariants\" as \"pvmzx\" on \"productVariants\".\"id\" = \"pvmzx\".\"productVariants_id\" left join \"collections\" as \"apucm\" on \"pvmzx\".\"collections_id\" = \"apucm\".\"id\" where (LOWER(\"productVariants\".\"format\") LIKE $1 or LOWER(\"productVariants\".\"isbn\") LIKE $2 or (\"productVariants\".\"sort\" = $3) or LOWER(\"productVariants\".\"status\") LIKE $4 or LOWER(\"productVariants\".\"externalId\") LIKE $5 or LOWER(\"productVariants\".\"language\") LIKE $6 or (\"productVariants\".\"editionVersionNumber\" = $7) or LOWER(\"productVariants\".\"conversionStatus\") LIKE $8 or LOWER(\"productVariants\".\"conversionLog\") LIKE $9 or LOWER(\"productVariants\".\"slug\") LIKE $10 or (\"productVariants\".\"conversionProgress\" = $11)) and ((\"apucm\".\"name\" like $12) and not \"productVariants\".\"status\" = $13) order by \"productVariants\".\"externalId\" asc limit $14) as \"inner\" on \"productVariants\".\"id\" = \"inner\".\"id\" order by \"inner\".\"sort_odajm\" asc - value \"9000000000000\" is out of range for type integer",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

- Create a model with a text property and also at least one number property (to make Directus try to cast value to number)
- Go to collection list and try pasting a value in the style of an EAN, for example: `9000000000000`.

### Directus Version

v9.23.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by drnachio** [comment] 2023-05-09 08:34
It is reproduced in Directus 10

**Comment by drnachio** [comment] 2023-05-09 08:39
Seems to be related with https://github.com/directus/directus/issues/17946

**Comment by br41nslug** [comment] 2023-05-09 10:27
Duplicate of https://github.com/directus/directus/issues/17946

**Closed by br41nslug** 2023-05-09 10:27 UTC
