### ISSUE TITLE
Missing field translation crashes the app

### ISSUE THREAD

**Issue by infomiho** [directus/directus#11490] opened 2022-02-07 20:48 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hey, after upgrading from version `9.4.3` to version `9.5.1` the App just crashed and was unavailable. The login page worked fine, but after login - there was an "Unexpected error" overlay.

### Details
The error message was the following:
```
undefined is not an object (evaluating ‘o.replace’)
```
By call stack we pinpointed the error to this line https://github.com/directus/directus/blob/7c7158a063b22933d9e0abcbf2f48dfa01e03034/app/src/stores/fields.ts#L79

After some further debugging with the JSON received from `/fields` API, we have found that the issue is caused by a field translation object that looks like this:
```
{ language: 'en-US' } 
```

You'll notice it is missing the `translation` string in the above object. Maybe an additional check here would be a good enough fix, here's my proposal: https://github.com/directus/directus/pull/11491

cc: @azrikahar

### To Reproduce

I suspect the translation was added but no translation string was entered.

### How we fixed it
The issue was gone after we removed the translations from the collection
```
curl --location --request PATCH 'https://cms.com/fields/my_collection/available_on?access_token=token' \
--header 'Content-Type: application/json' \
--data-raw '{
	"meta": {
		"translations": null
	}
}'
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### How are you deploying Directus?

k8s

**Comment by azrikahar** [comment] 2022-02-07 22:40
Hi, thanks for pinpointing it but unfortunately this is actually a duplicate of #11458 😅 Really appreciate the breakdown nonetheless!

**Closed by azrikahar** 2022-02-07 22:40 UTC
Labels: Bug (Potential)

**Comment by infomiho** [comment] 2022-02-07 22:59
@azrikahar  sorry for not looking first 🤦🏼‍♂️ thanks for the quick fix!

**Comment by azrikahar** [comment] 2022-02-07 23:07
@infomiho no worries. It really is super helpful when the issue owner has included some debugging/pinpointing as that's already half the battle in resolving issues, not to mention you even paired it with a PR! Just an unfortunate timing/coincidence 😄
