### ISSUE TITLE
Add documentation of VTable 

### ISSUE THREAD

**Issue by LAbigael** [directus/directus#21211] opened 2024-01-26 13:28 UTC
### Describe the Request

It seems like their is a working Component for making tables called VTable, maybe their was some documentation about it (mentionned in other issues). I couldn't find any. Could be added to the existing https://components.directus.io/.
Cheers.

### Maintainence Strategy

When VTable component api changes.

**Comment by paescuj** [comment] 2024-01-26 13:32
Thanks for opening this issue! However this is a duplicate of an existing issue #20607, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #20607 for future updates.

**Closed by paescuj** 2024-01-26 13:32 UTC
Labels: Documentation
