### ISSUE TITLE
graphql mutation requires an Id, REST POST method doesn't 

### ISSUE THREAD

**Issue by DeanKamali** [directus/directus#5875] opened 2021-05-25 16:19 UTC
1) The issue and what you expected to happen
    
    When adding a new item to the collection via REST,  I'm not required to provide an id that gets auto Incremented and my payload is limited to include required fields in the data model. 
    
example:

```
{
    "name": "test"
}
```

however, when using graphql mutation, I must provide id with `Int` value like so: 

```
mutation {
	create_test_item(data: {id: 100, name: "Hello world!"}) {
    name
  }
}
```
otherwise, I get an error: 

```
{
  "errors": [
    {
      "message": "GraphQL validation error.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_EXCEPTION",
        "graphqlErrors": [
          {
            "message": "Field \"create_tests_input.id\" of required type \"Int!\" was not provided.",
            "locations": [
              {
                "line": 2,
                "column": 30
              }
            ]
          }
        ]
      }
    }
  ]
}
```
 as per documentation here, providing an Id is not required
    
    https://docs.directus.io/reference/api/items/#create-an-item 
    

2) My environment:
    "directus": "^9.0.0-rc.69"
    "pg": "^8.6.0"

**Comment by rijkvanzanten** [comment] 2021-05-25 18:13
Duplicate of https://github.com/directus/directus/issues/5859, which is a duplicate of https://github.com/directus/directus/issues/5723, which was closed in https://github.com/directus/directus/commit/246c55266b78ae063408dbc1b04d1797bd85e476

**Closed by rijkvanzanten** 2021-05-25 18:13 UTC
