### ISSUE TITLE
gatsby-source-directus fails on build with gatsby 4 

### ISSUE THREAD

**Issue by cdanny358** [directus/directus#10603] opened 2021-12-18 17:52 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

`gatsby-source-directus` fails on build when using Gatsby 4, although for some reason it works in development mode. In section 2 of Gatsby's [v3 -> v4 plugin migration guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/), they state that you no longer can call `createRemoteFileNode` inside `createResolvers`, and offer an alternative means to create file nodes. `gatsby-source-directus` is still using the old, now-disallowed method of creating remote file nodes.

### To Reproduce

Run `yarn build` or `npm build` on a Gatsby 4 project using `gatsby-source-directus`. The build fails when first it encounters a remote image. Again, it works in development mode.

### Errors Shown

In the Gatsby terminal: 

`failed Building static HTML for pages`
`WebpackError: TypeError: Cannot read properties of null`

when encountering remote images.

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL

### What browser are you using?

Any

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by joselcvarela** [comment] 2021-12-20 06:38
Hello @cdanny358 
I am currently using `"gatsby": "^4.3.0",` and both development and build are working fine.
Why do you think the error is coming from our plugin? Is it possible to share more context or a stack trace of the error?
Also, how are you using images? I am using `gatsby-plugin-image`

**Comment by rijkvanzanten** [comment] 2021-12-30 23:25
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-12-30 23:25 UTC
Labels: Package: gatsby-source-directus, Can't Reproduce

**Comment by sean-binary** [comment] 2022-01-03 15:44
Hello @joselcvarela, I am facing something similar to @cdanny358 here. I am using Directus along with gatsby-plugin-image as well. Do we not need to migrate the directus source plugin as per the new Gatsby API that @cdanny358 mentioned [here](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-source-plugin-from-v3-to-v4/#the-new-way-1)?

**Comment by cdanny358** [comment] 2022-01-03 17:42
I was able to get my project to build by adding `GATSBY_CPU_COUNT=2` before `gatsby build` in `package.json`, otherwise I'd get errors similar to what you're seeing above. Still, Gatsby's v4 docs explicitly say that the current plugin shouldn't work, so I have to assume at some point this'll become a problem.

**Comment by joselcvarela** [comment] 2022-01-04 06:43
Hey @sean-binary 

In fact we do have upgrade our plugin to work with Gatsby v4. You can check it here https://github.com/directus/directus/pull/10422

Do you have any idea why you are seeing that? I think I would need a big project to test this, but currently I do not have any.
We believe Gatsby does things in parallel now, in contrast of the sequential process they were doing before.
You can try what @cdanny358 mentioned but you can also try to increase points on rate limiter https://docs.directus.io/configuration/config-options/#rate-limiting

**Comment by rijkvanzanten** [comment] 2022-01-04 15:02
It looks like gatsby automatically does retries and rate-limiting for data fetching, but doesn't do so in the gatsby-image-plugin. When you try to build a website, gatsby 4 will request all images at the same time it seems, causing the rate limiter to (correctly) kick in.

**Comment by cdanny358** [comment] 2022-01-06 15:30
FYI, I tried rate limiting with 25, 50, and 100 requests / second, and still got 429 errors (Too Many Requests) from Gatsby each time I tried to do a build without using `GATSBY_CPU_COUNT=2`.

**Comment by JakubOlejnik1155** [comment] 2022-05-17 07:04
@cdanny358 
It also doesn't work. Still the same error
