### ISSUE TITLE
Settings bookmark not working

### ISSUE THREAD

**Issue by mrtopher** [directus/directus#1972] opened 2017-11-28 14:46 UTC
## Version Info
  - Directus version and branch: 6.4.24 (latest)
  - PHP version: 7.1.8
  - MySQL version: 5.6.35
  - Web server: Apache 
  - OS name and version: macOS High Sierra 

## Expected Behavior
When I click on the bookmark listed on the left I expect it to take me to the Global Settings screen where I clicked the bookmark icon next to the page title.

## Actual Behavior
When I click the bookmark it just displays the item listing for my first table.

## Steps to Reproduce
 1. Navigate to the Global Settings screen.
 2. Click the bookmark icon to the right of the page title.
 3. Navigate away from this screen to a table listing or someplace else.
 4. Click the bookmark in the left nav.

I was able to reproduce the issue with trying to bookmark tables & inputs too. Not sure if it's settings specific or bookmark specific.

**Comment by WellingGuzman** [comment] 2017-11-28 20:15
I'm not able to reproduce this issue @mrtopher, would you care to share a schema?

What's the name/title of the bookmark?

**Comment by mrtopher** [comment] 2017-11-28 21:14
Hi @WellingGuzman, I have a screen recording here so you can get a better idea of what I'm seeing: http://recordit.co/PtiSPdcwME

**Comment by WellingGuzman** [comment] 2017-11-30 10:47
Thanks for the video, I'm working on a fix.

**Comment by WellingGuzman** [comment] 2017-11-30 12:28
Fixed by https://github.com/directus/directus/commit/a58a92d36f774c4ef164922b6d6d698cb008627e

**Closed by WellingGuzman** 2017-11-30 12:28 UTC
Labels: 3. Major, Bug
