### ISSUE TITLE
Many-to-one field not saving

### ISSUE THREAD

**Issue by xunra** [directus/directus#1719] opened 2017-08-02 08:22 UTC
## Version Info
  - Directus version and branch: 6.4 master on commit 228bc94
  - PHP version: 7.0.18
  - MySQL version:  5.7.19
  - Web server: Apache
  - OS name and version: Ubuntu 16.04

## Expected Behavior

After chaning a many to one field the new value is saved. If it's a field with "allow null" selected the value can be null or not selected.

## Actual Behavior

After the initial save or first save the value can't be changed.

## Steps to Reproduce
 1.  Install latest directus from master branch.
 2. Create a new table with a many to one field with the setting allow null selected.
 3. Create a few items without filling in the many to one field.
 4. Open a random item, change the many to one field to some value.
 5. Reopen the same item and try to change to value again.

## Schema Dump, Logs, or Screenshots

Table setup:
![image](https://user-images.githubusercontent.com/4763157/28864014-ccfe26d0-7773-11e7-8d50-e4bd02024dad.png)
M2O field setup:
![image](https://user-images.githubusercontent.com/4763157/28864026-d80e84a2-7773-11e7-9473-91b292080e5c.png)
![image](https://user-images.githubusercontent.com/4763157/28864031-db26ab06-7773-11e7-92c8-2bd3f62fc52c.png)
Items:
![image](https://user-images.githubusercontent.com/4763157/28864049-e4080d32-7773-11e7-87f8-7010821b1b4e.png)
Chaning an item:
![image](https://user-images.githubusercontent.com/4763157/28864060-ed6c3d9e-7773-11e7-877a-ada181a426d7.png)
After save:
![image](https://user-images.githubusercontent.com/4763157/28864064-f405451a-7773-11e7-86f5-1f5de17a0556.png)

**Comment by WellingGuzman** [comment] 2017-08-02 17:53
Hey @xunra,

Does the value get saved on the database?

**Comment by xunra** [comment] 2017-08-02 19:38
Hey @WellingGuzman 

No, no value gets saved.

**Comment by WellingGuzman** [comment] 2017-08-02 21:19
@xunra does it work on `develop`? can you share a schema so we can reproduce with your same data? I tried on both and it was working as expected.

**Comment by xunra** [comment] 2017-08-03 06:45
@WellingGuzman 

While I can save it once, it still has issues when I try to change the option after saving and a javascript error when I try to select the first option - "Select from below" to null it.
Also the select options have no texts.

``````````
app/core/interfaces/many_to_one/interface.js:20` Uncaught TypeError: Cannot read property 'toJSON' of undefined
    at child.change select (interface.js?bust=26968b0…:20)
    at HTMLDivElement.dispatch (jquery-1.11.0.js:4624)
    at HTMLDivElement.r.handle (jquery-1.11.0.js:4292)
``````````

Schema

``````````
INSERT` INTO `directus_columns` (`id`, `table_name`, `column_name`, `data_type`, `ui`, `relationship_type`, `related_table`, `junction_table`, `junction_key_left`, `junction_key_right`, `hidden_input`, `hidden_list`, `required`, `sort`, `comment`, `options`) VALUES
(58, 'test', 'id', 'INT', 'primary_key', NULL, NULL, NULL, NULL, NULL, 1, 0, 0, NULL, NULL, NULL),
(59, 'test', 'sort', 'INT', 'sort', NULL, NULL, NULL, NULL, NULL, 1, 0, 0, NULL, NULL, NULL),
(60, 'test', 'status', 'INT', 'status', NULL, NULL, NULL, NULL, NULL, 1, 0, 0, NULL, NULL, NULL),
(61, 'test', 'title', 'VARCHAR', 'text_input', NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 9999, '', NULL),
(62, 'test', 'parent', 'INT', 'many_to_one', 'MANYTOONE', 'test', NULL, NULL, 'parent', 0, 0, 0, 9999, '', '{"id":"many_to_one","visible_column":"Parent","visible_column_template":"{{title}}","visible_status_ids":"1,2","allow_null":1}');

CREATE TABLE `test` (
  `id` int(11) NOT NULL,
  `status` int(11) NOT NULL DEFAULT '2',
  `sort` int(10) UNSIGNED NOT NULL,
  `title` varchar(100) DEFAULT NULL COMMENT '''''',
  `parent` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `test` (`id`, `status`, `sort`, `title`, `parent`) VALUES
(1, 1, 0, 'one', 2),
(2, 1, 0, 'two', 3),
(3, 1, 0, 'three', 2);

ALTER TABLE `test`
  ADD PRIMARY KEY (`id`);
  
ALTER TABLE `test`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

INSERT INTO `directus_privileges` (`id`, `table_name`, `allow_view`, `allow_add`, `allow_edit`, `allow_delete`, `allow_alter`, `group_id`, `read_field_blacklist`, `write_field_blacklist`, `nav_listed`, `status_id`) VALUES
(21, 'test', 2, 1, 2, 2, 1, 1, NULL, NULL, 1, NULL);
``````````

**Comment by WellingGuzman** [comment] 2017-08-03 14:38
@xunra does the user has permission to read data from `parent`?

Thanks for the schema, I will test and see if I can replicate.

**Comment by xunra** [comment] 2017-08-03 15:13
Yes it does.

For now I have switched back to 6.3.x and everything works great.

**Comment by WellingGuzman** [comment] 2017-08-03 15:15
@xunra can you share the schema for that table? and why the visible_column option is `Parent` is that a table name on `parent` table?

**Comment by WellingGuzman** [comment] 2017-08-03 18:48
I noticed that you make a many to one, to the same table? is that the behavior you want to accomplish related one record from `test` to another record from `test`?

**Comment by WellingGuzman** [comment] 2017-08-03 18:50
I've been trying to reproduce this without any luck, and it seems to be working perfectly.

Can you clear your browser cache and see if that solves it?

**Comment by WellingGuzman** [comment] 2017-08-03 20:06
Hey @xunra, can you test with this commit (https://github.com/directus/directus/commit/443e4449d7fe9a4991257f5f9deb8c92ee915286) on `develop` branch?

**Comment by dsivokhin** [comment] 2017-08-07 13:55
Hi @WellingGuzman, I update all commits, but I have same problem, M2O field to the same table, not saving, if change select option and save, notice - `Warning
Nothing changed, nothing saved`, if change somthing else and save, value M2O not save in database.

And field type 'M2O Typeahead' have bad styles, dropdown list not white.

And another problem if value selected, and try set emty value, from select options 
`Error
Error: Uncaught TypeError: Cannot read property 'toJSON' of undefined
File: /app/core/interfaces/many_to_one/interface.js?bust=40311cec1bdd6961ee542c26c122d2aed777525a
Line:20`

**Comment by WellingGuzman** [comment] 2017-08-07 15:47
We are aware of the dropdown being without any style, we should be working on it soon.

If the issue still persists let us know, please share a reproducible step and we will re-open it.

This ticket has been closed by https://github.com/directus/directus/commit/2ea2b8e4d0f5ce09ce8c486f18d0da6c3c7314a6

**Closed by WellingGuzman** 2017-08-07 15:47 UTC
Labels: Can Not Duplicate
