### ISSUE TITLE
Auto generated translations collection gets created as singleton when entity collection is singleton

### ISSUE THREAD

**Issue by lluishi93** [directus/directus#3245] opened 2020-11-30 12:35 UTC
1. Create a collection, make it singleton
2. Add a translations field (auto-generate)
3. Create a bunch of text fields in the translations collection
4. Delete one of those text fields
5. Go to the collection
6. Try to open some of the translations
7. Check the following error:

![image](https://user-images.githubusercontent.com/14786440/100610941-d7ec1a00-3310-11eb-8040-4df785fa9f10.png)

![image](https://user-images.githubusercontent.com/14786440/100610983-e803f980-3310-11eb-96a4-72fe0257a78e.png)

IDK if this information is going to be enough. Please if you need the full database backup, let me know.

EDIT: It is also happening when a field is edited. This collection of ours has 100+ fields, FYI

**Comment by lluishi93** [comment] 2020-12-01 09:19
Using the following backup fixes the problem, until one field is deleted again:

```
rm labels-fields.sql

touch labels-fields.sql

echo "DELETE FROM directus_fields where collection = 'labels_translations';" >> labels-fields.sql

echo "\n" >> labels-fields.sql

docker exec -i mysql mysqldump -u root --password=password db --no-create-info --compact --tables directus_fields --where="collection = 'labels_translations'" >> labels-fields.sql

echo "\n" >> labels-fields.sql

echo "DROP TABLE labels_translations;" >> labels-fields.sql
docker exec -i mysql mysqldump -u root --password=password db labels_translations --no-data --compact >> labels-fields.sql
```

**Comment by lluishi93** [comment] 2020-12-02 12:25
LOL, I figured out. The translations collection was a singleton.
The thing is that when a collection is created as a singleton, and after that you add an auto-generated translations collection, this one gets created as a singleton as well, causing the problem described above.
@rijkvanzanten @benhaynes JTLYK, would be appropriate to make sure that the auto-generated translations collection gets created without being a SINGLETON.

**Comment by rijkvanzanten** [comment] 2020-12-02 14:57
Wooooow good catch!

**Comment by rijkvanzanten** [comment] 2021-01-13 21:48
@lluishi93 

> The thing is that when a collection is created as a singleton, and after that you add an auto-generated translations collection, this one gets created as a singleton as well, causing the problem described above.

The generated translations collection doesn't inherit any fields from the current collection. Is there a chance this was wrongly configured at one point accidentally? I can't reproduce this on my end. Does it still happen for you when auto-generating new translations

**Comment by benhaynes** [comment] 2021-02-10 18:12
Hey @lluishi93 — any thoughts on this? We'll try to reproduce this one more time, but if we're unsuccessful, we'll close this as a user error.

**Comment by lluishi93** [comment] 2021-02-15 10:23
It probably doesn't happen anymore. this can be closed IMHO

**Closed** 2021-02-15 14:40 UTC
Labels: Needs More Info
