### ISSUE TITLE
npm install directus + npx directus init not working

### ISSUE THREAD

**Issue by dieriba** [directus/directus#16262] opened 2022-11-02 00:01 UTC
### Describe the Bug

When I try to install directus in my Digital Ocean droplet I get error with the following command : npx directus init

### To Reproduce

npm install directus@latest
npx directus init

### Errors Shown

Error: Cannot find module '@authenio/samlify-node-xmllint'
Require stack:
- /var/www/api.ataera/directus/node_modules/directus/dist/auth/drivers/saml.js
- /var/www/api.ataera/directus/node_modules/directus/dist/auth/drivers/index.js
- /var/www/api.ataera/directus/node_modules/directus/dist/auth.js
- /var/www/api.ataera/directus/node_modules/directus/dist/services/authentication.js
- /var/www/api.ataera/directus/node_modules/directus/dist/services/index.js
- /var/www/api.ataera/directus/node_modules/directus/dist/middleware/respond.js
- /var/www/api.ataera/directus/node_modules/directus/dist/controllers/activity.js
- /var/www/api.ataera/directus/node_modules/directus/dist/app.js
- /var/www/api.ataera/directus/node_modules/directus/dist/server.js
- /var/www/api.ataera/directus/node_modules/directus/dist/cli/index.js
- /var/www/api.ataera/directus/node_modules/directus/dist/cli/run.js
- /var/www/api.ataera/directus/node_modules/directus/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/var/www/api.ataera/directus/node_modules/directus/dist/auth/drivers/saml.js:30:32)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/api.ataera/directus/node_modules/directus/dist/auth/drivers/saml.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/auth/drivers/index.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/auth.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/services/authentication.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/services/index.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/middleware/respond.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/controllers/activity.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/app.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/server.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/cli/index.js',
    '/var/www/api.ataera/directus/node_modules/directus/dist/cli/run.js',
    '/var/www/api.ataera/directus/node_modules/directus/cli.js'
  ]
}

### What version of Directus are you using?

9.19

### What version of Node.js are you using?

v18.12.0

### What database are you using?

v13

### What browser are you using?

edge

### How are you deploying Directus?

digital ocean

**Comment by freekrai** [comment] 2022-11-02 00:05
Duplicate of https://github.com/directus/directus/issues/16259 and fixed with https://github.com/directus/directus/pull/16260

**Closed by freekrai** 2022-11-02 00:05 UTC

**Comment by hailetrung** [comment] 2022-11-02 00:20
@freekrai I know it was fixed but the `npm init directus-project my-project` still not working as expected til now🥲
