### ISSUE TITLE
Documentation on WebSocket usage with the typescript SDK

### ISSUE THREAD

**Issue by sylro** [directus/directus#20841] opened 2023-12-21 19:28 UTC
### Describe the Request

Hello there,

I'm quite new on Directus, but I think it's a very good product. 

Though, I'm having trouble implementing a websocket real time connection with the typescript SDK provided. I couldn't found any documentation on the website, only some snippets within the github discussions. I found the documentation with vanilla javascript, but using the SDK on this subject is more complex I think. 

Is it possible to have a complete example of an implementation? Maybe the same case as the vanilla javascript one.

Thanks!

PS: I've managed to start a subscription, but I'm stuck to retrieve and using the events after that.
```
const directus = createDirectus('http://localhost:8055').with(rest()).with(realtime()).with(authentication('cookie', { credentials: include' }));

directus.refresh();

const { subscription } = await directus.subscribe('state', {
        event: 'create'
      });

### Maintainence Strategy

Just once I guess

**Comment by br41nslug** [comment] 2023-12-21 19:39
Closing this as duplicate of https://github.com/directus/directus/issues/20817 while those docs are still being worked on this is the best example available in the docs.
https://docs.directus.io/packages/@directus/sdk/#real-time beyond type hints and passing in a schema there is little difference between using it in JS or TS.

**Closed by br41nslug** 2023-12-21 19:39 UTC
Labels: Documentation
