### ISSUE TITLE
Deleting an external storage file

### ISSUE THREAD

**Issue by arladmin** [directus/directus#7960] opened 2021-09-10 00:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have an external (S3) storage configured.
When delete a file (directus_files) from the Admin app/API, i expected the file to also get deleted from the external storage, just like it is for local files. But that didn't happen. 

This would create a huge issue where there could potentially be thousands of orphan files left in the external storage bucket/folder attached to Directus.

### To Reproduce

1. Attach an external S3 storage to Directus
2. Upload a file to the said storage
3. Now delete it. The file gets deleted from Directus but is still found in the external storage

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

16.5.0

### What database are you using?

Postgres 12

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu

### How are you deploying Directus?

Docker

**Comment by emrahnazif** [comment] 2021-09-11 08:51
I confirm same issue.
latest version of directus with digitalocean s3 storage.

**To Reproduce:**

- clean install directus
- setup a s3 storage
- upload a file
- delete it
- check the s3 storage

**What version of Directus are you using?**
v9.0.0-rc.92
**What version of Node.js are you using?**
16.5.0
**What database are you using?**
Postgres 12
**What browser are you using?**
Chrome
**What operating system are you using?**
Ubuntu 18.04
**How are you deploying Directus?**
digitalocean marketplace

**Comment by paulboudewijn** [comment] 2021-11-22 21:31
Perhaps this is related to issue #8899 and PR #9126.

**Comment by marvinisaac** [comment] 2021-11-23 14:48
I'm getting the same issue while also using DigitalOcean's Spaces storage.

To reproduce:
- Run Directus via `docker-compose`
- Setup and connect DO Spaces
- Upload an image (Success)
- Delete (Error message in UI and in Docker logs attached)
- Database record gets deleted
- Image is still in storage (Filename is same as in error but with `.jpg` extension)

**What version of Directus are you using?**
v9.0.1

**What version of Node.js are you using?**
n/a (Comes with the container image)

**What database are you using?**
MariaDB 10.6.4

**What browser are you using?**
Chrome

**What operating system are you using?**
Windows 10

**How are you deploying Directus?**
Docker / `docker-compose`

![screenshot-01](https://user-images.githubusercontent.com/4396841/143045244-804d4d31-7952-48dd-b2ac-5c114712e068.png)

![screenshot-02](https://user-images.githubusercontent.com/4396841/143045252-ab130c77-aff1-4fe5-be7b-7d117fb19a25.png)

![screenshot-03](https://user-images.githubusercontent.com/4396841/143046048-d3dad64c-d181-48bb-9f49-3fecaa298401.jpg)

**Comment by emrahnazif** [comment] 2022-01-07 14:54
> #9126

This is still a problem for me. Any solution to this? 
v9.4.2

**Comment by marvinisaac** [comment] 2022-01-11 11:26
I switched from DigitalOcean Spaces to Google Cloud Storage. Everything is working OK now

**Comment by calebyusuf** [comment] 2022-02-12 21:58
> This is still a problem for me. Any solution to this? v9.4.2
Although I am running  v9.5.1

I was still getting this issue but just resolved it by adding the ListBucket and ListBucketVersions permissions to my S3 bucket policy _(although i don't think ListBucketVersions is necessary)_

List Bucket is used in node_modules/@directus/drive-s3/dist/AmazonWebServicesS3Storage.js

Hope this helps!!

**Comment by rijkvanzanten** [comment] 2022-02-28 20:54
I think there has been an update in this cold-case: https://github.com/directus/directus/issues/11641

Could you confirm the value used for ENDPOINT @calebyusuf?

**Comment by tarcon** [comment] 2022-04-05 12:49
This still does not seem to work in 9.8 using S3 as storage adapter

Deleting via the admin app or DELETE /files/:id rest api is successful (204) and removes the metadata in directus_files, but leaves the files in S3

**Comment by rijkvanzanten** [comment] 2022-04-05 13:56
@tarcon What AWS permissions are you using for the S3 bucket for the credentials used with Directus?

**Comment by tarcon** [comment] 2022-04-06 07:34
The directus log with loglevel trace do not show any error while deleting files. 

My private bucket has disabled ACLs. I have not set up iam policies for the access.
I work with a pretty lightweight config. The directus server accesses the bucket directly within a secure private network.

Am I missing something?

`

STORAGE_LOCATIONS: "s3",
 STORAGE_S3_DRIVER: "s3",
      STORAGE_S3_ROOT: "./files",
      STORAGE_S3_KEY: "",
      STORAGE_S3_SECRET: "",
      STORAGE_S3_BUCKET: bucket.bucketName,
      STORAGE_S3_REGION: "eu-central-1",
      STORAGE_S3_ENDPOINT: "s3.amazonaws.com",
      STORAGE_S3_ACL: "",
      `

**Comment by rijkvanzanten** [comment] 2022-04-06 14:34
I'm assuming it's because the bucket might be configured to allow anybody to put files, but not delete files 🤔

**Comment by rijkvanzanten** [comment] 2022-04-15 21:00
We haven't been able to reproduce this so far.. For all the instances we've debugged, it has been due to access control rules in S3 itself (eg incorrect configuration for `s3:deleteObject` and/or other S3 rules). I'll close this for now, but happy to keep discussing / debugging 👍🏻

**Closed by rijkvanzanten** 2022-04-15 21:00 UTC
Labels: Can't Reproduce

**Comment by mattbisme** [comment] 2022-05-27 07:53
I believe that I have figured this out. I've been using Backblaze's B2 (S3 compatible) storage; I was getting the same problem. The short answer seems to be that *S3 storage does not like relative paths*. 

So, in @tarcon's example, change
```
STORAGE_S3_ROOT="./files"
```
to
```
STORAGE_S3_ROOT="/files"
```

This is what worked for me, at least.

It might be worth updating the docs to reflect this. I also had the immediate thought that it was a permissions issue of some kind, but it is so much simpler than that!

**Comment by rijkvanzanten** [comment] 2022-05-27 13:50
cc @erondpowell

**Comment by tarcon** [comment] 2022-06-10 09:39
I can confirm this fixes my problem. Good job!

**Comment by rijkvanzanten** [comment] 2023-04-13 18:05
@chris-mcdonald-dev Mind opening a new issue? This one was marked resolved nearly exactly a year ago, which means that your problem is very likely caused by something else 🙂
