### ISSUE TITLE
Selecting a field for Filter in Admin UI fails

### ISSUE THREAD

**Issue by sagerio** [directus/directus#7048] opened 2021-07-28 17:26 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Seleting a field for filter in the "Advanced Filter" Section leads to no field selected, but the browsers devconsole gives the following output:

```
vendor.0c2f3d32.js:1 TypeError: Cannot read property '0' of undefined
    at addFilterForField (index.ebe38fc0.js:1)
    at Nt (vendor.0c2f3d32.js:1)
    at It (vendor.0c2f3d32.js:1)
    at ln (vendor.0c2f3d32.js:1)
    at g.onAdd.t.<computed>.t.<computed> (index.ebe38fc0.js:1)
    at Nt (vendor.0c2f3d32.js:1)
    at It (vendor.0c2f3d32.js:1)
    at ln (vendor.0c2f3d32.js:1)
    at e.field.children.g.onClick.t.<computed>.t.<computed> (index.ebe38fc0.js:1)
    at Nt (vendor.0c2f3d32.js:1)
```

### To Reproduce

1. In the admin UI, go to "Collections"
2. select any collection
3. on the right panel, click "Advanced filter"
4. click "Add filter"
5. select any field

### What version of Directus are you using?

9.0.0-rc.86

### What version of Node.js are you using?

14.15.1

### What database are you using?

SQLite 3.31.1

### What browser are you using?

Microsoft Edge 92.0.902.55

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Directus on NAS, Client locally

**Comment by rijkvanzanten** [comment] 2021-07-28 17:27
Duplicate of https://github.com/directus/directus/issues/7004

**Closed by rijkvanzanten** 2021-07-28 17:27 UTC
Labels: Bug (Potential)
