### ISSUE TITLE
not able create uuid_generate_v4();

### ISSUE THREAD

**Issue by jyotivarade** [directus/directus#5421] opened 2021-05-03 06:13 UTC
---

### Project details
Directus Version: 9.0.0-rc.61
Environment: production
OS: Linux 5.4.0-72-generic
Node: 10.24.1

**Comment by paescuj** [comment] 2021-05-03 09:08
Can you provide more details? E.g. in which file the error has occurred, etc.
Could be related to recent version bump of `@lukeed/uuid` (https://github.com/directus/directus/commit/e7c5a9f35eb6e451a8c07d0ceca38872226d3db6)

**Comment by jyotivarade** [comment] 2021-05-03 09:24
![image](https://user-images.githubusercontent.com/50901499/116859943-6517ff80-ac1e-11eb-89ad-e9ea0063f8e8.png)
I have created migration file to create tables and function. 

in table i have added id as uuid  as like below 
 id uuid DEFAULT public.uuid_generate_v4() NOT NULL,

![image](https://user-images.githubusercontent.com/50901499/116860233-e374a180-ac1e-11eb-8959-f65ce8f5dd16.png)
when i am trying to create location form Directus UI i am getting below error.

![image](https://user-images.githubusercontent.com/50901499/116860422-2cc4f100-ac1f-11eb-85ed-d1a1d37cbff6.png)
 
and i tried to create location from Dbeaver (pgADmin). and i am able create location and also uuid is created 
![image](https://user-images.githubusercontent.com/50901499/116860645-83322f80-ac1f-11eb-99b9-16749b5ff8de.png)

**Comment by paescuj** [comment] 2021-05-03 09:30
Thanks! Seems to be a duplicate of https://github.com/directus/directus/issues/5358.

**Comment by jyotivarade** [comment] 2021-05-03 09:44
@paescuj , is this issue related to version. because i have also install extension
![image](https://user-images.githubusercontent.com/50901499/116862329-34d26000-ac22-11eb-8e3a-419f58fd786f.png)

**Comment by paescuj** [comment] 2021-05-03 09:48
Yes, because this type of primary key is currently not supported by Directus.

**Comment by rijkvanzanten** [comment] 2021-05-03 13:55
Duplicate of https://github.com/directus/directus/issues/5358#issuecomment-830328640

**Closed by rijkvanzanten** 2021-05-03 13:55 UTC
