### ISSUE TITLE
Detail group field do not accept updates via the app

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#16357] opened 2022-11-08 17:10 UTC
### Describe the Bug

Added a "Detail group field" and tried to update a translation, i receive an error and settings are not updated using an admin user

{
  "errors": [
    {
      "message": "Alias type cannot be changed",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}

### To Reproduce

- Add a details group field on a collection via app
- update any setting and save

### Errors Shown

{
  "errors": [
    {
      "message": "Alias type cannot be changed",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

Directus Cloud

### What database are you using?

Directus Cloud

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by licitdev** [comment] 2022-11-08 17:25
Duplicate of #16315

**Closed by licitdev** 2022-11-08 17:25 UTC
Labels: Duplicate
