### ISSUE TITLE
M2M Relationship Forbidden Access by a role user (Even after fully enabling ALL permissions for the role)

### ISSUE THREAD

**Issue by sksar** [directus/directus#5732] opened 2021-05-17 19:07 UTC
In my Directus installation,
there are the following collections:
Products,
Sizes,

In the products collection, there is a field called sizes, which is a Many to Many relationships with Sizes.
The junction collection products_sizes was created by Directus.
When I log in to Directus as an Administrator account, I am able to add / edit / remove items from the sizes many to many relationship field of products.
However when I log in as a different user, (not admin user), and when I try to add / edit / remove the same items it shows this error (In the UI)
```
{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}
 ```

However, I went to the role and enabled full access for everything, including all of Directus collections. And the error stays the same. 

To replicate I tried and created a different Many to Many relationship, however, I got the same results each time.

---

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: Linux 5.4.0-73-generic
Node: 14.17.0

**Comment by rijkvanzanten** [comment] 2021-05-17 19:10
Duplicate of https://github.com/directus/directus/issues/5624

**Closed by rijkvanzanten** 2021-05-17 19:10 UTC
