### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by kevstev01** [directus/directus#4213] opened 2021-02-22 11:22 UTC
1) Trying to run the rc9 v41 docker image fails with an SQLite error during the database migration stage, with an error "Sqlite does not support alter column."

2) docker run -i -p 8055:8055 directus/directus:v9.0.0-rc.41

3) error occurs since rc 38 on Windows 10 using Docker Desktop, Docker Engine v20.10.2
Trying to use the docker image found on github and docker hub results in the same issue

**Comment by rijkvanzanten** [comment] 2021-02-22 15:46
Duplicate of https://github.com/directus/directus/issues/2904

**Closed by rijkvanzanten** 2021-02-22 15:46 UTC
