### ISSUE TITLE
npx directus-extension create <type> <name> doesn't work

### ISSUE THREAD

**Issue by rassvetdk** [directus/directus#7088] opened 2021-07-30 06:34 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When running let's say
```
npx directus-extension create module dashboard
```
you get the following error

> UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, lstat '/Volumes/Data/Code/directus-app-platform-pure/node_modules/@directus/extension-sdk/templates/common'

Looking into extension-sdk module templates the latest version 9.0.0-rc.87 the common folder is missing

![image](https://user-images.githubusercontent.com/28866431/127610921-cbdeec33-9433-49e1-b9f5-e8bb1a7ada3c.png)

### To Reproduce

1. Install extension sdk
2. run `npx directus-extension create module dashboard`

### What version of Directus are you using?

9.0.0-rc.87

### What version of Node.js are you using?

v14.17.3

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by paescuj** [comment] 2021-07-30 07:00
Duplicate of #6932

**Closed** 2021-07-30 13:27 UTC
Labels: Bug (Potential)
