### ISSUE TITLE
Translation bug

### ISSUE THREAD

**Issue by hrabovyiserhii** [directus/directus#15606] opened 2022-09-16 08:24 UTC
### Describe the Bug

1. If you fill in the text in the field with English, then switch to French and also fill in the value with text, then when switching back to English, the field previously filled will be empty.
2. We have 3 elements in translations array

### To Reproduce

We have only two languages (en and fr).
1. Create new table, then create new field with translations type, then create new field(input) in translations table.
Then If you fill in the text in the field with English, then switch to French and also fill in the value with text, then when switching back to English, the field previously filled will be empty. Look at pictures(1, 2, 3)
2. Create another one field(input) and fill in the fields in the same order as in the picture number 4
You'll see when you after filling field 1 you will enter 1 character in field 2 and you will see that the text is copied from field 1 to field 2. Then delete text from field 2 and you'll see that field 1 and field 2 will be cleared.  
When you enter one letter in field number 3, another character will appear in field 1(look at picture 5)
Result after saving you can see in the picture 6. 
3. Try copying the text in field1, then field2, then field3, and you will see that your field4 will be filled in automatically. But if you'll change field4, you'll see that your field1 and field3 will be cleared. Then if you start to enter in field1 you'll see that field1 will be changed to previous value. Then try to enter text to field3 and save. You'll that you have 3 elements in translations array. 

### Errors Shown

<img width="859" alt="1" src="https://user-images.githubusercontent.com/103687785/190586352-875c35a4-1667-448c-8b72-8230c2f3e795.png">
<img width="852" alt="2" src="https://user-images.githubusercontent.com/103687785/190586355-8d99d6e6-3cb2-4263-87a0-5e8e5fede98c.png">
<img width="839" alt="3" src="https://user-images.githubusercontent.com/103687785/190586358-e4f32205-4822-480e-bb77-7b0a828e14aa.png">
<img width="854" alt="4" src="https://user-images.githubusercontent.com/103687785/190588512-691fce55-2a05-4816-90ae-b3fad4266813.png">
<img width="853" alt="5" src="https://user-images.githubusercontent.com/103687785/190589891-1ab8c470-cf5d-49dc-915a-9a91b860e894.png">
<img width="728" alt="6" src="https://user-images.githubusercontent.com/103687785/190590320-d722931f-4dd6-4d93-9208-bfcfcfa07cf2.png">

### What version of Directus are you using?

9.17.4

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by licitdev** [comment] 2022-09-16 08:40
Duplicate of https://github.com/directus/directus/issues/15460
It will be fixed in the next release. Thank you.

**Closed by licitdev** 2022-09-16 08:40 UTC
