### ISSUE TITLE
M2M - Newly added items dissappear when sorting

### ISSUE THREAD

**Issue by ralrom** [directus/directus#5294] opened 2021-04-27 16:13 UTC
**1) The issue and what you expected to happen**
When adding multiple existing items to a Many-to-Many field, sorting the newly added items causes all of them to re-render as the same item.

Here's a screen recording (bug is visible at around 0:16 in the video) https://youtu.be/pLBonYtYfVI

**2) Exact steps to reproduce this issue**

1. Create a Many-to-Many field with a sort field (integer)
2. Create multiple items that can be added to the many-to-many field
3. Add multiple items in the Many-to-Many field at once
4. Try sorting the items, all of the new items will take the appearance of one of the newly added items
5. Some items might also disappear

(It seems to be an index issue)

**Workaround:**
As soon as you add the multiple items in the many-to-many field, save the document before doing any sorting. Once the document has been saved, it's possible to sort without the bug.

**3) Your environment:**

- directus/directus:v9.0.0-rc.61
- Sqlite3
- Docker
- Chrome Version 90.0.4430.93

**Comment by rijkvanzanten** [comment] 2021-04-27 16:14
Duplicate of https://github.com/directus/directus/issues/3721

**Closed by rijkvanzanten** 2021-04-27 16:14 UTC
