### ISSUE TITLE
Cannot remove collection

### ISSUE THREAD

**Issue by willemmulder** [directus/directus#14717] opened 2022-07-28 11:55 UTC
### Describe the Bug

I'm trying to delete a collection (because I'm not able to create records for that collection somehow, but that'a another issue) but whenever I try that I get an error

![image](https://user-images.githubusercontent.com/70933/181498433-dfd0405d-7a0f-4125-a58b-4bd160e757a7.png)

### To Reproduce

Create a collection

Then add a tree view field. Then delete that field again.

Now the collection cannot be deleted anymore.

### Errors Shown

{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'sql')",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

SQLite (Directus Cloud with free project... that's SQLite right?)

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus Cloud

**Comment by azrikahar** [comment] 2022-07-28 12:09
Should be the same root cause as #13816 👍 Closing as duplicate.

**Closed by azrikahar** 2022-07-28 12:09 UTC

**Comment by willemmulder** [comment] 2022-07-28 12:22
@azrikahar  Not sure if this is a duplicate..?  

The other issue is when there are self-referencing fields on the collection. But in this case, there *was* a self-referencing field on the collection, but that field was deleted. Or do deleted fields remain active somehow? E.g. a delete really is a soft-delete of kinds?

Thanks!

**Comment by azrikahar** [comment] 2022-07-28 12:36
> But in this case, there was a self-referencing field on the collection, but that field was deleted. 

Was the self-referencing field the Treeview field, or the Foreign Key field? Here's my attempt at reproducing it, which still fits the referenced issue's root cause:

https://user-images.githubusercontent.com/42867097/181505565-2fb74eab-545b-42e4-8e3e-525b3ff84c96.mp4

> Or do deleted fields remain active somehow? E.g. a delete really is a soft-delete of kinds?

There's no soft-delete in terms of field (there should be a prompt before you delete it). Certain setups (multi instances that wasn't configured to use redis/memcached) may face issue in terms of caching, but AFAIK community cloud should not face this issue 👍

**Comment by willemmulder** [comment] 2022-07-28 12:51
@azrikahar  I created a collection, then immediately created a Tree view field, with the foreign key set to the 'sort' field (I did not create any other field). Then deleted that Tree field, and got that error when trying to delete the collection, even though nu custom fields exist on that table anymore.

**Comment by azrikahar** [comment] 2022-07-28 12:57
> I created a collection, then immediately created a Tree view field, with the foreign key set to the 'sort' field (I did not create any other field). 

Assuming the "sort" field is the default system field based on your description, then that field will still become the Foreign Key field I mentioned. Can you verify whether my steps below exactly matches your latest description? 

https://user-images.githubusercontent.com/42867097/181510670-527d4bfc-20e0-4cff-baa1-a85a02494164.mp4

**Comment by willemmulder** [comment] 2022-07-28 13:08
@azrikahar Almost. I deleted the tree field, not the sort field.

But true, the system sort field will become a foreign key by specifying it in the tree field, right? And so I guess you could then describe it as a 'self-referencing field'? If so, then it fits the description of the other issue... :-)

**Comment by azrikahar** [comment] 2022-07-28 13:11
> But true, the system sort field will become a foreign key by specifying it in the tree field, right? And so I guess you could then describe it as a 'self-referencing field'?

Yes! Thanks for confirming.
