### ISSUE TITLE
Custom characters are removed from template

### ISSUE THREAD

**Issue by pierre-H** [directus/directus#5416] opened 2021-05-02 11:02 UTC
Using `{{table.name}} - {{table.descirption}}` should be available in O2M, M2M ...
But with the RC 61, it's remplaced ty `{{table.name}}{{table.descirption}}`.

**Comment by rijkvanzanten** [comment] 2021-05-04 23:06
This seems to work as expected for me 🤔 Can you share a step-by-step on how to reproduce this?

<img width="641" alt="CleanShot 2021-05-04 at 19 04 58@2x" src="https://user-images.githubusercontent.com/9141017/117080416-c5d13600-ad0b-11eb-81d6-dba572958fe4.png">

<img width="614" alt="CleanShot 2021-05-04 at 19 05 59@2x" src="https://user-images.githubusercontent.com/9141017/117080420-c7026300-ad0b-11eb-9c12-d9ccc6e7d48c.png">

**Comment by rijkvanzanten** [comment] 2021-05-04 23:06
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Comment by pierre-H** [comment] 2021-05-05 20:51
Here is a video of the bug : you can see that the `ok` at the end is removed and sometimes the ` - ` is removed.
I inserted the ` | ` directly in the database.

https://user-images.githubusercontent.com/6079305/117207541-584d0480-adf4-11eb-81e9-a049540feebd.mov

**Comment by tylerforesthauser** [comment] 2021-05-05 21:40
I have observed this behaviour as well

**Comment by pierre-H** [comment] 2021-05-06 15:52
@rijkvanzanten : as you can see in the video, the bug is still present in the RC 62.

**Comment by rijkvanzanten** [comment] 2021-06-04 03:51
https://user-images.githubusercontent.com/9141017/120743175-7b87d400-c4c6-11eb-9e4d-7d7d42d24328.mp4


@tylerforesthauser @pierre-H Could you confirm this problem still exists? I can't reproduce it at all..

If the problem still exists, could you share a DB dump where this is happening?

**Comment by pierre-H** [comment] 2021-06-04 06:25
Yes, I confirm you that the problem still exists with M2M :

https://user-images.githubusercontent.com/6079305/120755580-70589680-c50e-11eb-8e7c-13196a5549a7.mov

**Comment by pierre-H** [comment] 2021-06-04 06:26
> If the problem still exists, could you share a DB dump where this is happening?

I can't share you the DB dump of the database used in the video but I will try to give a an example dump.

**Comment by rijkvanzanten** [comment] 2021-06-04 14:37
So odd! Maybe a browser thing? What's that, Firefox?

**Comment by tylerforesthauser** [comment] 2021-06-04 20:54
@rijkvanzanten 
I can confirm that this issue seems to be browser-related and indeed I am personally using Firefox (89 / macOS 11.4). Tested on Google Chrome (91.0.4472.77) and it works just fine.

**Comment by Nitwel** [comment] 2021-08-23 15:11
This bug isn't caused by any special characters but rather firefox being annoying. When I wrote the `v-field-template` a year ago everthing worked fine (especially in firefox) but I guess firefox decided to change something that screws this interface up... 🤷‍♂️

**Closed** 2021-08-23 15:20 UTC
Labels: App, Bug
