### ISSUE TITLE
UI Bug on simplfied Mode when naming the Foreign Key of an O2M

### ISSUE THREAD

**Issue by Pachat** [directus/directus#13374] opened 2022-05-18 06:42 UTC
### Describe the Bug

When in simple mode an giving a new foreign key, the field is created as a simple field.
Though, it works OK when in Advanced mode.

### To Reproduce

Create an O2M field with a new foreign key

### Errors Shown

"The field does not exist"
(but the field is created without any relationship)

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

PostgreSQL 14.2

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-05-18 06:58
I can't seem to observe any bug when creating an O2M field in simple mode and adding the foreign key:

https://user-images.githubusercontent.com/42867097/168976826-5a6c691e-f99d-41ee-b5b3-67865211b995.mp4

Can you share more detail on reproducing this issue, or perhaps are there any steps that I might have missed in my example?

**Comment by Pachat** [comment] 2022-05-18 07:59
Sorry. It was because of working in different tabs:
modifying the data model * in one tab without refreshing before adding the field in the other tab.

_* precisely: deleting the corresponding M2O field in the foreign collection of a previous try_

Thank you for your time.

**Comment by azrikahar** [comment] 2022-05-19 08:26
Thanks for clarifying. I believe it should be due to when you were adding the field in the other tab, the previous tab's Pinia store was not updated as a result, unless I'm misunderstanding anything here. Perhaps one way this can be improved upon is when there's websockets to make sure different tabs stay updated 🤔 Though I do also wonder the 80/20 rule for such scenario. 

I'll close this for now, but if it does ever comes up even when you are solely working on the same tab, feel free to give us an update so that we can try to investigate further. 👍

**Closed by azrikahar** 2022-05-19 08:26 UTC
Labels: Needs More Info, Can't Reproduce
