### ISSUE TITLE
New Project Installation Error

### ISSUE THREAD

**Issue by alipasakaratas** [directus/directus#14274] opened 2022-07-04 12:44 UTC
### Describe the Bug

I was doing a clean install, after my successful installation, when I run the npx directus start command, I get the following error.

```
Error: knex: Required configuration option 'client' is missing.
at new Client (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\knex\lib\client.js:58:13)
at knex (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\knex\lib\knex-builder\Knex.js:16:28)
at getDatabase (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\directus\dist\database\index.js:102:32)
at validateDatabaseConnection (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\directus\dist\database\index.js:143:70)
at createApp (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\directus\dist\app.js:91:53)
at async createServer (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\directus\dist\server.js:41:38)
at async Command.startServer (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\directus\dist\server.js:128:20)
at async Command.parseAsync (C:\inetpub\vhost\realtygroup.digit.com\RealtyDirectus\node_modules\commander\lib\command.js:923:5)
```

#14120 

### To Reproduce

npm init directus-project projectName
select database mssql
write required db information
login to the project folder cd directus project
Run the command "npx directories start".
You will see the same error.

I got the same error when I said it on two different servers and on my local computer.

### Errors Shown

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/9849567/177157117-0af2cf9c-f7bd-42bc-a2bd-1a1d587ea2d8.png">

### What version of Directus are you using?

9.13

### What version of Node.js are you using?

14.16.0

### What database are you using?

MsSql 17

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally, windows server 2016

**Comment by rijkvanzanten** [comment] 2022-07-04 15:15
Please refrain from opening duplicate issues.

Duplicate of https://github.com/directus/directus/issues/14120, being discussed in https://github.com/directus/directus/discussions/14122

**Closed by rijkvanzanten** 2022-07-04 15:15 UTC
