### ISSUE TITLE
Sqlite migration directus v9.7.1 to v9.9.0 fails

### ISSUE THREAD

**Issue by Pachat** [directus/directus#12795] opened 2022-04-16 07:40 UTC
### Describe the Bug

When running` npx directus database migrate:latest
`
>09:31:42  Running migrations...
09:31:43  Applying Add Bookmark Icon and Color...
09:31:43  Applying Add Field Validation...
09:31:43  Applying Fix Typecast Flags...
09:31:43  Applying Add Default Language...
09:31:43  DROP TABLE "directus_users" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed

### To Reproduce

Over 9.7.1
`npm install directus`
`npx directus database migrate:latest`

### Errors Shown

`Error: DROP TABLE "directus_users" - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed`

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

v16.14.0

### What database are you using?

SQLite 3.37

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-04-16 07:44
Thanks for opening this issue! However this is a duplicate of an existing issues #12529 #10842, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #10842 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-16 07:44 UTC
Labels: Bug (Potential)
