### ISSUE TITLE
Flows: When modifying the Response Body to contain an array, the items in the array are not created

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#16177] opened 2022-10-26 09:34 UTC
### Describe the Bug

We have a flow which triggers on newly created "Start Rules". A web service generates the according time-slots for it.
The flow uses this service to expand the flow's payload, which should create all the slots automatically with the same request when a new start rule gets created.

![image](https://user-images.githubusercontent.com/9347206/197987908-e22b2694-b8a4-4c95-998c-13c68babcae5.png)

The flow is of type "Filter (Blocking)", because we want to alter the payload.
The response body is set to "{{$last.data}}".

As you can see, the request URL in the flow returns all the needed data in the "data" property (including the "slots"):
![image](https://user-images.githubusercontent.com/9347206/197988271-73d12386-eeee-48a3-90b0-29f6933cdee2.png)

But when looking at the created item in Directus, it seems to just ignore the array and "slots" stays empty:
![image](https://user-images.githubusercontent.com/9347206/197988453-5155bc17-87cf-4180-9fca-a1292bcbddd2.png)

### To Reproduce

This can be reproduced without an external service:

1. Create a collection with a O2M relationship. (Start Rule 1 -> N Slots)
2. Create a filter flow on the create action, with the response body as "Data of last Operation"
3. Use a "Transform Payload" node and add some entries in the array where the relationship of the object is.
4. (I used another override, just to make sure that the Reponse Body works, "trail: 3")
![image](https://user-images.githubusercontent.com/9347206/197990990-ca241d5c-c2d7-46b2-8ac5-ef4b196eb6cc.png)

5. The array on the object didn't update.
![image](https://user-images.githubusercontent.com/9347206/197991485-cf671967-539d-466e-ab9b-02b318f4757c.png)

### Errors Shown

No errors

### What version of Directus are you using?

9.19.2

### What version of Node.js are you using?

v16.7.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by LevinGermann** [comment] 2022-10-26 09:37
By the way, the format of the array objects is correct, because when I pass in an example object of the array the creation works fine:

![image](https://user-images.githubusercontent.com/9347206/197992202-737ca3e3-593e-4a58-8d70-0f0394fe84e5.png)

Looks to me that the override of the Transform Payload still didn't influence the array, but did on the Integer field "trail".

**Comment by azrikahar** [comment] 2022-10-31 04:37
Seems like this turns out to share the same root cause as relational presets as reported in #16127.

In OP's case, it is relational data **_added after filter hook_**. In order to have access to new-fields-added-by-filter-hook, it should be `payloadAfterHooks` instead of `payload`. On top of that, `payloadAfterHooks` is also being assigned to `payloadWithPresets` afterwards:

https://github.com/directus/directus/blob/2adbb3bfd27639b3af4453d4ffcdd3be59736dea/api/src/services/items.ts#L101-L121

However when to-many relational data is being processed here:

https://github.com/directus/directus/blob/2adbb3bfd27639b3af4453d4ffcdd3be59736dea/api/src/services/items.ts#L165-L169

it uses `payload` instead of `payloadAfterHooks`/`payloadWithPresets`, which meant the filter hook's **_relational_** data are not being "passed", which is exactly what OP described.

Closing this issue in favor of tracking it over in #16127 👍 Will update that issue to include filter hook as the affected feature as well.

**Closed by azrikahar** 2022-10-31 04:37 UTC
Labels: App, Bug (Potential)
