### ISSUE TITLE
Collection "collection_name" already exists error

### ISSUE THREAD

**Issue by Tazooou** [directus/directus#11749] opened 2022-02-20 14:37 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hello,

I have clean all my project as explain in documentation (remove directory + delete all bases of my database)

I install directus just after and now when I want to create a table who exist before suppression, I have this error message : 

 errors message : Collection \xxxxx\already exists., extensions: {"code": "INVALID_PAYLOAD"}

Do I have forget something to do when I delete all my project ?

Thank's for advance !

### To Reproduce

Create a new collection

### Errors Shown

```json
{
  "errors": [
    {
      "message": "Collection \"fungus\" already exists.",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

Maria DB

### What browser are you using?

Brave

### What operating system are you using?

Linux 5.4.0-99-generic

### How are you deploying Directus?

running locally

**Comment by sensedrive** [comment] 2022-02-20 18:53
@Tazooou Are you able to share a database and config (.env) with us? I had the same error message, but it was connected with the redis cache.

**Comment by sensedrive** [comment] 2022-02-21 05:52
Hello @Tazooou 

I could not reproduce the issue. I did the following steps:

1. Installed a fresh Directus 9.5.1
2. Created a table named "fungus"
3. I deleted the table named "fungus"
4. Re-created the table named "fungus"

**Comment by Tazooou** [comment] 2022-02-21 08:59
Hello @sensedrive,

I tried to create another table with a different name "Fungus". I deleted it and I created a new table with the name "fungus" and I didn't see any error ...

Problem solved :) May be a cache problem with my navigator ?

**Comment by sensedrive** [comment] 2022-02-21 10:49
@Tazooou hard to say. But I mentioned, that I had a similar issue, which was caused by the cache config in the .env file.

So, this can be closed.

**Comment by azrikahar** [comment] 2022-02-21 10:55
@sensedrive thank you very much for taking your time to look into this. Really appreciate the help! 

Closing for now, but we'll reopen this if OP ever finds this happening again in the future.

**Closed by azrikahar** 2022-02-21 10:55 UTC
Labels: Needs More Info, Can't Reproduce

**Comment by joselcvarela** [comment] 2022-02-21 13:39
>I had the same error message, but it was connected with the redis cache.

@sensedrive how did you solve that? By deleting the key?

**Comment by sensedrive** [comment] 2022-02-21 13:46
@joselcvarela I had to comment all cache relevant config, not only the CACHE_ENABLED flag, which I think is related to https://github.com/directus/directus/issues/11029
