### ISSUE TITLE
Using GraphQL API, creating an item having M2O relationship does not allow providing the foreign key instead requires that a new related object be created

### ISSUE THREAD

**Issue by ravi-2912** [directus/directus#13689] opened 2022-06-02 17:38 UTC
### Describe the Bug

Consider case of Many-to-One (M2O) having 2 tables Post and Comment.

Post has fields
*  `id` as `int`
*  `content` as `text`

Comment has fields
*  `id` as `int`
* `message` as `text`
* `post` which is as foreign key to table Post (M2O relation)

In GraphQL, a comment can only be created if a new post is also created. The schema definition of `post` in `create_comment_input` schema is of type `create_post_input` which means a post must be create if a new comment has to be made. 

This is not a desired behaviour as and as I cannot create a new comment without creating a post. I wish to create a comment and be able to assign a post by providing its `id`. Could you please look. Ideally, it would be nice to have both.

### To Reproduce

Steps are described above. Create Post and Comment table with M2O relations.

Creat a post first. 
Then try creating a comment.
GraphQL with throw `GRAPHQL_VALIDATION_EXCEPTION` and will require that a new post must be created if creating a new comment.

### Errors Shown

This error below is for my personal project and not for Post/Comment scenario. 

My Query

```gql
mutation CREATE_INSTURMENTS {
  create_instrument_item(
    data: {
      name: "Wheat"
      ticker: "WHT"
      broker: 1
      status: "draft"
    }
  ) {
    id
  }
}

```

```json
{
  "error": {
    "errors": [
      {
        "message": "GraphQL validation error.",
        "extensions": {
          "code": "GRAPHQL_VALIDATION_EXCEPTION",
          "graphqlErrors": [
            {
              "message": "Expected value of type \"create_broker_input\", found 1.",
              "locations": [
                {
                  "line": 2,
                  "column": 77
                }
              ]
            }
          ]
        }
      }
    ]
  }
}
```

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

16.15.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-06-02 17:41
Duplicate of https://github.com/directus/directus/issues/7237

**Closed by rijkvanzanten** 2022-06-02 17:41 UTC
Labels: Bug (Potential)
