### ISSUE TITLE
Incorrect CSV import

### ISSUE THREAD

**Issue by kostopravby** [directus/directus#12028] opened 2022-03-08 09:12 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Importing data from CSV file are incorrect.

### To Reproduce

Create collection with 2 columns. gescal(string), q(integer just for counter) for example. Make import from csv file.
Original data:
![image](https://user-images.githubusercontent.com/29959329/157204648-3bef704c-f56e-42e5-9d7b-49c769ee4ab5.png)
Imported data:
![image](https://user-images.githubusercontent.com/29959329/157204778-aebd9277-9271-4573-9b81-45bc60dcf2e9.png)
Incorrect "gescal" values in rows 1,2,7 and etc.

### Errors Shown

No errors

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

PostgreSQL 10 with postgis

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

docker

**Comment by rijkvanzanten** [comment] 2022-03-08 14:34
Can you share (a snippet of) the CSV we can use to debug with?

**Comment by azrikahar** [comment] 2022-03-17 08:35
Seems like the issue is with `JSON.parse` on csv imports here:

https://github.com/directus/directus/blob/b45620ac46b8c47e9e91456066a94c48acd4b9cc/api/src/services/import.ts#L112

where they ended up being treated as numbers but they exceeded [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) so the result became "inaccurate":

![chrome_JIInENunrY](https://user-images.githubusercontent.com/42867097/158768726-21d1396d-3fb3-4f12-bd82-26ba7570d36d.png)

Perhaps a solution would require moving this `get-js-type` util function to shared, getting the field types from `this.schema.collections[collection].fields` and only perform `JSON.parse` when they are `json`, `csv` or `geometry`:

https://github.com/directus/directus/blob/b45620ac46b8c47e9e91456066a94c48acd4b9cc/app/src/utils/get-js-type.ts#L13

**Comment by kostopravby** [comment] 2022-03-17 08:38
it's strange because this field has type string.

**Comment by azrikahar** [comment] 2022-03-17 09:57
Technically the import currently doesn't discern field types (in terms of Directus fields just to be sure), but if you mean the value passed into `JSON.parse` itself being type string, then you are indeed bringing up a rather interesting point! 

Perhaps an even more straightforward solution would be if the input already has double quotes like the CSV you have provided, it should be "escaped" so that `JSON.parse` won't attempt to cast it into a number:

![image](https://user-images.githubusercontent.com/42867097/158784428-9445e9c7-b384-4013-b122-14ba49db7923.png)

**Comment by azrikahar** [comment] 2022-04-12 07:45
Seems like csv-parser is returning all of them as string (even for `q` in OP's case) so it can be difficult to determine whether the original CSV has quotes or not.

Turning off the [quote](https://github.com/mafintosh/csv-parser#quote) option does return the value with quotes when it exists, but then the keys are also excluded from quote removal and became `'"getscal"'` rather than `getscal`.

Also seems to be what mafintosh/csv-parser#172 aimed to resolve.

**Closed** 2022-06-28 22:08 UTC
Labels: API, Bug
