### ISSUE TITLE
Public role permissions route breaks if exiting 'Use Custom' modal

### ISSUE THREAD

**Issue by NightlyFlux** [directus/directus#5409] opened 2021-05-01 19:24 UTC
**Steps to reproduce:**

1. Create a collection
2. Go to the public role page (http://localhost:8055/admin/settings/roles/public)
3. Select any CRUD action and choose 'Use custom'
4. Press the exit button
5. URL changes to (http://localhost:8055/admin/settings/roles/null) and breaks

**You have to manually go back and select the role again.**

---

### Project details
Directus Version: 9.0.0-rc.61
Environment: production
OS: Windows_NT 10.0.19042
Node: 15.14.0
Database: MySQL 8

**Comment by rijkvanzanten** [comment] 2021-05-03 13:33
Duplicate of https://github.com/directus/directus/issues/5298

**Closed by rijkvanzanten** 2021-05-03 13:33 UTC
