### ISSUE TITLE
Issue with installing latest create-directus-extension (v9.25.1)

### ISSUE THREAD

**Issue by sharkfin009** [directus/directus#18204] opened 2023-04-16 06:59 UTC
### Describe the Bug

When trying to install ( I have tried 3 different environments and many node verisons) I always get this error:

```
file:///Users/heatseeker/.npm/_npx/9ea216cce9aeac9a/node_modules/create-directus-extension/lib/index.js:4
import { inquirer } from 'inquirer';
         ^^^^^^^^
SyntaxError: Named export 'inquirer' not found. The requested module 'inquirer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'inquirer';
const { inquirer } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadESM (node:internal/process/esm_loader:85:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)

Node.js v17.9.1
```

### To Reproduce

Follow the docs, in terms of using the package. ie 'npm init directus-extension' and then agree to install the package.

I have installed an old version (9.23.1 to be safe) and the problem is resolved for me.

### Directus Version

v9.22.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by sharkfin009** [comment] 2023-04-16 07:00
btw I also tried using the official Docker Compose file. Same result.

**Comment by paescuj** [comment] 2023-04-16 07:17
Thanks for opening this issue! However this is a duplicate of an existing issue #18183, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment.

**Closed by paescuj** 2023-04-16 07:17 UTC

**Comment by ryanleung96** [comment] 2023-04-17 06:54
@paescuj I tried with the master branch and the problem is still out there. 

Would you please have a look?


```
PS C:\xampp-common\htdocs\directus-main> npm init directus-extension
Need to install the following packages:
  create-directus-extension@9.25.1
Ok to proceed? (y) y
file:///C:/Users/01667492/AppData/Local/npm-cache/_npx/9ea216cce9aeac9a/node_modules/create-directus-extension/lib/index.js:4
import { inquirer } from 'inquirer';
         ^^^^^^^^
SyntaxError: Named export 'inquirer' not found. The requested module 'inquirer' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'inquirer';
const { inquirer } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
npm ERR! code 1
npm ERR! path C:\xampp-common\htdocs\directus-main
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c cde
```

**Comment by azrikahar** [comment] 2023-04-17 07:31
That particular `import { inquirer } from 'inquirer'` line was fixed in https://github.com/directus/directus/pull/18187/files#diff-f546996c0cb2e926fdbb16bc686339fb1bd601c4cafcaf464a6adbf904323868R4, so if it is indeed the main branch on your end, make sure to pull changes to your forked/cloned repo as well 👍

Note that this is not included in a public release yet as of the writing of this comment, and the main branch can be ahead of the current public release (9.25.1).

**Comment by sharkfin009** [comment] 2023-04-17 09:14
thanks all, appreciate all the hard work . Loving directus!

**Comment by ryanleung96** [comment] 2023-04-17 14:21
@azrikahar I am working with the main branch source code locally and every time I try to create a new extension, I got the same error.

Looks like the `npm init directus-extension` will install the util from npm repo instead of locally resolving.
