### ISSUE TITLE
Unable to import users

### ISSUE THREAD

**Issue by aaron-manning** [directus/directus#12971] opened 2022-04-23 11:55 UTC
### Describe the Bug

It's not possible to import users into Directus from within Directus.

The UI provides the option to import users, so it should work.

Note that whenever the import feature fails, the error output into the UI is useless (always the same error 'This file's data structure doesn't match the collection.'). The only way to get the real error is to look at the http response or check the db log.

### To Reproduce

1. Create new directus install
2. Export users (the 1 admin user created on install) to csv
3. Import that csv

### Errors Shown
```
{
    "errors": [
        {
            "message": "You don't have permission to access this.",
            "extensions": {
                "code": "FORBIDDEN"
            }
        }
    ]
}
```
### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

14.18.1

### What database are you using?

postgres 14.3.2

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-04-23 12:46
Should be duplicate of #12873, as users & presets are both system collections 👍 Comment for more info on what's happening: https://github.com/directus/directus/issues/12873#issuecomment-1103709881

**Closed by azrikahar** 2022-04-23 12:46 UTC
Labels: Bug (Potential)

**Comment by KelvinCYDev** [comment] 2023-07-04 19:05
I have a similar problem and my question is that is it possible to allow non-admin roles to import users? 

Also, the import feature still appears in the UI for non-admin roles, which makes a bit of confusion for me that maybe it should work?
