### ISSUE TITLE
Creating new User with exsiting users email overrides original user

### ISSUE THREAD

**Issue by Geo719** [directus/directus#1983] opened 2017-12-04 16:06 UTC
## Version Info
  Latest Docker Image

## Expected Behavior
Creating a new user should be indipendent of any email used.

## Actual Behavior
Creating new User with exsiting users email overrides original user

## Steps to Reproduce
 1. Have Admin (A) user with email XYZ
 2. Create new (admin) user (B), also with email adress XYZ
 3. User data (A) will be updated with user data (B)

**Comment by WellingGuzman** [comment] 2017-12-04 17:40
This actually an expected behavior, it may seems confusing though as it's not self explanatory or give the user any warning.

@benhaynes may enlight us a lil bit better, I don't know if this was suppose to only work for non active users or all.

**Comment by WellingGuzman** [comment] 2017-12-06 04:43
I will close this as this is not a bug, but a expected behavior due to email being unique for each users.

On #1237 I'm going to add a comment to make sure we add a warning that the users exists and the current data will be overwriting to the existing user.

**Comment by rijkvanzanten** [comment] 2017-12-06 13:27
is this really expected @benhaynes @wellingguzman? I feel like it shouldn't allow creation (POST) when it already exists.. Only updates

**Comment by benhaynes** [comment] 2017-12-06 13:45
The reason is that disabled users are inaccessible, and if you go to recreate or invite that user again it would fail. 

I think the best solution would be to warn that a user with that email already exists and that you will overwrite if you continue. 

I disagree with closing this ticket and moving it to the "friendly errors" ticket. That makes these individual issues harder to track. Let's reopen and fix here.

**Comment by rijkvanzanten** [comment] 2018-03-20 14:17
At the moment, all core developers are working fulltime on the next major version of the platform, so I'll have to leave this open as a help-wanted. If anyone is inclined to take a swing at fixing this, a PR is very welcome 😄

**Comment by benhaynes** [comment] 2018-10-25 18:13
Kamino cloned this issue to [directus/app](https://github.com/directus/app/issues/1036)

**Comment by benhaynes** [comment] 2018-10-25 18:13
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/18)

**Closed by benhaynes** 2018-10-25 18:13 UTC
Labels: 4. Minor, Help Wanted, Interface, Optimization, v6
