### ISSUE TITLE
Directus - can't create any collection 

### ISSUE THREAD

**Issue by suresh20041993** [directus/directus#16293] opened 2022-11-03 06:00 UTC
### Describe the Bug

 CMS because I can't create any collection.
When creating a collection, an error occurs.

### To Reproduce

Create a collection from the user interface

### Errors Shown

{ "errors": [ { "message": "Collection \"Test\" doesn't exist", "extensions": { "code": "INVALID_PAYLOAD" } } ] }

### What version of Directus are you using?

Directus v9.0.0 RC 83

### What version of Node.js are you using?

14

### What database are you using?

Postgres 13

### What browser are you using?

chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-11-03 06:52
It can be very difficult to tell what could be the issue here, particularly since there have been a ton of changes since [`v9.0.0-rc.83`](https://github.com/directus/directus/releases/tag/v9.0.0-rc.83) to the current [`v9.20.3`](https://github.com/directus/directus/releases/tag/v9.20.3). It is recommended for bug reports to be made for the latest version as mentioned in the issue template 👍

This does seem to share the same issue as #10291, but it's more related to collations in MySQL. As you are using Postgres, I would recommend verifying whether the database user you are using has full permissions to the database as a potential cause here. There is also a more recent issue #16165 with a similar error, but it was also verified that it's something to do with the environment instead of Directus.

Closing this for now and will reopen when this can be reliably reproduced on the latest version.

**Closed by azrikahar** 2022-11-03 06:52 UTC
