### ISSUE TITLE
Directus 9.23.0 its not published on NPM

### ISSUE THREAD

**Issue by jesusmpc** [directus/directus#17664] opened 2023-03-01 14:06 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Try `npm info directus` and no `9.23.0` is available. Checking the action that performs the release https://github.com/directus/directus/actions/runs/4295889524/jobs/7486979867#step:5:2105 an authentication error arises but it completes OK

### To Reproduce

Just try to perform an `npm i directus@9.23.0`, the command will fail.

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2023-03-01 14:35
Duplicate of #17653

**Closed by paescuj** 2023-03-01 14:35 UTC
