### ISSUE TITLE
Permissions using $CURRENT_USER.X not working

### ISSUE THREAD

**Issue by u12206050** [directus/directus#19039] opened 2023-06-30 08:48 UTC
### Describe the Bug

Since 10.3.0 Permissions on directus collections that have minimal default permissions such as on the `directus_users` collection, don't seem to work with custom permissions when using `$CURRENT_USER.SOME_FIELD`

This results in fields being read only it seems and can't be edited.

From #18898

### To Reproduce

Create a `user_roles` collection with 
`user` m2m to `directus_users` with `roles` as alias
`role` m2m to `directus_roles` with `users` as alias

On a custom role on the `directus_users` collection add a permission to UPDATE eg.
{
  "role": {
      _in: "$CURRENT_USER.roles.role"
   }
}

Add the roles of other people to the user you will be testing with that has the new permission.
And then switch to that user to test if they can edit other people with the role that exists in one of their roles.

### Directus Version

10.3.0-10.3.1

### Hosting Strategy

Self-Hosted (Custom)

# root cause: 92f2a9197e1c71e88a92eb498278571f4901b0de

**Comment by u12206050** [comment] 2023-07-05 08:24
I am really worried that this hasn't had any response yet. It isn't labeled as bug or issue yet and is basically now 3 weeks old since the original issue was raised. Our most important users aren't able to carry out some of their tasks due to this and as an enterprise customer I would hope this could be sorted asap.

**Comment by rijkvanzanten** [comment] 2023-07-06 09:38
Duplicate of https://github.com/directus/directus/issues/18898

**Closed by rijkvanzanten** 2023-07-06 09:38 UTC
