### ISSUE TITLE
Can't edit wysiwyg field

### ISSUE THREAD

**Issue by sydney-d** [directus/directus#2599] opened 2020-02-25 17:37 UTC
# Bug Report

## Steps to Reproduce

1. Create a collection with a wysiwyg field
2. Add one item to the collection
3. Edit the field to add "toolbar options"
4. Click save
5. See error

## Expected Behavior
Updating field normaly

## Actual Behavior
An error toast pops

## Other Context & Screenshots

PATCH request sent to : 
`_/fields/blocks/wysiwyg_content`

response : 
```json

{
   "error":{
      "code":404,
      "message":"Statement could not be executed (42000 - 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(16777215) Null' at line 1)",
      "class":"Directus\\Exception\\SQLException",
      "file":"\/home\/site\/wwwroot\/src\/endpoints\/Fields.php",
      "line":122
   }
}
```

- Web Server: Apache
- PHP Version: 7.3
- Database: MySQL 8
- Directus Release Version: 8.5.5
- Install Method: ftp

**Comment by rijkvanzanten** [comment] 2020-02-25 18:14
Duplicate of https://github.com/directus/api/issues/1765

**Closed by rijkvanzanten** 2020-02-25 18:14 UTC
