### ISSUE TITLE
"directus_users" violates foreign key constraint "directus_sessions_user_foreign"

### ISSUE THREAD

**Issue by andriusign** [directus/directus#5561] opened 2021-05-09 13:44 UTC
DELETE to _/users/id_ results in error:
update or delete on table "directus_users" violates foreign key constraint "directus_sessions_user_foreign" on table "directus_sessions" 

```
directus-db | 2021-05-09 13:41:52.716 UTC [177] ERROR:  update or delete on table "directus_users" violates foreign key constraint "directus_sessions_user_foreign" on table "directus_sessions"
directus-db | 2021-05-09 13:41:52.716 UTC [177] DETAIL:  Key (id)=(73e8ad89-5e81-4788-b91e-23ae5cc6c9f5) is still referenced from table "directus_sessions".
directus-db | 2021-05-09 13:41:52.716 UTC [177] STATEMENT:  delete from "directus_users" where "id" in ($1)
directus-api | 13:41:52 🚨 error delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_sessions_user_foreign" on table "directus_sessions" 
directus-api | error: delete from "directus_users" where "id" in ($1) - update or delete on table "directus_users" violates foreign key constraint "directus_sessions_user_foreign" on table "directus_sessions"
directus-api |     at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
directus-api |     at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
directus-api |     at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
directus-api |     at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
directus-api |     at Socket.emit (events.js:315:20)
directus-api |     at addChunk (internal/streams/readable.js:309:12)
directus-api |     at readableAddChunk (internal/streams/readable.js:284:9)
directus-api |     at Socket.Readable.push (internal/streams/readable.js:223:10)
directus-api |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
directus-api | 13:41:52 ✨ request errored DELETE 500 /users/************ 44ms
```
---

### Project details
Directus Version: 9.0.0-rc.59
Environment: production
OS: Linux 5.4.0-72-generic
Node: 14.16.1

**Comment by rijkvanzanten** [comment] 2021-05-10 13:13
Duplicate of https://github.com/directus/directus/issues/5528

**Closed by rijkvanzanten** 2021-05-10 13:13 UTC
