### ISSUE TITLE
Decimal place in files search field throws error

### ISSUE THREAD

**Issue by vonadz** [directus/directus#20387] opened 2023-11-10 17:24 UTC
### Describe the Bug

When using the search input for assets in the dashboard, an error is thrown if the search query starts with a number and includes a period (ie 1.1 or 15.23)
![directus-search-error](https://github.com/directus/directus/assets/16930123/94ea0bb8-bc08-488b-8a8b-edafee73a16e)

### To Reproduce

Download a fresh install of directus and type "1.1" (with apostrophes) into the search input.

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-04-23 23:37
As of version v10.10.7 I'm unable to reproduce this issue when using queries with decimal points in the file library search bar (or any other for that matter) with any of the following database drivers `sqlite`, `postgres` and `mysql`. I will therefore close this issue. 

If it is still occurring for you please share your detailed setup and the exact error message. Thank you!

**Closed by hanneskuettner** 2024-04-23 23:37 UTC
Labels: :detective: Needs More Info
