### ISSUE TITLE
When adding an already existing item in a related table no error message leads to misinterpretation

### ISSUE THREAD

**Issue by Pachat** [directus/directus#11160] opened 2022-01-19 15:57 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

While adding a new field in a table when the + is clicked to add a related field in the parent table
and, by mistake, an already present value is entered in the parent key
we go back to the detail field with that value visible.
So we think that everything is OK.
But this is not the case: No id has been sent to the field.

The best solution would be to send the id of the already existing related field.
At minima, throw a message when the supposed new value in fact already exists.

### To Reproduce

Create 

Table A 
- field_B =M2O=> Table B.key_B

Table B 
- key_B (unique)

Input an item in Table B with
  key_B=`B1`

1. Now, add an item A.
2. On field_B, click on +
3. In the detail form of Table B, input `B1` in key_B
4. Save Table B
5. You see `B1` in field_B (which _falsely_ looks fine)
6. Save Table A (If you can, for in case you set field_B as required, you just can't save. No message tells you why)

### Errors Shown

You have a null `--` in field_B instead of `B1`

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

14.17.1

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox

### What operating system are you using?

Windows_NT 10.0.19043

### How are you deploying Directus?

locally

**Comment by joselcvarela** [comment] 2022-01-20 07:05
I believe this should be a duplicate of https://github.com/directus/directus/issues/10916

If you think that's not the case, feel free to reach us in order to reopen.

**Closed by joselcvarela** 2022-01-20 07:05 UTC
Labels: Bug (Potential)

**Comment by Pachat** [comment] 2022-01-20 10:36
You may consider that
- in  #10916, 
the field is **blank before** saving and **correct after** saving
- as, here, in #11160, it is the opposite: 
the field is **correct before** saving but **blank after** saving.
I don't know enough the internals to say if these two bugs are related or not.
