### ISSUE TITLE
Conditions do not work for relational (nested) fields

### ISSUE THREAD

**Issue by viters** [directus/directus#10632] opened 2021-12-22 11:01 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Conditions applied to nested fields are not respected on the details form.

### To Reproduce

1. Create a collection `collection` with radio field `type`, values `a` and `b`.
2. Add translations collection.
3. Add any field on translations and set condition to `hide on details` if `collection_id->type does not equal a`.
4. Go to details, change "type" between "a" and "b" - translation field should disappear and appear accordingly - but it does not change anyhow.

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

14

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-12-22 14:05
Duplicate of #9176.

**Closed by azrikahar** 2021-12-22 14:05 UTC
Labels: Bug (Potential)
