### ISSUE TITLE
Can't enable cascade delete on relation table from directus data model interface

### ISSUE THREAD

**Issue by TerreBRICE** [directus/directus#20076] opened 2023-10-19 11:19 UTC
### Describe the Bug

Can't enable cascade delete on relation table from directus data model interface. The save button is disabled. 

### To Reproduce

Create two entities A and B, and create a many to many relation between them. 
After go to the entity A_B, and try to add cascade on the item field. Impossible to save the change.
![image](https://github.com/directus/directus/assets/49029468/8a6e47fc-b0ec-4d99-b9df-5723b8a035cd)

### Directus Version

latest

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-10-24 20:46
Duplicate of https://github.com/directus/directus/issues/15546

**Closed by rijkvanzanten** 2023-10-24 20:46 UTC
