### ISSUE TITLE
Adding an item to a O2M, is not rendering correctly until save.

### ISSUE THREAD

**Issue by vitali-droujko** [directus/directus#17018] opened 2023-01-04 17:38 UTC
### Describe the Bug

When I am creating an item to a O2M field.
Once I added the item (not saving) the item is not rendering correctly looks like 
<img width="884" alt="Screenshot 2023-01-04 at 18 32 28" src="https://user-images.githubusercontent.com/71847509/210615026-25263df0-fd4c-435b-baee-1b586e50a551.png">

### To Reproduce

Create a O2M field to a collection. Save.
![Uploading Screenshot 2023-01-04 at 18.33.19.png…]()

Go to the collection and try to add an item.
<img width="879" alt="Screenshot 2023-01-04 at 18 34 17" src="https://user-images.githubusercontent.com/71847509/210615381-f879e972-cbd1-46ff-9937-b625cceeea83.png">
fill the field..
<img width="825" alt="Screenshot 2023-01-04 at 18 34 50" src="https://user-images.githubusercontent.com/71847509/210615512-287e0f25-944d-4c2a-bbf0-1074811e41e7.png">

Then it looks like: 
<img width="874" alt="Screenshot 2023-01-04 at 18 35 20" src="https://user-images.githubusercontent.com/71847509/210615545-c9bc3e39-0c01-41d8-a809-fed9cdfa8315.png">

Then, to solve the bug, save.
<img width="860" alt="Screenshot 2023-01-04 at 18 36 23" src="https://user-images.githubusercontent.com/71847509/210615793-5fac5065-bf5f-4051-81f7-eaf817e40ea5.png">

Go back:
<img width="875" alt="Screenshot 2023-01-04 at 18 37 02" src="https://user-images.githubusercontent.com/71847509/210615845-b2358557-764a-4fdf-bcb3-d6b722796595.png">

looks great.

### Errors Shown

no error shown.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

V18.12.1

### What database are you using?

Postgresql

### What browser are you using?

chrome, safari

### How are you deploying Directus?

running locally, then deploy into Kubernetes jobs.. (both is bugged)

**Comment by rijkvanzanten** [comment] 2023-01-04 19:46
Duplicate of https://github.com/directus/directus/issues/10647

**Closed by rijkvanzanten** 2023-01-04 19:46 UTC

**Comment by vitali-droujko** [comment] 2023-01-05 07:54
I'm sorry.. 
Thanks for support.
