### ISSUE TITLE
Version number in the directus app does not match docker image

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17124] opened 2023-01-12 19:10 UTC
### Describe the Bug

When I upgraded from `9.22.1` to 9.22.3` I recognized that the version number in the app changed to `9.22.2`. Today I upgraded to `9.22.4` but the version number in the app changed to `9.22.3`. Why is that?

### To Reproduce

Install directus >= 9.22.3 with docker, open directus and navigate to the settings page.

### What version of Directus are you using?

9.22.3 or 9.22.4

### What version of Node.js are you using?

Latest

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by paescuj** [comment] 2023-01-12 19:34
Duplicate of #17115

**Closed** 2023-01-12 19:36 UTC
