### ISSUE TITLE
Nested translations editing do not work correctly (no translation values displayed)

### ISSUE THREAD

**Issue by LazyBun** [directus/directus#12270] opened 2022-03-21 09:35 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using the method for displaying translated text in M2M relationships described [here](https://github.com/directus/directus/issues/11385#issuecomment-1045136001), nested translations editing does not work properly. The values in edit window are blank.

![2022-03-21-10-26-44](https://user-images.githubusercontent.com/32524814/159234506-38b6d65d-7ab9-4975-820c-2713acdd1057.png)

**_Note_**: displaying works correctly if no default translation display is configured

![image](https://user-images.githubusercontent.com/32524814/159235498-d90cf142-2326-4a14-94bd-8125fdba89c2.png)

### To Reproduce

* Create ingredient model with translated fields

![2022-03-21-10-20-51](https://user-images.githubusercontent.com/32524814/159234564-b2f5456f-e588-4ec6-a0ba-4bd94360e819.png)

* Create Recipe model that has M2M relationship to Ingriedient

![2022-03-21-10-21-36](https://user-images.githubusercontent.com/32524814/159234578-c0b2782d-51e5-4df8-960e-50a24e47f0ec.png)

* Configure ingredient model translations to display default value

![2022-03-21-10-22-11](https://user-images.githubusercontent.com/32524814/159234604-98fb7ee6-6213-4ffc-94ed-8918053d3d99.png)

* Configure m2m relationship field in recipe model to use ingredient translations default as display & interface
![2022-03-21-10-23-25](https://user-images.githubusercontent.com/32524814/159234631-167d3360-6564-48c6-af8e-1a0a7f8b416e.png)
![2022-03-21-10-23-42](https://user-images.githubusercontent.com/32524814/159234657-e8a372cb-9a36-440b-b587-c61a5ab3eb3c.png)

* Create ingredient, recipe and connect the two for following result

![2022-03-21-10-25-22](https://user-images.githubusercontent.com/32524814/159234698-c619328c-e50e-4bc0-95d0-3096f0dbb4cc.png)

* When editing the ingredient by clicking on it, the translations in side window are blank despite being filled out

![2022-03-21-10-26-44](https://user-images.githubusercontent.com/32524814/159234737-6aba6f95-c52a-4fea-a8b9-b625f1af1de4.png)

### Errors Shown

None, but one thing I've noticed is that if translation display _is not_ configured, then in logs I see:

```backend-gen2-directus-1  | 09:40:53 ✨ request completed GET 304 /items/ingredient_translations?fields=*&limit=-1&filter=%7B%22ingredient_id%22:%7B%22_eq%22:1%7D%7D 21ms```

(so translations are queried for)

If translation display _is_ configured, then no such log is present (so the translations are not queried for)

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

Node.js 14 running on 64bit Amazon Linux 2

### What database are you using?

Postgres 13

### What browser are you using?

chromium

### What operating system are you using?

Linux 5.13.19-2-MANJARO

### How are you deploying Directus?

Reproduced on local instance ran through docker, but this also happens on instance deployed via codecommit to ebs

**Comment by azrikahar** [comment] 2022-03-21 10:19
> When using the method for displaying translated text in M2M relationships described https://github.com/directus/directus/issues/11385#issuecomment-1045136001, nested translations editing does not work properly. The values in edit window are blank.

I believe this has the same root cause as #12013, so I'll proceed to close this for now. However really appreciate the detailed steps, screenshots, plus troubleshooting here!

> If translation display is configured, then no such log is present (so the translations are not queried for)

Out of curiosity, by not present, do you mean when opening the drawer? It might have been fetched prior to the drawer opening for the preview.

**Closed by azrikahar** 2022-03-21 10:19 UTC
Labels: Bug (Potential)

**Comment by LazyBun** [comment] 2022-03-21 10:31
@azrikahar 

> Out of curiosity, by not present, do you mean when opening the drawer? It might have been fetched prior to the drawer opening for the preview.

Yes, when opening the drawer. I've double checked all the logs and it looks like `ingredient_translations` does not get called at all when the display is configured. See the full logs below.

**_With display configured_**:

* When entering the entry edit:

```
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 200 /items/recipe/1 8ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 200 /activity?filter[collection][_eq]=recipe&filter[item][_eq]=1&filter[action][_eq]=comment&sort=-id&fields[]=id&fields[]=action&fields[]=timestamp&fields[]=user.id&fields[]=user.email&fields[]=user.first_name&fields[]=user.last_name&fields[]=user.avatar.id&fields[]=revisions.id&fields[]=comment 26ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 200 /shares?filter=%7B%22_and%22:[%7B%22collection%22:%7B%22_eq%22:%22recipe%22%7D%7D,%7B%22item%22:%7B%22_eq%22:%221%22%7D%7D]%7D&sort=name 31ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 200 /revisions?filter=%7B%22collection%22:%7B%22_eq%22:%22recipe%22%7D,%22item%22:%7B%22_eq%22:%221%22%7D%7D&sort=-id&limit=100&page=0&fields[]=id&fields[]=data&fields[]=delta&fields[]=collection&fields[]=item&fields[]=activity.action&fields[]=activity.timestamp&fields[]=activity.user.id&fields[]=activity.user.email&fields[]=activity.user.first_name&fields[]=activity.user.last_name&fields[]=activity.ip&fields[]=activity.user_agent&meta[]=filter_count 45ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 304 /notifications?filter=%7B%22_and%22:[%7B%22recipient%22:%7B%22_eq%22:%223bdac00c-1be3-42f2-a838-e318a89675a8%22%7D%7D,%7B%22status%22:%7B%22_eq%22:%22inbox%22%7D%7D]%7D&fields[]=id&fields[]=subject&fields[]=collection&fields[]=item&fields[]=timestamp&sort[]=-timestamp 31ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 200 /server/info 16ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 200 /items/recipe_ingredient?fields[]=id&fields[]=ingredient_id&filter[id][_in]=1 16ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 304 /notifications?filter=%7B%22_and%22:[%7B%22recipient%22:%7B%22_eq%22:%223bdac00c-1be3-42f2-a838-e318a89675a8%22%7D%7D,%7B%22status%22:%7B%22_eq%22:%22inbox%22%7D%7D]%7D&aggregate=%7B%22count%22:%22id%22%7D 23ms
backend-gen2-directus-1  | 10:22:50 ✨ request completed GET 200 /revisions?filter=%7B%22collection%22:%7B%22_eq%22:%22recipe%22%7D,%22item%22:%7B%22_eq%22:%221%22%7D,%22activity%22:%7B%22action%22:%7B%22_eq%22:%22create%22%7D%7D%7D&sort=-id&limit=1&fields[]=id&fields[]=data&fields[]=delta&fields[]=collection&fields[]=item&fields[]=activity.action&fields[]=activity.timestamp&fields[]=activity.user.id&fields[]=activity.user.email&fields[]=activity.user.first_name&fields[]=activity.user.last_name&fields[]=activity.ip&fields[]=activity.user_agent&meta[]=filter_count 33ms
backend-gen2-directus-1  | 10:22:51 ✨ request completed GET 200 /items/ingredient?fields[]=translations.name&fields[]=translations.id&fields[]=translations.id&fields[]=translations.languages_id.code&fields[]=translations.languages_id.code&fields[]=id&filter[id][_in]=1 18ms
backend-gen2-directus-1  | 10:22:51 ✨ request completed PATCH 204 /users/me/track/page 24ms
backend-gen2-directus-1  | 10:22:51 ✨ request completed GET 200 /items/ingredient?limit=25&fields[]=translations.name&fields[]=translations.id&fields[]=translations.languages_id.code&fields[]=translations.languages_id.code&fields[]=id&sort[]=id&page=1&filter=%7B%7D&meta[]=filter_count&meta[]=total_count 23ms
```

* When opening the edit drawer

```
backend-gen2-directus-1  | 10:23:53 ✨ request completed GET 200 /items/recipe_ingredient/1?fields=*,ingredient_id.* 22ms
backend-gen2-directus-1  | 10:23:53 ✨ request completed GET 200 /items/ingredient/1 27ms
backend-gen2-directus-1  | 10:23:53 ✨ request completed GET 200 /items/languages?fields[]=code&limit=-1&sort=code 15ms
```

**_With display not configured_**:

* When entering the entry edit:

```
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /items/recipe/1 13ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /activity?filter[collection][_eq]=recipe&filter[item][_eq]=1&filter[action][_eq]=comment&sort=-id&fields[]=id&fields[]=action&fields[]=timestamp&fields[]=user.id&fields[]=user.email&fields[]=user.first_name&fields[]=user.last_name&fields[]=user.avatar.id&fields[]=revisions.id&fields[]=comment 26ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /shares?filter=%7B%22_and%22:[%7B%22collection%22:%7B%22_eq%22:%22recipe%22%7D%7D,%7B%22item%22:%7B%22_eq%22:%221%22%7D%7D]%7D&sort=name 13ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /notifications?filter=%7B%22_and%22:[%7B%22recipient%22:%7B%22_eq%22:%223bdac00c-1be3-42f2-a838-e318a89675a8%22%7D%7D,%7B%22status%22:%7B%22_eq%22:%22inbox%22%7D%7D]%7D&fields[]=id&fields[]=subject&fields[]=collection&fields[]=item&fields[]=timestamp&sort[]=-timestamp 17ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /revisions?filter=%7B%22collection%22:%7B%22_eq%22:%22recipe%22%7D,%22item%22:%7B%22_eq%22:%221%22%7D%7D&sort=-id&limit=100&page=0&fields[]=id&fields[]=data&fields[]=delta&fields[]=collection&fields[]=item&fields[]=activity.action&fields[]=activity.timestamp&fields[]=activity.user.id&fields[]=activity.user.email&fields[]=activity.user.first_name&fields[]=activity.user.last_name&fields[]=activity.ip&fields[]=activity.user_agent&meta[]=filter_count 40ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 200 /server/info 10ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /items/recipe_ingredient?fields[]=id&fields[]=ingredient_id&filter[id][_in]=1 20ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /notifications?filter=%7B%22_and%22:[%7B%22recipient%22:%7B%22_eq%22:%223bdac00c-1be3-42f2-a838-e318a89675a8%22%7D%7D,%7B%22status%22:%7B%22_eq%22:%22inbox%22%7D%7D]%7D&aggregate=%7B%22count%22:%22id%22%7D 21ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /revisions?filter=%7B%22collection%22:%7B%22_eq%22:%22recipe%22%7D,%22item%22:%7B%22_eq%22:%221%22%7D,%22activity%22:%7B%22action%22:%7B%22_eq%22:%22create%22%7D%7D%7D&sort=-id&limit=1&fields[]=id&fields[]=data&fields[]=delta&fields[]=collection&fields[]=item&fields[]=activity.action&fields[]=activity.timestamp&fields[]=activity.user.id&fields[]=activity.user.email&fields[]=activity.user.first_name&fields[]=activity.user.last_name&fields[]=activity.ip&fields[]=activity.user_agent&meta[]=filter_count 20ms
backend-gen2-directus-1  | 10:26:54 ✨ request completed GET 304 /items/ingredient?limit=25&fields[]=translations.name&fields[]=translations.id&fields[]=translations.languages_id.code&fields[]=translations.languages_id.code&fields[]=id&sort[]=id&page=1&filter=%7B%7D&meta[]=filter_count&meta[]=total_count 29ms
backend-gen2-directus-1  | 10:26:55 ✨ request completed GET 304 /items/ingredient?fields[]=id&filter[id][_in]=1 13ms
backend-gen2-directus-1  | 10:26:55 ✨ request completed PATCH 204 /users/me/track/page 18ms
backend-gen2-directus-1  | 10:26:55 ✨ request completed GET 304 /items/ingredient?limit=25&fields[]=translations.name&fields[]=translations.id&fields[]=translations.languages_id.code&fields[]=translations.languages_id.code&fields[]=id&sort[]=id&page=1&filter=%7B%7D&meta[]=filter_count&meta[]=total_count 18ms
```

* When opening the edit drawer:

```
backend-gen2-directus-1  | 10:27:30 ✨ request completed GET 304 /items/languages?fields[]=code&limit=-1&sort=code 21ms
backend-gen2-directus-1  | 10:27:30 ✨ request completed GET 304 /items/recipe_ingredient/1?fields=*,ingredient_id.* 32ms
backend-gen2-directus-1  | 10:27:30 ✨ request completed GET 304 /items/ingredient_translations?fields=*&limit=-1&filter=%7B%22ingredient_id%22:%7B%22_eq%22:1%7D%7D 23ms
backend-gen2-directus-1  | 10:27:30 ✨ request completed GET 304 /items/ingredient/1 28ms
backend-gen2-directus-1  | 10:27:30 ✨ request completed GET 304 /items/ingredient_translations?fields=*&limit=-1&filter=%7B%22ingredient_id%22:%7B%22_eq%22:1%7D%7D 8ms
backend-gen2-directus-1  | 10:27:30 ✨ request completed GET 304 /items/ingredient_translations?fields=*&limit=-1&filter=%7B%22ingredient_id%22:%7B%22_eq%22:1%7D%7D 6ms
```

**Comment by sepios87** [comment] 2022-03-22 08:48
Hello, I have the same problem here with directus 9.7.0, when I want to display at the top of my page the name of the element according to the translation I have a strange behavior. 
When I put just the translation field in the display template, nothing is displayed (except '--') while in my display and in the display template of this element I have the name for example. 

Just with translation field in display template :
![image](https://user-images.githubusercontent.com/58748740/159441210-25a5cd3e-f5e4-4192-9473-5e5696cede78.png)
![image](https://user-images.githubusercontent.com/58748740/159441267-ea2725c9-6c65-4442-aeb6-0071d8ad8b5f.png)
'Modele Mission' is my traduction field : 
![image](https://user-images.githubusercontent.com/58748740/159441566-ec078046-b6e8-4630-a40c-af385c0dc9ee.png)

Render : 
![image](https://user-images.githubusercontent.com/58748740/159441396-481b3148-29ec-49f3-8db7-92307618b7a5.png)

I found a way to display something but it's not logical. In addition to the translation field, I put the name field which comes from translation next to it. It generates 'lorem --' for example... 
With translation and 'nom' from translation
![image](https://user-images.githubusercontent.com/58748740/159441747-8a7e6b6e-b51e-4dca-9882-89dfc3222cc8.png)
Render : 
![image](https://user-images.githubusercontent.com/58748740/159441820-82841c34-ce8b-4150-9958-1bc41d6b1663.png)

And when I try to put on the 'nom' from the translation to try it still gives me '--'.
With just name field (from translation) : 
![image](https://user-images.githubusercontent.com/58748740/159441874-0ce4d388-4f46-485f-b456-3c3e77ef4aa1.png)
Render : 
![image](https://user-images.githubusercontent.com/58748740/159441934-8ca1b29d-e58a-4901-b1e2-6e033141c255.png)

**Comment by azrikahar** [comment] 2022-03-22 11:53
@LazyBun I think it was fetched relationally in the 3rd to last line in "With display configured", compared to the 3rd to last line in "Without display configured" that doesn't fetch relationally. I could be wrong though, will need to investigate. Thanks again for the info!

@sepios87 I believe your issue is #11385 instead, rather than this one or #12013 🙂

**Comment by LazyBun** [comment] 2022-03-22 12:00
@azrikahar No problem. 

Btw, I could try to investigate this - I wanted to contribute a little, since we're using Directus on prod :)

In contributing guidelines it says that before making a change it should be discussed with owners. With your blessing I could look into it :P

**Comment by azrikahar** [comment] 2022-03-22 12:06
> Btw, I could try to investigate this - I wanted to contribute a little, since we're using Directus on prod :)

That'd be great!

> In contributing guidelines it says that before making a change it should be discussed with owners. With your blessing I could look into it :P

That statement is more so to prevent too many out-of-the-blue PRs, especially **new substantial features** rather than fixing issues, that sometimes may not be fleshed-out enough and may add more on the plate to us.

Bug fixes are always welcomed, no blessing needed 😄 Thanks again.
