### ISSUE TITLE
Custom Modules migration from Vue 2 to Vue 3

### ISSUE THREAD

**Issue by bernatvadell** [directus/directus#6299] opened 2021-06-16 05:59 UTC
Hi!

Recently I've upgraded to v9.0.0-rc.76 and my custom module has never worked again. 

My custom module has stopped working, and after several hours of correcting bugs, I have been stuck here: 

If I don't use directus components, it loads correctly, ex:

```vue
<template >
  <p>Content goes here...</p>
</template>

<script>
export default {};
</script>
```

If I use any of the directus components my screen is blank and the following warning appears on the console.

`[Vue warn]: resolveComponent can only be used in render() or setup().`

```vue
<template >
  <private-view title="My Custom Module">Content goes here...</private-view>
</template>

<script>
export default {};
</script>
```

This is my rollup config:
```js
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import replace from "@rollup/plugin-replace";
import { terser } from "rollup-plugin-terser";
import vue from "rollup-plugin-vue";

export default {
  input: "src/index.js",
  output: {
    format: "es",
    file: "./dist/index.js",
  },
  plugins: [
    nodeResolve(),
    commonjs(),
    replace({
      "process.env.NODE_ENV": JSON.stringify("development"),
      preventAssignment: true,
    }),
    vue({}),
    terser(),
  ],
};
```
This is my module index.js:
```js
import Test from "./routes/test.vue";

export default {
  id: "calendar",
  name: "$t:calendar",
  icon: "event",
  routes: [
    {
      name: "calendar-test",
      path: "",
      component: Test,
    },
  ],
  order: 1,
};
```

This is my package.json
```json
{
  "name": "calendar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "npx rollup -c",
    "watch": "npx rollup -c -w"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "@rollup/plugin-replace": "^2.4.2",
    "@vue/compiler-sfc": "^3.1.1",
    "rollup": "^2.51.2",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-vue": "^6.0.0-beta.10"
  },
  "dependencies": {
    "moment": "^2.29.1",
    "vue": "^3.1.1"
  }
}
```

Any ideas? Ty!

**Comment by nickrum** [comment] 2021-06-16 10:50
This is a known limitation of how Vue 3 handles component registration. Your custom module doesn't know that there is a `private-view` component.
We are working on a fix. In the meantime, if you rely on extensions, you should stay on `v9.0.0-rc.74`.

**Comment by bernatvadell** [comment] 2021-06-16 10:59
Thx mate!

**Comment by nickluger** [comment] 2021-06-18 05:31
Hey @bernatvadell - thank you for the issue 👍  - but why did you close it? I think, as long as the [modules How-to](https://docs.directus.io/guides/modules/) is breaking with the current version of Directus, and one cannot use any [Directus components](https://docs.directus.io/reference/app/components/) or `private-view`, this issue should stay open. It's blocking upgrades completely for anyone using custom modules/interfaces etc.?

**Comment by BinaryBen** [comment] 2021-06-18 05:34
Also curious why this is closed. I have been waiting for Directus to move to Vue 3 so I can sell it internally as an option for an upcoming project (i.e., so we can use Vue 3 across all parts of the project). But I can't do that if there aren't docs or even a way of making custom layouts/modules/etc work with Vue 3.

**Comment by nickluger** [comment] 2021-06-18 05:46
Hmm... Using other Directus components (except for views like `private-view`)  should actually be possible, as they are all globally registered Vue-3-style [here](https://github.com/directus/directus/blob/1961dc188bfa51cfa0f846eab8c7f20a26a075c7/app/src/components/register.ts), as far as I can see.

**Comment by bernatvadell** [comment] 2021-06-18 05:52
Sorry guys! when publishing the comment I closed it accidentally. 

Do we have a ticket in which this is being worked on? I wish I could help.

**Comment by BinaryBen** [comment] 2021-06-18 05:54
I think there is a bigger issue... I have a custom module building. But whether I use `<private-view>` or just a generic HTML tag, the route only shows my component without the Directus UI around it (the example image is just a `<p>` tag)

<img width="633" alt="Screen Shot 2021-06-18 at 1 51 56 pm" src="https://user-images.githubusercontent.com/12827556/122513160-961c8a00-d03c-11eb-8332-e512a34aaebf.png">
.

**Comment by bernatvadell** [comment] 2021-06-18 05:54
> Hey @bernatvadell - thank you for the issue 👍 - but why did you close it? I think, as long as the [modules How-to](https://docs.directus.io/guides/modules/) is breaking with the current version of Directus, and one cannot use any [Directus components](https://docs.directus.io/reference/app/components/) or `private-view`, this issue should stay open. It's blocking upgrades completely for anyone using custom modules/interfaces etc.?

Yep, at the moment I am still blocked in version `v9.0.0-rc.74`

**Comment by nickrum** [comment] 2021-06-18 09:38
> Hmm... Using other Directus components (except for views like `private-view`) should actually be possible, as they are all globally registered Vue-3-style [here](https://github.com/directus/directus/blob/1961dc188bfa51cfa0f846eab8c7f20a26a075c7/app/src/components/register.ts), as far as I can see.

The problem is that with Vue 3 you can have multiple Vue instances and Vue uses a global variable to determine which instance is currently "active". Once a new component is rendered, this global variable is used to check for registered components. Now, if you bundle an extension with the updated instructions, this global variable is copied into your extension bundle. Thus, it can't be set by the Vue instance and the globally registered components aren't visibleto your extension. By the way, `private-view` is also globally registered over [here](https://github.com/directus/directus/blob/1961dc188bfa51cfa0f846eab8c7f20a26a075c7/app/src/views/register.ts).
The solution to this is to share the vue dependency between the main Directus App and extensions.

> I think there is a bigger issue... I have a custom module building. But whether I use `<private-view>` or just a generic HTML tag, the route only shows my component without the Directus UI around it (the example image is just a `<p>` tag).

`private-view` actually contains the Directus UI, but as your extension doesn't know about it, it just renders as a `<private-view>`-tag.

**Closed** 2021-06-23 16:43 UTC
Labels: Question

**Comment by bernatvadell** [comment] 2021-06-23 17:51
Yep @rijkvanzanten 

Im trying to update at latest ver (9.0.0-v80) and migrate my custom module.

By marking the package "vue" as external in the rollup configuration. I have an error in the browser console that says: 

`Couldn't load custom module "calendar": TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".`

My rollup config is:
```js
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import vue from "rollup-plugin-vue";
import postcss from "rollup-plugin-postcss";

export default {
  input: "src/index.js",
  output: {
    format: "es",
    file: "./dist/index.js",
  },
  external: ["vue", "@directus/extension-sdk"],
  plugins: [
    vue({ preprocessStyles: true }),
    nodeResolve(),
    commonjs(),
    postcss(),
  ],
};
```

And this is my package.json:
```js
{
  "name": "calendar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "npx rollup -c",
    "watch": "npx rollup -c -w"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "@vue/compiler-sfc": "^3.1.2",
    "rollup": "^2.52.2",
    "rollup-plugin-postcss": "^4.0.0",
    "rollup-plugin-terser": "^7.0.2",
    "rollup-plugin-vue": "^6.0.0",
    "sass": "^1.35.1"
  },
  "dependencies": {
    "moment": "^2.29.1",
    "vue": "^3.1.2",
    "vue-fragment": "^1.5.2"
  }
}
```

Any ideas?

**Comment by rijkvanzanten** [comment] 2021-06-23 19:27
All the big updates @nickrum did in #6377 haven't been released yet 🙂 I think the best course of action is to hold off 'til 81 👍🏻

**Comment by klickparkdominik** [comment] 2021-06-24 13:00
Maybe I am missing something.
But after merging #6377 into my development environment my custom modules component/route still displays a white screen and is missing the Directus app UI.

**Comment by nickrum** [comment] 2021-06-24 17:21
@klickparkdominik There are a few additional commit's to `main` that are required to make this work. If your issue still persist with current `main`, feel free to open a new issue.
