### ISSUE TITLE
Restricted access - table alter access forbidden on table

### ISSUE THREAD

**Issue by romainhe** [directus/directus#1052] opened 2015-10-07 10:47 UTC
Hi, 
When I try to add new field on my new table this error appear... 

![capture](https://cloud.githubusercontent.com/assets/1837829/10311013/2a3ed966-6c45-11e5-9a88-73b991fda570.PNG)

**Comment by benhaynes** [comment] 2015-10-07 13:38
@WellingGuzman shouldn't any tables added into Directus get `alter` by default?

**Comment by WellingGuzman** [comment] 2015-10-07 19:52
@romainhe are you using the current version (there has been some changes in the database schema as well)? This was discussed and fixed #998 #1014 

If you are using the current version (with current schema) and still happen, I'd take a look at this again.

**Comment by romainhe** [comment] 2015-10-08 07:29
Actually I'm running 6.0.3 (displayed on the login page)
Downloaded last week directly on github


Thx for help

**Comment by beevelop** [comment] 2015-10-20 08:01
I can reproduce this bug using the **build** branch as the mentioned changes doesn't seem to be merged there yet. The issue is resolved in the **master** or **development** branch.

**Comment by WellingGuzman** [comment] 2016-04-22 19:06
@romainhe did you solve the problem? what @beevelop says resolved your problem? if it does it should be fixed by now.

**Comment by benhaynes** [comment] 2016-04-22 19:17
If it was an issue with the `build` branch but working on master, then this should be good to go now. I'll close it and we can reopen if someone is experiencing this problem still.

**Closed by benhaynes** 2016-04-22 19:17 UTC
Labels: 3. Major

**Comment by daddykom** [comment] 2017-06-29 15:47
I use Verion 6.3.9

When I try to add a field to a table, i get a 403 Forbidden from the Server:
POST https://directus.collins.ch/cms/api/1/tables/Testtab/columns

Adding the table works fine. adding a field to the table gives 403. 

It sends the PHPSESSID Cookie, the same like in the create table call.

Can anyone tell me, where this 403 is triggered in the software?
