### ISSUE TITLE
Directus container not waiting for database startup

### ISSUE THREAD

**Issue by br41nslug** [directus/directus#20542] opened 2023-11-27 15:13 UTC
### Describe the Bug

Ever since 10.7.0 the Directus container is starting before the database container is fully started and ready to accept connections resulting in the Directus container crashing on first start and requiring either a manual start or auto-restart a couple of times before it is actually started.

I've encountered this both with Postgres and MySQL 8. This was not an issue for me in v10.6.4 and before.

Failing on `10.8.2`:
![image](https://github.com/directus/directus/assets/9389634/c4f093ca-97dc-4f95-a880-ef625c2c7099)

Working on `10.6.4`:
![image](https://github.com/directus/directus/assets/9389634/4a1d13eb-34d3-4156-b3f5-cd7d9c403bbd)

Related issue: https://github.com/directus/directus/issues/20538

### To Reproduce

Using Docker Desktop on Windows (but it seems to also occur on Ubuntu)
1. create a docker-compose file based on the docs example https://docs.directus.io/self-hosted/docker-guide.html#example-docker-compose
2. run `docker-compose up` (or `docker-compose up -d`)
3. check the status of the Directus container

### Directus Version

\>= 10.7.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-11-27 15:18
Odd. The startup sequence isn't something that we control in the container itself, so I'm having some trouble imagining how the 10.7 upgrade causes the difference, unless the update just makes the container starts quicker 🤔

**Comment by paescuj** [comment] 2023-11-27 15:21
> Odd. The startup sequence isn't something that we control in the container itself, so I'm having some trouble imagining how the 10.7 upgrade causes the difference, unless the update just makes the container starts quicker 🤔

Yeah, same thought here. We never really waited for the database to be ready, so this must be an unintended side effect of another change, which for examples made the startup quicker or reduced some kind of timeout.

**Comment by Boegie19** [comment] 2023-11-27 15:29
Are you sure it is 10.7.0 and not 10.7.1? since if it is 10.7.1 it would most likely be that you now use pm2.

**Comment by rijkvanzanten** [comment] 2023-11-27 15:30
@Boegie19 Which shouldn't affect the waiting for things to be ready, as we never explicitly had anything built in that would wait for connections to become alive before either 🤔

**Comment by br41nslug** [comment] 2023-11-27 15:31
> Are you sure it is 10.7.0 and not 10.7.1? since if it is 10.7.1 it would most likely be that you now use pm2.

Yes im sure this started at 10.7.0, I explicitly tested each version down to 10.6.x to see where it stopped working.

**Comment by Boegie19** [comment] 2023-11-27 15:39
> @Boegie19 Which shouldn't affect the waiting for things to be ready, as we never explicitly had anything built in that would wait for connections to become alive before either 🤔

If this was never an explict feture why is this then a regression

Since you could walk into the same issue with a slow db startup.

**Comment by br41nslug** [comment] 2023-11-27 15:39
> we never explicitly had anything built in that would wait for connections to become alive before either 🤔

Sooo @rijkvanzanten does that mean it has always been blind luck that the Directus container took longer to start up than the containers it depends on? 😂 Perhaps we should introduce such logic if we've optimized it to the point of starting faster than its database

**Comment by rijkvanzanten** [comment] 2023-11-27 15:42
> does that mean it has always been blind luck that the Directus container took longer to start up than the containers it depends on?

That's exactly what I'm saying! We should add a health check to the example in our docker-compose, and then make sure the Directus container is configured to wait for `service_healthy` before starting up in it's `depends_on` flag 🙂

**Comment by br41nslug** [comment] 2023-11-27 15:43
> If this was never an explict feture why is this then a regression

I consider this bug to be a regression because it used to work consistently before 10.7 and after it consistently crashes causing a regression in User eXperience at the very least without knowing the actual cause.

**Comment by Stefa093** [comment] 2023-12-15 16:00
I'm having the same issue :/ I need to use docker container as background service but always it exited with code 13 and honestly don't know what to do 
![image](https://github.com/directus/directus/assets/111255088/7fa2d087-9a6d-4624-935a-132a84d75ebd)

**Comment by br41nslug** [comment] 2023-12-15 16:12
For others ending up here the current workaround is to restart the Directus container specifically when the database container is ready (this can be done by repeating `docker compose up -d` too as that will only start the containers not currently running)

**Comment by paescuj** [comment] 2023-12-15 16:17
> I'm having the same issue :/ I need to use docker container as background service but always it exited with code 13 and honestly don't know what to do ![image](https://private-user-images.githubusercontent.com/111255088/290872760-7fa2d087-9a6d-4624-935a-132a84d75ebd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2NTcwNDUsIm5iZiI6MTcwMjY1Njc0NSwicGF0aCI6Ii8xMTEyNTUwODgvMjkwODcyNzYwLTdmYTJkMDg3LTlhNmQtNDYyNC05MzVhLTEzMmE4NGQ3NWViZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQxNjEyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTA2Mzk1MWY1NjU2YTY1MGZmNDI3ZWY0M2M3NDI2MzBhNDhiODgyZWEwZWM4ODlhNmIyNzA4M2RkZDlmNWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o4njKfyREgE_lqlH6D4V0XJiFTHf8Te0EvGFAadVhLw)

The issue you're seeing is rather related to https://github.com/directus/directus/pull/20693.
Until the linked fix has been released, a workaround is to clear the cache before starting the service:
```
# from within the directus directory
rm node_modules/.cache/directus/*
```

**Comment by br41nslug** [comment] 2024-03-06 19:08
Anyone ending up here you can use the following health check in `docker-compose.yml` to have Directus wait for Postgres container to be ready:
```yaml
version: '3.7'
services:
    database:
      image: 'postgres:14'
      volumes:
        # environment
      environment:
        # environment
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    directus:
      image: directus/directus:10.10.0
      depends_on:
        database:
          condition: service_healthy
        cache:
          condition: service_started
      volumes:
        # volumes
      environment:
        # environment
    cache:
      image: redis:6

```

**Comment by Simran-B** [comment] 2024-04-12 13:41
The health check does not appear to work. Judging by the log, it seems like Directus is started while Postgres (`postgis/postgis:16-master` in my case) is still initializing. I suppose that `pg_isready` returns an exit code of 0 because Postgres is in fact accepting connections. However, it shuts down shortly after when the init process is complete, to then start for normal operation.

```
database-1  | server started
database-1  | CREATE DATABASE
...
database-1  | You are now connected to database "directus" as user "directus".
database-1  | CREATE EXTENSION
database-1  | CREATE EXTENSION
database-1  |
database-1  | 2024-04-12 09:23:56.253 UTC [63] LOG:  received fast shutdown request
database-1  | waiting for server to shut down...2024-04-12 09:23:56.260 UTC [63] LOG:  aborting any active transactions
database-1  | 2024-04-12 09:23:56.264 UTC [63] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
database-1  | .2024-04-12 09:23:56.341 UTC [90] FATAL:  terminating connection due to administrator command
database-1  | 2024-04-12 09:23:56.342 UTC [90] LOG:  could not send data to client: Broken pipe
database-1  | 2024-04-12 09:23:56.357 UTC [64] LOG:  shutting down
database-1  | 2024-04-12 09:23:56.364 UTC [64] LOG:  checkpoint starting: shutdown immediate
database-1  | 2024-04-12 09:23:56.402 UTC [99] FATAL:  the database system is shutting down
directus-1  | Error: connect ECONNREFUSED 172.19.0.4:5432
directus-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
directus-1  |   errno: -111,
directus-1  |   code: 'ECONNREFUSED',
directus-1  |   syscall: 'connect',
directus-1  |   address: '172.19.0.4',
directus-1  |   port: 5432
directus-1  | }
directus-1 exited with code 1
database-1  | ..2024-04-12 09:23:58.957 UTC [64] LOG:  checkpoint complete: wrote 4459 buffers (27.2%); 0 WAL file(s) added, 0 removed, 2 recycled; write=1.579 s, sync=0.948 s, total=2.601 s; sync files=963, longest=0.006 s, average=0.001 s; distance=34770 kB, estimate=34770 kB; lsn=0/36DBAB0, redo lsn=0/36DBAB0
database-1  | .2024-04-12 09:23:59.487 UTC [63] LOG:  database system is shut down
database-1  |  done
database-1  | server stopped
database-1  |
database-1  | PostgreSQL init process complete; ready for start up.
database-1  |
database-1  | 2024-04-12 12:00:09.678 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg110+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
database-1  | 2024-04-12 12:00:09.681 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database-1  | 2024-04-12 12:00:09.681 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database-1  | 2024-04-12 12:00:09.708 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database-1  | 2024-04-12 12:00:09.789 UTC [96] LOG:  database system was shut down at 2024-04-12 12:00:08 UTC
database-1  | 2024-04-12 12:00:09.833 UTC [1] LOG:  database system is ready to accept connections
```

It turns out that the initialization starts the server temporarily, only listening to local requests:

https://github.com/docker-library/postgres/blob/44ef8b226a40f86cf9df3f9299067db6779a3aa3/16/alpine3.19/docker-entrypoint.sh#L268-L269

When using `pg_isready` in `healthcheck`, the utility runs in the same container and the default host appears to be `localhost`, so it can actually establish a connection during init and reports success (healthy). Explicitly specifying the hostname seems to fix it because `pg_isready` now checks for a connection like from an external source, and therefore only responding successfully when postgres runs normally:

```yaml
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --host=database"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
```

Username and database name can apparently be left out. One may specify them to suppress errors in the log, but I couldn't actually observe log messages caused by the healthcheck even when specifying bad values. On the other hand, I did observe them when running `pg_isready` manually and with `command: -c log_destination=stderr` - strange.

**Comment by upttiunej** [comment] 2024-07-02 02:12
> Anyone ending up here you can use the following health check in `docker-compose.yml` to have Directus wait for Postgres container to be ready:
> 
> ```yaml
> version: '3.7'
> services:
>     database:
>       image: 'postgres:14'
>       volumes:
>         # environment
>       environment:
>         # environment
>       healthcheck:
>         test: ["CMD-SHELL", "pg_isready -U postgres"]
>         interval: 5s
>         timeout: 5s
>         retries: 5
>     directus:
>       image: directus/directus:10.10.0
>       depends_on:
>         database:
>           condition: service_healthy
>         cache:
>           condition: service_started
>       volumes:
>         # volumes
>       environment:
>         # environment
>     cache:
>       image: redis:6
> ```

this is actually help me. works like a charm.

**Closed** 2024-08-05 17:47 UTC
Labels: :cake: Bug, :elevator: Infra, :file_folder: Engine Misc., :fire::fire:
