### ISSUE TITLE
Duplicate app collection field when choosing on_delete: CASCADE

### ISSUE THREAD

**Issue by NightlyFlux** [directus/directus#6519] opened 2021-06-27 21:26 UTC
### What version of Directus are you using?

v9.0.0-rc.80

### What version of Node.js are you using?

v16.2.0

### What database are you using?

MySQL 8

### What browser are you using?

Edge

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

### Describe the Bug

When I try to create a M2O relationship and choose the cascade on delete option, the field gets visually duplicated on the app, the db tables seems fine, no duplication

### To Reproduce

1. Create 2 tables
2. Create a M2O relationship
3. Choose cascade on delete

**Comment by NightlyFlux** [comment] 2021-06-27 21:33
UPDATE: Happens with any type of on delete option... I'm creating a relationship between the restaurants(owner field) table and the directus_user table.

**Comment by rijkvanzanten** [comment] 2021-06-28 18:10
Duplicate of https://github.com/directus/directus/issues/6204

**Closed by rijkvanzanten** 2021-06-28 18:10 UTC
Labels: Bug (Potential)
