### ISSUE TITLE
Sort field in m:a relations is not being filled by default

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#15338] opened 2022-08-31 12:30 UTC
### Describe the Bug

The default value for the field is "null", which causes some unwanted behaviour, when adding new items to already sorted items.

Screenshot 1:
Shows the graphql query and response.

Screenshot 2:
But in the backend the order of the items is completely different.

<img width="1712" alt="grafik" src="https://user-images.githubusercontent.com/8351587/187678380-b3fd9dfb-999e-438b-b2a7-e0502f1be7b6.png">
<img width="830" alt="grafik" src="https://user-images.githubusercontent.com/8351587/187678183-74266e82-b193-43b7-a2f4-e6b87f2cb469.png">

### To Reproduce

1. Add two items and sort them. The field "sort" will be filled.
2. Leave the collection.
3. Add later again two items. Do NOT sort them. The field "sort" will be have the value "null".

### Errors Shown

The newly added items have the sort value "null", the old ones have a sort number.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

mariadb

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment] 2022-08-31 12:34
Duplicate of #11430

**Closed by br41nslug** 2022-08-31 12:34 UTC
Labels: Duplicate
