### ISSUE TITLE
Sorting drag and drop problem

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#2008] opened 2017-12-21 14:43 UTC
## Version Info
  - Directus version and branch:  master

## Actual Behavior

After last update, try sort items in table

![default](https://user-images.githubusercontent.com/4669992/34259617-08539c5a-e674-11e7-8c98-12beef695939.png)

![default](https://user-images.githubusercontent.com/4669992/34259634-15d0af58-e674-11e7-9548-542f1d2d709d.png)

**Comment by WellingGuzman** [comment] 2017-12-21 19:28
Hey @dsivokhin, can you please share a schema that we can use to replicate this issue?

**Comment by dsivokhin** [comment] 2017-12-22 07:54
Hello, @WellingGuzman 
[test.zip](https://github.com/directus/directus/files/1581784/test.zip)

**Comment by philleepflorence** [comment] 2018-01-10 15:46
Also getting this error when sorting, any updates?

**Comment by nihlton** [comment] 2018-01-11 16:39
I am also seeing this issue with chrome.  As a temporary work around for users - sorting appears to work in firefox.

**Comment by WellingGuzman** [comment] 2018-01-11 18:08
I tried @dsivokhin, schema without any luck, I forgot to report back the status of this ticket. If any of you could share a schema that trigger this, that would be great, no having luck with the ones I have.

Something this type of issues are due to how some table are structure.

**Comment by nihlton** [comment] 2018-01-11 23:26
@WellingGuzman which browser are you using?

i was able to repro using chrome, but not with firefox.

**Comment by dsivokhin** [comment] 2018-01-26 13:11
Hi @WellingGuzman, new information, if I have this error, then I do Logout and do Login, this error not reproduce, but if I work with anouther tables, and back to my table, I have this error. Maybe cache ?

**Comment by WellingGuzman** [comment] 2018-01-28 07:34
Hey @dsivokhin, I managed to reproduce this issue.

If you go to `/tables` and go to any tables, and try to sort, you get the error, but if you go directus to `/tables/<a-table>` and try to sort, you don't get any error.

**Comment by Carnewal** [comment] 2018-01-28 21:21
+1 Same issue here when sorting with Chrome.

**Comment by Carnewal** [comment] 2018-01-31 16:02
#2037

**Comment by rijkvanzanten** [comment] 2018-02-02 04:40
This is fixed by #2039 and will be released into `master` soon!

**Closed by rijkvanzanten** 2018-02-02 04:40 UTC
