### ISSUE TITLE
Cannot read properties of undefined (reading 'primary')

### ISSUE THREAD

**Issue by joelee2017** [directus/directus#12319] opened 2022-03-23 09:38 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Cannot read properties of undefined (reading 'primary')

![image](https://user-images.githubusercontent.com/33776374/159668581-d56f673d-a44b-4f4f-aacb-98cb3d9a4be7.png)

### To Reproduce

docker run -p 8055:8055 -e KEY=255d861b-5ea1-5996-9aa3-922530ec40b1  -e SECRET=6116487b-cda1-52c2-b5b5-c8022c45e263 -e ADMIN_EMAIL=admin@admin.com -e ADMIN_PASSWORD=xxx123456 -e DB_CLIENT=mssql -e DB_HOST=x.x.x.x -e DB_PORT=2433 -e DB_DATABASE=directus -e DB_USER=xxxxxx -e DB_PASSWORD=xxxxxxxx directus/directus    

### Errors Shown

```
09:32:17 ✨ Initializing bootstrap...
09:32:17 ✨ Database already initialized, skipping install
09:32:17 ✨ Running migrations...
09:32:17 ✨ Done
npm notice
npm notice New minor version of npm available! 8.3.1 -> 8.5.5
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>
npm notice Run `npm install -g npm@8.5.5` to update!
npm notice
09:32:19 ⚠️  PUBLIC_URL should be a full URL
09:32:19 ⚠️  Collection "directus_notifications" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_fields" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_activity" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_permissions" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_presets" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_relations" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_revisions" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_settings" doesn't have a primary key column and will be ignored
09:32:19 ⚠️  Collection "directus_webhooks" doesn't have a primary key column and will be ignored
TypeError: Cannot read properties of undefined (reading 'primary')
    at getASTFromQuery (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:49:56)
    at ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:194:58)
    at RelationsService.readAll (/directus/node_modules/directus/dist/services/relations.js:66:49)
    at getDatabaseSchema (/directus/node_modules/directus/dist/utils/get-schema.js:131:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getSchema (/directus/node_modules/directus/dist/utils/get-schema.js:36:22)
    at async registerAuthProviders (/directus/node_modules/directus/dist/auth.js:26:64)
    at async createApp (/directus/node_modules/directus/dist/app.js:97:5)
    at async createServer (/directus/node_modules/directus/dist/server.js:41:38)
    at async Command.startServer (/directus/node_modules/directus/dist/server.js:128:20)
```

### What version of Directus are you using?

latest

### What version of Node.js are you using?

v16.14.0

### What database are you using?

ms sql

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-03-23 15:08
What version of MS SQL are you using? I can't reproduce this using MS SQL Server 2019

**Comment by joelee2017** [comment] 2022-03-24 00:22
> What version of MS SQL are you using? I can't reproduce this using MS SQL Server 2019

2016

**Comment by rijkvanzanten** [comment] 2022-03-25 17:45
How are you running MS SQL specifically? eg how can I reproduce this locally?

**Comment by joelee2017** [comment] 2022-03-28 00:51
>How are you running MS SQL specifically? eg how can I reproduce this locally?

MS SQL is 2016 ver  and  running on windowns server 2016 ,

create clean database on sql server name is  directus 

use the remote to call it on the computer

use the docker for windows running on my computer

Use the To Reproduce code in powershell

--------------------------------------------------------------------------------------------
00:36:57 ✨ Initializing bootstrap...
00:36:57 ✨ Installing Directus system tables...
00:36:58 ✨ Running migrations...
00:36:58 ✨ Applying Remove Collection Foreign Keys...
00:36:58 ✨ Applying Remove System Relations...
00:36:58 ✨ Applying Remove System Collections...
00:36:58 ✨ Applying Remove System Fields...
00:36:58 ✨ Applying Add Cascade System Relations...
00:36:58 ✨ Applying Change Webhook URL Type...
00:36:58 ✨ Applying Add Relations Sort Field...
00:36:58 ✨ Applying Remove Locked Fields...
00:36:58 ✨ Applying Webhooks Collections Text...
00:36:58 ✨ Applying Add Refresh Interval...
00:36:58 ✨ Applying Make Filesize Nullable...
00:36:58 ✨ Applying Add Collections Accountability...
00:36:58 ✨ Applying Remove Files Interface...
00:36:58 ✨ Applying Rename Interfaces...
00:36:58 ✨ Applying Restructure Relations...
00:36:59 ✨ Applying Add Foreign Key Constraints...
00:36:59 ✨ Applying Add System Fk Triggers...
00:36:59 ✨ Applying Add Collections Icon Color...
00:36:59 ✨ Applying Add Insights...
00:36:59 ✨ Applying Add Deep Clone Config...
00:36:59 ✨ Applying Change Filesize Bigint...
00:36:59 ✨ Applying Add Conditions to Fields...
00:36:59 ✨ Applying Add Default Folder...
00:36:59 ✨ Applying Replace Groups...
00:36:59 ✨ Applying Add Required to Fields...
00:36:59 ✨ Applying Update Groups...
00:36:59 ✨ Applying Change Image Metadata Structure...
00:36:59 ✨ Applying Add Geometry Config...
00:36:59 ✨ Applying Remove Limit Column...
00:36:59 ✨ Applying Add Auth Provider...
00:36:59 ✨ Applying Webhooks Collections Not Null...
00:36:59 ✨ Applying Move Module Setup...
00:36:59 ✨ Applying Webhooks URL Not Null...
00:36:59 ✨ Applying Add Collection Organization...
00:36:59 ✨ Applying Replace Fields Group...
00:36:59 ✨ Applying Replace M2M Interface...
00:36:59 ✨ Applying Rename Login Action...
00:36:59 ✨ Applying Update Presets...
00:36:59 ✨ Applying Add Auth Data...
00:36:59 ✨ Applying Add Webhook Headers...
00:36:59 ✨ Applying Set Unique to User Token...
00:36:59 ✨ Applying Update Special Geometry...
00:36:59 ✨ Applying Remove Collections Listing...
00:36:59 ✨ Applying Add Notifications...
00:36:59 ✨ Applying Add Shares...
00:37:00 ✨ Applying Add Project Descriptor...
00:37:00 ✨ Applying Remove Default Project Color...
00:37:00 ⚠️  Collection "directus_notifications" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_fields" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_activity" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_permissions" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_presets" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_relations" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_revisions" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_settings" doesn't have a primary key column and will be ignored
00:37:00 ⚠️  Collection "directus_webhooks" doesn't have a primary key column and will be ignored
TypeError: Cannot read properties of undefined (reading 'primary')
    at getASTFromQuery (/directus/node_modules/directus/dist/utils/get-ast-from-query.js:49:56)
    at ItemsService.readByQuery (/directus/node_modules/directus/dist/services/items.js:194:58)
    at RelationsService.readAll (/directus/node_modules/directus/dist/services/relations.js:66:49)
    at getDatabaseSchema (/directus/node_modules/directus/dist/utils/get-schema.js:131:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getSchema (/directus/node_modules/directus/dist/utils/get-schema.js:36:22)
    at async Command.bootstrap (/directus/node_modules/directus/dist/cli/commands/bootstrap/index.js:43:24)
    at async Command.parseAsync (/directus/node_modules/commander/lib/command.js:923:5)
npm notice
npm notice New minor version of npm available! 8.3.1 -> 8.5.5
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>
npm notice Run `npm install -g npm@8.5.5` to update!
npm notice
PS D:\ProjectTest\directus_test2> npm -v
8.5.5
PS D:\ProjectTest\directus_test2>

**Comment by rijkvanzanten** [comment] 2022-04-07 20:53
Could you check if those directus collections have primary keys configured? It looks like every directus collection that uses an auto increment ID is failing to register the primary key correctly 🤔 

Could you share a database dump of the output?

I'm still not able to reproduce this on my end unfortunately, so I'll have to close this for now.. Happy to keep debugging/discussing, and we'll reopen if we find a way to repro this 🙂

**Comment by joelee2017** [comment] 2022-04-11 03:42
> Could you check if those directus collections have primary keys configured? It looks like every directus collection that uses an  auto increment ID is failing to register the primary key correctly

primary keys  how should i see 



> Could you share a database dump of the output? 

this ?

![image](https://user-images.githubusercontent.com/33776374/162661650-8543d58b-0d7c-452b-9678-c24c9530b409.png)

**Comment by joelee2017** [comment] 2022-04-14 02:09
> The most helpful way for us to debug this would be to have a sql file dump of the database. That way, we can import the exact setup you're working with and debug with it 🙂


[directus.zip](https://github.com/directus/directus/files/8485727/directus.zip)

**Comment by joelee2017** [comment] 2022-05-11 02:14
hi,  there any chance of this issue being fixed?

**Comment by rijkvanzanten** [comment] 2022-05-11 13:28
[**Unfortunately, we can not provide estimates on features or fixes**](https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix). As of now, the only way to get an accurate timeline or release date is to [sponsor](https://docs.directus.io/getting-started/support.html#sponsored-work) this task. We recognize that this may be an important feature/fix, but we are a small open-source organization with a lot to triage and complete. If you can't sponsor this ticket, then the next best thing is to increase its priority by giving it a 👍 . Or contribute a pull-request... after all, this is OSS!

---

_This is an automated response._

**Comment by HuldaCZ** [comment] 2022-06-06 12:29
Hello, I had same error. Because I don't properly follow [documentation](https://docs.directus.io/configuration/upgrades-migrations/). 

My solution to this error was running command: `npx directus database migrate:latest`

**Comment by rijkvanzanten** [comment] 2022-12-15 22:38
Linear: [ENG-264](https://linear.app/directus/issue/ENG-264/cannot-read-properties-of-undefined-reading-primary)

**Comment by tazo90** [comment] 2022-12-23 18:33
I faced the same error when using `ItemsService` in my custom endpoint, probably after adding m2m relation. The workaround for me was to use a direct `knex` instance.

**Comment by saerdnaer** [comment] 2023-01-15 23:35
In my case the problem was that the directus postgres role did not have full rights to tables created outside of itself. So the first inspection query in https://github.com/directus/directus/blob/6793d9fd40958a2706fefdd988d34b1a9ecb3369/packages/schema/src/dialects/postgres.ts#LL32-L45C38 did not yield the new tables, but second one did.

When the data of the second query gets processed tring to acces `table_name` on the `overview` object fails:

https://github.com/directus/directus/blob/6793d9fd40958a2706fefdd988d34b1a9ecb3369/packages/schema/src/dialects/postgres.ts#L123-L125


Fixing the permissions via 
```sql
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO directus;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO directus;
```
resolved the issue for me.

**Comment by paescuj** [comment] 2023-02-03 14:53
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

Presumably the original problem was caused by some database permission issues (similar to https://github.com/directus/directus/issues/12319#issuecomment-1383285391) or maybe other special database configurations.
If the problem persists, please provide full details on how the database has been configured along with the user set-up. Thanks!

**Closed by paescuj** 2023-02-03 14:53 UTC
Labels: DB: MS SQL Server, Needs More Info, Bug (Potential), Can't Reproduce

**Comment by MaLub** [comment] 2023-02-09 08:59
> In my case the problem was that the directus postgres role did not have full rights to tables created outside of itself. So the first inspection query in https://github.com/directus/directus/blob/6793d9fd40958a2706fefdd988d34b1a9ecb3369/packages/schema/src/dialects/postgres.ts#LL32-L45C38 did not yield the new tables, but second one did.
> 
> When the data of the second query gets processed tring to acces `table_name` on the `overview` object fails:
> 
> https://github.com/directus/directus/blob/6793d9fd40958a2706fefdd988d34b1a9ecb3369/packages/schema/src/dialects/postgres.ts#L123-L125
> 
> Fixing the permissions via
> 
> ```sql
> GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO directus;
> GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO directus;
> ```
> 
> resolved the issue for me.

Thank you - solves for me also - it's related to permissions in the postgres. Maybe a more suitable error message would be helpful.

**Comment by hamishjohnson** [comment] 2023-06-15 05:13
> In my case the problem was that the directus postgres role did not have full rights to tables created outside of itself. So the first inspection query in https://github.com/directus/directus/blob/6793d9fd40958a2706fefdd988d34b1a9ecb3369/packages/schema/src/dialects/postgres.ts#LL32-L45C38 did not yield the new tables, but second one did.
> 
> When the data of the second query gets processed trying to access `table_name` on the `overview` object fails:
> 
> https://github.com/directus/directus/blob/6793d9fd40958a2706fefdd988d34b1a9ecb3369/packages/schema/src/dialects/postgres.ts#L123-L125
> 
> Fixing the permissions via
> 
> ```sql
> GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO directus;
> GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO directus;
> ```
> 
> resolved the issue for me.

When I run that SQL, I get `Failed to run sql query: role "directus" does not exist`

What is that role? I had a look and in my other directus project, this doesn't exist either 🤔

`npx directus database migrate:latest` didn't work too.

**Comment by saerdnaer** [comment] 2023-09-13 13:42
> What is that role? I had a look and in my other directus project, this doesn't exist either 🤔

That is a custom role for that project/database – but you have to check how the permissions are setup at your project yourself.

**Comment by stuikomma** [comment] 2023-11-06 11:54
Here's how you can easily find the offending table(s):

```sql
SELECT relname as table_name
     , pg_attribute.attname as column_name
FROM pg_index
   , pg_class
   , pg_attribute
   , pg_namespace
WHERE
        indrelid = pg_class.oid
  AND nspname IN ('public')
  AND pg_class.relnamespace = pg_namespace.oid
  AND pg_attribute.attrelid = pg_class.oid
  AND pg_attribute.attnum = ANY (pg_index.indkey)
  AND indisprimary
  AND indnatts = 1
  AND relkind != 'S'
AND relname not in (SELECT distinct c.table_name
FROM
    information_schema.columns c
    LEFT JOIN information_schema.tables t
ON c.table_name = t.table_name
WHERE
    t.table_type = 'BASE TABLE'
  AND c.table_schema IN ('public')) -- You may have to change the schema name, but typically, it is simply 'public'
AND relname NOT IN (SELECT distinct c.table_name
                    FROM
                        information_schema.columns c
                            LEFT JOIN information_schema.tables t
                                      ON c.table_name = t.table_name
                    WHERE
                            t.table_type = 'BASE TABLE'
                      AND c.table_schema IN ('public')); -- Also change the schema name here
```

**Why?**

The error happens in https://github.com/directus/directus/blob/c560f6b64b33067322a5712a6de6225ecab4cdc3/packages/schema/src/dialects/postgres.ts#L202-L203

It takes the results of these two queries: [columnsResult](https://github.com/directus/directus/blob/c560f6b64b33067322a5712a6de6225ecab4cdc3/packages/schema/src/dialects/postgres.ts#L109-L123) and [primaryKeysResult](https://github.com/directus/directus/blob/c560f6b64b33067322a5712a6de6225ecab4cdc3/packages/schema/src/dialects/postgres.ts#L130-L144). If a table is listed in `primaryKeysResult` but not in `columnsResult`, you will get that error. The SQL above simply combines the two queries.

The same _may_ happen with `geometryColumns`, but I haven't used this, yet. ymmv.
