### ISSUE TITLE
Google login (oauth) is not working on 10.1.0 (self hosted docker)

### ISSUE THREAD

**Issue by davidpp** [directus/directus#18625] opened 2023-05-16 13:10 UTC
### Describe the Bug

After updating to Directus 10.1.0 (from 9.26), users using Google login can go through the Google login flow as usual, but once completed, they get redirected to the login page with an "Unexpected error" message.

Looking in the browser console, I can see a 400 error on auth/refresh with the following message:

`{"errors":[{"message":"\"refresh_token\" is required in either the JSON payload or Cookie","extensions":{"code":"INVALID_PAYLOAD"}}]}`

It's a production release (not localhost) and SSO was working before the update to 10.1.0.

Update:

On the server side, I found the following in the log:

```
[13:12:00.409] WARN: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.
    err: {
      "type": "Error",
      "message": "Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.",
      "stack":
          Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.
              at QueryCompiler_PG._prepUpdate (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:1354:13)
              at QueryCompiler_PG.update (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/dialects/postgres/query/pg-querycompiler.js:51:29)
              at QueryCompiler_PG.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:73:29)
              at QueryBuilder_PostgreSQL.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querybuilder.js:83:44)
              at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
              at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:300:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:30:19)
              at async file:///directus/node_modules/.pnpm/@directus+api@10.1.0/node_modules/@directus/api/dist/services/items.js:471:21
    }
[13:12:00.409] WARN: [OpenID] Unexpected error during OpenID login
    err: {
      "type": "Error",
      "message": "Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.",
      "stack":
          Error: Empty .update() call detected! Update data does not contain any values to update. This will result in a faulty query. Table: directus_users. Columns: auth_data.
              at QueryCompiler_PG._prepUpdate (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:1354:13)
              at QueryCompiler_PG.update (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/dialects/postgres/query/pg-querycompiler.js:51:29)
              at QueryCompiler_PG.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querycompiler.js:73:29)
              at QueryBuilder_PostgreSQL.toSQL (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/query/querybuilder.js:83:44)
              at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:4:30)
              at Runner.ensureConnection (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:300:20)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Runner.run (/directus/node_modules/.pnpm/knex@2.4.2_mysql@2.18.1_pg@8.10.0_sqlite3@5.1.6_tedious@16.0.0/node_modules/knex/lib/execution/runner.js:30:19)
              at async file:///directus/node_modules/.pnpm/@directus+api@10.1.0/node_modules/@directus/api/dist/services/items.js:471:21
    }
```

### To Reproduce

- Have Google oauth login enabled
- Have a user with Provider set to "Google"
- Try to login with Google

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-05-17 13:14
Thanks for opening this issue! However this is a duplicate of an existing issue #18595, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #18595 has been fixed by #18607 and released with [v10.1.1](https://github.com/directus/directus/releases/tag/v10.1.1).

**Closed by paescuj** 2023-05-17 13:14 UTC
