### ISSUE TITLE
Snapshot.yml not work

### ISSUE THREAD

**Issue by jorge6242** [directus/directus#16610] opened 2022-11-24 23:53 UTC
### Describe the Bug

Hi !
I try to apply my snaphot.yml from de server dev to my local , but nothing happens, and I don't know why!

Actually I create another new cms project, in order to apply the same .yml , but not work anyway

![image](https://user-images.githubusercontent.com/15070448/203875556-76664a62-50f6-4157-ab12-e86f37b82b42.png)

I have the complete message with the attach snapshot.yml file in the directus discord comunity https://discord.com/channels/725371605378924594/1045451194392383601/1045451194392383601

### To Reproduce

- I have my local with a old version of my models
- In my dev server, I create new models and remove as well
- In my dev server I create the snapshot again
- I commit the changes of my snapshot
- I pull the changes in my local in order to have the snapshot file updated
- I apply the snapshot in my local , and nothing happern

NOTE: When I create another new directus cms project , and use the same snapshot is working, but in my current repo , in my local , not work, What I do wrong?

### Errors Shown

Nothing

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

v14.20.1

### What database are you using?

local postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Not yet,

**Comment by paescuj** [comment] 2022-11-25 01:59
Probably duplicate of  #16503.

**Comment by azrikahar** [comment] 2022-11-25 04:09
>  but nothing happens

If you're trying this on `9.20.4` as described, there's likely logs (could also be "No changes to apply" logs) that are not showing up due to #16284, in which case I'd recommend setting `LOG_STYLE=raw` to surface them in the meantime 🙂

I've confirmed the schema snapshot you shared on discord to work on `9.20.4`:

https://user-images.githubusercontent.com/42867097/203899052-2b2010e7-10b4-42f8-a074-d3f3ebe40c6d.mp4

(zipped) schema snapshot shared by OP on discord:

[snapshot-23-11-2022.zip](https://github.com/directus/directus/files/10088520/snapshot-23-11-2022.zip)

---

Apart from that, if you are having any issue in `9.21.0` instead (as your schema snapshot indicates it is from this version, not `9.20.4`, then it should be the same issue #16503 as @paescuj pointed out 👍

**Closed by azrikahar** 2022-11-25 04:09 UTC
