### ISSUE TITLE
Capital letters in Collection name causes issues

### ISSUE THREAD

**Issue by dinglewanker** [directus/directus#19971] opened 2023-10-10 00:55 UTC
### Describe the Bug

When creating a Collection like "LoveTable" works.  But when you go back to the DataModel page and try to add a new Field.  It gives a error.  Looks like it's it's trying to reference a lowercased .frm filename.  When the mysql filename is actually Capitalized.  Example below is looking for "lovetable.frm" when the file that created was "LoveTable.frm"  

`{
  "errors": [
    {
      "message": "alter table LoveTable add Name varchar(255) null - ER_NOT_FORM_FILE: Incorrect information in file: './mydatabase/lovetable.frm'",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}`

### To Reproduce

Using docker compose file....

```
version: "3.8"
services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}   # set the root password
      MYSQL_DATABASE: "${DB_DATABASE}"             # database name to create on startup
      MYSQL_USER: "${DB_USER}"                     # new user to create on startup
      MYSQL_PASSWORD: "${DB_PASSWORD}"             # password for the new user
    ports:
      #- ${DB_PORT}:3306
      - "127.0.0.1:${DB_PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
  directus:
    image: directus/directus:10.6.3
    ports:
      - ${DUS_PORT}:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./data/directus/extensions:/directus/extensions
    depends_on:
      - database
    environment:
      KEY: 'zzz'     # Run `uuidgen`
      SECRET: 'zzz'  # Run `openssl rand -hex 32`
      DB_CLIENT: "mysql"              # Use MySQL as the database client
      DB_HOST: "database"             # database is the name of the database container
      DB_PORT: ${DB_PORT}
      DB_DATABASE: '${DB_DATABASE}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      ADMIN_EMAIL: '${DUS_ADMIN_EMAIL}'
      ADMIN_PASSWORD: '${DUS_ADMIN_PASSWORD}'

```

### Directus Version

v10.6.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-10-10 02:33
Directus itself doesn't generate or use frm files, which leads me to believe this must be specific to MySQL running on your exact environment. What OS are you using?

**Comment by dinglewanker** [comment] 2023-10-10 02:54
Using the official MySQL docker image. 

mysql:5.7

I would assume others are using the same image?

**Comment by azrikahar** [comment] 2023-10-10 06:46
Unfortunately I was not able to reproduce this error with the `mysql:5.7` image using the same table name of `LoveTable`, as I was able to add multiple new fields to that collection right after creating it.

Granted I'm not super familiar with the error code myself, some brief searches online leads me to believe that this is more of a corrupted MySQL database/table rather than a bug in Directus.

Can you try spinning up the mysql container again _without_ binding the `./data/db:/var/lib/mysql` volume as a sanity check? Presumably `./data/db` is somehow corrupted. Another attempt would be to not bind `./data/directus/extensions:/directus/extensions` for the Directus container as well just in case this might be caused by those extensions (if any).

That being said, I'll proceed to close this issue for now as it is not reproducible, but feel free to let us know if you can still reproduce this reliably with a fresh mysql container without binding any volume for said container.

**Closed by azrikahar** 2023-10-10 06:46 UTC
Labels: Needs More Info
