### ISSUE TITLE
Glitchy WYSIWYG Editor with custom format

### ISSUE THREAD

**Issue by tevarg** [directus/directus#23908] opened 2024-10-24 02:19 UTC
### Describe the Bug

I use a WYSIWYG editor with a custom format in my blog articles, which looks like this:

```
[
    {
        "title": "Info Card",
        "inline": "span",
        "styles": {
            "background-color": "#bee6ec",
            "border-width": "1px",
            "border-radius": "5px",
            "padding": "1rem 1rem 1rem 3.5rem",
            "color": "#0c5460",
            "border-color": "#bee6ec",
            "display": "flow-root",
            "margin": "2rem 0",
            "background-image": "url(https://cms.mekanika.io/assets/444996d5-08f7-4052-9e11-542a51e0809c)",
            "background-size": "40px",
            "background-position": "0.5rem",
            "background-repeat": "no-repeat"
        },
        "attributes": {
            "title": "Info Card"
        }
    }
]
```

It was working fine until very recently (maybe the last update I did from 11.0.1). Now, when a user types a few characters inside the WYSIWYG editor, the cursor glitches or disappears, and the page scrolls down, making it unusable. As soon as I remove the custom formatting, the bug disappears. I tried using other formats, simpler ones, but it still doesn't work either.

Is there anyone who could point me in the right direction to solve this? I don't have many ideas of the origin of this issue.

It is happening on our production server, running Directus 11.1.1 with Docker.

### To Reproduce

Create a new collection with a WISYWYG Editor. Try writing content in it; there are no issues. Now add a custom to it and try writing content; you should see the glitch described.

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-10-24 06:45
This is a duplicate of #23869 which has already been addressed via #23881. The fix will be available with the next release 👍

**Closed by paescuj** 2024-10-24 06:45 UTC
