### ISSUE TITLE
(Self-Hosted) Error when uploading SVG File

### ISSUE THREAD

**Issue by Mat4m0** [directus/directus#22214] opened 2024-04-16 16:58 UTC
### Describe the Bug

When uploading an SVG to my file library, I get the following error:

{
  "errors": [
    {
      "message": {
        "length": 140,
        "name": "error",
        "severity": "ERROR",
        "code": "22P02",
        "where": "unnamed portal parameter $6 = '...'",
        "file": "numutils.c",
        "line": "316",
        "routine": "pg_strtoint64"
      },
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

I tried on 2 different hosted instances on DigitalOcean, but same result.

### To Reproduce

- Host Directus on Digital Ocean
- Connect Supabase as DB and use their Bucket for file storage
- Go To Directus and Upload A SVG Image
- Error Should appear

### Directus Version

v10.10.5

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-04-16 17:00
Duplicate of https://github.com/directus/directus/issues/22168

**Closed by br41nslug** 2024-04-16 17:00 UTC
