### ISSUE TITLE
Error generating SQL with nested m2o->m2m filter

### ISSUE THREAD

**Issue by martijnboland** [directus/directus#5245] opened 2021-04-25 22:20 UTC
Directus 9.0.0-rc.60, PostgreSQL 12

I have a table 'event' that has m2o relation to a 'project' table. The 'project' table then has a m2m relation with 'directus_user' via a 'shared_with' table. 

Now when filtering on the 'directus_user_id' property of the 'shared_with' table, I get the following error:
```
error: select ... (snip fields) from "event" left join "project" as "hkece" on "event"."project_id" = "hkece"."id" where ("qjvzm"."directus_user_id" = $1) order by "event"."id" asc limit $2 - missing FROM-clause entry for table "qjvzm"
```

It looks like the m2m table is missing in the joins. When I directly query the project table and apply the same filter, everything works as expected. 
Below is the filter:

```
{
    "project_id": {
        "shared_with": {
            "directus_user_id": {
                "_eq": "$CURRENT_USER"
            }
        }
    }
}
```
BTW, this filter used to work correclty in version 9.0.0-rc.44.

**Comment by rijkvanzanten** [comment] 2021-04-25 22:31
Duplicate of https://github.com/directus/directus/issues/4485

**Closed** 2021-04-25 22:31 UTC
Labels: Duplicate

**Comment by martijnboland** [comment] 2021-04-26 07:32
Looks like the bug is introduced when the o2m join logic was refactored to prevent duplicate records (https://github.com/directus/directus/pull/4278). Want me to have a look at it?

**Comment by rijkvanzanten** [comment] 2021-04-26 13:41
@martijnboland Sure thing!
