### ISSUE TITLE
Block Editor Toggle Block errors

### ISSUE THREAD

**Issue by sladeslocksmith** [directus/directus#20524] opened 2023-11-26 01:37 UTC
### Describe the Bug

I'm getting the following errors when using the Toggle block in the Block Editor:

![toggle-errors](https://github.com/directus/directus/assets/147755112/9841aa32-e04a-480a-90b7-14b488dfb0b9)

It doesn't seem to be saving correctly, I'm unable to return to the editor and toggle the items again, as they appear to have broken out of the Toggle, as seen in the below image (the paragraphs are no longer in the toggle and clicking the arrows don't toggle anything.)

![toggle2](https://github.com/directus/directus/assets/147755112/a8e17308-64bf-46d4-9b68-95a646b8e45f)

### To Reproduce

Go into the block editor and try to add Toggle Blocks, a title for the toggle and paragraphs below the title of the toggle. Then save, then come back and see that the toggles don't work and that when getting the data the json it's not as it should be. Check console for errors.

Note: I'm using Brave (chrome) with Brave Shields turned off for the Studio.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Natetronn** [comment] 2023-11-26 02:01
Forgot to switch from the client account to my own...following.

**Comment by paescuj** [comment] 2023-12-12 17:10
While I couldn't actually reproduce the issue on my end, it looks exactly like https://github.com/kommitters/editorjs-toggle-block/issues/206. That issue has been fixed in [`editorjs-toggle-block@0.3.12`](https://github.com/kommitters/editorjs-toggle-block/releases/tag/v0.3.12) which is included in #20714 on our end and will be available with the next release. I'm closing this issue for now, but we'll reopen if it turns out it's still a problem.

**Closed by paescuj** 2023-12-12 17:10 UTC
Labels: Package: @directus/app, Bug
