### ISSUE TITLE
is there a way to have section breaks displayed as tabs ?

### ISSUE THREAD

**Issue by MartinMekhaiel** [directus/directus#1812] opened 2017-09-14 02:01 UTC
meaning every column under a section break is showed under the specific tab on the entry page?  

e.g

Section 1
Name
Description
Section 2 
Rating
Price

**|__tab (Section 1)__|** 
name                           
description

 **|__tab (Section2)__|**
rating
price

As the forms can get really long if you have many fields

Thanks for the response!

**Comment by WellingGuzman** [comment] 2017-09-14 02:41
Do you mean collapse (hide) the elements of each section?

**Comment by MartinMekhaiel** [comment] 2017-09-14 02:44
Yes or maybe also tabbed content 

eg. 
![responsive-multipurpose-tabs-accordion-plugin-with-jquery](https://user-images.githubusercontent.com/7896311/30409769-68917818-9907-11e7-9946-f3b221ae8b12.jpg)

**Comment by WellingGuzman** [comment] 2017-09-14 02:54
As now Directus doesn't support this yet. Although this feature you request has been discussed before (internally), you can open one on https://feathub.com/directus/directus.

As this is not a bug I will close it.

**Closed by WellingGuzman** 2017-09-14 02:54 UTC

**Comment by MartinMekhaiel** [comment] 2017-09-14 03:04
thanks
