### ISSUE TITLE
How can I save cropped images?

### ISSUE THREAD

**Issue by Cruddy56** [directus/directus#2095] opened 2018-03-12 19:47 UTC
Hi, I'm developing custom Cropper Interface, based on cropperjs. Almost everything works, there are only two things left to be done. That is: to save the cropped images and to make them available throught API. 

And there is a question: How can I do that?

I've tried to save/upload cropped images in similar way as in Single File Interface(this.fileModel.setFile(...)), but it didn't work, as I expected :(. Is there any trigger-kind-thing which upload file to the server? Or maybe I'm missing something and there is very easy way to that? I think it is important to point out that I intend to upload many images at once/per item in table.

**Comment by WellingGuzman** [comment] 2018-03-13 11:47
Are the cropped image the original image or the thumbnail of the original image?
Are you getting any error? or what exactly is not working?

As you mention `setFile` https://github.com/directus/directus/blob/2c1135cbb44f4157d5e919527ec7baa8b06876ee/app/core/interfaces/single_file/interface.js#L121
Set the data of the file, but this method expect a [File Object](https://developer.mozilla.org/en-US/docs/Web/API/File)

In your case what you can do here is set the data as an object and do any validation in the interface (if needed).

Example:

```js
// Make sure model is the filemodel
model.set({
  id: undefined, // make sure the id is not defined, new file, otherwise update
  name: 'image.jpg',
  title: 'My image title',
  size: 200, // size in bytes
  type: 'image/jpg', // mime type
  charset: 'binary',
  data: fileData // file data content encoded in base64
});
```

I will close this ticket as it's not a bug per se, but a lack of documentation.

Please if you still having issue with this, we can keep the conversation going here. also you are welcome into our [slack](https://slack.getdirectus.com) or ask on [stackoverflow](https://stackoverflow.com/questions/tagged/directus).

**Closed by WellingGuzman** 2018-03-13 11:47 UTC

**Comment by Cruddy56** [comment] 2018-03-14 08:29
> Are the cropped image the original image or the thumbnail of the original image?

None of them. What I need to do, is to add additional versions of image for different aspect ratios(16:9, 4:3, etc.), and than when I use API to request json object (ex.: "http://example.com/directus/api/1.1/files/1"), I want to receive something like this:
```
"data":	{
	"id":1,
	"status":1,
	"name":"00000000001.jpg",
	"title":"Mountain Range",
	"location":"Earth",
	"caption":"A gorgeous view of this wooded mountain range",
	"type":"image\/jpeg",
	"charset":"binary",
	"tags":"trees,rocks,nature,mountains,forest",
	"width":1800,
	"height":1200,
	"size":602058,
	"embed_id":null,
	"user":1,
	"date_uploaded":"2018-01-26T14:39:58-05:00",
	"storage_adapter":"local",
	"url":"\/directus\/storage\/uploads\/00000000001.jpg",
	"thumbnail_url":"\/directus\/storage\/uploads\/thumbs\/1.jpg",
	"old_thumbnail_url":"\/directus\/storage\/uploads\/thumbs\/00000000001-jpg-160-160-true.jpg",
	"sixteen_nine_url": "\/directus\/storage\/uploads\/16_9\/1-16-9.jpg",
	"four_three_url": "\/directus\/storage\/uploads\/4_3\/1-4-3.jpg,
	"html":null
}
```

**Comment by WellingGuzman** [comment] 2018-03-16 20:30
@Cruddy56 In that case:

- Create a custom endpoint that saves the file to the thumbs directory
- Add a filter hook that adds the new params: `four_three_url`, etc. every time you fetch data from files table. ([Directus Hooks](https://github.com/directus/docs/blob/master/developer-guide/hooks.md))

**Comment by Cruddy56** [comment] 2018-03-19 12:36
Ok, I've created a filter hook and it almost work. All I need, is to somehow "get" a url to thumbs.

But I'm not sure how to create a custom endpoint, and how to use it to save new thumbs(16:9, 4:3, etc.).
I think that example of creating and using it in js could help me a little.

Is it possible to save multiple thumbs at once? For example by creating a collection/array of files to save?

**Comment by Cruddy56** [comment] 2018-03-22 14:46
Custom endpoint and filter hook work.
Did Directus somehow prevent php from saving files directly into the server?
I've tried with:
```php
$path = $root_ratios_url.'/'.$f->dir.'/'.$f->name;
$data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $f->encoded));
file_put_contents($path, $data);
```
but it throws error:
>file_put_contents(/directus/storage/uploads/ratios/free/00000000015-Free-Free.png): failed to open stream: No such file or directory

so I've tried in other way:
```php
$path = $root_ratios_url.'/'.$f->dir.'/'.$f->name;
$data = base64_decode(preg_replace('#^data:image/\w+;base64,#i', '', $f->encoded));
$handle = fopen($path, "w");
if ($handle) {
    $fwrite($handle, $data);
    $fclose($handle);
}
```
end again it throws error:
>fopen(/directus/storage/uploads/ratios/free/00000000015-Free-Free.png): failed to open stream: No such file or directory

ratios directory, and all subdirectories(free, etc.) are present.

Do you have any idea what am I doing wrong?
