### ISSUE TITLE
In 9.24 "Sort Field" does not work in relational fields

### ISSUE THREAD

**Issue by Pachat** [directus/directus#18111] opened 2023-04-08 13:36 UTC
### Describe the Bug

When specifying another field than "sort" to sort relational rows, Directus keeps sorting in "sort"

### To Reproduce
In 9.24

- Have a collection R that can has two sort fields "sort_a" and "sort_b" other than "sort"
- In a main collection A, in the relational field to R, choose "sort_a" as a Sort Field
- In a main collection B, in the relational field to R, choose "sort_b" as a Sort Field

Whatever values you have in "sort_a" or "sort_b", either in collection A and collection B, Directus will not sort

The motivation here is that the presentation of collection R has to be sorted in a different order within collection A and collection B.

After some tries on "sort" only, it appears that R is not sorted either when set on "sort".

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-04-10 12:58
Looks to be a duplicate of https://github.com/directus/directus/issues/18096 applicable to any multiple relation o2m/m2m/m2a

**Closed by br41nslug** 2023-04-10 12:58 UTC
