### ISSUE TITLE
Sorting in backend removes relationship dependencies

### ISSUE THREAD

**Issue by firstIssue** [directus/directus#3983] opened 2021-02-09 13:05 UTC
When using the standard 'sort' field in a relational field, it just removes another relation when being drag/dropped.

I have a station with relation to scenes, those scenes again have relations to contents.
If I drag the scenes in their order and save, directus removes the relation to the content and generates a new empty one.

---

### Project details
Directus Version: 9.0.0-rc.34
Environment: production
OS: Linux 4.15.0-88-generic
Node: 10.23.2

**Comment by rijkvanzanten** [comment] 2021-02-09 14:49
@firstIssue Would you be able to share a DB dump where this is happening? Saves me a bunch of time trying to reproduce your exact setup based on this:

> I have a station with relation to scenes, those scenes again have relations to contents.

🙂

**Comment by firstIssue** [comment] 2021-02-09 14:52
> @firstIssue Would you be able to share a DB dump where this is happening? Saves me a bunch of time trying to reproduce your exact setup based on this:
> 
> > I have a station with relation to scenes, those scenes again have relations to contents.
> 
> 🙂

What format do you need

**Comment by firstIssue** [comment] 2021-02-09 14:54
> > @firstIssue Would you be able to share a DB dump where this is happening? Saves me a bunch of time trying to reproduce your exact setup based on this:
> > > I have a station with relation to scenes, those scenes again have relations to contents.
> > 
> > 
> > 🙂
> 
> What format do you need

> @firstIssue Would you be able to share a DB dump where this is happening? Saves me a bunch of time trying to reproduce your exact setup based on this:
> 
> > I have a station with relation to scenes, those scenes again have relations to contents.
> 
> 🙂
I hope this is the right format for you, not that familar with DB exporting and handling.
[dump (1).zip](https://github.com/directus/directus/files/5952118/dump.1.zip)

**Comment by rijkvanzanten** [comment] 2021-02-09 14:55
A SQL dump like you provided is perfect! That being said.. You shared an empty file 😁

**Comment by rijkvanzanten** [comment] 2021-02-23 22:31
I'll close this for now as I can't reproduce it, and the provided DB dump is totally empty..

@firstIssue Is this still happening for you? If so, can you share a db dump?

**Comment by firstIssue** [comment] 2021-02-24 06:40
Did you check the dump I sent you via mail? As this one here was the wrong one, the one per mail is 1,2MB. @rijkvanzanten

**Comment by rijkvanzanten** [comment] 2021-02-24 18:00
Ah, I didn't realize that was you haha. Thanks! @firstIssue

**Comment by benhaynes** [comment] 2021-04-02 17:49
@rijkvanzanten  — Is this the same issue as: https://github.com/directus/directus/issues/3875

**Comment by rijkvanzanten** [comment] 2021-04-02 19:05
Could be, hard to tell from the known info on both

**Comment by rijkvanzanten** [comment] 2021-05-14 16:53
I believe this is fixed in https://github.com/directus/directus/pull/5484

**Closed by rijkvanzanten** 2021-05-14 16:53 UTC
Labels: App, Bug
