### ISSUE TITLE
Sort field is not auto populated when creating new item in O2M relationship

### ISSUE THREAD

**Issue by yipivan** [directus/directus#23661] opened 2024-09-13 08:38 UTC
### Describe the Bug

When I create O2M relational items in a list, and they are sorted using a sort field. The sort field is not auto populated when I first create the item. It only appears when I save the item or rearrange the orders.

For example, the sort field reappear after I reorder the items
![directus](https://github.com/user-attachments/assets/aca559b5-3866-4aee-b514-7cf3b056b283)

Or save the item
![directus 1](https://github.com/user-attachments/assets/69b52d91-08aa-4832-871f-282ff2fb2053)

### To Reproduce

Create two collections A and B, and they are in O2M relationship with A has many B, and B has a sort field.
Create new items A, and then create child items B, observe the raw values or interface

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

mysql

**Comment by paescuj** [comment] 2024-09-13 09:18
Thanks for opening this issue! However this is a duplicate of an existing issue #19795, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #19795 for future updates.

**Closed by paescuj** 2024-09-13 09:18 UTC
