### ISSUE TITLE
Value of Sort Field in Collections Data Model keeps resetting

### ISSUE THREAD

**Issue by echocrow** [directus/directus#21170] opened 2024-01-23 15:42 UTC
### Describe the Bug

Collections can be configured with a custom "Sort Field", enabling a convenient sorting UI for the items of that collections.

However, when navigating to the data model config of a collection, the "Sort Field" is initialized with an empty value, and the data model form is marked as "dirty" (pending save).

### To Reproduce

1. Create a collection with a numerical field called "sort"
2. When editing the collection data model, select the "sort" field in the "Sort Field" field.
3. Save the collection's data model
4. Navigate back to the collection's data

Expected:
- No changes on page load
- "Sort Field" references "sort" field

Observed:
- Data model has a pending change after page load
- "Sort Field" is empty

---

Screen recording demonstrating this behavior:
https://github.com/directus/directus/assets/5488190/87c01072-b52b-433d-82b4-d957de3de17b

### Directus Version

v10.3.8

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment] 2024-01-23 15:43
Duplicate of https://github.com/directus/directus/issues/20871 will be fixed in the next release

**Closed by br41nslug** 2024-01-23 15:43 UTC
