### ISSUE TITLE
Fields are wrongly considered individually-unique when part of composite constraint

### ISSUE THREAD

**Issue by cah4a** [directus/directus#9217] opened 2021-10-28 12:36 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Despite directus is not supporting composite keys it still tries to handle them and make it worse.

It sees that a database has a composite unique key, and thinks that there are several unique keys for every field in that key. 

When I try to uncheck "Unique field" in the app, it shows an error that the index doesn't exist.
When I try to save'n'restore snapshot it creates multiple unique keys, instead of composite.

### To Reproduce

1. Create a table with fields:
- id
- foo
- bar

2. Add unique index (foo, bar) via custom migration

3. App thinks that I have two unique keys. One for every field in that index.

4. Make `directus schema snapshot`

5. After restoring that snapshot there are two unique keys instead of one composite with two fields.

### What version of Directus are you using?

9.0.0-rc.99

### What version of Node.js are you using?

12.22.7

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by jaycammarano** [comment] 2021-11-02 14:43
Hello,
Would the expected behavior be to support composite keys or to ignore them? Or something else?

**Comment by rijkvanzanten** [comment] 2021-11-02 14:46
@jaycammarano At this point, the first step is to make sure Directus doesn't break if you're using composite keys 👍🏻 After that, we can figure out what it would take to properly _support_ them in the app/api (eg how to configure them, how to handle it in routing/relations etc etc)

**Comment by rijkvanzanten** [comment] 2021-11-02 14:57
@jaycammarano I think it goes deeper than that. The API currently isn't "aware" of any composite keys, so tries treating unexpectedly, like:

> It sees that a database has a composite unique key, and thinks that there are several unique keys for every field in that key.

and 

> When I try to uncheck "Unique field" in the app, it shows an error that the index doesn't exist.

. 

That being said, we've never supported composite keys, so i personally see this as a new feature rather than a bug fix. @Oreilles what was your reasoning for marking this as a bug rather than a new feature (and in turn a semi-duplicate of https://github.com/directus/directus/discussions/7721) ?

**Comment by Oreilles** [comment] 2021-11-02 15:50
Wasn't aware of https://github.com/directus/directus/discussions/7721!
While supporting compound constraints definetly is a new feature, I think interpreting them as individual ones can be considered a bug: columns aren't individually unique, so showing them as such is false, and treating them as such leads to the issues @cah4a mentioned.

**Comment by rijkvanzanten** [comment] 2021-11-02 18:58
Ah yeah that part makes total sense 👍🏻

**Comment by cah4a** [comment] 2021-11-02 19:02
@Oreilles Yes, that's the point, thanks.
If directus could work with composite keys it would be awesome, but it's a completely different story.

**Comment by cah4a** [comment] 2021-11-02 19:38
I found the bug ;)

[That request](https://github.com/knex/knex-schema-inspector/blob/master/lib/dialects/postgres.ts#L264) is searching across all unique keys including composite because of the missing `indnkeyatts = 1` check.

Shall I open PR?

**Comment by rijkvanzanten** [comment] 2021-11-02 19:49
@cah4a Yes please!

**Comment by Oreilles** [comment] 2021-11-26 09:45
This has been fixed in `knex-schema-inspector 1.6.5` (Ref https://github.com/knex/knex-schema-inspector/commit/b2e3ace20777d34aa2f7bfe392dc6df353af16af https://github.com/knex/knex-schema-inspector/commit/cfe7cdb123fce646a3c33a9ae8709f8629058986 https://github.com/knex/knex-schema-inspector/commit/3b40c2c2348518caac0b65978161d0e9e876e07a )

**Closed by Oreilles** 2021-11-26 09:45 UTC
Labels: API, Bug

**Comment by schlensen** [comment] 2021-11-29 15:07
Hi there,

just a question: are you aware that this change breaks / broke support for PostgreSQL 10? (pg_index has no attribute indnkeyatts, see https://www.postgresql.org/docs/10/catalog-pg-index.html).

We are just setting up directus using AWS Aurora Serverless as Database provider, which (for now) only supports PostgreSQL 10 and we ran into this problem. 

Maybe you could provide a list of compatible databases / version?

Best regards and thanks in advance,

Jan

**Comment by Oreilles** [comment] 2021-11-29 15:22
@schlensen that wasn't known, thanks you for telling us. Would you mind creating a new issue so that we can track this and find the best solution ?

**Comment by schlensen** [comment] 2021-11-29 15:24
Hey @Oreilles, yes I'll open an issue, thank you. :)
