### ISSUE TITLE
"Unexpected error" when resetting password

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#23248] opened 2024-08-08 06:09 UTC
### Describe the Bug

When redefining a password via email, using the button "Forgot password", as soon as I try to set a new password, I get: "Unexpected error". Under the networks tab in the DevTools there's a "400 Bad Request".

After scratching my head for almost too long, I noticed that this happens when a password **does not meet the minimum requirements** set in the user profile. 

![image](https://github.com/user-attachments/assets/ca26115d-6b81-4b0f-ae58-513db91059b7)

Would be nice to have a clearer error message.

### To Reproduce

\-

### Directus Version

11.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres 15

**Comment by paescuj** [comment] 2024-08-08 07:56
Thanks for opening this issue! However this is a duplicate of an existing issue #21971, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #21971 for future updates.

**Closed by paescuj** 2024-08-08 07:56 UTC
