### ISSUE TITLE
Docker Directus V9.22.1 health check crashes service

### ISSUE THREAD

**Issue by stormbyte** [directus/directus#17088] opened 2023-01-11 12:10 UTC
### Describe the Bug

When I open the server health page `https://directus.local/server/health` the node application crashes.
In my docker-compose I have the following health check:
```
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8055/server/health
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3
```
What crashes the application almost as soon as it started.

If I disable the health check the service keeps running.

### To Reproduce

Run the directus container
```
image: directus/directus:9.22.1
```

wait for the message:
```
xxx_directus-1  | [11:50:35.588] INFO: Initializing bootstrap...
xxx_directus-1  | [11:50:35.675] INFO: Database already initialized, skipping install
xxx_directus-1  | [11:50:35.675] INFO: Running migrations...
xxx_directus-1  | [11:50:35.682] INFO: Done
xxx_directus-1  | [11:50:39.907] WARN: PUBLIC_URL should be a full URL
xxx_directus-1  | [11:50:40.213] INFO: Server started at http://0.0.0.0:8055
```
And if you then open the `server/health` url the service would crash

### Errors Shown

Error
```
xxx_directus-1  | node:events:491
xxx_directus-1  |       throw er; // Unhandled 'error' event
xxx_directus-1  |       ^
xxx_directus-1  | 
xxx_directus-1  | Error: ENOENT: no such file or directory, open '/directus/uploads/health-YmEki'
xxx_directus-1  | Emitted 'error' event on ReadStream instance at:
xxx_directus-1  |     at emitErrorNT (node:internal/streams/destroy:151:8)
xxx_directus-1  |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
xxx_directus-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
xxx_directus-1  |   errno: -2,
xxx_directus-1  |   code: 'ENOENT',
xxx_directus-1  |   syscall: 'open',
xxx_directus-1  |   path: '/directus/uploads/health-YmEki'
xxx_directus-1  | }
xxx_directus-1  | 
xxx_directus-1  | Node.js v18.12.1
```

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

mysql:8

### What browser are you using?

firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2023-01-11 12:21
Duplicate of #16904

**Closed by azrikahar** 2023-01-11 12:21 UTC

**Comment by fitu86** [comment] 2023-03-05 08:32
prueba cambiando el localhost de http://127.0.0.1 a http://172.18.0.1, a mi me funciono.
