### ISSUE TITLE
Custom field'S default value not sent to flow

### ISSUE THREAD

**Issue by rowild** [directus/directus#19360] opened 2023-08-06 15:01 UTC
### Describe the Bug

When a "native" Directus table like directus_users is extended – e.g. by adding a "newsletter" toggle field as it is done in this "Watch&Learn" video: https://www.youtube.com/watch?v=RoIruJEiYm4 – then the default value is not picked up by a flow operation.
The given video example builds a newsletter list: a user, whose "newsletter" toggle is set to "true", is saved to a "newsletter list" collection. To do so, the "newsletter" toggle is created in the "directus_user" table, and its default value is set to "true". It does not seem to be a problem in the video, but at least with Directus 10.5.2 the DEFAULT value of the "newsletter" toggle field is never sent to the flow. Only if the newsletter toggle is changed and set to "false", then it becomes part of the payload.

This is problematic, because, even if the value is initially set to "false" (so the change to "true" is recognized and therefore part of the payload), once the user decides to unsubscribe and therefore sets the value to "false" again, that very value is the default value and therefore not delivered as part of the payload. Therefore the flow causes and error and does not remove the user from the nrewletter list.

Meaning: the user never can never unsubscribe...

### To Reproduce

- Add a toggle field "newsletter" to the directus_user table with "true" as default value
- Create a new collection "newsletter_list" with the fields "first_name", "last_name" and "email"
- Create a flow "Newsletter List" which triggers, when a new user is created
(- continue creating the flow as described in the video, but ATM this is enough, simply check the log to see what is happening)

- Create a user – do not change the value of the newsletter togge
- Check the console to see that the newsletter toggle value is not part of the payload
- Create another user, change the newsletter toggle value
- Check the flow log: not "newsletter" is part of the payload

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-08-07 10:36
This is technically working as intended, default values aren't included in the payload because they will be set on the database level. Therefore not quite sure, if this falls more into the category of a feature request.

**Comment by rowild** [comment] 2023-08-07 10:38
But how will you then ever be able to unset a value to its original value? As described above: setting the newsletter toggle to "false" again leads to the situation that that value is never sent... there unsubscribe not possible...

**Comment by paescuj** [comment] 2023-08-07 11:20
Hmm, here's the payload I get which looks as expected to me:
1. Create item with default value
  ``{}``
2. Disable value
   ``{"toggle":false}``
3. Enable again
   ``{"toggle":true}``

**Comment by rijkvanzanten** [comment] 2023-08-07 13:42
A `filter` event gets the payload as submitted to the database. Default values are handled on the database level, hence _not_ submitting any value will set it back to the default 👍🏻 Closing this as it's currently working as intended. Happy to keep discussing though

**Closed by rijkvanzanten** 2023-08-07 13:42 UTC

**Comment by rowild** [comment] 2023-08-08 06:38
Aha, I didn't know that! Thank you for clarifying that for me!

**Comment by rowild** [comment] 2023-08-08 07:24
@rijkvanzanten I am not sure if I understand correctly. my flow checks if the parameter "newsletter" is equal to true. But that requires that the parameter "newsletter" is sent – which is not the case when it is set to its default value. Then I get an error saying 

`ValidationError: \"$trigger.payload.newsletter\" is required`
![01](https://github.com/directus/directus/assets/213803/dabed9c8-1f6c-4f08-a47a-d4d2b30d6954)

![02](https://github.com/directus/directus/assets/213803/21512994-69b3-4292-bc69-72028de8b631)
