### ISSUE TITLE
Relationships fields are broken in rc.100

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#9250] opened 2021-10-30 06:24 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Pretty much every relationship field (m2m, m2o ...) are broken in the rc.100. 
In some fields the related collection or junction collection is missing. In the translations the options are missing.

### To Reproduce

1. Create a new relationship field.
2. Open the field editor after saving it and go in the Relationship tab
3. Some collections are missing from the relationship

<img width="827" alt="Screenshot 2021-10-30 at 08 14 19" src="https://user-images.githubusercontent.com/9766700/139522875-ea207838-2330-4d70-bec3-69df36579f40.png">
<img width="818" alt="Screenshot 2021-10-30 at 08 14 05" src="https://user-images.githubusercontent.com/9766700/139522877-ab7a622d-0e80-4551-b395-29ed76f6878e.png">
<img width="841" alt="Screenshot 2021-10-30 at 08 12 44" src="https://user-images.githubusercontent.com/9766700/139522878-a2865960-b8d5-45e2-99f9-e3f76d555025.png">

### What version of Directus are you using?

9.0.0-rc.100

### What version of Node.js are you using?

16

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Safari

### What operating system are you using?

macOS 12.0.1

### How are you deploying Directus?

locally

**Comment by AlexisWalravens** [comment] 2021-10-30 11:34
Can confirm, I have the same bug.
RC.100 (upgraded from RC.90)

**Comment by Oreilles** [comment] 2021-10-30 12:51
Duplicate of #9182

**Closed by Oreilles** 2021-10-30 12:51 UTC
Labels: Bug (Potential)

**Comment by mattiaz9** [comment] 2021-10-30 13:00
@Oreilles Maybe it's related to #9182 but I think it's worth mentioning that the rc.99 version doesn't have the issue.

For me only the rc.100 introduced the problem and downgrading back to the 99 version fixed it.

**Comment by Oreilles** [comment] 2021-10-30 13:05
It is the same bug. It was most likely introduced with commit https://github.com/directus/directus/pull/9109, after which https://github.com/directus/directus/issues/9182 was reported.
