### ISSUE TITLE
 In flows for Directus 10.4.2 when using dynamic values getting undefined

### ISSUE THREAD

**Issue by LevelUpGit** [directus/directus#19057] opened 2023-07-03 14:39 UTC
### Describe the Bug

When using dynamic values in flows, I was using  {{ $CURRENT_USER.first_name }} {{ $CURRENT_USER.last_name }} in subject of email, I am getting undefined.

Also when using filters and dynamic filter like $NOW.

### To Reproduce

Create any directus flow, create step "Sending email", in Subject line use {{ $CURRENT_USER.first_name }} or any other. 

### Directus Version

v10.4.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by ConnorSimply** [comment] 2023-07-07 19:26
Hi @LevelUpGit,

- `$CURRENT_USER` and `$NOW` are [dynamic **filter** variables](https://docs.directus.io/reference/filter-rules.html#dynamic-variables) and can only be used in filters. To get that data you will need to use the accountability object with the current user id to fetch the users data.
- I just tested using `$NOW` and the dynamic filter variables in a flow and they worked as expected. 

Since I am unable to reproduce this I am going to close this out for now, if you could share the exact operation configuration that is not working that will help with reproduction or you can seek help in our Discord if it ends up not being a bug!

**Closed by ConnorSimply** 2023-07-07 19:26 UTC
