### ISSUE TITLE
error when create new field again

### ISSUE THREAD

**Issue by haidv1992** [directus/directus#19613] opened 2023-09-07 04:29 UTC
### Describe the Bug

when create a field then delete and create again got error

![image](https://github.com/directus/directus/assets/86423592/399ab2e4-b1e8-4ba3-9506-54402fef6f0a)

### To Reproduce

error when create new field again

### Directus Version

V10.6.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by DanielBiegler** [comment] 2023-09-08 11:08
Hi there, thanks for filing an issue but a little more information would be nice because creating, deleting and creating again does not reproduce your error for me.

**Comment by rijkvanzanten** [comment] 2023-09-21 18:08
Closing this as there's not enough information available for us to debug. Happy to reopen when more information becomes available

**Closed by rijkvanzanten** 2023-09-21 18:08 UTC
Labels: Needs More Info
