### ISSUE TITLE
Problems with broken image at item creation/editing

### ISSUE THREAD

**Issue by iksent** [directus/directus#11556] opened 2022-02-10 07:31 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I moved my instance of DB to another server, but without media (without public folder), so some images are broken now.

There are some problems with displaying such images:

1)
 
- The broken image has the wrong height (i think it should be bigger vertically):

![image](https://user-images.githubusercontent.com/32956521/153357770-30fa7e67-cedb-42f7-b9e3-7ed0d4b8f060.png)

- Also you can't click on button at the bottom of the block:

https://user-images.githubusercontent.com/32956521/153358158-9a3eb6d0-03d6-43ba-8f50-042b6dc427e5.mov

2) Image displays as broken even after selecting new correct image:

https://user-images.githubusercontent.com/32956521/153358736-4d23ed94-8487-4a72-b03c-c609f9c8f147.mov

### To Reproduce

- Break some images :)

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.17.5

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2022-02-10 07:38
This delves in the image interface error handling in general (different error but same root cause) as reported in #10475. Closing this in favor of tracking it over there.

**Closed by azrikahar** 2022-02-10 07:38 UTC
Labels: Bug (Potential)

**Comment by iksent** [comment] 2022-02-10 07:43
Sometimes it's so hard to find a similar problem before creating your own!
