### ISSUE TITLE
Just created item sometimes inaccessible in action hook

### ISSUE THREAD

**Issue by samdze** [directus/directus#13233] opened 2022-05-11 13:02 UTC
### Describe the Bug

I have this `directus_users` filter in which I create a profile item linked to (O2O) a `directus_users` item:

```typescript
filter('users.create', async (input, meta, { database, schema, accountability }) => {
	const profilesService = new ItemsService('profiles', { database, schema, accountability })
	const resultId = await profilesService.createOne({ first_name: input.first_name, last_name: input.last_name, email: input.email })

	return { ...input, profile: resultId }
})
```

Then, in this action below, I want to assign the user id to the newly created profile item.

```typescript
action('users.create', async (input, { database, schema }) => {
	const usersService = new UsersService({ database, schema })
	const { profile: profileId } = await usersService.readOne(input.key, { database, schema })

	const profilesService = new ItemsService('profiles', { database, schema })
	await profilesService.updateOne(profileId, { user: input.key })
})
```

The issue is that **sometimes**, on this line:
`const { profile: profileId } = await usersService.readOne(input.key, { database, schema })`
I get a ForbiddenException, probably because (again, sometimes) the user is not yet fully created or readable, and the profile item update gets aborted.

I'd expect an item to be always ready to be read and updated in the action triggered by its creation.

Right now I have to do this read and update in an action due to #13188 not being implemented.

### To Reproduce

The steps are described above.

### Errors Shown

```
⚠️  An error was thrown while executing action "users.create"
⚠️  You don't have permission to access this.
```

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

Docker image version

### What database are you using?

Postgres 14

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment] 2022-05-11 14:37
Closing this as a duplicate of #11172

**Closed by br41nslug** 2022-05-11 14:37 UTC
Labels: Duplicate
