### ISSUE TITLE
/admin/settings/presets does not save layout preferences

### ISSUE THREAD

**Issue by bamboowonder** [directus/directus#13820] opened 2022-06-09 19:31 UTC
### Describe the Bug

when changing any visible columns, sort order or layout  in "Presets and Bookmarks", it is not saved automatically, and is not possible to save manually.

### To Reproduce

change anything about layout, columns or sort in /admin/settings/presets
reload page or navigate away and return
default view is reverted

### Errors Shown

none

### What version of Directus are you using?

9.12.1

### What version of Node.js are you using?

12.22.9

### What database are you using?

postgres 14

### What browser are you using?

chrome

### How are you deploying Directus?

CLI npm package

**Comment by rijkvanzanten** [comment] 2022-06-09 19:38
Duplicate of https://github.com/directus/directus/issues/13326

**Closed by rijkvanzanten** 2022-06-09 19:38 UTC
