### ISSUE TITLE
Incoherencies in columns/fields visualization for linked collections (O2M / M2O)

### ISSUE THREAD

**Issue by mmmaxxxe** [directus/directus#14493] opened 2022-07-18 16:28 UTC
### Describe the Bug

Sometimes, columns of a linked collection don't renders as expected

**Main collection (OK)**

![image](https://user-images.githubusercontent.com/102175921/179551050-7f6a1adb-c9fd-4cd1-8301-7c04b90805c7.png)

The main collection is linked to other tables via a M2O

**Linked collection (problems):**

![image](https://user-images.githubusercontent.com/102175921/179556822-cda301c5-2800-4326-8588-d349360f2d2e.png)

this is linked O2M to the Main table. Relations are correct, there aren't any special privileges because i'm using an admin user.
As You can see the columns in the linked tables aren't rendering correctly (images not shown, status column not rendered correctly)

Note: both collections has a "status" column as happens by default on directus

### To Reproduce

Link two tables (main and child)

Main with a O2M to a child 
Main has image field at least
Main has a status column with a conditional formatting

in child collection view, add column  with columns taken from the main collection

### Errors Shown

None

### What version of Directus are you using?

9.13 - standard cloud

### What version of Node.js are you using?

standard cloud

### What database are you using?

standard cloud

### What browser are you using?

chrome, firefox, brave

### How are you deploying Directus?

standard cloud

**Comment by rijkvanzanten** [comment] 2022-07-18 16:30
I believe this is a duplicate of https://github.com/directus/directus/issues/12271

**Closed by rijkvanzanten** 2022-07-18 16:30 UTC
