### ISSUE TITLE
API POST: Invalid foreign key in field

### ISSUE THREAD

**Issue by dosandco** [directus/directus#11512] opened 2022-02-08 14:26 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to add a new record via the API POST call, I can do so fine leaving a M2O field blank, but if I try to populate the M2O field with another record's unique id, I get the following error:

```
Status code 400
{"errors":[{"message":"Invalid foreign key in field \"portfolio_position\".","extensions":{"code":"INVALID_FOREIGN_KEY","collection":"transaction","field":"portfolio_position","invalid":"NEOS328S-investments-61de14ae-4486-4d51-aff3-fd51a71628d3"}}]}
```

This used to work fine, but has stopped working since I upgraded to 9.5.0/1 (I was a few versions behind before then, so don't know exactly when it stopped).

### To Reproduce

Send a POST API call to create a new record in a collection with a M2O field and attempt to populate the M2O field with the ID of the other record.

It might make a difference that the id type of the 'one' is 'manual' (as opposed to sequential number or UUID).

### Errors Shown

Status code 400

```json
{"errors":[{"message":"Invalid foreign key in field \"portfolio_position\".","extensions":{"code":"INVALID_FOREIGN_KEY","collection":"transaction","field":"portfolio_position","invalid":"NEOS328S-investments-61de14ae-4486-4d51-aff3-fd51a71628d3"}}]}
```

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.15.4

### What database are you using?

PostgreSQL 12

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

DigitalOcean droplet + DO hosted database

**Comment by dosandco** [comment] 2022-02-08 14:28
Might be similar/related to https://github.com/directus/directus/issues/11400

**Comment by azrikahar** [comment] 2022-02-09 06:50
Hi, I've tried to follow the reproduction steps but it seems to work fine on my end:

![w1xo8J6hen](https://user-images.githubusercontent.com/42867097/153136583-7d2e75c8-e865-48a8-bdf0-b1f7d021bf6e.gif)

`id` of `bar` collection in this case is also a manually entered string as well.

Just to confirm, were you able to reproduce this with the steps you have outlined on a fresh instance locally?

**Comment by kropsi** [comment] 2022-02-21 08:22
We have the same problem on `9.0.0-rc.94`, which suddenly appeared. It is also for M2O relation where we cannot create an item with a subitem bound by id. It also throughs `INVALID_FOREIGN_KEY`. We had several items in that item collection, so it worked before and stopped at some point. We didn't touch this part, so it broke at some point.

We tried to remove the table for subitems and the field. We created it again. We experience the same problem.

In the end, we had to delete the table of items, then we recreated it and recreated the M2O connection to subitems. That resolved the problem.

We have many other M2O relations in the systems where everything works right now, but it is a bit scary that this part can get corrupted somehow, as there is a lot of data in other collections, and it won't be easy to recreate it.

**Comment by joselcvarela** [comment] 2022-02-21 13:54
@kropsi as you can see here in the following link, there is much more versions since `rc.94`: https://www.npmjs.com/package/directus
You may want to update your instance, otherwise we may not consider your issue as a bug.

**Comment by rijkvanzanten** [comment] 2022-04-07 21:20
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2022-04-07 21:20 UTC
Labels: Needs More Info, Can't Reproduce
