### ISSUE TITLE
Update permissions still incorrect in 10.5.2

### ISSUE THREAD

**Issue by martinsotirov** [directus/directus#19327] opened 2023-08-02 07:28 UTC
### Describe the Bug

As already mentioned in #18898, #19073, #19043 and #19249, the update permissions for nested filters don't work since 10.3.0.

### To Reproduce

Create a many-to-many relation from Entity A to Directus Users. Create a one-to-many relation from Entity A to Entity B. Try to set update permissions for Entity B.

```
{
	"_and": [
		{
			"entityA": {
				"admin": {
					"directus_users_id": {
						"_contains": "$CURRENT_USER.id"
					}
				}
			}
		}
	]
}
```

On v10.2.1 the frontend displays a popup error `[FORBIDDEN] You don't have permission to access this.` but after dismissing it, you can still update the item. After v10.3.0 the popup error is displayed and you can't edit the item after dismissing the error.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by martinsotirov** [comment] 2023-08-02 07:52
Also, it doesn't make a difference if my relation to the directus_users is one-to-many or many-to-many. In both cases the update permissions don't work. The only difference is that on v10.2.1 with one-to-many no error is displayed and I can edit the item, while with many-to-many an error is displayed first but I can edit the item after dismissing the error.

**Comment by u12206050** [comment] 2023-08-11 16:15
Since the previous issue has been closed I am just pasting again our permission as well:
```
{"_and":[{"_or":[{"role":{"_in":["$CURRENT_USER.roles.role"]}},{"id":{"_eq":"$CURRENT_USER"}}]}]}
```

Basically users and m2m to directus_roles which we populate with which roles another role can manage. Unfortunately this has stopped working since a about 2 months ago :(

**Comment by u12206050** [comment] 2023-08-15 09:38
Hmm, I actually looked now at my PR and what it fixed, and it seems that it did fix the original issue and is working as it should (ie. values for dynamic variables eg. $CURRENT_ROLE.name are being replaced correctly). 
But seems the actual validating is broken somewhere else now...

**Comment by martinsotirov** [comment] 2023-08-17 11:32
Just to clarify, my issue is not with user roles but with specific user's who are related to Entity A which itself is related to Entity B. What I'm trying to do is set access for the user to Entity B through the user's relation to Entity A.

**Comment by sarthakgaur** [comment] 2023-08-17 11:48
I am facing the same problem as @martinsotirov. I have pretty much tried everything. Nothing works. I even gave full update access for a table to a role. But, you still can't update the row through a related table.

I even tried downgrading to v10.2.1. That also did not work. Further downgraded to 9.25.2. This seems to work.

There seems to be a lot of confusion when it comes to downgrading. A lot of people are doing it incorrectly. Here's what you have to do if you want to downgrade to v9.25.2.

1. Find the date when that version was released. For v9.25.2, the date was April 20, 2023.
2. Open the `directus_migrations` table.
3. Sort the rows by the `version` column in ascending order.
4. Find the `version` number that comes just before `20230420`. The versions are represented in a date format `YYYYMMDD`.
5. Count the number of entries after this version number. Let's say there are `n` entries after.
6. Run `npx directus database migrate:down` `n` number of times. If you accidentally ran it a few more times, don't worry. We can fix this later.
7. Run `npm install directus@v9.25.2`.
8. Run `npx directus start`.
9. If the output mentions that you need to run migrations, run `npx directus database migrate:latest`.

That's all. You can replicate the steps to downgrade to any version number, just replace the directus version number with the version number you want and the `version` column in the `directus_migrations` table to the release date of that version.

**Comment by plutsan** [comment] 2023-08-22 15:53
Permissions also not working for us as expected.
In our case we are having `Organization` collection. `directus_users` having m2o `organization` field same as other collection - `Artist`.

And we are setting permissions for the user role:
read permissions - to all Artists except some fields
update/delete permissions - to only Artists within same organization

<img width="593" alt="permission" src="https://github.com/directus/directus/assets/12510704/e368d5a5-6fb4-4a4d-a70c-a4b1dc56825d">

But Artists in the Directus UI with the same as a user or other organization is disabled for editing. Artist without organization set is enabled for editing (which is incorrect from the permissions perspective) but trying to update it will return 403 Forbidden (which is correct from the permissions perspective). 

**Interesting finding:**
Artists with the same as a user or other organization or Artist with no organization become available for editing in the Directus UI if remove Artist organization field from read permissions

<img width="577" alt="field" src="https://github.com/directus/directus/assets/12510704/8d5e32fa-8b94-4ded-bd13-0515de1ed813">

But edit operation will be successful only for the Artist with same organization as user, as was defined in the edit permissions, and other cases will fail with 403 Forbidden

So can assume that permissions works fine but UI is having some issues.

**Comment by sensedrive** [comment] 2023-08-25 18:18
We have an issue with seeting update permissions to specific items in a collection, where the user is connected "over three corners". I know, this worked in older directus (at least 9) versions.

The fact is ... i cannot set any update permissions now anymore.

Cant believe so few people are facing this issue. For me it is one of the most important core features.

```json
{
	"clients": {
		"clients_id": {
			"supervisors": {
				"directus_users_id": {
					"id": {
						"_eq": "$CURRENT_USER"
					}
				}
			}
		}
	}
}
```

I appreciate any help on this. Thank you in advance!

**Comment by Pachat** [comment] 2023-08-25 19:31
I have the same problem on v10.6.0. Therefore, still stuck to v10.2.1, which is 10 versions back.

**Comment by u12206050** [comment] 2023-08-26 07:27
> We have an issue with setting update permissions to specific items in a collection, where the user is connected "over three corners". I know, this worked in older directus (at least 9) versions.
> 
> 
> 
> The fact is ... i cannot set any update permissions now anymore.
> 
> 
> 
> Cant believe so few people are facing this issue. For me it is one of the most important core features.
> 
> 
> 
> ```json
> 
> {
> 
> 	"clients": {
> 
> 		"clients_id": {
> 
> 			"supervisors": {
> 
> 				"directus_users_id": {
> 
> 					"id": {
> 
> 						"_eq": "$CURRENT_USER"
> 
> 					}
> 
> 				}
> 
> 			}
> 
> 		}
> 
> 	}
> 
> }
> 
> ```
> 
> 
> 
> I appreciate any help on this. Thank you in advance!

Try it in reverse so that the initial field is only one level deep and you access it via alias field on the current user ie. 

'''{ "clients": { "_in": "$CURRENT_USER.supervises.client_id" } }'''

**Comment by Pachat** [comment] 2023-08-26 08:00
> Try it in reverse so that the initial field is only one level deep and you access it via alias field on the current user ie.

In my case, the filter that works correctly on v10.2.1 but not in the later versions is
```
{
	"_and": [
		{
			"roles_assigned": {
				"directus_roles_id": {
					"network": {
						"roles_in_network": {
							"id": {
								"_eq": "$CURRENT_ROLE"
							}
						}
					}
				}
			}
		}
	]
}
```

**Comment by u12206050** [comment] 2023-08-27 08:47
I've been able to solve it by explicitly using the `role->id` on relation fields instead of just `role` for example.

And testing this it seems to work both on 10.5 and 10.6. Here is my current update permissions on directus_users
```
{
	"_and": [
		{
			"_or": [
				{
					"role": {
						"_null": true
					}
				},
				{
					"id": {
						"_eq": "$CURRENT_USER"
					}
				},
				{
					"role": {
						"id": {
							"_in": [
								"$CURRENT_USER.roles.role"
							]
						}
					}
				},
				{
					"role": {
						"id": {
							"_eq": "f1418822-89de-44cf-a6c6-ea0899c7d5db"
						}
					}
				}
			]
		}
	]
}
```

**Comment by YoshioKobayashi** [comment] 2023-08-28 06:35
We are having a similar issue, where we cannot use update permissions when we extend the directus_users with a company field and then try to set permissions in the user role on a products table referencing that company field. I'm adding reproducable minimal example how-to here for reference.

1. Create collection called "products" with normal integer inc PK
2. Add some fields to the collection, f.e. "name" and / or "color"
3. Add another collection "company" with integer inc PK
4. Add "name" field to company collection
5. Extend directus_users with many-to-one relationship to "cpmpany" collection
6. Creata a new company instance
7. Create a new User that is linked to that company instance
8. Create new Role [called "Kunde"] with app-Access
9. Change products Role to

CREATE			-> all allowed
VIEW, EDIT, DELETE 	-> user_created.company EQUALS $CURRENT_USER.company.id

Set it to allow accessing/editing all fields f.e. id, user_created, name

10. Login with the newly created User
11. Create new product(s) and save

While the filter works as expected when viewing the table, you can not edit the product when you open it via clicking the table vi

**Comment by kh-proxbit** [comment] 2023-08-30 22:48
> We are having a similar issue, where we cannot use update permissions when we extend the directus_users with a company field and then try to set permissions in the user role on a products table referencing that company field. I'm adding reproducable minimal example how-to here for reference.
> 
> 1. Create collection called "products" with normal integer inc PK
> 2. Add some fields to the collection, f.e. "name" and / or "color"
> 3. Add another collection "company" with integer inc PK
> 4. Add "name" field to company collection
> 5. Extend directus_users with many-to-one relationship to "cpmpany" collection
> 6. Creata a new company instance
> 7. Create a new User that is linked to that company instance
> 8. Create new Role [called "Kunde"] with app-Access
> 9. Change products Role to
> 
> CREATE -> all allowed VIEW, EDIT, DELETE -> user_created.company EQUALS $CURRENT_USER.company.id
> 
> Set it to allow accessing/editing all fields f.e. id, user_created, name
> 
> 10. Login with the newly created User
> 11. Create new product(s) and save
> 
> While the filter works as expected when viewing the table, you can not edit the product when you open it via clicking the table vi
Any news on this? Got the same issue

**Comment by Pachat** [comment] 2023-09-01 06:55
> Any news on this? Got the same issue
It would indeed be nice if this problem was fixed in the next version.
At the moment I'm stuck 10 releases back at 10.2.1 and can't benefit from the fantastic improvements the Directus team is making.

**Comment by shipsides-sparknel** [comment] 2023-09-07 06:38
when this initially broke, both update and delete were affected at the same time for in-app. is delete within the scope of this?

examples for collection delete permissions:
``````
{
			"uploaded_by": {
				"_eq": "$CURRENT_USER"
			}
``````
works

``````
{
			"uploaded_by": {
				"_eq": "$CURRENT_USER.id"
			}
``````
works

``````
{
	"uploaded_by": {
		"id": {
			"_eq": "$CURRENT_USER"
		}
	}
}
``````
doesn't work

``````
{
	"uploaded_by": {
		"id": {
			"_eq": "$CURRENT_USER.id"
		}
	}
}
``````
doesn't work

the problem is that when referring to static values, you can't make it work.

``````
{
	"_or": [{
			"folder": {
				"parent": {
					"_eq": "946fe764-5445-419d-ada5-ec9ab8edb81b"
				}
			}
		},
		{
			"folder": {
				"parent": {
					"id": {
						"_eq": "946fe764-5445-419d-ada5-ec9ab8edb81b"
					}
				}
			}

		}
	]
}
``````
neither of the above works

**Comment by Pachat** [comment] 2023-09-07 06:44
It looks like it is more a question of multi-levels in the filter than a question of static value at the right.
Multi-levels at the left of the filter works on version 10.2.1 but not since.

**Comment by max-mayorov** [comment] 2023-09-14 09:41
We are also experiencing the same problem and it blocks delivering of the product to the client. I hope this can be resolved soon.

**Comment by paescuj** [comment] 2023-09-20 09:23
Hey there 👋

This has been fixed with a temporary workaround in #19728 which has been released in [v10.6.2](https://github.com/directus/directus/releases/tag/v10.6.2).
The workaround comes with the limitation that items might be presented to the user as "updatable" even if they aren't, but the API will correctly refuse the update in such cases and the `You don't have permission to access this` message will be shown.
A complete solution will be provided at a later date. In the meantime, the workaround ensures that items can be edited again.

**Comment by sensedrive** [comment] 2023-09-28 13:49
Still an issue for us. We still can not configure update permissions for "product_groups". The user should be able to update the product_group, if the product_group is used by a client, which has the current user inside the list of supervisors.

**client** collection
client -> product_groups
client -> supervisors

**product_groups** collection:
product_groups -> clients (product_groups, which are used by clients)

```json
{
    "_and": [
        {
            "_or": [
                {
                    "clients": {
                        "clients_id": {
                            "supervisors": {
                                "directus_users_id": {
                                    "id": {
                                        "_eq": "$CURRENT_USER"
                                    }
                                }
                            }
                        }
                    }
                },
                {
                    "user_created": {
                        "id": {
                            "_eq": "$CURRENT_USER"
                        }
                    }
                }
            ]
        }
    ]
}
```

**Comment by sensedrive** [comment] 2023-10-12 09:06
Spending more time on this issue, it seems, the API is now working, but the UI is not correctly displaying the permissions. I am still able to do form changes, but it gives me now the following error message.

{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN",
    "stack": "..."
  }
}

What is the plan now, regarding to this ticket? Just curious about the priority (which is still set to urgent)

**Comment by paescuj** [comment] 2023-10-12 09:14
> Spending more time on this issue, it seems, the API is now working, but the UI is not correctly displaying the permissions. I am still able to do form changes, but it gives me now the following error message.
> 
> { "message": "You don't have permission to access this.", "extensions": { "code": "FORBIDDEN", "stack": "..." } }
> 
> What is the plan now, regarding to this ticket? Just curious about the priority (which is still set to urgent)

Yeah, this matches with what I've described in https://github.com/directus/directus/issues/19327#issuecomment-1727328226.

It's still planned to fully resolve this issue soon, but not a top priority at the moment.

**Comment by Galaen** [comment] 2023-12-05 15:32
Adding to this issue because the workaround only partially fixed the edit issue and not in all cases and also because it doesn't fix the DELETE and SHARE cases.

We have a "**resorts**" collection and on the directus user we added a "**resorts**" field  (many to many).
So when you create users, you can assign multiple resorts to them.

We also have other collections (activities for example) with a resort field (Many to one). You can select one resort per activity.

We also have a role "resort admin".
and the READ/UPDATE/DELETE/etc. for the collection activities are setup this way:
```
{
    "_and": [
        {
            "resort": {
                "id": {
                    "_in": "$CURRENT_USER.resorts.resorts_id"
                }
            }
        }
    ]
}
```
So a user should only see/edit/etc. the activities for their resorts.
In Directus 9.X it worked well.

I don't know exactly which one but before 10.3 it broke and only the READ was working.
Since 10.6.2 (still the case in 10.8.2) the EDIT now also work BUT the DELETE button is grayed and share has no button.
If you allow the DELETE without constraint, edit an activity, the DELETE button won't be grayed. You now add again the above rule and click the Delete button and it will work when it should (so the problem is only about the fact that the button is grayed or the share button not visible)

Now I also have a rule for resort admins to only see their own resorts setup this way:
```
{
    "_and": [
        {
            "id": {
                "_in": "$CURRENT_USER.resorts.resorts_id"
            }
        }
    ]
}
```
Same as before without the "resort" part as we are in the resort itself.
And this work for the READ (I only see the resort given in the user field resorts), but not only the DELETE and SHARE are NOT working as above but also all resort fields are grayed.

It's also worth noting that the rule displays an error in the interface even though it actually works (at least for READ and EDIT)
![image](https://github.com/directus/directus/assets/7955669/20ce611b-14a4-48d9-863b-7e3900bec876)

So are we doing something bad ? Or is the workaround not covering those cases ? And if not, will it be fixed or is it something not intended to use this way ?

**Closed** 2024-02-07 20:50 UTC
Labels: Package: @directus/app, Bug, Enterprise
