### ISSUE TITLE
Cannot add Fields to Repeater

### ISSUE THREAD

**Issue by dkophelyi** [directus/directus#11606] opened 2022-02-11 16:56 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When i try to add a child field to a Repeater field, i cannot save the entry or close the panel.
I get the following error in the console:

![image](https://user-images.githubusercontent.com/59764298/153633693-afab03d9-5a18-40c0-8448-5db6e9ea5d9b.png)

### To Reproduce

1) Create a collection
2) Create a field, set Type to JSON and choose the Repeater interface
3) Go to Interface/Edit Fields/Create New
4) You cannot save/close the panel

### Errors Shown

![image](https://user-images.githubusercontent.com/59764298/153634097-a2d0d4e5-dd9e-48b7-9ddd-5be601df8d8c.png)

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

SQLite

### What browser are you using?

Chrome

### What operating system are you using?

Linux

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-02-12 01:01
Duplicate of #11487, #11447. It has been resolved by #11453 and will be included in the next release 👍

**Closed by azrikahar** 2022-02-12 01:01 UTC
Labels: Bug (Potential)
