### ISSUE TITLE
M2O Cannot read property 'sql' of undefined

### ISSUE THREAD

**Issue by Blechlawine** [directus/directus#10097] opened 2021-11-26 19:54 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I get an "unexpected error" when creating an M2O relation "Cannot read property 'sql' of undefined". The created field shows up in the list of fields though and trying to delete it results in the same error again.

### To Reproduce

1. Create one Data model (here: A) with a UUID id
2. Create another Data model (here: B) with a UUID id
3. on B create an M2O field with A
4. get an unexpected error: "Cannot read..."

### Errors Shown

```
20:45:50 ­ƒÜ¿ Cannot read property 'sql' of undefined 
TypeError: Cannot read property 'sql' of undefined
    at E:\directus-test\node_modules\knex\lib\dialects\sqlite3\schema\ddl.js:50:75
    at async client.transaction.connection (E:\directus-test\node_modules\knex\lib\dialects\sqlite3\schema\ddl.js:321:48)
```

### What version of Directus are you using?

9.1.2

### What version of Node.js are you using?

14.16.0

### What database are you using?

SQLite 3 (npm package version 5.0.2)

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment] 2021-11-29 11:20
Did you name your table "A" and "B" ?
I get several errors when naming the tables with single-letter names but none otherwise.

**Comment by Blechlawine** [comment] 2021-11-29 11:52
@Oreilles no, their names aren't just one letter :D I just used one letter names in this issue, cause i didn't think it would be different with different names

**Comment by Oreilles** [comment] 2021-11-30 12:36
I'm unable to reproduce this issue.
I'd suggest making sure you're on the latest DIrectus release, that all the migrations have been run, and try cleaning up the dependencies with `rm -r **/node_modules && npm cache clean --force && npm install`.

**Comment by rijkvanzanten** [comment] 2021-12-02 23:22
I wasn't able to reproduce this on a fresh installation neither..

@Blechlawine What were the actual collection names you used? Knex uses quite a lot of trickery under the hood to make certain features work in SQLite, so it's not unthinkable that an unexpected collection name could mess things up 🤔 

---

Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-12-02 23:22 UTC
Labels: Needs More Info

**Comment by Blechlawine** [comment] 2021-12-03 21:32
@rijkvanzanten my collection names were "Category" and "Type". I guess those are already in use somewhere? So I tried again with different model names, and now it works.
