### ISSUE TITLE
Error when using download image from link feature.

### ISSUE THREAD

**Issue by awesomentw** [directus/directus#2504] opened 2019-12-11 14:32 UTC
Hi! First of all. This is amazing cms, i started to working with this few weeks ago. Features are intuitive and it's a pleasure to work with this. Im going to use this in at leads 4 websites.

# Bug Report

## Steps to Reproduce

1. Go to any place where you can add image. Click on link , paste link and click save.

## Expected Behavior

I was expecting function to download image to server and connect with record.

## Actual Behavior

Console
```
Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
Error: filename_download: This value should not be blank.
    at new a (API.js:39)
    at API.js:253
```
Network
```
code: 4
message: "filename_download: This value should not be blank."
```

**Comment by rijkvanzanten** [comment] 2019-12-11 15:09
Thanks for the kind words 🙂 ❤️ 

Someone else reported the same issue right before you did. We'll get this resolved asap.

Duplicate of https://github.com/directus/api/issues/1552

**Closed by rijkvanzanten** 2019-12-11 15:09 UTC
