### ISSUE TITLE
Junction Collection field empty by m2m relations

### ISSUE THREAD

**Issue by Smoggg** [directus/directus#9416] opened 2021-11-03 14:21 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I added some m2m fields and the "Junction collection" field where I suppose that the name of the generated 3d table should be is always empty. 

![image](https://user-images.githubusercontent.com/32272077/140076029-d4414732-37cd-4c49-ad8a-0ba72fcaf846.png)

### To Reproduce

add 2 collections
add 1 m2m field in one of the 2 collections that reference the other
check out the field in the "relationship" tab and the "Junction collection" field is empty

### What version of Directus are you using?

v9.0.0-rc.100

### What version of Node.js are you using?

v16.9.1

### What database are you using?

MySQL 8.0.12 & Azure MySQL 8.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-11-03 14:30
Duplicate of https://github.com/directus/directus/issues/9182

**Closed by rijkvanzanten** 2021-11-03 14:30 UTC
Labels: Duplicate
