### ISSUE TITLE
Invalid time value when editing/viewing a item

### ISSUE THREAD

**Issue by MiniDigger** [directus/directus#3581] opened 2021-01-05 10:54 UTC
rc28, db is postgre.

error:
```
11:49:03 ߚ蠉nvalid time value
--
  | RangeError: Invalid time value
  | at Object.format (/directus/node_modules/date-fns/format/index.js:391:11)
  | at PayloadService.<anonymous> (/directus/node_modules/directus/dist/services/payload.js:261:57)
  | at Generator.next (<anonymous>)
  | at /directus/node_modules/directus/dist/services/payload.js:12:71
  | at new Promise (<anonymous>)
  | at __awaiter (/directus/node_modules/directus/dist/services/payload.js:8:12)
  | at PayloadService.processDates (/directus/node_modules/directus/dist/services/payload.js:232:16)
  | at PayloadService.<anonymous> (/directus/node_modules/directus/dist/services/payload.js:191:28)
  | at Generator.next (<anonymous>)
  | at fulfilled (/directus/node_modules/directus/dist/services/payload.js:9:58)
```

added some logging, value is "Invalid Date" here https://github.com/directus/directus/blob/main/api/src/services/payload.ts#L258

table looks like this:
| id | status | sort | date\_created | date\_updated | titel | publish\_on | text | author | url |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 2 | published | NULL | 2021-01-05 10:34:10.237000 | NULL | Test News | 2021-01-05 11:33:40.000000 | &lt;p&gt;Dies ist ein Test&lt;/p&gt; | 08.894 | test |

publish_on is a Datetime field, with include seconds = false and use 24 hour format = true. it is required.

worth noting that it was created in the DB, just the reading seems to fail.

**Comment by MiniDigger** [comment] 2021-01-05 10:58
I added a && value != "Invalid Date" here and now I can view the item again, but the interface for publishOn is empty.
https://github.com/directus/directus/blob/main/api/src/services/payload.ts#L250

**Comment by MiniDigger** [comment] 2021-01-05 11:00
a graph query to that field returns
```
{
  "errors": [
    {
      "message": "String cannot represent value: {}",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "items",
        "news",
        0,
        "publish_on"
      ]
    }
  ],
  "data": {
    "items": {
      "news": [
        {
          "publish_on": null
        }
      ]
    }
  }
}
```
worth noting that this may be a locale problem.

**Comment by irishburlybear** [comment] 2021-01-09 15:32
I fixed mine by Including the T timezone style formatting
0000-00-00**T**00:00:00 <-- Like this...

**Comment by rijkvanzanten** [comment] 2021-01-13 23:12
@MiniDigger What collation / locale / date format settings is this under?

**Comment by rijkvanzanten** [comment] 2021-01-13 23:13
@MiniDigger What collation / locale / date format settings is this under?

**Comment by MiniDigger** [comment] 2021-01-14 11:54
these should be all relevant settings (SHOW ALL, manually filtered)

| name | setting | description |
| :--- | :--- | :--- |
| client\_encoding | UTF8 | Sets the client's character set encoding. |
| DateStyle | ISO, DMY | Sets the display format for date and time values. |
| integer\_datetimes | on | Datetimes are integer based. |
| IntervalStyle | postgres | Sets the display format for interval values. |
| lc\_collate | en\_US.UTF-8 | Shows the collation order locale. |
| lc\_ctype | en\_US.UTF-8 | Shows the character classification and case conversion locale. |
| lc\_messages |  | Sets the language in which messages are displayed. |
| lc\_monetary | de\_DE.UTF-8 | Sets the locale for formatting monetary amounts. |
| lc\_numeric | de\_DE.UTF-8 | Sets the locale for formatting numbers. |
| lc\_time | de\_DE.UTF-8 | Sets the locale for formatting date and time values. |
| server\_encoding | UTF8 | Sets the server \(database\) character set encoding. |
| server\_version | 12.3 | Shows the server version. |
| server\_version\_num | 120003 | Shows the server version as an integer. |
| TimeZone | UTC | Sets the time zone for displaying and interpreting time stamps. |
| timezone\_abbreviations | Default | Selects a file of time zone abbreviations. |

as said in the initial issue, the value var is "Invalid Date" there.

worth noting that, I also have this fix applied: https://github.com/directus/directus/issues/3139#issuecomment-737164139, but iirc that code wasnt hit for this issue

**Comment by rijkvanzanten** [comment] 2021-05-24 20:21
I think this is a similar scenario as https://github.com/directus/directus/issues/3139 🤔

I can't seem to reproduce it on my end either (just changed my `lc_time` to German, and made sure DateStyle was set to `ISO, DMY`, but things seem to work as expected).

Nobody seems to have run into the same issue since it was opened in January (no upvotes or similar issues as far as I know), so I'm wondering if this could've been a fluke or a specific database configuration thing you have locally that might cause problems here 🤔 

@MiniDigger could you confirm this is still an issue? If so, is there a way I can accurately reproduce it?

**Comment by rijkvanzanten** [comment] 2021-05-24 20:21
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-05-24 20:21 UTC
Labels: API, App, Bug, DB: Postgres
