### ISSUE TITLE
Error when saving items with O2M relations that have RBAC settings for the related collections.

### ISSUE THREAD

**Issue by younky-yang** [directus/directus#13997] opened 2022-06-20 14:34 UTC
### Describe the Bug

To make it easier, I will describe the issue with the following scenarios. I have few collections as defined in the attached snapshot.yaml, please just focus on customers, orders, goods, and categories for this case.
Customer is defined as below screenshot shows.
![customer](https://user-images.githubusercontent.com/10388011/174622298-6694b15e-d2c1-4b0a-9bcb-4d46cc9377f1.png)
order's display template is name of good collection as below screenshot. 
![customer-orders](https://user-images.githubusercontent.com/10388011/174622539-fde3a3a0-577c-4a52-a5e2-c814adc1e936.png)
orders is defined as below screenshot. 
![orders](https://user-images.githubusercontent.com/10388011/174622724-ca738b83-7125-40fa-b467-d5e6eac92dc6.png)
below is definition of goods. Catagory just has a name field besides the id and other directus fields.
![goods](https://user-images.githubusercontent.com/10388011/174622913-51e2dc40-fe4a-403a-bf1c-a2ef6535bd27.png)
customers and orders has O2M relations, orders and goods has M2O relations, goods and categories has M2O relations. 

The key for the issue is to set the display template of customers.orders to goods.name.

![2022-06-20 221702](https://user-images.githubusercontent.com/10388011/174621881-09c37b20-60f1-495b-8d0f-921d4c91ae41.png)
I setup a role named editor which doesn't allow the editor to update goods, but choose from the predefined goods. 

So fill some categories and goods into collection, and use a user with editor role, to create or update a customer item. In the customer item form, select orders, and update comments of orders, then close order drawer, then click save for customer, you will get an error about "You don't have permission to access this.".

 

### To Reproduce

As mentioned in above field. The issue is the display template set for the relation fields. In above case, if you set the display template to orders.order_date, you won't get the error with the same RBAC role settings, but if you set it to orders.good.name, then you got the error.

### Errors Shown

You will get an error of "You don't have permission to access this."

### What version of Directus are you using?

9.12.2 and the latest main branch

### What version of Node.js are you using?

16.15.1

### What database are you using?

postgresql 13

### What browser are you using?

chrome and firefox

### How are you deploying Directus?

local and AWS fargate

**Comment by younky-yang** [comment] 2022-06-20 14:35
How can I upload the snapshot.yaml here?

**Comment by br41nslug** [comment] 2022-06-20 14:40
I think this could be a duplicate of #13765

**Comment by azrikahar** [comment] 2022-06-21 06:53
Closing as duplicate.

**Closed by azrikahar** 2022-06-21 06:53 UTC
Labels: Duplicate
