### ISSUE TITLE
Default form validation not working in create/edit dialog

### ISSUE THREAD

**Issue by tonyellow** [directus/directus#16314] opened 2022-11-04 07:34 UTC
### Describe the Bug

When editing or creating a related item from the detail view the validation system is not working. There are no validation messages shown. When clicking the blue save button, nothing happens. 

![Screenshot 2022-11-04 at 08 24 42](https://user-images.githubusercontent.com/8984917/199917926-2b587d5f-8090-475d-ad88-066b73a6ccca.png)

### To Reproduce

Create a new item  through a o2m relation field. A new dialog is opening with the create from. Leave out required fields and click the blue save button. Nothing happens and no messages are shown.

### Errors Shown

none

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

v16.18.0

### What database are you using?

Postgres 15

### What browser are you using?

Chrome mac os x

### How are you deploying Directus?

locally npx

**Comment by azrikahar** [comment] 2022-11-04 08:07
Thanks for opening this issue! However this is a duplicate of an existing issue #16091, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #16091 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2022-11-04 08:07 UTC
