### ISSUE TITLE
Multiple m2m rules in permissions causing large count

### ISSUE THREAD

**Issue by u12206050** [directus/directus#17300] opened 2023-01-25 13:58 UTC
### Describe the Bug

When checking multiple m2m relationship rules in permissions, the count on content items is wrong, and the query performance takes a hit.

Pagination therefor is also showing wrong:

![Screenshot 2023-01-25 at 15 00 44](https://user-images.githubusercontent.com/6641242/214583240-4987ecfd-b3d8-490d-92bc-def85a655006.png)

As you can see that is much less than 50 items, but am at the end of the result list.

Related issues: #17028 #13107 

### To Reproduce

On a collect that has two m2m relationships, add a permission checking something on both of those m2m relationships:

eg.

```
{
  "_and": [
    {
      "status": { "_eq": 1 }
    },
    {
      "_or": [
        {
          "registrations": {
            "orgId": {
              "_in": ["$CURRENT_USER.organizations.orgId"]
            }
          }
        },
        {
          "_and": [
            {
              "organizations": {
                "orgId": {
                  "_in": ["$CURRENT_USER.organizations.orgId"]
                }
              }
            }
          ]
        }
      ]
    }
  ]
}
```

The actual records don't seem to be duplicated, but the count is very high, relative to the amount of m2m relationships joined via the sql query.

### Errors Shown

In correct count shown. Decreased performance compared to when just one m2m relationship is being checked.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

18.12.1

### What database are you using?

MYSQL

### What browser are you using?

Chromium

### How are you deploying Directus?

Locally GCP

**Comment by licitdev** [comment] 2023-01-26 20:01
Duplicate of #17028

**Closed by licitdev** 2023-01-26 20:01 UTC
Labels: API, Bug
