### ISSUE TITLE
Autocomplete Input (API) - Can't select the output it returns from the dropdown

### ISSUE THREAD

**Issue by dhhdev** [directus/directus#14112] opened 2022-06-25 15:37 UTC
### Describe the Bug

As the title states, I have trouble selecting any result from the dropdown menu that comes up. (Tried both Safari and Firefox on macOS.)

Tried to figure out if it was a custom CSS thing or something, but I can't seem to find where it actually adds it to the DOM while inspecting.

<img width="818" alt="Skærmbillede 2022-06-25 kl  17 26 02" src="https://user-images.githubusercontent.com/726669/175780329-a47a064b-5d56-471b-95b7-740d51a8f03a.png">

As soon as I try to click the result, it just disappears and doesn't fill it into the input field.

### To Reproduce

1. Use the Autocomplete Input (API) field.
2. Set it up to use any resource.

I use this API provided by a government entity to get addresses in Denmark.

https://api.dataforsyningen.dk/adresser/autocomplete?q=

I set value path simply to "tekst" to get this result. +1 to them for making that simple.

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

No idea.

### What database are you using?

Postgres 13

### What browser are you using?

Safari and Firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-06-25 16:29
Thanks for opening this issue! However this is a duplicate of an existing issue #13860, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. With that said, the issue has been resolved by PR #14043 and will be included in the next release. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-06-25 16:29 UTC
