### ISSUE TITLE
Small Bug: color display field on new themes.

### ISSUE THREAD

**Issue by JugaadiTek** [directus/directus#21342] opened 2024-02-06 16:18 UTC
### Describe the Bug

![image|50%](https://github.com/directus/directus/assets/106853815/3ad48416-2a57-40e1-9922-9c40b6023e41)

When using the color match theme, color display fields stop working.

### Directus Version

10.8.3

### Hosting Strategy

Self-Hosted (Docker Image) @ railway

**Comment by rijkvanzanten** [comment] 2024-02-06 16:25
I'm 80% sure this was fixed as part of https://github.com/directus/directus/pull/20782 in more specifically this commit: https://github.com/directus/directus/pull/20782/commits/c02b20d3dae9d2f8ee7152af9dc065717e634668

The underlying reason is that the color display tried using `color-js` to parse the color value, but the color-match theme uses `color-mix()` which `color-js` doesn't support (yet?). That linked PR wraps that bit in a try catch so it fails gracefully and ignores the contrast check for the border when that happens.

**Comment by rijkvanzanten** [comment] 2024-02-08 22:24
I'm not able to reproduce this in 10.9, so I'm considering this as resolved by https://github.com/directus/directus/commit/c02b20d3dae9d2f8ee7152af9dc065717e634668 🙂

**Closed by rijkvanzanten** 2024-02-08 22:24 UTC
Labels: Bug
