### ISSUE TITLE
Creating new on M2M overrides previous selected item instead of updating itself

### ISSUE THREAD

**Issue by jacobrienstra** [directus/directus#14534] opened 2022-07-20 19:02 UTC
### Describe the Bug

Basically the title. If you select an existing item in an M2M, then create a new one, THEN edit that new one, it will change the first selected item instead of the correct, created one. 

https://user-images.githubusercontent.com/10411238/180061106-5325e0e7-a7ba-4574-afac-3e69e095bde2.mov

### To Reproduce

Create a collection and a related collection, put an M2M field between them. Create a few entries in each collection.

On an item, use Add Existing to connect a few related entries. Then use Create New to create a new related entry. Save the drawer. Then click on the one you just created to edit it, edit it, and save the drawer again. You should see the existing entry edited instead of the one you created. 

The culprit is these lines:
https://github.com/directus/directus/blob/9d738d12ce7a9bf754e92443450a72a2a83b3794/app/src/composables/use-relation/use-relation-multiple.ts#L149-L158

In an M2M, both selected items and created items are `$type = 'created'`, which means when you assign indexes to the `newItems` starting at 0, they overlap the selected indexes. 

### Errors Shown

No I don't think so.

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-10-05 06:31
I believe this was actually fixed by #15500 in version `9.18.0`. This shared the same issue as #15460 (technically that should've been a duplicate of this issue!), and the PR addressed the same lines of codes being the culprit as mentioned in this issue 👍 Marking this as resolved.

## Before (9.17.4)

https://user-images.githubusercontent.com/42867097/193995562-bbaa5942-fcf6-4166-a8df-b8633d79d837.mp4

## After (9.18.1)

https://user-images.githubusercontent.com/42867097/193995528-1a7ee630-729b-4c00-82d1-62a1df567697.mp4

**Closed by azrikahar** 2022-10-05 06:31 UTC
Labels: App, Bug
