### ISSUE TITLE
Google Login is not working with next-auth.

### ISSUE THREAD

**Issue by amankch** [directus/directus#17918] opened 2023-03-24 12:10 UTC
### Describe the Bug

Google Login of Directus is not working with nextjs, next-auth. 

### To Reproduce

Create a Next APP
Integrate Next-auth and implement Google Sign In
Now try to login/sign in with Directus provided URL with next-auth google login access_token.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-03-24 12:13
Likely a duplicate of either https://github.com/directus/directus/issues/17901 or https://github.com/directus/directus/issues/17905

**Closed** 2023-03-24 12:14 UTC
Labels: Duplicate, Needs More Info
