### ISSUE TITLE
Dropdown Enum issues

### ISSUE THREAD

**Issue by Zaelot** [directus/directus#1771] opened 2017-08-28 12:44 UTC
## Version Info
  - Directus version and branch: 6.4.1
  - PHP version: PHP 7.1.8
  - MySQL version: MariaDB 10.1
  - Web server: Apache
  - OS: Debian Jessie

## Expected Behavior
To be able to set values from the dropdown UI element. To clearly see where to input values. To be able to set default value. (To be able to modify the values.)
Bonus: To be able to reorder columns in _View Settings_.

## Actual Behavior
Initially shows the last enum as the default selected (despite whatever was set in the _Default_ field). Selection then seems to go smoothly without any visible errors, but when returning to double check the entry, it's showing the same last value of the dropdown. API doesn't return a value for it either.
During the column creation, the input field for the values is named "Length". (Even though the Input field is not in read-only mode in Column Setup, any modification to _Length_ field result in save error. "42000 - 1064, error in SQL syntax".)
Bonus: The cursor changes into the reordering mode, but unable to drag them. Changing sorting order in the _Tables & Inputs_ also doesn't affect the display order of the columns in Table view.

## Steps to Reproduce
 1. Add a new Column, choose **String** > **Dropdown Enum** as _User Interface_ type. Input comma separated values into _Length_ element. 
 2. Add new entry (or edit an old one) to the table. Select a value from the newly created dropdown. Save. (Also notice, how anything that was inputted into _Default_ value didn't effect anything.)
 3. Return to inspect the value, to see that it didn't actually save the change.
 4. Bonus: Return to edit the _Column Setup_ values for the Dropdown Enum, and try to save the changes.
 5. Bonus: Open _View Settings_ in the Table view, and try to drag the columns. Change their sorting order in _Tables & Inputs_, and return to check the _View Settings_.

## Schema Dump, Logs, or Screenshots
Tables view: no value on the Enum Dropdown. Can't reorder columns. Error message.
![image](https://user-images.githubusercontent.com/2608781/29772646-60d9440a-8c02-11e7-8f3d-1812a22e2437.png)

Tables & Inputs view. Reordered columns with sorting. Set a default value during creation. (Ignore the comment.)
![image](https://user-images.githubusercontent.com/2608781/29772889-77965de4-8c03-11e7-8251-11043625f83d.png)

Error message on a similar column that doesn't have a comment.
![image](https://user-images.githubusercontent.com/2608781/29773335-8f8aaee4-8c05-11e7-9b18-a620f0e7ec8c.png)

**Comment by Zaelot** [comment] 2017-08-28 14:04
Hmm, you can see the resetting value (ie, not actually having a value) issue by just refreshing the page. Though the enum issue remains, it seems refreshing the particular page fixes View Options issue. (Both allows to reorder the columns, and shows them in their correct place according to the sorting order.)

**Comment by WellingGuzman** [comment] 2017-08-30 03:47
Hey @Zaelot, I've made an update to the creation and update of the enum interface column.

Although I couldn't reproduce the issue with the reordering, can you be more clear, becuase it seems to be working.

Ref: https://github.com/directus/directus/commit/eee344c2f2eb45d0f3367b26661b99065ddc88c2

**Comment by Zaelot** [comment] 2017-08-30 12:24
1. Created a new table
2. Created a new broken enum dropdown.
3. Created an entry to the table to see that the dropdown was indeed broken.
4. Created a new text input on the table.
5. Filled a value to the new text input field.
6. Adjusted _Visibility Options_, and tried reordering. (Didn't reorder.)

Hitting F5 fixed that - so guess it just hadn't caught up to all that was going on. I have encountered similar kind of behaviour previously (like when working with the same UI in different tabs), somehow part of the changes are there, but the UI doesn't operate correctly unless it's properly refreshed.

**Comment by WellingGuzman** [comment] 2017-08-30 16:18
> 2. Created a new broken enum dropdown.
How do I created a broken enum dropdown? what do you mean?

I will try with adjusting `Visibility Options`.

Did the patch I commit last night fix any of the issues you reported?

**Comment by WellingGuzman** [comment] 2017-08-30 17:27
Closed by https://github.com/directus/directus/commit/62a6b0980529ebb1cab1894a3d915a704d50b8a9

**Closed by WellingGuzman** 2017-08-30 17:27 UTC
Labels: 3. Major, 6. In-Progress, API, Bug, Interface

**Comment by Zaelot** [comment] 2017-08-31 08:14
> How do I created a broken enum dropdown? 
I meant the user interface _Dropdown Enum_. For me, they've all been broken in version 6.4.1. (Of course, I do test with enum values such as `Another test,2,1,4,01,5`.) The user interface shows the values that were inserted into the _Length_ field during the creation of the column, and let's select a value, but apparently does not actually save the selection at any point, and doesn't report any errors either.

I haven't had the chance to test the updated version yet, I will though, when our admin gets around to updating.
