### ISSUE TITLE
@directus/cli SyntaxError: Unexpected token 'const'

### ISSUE THREAD

**Issue by mqwerty** [directus/directus#14482] opened 2022-07-18 03:17 UTC
### Describe the Bug

% directusctl
/opt/homebrew/lib/node_modules/@directus/cli/dist/cli/commands/docs.d.ts:1
declare const _default: import("../..").Command<import("../..").Toolbox<import("@directus/sdk").TypeMap>, unknown, void>;
        ^^^^^

SyntaxError: Unexpected token 'const'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1049:15)
    at Module._compile (node:internal/modules/cjs/loader:1084:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadModule (/opt/homebrew/lib/node_modules/@directus/cli/node_modules/gluegun/build/loaders/module-loader.js:15:12)
    at loadCommandFromFile (/opt/homebrew/lib/node_modules/@directus/cli/node_modules/gluegun/build/loaders/command-loader.js:41:56)

### To Reproduce

npm -g i @directus/cli
directusctl

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

18.6.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-07-18 03:30
Thanks for opening the issue! We're tracking this issue in directus/cli#1 now as it was moved 👍 Closing this as a duplicate of it.

**Closed by azrikahar** 2022-07-18 03:30 UTC
