### ISSUE TITLE
Generated OpenAPI schema uses the same `operationId` for two different operations

### ISSUE THREAD

**Issue by danmichaelo** [directus/directus#23447] opened 2024-08-22 06:58 UTC
### Describe the Bug

The OpenAPI schema returned from `/server/specs/oas` uses `"updateExtensions"` as `operationId`  for two different operations:

```json
    "/extensions/{name}": {
      "patch": {
        "summary": "Update an Extension",
        "description": "Update an existing extension.",
        "operationId": "updateExtensions",
```

and

```json
    "/extensions/{bundle}/{name}": {
      "patch": {
        "summary": "Update an Extension",
        "description": "Update an existing extension.",
        "operationId": "updateExtensions",
```

This causes e.g. openapi-typescript to fail.

### To Reproduce

```sh
$ curl -s -H "Authorization: Bearer REDACTED" localhost:8055/server/specs/oas \
  | jq . | grep '"operationId": "updateExtensions"'
        "operationId": "updateExtensions",
        "operationId": "updateExtensions",
```

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-08-22 08:42
Thanks for opening this issue! However this is a duplicate of an existing issue #23429, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #23429 for future updates.

**Closed by paescuj** 2024-08-22 08:42 UTC
