### ISSUE TITLE
Logout on refresh of AdminPanel

### ISSUE THREAD

**Issue by torstenhoegel** [directus/directus#8819] opened 2021-10-15 10:40 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hello guys,

after upgrading to rc.97, I'm experiencing the issue of being logged out after refresh of the admin panel.

This happenes on all instances on version v9.0.0-rc.97, both new installs as well as updated ones

### To Reproduce

Log in to Admin Panel, refresh the page -> logged out

### What version of Directus are you using?

v9.0.0-rc.97

### What version of Node.js are you using?

v16.10.0 / v14.15.4

### What database are you using?

psql (12.8 (Ubuntu 12.8-0ubuntu0.20.04.1)) / SQLite

### What browser are you using?

Chrome / Safari

### What operating system are you using?

macOS / Windows / Linux (ZorinOS + Ubuntu)

### How are you deploying Directus?

locally, docker, deploy script on digitalocean

**Comment by azrikahar** [comment] 2021-10-15 10:48
Duplicate of #8808

**Closed by azrikahar** 2021-10-15 10:48 UTC
Labels: Bug (Potential)
