### ISSUE TITLE
Translated text is not displayed in a selector from a relation much to one

### ISSUE THREAD

**Issue by aizquierdo100** [directus/directus#10401] opened 2021-12-08 21:27 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a collection called Province that has a multilanguage name field. I use the Translations (O2M) for it.

![province](https://user-images.githubusercontent.com/61983998/145282589-c5c3f842-9fd4-4c2f-b942-c3d0fbf4d639.JPG)
![province collection](https://user-images.githubusercontent.com/61983998/145282648-c2d6d449-f9b7-4565-b127-7237cc32da11.JPG)

![province trans](https://user-images.githubusercontent.com/61983998/145282694-b69fb220-c66f-4788-91d9-6dbe2c8272e0.JPG)

Then I have another collection called City that has a Many to One relationship with the Province collection. 
![city](https://user-images.githubusercontent.com/61983998/145282784-8b7d06aa-c959-4a14-92fa-e1c49a20c504.JPG)
![city collection](https://user-images.githubusercontent.com/61983998/145282834-16b04422-cb63-4379-9d98-81d6cd16cdaa.JPG)

I setup up the interface and the display section for the Many to One relation in the City collection.
![interface](https://user-images.githubusercontent.com/61983998/145283357-86d1cc1e-a90b-4d3d-8ccc-8e66f32e7a3e.JPG)
![display](https://user-images.githubusercontent.com/61983998/145283372-056a7b14-6c77-49e0-9864-171de5c3972c.JPG)

I hope to see in the province selector of the form to create cities the name of the provinces, but nevertheless it is not shown.

![city](https://user-images.githubusercontent.com/61983998/145283692-9728e96f-8f99-47a3-9e46-34d696535735.JPG)

The name of the province is not shown in the list of cities either.

![List](https://user-images.githubusercontent.com/61983998/145283869-b3269c4a-f7d1-4917-92dd-1f284fc935f4.JPG)

It is something i do wrong or is a malfunction? 

### To Reproduce

-

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

16.13.0

### What database are you using?

postgres 13

### What browser are you using?

Edge

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by JohnHillegass** [comment] 2021-12-10 00:28
I am seeing something similar with a many to any relationship. It seems the table view selector does not resolve the same way the detail view does.

**Comment by sn3h** [comment] 2021-12-16 21:20
Hello, I'm having the same issue with M2M. The thing is that translation field has this option:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/768656/146449957-19daddbb-a172-4647-8f9f-0c0e5bce3531.png">
<img width="388" alt="image" src="https://user-images.githubusercontent.com/768656/146449919-779a624b-b9ac-4e6c-8ac2-33afb4c9192e.png">

but relation has only Raw or Relative which fails even if set up properly, most probably as it does not know which language to use as default. 

Suggestion: It would be nice if default language for translations would be global variable  that would guide the system even in this scenario. In other words, if Translation display option would be merged with Related Values option

**Comment by jaycammarano** [comment] 2022-01-27 20:11
I'm able to reproduce this in 9.5.

> Suggestion: It would be nice if default language for translations would be global variable that would guide the system even in this scenario. In other words, if Translation display option would be merged with Related Values option

There is a PR for something similar: #8196 might be what you want.

**Comment by azrikahar** [comment] 2022-02-08 05:19
> hopefully just minimising admin by sharing the fix around

@AdamDudley Thanks! Really appreciate it. 😊

---

As the "relational translations display template" issue is indeed partly or even mostly related to the other issues in the comment above, and since #9329 should be the same underlying issue, I'll close in favor of tracking it over there.

**Closed by azrikahar** 2022-02-08 05:19 UTC
Labels: App, Bug
