### ISSUE TITLE
M2A field opens the junction collection when clicked

### ISSUE THREAD

**Issue by xu4wang** [directus/directus#17606] opened 2023-02-23 08:17 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I have one collection named clients which have only one M2A field, named business.

In the below screen capture, If I  click the small arrow below "1 item".
<img width="751" alt="image" src="https://user-images.githubusercontent.com/311397/220852868-3a3631b8-83e7-44e2-a5d0-9a4b1cab7fa5.png">

It will open the junction collection. clients_business.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/311397/220852907-f972bb58-0560-4ad2-87ce-543e783a0bf8.png">

I think the junction collection is not supposed to be edited under content.

### To Reproduce

1. create one collection "clients'
2. create 2 more collections "profile1" and "profile2"
3. create on M2A field "business" under clients
4. add one item inside clients, add one value into the business field too.
5. open clients under content
6. click the only one item
7. click the only one field "business"
8. focus on the 1 item, and click the arrow below

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2023-02-23 09:18
Duplicate of #17108

**Closed by azrikahar** 2023-02-23 09:18 UTC
