### ISSUE TITLE
Problem with parsing custom field validation?

### ISSUE THREAD

**Issue by vanessajbell** [directus/directus#4273] opened 2021-02-24 18:20 UTC
1) I'd like to set up custom update settings for a restricted role. So they should only be able to update the 'Status' field to either 'draft' or 'review'. I am attaching screenshots of what I entered into validation as well as the error message I'm getting if the editor user tries to change the status from 'draft' to 'review' (which should be allowed).

2) Exact steps to reproduce this issue
   For a restricted (non-admin) role, write a custom field validation for updating a collection. As the restricted user, attempt to update the field with validation for an existing item in that collection.

3) Your environment:
    **What version of Directus you are using:** ^9.0.0-rc.34
    **Which DBMS are you using:** Postgres ^8.5.1
    **Which deployment are you using (npx, Docker, ...):** npx
    **What browser are you using:** Chrome 88

4) Any other relevant information we might need to reproduce this issue
![field-validation](https://user-images.githubusercontent.com/72411922/109045889-fbf99600-7688-11eb-9f73-5688e73a0224.jpg)
![maybe-a-bug](https://user-images.githubusercontent.com/72411922/109045894-fc922c80-7688-11eb-9b66-a7b6c77815d3.jpg)

**Comment by rijkvanzanten** [comment] 2021-02-24 18:56
I think this is a duplicate of https://github.com/directus/directus/issues/3597 which was fixed in rc.35 👍🏻 

It seems to work as expected in the latest version of Directus

**Closed by rijkvanzanten** 2021-02-24 18:56 UTC
Labels: Duplicate
