### ISSUE TITLE
Foreign key error at update of a M2O field 

### ISSUE THREAD

**Issue by stouch** [directus/directus#9752] opened 2021-11-12 10:43 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Since 9.0.1, it became impossible to just update the "Display" tab of a M2O field.

### To Reproduce

Just create a M2O field and then try to update the "Display" tab -> Getting a foreign key error.

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

latest

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-11-16 04:15
Can't seem to reproduce this on my end:

https://user-images.githubusercontent.com/42867097/141906734-b090f307-fa6d-4359-bdf9-85d9ac8e6bf9.mp4

Can you confirm the steps I did was what you meant? Just in case there's any misinterpretation here.

If it is, it'll be very helpful if you can revise the reproduction steps so that we'll be able to reliably reproduce it to confirm that it is indeed a valid bug.

**Comment by kwiatkk1** [comment] 2021-11-19 11:13
@azrikahar did you used mysql as a database? because I think bug may be mysql related: 

I created two collections (`faq`, `faq_groups`) via Directus UI:
- both of them have default id field (auto increment, not null, integer) which in db produces: `id int unsigned NOT NULL AUTO_INCREMENT`
- faq has m2o reference field group (`group int unsigned DEFAULT NULL`) which references faq `id CONSTRAINT faq_group_foreign FOREIGN KEY (group) REFERENCES faq_groups (id) ON DELETE SET NULL`

To that point everything works fine.

But when I try to modify group field (for example change its display options), an error with the following message occures:
- `alter table faq modify group int null - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'group' and referenced column 'id' in foreign key constraint 'faq_group_foreign' are incompatible.`

I think it is because ALTER doesn't include `'unsigned'`.

**Comment by rijkvanzanten** [comment] 2021-11-22 19:15
@kwiatkk1 What version of MySQL are you using? I just tried this on MySQL 8.0.16 and it seems to work as expected

**Comment by kwiatkk1** [comment] 2021-11-29 13:32
`v8.0.26`

I've tried to replicate it once again (using the latest Directus release, 9.1.2), and it seems to work fine now. 
So either I did something wrong from the beginning / have a wrong setup then, or it was fixed in a meantime.

**Closed** 2021-12-01 01:11 UTC
Labels: Needs More Info
