### ISSUE TITLE
"Unknown error" on password reset

### ISSUE THREAD

**Issue by battosai30** [directus/directus#23880] opened 2024-10-18 15:43 UTC
### Describe the Bug

If you set a password policy, and user set a password which don't respect it, it throws a "Unknown error" message.

### To Reproduce

Define password policy
Start a "forget password" process
Follow the link
Set a password which doesn't respecct the password policy

I did not try again but just before discovering this issue, I was not able to log in. It leads me to reset my password. But before I was not able anymore to login, I added a password policy my password was not respecting. Maybe the same bug leading to two different issues ?

### Directus Version

v11.1.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

MySQL

**Comment by robsoncombr** [comment] 2024-11-23 19:41
This is a bug in user interface. Was going to file same bug but found this already opened.

If the password does not match the rules defined in Settings during the User Registration, no error or exception is sent to log, also, the UI error says that there was an "Unexpected Error", the only place I see a real note it in the response payload from the POST call, below:

```json
[
  {
    "message": "Validation failed for field \"password\". Value doesn't have the correct format.",
    "extensions": {
      "field": "password",
      "type": "regex",
      "invalid": "************",
      "code": "FAILED_VALIDATION"
    }
  }
]
```

**Comment by rijkvanzanten** [comment] 2024-11-26 00:43
Thanks for the issue! There's already another issue reporting the same problem, so I'll close this one so we don't end up with duplicates 🙂 https://github.com/directus/directus/issues/21971

**Comment by rijkvanzanten** [comment] 2024-11-26 00:43
Duplicate of https://github.com/directus/directus/issues/21971

**Closed by rijkvanzanten** 2024-11-26 00:43 UTC
