### ISSUE TITLE
M2O: Updating, Creating, Removing, (PATCH) from one-side broken

### ISSUE THREAD

**Issue by nickluger** [directus/directus#5710] opened 2021-05-17 05:34 UTC
### How to reproduce:

1. Create a simple M2O-relationship like `author (1) <=> articles (many)`. You can also use my SQL-Dump of this DB for a quick setup: 
[directus-patch-m2o-broken-issue-report-dump.sql.zip](https://github.com/directus/directus/files/6491308/directus-patch-m2o-broken-issue-report-dump.sql.zip)
2. There's an author `Ben Graham`. Go into the author and try to create a new `article`, like `"Security Analysis"`.
3. See the error:

![Bildschirmfoto 2021-05-17 um 07 29 39](https://user-images.githubusercontent.com/32647249/118436770-afe74c00-b6e1-11eb-98ef-cbf473cc684a.png)

This is the log in `trace`-log level with all DB requests:
```
07:29:25 �07:30:41 🔍 [5.534ms] select "role", "directus_roles"."admin_access", "directus_roles"."app_access" from "directus_users" left join "directus_roles" on "directus_users"."role" = "directus_roles"."id" where "directus_users"."id" = $1 and "status" = $2 limit $3 [1c1a31be-09a0-40bb-9e14-6b88a574526a, active, 1]
07:30:41 🔍 [10.957ms] update "directus_users" set "last_access" = $1 where "id" = $2 [Mon May 17 2021 07:30:41 GMT+0200 (Mitteleuropäische Sommerzeit), 1c1a31be-09a0-40bb-9e14-6b88a574526a]
07:30:41 🔍 [2.726ms] select "ip_access" from "directus_roles" where "id" = $1 limit $2 [fe7a6664-aae4-40ba-9bc8-81b5e6e6ef83, 1]
07:30:41 🔍 [3.863ms]
        SELECT
          relname as table_name,
          pg_attribute.attname as column_name
        FROM
          pg_index,
          pg_class,
          pg_attribute,
          pg_namespace
        WHERE
          indrelid = pg_class.oid
          AND nspname IN ($1)
          AND pg_class.relnamespace = pg_namespace.oid
          AND pg_attribute.attrelid = pg_class.oid
          AND pg_attribute.attnum = ANY (pg_index.indkey)
          AND indisprimary
       [public]
07:30:41 🔍 [13.643ms]
        SELECT
          c.table_name,
          c.column_name,
          c.column_default as default_value,
          c.is_nullable,
          c.data_type,
          c.is_identity
        FROM
          information_schema.columns c
        LEFT JOIN information_schema.tables t
          ON c.table_name = t.table_name
        WHERE
          t.table_type = 'BASE TABLE'
          AND c.table_schema IN ($1);
       [public]
07:30:41 🔍 [1.916ms] select "collection", "singleton", "note", "sort_field", "accountability" from "directus_collections" []
07:30:41 🔍 [1.852ms] select "id", "collection", "field", "special", "note" from "directus_fields" []
07:30:41 🔍 [2.113ms] select * from "directus_relations" []
07:30:41 🔍 [2.514ms] insert into "article" ("author", "title") values ($1, $2) [1, Security Analysis]
07:30:41 🔍 [2.641ms] select max("id") as "id" from "article" limit $1 [1]
07:30:41 🔍 [2.191ms] insert into "directus_activity" ("action", "collection", "ip", "item", "user", "user_agent") values ($1, $2, $3, $4, $5, $6) [create, article, ::1, 3, 1c1a31be-09a0-40bb-9e14-6b88a574526a, Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36]
07:30:41 🔍 [1.813ms] select max("id") as "id" from "directus_activity" limit $1 [1]
07:30:41 🔍 [2.055ms] insert into "directus_revisions" ("activity", "collection", "data", "delta", "item") values ($1, $2, $3, $4, $5) [17, article, {"title":"Security Analysis","author":"1","id":3}, {"title":"Security Analysis","author":"1","id":3}, 3]
07:30:41 🔍 [2.801ms] select max("id") as "id" from "directus_revisions" limit $1 [1]
07:30:41 🔍 [3.152ms] select "article"."id" from "article" where ("article"."author" = $1 and "article"."id" not in ($2)) order by "article"."id" asc limit $3 [1, 3, 100]
07:30:41 🐛 "author" contains an invalid value
07:30:41 ✨ request completed PATCH 400 /items/author/1 109ms
```

### Also

- Running the last request `select "article"."id" from "article" where ` directly on the DB works but always returns an empty result. Is this intentional?
- **M2M**-relations **work fine**!
- Creating the `article` from the **many-collection** and associating the `author`, `Ben Graham` there, **works perfectly**.
- This also fails when **adding** or **removing** existing items, i.e. `articles`.
- I searched the Directus codebase for the term `"contains an invalid value"` and did not find anything... Is this emitted by an underlying library?

### Project details
Directus Version: 9.0.0-rc.68
Environment: production
OS: macOS Big Sur (11)
Node: 14.16.1

**Comment by nickluger** [comment] 2021-05-17 05:44
DB Settings used for the SQL dump
```
DB_CLIENT="pg"
DB_HOST="127.0.0.1"
DB_PORT="5432"
DB_DATABASE="directus-issues"
DB_USER="bluey"
DB_PASSWORD="password"
DB_SSL="false"
```

**Comment by rijkvanzanten** [comment] 2021-05-17 14:47
Duplicate of https://github.com/directus/directus/issues/5070

**Closed by rijkvanzanten** 2021-05-17 14:47 UTC
Labels: Duplicate

**Comment by rijkvanzanten** [comment] 2021-05-17 14:49
@nickluger The problem is that Directus nullifies the m2o fields for all deselected items in the O2M. If your m2o field is not nullable, it'll throw an error saying that it fails the validation, as `null` isn't allowed in that field. This is technically failing successfully. We're currently wrapping up https://github.com/directus/directus/pull/5615 that includes a feature that allows you to chose whether to nullify the m2o field, set it to another value (/default) or delete the related item outright 👍🏻

**Comment by nickluger** [comment] 2021-05-17 17:10
Thanks @rijkvanzanten for the hint to the duplicate. It's clear that **deselecting** would lead to nullification, while `null` is not allowed, which should result in some error or deletion. But in my use case I'm **adding** a new item on the `M`-side of `O2M`. This should receive the ID of the `O`-side-item and not `null`.

**Comment by nickluger** [comment] 2021-05-17 17:14
P.S. There are no `articles` being deselected in this step, there are actually none at all on the `author` yet. The #5070 is actually the same case? Nothing being deselected or deleted there, just a creation.

**Comment by rijkvanzanten** [comment] 2021-05-17 17:25
> This should receive the ID of the O-side-item and not null.

Correct, and it does 🙂 

> P.S. There are no articles being deselected in this step, there are actually none at all on the author yet. The #5070 is actually the same case? Nothing being deselected or deleted there, just a creation.

That's correct. The way the o2m flow works currently is by saving all the changes in the array, and nullifying any record that used to have the current item as parent and isn't included in the current change set anymore:

https://github.com/directus/directus/blob/ceb5788602005a6e56dbdb9e2da726125a4ac27b/api/src/services/payload.ts#L474-L493

I suppose we could add in a read to check if any of those items exist before trying to nullify them, but that would only delay the inevitable as deselecting would still throw the error 🤔

**Comment by nickluger** [comment] 2021-05-17 18:20
Thank you @rijkvanzanten for the explanation and patience, but I still don't get it completely 😅

> nullifying any record that used to have the current item as parent 

No record has (or ever had) the current item as parent (in my example).

>  and isn't included in the current change set anymore

The first and only record ever created is included in the current changeset, but no other record was every related to the parent anyway, so the change is only an addition. If we create the list of items that were associated to the parent, but are no longer in the changeset, this list should be empty. 

In other words, this filter should cause the updated set to be empty:
```ts
[relation.many_primary]: {										
_nin: savedPrimaryKeys,									
},
```

because `savedPrimaryKeys` should only contain the new item and there is no item in the database that at the same time fulfills:
```ts
[relation.many_field]: {										
_eq: parent,									
},
```

So this code should not nullify anything? That's why I do not understand, why it's responsible for my use case.
This would only happen if `savedPrimaryKeys` would (for whatever reason) not contain the ID of the newly created Child. In that case the newly created child would be set to `null` which would cause the error of course.

**Comment by rijkvanzanten** [comment] 2021-05-17 18:24
> So this code should not nullify anything? That's why I do not understand, why it's responsible for my use case.

You are correct! However, I am also correct 😄 

We tell the database to nullify all existing items with the current item as parent, excluding the newly created row.

You are correct in saying that "with the current item as parent, excluding the newly created row" results in 0 items being updated. However, the database isn't smart enough to know that. It just sees the "set to null" and goes NOPE ⚠️ 🚨 👮🏻 

That's why my proposed workaround would work for this particular use case (check if "with the current item as parent, excluding the newly created row" has > 0 items to update before trying to update) will help, but it will still fail when deselecting items, as long as nullify is used for deselect.

**Comment by nickluger** [comment] 2021-05-17 18:42
Ayy, okay, that's very interesting! 😯

Just curious: Is that an ORM thing? Because running a raw `UPDATE article SET author_id = NULL` works fine on Postgres, if the `WHERE`-filter leads to an empty set, although `author_id` is a `NOT NULL`-field.

OK, then this workaround would be perfect 👌   - and necessary to make O2M-creation possible again. I don't see that https://github.com/directus/directus/issues/2942 would help here.

Regarding **deselection**:
Neither `ON CASCADE DELETE` nor `ON CASCADE SET NULL` would be apt for our use case, as I need it to throw an error. In DB language, we need `ON CASCADE RESTRICT`. So the error is the expected behavior for deselecting items that were previously selected. Does https://github.com/directus/directus/issues/2942 handle that?

Just the error message could be a bit friendlier/human understandable. Although i know the issue, i often ask myself what just happened if i forget it's an M2O and not an M2M 😅

**Comment by nickluger** [comment] 2021-05-17 18:47
Something is already running your workaraound-request it seems, if i take a look at the logs:
```
select "article"."id" from "article" where ("article"."author" = $1 and "article"."id" not in ($2)) order by "article"."id" asc limit $3 [1, 3, 100]
```
Could its result be reused for the >0 check?

**Comment by rijkvanzanten** [comment] 2021-05-17 18:47
> Just curious: Is that an ORM thing?

Not 100% sure! Could also be small differences in how DB vendors handle different situations 🤔 

`ON CASCADE RESTRICT` from the "o2m" perspective would effectively be the same as the current situation, assuming we have that o2m update check implemented 🙂 I'll add that check as part of the #5615 👍🏻

**Comment by rijkvanzanten** [comment] 2021-05-17 18:48
> Something is already running your workaraound-request it seems, if i take a look at the logs: could it be reused for the >0 check?

Yes and yes!

**Comment by rijkvanzanten** [comment] 2021-05-17 19:50
@nickluger f33abfc27321e628807a5cb7352e2786fb705f26 should do the trick 🙂

**Comment by nickluger** [comment] 2021-05-18 11:35
Works like a charm 👌  - thank you @rijkvanzanten.

By the way: Although things are still going a bit bumpy sometimes (as it's in RC state), the responsiveness & resourcefulness of you guys and also the Directus-community is really exceptional 👍
