### ISSUE TITLE
CRDB Install and migrate does not set Primary Key name for all keys

### ISSUE THREAD

**Issue by wodka** [directus/directus#13173] opened 2022-05-08 07:51 UTC
### Describe the Bug

The primary key name of several tables is called "primary" - which then causes problems because the it is the same across tables and then duplicates fields in relation tables.

Tables with this problem:
* directus_activity
* directus_fields
* directus_notifications
* directus_permissions
* directus_presets
* directus_relations
* directus_revisions
* directus_settings
* directus_webhooks

Also all created DataModels!

![image](https://user-images.githubusercontent.com/385731/167286750-80ca0d7b-2a40-4c7a-83a4-a296e93ec7b7.png)

this causes something like this:
![image](https://user-images.githubusercontent.com/385731/167286816-831b7076-a080-4fb1-a4d1-b66b578b160e.png)

### To Reproduce

just install directus and start with CRDB - default primary key names are there set to `primary`

### Errors Shown

Visible through seemingly duplication of fields:
![image](https://user-images.githubusercontent.com/385731/167286816-831b7076-a080-4fb1-a4d1-b66b578b160e.png)

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

16

### What database are you using?

Cockroachdb

### What browser are you using?

Chrome

### How are you deploying Directus?

CLI / Docker

**Comment by azrikahar** [comment] 2022-05-08 14:32
Can confirm the same behavior for the listed Directus system tables, and the duplicate fields:

https://user-images.githubusercontent.com/42867097/167301045-5845b5e7-4bc9-4dd3-ba88-2185571b6574.mp4

I believe this should actually be the same root cause as #11760, so lets close this in favor of tracking it over there 👍

**Closed by azrikahar** 2022-05-08 14:32 UTC
Labels: Bug (Potential)
