### ISSUE TITLE
Directus v9.22.4 Minio

### ISSUE THREAD

**Issue by stormbyte** [directus/directus#17190] opened 2023-01-16 13:39 UTC
### Describe the Bug

```
STORAGE_REMOTE_S3_FORCE_PATH_STYLE=true
```
Is no longer respected 

### To Reproduce

Setup Minio docker
Setup Directus With S3 storage 
Health check fails because incorrect domain.

Revert back to v9.21.2 and still works

### Errors Shown

xxx-directus-1  | [13:25:46.116] WARN: getaddrinfo ENOTFOUND directus.minio
xxx-directus-1  |     err: {
xxx-directus-1  |       "type": "Error",
xxx-directus-1  |       "message": "getaddrinfo ENOTFOUND directus.minio",
xxx-directus-1  |       "stack":
xxx-directus-1  |           Error: getaddrinfo ENOTFOUND directus.minio
xxx-directus-1  |               at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
xxx-directus-1  |       "errno": -3008,
xxx-directus-1  |       "code": "ENOTFOUND",
xxx-directus-1  |       "syscall": "getaddrinfo",
xxx-directus-1  |       "hostname": "directus.minio",
xxx-directus-1  |       "$metadata": {
xxx-directus-1  |         "attempts": 1,
xxx-directus-1  |         "totalRetryDelay": 0
xxx-directus-1  |       }
xxx-directus-1  |     }

### What version of Directus are you using?

v9.22.4

### What version of Node.js are you using?

v18.13.0

### What database are you using?

Postgres 13

### What browser are you using?

firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2023-01-16 13:57
With `9.22.4` onwards, you will need to use `STORAGE_REMOTE_FORCE_PATH_STYLE=true` (no `_S3_` in between) instead of `STORAGE_REMOTE_S3_FORCE_PATH_STYLE=true` 👍

Closing this as duplicate of #17170, but opting to track this as an update to the docs via https://github.com/directus/docs/issues/265.

**Closed by azrikahar** 2023-01-16 13:57 UTC
