### ISSUE TITLE
Applying a schema does not seem to invalidate the schema cache

### ISSUE THREAD

**Issue by KieronWiltshire** [directus/directus#22674] opened 2024-06-05 14:06 UTC
### Describe the Bug

I have a command which looks like this:
`npx directus schema snapshot ./snapshots/\"$(date +\"%F\")\"-snapshot-\"$(date +\"%s\")\".yaml"`

I executed this command on my laptop environment, I then went to my desktop and executed the following command:
npx directus schema apply ./snapshots/<snapshot>.yaml

My schema applied, but I got this error:
![image](https://github.com/directus/directus/assets/4332346/808c82e4-2331-4986-8827-7308decb3797)

Flushing the cache and restarting my docker container then resolved the issue.

### To Reproduce

1. Create a basic schema
2. Export the schema
3. Clear environment completely and start fresh
4. Start directus and apply schema while directus is running

### Directus Version

v10.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis/postgis:16-3.4

**Comment by br41nslug** [comment] 2024-06-05 14:15
I am unable to reproduce this issue using the given reproduction steps, please provide enough information to recreate the error situation on a fresh instance.
![image](https://github.com/directus/directus/assets/9389634/68c2a03f-851b-4c81-a0c2-8ea772b1873e)

Closing the issue for now but happy to re-open when enough details are available to reproduce it 😄

**Closed by br41nslug** 2024-06-05 14:15 UTC
Labels: :detective: Needs More Info

**Comment by marian-galik** [comment] 2024-06-13 15:22
https://github.com/directus/directus/issues/17117
