### ISSUE TITLE
One to many: Create new fails if related many to one is required

### ISSUE THREAD

**Issue by Dominic-Marcelino** [directus/directus#15062] opened 2022-08-14 15:14 UTC
### Describe the Bug

Let's create a "**parent**" and a "**child**" collection.
The **child** collection get's a **many-to-one relation** to the **parent** and the parent a related **one-to-many** alias.

When we try to create new child items from the parent's object, the childs "parent" field is always disabled in the drawer. 
On creating the item it get's automatically set to the current opened parent (everything as expected).

But once we make the parent-id field required on the child we can't create any child-items from the parent anymore. The app prevents this, as there's no parent selected. 

### To Reproduce

@ see above

1.) Create child and parent collection
2.) Create many-to-one relation on child to parent & corresponding one-to-many alias
3.) Create a parent object and try to create a child --> everything works as expected
4.) Set the parent_id on the child as required
5.) Re-try to create a child from the parent and it fails

### Errors Shown

the parent.id field is required

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

N/A

### What database are you using?

MySQL

### What browser are you using?

Chrome

### How are you deploying Directus?

N/A

**Comment by azrikahar** [comment] 2022-08-14 15:34
Duplicate of #15043 #15012 #14992. It has since been resolved by #14996 and will be included in the [next release](https://github.com/directus/directus/milestone/119).

**Closed by azrikahar** 2022-08-14 15:34 UTC

**Comment by drnachio** [comment] 2022-08-19 15:16
It is failing again in [v9.16.1](https://github.com/directus/directus/releases/tag/v9.16.1), I've bee waiting 2 week to be able to create O2M records.

**Comment by rijkvanzanten** [comment] 2022-08-19 15:19
@drnachio please don't cross post [the same message](https://github.com/directus/directus/issues/15053#issuecomment-1220797206) on duplicates.

**Comment by drnachio** [comment] 2022-08-19 15:25
Sorry
