### ISSUE TITLE
Clicking on an in-app notification navigates to a broken link

### ISSUE THREAD

**Issue by adanielyan** [directus/directus#17145] opened 2023-01-13 23:14 UTC
### Describe the Bug

When clicking on an item in the in-app notifications list the app navigates to `/<username>/content/null/null` and shows `Page Not Found` message.
<img width="931" alt="image" src="https://user-images.githubusercontent.com/861777/212435375-71bdda4e-8f56-4ef0-b71e-01885e80371b.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/861777/212435437-69e884eb-ff44-4d6f-8f92-e39613181bf2.png">

### To Reproduce

- Create a notification using Flows
- Click on notifications (bell) icon
- Click on the new notification in the list of notifications

### Errors Shown

No errors, just a Page Not Found message.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.12.1

### What database are you using?

Postgres 14 on RDS

### What browser are you using?

Edge

### How are you deploying Directus?

on Ubuntu server

**Comment by br41nslug** [comment] 2023-01-15 13:56
Duplicate of https://github.com/directus/directus/issues/13727

**Closed by br41nslug** 2023-01-15 13:56 UTC
Labels: Duplicate
