### ISSUE TITLE
M2O / O2M relationship creation not working in the latest RC 28 version

### ISSUE THREAD

**Issue by josias-r** [directus/directus#3663] opened 2021-01-12 15:21 UTC
I recently upgraded a project (I think from RC version 23) to version 28.
Since the upgrade, creating M2O or O2M relationships is not possible anymore, it is bugging.

For example:
I selected "Add-One-to-Many to my other collection as well":
<img width="594" alt="Screenshot 2021-01-12 at 16 15 27" src="https://user-images.githubusercontent.com/11424820/104333744-defe6e80-54f1-11eb-9139-04d62102149d.png">

And it ended up creating two new fields for the current collection instead of the "other" collection as it should have done:
<img width="814" alt="Screenshot 2021-01-12 at 16 15 42" src="https://user-images.githubusercontent.com/11424820/104333819-f3426b80-54f1-11eb-9f05-df06add1c548.png">

So I deleted the faulty created field and manually created the other relation from the other collection. This "seemed" to work, but afterwards, the item list didn't load anymore and I saw some error somewhere saying "the relationship is not set-up correctly".

All of this worked fine in a previous version

Note: Someone pointed out to me on discord, that this seems to be an app problem and it works through the API, I didn't test that.

**Comment by rijkvanzanten** [comment] 2021-01-12 15:31
I believe this is a duplicate of https://github.com/directus/directus/issues/3473 which is fixed in https://github.com/directus/directus/pull/3638

**Closed** 2021-01-12 15:32 UTC
