### ISSUE TITLE
Database error on editing M2O field properties

### ISSUE THREAD

**Issue by igiornotigi** [directus/directus#18576] opened 2023-05-12 10:38 UTC
### Describe the Bug

After creating a M2O field, any other modification result in a database error:

[INTERNAL_SERVER_ERROR] alter table `items_b` modify `rel` int - ER_FK_COLUMN_CANNOT_CHANGE: Cannot change column 'rel': used in a foreign key constraint 'items_b_rel_foreign'

![directus](https://github.com/directus/directus/assets/57590952/1f67f950-56dd-4e5b-aa57-dfa16ed0e99d)

database: MariaDB
hosting: ubuntu 22.04 local npm development
node version: 18.12.1

### To Reproduce

- create a M2O field and save
- try to modify the field settings

### Directus Version

v10.1.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by igiornotigi** [comment] 2023-05-12 13:02
seems to be a mariadb/mysql related issue.
Tested with docker/postgres and no problem

**Comment by licitdev** [comment] 2023-05-12 13:12
Duplicate of #18247

**Closed by licitdev** 2023-05-12 13:12 UTC
