### ISSUE TITLE
M2M relation display takes me to junction collection

### ISSUE THREAD

**Issue by dkophelyi** [directus/directus#9465] opened 2021-11-04 14:24 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When I set relational field to display and click on the link icon

![image](https://user-images.githubusercontent.com/59764298/140329826-c093dfa9-c8f1-4c95-b381-ba35512e8c99.png)

It takes me to the junction collection (which is hidden by default)

![image](https://user-images.githubusercontent.com/59764298/140329903-970416fa-7b15-43fb-9190-5efdcb6e3819.png)

### To Reproduce

1) Create 2 collections
2) Set the M2M relational field in each collections
3) Create items in both collections
4) Link the items to each other
5) In Layout Options > Fields enable the relational field
6) Click on `1 Item` then click on the link button

### Errors Shown

-

### What version of Directus are you using?

v9.0.0-rc.101

### What version of Node.js are you using?

16.11.1

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-11-04 17:36
This technically works as it's supposed to, as it uses the one-to-many relation to pull in those links. That being said, I do agree it's unexpected when you're using it with a m2m 👍🏻

**Comment by Toilal** [comment] 2021-11-04 18:59
This PR #9451 exactly solves this issue

**Comment by rijkvanzanten** [comment] 2021-11-04 22:56
Duplicate of #9422

**Closed by rijkvanzanten** 2021-11-04 22:56 UTC
Labels: App, Bug
