### ISSUE TITLE
Condition not working well with Dropdown Selection field type

### ISSUE THREAD

**Issue by jeffsmonteiro** [directus/directus#19588] opened 2023-09-04 23:08 UTC
### Describe the Bug

When creating a dropdown type field and adding a condition, the interface should respond to the change caused by the condition, which is not happening. The same test fail with a Radio type field.

FIELD
![image](https://github.com/directus/directus/assets/595398/0f9f8114-03d7-423f-9954-dd2fa3f7fe01)

FIELD OPTIONS
![image](https://github.com/directus/directus/assets/595398/43f3088b-de8c-456f-81ec-8a221b841f6b)

FIELD CONDITION
![image](https://github.com/directus/directus/assets/595398/591edd34-3313-4b79-92be-4379324ba580)

USER INTERFACE WITH DEFAULT OPTIONS
![image](https://github.com/directus/directus/assets/595398/fd992080-9840-4310-891f-02dc30e563e5)

USER INTERFACE WITH CONDITIONAL OPTION (would be Thrid, only)
![image](https://github.com/directus/directus/assets/595398/138d65d3-bfec-436d-b245-78593514e1d1)

### To Reproduce

1. Create the field "A" as selection dropdown with some options 
2. Create the field "B" a selection dropdown field with some options
3. Add a condition to field "B" determining a specific value as trigger and creating a new option to displey when the condition is met
4. Try the interface

### Directus Version

v10.5.3

### Hosting Strategy

Directus Cloud

**Comment by azrikahar** [comment] 2023-09-05 07:00
Thanks for opening this issue! However this is a duplicate of an existing issue #15281, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #15281 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2023-09-05 07:00 UTC
