### ISSUE TITLE
BUG: sqlite has no 'point' type - no such function: st_astext, creating a map field on an sqlite database causes 'page not found' error on edit

### ISSUE THREAD

**Issue by sxsws** [directus/directus#13271] opened 2022-05-13 08:30 UTC
### Describe the Bug

sqlite only has limited data types and i believe maps unknown data types to a string. the map field creates a field of point which it does not have. this prevents using the map field when editing. It causes an sqlite error - `no such function: st_astext`

### To Reproduce

1. Use sqlite db
2. Add map field to a collection (that creates a field of datatype 'point' to be created). I believe sqlite maps any unknown type to a string.
3. Attempt to edit a value and see 404 page

### Errors Shown

```
Error: select `persons`.`id`, `persons`.`status`, `persons`.`date_created`, `persons`.`date_updated`, `persons`.`firstName`, `persons`.`lastName`, `persons`.`title`, `persons`.`address`, `persons`.`rating`, `persons`.`photo`, st_astext(`persons`.`location`) as `location` from `persons` where `persons`.`id` = 2 order by `persons`.`id` asc limit 100 - SQLITE_ERROR: no such function: st_astext
```

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

12.22.5

### What database are you using?

sqlite 3.37.2

### What browser are you using?

firefox

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-05-13 08:43
Duplicate of #10648. SpatiaLite is required for geometry fields to work in SQLite, and this comment here should provide more info on the reasoning and the linked PR should shed some light on the setup steps: https://github.com/directus/directus/issues/10648#issuecomment-1000320206

**Closed by azrikahar** 2022-05-13 08:43 UTC
Labels: Bug (Potential)
