### ISSUE TITLE
Error: ER_DUP_FIELDNAME: Duplicate column name 'id'

### ISSUE THREAD

**Issue by egahmad** [directus/directus#21716] opened 2024-03-06 09:24 UTC
### Describe the Bug

We are using Docker and since the new release yesterday we get this errors and directus is not running 

directus                      | Error: ER_DUP_FIELDNAME: Duplicate column name 'id'
directus                      |     at Sequence._packetToError (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
directus                      |     at Query.ErrorPacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
directus                      |     at Protocol._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:291:23)
directus                      |     at Parser._parsePacket (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:433:10)
directus                      |     at Parser.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Parser.js:43:10)
directus                      |     at Protocol.write (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:38:16)
directus                      |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:88:28)
directus                      |     at Socket.<anonymous> (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:526:10)
directus                      |     at Socket.emit (node:events:517:28)
directus                      |     at addChunk (node:internal/streams/readable:368:12)
directus                      |     --------------------
directus                      |     at Protocol._enqueue (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/protocol/Protocol.js:144:48)
directus                      |     at Connection.query (/directus/node_modules/.pnpm/mysql@2.18.1/node_modules/mysql/lib/Connection.js:198:25)
directus                      |     at /directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/dialects/mysql/index.js:137:18
directus                      |     at new Promise (<anonymous>)
directus                      |     at Client_MySQL._query (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/dialects/mysql/index.js:131:12)
directus                      |     at executeQuery (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
directus                      |     at Client_MySQL.query (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/client.js:154:12)
directus                      |     at Runner.query (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:141:36)
directus                      |     at Runner.queryArray (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:235:21)
directus                      |     at ensureConnectionCallback (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:11:19) {
directus                      |   code: 'ER_DUP_FIELDNAME',
directus                      |   errno: 1060,
directus                      |   sqlMessage: "Duplicate column name 'id'",
directus                      |   sqlState: '42S21',
directus                      |   index: 0,
directus                      |   sql: 'alter table `directus_extensions` add `id` char(36) null, add `source` varchar(255), add `bundle` char(36)'
directus                      | }
directus                      | [09:18:30.230] TRACE: Retrieving database version
directus                      | [09:18:30.243] TRACE: Retrieving database version
directus                      | [09:18:30.244] TRACE: [2.645ms] select @@collation_database as collation limit ? [1]
directus                      | [09:18:30.248] TRACE: [2.853ms] select count(*) as `count` from `information_schema`.`tables` where `table_schema` = ? and `table_name` = ? limit ? [payitcamp, directus_collections, 1]
directus                      | [09:18:30.253] TRACE: [4.862ms] select `TABLE_NAME` as `name`, `TABLE_COLLATION` as `collation` from `information_schema`.`tables` where `TABLE_SCHEMA` = ? [payitcamp]
directus                      | [09:18:30.254] TRACE: [2.911ms] select `version` from `directus_migrations` []
directus                      | [09:18:30.254] INFO: Skipping CLI extensions initialization due to outstanding migrations.
directus                      | [09:18:30.262] INFO: Initializing bootstrap...

### To Reproduce

No steps needed, Docker pull the new update and then the container fail to start.

### Directus Version

v10.10.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by cliqer** [comment] 2024-03-06 10:42
Adding to this issue this is happening in the self-hosted too on migration:upgrade.
```
      "code": "ER_DUP_FIELDNAME",
      "errno": 1060,
      "sqlMessage": "Duplicate column name 'id'",
      "sqlState": "42S21",
      "index": 0,
      "sql": "alter table `directus_extensions` add `id` char(36) null, add `source` varchar(255), add `bundle` char(36)"
```
If I delete the columns, the migration script recreates these and then throws an error that it cannot remove the Primary key from id

**Comment by paescuj** [comment] 2024-03-06 12:49
Thanks for opening this issue! However this is a duplicate of an existing issue #21710, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #21710 for future updates.

**Closed by paescuj** 2024-03-06 12:49 UTC

**Comment by nasserelarrab** [comment] 2024-03-17 12:46
> Thanks for opening this issue! However this is a duplicate of an existing issue #21710, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #21710 for future updates.

yes i found the solution here
thank you
