### ISSUE TITLE
Run Script in a Flow Triggered by another flow data parameter is stale

### ISSUE THREAD

**Issue by jakedowns** [directus/directus#16329] opened 2022-11-05 08:16 UTC
### Describe the Bug

it seems like the data parameter passed to the Run Script operation has the data from the previous operation,
but not the currently executing action

for example, $last is null, and local "{{operationKey}}" data is also missing from the data object.

### To Reproduce

create a flow that defines some data
in a run script block just return data
```
module.exports = async function(data) {
    return data;
}
```

pass it to a log operation `{{$last}}`

create a second flow that calls the first flow

view the logs of the first flow. notice that the logged data object does not contain the data created in the first flow. only the second flow.

### What version of Directus are you using?

9.20.3

### What version of Node.js are you using?

n/a cloud hosted

### What database are you using?

n/a cloud hosted

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud Hosted

**Comment by jakedowns** [comment] 2022-11-05 08:19
i understand that it makes sense to retain the availability of the original data, $trigger and all...
but maybe it could be nested into a $previous_flow object?

**Comment by licitdev** [comment] 2022-11-07 07:03
Duplicate of #15653.

In addition, the returning of `data` in Run Script results in a circular reference in `$last`, leading to possible issues / errors. Ref: #15291. 

If it's necessary to pass the entire data object to the next operation, I believe `return Object.assign({}, data})` should break the circular reference.

**Closed by licitdev** 2022-11-07 07:03 UTC
Labels: Duplicate
