### ISSUE TITLE
String/json input variables in operations Raw Editor needs to be enclosed by quotation marks

### ISSUE THREAD

**Issue by danielband** [directus/directus#19244] opened 2023-07-26 06:07 UTC
### Describe the Bug

Non numeric field parameters need to be enclosed by quotation marks or the value is set to null. Also numeric parameters don't need to be enclosed but the value does not appear outside of the raw editor.

Not enclosing the parameter worked in previous versions just fine (I updated from 9.21.2). When the parameter was not enclosed in the raw editor Directus added the quotation marks in normal editor. Now, the quotation marks must be set in the raw editor by the user. 

![Bildschirmfoto 2023-07-26 um 12 54 57](https://github.com/directus/directus/assets/72872468/643d00cb-b7c6-4082-9244-e69c55073ea5)

Could not find any hint in v10.5 that it should work with the newest version.

### To Reproduce

How it does not work but should work:
1. Create Read Data Operation for example.
2. Try to set the raw editor of the query to something like {{$trigger.body}}
3. Save

==> The value is null

How it works:
Enter "{{$trigger.body}}" in the raw editor

### Directus Version

v10.4.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-07-27 18:19
https://github.com/directus/directus/assets/9141017/a4270046-ad18-49f3-a267-c9f3db7cf1a8

I'm not able to reproduce this based on the given instructions in the latest release (10.5.1 at time of writing) so I'll close this for now. Happy to reopen if I misunderstood or if more information becomes available 🙂

**Comment by danielband** [comment] 2023-07-28 01:35
Hi, it seems that the collection field is actually the one behaving like it should :D
Where I can reproduce the issue:
- Query field e.g in Read Operation (null value)
- Milliseconds in sleep (visual bug)

So for numeric fields there seems to be a visual bug and for json fields reject non quoted values. [Watch!](https://sos-de-fra-1.exo.io/directus/Bildschirmaufnahme%202023-07-28%20um%2008.25.15.mov)

**Comment by rijkvanzanten** [comment] 2023-07-28 13:27
Ahh what are the odds 😅

**Comment by rijkvanzanten** [comment] 2023-07-28 13:38
@azrikahar Mind helping me with this one? 🙂

**Comment by rijkvanzanten** [comment] 2023-07-28 13:50
> We should either change the types and apply some validation logic or transform the input on saving for those interfaces.

Or option 3: ignore the types completely when the raw editor is used

**Comment by paescuj** [comment] 2023-07-28 13:50
> > We should either change the types and apply some validation logic or transform the input on saving for those interfaces.
> 
> Or option 3: ignore the types completely when the raw editor is used

Ah, right that would make sense 👍

**Comment by danielband** [comment] 2023-07-29 03:54
Ah, one more thing concerning the field editor (not the raw editor). If I quote the input `"{{$trigger}}"` then the input is escaped `\"{{$trigger}}\"`. Which results in the input not being able to get parsed correctly.

**Comment by azrikahar** [comment] 2023-09-06 13:32
Just an update and clarification for the linked PR #19608:

> Now, the quotation marks must be set in the raw editor by the user.

> Query field e.g in Read Operation (null value)

Both of these should be addressed by the linked PR now (i.e. "double escaped quotes" issues in general for json fields), and I believe #19126 did play a part in resolving the null value portion of this issue as well!

> Milliseconds in sleep (visual bug)

Although this is indeed a visual/UX issue, but the linked PR doesn't technically address this yet since technically numeric inputs doesn't allow plain string by default. 

During the first conception of this `{}` raw editor, I do recall there was the idea of making all the fields to toggling raw editor _on_ when we're opening the drawer, to both indicate a field is using a variable/operation key as a way to resolve this not only for numeric fields, but also for any fields that don't typically "show" a plain string value. Perhaps detecting whether ala the match being done over here: https://github.com/directus/directus/blob/26fb314e9734dbf158d09ffe3e560e5b625bd510/packages/utils/shared/apply-options-data.ts#L38 
would be a potential solution?

Just wanted to clarify although the PR doesn't truly show the string value for numeric fields, it should be a seperate PR and issue in and of itself, at least from what my understanding of the underlying reason for said visual bug.

**Closed** 2023-09-08 07:39 UTC
Labels: Package: @directus/app, Bug

**Comment by paescuj** [comment] 2023-09-08 07:44
> During the first conception of this `{}` raw editor, I do recall there was the idea of making all the fields to toggling raw editor _on_ when we're opening the drawer, to both indicate a field is using a variable/operation key as a way to resolve this not only for numeric fields, but also for any fields that don't typically "show" a plain string value. Perhaps detecting whether ala the match being done over here:
> 
> https://github.com/directus/directus/blob/26fb314e9734dbf158d09ffe3e560e5b625bd510/packages/utils/shared/apply-options-data.ts#L38
>
>  would be a potential solution?

That sounds like a good plan to me 👍 Should we track this in a separate issue?
