### ISSUE TITLE
Got status 500 fetching schema from "http://127.0.0.1:8055/graphql/system"

### ISSUE THREAD

**Issue by Yvan2Ero** [directus/directus#12256] opened 2022-03-20 20:20 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I got status 500 when fetching schema from "http://127.0.0.1:8055/graphql/system"
I also get the same status when I perform an authentication request in **graphql**. 

### To Reproduce

After configuring a Directus 9.7.0 project, try to retrieve the database schema or try a **graphql** query on **/graphql/system**.
In my case I tried an authentication request using **insomnia**: 
`mutation {
	auth_login(email: "admin@example.com", password: "d1r3ctu5") {
		access_token
		refresh_token
	}
}
`

### Errors Shown

When fetching Schema:
![Screenshot_20220320_211023](https://user-images.githubusercontent.com/63490400/159184100-1b1230fb-faef-40e9-ade9-4a2f5c9a7144.png)

When submitted a **graphql** auth request:

![Screenshot_20220320_211401](https://user-images.githubusercontent.com/63490400/159184308-b5603ae5-8696-4e2d-b7b5-1302529b7c1c.png)

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### What operating system are you using?

Linux 5.4.0-99-generic

### How are you deploying Directus?

Running locally

**Comment by licitdev** [comment] 2022-03-21 08:31
@Yvan2Ero I am unable to reproduce the issue on Insomnia. Tested on both 9.7.0 production and locally on main branch.

<img width="1392" alt="Screenshot 2022-03-21 at 4 14 11 PM" src="https://user-images.githubusercontent.com/26413686/159225250-abf9ac91-f891-4059-8bd9-992c43791de4.png">

Please assist to test if the issue persists after running `npx directus bootstrap`.

**Comment by rijkvanzanten** [comment] 2022-03-21 13:34
@licitdev I believe this might be the same / very closely related to https://github.com/directus/directus/issues/12233. I'll close this as a duplicate for now, as the fix for https://github.com/directus/directus/issues/12233 will most certainly also resolve this 👍🏻

**Comment by Yvan2Ero** [comment] 2022-04-01 14:32
I just noticed that this error occurs when I reuse a database created during the configuration of another directus project. But with REST API everything works fine.

**Comment by rijkvanzanten** [comment] 2022-04-01 14:55
> I just noticed that this error occurs when I reuse a database created during the configuration of another directus project. But with REST API everything works fine.

Would you be able to share the exact steps to reproduce that setup? So far we haven't been able to get the error unfortunately

**Comment by Yvan2Ero** [comment] 2022-04-03 07:50
> > I just noticed that this error occurs when I reuse a database created during the configuration of another directus project. But with REST API everything works fine.
> 
> Would you be able to share the exact steps to reproduce that setup? So far we haven't been able to get the error unfortunately

1. configure a first Directus project with a posgresql database
2. Create collections and put some content
3. In order to reuse this same database in another project, configure a second project with another postgresql database
4. Once the second project is functional, try to use the data from the database configured with the first project, by modifying the .env file of the second project in order to put the information of the DB of the first.
5. Launch the second project: Everything will work fine, except the GraphQL queries on `/graphql/system`

**Comment by Yvan2Ero** [comment] 2022-04-09 08:47
> Would you be able to share a database dump of that setup? I'm still not able to reproduce this :C
[db.txt](https://github.com/directus/directus/files/8456564/db.txt)
rename to **db.sql**

**Comment by rijkvanzanten** [comment] 2022-04-11 19:38
@Yvan2Ero your permissions include update permissions to `directus_users` for the public role, which trips up the schema construction in GraphQL, as it tries to create the mutation for update_me, but there is no "me" as you're not logged in. Pushing a fix now 👍🏻

**Closed** 2022-04-11 19:39 UTC
Labels: API, Bug
