### ISSUE TITLE
Collection Field update - SQL error DROP INDEX

### ISSUE THREAD

**Issue by agorem** [directus/directus#4507] opened 2021-03-12 17:24 UTC
Hi, 

I have installed Directus rc 9.0.0 rc48 over VPS Centos 8 with MariaDb 10.3.27

Logged as Admin user when I try to save  a collection field update, I get the following error message related with a SQL action to ALTER a TABLE DROPPING an INDEX.

I check the Database Data Model and I can't find the INDEX the process tries to DROP.

I have performed the same action with different fields types getting the same error.

Kind regards....Antonio
![directus_edit_field_error](https://user-images.githubusercontent.com/9202643/110975770-72bcb180-8360-11eb-8c08-202aca4a641d.png)

**Comment by rijkvanzanten** [comment] 2021-03-12 17:36
Duplicate of https://github.com/directus/directus/issues/4481. This was fixed and released in rc.49 🙂

**Closed by rijkvanzanten** 2021-03-12 17:36 UTC
