### ISSUE TITLE
Translation Strings error

### ISSUE THREAD

**Issue by HemboPagi** [directus/directus#12425] opened 2022-03-28 11:29 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When using Translation Strings functionality in App, i received an error after trying to save key and translations.

### To Reproduce

1. Go admin/settings/translation-strings and click + (create translation string)

2. Fill in the Key and translations and save

<img width="834" alt="Screenshot 2022-03-28 at 14 27 14" src="https://user-images.githubusercontent.com/95413906/160388390-d6c2bfa6-c98f-4ccc-a6a9-aed8868b72f5.png">
 

### Errors Shown

{
  "message": "_.data.data.translation_strings.map is not a function. (In '_.data.data.translation_strings.map(y=>{var h;return{key:y.key,translations:r((h=y.translations)!=null?h:null)}})', '_.data.data.translation_strings.map' is undefined)",
  "line": 1,
  "column": 100010,
  "sourceURL": "https://xxxxxxx/admin/assets/index.262f690c.entry.js",
  "stack": "@https://db.dl.tlu.ee/admin/assets/index.262f690c.entry.js:1:100010\nasyncFunctionResume@[native code]\n@[native code]\npromiseReactionJobWithoutPromise@[native code]\npromiseReactionJob@[native code]"
}

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

14.18.2

### What database are you using?

Maria DB

### What browser are you using?

Safari

### What operating system are you using?

Linux 4.18.0-348.12.2.el8_5.x86_64

### How are you deploying Directus?

Running at uni virtual machine

**Comment by azrikahar** [comment] 2022-03-28 11:40
Duplicate of #12346, fixed by #12349 which will be released in [the next version](https://github.com/directus/directus/milestone/103).

**Closed by azrikahar** 2022-03-28 11:40 UTC
Labels: Bug (Potential)

**Comment by HemboPagi** [comment] 2022-03-28 12:11
thanks!
