### ISSUE TITLE
Ambiguous column reference when using sort and filter combined

### ISSUE THREAD

**Issue by DerMambo** [directus/directus#4246] opened 2021-02-23 14:46 UTC
1) The issue and what you expected to happen

I get an error when combining filter, limit and sort:
 
```graphql
query foo {
  items {
    pages(filter: {parent: {id: {_eq: 4}}}, limit: 2, sort: "date_published") {
      id
    }
  }
}
```

```json
{
  "errors": [
    {
      "message": "select \"pages\".\"id\" from \"pages\" left join \"pages\" as \"sJ9yuZVT\" on \"pages\".\"parent\" = \"sJ9yuZVT\".\"id\" where (\"sJ9yuZVT\".\"id\" = $1) group by \"pages\".\"id\" order by \"date_published\" asc limit $2 - column reference \"date_published\" is ambiguous",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "items",
        "pages"
      ]
    }
  ],
  "data": {
    "items": {
      "pages": null
    }
  }
}
```

2) Exact steps to reproduce this issue

Create a component collection named "component_page_preview_list"
parent_page M2O to page relation

Create a collection named "pages"
parent M2O to page relation
children O2M to page relation
components M2A to component relation
date_published datetime field
path string field

Create some entries for all of these.

Especially this relation is needed:
PageA --components--> component_page_preview_list --parent_page--> PageA -- children --> PageB
PageB -- parent --> PageA

3) Your environment:
    Directus 9.0.0-rc.42
    Postgres
    Docker

**Comment by rijkvanzanten** [comment] 2021-02-23 15:31
Number 1 is a duplicate of https://github.com/directus/directus/issues/3434 👍🏻 

I'll update your ticket to only be about Number 2

**Closed** 2021-02-23 15:53 UTC
Labels: API, Bug, Good First Issue
