### ISSUE TITLE
Error 500 when inserting new data into a specific table or updating existing ones

### ISSUE THREAD

**Issue by keniobats** [directus/directus#16872] opened 2022-12-21 13:23 UTC
### Describe the Bug

Hello,

I have a table with some relations on it, but the issue happens only with the main table when inserting even the minimum required data.
The other tables related to it has no problems at all when inserting data on them.

### To Reproduce

Here's a json representation of my main collection's structure:

```

[
	{
		"legajo": "test",
		"tipo_intervencion": "test",
		"fecha_de_comunicacion": "2022-12-11T23:41:00",
		"fecha_de_intervencion": "2022-12-12T00:52:00",
		"fecha_finalizacion_intervencion": "2022-12-12T05:20:00",
		"direccion": "test",
		"equipo_intervencion": [
			"test",
		],
		"date_created": "2022-12-12T20:53:16.745Z",
		"ubicacion": {
			"type": "Point",
			"coordinates": [
				-65.15118549932684,
				-26.883248226562642
			]
		},
		"observaciones": null,
		"id": 201,
		"ufi_interviniente": "Test",
		"acta_intervencion": "<p>A</p>",
		"victima": [
			196
		],
		"testigo": [
			407,
			408,
			409,
			410,
			411,
			412
		],
		"intervenciones_policias": [],
		"imputado": [
			150,
			151
		],
		"archivos_acta": [
			234
		],
		"Fotos_intervencion_": []
	}
]
```

### Errors Shown

```
[13:05:48] ERROR (41 on 9fbf537347cd): insert into "Intervenciones" ("date_created", "fecha_de_comunicacion", "fecha_de_intervencion", "fecha_finalizacion_intervencion", "tipo_intervencion", "ufi_interviniente", "user_created") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - column "indices" does not exist
    err: {
      "type": "DatabaseError",
      "message": "insert into \"Intervenciones\" (\"date_created\", \"fecha_de_comunicacion\", \"fecha_de_intervencion\", \"fecha_finalizacion_intervencion\", \"tipo_intervencion\", \"ufi_interviniente\", \"user_created\") values ($1, $2, $3, $4, $5, $6, $7) returning \"id\" - column \"indices\" does not exist",
      "stack":
          error: insert into "Intervenciones" ("date_created", "fecha_de_comunicacion", "fecha_de_intervencion", "fecha_finalizacion_intervencion", "tipo_intervencion", "ufi_interviniente", "user_created") values ($1, $2, $3, $4, $5, $6, $7) returning "id" - column "indices" does not exist
              at Parser.parseErrorMessage (/directus/node_modules/pg-protocol/dist/parser.js:287:98)
              at Parser.handlePacket (/directus/node_modules/pg-protocol/dist/parser.js:126:29)
              at Parser.parse (/directus/node_modules/pg-protocol/dist/parser.js:39:38)
              at Socket.<anonymous> (/directus/node_modules/pg-protocol/dist/index.js:11:42)
              at Socket.emit (node:events:513:28)
              at addChunk (node:internal/streams/readable:315:12)
              at readableAddChunk (node:internal/streams/readable:289:9)
              at Socket.Readable.push (node:internal/streams/readable:228:10)
              at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
      "length": 341,
      "name": "error",
      "severity": "ERROR",
      "code": "42703",
      "internalPosition": "36",
      "internalQuery": "SELECT primary_keys, foreign_keys, indices\n                                                                    FROM public._view\n            WHERE table_name = TG_TABLE_NAME",
      "where": "PL/pgSQL function table_notify() line 33 at SQL statement",
      "file": "parse_relation.c",
      "line": "3548",
      "routine": "errorMissingColumn"
    }
[13:05:48] POST /items/Intervenciones 500 33ms
```

### What version of Directus are you using?

9.21.2

### What version of Node.js are you using?

v16.18.1

### What database are you using?

postgis/postgis:13-master (docker)

### What browser are you using?

Chrome Version 108.0.5359.124 (Official Build) (64-bit)

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-12-23 00:20
Does this happen when using the app or are you seeing it on direct API usage?

**Comment by azrikahar** [comment] 2022-12-24 12:20
`TG_TABLE_NAME` seems to be a special variable for Postgres trigger functions: https://www.postgresql.org/docs/current/plpgsql-trigger.html, could this be a misconfigured trigger by any chance? (which should mean it's not caused by Directus in that case) 

Closing this in the meantime while we await for more info regarding this bug report 👍

**Closed by azrikahar** 2022-12-24 12:20 UTC

**Comment by keniobats** [comment] 2022-12-26 12:31
Hello @azrikahar and @rijkvanzanten 

> Does this happen when using the app or are you seeing it on direct API usage?

With both.


> `TG_TABLE_NAME` seems to be a special variable for Postgres trigger functions: https://www.postgresql.org/docs/current/plpgsql-trigger.html, could this be a misconfigured trigger by any chance? (which should mean it's not caused by Directus in that case)
> 
> Closing this in the meantime while we await for more info regarding this bug report +1

Indeed. I was using PGSync which syncs postgres with elasticsearch and that was causing the issue. 

Thanks a lot!

**Comment by azrikahar** [comment] 2022-12-27 09:59
> Indeed. I was using PGSync which syncs postgres with elasticsearch and that was causing the issue.

TIL! Thanks for the update on the root cause here ☺
