### ISSUE TITLE
Error exporting users

### ISSUE THREAD

**Issue by glowkeeper** [directus/directus#8545] opened 2021-10-04 16:56 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [ ] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Trying to export user data from the admin' app via the Administrator user. I click on users, export, and I get this:

{"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}

### To Reproduce

Log in as Administrator, then try and export users.

### What version of Directus are you using?

9.0.0-rc.51

### What version of Node.js are you using?

15.8.0

### What database are you using?

MySQL 8.0.23

### What browser are you using?

Chrome

### What operating system are you using?

Debian 4.19.194-3

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-10-04 17:29
Duplicate of https://github.com/directus/directus/issues/6243, which was fixed in https://github.com/directus/directus/pull/7175, and released in rc.89

**Closed by rijkvanzanten** 2021-10-04 17:29 UTC
Labels: Bug (Potential)

**Comment by glowkeeper** [comment] 2021-10-04 19:31
Cool.

So I have to upgrade, which makes me nervous 'cause it's a system with nearly 10k users (and growing). Are there any breaking changes between rc.51 and the latest release?

**Comment by rijkvanzanten** [comment] 2021-10-04 19:38
It's hard to say exactly what changes might affect your exact use, and which ones don't. Overall, IIRC the /items endpoint hasn't changed between those versions.

Starting with RC70, we've started to track all the changes of every version: https://github.com/directus/directus/blob/main/changelog.md

I'd definitely recommend making a staging copy of your setup, and using that to test the upgrades before committing to the same thing on the prod instance 👍🏻 Overall, i do highly recommend staying up to date, as every release introduces a lot of bug fixes, new features, and security updates.

**Comment by glowkeeper** [comment] 2021-10-04 20:03
Thanks, @rijkvanzanten - I'll run it past the team and form an upgrade plan...
