### ISSUE TITLE
Files are inaccessible a few hours after uploading in admin panel 

### ISSUE THREAD

**Issue by supra-dheerajacharya** [directus/directus#22981] opened 2024-07-11 11:11 UTC
### Describe the Bug

In the files module, a few hours after uploading, files become inaccessible and return the error: {"errors":[{"message":"You don't have permission to access this.","extensions":{"code":"FORBIDDEN"}}]}, despite still being in the upload folder.
![image](https://github.com/directus/directus/assets/158996872/9c1a1c97-f855-4f20-ad25-60c24aa0edea)

### To Reproduce

- Upload a file via the admin panel; it will be accessible immediately after upload.
- Wait for a few hours.
- Upon checking the files, they will no longer be accessible.

### Directus Version

v10.13.1

### Database

postgres

**Comment by hanneskuettner** [comment] 2024-07-11 11:14
Do you have TUS uploads enabled?

**Comment by supra-dheerajacharya** [comment] 2024-07-11 11:27
What TUS uploads @hanneskuettner

**Comment by hanneskuettner** [comment] 2024-07-11 11:42
That answers that haha. It is a new way of uploading files, that we introduced in 10.13, but if you did not enabled it explicitly, it will be disabled by default, so that is all fine. It was just an initial idea, since that is something new that was added.

Do you still see the files from the admin account? Do you have any flows or extensions enabled?

**Comment by supra-dheerajacharya** [comment] 2024-07-11 11:50
As you can see, the upload is working fine. The issue is in reading those files. Yes I have a flow but it is not related to the storage part and doesn't have any extension @hanneskuettner

**Comment by supra-dheerajacharya** [comment] 2024-07-11 11:51
> That answers that haha. It is a new way of uploading files, that we introduced in 10.13, but if you did not enabled it explicitly, it will be disabled by default, so that is all fine. It was just an initial idea, since that is something new that was added.
> 
> Do you still see the files from the admin account? Do you have any flows or extensions enabled?

Is there any documentation regarding the new way of uploading files?

**Comment by hanneskuettner** [comment] 2024-07-11 11:57
> As you can see, the upload is working fine. The issue is in reading those files. Yes I have a flow but it is not related to the storage part and doesn't have any extension 

I can see that the upload seems to be working fine, I'm just trying to figure out if you have permissions that would jump in after a certain time and target the `directus_files` collection. 

When you say "not related to the storage part", can you please confirm that they do not interact with `directus_files` at all?

Since you're saying they are not in the upload folder, you are using the local storage adapter, yes?

Do you see any errors in your Directus logs?

Do you have access to the database and can confirm that the files are located with the filename that corresponds to the `filename_disk` column?

> Is there any documentation regarding the new way of uploading files?
Not yet, but it only really makes sense to enable that if you intend on doing multi GB uploads.

**Comment by supra-dheerajacharya** [comment] 2024-07-11 12:12
> > As you can see, the upload is working fine. The issue is in reading those files. Yes I have a flow but it is not related to the storage part and doesn't have any extension
> 
> I can see that the upload seems to be working fine, I'm just trying to figure out if you have permissions that would jump in after a certain time and target the `directus_files` collection.
> 
> When you say "not related to the storage part", can you please confirm that they do not interact with `directus_files` at all?
> 
> Since you're saying they are not in the upload folder, you are using the local storage adapter, yes?
> 
> Do you see any errors in your Directus logs?
> 
> Do you have access to the database and can confirm that the files are located with the filename that corresponds to the `filename_disk` column?
> 
> > Is there any documentation regarding the new way of uploading files?
> 
> Not yet, but it only really makes sense to enable that if you intend on doing multi GB uploads.

- Flow is not interacting with directus_files
- Yes I am using local environment files that are in the upload folder in my code but reading them gives a 403 error in my console but no error in activity logs
![image](https://github.com/directus/directus/assets/158996872/48979e65-84c4-43fe-b2f1-398951736c26)
- I am admin user
- Yes, the filename that corresponds to the `filename_disk` column

**Comment by hanneskuettner** [comment] 2024-07-11 12:19
> Yes I am using local environment files that are in the upload folder in my code but reading them gives a 403 error in my console but no error in activity logs

By activity logs you mean your Docket logs, I presume?

Can you confirm that the requests that are returning the 403 are made to `/assets/<uuid>`?

**Comment by hanneskuettner** [comment] 2024-07-11 12:40
How do you store the files outside of Docker? Through a folder that is mounted into your container?

**Comment by supra-dheerajacharya** [comment] 2024-07-11 13:17
yes, we have mounted /database, /uploads, and /extensions. @hanneskuettner

**Comment by rijkvanzanten** [comment] 2024-07-11 14:09
This definitely sounds like your persistent storage isn't persistent. 

> And if the image is not on the disk I should get a not found error rather then a permission error!!!

That's on purpose, see https://github.com/directus/directus/discussions/4368 for more discussion on that topic 👍🏻

**Comment by rijkvanzanten** [comment] 2024-07-11 21:07
I'm not able to reproduce this based on the reproduction steps shared, so I'll close this for now. Happy to keep discussing or reopen when more information becomes available 👍🏻

**Closed by rijkvanzanten** 2024-07-11 21:07 UTC
Labels: :detective: Needs More Info
