### ISSUE TITLE
O2M interface doubles relations after sorting (visual bug)

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#15453] opened 2022-09-07 13:05 UTC
### Describe the Bug

In an O2M relation with sorting, the interface shows each element two times after the element got sorted: 
[Uploading screen-capture (7).webm…]()

### To Reproduce

- Create O2M Interface with sorting for collection A & B
- Add relations to the interface
- Drag&drop an element to resort it 

(see video)

### What version of Directus are you using?

9.17.3

### What version of Node.js are you using?

v14.19.3

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### How are you deploying Directus?

Linux VPS

**Comment by azrikahar** [comment] 2022-09-08 04:46
Seems like the video wasn't attached/uploaded correctly, would you mind retrying it?

**Comment by MichaelNussbaumerGOWEST** [comment] 2022-09-08 04:48
[screen-capture (7).webm](https://user-images.githubusercontent.com/15796397/189036657-5225c754-d47b-4624-afb8-e10796336791.webm)

**Comment by azrikahar** [comment] 2022-09-08 05:07
Thanks for reuploading the video! Unfortunately I'm not able to reproduce this neither on `9.17.3` nor `9.17.4` after following the current reproduction steps. (attaching both attempts at the end of this comment)

Can you try with a fresh Directus instance just so we can be sure whether this is a bug with Directus itself, or somehow just a bug on your current setup? 

---

### Attempt at reproducing this with 9.17.3

https://user-images.githubusercontent.com/42867097/189038987-03091ff1-6ab2-4612-b5ba-820423674509.mp4

### Attempt at reproducing this with 9.17.4

https://user-images.githubusercontent.com/42867097/189039007-b382c37e-6d36-4717-8ca1-35849cb41208.mp4

**Comment by MichaelNussbaumerGOWEST** [comment] 2022-09-08 05:22
Error only occurs when the interface has no Display template. After I added it, the error is gone.

**Comment by azrikahar** [comment] 2022-09-08 05:59
Hmm I re-tried doing everything from scratch and made sure not to set any display template, but I'm still not able to reproduce this:

https://user-images.githubusercontent.com/42867097/189045397-b4592307-7d6e-44a3-a1fb-1c7ac659eacb.mp4

> Error only occurs when the interface has no Display template. After I added it, the error is gone.

Do you mean now there's no error anymore even when you remove display template again?

**Comment by MichaelNussbaumerGOWEST** [comment] 2022-09-08 06:32
In my installation was a default display template for the related collection defined. In your case for collection B

**Comment by azrikahar** [comment] 2022-09-08 06:50
There shouldn't be any default display template out-of-the-box with Directus right? 🤔 Or do you mean default as in after you applied a schema snapshot?

That being said, were you able to reproduce this on a _fresh_ Directus instance? I think that's very important to make sure we're not missing any other potential details here.

**Comment by rijkvanzanten** [comment] 2022-09-13 01:34
I haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2022-09-13 01:34 UTC
Labels: App, Needs More Info, Can't Reproduce
