### ISSUE TITLE
Events during import

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#13508] opened 2022-05-24 13:59 UTC
## Description
My goal is to update every item after it's creation. To do that I am using a Webhook and on the handler I am making a `PATCH` on that item with the data I want.
When I create via App or via API it seems to not have any issues, but when I use the import feature, the items are created but only the last ones are updated with the data I asked. More curious is in Revisions I can see the data updated there, but not in the item itself.

## Investigation
https://github.com/directus/directus/blob/b855eb78748a468821e3a886cd0999d2ba789e6d/api/src/services/import-export.ts#L109
Because all the import process is running under a transaction, the `action` hooks (Webhooks are based on that) that happen for each item will be triggered but in database no data is there yet because the transaction is still running.

Also, if I put a `sleep` of a second between those two lines, everything works as expected:
https://github.com/directus/directus/blob/b855eb78748a468821e3a886cd0999d2ba789e6d/api/src/services/items.ts#L373-L374

### To Reproduce

- Create Blog collection
- Create Webhook which listens to `create` on Blog collection
- On Webhook handler, update the received item with some new data
- Import a CSV with 6 or more items into Blog

### Errors Shown

No errors are shown, just items are not updated as expected.

### What version of Directus are you using?

9.11.0 (main)

### What version of Node.js are you using?

v16.14.2

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2022-05-25 20:57
Duplicate of [#11172](https://github.com/directus/directus/issues/11172)

**Closed by rijkvanzanten** 2022-05-25 20:57 UTC
Labels: Duplicate
