### ISSUE TITLE
9.0.0-rc58 field labels are not displayed correctly in app

### ISSUE THREAD

**Issue by neo7-studio-web** [directus/directus#5099] opened 2021-04-16 13:01 UTC
Tested with Firefox and Chrome

Problem appeared when I updated from rc56 to rc58. It appears each time I log in.

If i update the data model, labels are back again.

![bug1](https://user-images.githubusercontent.com/18073828/115027926-99708980-9ec4-11eb-8adb-5d899909e92e.jpg)
![bug 2](https://user-images.githubusercontent.com/18073828/115027921-983f5c80-9ec4-11eb-9ba2-becea0a18cef.jpg)

**Comment by rijkvanzanten** [comment] 2021-04-16 14:17
Duplicate of https://github.com/directus/directus/issues/5078, fixed in https://github.com/directus/directus/commit/8af2cbadfaea857e86a985ebb5767f318fdc09e5, released in rc.59 😄

**Closed by rijkvanzanten** 2021-04-16 14:17 UTC

**Comment by neo7-studio-web** [comment] 2021-04-16 14:43
My word, you are too quick ! Thanks
