### ISSUE TITLE
Directus deletes the database or at least corrupts it

### ISSUE THREAD

**Issue by Bowadaa** [directus/directus#24271] opened 2024-12-21 14:49 UTC
### Describe the Bug

When I change elements of the directus model after a while, I can no longer connect and I have to restore the database.

![image](https://github.com/user-attachments/assets/180b42fe-eafd-43de-bb31-1ea21629e011)
### To Reproduce

It's totally random

### Directus Version

11.3.5

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 17

**Comment by robsoncombr** [comment] 2024-12-21 16:59
Hey @Bowadaa nice caught! Could you please try to reproduce the problem with Schema Cache disabled? I think I experienced something similar, not very damage but I noticed, in development, that the UI and/or the Cache was holding previous information even after save something new, I think I noticed something when working on multiple tabs.. Just wondering if you changed something and than changed again in sequence and it could have pick something from Cache or the Front sent something old.

I'm not sure, I just saw your report and remembered I saw something similar before, I disabled some caches and I don't notice it for some time now. Maybe the real Gurus might have some further idea.

For the record find Caching Config at [https://docs.directus.io/self-hosted/config-options.html#cache](https://docs.directus.io/self-hosted/config-options.html#cache)

**Comment by Bowadaa** [comment] 2024-12-21 17:13
Hi @robsoncombr 

Thank you so much for your suggestion and for taking the time to share your experience! I really appreciate it. I'll try disabling the Schema Cache as you mentioned and will test the scenario thoroughly to see if it resolves the issue.

Once I’ve completed my testing, I’ll definitely follow up with feedback on the results.

Thanks again for your help !

Best regards,

**Comment by Bowadaa** [comment] 2024-12-21 17:48
@robsoncombr 

Thank you again for your suggestion! I wanted to let you know that I added the suggested environment variables to disable the Schema Cache:

```
CACHE_ENABLED=false  
CACHE_SCHEMA=false  
```

After making these changes, I redeployed the project on Railway to ensure everything was updated. Unfortunately, the issue still persists.

I’ve also been checking the logs for additional insights but haven’t found a clear resolution yet. If you have any further suggestions or ideas on what else I could try, I’d greatly appreciate your input.

Thanks again for your time and support!

Best regards,

**Comment by robsoncombr** [comment] 2024-12-22 10:52
@Bowadaa Thank you very much for your time and patience on this, I know that sometimes reproducing and updating issues is not always the coolest task. I'm really interested on this issue, because if there is really something scrambling the schema or causing data loss, I consider a very high severity matter.

Would you have some sort of fast step-by-step to reproduce? On beginning you mentioned it was a random situation, but since you were able to reproduce maybe you have a better idea on how we could make it play here.

Thank you very much and see you. ;)

**Comment by Bowadaa** [comment] 2024-12-25 14:30
Hi @robsoncombr,

I have changed my calls to directus, I used to make calls with fairly open filters *.*.*.* for example to retrieve all my collections but since I no longer do this, I no longer have any problems thank you very much for your help and merry christmas.

**Comment by rijkvanzanten** [comment] 2024-12-25 16:49
Thank you for the update! Seeing we haven't been able to reproduce this and the problem we seemingly resolved, I'll close this for now. Merry Christmas to you as well! 🎄

**Closed** 2024-12-25 16:49 UTC
Labels: Needs Info
