### ISSUE TITLE
Unable to add relations with existing M2M

### ISSUE THREAD

**Issue by yellowBanano** [directus/directus#5196] opened 2021-04-22 16:13 UTC
I've tried to add relation inside admin panel and got an error about validation. I guess it's due to some NULL smth. I though that latest updates might change relation structure, that is why as experiment I created M2M relation via CMS interface. `categories_sample`. It works fine, but I didn't find any difference in `directus_relations` & `directus_fields` tables for `course_categories_category` (existing) and `course_category` (through CMS). All records displaying okay in both cases, but in _existing_ table I cannot save any new relation.
I found only difference in indexes. The one created through CMS without Foreign keys, but mine has. What might be the reason of error?

My env:
DB -- MySQL 8
Version -- v9.0.0-rc.59
Deployment -- npx
Browser -- latest Mozilla Firefox

![изображение](https://user-images.githubusercontent.com/32203047/115747625-1ce71a80-a39e-11eb-8a7a-44dd3d2f1b0f.png)
![изображение](https://user-images.githubusercontent.com/32203047/115747749-35573500-a39e-11eb-90b7-f1af0e93dc62.png)
![изображение](https://user-images.githubusercontent.com/32203047/115747818-4738d800-a39e-11eb-9312-20df816f286b.png)
![изображение](https://user-images.githubusercontent.com/32203047/115747927-6172b600-a39e-11eb-83b1-e25f65cf7f41.png)
![изображение](https://user-images.githubusercontent.com/32203047/115748080-849d6580-a39e-11eb-96cd-8f90a038cf6d.png)
![изображение](https://user-images.githubusercontent.com/32203047/115748110-89fab000-a39e-11eb-9aae-af54ef5fba45.png)
![изображение](https://user-images.githubusercontent.com/32203047/115748264-ad255f80-a39e-11eb-8155-836cc0391fd4.png)

**Comment by rijkvanzanten** [comment] 2021-04-22 23:43
Duplicate of https://github.com/directus/directus/issues/5070

**Closed by rijkvanzanten** 2021-04-22 23:43 UTC
