### ISSUE TITLE
Admin users failed to pass GraphQL validation, while permissioned users succeeded

### ISSUE THREAD

**Issue by samuelutomo** [directus/directus#10468] opened 2021-12-13 08:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

So I wrote a hook extension that calls Directus' GraphQL endpoint and sends a mutation query. I have 2 roles set, Administrator (a default role from Directus) and Manager with a specific set of permissions.

The mutation query somehow fails when used by users with Administrator role, while the permissioned ones succeeded.

To verify this weird behavior, I created another role that have a default system permission  with all permissions enabled for the user collection. The same GraphQL validation error occurred.

Does anyone have any similar experiences such as this? How do you deal with it?

@rijkvanzanten Is this supposed to be an unresolved bug?

### To Reproduce

```gql
mutation {
  create_pricing_service_statuses_item(data: {
    pricing_service_id: { id: 35 },
    status_id: { id: 1 },
    command_id: { id: 2 }
  }) {
    id
    status_id { id status }
    command_id { id command }
  }
}
```

### Errors Shown

```json
{
  "errors": [
    {
      "message": "GraphQL validation error.",
      "extensions": {
        "code": "GRAPHQL_VALIDATION_EXCEPTION",
        "graphqlErrors": [
          {
            "message": "Field \"create_service_commands_input.command\" of required type \"String!\" was not provided.",
            "locations": [
              {
                "line": 5,
                "column": 17
              }
            ]
          }
        ]
      }
    }
  ]
}
```

### What version of Directus are you using?

v9.2.2

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres 13 with PostGIS 3.1 extension

### What browser are you using?

Chrome, cURL, Altair GUI

### What operating system are you using?

Ubuntu 20.04.3 LTS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-12-13 19:35
Because the top level mutation is a "create", all nested data is treated as a create. This is a known issue, tracked in https://github.com/directus/directus/issues/7237.

In this particular case, one of your nested collections requires the "command" field to be set, as per the error:

`Field \"create_service_commands_input.command\" of required type \"String!\" was not provided.`

Duplicate of https://github.com/directus/directus/issues/7237

**Closed by rijkvanzanten** 2021-12-13 19:35 UTC
Labels: Bug (Potential)

**Comment by samuelutomo** [comment] 2021-12-14 00:40
> Because the top level mutation is a "create", all nested data is treated as a create. This is a known issue, tracked in #7237.
> 
> In this particular case, one of your nested collections requires the "command" field to be set, as per the error:
> 
> `Field \"create_service_commands_input.command\" of required type \"String!\" was not provided.`
> 
> Duplicate of #7237

But why does it work with permissioned user roles?

**Comment by rijkvanzanten** [comment] 2021-12-14 15:39
I'm assuming because your other permissioned role doesn't have write access to that particular field, so it doesn't show up in the GraphQL schema
