### ISSUE TITLE
npx create doesn't work on clean MySql

### ISSUE THREAD

**Issue by SebaSOFT** [directus/directus#4475] opened 2021-03-11 09:34 UTC
1) The issue and what you expected to happen
Having a clean database and MySql with a privileged user, the npx create script should work right away

2) Exact steps to reproduce this issue
    - Create a database and grant all privileges to a users
    - run `npx create-directus-project vayapin-website-directus`
    - Fill the MySQL contact data

3) Your environment:
    What version of Directus you are using.
       - latest create script
    Which DBMS are you using (MySQL 8, Postgres 12, ...).
       Server version: 5.7.33 MySQL Community Server (GPL)
    Which deployment are you using (npx, Docker, ...).
       npx on a VM
    What browser are you using (Chrome 87, Safari 14, ...).
       no yes a browser

4) Any other relevant information we might need to reproduce this issue
    A SQL dump of the setup.
```
$ npx create-directus-project vayapin-website-directus
npx: instaló 53 en 5.231s
? Choose your database client MySQL / MariaDB / Aurora
? Database Host: 127.0.0.1
? Port: 3306
? Database Name: test_database
? Database User: root
? Database Password: ********

Something went wrong while seeding the database:

[ER_CANT_DROP_FIELD_OR_KEY] alter table `directus_activity` drop foreign key `directus_activity_collection_foreign` - ER_CANT_DROP_FIELD_OR_KEY: Can't DROP 'directus_activity_collection_foreign'; check that column/key exists

Please try again

? Database Host: (127.0.0.1) 
(node:23229) UnhandledPromiseRejectionWarning: Error: Command was killed with SIGINT (User interruption with CTRL-C): npx directus init
    at makeError (/home/sebawork/.npm/_npx/23229/lib/node_modules/create-directus-project/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/sebawork/.npm/_npx/23229/lib/node_modules/create-directus-project/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Command.create (/home/sebawork/.npm/_npx/23229/lib/node_modules/create-directus-project/lib/index.js:73:2)
(node:23229) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23229) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

shouldn't this be a standard regression test?

**Comment by SebaSOFT** [comment] 2021-03-11 09:37
Maybe a duplicate of #4470, you can close then.

**Comment by rijkvanzanten** [comment] 2021-03-11 12:36
Yup! Duplicate of #4470

**Closed by rijkvanzanten** 2021-03-11 12:36 UTC
