### ISSUE TITLE
id is required error when trying to create a collection from UI

### ISSUE THREAD

**Issue by pvshum** [directus/directus#3208] opened 2020-11-26 11:47 UTC
PostgreSQL: v12 
Node.js Version: v14.15.1

<img width="556" alt="Screenshot 2020-11-26 at 14 21 14" src="https://user-images.githubusercontent.com/995412/100347239-1ecace80-2ff6-11eb-83a5-17844fdf1089.png">

```JSON
{
  "errors": [
    {
      "message": "\"id\" is required",
      "extensions": {
        "field": "id",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    },
    {
      "message": "\"id\" is required",
      "extensions": {
        "field": "id",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    },
    {
      "message": "\"id\" is required",
      "extensions": {
        "field": "id",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    },
    {
      "message": "\"id\" is required",
      "extensions": {
        "field": "id",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    },
    {
      "message": "\"id\" is required",
      "extensions": {
        "field": "id",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    },
    {
      "message": "\"id\" is required",
      "extensions": {
        "field": "id",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    },
    {
      "message": "\"id\" is required",
      "extensions": {
        "field": "id",
        "type": "required",
        "code": "FAILED_VALIDATION"
      }
    }
  ]
}
```

**Comment by pvshum** [comment] 2020-11-26 13:31
Small correction - this happens when using sqlite, not postgress

**Comment by benhaynes** [comment] 2020-11-26 13:33
Ahh, that makes more sense. SQLite has some significant differences from the other SQL vendors... it's still in "beta" for v9. MySQL and Postgres should be pretty stable.

**Comment by pvshum** [comment] 2020-11-26 13:37
Confirmed, Postgres works fine.

**Comment by rijkvanzanten** [comment] 2020-11-26 14:52
Duplicate of https://github.com/directus/directus/issues/3186

**Closed by rijkvanzanten** 2020-11-26 14:52 UTC
Labels: API, Bug, DB: SQLite

**Comment by caiguofeng0209** [comment] 2020-11-30 07:27
Do you want such doggy's uncut cock ?
