### ISSUE TITLE
ERROR: [OpenID] Failed to fetch provider config When Upgrade from 10.9.3 to 10.10.3.

### ISSUE THREAD

**Issue by sekhuat** [directus/directus#21814] opened 2024-03-12 06:51 UTC
### Describe the Bug

I perform an upgrade from 10.9.3 to 10.10.3 and got the following error when starting Directus.

```
[06:20:55.091] INFO: Loaded extensions: calibrate, cauth, content, filmroll, notification, payment, subscription, system, webpush
[06:20:55.102] ERROR: [OpenID] Failed to fetch provider config
    err: {
      "type": "TypeError",
      "message": "The \"listener\" argument must be of type function. Received an instance of Object",
      "stack":
          TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received an instance of Object
              at checkListener (node:events:270:3)
              at ClientRequest.once (node:events:651:3)
              at new ClientRequest (node:_http_client:244:10)
              at Object.request (node:https:366:10)
              at wl.request.<computed>.wl.request (file:///Users/sekhuat/Development/MyApp/api/extensions/subscription/dist/index.js?t=1710224454811:3:141215)
              at Issuer.request (/Users/sekhuat/Development/MyApp/api/node_modules/openid-client/lib/helpers/request.js:123:73)
              at Issuer.discover (/Users/sekhuat/Development/MyApp/api/node_modules/openid-client/lib/issuer.js:143:36)
              at file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/auth/drivers/openid.js:42:20
              at new Promise (<anonymous>)
              at new OpenIDAuthDriver (file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/auth/drivers/openid.js:41:23)
              at getProviderInstance (file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/auth.js:59:20)
              at file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/auth.js:44:26
              at Array.forEach (<anonymous>)
              at registerAuthProviders (file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/auth.js:33:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async createApp (file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/app.js:83:5)
              at async createServer (file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/server.js:22:38)
              at async Command.startServer (file:///Users/sekhuat/Development/MyApp/api/node_modules/@directus/api/dist/server.js:117:20)
              at async Command.parseAsync (/Users/sekhuat/Development/MyApp/api/node_modules/commander/lib/command.js:1015:5)
      "code": "ERR_INVALID_ARG_TYPE"
    }
```

However, if I disable the Auth Providers by comment off my Auth Providers setting in the .env file, I am able to start Directus without any issue.

### To Reproduce

* Upgrade from 10.9.3 to 10.10.3 as per normal
* With the following Auth Provider setting in .env file (I had replaced the client id, secret, domain and token as I can't disclose it at here.
```
AUTH_PROVIDERS="auth0"
AUTH_AUTH0_DRIVER="openid"
AUTH_AUTH0_CLIENT_ID="xxxxxxx"
AUTH_AUTH0_CLIENT_SECRET="xxxxxxxxxxxxxx"
AUTH_AUTH0_ISSUER_URL="https://zzzzz.us.auth0.com/.well-known/openid-configuration"
AUTH_AUTH0_DOMAIN="zzzzz.us.auth0.com"
AUTH_AUTH0_MANAGEMENTAPI_TOKEN="xxxxxxx the token xxxxxxx"
AUTH_AUTH0_MANAGEMENTAPI_URL="https://zzzzz.us.auth0.com/api/v2"
AUTH_AUTH0_IDENTIFIER_KEY="sub"
AUTH_AUTH0_ALLOW_PUBLIC_REGISTRATION=true
AUTH_AUTH0_DEFAULT_ROLE_ID="293e3266-4d0d-4551-a662-c22f7915282b"
AUTH_AUTH0_ICON="shield"
```
* Start Directus as usual and I will get the above mentioned error.

However, if I comment off the auth provider setting in the .env file, I can start Directus without any issue.

### Directus Version

10.9.3 to 10.10.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by joselcvarela** [comment] 2024-03-12 14:26
Hello @sekhuat 
I just tested this my self and I am not able to reproduce this issue.
It looks like the error is coming from one of your extensions. On the logs you post, here's the issue:
```
              at wl.request.<computed>.wl.request (file:///Users/sekhuat/Development/MyApp/api/extensions/subscription/dist/index.js?t=1710224454811:3:141215)
```

@paescuj I am not able to replicate. Should we close this one?

**Closed** 2024-03-12 14:34 UTC
