### ISSUE TITLE
Impossible to retrieve an item filters by content version with GraphQL

### ISSUE THREAD

**Issue by arthurju** [directus/directus#20521] opened 2023-11-24 15:56 UTC
### Describe the Bug

Hi Directus team,

I am trying to fetch a particular content version of an item inside a collection though graphQL.

According to the documentation you can do something like that : 
`query {
	about(version: "draft") {
		id
	}
}`

So I have tried with my collection "posts" and my version "facebook" : 
`query {	
	posts(version: "facebook")
	{
		id
	}
}`

And what I get is something like that : 
`{
	"errors": [
		{
			"message": "GraphQL validation error.",
			"extensions": {
				"code": "GRAPHQL_VALIDATION",
				"errors": [
					{
						"message": "Unknown argument \"version\" on field \"Query.posts\".",
						"locations": [
							{
								"line": 2,
								"column": 8
							}
						]
					}
				]
			}
		}
	]
}`

But when I try with a REST query I do not have any issue : 
`https://preprod.admin.international.la-croix.com/items/posts?version=facebook`
It results with 200 OK

### To Reproduce

1. Create a new collection "posts"
2. Enable content version on the "posts" collection
3. Create a item of this posts collection
4. Create a version named "facebook" of your post item
5. Apply this graphQL query : 
`query {	
	posts(version: "facebook")
	{
		id
	}
}`

### Directus Version

10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-11-24 15:58
Duplicate of #20367 not 100% exactly but the PR will address this same issue.

**Closed by br41nslug** 2023-11-24 15:58 UTC
