### ISSUE TITLE
Develop Branch doesn't show any Data

### ISSUE THREAD

**Issue by chrisbenjamin** [directus/directus#1822] opened 2017-09-16 17:45 UTC
Installed locally a fresh directus from the develop branch. I can add tables and add data into these tables, but I couldn't see any output (see screenshots)

## Version Info
Directus version and branch: develop-branch (today, 11:19 CET)
PHP version: 7.1.9
MySQL version: 5.0.11-dev
Web server: nginx/1.6.2
OS name and version: Debian GNU/Linux 8 (jessie)

## Expected Behavior
Show Tables and its outputs

## Actual Behavior
Nothing to see.

## Steps to Reproduce
1) install develop branch
2) create any table with simple field (e.g. varchar)
3) add content
4) show table 

## Schema Dump, Logs, or Screenshots
<img width="1168" alt="bildschirmfoto 2017-09-16 um 19 43 26" src="https://user-images.githubusercontent.com/569479/30514555-6c391cfc-9b17-11e7-8c74-f3106e10cf76.png">
<img width="1165" alt="bildschirmfoto 2017-09-16 um 19 43 36" src="https://user-images.githubusercontent.com/569479/30514554-6c36d9ec-9b17-11e7-91fc-77a5853de302.png">
<img width="1165" alt="bildschirmfoto 2017-09-16 um 19 43 50" src="https://user-images.githubusercontent.com/569479/30514553-6c33f1dc-9b17-11e7-939e-931fcb07f2a3.png">

**Comment by WellingGuzman** [comment] 2017-09-16 17:50
Not able to reproduce this, this is an odd behavior as the status interface is empty.
Do you have any error in the logs (browser)?
Does the record get inserted into the database?
Are you really using MySQL 5.0?

**Comment by WellingGuzman** [comment] 2017-09-16 17:51
Something to notice is that I'm using the schema you shared in #1817

**Comment by chrisbenjamin** [comment] 2017-09-16 17:57
@WellingGuzman I tried again to reproduce this with a new develop download. 
The error appears only, when you don't have a configuration.php. During the installation routine the script doesn't rename the sample file to configuration.php - After renaming it, it seems to work.

like in the prebuild release, the installation routine is buggy. I always have to import the schema.sql manually. Are you aware of that?

**Comment by WellingGuzman** [comment] 2017-09-16 18:04
We are not experiencing it or it hasn't been reported. Is using an old mysql version has to do with this? if you try to use a more recent mysql version does it works?

**Comment by chrisbenjamin** [comment] 2017-09-16 20:19
Next time I will check and will track all error messages in separate ticket.

**Comment by WellingGuzman** [comment] 2017-09-17 02:33
Thanks, closing this.

**Closed by WellingGuzman** 2017-09-17 02:33 UTC
Labels: Can Not Duplicate
