### ISSUE TITLE
Error incompatible alter table of M2O constraint in Mysql 8

### ISSUE THREAD

**Issue by khunsatant** [directus/directus#18300] opened 2023-04-23 03:59 UTC
### Describe the Bug

<pre>
{
  "errors": [
    {
      "message": "alter table `contact` modify `customer` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'customer' and referenced column 'id' in foreign key constraint 'contact_customer_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
</pre>

Related to this closed [#15785](https://github.com/directus/directus/issues/15785)
**it comes again when update to version: 9.25.2

Database: Mysql 8

### To Reproduce

Create M2O relation and try to update an interface or display of it.

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by M-GRV** [comment] 2023-04-28 16:49
https://github.com/directus/directus/issues/18247

Same issue as described above.

**Comment by M-GRV** [comment] 2023-04-28 16:55
This is only happening on mysql based dbs. I'm switching to postgres to check.

**Comment by vanling** [comment] 2023-05-11 21:52
Still happening in 10.0.1 when trying to edit the related values on m2o

```{
  "errors": [
    {
      "message": "alter table `xxxx_documentation` modify `category_id` int - UNKNOWN_CODE_PLEASE_REPORT: Referencing column 'category_id' and referenced column 'id' in foreign key constraint 'xxxx_documentation_category_id_foreign' are incompatible.",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}```

**Comment by licitdev** [comment] 2023-05-12 13:13
Duplicate of #18247

**Closed by licitdev** 2023-05-12 13:13 UTC
