### ISSUE TITLE
Stuck on Loading

### ISSUE THREAD

**Issue by Thomas-Blakeney** [directus/directus#15869] opened 2022-10-03 19:23 UTC
### Describe the Bug

Site stuck on loading when try to open the Admin Dashboard.

![CleanShot 2022-10-03 at 21 20 13](https://user-images.githubusercontent.com/72545889/193661186-c97f8e95-a6d7-4f86-97a3-c7622f0ff3a9.png)

### To Reproduce

Try to open the Dashboard after a while of using.

### Errors Shown

Uncaught SyntaxError: Invalid or unexpected token (at index.dfa694ae.entry.js:1:171618)

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

Docker

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Safari, Opera GX

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-10-04 04:11
This looks very similar to #10826 and #13226. Are you using Cloudflare CDN by any chance? If yes, can you try disabling it as mentioned by this comment: https://github.com/directus/directus/issues/10826#issuecomment-1004372023?

Closing this for now as it seems to be same issue at first glance, but will re-open if it turns out to not be the case and when more detailed reproduction steps are subsequently provided.

**Closed by azrikahar** 2022-10-04 04:11 UTC

**Comment by Thomas-Blakeney** [comment] 2022-10-04 06:38
Thank you, it works now!

**Comment by whyrnld** [comment] 2023-09-24 15:14
I solved it by disabling autominify for the cms domain, and also clearing the cache
