### ISSUE TITLE
Expand field options not working on small screen

### ISSUE THREAD

**Issue by joselcvarela** [directus/directus#8035] opened 2021-09-14 17:06 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When on small screen (width <960px), the create field options are not visible.

https://user-images.githubusercontent.com/14039341/133301485-b6521c0f-db47-4261-9bda-7ae4917fb206.mp4

### To Reproduce

1. Open a browser no larger than 960px
1. Go to Settings > Data Model > [Choose a Model] > Create (or edit) a field
1. Toggle arrow on top

### What version of Directus are you using?

9.0.0-rc.92 (2f319d4f2)

### What version of Node.js are you using?

v16.6.1

### What database are you using?

SQLite

### What browser are you using?

Edge

### What operating system are you using?

Windows

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment] 2021-09-15 08:42
Just to clarify, by "create field options", do you mean this (schema, relationship etc)?

![Jw06W4KI36](https://user-images.githubusercontent.com/42867097/133399503-a2389d0a-18d1-44e1-aa1e-73c1b181f5d7.gif)

and in case anyone else was wondering if the arrow for open/close changed (thought I was misremembering things haha), it did used to look like this:

![chrome_rqoYTjlwWv](https://user-images.githubusercontent.com/42867097/133400137-8a62762a-2bdf-415e-818a-26e65a87f7fa.png)

it was changed in #7972. So perhaps this is more of a UI/UX thing, unless I'm misunderstanding anything here.

With that said, I'd agree the action bar expand button probably shouldn't show up if there's no option available, regardless of whether the current menu is easily recognizable or not.

**Comment by benhaynes** [comment] 2021-09-15 12:32
> it was changed in #7972. So perhaps this is more of a UI/UX thing, unless I'm misunderstanding anything here.

This was my edit, I felt it was more consistent with the other places we're using dropdowns/accordions, but am down to discuss if this causes confusion, or how it could be improved.

**Comment by benhaynes** [comment] 2021-09-15 12:34
Also, I agree... we should not show the action button expand if there's nothing within it. 👍

**Comment by rijkvanzanten** [comment] 2021-09-15 14:28
Seems like it works as expected. We can keep discussing ways to optimize, but i'll close it as its not a bug 👍🏻

**Closed by rijkvanzanten** 2021-09-15 14:28 UTC
Labels: Question
