### ISSUE TITLE
Install with SqLite

### ISSUE THREAD

**Issue by GerhardMes** [directus/directus#3824] opened 2021-01-27 10:41 UTC
I tried to install a new project with SQLite (I know it is beta), but 

(1) first, as mentioned I included empty data.db in my folder, but 
  got:  [Error] Database is already installed - try again

(2) second, I deleted the data.db and tried to install, but
  got:  [Error] Sqlite does not support alter column.

Any advice - if my system did something wrong, or the install script. 
Would really like to test Directus, especially with the node support.
Cheers and thanks

**Comment by rijkvanzanten** [comment] 2021-01-27 15:01
Duplicate of https://github.com/directus/directus/issues/2904

**Closed by rijkvanzanten** 2021-01-27 15:01 UTC
