### ISSUE TITLE
REST API GET /policies returns duplicate content

### ISSUE THREAD

**Issue by pomeh** [directus/directus#23785] opened 2024-10-04 13:41 UTC
### Describe the Bug

REST API `GET /policies` returns a list of policies.

Each policy contains 2 properties: `users` and `roles`.

Problems are:

1. The value of these fields are always the same.
2. When creating a new policy (through JS SDK), having two distinct values leads to inconsistent behavior

### To Reproduce

# Steps

1. Start a fresh instance
2. Check `GET /policies` output
3. Go to [`public` policy page](http://localhost:8055/admin/settings/policies/abf8a154-5b1c-4a46-ac9c-7300570f4f17), add default admin user in user list and save changes
4. Check `GET /policies` output again 

# Expected output

1. N/A
2. public policy should be associated with public role only. By default, no user is associated with public policy
3. saves OK
4. public policy should now be associated with:
    - public role (key `roles` in JSON output) -> value **should NOT** be changed from step 2. above
    - administrator user (key `users` in JSON output) -> this value should be changed

# Got output

1. N/A

## Studio

![studio-no-user](https://github.com/user-attachments/assets/32ef44e1-acd8-4c6f-aebf-e3f556085761)

Note: public role is not listed, this is known bug https://github.com/directus/directus/issues/23257

2. :x: public policy has both keys `roles` and `users` set. Both properties have the exact same value

## api

![api-no-user](https://github.com/user-attachments/assets/435cbd05-ddfa-4c02-9ec0-7a072656a68d)

Note: I used `/policies?fields=*,roles.*,users.*&filter[id][_eq]=abf8a154-5b1c-4a46-ac9c-7300570f4f17` request URL for better output, but same behavior occurs without query params `/policies`.

## json

```json
{
  "data": [
    {
      "id": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
      "name": "$t:public_label",
      "icon": "public",
      "description": "$t:public_description",
      "ip_access": null,
      "enforce_tfa": false,
      "admin_access": false,
      "app_access": false,
      "permissions": [],
      "users": [
        // ❌❌❌ users key should be empty
        {
          "id": "cacabcb6-2fa2-4121-925c-d100068c4dec",
          "role": null,
          "user": null,
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": 1
        }
        // ❌❌❌
      ],
      "roles": [
        {
          "id": "cacabcb6-2fa2-4121-925c-d100068c4dec",
          "role": null,
          "user": null,
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": 1
        }
      ]
    }
  ]
}
```

3. ✅ saves OK

## Studio

![studio-with-user](https://github.com/user-attachments/assets/701eb032-7a0d-4390-b497-df1cdf80af55)

4. :x: both both keys `roles` and `users` are modified

![api-with-user](https://github.com/user-attachments/assets/5073ef98-0e66-4972-be33-7e7af367eb7f)

## json

```json
{
  "data": [
    {
      "id": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
      "name": "$t:public_label",
      "icon": "public",
      "description": "$t:public_description",
      "ip_access": null,
      "enforce_tfa": false,
      "admin_access": false,
      "app_access": false,
      "permissions": [],
      "users": [
        {
          "id": "cacabcb6-2fa2-4121-925c-d100068c4dec",
          "role": null,
          "user": null,
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": 1
        },
        // ✅✅✅ new value added
        {
          "id": "76baa576-c56c-4075-a999-71fd5927295b",
          "role": null,
          "user": "99e63779-5603-4719-9ed1-59904124e843",
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": null
        }
        // ✅✅✅
      ],
      "roles": [
        {
          "id": "cacabcb6-2fa2-4121-925c-d100068c4dec",
          "role": null,
          "user": null,
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": 1
        },
        // ❌❌❌ new value added
        {
          "id": "76baa576-c56c-4075-a999-71fd5927295b",
          "role": null,
          "user": "99e63779-5603-4719-9ed1-59904124e843",
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": null
        }
        // ❌❌❌
      ]
    }
  ]
}
```

User `"99e63779-5603-4719-9ed1-59904124e843"` is my admin user's uuid.

The ouput should have only 1 role and 1 user, like this:

```json

      "users": [
        // 👇👇👇 admin user only 
        {
          "id": "76baa576-c56c-4075-a999-71fd5927295b",
          "role": null,
          "user": "99e63779-5603-4719-9ed1-59904124e843",
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": null
        }
      ],
      "roles": [
        // 👇👇👇 public role only 
        {
          "id": "cacabcb6-2fa2-4121-925c-d100068c4dec",
          "role": null,
          "user": null,
          "policy": "abf8a154-5b1c-4a46-ac9c-7300570f4f17",
          "sort": 1
        }
      ]
```

# Update

Last but not least, I've seen a related problem using `POST /policies` endpoint.

If the payload contains both keys `roles` and `users` with **exact same values**, the link policy<->role and/or policy<->user is/are created accordingly.

If one key is set and the other one not defined at all, it works OK too.

But, if one key is set and the other one is empty array `[]`, then link policy<->role/user IS NOT created at all.

### Directus Version

v11.1.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

**Comment by elaminm2003** [comment] 2024-10-06 02:28
@pomeh I want to work on this issue. can you please assign it to me

**Comment by pomeh** [comment] 2024-10-07 08:42
@elaminm2003 thanks for this proposal, but I'm not a directus maintainer and I have no permissions to assign an issue.

But I guess you can still start to look into the source for how to fix this, open a Pull Request whenever you're done and link it to this issue.

**Comment by hanneskuettner** [comment] 2024-10-18 12:36
This issue has to do with the way the connection between policies and users/roles are stored. We utilize the `directus_access` table, that is the junction table to two M2M relations. If `directus_access.user` is set then it is a junction item for the `directus_policies` <-> `directus_users` relation and if `directus_access.role` is set then it is a junction item for the `directus_policies` <-> `directus_roles`. <br><br>This setup is fairly unique and it seems like this has surfaced a bug deep within the SQL query crafting logic, that does not account for this scenario, where multiple M2M relations share a single junction table. The whole policy / permissions engine has not been impacted by it, because those queries are hand-crafted and do not rely on the automatic SQL query generation.

**Comment by ilseva** [comment] 2024-10-21 15:34
I have a similar problem when I try to create a policy using ReST API.
With a payload like this
```json
{
	"name": "<policy_name>",
	"icon": "verified_user",
	"description": "<policy_description>",
	"admin_access": false,
	"app_access": false,
	"users": ["<user_uuid>"]
}
```
the POST /policies return a 403 error and in the log I found this query
```sql
select `id`, `policy` from `directus_access` where `id` = ? limit ? [<user_uuid>, 1]
```
After that it throw the exception.
I tried to set `users` and `roles` with the same value as suggested, but I received always the 403 error.

**Comment by hanneskuettner** [comment] 2024-10-21 15:41
> I have a similar problem when I try to create a policy using ReST API.

The problem you're facing is that `users` isn't really expecting user UUIDs, but instead there is a junction table in between called `directus_access`. So in order to connect the user your payload needs to look like this:

```json
{
	"name": "<policy_name>",
	"icon": "verified_user",
	"description": "<policy_description>",
	"admin_access": false,
	"app_access": false,
	"users": { "create": [{"user": "<user-id>"}] }
}
```

**Comment by ilseva** [comment] 2024-10-21 15:45
> > I have a similar problem when I try to create a policy using ReST API.
> 
> The problem you're facing is that `users` isn't really expecting user UUIDs, but instead there is a junction table in between called `directus_access`. So in order to connect the user your payload needs to look like this:
> 
> ```json
> {
> 	"name": "<policy_name>",
> 	"icon": "verified_user",
> 	"description": "<policy_description>",
> 	"admin_access": false,
> 	"app_access": false,
> 	"users": { "create": [{"user": "<user-id>"}] }
> }
> ```

thanks!
but fix the docs... :-)
https://docs.directus.io/reference/system/policies.html#the-policy-object

**Comment by ilseva** [comment] 2024-10-21 16:18
> Do you mind telling us what needs to be updated, or even create a quick issue for it? To me the info looks accurate at first glance

this is the example in the policies docs page
```json
{
	"id": "653925a9-970e-487a-bfc0-ab6c96affcdc",
	"name": "Admin",
	"icon": "supervised_user_circle",
	"description": null,
	"ip_access": null,
	"enforce_tfa": false,
	"admin_access": true,
	"app_access": true,
	"users": ["0bc7b36a-9ba9-4ce0-83f0-0a526f354e07"],
	"roles": ["8b4474c0-288d-4bb8-b62e-8330646bb6aa"],
	"permissions": ["5c74c86f-cab0-4b14-a3c4-cd4f2363e826"]
}
```
it seems that the `users` property should be an array.
The link to the "access" page return 404.
I will open an issue.
Thanks for support.

**Comment by pomeh** [comment] 2024-10-21 16:20
To my understanding, there are a few problems here:

1. the `users` key is not a list of **users' uuid** (`"users": ["<user_uuid>"]`), but rather a list of **`directus_access`'s uuid**. I was getting totally crazy before I understood this 🤣
2. in the doc example, having something like `"users": ["0bc7b36a-9ba9-4ce0-83f0-0a526f354e07"]` is very confusing as you might think its a user's uuid, while it's not, and the docs are not really explicit about this IMHO. There is the phrase `It expects and returns data from the directus_access collection.` but I understood it after having trouble like @ilseva had
3. the syntax `"users": { "create": [{"user": "<user-id>"}] }` is not documented, while it's the syntax used by the studio. I've search on other page like "global REST architecturing" or [global query](https://docs.directus.io/reference/query.html) etc. but I never found this kind of syntax
4. the syntax `"users": { "create": [{"user": "<user-id>"}] }` can only be used for creating/updating content, but it's not what the format returned by the GET endpoint
5. you can create using the syntax I mentioned in my initial post `"users":  { "id": "<new_directus_access_uuid>", "role": null, "user": "<existing_directus_user_uuid>", "policy": "existing_directus_policy_uuid", "sort": 1 }`, but this is not documented

The same 5 points applies to both `users` key and `roles` key.

**Comment by pomeh** [comment] 2024-10-21 16:22
>  The link to the "access" page return 404.

@ilseva I already logged an issue for this specific point: https://github.com/directus/directus/issues/23782

**Comment by hjopel** [comment] 2024-11-13 12:13
Hi everyone, following the thread in the discord channel (https://discord.com/channels/725371605378924594/1306218917584441375) I'll add more context to this issue:

I'm experiencing an issue with the policy management in Directus where updating roles affects the user assignments unexpectedly, which seems related to how directus_access functions as a junction table for policies, users, and roles.

Here’s the sequence:

1. I created a new policy and assigned it directly to a single user, without associating it with any role. directus_access accurately reflects this:

![image](https://github.com/user-attachments/assets/a007bce7-de66-4177-8c58-9e2a5edf50d8)

2. Fetching the policy after this returns policies and users with the same value (as discussed above already).

3. When I update the policy and set roles to an empty array via an api call, it also removes the policy from users — even though the user was directly assigned and roles were initially empty:

![image](https://github.com/user-attachments/assets/da8105c7-ff6c-42f5-bc96-d71350acec90)

4. The database doesn't contain the entry mapping the policy to the user anymore:

![image](https://github.com/user-attachments/assets/2f8764bd-0bbb-4ab7-8f41-4f16bfa2f90b)




4..  This is more than an API response issue. The DB accurately reflects the initial assignment to the user, but after updating via API, the user association is removed from the database, too.

This behavior makes direct assignments to individual users unreliable when using the API to update policy roles.

**Comment by pomeh** [comment] 2024-11-15 14:36
Hello @hjopel, thanks for this detailed report :)

I also noticed this bug regarding policy object update API. I tried to explain this bug in [my initial comment](https://github.com/directus/directus/issues/23785#issue-2566410702), under the `Update` section at the end. I also found a possible workaround for now, which consist of **always setting the same value** for both keys `roles` and `users`.

To get further, your post made me wonder: **how does the Directus studio do to perform such update ?** (add one user or add one role).

I tried it and it turns the studio uses a different, undocumented syntax, which [I was talking earlier too](https://github.com/directus/directus/issues/23785#issuecomment-2427140050).

So @hjopel a second workaround for your problem may be to use this undocumented syntax (with all the uncertainties it comes with):

```js
// policy id = a1179bcb-8a68-4680-be12-3073592d95b6
// role id = 7f5a57f6-86f7-4b32-93ce-e94c14fc8a85

await fetch("http://localhost:8055/policies/a1179bcb-8a68-4680-be12-3073592d95b6", {
    "method": "PATCH",
    "headers": {
        "Content-Type": "application/json",
    },
    "body": JSON.stringify({
      "roles": {
        "create": [
          {
            "policy": "a1179bcb-8a68-4680-be12-3073592d95b6",
            "role": {
              "id": "7f5a57f6-86f7-4b32-93ce-e94c14fc8a85"
            }
          }
        ],
        "update": [],
        "delete": []
      }
    }),
});
```

**Closed** 2024-12-02 09:51 UTC
Labels: Bug, ⚠️ Enterprise, Querying

**Comment by licitdev** [comment] 2024-12-16 16:44
The patch from https://github.com/directus/directus/pull/23879 has been reverted in [v11.3.3](https://github.com/directus/directus/releases/tag/v11.3.3).

Kindly use `deep` filtering instead.
`/policies?deep[roles][_filter][role][_nnull]=true&deep[users][_filter][user][_nnull]=true`

**Comment by hjopel** [comment] 2024-12-17 08:17
@licitdev is a more permanent fix planned? deep filtering is nice and all, but it'd be good if the "normal" endpoint actually worked properly

**Comment by licitdev** [comment] 2024-12-17 16:49
@hjopel No change is planned at this time. The endpoint is working as intended based on the current data structure, where the foreign key is reused. Deep filtering is the recommended approach to achieve the desired results. We'll keep this feedback in mind as we evaluate future improvements.

**Comment by hjopel** [comment] 2024-12-18 08:08
> Hi everyone, following the thread in the discord channel (https://discord.com/channels/725371605378924594/1306218917584441375) I'll add more context to this issue:
> 
> I'm experiencing an issue with the policy management in Directus where updating roles affects the user assignments unexpectedly, which seems related to how directus_access functions as a junction table for policies, users, and roles.
> 
> Here’s the sequence:
> 
> 1. I created a new policy and assigned it directly to a single user, without associating it with any role. directus_access accurately reflects this:
> 
> ![image](https://private-user-images.githubusercontent.com/70332133/385750846-a007bce7-de66-4177-8c58-9e2a5edf50d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDk0NzQsIm5iZiI6MTczNDUwOTE3NCwicGF0aCI6Ii83MDMzMjEzMy8zODU3NTA4NDYtYTAwN2JjZTctZGU2Ni00MTc3LThjNTgtOWUyYTVlZGY1MGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA4MDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NzljNzA1ZGMzYjkzMDE4Yjc1ZDUzMTlkODlmMWE1YTFmZGNiZWUwZDI4ODQ3OTA5ZGNiMDJkZTY3NmJlMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vuhr1Y5U-yCLNOAAIGtKNdMqjkQd46J_Y7YQkJYec2A)
> 
> 2. Fetching the policy after this returns policies and users with the same value (as discussed above already).
> 3. When I update the policy and set roles to an empty array via an api call, it also removes the policy from users — even though the user was directly assigned and roles were initially empty:
> 
> ![image](https://private-user-images.githubusercontent.com/70332133/385751293-da8105c7-ff6c-42f5-bc96-d71350acec90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDk0NzQsIm5iZiI6MTczNDUwOTE3NCwicGF0aCI6Ii83MDMzMjEzMy8zODU3NTEyOTMtZGE4MTA1YzctZmY2Yy00MmY1LWJjOTYtZDcxMzUwYWNlYzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA4MDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDgzY2EwN2JhOThhNjdlMmRiMzRkNTk4YTZiZDUxOWZkYTFjZmZmZTBlOGE1ODM0ODBjNGFmYzcwMzJlOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r3bRSn5ZLMFlNQFmLXX2lfLRpuNTtvJXbgZDczFcEqI)
> 
> 4. The database doesn't contain the entry mapping the policy to the user anymore:
> 
> ![image](https://private-user-images.githubusercontent.com/70332133/385751509-2f8764bd-0bbb-4ab7-8f41-4f16bfa2f90b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MDk0NzQsIm5iZiI6MTczNDUwOTE3NCwicGF0aCI6Ii83MDMzMjEzMy8zODU3NTE1MDktMmY4NzY0YmQtMGJiYi00YWI3LThmNDEtNGYxNmJmYTJmOTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA4MDYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljMmQ3YzUzZGJkYzE5NWYyYzFiNzdlNjQ2MjdjZDZjMWNlNjNlN2ZkOGQxM2UzYTJmZmY5OWMyZTk2ZWY0N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aaX2wx0lTOwhJo-RX0R3JxL616CDugeetv9SI0ifwe8)
> 
> 4.. This is more than an API response issue. The DB accurately reflects the initial assignment to the user, but after updating via API, the user association is removed from the database, too.
> 
> This behavior makes direct assignments to individual users unreliable when using the API to update policy roles.

@licitdev ok thanks, got it. how would you suggest to go about this issue then?
