### ISSUE TITLE
Fresh CLI install does not let me log in

### ISSUE THREAD

**Issue by keesvanbemmel** [directus/directus#4532] opened 2021-03-14 14:23 UTC
Hi team,

This should be fairly easy to reproduce as I tried it multiple times now.

I'm running this with Node v14.15.4, directus in package-lock shows `9.0.0-rc.50`

Follow the steps from your documentation for installing through CLI: https://docs.directus.io/guides/installation/cli/
Pick SQLite as DB.

After install and starting, I can't log in with the user I added in the CLI. The network console shows me 400, the UI shows me "Unexpected Error". The response of this endpoint: `http://localhost:8055/auth/login` shows me:
```{"errors":[{"message":"Invalid foreign key.","extensions":{"code":"INVALID_FOREIGN_KEY"}}]}```

What am I missing?

**Comment by rijkvanzanten** [comment] 2021-03-14 16:28
Duplicate of https://github.com/directus/directus/issues/4489

**Closed by rijkvanzanten** 2021-03-14 16:28 UTC
