### ISSUE TITLE
Obtaining relational information from he directus_users table is not working anymore

### ISSUE THREAD

**Issue by drnachio** [directus/directus#20501] opened 2023-11-22 14:09 UTC
### Describe the Bug

All queries via SDK or API Rest obtaining information related to the directus_users table (for example consulting the first name of the user who created a record) have stopped working since the update to version 10.8.1

### To Reproduce

Attempt to perform any query that obtains data about the user who modified or created a record in a table.

### Directus Version

10.8.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-11-22 14:17
Please double check your permissions and/or elaborate on the reproduction steps (and directus setup involved).

I am unable to reproduce this by just querying related data:
![image](https://github.com/directus/directus/assets/9389634/68130d2d-126b-4afd-8f67-7ce0c7dca276)
![image](https://github.com/directus/directus/assets/9389634/dcb96237-a9ca-4176-91ef-593b1c4601f4)

Closing the issue for now but happy to re-open it if more information becomes available to reproduce the issue :smile:

**Closed by br41nslug** 2023-11-22 14:17 UTC
Labels: Needs More Info

**Comment by drnachio** [comment] 2023-11-22 14:27
Wow... not the same result in any of my upgraded projects and tables.

This works:

<img width="964" alt="image" src="https://github.com/directus/directus/assets/5763165/b6de9124-67b9-479e-a0f7-d6c906244b97">

But this do not work:

<img width="961" alt="image" src="https://github.com/directus/directus/assets/5763165/bfb4339c-552d-4684-ac25-76d8369bab25">

Or any other field:

<img width="962" alt="image" src="https://github.com/directus/directus/assets/5763165/6b6d42fb-e665-45b1-bec3-0c2cf48ee57d">

The auth token used in the request have all read permissions on table directus_users.

**Comment by br41nslug** [comment] 2023-11-22 14:29
By default read permissions are limited to only your own user/role for any non-admin users. Did you broaden those default app permissions?

https://github.com/directus/directus/issues/20492#issuecomment-1820862724

**Comment by drnachio** [comment] 2023-11-22 14:30
The exact same query was woking on the previous versions.

**Comment by drnachio** [comment] 2023-11-22 14:30
> By default read permissions are limited to only your own user/role for any non-admin users. Did you broaden those default app permissions?
> 
> [#20492 (comment)](https://github.com/directus/directus/issues/20492#issuecomment-1820862724)

Yes

**Comment by drnachio** [comment] 2023-11-22 14:32
I think that this one will be related: https://github.com/directus/directus/issues/20496

**Comment by br41nslug** [comment] 2023-11-22 14:35
> I think that this one will be related: https://github.com/directus/directus/issues/20496

Correct that one likely has the same default permission root cause.

**Comment by drnachio** [comment] 2023-11-22 14:37
Thx a lot!

This made the tick:

<img width="672" alt="image" src="https://github.com/directus/directus/assets/5763165/36d77095-cc65-4ccc-bdf1-71a0201a5ad4">

**Comment by drnachio** [comment] 2023-11-22 14:38
It is obtaining the user information now.
