### ISSUE TITLE
Broken backward compatibility to the system collection directus_users

### ISSUE THREAD

**Issue by ncxx23** [directus/directus#17377] opened 2023-02-02 14:06 UTC
### Describe the Bug

After upgrading to 9.22.4, all m2m fields referring to the system directus_user collection start generating errors when interacting with items in field.
It looks like in new version used another way to accessing to the junction collection and this relations broke (auto generated Id changed to UIID)

9.22.4: https://host/items/vacancies_directus_users_1/d6abef43-fcd1-12gh-a2d0-0345a1bff318
9.22.1: https://host/items/vacancies_directus_users_1/43?fields=*,directus_users_id.*

### To Reproduce

Update to 9.22.4
Create field with m2m collection to directus_users
Add some user to this field and click on this element.

### Errors Shown

{
  "errors": [
    {
      "message": "You don't have permission to access this.",
      "extensions": {
        "code": "FORBIDDEN"
      }
    }
  ]
}
![Screenshot 2023-02-02 at 16 02 22](https://user-images.githubusercontent.com/124268186/216345644-4b27778d-9f81-4001-a7d5-78cbad899ba0.png)

### What version of Directus are you using?

9.22.4 \ 9.22.1

### What version of Node.js are you using?

Postgres: 15.1

### What database are you using?

Postgres: 15.1

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2023-02-02 14:16
Duplicate of #17108. It definitely makes sense for it to have worked in `9.22.1` as the bug was unfortunately a regression introduced by #16700 in `9.22.2` 👍

**Closed by azrikahar** 2023-02-02 14:16 UTC
