### ISSUE TITLE
Wrong value of email field during edit user process

### ISSUE THREAD

**Issue by sidartaveloso** [directus/directus#4786] opened 2021-03-31 15:45 UTC
On **User Directory**, when I click to edit some user, the value of field **email** is defined with my own email.

![image](https://user-images.githubusercontent.com/144222/113172537-e266e380-921e-11eb-95bd-0cf96dbe4521.png)

---

### Project details
Directus Version: 9.0.0-rc.28
Environment: production
OS: Linux 5.4.0-66-generic
Node: 14.15.3

**Comment by rijkvanzanten** [comment] 2021-03-31 15:49
@sidartaveloso Could this be your password managed autofilling the value? I noticed that the password field has that blue auto-fill style 🤔

**Comment by benhaynes** [comment] 2021-03-31 18:49
I can not reproduce this — and the following leads me to believe this is a password manager autofilling:
* Blue background and "unlock" in password field
* Save button is activated

This is also very far behind master (the latest release), which would show us if the value was updated with the new badge. For the reasons above, I'll close this. OP can check the above and reopen as needed.

**Closed by benhaynes** 2021-03-31 18:49 UTC
Labels: App, Bug (Potential), Good First Issue

**Comment by sidartaveloso** [comment] 2021-03-31 18:55
> @sidartaveloso Could this be your password managed autofilling the value? I noticed that the password field has that blue auto-fill style

@rijkvanzanten In fact, both fields have the blue auto-fill style. So, you are right, I confirmed with other tests that auto-fill are changing the email and password during the edition.

![image](https://user-images.githubusercontent.com/144222/113196055-6e860480-9239-11eb-9193-cf9d4503c4e7.png)
