### ISSUE TITLE
SDK : TS conflict with VueJS and Preact

### ISSUE THREAD

**Issue by pierre-H** [directus/directus#13615] opened 2022-05-30 07:53 UTC
### Describe the Bug

Since the SDK includes the shared package which itself includes vuejs, there is a confilct in the definition of `VNode` with preact.

`Type 'VNodeNormalizedRefAtom' is not assignable to tyoe 'Ref<any> | null | undefined'`

In the file `node_modules\@vue\runtime-core\dist\runtime-core.d.ts` , the interface `VNode` is declared with `ref: VNodeNormalizedRef | null;`. 
In the file `node_modules\preact\src\internal.d.ts`, the interface `VNode` is declared with `ref?: Ref<any> | null;`.

Why the JS SDK requires VueJS ?
According to me, it should not depend on a specific UI framework/library.

### To Reproduce

Create a project with preact and the JS SDK.

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

17.4.0

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

locally

**Comment by br41nslug** [comment] 2022-05-30 08:20
Duplicate of #13049

**Closed by br41nslug** 2022-05-30 08:20 UTC
Labels: Duplicate

**Comment by piotr-cz** [comment] 2022-07-04 14:06
Try redeclaring `VNode`:

```jsonc
// tsconfig.json
{
  //...
  "include": [
    "src",
    "types"
  ],
}
```

```ts
// types/preact.d.ts
import 'preact'

declare global {
  namespace JSX {
    export type VNode = preact.VNode
  }
}
```

I'm not sure if this is how it should be done, but it works
