### ISSUE TITLE
Unable to create new user via api

### ISSUE THREAD

**Issue by IamRewt** [directus/directus#22826] opened 2024-06-23 18:41 UTC
### Describe the Bug

When attempting to POST a new user to the api, a 200 OK response is returned with a list of all directus users, as if I had sent a GET request.

### To Reproduce

POST /users
`{
    "first_name": "Api",
    "last_name": "Made",
    "email": "admin@example.com",
    "password": "test"
}`

### Directus Version

11 rc2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgresql 15

**Comment by hanneskuettner** [comment] 2024-06-24 06:20
Heya! First of all, thank you for reporting this issue.

Do you mind sharing a more information?  I'm trying to reproduce this on my end, but I'm seeing the expected results.

A few things we can try to find the cause:

1. Have you made sure that you are *really* sending a POST request? (sorry if I'm asking something this obvious, but maybe you see where I'm coming from if you get the result for `GET /users`)
2. Are you an authenticated user or a public user?
3. Do you have any custom permissions/policies configured for the user you're using to interact with the API?
4. Can you share the relevant entry from `GET /permissions/me` that applies to `directus_users` of the user you're using to interact with the API?

**Comment by IamRewt** [comment] 2024-06-24 14:02
> Heya! First of all, thank you for reporting this issue.
> 
> Do you mind sharing a more information? I'm trying to reproduce this on my end, but I'm seeing the expected results.
> 
> A few things we can try to find the cause:
> 
> 1. Have you made sure that you are _really_ sending a POST request? (sorry if I'm asking something this obvious, but maybe you see where I'm coming from if you get the result for `GET /users`)
> 2. Are you an authenticated user or a public user?
> 3. Do you have any custom permissions/policies configured for the user you're using to interact with the API?
> 4. Can you share the relevant entry from `GET /permissions/me` that applies to `directus_users` of the user you're using to interact with the API?

1) Yes, i am certain that I am sending a post, using postman. 

2) This is an authenticated user.

3) No, this is an administrator user.

4) As it’s an administrator user, it has all access to all things.

Additionally, I did verify that I can post and patch to other collections just fine. I also copied the request content and test on the latest v10 version and it works as expected, it’s only v11 rc2 that I cannot post users too.

**Comment by hanneskuettner** [comment] 2024-06-24 14:12
Is this on a production database or would you be willing to share a SQL dump of you Postgres DB, so I can look into it locally? 

If you don't want to share it here on Github you can send it to me at hannes[at]directus.io

Do you have server logs available and can verify there that the request shows up as a POST request there as well? It should show up as `[16:11:00] POST /users 200 63ms` in the logs.

**Comment by IamRewt** [comment] 2024-06-24 14:31
Yes getting a list of all users like it’s a get request to the users endpoint without any id.

I can share that data privately later tonight.

**Comment by IamRewt** [comment] 2024-06-24 20:29
This is what is being sent via postman:
`POST /users HTTP/1.1
Host: <base address>
Content-Type: application/json
Authorization: ••••••
Content-Length: 292

{
    "first_name": "Api",
    "last_name": "Made",
    "email": "admin@example.com",
    "password": "test",
    "role": "3292e381-ccd0-4dc8-a472-22e6b38c1117",
    "policies": [
        "3deffd7c-579c-4d5e-be49-547648a4a7e0",
        "3fabe924-918f-421d-84d5-f8447348e9f0"
    ]
}`

In my container logs, it is coming in as a get request.

`[16:22:15] GET /users 200 18ms`

But when I change the base address to that of my instance running 10.12.1, it comes through as a post request and creates the user.

**Comment by hanneskuettner** [comment] 2024-06-24 21:04
Is there anything special about your setup? Does the v11 instance run with any Webserver in between or something along those lines? Because I the server receives the request as a get, I would expect that result. 

Can you try copying the request as a curl request from postman like [this](https://stackoverflow.com/a/49433083) and see if that changes things for you?

**Comment by IamRewt** [comment] 2024-06-24 21:12
I've tried with and without roles and policies attached to the object and it's the same each time.

There is nothing special about the v11 instance, it's just your docker image retrieved from docker hub. The db is postgres 15, and there is nothing custom about it either. It's a fresh instance as well, it was not upgraded from v10.

Here is the request as curl:

```
curl --location '<base address>/users' \
--header 'Content-Type: application/json' \
--header 'Authorization: ••••••' \
--data-raw '{
    "first_name": "Api",
    "last_name": "Made",
    "email": "admin@example.com",
    "password": "test",
    "role": "3292e381-ccd0-4dc8-a472-22e6b38c1117"
}'
```

**Comment by hanneskuettner** [comment] 2024-06-24 21:23
Thank you for the info. Let's see if we can get to the bottom of this, cause I'm still seeing the correct behavior on my end, with a Postgres 15 database and an image straight from docker hub.

Can you confirm that this also happens if you run a local instance with a SQLite database, run straight from the terminal, with `docker run -p 8058:8055 directus/directus:11.0.0-rc.2`? (You will have to manually log in, the password is printed to the terminal when launching the instance for the first time).

Also, just to confirm again, the setup between the v10 and v11 is identical? Nothing fancy like a proxy going on?

**Comment by IamRewt** [comment] 2024-06-24 21:40
Ok this led me down a weird path of discovery. 

I do have nginx running as a reverse proxy, so I decided to test both the v10 and v11 instances with the local ip address instead of the domain to bypass nginx.

On v10, the request works fine with and without a role id.

On v11, if I have a role id attached to the user, it gives a 403 error.
Without a role id, I can create a user.
I am using role ids specific to each instance, not the same id.

So still something going wrong there on multiple fronts.
a) nginx seems to be having some disagreement with v11 that it doesn't have with v10.
b) there seems to be something weird going on with permissions on v11 preventing adding a user with a role id included.

Just to note, both on v10 and v11 I'm using an administrator user to post this, so there shouldn't be any issue there.

**Comment by hanneskuettner** [comment] 2024-06-25 04:40
Some interesting discoveries indeed! 🤔 Thank you for following along and providing this info!

Does the 403 give you any more information in the error message? If it is a permissions related thing it should give you more info on why the request failed, eg. if you don't have permission to a field (definitely shouldn't be the case as you are an admin user). 

And just to confirm both nginx instances are configured identically? Mind sharing that config, to see if I have any look reproducing it with that?

**Comment by hanneskuettner** [comment] 2024-06-28 08:42
Any updates from your end? I will close the issue for now but I'm happy to reopen once we have more info to go on.

**Closed by hanneskuettner** 2024-06-28 08:42 UTC
Labels: :detective: Needs More Info, :star2: V11 RC

**Comment by IamRewt** [comment] 2024-06-28 16:51
> Any updates from your end? I will close the issue for now but I'm happy to reopen once we have more info to go on.

No real updates on my end, I setup an instance on a raspberry pi and it worked as expected. I figured at this point I'll wait and see what happens with the next docker release, maybe it'll be fixed?

My nginx instances are identical, and there is no caching or anything of that nature, honestly not sure what it could be.
