### ISSUE TITLE
Not able to move fields inside fieldgroups anymore

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#12631] opened 2022-04-08 09:55 UTC
### Describe the Bug

I am not able to move fields inside to fieldgroups anymore.

### To Reproduce

Create a "detail group" and try to place a field into it.

<img width="1680" alt="grafik" src="https://user-images.githubusercontent.com/8351587/162412514-6c403c84-938d-45cf-a064-bf3f3434e9a5.png">

### Errors Shown

<img width="1680" alt="grafik" src="https://user-images.githubusercontent.com/8351587/162412570-dc1164fa-231a-47b6-920d-69563d6cbd4a.png">

{
  "errors": [
    {
      "message": "update `directus_fields` set `collection` = 'settings', `field` = 'favicon', `sort` = 1, `group` = 'logo_favicon' where `id` in (482) - ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect integer value: 'logo_favicon' for column `bluoverda`.`directus_fields`.`group` at row 1",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### What version of Directus are you using?

9.8.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

mariadb

### What browser are you using?

Firefox

### How are you deploying Directus?

Paas

**Comment by azrikahar** [comment] 2022-04-08 10:25
I assume this is an upgrade from a rather old version? This seems to be a duplicate of #8675 with the same error, and I can't reproduce it on my end:

https://user-images.githubusercontent.com/42867097/162417524-96aa9cfe-ee17-4e87-ac76-06a288467d75.mp4

In the same issue, you can try the steps outlined [here](https://github.com/directus/directus/issues/8675#issuecomment-940629829) with another elaboration [here](https://github.com/directus/directus/issues/8675#issuecomment-940940506) to try and resolve this. If the issue still persists after doing the solution mentioned in the rc.96 release note, we can reopen this issue 👍

**Closed by azrikahar** 2022-04-08 10:25 UTC
Labels: Bug (Potential)
