### ISSUE TITLE
9.23.0 is not available on npm

### ISSUE THREAD

**Issue by gramakri** [directus/directus#17660] opened 2023-03-01 09:15 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

The latest version 9.23.0 is not available on npm . 9.22.4 is the latest version. Please see https://www.npmjs.com/package/directus?activeTab=versions 

### To Reproduce

`npm install directus@9.23.0` does not work.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for directus@9.23.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-03-01T09_09_16_593Z-debug-0.log
```

### Hosting Strategy

Self-Hosted (Custom)

**Comment by paescuj** [comment] 2023-03-01 09:17
Duplicate of #17653

**Closed by paescuj** 2023-03-01 09:17 UTC

**Comment by gramakri** [comment] 2023-03-01 09:19
Err.. shame on me, for not finding the existing report . Thanks for the fix!
