### ISSUE TITLE
Group will not get Hidden on Detail on Conditions when inside an accordion 

### ISSUE THREAD

**Issue by Pachat** [directus/directus#14384] opened 2022-07-12 04:15 UTC
### Describe the Bug

What we want is hide under conditions a group that is inside an an accordion.
_(Works when the group is out of the accordion,but not when inside)_

### To Reproduce

1. On a collection, create an accordion field and inside the accordion a group with an input field
2. Edit the group and add a condition  (for instance `ID isn't Null`) for `Hidden on Detail`

### Errors Shown

The group is still visible

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

12.22.12

### What database are you using?

PostgreSQL 14.2

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

VPS

**Comment by azrikahar** [comment] 2022-07-12 07:13
Granted I was not able to reproduce this with nesting **detail group** in the accordion:

https://user-images.githubusercontent.com/42867097/178430164-64ceb122-94f9-4c2e-a8af-7c79a293d38d.mp4

Both nested **raw group** and **accordion group** aren't visible at all due to #14349. As for any other condition related issue, it is likely due to #14285 instead. 

With the above points in mind, I'll close this for now in favor of tracking things in their separate issue as I believe they share the same root cause. We'll re-open if that's not the case.

**Closed** 2022-07-12 07:13 UTC
Labels: Duplicate
