### ISSUE TITLE
When adding a new entry to a O2M list, the sort field is not populated

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#10657] opened 2021-12-23 12:42 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a collection that has a O2M relationship to another collection.
When I use the "Create New" functionality and save it, the "sort" field is not populated, even though it's inserted in the list.
This is only updated once I move the field around.
I would assume that when I have the "sort" field set on the relationship, it should automatically be set as the latest sort ID.

https://user-images.githubusercontent.com/9347206/147241697-3b9e9483-25ff-401f-bf4b-655cc8866136.mov

### To Reproduce

Create a new entry in a O2M list, the sort order is not respected because the "sort" field is not filled.

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by HitomiTenshi** [comment] 2021-12-23 13:17
May be related to: #6111

**Comment by rijkvanzanten** [comment] 2021-12-25 01:37
Duplicate of #6111

**Closed by rijkvanzanten** 2021-12-25 01:37 UTC
Labels: Bug (Potential)
