### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Wulfheart** [directus/directus#2241] opened 2018-11-12 21:23 UTC
Hello,

I've been doing the instruction step-by-step.
1. Cloning the git repository
2. Set document root to the `/public` directory
3. Navigate your browser to the App at `/admin`
=> Error message `Couldn't reach API`
I read that maybe the custom setup would work. Long story short: It doesn't.
Furthermore the link is: `https://directus.domain.com/admin/#/login` according to the docs the `#` should be an `_`.
Any ideas how to fix this?

Greetings

**Comment by shealavington** [comment] 2018-11-12 23:05
> 3\. I read that maybe the custom setup would work. Long story short: It doesn't.

Kinda need the long-story, so we know what you've tried and what you haven't, what you've written is rather vague.


> Furthermore the link is: `https://directus.domain.com/admin/#/login` according to the docs the `#` should be an `_`.

You're confusing the APP with the API there, as you're on the /admin, you're in the GUI interface and the # is Vue's way of dealing with URLs, the underscore is used for the API and reaching endpoints.

**Comment by rijkvanzanten** [comment] 2018-11-14 16:01
I'm pretty sure this is a duplicate of #2242. Please let me know if the new release (7.0.7) fixed it for you @Wulfheart. If not, we'll reinvestigate this :)

**Closed by rijkvanzanten** 2018-11-14 16:01 UTC
Labels: duplicate

**Comment by Wulfheart** [comment] 2018-11-14 20:02
Edit: It worked after trying it again.

**Comment by swatiag1101** [comment] 2019-05-03 16:45
Hi @Wulfheart I am having the exact same issue as the one you have reported in this thread. Great that you got it working eventually. I have installed the latest Directus version today and setup everything using the manual process [ It never prompted me for an automatic installation when navigating to https://domain.com/admin ]

However, I still get the Couldn't Reach API error.

Can you suggest what did you do differently that resolved the issue?

@shealavington @rijkvanzanten I have setup a fresh install with apache, php7.1, mysql 5.7 and my directus files are in the /var/www/app folder and my domain is pointing to /var/www/app/folder

I have done the necessary chmod, chown permissions and checked all apache conf files etc.

Can't get it past the Couldn't Reach API error

Any help will be greatly appreciated.

**Comment by swatiag1101** [comment] 2019-05-03 17:15
Update: This worked for me now - I had not set the AllowOverride All in apache config.
