### ISSUE TITLE
Public /files show all files even when filtered with uploaded_by

### ISSUE THREAD

**Issue by Pachat** [directus/directus#19924] opened 2023-10-06 08:18 UTC
### Describe the Bug

In fact, when not connected, /files will show the data with `uploaded_by: null` even when uploaded_by isn't null (as verified in the DB)

Hence, we cannot restrict the publicly files' list based on uploaded_by

### To Reproduce

Disconnected, show url : `app.domain.com/files`

All `uploaded_by` will be shown as `null`

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by Pachat** [comment] 2023-10-06 08:55
Tried to add an M2O field on users. But get the same bug: it show null although not null in the DB.
Is this caused by relational field?

**Comment by DanielBiegler** [comment] 2023-10-06 09:20
Cant reproduce both for 10.2.1 nor 10.6.2. I can filter and it works. Closing for now as we dont have enough information here but happy to reopen in case theres updates.

Also on another note, I'd suggest filtering the public files via a folder and not a user. That way you can very easily move the files in or out and your API will reflect that. After creating your folder, go into it and look at the URL, it'll tell you the ID of the folder. Use that ID in a filter for directus_files and you're good. :smile: :v:

**Closed by DanielBiegler** 2023-10-06 09:20 UTC
Labels: Needs More Info

**Comment by Pachat** [comment] 2023-10-06 09:32
Thanks for the tip on the folders.

The filter actually works on `/admin/files`

My question is about `/files`
It shows the full 'data':[....JSON..]` and it is a privacy violation. 
Additionally, it does not update when changing filters although `/admin/files` refreshes correctly.

**Comment by DanielBiegler** [comment] 2023-10-06 09:52
I did test `/files`. Everything works correctly for me. You may need to double check your settings, I dont know your setup so cant help without more information.

> Additionally, it does not update when changing filters although /admin/files refreshes correctly

What do you mean by that exactly? The filter in the search bar is just for your local search, you gotta restrict the API in the permissions settings under `/admin/settings/roles/`

**Comment by Pachat** [comment] 2023-10-06 19:07
My concern was on Public roles. Closing all Public access to `directus_files` was indeed the solution. Thanks.

**Comment by Pachat** [comment] 2023-10-10 05:28
Closing all Public access to does not allow to see files through a direct link 
`https://app.mysite.com/assets/2a3241e4-ad86-4f05-9c9f-f4d408b5c14c`. 
I have at least to expose publicly the ID.
Is there a way to manage `https://app.mysite.com/files` not to list IDs?

**Comment by DanielBiegler** [comment] 2023-10-10 08:49
> To enable such direct links, I must at least publicly expose the ID.

Correct

> Is there a way to handle https://app.mysite.com/files to not list IDs?

Theres no easy native way as of right now. Maybe with an extension but you'd need to tinker with it.
