### ISSUE TITLE
Can't delete file from library

### ISSUE THREAD

**Issue by federicocappellotto97** [directus/directus#9774] opened 2021-11-13 13:39 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If i delete an image from library i get this error:
`
{
  "errors": [
    {
      "message": "delete from `directus_files` where `id` in ('e9c5f419-f465-4548-8be9-42e5ec32e0f1') - ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`directus-saccardo`.`directus_settings`, CONSTRAINT `directus_settings_project_logo_foreign` FOREIGN KEY (`project_logo`) REFERENCES `directus_files` (`id`))",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
`

### To Reproduce

Delete an image from library

### Errors Shown

{
  "errors": [
    {
      "message": "delete from `directus_files` where `id` in ('e9c5f419-f465-4548-8be9-42e5ec32e0f1') - ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`directus-saccardo`.`directus_settings`, CONSTRAINT `directus_settings_project_logo_foreign` FOREIGN KEY (`project_logo`) REFERENCES `directus_files` (`id`))",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

MysQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Locally

**Comment by federicocappellotto97** [comment] 2021-11-13 13:41
Update, resolved: this file was the project logo.
I removed the logo then i deleted correctly the file.

**Comment by ruihildt** [comment] 2021-11-13 22:11
I hit the same error for the same reason, either the logo should be deleted or a nicer error be shown.

**Comment by federicocappellotto97** [comment] 2021-11-14 13:42
Maybe it would be better to give more tips about the error instead of "Internal server error"

**Comment by azrikahar** [comment] 2021-11-14 14:08
This has indeed been brought up quite a few times, and technically a duplicate of #9507, so I'll proceed to close this 👍

**Closed by azrikahar** 2021-11-14 14:08 UTC
Labels: Bug (Potential)
