### ISSUE TITLE
Hard refresh on Admin App logout session and breaks app until container restart

### ISSUE THREAD

**Issue by b3nab** [directus/directus#23473] opened 2024-08-24 17:34 UTC
### Describe the Bug

After login in into Directus Admin and doing a hard refresh I am logged out and the admin became unusable until I restarted the container.

It seems related to other issues probably: #22696, #22584 

### To Reproduce

Nothing fancy and simple steps:

1. have a connection string for supabase (but I think it should be the same with any other postgres db)
2. configure envs with DB_CLIENT, DB_CONNECTION_STRING and DB_SEARCH_PATH - like "array:directus,extensions"
3. start docker container and it run migrations and start directus
4. navigate to your directus admin url and login
5. at this point everything seems to work flawless until you forget to NOT hard refresh the page... the suddenly "An unexpected error occurred." with INTERNAL_SERVER_ERROR.

At this point the only way to be able to login back again is to restart the docker container.

So (just speculation from now on) it seems that this error is in some way connected to the admin frontend app (maybe?) and something related to some configurations changing at runtime when doing an hard refresh. Maybe this hard refresh is the cause that generates other consequent cause-effect at runtime making the queries break at some level.
Or another way to think at this issue is that the DB_SEARCH_PATH is the one as root cause of this problem because of the multischema nature of how Supabase DB is structured (extensions and auth schemas are specific to supabase). But really just speculating a lot and trying to give my 2 cents to help you solve this little bugs.

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15.6 on Supabase

**Comment by rijkvanzanten** [comment] 2024-08-26 19:50
Are you running more than 1 docker image simultaneously in this example?

**Comment by b3nab** [comment] 2024-08-26 22:11
Mmmh don't know if I got your question but if you're asking if I'm running more than 1 directus image simultaneously the answer is not. If it's a general question then yes, sure, I have multiple containers running on top of docker.

**Comment by rijkvanzanten** [comment] 2024-08-26 22:23
Ah yeah I meant > 1 container of Directus running simultaneously 🙂 Sometimes these issues are caused because folk run Directus load balanced without having configured Redis for example which can cause the individual containers to get out of sync and behave erratically. Sounds like this is something else though.

Are you able to reproduce this against a local Postgres container as well? Trying to see if this is a Supabase specific problem or something else client-side 🤔

**Comment by b3nab** [comment] 2024-08-27 21:30
yeah I excluded Redis because I am running 1 single instance of Directus in 1 single container, so as per documentation if I understood correctly I could skip to add Redis in the loop.. but thinking about it I can give it a try adding Redis.
Consider also that I tested literaly every version from 10.4 to 11 doing basically: 1. drop all tables in db 2. run directus image with pinned version (e.g.: directus/directus:10.6) and leaving the ENV the same for all, after some minutes to up to an hour if I reload the page it shows the errors and from that moment on Directus became inaccessible in anyway. Then I took the same steps for all the other versions and all seems to have the same issue.

I will let you know if something change with Redis, even if I run one single instance. Because the thing probably is that is nothing change then as you said there is something weird happening with supabase, but idk really.

**Comment by b3nab** [comment] 2024-08-31 01:27
Little update: I tried adding Redis following the docs on directus website but the results are pretty much the same even with Redis.

```
INFO: Server started at http://0.0.0.0:8055
2024-08-31T01:22:02.498279186Z [01:22:01] POST /auth/refresh 400 28ms
2024-08-31T01:22:06.549828465Z [01:22:05] GET / 302 3ms
2024-08-31T01:22:06.552835034Z [01:22:05] GET /admin 200 1ms
2024-08-31T01:22:06.553030114Z [01:22:05] GET /admin/assets/runtime-core.esm-bundler-zlSgKseS.js 200 13ms
2024-08-31T01:22:06.553158754Z [01:22:05] GET /admin/assets/pinia.ZGOsqJmi.entry.js 200 9ms
2024-08-31T01:22:06.553315795Z [01:22:05] GET /admin/assets/vue-router.Dt24BTtJ.entry.js 200 10ms
2024-08-31T01:22:06.553440475Z [01:22:05] GET /admin/assets/vue.runtime.esm-bundler-BY4gCD-H.js 200 9ms
2024-08-31T01:22:06.553569276Z [01:22:05] GET /admin/assets/vue-i18n.upvyfvU5.entry.js 200 5ms
2024-08-31T01:22:06.553704556Z [01:22:05] GET /admin/assets/index-CHzbp3wQ.css 200 21ms
2024-08-31T01:22:06.554630399Z [01:22:05] GET /admin/assets/index-DqDL7Qf0.js 200 15ms
2024-08-31T01:22:06.554644999Z [01:22:05] GET /admin/assets/index.ZEGekNQg.entry.js 200 56ms
2024-08-31T01:22:07.064808270Z [01:22:06] GET /extensions/sources/index.js 200 14ms
2024-08-31T01:22:07.067543198Z [01:22:06] POST /auth/refresh 400 9ms
2024-08-31T01:22:07.067674638Z [01:22:06] GET /auth?sessionOnly 200 21ms
2024-08-31T01:22:07.068645561Z [01:22:06] GET /server/info 500 36ms
2024-08-31T01:22:07.068805482Z [01:22:07] GET /admin/assets/Inter-Bold-d8J9BkrN.woff2 200 9ms
2024-08-31T01:22:07.068978962Z [01:22:07] GET /admin/assets/Inter-Medium-IZr8HYrM.woff2 200 11ms
2024-08-31T01:22:07.069103962Z [01:22:07] GET /admin/assets/FiraMono-Medium-CE-6Frqh.woff2 200 9ms
2024-08-31T01:22:07.069243283Z [01:22:07] GET /admin/assets/material-symbols-BLTCXYgc.woff2 200 18ms
2024-08-31T01:22:07.069420083Z [01:22:07] GET /admin/assets/Inter-SemiBold-1vGiIFm-.woff2 200 10ms
2024-08-31T01:22:07.612198571Z [01:22:06.958] ERROR: select "directus_settings"."project_name", "directus_settings"."project_descriptor", "directus_settings"."project_logo", "directus_settings"."project_color", "directus_settings"."default_appearance", "directus_settings"."default_theme_light", "directus_settings"."default_theme_dark", "directus_settings"."theme_light_overrides", "directus_settings"."theme_dark_overrides", "directus_settings"."default_language", "directus_settings"."public_foreground", "directus_settings"."public_favicon", "directus_settings"."public_note", "directus_settings"."custom_css", "directus_settings"."public_registration", "directus_settings"."public_registration_verify_email", "directus_settings"."public_background", "directus_settings"."id" from "directus_settings" order by "directus_settings"."id" asc limit $1 - relation "directus_settings" does not exist
2024-08-31T01:22:07.612288171Z err: {
2024-08-31T01:22:07.612291491Z "type": "DatabaseError",
2024-08-31T01:22:07.612294091Z "message": "select \"directus_settings\".\"project_name\", \"directus_settings\".\"project_descriptor\", \"directus_settings\".\"project_logo\", \"directus_settings\".\"project_color\", \"directus_settings\".\"default_appearance\", \"directus_settings\".\"default_theme_light\", \"directus_settings\".\"default_theme_dark\", \"directus_settings\".\"theme_light_overrides\", \"directus_settings\".\"theme_dark_overrides\", \"directus_settings\".\"default_language\", \"directus_settings\".\"public_foreground\", \"directus_settings\".\"public_favicon\", \"directus_settings\".\"public_note\", \"directus_settings\".\"custom_css\", \"directus_settings\".\"public_registration\", \"directus_settings\".\"public_registration_verify_email\", \"directus_settings\".\"public_background\", \"directus_settings\".\"id\" from \"directus_settings\" order by \"directus_settings\".\"id\" asc limit $1 - relation \"directus_settings\" does not exist",
2024-08-31T01:22:07.612304411Z "stack":
2024-08-31T01:22:07.612307491Z error: select "directus_settings"."project_name", "directus_settings"."project_descriptor", "directus_settings"."project_logo", "directus_settings"."project_color", "directus_settings"."default_appearance", "directus_settings"."default_theme_light", "directus_settings"."default_theme_dark", "directus_settings"."theme_light_overrides", "directus_settings"."theme_dark_overrides", "directus_settings"."default_language", "directus_settings"."public_foreground", "directus_settings"."public_favicon", "directus_settings"."public_note", "directus_settings"."custom_css", "directus_settings"."public_registration", "directus_settings"."public_registration_verify_email", "directus_settings"."public_background", "directus_settings"."id" from "directus_settings" order by "directus_settings"."id" asc limit $1 - relation "directus_settings" does not exist
2024-08-31T01:22:07.612316331Z at Parser.parseErrorMessage (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:283:98)
2024-08-31T01:22:07.612318931Z at Parser.handlePacket (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:122:29)
2024-08-31T01:22:07.612321371Z at Parser.parse (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/parser.js:35:38)
2024-08-31T01:22:07.612323811Z at Socket.<anonymous> (/directus/node_modules/.pnpm/pg-protocol@1.6.1/node_modules/pg-protocol/dist/index.js:11:42)
2024-08-31T01:22:07.612326651Z at Socket.emit (node:events:517:28)
2024-08-31T01:22:07.612328891Z at addChunk (node:internal/streams/readable:368:12)
2024-08-31T01:22:07.612331171Z at readableAddChunk (node:internal/streams/readable:341:9)
2024-08-31T01:22:07.612336691Z at Readable.push (node:internal/streams/readable:278:10)
2024-08-31T01:22:07.612339091Z at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2024-08-31T01:22:07.612341411Z "length": 117,
2024-08-31T01:22:07.612343571Z "name": "error",
2024-08-31T01:22:07.612345731Z "severity": "ERROR",
2024-08-31T01:22:07.612347971Z "code": "42P01",
2024-08-31T01:22:07.612350051Z "position": "733",
2024-08-31T01:22:07.612352211Z "file": "parse_relation.c",
2024-08-31T01:22:07.612354371Z "line": "1392",
2024-08-31T01:22:07.612356531Z "routine": "parserOpenTable"
2024-08-31T01:22:07.612358731Z }
```

Keep in mind that the project is completely new, so I think there are some troubles managing a database of a directus instance when is totally new and also empty (at least that's what I understood from the errors above).

**Comment by hanneskuettner** [comment] 2024-08-31 04:28
Can you verify that the table `directus_settings` exists within your supabase postgres instance and that it's accessible for the user you're using for Directus? The error indicates that the table was not found.

**Comment by b3nab** [comment] 2024-08-31 09:47
> Can you verify that the table `directus_settings` exists within your supabase postgres instance and that it's accessible for the user you're using for Directus? The error indicates that the table was not found.

Yes the tables are all present in the db. Directus created all of them during the first boot. The thing is that most of these tables are empty, for example this `directus_settings`contains 0 rows.
To me is not clear why Directus breaks up when the db is not able to find some matching rows.

At this point the only thing seems to be relevant is the schema/search_path.
Anyway I'm trying a fresh install of directus + redis + a local postgres db, I will let you know in the following days.

**Comment by rijkvanzanten** [comment] 2024-09-02 22:10
I haven't been able to reproduce this with postgres / postgis with the current information available, so I'll close this for now. Please keep me posted on your research and we'll reopen this if a bug in directus is the cause here 🙂

**Closed by rijkvanzanten** 2024-09-02 22:10 UTC

**Comment by b3nab** [comment] 2024-09-03 19:17
Ok I have some updates to share with you, so I played around some variables to better understand, which are: 
- DB used: postgres/postgis or others like supabase
- Schema used: default public schema or some custom schemas (I was using "directus" as schema name)
- The order of the schema in DB_SEARCH_PATH env variable

So in the end my understanding is that Directus cannot be used with another schema different from the public and even if you want to use DB_SEARCH_PATH env variable you should always point to the public as the first schema in the array like so:

this is working -> `DB_SEARCH_PATH=array:public,auth,extensions`
this one leads to the error in the first post -> `DB_SEARCH_PATH=array:directus,public,auth,extensions`
