### ISSUE TITLE
Collection page displaying duplicate items

### ISSUE THREAD

**Issue by Vprasannaakumar** [directus/directus#14113] opened 2022-06-25 17:37 UTC
### Describe the Bug

Hi,
I tried to modify directus user collection for custom roles.

I created user contexts and assigned to users.

I created read access rule for "article" collection with user contexts.

But collection page displaying duplicate items.

Please find attached video to reproduce this issue.

https://user-images.githubusercontent.com/32242696/175784258-57a407e5-9b6f-4145-ad8f-e25c57e5cbad.mp4

Created Read Access Rule:
{
	"_and": [
		{
			"user_created": {
				"userContext": {
					"context_id": {
						"title": {
							"_in": [
								"$CURRENT_USER.userContext.context_id.title"
							]
						}
					}
				}
			}
		}
	]
}

### To Reproduce

1.Create a new collection "context" (add two fields , title and description)
2.Make few entries to this context
3.Create many-to-many relationship between User -> context   (From user to context)
4.Open admin user, add all contexts to the admin user
5.Create second user(ex:user1) with some other role(ex: manager), add some contexts to user1
6.Create new collection (ex: article)
5.Create read access rule for collection(ex: article) using user contexts (make sure all fields are selected under Field Permissions)
6.Using admin user, add one entry to collection "article"
7.Login with second user (ex:user1)
8.You will see single object will be displayed multiple times
(if second user, holds 4 contexts which are in common with first user, item will be displayed for 4 times)

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.14.0

### What database are you using?

MySQL

### What browser are you using?

Edge

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2022-06-27 01:10
I believe this should be the same or has the same root cause as #13107 (particularly when setting specific custom permissions which then causes duplicate items via API). Closing this for now in favor of tracking it over there 👍

**Closed by azrikahar** 2022-06-27 01:10 UTC
