### ISSUE TITLE
Item Detail : can't see revisions in the sidebar

### ISSUE THREAD

**Issue by Jeyffrey** [directus/directus#4210] opened 2021-02-22 10:05 UTC
I can't see revisions in the item detail page.

Should I configure something to see items modifications directly in this sidebar ?

---

### Project details
Directus Version: 9.0.0-rc.40
Environment: production
OS: macOS Catalina (10.15)
Node: 14.15.5

**Comment by Nitwel** [comment] 2021-02-22 10:51
Revisions should work without doing anything.
Could you provide more details on how to reproduce this or how your DB looks like?

**Comment by rijkvanzanten** [comment] 2021-02-22 15:52
> Should I configure something to see items modifications directly in this sidebar ?

Your user-role needs to have access to directus_revisions.

---

We'll close this for now, but we can reopen if we have a way to reproduce this 🙂

**Closed by rijkvanzanten** 2021-02-22 15:53 UTC
Labels: App, Needs More Info

**Comment by Jeyffrey** [comment] 2021-02-22 16:08
> > Should I configure something to see items modifications directly in this sidebar ?
> 
> Your user-role needs to have access to directus_revisions.

I'm connected as the Admin user.

I just created a sample project with the "npx" commands and a MySQL database.
I only followed the "Quick start guide" and made a simple collection.

When i go the "/revisions" endpoint, i see that there are 100 entries. 
Even if i change something in the back-office, it doesn't change, i always got 100 entries.

**Comment by rijkvanzanten** [comment] 2021-02-22 16:09
Also try updating to the latest version of Directus 🙂

**Comment by Jeyffrey** [comment] 2021-02-22 16:19
> Also try updating to the latest version of Directus 🙂

Thank's ! It works well now.
For a real project, do you think I should use Directus v8 cause the v9 is still in R.C. ?

**Comment by rijkvanzanten** [comment] 2021-02-22 16:21
No, IMO v9 is more stable at this point than v8, and v8 won't be actively supported (outside of community pro)
