### ISSUE TITLE
missing FROM-clause entry for table "..."

### ISSUE THREAD

**Issue by xesjkeee** [directus/directus#4778] opened 2021-03-31 12:10 UTC
I using that db scheme for the project

![scheme](https://user-images.githubusercontent.com/17751886/113140061-915feb00-9230-11eb-9ac1-a0bf664a6e57.png)

So trying to add permissions for Read Articles:

```json
{
  "_or": [
    {
      "user_created": {
        "_eq": "$CURRENT_USER"
      }
    },
    {
      "_and": [
        {
          "publisher": {
            "_neq": "null"
          }
        },
        {
          "publisher": {
            "published_articles": {
              "published": {
                "_eq": "true"
              }
            }
          }
        }
      ]
    }
  ]
}
```

Then navigated to `Collections` -> `Articles` and got `An unexpected error occurred.`

In logs: 

```bash
14:54:59 🚨 error select "articles"."description", "articles"."status", "articles"."title", "articles"."id", 
"articles"."preview_image" from "articles" left join "publishers" as "yfbdh" on 
"articles"."publisher" = "yfbdh"."id" where (("articles"."user_created" = $1 or ("articles"."publisher" 
is not null and "fozlt"."published" = $2))) order by "articles"."id" asc limit $3 - 
missing FROM-clause entry for table "fozlt"
    at Parser.parseErrorMessage (/blog/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/blog/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/blog/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/blog/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:486:12)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

My environment:
- directus@^9.0.0-rc.52
- Postgres 12
- deployment via npx
- Chrome 89

What can I add to help you?

**Comment by xesjkeee** [comment] 2021-03-31 12:17
Upgrated to `directus@^9.0.0-rc.53`, but problem still here

**Comment by rijkvanzanten** [comment] 2021-03-31 13:53
@xesjkeee I think this might be a duplicate of https://github.com/directus/directus/issues/4485 🤔

**Closed** 2021-03-31 13:54 UTC
Labels: Duplicate
