### ISSUE TITLE
create-directus-project error in mssql database seed

### ISSUE THREAD

**Issue by Antti-Honkala** [directus/directus#3850] opened 2021-01-29 18:12 UTC
1) The issue and what you expected to happen
    create-directus-project crashes on database seed

> Something went wrong while seeding the database:
>
>**[EREQUEST]** ALTER TABLE [directus_fields] ADD CONSTRAINT [directus_fields_group_foreign] FOREIGN KEY ([group]) REFERENCES [directus_fields] ([id]) ON UPDATE CASCADE ON DELETE SET NULL - Could not create constraint. See previous errors.

2) Exact steps to reproduce this issue
    When I run the installer script "**npx create-directus-project my-project**" and put my mssql database details it gives an error message that is shown on the screenshot

3) Your environment:
Windows Server 2012R2 and SQL Server 2012 

4) Any other relevant information we might need to reproduce this issue

Tables are created, but there is a problem creating the  **[directus_fields_group_foreign]** constraint and I cannot finish the installer successfully

![error_2](https://user-images.githubusercontent.com/32385081/106311467-dd60d480-626d-11eb-941d-481e20d62eb3.PNG)

**Comment by rijkvanzanten** [comment] 2021-01-29 18:17
Duplicate of https://github.com/directus/directus/issues/3158

**Closed by rijkvanzanten** 2021-01-29 18:17 UTC
