### ISSUE TITLE
Dropdown MulitSelect raw value instead of dropdown and labels

### ISSUE THREAD

**Issue by boscho87** [directus/directus#11947] opened 2022-03-04 14:36 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The labels not shown like expected on Muli Select Dropdown. When i Change Field to MultiSelect with Checkbox. All Checkbox on the entries are shown as inactive even there are more then one is actually active

![image](https://user-images.githubusercontent.com/11815871/156781748-e78caa2d-b2a2-492d-b681-e2d22e3184c5.png)
![image](https://user-images.githubusercontent.com/11815871/156781505-ad51fd89-d431-4573-bf60-e544137ec5bf.png)

### To Reproduce

Nor shure what caused this, but i migrated form a older "php directus" with the directus migration tool

### What version of Directus are you using?

9.2.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

 mysql5.7

### What browser are you using?

chrome

### What operating system are you using?

arch linux

### How are you deploying Directus?

podman (docker)

**Comment by rijkvanzanten** [comment] 2022-03-04 16:15
If you open one of those options, what's the value? Could you share a database dump or schema snapshot with the configuration that's causing this?

**Comment by boscho87** [comment] 2022-03-04 18:40
maybe the problem could be that in the field table the `special` column was not set to json. After i changed this and restartet my docker container it was working like expected. (Should i Close?) i think it was a problem in the migrations

**Comment by rijkvanzanten** [comment] 2022-03-04 20:14
Ah, that could be! What exact version of MySQL 5 are you on?

**Comment by boscho87** [comment] 2022-03-04 21:14
5.7

**Comment by rijkvanzanten** [comment] 2022-03-04 21:46
5.7.8 or later?

**Comment by boscho87** [comment] 2022-03-04 21:47
![image](https://user-images.githubusercontent.com/11815871/156846321-9ee50ddc-5216-4557-9861-e7c5a3b8c8e8.png)

**Comment by azrikahar** [comment] 2022-03-21 12:27
@boscho87 just to follow up, this has since resolved right? as I do believe it should be a one-time thing here.

@rijkvanzanten should this issue be moved to the `directus-community/migration-tool` repo? Though I did briefly looked into it and notice the following lines:

https://github.com/directus-community/migration-tool/blob/2fdae2ed151f2528755433305db67f5387c88fa7/tasks/schema.js#L230

https://github.com/directus-community/migration-tool/blob/2fdae2ed151f2528755433305db67f5387c88fa7/tasks/schema.js#L295-L297

which does indicate the migration should've correctly set the `special` as `["json"]` 🤔 but admittedly I'm not too familiar with the migration as a whole.

**Comment by rijkvanzanten** [comment] 2022-03-21 13:14
@azrikahar If this was caused by the migration tool, then by all means yes. @boscho87 Could you confirm the issue is resolved when adding that `json` flag?

**Comment by rijkvanzanten** [comment] 2022-04-18 23:26
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2022-04-18 23:26 UTC
Labels: External, Can't Reproduce
