### ISSUE TITLE
o2m relation not prefilled and visible

### ISSUE THREAD

**Issue by boo-code** [directus/directus#15043] opened 2022-08-12 11:37 UTC
### Describe the Bug

When creating new o2m related record, related key is not prefilled and not hidden. It's not possible to select an existing parent record for the field too, because the select drop-down button is not active etc. Before the latest update it was working correctly.

![image](https://user-images.githubusercontent.com/65190196/184346547-fd600b60-5a88-4d25-9c6f-5df83b443f10.png)

![image](https://user-images.githubusercontent.com/65190196/184345762-36080110-3a58-4f8e-9dcf-3a435159a4da.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/65190196/184346248-25e6850d-c906-4d60-99ff-60f70abbbcfe.png)

Create o2m relation and from parent record try to add new related records.

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

18.4.0

### What database are you using?

Postgres 14

### What browser are you using?

Chrome

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment] 2022-08-12 13:55
Should be duplicate of #14992 👍

**Closed by azrikahar** 2022-08-12 13:55 UTC
