### ISSUE TITLE
Assets: Display PDF FILE in Safari

### ISSUE THREAD

**Issue by AndreasGBS** [directus/directus#23130] opened 2024-07-30 12:11 UTC
### Describe the Bug

The display of PDF files via assets is wrong in Apple Safari under MAC OS, it is displayed very small, should be displayed in full width as in Chrome. If I deliver the same PDF via Apache, the display is ok. 

![MLp9](https://github.com/user-attachments/assets/90599555-2845-49d1-b2dd-1d89609bd3f5)

### To Reproduce

Here is an example: https://api.region-landeck.at/assets/c217757f-5b19-47d3-9567-e9203aec35ea 
Open the file with Safari on Mac Os

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by hanneskuettner** [comment] 2024-07-31 08:37
This seems to be caused by Safari allowing it's own PDF viewers CSS to be blocked by server side CSP headers (which feels weird to me, tbh). This only seems to be introduced after Safari 17.3 (as tests with browserstack confirm that this is a non issue before).

<img width="1322" alt="Screenshot 2024-07-31 at 10 22 14" src="https://github.com/user-attachments/assets/aad4dbff-88e8-47c4-9c2a-ef136c5befcb">

You might have to set `ASSETS_CONTENT_SECURITY_POLICY_DIRECTIVES__STYLE_SRC="'unsafe-inline'"` in you configuration to work around that. 

Since it seems like a bug (or change) in Safari I wonder if this is something we need to or should deal with in Directus.

**Comment by AndreasGBS** [comment] 2024-07-31 09:22
HI @hanneskuettner, 
your workaround with 

`ASSETS_CONTENT_SECURITY_POLICY_DIRECTIVES__STYLE_SRC="'unsafe-inline'"`

works, e.g. https://api.region-landeck.at/assets/c217757f-5b19-47d3-9567-e9203aec35ea

> Since it seems like a bug (or change) in Safari I wonder if this is something we need to or should deal with in Directus.

Good question, I'll leave the ticket open

**Comment by rijkvanzanten** [comment] 2024-07-31 19:25
Closing this as I believe this to be a bug in Safari's rendering engine, not Directus. All other browsers behave as you'd expect 🙂

**Closed by rijkvanzanten** 2024-07-31 19:25 UTC
Labels: :cake: Bug, :file_folder: Assets, :elevator: Server, :fire::fire:
