### ISSUE TITLE
On 9.23.3 refreshing the page disconnects and goes to login

### ISSUE THREAD

**Issue by Pachat** [directus/directus#17913] opened 2023-03-24 10:34 UTC
### Describe the Bug

On any page, refreshing disconnects and goes to login

### To Reproduce

Open an app
Press F5 (if on Windows)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by licitdev** [comment] 2023-03-24 10:43
Duplicate of #17901

**Closed by licitdev** 2023-03-24 10:43 UTC
