### ISSUE TITLE
Not able to set the display of a M2A field

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17097] opened 2023-01-11 19:37 UTC
### Describe the Bug

I’m not able to set the display of a M2A field. I want to display fields from the M2A junction table as well as the related collections. It is only possible to use the display of the related collections — but there I have no access to the junction collection.

### To Reproduce

Let’s say we have a silder in a project. This slide can have images and videos. So I will create a `projects` collection with a M2A field called `slides`, that creates the `projects_slides` junction collection. The junction collection connects the `projects_slides_images` and the `projects_slides_videos` collection. To keep it simple create only a title field (input field) for every collection. Now I set the display for the M2A field inside the projects collection, but it does not work. Only the display of the `projects_slides_images` and `projects_slides_videos` appear in the list of the M2A field. So we are not able to display fields from the junction collection.

### What version of Directus are you using?

9.22.2

### What version of Node.js are you using?

Latest

### What database are you using?

MySQL

### What browser are you using?

Firefox

### How are you deploying Directus?

Docker

**Comment by Nitwel** [comment] 2023-02-03 15:15
I'm able to select fields from junction and related collection to display. Could you provide a screenshot on where you are having these problems? I also have to close this for now as the issue is to vague, but please reopen it if you have exact steps to reproduce this.

![grafik](https://user-images.githubusercontent.com/22577866/216637489-57f699c4-baad-4ec0-82f8-5f7155f53850.png)

**Closed by Nitwel** 2023-02-03 15:15 UTC

**Comment by JonathanDoelan** [comment] 2023-02-03 15:27
@Nitwel Here I’ve tried to set the display via the `slides` field (which fyi I’ve named Gallery)

<img width="942" alt="schema" src="https://user-images.githubusercontent.com/2291224/216641397-c21d7aec-8d7f-4eb7-99d9-c0a44ba097f9.png">


… and this is the output …

<img width="848" alt="output" src="https://user-images.githubusercontent.com/2291224/216641621-32f8844a-8e2c-45a0-b779-0c1900017068.png">


How can I reopen this issue?
