### ISSUE TITLE
Click to configure on Database Only collection doesn't work

### ISSUE THREAD

**Issue by paulboudewijn** [directus/directus#9966] opened 2021-11-21 22:36 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

![image](https://user-images.githubusercontent.com/17253180/142781423-f763e830-a16c-45fc-a5cc-ecb94cc7e6c6.png)

Clicking on a database-only collection doesn't do anything since the onclick handler doesn't exist.

**If have a PR ready**

A workaround is to select the option "make collection visible" in the collection options dialog, this will first add the collection and then make it visible.

### To Reproduce

Click on a database-only collection and note nothing happens.

### Errors Shown

```
Uncaught TypeError: _ctx.openCollection is not a function
    at onClick (collections.vue:73)
    at callWithErrorHandling (runtime-core.esm-bundler.js:6701)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6710)
    at HTMLDivElement.invoker (runtime-dom.esm-bundler.js:350)
```

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

v16.13.0

### What database are you using?

MSSQL

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

running locally

**Comment by paescuj** [comment] 2021-11-21 22:46
Duplicate of #9052

**Closed** 2021-11-21 23:00 UTC
Labels: Bug (Potential)
