### ISSUE TITLE
Disable creating new file images when editing an uploaded image 

### ISSUE THREAD

**Issue by tasoskakour** [directus/directus#20618] opened 2023-12-03 09:34 UTC
### Describe the Improvement

Currently when we want to edit an image in the admin UI, a new big-sized file of this image is created with `system-large-contain` preset and is actually stored in our file storage system. 
Sometimes, this new created preview is even bigger (in filesize) than our originally uploaded image.

As a result, we end up having these "useless" big files saved in our storage provider.

Do you think it would be worth to tweak it a bit so that these large files are not stored? 

Keep up the awesome work! :pray: :clap:

**Comment by rijkvanzanten** [comment] 2023-12-04 08:26
Those files are the thumbnails that are generated by Directus for use in previews in the admin app. Those are not something we're currently looking to remove. We could consider a new feature request to explicitly disable that behavior though, but that needs more discussion first 🙂 

I'll close this for now as that's expected / intended behavior at present time.

**Closed by rijkvanzanten** 2023-12-04 08:26 UTC
