### ISSUE TITLE
Broken file-upload input

### ISSUE THREAD

**Issue by loicnestler** [directus/directus#2353] opened 2019-04-29 19:19 UTC
# Bug Report

## Steps to Reproduce

1. Create a collection and add a field with type 'file'
2. In the edit section, try to upload a file (either by dragging it on the zone or by clicking on one of the buttons)
3. See error

## Expected Behavior
A working file-upload

## Actual Behavior
A broken file-upload

## Other Context & Screenshots
![screenshot](https://i.imgur.com/bjVqpcM.png)
As you can see the form looks buggy and I'm unable to neither drag 'n' drop a file onto the form nor clicking on one of the buttons.

## Technical Details

- Device: [Lenovo Y50-70, Apple MacBook Pro 2015, Apple Mac]
- OS: [Arch Linux 4.20.6, macOS]
- Web Server: [nginx/1.14.0 (Ubuntu)]
- PHP Version: [7.2.17-0ubuntu0.18.04.1]
- Database: [5.7.25-0ubuntu0.18.04.2]
- Install Method: [cloned `master` branch]

**Comment by rijkvanzanten** [comment] 2019-04-29 19:25
Duplicate of https://github.com/directus/app/pull/1537

**Closed by rijkvanzanten** 2019-04-29 19:25 UTC
Labels: duplicate
