### ISSUE TITLE
GraphQL alias not working

### ISSUE THREAD

**Issue by federicocappellotto97** [directus/directus#9842] opened 2021-11-16 11:21 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a content type with an input field called **titolo**.
This query works well:
`query {
	Eventi_calendario {
           titolo
    }
}`
But if i add an alias it doesnt't work:
`
query {
	Eventi_calendario {
       title: titolo
    }
}`

It says `Cannot read property 'type' of undefined`

### To Reproduce

Create a collection type with input field and try to query with GraphQL adding an alias to that field

### Errors Shown

`{
    "errors": [
        {
            "message": "Cannot read property 'type' of undefined",
            "locations": [
                {
                    "line": 2,
                    "column": 2
                }
            ],
            "path": [
                "Eventi_calendario"
            ]
        }
    ],
    "data": {
        "Eventi_calendario": null
    }
}`

### What version of Directus are you using?

9.0.1

### What version of Node.js are you using?

14.18.1

### What database are you using?

MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment] 2021-11-16 11:33
Duplicate of #9390

---

Hi @federicocappellotto97, just a reminder that before we check `There's no other issue that already describes my problem.` (the 3rd Preflight **Checklist** item), we should verify and try to do a search first to confirm there are no existing issues, especially open issues, for the bug(s) you are facing.

I understand that at times it can be hard to get a matching result since we can word things differently for the same thing, myself included! 😄 However in this case, doing a search for "graphql alias" [does surface the relevant issues](https://github.com/directus/directus/issues?q=graphql+alias) for us. Hope that's understandable, and thanks for all the past issues you have reported nonetheless! 👍

**Closed by azrikahar** 2021-11-16 11:33 UTC
Labels: Bug (Potential)
