### ISSUE TITLE
Hidden fields show up as skeletons while loading

### ISSUE THREAD

**Issue by SeanDylanGoff** [directus/directus#15724] opened 2022-09-23 12:52 UTC
### Describe the Bug

This is a regression caused by https://github.com/directus/directus/pull/15144 and https://github.com/directus/directus/pull/15160
While data is still loading fieldMap is unavailable, causing hidden fields to be shown in their loading state (v-skeleton-loader)

### To Reproduce

- Create an item in a table with 1 hidden and 1 visible field (e.g. id hidden and title visible)
- When re-opening the item observe a quick flash of 2 skeleton loaders.

**Comment by SeanDylanGoff** [comment] 2022-09-23 14:55
🧐 This repo. No idea how i could even choose cynova/directus as a merge target accidentally, as that repo is only meant for changes that should merge back here and is in no way connected to seandylangoff/directus.

**Comment by rijkvanzanten** [comment] 2022-12-15 22:36
Linear: [ENG-183](https://linear.app/directus/issue/ENG-183/hidden-fields-show-up-as-skeletons-while-loading)

**Comment by ComfortablyCoding** [comment] 2023-12-28 16:10
I am unable to reproduce this issue on the latest version with the reproducible steps listed. Closing this for now but happy to re-open the issue if more information becomes available.

![image](https://github.com/directus/directus/assets/44623501/c12ccbe4-0022-48d9-822f-869dd209df18)

https://github.com/directus/directus/assets/44623501/ba5e3098-fc39-4799-93bd-bd023cdc8966

**Closed by ComfortablyCoding** 2023-12-28 16:10 UTC
Labels: Package: @directus/app, Bug
