### ISSUE TITLE
embedded files not supported yet

### ISSUE THREAD

**Issue by erik-konrad** [directus/directus#3745] opened 2021-01-19 15:32 UTC
In case of a directus upgrade from 8 to 9, we have seen, that there is no option for creating new embedded youtube videos. The API also delivers the embed field only without a correct link on Youtube videos created in V8. 

At the moment, it is not possible to create embedded file references.

**Comment by rijkvanzanten** [comment] 2021-01-19 15:33
Duplicate of https://github.com/directus/directus/discussions/3060

**Closed by rijkvanzanten** 2021-01-19 15:33 UTC

**Comment by bitstarr** [comment] 2021-01-19 15:45
@rijkvanzanten So will this feature come back, or not? And when?
This was working in v8 and with the move of killing a stable software in favour of an RC it would be pretty nice recover some of the features…

**Comment by benhaynes** [comment] 2021-01-19 15:50
Yes it will be supported... but no we can't give timelines for updates:

https://docs.directus.io/getting-started/support.html#can-you-give-an-eta-for-this-feature-fix

**Comment by bitstarr** [comment] 2021-01-19 15:57
Better answer that mentioning a 3 months old discussion which is kinda dead. Thanks @benhaynes
If i could convice some people to spend a bit, who will i need to speak to in case of sponsoring this feature?

**Comment by benhaynes** [comment] 2021-01-19 16:04
You can speak to me on Discord regarding "sponsored" work!

https://directus.chat
