### ISSUE TITLE
Database error after recreating the Docker file

### ISSUE THREAD

**Issue by FantaMagier** [directus/directus#6533] opened 2021-06-28 11:28 UTC
### What version of Directus are you using?

v9.0.0-rc.81

### What version of Node.js are you using?

Directus Docker Container 

### What database are you using?

Directus Docker Container 

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

### Describe the Bug

After get the newest Version of the Directus Docker Container, following happens after starting the Container. The Version before was well running and v9.0.0-rc.69 and was recreating to v9.0.0-rc.81.

11:22:40 ⚠️  >

11:22:40 ⚠️  >                         WARNING!

11:22:40 ⚠️  >

11:22:40 ⚠️  >  The KEY and SECRET environment variables are not set. Some

11:22:40 ⚠️  >  temporary variables were generated to fill the gap, but in

11:22:40 ⚠️  >        production this is going to cause problems.

11:22:40 ⚠️  >

11:22:40 ⚠️  >                        Reference:

11:22:40 ⚠️  > https://docs.directus.io/reference/environment-variables.html

11:22:40 ⚠️  >

11:22:40 ⚠️  >
11:23:51 ✨ Initializing bootstrap...
11:23:51 ✨ Database already initialized, skipping install
11:23:51 ✨ Running migrations...
✨ Applying Restructure Relations...
[Error: alter table `directus_relations` add column `one_deselect_action` varchar(255) default 'nullify' - SQLITE_READONLY: attempt to write a readonly database] {
  errno: 8,
  code: 'SQLITE_READONLY'
}

### To Reproduce

Get the Docker of Version  v9.0.0-rc.69 and recreate the Docker file to v9.0.0-rc.81.

**Comment by rijkvanzanten** [comment] 2021-06-28 15:02
I believe this is a duplicate of https://github.com/directus/directus/discussions/6480

**Closed by rijkvanzanten** 2021-06-28 15:02 UTC
Labels: Bug (Potential)
