### ISSUE TITLE
File size validation rule doesn't work as expected

### ISSUE THREAD

**Issue by samdze** [directus/directus#13140] opened 2022-05-05 14:02 UTC
### Describe the Bug

I set a custom validation for a field, here it is:
![Screenshot 2022-05-05 at 15 46 29](https://user-images.githubusercontent.com/19392104/166936997-1a4ecc62-0d30-4b10-9495-016bc1c515f9.png)

But when I try to assign an image to the icon field and save, the file gets rejected no matter the file size:
![Screenshot 2022-05-05 at 15 59 50](https://user-images.githubusercontent.com/19392104/166939701-702a1ca0-b51d-4380-a910-3e3f408c47be.png)

If I try to get the file object through GET /files/:id this is the data I get:
```
{
    "data": {
        "id": "8c3bfa91-245f-4c52-871d-4cb304f57917",
        "storage": "local",
        "filename_disk": "8c3bfa91-245f-4c52-871d-4cb304f57917.png",
        "filename_download": "pico-8-logo.png",
        "title": "Pico 8 Logo",
        "type": "image/png",
        "folder": "2abd41c1-0fd1-4b34-800e-42893dc58a4a",
        "uploaded_by": "f1d6695a-ac05-425a-9cfb-6ac7ced10a47",
        "uploaded_on": "2022-05-05T10:21:44.472Z",
        "modified_by": "f1d6695a-ac05-425a-9cfb-6ac7ced10a47",
        "modified_on": "2022-05-05T10:34:15.266Z",
        "charset": null,
        "filesize": "6802",
        "width": 800,
        "height": 800,
        "duration": null,
        "embed": null,
        "description": null,
        "location": null,
        "tags": null,
        "metadata": {}
    }
}
```
filesize is a string, maybe this is the issue.

### To Reproduce

1. Create a table with an image field with the validation rule described above.
2. Create a new item of the newly created table and try to upload and assign an image (< 1 MB).
3. On save, Directus complains that the validation rule didn't pass.

### Errors Shown

I get "Failed to load resource: the server responded with a status of 400 (Bad Request)".
The message is:
```
{
    "errors": [
        {
            "message": "\"icon\" must be of type object",
            "extensions": {
                "code": "FAILED_VALIDATION",
                "field": "icon"
            }
        }
    ]
}
```

### What version of Directus are you using?

9.10.0

### What version of Node.js are you using?

Version contained in the official Docker image

### What database are you using?

Postgres 14.1

### What browser are you using?

Safari

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-05-08 14:44
I believe this should be a duplicate of #13148 #11775, or at least the same underlying root cause. Let's track this over at #11775.

**Closed by azrikahar** 2022-05-08 14:44 UTC
Labels: API, Bug

**Comment by shahinalomi** [comment] 2022-09-18 15:40
Ok

**Comment by shahinalomi** [comment] 2022-09-18 16:14
gh pr checkout 13196
