### ISSUE TITLE
Filters fail on root m2o field

### ISSUE THREAD

**Issue by NightlyFlux** [directus/directus#5978] opened 2021-06-01 17:20 UTC
Tried to use the "_nempty" filter on a API call and I get error 400 `"_nempty" has to be boolean`

Tried `&filter[inventario][_nempty]` and `&filter[inventario][_nempty]=true` got the same result

Is it a bug or how am I supposed to use it?😅

---

### Project details
Directus Version: 9.0.0-rc.69
Environment: production
OS: Linux 4.4.0-1088-aws
Node: 14.17.0

**Comment by rijkvanzanten** [comment] 2021-06-01 17:29
That last example seems to work as expected on my end! What's the full filter you're using?

`GET /items/articles?access_token=admin&filter[title][_nempty]=true`

**Comment by NightlyFlux** [comment] 2021-06-01 17:39
`GET /items/productos?fields=codigo,titulo,sku,costo,descripcion,descuento,imagenes.directus_files_id,inventario.cantidad,categorias.categorias_id.nombre&filter[inventario][_nempty]=true`

Tried again and got this on console:

```
2021-06-01T17:37:48.671101+00:00 app[web.1]: 17:37:48 🚨 select `productos`.`codigo`, `productos`.`titulo`, `productos`.`sku`, `productos`.`costo`, `productos`.`descripcion`, `productos`.`descuento` from `productos` where (`productos`.`codigo` in (select `inventario`.`codigo_producto` as `codigo_producto` from `inventario` where (`inventario`.`_nempty` is not null or `inventario`.`_nempty` != ''))) order by `productos`.`codigo` asc limit 100 - ER_BAD_FIELD_ERROR: Unknown column 'inventario._nempty' in 'where clause' 
2021-06-01T17:37:48.671111+00:00 app[web.1]: Error: ER_BAD_FIELD_ERROR: Unknown column 'inventario._nempty' in 'where clause'
2021-06-01T17:37:48.671121+00:00 app[web.1]:     at Query.Sequence._packetToError (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
2021-06-01T17:37:48.671122+00:00 app[web.1]:     at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
2021-06-01T17:37:48.671122+00:00 app[web.1]:     at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
2021-06-01T17:37:48.671123+00:00 app[web.1]:     at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
2021-06-01T17:37:48.671123+00:00 app[web.1]:     at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)
2021-06-01T17:37:48.671124+00:00 app[web.1]:     at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
2021-06-01T17:37:48.671124+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:88:28)
2021-06-01T17:37:48.671124+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
2021-06-01T17:37:48.671125+00:00 app[web.1]:     at Socket.emit (events.js:376:20)
2021-06-01T17:37:48.671125+00:00 app[web.1]:     at Socket.emit (domain.js:470:12)
2021-06-01T17:37:48.671126+00:00 app[web.1]:     --------------------
2021-06-01T17:37:48.671126+00:00 app[web.1]:     at Protocol._enqueue (/app/node_modules/mysql/lib/protocol/Protocol.js:144:48)
2021-06-01T17:37:48.671127+00:00 app[web.1]:     at Connection.query (/app/node_modules/mysql/lib/Connection.js:198:25)
2021-06-01T17:37:48.671127+00:00 app[web.1]:     at /app/node_modules/knex/lib/dialects/mysql/index.js:126:18
2021-06-01T17:37:48.671128+00:00 app[web.1]:     at new Promise (<anonymous>)
2021-06-01T17:37:48.671128+00:00 app[web.1]:     at Client_MySQL._query (/app/node_modules/knex/lib/dialects/mysql/index.js:120:12)
2021-06-01T17:37:48.671128+00:00 app[web.1]:     at executeQuery (/app/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
2021-06-01T17:37:48.671130+00:00 app[web.1]:     at Client_MySQL.query (/app/node_modules/knex/lib/client.js:134:12)
2021-06-01T17:37:48.671130+00:00 app[web.1]:     at Runner.query (/app/node_modules/knex/lib/execution/runner.js:130:36)
2021-06-01T17:37:48.671131+00:00 app[web.1]:     at ensureConnectionCallback (/app/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
2021-06-01T17:37:48.671131+00:00 app[web.1]:     at Runner.ensureConnection (/app/node_modules/knex/lib/execution/runner.js:272:20)
2021-06-01T17:37:48.675663+00:00 app[web.1]: 17:37:48 ✨ request errored GET 500 /items/productos?fields=codigo,titulo,sku,costo,descripcion,descuento,imagenes.directus_files_id,inventario.cantidad,categorias.categorias_id.nombre&filter%5Binventario%5D%5B_nempty%5D=true 601ms
```

**Comment by rijkvanzanten** [comment] 2021-06-01 17:45
Is inventario a relational field?

**Comment by NightlyFlux** [comment] 2021-06-01 17:46
> Is inventario a relational field?
> 
> 

Yes it is

**Comment by rijkvanzanten** [comment] 2021-06-01 17:52
Ahh I see, it's thinking that `_nempty` is a field in `inventario`

**Comment by NightlyFlux** [comment] 2021-06-01 17:55
> Ahh I see, it's thinking that `_nempty` is a field in `inventario` 

Oh ok, is there a way I can validate if the field is empty with another filter rule?🤔

**Comment by rijkvanzanten** [comment] 2021-06-01 18:01
What you're trying right now should ideally work of course, but in the mean time, could you try to see if `filter[inventario][id][_nnull]=true` does the trick?

**Comment by NightlyFlux** [comment] 2021-06-01 18:06
> What you're trying right now should ideally work of course, but in the mean time, could you try to see if `filter[inventario][id][_nnull]=true` does the trick?

That did the trick thank you!

**Comment by rijkvanzanten** [comment] 2021-06-04 01:58
I believe this was fixed in RC70+ The updated way the API recognizes M2O fields seems to have resolved this issue as well (I can't reproduce it anymore at least). Could you confirm @NightlyFlux ?

**Closed by rijkvanzanten** 2021-06-04 01:58 UTC
Labels: API, Bug

**Comment by NightlyFlux** [comment] 2021-06-04 16:12
> I believe this was fixed in RC70+ The updated way the API recognizes M2O fields seems to have resolved this issue as well (I can't reproduce it anymore at least). Could you confirm @NightlyFlux ?

Still having the same result from before sadly...

**Comment by rijkvanzanten** [comment] 2021-06-04 16:14
Can you send a DB dump where this is happening? I couldn't reproduce it based on the information above 🤔

**Comment by NightlyFlux** [comment] 2021-06-04 16:20
Wish I could but I have a confidentiality agreement at work😕 But it basically thinks `_nempty` is a field from `inventario`

**Comment by rijkvanzanten** [comment] 2021-06-04 16:34
Hmm I see.. Could you maybe try setting up a dummy schema with just this relationship? 🤔

**Comment by NightlyFlux** [comment] 2021-06-04 16:35
Sure man as soon I get off work I'll do it!

**Comment by rijkvanzanten** [comment] 2021-06-04 16:41
Thanks a lot! 🙂
