### ISSUE TITLE
No Email string validation when creating a user

### ISSUE THREAD

**Issue by Rendmm** [directus/directus#4159] opened 2021-02-18 22:01 UTC
1) The issue and what you expected to happen
    I created a user via the app. And was able to save a nonvalid email like abc.
    I would expect to not be able to save the User, since she couldn't login with abc or to get at least a warning in the input field.

2) Exact steps to reproduce this issue
    create user with non valid email

3) Your environment:
    What version of Directus you are using. rc40
    Which DBMS are you using Postgres
    Which deployment are you using Docker
    What browser are you using FF 82

**Comment by rijkvanzanten** [comment] 2021-02-18 22:03
I _think_ i'm going to consider this a semi-duplicate of https://github.com/directus/directus/issues/2917

There's no way to currently have type-specific validation like that, so having #2917 allows us to enable the same for directus_users.email

**Closed** 2021-02-18 22:04 UTC
Labels: Duplicate
