### ISSUE TITLE
Data not always appearing when navigating

### ISSUE THREAD

**Issue by jimhuds** [directus/directus#17047] opened 2023-01-08 10:13 UTC
### Describe the Bug

When clicking different content tabs, sometimes no data is loaded and the table does not appear.

### To Reproduce

Clicking between parent content tabs will make nothing appear in the window. To get data to appear again I have to click a child tab first or refresh the page. I can see that the database queries are successful in my browser and in Directus logs. I have tried a different browser and also tried updating to the latest Directus and Node 18 versions. There are no filters or columns that shouldn't be there. I cannot work out what the problem is.

### Errors Shown

No errors shown.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.3

### What database are you using?

MariaDB

### What browser are you using?

Chrome,Safari

### How are you deploying Directus?

NPM/PM2

**Comment by azrikahar** [comment] 2023-01-08 11:00
Duplicate of #16883

**Closed by azrikahar** 2023-01-08 11:00 UTC
