### ISSUE TITLE
Unsupported media type - Image preview 

### ISSUE THREAD

**Issue by Vahagn-Zaqaryan** [directus/directus#23034] opened 2024-07-16 20:46 UTC
### Description

When uploading an SVG image in any Directus version v10.11.0 or above, the image preview displays "Unsupported media type."

### Actual behavior

Uploading an SVG image results in the preview displaying "Unsupported media type."
<img width="833" alt="image" src="https://github.com/user-attachments/assets/2123431e-9ca6-453e-8068-7e81b89b750e">

### Expected behavior

The image preview should display the SVG image properly, as it did in version v10.10.7.
<img width="854" alt="image" src="https://github.com/user-attachments/assets/fb0c0cb2-9810-456d-bb28-3fd3ed1e8695">

### To Reproduce

- Create a test collection.
- Add an image block to the collection.
- Upload any SVG image.
- The preview will show "Unsupported media type."

The issue exists in versions v10.11.0 and above. In version v10.10.7, the preview works correctly.

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 15

**Comment by paescuj** [comment] 2024-07-16 21:28
Thanks for opening this issue! However this is a duplicate of an existing issue #22461, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #22461 for future updates.

**Closed by paescuj** 2024-07-16 21:28 UTC
Labels: :cake: Regression, :file_folder: Forms, :elevator: Web, :fire::fire::fire:

**Comment by markosiilak** [comment] 2024-07-22 14:13
I see that also in v10.13.1
In my live version v10.7.2 it working correctly
