### ISSUE TITLE
Lost all relations between collections when I add or remove a now relation to an existing collection

### ISSUE THREAD

**Issue by db-conception** [directus/directus#14749] opened 2022-07-29 19:16 UTC
### Describe the Bug

I lost all relations on edited collection

### To Reproduce

Create a collection "hotel". 
Add a field (for exemple an integer  number of stars)
Add a translation field
On hotel_translation, add a field title 

Now create fake data
for hotel : 
{ id : 1, translations : {id: 1, title : "My hotel"}

Create a collection "room"
Add a name field to room
Add a many to one field to room, linked to hotel
Go back to hotel setting, and add a one to many field to rooms

Add rooms fake data : 
{id: 1, name: "Simple bedroom"}
{id: 2, name: "Suite"}
Link the two rooms to the hotel

See that the translation of the hotel is missing. 

If you don't reproduce, please add a new relation to hotel and check that you don't lost all relation to hotel (translation AND room)

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

16.15.1

### What database are you using?

I don't know

### What browser are you using?

Chrome

### How are you deploying Directus?

Directus cloud free version

**Comment by db-conception** [comment] 2022-07-29 19:17
I created few hours ago a thread on discord : https://discord.com/channels/725371605378924594/741330910594465823/1002624523784425492

**Comment by rijkvanzanten** [comment] 2022-07-29 20:12
I believe this is a duplicate of https://github.com/directus/directus/issues/13936, which was fixed in https://github.com/directus/directus/pull/14512, which will be launched to cloud shortly 👍🏻

**Closed by rijkvanzanten** 2022-07-29 20:12 UTC
Labels: Duplicate

**Comment by db-conception** [comment] 2022-08-14 14:50
Excuse me, but when the fix will be applied on the cloud ? I still lost all relations... I can't continue to work in this conditions....
When it will be deployed, Will I have something to do to get the update ? 

Regards

**Comment by rijkvanzanten** [comment] 2022-08-15 14:16
The current version of the platform can be found under settings at the bottom of the navigation bar. The above fix was included in v9.14.2, at time of writing, community cloud is at 9.15.1. If you have any issues with your instance, it's easiest to reach out to Cloud support directly through the chat widget on the cloud dashboard 🙂
