### ISSUE TITLE
Directus comment does not show up anywhere

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#14783] opened 2022-08-01 21:12 UTC
### Describe the Bug

I wanted to try out the new Comments feature just out of curiosity, however:

On version 9.14.5, when I comment something, it posts successfully, but then still says "No comments yet", even if I refresh the page.

![image](https://user-images.githubusercontent.com/4715129/182247518-c67c0255-f014-4702-924f-45617242c03c.png)

If I mention someone in this comment, his email and notifications get an alert, but the comment still doesn't show up when I click on the notification.

### To Reproduce

1. Go into an item
2. On the right side, expand "Comments"
3. Write a comment
4. _Abra kadabra_, it's gone.

### Errors Shown

No errors in the Browser console, no errors in the server terminal.

### What version of Directus are you using?

9.14.5

### What version of Node.js are you using?

v16.14.2

### What database are you using?

Postgres 13

### What browser are you using?

Chrome 103

### How are you deploying Directus?

Locally

**Comment by rijkvanzanten** [comment] 2022-08-01 21:14
Duplicate of https://github.com/directus/directus/issues/14608

**Closed by rijkvanzanten** 2022-08-01 21:14 UTC
