### ISSUE TITLE
Migrating from sqlite to postgres fails

### ISSUE THREAD

**Issue by abenz1267** [directus/directus#14507] opened 2022-07-19 10:05 UTC
### Describe the Bug

When trying to migrate an exported schema from sqlite to postgres, an error appears:

```
error alter table "Action" add constraint "action_parent_foreign" foreign key ("parent") references "Content" ("id") on delete SET NULL - foreign key constraint "action_parent_foreign" cannot be implemented
```

### To Reproduce

create schema via `directus schema snapshot` (from sqlite)

try to import via `directus schema apply` (to postgres 11)

Sqlite file is this one:
[data.db.zip](https://github.com/directus/directus/files/9139944/data.db.zip)

### What version of Directus are you using?

9.14.1

### What version of Node.js are you using?

18.2.

### What database are you using?

sqlite, postgres 11

### What browser are you using?

chrome

### How are you deploying Directus?

local

**Comment by azrikahar** [comment] 2022-07-19 10:07
Should be duplicate of #13988 👍

**Closed by azrikahar** 2022-07-19 10:07 UTC
Labels: Duplicate
