### ISSUE TITLE
Exception popup appears below deletion prompt when deletion fails in table layout

### ISSUE THREAD

**Issue by christianrr** [directus/directus#11173] opened 2022-01-19 20:32 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have a filter hook that prevents deletion under certain circumstances.

When I delete an item in table layout and press Delete/Confirm in the deletion prompt, the exception popup appears under the prompt.

When the deletion is triggered in the item detail page, the exception popup appears above the deletion prompt as expected.

![image](https://user-images.githubusercontent.com/10274479/150208571-ea6d8c16-755a-4abd-8d36-01f034484f87.png)

### To Reproduce

- Create a hook that prevents deletion
- Select item in table layout and press delete
- Press Delete/Confirm in deletion prompt
- Exception popup appears under deletion prompt

### Errors Shown

-

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-01-19 20:39
Duplicate of https://github.com/directus/directus/issues/10892

**Closed by rijkvanzanten** 2022-01-19 20:39 UTC
Labels: Bug (Potential)
