### ISSUE TITLE
Time report error on create column.

### ISSUE THREAD

**Issue by biapar** [directus/directus#9784] opened 2021-11-14 08:12 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I see that the created column report a wrong passed time. That is if I create an item now, it report “an hour ago”.
Could you use second,  minutes and so?

### To Reproduce

Create an item and see the time column in the table view.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

14

### What database are you using?

SQLite 

### What browser are you using?

All

### What operating system are you using?

Ubuntu and MacOs

### How are you deploying Directus?

Azure

**Comment by danilopolani** [comment] 2021-11-14 21:51
Hey, what's the timezone of your server and your database? If they're not `UTC`, can you try to set them at that value? For the server you can eventually do it at "runtime" like this: https://github.com/directus/directus/issues/7383#issuecomment-960306569

**Comment by azrikahar** [comment] 2021-11-15 02:37
I can't seem to reproduce this on my end based on the steps outlined:

https://user-images.githubusercontent.com/42867097/141712898-7b15f43e-1a1e-4f30-8167-1c2b067e5b7d.mp4

As @danilopolani mentioned, would you mind checking that? It'd also be great if you can check on the current latest version `9.0.1` just to be sure. There's also #9645 where their timezone is UTC +1 so it's not exactly a bug. 

If you have checked the above step on `9.0.1` and the problem still persists, can you provide more details such as:

- What is your current timezone in UTC?
- Can you reliably reproduce this on a fresh install? Perhaps a revised reproduction steps? If this is an actual bug, it definitely can be difficult to initiate a fix if we can't reproduce it on our end.
- Are you using the provided optional `date_created` field available when creating a new collection, or are you creating the datetime field yourself? 
- Can you confirm whether this field is of type `DateTime` or `Timestamp`?

**Comment by biapar** [comment] 2021-11-15 07:50
This column.
![image](https://user-images.githubusercontent.com/661517/141742572-c7706e0f-e8c3-40a7-8d81-369a230f0127.png)

**Comment by biapar** [comment] 2021-11-15 07:52
I tried now and report un hour ago.

![image](https://user-images.githubusercontent.com/661517/141742811-a5ecd585-f6e5-448e-98c4-d040c0eb16a6.png)

**Comment by azrikahar** [comment] 2021-11-16 04:50
> * What is your current timezone in UTC?
> * Can you reliably reproduce this on a fresh install? Perhaps a revised reproduction steps? If this is an actual bug, it definitely can be difficult to initiate a fix if we can't reproduce it on our end.
> * Are you using the provided optional `date_created` field available when creating a new collection, or are you creating the datetime field yourself?
> * Can you confirm whether this field is of type `DateTime` or `Timestamp`?

@biapar unfortunately there are still not enough information yet for us to reproduce this on our end. Can you provide answers to the questions above? 

> The time reported was an hour before my local time.

May I know what is the actual timezone, such as UTC +8 for example? Since I won't be able to know what is your local time as I don't think we have the same timezone here... 😅

**Comment by Oreilles** [comment] 2021-11-18 09:38
Seems like a duplicate of https://github.com/directus/directus/issues/7383 and https://github.com/directus/directus/issues/9645, both are using SQLite.

**Comment by danilopolani** [comment] 2021-11-18 17:34
> > * What is your current timezone in UTC?
> > * Can you reliably reproduce this on a fresh install? Perhaps a revised reproduction steps? If this is an actual bug, it definitely can be difficult to initiate a fix if we can't reproduce it on our end.
> > * Are you using the provided optional `date_created` field available when creating a new collection, or are you creating the datetime field yourself?
> > * Can you confirm whether this field is of type `DateTime` or `Timestamp`?
> 
> @biapar unfortunately there are still not enough information yet for us to reproduce this on our end. Can you provide answers to the questions above?
> 
> > The time reported was an hour before my local time.
> 
> May I know what is the actual timezone, such as UTC +8 for example? Since I won't be able to know what is your local time as I don't think we have the same timezone here... 😅

PS: The screenshot refers to Italy and right now we're GMT +1, so it perfectly matches this case ("an hour ago"). I guess it's just a misconfiguration of timezones?

**Comment by biapar** [comment] 2021-11-19 07:40
I'm in Italy and I see that the real date is in GMT time and not in local time.
Where to setting up the time zone?
Do Directus use the server time?

**Comment by danilopolani** [comment] 2021-11-19 10:44
I don't know much about this, but I think Directus (node + knex, actually) uses the server timezone. I found out, tho, that SQLite by default stores the datetime/timestamps as UTC: if I take a look to my SQLite DB, indeed, the unix timestamp is UTC, although other DB drivers such as Postgres store the date with timezone applied (+1). Using `TZ=UTC npx directus start` does nothing in my PostgreSQL project and neither does `TZ="Europe/Rome" npx directus start` for SQLite.

----

The approach I'd personally love is similar to Laravel: you have a `TIMEZONE` env variable (the [`DB_TIMEZONE`](https://github.com/directus/directus/issues/7383#issuecomment-898019175) here is not used anymore I guess) that manages the dates, so you don't leave this job to Knex, to any future library replacing it or to the server.
Then you have also have the ability to format the date while reading it.

In my own projects I always have `TIMEZONE=UTC`, so the dates are always stored as UTC and then I apply my own format (basically just pass the correct timezone) on read operations (global config / config per-collection / env). Maybe something similar could be possible with Directus too?

**Comment by rijkvanzanten** [comment] 2021-11-22 19:18
Duplicate of #7383

**Comment by rijkvanzanten** [comment] 2021-11-22 19:19
> In my own projects I always have TIMEZONE=UTC, so the dates are always stored as UTC and then I apply my own format (basically just pass the correct timezone) on read operations (global config / config per-collection / env). Maybe something similar could be possible with Directus too?

@danilopolani Yeah I'd normally do something similar too. However, in this particular case, we'll have to assume that other services and uses are modifying the database simultaneously with Directus, so we can't just assume things are UTC. 🤔

**Closed by rijkvanzanten** 2021-11-22 19:18 UTC
Labels: Needs More Info
