### ISSUE TITLE
Connection Info is not displayed properly

### ISSUE THREAD

**Issue by ngjoni** [directus/directus#11288] opened 2022-01-26 06:29 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

It is no longer possible to see the ping information of the connection correctly

### To Reproduce

Hover to the wifi symbol at the top left of your admin panel

![image](https://user-images.githubusercontent.com/49320058/151113857-3d2a9588-1d39-4a25-9ad3-9ac9cab458da.png)

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

Postgres 12

### What browser are you using?

Chrome, Safari

### What operating system are you using?

Windows, macOS

### How are you deploying Directus?

running on my self-hosted server

**Comment by azrikahar** [comment] 2022-01-26 06:37
Duplicate of #10260, fixed in #11263 (not released yet) 👍

**Closed by azrikahar** 2022-01-26 06:37 UTC
Labels: Bug (Potential)
