### ISSUE TITLE
Translation field does not support the alternative name

### ISSUE THREAD

**Issue by bronte2k7** [directus/directus#5374] opened 2021-04-29 19:40 UTC
Directus Version: 9.0.0-rc.61
Environment: development
OS: Linux Mint 20.1
Node: v14.16.1
Database: PostgreSQL 13.2
[2021-04-30 00:30:21.mp4.tar.gz](https://github.com/directus/directus/files/6401197/2021-04-30.00.30.21.mp4.tar.gz)

**Comment by rijkvanzanten** [comment] 2021-04-29 19:49
Duplicate of https://github.com/directus/directus/issues/3361

Next time, please fill out the issue template. It's there for a reason 👍🏻

**Closed by rijkvanzanten** 2021-04-29 19:49 UTC
Labels: Duplicate
