### ISSUE TITLE
users field order mixed for 10.8.3

### ISSUE THREAD

**Issue by swarmbotix** [directus/directus#21066] opened 2024-01-13 00:07 UTC
### Describe the Bug

custom fields in directus users collection order is messed up.

I haven't chanted anything but docker-compose.ytml
image: directus/directus:10.8.2 -> image: directus/directus:10.8.3

10.8.2
![Screenshot from 2024-01-12 16-05-34](https://github.com/directus/directus/assets/141169360/ed75f05f-884f-4a48-bcf0-8ba3ceb2fe01)

10.8.3
![Screenshot from 2024-01-12 16-06-53](https://github.com/directus/directus/assets/141169360/cb7b3b30-ab34-427b-8097-b3d86c1c183b)

### To Reproduce

updated from version 10.8.3 from 10.8.2

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-01-13 00:26
Thanks for opening this issue! However, this is a duplicate of #20894, which has been fixed in #20910. The fix will be available in the next release.

**Closed by paescuj** 2024-01-13 00:26 UTC
