### ISSUE TITLE
Issue with very high memory usage

### ISSUE THREAD

**Issue by arladmin** [directus/directus#21308] opened 2024-02-05 09:18 UTC
### Describe the Bug

Hi. This Directus instance, primarily deals with managing Video files, ranging from 500MB to 10GB in size.

The issue i'm facing is that after a few hours of instance restart, the instance's memory usage climbs upto 10GB (the max limit set in my case) where the instance then crashes and the cycle continues. 
The 'usage' here means uploading of video files (stored in S3).

Why such high memory usage?
What can i do to prevent/better manage it?

---

Example:
![image](https://github.com/directus/directus/assets/64059154/9c4a996c-4b4a-48c4-9a41-71bcf295c91c)

The 'event' here that triggered this exponential climb in memory usage is the uploading of a file (7.3 GB in size)
1. Why is the entire file being loaded into the memory, and not being directly streamed to its end destination (S3 storage in this case) ?
2. Even if the file was loaded into the memory first, the memory should have been cleared once the transfer was complete, right?
3. Another file (4.4 GB in size) was uploaded a few minutes after. That didn't seem to have any further effect though. Why?

### To Reproduce

..

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Custom) : Cloudron (https://docs.cloudron.io/apps/directus/)

**Comment by br41nslug** [comment] 2024-02-05 09:42
Looks like the AWS SDK may still be loading in the whole file into memory as it tries to concurrently do a multipart upload (tuned for max upload speed i presume) https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/src/Upload.ts#L97

**Comment by arladmin** [comment] 2024-02-05 09:44
Another example:

This is the behaviour when i upload the same file to a different Directus instance (hosted on a 4GB, 2vCPU DigitalOcean droplet, with standard docker-compose setup):

![image](https://github.com/directus/directus/assets/64059154/e56fa01d-5003-4156-b927-596fc738c310)

In this case, the excess memory usage is a 'paltry', 150MB, but the CPU usage is excessive. 
Nevertheless, after the upload process completes, the memory does dial back a bit, but still retains some of the load. Why?

**Comment by arladmin** [comment] 2024-02-05 09:48
Update: the remaining 'excess' memory usage disappeared in exactly 10 mins. time since the start of the upload process (Note: the upload process lasted only for 3 mins.) :

![image](https://github.com/directus/directus/assets/64059154/d05f4501-59a6-46b1-851a-962a37fdfb02)

Why?

**Comment by arladmin** [comment] 2024-02-05 09:49
@br41nslug 

> Looks like the AWS SDK may still be loading in the whole file into memory as it tries to concurrently do a multipart upload (tuned for max upload speed i presume) https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/src/Upload.ts#L97

What could be a fix/workaround to avoid/manage these (excessive resource utilisation) scenarios ?

**Comment by br41nslug** [comment] 2024-02-05 09:54
> What could be a fix/workaround to avoid/manage these (excessive resource utilisation) scenarios ?

Hard to say without knowing the cause. But from your graphs it looks to be S3 specific.

**Comment by arladmin** [comment] 2024-02-05 10:37
@br41nslug 

> > What could be a fix/workaround to avoid/manage these (excessive resource utilisation) scenarios ?
> 
> Hard to say without knowing the cause. But from your graphs it looks to be S3 specific.

Is there some basic triage that i can do in my systems, which can help you in quickly identifying the cause?

**Comment by binaryben** [comment] 2024-02-05 14:24
Is a possible work around to configure multiple storage options with one of them being a local store. Upload first to local store and then set up a flow to move it to S3? Unfortunately moving big files into the cloud has been a challenge for a long time and it would be difficult to fix properly if the issue is in the official AWS SDK.

**Comment by br41nslug** [comment] 2024-02-05 14:37
> Upload first to local store and then set up a flow to move it to S3?

That would indeed move the load from time of upload to whenever the flow runs but doesnt actually lessen memory usage, but it could definitely move the usage to less visited time.

**Comment by binaryben** [comment] 2024-02-05 14:43
> ... could definitely move the usage to less visited time.

Yeh, I should have been more explicit that was my intent. May also allow for scheduling the uploads to happen sequentially to make sure there isn't more uploads happening than the available memory can support.

**Comment by kulogix** [comment] 2024-02-14 18:28
Would be nice to provide tokenized S3 upload route directly to client, bypassing directus instance entirely. Then can configure webhook back to directus to notify when upload is complete -- or allow client to notify when it thinks it's done, and have directus call s3 to verify.

**Comment by rijkvanzanten** [comment] 2024-07-12 19:06
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2024-07-12 19:06 UTC
Labels: :elevator: Server
