### ISSUE TITLE
Wrong count of items when the Rule permisssion contains an M2M condition

### ISSUE THREAD

**Issue by Pachat** [directus/directus#17148] opened 2023-01-14 11:51 UTC
### Describe the Bug

Looks like the count is done on `SELECT` instead of `SELECT DISTINCT`

### To Reproduce

1. In a collection `test_one` add an M2M field `twos` to another collection `test_two` 
2. Add at least one item : ('one_1', ['two_1', 'two_2'])
3. For a role, set `All Access` to the collections `test_one`, `test_two` and `test_one_test_two`
4. List: the count is correct at 1
5. Set a read rule permission `{"_and":[{"twos":{"test_two_id":{"name":{"_contains":"two_"}}}}]}`

### Errors Shown

List: the count is wrong at 2

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

19.0.1

### What database are you using?

Postgresql 15

### What browser are you using?

Firefox & Edge

### How are you deploying Directus?

VPS

**Comment by azrikahar** [comment] 2023-01-16 05:31
Can confirm this issue, which most likely has the same root cause as #17028. I believe both are related to #14798, judging from their occurrence from `9.22.x` onwards.

Closing this in favor of #17028.

**Closed by azrikahar** 2023-01-16 05:31 UTC
