### ISSUE TITLE
Cannot apply snapshot

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#8132] opened 2021-09-18 12:29 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I get the following error after trying to apply a snapshot:
```
14:17:12 🚨 error 
        SELECT c.table_name
          , c.column_name
          , c.column_default as default_value
          , c.data_type
                                        , c.character_maximum_length as max_length
          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity
          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable
        FROM
          information_schema.columns c
        LEFT JOIN information_schema.tables t
          ON c.table_name = t.table_name
        WHERE
          t.table_type = 'BASE TABLE'
          AND c.table_schema IN ($1);
       - current transaction is aborted, commands ignored until end of transaction block 
error: 
        SELECT c.table_name
          , c.column_name
          , c.column_default as default_value
          , c.data_type
                                        , c.character_maximum_length as max_length
          , CASE WHEN c.is_identity = 'YES' THEN true ELSE false END is_identity
          , CASE WHEN c.is_nullable = 'YES' THEN true ELSE false END is_nullable
        FROM
          information_schema.columns c
        LEFT JOIN information_schema.tables t
          ON c.table_name = t.table_name
        WHERE
          t.table_type = 'BASE TABLE'
          AND c.table_schema IN ($1);
       - current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/project_path/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/project_path/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/project_path/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/project_path/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
error Command failed with exit code 1.
```

### To Reproduce

This is what I did:
1) drop all my tables
2) run `npx directus bootstrap`
3) run `npx directus database migrate:latest`
4) make changes to some collections & fields
5) run `npx directus schema snapshot ./snapshot.yaml`
6) drop all my tables again
7) (This might be the problem) Add some missing foreign keys to my migrations. Example: `table.foreign('user_id').references('directus_users.id')` 
8) run `npx directus bootstrap`
9) run `npx directus database migrate:latest`
10) Finally run `npx directus  schema apply ./snapshot.yaml`

### What version of Directus are you using?

9.0.0-rc.93

### What version of Node.js are you using?

14.17.3

### What database are you using?

PostgreSQL 13.2.1

### What browser are you using?

Not relevant

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2021-09-18 16:20
Are you using any groups by chance? Would you be able to share this snapshot (either here or in private through rijk@directus.io) ?

**Comment by mattiaz9** [comment] 2021-09-18 16:33
I'm afraid I deleted that snapshot and restarted from the ground.
However I believe I was using a group at some point, but I'm not entirely sure.

**Comment by rijkvanzanten** [comment] 2021-09-19 00:40
I'll consider it a duplicate of https://github.com/directus/directus/issues/8113 then :) we can reopen this issue of it turns out to be something else 👍🏻

**Closed** 2021-09-19 00:40 UTC
Labels: Duplicate
