### ISSUE TITLE
Unable to use date interface anymore

### ISSUE THREAD

**Issue by kosicielPL** [directus/directus#8321] opened 2021-09-25 20:09 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Picking any of properties of date interface (day, month, year) causes whole dialog box to close without assigning any value. 

### To Reproduce

1. Update directus to newest wersion
2. Establish date property on any collection
3. Try to pick specific date/time from date interface dialog box

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

4.17.6

### What database are you using?

Postgres 13

### What browser are you using?

Any

### What operating system are you using?

Ubuntu 20.04

### How are you deploying Directus?

DigitalOcean droplet

**Comment by rijkvanzanten** [comment] 2021-09-25 20:39
Duplicate of https://github.com/directus/directus/issues/8313, which was a duplicate of https://github.com/directus/directus/issues/8250.

**Closed** 2021-09-25 20:39 UTC
Labels: Duplicate
