### ISSUE TITLE
Locked System Fields displaying additional editable field

### ISSUE THREAD

**Issue by abertay-university** [directus/directus#6709] opened 2021-07-07 15:11 UTC
### Describe the Bug

When viewing a system collection, I see 2 fields for each field. One is locked, the other I can make changes to.

![image](https://user-images.githubusercontent.com/31690037/124783885-4fd09180-df3d-11eb-911c-077f0f676f2e.png)

### To Reproduce

1. Go to Setting > Data Models
2. Change the view to enable System Collections
3. Click on a collection eg Directus Files

### What version of Directus are you using?

9.0 r83

### What version of Node.js are you using?

14.17.2

### What database are you using?

MySQL

### What browser are you using?

Firefox 89

### What operating system are you using?

macOS 11.4

### How are you deploying Directus?

Linux Web Server

**Comment by starina** [comment] 2021-07-07 16:28
Yup, the same is on Windows 10, localy hosted, r83..

**Comment by rijkvanzanten** [comment] 2021-07-12 13:06
Duplicate of https://github.com/directus/directus/issues/6684

**Closed by rijkvanzanten** 2021-07-12 13:06 UTC
Labels: Bug (Potential)
