### ISSUE TITLE
Need page refresh to update the content

### ISSUE THREAD

**Issue by chetank628** [directus/directus#17020] opened 2023-01-04 20:55 UTC
### Describe the Bug

Switching between the content gives a blank page need to refresh the page to see the content
I am using the latest Docker image from Directus with the default configuration it was working fine earlier on the older version

https://user-images.githubusercontent.com/10745374/210648151-804034bc-45dd-4809-b80c-27207a5e9f38.mov

### To Reproduce

1)select any content and add data to that content  and save
2)select another content to insert data and gets a blank page 

### Errors Shown

blank screen

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18.+

### What database are you using?

sqlite

### What browser are you using?

edge

### How are you deploying Directus?

Docker official image

**Comment by rijkvanzanten** [comment] 2023-01-04 20:56
Duplicate of https://github.com/directus/directus/issues/16883

**Closed by rijkvanzanten** 2023-01-04 20:56 UTC
