### ISSUE TITLE
WYSIWYG editor beaks in combination with translations

### ISSUE THREAD

**Issue by maltejur** [directus/directus#12200] opened 2022-03-16 21:05 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Having a WYSIWYG editor as a "translated" field does not seem to work, the content just won't get saved.

https://user-images.githubusercontent.com/48161361/158689568-1ccab5a4-8d22-4723-964f-08dfb0d2cb6d.mp4

### To Reproduce

1. Create a new project (`npm init directus-project example-project`) and use sqlite
2. Create a new data model `test`
3. Add a "WYSIWYG" field to `test` called `content` (with all the default values)
4. Add a "Translations" field to `test` called `translations` (with all the default values)
5. Add a "WYSIWYG" field to the newly created data model `test_translations` called `content` (with all the default values)
6. Try to create a new entry in `test` and fill out both WYSIWYG fields with data
7. Observe that either a completely new entry was created or that the translated field is empty

You can repeat the same steps with a "Textarea" instead of a "WYSIWYG" and everything works fine.

### Errors Shown

There are no error popups, no errors in the console and the server just sends successful status codes. It seems though the error is client-side since judging from the network tab in the dev console, the content of the WYSIWYG field is never sent to the server.

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

14.19.0

### What database are you using?

sqlite 3.38.1

### What browser are you using?

LibreWolf (Firefox), also tested with Chromium

### What operating system are you using?

Arch Linux

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2022-03-16 22:32
Duplicate of https://github.com/directus/directus/issues/12005

**Closed by rijkvanzanten** 2022-03-16 22:32 UTC
Labels: Bug (Potential)
