### ISSUE TITLE
Collection not loading for user with Custom Item Permission 

### ISSUE THREAD

**Issue by stgonzales** [directus/directus#8073] opened 2021-09-16 11:51 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

❕ _Similar issue(#7286). Only open another one according to @rijkvanzanten instructions._

After setting a custom Item Permission in a Role, users in that role can't see the collection content.
I have two collections (`Site` and `Text`), collection `Text` has a relational field `Many to One` with `Site`.
The collection `Text` also have relational fields with other collections. 
Some users have permission to see specific items in the collection `Text`,  so I use a custom Item Permission in the user Role to filter `Text` collection items with a specific `site_ id`: 

```
{
    "site_id": {
        "_eq": "a994fc30-c0af-4b63-bd92-ea960eb72562"
    }
}
```

After that when the user tries to open the collection it keeps only loading.

![image](https://user-images.githubusercontent.com/12421471/133605837-1b9f0e5f-4286-4d3a-8ed2-1dc24647f561.png)

And the message error `Cannot read properties of undefined (reading 'related_collection')` on the console:

![image](https://user-images.githubusercontent.com/12421471/133605964-fc4ea883-d30a-465a-8b79-eb51fc96783c.png)

### To Reproduce

1. Create two collections and create a `Many to One` relation on the **second** collection with the **first**.
2. Create a new user and new Role with a custom read item permission on the **second** collection and full read permission on **first** collection.
3. Login with the new user and try to open the collections.

These were the steps that I did before opening this issue.

### What version of Directus are you using?

v9.0.0-rc.92

### What version of Node.js are you using?

v14.17.0

### What database are you using?

PostgreSQL 13.4 (Debian 13.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by azrikahar** [comment] 2021-09-21 08:07
Hi, when you set the filter rule for that role, were the fields permissions set/checked? I was able to reproduce the error (albeit slightly different error, mine is `(reading 'fields')`), but once I ensure the fields are checked, it was resolved in my case. 

When I follow the 2nd step in your reproduction step, the field permissions aren't selected after we set item permissions only. Here's what I meant:
![RYeg4Ce2SE](https://user-images.githubusercontent.com/42867097/134135098-a251fd3e-7a9c-44f2-a4be-e3e168eea74a.gif)

**Comment by stgonzales** [comment] 2021-09-22 10:03
Hi @azrikahar,

> were the fields permissions set/checked?

Yes, all the fields are checked

https://user-images.githubusercontent.com/12421471/134324192-f8b7ffbc-9f01-4d1a-a803-3f50010ee9b3.mov

.

**Comment by azrikahar** [comment] 2021-09-24 02:38
@stgonzales thanks for the clear video! definitely helped to clear things up as I thought when you mentioned "full read permission" meant "Full Access" in my previous test.

Unfortunately, I am still unable to reproduce this on rc.92, with the same configurations you described on your issue & what is shown in your video (attached my video here, let me know if I missed anything). My current suspicion would be on the `The collection Text also have relational fields with other collections.` you described. 

Would you mind trying out the reproduction steps you shared _without_ any relational fields on your end? It'll be very helpful for us to narrow down on the actual root cause here 👍

---

https://user-images.githubusercontent.com/42867097/134609864-c80de7e0-c48f-4c62-9d49-08bb93ebdd7e.mp4

**Comment by joselcvarela** [comment] 2021-09-24 06:17
Maybe you can share a reproducible database dump @stgonzales I think it would be easier.

**Comment by rijkvanzanten** [comment] 2021-12-03 01:04
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-12-03 01:04 UTC
Labels: Needs More Info
