### ISSUE TITLE
No data displayed after tab switch

### ISSUE THREAD

**Issue by MrBond2104** [directus/directus#16898] opened 2022-12-23 16:21 UTC
### Describe the Bug

Today I tried to move my Directus and encountered the following problem: The data tables are displayed in directus. But as soon as I switch tabs, the data window remains empty. I have to manually refresh the page to see data.

### To Reproduce

My old instance is running version 9.20.4.
My new instance in version 9.22.1.

The database was cloned 1 to 1 and accordingly updated with npx directus database migrate:latest.
.env and uploads are the same.

### Errors Shown

![image](https://user-images.githubusercontent.com/69170694/209366676-f2619ced-7de4-4c99-bfac-0aa6a38c77ba.png)

After manual refresh:
![image](https://user-images.githubusercontent.com/69170694/209366766-099d63c3-7ca0-4933-82a7-d6c20baf2d99.png)

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

v18.12.1

### What database are you using?

10.5.18-MariaDB-0+deb11u1 Debian 11

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2022-12-23 16:22
Duplicate of https://github.com/directus/directus/issues/16883

**Closed by rijkvanzanten** 2022-12-23 16:22 UTC
