### ISSUE TITLE
Field condition don't work with $CURRENT_USER (neither $CURRENT_ROLE)

### ISSUE THREAD

**Issue by Pachat** [directus/directus#12726] opened 2022-04-13 10:35 UTC
### Describe the Bug

When assign $CURRENT_USER.id in a Filed's Filter Condition, the filter is not working.

### To Reproduce

1. Create MyCollection with `user_created`, `input_visible` and `input_hidden`
2. Set the following condition on `input_hidden` so that only the `user_created` should see it
```
{
	"_and": [
		{
			"user_created": {
				"id": {
					"_neq": "$CURRENT_USER.id"
				}
			}
		}
	]
}

```
with `Hidden on detail`
3. Give access to another role 
3. Create an element and save it
4. Connect as as user of the other role you gave access to
5. On the list click the row of the element

### Errors Shown

1. As another user than the one who created the item, you will still see the column `input_hidden` and its value

2. After clicking you will get the error message `[FORBIDDEN] You don't have permission to access this.`

3. Nevertheless, after clicking `Dismiss`, you will access to the element including `input_hidden` and its value

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.0

### What database are you using?

SQLite version 3.37.0

### What browser are you using?

Firefox and Edge

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-04-13 10:50
This is the current expected behavior, and has been documented in the [Filter Rule's Dynamic Variables](https://docs.directus.io/configuration/filter-rules/#dynamic-variables) notice, specifically:

> Note: This feature is only available for permissions, validation, and presets. Regular filters and **conditional fields** currently only support the root ID.

On that note, there are also PRs #9539 and #9572 aiming to add support to filters and conditional fields respectively. I'll proceed to close this since it is not an unexpected bug 👍

**Closed by azrikahar** 2022-04-13 10:50 UTC
Labels: Bug (Potential)

**Comment by azrikahar** [comment] 2022-06-09 12:59
@piotr-cz it should work. There were some issues in the past but #10882 and #11423 should have fixed it. If you discover any issue with it in the latest version, feel free to share more detail on it with a minimal reproducible setup so that we can investigate it further 👍

**Comment by piotr-cz** [comment] 2022-06-09 13:05
@azrikahar 
Thanks, but it just doesn't work for my case (see https://github.com/directus/directus/discussions/9682#discussioncomment-2911547).

I'm not sure if I'm doing something wrong it it's been removed in https://github.com/directus/directus/pull/10576#issuecomment-1003481572

**Comment by azrikahar** [comment] 2022-06-09 14:22
@piotr-cz Thanks for creating the issue. The team will check on it when possible.
