### ISSUE TITLE
If empty relations, in display no-value in M2M 

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1723] opened 2017-08-07 14:51 UTC
## Version Info
  - Directus version and branch: 6.4 develop
  - PHP version: 7.0
  - MySQL version: 5.7
  - Web server: nginx
  - OS name and version: Ubuntu 16.04

## Actual Behavior
If item no relations values, display no-value in M2M fields

## Schema Dump, Logs, or Screenshots
![1](https://user-images.githubusercontent.com/4669992/29031995-a436592e-7b98-11e7-96d7-26b860d59895.PNG)

![2](https://user-images.githubusercontent.com/4669992/29031992-a2509d2c-7b98-11e7-83c3-24023626aebb.PNG)

**Comment by WellingGuzman** [comment] 2017-08-07 15:51
Hey @dsivokhin can be please be more specific what's the issue is all about and steps on how to replicate or an example schema?

**Comment by dsivokhin** [comment] 2017-08-08 08:06
Sorry for small info. It's easy to reproduce. I attached the shema. 
1. Open table 'products'
2. Open first item 'TestProduct-1'

'TestProduct-1' has not relations for 'photos' and 'catalogs' but them display as empty values.

![1](https://user-images.githubusercontent.com/4669992/29062117-1351f53a-7c29-11e7-9933-ca794cb9b70f.PNG)

[test_directus.zip](https://github.com/directus/directus/files/1207234/test_directus.zip)

**Comment by WellingGuzman** [comment] 2017-08-09 06:19
Thanks for the information and the schema @dsivokhin.

It has been fixed by https://github.com/directus/directus/commit/dd871139b740a99af17f4cadcd779f0287613df4

**Closed** 2017-08-09 06:18 UTC
Labels: 4. Minor, Can Not Duplicate, Interface, Relational
