### ISSUE TITLE
Directus 9.22.1 - Image upload crashes the whole app

### ISSUE THREAD

**Issue by michael-scheurer** [directus/directus#17033] opened 2023-01-06 10:11 UTC
### Describe the Bug

Whenever we upload the following image, the whole directus application crashes.

<img width="651" alt="Roger" src="https://user-images.githubusercontent.com/70939054/210978257-5d0a6aef-801f-4fd1-aeae-3ba77ce3743e.png">

### To Reproduce

- Spin up Directus v9.22.1
- Upload the following image, to make sure image upload works in general: 
![tomate](https://user-images.githubusercontent.com/70939054/210978902-a928582f-1d49-4228-9cff-28eb8b9cd1da.jpg)

- Upload the following image
<img width="651" alt="Roger" src="https://user-images.githubusercontent.com/70939054/210978639-c0a138a1-2e07-4335-b057-c98491d656b3.png">

- App crashes or is unable to upload this specific image. Even after removing all exif data

Or use the reproduction Directus instance I spin up for you:

url: fb4cvbhzerj4zlxe6551.cleaver.rocks
user: reproduction-directus@seccom.ch
Y$Z[1430_caV7#_C|[8$l/lVcv'xp4e&,%h2IkJ9

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

16 or 18 doesn't matter

### What database are you using?

Postgres 15

### What browser are you using?

Brave, Chrome, Firefox

### How are you deploying Directus?

Locally, Red Hat Openshift, Cleavr.io, it doesn't matter

**Comment by br41nslug** [comment] 2023-01-06 10:47
Duplicate of #16971 will be in the next release.

**Closed by br41nslug** 2023-01-06 10:47 UTC
Labels: API, Bug
