### ISSUE TITLE
Directus container suddenly exits

### ISSUE THREAD

**Issue by NafunaAfrica** [directus/directus#19943] opened 2023-10-07 13:58 UTC
### Describe the Bug

I am using the directus docer-compose file. It spins up redis, directus and posgres. I am running front end on a cdn. I am using nginx proxy manager and started getting CORS errors after deploy. I then added this code to allow origins:

proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Connection '';
chunked_transfer_encoding off;
proxy_buffering off;
proxy_cache off;

add_header 'Access-Control-Allow-Origin' '*';
add_header 'Access-Control-Allow-Credentials' 'true';
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Accept';
add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';

but after I use the app for a bit, directus container will exit after an hour or so of usage.

My second instance of directus is running without a problem but I am not using it in production. I deployed these at the same time. Can a CORS make directus exit?

### To Reproduce

Use portainer and run directus docker-compose from documentation. Using standard digital ocean ubuntu 22 VM with 1GB ram. Using enginx proxy manager with the above code and running sveltekit file that's using SDK to fetch

### Directus Version

10.4.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-10-07 15:22
No CORS cannot crash the instance as it is something done by the Browser not the server. Could you provide any errors you are getting on the server side when it crashes?

**Comment by NafunaAfrica** [comment] 2023-10-08 05:52
Thats where the mystery is for me: 
![image](https://github.com/directus/directus/assets/84924809/861ba975-8319-4c83-b30c-fd84dd6cc593)

everything looks ok in the container logs but this is how the containers will be looking: 
![image](https://github.com/directus/directus/assets/84924809/348b4c5d-9c78-422e-a2d3-adaf4730ad09)

**Comment by azrikahar** [comment] 2023-10-09 03:47
> Using standard digital ocean ubuntu 22 VM with 1GB ram

Can you share how many containers are running in this particular droplet in total? I wonder if it's "exiting" due to insufficient memory rather than an actual crash, at least due the seemingly arbitrary reason for exiting and without a clearer way to reproduce this behavior. 

> My second instance of directus is running without a problem but I am not using it in production.

Perhaps especially if this second instance is in a separate droplet, even if it also only has 1GB ram, with potentially less containers running as it's not in production (very wild guess here)

**Comment by paescuj** [comment] 2023-10-09 12:32
Hey there @NafunaAfrica, thank you for opening this issue! However, with the given information it's not possible to make safe assumptions about the possible causes or reproduce the issue on our end.
Please take a look at https://github.com/directus/directus/issues/19943#issuecomment-1752308246 and also ensure you're using the latest version of Directus ([v10.6.3](https://github.com/directus/directus/releases/tag/v10.6.3) at this point in time). I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by paescuj** 2023-10-09 12:32 UTC
Labels: Needs More Info
