### ISSUE TITLE
Edit Schema Issue

### ISSUE THREAD

**Issue by manoj1090** [directus/directus#2608] opened 2020-03-12 12:42 UTC
# Bug Report

## Steps to Reproduce
Directus Version: 8.6.2
1. Go to the created collection for example "category",
2. In category name field is defined as unique, 
3. After creating category collection we need to remove that unique from name field,
4. But it not getting updated.

**Comment by fairbairn** [comment] 2020-04-30 22:04
This bug still exists.

**Comment by rijkvanzanten** [comment] 2020-05-11 14:18
Duplicate of https://github.com/directus/app/issues/2780

**Closed by rijkvanzanten** 2020-05-11 14:18 UTC
