### ISSUE TITLE
Migration from 10.10.5 to 10.12.1 fails

### ISSUE THREAD

**Issue by Pachat** [directus/directus#22720] opened 2024-06-11 02:08 UTC
### Describe the Bug

First fail
>in file /node_modules/knex/lib/dialects/postgres/schema/pg-tablecompiler.js just replace the 3 occurences of
drop constraint by drop constraint if exists

still not corrected in 10.12.1 so migrate:latest from 10.10.5 to 10.12.1 doesn't work
see #22120

Then modifying the file by hand, leads to another error
> alter table "directus_fields" add constraint "directus_fields_group_foreign" foreign key ("group") references "directus_fields" ("id") - foreign key constraint "directus_fields_group_foreign" 
 cannot be implemented	
	Key columns \"group\" and \"id\" are of incompatible types: character varying and integer.	

Anyhow the bare new v10.12.1 DB does not contain a "directus_fields_group_foreign"

### To Reproduce

After importing a 10.10.5 sql to replace a PostgreSQL db of a new Directus v10.12.1, 
apply `npx directus database migrate:latest`

### Directus Version

v 10.12.1

### Hosting Strategy

Self-Hosted (Custom)

### Database

 PostgreSQL 15

**Comment by br41nslug** [comment] 2024-06-11 13:38
I have not been able to reproduce this on a clean update from `10.10.5` to `10.12.1`. Please provide detailed reproduction steps for how to get into this situation on a fresh Directus instance or provide the dump for this specific instance.

None of these errors should be caused by the 2 migrations in this update step so Im guessing this is still a remnant from a previous failed migration or database dump.


https://github.com/directus/directus/assets/9389634/d5b96e9e-8567-4404-961c-defa81805fcb

1. new database for version 10.10.5
2. interact with the app, create a collection
3. update to 10.12.1, no migration issues

Closing this issue for now but happy to re-open if we can get it reproducable, until then lets track it over here which seems to be the issue that got you in this error state https://github.com/directus/directus/issues/22120

**Closed by br41nslug** 2024-06-11 13:38 UTC
Labels: :detective: Needs More Info
