### ISSUE TITLE
preview_url is included in snapshots.yml

### ISSUE THREAD

**Issue by LABCAT** [directus/directus#20427] opened 2023-11-15 01:03 UTC
### Describe the Bug

This is probably intended but quite undesirable if you use the snapshots.yml file to migrate your collections and fields between different environments.

I have an automated pipeline set up that apply the snapshot when changes are deployed to new environments. 

Now after every deployment, I have to login to the CMS and update the preview for all collections that have.

Ideally we could instead use something like {{env.MY_ENV_VAR}}/{{id}} in the preview url. Alternatively removing preview_url from snapshots would also solve the issue (or even an opt out).

### To Reproduce

Add a preview URL to any collection and then run:

`npx directus schema snapshot ./snapshot/snapshot.yaml`

Then view the newly created snapshot.yaml and you will see it contains this:

`preview_url: >-
        http://localhost:3000/{{id}}

### Directus Version

10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2023-11-15 10:42
This is unfortunately neither a bug nor a tiny tweak 🤔 Could you create a [Feature Request](https://github.com/directus/directus/discussions/categories/feature-requests) for this instead? Because this will require some more thought on what the best solution is and how it should be implemented in both the CLI and API.

Closing this for now as technically working as intended.

**Closed by br41nslug** 2023-11-15 10:42 UTC
