### ISSUE TITLE
Frontend: Content table stop showing items

### ISSUE THREAD

**Issue by tinchoz49** [directus/directus#17059] opened 2023-01-09 14:40 UTC
### Describe the Bug

After I switch between different collections in the frontend the datatable stop listing the items.

https://user-images.githubusercontent.com/819446/211333037-d6b1ca72-36e0-4970-b7bd-d90bb32d32eb.mov

### To Reproduce

1. Create a new project with  `npm init directus-project`
2. Use sqlite or postgres (i tested with both)
3. Start the clean project
4. Create 2 collections so you can switch between them
5. Follow the video reproduction

### Errors Shown

no, there are not errors.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

16.18.1

### What database are you using?

sqlite

### What browser are you using?

brave

### How are you deploying Directus?

running locally

**Comment by br41nslug** [comment] 2023-01-09 14:44
Duplicate of https://github.com/directus/directus/issues/16883 will be fixed with the next release

**Closed by br41nslug** 2023-01-09 14:44 UTC
