### ISSUE TITLE
Updating one to many related item, duplicates item of another relation.

### ISSUE THREAD

**Issue by sksar** [directus/directus#12881] opened 2022-04-20 15:31 UTC
### Describe the Bug

I have three collections
Products
Bills
Bill_items

Bill_items has relation with a bill and product. (Acting as many to many)
I can successfully create bill, and using the relational interface I can also create the bill_items.
But when I go and edit the bill item, it goes and tries to create another new product.

My guess is the relationship is not working, it is thinking to create a new product.

### To Reproduce

Here is the original video link in high res: https://drive.google.com/file/d/1pSTnKc6QE9IKVMXLac7M1q9BWM8ousfu/view?usp=sharing

https://user-images.githubusercontent.com/11752260/164266718-262024c5-7d6c-4ed1-bc56-ccf0c106ae63.mp4

As you can see in the video, I created a new bill and added a new bill_item (which has a relationship with the product)
Now when I save, go back and edit the bill item (from within bills collection) and then save it, it tries to create a new product.
(As you will see I had to disable the unit and code of the product for it to work, or it was saying unit is required cause when creating a new product it is required)

My guess is I think the interface might be trying to create a new product. The GraphQL API works fine though.

Note: if I update the bill item directly it works fine.

Here is a screenshot of the error in the browser console, 
I think in the product it should be product: <id>, (like product: 2), 

<img width="1259" alt="Screenshot 2022-04-20 at 21 18 54" src="https://user-images.githubusercontent.com/11752260/164271550-6ee30201-ddcb-4354-bfc6-4243b9dcb766.png">

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.13.2

### What database are you using?

mysql

### What browser are you using?

Chrome, Safari

### How are you deploying Directus?

local

**Comment by sksar** [comment] 2022-04-20 15:54
> I think this is already fixed in #12840 🙂

Just to add, I have attached 
<img width="1259" alt="Screenshot 2022-04-20 at 21 18 54" src="https://user-images.githubusercontent.com/11752260/164271847-1a708bdd-3b53-4dc4-921b-c5c7e225513c.png">
a screenshot.

From the looks of it, I do think that in the JSON it should be 
```
product: <id>
```
instead of 
```
product: { code: "", title: "" }
```

**Comment by u12206050** [comment] 2022-04-21 17:34
Have the same issue, forced to roll back to 9.8.0 since client can't update anything through relationship without getting this error.

**Comment by u12206050** [comment] 2022-04-21 19:26
Could do with a hot fix release for this issue @rijkvanzanten?

**Comment by rijkvanzanten** [comment] 2022-04-22 15:53
I wasn't able to reproduce this after the fixes #12840 were merged, so we should be good 👍🏻

**Comment by sksar** [comment] 2022-04-22 21:14
I updated the instance to v9.9.1 just now, and the result is still the same. As shown in the video.

**Comment by rijkvanzanten** [comment] 2022-04-22 21:14
@sksar Could you share a database dump with a minimal reproduction to test with? I tried setting up a fresh instance based on the video you shared, but wasn't able to reproduce it 🤔

**Comment by sksar** [comment] 2022-04-22 21:15
@rijkvanzanten  Yes, I am sharing the database dump. Send me your email.

**Comment by rijkvanzanten** [comment] 2022-04-22 21:16
You can share it to rijk@directus.io 👍🏻

**Comment by u12206050** [comment] 2022-04-22 21:19
Can confirm, still getting same error response.
Based on the payload in the network tab I see that a relation is part of the payload even though I am not changing that relation at all:

```
person->registration->event

Updating registration (change status to cancelled), payload:

{"registrations":{
  "create":[],
  "update": [{
      "id":"8618abc9-6d6c-4c0a-8e48-5a3ef169679c",
      "event":{"reference":"FHSA012322"},
      "status":"cancelled"
    }],
  "delete":[]
}}
```
As you see this part `"event":{"reference":"FHSA012322"},` shouldn't be there

**Comment by sksar** [comment] 2022-04-22 21:22
> Can confirm, still getting same error response. Based on the payload in the network tab I see that a relation is part of the payload even though I am not changing that relation at all:
> 
> ```
> person->registration->event
> 
> Updating registration (change status to cancelled), payload:
> 
> {"registrations":{
>   "create":[],
>   "update": [{
>       "id":"8618abc9-6d6c-4c0a-8e48-5a3ef169679c",
>       "event":{"reference":"FHSA012322"},
>       "status":"cancelled"
>     }],
>   "delete":[]
> }}
> ```
> 
> As you see this part `"event":{"reference":"FHSA012322"},` shouldn't be there

Yes, I think that is the same as the one above where I have shared a screenshot.

**Closed** 2022-05-09 19:53 UTC
Labels: App, Bug

**Comment by u12206050** [comment] 2022-06-24 14:21
This is issue seems to be back. I have users of a specific role that are unable to update a related item, when said related item has another relation (which the user may not update) as part of the display:

<img width="595" alt="Screenshot 2022-06-24 at 16 20 27" src="https://user-images.githubusercontent.com/6641242/175555216-2f2c8e7c-1178-4777-a6fa-ec37f50f6830.png">

As you can see, here I am trying to update the related `registration` item, which is displaying the event reference.
Even though I just changed the `status` and `managed_by` fields on `registration` I get access denied because I am not allowed to edit `event`

**Comment by rijkvanzanten** [comment] 2022-06-24 14:43
> This is issue seems to be back. I have users of a specific role that are unable to update a related item, when said related item has another relation (which the user may not update) as part of the display:
> 
> <img alt="Screenshot 2022-06-24 at 16 20 27" width="595" src="https://user-images.githubusercontent.com/6641242/175555216-2f2c8e7c-1178-4777-a6fa-ec37f50f6830.png">
> 
> As you can see, here I am trying to update the related `registration` item, which is displaying the event reference. Even though I just changed the `status` and `managed_by` fields on `registration` I get access denied because I am not allowed to edit `event`

Tracking that in https://github.com/directus/directus/issues/13765 👍🏻
