### ISSUE TITLE
Creating an item in a collection via POST returns a completely different (existing) item

### ISSUE THREAD

**Issue by ravolta-io** [directus/directus#7113] opened 2021-07-31 10:53 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When doing a POST to create a new item in a collection, the response is a completely different item. 

I am using Axios to send the request from a React application.

1. This is the payload I sent to the API
<img width="741" alt="Schermafbeelding 2021-07-31 om 12 33 53" src="https://user-images.githubusercontent.com/47642986/127737531-ac6bfb2c-ef8b-44a0-8640-3ddbe371d94e.png">

2. This is the response
<img width="718" alt="Schermafbeelding 2021-07-31 om 12 34 04" src="https://user-images.githubusercontent.com/47642986/127737543-4ddaa677-9ee0-4676-9052-95859b67d6a7.png">
Judging by the property deck_name we see it's a completely different item. However, the newly created item is correctly created in the database and the correct relations are there. So it's just the response that's wrong.

### To Reproduce

1. Have a collection with some items in them
2. Create a new item using POST via the API
3. Log the request response
4. See a different item is returned instead of the newly created one

### What version of Directus are you using?

v9.0.0-rc.87

### What version of Node.js are you using?

v12.18.3

### What database are you using?

Postgres 13

### What browser are you using?

Brave/Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

manually to DigitalOcean Droplet

**Comment by rijkvanzanten** [comment] 2021-07-31 18:02
Duplicate of https://github.com/directus/directus/issues/6279

**Closed by rijkvanzanten** 2021-07-31 18:02 UTC
Labels: Duplicate
