### ISSUE TITLE
Backoffice GUI bugs

### ISSUE THREAD

**Issue by lucrp** [directus/directus#10351] opened 2021-12-07 00:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I'm doing a tutorial about Directus to test the CMS, and in the video, the instructor uses version 9.0.1. I installed Directus in a Docker container following and copying/pasting the exact same docker-compose.yml lines in the [Docs](https://docs.directus.io/getting-started/installation/docker/#docker-compose). 

Following the [video tutorial](https://www.youtube.com/watch?v=f0nHtLJOBXs) I can see some differences in the UI and I think there are some bugs in it, like overflows with scroll bars and form input colors :

- First of all, the position of project-info block on top of the menu bar with the connectivity indicator (I think it's wrong)
![directus_UI_bug_BO](https://user-images.githubusercontent.com/6523221/144943460-e9a414c6-072a-4aca-b395-2a3ab49f8b2f.png)
- The information menu on the right hides some content and gets overflow witth scroll bar
![directus_UI_info_menu_right](https://user-images.githubusercontent.com/6523221/144943741-f16314da-4499-4b90-bbeb-211da11e61c1.png)
-When creating new collection, input text is dark and one can barely read it. 
![directus_UI_bug_collection](https://user-images.githubusercontent.com/6523221/144945174-1c50f86e-66c8-4ba4-aa57-ae2836f8faf3.png)
- The same dark input text applies when creating a new item from collection:
![directus_BUG_UI_create_item](https://user-images.githubusercontent.com/6523221/144945486-f2fc8e0e-93f0-409d-af1c-4ef49f6d5793.png)

This one is not a bug, but I think it is not clear, specially for a new user, what these icons means, compared to version 9.0.1, as you can see in the video tutorial:
- version 9.0.1
![directus_version_9_0](https://user-images.githubusercontent.com/6523221/144946279-4ddec672-2d0d-4e6a-9966-5bd0d0dcf465.png)
- Version 9.2.1 
![directus_create_new_field](https://user-images.githubusercontent.com/6523221/144946331-0e5889ce-1407-4808-aeda-63efb32fad1c.png)

Also, when testing with Docker, I had the same problem as described in the closed issue [#8080](https://github.com/directus/directus/issues/8080), but I think this is a subject for another issue.  😄 

### To Reproduce

Install the latest version (9.2.1) in both Docker or in Linux Debian 11 and login. 

I tested installing Directus in my machine with npm and npx and with Docker copyin/paste the same docker-compose.yml from the Docs, and I had the same UI bugs described above.

### Errors Shown

```
Error: Request failed with status code 503
    gT http://localhost:8055/admin/assets/vendor.764dd834.js:69
    Qj http://localhost:8055/admin/assets/vendor.764dd834.js:69
    L http://localhost:8055/admin/assets/vendor.764dd834.js:70
```
```
TypeError: ge is undefined                                                        vendor.764dd834.js:5:1162 
    me http://localhost:8055/admin/index.b3ccaf38.js:83
    J http://localhost:8055/admin/index.b3ccaf38.js:83
    Ih http://localhost:8055/admin/assets/vendor.764dd834.js:5
    U1 http://localhost:8055/admin/assets/vendor.764dd834.js:5
    iB http://localhost:8055/admin/assets/vendor.764dd834.js:2
    W http://localhost:8055/admin/index.b3ccaf38.js:43
    mH http://localhost:8055/admin/assets/vendor.764dd834.js:5
    d0 http://localhost:8055/admin/assets/vendor.764dd834.js:5
    Ih http://localhost:8055/admin/assets/vendor.764dd834.js:5
    U1 http://localhost:8055/admin/assets/vendor.764dd834.js:5
    iB http://localhost:8055/admin/assets/vendor.764dd834.js:2
    W http://localhost:8055/admin/index.b3ccaf38.js:43
```
![directus_bug_console](https://user-images.githubusercontent.com/6523221/144944498-1e2d6e00-7750-4b9d-9aaf-3786e8f1aa92.png)

### What version of Directus are you using?

9.2.1

### What version of Node.js are you using?

16.13.1 (version used by Docker image)

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Firefox

### What operating system are you using?

Debian 11

### How are you deploying Directus?

running locally on Docker

**Comment by azrikahar** [comment] 2021-12-07 03:14
Hi! Seems like this might be a Debian specific issue, at least from this comment here: https://github.com/directus/directus/issues/8820#issuecomment-945594521. Would you mind updating the browser as mentioned in the comment?

If it still persists, do let us know the exact versions of both the Chrome & Firefox browsers you've tested 👍

**Comment by rijkvanzanten** [comment] 2021-12-07 03:42
Duplicate of #8820

**Closed by rijkvanzanten** 2021-12-07 03:42 UTC
Labels: Needs More Info
