### ISSUE TITLE
Directus Dashboard: Can't enter tags in Chrome on Android.

### ISSUE THREAD

**Issue by SuperSandyman** [directus/directus#21068] opened 2024-01-13 12:02 UTC
### Describe the Bug

When I accessed the self-hosted Directus from Chrome for Android, I could not type in the tag field; in Firefox I could, and in MS Edge it was impossible, as it was in Chrome. I also changed the keyboard from Gboard to SwiftKey (MS) with the same result.

https://github.com/directus/directus/assets/66544945/588fe39a-4697-4e6d-9df3-c209d7a926ad

### To Reproduce

- Android 12 
- Chrome (Latest)
- Gboard (Latest)

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-01-15 09:36
I am unable to reproduce this on my android 12 phone with the provided GBoard. Could the chosen language affect whether an [enter] is emitted 🤔 

| a | b|
|------|---------|
| ![image](https://github.com/directus/directus/assets/9389634/4a8bf001-66e3-4709-9465-d5d0d0102a35) | ![image](https://github.com/directus/directus/assets/9389634/9cb6b219-65e9-4f4c-b16d-8c26ee45698b) |

Closing this issue for now as not reproducable but happy to re-open it once we can reproduce it.

**Closed by br41nslug** 2024-01-15 09:36 UTC

**Comment by SuperSandyman** [comment] 2024-01-15 10:17
I also tried changing the language settings in GBoard to English, etc., but the result was the same, and the same with Microsoft SwiftKey, so it's probably a Chrome or Directus issue....
