### ISSUE TITLE
Can't relate more than 101 items to a single item

### ISSUE THREAD

**Issue by JackMullinkosson** [directus/directus#22144] opened 2024-04-09 19:31 UTC
### Describe the Bug

Attempting to relate items to an item that already has 101 relations won't work. It may show that it has saved temporarily but after a few minutes the item will go back to only having 101 relations. This happens whether you relate the items via a flow or manually. 

### To Reproduce

Create two collections, for example, bookings and venues. Relate 102 bookings to the same venue item. Wait a few minutes and refresh the venue item page. Count the number of related bookings. 

### Directus Version

v10.10.5

### Hosting Strategy

Directus Cloud

**Comment by br41nslug** [comment] 2024-04-09 19:34
Have you set the `QUERY_LIMIT_DEFAULT` to more than 100?
https://docs.directus.io/self-hosted/config-options.html#general

Closing this for now but happy to re-open if that is not the cause 😄

**Closed by br41nslug** 2024-04-09 19:34 UTC

**Comment by JackMullinkosson** [comment] 2024-04-09 19:40
How to set these options for Directus cloud projects?

**Comment by JackMullinkosson** [comment] 2024-04-09 19:48
Gotcha - in my case I just want to set and save the items in my db using flows and manual actions. Sounds like the only way I can achieve that is by asking cloud support for help.
