### ISSUE TITLE
Social login says "invalid password" for a user created with email method

### ISSUE THREAD

**Issue by saptha** [directus/directus#9943] opened 2021-11-20 12:11 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Scenario 1: I created a user using email and password. Then I tried to login via Google's social auth method. 
The system says "invalid user name / password" 
I think it is trying to authenticate again.

Scenario 2: I enabled the env variable `AUTH_GOOGLE_ALLOW_PUBLIC_REGISTRATION=true`
I try to login the same user again via social auth,  this time the system says "Email has to be unique"
It tries to create the user again.

Expected result: The system should allow to login as the user is already authenticated via social auth.

### To Reproduce

Create the user by normal method - email and password
Then attempt to login via social auth

### Errors Shown

"Invalid username/password"
"Email has to be unique"

### What version of Directus are you using?

9.0.0-rc.90

### What version of Node.js are you using?

17.0.1

### What database are you using?

mysql

### What browser are you using?

Chrome

### What operating system are you using?

windows

### How are you deploying Directus?

PaaS

**Comment by aidenfoxx** [comment] 2021-11-20 12:35
This is expected behavior. Users can only have 1 authentication method, defined by their "Provider" value. You can't log in via social auth because your user is tied to the email/password method.

This "issue" already being discussed here: https://github.com/directus/directus/issues/9331

**Comment by saptha** [comment] 2021-11-20 16:22
This was the behavior seen in the earlier version.

**Comment by aidenfoxx** [comment] 2021-11-20 17:15
That was changed in rc99 when we moved to a different auth system.

**Comment by rijkvanzanten** [comment] 2021-11-20 17:47
This change was made for security reasons and is the intended behavior at this time. The issue @aidenfoxx mentioned is used to track the feature request to find a safe way to open this up a little more 👍🏻

Duplicate of https://github.com/directus/directus/issues/9331

**Closed** 2021-11-20 17:47 UTC
Labels: Duplicate
