### ISSUE TITLE
Automatically generate default value of collection based on another schema value

### ISSUE THREAD

**Issue by pauserratgutierrez** [directus/directus#23522] opened 2024-08-30 22:44 UTC
### Describe the Improvement

In the Admin UI, I created a schema that consists of a name and a slug. When populating the name, I would like the slug to automatically be used as the default value for the input, but also allow us to modify it just like now.

For example, here, add an option like "populate from field"
![image](https://github.com/user-attachments/assets/be9a56f3-b3fa-49ac-b1b3-5d3b9b4fc149)

The slug will be populated based on the name:
![image](https://github.com/user-attachments/assets/f66193ec-440c-49f7-80a5-016675510315)

Whenever a change to the slug is made, it stops auto-populating, so it can be really modified
![image](https://github.com/user-attachments/assets/51af5eef-816e-46e5-bcc2-8ebf1a5ace8d)

**Comment by rijkvanzanten** [comment] 2024-09-02 19:52
Duplicate of https://github.com/directus/directus/discussions/4231

**Closed by rijkvanzanten** 2024-09-02 19:52 UTC
