### ISSUE TITLE
Conditional Dropdown doesn't work as expected

### ISSUE THREAD

**Issue by drupalshift** [directus/directus#18756] opened 2023-05-28 09:01 UTC
### Describe the Bug

When you have two dropdowns and the second dropdown has conditional values based on the first when you change the first one and select the second one if you again change the first one the value of the second one remains!

https://github.com/directus/directus/assets/9895625/78c6dd3c-8b66-488e-9a06-6ffe6a40023c

### To Reproduce

Create two dropdowns. The first dropdown has two options: Texas and New Mexico. The second dropdown has conditional options that depend on the selection in the first dropdown. If the first dropdown is set to Texas, the second dropdown will display options for Houston and Dallas. If the first dropdown is set to New Mexico, the second dropdown will display options for Santa Fe and Albuquerque.

Now Test it in the form 
When the first dropdown is changed to Texas and the second dropdown is set to Dallas, go ahead and change the first dropdown to New Mexico, the second dropdown will still be set to Dallas. It would be ideal if the second dropdown could be set to a null value when the first dropdown is changed.

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-05-30 11:48
Thanks for opening this issue! However this is a duplicate of an existing issue #15281, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #15281 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2023-05-30 11:48 UTC
