### ISSUE TITLE
Cannot delete user_created and user_updated system fields

### ISSUE THREAD

**Issue by sksar** [directus/directus#12515] opened 2022-04-01 08:20 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to delete the system fields user_created and user_updated from a data model it is showing this error.

<img width="601" alt="Screenshot 2022-04-01 at 13 41 46" src="https://user-images.githubusercontent.com/11752260/161223004-66060e06-1c79-446e-8992-7c7d17ae5eee.png">

And thus it is not removable.

### To Reproduce

Create a data model such as 'Products', then while creating the data model do select the optional system fields user_created, user_updated.
Then after that add some data to the collection.
Then try to delete the system fields user_created or user_updated.

### Errors Shown

```
13:39:11 ✨ request errored DELETE 500 /fields/products/user_created 8ms
13:41:35 🚨 alter table `products` drop `user_created` - ER_FK_COLUMN_CANNOT_DROP: Cannot drop column 'user_created': needed in a foreign key constraint 'products_user_created_foreign' 
Error: ER_FK_COLUMN_CANNOT_DROP: Cannot drop column 'user_created': needed in a foreign key constraint 'products_user_created_foreign'
```
<img width="862" alt="Screenshot 2022-04-01 at 13 50 33" src="https://user-images.githubusercontent.com/11752260/161224455-4f4b7c94-8154-44cc-ba73-1823d3a3c818.png">

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.13.2

### What database are you using?

mysql

### What browser are you using?

safari

### What operating system are you using?

macOS Monterey (12)

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-04-01 13:39
Duplicate of https://github.com/directus/directus/issues/12478

**Closed by rijkvanzanten** 2022-04-01 13:39 UTC
Labels: Bug (Potential)
