### ISSUE TITLE
M2A list not updating

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#10583] opened 2021-12-17 11:33 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

When trying to create a new entry in a M2A list, it doesn't insert the newly created entry into the list.

https://user-images.githubusercontent.com/9347206/146538485-8f5abe81-de4a-412b-a3bc-34e055b7fccc.mov

That's how it worked like in 9.2.1:

https://user-images.githubusercontent.com/9347206/146538436-381dbef7-b8e6-4b04-b454-7797d41dff5a.mov

It stopped working in 9.2.2 and still doesn't work in 9.3.0.

### To Reproduce

Create a M2A list and try to insert new entries.

### What version of Directus are you using?

9.3.0

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Safari

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by franco-onevillas** [comment] 2021-12-17 14:51
Hi, I was going to create a similar issue but I think is related to this one:

The items are not showing but the data is there (see raw value):

![image](https://user-images.githubusercontent.com/92261640/146562415-01cb72e9-47e1-417b-ae3b-ecc840fe86e1.png)
![image](https://user-images.githubusercontent.com/92261640/146562430-4337fa46-37af-48c7-813b-f614fc72e2b6.png)


### What version of Directus were you using before updating?
9.0

### What version of Directus are you using?
9.3.0

### What is the last version of Directus were it's working?
9.2.1

Regards

**Comment by reggiedunloper** [comment] 2021-12-17 16:29
Same issue as above.  Data is being saved and accessible via graphql, but always shows 'no items' in interface.

**Comment by azrikahar** [comment] 2021-12-20 02:33
Although the reported behavior is slightly different, I believe this shares the same underlying root cause with #10474 in M2A. I'll close this for now in favor of tracking it there 👍

**Closed by azrikahar** 2021-12-20 02:33 UTC
Labels: Bug (Potential)
