### ISSUE TITLE
Can but cant drag around fields in the system collection

### ISSUE THREAD

**Issue by Attacler** [directus/directus#5825] opened 2021-05-22 12:36 UTC
1) The issue and what you expected to happen
When you drag around fields in the directus_user collection, the field do move but not inside of the settings.

2) Exact steps to reproduce this issue
Create a new field, drag that above the locked (above the first/lastname)
Also, after adding some fields, some default fields appear randomly infront of others (might be because i dragged many things around 😂 )

Images:
![image](https://user-images.githubusercontent.com/42644889/119226706-cb4fbe00-bb0a-11eb-9c57-538b692e1e1d.png)
User view

Collection view
![image](https://user-images.githubusercontent.com/42644889/119226713-d571bc80-bb0a-11eb-9196-84d28e158028.png)

3) Your environment:
Using directus rc69
Using npx directus start

4) Any other relevant information we might need to reproduce this issue
Nothing to report here

5) Idea
Maybe add the ability to drag around the system fields? this way you could make it appear in any order you like and this issue would be solved too.

**Comment by rijkvanzanten** [comment] 2021-05-22 14:13
Duplicate of https://github.com/directus/directus/issues/5520

**Closed** 2021-05-22 14:13 UTC
Labels: Duplicate
