### ISSUE TITLE
Custom migration - "up is not a function"

### ISSUE THREAD

**Issue by skuhnow** [directus/directus#18515] opened 2023-05-08 13:13 UTC
### Describe the Bug

I've create a custom migration, but cannot execute it

### To Reproduce

1) Bootstrap a new instance with `npx directus bootstrap`
2) Create a custom migration `extensions/migrations/20201202A-my-custom-migration.js` with the content
 
```js
module.exports = {
    async up(knex) {
        await knex.schema.createTable('test', (table) => {
            table.increments();
            table.string('rijk');
        });
    },

    async down(knex) {
        await knex.schema.dropTable('test');
    },
};
```
3) Run `npx directus database migrate:latest`
4) Get error

```bash
$:~/dev/directus$ npx directus database migrate:latest
[15:08:02.549] INFO: Loaded extensions: content-hook, file-upload-hook, saml-user-hook
[15:08:02.563] INFO: Running migrations...
[15:08:02.574] INFO: Applying My Custom Migration...
[15:08:02.575] ERROR: up is not a function
    err: {
      "type": "TypeError",
      "message": "up is not a function",
      "stack":
          TypeError: up is not a function
              at latest (file:///home/sebastian/dev/directus/node_modules/@directus/api/dist/database/migrations/run.js:91:23)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async run (file:///home/sebastian/dev/directus/node_modules/@directus/api/dist/database/migrations/run.js:42:9)
              at async migrate (file:///home/sebastian/dev/directus/node_modules/@directus/api/dist/cli/commands/database/migrate.js:8:9)
              at async Command.parseAsync (/home/sebastian/dev/directus/node_modules/commander/lib/command.js:935:5)
    }

```

### Directus Version

v9.25.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-05-08 13:47
Duplicate of https://github.com/directus/directus/issues/18359 The example is still using CommonJS. **With the next release** you can rename the migration file to `*.cjs` as a quickfix. For now you'll have to rewrite it to ESM which would look like:
```js
export async function up(knex) {
	await knex.schema.createTable('test', (table) => {
		table.increments();
		table.string('rijk');
	});
};
export async function down(knex) {
	await knex.schema.dropTable('test');
};
```

**Closed by br41nslug** 2023-05-08 13:47 UTC
