### ISSUE TITLE
Related Item field blank when page size is 250

### ISSUE THREAD

**Issue by ggez44** [directus/directus#3756] opened 2021-01-19 22:57 UTC
I have 2 collections, CollectionA and CollectionB in a many-to-one relationship

in CollectionA, i have a field that is displaying a value from CollectionB.  This works fine except when I change the page size to 250.  In that case, this field is only filled for the first 100, and empty for the rest.

using postgres 11.10 on directus v9 rc.30

**Comment by rijkvanzanten** [comment] 2021-01-27 15:48
I believe this to be a duplicate of https://github.com/directus/directus/issues/3791

**Closed by rijkvanzanten** 2021-01-27 15:48 UTC
Labels: App, Bug
