### ISSUE TITLE
Calendar layout abrupted: only header is shown

### ISSUE THREAD

**Issue by anantakrishna** [directus/directus#18856] opened 2023-06-10 11:07 UTC
### Describe the Bug

Getting acquainted with Directus, running it locally in a Docker. Added one content type and few items. Wanted to try the Calendar layout, but it shows abruptly, only the header.

![image](https://github.com/directus/directus/assets/6065071/1eb82551-8483-463e-b697-e2130da7f7e9)

Tried in Firefox and Chromium.

### To Reproduce

- Set up Directus according to https://docs.directus.io/self-hosted/quickstart.html#_1-installation
- Log in and add a simple content type with Date Created field.
- Switch to the calendar layout.

### Directus Version

v10.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-06-10 11:09
Thanks for opening this issue! However this is a duplicate of an existing issue #18848, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #18848 has been fixed by #18853 which will be available with the next release.

**Closed by paescuj** 2023-06-10 11:09 UTC

**Comment by anantakrishna** [comment] 2023-06-10 11:12
Oh, somehow I missed that issue, though searched for an existing one. Thanks for a lightning response! I'm impressed.
