### ISSUE TITLE
Extensions compiling "MODULE_NOT_FOUND" error when using PNPM

### ISSUE THREAD

**Issue by Joonel** [directus/directus#23529] opened 2024-09-01 15:20 UTC
### Describe the Bug

When running dev, build or link scripts:

```
> directus-extension build -w --no-minify

node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'E:\directus-extensions-with-pnpm\extensions\example-extension\node_modules\@directus\extensions-sdk\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

No issues when using ```npm i```.

### To Reproduce

clone repo (a barebone extension within a monorepo) - https://github.com/Joonel/directus-extensions-with-pnpm
then `pnpm i` and `pnpm run build` in the root of an extension folder.

### Directus Version

11.0.2

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2024-09-02 11:16
Unfortunately I am unable to reproduce the issue using the provided demo repo.
```
> gh repo clone Joonel/directus-extensions-with-pnpm
...
Receiving objects: 100% (11/11), done.
> cd directus-extensions-with-pnpm/extensions/example-extension
> pnpm i && pnpm build
...
example-extension@1.0.0 build C:\...\directus-extensions-with-pnpm\extensions\example-extension
directus-extension build

✔ Done
```

Any additional information you can provide to help debug the issue? Like operating system, node version, pnpm version, etc.
Closing the issue for now but happy to re-open it with more information.

**Closed by br41nslug** 2024-09-02 11:16 UTC
