### ISSUE TITLE
Custom validation with related field

### ISSUE THREAD

**Issue by bernatvadell** [directus/directus#20459] opened 2023-11-17 11:32 UTC
### Describe the Bug

when I try to create a validation between two dates, it gives me an error on the internal server.

### To Reproduce

1) We create a new entity
2) we add two fields, e.g. checkin and checkout
3) in the checkout field, in the validations section, we create a new validation with the "checkout" specification Greater than {{checkin}}
![image](https://github.com/directus/directus/assets/17298604/3b7e2313-b39b-415f-bb77-6d07c443ce58)
4) We try to create a new record in the collection and we will get the error message.
{
  "message": "date must have a valid date format or reference",
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR"
  }
}
![image](https://github.com/directus/directus/assets/17298604/f8d93fae-f7c4-4502-a4a8-d2cdf65bc212)

### Directus Version

v10.8.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by bernatvadell** [comment] 2023-11-17 11:43
Would PR #14887 solve my problem?

**Comment by azrikahar** [comment] 2023-11-17 12:30
> Would PR #14887 solve my problem?

I believe so, as it implements #2993. In the meantime, I think a potential workaround would be an `items.update` hooks extension/flow to attempt said date checking.

That being said, as this is technically not an existing feature yet, I'll proceed to close this as not a bug 👍

**Closed by azrikahar** 2023-11-17 12:30 UTC
