### ISSUE TITLE
/users/me endpoint will only return the ID, no other fields after update to 9.7.1 when custom permissions for user update are in place.

### ISSUE THREAD

**Issue by lino** [directus/directus#12397] opened 2022-03-25 18:04 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

/users/me will only return the ID regardless of what is expected or added to the query.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/1456957/160176358-0160d162-43f8-4afe-a03e-c2bb93de8b27.png">

The expected output would be something more similar to this
<img width="860" alt="image" src="https://user-images.githubusercontent.com/1456957/160176795-2272e680-9dcd-45c4-90ba-be60a46bd3f8.png">

### To Reproduce

1. Start directus 9.7.1 from docker container
2. Create a role (in my case without app access)
3. Create a user and assign it to the role
4. Log in with this user and request /users/me

In comparison, the request works for the admin user. Removing the restriction from directus_permission "fixes" the problem, but I have doubts about the long term effects of this (DO NOT EVEN CONSIDER THIS AS A FIX IF YOU'RE READING THIS, thank you)

As soon as a custom permission is in place, the /users/me endpoint breaks. Getting the user data via the user collection works, though. I don't know yet, but possible the changes in the AuthorizationService (validateFilterPermissions) made this break or fixed a bug that masked this issue.

It does not seem to be an issue with field based permissions, even when I change the permission to * the behaviour is shown.

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

reproducible in the docker image

### What database are you using?

reproducible in the docker image

### What browser are you using?

curl

### What operating system are you using?

Arch Linux

### How are you deploying Directus?

docker

**Comment by lino** [comment] 2022-03-25 18:13
A viable mitigation strategy in my humble opinion is to stay on 9.7.0 until we've clarified the issue. Please do not change your permission settings spontaneously to keep directus working.

**Comment by lino** [comment] 2022-03-25 20:26
You're absolutely right. My PoC was not finetuned enough. I'll prepare an environment to reproduce our exact issue.

**Comment by LevinGermann** [comment] 2022-03-26 19:51
Is this maybe related to #11906 ?

**Comment by lino** [comment] 2022-03-27 11:32
I have trouble finding out how to reproduce this issue, but I will find out. Possibly it's related to something in my extensions, however I still regard this as a bug because it used to work with 9.7.0 and now doesn't.

**Comment by eikaramba** [comment] 2022-03-29 00:48
i had the same problem! i also had custom rules to allow users to read their own infos etc.

after updating to 9.7.1 i only got the id back. reseting the permissions via enabling app access and setting recommend settings fixed it. from that i set everything back to how it was and it was working. very strange.

**Comment by licitdev** [comment] 2022-03-29 00:57
@rijkvanzanten This could be due to legacy permissions stored within the DB. Will a migration be necessary? Ref: https://github.com/directus/directus/pull/12277

On a side note, `authorization.ts#315` in https://github.com/directus/directus/pull/12426 checks the legacy empty array permissions to only read the `id` field instead of throwing a forbidden error.

**Comment by Nisthar** [comment] 2022-04-01 12:00
It works if you allow `ID` in the field permissions

**Comment by eikaramba** [comment] 2022-04-01 12:25
@Nisthar no it doesn't this is a migration issue. i had the same problem. on another server i had it again, needed to reset all users permissions and switch back to the same permissions manually. everything is the same, but now it works.

**Comment by rijkvanzanten** [comment] 2022-06-28 22:57
We haven't been able to reproduce this, and it seems like the issue hasn't resurfaced / does no longer happen in the later versions. I'll close this for now, but happy to keep discussing and will reopen if more information comes up 🙂

**Closed by rijkvanzanten** 2022-06-28 22:57 UTC
Labels: Needs More Info

**Comment by malipetek** [comment] 2023-04-02 15:57
I had the same issue while testing with a new dummy user. This user did not have a role assigned to it. After assigning user to a role, it was fixed.

**Comment by bennyzen** [comment] 2023-12-16 17:15
Just faced the exactly same problem and the solution was to check the `id` field. It's reproducible, as I tried on different installs and they all behave the same. When the `id` field is **not** selected in custom-permissions, `/users/me` will only return the id. This should be documented somewhere, as it's not really obvious and took me hours to figure out.

**Comment by paescuj** [comment] 2023-12-16 19:40
> Just faced the exactly same problem and the solution was to check the `id` field. It's reproducible, as I tried on different installs and they all behave the same. When the `id` field is **not** selected in custom-permissions, `/users/me` will only return the id. This should be documented somewhere, as it's not really obvious and took me hours to figure out.

Would you mind opening a new issue with the necessary information?
