### ISSUE TITLE
GraphQL Endpoint not working

### ISSUE THREAD

**Issue by juancarlosjr97** [directus/directus#5296] opened 2021-04-27 17:07 UTC
Version: rc.61
Database: PosgreSQL, MySQL, SQLite

1. Tested using a current live system
2. Tested from a clean installation, creating a new collection and making all the collections entirely public as everything.

`/graphql` or `/graphql/system` are not working.

**Comment by rijkvanzanten** [comment] 2021-04-27 20:44
Not working.. how? Any errors? Any steps to reproduce?

![CleanShot 2021-04-27 at 16 44 22@2x](https://user-images.githubusercontent.com/9141017/116310330-d7e52e80-a777-11eb-9e8e-61a4dadc57a6.png)

LGTM 🤷🏻

**Comment by rijkvanzanten** [comment] 2021-04-27 20:45
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-04-27 20:45 UTC

**Comment by juancarlosjr97** [comment] 2021-05-05 09:19
Does it mean it will not longer work via the browser as before on early rc?

It does work the GraphQL just is not loading the playground on the browser as before.

**Comment by rijkvanzanten** [comment] 2021-05-05 13:49
Ohh yeah that's correct. We don't ship GraphiQL in production builds 👍🏻

**Comment by sksar** [comment] 2021-05-09 07:29
> Ohh yeah that's correct. We don't ship GraphiQL in production builds 👍🏻

How do I install/configure GraphiQL in a production build, is there a command or tutorial somewhere we can follow?

**Comment by rijkvanzanten** [comment] 2021-05-10 13:50
@sksar There's many different GraphQL explorer tools available, for example: 

* [graphiql-online](https://graphiql-online.com)
* [Altair](https://altair.sirmuel.design)
* [Paw](https://paw.cloud)
* Apollo Studio Explorer

and many others 👍🏻

**Comment by SalahAdDin** [comment] 2022-08-02 10:54
> Ohh yeah that's correct. We don't ship GraphiQL in production builds 👍🏻

why?

What about enabling the playground for dev environments? I'm trying to test it on a local docker container but I can't get access to it.

**Comment by rijkvanzanten** [comment] 2022-08-02 13:19
@SalahAdDin Because there's a lot of different options available, and everybody has their own preference as to which one is the best tool for the job. We shipped with GraphiQL for a little bit, and people immediately started asking for graphql-playground instead. At the end of the day, there's no real benefit to hosting our own copy of those popular tools, as they all work perfectly as standalone apps (which also has the benefit you can use the same tool for multiple APIs). Even since may 10th last year there's a couple new popular ones that were added, including Insomnia and Postman

**Comment by SalahAdDin** [comment] 2022-08-02 20:21
> @SalahAdDin Because there are a lot of different options available, and everybody has their own preference as to which one is the best tool for the job. We shipped with GraphiQL for a little bit, and people immediately started asking for graphql-playground instead. At the end of the day, there's no real benefit to hosting our own copy of those popular tools, as they all work perfectly as standalone apps (which also has the benefit you can use the same tool for multiple APIs). Even since May 10th last year there's a couple of new popular ones that were added, including Insomnia and Postman

GraphiQL is even fair enough, actually, any tool for testing **GraphQL** provided by this awesome project is a good add in my opinion.
