### ISSUE TITLE
Translations related fields

### ISSUE THREAD

**Issue by rvizzoca** [directus/directus#6930] opened 2021-07-22 15:38 UTC
### Describe the Bug

In previous versions, the translations field displayed the number of translatable fields and allowed them to be managed directly.

**Version 9.0.0.rc.68**
![Schermata 2021-07-22 alle 17 34 30](https://user-images.githubusercontent.com/74315471/126667002-cd78d8b5-58e0-47ea-85e1-0900848158f8.png)

**Version 9.0.0.rc.83**
![Schermata 2021-07-22 alle 17 34 38](https://user-images.githubusercontent.com/74315471/126667049-733b265a-4ce4-4f71-9150-79cb554dd343.png)

### To Reproduce

Add a field of type translations to a collection.

### What version of Directus are you using?

v9.0.0.rc.83

### What version of Node.js are you using?

v14.17.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-07-22 15:46
Duplicate of https://github.com/directus/directus/issues/6582

**Closed by rijkvanzanten** 2021-07-22 15:46 UTC
Labels: Bug (Potential)
