### ISSUE TITLE
Single/Multiple File fields Allowed Filetypes not accepting file types

### ISSUE THREAD

**Issue by doughnet** [directus/directus#1304] opened 2016-11-28 16:56 UTC
## Version Info
  - Directus version and branch: (Or commit hash)
  - PHP version: 5.6.x
  - Web server: LiteSpeed
  - OS name and version: Debian 8.x 64bit

## Expected Behavior
When setting the field options, you can specify the Allowed FileTypes.  I entered in: jpg, png
After saving it should allow jpg & png files.

## Actual Behavior
It gives an error when uploading jpg or png files.

**Comment by WellingGuzman** [comment] 2016-11-28 17:00
Hey @doughnet which version are you using?

I'm taking a look now, at least it should be working on Single File UI.

**Comment by doughnet** [comment] 2016-11-28 17:04
Howdy!

6.3.5

**Comment by WellingGuzman** [comment] 2016-11-28 17:21
I've tested on 6.3.5, it worked, and we do not have the options for multiple files. (I will add a note for adding it)

Can you please give a step by step to replicate it?

**Comment by benhaynes** [comment] 2016-11-28 17:22
Could it be a whitespace issue? `jpg, png` versus `jpg,png`? Or are we trimming out the whitespace after exploding the values? Also, this option supports MIME type OR extension, correct?

**Comment by WellingGuzman** [comment] 2016-11-28 17:24
you darn right @benhaynes, Thanks 👍 working on it.

**Comment by WellingGuzman** [comment] 2016-11-28 17:25
also it does supports MIME Type and extension.

**Comment by doughnet** [comment] 2016-11-28 17:32
I tried it both methods though and neither work
jpg, png
jpg,png
png, jpg
png,jpg

**Comment by benhaynes** [comment] 2016-11-28 17:33
@doughnet – that's odd... but you said that ONE extension (not a CSV) _does_ work?

**Comment by doughnet** [comment] 2016-11-28 17:35
csv with MIME type does work

not a CSV (example just using jpg) does work

**Comment by WellingGuzman** [comment] 2016-11-28 17:46
weird, what file are you trying to upload? I'm out of ideas what could it be.

**Comment by doughnet** [comment] 2016-11-28 17:50
Quite sure I'm not doing anything wrong but here are images for proof/process.

![settings](https://cloud.githubusercontent.com/assets/9806529/20679499/04b744b2-b550-11e6-8925-4b148262de82.png)
![picking_jpg](https://cloud.githubusercontent.com/assets/9806529/20679497/04b54b76-b550-11e6-8a62-646175355a66.png)
![denied](https://cloud.githubusercontent.com/assets/9806529/20679498/04b661a0-b550-11e6-9a95-bab26f08ad85.png)

**Comment by WellingGuzman** [comment] 2016-11-29 19:03
@doughnet I want to you let you know I keep trying to replicate without no luck, I will get back to you with a fix as soon as I replicate it.

**Comment by doughnet** [comment] 2016-11-29 19:06
No problem.  Are there any additional details that could help?

**Comment by WellingGuzman** [comment] 2017-05-04 06:29
@doughnet This has been a long way since we were discussing this problem, I'm not still able to reproduce it, and probably a long the way was fixed for you too. can you confirm this?

**Comment by WellingGuzman** [comment] 2017-05-11 03:00
I will close this, Assuming this was fixed in some way as it seems to be working. (I can't reproduce this error) Please let us know if still happening to you.

**Closed by WellingGuzman** 2017-05-11 03:00 UTC
Labels: 3. Major, 6. In-Progress, UI
