### ISSUE TITLE
Thumbnails don't load correctly when switching collections in admin app

### ISSUE THREAD

**Issue by Snokown** [directus/directus#16704] opened 2022-12-02 22:29 UTC
### Describe the Bug

Displaying collections as "cards" in multiple collections. The first collection I open shows the correct thumbnails, however when I switch to another collection, it loads the default "box" fallback image until the page is refreshed. Then this same issue occurs when clicking the other collections.

Loom: https://www.loom.com/share/883015ae9d704d8e98c480dde1b5c723
(sorry for the background noise, figured loom would let me remove it in editing...nope! 😝)

If it matters, I am using the Digital Ocean Bucket storage adapter.

### To Reproduce

Set multiple collections to use the "Cards" style layout with images connected in the collection item. Click on a collection tab to view it, see the images, switch collection tab to another one and see the default thumbnails. Refresh the page and the thumbnails will load correctly.

### Errors Shown

No errors in the console.

### What version of Directus are you using?

9.20.4

### What version of Node.js are you using?

16.18.0

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-12-15 22:35
Linear: [ENG-120](https://linear.app/directus/issue/ENG-120/thumbnails-dont-load-correctly-when-switching-collections-in-admin-app)

**Comment by paescuj** [comment] 2023-02-01 11:10
Thank you very much for your issue report!
It seems like this issue has been fixed in the meantime and I'm not able to reproduce it in the latest version ([v9.22.4](https://github.com/directus/directus/releases/tag/v9.22.4).
Therefore, I'm closing this issue for now.

**Closed by paescuj** 2023-02-01 11:10 UTC
Labels: App, Bug (Potential)
