### ISSUE TITLE
No matching version found for directus@10.2.0.

### ISSUE THREAD

**Issue by sekhuat** [directus/directus#18698] opened 2023-05-23 09:17 UTC
### Describe the Bug

My existing version is 10.1.0 and when I run the directus via the command line it shows that there is update available.

[09:08:14.940] INFO: Server started at http://0.0.0.0:8055
[09:08:17.147] WARN: Update available: 10.1.0 -> 10.2.0

I stop the directus and edit the package.json by changing "directus": "10.1.0" => "directus": "10.2.0".

When I issue the `npm update` command to update directus, I got the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for directus@10.2.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

### To Reproduce

* Edit the package.json by changing "directus": "10.1.0" => "directus": "10.2.0".
* Issue the `npm update` command to update directus

### Directus Version

v10.2.0

### Hosting Strategy

Self-Hosted (Custom)

**Comment by licitdev** [comment] 2023-05-23 09:31
Duplicate of https://github.com/directus/directus/issues/18632

**Closed by licitdev** 2023-05-23 09:31 UTC
