### ISSUE TITLE
Unable to use the directus sdk 

### ISSUE THREAD

**Issue by abe-humaapi** [directus/directus#13865] opened 2022-06-13 10:31 UTC
### Describe the Bug

when i install directus sdk librairy it show a typeScript error saying my component ' cannot be used as a JSX component.
  Its return type 'ReactElement<any, any> | null' is not a valid JSX element
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/88038146/173330316-32747efb-f318-49aa-a2df-a7189349f857.png)
    

i suspect the error is coming from your librairy folder exactely the sharred folder on the tsconfig.json file whom is creating a conflict with my own  tsconfig.json so i sugest you should just remove your  own tsconfig.json 

![image](https://user-images.githubusercontent.com/88038146/173332757-480f97fb-428a-4a85-9c66-124ad3328ff8.png)

### To Reproduce

install directus on your nextjs project with typeScript

### Errors Shown

my component ' cannot be used as a JSX component.
  Its return type 'ReactElement<any, any> | null' is not a valid JSX element 

### What version of Directus are you using?

cloud 9.12.2

### What version of Node.js are you using?

v16.14.0

### What database are you using?

community

### What browser are you using?

chrome

### How are you deploying Directus?

directus cloud

**Comment by azrikahar** [comment] 2022-06-13 10:41
Thanks for opening this issue! However this is a duplicate of existing issues #13615 #13049, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #13049 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-06-13 10:41 UTC
