### ISSUE TITLE
Cannot change sort order on a M2A relationship

### ISSUE THREAD

**Issue by shivam95** [directus/directus#6628] opened 2021-07-02 18:50 UTC
### Describe the Bug

![image](https://user-images.githubusercontent.com/11583651/124317004-1a6e2180-db94-11eb-8215-bce27e5c54eb.png)

I am getting these errors when i am  trying to update a sort order in M2A relationship.  

I think the issue is with empty image objects which app is sending to backend while updating sort order. I may be wrong here 

![image](https://user-images.githubusercontent.com/11583651/124318102-c49a7900-db95-11eb-861d-b976bea22da0.png)

### To Reproduce

Create M2A relationship.
Make sure that the relationship tables have image/media fields, and relationship have sort field
Update sort order of the content
Issue is reproduced

### What version of Directus are you using?

v9.0.0-rc.81

### What version of Node.js are you using?

Docker Image 

### What database are you using?

Postgres

### What browser are you using?

Edge (Chromium)

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2021-07-04 11:45
I'll close this as a duplicate of https://github.com/directus/directus/issues/6085, as the underlying problem is the same 👍🏻

**Closed by rijkvanzanten** 2021-07-04 11:45 UTC
Labels: App, Bug (Potential)
