### ISSUE TITLE
Login server error occured

### ISSUE THREAD

**Issue by rnnyrk** [directus/directus#1282] opened 2016-10-16 08:51 UTC
## Version Info
- Directus version and branch: 6.3.4
- PHP version: 5.5.9-1ubuntu4.17
- MySQL version: Ver 14.14 Distrib 5.5.49
- Web server: Apache(2)
- OS name and version: macOS El Captain
## Expected Behavior

Install Directus as a local installation.
Login using email and password.
## Actual Behavior

Install Directus as a local installation.
Getting error when submitting email and password. (I see in the console that there is a 404 error to the api path.)
## Steps to Reproduce
1. Install a fresh installation
2. Try to log in
## Logs or Screenshots

Same as: https://github.com/directus/directus/issues/1239
## Issue

My question is very similar to the one above, but I can't seem to fix it with the solution given in that topic. I'd a fresh install, but trying to login keeps returning a "Server error occured". In my root there is a .htaccess and everything else from [this file](https://github.com/directus/directus/blob/master/.htaccess):

```
<ifModule mod_rewrite.c>
    RewriteEngine On
    # Uncomment this if you are getting routing errors:
    RewriteBase /
</ifModule>
```

Also /api/.htaccess contains everything from [the example file](https://github.com/directus/directus/blob/master/api/.htaccess) except the change I commented `RewriteBase /api` out. When I execute `a2enmod rewrite` it logs that `mod_rewrite` is allready installed. 

I've also tried editing the VirtualHost files. In `/etc/apache2/apache2.conf` I've configured it as shown below. As said in [the documentation](http://getdirectus.com/docs/developer/faq)  I'd add the `AllowOverride All`, but unfortunately it didn't work.

```
<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/directus/>
        Options Indexes MultiViews FollowSymLinks
        AllowOverride All
        Order allow,deny
        Allow from all
        Require all granted
</Directory>
```

This topic https://github.com/directus/directus/issues/1038 also suggested to change `FollowSymLinks` to `SymLinksIfOwnerMatch`, but this didn't change anything.

In `/etc/apache2/sites-available/directus.conf` I do have the code as following: 

```
<VirtualHost *:8080>
    ServerName directus.DOMAIN.com
    ServerAlias directus.DOMAIN.com
    DocumentRoot /var/www/directus
    DirectoryIndex index.php
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

After I did some changes I always did run `sudo service apache2 restart` which logged a [OK] status. 

I don't know how to fix anymore.
Someone who can help me out?

**Comment by WellingGuzman** [comment] 2016-10-16 17:50
Hello @Ronnyrr,

Did you commented out `RewriteBase /`? try to comment that line and see if it works. Otherwise let us know to help you fix your issue.

**Comment by Ronnyrr** [comment] 2016-10-16 18:06
@WellingGuzman Yes I did comment that line (13) out. Making that line a comment again doesn't solve my issue. Also commenting line 6 `RewriteBase /` in api/.htaccess in or out won't change a thing.

**Comment by WellingGuzman** [comment] 2016-10-16 18:14
@Ronnyrr is your error 500 or 404? can you show me the message that your server throws?

You can take a look at this to test your mod_rewrite: https://github.com/directus/directus/issues/889#issuecomment-249789534

**Comment by Ronnyrr** [comment] 2016-10-16 18:38
I do not exactly know which error status I get, where is this shown? 
The log in `api/logs/2016-10-16` shows the following:

```
ERROR - 2016-10-16T04:13:30-04:00 - exception 'ErrorException' with message 'Declaration of Directus\Db\TableGateway\AclAwareTableGateway::makeTableGatewayFromTableName() should be compatible with Directus\Db\TableGateway\BaseTableGateway::makeTableGatewayFromTableName($table, $adapter)' in /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:0
Stack trace:
#0 /var/www/directus/vendor/composer/ClassLoader.php(412): Directus\Exception\ExceptionHandler->handleError(2048, 'Declaration of ...', '/var/www/direct...', 0, Array)
#1 /var/www/directus/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/direct...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Tab...')
#4 /var/www/directus/api/core/Directus/Db/TableGateway/DirectusTablesTableGateway.php(9): spl_autoload_call('Directus\Db\Tab...')
#5 /var/www/directus/vendor/composer/ClassLoader.php(412): include('/var/www/direct...')
#6 /var/www/directus/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/direct...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Directus\Db\Tab...')
#8 /var/www/directus/api/core/Directus/Bootstrap.php(328): spl_autoload_call('Directus\Db\Tab...')
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#11 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#12 /var/www/directus/index.php(13): require('/var/www/direct...')
#13 {main}
```

I've also tried your suggested topic. `$_SERVER['REQUEST_URI']` prints the following path: `string(21) "/test/mod_rewrite.php"`

When I'll check my `phpinfo()` the `mod_rewrite` module is loaded.

In my apache config I deleted the lines:

```
Options Indexes FollowSymLinks
Require all granted
```

So my config now looks like:

```
<Directory /var/www/directus/>
        AllowOverride All
        Order allow,deny
        Allow from all
</Directory>
```

As shown in your example in topic #889. Still the same error.
Thanks for trying to help. Hopefully we can fix this :)

**Comment by WellingGuzman** [comment] 2016-10-16 18:40
@Ronnyrr Oh so there's not issue with your mod_rewrite, the issue is in Directus, which version, branch are you using?

**Comment by Ronnyrr** [comment] 2016-10-16 18:43
Version 6.3.4 mouse over shows: h9b90cosim433sd5aq7pvm58m6

**Comment by WellingGuzman** [comment] 2016-10-16 18:50
@Ronnyrr update your master branch by using `git pull` and let me know if it works for you now.

**Comment by Ronnyrr** [comment] 2016-10-16 19:15
I completely deleted the CMS and cloned it from github. I'd delete the database tables an did the installation process again. 

Unfortunately the "Pre-installation check" says my mod_rewrite still isn't correct. [See this image.](http://oi68.tinypic.com/2nujdqu.jpg)

But when I run `a2enmod rewrite` it prints `Module rewrite already enabled` and `git pull` shows `Already up-to-date.`. Still unable to login.

**Comment by WellingGuzman** [comment] 2016-10-16 19:36
Click install anyway and try to log in and tell me what's the error, this means that there's still an issue with Directus. Check the logs `/api/logs`.

**Comment by Ronnyrr** [comment] 2016-10-16 19:40
I allready did. Still unable to login.
Error log shows multiple errors. This is the **complete** error log:

```
ERROR - 2016-10-16T15:10:17-04:00 - exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist' in /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:240
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(240): PDOStatement->execute()
#1 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(233): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /var/www/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(565): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(179): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#4 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#5 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#6 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#7 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#8 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#11 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#12 /var/www/directus/index.php(13): require('/var/www/direct...')
#13 {main}

Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (42S02 - 1146 - Table 'directus.directus_tables' doesn't exist)' in /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:245
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(233): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /var/www/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(565): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#2 /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(179): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#4 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#5 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#6 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#7 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#8 [internal function]: Directus\Bootstrap::acl(NULL)
#9 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#10 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#11 /var/www/directus/index.php(13): require('/var/www/direct...')
#12 {main}

Next exception 'RuntimeException' with message 'This query failed: SELECT `directus_tables`.* FROM `directus_tables`' in /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:182
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#1 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#2 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#3 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#4 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#5 [internal function]: Directus\Bootstrap::acl(NULL)
#6 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#7 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#8 /var/www/directus/index.php(13): require('/var/www/direct...')
#9 {main}
ERROR - 2016-10-16T15:10:30-04:00 - exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist' in /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:240
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(240): PDOStatement->execute()
#1 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(233): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /var/www/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(565): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(179): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#4 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#5 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#6 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#7 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#8 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#11 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#12 /var/www/directus/index.php(13): require('/var/www/direct...')
#13 {main}

Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (42S02 - 1146 - Table 'directus.directus_tables' doesn't exist)' in /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:245
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(233): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /var/www/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(565): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#2 /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(179): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#4 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#5 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#6 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#7 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#8 [internal function]: Directus\Bootstrap::acl(NULL)
#9 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#10 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#11 /var/www/directus/index.php(13): require('/var/www/direct...')
#12 {main}

Next exception 'RuntimeException' with message 'This query failed: SELECT `directus_tables`.* FROM `directus_tables`' in /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:182
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#1 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#2 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#3 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#4 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#5 [internal function]: Directus\Bootstrap::acl(NULL)
#6 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#7 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#8 /var/www/directus/index.php(13): require('/var/www/direct...')
#9 {main}
ERROR - 2016-10-16T15:10:39-04:00 - exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist' in /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:240
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(240): PDOStatement->execute()
#1 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(233): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#2 /var/www/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(565): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(179): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#4 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#5 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#6 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#7 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#8 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#9 [internal function]: Directus\Bootstrap::acl(NULL)
#10 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#11 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#12 /var/www/directus/index.php(13): require('/var/www/direct...')
#13 {main}

Next exception 'Zend\Db\Adapter\Exception\InvalidQueryException' with message 'Statement could not be executed (42S02 - 1146 - Table 'directus.directus_tables' doesn't exist)' in /var/www/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:245
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(233): Zend\Db\Adapter\Driver\Pdo\Statement->execute()
#1 /var/www/directus/api/core/Directus/Db/TableGateway/BaseTableGateway.php(565): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#2 /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php(179): Directus\Db\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#3 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#4 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#5 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#6 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#7 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#8 [internal function]: Directus\Bootstrap::acl(NULL)
#9 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#10 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#11 /var/www/directus/index.php(13): require('/var/www/direct...')
#12 {main}

Next exception 'RuntimeException' with message 'This query failed: SELECT `directus_tables`.* FROM `directus_tables`' in /var/www/directus/api/core/Directus/Db/TableGateway/AclAwareTableGateway.php:182
Stack trace:
#0 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(208): Directus\Db\TableGateway\AclAwareTableGateway->executeSelect(Object(Zend\Db\Sql\Select))
#1 /var/www/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(195): Zend\Db\TableGateway\AbstractTableGateway->selectWith(Object(Zend\Db\Sql\Select))
#2 /var/www/directus/api/core/Directus/Bootstrap.php(330): Zend\Db\TableGateway\AbstractTableGateway->select()
#3 /var/www/directus/api/core/Directus/MemcacheProvider.php(117): Directus\Bootstrap::Directus\{closure}()
#4 /var/www/directus/api/core/Directus/Bootstrap.php(333): Directus\MemcacheProvider->getOrCache('directus_tables', Object(Closure), 1800)
#5 [internal function]: Directus\Bootstrap::acl(NULL)
#6 /var/www/directus/api/core/Directus/Bootstrap.php(51): call_user_func('Directus\Bootst...', NULL)
#7 /var/www/directus/api/api.php(132): Directus\Bootstrap::get('acl')
#8 /var/www/directus/index.php(13): require('/var/www/direct...')
#9 {main}
```

There is also a development.log which contains:

```
Oct 16 15:09:18 [info] CREATE TABLE `directus_schema_migrations` (
`version` varchar(255))  ENGINE=InnoDB  DEFAULT CHARSET=utf8;
Oct 16 15:09:18 [info] CREATE UNIQUE INDEX `idx_directus_schema_migrations_version` ON `directus_schema_migrations`(`version`)
Oct 16 15:09:18 [info] SELECT version FROM directus_schema_migrations
Oct 16 15:09:18 [info] SELECT version FROM directus_schema_migrations
Oct 16 15:09:18 [info] SELECT version FROM directus_schema_migrations
Oct 16 15:10:55 [info] CREATE TABLE `directus_schema_migrations` (
`version` varchar(255))  ENGINE=InnoDB  DEFAULT CHARSET=utf8;
Oct 16 15:10:55 [info] CREATE UNIQUE INDEX `idx_directus_schema_migrations_version` ON `directus_schema_migrations`(`version`)
Oct 16 15:10:56 [info] SELECT version FROM directus_schema_migrations
Oct 16 15:10:56 [info] SELECT version FROM directus_schema_migrations
Oct 16 15:10:56 [info] SELECT version FROM directus_schema_migrations
```

**Comment by WellingGuzman** [comment] 2016-10-16 19:42
Doesn't seem that the install creates all the tables, is your database empty? or missing some tables? show me the tables that the database has.

**Comment by Ronnyrr** [comment] 2016-10-16 19:47
The database does contain tables:

```
directus_activity
directus_bookmarks
directus_columns
directus_files
directus_groups
directus_messages
directus_messages_recipients
directus_preferences
directus_privileges
directus_schema_migrations
directus_settings
directus_tables
directus_ui
directus_users
```

**Comment by WellingGuzman** [comment] 2016-10-16 20:05
Can you please give me more context of what's going on here?

I see a log that says `Statement could not be executed (42S02 - 1146 - Table 'directus.directus_tables' doesn't exist)`.

Something happens before you install? Are you making sure you are looking at the right database?

**Comment by Ronnyrr** [comment] 2016-10-16 20:09
I would love to, but there isn't much more context to show. 
I'd create a database which I install directus in. The database is called directus and the tables mentioned above are inserted in this database (so this looks like it works as expected).

Al my config settings are posted in earlier comments in this topic and I ran `curl -s https://getcomposer.org/installer | php` and `php composer.phar install` before the installation. That's all I can say I guess?

**Comment by WellingGuzman** [comment] 2016-10-16 20:13
If possible, can you show me a screencast? I have no clue why if the table exists, zend-db (pdo) throws an error that it doesn't.

Can you also take a look at the network tab while you are installing directus?

**Comment by WellingGuzman** [comment] 2016-10-19 16:59
@Ronnyrr I will close this as this is not directly related to directus.

I can still help you, _if still necessary_, on setting up Mod Rewrite.

**Comment by Ronnyrr** [comment] 2016-10-19 22:38
Yes please. I'm still not able to get it working.
Can you tell me what I did wrong or which apache settings I'm missing?

**Comment by benhaynes** [comment] 2016-10-20 17:09
Hey @Ronnyrr – I've invited you to our Directus Slack channel... we can help you figure this out over there. 👍

**Comment by chrisformula** [comment] 2017-04-19 13:51
How did you solve this?

**Comment by Ronnyrr** [comment] 2017-04-19 15:58
I was able to fix it, but I don't know anymore how I did it, sorry. I ran into lately again, but chose to use another CMS because I didn't had time to figure it out again.

**Comment by WellingGuzman** [comment] 2017-04-19 17:17
hey @chrisformula any logs in `api/logs`? try to do the steps in this [comment](https://github.com/directus/directus/issues/889#issuecomment-249789534)

**Comment by chrisformula** [comment] 2017-04-20 06:00
Hey @WellingGuzman 

This is all that is in my log file:
Apr 19 10:44:07 [info] CREATE TABLE `directus_schema_migrations` (
`version` varchar(255))  ENGINE=InnoDB  DEFAULT CHARSET=utf8;
Apr 19 10:44:07 [info] CREATE UNIQUE INDEX `idx_directus_schema_migrations_version` ON `directus_schema_migrations`(`version`)
Apr 19 10:44:09 [info] SELECT version FROM directus_schema_migrations
Apr 19 10:44:09 [info] SELECT version FROM directus_schema_migrations
Apr 19 10:44:09 [info] SELECT version FROM directus_schema_migrations

**Comment by benhaynes** [comment] 2018-10-24 15:53
For all those experiencing this issue... what version of Directus are you using? Is this all for v6.3.4 as posted in the original comment?

**Comment by benhaynes** [comment] 2018-10-25 18:04
Kamino closed and cloned this issue to [directus/directus-6-legacy](https://github.com/directus/directus-6-legacy/issues/4)

**Closed by benhaynes** 2018-10-25 18:04 UTC
Labels: 2. Critical, Bug, Hacktoberfest

**Comment by byt3-m3** [comment] 2019-08-05 16:28
Hello is this issue still closed, i followed three different tutorials and still ended up with the same error as stated above, using Ubuntu 18.04, Apache2 and MariaDB

**Comment by benhaynes** [comment] 2019-08-06 15:24
Yes, still closed. This specific issue was from a much older version of Directus... if you're experiencing something similar I would recommend opening up a new ticket or discuss with the community on our Slack:

https://directus.chat
