### ISSUE TITLE
Relational field validation stopped working

### ISSUE THREAD

**Issue by falmanna** [directus/directus#15931] opened 2022-10-10 15:23 UTC
### Describe the Bug

When creating items, seems like relational fields validation is always throwing invalid error. 
I don't remember experiencing this issue, and some of my existing fields validations started throwing errors.

### To Reproduce

1. Create collection `user` -> add string field `name`
2. Create item and set `name` to `test` (or any value, tested it on number fields as well)
3. Create collection `test_role` -> add M2O field `user`
4. Open field `user` -> validation -> set `User -> Name Equals test` and save
5. Try to create item in `test_role` -> select the user named `test`, it should throw an error.
6. Try with another fields with invalid values, it will throw errors as well.  

### Errors Shown

The following fields have invalid values:
- User: validationError.undefined

And in the logs I am receiving `"User" must be of type object`

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

18.2.0

### What database are you using?

tested with SQLite and CockroachDB latest versions 

### What browser are you using?

Chrome

### How are you deploying Directus?

Bug appeared on Docker and reproduced locally

**Comment by azrikahar** [comment] 2022-10-11 02:14
> I don't remember experiencing this issue

Just curious, were you upgrading from a previous version that worked? This seems to share the same root cause as #13148 #12600 #11775 which should be present in 9.5.0+ (not sure if supported earlier than that), as relational fields validation issue stems from it not expanding said relational fields. For example, in your step 5 selection, it will populate it with the user ID, but the API is trying to compare that ID (rather than expanding it) with the name validation _object_, hence the "must be an object" error. 

This comment here elaborates more on this issue with relational fields validations (and also relational fields conditions): https://github.com/directus/directus/issues/11775#issuecomment-1065635418. With that said, closing this in favor of tracking it in #11775 👍

**Closed by azrikahar** 2022-10-11 02:14 UTC
