### ISSUE TITLE
Users with limited access cannot comment content items

### ISSUE THREAD

**Issue by Prochy20** [directus/directus#11439] opened 2022-02-04 21:17 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Hi,

I am getting this strange error when users try to comment a content item in collection while they have limited access rights to the collection:

```
0|Admin  | Error: [generateJoi] Filter doesn't contain field key. Passed filter: {}
0|Admin  |     at generateJoi (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/generate-joi.js:74:15)
0|Admin  |     at validatePayload (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:35:55)
0|Admin  |     at /var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:28:82
0|Admin  |     at Array.map (<anonymous>)
0|Admin  |     at validatePayload (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:28:66)
0|Admin  |     at /var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:22:20
0|Admin  |     at Array.map (<anonymous>)
0|Admin  |     at validatePayload (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:21:66)
0|Admin  |     at AuthorizationService.validatePayload (/var/www/esport_admin/node_modules/directus/dist/services/authorization.js:210:84)
0|Admin  |     at /var/www/esport_admin/node_modules/directus/dist/services/items.js:84:46
```

This is how's the rule set for this role

```
{
	"_and": [
		{
			"_and": [
				{
					"status": {
						"_ncontains": "published"
					}
				},
				{
					"status": {
						"_ncontains": "for_approval"
					}
				},
				{
					"author": {
						"id": {
							"_eq": "$CURRENT_USER"
						}
					}
				}
			]
		}
	]
}
```

This is how's the role access rights set:

![image](https://user-images.githubusercontent.com/54104598/152604001-6e7e9d83-2f8c-4a3f-82bf-117bbf958434.png)

### To Reproduce

~~1. Assign the user limited rights to content item~~
~~2. Try to post a comment~~

1. Create a simple collection `test` with one string input
2. Create a role with following additional permissions:
   - full CREATE & READ permissions on collection `test`
   - full CREATE permissions on `directus_activity` (this is the key step)
3. Create a user for above role and login as the user
3. Create an item in collection `test`
4. Create a comment the new item
5. Encounter errors below

### Errors Shown

PM2 LOG:

```
0|Admin  | Error: [generateJoi] Filter doesn't contain field key. Passed filter: {}
0|Admin  |     at generateJoi (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/generate-joi.js:74:15)
0|Admin  |     at validatePayload (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:35:55)
0|Admin  |     at /var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:28:82
0|Admin  |     at Array.map (<anonymous>)
0|Admin  |     at validatePayload (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:28:66)
0|Admin  |     at /var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:22:20
0|Admin  |     at Array.map (<anonymous>)
0|Admin  |     at validatePayload (/var/www/esport_admin/node_modules/directus/node_modules/@directus/shared/dist/cjs/utils/validate-payload.js:21:66)
0|Admin  |     at AuthorizationService.validatePayload (/var/www/esport_admin/node_modules/directus/dist/services/authorization.js:210:84)
0|Admin  |     at /var/www/esport_admin/node_modules/directus/dist/services/items.js:84:46
```

Application just pops a message "Internal server error"

### What version of Directus are you using?

9.5.1

### What version of Node.js are you using?

14.18.3

### What database are you using?

MySQL: Ver 14.14 Distrib 5.7.36, for Linux (x86_64) using EditLine wrapper  What

### What browser are you using?

Google Chrome v 96.0.4664.110

### What operating system are you using?

Desktop: MacOS Monterey 12.1 | Server: Ubuntu 18.04 LTS

### How are you deploying Directus?

Digital Ocean VPS (Using Ubuntu 18.04 LTS)

**Comment by azrikahar** [comment] 2022-02-08 08:28
Hi, unfortunately I can't seem to reproduce this issue on my end, here's a clip on what I did:

https://user-images.githubusercontent.com/42867097/152946196-a944afb1-f9ac-4079-9214-be0529e05e24.mp4

Still image of `Regular` role's permission setting for easier reference:

![image](https://user-images.githubusercontent.com/42867097/152946362-b843c073-b9fc-448c-87a9-bf82a65c0749.png)

Note that the permissions for system collections are all out-of-the-box & default values when I created the Regular role. At a glance, arguably yours are even more permissive, so there shouldn't be any permissions issue. The cursory guess at this point in time is you may have misconfigured a particular permissions. Though this error does seem similar to #8527, but it's still likely a misconfiguration as we had never been able to reproduce that issue as well.

Perhaps you can run the following SQL query (modify the role uuid to yours) to check them out:

`SELECT * FROM "directus_permissions" WHERE role='f20b669d-bc65-4a12-b657-26ccbfc928d1'`

![image](https://user-images.githubusercontent.com/42867097/152947090-0a3db3df-d728-49e0-b83d-785eadb77141.png)

**Comment by Prochy20** [comment] 2022-02-08 08:58
@azrikahar Kindly see video here.

https://user-images.githubusercontent.com/54104598/152952603-3eba5ebc-c5ad-4850-9753-e439a2f2be0c.mov

Actually the users cannot post a comment which results in error as shown above. That's what I am after...

**Comment by azrikahar** [comment] 2022-02-08 10:17
Thanks for sharing the screen capture for confirmation.

>  I just cant explain why is this happening though...

This is particularly why I was wondering would you be able to run the SQL query I had mentioned in my previous comment 😄 or else it would indeed be very hard for us to actually look into this since unfortunately we can't reproduce this issue on our end.

**Comment by Prochy20** [comment] 2022-02-08 11:00
@azrikahar 

![image](https://user-images.githubusercontent.com/54104598/152974241-943173c9-7fa6-4a06-a340-92eab06d0c56.png)


RAW: 

```
id	role	collection	action	permissions	validation	presets	fields
150	bb505004-b777-48ca-ba27-76d993321667	countries	read	{}	{}	NULL	*
1092	bb505004-b777-48ca-ba27-76d993321667	directus_activity	create	{}	{}	NULL	*
1093	bb505004-b777-48ca-ba27-76d993321667	directus_activity	read	{}	{}	NULL	*
1094	bb505004-b777-48ca-ba27-76d993321667	directus_activity	update	{}	{}	NULL	*
1095	bb505004-b777-48ca-ba27-76d993321667	directus_activity	delete	{}	{}	NULL	*
704	bb505004-b777-48ca-ba27-76d993321667	directus_files	create	{}	NULL	NULL	*
705	bb505004-b777-48ca-ba27-76d993321667	directus_files	read	{}	NULL	NULL	*
706	bb505004-b777-48ca-ba27-76d993321667	directus_files	update	{}	NULL	NULL	*
707	bb505004-b777-48ca-ba27-76d993321667	directus_files	delete	{}	NULL	NULL	*
716	bb505004-b777-48ca-ba27-76d993321667	directus_folders	create	{}	NULL	NULL	*
717	bb505004-b777-48ca-ba27-76d993321667	directus_folders	read	{}	NULL	NULL	*
718	bb505004-b777-48ca-ba27-76d993321667	directus_folders	update	{}	NULL	NULL	*
719	bb505004-b777-48ca-ba27-76d993321667	directus_folders	delete	{}	NULL	NULL	NULL
1083	bb505004-b777-48ca-ba27-76d993321667	directus_revisions	update	{}	{}	NULL	*
1084	bb505004-b777-48ca-ba27-76d993321667	directus_revisions	delete	{}	{}	NULL	*
737	bb505004-b777-48ca-ba27-76d993321667	directus_revisions	read	{}	{}	NULL	*
738	bb505004-b777-48ca-ba27-76d993321667	directus_revisions	create	{}	{}	NULL	*
722	bb505004-b777-48ca-ba27-76d993321667	directus_roles	read	{}	NULL	NULL	*
723	bb505004-b777-48ca-ba27-76d993321667	directus_shares	read	{"_or": [{"role": {"_eq": "$CURRENT_ROLE"}}, {"role": {"_null": true}}]}	NULL	NULL	*
724	bb505004-b777-48ca-ba27-76d993321667	directus_shares	create	{}	NULL	NULL	*
725	bb505004-b777-48ca-ba27-76d993321667	directus_shares	update	{"user_created": {"_eq": "$CURRENT_USER"}}	NULL	NULL	*
726	bb505004-b777-48ca-ba27-76d993321667	directus_shares	delete	{"user_created": {"_eq": "$CURRENT_USER"}}	NULL	NULL	*
720	bb505004-b777-48ca-ba27-76d993321667	directus_users	read	{}	{}	NULL	*
721	bb505004-b777-48ca-ba27-76d993321667	directus_users	update	{"id": {"_eq": "$CURRENT_USER"}}	NULL	NULL	first_name,last_name,email,password,location,title,description,avatar,language,theme
149	bb505004-b777-48ca-ba27-76d993321667	dota_heroes	read	{}	{}	NULL	*
148	bb505004-b777-48ca-ba27-76d993321667	dota_positions	read	{}	{}	NULL	*
147	bb505004-b777-48ca-ba27-76d993321667	games	read	{}	{}	NULL	*
590	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki	read	{}	{}	NULL	*
592	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki	create	{}	{}	NULL	*
595	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki	update	{"_and": [{"author": {"id": {"_eq": "$CURRENT_USER"}}}, {"status": {"_in": ["draft", "review"]}}]}	NULL	NULL	avatar,nickname,hero_image,first_name,photo,status,last_name,alte_nicknames,author,user_created,hobbies,birth_date,nationality,social_networks,games,facts,general_information,body
591	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki_games	read	{}	{}	NULL	*
593	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki_games	create	{}	{}	NULL	*
596	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki_games	update	{"personalities_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	games_id,personalities_wiki_id
597	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki_games	delete	{"personalities_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
930	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki_sources	read	{}	{}	NULL	*
931	bb505004-b777-48ca-ba27-76d993321667	personalities_wiki_sources	create	{}	{}	NULL	*
505	bb505004-b777-48ca-ba27-76d993321667	player_wiki_teams	read	{}	{}	NULL	*
506	bb505004-b777-48ca-ba27-76d993321667	player_wiki_teams	create	{}	{}	NULL	*
507	bb505004-b777-48ca-ba27-76d993321667	player_wiki_teams	delete	{"player": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
508	bb505004-b777-48ca-ba27-76d993321667	player_wiki_teams	update	{"_and": [{"_or": [{"player": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}, {"team": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}]}]}	{}	NULL	*
119	bb505004-b777-48ca-ba27-76d993321667	players_wiki	read	{}	{}	NULL	*
120	bb505004-b777-48ca-ba27-76d993321667	players_wiki	update	{"_and": [{"_and": [{"status": {"_ncontains": "published"}}, {"status": {"_ncontains": "for_approval"}}, {"author": {"id": {"_eq": "$CURRENT_USER"}}}]}]}	{"status": {"_ncontains": "published"}}	NULL	avatar,id,nickname,favorite_dota_heroes,hero_image,status,alte_nicknames,dota_positions,photo,hobbies,author,birth_date,nationality,date_created,social_networks,user_updated,facts,date_updated,games,general_information,dota_informations,divider-6hjpzn,body,Assets,team,sources,slug,meta_description,teams,meta_keywords,first_name,last_name,user_created
121	bb505004-b777-48ca-ba27-76d993321667	players_wiki	create	{}	{}	NULL	*
359	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_heroes	create	{}	{}	NULL	*
369	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_heroes	update	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	dota_heroes_id,players_wiki_id,id
370	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_heroes	delete	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
125	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_heroes	read	{}	{}	NULL	*
360	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_positions	create	{}	{}	NULL	*
367	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_positions	update	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	dota_positions_id,players_wiki_id,id
368	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_positions	delete	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
126	bb505004-b777-48ca-ba27-76d993321667	players_wiki_dota_positions	read	{}	{}	NULL	*
356	bb505004-b777-48ca-ba27-76d993321667	players_wiki_games	update	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	games_id,players_wiki_id
357	bb505004-b777-48ca-ba27-76d993321667	players_wiki_games	delete	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
361	bb505004-b777-48ca-ba27-76d993321667	players_wiki_games	create	{}	{}	NULL	*
127	bb505004-b777-48ca-ba27-76d993321667	players_wiki_games	read	{}	{}	NULL	*
351	bb505004-b777-48ca-ba27-76d993321667	players_wiki_sources	create	{}	{}	NULL	*
352	bb505004-b777-48ca-ba27-76d993321667	players_wiki_sources	read	{}	{}	NULL	*
362	bb505004-b777-48ca-ba27-76d993321667	players_wiki_sources	update	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	sources_id,players_wiki_id
363	bb505004-b777-48ca-ba27-76d993321667	players_wiki_sources	delete	{"players_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
134	bb505004-b777-48ca-ba27-76d993321667	social_networks	read	{}	{}	NULL	*
353	bb505004-b777-48ca-ba27-76d993321667	sources	read	{}	{}	NULL	*
354	bb505004-b777-48ca-ba27-76d993321667	sources	create	{}	{}	NULL	*
355	bb505004-b777-48ca-ba27-76d993321667	sources	update	{"user_created": {"id": {"_eq": "$CURRENT_USER"}}}	NULL	NULL	NULL
366	bb505004-b777-48ca-ba27-76d993321667	sources	delete	{"user_created": {"id": {"_eq": "$CURRENT_USER"}}}	NULL	NULL	NULL
523	bb505004-b777-48ca-ba27-76d993321667	teams_wiki	update	{"_and": [{"author": {"id": {"_eq": "$CURRENT_USER"}}}, {"status": {"_in": ["draft", "review"]}}]}	NULL	NULL	hero_image,id,founded,meta_keywords,status,nationality,meta_description,social_networks,author,games,players,facts,perex,body,sources,slug,meta,logo,name,placeholder,active,disbanded
524	bb505004-b777-48ca-ba27-76d993321667	teams_wiki	create	{}	{}	NULL	*
123	bb505004-b777-48ca-ba27-76d993321667	teams_wiki	read	{}	{}	NULL	*
513	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_games	read	{}	{}	NULL	*
514	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_games	create	{}	{}	NULL	*
519	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_games	update	{"teams_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	{}	NULL	*
526	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_games	delete	{"teams_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
515	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_sources	create	{}	{}	NULL	*
516	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_sources	read	{}	{}	NULL	*
518	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_sources	update	{"teams_wiki_id": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	{}	NULL	*
525	bb505004-b777-48ca-ba27-76d993321667	teams_wiki_sources	delete	NULL	NULL	NULL	NULL
598	bb505004-b777-48ca-ba27-76d993321667	wiki_personalities_social_networks	create	{}	{}	NULL	*
599	bb505004-b777-48ca-ba27-76d993321667	wiki_personalities_social_networks	read	{}	{}	NULL	*
600	bb505004-b777-48ca-ba27-76d993321667	wiki_personalities_social_networks	update	{"personality": {"author": {"id": {"_eq": null}}}}	NULL	NULL	personality,social_network,url,description
601	bb505004-b777-48ca-ba27-76d993321667	wiki_personalities_social_networks	delete	{"personality": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
143	bb505004-b777-48ca-ba27-76d993321667	wiki_players_social_networks	read	{}	{}	NULL	*
144	bb505004-b777-48ca-ba27-76d993321667	wiki_players_social_networks	update	{"player": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	{}	NULL	*
145	bb505004-b777-48ca-ba27-76d993321667	wiki_players_social_networks	delete	{"user_created": {"id": {"_eq": "$CURRENT_USER"}}}	{}	NULL	*
146	bb505004-b777-48ca-ba27-76d993321667	wiki_players_social_networks	create	{}	{}	NULL	*
520	bb505004-b777-48ca-ba27-76d993321667	wiki_teams_social_networks	create	{}	{}	NULL	*
521	bb505004-b777-48ca-ba27-76d993321667	wiki_teams_social_networks	read	{}	{}	NULL	*
522	bb505004-b777-48ca-ba27-76d993321667	wiki_teams_social_networks	update	{"team": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	{}	NULL	*
527	bb505004-b777-48ca-ba27-76d993321667	wiki_teams_social_networks	delete	{"team": {"author": {"id": {"_eq": "$CURRENT_USER"}}}}	NULL	NULL	NULL
```

**Comment by azrikahar** [comment] 2022-02-09 05:00
@Prochy20 Thanks for running the query and sharing the result. After looking into it, I believe I may have found out what is the issue here. Currently you have enabled/checked all four CRUD permissions on `directus_activity` which may be the culprit. Can you reset them to their default settings? Here's a quick visualization on what I mean:

![QBjxuuN5be](https://user-images.githubusercontent.com/42867097/153124850-9e8278f2-3dd0-4c77-a9ad-3a83052cc661.gif)

So the `directus_activity` permissions for your role should look like "custom custom none none none" in that order like what I shown if that makes sense. Do try to comment as the user with that role after you done this and get back to us whether that resolves it.

**Comment by azrikahar** [comment] 2022-02-09 05:19
## Investigation result

When we create a new role, it has minimum permissions for create & read in `directus_activity`:

![image](https://user-images.githubusercontent.com/42867097/153125853-a508a30d-b728-401f-b0fd-4eec5c88f51a.png)

So that when we create a comment, one of the filter rules present is:

```js
    {
      "comment": {
        "_nnull": true
      }
    },
```

This is due to the minimal create permissions on `directus_activity` configured here:

https://github.com/directus/directus/blob/d8f744b1512674468f3df567368da62c250d75e2/api/src/database/system-data/app-access-permissions/app-access-permissions.yaml#L10-L14

However, when we give full permissions on create like so:

![image](https://user-images.githubusercontent.com/42867097/153126185-092b3a14-bf0c-4171-a711-001350f8a77d.png)

The filter rule became:

```js
    {
      "_or": [
        {},
        {
          "comment": {
            "_nnull": true
          }
        }
      ]
    },
```

This is because the new full create but EMPTY permissions is merged with minimal create permissions in an OR strategy as seen here:

https://github.com/directus/directus/blob/d8f744b1512674468f3df567368da62c250d75e2/api/src/utils/get-permissions.ts#L79-L83

Since the first child of the OR filter is `{}` (because the user never configured it after checking full permissions), this is why OP faces the error triggered when a filter has no key:

https://github.com/directus/directus/blob/d8f744b1512674468f3df567368da62c250d75e2/packages/shared/src/utils/generate-joi.ts#L84-L86

cc @licitdev 🐱‍🏍

**Comment by benhaynes** [comment] 2022-02-09 12:27
Wow, great research, @azrikahar!! 🙌

**Comment by Prochy20** [comment] 2022-02-09 13:08
Hi @azrikahar ,

Thanks for the research! I did what you suggested and it worked! The only thing is it makes the comments useless because when it's set like that, users cannot see comments of other users, unless I give them an admin access....

Also the users could not delete their own comments and even update them

See on printscreen - left: Admin view | Right: User view....

![image](https://user-images.githubusercontent.com/54104598/153206422-feae2578-90dc-40fd-9a0a-377752ef0b48.png)

So I had to set it up as follows:

![image](https://user-images.githubusercontent.com/54104598/153207079-75198f6a-2978-4981-9a34-0a6634731162.png)

Where I put this condition to update / delete:

```
{
	"user": {
		"id": {
			"_eq": "$CURRENT_USER"
		}
	}
}
```

Anyway the reseting of the rights was a right call, because the "create" action must be set as you have described.

@benhaynes maybe you could think about creating a separated "right" for comments in the future ;-) :-)

**Comment by Prochy20** [comment] 2022-02-09 19:27
Hey @benhaynes - many thanks for your open-minded attitude. 👏

**Closed** 2022-02-28 17:03 UTC
Labels: API, Bug
