### ISSUE TITLE
M2M (Builder) INTERNAL_SERVER_ERROR when select from collection with many items

### ISSUE THREAD

**Issue by melrefaie** [directus/directus#22198] opened 2024-04-15 13:09 UTC
### Describe the Bug

using M2M (Builder) with collection that has many items it fails to load afte selecting some items for first time then save. when trying to add more it fails. but it work with collections with less items

### Directus api log

```
2|medinaportal-websites-api  | [12:53:48] GET /items/archive?filter[_and][0][$FOLLOW(a_stories_items,item,collection)][_none][_and][0][a_stories_id][_eq]=c5359c7e-0f1b-499e-963b-29ce0f3d15aa&filter[_and][0][$FOLLOW(a_stories_items,item,collection)][_none][_and][1][collection][_eq]=archive&aggregate[countDistinct]=id 500 18ms
2|medinaportal-websites-api  | [12:53:48] GET /items/archive?limit=25&fields[]=status&fields[]=featured&fields[]=cover.id&fields[]=cover.type&fields[]=cover.title&fields[]=title&fields[]=category.title&fields[]=category.id&fields[]=category_lv2.title&fields[]=category_lv2.id&fields[]=category_lv3.title&fields[]=category_lv3.id&fields[]=style&fields[]=views&fields[]=date_created&fields[]=collection.title&fields[]=collection.id&fields[]=tags.tags_id.title&fields[]=tags.tags_id.id&fields[]=id&sort[]=-date_created&page=1&filter[_and][0][$FOLLOW(a_stories_items,item,collection)][_none][_and][0][a_stories_id][_eq]=c5359c7e-0f1b-499e-963b-29ce0f3d15aa&filter[_and][0][$FOLLOW(a_stories_items,item,collection)][_none][_and][1][collection][_eq]=archive 500 39ms
2|medinaportal-websites-api  | [12:53:48] GET /items/archive?aggregate[countDistinct]=id 304 38ms
2|medinaportal-websites-api  | [12:53:48.440] ERROR: select count(distinct "archive"."id") as "countDistinct->id" from "archive" left join "a_stories_items" as "txtuf" on "collection" = $1 and "txtuf"."item" = CAST("archive"."id" AS CHAR(255)) where (CAST("archive"."id" AS CHAR(255)) not in (select "a_stories_items"."item" as "item" from "a_stories_items" where "a_stories_items"."item" is not null and ("a_stories_items"."a_stories_id" = $2 and "a_stories_items"."collection" = $3))) limit $4 - column reference "collection" is ambiguous
2|medinaportal-websites-api  |     err: {
2|medinaportal-websites-api  |       "type": "DatabaseError",
2|medinaportal-websites-api  |       "message": "select count(distinct \"archive\".\"id\") as \"countDistinct->id\" from \"archive\" left join \"a_stories_items\" as \"txtuf\" on \"collection\" = $1 and \"txtuf\".\"item\" = CAST(\"archive\".\"id\" AS CHAR(255)) where (CAST(\"archive\".\"id\" AS CHAR(255)) not in (select \"a_stories_items\".\"item\" as \"item\" from \"a_stories_items\" where \"a_stories_items\".\"item\" is not null and (\"a_stories_items\".\"a_stories_id\" = $2 and \"a_stories_items\".\"collection\" = $3))) limit $4 - column reference \"collection\" is ambiguous",
2|medinaportal-websites-api  |       "stack":
2|medinaportal-websites-api  |           error: select count(distinct "archive"."id") as "countDistinct->id" from "archive" left join "a_stories_items" as "txtuf" on "collection" = $1 and "txtuf"."item" = CAST("archive"."id" AS CHAR(255)) where (CAST("archive"."id" AS CHAR(255)) not in (select "a_stories_items"."item" as "item" from "a_stories_items" where "a_stories_items"."item" is not null and ("a_stories_items"."a_stories_id" = $2 and "a_stories_items"."collection" = $3))) limit $4 - column reference "collection" is ambiguous
2|medinaportal-websites-api  |               at Parser.parseErrorMessage (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/parser.js:287:98)
2|medinaportal-websites-api  |               at Parser.handlePacket (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/parser.js:126:29)
2|medinaportal-websites-api  |               at Parser.parse (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/parser.js:39:38)
2|medinaportal-websites-api  |               at Socket.<anonymous> (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/index.js:11:42)
2|medinaportal-websites-api  |               at Socket.emit (node:events:517:28)
2|medinaportal-websites-api  |               at addChunk (node:internal/streams/readable:368:12)
2|medinaportal-websites-api  |               at readableAddChunk (node:internal/streams/readable:341:9)
2|medinaportal-websites-api  |               at Readable.push (node:internal/streams/readable:278:10)
2|medinaportal-websites-api  |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2|medinaportal-websites-api  |       "length": 112,
2|medinaportal-websites-api  |       "name": "error",
2|medinaportal-websites-api  |       "severity": "ERROR",
2|medinaportal-websites-api  |       "code": "42702",
2|medinaportal-websites-api  |       "position": "119",
2|medinaportal-websites-api  |       "file": "parse_relation.c",
2|medinaportal-websites-api  |       "line": "913",
2|medinaportal-websites-api  |       "routine": "colNameToVar"
2|medinaportal-websites-api  |     }
2|medinaportal-websites-api  | [12:53:48.480] ERROR: select "archive"."status", "archive"."featured", "archive"."title", "archive"."style", "archive"."views", "archive"."date_created", "archive"."id", "archive"."cover", "archive"."category", "archive"."category_lv2", "archive"."category_lv3", "archive"."collection" from "archive" inner join (select distinct "archive"."id", "archive"."date_created" as "sort_ypafy" from "archive" left join "a_stories_items" as "qtvil" on "collection" = $1 and "qtvil"."item" = CAST("archive"."id" AS CHAR(255)) where (CAST("archive"."id" AS CHAR(255)) not in (select "a_stories_items"."item" as "item" from "a_stories_items" where "a_stories_items"."item" is not null and ("a_stories_items"."a_stories_id" = $2 and "a_stories_items"."collection" = $3))) order by "archive"."date_created" desc limit $4) as "inner" on "archive"."id" = "inner"."id" order by "inner"."sort_ypafy" desc - column reference "collection" is ambiguous
2|medinaportal-websites-api  |     err: {
2|medinaportal-websites-api  |       "type": "DatabaseError",
2|medinaportal-websites-api  |       "message": "select \"archive\".\"status\", \"archive\".\"featured\", \"archive\".\"title\", \"archive\".\"style\", \"archive\".\"views\", \"archive\".\"date_created\", \"archive\".\"id\", \"archive\".\"cover\", \"archive\".\"category\", \"archive\".\"category_lv2\", \"archive\".\"category_lv3\", \"archive\".\"collection\" from \"archive\" inner join (select distinct \"archive\".\"id\", \"archive\".\"date_created\" as \"sort_ypafy\" from \"archive\" left join \"a_stories_items\" as \"qtvil\" on \"collection\" = $1 and \"qtvil\".\"item\" = CAST(\"archive\".\"id\" AS CHAR(255)) where (CAST(\"archive\".\"id\" AS CHAR(255)) not in (select \"a_stories_items\".\"item\" as \"item\" from \"a_stories_items\" where \"a_stories_items\".\"item\" is not null and (\"a_stories_items\".\"a_stories_id\" = $2 and \"a_stories_items\".\"collection\" = $3))) order by \"archive\".\"date_created\" desc limit $4) as \"inner\" on \"archive\".\"id\" = \"inner\".\"id\" order by \"inner\".\"sort_ypafy\" desc - column reference \"collection\" is ambiguous",
2|medinaportal-websites-api  |       "stack":
2|medinaportal-websites-api  |           error: select "archive"."status", "archive"."featured", "archive"."title", "archive"."style", "archive"."views", "archive"."date_created", "archive"."id", "archive"."cover", "archive"."category", "archive"."category_lv2", "archive"."category_lv3", "archive"."collection" from "archive" inner join (select distinct "archive"."id", "archive"."date_created" as "sort_ypafy" from "archive" left join "a_stories_items" as "qtvil" on "collection" = $1 and "qtvil"."item" = CAST("archive"."id" AS CHAR(255)) where (CAST("archive"."id" AS CHAR(255)) not in (select "a_stories_items"."item" as "item" from "a_stories_items" where "a_stories_items"."item" is not null and ("a_stories_items"."a_stories_id" = $2 and "a_stories_items"."collection" = $3))) order by "archive"."date_created" desc limit $4) as "inner" on "archive"."id" = "inner"."id" order by "inner"."sort_ypafy" desc - column reference "collection" is ambiguous
2|medinaportal-websites-api  |               at Parser.parseErrorMessage (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/parser.js:287:98)
2|medinaportal-websites-api  |               at Parser.handlePacket (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/parser.js:126:29)
2|medinaportal-websites-api  |               at Parser.parse (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/parser.js:39:38)
2|medinaportal-websites-api  |               at Socket.<anonymous> (/var/www/medina/medinaportal-websites-api/node_modules/pg-protocol/dist/index.js:11:42)
2|medinaportal-websites-api  |               at Socket.emit (node:events:517:28)
2|medinaportal-websites-api  |               at addChunk (node:internal/streams/readable:368:12)
2|medinaportal-websites-api  |               at readableAddChunk (node:internal/streams/readable:341:9)
2|medinaportal-websites-api  |               at Readable.push (node:internal/streams/readable:278:10)
2|medinaportal-websites-api  |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2|medinaportal-websites-api  |       "length": 112,
2|medinaportal-websites-api  |       "name": "error",
2|medinaportal-websites-api  |       "severity": "ERROR",
2|medinaportal-websites-api  |       "code": "42702",
2|medinaportal-websites-api  |       "position": "422",
2|medinaportal-websites-api  |       "file": "parse_relation.c",
2|medinaportal-websites-api  |       "line": "913",
2|medinaportal-websites-api  |       "routine": "colNameToVar"
2|medinaportal-websites-api  |     }
```

### Create M2M (Builder) and add some collection to it

<img width="272" alt="image" src="https://github.com/directus/directus/assets/25461028/296eb220-76e4-4de2-abca-ca8398a14eea">

### When i add archive collection for the first time it works fine. but when i try to add more later it fails. 

<img width="666" alt="image" src="https://github.com/directus/directus/assets/25461028/fc36aef6-e15e-4342-9696-9c42a57b1104">
<img width="222" alt="image" src="https://github.com/directus/directus/assets/25461028/925cf20d-8b41-499f-9efc-0d9faaceb7b5">

### After selecting some items then save and try add more it fails

<img width="498" alt="image" src="https://github.com/directus/directus/assets/25461028/b11b69ca-7227-408b-b90b-6e8192acd36d">

```
{
  "errors": [
    {
      "message": "select \"archive\".\"status\", \"archive\".\"featured\", \"archive\".\"title\", \"archive\".\"style\", \"archive\".\"views\", \"archive\".\"date_created\", \"archive\".\"id\", \"archive\".\"cover\", \"archive\".\"category\", \"archive\".\"category_lv2\", \"archive\".\"category_lv3\", \"archive\".\"collection\" from \"archive\" inner join (select distinct \"archive\".\"id\", \"archive\".\"date_created\" as \"sort_vhrcf\" from \"archive\" left join \"a_stories_items\" as \"jixoa\" on \"collection\" = $1 and \"jixoa\".\"item\" = CAST(\"archive\".\"id\" AS CHAR(255)) where (CAST(\"archive\".\"id\" AS CHAR(255)) not in (select \"a_stories_items\".\"item\" as \"item\" from \"a_stories_items\" where \"a_stories_items\".\"item\" is not null and (\"a_stories_items\".\"a_stories_id\" = $2 and \"a_stories_items\".\"collection\" = $3))) order by \"archive\".\"date_created\" desc limit $4) as \"inner\" on \"archive\".\"id\" = \"inner\".\"id\" order by \"inner\".\"sort_vhrcf\" desc - column reference \"collection\" is ambiguous",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### If i select another collection with less items it works fine 
<img width="658" alt="image" src="https://github.com/directus/directus/assets/25461028/1426685d-b914-4a37-b465-c0958cb88ddd">

<img width="209" alt="image" src="https://github.com/directus/directus/assets/25461028/59c47fe4-ef79-4ee9-8da0-ccc26b13b779">

### Network log 
<img width="706" alt="image" src="https://github.com/directus/directus/assets/25461028/5dd90197-06a0-4359-a141-7764baf20229">

Response
```
{
    "errors": [
        {
            "message": "select count(distinct \"archive\".\"id\") as \"countDistinct->id\" from \"archive\" left join \"a_stories_items\" as \"wodcu\" on \"collection\" = $1 and \"wodcu\".\"item\" = CAST(\"archive\".\"id\" AS CHAR(255)) where (CAST(\"archive\".\"id\" AS CHAR(255)) not in (select \"a_stories_items\".\"item\" as \"item\" from \"a_stories_items\" where \"a_stories_items\".\"item\" is not null and (\"a_stories_items\".\"a_stories_id\" = $2 and \"a_stories_items\".\"collection\" = $3))) limit $4 - column reference \"collection\" is ambiguous",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

```
{"data":[{"countDistinct":{"id":"256"}}]}
```

```
{
    "errors": [
        {
            "message": "select \"archive\".\"status\", \"archive\".\"featured\", \"archive\".\"title\", \"archive\".\"style\", \"archive\".\"views\", \"archive\".\"date_created\", \"archive\".\"id\", \"archive\".\"cover\", \"archive\".\"category\", \"archive\".\"category_lv2\", \"archive\".\"category_lv3\", \"archive\".\"collection\" from \"archive\" inner join (select distinct \"archive\".\"id\", \"archive\".\"date_created\" as \"sort_rvcag\" from \"archive\" left join \"a_stories_items\" as \"qlmcw\" on \"collection\" = $1 and \"qlmcw\".\"item\" = CAST(\"archive\".\"id\" AS CHAR(255)) where (CAST(\"archive\".\"id\" AS CHAR(255)) not in (select \"a_stories_items\".\"item\" as \"item\" from \"a_stories_items\" where \"a_stories_items\".\"item\" is not null and (\"a_stories_items\".\"a_stories_id\" = $2 and \"a_stories_items\".\"collection\" = $3))) order by \"archive\".\"date_created\" desc limit $4) as \"inner\" on \"archive\".\"id\" = \"inner\".\"id\" order by \"inner\".\"sort_rvcag\" desc - column reference \"collection\" is ambiguous",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ]
}
```

### Directus Version

v10.9.3

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2024-04-16 10:03
Looking at the description it looks like you are using a `many-to-any` instead of a `many-to-many`.

**Comment by br41nslug** [comment] 2024-04-16 10:29
Hadnt seen this older ticket before, this seems to be a duplicate of https://github.com/directus/directus/issues/21663 considering it's the exact same error.

**Closed by br41nslug** 2024-04-16 10:29 UTC
Labels: :detective: Needs Research

**Comment by melrefaie** [comment] 2024-04-16 10:56
> Looking at the description it looks like you are using a `many-to-any` instead of a `many-to-many`.
> 
> @melrefaie What database are you using?

I use postgres.

yes its `many-to-any` 
<img width="293" alt="image" src="https://github.com/directus/directus/assets/25461028/cd3c5113-71a7-40ce-8fe2-d1e919708f54">

**Comment by melrefaie** [comment] 2024-04-16 11:02
> Hadnt seen this older ticket before, this seems to be a duplicate of #21663 considering it's the exact same error.

@br41nslug i think its different cause i don't have any permissions and i use Administrator role user.

plus it works fine in create for first time but this issuse appear when edit

**Comment by br41nslug** [comment] 2024-04-16 11:05
I dont think permissions are the cause there, as he mentions he has a field named `collection` on the related m2a table causing the issue.

**Comment by melrefaie** [comment] 2024-04-16 11:07
> I dont think permissions are the cause there, as he mentions he has a field named `collection` on the related m2a table causing the issue.

Yes i do have one i will try rename it
