### ISSUE TITLE
Importing relationships when tables are created outside the application

### ISSUE THREAD

**Issue by devistar** [directus/directus#9123] opened 2021-10-25 14:18 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When importing tables are created outside the application, the relations are not correctly defined in directus.

They are not recorded in the directus_relations table.

We cannot therefore use the advanced filters on the relation.

It is also not possible to define the special o2m field in the referenced table.

### To Reproduce

Import tables with relationships that were not created using the directus app.

Try to edit the relation field.

Try to apply an advanced filter in the list.

### Errors Shown

No errors shown

### What version of Directus are you using?

9.0.0-rc.99

### What version of Node.js are you using?

v14.15.4

### What database are you using?

SQL Server 2017

### What browser are you using?

Vivaldi

### What operating system are you using?

Windows

### How are you deploying Directus?

Running locally

**Comment by Oreilles** [comment] 2021-10-30 13:41
Maybe related to https://github.com/directus/directus/issues/9182

**Comment by Oreilles** [comment] 2021-11-01 11:16
Duplicate of https://github.com/directus/directus/issues/9182.
When adding the fields, the relations are not recognized anymore, which is why they're not added.

**Closed by Oreilles** 2021-11-01 11:16 UTC
Labels: Needs More Info
