### ISSUE TITLE
Double mustaches in Update Data operation's payload and IDs lead to errors for non-admin users

### ISSUE THREAD

**Issue by RawmanGrey** [directus/directus#24025] opened 2024-11-11 16:48 UTC
### Describe the Bug

Flow with event hook blocking items updates (at least in my use case) has to end with requested update. To achieve that, I use "Update Data" operation: by toggling raw editor and entering `{{$trigger.keys}}` to "IDs" field and `{{$trigger.payload}}` to "Payload" field. Update Data operation takes permissions from trigger. 

Problem is, if flow is triggered by update initiated by non-admin user*, it results in 403 error: `"You don't have permission to access field \"0\" in collection \"collection\" or it does not exist. Queried in root."`. Despite the error, update is applied to item. 

I suppose, this is related to #23989 

* User has all required permissions to alter collection and can do so if flow is disabled.

### To Reproduce

I was able to reproduce this issue on below docker compose:
```
name: test-directus

services:
  postgis:
    container_name: test--postgis
    image: postgis/postgis:16-3.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 25432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  directus:
    image: directus/directus:11.2.1
    container_name: test--directus
    ports:
      - 8055:8055
    depends_on:
      postgis:
        condition: service_healthy
    environment:
      - KEY=secret
      - SECRET=secret
      - ADMIN_EMAIL=admin@mail.com
      - ADMIN_PASSWORD=password
      - DB_CLIENT=pg
      - DB_HOST=postgis
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - SERVE_APP=true

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:8055/server/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

networks:
  default:
    name: test-network
```
To reproduce:
1) Log into admin account and create "test" collection with simple text input field "name". Create item there.
2) Create new flow, triggered by item update in "test" collection. Choose blocking type.
2.2) Add Update Data operation, choose "test" collection, click on "{}" button next to "IDs" field and input `{{$trigger.keys}}` there. click on "{}" button next to "Payload" field and enter `{{$trigger.payload}}` there. Save Flow.  
3) Create new user, grant him permissions to perform updates on "test" collection. 
4) Login to new user, try updating item and witness error.

### Directus Version

v11.2.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgis:16-3.4

**Comment by hanneskuettner** [comment] 2024-11-11 19:11
Can you see the payload that is being passed to the update data operation? This might explain what is going wrong.

**Comment by RawmanGrey** [comment] 2024-11-12 06:54
> Can you see the payload that is being passed to the update data operation? This might explain what is going wrong.

Yes, all data in flow looks the same — both if update triggered by admin and not admin.


<details> 
  <summary>Screenshot of data in flow </summary>
  
   ![Screenshot_20241112](https://github.com/user-attachments/assets/b0e4da44-d818-4e8e-8d72-b46fc1c9e230)
</details>

<details> 
  <summary>Screenshot of Update Data operation settings </summary>
  
  ![Screenshot_20241112_0](https://github.com/user-attachments/assets/45b83e37-d533-4273-9d9f-054cd4d0b899)
</details>

**Comment by hanneskuettner** [comment] 2024-11-12 08:23
Ah. This makes sense. I was just able to replicate the problem. It has to do with the way you use an update data operation in a filter trigger. 

A flow triggered with a filter or action hook expects that the flow returns the modified data that is used for item update operation. As such it takes the result of the filter flow as the new payload for the item update. In your case this is the primary key returned by the "Update Data" operation, so `1`, which is the wrong payload type for the item update.

Your item still gets updated since you use the update data operation in your flow. So the order of operations that are happening are

* The item update is started
* Filter flow is triggered
* Flow calls "Update Data" with the full payload and updates your item (that's the update you see) and returns "1"
* The return value of the flow is used as the new item update payload of the outer item update (and "1" is not the correct form (as a JSON object is expected))
* The outer item update fails with the error message because of the malformed payload

So this is not a bug in Directus, but rather a symptom of using the filter flow incorrectly. I don't know what your original intentions were, but if it is modifying the item update payload before it is updated in the database, you can just use a "Transform Payload".

I will close this, as this is not a bug.

**Closed by hanneskuettner** 2024-11-12 08:23 UTC

**Comment by RawmanGrey** [comment] 2024-11-12 10:06
Thank you for detailed explanation, @hanneskuettner! 

It was weird, that flow's behavior was different with admin and non-admin users... Adding `$trigger.payload` to Trigger's response "other" body solves my problem, so as ending flow by returning `$trigger.payload`

**Comment by hanneskuettner** [comment] 2024-11-12 10:08
> It was weird, that flow's behavior was different with admin and non-admin users 

That is because for non-admin users there is some additional permission checking which is missing on the admin side. And that piece of code was stumbling over the malformed payload.
