### ISSUE TITLE
Adding O2M to any collection fails

### ISSUE THREAD

**Issue by M-GRV** [directus/directus#18690] opened 2023-05-22 16:00 UTC
### Describe the Bug

Currently when trying to create an O2M on any collection it will fail with this error:
![image](https://github.com/directus/directus/assets/130182174/8a0dfe47-d9d6-44ee-85de-1a44302b50ad)

Workaround:
You can instead go to the collection you wanted to relate too and create a M2O, during the advanced setup under relation, you can select create O2M. That will work.

![image](https://github.com/directus/directus/assets/130182174/c6ca4cb4-6f0a-4c75-ad5f-eb8981e4b09d)

on 10.1.1 using postgres

### To Reproduce

On any current or new collection, try to create a O2M. 

### Directus Version

10.1.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-05-23 10:49
Tested on postgres but unable to reproduce this locally with the given reproduction steps. This is likely some error state specifically in your database like foreign key name collision or similar.


https://github.com/directus/directus/assets/9389634/86ecd950-df9f-40d0-8283-7646a51a5e9d



Closing this issue for now, happy to re-open when more detailed information becomes available.

**Closed by br41nslug** 2023-05-23 10:49 UTC

**Comment by resultatum** [comment] 2023-09-10 18:00
@M-GRV @mcarlson @smashwilson @freekrai 
I have same error https://github.com/directus/directus/issues/19648
