### ISSUE TITLE
Colored dot favicon does not work if a custom module is loaded

### ISSUE THREAD

**Issue by christianrr** [directus/directus#8461] opened 2021-09-30 14:14 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When a project color and logo is set, the favicon of the Admin App should appear as colored dot. However, this works only as long as no custom modules or interfaces are loaded. 

If any plugins are included, the app watch handlers for serverStore in app.vue do not fire any more. For that reason, the favicon does not get replaced any more.

I assume, that there is an issue with the rollup plugin mechanism?

### To Reproduce

- Setup a clean Directus installation
- Open it up and configure project color and logo
- Logout from Admin App
- Favicon is displayed as colored dot ✌️

- Now, add a custom module (as described in the docs)
- Restart Directus
- Reload the Admin app
- Default favicon is displayed, because serverStore watchers do not fire any more

### What version of Directus are you using?

v9.0.0-rc95

### What version of Node.js are you using?

v14.16

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2021-09-30 15:04
Very odd indeed. @nickrum any thoughts?

**Comment by nickrum** [comment] 2021-09-30 15:09
I can't think of a way in which extension loading could affect the serverStore. I'll take a look 👍

**Comment by rijkvanzanten** [comment] 2021-12-03 01:03
I can't reproduce this on 9.1.2 with a fresh setup. Would you be able to share the offending module that causes this behavior? Thanks!

---

Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-12-03 01:03 UTC
Labels: Needs More Info
