### ISSUE TITLE
Extra delimiters when storing the value for the checkboxes

### ISSUE THREAD

**Issue by dsivokhin** [directus/directus#1681] opened 2017-07-11 13:39 UTC
## Version Info
  - Directus version and branch: 6.4 master
  - PHP version: 7.0
  - MySQL version: Mysql 5.6
  - Web server: nginx
  - OS name and version: Ubuntu 16.04

## Expected Behavior
In my table column  `value1, value2, ... value{n}` - without first and last delimetr

## Actual Behavior
UI checkboxes save values in my table column like: `,value1, value2, ... value{n},`

**Comment by benhaynes** [comment] 2017-07-11 13:49
Hey @dsivokhin – this is by design. Though we can add an interface option to disable this. Here is the reasoning:

Let's say this is managing tags (or something similar). If you need to query for a specific tag:

`SELECT * FROM vehicles WHERE tag = '%car%'`
**This will return results with car, cart, carriage, etc...**

`SELECT * FROM vehicles WHERE tag = '%,car,%'`
**This will only return results with "car"** but this only works if you have leading and trailing delimiters.

**Comment by rijkvanzanten** [comment] 2017-07-11 14:24
Hey @dsivokhin! I've made the extra delimiters optional in https://github.com/directus/directus/commit/453f1470a805fa7e2c3c72b169dc87fc4fe8e1d4. This will be merged into master soon, but you could use [the develop branch](https://github.com/directus/directus/tree/develop) if you need this option now.

**Comment by WellingGuzman** [comment] 2017-07-11 17:59
Wouldn't this break the filtering? we should find a way to filter the values OR warn the filter won't work as expected.

**Comment by rijkvanzanten** [comment] 2017-07-11 19:30
Filtering should still work, but it will also show items which match the pattern next to only this with full word. This is different behavior than "normal", but could be very useful in certain situations nonetheless.

**Comment by WellingGuzman** [comment] 2017-07-11 19:44
yeah, that what I meant, and this is an optional option. so we should be good.

**Comment by dsivokhin** [comment] 2017-07-20 11:48
@rijkvanzanten, Thank you, when saving item it's work, but when displaying on the page, not all checkboxes are correctly marked

**Comment by rijkvanzanten** [comment] 2017-07-20 13:07
Hi @dsivokhin, that definitely shouldn't happen. I'll check it out!

**Comment by WellingGuzman** [comment] 2017-07-21 11:42
Hey @dsivokhin, does this commit (https://github.com/directus/directus/commit/54a2390b934d7d2636028bb3c454a1782a57cc26) fixes the problem you are experiencing.

@rijkvanzanten I took the change as I just experienced this issue (or similar) myself.

**Comment by WellingGuzman** [comment] 2017-08-04 06:21
I will call this closed. no responses in days, but more importantly fixed by https://github.com/directus/directus/commit/54a2390b934d7d2636028bb3c454a1782a57cc26

**Closed by WellingGuzman** 2017-08-04 06:21 UTC
Labels: 4. Minor, Interface, Optimization
