### ISSUE TITLE
Unwanted autocomplete

### ISSUE THREAD

**Issue by manuelwehrli** [directus/directus#4815] opened 2021-04-01 23:56 UTC
When editing a user in the admin app, the browser's password manager always fills out the "empty" (hidden content) password field with the first credential found for the domain, so when saving, it overwrites the password of a user with one of the editor without his awareness, so the user will be locked out suddenly. When creating a new user, it even fills out the email field with the first username/email found in the password manager. This behaviour should only happen on a login mask. Having different backoffice workers, this will lead to chaos in the database when they need to edit user data, as they probably will save their credentials in a password manager for fast access to the admin app. The problem of browsers ignoring autocomplete=off is well-known, but there are simple solutions to resolve it, for example here: https://stackoverflow.com/questions/23646953/stop-browser-from-auto-filling-the-form-username-and-password-fields

Environment: Directus v9.0.0-rc.53 / Postgres 13.2 / Docker / Firefox 87.0

**Comment by benhaynes** [comment] 2021-04-02 14:55
Duplicate of: https://github.com/directus/directus/issues/4348

@rijkvanzanten — any reasons this would still be happening?

**Closed** 2021-04-02 15:02 UTC
Labels: Duplicate

**Comment by rijkvanzanten** [comment] 2021-04-02 15:04
@benhaynes the problem is that some password managers ignore the specced autocomplete flag

The

> but there are simple solutions to resolve it

are not _as_ simple as it might sound, as it relies on hacking in `readonly` and disabling it on the fly on `blur`. However, just tacking that on means that we'll break the regular use of `readonly` that already exists

**Comment by manuelwehrli** [comment] 2021-04-02 15:14
Can we at least load a pseudo-value into the password field, which does not get saved unless changed, so the browser does not see any need to autocomplete something? I think that many admin dashboards do something like this to avoid other hacks.

**Comment by rijkvanzanten** [comment] 2021-04-02 15:16
That could work, just unfortunate that it removes the "value was hashed" message in the input placeholder, but that's an acceptable tradeoff. Wanna open a PR for that @manuelwehrli? Should only apply to the `hashed` interface
