### ISSUE TITLE
Action Flow doesn't show updated payload anymore

### ISSUE THREAD

**Issue by franklaboris** [directus/directus#22506] opened 2024-05-16 02:37 UTC
### Describe the Bug

I was using v10.4. until a couple of weeks ago
I have a 'filter' (on create) flow that adds a couple of properties to the payload. It works as expected creating a DB record with those 2 additional fields.
I have another 'action' (on create) flow triggered by the same collection and the same action. On v10.4 $trigger.payload included the new 2 properties
Now in v10.11 the payload in the 'action' flow is not showing any changes.

Is this the intended behavior? IMHO the previous behavior made more sense.
Is there a way to recover the modified payload in the 'action' flow?

### To Reproduce

To have a 'filter' flow and an 'action' flow triggered on 'create' event on the same collection

### Directus Version

v10.11

### Hosting Strategy

Self-Hosted (Custom)

### Database

postgres 15

**Comment by hanneskuettner** [comment] 2024-05-16 04:46
Just to make sure, by additional fields, you actually mean fields that are set up in your collection and not some "random" metadata you're trying to attach to the payload?

**Comment by br41nslug** [comment] 2024-05-16 12:26
Duplicate of https://github.com/directus/directus/issues/19473

**Closed by br41nslug** 2024-05-16 12:26 UTC
