### ISSUE TITLE
Boolean values not showing on content Dashboard

### ISSUE THREAD

**Issue by hissingpanda** [directus/directus#18521] opened 2023-05-08 20:16 UTC
### Describe the Bug

Boolean fields are no longer indicating true and false values on the main dashboard. They just show blank null values. When selecting individual records the same fields show the correct True/False value.

![Screenshot 2023-05-08 131102](https://user-images.githubusercontent.com/7660115/236924452-6abdd169-330b-45a5-bf0a-8673c07dbd36.png)

Here you can see one of those same records showing True within the record for the same field.
![Screenshot 2023-05-08 125329](https://user-images.githubusercontent.com/7660115/236924661-452239af-dcaf-4ba8-9b99-a120e16fe4aa.png)

### To Reproduce

1. Create a Boolean field
2. Create new item and set boolean field to true
3. Go to the content dashboard and add that field to show it

### Directus Version

v10.0.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-05-09 21:49
Thanks for opening this issue! However this is a duplicate of an existing issue #18317, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #18317 has been fixed by #18357 which will be available with the next release.

**Closed by paescuj** 2023-05-09 21:49 UTC
Labels: App, Bug
