### ISSUE TITLE
When creating a record, the condition for the readonly field outside the group does not work

### ISSUE THREAD

**Issue by koksikus** [directus/directus#17242] opened 2023-01-19 15:56 UTC
### Describe the Bug

When creating a record, the condition for the readonly field outside the group does not work. 

https://user-images.githubusercontent.com/90528895/213489819-8fcad6ed-c44a-4dfb-acd1-1fe78b8b71b6.mp4

As seen in the video. The main thing is that this only happens when creating a new record. When the record is already saved, the condition always works. When creating a new record, if the field to which the condition applies is in the same group, it works, just move it outside the group and, unfortunately, it does not work anymore.

### To Reproduce

Create a condition, considering a field outside the group. Condition for a read-only field.
When creating a record, see if you can edit this field.

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

16.18.1

### What database are you using?

MS SQL or MySQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by koksikus** [comment] 2023-02-06 13:07
Is this a bug, or am I wrong??

**Comment by koksikus** [comment] 2023-02-14 19:33
I checked it again and the field cannot be in any group. If it is in it, the condition does not work when creating the record.

**Comment by koksikus** [comment] 2023-03-20 17:45
I'm very curious if I found a bug or it's my wrong setting 🤔😉

**Comment by rijkvanzanten** [comment] 2023-03-20 19:31
I think it's a bug :)

**Comment by koksikus** [comment] 2023-03-20 19:50
Thanks for the answer and I'm sad that it is true 😭😉. 
I use this solution very often due to another bug #11058

**Comment by Nitwel** [comment] 2023-10-09 15:25
I was not able to reproduce this on the latest version, could you (@koksikus) check again if this is still an problem for you on the latest version? I'm gonna close this for now but in case this is still not fixed for you, we're gonna open this issue again.

**Closed by Nitwel** 2023-10-09 15:25 UTC
Labels: Package: @directus/app, Bug

**Comment by koksikus** [comment] 2023-10-09 15:42
I confirm, it works in the latest version.
