### ISSUE TITLE
User info popover positioned incorrectly for revisions

### ISSUE THREAD

**Issue by aidenfoxx** [directus/directus#8026] opened 2021-09-14 12:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When hovering over an editors name under collection revisions, the user info popover is positioned incorrectly in Firefox and Chrome.

<img width="1479" alt="Screenshot 2021-09-14 at 14 45 27" src="https://user-images.githubusercontent.com/5548518/133260727-643a08cc-4600-4bb7-89f7-02ad05a2268f.png">

### To Reproduce

Hover over a users name under revisions.

### What version of Directus are you using?

rc92

### What version of Node.js are you using?

v14.17.6

### What database are you using?

OracleDB

### What browser are you using?

Firefox and Chrome

### What operating system are you using?

MacOS and Linux

### How are you deploying Directus?

K8S

**Comment by nickrum** [comment] 2021-09-14 12:58
This has already been fixed by #7947 which will be included in the next release.

Duplicate of #7926

**Closed by nickrum** 2021-09-14 12:58 UTC
Labels: Bug (Potential)
