### ISSUE TITLE
After deleting a field from a collection it is nor removed from directus_fields table thus triggering error "Field x Already Exists"

### ISSUE THREAD

**Issue by isawk** [directus/directus#20472] opened 2023-11-19 08:44 UTC
### Describe the Bug

When a field is created on a collection and that field is deleted, attempt to recreate same field with same name triggers a field already exists error. It seems a field is not removed from directus_fields tables when deleted from collection.

**Database Table Definition**
Notice column names do not match those in directus_fields, fields has column "title" which was deleted

![image](https://github.com/directus/directus/assets/21027753/3d3b270d-3aee-4c1c-aac6-225085907b03)

**Whats in directus_fields tables**
Notice field "title" which is no longer in table definition, column was deleted

![image](https://github.com/directus/directus/assets/21027753/ed26a259-90fd-49dd-9624-0e02321f206d)

### To Reproduce

- Create a collection
- Added a field to the collection
- Remove the field from the collection
- Attempt to create same field again with same name

### Directus Version

10.8.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2023-11-19 14:55
I've tested this and was unfortunately unable to reproduce this given the reproduction steps. Please elaborate on the specific situation/setup that is causing this issue. Things that may help reproduction are:
- how are you running Directus?
- Do you get any errors/logs on deletion/creation?
- What database vendor are you using?

Closing this for now but happy to re-open the issue once more information becomes available.

**Closed by br41nslug** 2023-11-19 14:55 UTC
Labels: Needs More Info

**Comment by Valektrum** [comment] 2024-01-23 18:44
We have the same issue.
- We are running Directus 10.8.3 on Azure using the docker image
- When trying to create the field, I get the following error message: `Invalid payload. Field "fieldName" already exists in collection "collectionName".`
- We are using mssql

Would it be safe to manually delete the entry in "directus_fields"?

**Comment by br41nslug** [comment] 2024-01-24 11:09
If the actual field no longer exists then yeah it should be safe to delete from `direcuts_fields` (this is quite the error state as something removed the field directly in the database avoiding Directus logic). Also be sure to double check `directus_relations` if it is a relational field.
