### ISSUE TITLE
After deleting a custom module, its reference in the (SQLite) db "directus-settings" is not removed

### ISSUE THREAD

**Issue by rowild** [directus/directus#14205] opened 2022-06-30 07:25 UTC
### Describe the Bug

Removing a (deactivated) module extension from its folder "extension/modules" does not remove it from its json in the SQLite db table "directus-settings" => "module_bar". 

### To Reproduce

1. locally, create a module extension 
2. move the content of "dist" to the directus instance's "extension/modules/[ext-name]" location
3. (re)start directus
4. go to settings
5. activate the custom module
6. check SQLite db "directus-settings" => "module_bar": the custom module is listed there (set to "enabled": "true")
7. deactivate custom module
9. check db again: the custom module is there (set to "enabled": "false")
10. remove the custom module from "extensions/modules"
11. restart directus (to clear all cache)
12. check terminal, where all loaded ext will be listed; the custom module should not be there anymore
13. check db again: the custom module is STILL there (set to "enabled": "false"), even though it shouldn't

### Errors Shown

No errors shown, but here are some screenshots of the procedure:

1. Install custom module

![01-custom-module-installed](https://user-images.githubusercontent.com/213803/176616896-1d379556-d049-46eb-91cc-7424eef97eb4.jpg)

2. Restart directus

![02-custom-module-loaded-after-restart](https://user-images.githubusercontent.com/213803/176616910-296940b7-dc9b-4e96-989d-09f19b4d27e6.jpg)

3. go to settings...

![03-custom-module-appears-in-settings](https://user-images.githubusercontent.com/213803/176616913-a8700c8b-cf93-44b8-91e0-fb1ac5296331.jpg)

4. ... and activate the custom module

![04-active-custom-modules](https://user-images.githubusercontent.com/213803/176616918-bc0ca77f-c5f7-4294-a708-c7d43d974d35.jpg)

5. Check db: module is there, "enabled" set to "true"

![05-check-db](https://user-images.githubusercontent.com/213803/176616925-ce36ddc0-422e-4849-a77f-5dd9899933d5.jpg)

6. Deactivate custom module – restart directus – check terminal: custom module not loaded anymore

![06-deactivate-custom-modules-insettings-and-restart-directus__module-not-loaded](https://user-images.githubusercontent.com/213803/176616928-c2f8a65f-7000-40b2-a1e6-7110269b8334.jpg)

7. Check db: "enabled" set to "false":

![07-check-db__module-enabled-set-to-false](https://user-images.githubusercontent.com/213803/176616930-a78366cb-03c4-4e47-9fb9-6cad460c6148.jpg)

8. Now remove all custom-module-related files from "extensions/modules", restart directus and check db again: the entry to the custom module is still there

![08-remove-files-from-ext-folder-and-restart-directus__check-db__module-still-there](https://user-images.githubusercontent.com/213803/176616933-42d615a8-c369-452b-925c-9b583db70936.jpg)

### What version of Directus are you using?

9.12.2, 9.13.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

SQLite 3.28.0

### What browser are you using?

Chrome 103

### How are you deploying Directus?

locally

**Comment by rijkvanzanten** [comment] 2022-06-30 14:54
While this is technically the case, I don't think it's something worth resolving. The only real way to "fix" this would be for the app to check whether or not any allow-list items are configured that don't correspond to an existing module, and then push an update to /settings to remove just that one item. That's quite a bit of extra overhead to maintain to optimize a field value in settings that doesn't cause any side effects at all 🤔 

Seeing that this doesn't cause any issues in usage of Directus at all, and seeing that the only workaround would cause a lot of additional stuff to maintain for no real benefits, I think we'll consider this a won't-fix. Happy to keep discussing tho!

**Closed by rijkvanzanten** 2022-06-30 14:54 UTC
Labels: Won't Fix

**Comment by rowild** [comment] 2022-06-30 15:11
@rijkvanzanten Thank you for your feedback! I agree that this is very minor.

However, there is one case I'd like to bring to your attention. 
This is what Idid:

- I installed @wellenform/directus-extension-hourclock-module
- I copied (!) the content of its "dist" folder to "extension/modules/hourclock/'

This left me with 2 modules of the same name, one in node_modules (installed via npm), the other one in "extensions/modules" (were I copied the files to manually). 
(I know that this is a totally wrong way, nevertheless it was the reason why I found this error.)

And eventually that resulted in giving me 2 options with the same name in SETTINGS for the same thing. With 2 entries in the respective json field of the directus-settings table.

The  only way to solved this "problem" is by going to the db.
Since this problem can be created, I wonder, if this isn't a potential danger living in the quiet?

More importantly: I'm far away from being good at Directus, but so far I understood that adding and removing extensions requires a restart of directus. Therefore I am not so sure if a solution of this problem would really result in such an overhead? My naive thinking in this case works like this:
Whenever I restart Directus, the terminal tells me which extensions were detected. Which means it is detecting all the active and inactive stuff anyway, whenever I start Directus. How about simply overwriting that very db entry at start-up? That's a common approach, as far as I know, when it comes to config files and similar stuff. (I know that this is the case in TYPO3, and it is very fast.)

Furthermore: So far I only checked "modules". What if the same thing happens with "Interfaces", "panels", etc? (I haven't checked how those are saved, so I might be assuming something that is in fact irrelevant.)

**Comment by rijkvanzanten** [comment] 2022-06-30 15:16
That case wouldn't necessarily be solved by working around the issue mentioned in the original post though. In this case, the problem sounds like the module was imported twice because it was duplicated between `node_modules` and `extensions`, cleaning out the settings on restarts wouldn't necessarily have solved the duplication problem.

As for the other extensions, most places where extensions are used in app are built with graceful degradation in mind. If an interface is rendered with an illegal type, it should degrade to the default interface for that type (given we might've missed some cases there, but that's the intended behavior).

**Comment by rowild** [comment] 2022-06-30 15:20
No, but I wanted to mention it as a potential pitfall. (Even though I know, that I messed up and acted against the workings of Directus.)
But still "dirt" remains in that json, when an extension is uninstalled. The idea of overwriting that table content on startup is a no-go?

**Comment by rijkvanzanten** [comment] 2022-06-30 15:33
> But still "dirt" remains in that json, when an extension is uninstalled. The idea of overwriting that table content on startup is a no-go?

I think so, as there's also no way for the API to know whether or not the missing dependency is on purpose 🤔 Lets say you accidentally update the path to `./extensions` because you're deploying to a new infra, and all of a sudden Directus will destructively update all the configuration. That'd be a big disaster 🤔

**Comment by rijkvanzanten** [comment] 2022-06-30 15:34
The only real way I could imagine this to be possible is to make a "clean" command in the CLI that will cross reference used extensions vs available extensions (and maybe clean up other similar dirt) 🤔

**Comment by rowild** [comment] 2022-06-30 18:25
@rijkvanzanten Thanks for explaining! I definitely have some learning to do :-)

**Comment by rowild** [comment] 2022-06-30 18:40
May I bother you once more, please? I am very confused now, though... Why is there an extension folder anyway? Eventually, ext will be installed via npm, so that extension folder is actually not needed. Is it "just a convenience" for local development? After all, npm allows installation from github repos and local folders directly, too.

But I am sure I am missing out on sth here - but what?
If I change the path to `./extensions` wouldn't I want Directus to automatically update any and all configuration? Get rid of not installed ext, detect new ones?

The "clean" function that you mention would only have to run once an ext gets uninstalled. Therefore I think the performance is only a secondary concern ... ?

But I read that in a couple of months you'll concentrate on the ext dev aspect of Directus, so maybe it will make "click" in my head then...

**Comment by rijkvanzanten** [comment] 2022-06-30 20:23
> Why is there an extension folder anyway?

The extensions folder used to be the only way to inject extensions. NPM modules came later. That being said, not every installation necessarily relies on NPM in the first place, so we can't assume that exists. It's also partially what you mentioned:

> Is it "just a convenience" for local development? 

For simple hooks / endpoints, it's often easier to "plop" in a JS file locally, rather than having to push something to NPM or figure out another workaround to get the code in through node_modules (like the git or `file://` strategy).

> If I change the path to ./extensions wouldn't I want Directus to automatically update any and all configuration? Get rid of not installed ext, detect new ones?

You might, but I'm not comfortable in saying that is the case for 80%+ of uses. You might want to temporarily disable an extension because of a breaking bug that needs to be hot patched without losing all configuration you've done before for example.

> The "clean" function that you mention would only have to run once an ext gets uninstalled. Therefore I think the performance is only a secondary concern ... ?

It would only be ran when you explicitly change extensions and want the database to be altered to remove any trace from it ever existing. There isn't currently a hook point for when extensions are (un)installed, so this will be a manual command to run.

> But I read that in a couple of months you'll concentrate on the ext dev aspect of Directus, so maybe it will make "click" in my head then...

True and hopefully! The `npm` support for extensions also comes from the want of having the ability to install extensions "over the air" (meaning that the API can download and reload extensions in run-time), which in turn allows for a real in-app marketplace (#14063) that allows for installing / managing them in a no-code way. Once we get to that point, I would also assume that extensions have the ability to "install" and "uninstall" things to the database, which in turn could tap into the "clean" stuff we're discussing above 🙂

**Comment by rowild** [comment] 2022-06-30 21:48
@rijkvanzanten I truly appreciate your time explaining that all to me! Thank you very, very much!
