### ISSUE TITLE
Internal server error on opening M2A record with nested M2M relation without admin privileges

### ISSUE THREAD

**Issue by alwinzwets** [directus/directus#7191] opened 2021-08-04 16:16 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I have a collection named `presentations` with a multiple files (m2m) field. 
A second collection named `sessions` has a m2a field that links with presentations.

When editing these sessions in an Administrator role, all is working fine. If I create an editor role with full access to all collections I'm getting an INTERNAL_SERVER_ERROR if I try to open a presentation from the sessions collection. 

![image](https://user-images.githubusercontent.com/710737/128215025-905a04c8-b5b2-41c5-b9e0-bc584603040e.png)

This might be related to [#7086](https://github.com/directus/directus/issues/7086) but I'm not sure.

The crash seems to be related to [line 111 in services/authorization.ts](https://github.com/directus/directus/blob/6d29ebfd4682d4f384d15410d8c244439433e775/api/src/services/authorization.ts#L111) where `const permissions` remains `undefined`.

### To Reproduce

1. Create a collection A with multiple files field
2. Create a collection B with m2a field to collection in step 1.
3. Create records for both collections.
4. Create an editor role without Admin access
5. Login with editor role
6. Open a record of collection B and double click on the m2a record of collection A

[Attached is a postgres backup file to reproduce the issue.](https://github.com/directus/directus/files/6932696/directus_test.zip)

### What version of Directus are you using?

v9.0.0-rc.88

### What version of Node.js are you using?

v16.6.1

### What database are you using?

Postgres 13.3

### What browser are you using?

Vivaldi/4.1.2369.11 Chrome/92.0.4515.126

### What operating system are you using?

Windows 10

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2021-08-04 16:29
Based on the reproduction steps, and your note about the undefined permissions, I'm fairly sure this is a duplicate of #7086, which was resolved in https://github.com/directus/directus/pull/7168.

**Closed by rijkvanzanten** 2021-08-04 16:29 UTC
Labels: Bug (Potential)

**Comment by sensedrive** [comment] 2021-08-05 07:35
We are also still having this issue. I tried to get behind this issue, but for me it seems a bit too complex.

We try to retrieve data throught REST API `/items/collection/fields=*.*.*` and getting a 500

<img width="1304" alt="grafik" src="https://user-images.githubusercontent.com/8351587/128310391-94cd3fb7-fea3-4073-b5dc-fab8ae755f4f.png">

We are running v9.0.0-rc.88

**Comment by rijkvanzanten** [comment] 2021-08-05 13:25
@sensedrive https://github.com/directus/directus/issues/7086 is fixed and will be released in rc.89
