### ISSUE TITLE
Heroku + PostgreSQL issue

### ISSUE THREAD

**Issue by sylvaindeloux** [directus/directus#5049] opened 2021-04-14 07:43 UTC
Hi

I'm using Heroku, with a PostgreSQL add-on and I get "Can't connect to the database" error during release process (no issue during build).
All my env are in the `directus.config.js` file and I set the `CONFIG_PATH` to `/app/directus.config.js` on dyno settings.

My `package.json`:

```json
{
  "dependencies": {
    "directus": "^9.0.0-rc.53",
    "pg": "^8.6.0"
  }
}
```

My `directus.config.js`:

```
module.exports = {
    ...
    DB_CLIENT: "pg",
    ...
    DB_CONNECTION_STRING: process.env.DB_CONNECTION_STRING || process.env.DATABASE_URL,
    ...
};
```

Database DSN is added automatically in `DATABASE_URL` by Heroku.

Result (release log):

```
06:35:36 ✨ Initializing bootstrap...
06:36:01 🚨 Can't connect to the database
```

Does someone have an idea? Thanks :)

_Originally posted in https://github.com/directus/directus/discussions/5047 but I don't know where to post that kind of issue._

**Comment by WoLfulus** [comment] 2021-04-14 11:21
> Originally posted in #5047 but I don't know where to post that kind of issue.

I imagine this would be a better place: 
https://github.com/directus-community/heroku-template

Are you using the same exact setup? Does the database deployed correctly?

**Comment by workatease** [comment] 2021-04-14 12:23
> Hi
> 
> I'm using Heroku, with a PostgreSQL add-on and I get "Can't connect to the database" error during release process (no issue during build).
> All my env are in the `directus.config.js` file and I set the `CONFIG_PATH` to `/app/directus.config.js` on dyno settings.
> 
> My `package.json`:
> 
> ```json
> {
>   "dependencies": {
>     "directus": "^9.0.0-rc.53",
>     "pg": "^8.6.0"
>   }
> }
> ```
> 
> My `directus.config.js`:
> 
> ```
> module.exports = {
>     ...
>     DB_CLIENT: "pg",
>     ...
>     DB_CONNECTION_STRING: process.env.DB_CONNECTION_STRING || process.env.DATABASE_URL,
>     ...
> };
> ```
> 
> Database DSN is added automatically in `DATABASE_URL` by Heroku.
> 
> Result (release log):
> 
> ```
> 06:35:36 ✨ Initializing bootstrap...
> 06:36:01 🚨 Can't connect to the database
> ```
> 
> Does someone have an idea? Thanks :)
> 
> _Originally posted in https://github.com/directus/directus/discussions/5047 but I don't know where to post that kind of issue._

Enable verbose output in heroku to more details. Why it is not connecting set config value as
NPM_CONFIG_LOG=verbose

**Comment by sylvaindeloux** [comment] 2021-04-14 12:36
Added NPM_CONFIG_LOG=verbose env to Heroku config + `directus.config.js` file => same result, no error

**Comment by workatease** [comment] 2021-04-14 12:54
> Added NPM_CONFIG_LOG=verbose env to Heroku config + `directus.config.js` file => same result, no error

Sorry my mistake it's NPM_CONFIG_LOGLEVEL![Screenshot_20210414-085405.jpg](https://user-images.githubusercontent.com/57198612/114713372-0a664480-9cff-11eb-944b-09fd205a230a.jpg)

**Comment by sylvaindeloux** [comment] 2021-04-14 13:08
Same :/

**Comment by workatease** [comment] 2021-04-14 13:26
I use Heroku for directus with postgres I set all my values in heroku config vars. i don't use a separate config file and it work for me.

**Comment by workatease** [comment] 2021-04-14 14:21
I dont think this issue is related to directus its related to heroku configuration

**Comment by rijkvanzanten** [comment] 2021-04-14 14:48
Duplicate of https://github.com/directus/directus/issues/5049

No need to post things double @sylvaindeloux 👍🏻

**Closed by rijkvanzanten** 2021-04-14 14:48 UTC
