### ISSUE TITLE
Issues with using custom migrations, date sequence clashes with directus migrations

### ISSUE THREAD

**Issue by bposman** [directus/directus#23085] opened 2024-07-23 15:09 UTC
### Describe the Bug

Due to the considerable changes in directus 10.10.x we've been a bit delayed in upgrading.

We use custom migrations to add new collections and fields, and our file naming scheme is

`YYYYMMDD001-migration-name.js`

That works fine, but since we've created migrations with recent dates, such as this week, when I upgrade the directus package, it doesn't run the missing core migrations because they are older than my custom ones.

The culprit for this is all migrations are put in to one sorted list, and only those that are not complete AND are more recent than the last run migration are processed. 

https://github.com/directus/directus/blob/d0b1d52b9112828a384cc4699b4b3fd1a09d7e4f/api/src/database/migrations/run.ts#L70

Do we even need the date check here? I realize there may be some edge cases if you take out the check, but if it can't be taken out, the core/custom migrations should probably have different namespaces so they don't interfere with each other

### To Reproduce

Run directus v10.9.x
Add a custom migration with today's date as filename
`20240723001-migration-test.js`

run `directus bootstrap`

Upgrade to a newer directus version such as v10.13.1

run `directus database migrate:up` or `directus bootstrap`

No migrations are run, despite there being two migrations missing from the db.
ERROR: Nothing to upgrade

### Directus Version

v10.13.1

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2024-07-24 17:52
> Do we even need the date check here? I realize there may be some edge cases if you take out the check, but if it can't be taken out, the core/custom migrations should probably have different namespaces so they don't interfere with each other

The date check is required yes, as migrations can be reliant on previous migrations. For example if your custom migration relies on the datamodel of directus system tables in any way, it's critical that they're executed in the correct order.

In this particular case, in order to get through the upgrade correctly, I'd suggest backdating your migrations so they fit the execution order. 

I'll close this for now as the migrations system is operating as intended. Happy to take [a new feature requests](https://github.com/directus/directus/discussions/new?category=draft-feature-requests) if you or anybody reading this has a different take on how to create dependencies between migrations that will solve for this issue 🙂

**Closed by rijkvanzanten** 2024-07-24 17:52 UTC

**Comment by bposman** [comment] 2024-07-25 08:47
@rijkvanzanten 

The issue with backdating migrations, is they have already been applied to the database before I knew of this issue, so that means I have to change records in the directus_migrations table.

Surely in terms of ordering, the sorting of migrations by filename (meaning date) which happens earlier solves that.
