### ISSUE TITLE
Limit -1 doesn't work properly for nested collections (deep)

### ISSUE THREAD

**Issue by mpartipilo-fincons** [directus/directus#12588] opened 2022-04-05 16:15 UTC
### Describe the Bug

Query string param deep with [_limit] =-1  does not return all expected results

### To Reproduce

I have the following data model:

>  **MyCollection**
> >      - my_field (M2O)
> >              -nested_fields (M2M)
> >              -...
> >      - other_field
> >      -...
> 

If making a call to the items service I use the parameter deep with **limit=-1** I get a different result than the same call made using **limit=1000** (the actual results are 115).

ex. / items / myCollection? deep = {"my_field": {"nested_fields": {"_limit": -1}}}

total count of "nested_fields": 114

  / items / myCollection? deep = {"my_field": {"nested_fields": {"_limit": 1000}}}

total count of "nested_fields": 115

### What version of Directus are you using?

9.7

### What version of Node.js are you using?

16.0.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-04-05 16:31
Thanks for reporting this issue. It is a duplicate of #12382, and the good news is it has already been fixed by #12385 released in `v9.8.0`.

**Closed by azrikahar** 2022-04-05 16:31 UTC
Labels: Bug (Potential)
