### ISSUE TITLE
Can't update a M2O field

### ISSUE THREAD

**Issue by Eliophot** [directus/directus#7775] opened 2021-09-02 13:28 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Hello

Can't update a M2O field, I have an issue:

![KTDWIjU](https://user-images.githubusercontent.com/81296123/131851750-e86493ea-c820-4777-aebf-8dd8059e8c09.png)

Thanks

### To Reproduce

1. Click on M2O field to edit
2. save

### What version of Directus are you using?

rc91

### What version of Node.js are you using?

12.20.1

### What database are you using?

MySQL

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### How are you deploying Directus?

locally

**Comment by Silbad** [comment] 2021-09-02 20:21
Same pb for old project migrate rc69 to rc91
Recent project => OK

**Comment by rijkvanzanten** [comment] 2021-09-03 01:54
That error makes it look like the original M2O used a wrong field-field type 🤔 Does your originating "id_website" column have a different type / int length / collation or any other difference along those lines?

**Comment by Eliophot** [comment] 2021-09-03 12:34
Hello,
On collection websites, the ID is an INT
![image](https://user-images.githubusercontent.com/81296123/132000948-2e4f6073-90de-4ef7-9974-f264ffb32f60.png)
My M2O is an INT
![image](https://user-images.githubusercontent.com/81296123/132001106-89b0fa01-1c2b-4c0e-b926-a8962face247.png)
Maybe I did something wrong, but when you create an M2O, you don't have the possibility to change the type.

**Comment by rijkvanzanten** [comment] 2021-09-03 15:27
@Eliophot Was this a newly created m2o field, or a pre-existing? @Silbad seems to indicate that this might no longer be a problem when creating new fields?

**Comment by Silbad** [comment] 2021-09-03 16:55
So yes and no. Actually I answered too quickly. I had tested an M2O that worked. I also have cases that don't work. I have the impression that this is a problem with MySQL.

**Comment by rijkvanzanten** [comment] 2021-09-03 16:57
Do you have a specific field / type combination that fails every time? Trying to figure out how I can get this issue to show up on my side 🤔

**Comment by Silbad** [comment] 2021-09-03 17:01
Type Int
![image](https://user-images.githubusercontent.com/31576982/132042015-5e53bdaa-2c08-45f2-b744-651ce779972e.png)

**Comment by Silbad** [comment] 2021-09-03 17:16
Looks like some Ghost users have encountered the same problem: https://forum.ghost.org/t/unable-to-upgrade-ghost-from-v4-2-0-to-v4-3-0-cascade-unknown-code-please-report/22086

**Comment by rijkvanzanten** [comment] 2021-09-03 17:20
I'm assuming there might be a mysql specific configuration thing going haywire. Maybe your original column had a different collation than what directus creates by default on the connection?

**Comment by Silbad** [comment] 2021-09-03 17:26
Yes, I think it's something like that. I restored a backup of the database by doing an import. And probably with the wrong charset. 
I also found this : https://siliconheaven.info/upgrading-ghost-3-x-4-x/#gsc.tab=0
Ok I'll take a look

**Comment by Silbad** [comment] 2021-09-03 17:32
Non collation, but normal for a Int field ?
![image](https://user-images.githubusercontent.com/31576982/132045073-c94f3be5-f940-4bac-86fc-14d894b9025d.png)

**Comment by Eliophot** [comment] 2021-09-17 09:18
A start?
![diff](https://user-images.githubusercontent.com/81296123/133758576-a2e20ba7-a411-4d35-8ba8-a1f06922fe93.png)

**Comment by ohbob** [comment] 2021-11-07 20:16
I have the same issue with the latest version, and newly created collections a,b relation with m2o. Tried this on osx, sqlite3 and windows MariaDB, same result. So it's not only MySQL related.

**Comment by Eliophot** [comment] 2021-11-08 11:55
Hello, I add **DB_CHARSET="utf8mb4"**, but always an issue.
In fact, before the update that adds the constraints, the box allowing NULLs could be checked. Now it can't be unchecked because I have the impression that the MYSQL test is done beforehand. The problem is that you can't change anything because of this.

**Comment by Oreilles** [comment] 2021-11-16 15:02
Seems like another issue: You cannot have `ON DELETE SET NULL` rule on your relation if you want the column to be `NOT NULL`.
You need to either change the `ON DELETE` trigger to `CASCADE` or `PREVENT SUPPRESSION`, or make the relational field nullable - then you should be able to update it.
Please try and tell us if you still face this issue.

**Comment by rijkvanzanten** [comment] 2021-12-01 01:10
I'll close this for now, as it's most likely that the OP was/is caused by a discrepancy in the character set / collation of the two tables. For other people finding this, make sure to configure the `DB_CHARSET` environment variable to match the character set of your database.

**Closed by rijkvanzanten** 2021-12-01 01:10 UTC
Labels: API, DB: MySQL, Needs More Info

**Comment by Eliophot** [comment] 2021-12-01 11:10
I update to 9.1.2 + add DB_CHARSET and... It's work ! Thanks @Oreilles & @rijkvanzanten
