### ISSUE TITLE
Preserving the current page when navigating to a specific item and going back

### ISSUE THREAD

**Issue by Oreilles** [directus/directus#3644] opened 2021-01-10 23:36 UTC
If you're on page `n` of any layout, go to the edit page of an item, then go back, the current page is lost and you're back to page 1.

This is not an expected behaviour, particularily considering that all the other filters are kept intact.

**Comment by benhaynes** [comment] 2021-01-11 12:53
Absolutely! I've marked this as a bug because this is very unexpected behavior (and annoying), although I know Rijk we'll see it as a enhancement. 😉

In addition, I think each layout should have an option to flash / highlight item you just navigated from.

**Comment by Oreilles** [comment] 2021-01-11 13:03
> In addition, I think each layout should have an option to flash / highlight item you just navigated from.

It sure would be great to have access to that information!

**Comment by rijkvanzanten** [comment] 2021-01-11 15:39
blah blah not a bug blah blah never existed blah blah is a new feature blah blah

all joking aside though, this should be stored in view_query and persisted to the DB, just like any other query setting (sort/search/etc)

**Closed** 2021-01-13 20:34 UTC
Labels: App, Bug
