### ISSUE TITLE
Cannot add tags from mobile

### ISSUE THREAD

**Issue by darioguarascio** [directus/directus#16642] opened 2022-11-28 06:34 UTC
### Describe the Bug

In a `tags` field, it is impossible to add tags when inserting data from a mobile phone due to the lack of CR button

### To Reproduce

- create a table with a `tags` field
- access Directus from a smartphone
- insert a new row
- try to add tags

### What version of Directus are you using?

latest

### What version of Node.js are you using?

docker-based

### What database are you using?

postgres-13

### What browser are you using?

Chrome

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-11-28 08:32
Make sure to hit Enter to add the tag(s) you wanted:

https://user-images.githubusercontent.com/42867097/204230070-bebce8b1-a262-4f0d-9c83-9638c4bab21a.mp4

Alternatively you can also use `comma` instead of Enter. Closing as I was not able to reproduce this on mobile.

**Closed by azrikahar** 2022-11-28 08:32 UTC

**Comment by darioguarascio** [comment] 2022-11-28 10:23
@azrikahar I am using [SwiftKey Keyboard](https://play.google.com/store/apps/details?id=com.touchtype.swiftkey&gl=us) in Android and there is no Enter button on this one, only a tab-like, which sends me to the next field

**Comment by darioguarascio** [comment] 2022-11-29 10:41
https://user-images.githubusercontent.com/3661363/204507960-51e5c59e-0066-4180-8ffa-b25aae52e774.mp4

My guess is that it works on your end because you only have 1 element (tags) and not a subsequent one. In my case there is a textarea after the tags and perhaps the tabindex could interfere with the Enter button.

Just a guess

**Comment by azrikahar** [comment] 2022-11-29 11:19
Thanks for the screen capture! It's really bizarre how comma also doesn't work in your case, especially since the code to detect either Enter or comma was already present since the alpha version:

https://github.com/directus/directus/blob/d6b8e5963d955769cfe2a721014ca17191d8850c/app/src/interfaces/tags/tags.vue#L164

The tabindex + multiple element sounds very possible to be the issue as that seems to be the case on your phone, but unfortunately I was not able to reproduce this on my end (as it doesn't turn into "tab/focus to another input" for me):

https://user-images.githubusercontent.com/42867097/204514026-63dfeea2-1695-4c4b-aeb4-a653b69af5d3.mp4

so I'm also not sure what else could be the factor here 🤔 maybe SwiftKey versions as I was not able to find related settings to customize the Enter key behavior.

**Comment by darioguarascio** [comment] 2022-11-29 11:58
https://user-images.githubusercontent.com/3661363/204523111-ee01dd0d-e395-47ae-b776-0c621782ae0d.mp4

so..it looks like it is not the keyboard.

**Comment by azrikahar** [comment] 2022-11-30 11:10
Thanks for confirming. Unfortunately this seems to be a rather isolated issue, so I'm not sure what could be overriding the enter key behavior in your phone. Perhaps you can try another browser as an additional test? I was able to find the `enterkeyhint` attribute: https://css-tricks.com/enterkeyhint/, where `enterkeyhint="next"` feels like your current behavior, but currently the App does not use this attribute at all, so maybe it could be a system/browser wide override on your phone?

That being said, I do think there's value in having some form of tangible "add" button that can be clicked in terms of UX in general, and now possibly serve as a good fallback for cases such as yours, so do feel free to open a feature request in discussion so that we can gauge the community interest. 👍
