### ISSUE TITLE
ERRNO 1 : SQLITE error when trying to crop or edit an image.

### ISSUE THREAD

**Issue by haydenzeller** [directus/directus#22634] opened 2024-06-02 11:50 UTC
### Describe the Bug

receiving [INTERNAL_SERVER_ERROR] { "errno": 1, "code": "SQLITE_ERROR" } when trying to edit or crop photos

### To Reproduce

docker-compose deployment
upload image to file library
edit, crop, attempt to apply changes

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Sqlite

**Comment by br41nslug** [comment] 2024-06-03 09:08
I am unable to reproduce this issue by simply uploading and cropping an image, please provide enough information so we can reproduce it on our side 😄 
Closing this issue for now but happy to re-open if more info becomes available

**Closed by br41nslug** 2024-06-03 09:08 UTC
Labels: :detective: Needs More Info
