### ISSUE TITLE
App export issues - relational | filters | missing fields | etc

### ISSUE THREAD

**Issue by w0kyj** [directus/directus#13775] opened 2022-06-07 22:08 UTC
### Describe the Bug

Several related issues when exporting data via the Admin App:
- Export order not matching
- Field/Column names inconsistent (image.title, but translations, instead of translations.title)
- Field/Columns not exported (e.g. image excluded, but image.title included)
- Export seems to ignore relational filters too:
    - Added a language filter for equals en-US, but still get all translations title values

### To Reproduce

Directus Community Cloud Demo:
- Articles Collection
    - Export Items -- All defaults
        - Export field order not the same as in the fields list

    <img width="410" alt="Screen Shot 2022-06-07 at 3 23 02 PM" src="https://user-images.githubusercontent.com/40695629/172488688-61477939-3c2f-4286-9483-25588eea7a90.png">

    [articles 20220607-212312.csv](https://github.com/directus/directus/files/8856762/articles.20220607-212312.csv)

- Articles Collection
    - Export Items -- Add relational fields (drag order as needed)
        - specifically added fields for translations.title leaving original translations field
            - Original translations export with id values no longer in the export
            - Same happens with other relational fields

    <img width="414" alt="Screen Shot 2022-06-07 at 3 50 33 PM" src="https://user-images.githubusercontent.com/40695629/172488980-2901e1f0-e84b-4392-99a1-62c20c9a18a5.png">

    [articles 20220607-215054.csv](https://github.com/directus/directus/files/8856794/articles.20220607-215054.csv)

- Articles Collection
    - Export Items -- 
        - Added a relational filter for language code
            - Top level articles records filtered correctly
            - Related exports do not respect the filter - eg was only expecting the en-US translations in the export

    <img width="413" alt="Screen Shot 2022-06-07 at 3 59 42 PM" src="https://user-images.githubusercontent.com/40695629/172490225-460deb40-4f00-4e9f-b274-2ffebd62afff.png">

    [articles 20220607-215914.csv](https://github.com/directus/directus/files/8856833/articles.20220607-215914.csv)

### Errors Shown

N/A

### What version of Directus are you using?

9.11.1

### What version of Node.js are you using?

Community Cloud

### What database are you using?

SQLite

### What browser are you using?

Chrome

### How are you deploying Directus?

Community Cloud

**Comment by azrikahar** [comment] 2022-06-08 12:22
> - Export seems to ignore relational filters too:
>   - Added a language filter for equals en-US, but still get all translations title values

I believe it's not ignoring, but _technically_ working as intended. 

To achieve the desired outcome, we'll need to use `deep` (but understandably the app doesn't currently provide this input/config) 🤔 Here's a more elaborate answer regarding this scenario: https://github.com/directus/directus/discussions/13459#discussioncomment-2806776

**Comment by rijkvanzanten** [comment] 2022-12-15 22:38
Linear: [ENG-248](https://linear.app/directus/issue/ENG-248/app-export-issues-relational-or-filters-or-missing-fields-or-etc)

**Comment by ConnorSimply** [comment] 2023-06-05 22:58
The API and Export Service are _technically_ working as intended, as the Export Items drawer uses the REST API Export Query Parameter. The data from the API is authoritative and structurally must match the exports. You can not have duplicate keys/fields or rely on order with the API due to it being JSON and the nature of the API. I am closing this issue out in favor of making a new issue to revisit the UX of the export drawer to match what is actually happening in the API.

**Closed by ConnorSimply** 2023-06-05 22:58 UTC
Labels: Package: @directus/app, Bug
