### ISSUE TITLE
M2O Tables selectable for searching

### ISSUE THREAD

**Issue by KillerX** [directus/directus#14306] opened 2022-07-07 07:13 UTC
### Describe the Bug

When using filters to search the O2M fields can be selected as the left side of the filter:

![image](https://user-images.githubusercontent.com/398737/177713001-b99249e2-cfe3-47b2-be25-9d0df1762c73.png)

![image](https://user-images.githubusercontent.com/398737/177713286-1c291acc-3af3-4f77-946f-601808e57b11.png)

This causes requests like this to be generated: `http://localhost:8055/items/episodes?limit=25&filter={"_and":[{"_and":[{"translations":{"_contains":"X"}}]},{"status":{"_neq":"archived"}}]}&fields[]=status&fields[]=translations&sort=id&aggregate={"count":["*"]}`

Which in turn produce SQL like:

```sql
select count(*) as "count" from "episodes" where (("episodes"."id" in (select "episodes_translations"."episodes_id" as "episodes_id" from "episodes_translations" where "episodes_translations"."episodes_id" is not null and "episodes_translations"."_contains" like $1)) and not "episodes"."status" = $2) limit $3
```

As you can see there is a ` "episodes_translations"."_contains" like $1` that doesn't make sense.

Expected:

Either prevent M2O fields from being selected in the menu and open the next level like so (this works when using the arrow):
![image](https://user-images.githubusercontent.com/398737/177713608-2f2cc601-947c-4980-888f-82f220c5a7d5.png)

Or generate a query that applies the condition to all fields (likely overkill).

### To Reproduce

Use UI to construct the filter on a M2O field

### Errors Shown

```json
{"errors":[{"message":"select count(*) as \"count\" from \"episodes\" where ((\"episodes\".\"id\" in (select \"episodes_translations\".\"episodes_id\" as \"episodes_id\" from \"episodes_translations\" where \"episodes_translations\".\"episodes_id\" is not null and \"episodes_translations\".\"_contains\" like $1)) and not \"episodes\".\"status\" = $2) limit $3 - column episodes_translations._contains does not exist","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

### What version of Directus are you using?

9.13.0

### What version of Node.js are you using?

v16.15.1

### What database are you using?

Postgres 13

### What browser are you using?

Firefox

### How are you deploying Directus?

Local testing, Docker

**Comment by rijkvanzanten** [comment] 2022-07-07 08:35
Duplicate of https://github.com/directus/directus/issues/13690

**Closed by rijkvanzanten** 2022-07-07 08:35 UTC
