### ISSUE TITLE
Wrong count in drawer of M2M

### ISSUE THREAD

**Issue by 1cgonza** [directus/directus#17028] opened 2023-01-05 18:51 UTC
### Describe the Bug

I have a collection called `obras` with several M2M fields. If I want to add an existing item, the drawer has the wrong count of items which creates the following issues:

- Searching does not yield any results, it just shows the entire table again.
- In pagination, when I select a page beyond of what it should be, it goes back to 1. I can't reach the last page either.

This is only happening when editing an existing item. The count is correct when I want to create a new entry in `obras`. So it an inconsistent behavior. 

To give an example, one of the fields in `obras` relates to `autores` which has a total of 1,147 items, but the drawer shows 9,325. I've checked the junction table `obras_autores` trying to figure out the origin of the **9,325** count, but this table has 24,999 entries which is correct. 

This is how the M2M field is created:

![relation](https://user-images.githubusercontent.com/4657617/210855007-f2abaf17-1176-46f6-8538-9a9f47a219c1.png)

In the collection, the count is correct:

![count-autores](https://user-images.githubusercontent.com/4657617/210855258-a4020712-c093-4a4a-8b22-2635e369d2c8.png)

But in the drawer, when I want to add an existing item, the count is wrong:

![bug](https://user-images.githubusercontent.com/4657617/210855400-dfa9603a-b0fc-44c7-8d57-8b3b295e98ee.png)

This is happening with all the M2M fields in "obras".

En extra note in case it helps, I've created all the entries in `obras` with the SDK and not manually. 

### To Reproduce

Since it is only happening on existing entries and not on the creation of new ones, entries need to be created first:

1. Create 2 collections.
2. Add items to collection B.
3. Create a M2m field in collection A.
4. Create an entry in collection A.
5. Edit entry in collection A and try to add an existing item to the M2M field.

### Errors Shown

No errors shown.

### What version of Directus are you using?

9.22.1

### What version of Node.js are you using?

18

### What database are you using?

Postgres 13

### What browser are you using?

Chrome, Firefox

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2023-01-06 11:37
> - Searching does not yield any results, it just shows the entire table again.
- In pagination, when I select a page beyond of what it should be, it goes back to 1. I can't reach the last page either.

Unfortunately I was not able to reproduce either of these issues on my end. Here's a screen capture of what I've tried:

https://user-images.githubusercontent.com/42867097/211004641-3d7224c9-21df-4abd-aa38-fe18bf6584b1.mp4

(tested on Postgres)

Are there any steps that might be missing in the reproduction steps? Closing this for now until further info arises.

> This is happening with all the M2M fields in "obras".

Is this only happening in this specific collection, and not any other collections? Were you able to reproduce this with another collection(s), such as the Collection A and Collection B scenario in the reproduction steps?

> En extra note in case it helps, I've created all the entries in `obras` with the SDK and not manually.

Can you share an example of how are you performing this action, such as the payload and/or any code snippets?

**Comment by 1cgonza** [comment] 2023-01-07 03:31
Hi @azrikahar, thanks for checking this. I was not very clear in the last step to reproduce, sorry. The problem happens after I create the entry and got back to edit it afterwards. When I first create it, the count is fine, it only happens when I exit, come back to it and try to add a new element to the m2m field. 

Here a screen recording so you can see. You will notice how slow it is to save, or do anything really, I have other projects with Directus and no issues at all, I actually love using it. This project in particular is larger than the others, the collection you see here has 24,999 entries at the moment, it has 9 M2M fields, 17 M2O, and 8 regular fields. I am running this locally on a descent machine, yet it keeps hanging up. It might not be related to the problem, but the wrong count seems to be part of the problem I am having and really appreciate any help.

https://user-images.githubusercontent.com/4657617/211129313-5a082790-ae54-47f9-9125-25cf0c073efb.mp4

**Comment by 1cgonza** [comment] 2023-01-07 03:57
FYI, yesterday when I posted this the wrong count was on 9,325 as you can see from the picture. I did not add anything to the database, but today, when I recorded the previous video, the count is 25,000.

**Comment by azrikahar** [comment] 2023-01-09 10:04
> You will notice how slow it is to save,

This does looks odd, but it can be difficult to tell whether this is caused by other factors such as db connection/latency, or if it's Directus itself, especially if this is no reproducible in a new Directus instance.

> I have other projects with Directus and no issues at all, I actually love using it. 

Glad to hear!

> FYI, yesterday when I posted this the wrong count was on 9,325 as you can see from the picture. I did not add anything to the database, but today, when I recorded the previous video, the count is 25,000 when it should be 1,147.

Thanks for the detail. Just to confirm, could it be when you posted, "Obras" had 9325 records?

The count showing 25,000 instead of 1147 leads me to believe that it is _wrongly_ showing the count of "Obras" instead of "Autores".

If that is the case, I believe the issue is actually the same as #16883 because both cases rely on the `use-items` composable under the hood 👍

**Comment by 1cgonza** [comment] 2023-01-09 10:41
@azrikahar I understand you closed the issue because it is not reproducible, I really appreciate your help. If you have any pointers so I can keep digging on my own, that would be wonderful.

**Comment by azrikahar** [comment] 2023-01-09 12:03
> I did more tests and the speed issue had to do with the fact that I added the column "obras" to all my other collections so I could see the count and quick access (this feature was potentially very useful for the project).

Thanks for investigating, that does make sense. If you have any suggestions to improve the performance, feel free to open a separate discussion for it 👍

> If you have any pointers so I can keep digging on my own, that would be wonderful.

Changing the log level to `trace` was going to be my go-to suggestion, but I'm glad you have taken that step preemptively. Really appreciate it!

> It is very puzzling, I noticed that the wrong count depends on the current value of the field:
If the field "autores" is null, the count is 25,000, then it just changes values every time the field is populated. So the difference between 9,325 and 25,000 was just because I was looking at different records at the time. 

This is indeed the most important detail here to reproduce the issue! I'm now able to reproduce it with a minimal setup (3 records only) as seen here:

https://user-images.githubusercontent.com/42867097/211302830-6d7aa438-f884-4959-b809-c5a4625e8048.mp4

Reproduction steps:

1. Create collection `a` with a `name` string field
2. Create collection `b` with a `name` string field
3. Add a M2M field from collection `a` to `b`
4. Add 3 records to collection `a`, namely `A1`, `A2`, and `A3`
5. Add 3 records to collection `b`, namely `B1`, `B2`, and `B3`
6. Go to A1, click Add Existing on the M2M field. You should see the count shows 3 items. Select two existing `b` records and save
7. Go to A2, click Add Existing on the M2M field. You should see the count shows 3 items. Select one existing `b` records and save
7. Go to A3, click Add Existing on the M2M field. You should see the count shows 3 items, but now it is showing 4 items instead.

Additional note: This is reproducible on main https://github.com/directus/directus/commit/bcbbd81257b055aa086b790dbe087bab3d98360d.

**Comment by 1cgonza** [comment] 2023-01-09 16:24
> This is indeed the most important detail here to reproduce the issue! I'm now able to reproduce it with a minimal setup (3 records only) as seen here:

I see, thanks for taking the time! I'll keep track on the progress so I can update once this gets resolved. If I can help in any way, I am happy to do so. Have not made any PR for you guys but now that I am using Directus on a regular basis I feel invested on helping.

> Thanks for investigating, that does make sense. If you have any suggestions to improve the performance, feel free to open a separate discussion for it +1

Will do :+1:

**Comment by azrikahar** [comment] 2023-01-16 05:31
Note: The fix for this issue should also be checked against #17148.

**Closed** 2023-01-17 08:18 UTC
Labels: API, Bug
