### ISSUE TITLE
Incorrect total count when choosing existing item using a M2M field on a saved item.

### ISSUE THREAD

**Issue by boncossoftware** [directus/directus#17594] opened 2023-02-22 13:49 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

When selecting "choose existing" on a M2M field inside an existing saved item the count displayed in the related item's selection table is incorrect (in the thousands). 

![Screen Shot 2023-02-22 at 09 28 24](https://user-images.githubusercontent.com/5249176/220637687-cb57b436-f4f0-4e6d-9525-b6f925617556.png)

### To Reproduce

In my case I have a surgery vitals object that contains an M2M caregivers (actor object with type caregiver) relationship field. When I select the actor on a newly created item, that is not saved yet, it displays the correct count. Afterwards when navigating back to the created item and trying to add another existing item, the count at the top and the amount of pages displayed at the bottom is incorrect. The list does displays the correct amount of items though. In my case I have 90 items in total and it displays a count of 26662. 

It seems to me that this query is where the issue lies:
/items/actors?filter[_and][0][_and][0][types][_contains]=caregiver&filter[_and][0][_and][1][status][_eq]=published&filter[_and][1][$FOLLOW(surgery_vitals_caregivers,actors_id)][_none][surgery_vitals_id][_eq]=14495&aggregate[count]=*

### Hosting Strategy

Self-Hosted (Custom)

**Comment by licitdev** [comment] 2023-02-22 16:54
Duplicate of #17028

**Closed by licitdev** 2023-02-22 16:54 UTC
