### ISSUE TITLE
Modal bug while creating folder for models

### ISSUE THREAD

**Issue by iksent** [directus/directus#11545] opened 2022-02-09 15:48 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### To Reproduce

1. Try to create folder for models
2. Then click on Translations creation:
3. You'll see a new modal **behind** the opened popup, but it must be **above**

![image](https://user-images.githubusercontent.com/32956521/153237264-bc223c9d-ac9f-4c2f-9c46-64767dec9cc1.png)

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

14.17.5

### What database are you using?

MariaDB

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally (production)

**Comment by rijkvanzanten** [comment] 2022-02-09 15:53
Duplicate of https://github.com/directus/directus/issues/10892

**Closed by rijkvanzanten** 2022-02-09 15:53 UTC
Labels: Bug (Potential)
