### ISSUE TITLE
Directus Admin-App is logging out, when doing a hard refresh

### ISSUE THREAD

**Issue by sensedrive** [directus/directus#22696] opened 2024-06-07 09:18 UTC
### Describe the Bug

After login in into Directus Admin App and doing a hard refresh I am being directly logged out.

Since Version Update 10.11.1, still not working.

Maybe related: https://github.com/directus/directus/issues/22584

I get

```
[1] [0] [11:13:58.260] ERROR: select "s"."expires" as "session_expires", "s"."next_token" as "session_next_token", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ("u"."role", "d"."role") where "s"."token" = $1 and "s"."expires" >= $2 and ("d"."date_end" is null or "d"."date_end" >= $3) and ("d"."date_start" is null or "d"."date_start" <= $4) limit $5 - column s.next_token does not exist
[1] [0]     err: {
[1] [0]       "type": "DatabaseError",
[1] [0]       "message": "select \"s\".\"expires\" as \"session_expires\", \"s\".\"next_token\" as \"session_next_token\", \"u\".\"id\" as \"user_id\", \"u\".\"first_name\" as \"user_first_name\", \"u\".\"last_name\" as \"user_last_name\", \"u\".\"email\" as \"user_email\", \"u\".\"password\" as \"user_password\", \"u\".\"status\" as \"user_status\", \"u\".\"provider\" as \"user_provider\", \"u\".\"external_identifier\" as \"user_external_identifier\", \"u\".\"auth_data\" as \"user_auth_data\", \"r\".\"id\" as \"role_id\", \"r\".\"admin_access\" as \"role_admin_access\", \"r\".\"app_access\" as \"role_app_access\", \"d\".\"id\" as \"share_id\", \"d\".\"item\" as \"share_item\", \"d\".\"role\" as \"share_role\", \"d\".\"collection\" as \"share_collection\", \"d\".\"date_start\" as \"share_start\", \"d\".\"date_end\" as \"share_end\", \"d\".\"times_used\" as \"share_times_used\", \"d\".\"max_uses\" as \"share_max_uses\" from \"directus_sessions\" as \"s\" left join \"directus_users\" as \"u\" on \"s\".\"user\" = \"u\".\"id\" left join \"directus_shares\" as \"d\" on \"s\".\"share\" = \"d\".\"id\" left join \"directus_roles\" as \"r\" on \"r\".\"id\" in (\"u\".\"role\", \"d\".\"role\") where \"s\".\"token\" = $1 and \"s\".\"expires\" >= $2 and (\"d\".\"date_end\" is null or \"d\".\"date_end\" >= $3) and (\"d\".\"date_start\" is null or \"d\".\"date_start\" <= $4) limit $5 - column s.next_token does not exist",
[1] [0]       "stack":
[1] [0]           error: select "s"."expires" as "session_expires", "s"."next_token" as "session_next_token", "u"."id" as "user_id", "u"."first_name" as "user_first_name", "u"."last_name" as "user_last_name", "u"."email" as "user_email", "u"."password" as "user_password", "u"."status" as "user_status", "u"."provider" as "user_provider", "u"."external_identifier" as "user_external_identifier", "u"."auth_data" as "user_auth_data", "r"."id" as "role_id", "r"."admin_access" as "role_admin_access", "r"."app_access" as "role_app_access", "d"."id" as "share_id", "d"."item" as "share_item", "d"."role" as "share_role", "d"."collection" as "share_collection", "d"."date_start" as "share_start", "d"."date_end" as "share_end", "d"."times_used" as "share_times_used", "d"."max_uses" as "share_max_uses" from "directus_sessions" as "s" left join "directus_users" as "u" on "s"."user" = "u"."id" left join "directus_shares" as "d" on "s"."share" = "d"."id" left join "directus_roles" as "r" on "r"."id" in ("u"."role", "d"."role") where "s"."token" = $1 and "s"."expires" >= $2 and ("d"."date_end" is null or "d"."date_end" >= $3) and ("d"."date_start" is null or "d"."date_start" <= $4) limit $5 - column s.next_token does not exist
[1] [0]               at Parser.parseErrorMessage (/Users/martin/PhpstormProjects/leicht+luftig/lndw-halle/node_modules/pg-protocol/dist/parser.js:283:98)
[1] [0]               at Parser.handlePacket (/Users/martin/PhpstormProjects/leicht+luftig/lndw-halle/node_modules/pg-protocol/dist/parser.js:122:29)
[1] [0]               at Parser.parse (/Users/martin/PhpstormProjects/leicht+luftig/lndw-halle/node_modules/pg-protocol/dist/parser.js:35:38)
[1] [0]               at Socket.<anonymous> (/Users/martin/PhpstormProjects/leicht+luftig/lndw-halle/node_modules/pg-protocol/dist/index.js:11:42)
[1] [0]               at Socket.emit (node:events:517:28)
[1] [0]               at addChunk (node:internal/streams/readable:368:12)
[1] [0]               at readableAddChunk (node:internal/streams/readable:341:9)
[1] [0]               at Readable.push (node:internal/streams/readable:278:10)
[1] [0]               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[1] [0]       "length": 110,
[1] [0]       "name": "error",
[1] [0]       "severity": "ERROR",
[1] [0]       "code": "42703",
[1] [0]       "position": "44",
[1] [0]       "file": "parse_relation.c",
[1] [0]       "line": "3722",
[1] [0]       "routine": "errorMissingColumn"
[1] [0]     }

```

### To Reproduce

* Login into Directus, do a hard Refresh
* Do a hard refresh

### Directus Version

v10.12.0

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

postgres

**Comment by br41nslug** [comment] 2024-06-07 10:40
> column user_sessions.next_token does not exist

Looks like you're missing the newly added column on the sessions table, have you run all the migrations?

Closing this issue for now as not reproducable but happy to re-open if more info becomes available

**Closed by br41nslug** 2024-06-07 10:40 UTC
Labels: :detective: Needs More Info
