### ISSUE TITLE
Not able to delete a user who have uploaded files.

### ISSUE THREAD

**Issue by JonathanDoelan** [directus/directus#17558] opened 2023-02-16 15:42 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I am not able to delete a user. Even if I am logged in as Admin. I have figured out that it has something to do with files the user have uploaded — as you can verify in the error output below. Maybe problems with cascading?

This is the error output:
```js
{
  "errors": [
    {
      "message": "delete from `directus_users` where `id` in ('9093ecbe-85dd-4665-a953-70559e37970d') - ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`XXXX`.`directus_files`, CONSTRAINT `directus_files_modified_by_foreign` FOREIGN KEY (`modified_by`) REFERENCES `directus_users` (`id`))",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

### To Reproduce

Simply create a user called `Mr. Delete` with e-mail and password. Login as `Mr. Delete` and upload a file. Logout and login again as your main admin user, then try to delete the user `Mr. Delete` — not working :(

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-02-16 15:45
Thanks for opening this issue! However this is a duplicate of an existing issue #9507, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #9507 for future updates.

**Closed by paescuj** 2023-02-16 15:45 UTC
