### ISSUE TITLE
M2M field is refreshed when editing another field

### ISSUE THREAD

**Issue by abdonrd** [directus/directus#23942] opened 2024-10-30 02:52 UTC
### Describe the Bug

In a collection that has an M2M field, when you edit any other field, the M2M field is refreshed.

Note the flash on the M2M field and the network requests in this example:

https://github.com/user-attachments/assets/0e3bb548-861d-4055-bcf0-7cec10e35263

### To Reproduce

Create a collection with one M2M field and other fields.
Edit any of the other fields and you see how the M2M field refreshs.

### Directus Version

v11.1.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

PostgreSQL 16

**Comment by hanneskuettner** [comment] 2024-10-30 07:46
This is a duplicate of #23750. I will close this issue and continue to track the progress in the original issue.

**Closed by hanneskuettner** 2024-10-30 07:46 UTC
