### ISSUE TITLE
Data model "folder translation" drawer is covered by "Edit Folder" modal

### ISSUE THREAD

**Issue by loongmxbt** [directus/directus#11078] opened 2022-01-16 13:47 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

In Settings -> Data Model, after adding a folder, when try to create translations, translation drawer is under the current "Edit Folder" Modal, causing the translation hard to create.

![image](https://user-images.githubusercontent.com/5986600/149662633-2100360f-eaaa-431a-9381-d75b0bea6337.png)

https://www.dropbox.com/s/gh55kmlwzeak278/Data%20model%20folder%20translation%20bug.mp4?dl=0

### To Reproduce

In Settings -> Data Model, after adding a folder, when try to create translations, translation drawer is under the current "Edit Folder" Modal, causing the translation hard to create.

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.2

### What database are you using?

MySQL 5.7

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

locally

**Comment by joselcvarela** [comment] 2022-01-17 06:26
Also it seems that label is not translated:
![image](https://user-images.githubusercontent.com/14039341/149718284-445c461d-4986-49c0-af1a-613dd20e776b.png)

Just to make sure @benhaynes we should use the new translations interface here right?

**Comment by benhaynes** [comment] 2022-01-17 12:19
Hmm, if we can, yeah. Though I think the system repeater style is easiest for short strings. @rijkvanzanten ?

**Comment by rijkvanzanten** [comment] 2022-01-17 19:11
Yeah i'm a little torn on the UX for translating a single field 🤔

**Comment by rijkvanzanten** [comment] 2022-01-17 19:12
Also, duplicate of https://github.com/directus/directus/issues/10892

**Closed by rijkvanzanten** 2022-01-17 19:12 UTC
Labels: App, Bug
