### ISSUE TITLE
Wrong primaryKey & field values on custom interfaces after upgrading Directus

### ISSUE THREAD

**Issue by TarekTolba1** [directus/directus#22823] opened 2024-06-22 22:07 UTC
```ts
// Component API

export default {
  inject: ['values'], // <<<<<<<<<
  
  // elsewhere ...
  methods: {
    log() {
      console.log(this.values);
    }
  }
};

// Composition API
import { inject } from 'vue';
const values = inject('values');
```

_Originally posted by @rijkvanzanten in https://github.com/directus/directus/discussions/3583#discussioncomment-269657_

After upgrading to Directus 10.12.1, I encountered the issue that most of the time the interface start with a wrong `primaryKey` & injected `values` because they aren't populated yet when the interface is created.
Instead, they are populated with values a second or 2 after the setup/onMounted methods were executed. 
```
  setup(props, { emit }) {
    const values = inject("values");
    console.info(values.value); // empty object {}
    console.info(props.primaryKey); // "+"
    setTimeout(() => console.info(values.value), 2000); // populated object with values {"id":.....}
     setTimeout(() => console.info(values.value), 2000); // correct primaryKey "16"
```
Hence, you can't tell if the item is in the create state or is it created but still didn't load the data properly yet

Is it possible to fix this by providing the values earlier in the cycle?

**Comment by TarekTolba1** [comment] 2024-06-22 23:48
Solved.
To access the values in setup() you need to re-compute the value
``` // Inject the computed property
    const valuesRef = inject('values');
    const values = computed(() => valuesRef.value);`

**Comment by rijkvanzanten** [comment] 2024-06-24 16:19
The form renders before the item data is loaded, so the interfaces and other form elements only get the item data once the form is done loading. I'd recommend adding a watcher to the primary key or loading state and use that as a on-load alternative 👍🏻 

Happy to discuss alternatives to this setup in a new feature request. I'll close this for now as it's technically working as intended. Ty!

**Closed by rijkvanzanten** 2024-06-24 16:19 UTC
