### ISSUE TITLE
WARN: [OAuth2] Unknown RP error / outgoing request timed out after 3500ms

### ISSUE THREAD

**Issue by cdwmhcc** [directus/directus#20245] opened 2023-10-30 00:23 UTC
### Describe the Bug

``` bash
[08:19:51] GET /auth 200 16ms
[08:20:00] GET /auth/login/github?redirect=https%3A%2F%2Fapi.server.com%2Fadmin%2Flogin%3Fcontinue%3D 302 12ms
[08:20:04.334] WARN: [OAuth2] Unknown RP error
    err: {
      "type": "RPError",
      "message": "outgoing request timed out after 3500ms",
      "stack":
          RPError: outgoing request timed out after 3500ms
              at /apps/web/api/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/helpers/request.js:137:13
              at async Client.grant (/apps/web/api/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:1316:22)
              at async Client.oauthCallback (/apps/web/api/node_modules/.pnpm/openid-client@5.4.2/node_modules/openid-client/lib/client.js:603:24)
              at async OAuth2AuthDriver.getUserID (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.1_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/oauth2.js:91:24)
              at async AuthenticationService.login (file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.1_vue@3.3.4/node_modules/@directus/api/dist/services/authentication.js:43:22)
              at async file:///apps/web/api/node_modules/.pnpm/@directus+api@14.0.1_vue@3.3.4/node_modules/@directus/api/dist/auth/drivers/oauth2.js:252:28
      "name": "RPError"
    }
[08:20:04] GET /auth/login/github/callback?code=6072854f152d6a5be88f&state=ZGVtlnV0Uehc8q377XAUBWBxIzhXzc6swYL8Hy8GcXQ 302 3.5s
[08:20:04] GET /admin/login?reason=INVALID_CREDENTIALS 200 1ms
[08:20:04] GET /extensions/sources/index.js 200 9ms
[08:20:04] POST /auth/refresh 400 8ms
[08:20:04] GET /server/info 200 5ms
[08:20:04] GET /auth 200 4ms
```

### To Reproduce

``` env
PUBLIC_URL="https://api.server.com"

REFRESH_TOKEN_COOKIE_SECURE=true
REFRESH_TOKEN_COOKIE_SAME_SITE="None"

AUTH_PROVIDERS="github"
AUTH_GITHUB_DRIVER="oauth2"
AUTH_GITHUB_CLIENT_ID="xxxxx"
AUTH_GITHUB_CLIENT_SECRET="xxxxxx"
AUTH_GITHUB_AUTHORIZE_URL="https://github.com/login/oauth/authorize"
AUTH_GITHUB_ACCESS_URL="https://github.com/login/oauth/access_token"
AUTH_GITHUB_PROFILE_URL="https://api.github.com/user"
AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION=true
AUTH_GITHUB_DEFAULT_ROLE_ID="c57d51ba-339b-4097-a718-adb95864b7b8"
```

### Directus Version

10.7.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by azrikahar** [comment] 2023-10-30 08:40
Unfortunately I was unable to reproduce the same timeout error as seen here:

https://github.com/directus/directus/assets/42867097/3366072e-a248-41e8-b125-a16e1cb9b3a7

with the following environment variables:

```env
PUBLIC_URL="http://localhost:8080"

REFRESH_TOKEN_COOKIE_SECURE=true
REFRESH_TOKEN_COOKIE_SAME_SITE="None"

AUTH_PROVIDERS="github"
AUTH_GITHUB_DRIVER="oauth2"
AUTH_GITHUB_CLIENT_ID="xxx"
AUTH_GITHUB_CLIENT_SECRET="xxx"
AUTH_GITHUB_AUTHORIZE_URL="https://github.com/login/oauth/authorize"
AUTH_GITHUB_ACCESS_URL="https://github.com/login/oauth/access_token"
AUTH_GITHUB_PROFILE_URL="https://api.github.com/user"
AUTH_GITHUB_ALLOW_PUBLIC_REGISTRATION=true
AUTH_GITHUB_DEFAULT_ROLE_ID="<uuid>"
```

and the following oauth app config on GitHub:

![](https://github.com/directus/directus/assets/42867097/8cff1506-a992-43a9-afa0-c87ad5cac7c4)


Judging from the error `RPError: outgoing request timed out after 3500ms`, I think the issue here is your instance is somehow on a network that is unable to reach GitHub, as described by this other comment https://github.com/nextauthjs/next-auth/issues/3920#issuecomment-1037149713 (although this is a next-auth issue, it uses the same underlying `openid-client` package, hence the identical error). It would be helpful if you can retry it with a different internet connectivity such as mobile hotspot if there's no other alternatives readily available around you.

I'll close this issue for now since it's not reproducible at the moment and it is likely to be a network issue rather than a bug/error 👍

**Closed by azrikahar** 2023-10-30 08:40 UTC

**Comment by cdwmhcc** [comment] 2023-10-30 09:00
@azrikahar I think this should be a network issue. I just tested it locally and it works. Sorry to cause you any trouble.

**Comment by cdwmhcc** [comment] 2023-10-30 09:05
@azrikahar If it's convenient, can I ask you another question here?
I created a user without `email` and `password`, but with a unique field `credentials`. Is there any way to obtain the access_token of this user through the API without generating a static token for it?

**Comment by azrikahar** [comment] 2023-10-30 10:11
> If it's convenient, can I ask you another question here? I created a user without `email` and `password`, but with a unique field `credentials`. Is there any way to obtain the access_token of this user through the API without generating a static token for it?

I don't think there's a straightforward way since the default/local login provider still requires email/password. Static token would be the current recommended approach, unless there's a particular reason that may lead you to not prefer using it.

That being said, this does also reminds me of #9284, which should technically make it possible for you to implement what you're looking for (at least from my understanding). Maybe this can be an RFC by itself, but there might be some underlying technical overlap with #17888.
