### ISSUE TITLE
Invalid foreign key in field "group"

### ISSUE THREAD

**Issue by juicejs** [directus/directus#10971] opened 2022-01-11 11:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

The schema.yaml seams broken when there's a "folder" created in the data model that has sub collection.

The current solution is to not use folders when you rely on schema migrations. 

### To Reproduce

1. Create a "folder" item in the the data model
2. Add a new collection and add it as a subcollection
3. run "directus schema snapshot ./schema.yaml --format yaml"
4. Clear the database or use a new empty one
5. Run "npx directus bootstrap"
6. run "npx directus schema apply ./schema.yaml -y"

### Errors Shown

You will get this error:
🚨 Failed to create collection "Item"
🚨 Invalid foreign key in field "group". 
Error: Invalid foreign key in field "group".

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

v12.22.7

### What database are you using?

Tested on Postgres 13 and MySQL

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Deployment with Docker but the error can be reproduced locally and using the CLI

**Comment by Oreilles** [comment] 2022-01-11 13:23
Duplicate of https://github.com/directus/directus/issues/9723

**Closed by Oreilles** 2022-01-11 13:23 UTC
Labels: Bug (Potential)
