### ISSUE TITLE
Multiple Files upload and sort bug

### ISSUE THREAD

**Issue by martijn-dev** [directus/directus#7710] opened 2021-08-31 11:09 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

When I upload multiple files to a 'multiple files field' and I try to sort the files after, all files change to the first item in the list.
This only happens if I try to sort the files immediately after I upload them.
If I upload the files, save the item and try to sort, the issue doesn't occur.

See the video for an example:

https://user-images.githubusercontent.com/73393707/131465640-d69d9f54-2dbd-4138-b628-bfd91f6df2e0.mp4

### To Reproduce

- Create a multiple files field with an sort parameter.
- Upload multiple files to the field.
- Try to sort them.

### What version of Directus are you using?

v9.0.0-rc.91

### What version of Node.js are you using?

Postgres 13.3

### What database are you using?

v16.6.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### How are you deploying Directus?

running locally

**Comment by Nitwel** [comment] 2021-08-31 12:04
This is a duplicate of #3840 and will be fixed in rc.92.

**Closed by Nitwel** 2021-08-31 12:04 UTC
Labels: Duplicate
