### ISSUE TITLE
[FAILED_VALIDATION] "folder" must be of type object when assigning a custom validation for Files

### ISSUE THREAD

**Issue by MarcellusCodes** [directus/directus#13148] opened 2022-05-06 08:53 UTC
### Describe the Bug

I set a custom validation field for my users to only be able to add an image in a specific folder.
![image](https://user-images.githubusercontent.com/90842582/167098683-c08d12d6-559e-4b93-9a01-7997cb0d9b5d.png)

But when I try to add an image to that folder I get this error message:
![image](https://user-images.githubusercontent.com/90842582/167098951-a2bbea1f-f181-411f-9eaa-dd4c04155117.png)

### To Reproduce

1. Create a simple folder structure: Test -> Tester -> Testing.
2. Create a role for example: "Test" then go into roles & permissions assign files a custom validation Role with -> folders and then the corresponding name of that nested folder -> Testing
3. Create a new user assign that role, login with the newly created user and try to submit a file in the folder.

### Errors Shown

Just a Post 400 / files

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.7.0

### What database are you using?

SQLite3 5.05

### What browser are you using?

Chrome

### How are you deploying Directus?

running locally

**Comment by icrotz** [comment] 2022-05-06 10:06
Duplicate of https://github.com/directus/directus/issues/11775

**Closed** 2022-05-06 12:37 UTC
Labels: Duplicate
