### ISSUE TITLE
graphql alias return null on array

### ISSUE THREAD

**Issue by zippax** [directus/directus#10835] opened 2022-01-03 23:40 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

**using GraphQL without alias :**

`
   items{
        name
   }
`

**return :**

`
"items": [
          {
            "name": "Pepsi"
          }
       ]
`

**but if I use alias:**

`
   data: items{
        name
   }
`

**it return**  `data: null`

### To Reproduce

The result must be: <Array> not Null

`
"data": [
          {
            "name": "Pepsi"
          },
          ....
       ]
`

### Errors Shown

no error showing, only return wrong result

### What version of Directus are you using?

9.4.2

### What version of Node.js are you using?

v16.7.0

### What database are you using?

mysql

### What browser are you using?

firefox, chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

running locally

**Comment by rijkvanzanten** [comment] 2022-01-04 00:33
I believe this is a duplicate of https://github.com/directus/directus/issues/9390

**Closed by rijkvanzanten** 2022-01-04 00:33 UTC
Labels: Bug (Potential)
