### ISSUE TITLE
Deep filtering returns no results

### ISSUE THREAD

**Issue by gkielwasser** [directus/directus#9636] opened 2021-11-09 08:50 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

[Both deep filtering syntax](https://docs.directus.io/reference/query/#deep) doesn't work anymore in v9.0.0. An empty translations array is returned even if entries should match.

```
GET &deep[translations][_filter][languages_code][_eq]=fr-CH

Results:
data: { translations : [ ] }
```
and
```
GET &deep={ "translations": { "_filter":  { "languages_code": {"_eq": "fr-CH" }  } } }

Results:
data: { translations : [ ] }
```

### To Reproduce

Try to filter a collection that has the default relational translations applied.

### What version of Directus are you using?

9.0.0

### What version of Node.js are you using?

16.13.0

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

Windows_NT 10.0.19042

### How are you deploying Directus?

locally

**Comment by joselcvarela** [comment] 2021-11-09 08:57
Hello @gkielwasser 
It seems a duplicate of https://github.com/directus/directus/issues/9578
But you already have commented there, so why did you open this?
Is this different in any way from the other one?

**Comment by gkielwasser** [comment] 2021-11-09 09:08
> Hello @gkielwasser It seems a duplicate of #9578 But you already have commented there, so why did you open this? Is this different in any way from the other one?

Hello @joselcvarela,

I thought it would be related but talking with @kwiatkk1 it seems not.

My ticket describe a bug using one of the default 2 deep filtering syntax exposed in the [documentation](https://docs.directus.io/reference/query/#deep).

The other ticket, from what I have understood seems to describe a deep filtering using a syntax where "_filter" and "translations" field is swapped from what it should be according to the documentation. I'm still not so sure I have understood well, but I let the author clarify that again.

**Comment by Oreilles** [comment] 2021-11-10 12:41
Closing as it is indeed a duplicate of https://github.com/directus/directus/issues/9578

**Closed by Oreilles** 2021-11-10 12:41 UTC
Labels: Bug (Potential)
