### ISSUE TITLE
Crash on EXTENSIONS_AUTO_RELOAD

### ISSUE THREAD

**Issue by leonardomdr** [directus/directus#11095] opened 2022-01-17 11:18 UTC
### Preflight Checklist

- [x] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

**Bug**
- Directus is crashing every time the extension is reloaded.

**Important**
- It's a module extension and it works fine after restarting directus
- It only crashes directus when it tries to reload the extension 

**Extension file**
`import{resolveComponent as e,openBlock as o,createBlock as t,withCtx as r,createTextVNode as n}from"vue";var a={};const u=n("Content goes here...");a.render=function(n,a,d,i,l,s){const c=e("private-view");return o(),t(c,{title:"My Custom Module"},{default:r((()=>[u])),_:1})},a.__file="src/module.vue";var d={id:"leonardo",name:"leonardo",icon:"box",routes:[{path:"",component:a}]};export{d as default};`

**Extension location**
`/directus/extensions/modules/leonardo/index.js`

### To Reproduce

1. Install Directus
2. Set EXTENSIONS_AUTO_RELOAD config to true
2. Copy the extension code (use the sample above) to the module extension folder (also provided above)
3. Change `Content goes here...` to anything else, like `Content goes here... 2`
4. Directus will try to auto reload and crash

 

### Errors Shown

**Stack trace**
```
/directus/node_modules/rollup/dist/shared/rollup.js:158
        base = Object.assign(new Error(base.message), base);
                             ^

Error: 'default' is not exported by extensions/modules/leonardo/index.js, imported by virtual:entry
    at error (/directus/node_modules/rollup/dist/shared/rollup.js:158:30)
    at Module.error (/directus/node_modules/rollup/dist/shared/rollup.js:12423:16)
    at Module.traceVariable (/directus/node_modules/rollup/dist/shared/rollup.js:12808:29)
    at ModuleScope.findVariable (/directus/node_modules/rollup/dist/shared/rollup.js:11588:39)
    at Identifier.bind (/directus/node_modules/rollup/dist/shared/rollup.js:6468:40)
    at ArrayExpression.bind (/directus/node_modules/rollup/dist/shared/rollup.js:5072:31)
    at ExportDefaultDeclaration.bind (/directus/node_modules/rollup/dist/shared/rollup.js:5076:23)
    at Program.bind (/directus/node_modules/rollup/dist/shared/rollup.js:5072:31)
    at Module.bindReferences (/directus/node_modules/rollup/dist/shared/rollup.js:12419:18)
    at Graph.sortModules (/directus/node_modules/rollup/dist/shared/rollup.js:23035:20) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: '\x00virtual:entry',
  pos: 7,
  loc: { column: 7, file: '\x00virtual:entry', line: 1 },
  frame: "1: import e0 from './extensions/modules/leonardo/index.js';\n" +
    '          ^\n' +
    '2: export default [e0];',
  watchFiles: [
    '\x00virtual:entry',
    '/directus/extensions/modules/leonardo/index.js'
  ]
}
```

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.1

### What database are you using?

n.A.

### What browser are you using?

n.A.

### What operating system are you using?

debian

### How are you deploying Directus?

docker

**Comment by joselcvarela** [comment] 2022-01-17 14:09
Hey @leonardomdr 
Can you try with a fresh install?
I was able to run your reproduction steps without any issue:

https://user-images.githubusercontent.com/14039341/149783858-547221c2-7d1b-49cc-bbcc-ae3ac7e1ca21.mov

**Comment by leonardomdr** [comment] 2022-01-17 16:15
I **think** I got what happened.

I'm not developing it in a localhost environment. The problem seems to happen when I start to upload the file to the host. Directus is probably trying to parse the file while it is uploading and getting partial content or something like this.

I tried to enable "useTempFile" in my sftp plugin, but it didn't work as well, because the plugin uploads a ".new" file in the extensions folder and Directus triggers the reload as well.

In localhost I couldn't reproduce the error, exactly like your video.

Thank you, it's probably on my end.

**Comment by joselcvarela** [comment] 2022-01-17 16:29
No problem 👍
Closing since this seems to be an issue on OP end and not on Directus itself.

**Comment by nickrum** [comment] 2022-01-17 17:12
@leonardomdr Good catch! We could totally configure the file watcher to only watch `index.js` files. That way you could at least use the "useTempFile" of your sftp plugin and I think this would be a good idea in general.

Also, Directus shouldn't crash in case it encounters a malformed App extension.

**Comment by joselcvarela** [comment] 2022-01-17 17:22
@nickrum should we reopen this?

**Closed** 2022-01-17 18:14 UTC
Labels: API, Bug

**Comment by leonardomdr** [comment] 2022-01-17 22:12
How can I test this image now? Or should I wait for the next release?

**Comment by rijkvanzanten** [comment] 2022-01-17 22:38
It'll be launched in 9.5.0 which is scheduled for release this Thursday 👍🏻 Alternatively, you can run Directus from source using the instructions found here https://docs.directus.io/contributing/running-locally/
