### ISSUE TITLE
Nested query filters with functions don't work because of table aliases

### ISSUE THREAD

**Issue by nodeworks** [directus/directus#15990] opened 2022-10-13 17:23 UTC
### Describe the Bug

When doing a nested query with nested filters and a function the API throws an error saying it can't find the specified function. This is because the getColumn function is passed a table name that can be an alias. When trying to get the column information it's looking for the aliased table in the schema object. This doesn't exist.

### To Reproduce

Run a query with nested filters and a function like "year"

### What version of Directus are you using?

9.18.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

MSSQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by licitdev** [comment] 2022-10-13 18:01
Duplicate of https://github.com/directus/directus/issues/12725

**Closed by licitdev** 2022-10-13 18:01 UTC
Labels: Duplicate
