### ISSUE TITLE
Cannot save collections and fields after upgrading to rc100

### ISSUE THREAD

**Issue by adanielyan** [directus/directus#9259] opened 2021-10-30 18:18 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

After upgrading to rc100 my relationship fields configuration cannot be saved. I tried installing a clean instance with Postgres and had same issue. Also the relational fields look broken too. Sometimes only label is rendering, and sometimes a text box is rendered, but no create or select buttons.

I also cannot edit any items after they are created.

### To Reproduce

Create a relational field, in my case it was one to many.
Edit it, then go to Relationship.
The related collection and foreign key fields will be empty 
![image](https://user-images.githubusercontent.com/861777/139552335-f739513a-2b53-4793-9f8d-1bfd245064b3.png)
Make a change, e.g. type a foreign key name. The save button will remain disabled
![image](https://user-images.githubusercontent.com/861777/139553111-3add6a39-edb6-457e-9fef-6531112d2489.png)

### Errors Shown

None

### What version of Directus are you using?

rc100

### What version of Node.js are you using?

16.3.0

### What database are you using?

pg 10.5

### What browser are you using?

Edge

### What operating system are you using?

MacOS

### How are you deploying Directus?

locally

**Comment by Oreilles** [comment] 2021-10-30 19:44
Duplicate of #9182

**Closed by Oreilles** 2021-10-30 19:44 UTC
Labels: Bug (Potential)
