### ISSUE TITLE
Unable to delete items in one of my collections

### ISSUE THREAD

**Issue by Fbuona** [directus/directus#20923] opened 2023-12-29 16:21 UTC
### Describe the Bug

For a few days I'm unable to delete items in one of my collections. Either from Directus website and from my app directly.
The error that appears is  "INTERNAL_SERVER_ERROR" "$last.emailDelete" must be [true].
It worked perfectly and suddenly not anymore. 
All the others collection have no problem ! 

Did you already experience this problem ?

Thanks in advance for help.

### To Reproduce

I used Directus V10.8.0 and today I tried to update to V10.8.3 but with no amelioration.

### Directus Version

V10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-12-29 16:48
> The error that appears is "INTERNAL_SERVER_ERROR" "$last.emailDelete" must be [true].

`$last.emailDelete`, particularly `$last`, should be one of the key within the data chain of a particular flow to refer to the last operation. Reference to docs: https://docs.directus.io/app/flows.html#the-data-chain

This does mean it is most likely an error caused by a flow that you have in your setup. Can you try investigating and track down which flow is causing this? It is most probably a flow with event hooks, especially the `items.delete` or `<your_collection>.items.delete` hook, but flows can be fairly elaborate so feel free to check other flows as well if you don't have any event hooks trigger flows.

Closing this as not a bug for now with a cursory evaluation that this should be more of a misconfiguration of said flow, but we'll re-open if more information leads us to finding out it's an actual bug in Directus itself.

**Closed by azrikahar** 2023-12-29 16:48 UTC

**Comment by Fbuona** [comment] 2023-12-29 17:55
Thanks a lot for your quick answer, I'll check in this direction and let you know ;)
