### ISSUE TITLE
Cannot created nested items for Many To Many (m2m) relation field

### ISSUE THREAD

**Issue by amo42** [directus/directus#17555] opened 2023-02-16 14:08 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

Referring to this https://discord.com/channels/725371605378924594/1075396128557760572/1075396128557760572 it seems to be a bug while creating the items.

If you create a new item, which has a m2m-field that is filled with an also new item, the nested item is not created as expected.

This happens using the SDK as well as the REST api, regardless of the used method (Basic, Detailed)

### To Reproduce

1. Having 2 collection (A and B), 
2. with a title field each, 
3. and a M2M field within A
4. you should be able to create a new A-Item using this payload:
```
{
    "rel_a_title": "all new existing"
}
```
5. Which works as expected. 
6. But using the format:
```
{
    "rel_a_title": "all new",
    "b_item": {
        "create": [{ "b_title": "A new nested item" }]
    }
}
```
7. it returns a valid HTTP code, but does only return the junction item id, I would expect it has to return the ID of the "nested" B-item which is not created. To create a new B-Item directly within the single request, there is no new B-Item created, while the junction table is updated and even the Directus App shows "1 item" which is undefined:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/12328155/219384640-00840df1-f785-4900-a485-da5b643ea670.png">

<img width="662" alt="payload" src="https://user-images.githubusercontent.com/12328155/219386866-4a2126cc-a25c-466c-b9f3-f452930d4baa.png">

<img width="848" alt="Rel_a_Rel_B" src="https://user-images.githubusercontent.com/12328155/219387162-143543cd-d51a-498a-9aea-b3b08a7407c5.png">

Also if you add an existing one, the behavior is the same:
<img width="844" alt="Editing_Item_in_Rel_A" src="https://user-images.githubusercontent.com/12328155/219385182-14e72d6e-9c11-468c-bfb6-bebddb6ca1d8.png">

As shown, the B-item with id 2 was created manually within the app, but the UI still thinks there is another one. 

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-02-23 09:58
I believe this is a similar confusion as #16913 regarding creating nested items within relationships with junction table.

Can you try going through the answer here: https://github.com/directus/directus/discussions/16913#discussioncomment-4490519, and let us know whether does it help? 

In this particular instance for example, the format of data that you're sending (in step 6 of your To Reproduce section) should be either of the following instead:

- Basic

  ```json
  {
    "rel_a_title": "all new",
    "b_item": [
        {
          "rel_b_id": { 
            "b_title": "A new nested item"
          }
        }
    ]
  }
  ```

- Detailed

  ```json
  {
    "rel_a_title": "all new",
    "b_item": {
      "create": [
        {
          "rel_b_id": { 
            "b_title": "A new nested item"
          }
        }
      ]
    }
  }
  ```

Note that `rel_b_id` is a guesstimate from your screenshot of the junction table, so do change it if it's actually different in your setup 👍

I'll proceed to close this as a question for now, and we can reopen afterwards if it turns out to be an actual bug.

**Closed by azrikahar** 2023-02-23 09:58 UTC

**Comment by azrikahar** [comment] 2023-02-27 11:15
> is It my fault or is the official docu kind of misleading due to this payload:

Seeing that there has been several questions surrounding this topic, the docs can and should be improved, as mentioned in https://github.com/directus/directus/discussions/16913#discussioncomment-4501068 👍 I believe directus/docs#274 is meant to enhance this exact section/info.

The payload you have screenshotted is indeed an O2M payload (no junction table) hence it is technically correct, but definitely "misleading" in the sense that it can be mistaken to work as-is for M2M (with junction table). 

> From your payload you're setting the "ID" with the item that does not yet exist but gets kind of replaced while the nested item is created on the fly? Did I get this right?

I'm not sure I understood this question correctly, but assuming by "ID" you meant the one in the screenshot, hopefully the following updated example for O2M with comments from directus/docs#274 can elaborate on it better:

```js
{
	"children": {
		"create": [{ "name": "A new nested item" }], // creates & links item
		"update": [
			// links item 2 without updating it
			{ "id": 2 },
			// links and updates item 149
			{ "id": 149, "name": "An updated nested item" }
		],
		"delete": [7] // unlinks item 7
	}
}
```
