### ISSUE TITLE
Notice field has problems when put into a detail group

### ISSUE THREAD

**Issue by Kici33** [directus/directus#16273] opened 2022-11-02 11:24 UTC
### Describe the Bug

Reading properties of undefined, when putting notice field into group

### To Reproduce

1. Creation of Notice field
2. Creation of Detailed group
3. Dragging notice field into detailed group

### Errors Shown

After creating notice field, and dragging it into a detail group.
Error happens as follows:

![image](https://user-images.githubusercontent.com/31071107/199476582-ff9768ea-065d-4b7c-a3e8-19fd23a5162f.png)
 at FieldsService.updateField 307:73, where it reads type of undefined.

### What version of Directus are you using?

9.20.1

### What version of Node.js are you using?

v16.14.0

### What database are you using?

SQLite 3, not sure which exactly

### What browser are you using?

Opera

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-11-02 11:24
Thanks for opening this issue! However this is a duplicate of an existing issue #16269, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #16269 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2022-11-02 11:24 UTC
