### ISSUE TITLE
Accidentally entered a state with collections and fields that don't exist according to the API but still exist in the database

### ISSUE THREAD

**Issue by eternalflamez** [directus/directus#12565] opened 2022-04-04 15:39 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I removed fields of a collection through an API call, but then after adding the fields again, I got an error that the fields still exist. 

Then I tried removing the offending collection, which appeared to succeed but it's still blocking me from recreating the collection, even though it doesn't exist according to the collections get call.

### To Reproduce

Hard to say, this was in a translations table, with about 60 fields that I deleted simultaniously, maybe it didn't process all of those?

### Errors Shown

{
  "errors": [
    {
      "message": "Collection \"test_translations\" already exists.",
      "extensions": {
        "code": "INVALID_PAYLOAD"
      }
    }
  ]
}

### What version of Directus are you using?

9.7.1

### What version of Node.js are you using?

16.14.2

### What database are you using?

Default? How do I tell on standard cloud?

### What browser are you using?

Chrome and Postman for API calls

### What operating system are you using?

Linux 4.14.262-200.489.amzn2.x86_64

### How are you deploying Directus?

PaaS maybe? It's standard cloud

**Comment by azrikahar** [comment] 2022-04-05 07:12
Thanks for opening this issue! However this is a duplicate of an existing issue #12331, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #12331 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-05 07:12 UTC
Labels: Bug (Potential)
