### ISSUE TITLE
Komische Anzeige über Collections

### ISSUE THREAD

**Issue by TorbenHammes** [directus/directus#3297] opened 2020-12-03 23:05 UTC
Each of my collections has this text above the title. Is this a bug or have I set something wrong?
Have a nice weekend :-D

<img width="727" alt="Bildschirmfoto 2020-12-04 um 00 02 51" src="https://user-images.githubusercontent.com/12980389/101099013-3856b200-35c4-11eb-9496-44b98af0dba3.png">

---

### Project details
Directus Version: 9.0.0-rc.20
Environment: production
OS: Linux 5.4.0-1030
Node: 10.19.0

**Comment by rijkvanzanten** [comment] 2020-12-03 23:07
Duplicate of https://github.com/directus/directus/issues/3210

We have some last cleanup to do in the translations 😄 (https://github.com/directus/directus/issues/2962)

**Comment by TorbenHammes** [comment] 2020-12-03 23:08
Thanks and sorry for the inconvenience

**Closed by rijkvanzanten** 2020-12-03 23:07 UTC

**Comment by rijkvanzanten** [comment] 2020-12-03 23:10
No problem! When in doubt, a duplicate issue is always better than not knowing a problem exists at all 🙂
