### ISSUE TITLE
Issue with 9.12.2 and grouping in collections when using many to many relationships

### ISSUE THREAD

**Issue by rmurraygratte** [directus/directus#13962] opened 2022-06-17 12:10 UTC
### Describe the Bug

Previously with many to many relationships you could show them in the collection but they were grouped and would say "2 Items" for instance and then you could click into that and then into the items themselves. This was the case on a 9.9.x that I was using locally. However I have upgraded and now when I click the parent of the table it displays blank values. The alternative are to display the id's or names in a comma separated list, which is not what I want,

![image](https://user-images.githubusercontent.com/107687375/174295060-15511232-063e-4c32-8bc8-3062b81ffb3a.png)

### To Reproduce

Use an older version, create a many to many relationship and group multiple values into one linked value. For instance company Id should show "2 Items" and not a comma separated list.

### Errors Shown

No

### What version of Directus are you using?

9.12.2

### What version of Node.js are you using?

16.13.1

### What database are you using?

Azure SQL

### What browser are you using?

Chrome

### How are you deploying Directus?

Azure App Service

**Comment by br41nslug** [comment] 2022-06-17 12:13
duplicate of #13836 should be resolved with the next release when #13866 gets merged.

**Closed by br41nslug** 2022-06-17 12:13 UTC
Labels: Duplicate
