### ISSUE TITLE
Can't create new item after importing items with CSV file

### ISSUE THREAD

**Issue by rashidpathiyil** [directus/directus#11977] opened 2022-03-06 06:35 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Can't create new items.
I think experiencing this issue after importing items using bulk import option with CSV file.

![image](https://user-images.githubusercontent.com/15140041/156911893-636c8cb7-52cb-483e-8d70-bb567116009d.png)
![image](https://user-images.githubusercontent.com/15140041/156912486-81c96cec-a5af-4ae0-971f-ea775f7ac353.png)

### To Reproduce

1, Import a bulk data with CSV file

```
ID   Name
--   -------
1    Item 1
2    item 2
```

2, Try to create a new item from Directus UI

### Errors Shown

 Value has to be unique

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Postgres 13

### What browser are you using?

chrome

### What operating system are you using?

Windows 11

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment] 2022-03-06 10:47
Duplicate of #6321

**Closed by azrikahar** 2022-03-06 10:47 UTC
Labels: Bug (Potential)
