### ISSUE TITLE
Sdk schema merging issue with default Directus collection types

### ISSUE THREAD

**Issue by mattiaz9** [directus/directus#21069] opened 2024-01-13 15:55 UTC
### Describe the Bug

There is a weird behavior regarding the default Directus types using the `MergeCoreCollection` utility type.
When a custom collection have more than 1 nested collection, and one of them is a directus type it can't infer the correct types in the `readItem` or `readItems` functions.

The problem is probably caused by the `MergeCoreCollection` type since when the related directus collection is defined in the Schema (even if empty) the error goes away.

For instance if you are using `DirectusFile` in a custom collection, by adding the `directus_files` definition in the Schema definition the error disappear.

### To Reproduce

sandbox: https://codesandbox.io/p/devbox/lldd35

### Directus Version

v14.0.0 (sdk)

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2024-01-15 09:45
Duplicate of https://github.com/directus/directus/issues/19815

**Closed by br41nslug** 2024-01-15 09:45 UTC
