### ISSUE TITLE
Latency Indicator Tooltip Displaying Improperly

### ISSUE THREAD

**Issue by supermx1** [directus/directus#11341] opened 2022-01-29 21:30 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

https://user-images.githubusercontent.com/9326922/151678142-c9063159-ef10-4374-8f03-784d747561b8.mp4

### To Reproduce

Hover over the latency indicator

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

16

### What database are you using?

MySQL

### What browser are you using?

Chrome, Brave

### What operating system are you using?

MacOS, Windows Server 2019

### How are you deploying Directus?

Locally

**Comment by azrikahar** [comment] 2022-01-30 04:28
Duplicate of #11260

**Closed by azrikahar** 2022-01-30 04:28 UTC
Labels: Bug (Potential)
