### ISSUE TITLE
Relational Interface Pagination

### ISSUE THREAD

**Issue by MichaelNussbaumerGOWEST** [directus/directus#12564] opened 2022-04-04 14:58 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

If I have a relational interface with more than 100 Relations, it only shows the first 100 Items due to the API limit. It would be nice to have a pagination so you can maybe configure how many relations you want to see and browse through all the relations via pagination like on the layout view.

### To Reproduce

Add an Item with more than 100 Relations

### What version of Directus are you using?

9.6.0

### What version of Node.js are you using?

16.13.1

### What database are you using?

MySQL 8

### What browser are you using?

Chrome

### What operating system are you using?

Linux 4.18.0-348.20.1.el8_5.x86_64

### How are you deploying Directus?

locally

**Comment by azrikahar** [comment] 2022-04-04 15:10
Thanks for opening this issue! However this is a duplicate of existing issues #10616 #3889, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #3889 for future updates. [^1]

[^1]:This is an automated response.

**Closed by azrikahar** 2022-04-04 15:10 UTC
Labels: Bug (Potential)
