### ISSUE TITLE
Ghost fields

### ISSUE THREAD

**Issue by nskartoredjo** [directus/directus#20681] opened 2023-12-08 10:24 UTC
### Describe the Bug

Ones in a while, a set of fields isn't displayed correctly, and a 'ghost field' appears.

![image](https://github.com/directus/directus/assets/5946359/e802d3a9-d95a-41f3-b4b1-928c1b84c5fb)

I can't seem to find a proper solution on how to fix it, nor do I know what actually causes it. If I look into the database, the order seems to be correctly configured:

sort | field
--- | ---
5 | voltage
2 | pwr_avg
4 | pwr_max
1 | power
3 | pwr_min

### To Reproduce

I can't find a consistent way to reproduce the issue. It happens on all kinds of collections, larger ones and smaller ones.

### Directus Version

v10.7.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-12-11 11:47
Closing this as a duplicate of #20583. Happy to reopen if it's not that 👍

**Closed by rijkvanzanten** 2023-12-11 11:47 UTC
Labels: Needs More Info

**Comment by nskartoredjo** [comment] 2023-12-14 17:12
My apologies for the late response. I'm not using any conditions on the fields

**Comment by paescuj** [comment] 2023-12-14 17:21
> My apologies for the late response.

No worries! 👍

> I'm not using any conditions on the fields

I think it might still be fixed by #20599 which will be available in the next release. So maybe you can test again once the fix has been released and report back if you still see 👻 fields.

**Comment by paescuj** [comment] 2024-01-09 12:17
Awesome, thanks for your feedback! ❤️
