### ISSUE TITLE
`config > permissions > field presets` is partially working.

### ISSUE THREAD

**Issue by erondpowell** [directus/directus#15505] opened 2022-09-09 16:25 UTC
This feature seems to be partially working. I do think we have a bug.

Yesterday, neither the date-published nor the `images` (or any other preset) was being applied as a default in the app for the relevant role.

https://user-images.githubusercontent.com/62306630/189395840-f5cc8fe6-b4c9-4608-8f7b-42023718e81f.mp4

_Originally posted by @erondpowell in https://github.com/directus/directus/discussions/15483#discussioncomment-3610000_

**Comment by azrikahar** [comment] 2022-10-05 09:23
I can't seem to reproduce this on my end (tested with and without cache):

https://user-images.githubusercontent.com/42867097/194026375-4ab7ec43-1168-4673-a833-46a9d196c03e.mp4

but based on the reported partially working nature, I'm wondering if this is (somehow) a permissions cache related issue specific to cloud? 🤔 cc @joselcvarela

**Comment by joselcvarela** [comment] 2022-10-10 14:54
I tried on my Cloud project and can't reproduce it either.
Though we just had some changes on Cloud.
I suspect the issue can come from cache, but not 100% sure.

Can you reproduce this every time @erondpowell ?

**Comment by rijkvanzanten** [comment] 2022-10-12 19:38
We haven't been able to reproduce this based on the given information, so I'll close this for now. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by rijkvanzanten** 2022-10-12 19:38 UTC
Labels: API, Needs More Info, Can't Reproduce
