### ISSUE TITLE
If replacing image - unknown error occurs

### ISSUE THREAD

**Issue by faberv** [directus/directus#4396] opened 2021-03-05 17:11 UTC
```json
{
  "errors": [
    {
      "message": "E_UNKNOWN: An unknown error happened with the file 468d0c88-72fc-4bf7-b59c-c616c7cc95df.\n\nError code: undefined\nOriginal stack:\nTypeError: fs_1.promises.opendir is not a function\n    at LocalFileSystemStorage._flatDirIterator (/mnt/d/Server/lt/learntube-directus/node_modules/@directus/drive/dist/LocalFileSystemStorage.js:218:45)\n    at _flatDirIterator.next (<anonymous>)\n    at FilesService.<anonymous> (/mnt/d/Server/lt/learntube-directus/node_modules/directus/dist/services/files.js:51:103)\n    at Generator.next (<anonymous>)\n    at fulfilled (/mnt/d/Server/lt/learntube-directus/node_modules/directus/dist/services/files.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

---

### Project details
Directus Version: 9.0.0-rc.44
Environment: production
OS: Linux 4.4.0-19041-Microsoft
Node: 12.6.0

**Comment by rijkvanzanten** [comment] 2021-03-05 17:14
Duplicate of https://github.com/directus/directus/issues/3998

**Comment by rijkvanzanten** [comment] 2021-03-05 17:14
For now, you can use Node 12.12+ as a workaround

**Closed by rijkvanzanten** 2021-03-05 17:14 UTC
Labels: Duplicate

**Comment by faberv** [comment] 2021-03-05 19:50
Thank you very much! Solved 👍 😎
