### ISSUE TITLE
Error Deleting A Toggle Field

### ISSUE THREAD

**Issue by st11x** [directus/directus#12566] opened 2022-04-04 16:21 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I created a new Toggle field in my collection. Later I decided that I needed to rename it so I duplicated the field. 

However, now I can't delete any of the 2 fields. In fact, I can't delete any fields off the collection, I get a foreign key constraint failed error. 

![image](https://user-images.githubusercontent.com/7398499/161587907-f6b6ed0f-39a7-410d-8a38-277c81aae037.png)

Looks as if it is trying to drop the db table that is my collection. I was able to do that previously. 

 

### To Reproduce

I cannot reproduce this on another instance, so I don't know how this came about.

### What version of Directus are you using?

9.7.0

### What version of Node.js are you using?

16.14.0

### What database are you using?

Sqllite

### What browser are you using?

Edge

### What operating system are you using?

Windows 10

### How are you deploying Directus?

Docker

**Comment by nickrum** [comment] 2022-04-04 16:33
Duplicate of #10842

**Closed by nickrum** 2022-04-04 16:33 UTC
Labels: Bug (Potential)

**Comment by st11x** [comment] 2022-04-04 16:46
Thank you. I think that issue is related but not exactly so.

![image](https://user-images.githubusercontent.com/7398499/161590578-a46f48ad-0359-4322-b3ad-864bcd1c8b22.png)

I opened the table and saw that there is a foreign key to itself. That is because I have a field that is a M2O that refers to another from the same collection. Since Sqllite drops the table, this foreign key is also going to prevent this collection from being deleted too.

**Comment by st11x** [comment] 2022-04-04 17:34
Got it thanks. I tried doing the same by dropping the column in DBeaver and it is also trying to drop and recreate the table. It may also be a SQLite limitation.

**Comment by nickrum** [comment] 2022-04-04 18:05
You are right, this is a limitation in SQLite. The SQLite docs even suggest to do the drop-and-recreate-flow to alter the schema of a table, so I would assume DBeaver does something very similar to what Knex is doing.
