### ISSUE TITLE
Connection tooltip appears outside of page bounds

### ISSUE THREAD

**Issue by Fusseldieb** [directus/directus#11308] opened 2022-01-27 16:57 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

Title describes it. 
I remember that this worked on versions prior to 9.5.0, but unfortunately can't pinpoint in which release it broke.
In my opinion this isn't a priority issue, but I wanted to report the bug anyways.

![image](https://user-images.githubusercontent.com/4715129/151406020-0aa41c76-2ecf-4a7b-8f93-aee00f7a80b3.png)

### To Reproduce

1. Hover over the signal icon on the top left side
2. Break the laws of physics to see ouside the side bounds ;)

### Errors Shown

No errors, purely a visual issue

### What version of Directus are you using?

9.5.0

### What version of Node.js are you using?

-

### What database are you using?

-

### What browser are you using?

Chrome 97.0

### What operating system are you using?

Windows 10

### How are you deploying Directus?

running locally

**Comment by jaycammarano** [comment] 2022-01-27 17:06
Duplicate of #11288

**Closed by jaycammarano** 2022-01-27 17:06 UTC
Labels: Bug (Potential)
