### ISSUE TITLE
Collections created under a group not being removed during schema sync

### ISSUE THREAD

**Issue by spardue** [directus/directus#23692] opened 2024-09-18 15:29 UTC
### Describe the Bug

The following collection was not removed when I applied the schema we store in git. Other collections were removed. I tracked it down to any collections that were under the `default` group were not being deleted. As soon as I removed the `Gallery_Links` collection from the `default` group it got removed.
```json
{
  "collection": "Gallery_Links",
  "diff": [
    {
      "kind": "D",
      "lhs": {
        "collection": "Gallery_Links",
        "meta": {
          "accountability": "all",
          "archive_app_filter": true,
          "archive_field": null,
          "archive_value": null,
          "collapse": "open",
          "collection": "Gallery_Links",
          "color": null,
          "display_template": null,
          "group": "default",
          "hidden": false,
          "icon": "gallery_thumbnail",
          "item_duplication_fields": null,
          "note": null,
          "preview_url": null,
          "singleton": false,
          "sort": 5,
          "sort_field": null,
          "translations": null,
          "unarchive_value": null,
          "versioning": false
        },
        "schema": {
          "name": "Gallery_Links"
        }
      }
 }
```

We are using node JS migrations:
https://docs.directus.io/guides/migration/node.html

### To Reproduce

1. Create a collection under a group in directus.
2. Apply the schema with a version that does not have the new collection

Expected Results:
The collection created under the group is not there.
Actual Results:
The collection is still there

### Directus Version

10.12.1

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

Postgres 13

**Comment by joselcvarela** [comment] 2024-10-31 14:53
This is a duplicate of https://github.com/directus/directus/issues/16683 which is now fixed on https://github.com/directus/directus/pull/23851 and was released on version 11.1.2

**Closed by joselcvarela** 2024-10-31 14:53 UTC
