### ISSUE TITLE
When the date picker extends below the browser viewport, there is no way to scroll down to select

### ISSUE THREAD

**Issue by nicksergeant** [directus/directus#21181] opened 2024-01-24 15:29 UTC
### Describe the Bug

If you are using a smaller computer screen and have a date picker toward the bottom of the object editing interface, there is no way to scroll down once the date picker is open, so you cannot select certain dates or set the time at all.

<img width="1200" alt="image" src="https://github.com/directus/directus/assets/27332/2377046b-751e-4256-9c76-f66f26155ca6">

### To Reproduce

Use a small monitor / laptop, and open an object editing view with a date picker after a few other fields.

### Directus Version

v10.8.3

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2024-01-24 18:44
Thanks for opening this issue! However, this is a duplicate of #20850, which has been fixed in #20879. The fix will be available in the next release.

**Closed by paescuj** 2024-01-24 18:44 UTC

**Comment by nicksergeant** [comment] 2024-01-24 18:46
@paescuj ahhh amazing, thank you!
