### ISSUE TITLE
SQLite: Deleting a user with an image throws error

### ISSUE THREAD

**Issue by rowild** [directus/directus#19373] opened 2023-08-08 07:45 UTC
### Describe the Bug

When a user has an image assigned, it is not possible to delete one or many user(s) in a Directus 10.5.2 Docker instance with SQLite. This happens in 10.5.1 and 10.5.2 (probably earlier, too).

This is the error that is thrown:

For one user:

```json
{
  "errors": [
    {
      "message": "delete from `directus_users` 
          where `id` in ('3a487132-0a51-437a-8399-19f1b06cf591')
          - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

For many users:

```json
{
  "errors": [
    {
      "message": "delete from `directus_users` where `id` in (
        '56c691bd-6c63-4b43-9b51-4407692c51e6',
        '8b75e84e-54f3-4787-a921-a1bb5d4dcfd4',
        '3a487132-0a51-437a-8399-19f1b06cf591',
        '76b2bdcc-c124-4f20-9631-3ca0526d84f1') - SQLITE_CONSTRAINT: FOREIGN KEY constraint failed",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

The workaround would be to open the detail view of a user, delete that image there, save, go back to the user list and then delete the user.

Not tested with other DBs.

### To Reproduce

- Setup a Directus instance with SQLite.
- Create a new user and add an image
- Try to delete the user

### Directus Version

10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-08-08 09:03
Duplicate of #19303, fixed in #19308.

**Comment by paescuj** [comment] 2023-08-08 09:08
Thanks for opening this issue! However this is a duplicate of an existing issue #9507, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #9507 for future updates.

**Closed by paescuj** 2023-08-08 09:08 UTC

**Comment by rowild** [comment] 2023-08-08 13:36
@paescuj Please reopen this issue. This is a bit different from #9507 in that

- it is related to users that an admin creates - no need to log in as a different user
- it relates only to users WITH an avatar image
- it only occurs in SQLite

**Comment by rowild** [comment] 2023-08-08 13:50
@rijkvanzanten I understand.
I nevertheless would like to point out once more, that my particular observation only occurs in SQLite, while the other issue is one that concerns all DBs. As mentioned: deleting users with Avatar works fine in PostGres.
Just saying... maybe it doesn't hurt to keep this in mind.

**Comment by rijkvanzanten** [comment] 2023-08-08 13:54
That's why we make sure to explicitly link any related issues when closing things as duplicate. That way, they show up in the original thread so we're reminded to check when closing the parent issue 🙂 

<img width="618" alt="CleanShot 2023-08-08 at 09 53 29@2x" src="https://github.com/directus/directus/assets/9141017/00567f13-4517-462e-bdc1-05c1812be657">

**Comment by rowild** [comment] 2023-08-08 13:57
Thanks, @rijkvanzanten ! 
Given the original post date, #9507 seems to be quite a complicated issue! Hope you can break it down into smaller bits and pieces and solve the underlying issue!
