### ISSUE TITLE
When using the preview translation feature, Translation fields appear as edited

### ISSUE THREAD

**Issue by LevinGermann** [directus/directus#13456] opened 2022-05-20 17:12 UTC
### Describe the Bug

When we use the preview translation feature, the fields appear as edited.
Video show-casing the issue:

https://user-images.githubusercontent.com/9347206/169577783-6931ee0d-16b1-4e68-9928-ac6bc387984d.mov

When a user only has access to the languages German and English, then the raw edited value field (when opening the same as in the video) looks like this:

```
[
	{
		"name": "Place des Alpes",
		"languages_code": null
	},
	{
		"name": "The Alpes square",
		"languages_code": {
			"code": "en-US",
			"name": "English"
		}
	},
	{
		"name": "Place des Alpes [Alpenplatz]",
		"languages_code": {
			"code": "de-DE",
			"name": "German"
		}
	}
]
```

One problem itself is having an update that isn't actually one, but the more severe is (because there is an update for this field) pushing this update with the language_code as null, because in this case when trying to save, this leads to a data issue/error.

### To Reproduce

1. Create a O2M collection
2. On the Many-side, create a translation field.
3. Use the preview translation feature on the Many-collection for some field in the translation.
4. Have this display in the O-collection in the list.

### What version of Directus are you using?

9.11.0

### What version of Node.js are you using?

v16.7.0

### What database are you using?

PostgresQL 13.2

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by br41nslug** [comment] 2022-05-23 09:08
I am unable to reproduce this specific case so far.
> When a user only has access to the languages German and English
Can you share specifically how you've limited the languages? And other relevant permissions you may have set.

**Comment by LevinGermann** [comment] 2022-05-23 09:35
Thanks @br41nslug for your investigation so far.
I reproduced it quickly using a small data-set using SQLite:
[data.db.zip](https://github.com/directus/directus/files/8753333/data.db.zip)

User: admin@example.com
Password: password

You can see if you open "Trail -> EXAMPLE_1" and open the only location in the O2M list, the translation part appears edited.

If you remove "Translations" from the Display Template, the issue doesn't appear.
![image](https://user-images.githubusercontent.com/9347206/169790237-35ff6fe1-af32-4e2c-abd5-9d82dab7e9ea.png)

**Comment by LevinGermann** [comment] 2022-05-23 09:46
> When a user only has access to the languages German and English

I updated the above data-dump with this part.
[data.db.zip](https://github.com/directus/directus/files/8753473/data.db.zip)

User: author@example.com
Password: password

If you open the "Trail"-Item again and look at the translations, they still appear edited but the value contains the mentioned problem:
``` 
[

	{
		"name": "English Name",
		"id": 1,
		"languages_id": {
			"code": "en-US",
			"name": "English"
		}
	},
	{
		"name": "French Name",
		"id": 2,
		"languages_id": null
	}
]

```

**Comment by br41nslug** [comment] 2022-05-23 10:19
Thanks I was able to reproduce it using that provided database. I do however think this is working as expected if you only limit the languages table then the language relation on the junction table will be `null` as you don't have perms for that language but do have permission for that junction item.

I was able to solve to saving issue by adding the appropriate restrictions (similar to the one you had for languages) on the translations junction table:
![](https://i.imgur.com/updi31F.png)
![](https://i.imgur.com/8dKkycg.png)
*I set the edits to the same as the view permission*

The interface will still recognize its contents as "changed" because technically it is changed it's missing a language record in its data. With these permissions however it no longer interferes with the saving of the data on the o2m side.

**Comment by br41nslug** [comment] 2022-05-23 10:23
Closing this issue for now, if setting these permissions does not solve your initial problem we can re-open this and investigate further.

**Closed by br41nslug** 2022-05-23 10:23 UTC
Labels: Needs More Info, Bug (Potential), Can't Reproduce

**Comment by LevinGermann** [comment] 2022-05-23 11:55
Thanks @br41nslug , setting these permissions helps and your explanation makes sense. 👍 

> The interface will still recognize its contents as "changed" because technically it is changed it's missing a language record in its data. With these permissions however it no longer interferes with the saving of the data on the o2m side.

Regarding this, this is now no longer a problem, I just see some inconsistency:
For M2A lists this interestingly doesn't occur (we have entries for German, English and French):

https://user-images.githubusercontent.com/9347206/169813654-2e57f751-7750-484e-a77e-97dc844a14bd.mov

Not really a problem for us, just to make you aware of this... :)

**Comment by LevinGermann** [comment] 2022-05-24 08:05
https://user-images.githubusercontent.com/9347206/169981054-b098f3b6-5179-4f1a-a2ed-29da7379c41d.mov

To make matters even worse, I think this somehow influences the data-consistency and decouples the translation object from the collection . (See above)
