### ISSUE TITLE
Server problem with upload images and files

### ISSUE THREAD

**Issue by Ivann-2612** [directus/directus#12245] opened 2022-03-19 15:47 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

I have an error when I want to upload a picture and files

### To Reproduce

Problem is with uploading a pictures in my project.You have an images with problem

![ECA52D92-0F3C-4A33-B17F-E08E929E1489](https://user-images.githubusercontent.com/60244706/159128129-41f19e5d-04e3-4fb4-bf98-3de736086ee8.jpeg)
![420E4FAE-78BC-4D3E-9CDF-01B4DFE06E78](https://user-images.githubusercontent.com/60244706/159128130-38c60c65-a711-4962-873f-81964c9c1bc2.jpeg)

### Errors Shown

Internal server error

### What version of Directus are you using?

9

### What version of Node.js are you using?

Latest

### What database are you using?

Sqlite3

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Locally

**Comment by emrahnazif** [comment] 2022-03-20 11:17
This looks like same issue with #11719

**Comment by Ivann-2612** [comment] 2022-03-20 11:28
I can’t see the answer in this issue,can you tell me what should I do?

**Comment by emrahnazif** [comment] 2022-03-20 11:49
> I can’t see the answer in this issue,can you tell me what should I do?

I assume you created the "Corresponding Field" while creating the pictures field. Removing the "Corresponding Field" fix the problem for me (even though I want to have that option...).

**Comment by licitdev** [comment] 2022-03-21 07:12
Closing as this is a duplicate of #11719.
Thank you @emrahnazif for the workaround.

**Closed by licitdev** 2022-03-21 07:12 UTC
Labels: Bug (Potential)
