### ISSUE TITLE
Cannot add more than 22 values in a "is one of" filter?

### ISSUE THREAD

**Issue by arladmin** [directus/directus#19465] opened 2023-08-17 16:40 UTC
### Describe the Bug

In the Directus app, whenever i try to add more than 22 values in a "is one of" filter, i get the **500** error.

![image](https://github.com/directus/directus/assets/64059154/d3e23e8c-2871-462d-88a3-1c531761aef8)

### To Reproduce

.

### Directus Version

v10.5.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by rijkvanzanten** [comment] 2023-08-17 17:02
Duplicate of https://github.com/directus/directus/issues/16745

**Closed by rijkvanzanten** 2023-08-17 17:02 UTC
