### ISSUE TITLE
Rights to view the image is missing even through API and directus dashboard

### ISSUE THREAD

**Issue by anish0123** [directus/directus#19726] opened 2023-09-18 15:03 UTC
### Describe the Bug

Hi, 
I have a data collection with a data model, that contains text and images

The problem is that image from 1st data collection model returns 403 forbidden even thought nothing has changed. I am able to access the id but not the image related to the id. I am unable to access the image even from API and admin dashboard.
The other images are displayed normally.

The issue is kind of related to discussion #9839 . I could not find any solution from the discussion so I am hoping I could get some help from here. Thank you!

![Screenshot 2023-09-18 at 18 00 58](https://github.com/directus/directus/assets/87969471/d7b5f92e-9112-40dd-9c57-017d9e4062fa)

### To Reproduce

1. Upload images through a data collection
2. Work for couple of days
3. Status: errors": [
{
"message": "You don't have permission to access this.",
"extensions": {
"code": "FORBIDDEN"
}
}
]

### Directus Version

v10.6.1

### Hosting Strategy

Self-Hosted (Custom)

**Comment by DanielBiegler** [comment] 2023-09-18 16:24
Hi there! Well, theres not much to go from here, could you please provide more details?

Is it possible that you moved your uploads folder, for example when you develop and move to production? Can you confirm that the file actually exists with the same ID? See the following image and compare the id in the URL and the ID in my local file browser:

![image](https://github.com/directus/directus/assets/14810858/f531cb85-4c29-4e99-876a-458fc563da71)
 
- What kind of storage are you using?
- Is there any error log in the console? Any errors in the browser?

Please provide more information as that helps us to actually help you. Thank you! :)

**Comment by anish0123** [comment] 2023-09-20 14:47
Hi, I am sorry I could not provide you with more details because I am not too sure about the problem and how did it occur.
There has not been any changes to uploads folder.  The files are being stored directly in azure server, so I could not check if the file exists in the server. I could not find a way to check it.  The only error when I try to load the file is status error:  errors": [
{
"message": "You don't have permission to access this.",
"extensions": {
"code": "FORBIDDEN"
<img width="1470" alt="Screenshot 2023-09-20 at 17 46 41" src="https://github.com/directus/directus/assets/87969471/ca94acef-d6e8-426b-98c5-31afb54b2bff">

}
}
]
I have attached the picture so it show more in detail about the error. I hope I have explained the error a bit more in detail. Thank you!

**Comment by anish0123** [comment] 2023-09-20 14:51
Hi, I am sorry I could not provide you with more details because I am not too sure about the problem and how did it occur.
There has not been any changes to uploads folder.  The files are being stored directly in azure server, so I could not check if the file exists in the server. I could not find a way to check it.  The only error when I try to load the file is status error:  errors": [
{
"message": "You don't have permission to access this.",
"extensions": {
"code": "FORBIDDEN"
<img width="1470" alt="Screenshot 2023-09-20 at 17 46 41" src="https://github.com/directus/directus/assets/87969471/ca94acef-d6e8-426b-98c5-31afb54b2bff">

}
}
]
<img width="1470" alt="Screenshot 2023-09-20 at 17 46 41" src="https://github.com/directus/directus/assets/87969471/3a949087-4c45-4c4c-969e-d0fe19840622">

I have attached the picture so it show more in detail about the error. I hope I have explained the error a bit more in detail. Thank you!

**Comment by anish0123** [comment] 2023-09-20 14:53
Hi, I am sorry I could not provide you with more details because I am not too sure about the problem and how did it occur.
There has not been any changes to uploads folder.  The files are being stored directly in azure server, so I could not check if the file exists in the server. I could not find a way to check it.  The only error when I try to load the file is status error:  
errors": [
{
"message": "You don't have permission to access this.",
"extensions": {
"code": "FORBIDDEN"
}
}
]
I have attached the picture so it show more in detail about the error. I hope I have explained the error a bit more in detail. Thank you!

<img width="1470" alt="Screenshot 2023-09-20 at 17 46 41" src="https://github.com/directus/directus/assets/87969471/4add7495-a192-49c7-9329-69c1cbbc031f">

**Comment by DanielBiegler** [comment] 2023-09-20 16:21
With no reproduction steps, no information about your setup, no environment variables or any error logs I can't help. This seems like some type of misconfiguration on your end, so I'll close this for now because we use GitHub Issues to keep track of bugs in Directus. Happy to keep discussing in this thread, and we'll reopen once more information becomes available 👍🏻

**Closed by DanielBiegler** 2023-09-20 16:21 UTC
Labels: Needs More Info
