### ISSUE TITLE
When deleting an extension folder, the directus_extensions entry remains

### ISSUE THREAD

**Issue by Pachat** [directus/directus#21970] opened 2024-03-25 11:40 UTC
### Describe the Bug

When deleting an extension folder, the directus_extensions entry remains listed
Not sure weather it is the wanted feature.
In that case, we should be able to Uninstall from the collection.
Other wise, the directus_extensions should be deleted and not appear in the extensions list.

### To Reproduce

Remove the server's folder of an extension
Refresh the extensions list in admin.

### Directus Version

v10.10.4

### Hosting Strategy

Self-Hosted (Custom)

**Comment by br41nslug** [comment] 2024-03-25 11:42
Duplicate of https://github.com/directus/directus/issues/21717

**Closed by br41nslug** 2024-03-25 11:42 UTC
