### ISSUE TITLE
Value of text input is set to "NULL" when no data present

### ISSUE THREAD

**Issue by hybridvision** [directus/directus#1741] opened 2017-08-15 17:15 UTC
## Version Info
  - Directus version and branch: 095dcee9efb61ca4674b805474b48bdcc0c9ab58 (latest develop)
  - PHP version: 7.0.13
  - MySQL version: MariaDB 10.2.7
  - Web server: Nginx
  - OS name and version: OS X 10.9.5

## Expected Behavior
When managing a simple VARCHAR field that has a default value of NULL, the text field should be empty when it has no value (or show the placeholder if set).

Field setup:

![image](https://user-images.githubusercontent.com/11492432/29326192-d9160024-81ea-11e7-827b-3fdbcd9bf258.png)

## Actual Behavior
The text field has a value of "NULL" (an actual 4 character string) that needs to be deleted to enter a real value: 

![image](https://user-images.githubusercontent.com/11492432/29325888-b0412d28-81e9-11e7-805a-45f264a4fdda.png)

Interestingly, if I don't touch this field and save the record, the string "NULL" is not entered into the database and the value remains a true `NULL`.

I also noticed that setting a placeholder doesn't work properly: when I edit the field and update the interface options, the placeholder doesn't seem to be saved (similar behaviour to https://github.com/directus/directus/issues/1708#issuecomment-322519877) AND the sort order is reset, sending the field to the bottom of the list. This reordering remains even after a full refresh.

## Steps to Reproduce
 1. Create a field in a table with a setup as shown in the screenshot above.
 2. Go to the table and try to add a new record.
 3. See that the value of the text field is set to "NULL"

Thanks for your work on Directus!

**Comment by WellingGuzman** [comment] 2017-08-15 19:35
Hey @hybridvision did you type the word `NULL` into the default? or was this a column created in the database directly?

I can't reproduce this issue

**Comment by benhaynes** [comment] 2017-08-15 21:59
Just to clarify:

Leave default value untouched: `NULL` (true NULL)
Change the default and then type "NULL" results in the string "NULL"

We can do one of two things:

1. Make "NULL" always equal `NULL`... even if typed by the user. The only problem here is that "NULL" (string) can never be the default.
2. Add a checkbox beside the Default label to explicitly set it to `NULL`


Any thoughts?

**Comment by hybridvision** [comment] 2017-08-15 22:56
Hi @WellingGuzman - no, I never typed the word `NULL`anywhere. I just went to the table, clicked "Add New Column" and then filled out the field name and hit save like so:
 
![image](https://user-images.githubusercontent.com/11492432/29339705-b418ffe8-821b-11e7-856b-deee59d31c6f.png)

You will notice in this screenshot above that the default value field is actually empty and there is just the placeholder `NULL`. However, as soon as I hit save and come back to look at the field settings, it is now the string "NULL" instead of being empty:

![image](https://user-images.githubusercontent.com/11492432/29339825-602b5e66-821c-11e7-8833-788b94227613.png)

In this screenshot, I just clicked in the box and selected the text to show it is not a placeholder.

I'm not sure what is going on but at some point the value is being made a string. I'm new to Directus so I don't know how this was handled previously...

@benhaynes - when the default value field is empty, the placeholder says `NULL`so couldn't an empty default value be considered `NULL`? It doesn't really make sense to me that I enter nothing in the field and when I come back, it's populated with the string "NULL". I think it should remain empty and that be considered `NULL`. Maybe I'm missing some possible use cases but that makes most sense to me... I guess the explicit checkbox would be clearest if we can't have an empty value for some reason.

**Comment by WellingGuzman** [comment] 2017-08-15 23:07
Hey @hybridvision out of curiosity what browser are you using? maybe doesn't play nice with placeholder attribute.

**Comment by hybridvision** [comment] 2017-08-16 07:46
Hi @WellingGuzman, I'm using Chrome 59.0.3071.115 so I don't think there's any problem with the placeholder. When I inspect the element, the value is being set to "NULL":

![image](https://user-images.githubusercontent.com/11492432/29352609-b02b06c8-8267-11e7-9998-680c819646dc.png)

**Comment by hybridvision** [comment] 2017-08-17 13:56
An update on this: I tried on a different system with a similar setup but newer OS (MacOS 10.12.6) and with a fresh Directus install, this behaviour is not there.

I then went back to the original system and did a fresh Git clone, composer install, created a blank database and installed Directus again. On this system (OS X 10.9.5), the "NULL" behaviour reported in this ticket remains... I even tried a different browser and confirmed that an empty string is being sent when I save the column on the problematic system.

Aside from the OS version, I'm not sure what could influence this behaviour. On the working system, the PHP version is slightly older (7.0.9 vs 7.0.13) and so is the database server (MariaDB 10.1.16 vs 10.2.7). Do you think the database server version could be the cause?

**Comment by WellingGuzman** [comment] 2017-08-17 14:32
hey @hybridvision The database can potentially influence this as we get default, using MariaDB 10.1.16 throws the "NULL" string issue?

**Comment by hybridvision** [comment] 2017-08-17 15:25
Ah I see - no, it's MariaDB 10.2.7 that has the problem so it seems to be a change that was introduced in the newer 10.2 version. More info here if you're interested: https://mariadb.com/kb/en/mariadb/what-is-mariadb-102/

I've never had issues with MairaDB for development on other projects but I guess officially it's not supported by Directus?

**Comment by WellingGuzman** [comment] 2017-08-17 15:40
We never tested it on MariaDB but we assume it could have some minor issues, and we probably finally found one. we directly support Percona and MySQL which are the one we actively use.

I will install MariaDB and test. (Thanks for the 10.2 changelog)

**Comment by hybridvision** [comment] 2017-08-17 20:48
Thanks @WellingGuzman! If you have time to do some tests with MariaDB, that would be great because it does seem a bit buggy with Directus. Maybe I'll have to use MySQL in the end...

By the way, I don't know which system you use but if you're on a Mac, it's easy to use Homebrew to install MariaDB - the current is 10.2 but you can install 10.1 by specifying `mariadb@10.1`.

**Comment by WellingGuzman** [comment] 2017-08-20 22:10
Hey @hybridvision I have fixed this issue, please confirm.

Closed byhttps://github.com/directus/directus/commit/98cfd46edc0a40342cff5a47ee2a2734e1eec029

**Closed by WellingGuzman** 2017-08-20 22:10 UTC
Labels: 4. Minor, Bug, Can Not Duplicate

**Comment by hybridvision** [comment] 2017-08-21 16:22
Thanks @WellingGuzman - it works perfectly now! :)

**Comment by WellingGuzman** [comment] 2017-08-21 20:53
@hybridvision awesome!
