### ISSUE TITLE
Crash app after Okta login attempt

### ISSUE THREAD

**Issue by zhibirc** [directus/directus#18034] opened 2023-04-03 13:08 UTC
### Describe the Bug

Welcome screen/initial page loaded well. Then, after login attempt using Okta, I got the following error in my container with Directus:

```
[12:43:59] GET /auth/login/okta?redirect=https://<CMS_URL>/admin/login?continue 302 11ms
/app/node_modules/directus/dist/utils/redact-header-cookies.js:7
        cookieHeader = cookieHeader.replace(re, `$1--redacted--`);
                                    ^

TypeError: cookieHeader.replace is not a function
    at redactHeaderCookie (/app/node_modules/directus/dist/utils/redact-header-cookies.js:7:37)
    at res (/app/node_modules/directus/dist/logger.js:118:97)
    at Object.wrappedResSerializer [as res] (/app/node_modules/pino-std-serializers/index.js:31:14)
    at Pino.asJson (/app/node_modules/pino/lib/tools.js:132:33)
    at Pino.write (/app/node_modules/pino/lib/proto.js:205:28)
    at Pino.LOG [as info] (/app/node_modules/pino/lib/tools.js:62:21)
    at onResFinished (/app/node_modules/pino-http/logger.js:124:15)
    at ServerResponse.onResponseComplete (/app/node_modules/pino-http/logger.js:173:14)
    at ServerResponse.emit (node:events:525:35)
    at onFinish (node:_http_outgoing:950:10)
```

**Specified file:**

directus/dist/utils/redact-header-cookies.js

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.redactHeaderCookie = void 0;
function redactHeaderCookie(cookieHeader, cookieNames) {
    for (const cookieName of cookieNames) {
        const re = new RegExp(`(${cookieName}=)([^;]+)`);
        cookieHeader = cookieHeader.replace(re, `$1--redacted--`);
    }
    return cookieHeader;
}
exports.redactHeaderCookie = redactHeaderCookie;
```

This flow worked perfectly until new version 9.23.3 was deployed.

**Node.js**: v18.12.1
**Directus**: 9.23.3

### To Reproduce

Try to login with Okta, may be some other IDP auth fails in the same way.

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-04-03 13:10
Duplicate of #17905, and it's fixed by #17914 for `9.23.4` 👍

**Closed by azrikahar** 2023-04-03 13:10 UTC
