### ISSUE TITLE
Custom interface not working

### ISSUE THREAD

**Issue by Meldiron** [directus/directus#5064] opened 2021-04-14 21:35 UTC
Issue: Hello-world custom interface does not work properly

Version: `docker directus/directus:v9.0.0-rc.57 DIGEST:sha256:d0c8fcc9e7147933dc60834e0c6684868f8d847bf3be0f644a2ab212bad995d2`

Steps to reproduce:
1. Follow guide on `how to create custom interface`
2. Try to use custom interface

Details:

After creating a new interface, request to `/extensions/interfaces/` returns `{"data":["category-tree"]}`, but there is no request to fetch `index.js` file of this interface.

![image](https://user-images.githubusercontent.com/19310830/114782142-e1cf6080-9d79-11eb-8ca9-21f85f36b609.png)

If I create new field, I cant see my interface in the option list.

![image](https://user-images.githubusercontent.com/19310830/114782195-f27fd680-9d79-11eb-937e-793ce80b691a.png)

If I manually set the field interface in the database in directus_fields table, I end up with this error

![image](https://user-images.githubusercontent.com/19310830/114782231-03c8e300-9d7a-11eb-9772-b2b8077a1e08.png)

There are no errors in the console.

**Comment by rijkvanzanten** [comment] 2021-04-14 21:38
I believe this is a duplicate of https://github.com/directus/directus/issues/5028 / https://github.com/directus/directus/issues/4902 fixed in https://github.com/directus/directus/pull/4986 👍🏻

**Closed by rijkvanzanten** 2021-04-14 21:38 UTC
