### ISSUE TITLE
10.10.0 installation or upgrade fails "TypeError: Cannot read properties of undefined (reading 'join')"

### ISSUE THREAD

**Issue by Atemndobs** [directus/directus#21722] opened 2024-03-06 14:18 UTC
### Describe the Bug

When attempting to install or upgrade to Directus version 10.10.0 using Docker, the process fails with a TypeError: Cannot read properties of undefined (reading 'join') during the migrations phase. This issue occurs both when trying to install Directus afresh or upgrade from version 10.9.3, even on a fresh database.

Full error
directus_app  | [14:05:51.219] INFO: Applying Marketplace...
directus_app  | TypeError: Cannot read properties of undefined (reading 'join')
directus_app  |     at Function.<anonymous> (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/database/index.js:132:86)
directus_app  |     at Function.emit (node:events:517:28)
directus_app  |     at Client_MySQL.<anonymous> (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/knex-builder/make-knex.js:307:10)
directus_app  |     at Client_MySQL.emit (node:events:517:28)
directus_app  |     at /directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:165:21
directus_app  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
directus_app  |     at async Runner.queryArray (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:287:20)
directus_app  |     at async Runner.ensureConnection (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:318:14)
directus_app  |     at async Runner.run (/directus/node_modules/.pnpm/knex@3.1.0_mysql@2.18.1_pg@8.11.3_sqlite3@5.1.7_tedious@17.0.0/node_modules/knex/lib/execution/runner.js:30:19)
directus_app  |     at async up (file:///directus/node_modules/.pnpm/file+api_@unhead+vue@1.8.10_pinia@2.1.7_typescript@5.3.3_vue@3.4.21/node_modules/@directus/api/dist/database/migrations/20240204A-marketplace.js:53:5)

### To Reproduce

Clone the Directus repository.
Attempt to install or upgrade to Directus version 10.10.0 using the command docker compose up --build.
Observe the failure in the console output during the migrations phase, specifically at the step involving the application of migrations related to the marketplace.

### Directus Version

v10.10.0

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-03-06 14:19
Duplicate of https://github.com/directus/directus/issues/21710

**Closed by br41nslug** 2024-03-06 14:19 UTC
