### ISSUE TITLE
Insights module bugs

### ISSUE THREAD

**Issue by Attacler** [directus/directus#8701] opened 2021-10-11 19:46 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

First of all, i know its a beta but here are some things i found:
- Filter on date empty gives an error in the network tab:
    ```js
    {"errors":[{"message":"\"_null\" has to be a boolean","extensions":{"code":"INVALID_QUERY"}}]}
    ```
   The query it is trying to execute:
   ```js
   {"_and":[{"betaald_op":{"_null":null}}]}
   ```
   
- Sometimes date does not go well

   ![image](https://user-images.githubusercontent.com/42644889/136847211-2e09c434-5a28-4048-b721-6d1443764fb6.png)
   
   The settings i have selected:
   
   ![image](https://user-images.githubusercontent.com/42644889/136847258-effaa3fa-eb60-4672-8fac-7a127d4a7790.png)

   Fields:
    - uren = float
    - registratiedatum = date

So far it looks like a great feature!

### To Reproduce

See above

### What version of Directus are you using?

docker rc96

### What version of Node.js are you using?

docker

### What database are you using?

Postgres 13

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2021-10-12 09:28
> I restarted the directus instance and it seems to work like meant to be.
Not sure if there is any (browser/server) cache or anything else involved.

That's... strange indeed. I also did another test by enabling cache, but nothing seems to be out of the ordinary. However it _might_ be somehow a weirdly formed cached data. (or maybe caused by the bug with filter 🤔)

Since the first bug will be addressed by another PR, and this second date bug "seemingly" disappeared, I'll close this issue for now. Do let us know if it ever appear again so we can reopen this 👍

**Comment by azrikahar** [comment] 2021-11-05 05:06
@Attacler Pardon the delay on getting back on this 🙈 However I've just recently been able to reproduce this here:

![chrome_D6ras2qDuM](https://user-images.githubusercontent.com/42867097/140460857-e6c82433-c6d5-418f-82eb-aaa04c8edb7d.png)

Oddly enough changing this from `datetime` to `numeric` ([Reference](https://apexcharts.com/docs/options/xaxis/#type))

https://github.com/directus/directus/blob/28ac068720f63da5ee21911a738a16d24fd7ef21/app/src/panels/time-series/time-series.vue#L306

seems to fix it:

![chrome_O4lpsSZNTX](https://user-images.githubusercontent.com/42867097/140460874-7debd982-6000-4328-be8c-2fab69045e09.png)

We'll need to investigate further whether this is an issue of Directus' current implementation of ApexCharts.js, or an actual bug with ApexCharts.js itself.

**Comment by Attacler** [comment] 2021-11-05 08:22
@azrikahar thank you for getting back on it.
I think that it could be solved with making it a string and making the date a string (date.toLocaleDateString).
Not sure if this is the solution tho, just a thing that went trough my head while reading this.

**Comment by azrikahar** [comment] 2021-11-05 09:40
That is indeed one of the possibility I thought of as well, but it'd also probably better if we can still leverage on the provided datetime type. I think I was able to reproduce it on someone else's codepen (very slightly break, but still looked fine, unlike ours), but I didn't note down what it was & I closed the tab earlier 😂

Currently I'm hoping to reproduce this in something like codepen or jsfiddle so we can be extra sure if it's a bug with the chart library 👍 Will try to look into it.

**Comment by azrikahar** [comment] 2021-12-14 05:49
It's been a while but as I've once again unintentionally reproduced this, this is starting to be suspected as an issue with the API returned value rather than an issue with the chart rendering.

Also managed to reproduce it by using the API data in minimal setup: https://jsitor.com/preview/hlF6fQJni

@Attacler do you by any chance still have a reproducible/existing chart like this? It's okay if you don't have it anymore, but in case you do have it, would you mind providing the returned payload via the API? Here's an example of how to do that from what I could think of:

https://user-images.githubusercontent.com/42867097/145939307-3e643ee6-4158-4f29-a0bf-21eb8cba7d63.mp4

1. Open devtools so it will track network requests
2. View the dashboard with the faulty dashboard
3. check network tabs in Devtools, and find the API call that corresponds to the faulty chart's data (might be difficult if you have multiple charts)
4. Copy the data returned via the step shown in the clip above and share it here
5. It'd also be helpful if you can share the query that the API call used, which can be viewed in the Payload tab of the same network request:

    ![image](https://user-images.githubusercontent.com/42867097/145939608-50734d8b-dc01-48c0-99d6-94c5dca47bcd.png)

**Comment by rijkvanzanten** [comment] 2022-04-15 21:50
I'm not able to reproduce this under v9.9.0. @azrikahar / @Attacler could you confirm if the issue still persists on your end? We can reopen accordingly 🙂  Thanks!

**Closed by rijkvanzanten** 2022-04-15 21:50 UTC
Labels: Can't Reproduce
