### ISSUE TITLE
Pie Chart doesn't provide a way to label the value on the Chart

### ISSUE THREAD

**Issue by peatiscoding** [directus/directus#20551] opened 2023-11-27 22:59 UTC
### Describe the Improvement

**Pie / Donut Chart to allow configurable displaying Label**

Version: 3.8.2

Directus' Pie / Donut chart does allow configure of a `value` but not the `label`. The only value being used is the value that contribute to the pie. However I think many usecases would need to `label` the aggregated value. (e.g. category, entity title, etc).

![Screenshot 2566-11-28 at 05 53 08](https://github.com/directus/directus/assets/12985531/ff59196a-4823-4552-b41c-40c57a4d6a3a)

If directus would allow the Label of the chart to be configured that would be awesome!

**Comment by krysialynne** [comment] 2023-11-29 17:21
This is already a feature request under review: https://github.com/directus/directus/discussions/18833

**Comment by rijkvanzanten** [comment] 2023-12-11 11:40
Closing this as it's a duplicate of #18833 which needs a bit more discussion before it becomes a ready-to-implement issue

**Closed by rijkvanzanten** 2023-12-11 11:40 UTC
