### ISSUE TITLE
M2O Display and Interface won't display related values

### ISSUE THREAD

**Issue by flicksolutions** [directus/directus#6036] opened 2021-06-03 16:38 UTC
On a M2O-Field, the Display- and Interface-Fields do not display relative values even if relative values are selected:
![display](https://user-images.githubusercontent.com/33655122/120679620-a90a5880-c499-11eb-8d72-02750d3776e1.png)
It shows just nothing in the list-view:
![list](https://user-images.githubusercontent.com/33655122/120679705-c5a69080-c499-11eb-9d5a-d271801cbedf.png)
or in the item itself:
![detail](https://user-images.githubusercontent.com/33655122/120679756-d2c37f80-c499-11eb-9d18-a95ca038709d.png)

The same goes for the interface values.

The only thing that works is to display the ID and only the ID:
![ID-Display](https://user-images.githubusercontent.com/33655122/120680436-96dcea00-c49a-11eb-8fef-e047ea65e5d4.png)

I am using **rc.71** on a DO-Droplet.

Thanks for your feedback!

**Comment by rijkvanzanten** [comment] 2021-06-04 01:22
@flicksolutions Can you share a DB dump where this is happening? I just setup a fresh installation and tried it out, and it seems to work as expected on my end 🤔 

<img width="946" alt="CleanShot 2021-06-03 at 21 22 02@2x" src="https://user-images.githubusercontent.com/9141017/120731503-c3503080-c4b1-11eb-8d40-30c449604a7f.png">

![CleanShot 2021-06-03 at 21 22 13@2x](https://user-images.githubusercontent.com/9141017/120731516-ca773e80-c4b1-11eb-89be-9be50882cf49.png)

![CleanShot 2021-06-03 at 21 22 27@2x](https://user-images.githubusercontent.com/9141017/120731521-cf3bf280-c4b1-11eb-86d0-7695b4ebdd51.png)

**Comment by rijkvanzanten** [comment] 2021-06-04 01:22
Thank you for taking the time to submit this! Unfortunately, our team was not been able to reproduce it based on the information provided. Therefore, we will close this ticket for now, but will happily re-open it if new details are provided that allow us to reliably replicate the problem.

As a reminder:
* Provide as much detail as possible in the issue description
* Video screen captures and clear steps are very helpful
* A full SQL dump is the fastest way for us to test/resolve (can be sent privately)
* Make sure you are on the latest version of Directus
* Did you try turning it off and on again?

---

_This is an automated response._

**Closed by rijkvanzanten** 2021-06-04 01:22 UTC
Labels: App, Bug (Potential)

**Comment by flicksolutions** [comment] 2021-06-04 08:13
> @flicksolutions Can you share a DB dump where this is happening? I just setup a fresh installation and tried it out, and it seems to work as expected on my end 🤔

hi @rijkvanzanten!
yeah, sure I can provide you with that!
I feel a bit uncomfortable to post it in this thread: can I send it to you in a PM? (for example over discord?)

Thank you for looking into this!

**Comment by flicksolutions** [comment] 2021-06-04 08:27
Also I discovered, that the bug has something to do with the display setting of the targeted-field!
If I display the raw value of the String field, then it will show up everywhere just fine. But if I choose the **Collection** Display Interface. It won't show up in the M2O's Display.

Is what I've written understandable? It's a bit hard to explain. I try it formaly.

This does work:
collection O: M2O-Field Display: field A of collection M
collection M: field A Display: *raw-value*

This does **not** work:
collection O: M2O-Field Display: field A of collection M
collection M: field A Display: *Collection*

![Display of target field](https://user-images.githubusercontent.com/33655122/120771248-4f4c7180-c51f-11eb-92b7-33d24c199c5e.png)

**Comment by rijkvanzanten** [comment] 2021-06-04 15:21
> I feel a bit uncomfortable to post it in this thread: can I send it to you in a PM? (for example over discord?)

Heya! You can send it directly to me at rijk@directus.io 🙂

**Comment by rijkvanzanten** [comment] 2021-06-04 15:22
> But if I choose the Collection Display Interface. It won't show up in the M2O's Display.

Ahh, the collection display is meant to show a collections' name based on the saved collection key. I think the reason it's not showing anything is because the value you're trying to have the collections display render isn't actually a collection key 🙂

**Comment by flicksolutions** [comment] 2021-06-04 16:05
Oh, God. This is embarrassing... The data structure changed somewhat during the project so that the values I'm trying to display are actually not keys of collections any more... you are totally right!

I'm sorry for falsely opening a Bug report. :/
Thanks again!

**Comment by rijkvanzanten** [comment] 2021-06-04 16:07
No problem! Glad to hear it was resolved 🙂
