### ISSUE TITLE
Save and quit does no longer returns to collection bookmark

### ISSUE THREAD

**Issue by boncossoftware** [directus/directus#22338] opened 2024-04-29 14:01 UTC
### Describe the Bug

Previously in version <= v10.10.5, when you save and quit an item you would return to the bookmark you were in before. In the latest version v10.10.7 it will no longer return to the bookmark but would instead return to the collection itself. This means that every time you edit an item (then save and quit by pressing the top right blue save button) you have to go back to the bookmark you were in. 

### To Reproduce

Create a bookmark for an item and go to that bookmark making sure there are some items in there to edit. Then edit one of the items and press the save button. You will not return to the bookmark but will instead return the the main collection.

### Directus Version

v10.10.7

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by br41nslug** [comment] 2024-04-29 14:03
Duplicate of #22187

**Closed by br41nslug** 2024-04-29 14:03 UTC
