### ISSUE TITLE
Non-admin users can't update 'multiple files' field

### ISSUE THREAD

**Issue by mcarlson** [directus/directus#5609] opened 2021-05-11 19:36 UTC
Non-admin users can't update 'multiple files' field, even with all permissions set to true for all collections and system collections.  This kind of request from the browser:

```js
fetch("http://localhost:8055/items/uploads/1", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "authorization": "Bearer XXXXX",
    "cache-control": "no-cache",
    "content-type": "application/json;charset=UTF-8",
    "pragma": "no-cache",
    "sec-ch-ua": "\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\"",
    "sec-ch-ua-mobile": "?0",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "cookie": "XXXXX"
  },
  "referrer": "http://localhost:8055/admin/collections/uploads/1",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"files\":[{\"directus_files_id\":\"72dac28b-3178-48e1-86da-644b7877354f\"}]}",
  "method": "PATCH",
  "mode": "cors"
});
```

Returns:

```json
{
  "message": "You don't have permission to access this.",
  "extensions": {
    "code": "FORBIDDEN"
  }
}
```

---

### Project details
Directus Version: 9.0.0-rc.64
Environment: production
OS: macOS Catalina (10.15)
Node: 12.18.4

**Comment by kendoka** [comment] 2021-05-12 17:25
I believe this also related: [#5624](https://github.com/directus/directus/issues/5624) and indeed it was working in .62, but was broken from >= .63

**Comment by rijkvanzanten** [comment] 2021-05-12 17:29
@kendoka Ah yeah, good catch 

Duplicate of  #5624

**Closed by rijkvanzanten** 2021-05-12 17:29 UTC

**Comment by mcarlson** [comment] 2021-05-18 12:56
FWIW yes, I was using a proper bearer token - I edited it before posting here. I should have mentioned this! Indeed the dupe captures what I'm seeing more accurately. It would be good to get a fix, it's a pretty major issue. Thank you!
