### ISSUE TITLE
Array of Groups

### ISSUE THREAD

**Issue by levimichael** [directus/directus#2119] opened 2018-04-13 00:19 UTC
Our team would love to see users being able to be in multiple groups, not just one.

Thanks guys!

**Comment by WellingGuzman** [comment] 2018-04-13 03:53
Hey @levimichael would you like to explain more about this? how will this work? benefits, etc from your point of view at least.

Some people has commented about this before, and I want to know more how you all came to the conclusion of this new feature.

Although this is not a bug, it will probably fit best on https://request.getdirectus.com

I will close this ticket, but feel free to continue discussing the subject.

**Closed by WellingGuzman** 2018-04-13 03:53 UTC
