### ISSUE TITLE
Seems like didn't create the tables by install step

### ISSUE THREAD

**Issue by jacobzeng** [directus/directus#1703] opened 2017-07-20 11:36 UTC
## Version Info
  - directus-build-6.4.0-20170710010648.tar.gz
  - PHP version: PHP 7.0.7 (cli) (built: Jun 10 2016 02:48:02) ( NTS )
  - MySQL version: MySQL 5.5
  - Web server: Apache
  - OS name and version: Ubuntu 14.04

## Expected Behavior

Install successful

## Actual Behavior

Got error when install step 4,  there is no any tables in database

## Logs or Screenshots

```
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist in /var/www/html/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239 Stack trace: #0 /var/www/html/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute() #1 /var/www/html/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute() #2 /var/www/html/api/core/Directus/Database/TableGateway/BaseTableGateway.php(678): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select)) #3 /var/www/html/api/core/Directus/Database/TableGateway/BaseTableGateway.php(659): Directus\Database\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select), Array) #4 /var/www/html/api/core/Directus/Database/TableGateway/BaseTableGateway.php(643): Directus\Database\TableGateway\BaseTableGateway->selectWith(Object(Zend\Db\Sql\Select), Array) #5 /var/www/html/ in /var/www/html/api/core/Directus/Database/TableGateway/BaseTableGateway.php on line 700
```

**Comment by WellingGuzman** [comment] 2017-07-20 20:28
Hey @jacobzeng, thanks for the report.  this issue was fixed by https://github.com/directus/directus/commit/dc547af4868b53b50f45d9ceb24126309b445e50

**Comment by jacobzeng** [comment] 2017-07-21 01:08
Hey @WellingGuzman ,thanks for  you reply,.
I update the newest code(develop branch), and still got the error.

```

Fatal error: Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of Exception, instance of Error given in /var/www/html/installation/bootstrap.php:17 Stack trace: #0 [internal function]: {closure}(Object(Error)) #1 /var/www/html/api/core/Directus/Hook/Emitter.php(266): call_user_func_array(Object(Closure), Array) #2 /var/www/html/api/core/Directus/Hook/Emitter.php(107): Directus\Hook\Emitter->executeListeners(Array, Array, 0) #3 /var/www/html/api/core/Directus/Exception/ExceptionHandler.php(73): Directus\Hook\Emitter->run('application.err...', Object(Error)) #4 [internal function]: Directus\Exception\ExceptionHandler->handleException(Object(Error)) #5 {main} thrown in /var/www/html/installation/bootstrap.php on line 17
```

**Comment by WellingGuzman** [comment] 2017-07-21 01:59
Hey @jacobzeng, what are the tables the installer created? Did you clear all the previous table created?

**Comment by jacobzeng** [comment] 2017-07-21 07:27
I just create a new database for test, there is no any tables created by install steps, so weird!
For now, i created the tables by execute `api/schema.sql` manually.

BTW, thanks to your guys for share the cool tool.

**Comment by WellingGuzman** [comment] 2017-07-21 08:53
Hey @jacobzeng, are you using the `develop` branch or the tar file?

It seems it's throwing a different error, now.

If you go to `installation/bootstrap.php` and comment out these lines:

```php
$emitter = new \Directus\Hook\Emitter();
$exceptionHandler = new \Directus\Exception\ExceptionHandler($emitter);
$emitter->addAction('application.error', function (Exception $exception) {
    $now = time();
    $path = get_directus_path();
    $message = $exception->getMessage();

    include __DIR__ . '/views/page.php';
});
```

And try again, what error do you see when you click install?

**Comment by piupiupiu** [comment] 2017-07-24 11:55
I have exactly the same issue. Removing the code you suggested throws a 500 error.

**Comment by WellingGuzman** [comment] 2017-07-24 18:33
@piupiupiu exactly what I was expecting to see, but any good information about that 500 error? any backtrace?

**Comment by piupiupiu** [comment] 2017-07-25 08:36
@WellingGuzman,

Here is the stack trace:

https://pastebin.com/8cwgmw9k

I'm not sure if it is helpful. I found somewhere the following advice:

> $emitter->addAction('application.error', function (Exception $exception) {

replaced with

> $emitter->addAction('application.error', function (Throwable $exception) {

It produced another bunch of errors but directus was actually installed.

**Comment by WellingGuzman** [comment] 2017-07-25 15:21
@piupiupiu are the errors above thrown when you replace `Exception` with `Throwable` or when you remove those lines from `bootstrap.php`? it seems to be chopped though.

Whatever it is it seems it's an Fatal Error, but can't see of any logs that has been share with us what was the actual error message.

**Comment by Keyes** [comment] 2017-07-30 18:33
Got the same error:

- PHP 7.0.15-1
- nginx/1.11.3
- MySQL 5.5.56-MariaDB
- Ubuntu 14.04.5 LTS
- directus checked out via git master

Two tables were created when the error occurs: directus_groups, directus_schema_migrations

**Comment by WellingGuzman** [comment] 2017-08-02 18:11
Hey @Keyes, Thanks for the information.

did you try the `develop` branch? We are trying to reproduce this error. It was suppose to be fixed by https://github.com/directus/directus/commit/dc547af4868b53b50f45d9ceb24126309b445e50

We are still trying to check that configuration is triggering this issue.

**Closed** 2017-08-07 17:34 UTC
Labels: 1. Blocker, Bug, Schema-Change

**Comment by Keyes** [comment] 2017-08-09 12:16
Error with current (pulled 5 Minutes ago) develop branch:

> Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'directus.directus_tables' doesn't exist in /var/www/XXXX/html/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php:239 Stack trace: #0 /var/www/XXXX/html/directus/vendor/zendframework/zend-db/src/Adapter/Driver/Pdo/Statement.php(239): PDOStatement->execute() #1 /var/www/XXXX/html/directus/vendor/zendframework/zend-db/src/TableGateway/AbstractTableGateway.php(239): Zend\Db\Adapter\Driver\Pdo\Statement->execute() #2 /var/www/XXXX/html/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(708): Zend\Db\TableGateway\AbstractTableGateway->executeSelect(Object(Zend\Db\Sql\Select)) #3 /var/www/XXXX/html/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php(689): Directus\Database\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select), Array) #4 /var/www/XXXX/html/directus/api/core/Directus/Database/TableGateway/BaseTableGate in /var/www/XXXX/html/directus/api/core/Directus/Database/TableGateway/BaseTableGateway.php on line 730
