### ISSUE TITLE
DefineHooks Init Method Doesnt Work

### ISSUE THREAD

**Issue by bekirbostanci** [directus/directus#22681] opened 2024-06-06 08:26 UTC
### Describe the Bug

Story :  I have one application and inside of the application there are clients, drivers and delivery collections. 
Delivery collection must contains driver and client and also I dont want to do it with relational way because at future when something changed in  that time old delivery will also. 
Because of this I created one extension and before than I save, extension will get information from other collection and copy information. I mean I want to create deep copy and shallow copy. 

Problem : When I try to get data inside of **filter event** it doesnt work. When I try to get data in **init event** it doesnt work again. I searched an example but there is not.  Am I missing something or does init event function not work properly? 
 
```
import { defineHook } from "@directus/extensions-sdk";
import { createDirectus, rest, readItems } from "@directus/sdk";

async function fetchData() {
  const client = createDirectus("http://localhost:8055/").with(rest());
  const result = await client.request(
    readItems("clients", {
      fields: ["*"],
    })
  );
  console.log(result);
}

export default defineHook(({ filter, action, init }) => {
  filter("items.create", async (input: any, { collection }) => {
    await fetchData();
    console.log("Creating Item!3");
    if (collection === "delivery") {
      console.log(input);
    }

    return input;
  });
  action("items.create", async () => {
    await fetchData();
    console.log("Item created!");
  });

  init("items.create", async () => {
    await fetchData();
    console.log("test");
  });
});

```

### To Reproduce

Create a hook extension and try to trigger init function 

### Directus Version

v10.11.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite3

**Comment by hanneskuettner** [comment] 2024-06-06 09:27
I think you're misunderstanding where your hooks are running. Hooks run on the server, so there is no need for you to use the SDK here. You can simply use the services that are available server side, you can find more info in [our documentation](https://docs.directus.io/extensions/services/introduction.html). 

Also the event you're trying to listen in the `init` does not exist, check out the available events here: https://docs.directus.io/extensions/hooks.html#available-events

I'll close this now, as this is not a bug in Directus, but rather an implementation problem on your end. If you have any further questions where things are unclear, please head over to our [Community Discord](https://directus.chat) and ask your questions over there, thank you!

**Closed by hanneskuettner** 2024-06-06 09:27 UTC

**Comment by bekirbostanci** [comment] 2024-06-06 10:26
Thank you for your fast reply and thank you for information about availability about **init** event. 
When I change my db sqlite to pg ItemsService works inside of the filter event. However at sqlite it doesnt work. Maybe because of me but just if somebody faced with same problem, change database to pg.

**Comment by hanneskuettner** [comment] 2024-06-06 10:39
That does sound like a problem. There shouldn't be a difference between sqlite and postgres. Do you mind sharing any errors you're seeing when using the ItemsService in the filter hook?

**Comment by bekirbostanci** [comment] 2024-06-06 10:47
Sorry I delete the database but luckily I tried to solve problem with chat gpt :) and I had written error message to there.
I am not sure but I think, inside of the filter event directus and my extension tries to access database at the same time because of this reason problem occurs.

```
  ERROR: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?

			axios.get('http://localhost:8055/items/clients/1')
			.then(function (response) {
				// handle success
				console.log(response);
			})


			const test = await axios.get('http://localhost:8055/items/clients/1')
```

**Comment by hanneskuettner** [comment] 2024-06-06 10:53
That has to do with the way you're creating the `ItemsService`, the hook receives a `database` property in the context, which might be a `knex.transaction`, if one has been created. If you're not passing that one to your `ItemsService` like so: `ItemsService({knex: database})` the default database connection will be used which deadlocks in SQLite. So I'm afraid to say, that was still an implementation problem.

**Comment by bekirbostanci** [comment] 2024-06-06 10:55
It is possible but just when I didnt change anything same code worked with pg. Anyways thanks for your fast replies :)
