### ISSUE TITLE
TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by andrew-medvedev** [directus/directus#3527] opened 2020-12-28 08:56 UTC
1) After connecting to my existing database(with some content for my mobile game), I've just clicked on one of the collections and website stopped responding. At console I got this: https://gyazo.com/b1a68ffb47fb2f12920b693ff4786b3a

2) Run app with `directus start`, go to localhost:8055, login, click on collection `Action Chains`

3) Directus 9.0.0-rc.26 , Postgresql x64 12 , Node v12.19.0 , Brave v1.18.75

4) I don't think so

**Comment by andrew-medvedev** [comment] 2020-12-28 09:04
Reproduced at latest chrome: https://gyazo.com/6a651c334c96c720ba767c1c86e1ccdd

**Comment by rijkvanzanten** [comment] 2020-12-28 15:28
@andrew-medvedev What displays are you using on that collection?

**Comment by andrew-medvedev** [comment] 2020-12-28 16:14
@rijkvanzanten I don't use any displays. I'm not using any displays and I've not learned anything about them yet.
All I did is from this guide: https://docs.directus.io/guides/installation/cli.html

**Comment by benhaynes** [comment] 2021-02-10 17:15
What info do we need to debug this? @rijkvanzanten

**Comment by rijkvanzanten** [comment] 2021-02-10 17:18
An accurate way to reproduce this. I haven't seen this happen on fresh installs, so there must be some combination of defaults on this particular existing db schema 🤔

**Comment by rijkvanzanten** [comment] 2021-02-24 18:58
I'll close this for now. We're not able to reproduce this and it doesn't seem like anybody else has run into this since..

If you have a particular way to reproduce this @andrew-medvedev we can reopen!

**Closed by rijkvanzanten** 2021-02-24 18:58 UTC
Labels: App, Needs More Info

**Comment by ananokta** [comment] 2021-11-25 18:35
I have the same error using a natural key on the following schema:
CREATE TABLE `cronmon` (
  `domain` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cronrun` datetime DEFAULT NULL,
  `dbbackup` datetime DEFAULT NULL,
  `dbbackuppurge` datetime DEFAULT NULL,
  `updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `cronmon`
  ADD PRIMARY KEY (`domain`);
COMMIT;
__
directus:9.0.0-rc.101

**Comment by gurumark** [comment] 2021-11-25 18:36
I have the same error using a natural key on the following schema:
CREATE TABLE cronmon (
domain varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
cronrun datetime DEFAULT NULL,
dbbackup datetime DEFAULT NULL,
dbbackuppurge datetime DEFAULT NULL,
updated datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE cronmon
ADD PRIMARY KEY (domain);
COMMIT;
__
directus:9.0.0-rc.101

**Comment by rijkvanzanten** [comment] 2021-11-25 18:41
@gurumark This issue is very old and for a version that's very different from the release you're on. Mind opening a new issue?
