### ISSUE TITLE
Multi select is not working if more than 15 items are selected in directus.(Many-to-Many relation)

### ISSUE THREAD

**Issue by evantdm** [directus/directus#17580] opened 2023-02-21 07:06 UTC
### Checklist

- [X] I'm using the [latest version of Directus](https://github.com/directus/directus/releases)
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes the problem.
- [X] I've completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).

### Describe the Bug

I have created a new collection called trainee and many to many relationship exists between user collection and trainee collection. When i try to map multiple trainee with user, its not allowing me to add more than 15 users. For first 15 items its showing the value, for remaining items no value is shown in UI. Even I tried to change the pagination, it's still not working.
I have added the video below to reproduce the issue.

### To Reproduce

https://user-images.githubusercontent.com/93902000/220268011-727ba97b-4c49-425c-9750-afa36e9e7613.mp4

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by paescuj** [comment] 2023-02-21 08:30
Thanks for opening this issue! However this is a duplicate of an existing issue #17413, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. The existing issue #17413 has been fixed by #17439 which will be available with the next release.

**Closed by paescuj** 2023-02-21 08:30 UTC
