### ISSUE TITLE
Directus recreate an entry when updating a relationship

### ISSUE THREAD

**Issue by shankiflang** [directus/directus#13042] opened 2022-04-28 13:11 UTC
### Describe the Bug

I have a little problem with the way Directus works.
To make it simple I'll explain:
I have a data model of recipes. In this one, I put an one to many to a data model that will act as a join. It will group the ingredients with their quantity and the unit (L, kg, ...) in the said recipe. (You can see the image)
When I add an ingredient and select it, everything is fine. The problem comes when I reopen a recipe with ingredients and I want to change the name of the ingredient or any other information. It will, instead of just changing the entry, recreate an ingredient. As I have put that the ingredients must be unique, I can't modify them in the recipes. I can only add them and once validated, it's over.
Do you know if I made a mistake with the relations or is it a problem in Directus?

### To Reproduce

![photo_2022-04-28_14-28-16](https://user-images.githubusercontent.com/32774804/165759631-b8dd2403-27c3-4fb2-bd92-90a73df5aa3b.jpg)

### What version of Directus are you using?

9.9.0

### What version of Node.js are you using?

16.14.2

### What database are you using?

Postgre

### What browser are you using?

Chrome

### How are you deploying Directus?

Docker

**Comment by rijkvanzanten** [comment] 2022-04-28 13:41
Can you try updating to the latest version of Directus? I'm fairly sure this was fixed in https://github.com/directus/directus/pull/12840. We can reopen if it doesn't work in the latest version 👍🏻

**Closed by rijkvanzanten** 2022-04-28 13:41 UTC
Labels: Bug (Potential)

**Comment by shankiflang** [comment] 2022-04-28 13:45
> Can you try updating to the latest version of Directus? I'm fairly sure this was fixed in #12840. We can reopen if it doesn't work in the latest version 👍🏻

I updated Directus but still the error. Is there any particular manipulation to do other than changing the version of Directus?

**Comment by rijkvanzanten** [comment] 2022-04-28 14:10
Would you be able to share a database dump of a minimal reproduction? I have some trouble reproducing the setup based on the image and description alone (the exact relational configuration matters a lot here 🙂 )

**Comment by shankiflang** [comment] 2022-04-28 14:55
> Would you be able to share a database dump of a minimal reproduction? I have some trouble reproducing the setup based on the image and description alone (the exact relational configuration matters a lot here 🙂 )

I can only retrieve the entire database. Where can I send it to you?

**Comment by shankiflang** [comment] 2022-04-28 15:59
mmh I recreated all the tables with relation and it seems to be solved. I'll get back to you just in case. Thanks!

**Comment by shankiflang** [comment] 2022-04-30 10:08
@rijkvanzanten I made a directus test website. https://directustest.slatsh.com/ with defaut admin account. Is it okay for you to try ? (I looked and the error is still there)

**Comment by shankiflang** [comment] 2022-04-30 10:23
[directustest.zip](https://github.com/directus/directus/files/8596680/directustest.zip)
And here is the sql

**Comment by br41nslug** [comment] 2022-05-05 12:39
This is happening because the o2m interface is not properly sending id's of relations on the junction table.
