### ISSUE TITLE
Related items not showing up in the side editor

### ISSUE THREAD

**Issue by rafmsou** [directus/directus#13018] opened 2022-04-26 18:29 UTC
### Describe the Bug

The side editor that opens up a related collection shows its relations as blank even though there is a related item there:

<img width="1629" alt="image" src="https://user-images.githubusercontent.com/1795949/165365569-7e99c7af-18be-4bac-b329-cf4d6bc4034c.png">

This seems to be happening for all types of relationships.

### To Reproduce

- Create a collection **Collection_A** with a M2M field to **Collection_B**
- In the **Collection_B** collection create a M2M field to **Collection_C**
- Feed data into those 3 collections
- Open **Collection_A** and try to navigate to **Collection_C** 

**Collection_C** won't be reachable because the field in the side editor will show as "No items" in **Collection_B**

### Errors Shown

No errors in the console or network requests

### What version of Directus are you using?

Cloud Project - 9.9.0

### What version of Node.js are you using?

Cloud Project

### What database are you using?

Cloud Project

### What browser are you using?

Chrome

### How are you deploying Directus?

Cloud Project

**Comment by rijkvanzanten** [comment] 2022-04-26 18:40
Duplicate of https://github.com/directus/directus/issues/12836. This was released as 9.9.1 which will be on cloud soon 👍🏻

**Closed by rijkvanzanten** 2022-04-26 18:40 UTC
Labels: Bug (Potential)

**Comment by rafmsou** [comment] 2022-04-26 18:59
@rijkvanzanten Actually 9.9.1 was already deployed but the support team had to roll it back because of other issues. I'll check with them again what can be done.
