### ISSUE TITLE
"Delete mode" - "Delete related item" and "Nullify relationship" not working 

### ISSUE THREAD

**Issue by awbranch** [directus/directus#2458] opened 2019-11-04 15:58 UTC
# Bug Report
Deleting a parent object does not delete a related child object as expected.

## Steps to Reproduce
1. Create a collection named "Parent"
2. Create a collection named "Child"
3. In Child collection create a Many to One to the parent
4. In the Parent collection create a One to Many to the child named children
5. In the children field under "Options" select "Delete mode" "Delete related item"
6. Create a parent and several children
7. Delete the parent
8. Check the database, the children are still there

Repeat but set the children "Options" "Delete mode" to "Nullify relationship" it doesn't nullify the relationship.

## Expected Behavior
After the delete of the parent object, the child objects should be deleted or have their foreign keys to the parent nullified.

## Actual Behavior
The child object isn't removed or its parent foreign key isn't set to null.

Also if there is a foreign key constraint between the parent and child directus displays an error, presumably because it isn't deleting the children correctly. 

## Technical Details

- Install Method: Cloned master - commit 190927A from https://github.com/directus/directus.git

**Comment by benhaynes** [comment] 2019-11-04 16:44
Thanks! Duplicate of: https://github.com/directus/api/issues/384

**Closed by benhaynes** 2019-11-04 16:44 UTC
Labels: duplicate
