### ISSUE TITLE
"ws://undefined/websocket" in docker startup logs

### ISSUE THREAD

**Issue by pomeh** [directus/directus#23516] opened 2024-08-29 16:54 UTC
### Describe the Bug

When running Directus via a docker image, latest version 11.0.2 show some invalid config in the startup log

### To Reproduce

Start a fresh directus instance via Docker image with an empty SQLite database, and check logs (`docker logs`).

With version `10.13.1`:

```
[18:07:59.006] WARN: Spatialite isn't installed. Geometry type support will be limited.
[18:07:59.010] INFO: Watching extensions for changes...
[18:07:59.066] INFO: GraphQL Subscriptions started at ws://0.0.0.0:8055/graphql
[18:07:59.067] INFO: WebSocket Server started at ws://0.0.0.0:8055/websocket
[18:07:59.083] INFO: Server started at http://0.0.0.0:8055
```

With version `11.0.2`:

```
[18:16:56.495] WARN: Spatialite isn't installed. Geometry type support will be limited.
[18:16:56.500] INFO: Watching extensions for changes...
                                                           👇👇👇👇
[18:16:56.557] INFO: GraphQL Subscriptions started at ws://undefined/graphql
                                                           👇👇👇👇
[18:16:56.557] INFO: WebSocket Server started at ws://undefined/websocket
[18:16:56.575] INFO: Server started at http://0.0.0.0:8055
```

I've not encoutered problems while using Directus app, but I don't use GraphQL and I'm not sure I'm using websocket at all.

### Directus Version

v11.0.2

### Hosting Strategy

Self-Hosted (Docker Image)

### Database

sqlite

**Comment by hanneskuettner** [comment] 2024-08-29 17:32
Duplicate of #23484

**Closed** 2024-08-29 17:32 UTC
