### ISSUE TITLE
Different search results in the M2M field.

### ISSUE THREAD

**Issue by koksikus** [directus/directus#17391] opened 2023-02-03 13:01 UTC
### Describe the Bug

I have 2 collections linked by M2M relationship. Being first in the main search by searching through this field the search result is valid.
If I am in the second collection in a specific record and I try to add data from the first collection and the filter has the same rule because I just searched for it in the first collection but there is a different result. In the previous version of directus 9.18.1 it works great.

### To Reproduce

Create 2 collections
add M2M field
search the table through this field with a filter on the second collection, e.g. where there is a number in the field
Go to the second collection
enter a specific record
into the M2M field
Click add existing
try to add only records that match the filter above
(the difference for me is 24 records in the first case, in the second more than 300 are displayed)

### What version of Directus are you using?

9.22.4

### What version of Node.js are you using?

16.18.1

### What database are you using?

MS SQL

### What browser are you using?

Edge

### How are you deploying Directus?

locally

**Comment by paescuj** [comment] 2023-02-03 13:17
Thanks for opening this issue! However this is a duplicate of an existing issue #17028, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment.

#17028 has been fixed by #17184 which will be available with the next release.

**Closed by paescuj** 2023-02-03 13:17 UTC
