### ISSUE TITLE
Request to `/dashboards` results in error 403 during page launch

### ISSUE THREAD

**Issue by licitdev** [directus/directus#8517] opened 2021-10-03 13:40 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

Denying permissions of `directus_dashboards` or setting to `App Access Minimum` permissions results in a request with error 403 when the app loads. 

<img width="733" alt="Screenshot 2021-10-03 at 9 27 46 PM" src="https://user-images.githubusercontent.com/26413686/135755890-23b0ab03-33e4-4e3c-823f-b207918f2a52.png">

The request is sent from the latter code block.

https://github.com/directus/directus/blob/fb815913573cfff3e724f34bf5102fb85f84f1ac/app/src/stores/insights.ts#L11-L15

How should this issue be resolved?

### To Reproduce

Create a role, with `App Access Minimum` permissions or with denied access to `directus_dashboards`.
Refresh app and see the failed request in the network request tab.

### What version of Directus are you using?

v9.0.0-rc.95

### What version of Node.js are you using?

v16

### What database are you using?

Postgres

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

PaaS

**Comment by azrikahar** [comment] 2021-10-04 06:23
IIRC I've raised this out when Insights module first got merged, and @rijkvanzanten promptly added the try catch block in [this commit](https://github.com/directus/directus/commit/87bc6731e7a4bb099b0a6aaa9cbe61a40304944c) which should be in rc.95 already. 

https://github.com/directus/directus/blob/fb815913573cfff3e724f34bf5102fb85f84f1ac/app/src/stores/insights.ts#L12-L20

On second thought, can you clarify the bug here? The user with no permission can still access the app without issue right (IIRC the user can't access the app if the catch wasn't implemented)? I believe it is an intended behaviour, as  they don't have permission to view dashboard, hence the catch block sets it as an empty array.

**Comment by licitdev** [comment] 2021-10-04 06:37
@azrikahar Yes I saw the try catch, the app runs fine.
However, I thought that for a production app, there should be no unnecessary requests leading to 403.
Example for another module such as `directus_files`, if permission is not given, there is no request leading to error 403.

Hence I was asking on how should this issue be resolved: prevent the request from going in the first place.
Or perhaps should the request resulting in 403 error should be ignored?

**Comment by azrikahar** [comment] 2021-10-04 07:51
That's a valid point indeed 👍

> prevent the request from going in the first place.

Hmm we should be able to do this by checking the user role via user store, or maybe even the permission via permission store, which might then be better than ignoring the error. @rijkvanzanten thoughts on this?

**Comment by licitdev** [comment] 2021-10-04 08:07
@azrikahar I usually debug issues both with the latest code base and RC before submitting a bug report. 
Sometimes the fix is rather clearcut, which I would push a PR for it. 
However for this issue, as I wasn't sure which is the best way to resolve, thus the question in the bug report. 
Thank you for clarifying! 😊

**Comment by rijkvanzanten** [comment] 2021-10-04 14:08
> Hmm we should be able to do this by checking the user role via user store, or maybe even the permission via permission store, which might then be better than ignoring the error. @rijkvanzanten thoughts on this?

Yeah good one. Currently, the dashboards store is hydrated simultaneously with the permissions store, so we don't have that information yet at that point of the flow. We can update that to fetch the permissions first before any of the other stores, and then handle that gracefully (that's probably the best way forwards for this)

**Closed** 2021-10-07 22:17 UTC
Labels: App, Bug, Hacktoberfest
