### ISSUE TITLE
Invited admin users cannot set their password in rc.93 and rc.94

### ISSUE THREAD

**Issue by HitomiTenshi** [directus/directus#8274] opened 2021-09-23 20:47 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues) that already describes my problem.

### Describe the Bug

I was inviting another user to my directus instance today and it turns out they cannot set their password. This is was the client sees:

![chrome_2021-09-23_22-38-02](https://user-images.githubusercontent.com/7304212/134581045-365f91a0-1c5b-40e6-9730-8cabe84d8fe3.png)

This is the error on the server side:

```
Sep 23 20:36:51 directus[998892]: 20:36:51 ✨ request errored POST 500 /users/invite/accept 11ms
Sep 23 20:36:51 directus[998892]:     at Runner.ensureConnection (/opt/directus/node_modules/knex/lib/execution/runner.js:272:20)
Sep 23 20:36:51 directus[998892]:     at ensureConnectionCallback (/opt/directus/node_modules/knex/lib/execution/internal/ensure-connection-callback.js:13:17)
Sep 23 20:36:51 directus[998892]:     at Runner.query (/opt/directus/node_modules/knex/lib/execution/runner.js:130:36)
Sep 23 20:36:51 directus[998892]:     at Client_MySQL.query (/opt/directus/node_modules/knex/lib/client.js:134:12)
Sep 23 20:36:51 directus[998892]:     at executeQuery (/opt/directus/node_modules/knex/lib/execution/internal/query-executioner.js:37:17)
Sep 23 20:36:51 directus[998892]:     at Client_MySQL._query (/opt/directus/node_modules/knex/lib/dialects/mysql/index.js:120:12)
Sep 23 20:36:51 directus[998892]:     at new Promise (<anonymous>)
Sep 23 20:36:51 directus[998892]:     at /opt/directus/node_modules/knex/lib/dialects/mysql/index.js:126:18
Sep 23 20:36:51 directus[998892]:     at Connection.query (/opt/directus/node_modules/mysql/lib/Connection.js:198:25)
Sep 23 20:36:51 directus[998892]:     at Protocol._enqueue (/opt/directus/node_modules/mysql/lib/protocol/Protocol.js:144:48)
Sep 23 20:36:51 directus[998892]:     --------------------
Sep 23 20:36:51 directus[998892]:     at addChunk (internal/streams/readable.js:290:12)
Sep 23 20:36:51 directus[998892]:     at Socket.emit (events.js:400:28)
Sep 23 20:36:51 directus[998892]:     at Socket.<anonymous> (/opt/directus/node_modules/mysql/lib/Connection.js:526:10)
Sep 23 20:36:51 directus[998892]:     at Socket.<anonymous> (/opt/directus/node_modules/mysql/lib/Connection.js:88:28)
Sep 23 20:36:51 directus[998892]:     at Protocol.write (/opt/directus/node_modules/mysql/lib/protocol/Protocol.js:38:16)
Sep 23 20:36:51 directus[998892]:     at Parser.write (/opt/directus/node_modules/mysql/lib/protocol/Parser.js:43:10)
Sep 23 20:36:51 directus[998892]:     at Parser._parsePacket (/opt/directus/node_modules/mysql/lib/protocol/Parser.js:433:10)
Sep 23 20:36:51 directus[998892]:     at Protocol._parsePacket (/opt/directus/node_modules/mysql/lib/protocol/Protocol.js:291:23)
Sep 23 20:36:51 directus[998892]:     at Query.ErrorPacket (/opt/directus/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
Sep 23 20:36:51 directus[998892]:     at Query.Sequence._packetToError (/opt/directus/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
Sep 23 20:36:51 directus[998892]: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `status` = 'active' where `id` = 'd57fb6d7-db37-42ce-808d-f484f0524670'' at line 1
Sep 23 20:36:51 directus[998892]: 20:36:51 🚨 update `directus_users` set `password` = {}, `status` = 'active' where `id` = 'd57fb6d7-db37-42ce-808d-f484f0524670' - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' `status` = 'active' where `id` = 'd57fb6d7-db37-42ce-808d-f484f0524670'' at line 1
```

Doesn't work on both `rc.93` and `rc.94`.

### To Reproduce

1. Invite an email with the role "Administrator".
2. Click the invite link in the email
3. Try to set your password, it doesn't work (seems to be some issue with MariaDB?)

Tested on both `rc.93` and `rc.94`.

### What version of Directus are you using?

v9.0.0-rc.94

### What version of Node.js are you using?

14.17.6

### What database are you using?

MariaDB 10.3.31

### What browser are you using?

Chrome

### What operating system are you using?

Windows Client / Ubuntu 20.04 Server

### How are you deploying Directus?

running locally via npm package

**Comment by rijkvanzanten** [comment] 2021-09-23 20:48
Duplicate of https://github.com/directus/directus/issues/8229

**Closed by rijkvanzanten** 2021-09-23 20:48 UTC
Labels: Bug (Potential)
