### ISSUE TITLE
O2M validation problem

### ISSUE THREAD

**Issue by MadnessCODE** [directus/directus#5235] opened 2021-04-24 08:18 UTC
Hi, 
I have 2 collections ex.(item, categories) and both had slug field as required, and O2M relation between. When I added new category on item this error appeared: 
'There were validation errors for the following hidden fields: name: validationError.FAILED_VALIDATION'

When I remove required flag from categories collection everything works fine

Environment:
    Directus v9.0.0-rc.60
    Mysql 5.7.30
    Windows
    Node 15.2.0

**Comment by rijkvanzanten** [comment] 2021-04-24 14:19
Duplicate of https://github.com/directus/directus/issues/5070

**Closed by rijkvanzanten** 2021-04-24 14:19 UTC
