### ISSUE TITLE
Studio not enforcing translation fields marked as mandatory.

### ISSUE THREAD

**Issue by laportem** [directus/directus#20690] opened 2023-12-10 03:03 UTC
### Describe the Bug

All translation fields of a collection marked as mandatory are not being enforced by data studio. It allows translation fields flagged as mandatory to be saved with null or blank value.

### To Reproduce

Create a translation relationship, and make the translation relationship mandatory. Next, create a mandatory text field in the translation relationship collection. Try to save a collection record without a value in the translation field.

### Directus Version

v10.8.2

### Hosting Strategy

Self-Hosted (Docker Image)

**Comment by azrikahar** [comment] 2023-12-11 09:25
Thanks for opening this issue! However this is a duplicate of an existing issue #15604, so I'll proceed to close this but if you think this is actually a different issue, then please do not hesitate to comment. Otherwise you may subscribe to #15604 for future updates. [^1]

[^1]: _This is an automated response._

**Closed by azrikahar** 2023-12-11 09:25 UTC
