### ISSUE TITLE
Folder structure is not available in file drawer

### ISSUE THREAD

**Issue by lahdekorpi** [directus/directus#5082] opened 2021-04-15 15:25 UTC
The folder structure is only available in the File Library, not the File Drawer. This causes issues in projects with thousands of pictures organized into folders.

![image](https://user-images.githubusercontent.com/570545/114895044-d29ef000-9e17-11eb-821b-e7b5d7360bc4.png)
Folder structure.

![image](https://user-images.githubusercontent.com/570545/114895155-ec403780-9e17-11eb-98db-3960e6d3f66b.png)
Structure not available.

**Comment by rijkvanzanten** [comment] 2021-04-15 15:27
Duplicate of https://github.com/directus/directus/discussions/4999

**Closed by rijkvanzanten** 2021-04-15 15:27 UTC
