### ISSUE TITLE
Duplicating Fields on almost all collections in UI

### ISSUE THREAD

**Issue by rogersanick** [directus/directus#11434] opened 2022-02-04 14:55 UTC
### Preflight Checklist

- [X] I have completed all [Troubleshooting Steps](https://docs.directus.io/getting-started/support/#troubleshooting-steps).
- [X] I'm on [the latest version of Directus](https://github.com/directus/directus/releases).
- [X] There's [no other issue](https://github.com/directus/directus/issues?q=is%3Aissue) that already describes my problem.

### Describe the Bug

We are seeing duplicate fields on almost all collections. 

### To Reproduce

1. Define a collection based on a pre-existing DB Table
2. Add all of the fields and define appropriate interfaces
3. Navigate to the content section (main application page)
4. Click on a collection
5. View duplicate fields

It seems like most of the duplicated fields are FK relationships:
<img width="718" alt="Screen Shot 2022-02-04 at 9 54 14 AM" src="https://user-images.githubusercontent.com/16504493/152550201-7780b8b6-7c1f-4521-a3d8-e57d36615fd7.png">

The fields also multiply when they are edited. This behavior partially resets when you refresh the page:

![image](https://user-images.githubusercontent.com/16504493/152552002-60a78cfd-1ce8-4cc3-b426-97dedd6f7e35.png)

### Errors Shown

N/A

### What version of Directus are you using?

9.4.3

### What version of Node.js are you using?

16.13.2

### What database are you using?

Postgres 10

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### How are you deploying Directus?

Docker

**Comment by azrikahar** [comment] 2022-02-07 08:54
This could be unrelated, but it does remind me of a similar phenomenon reported here: https://github.com/directus/directus/discussions/10557#discussioncomment-1826084, where it ended up being the db structure imported from DataGrip turned all the keys to the same name. 

When you say pre-existing DB Table, was it by any chance imported from DataGrip (or even via other db management tool)? Would you mind checking the contraints names whether they are repeating or of the same name?

**Comment by rogersanick** [comment] 2022-02-14 19:33
Hey @azrikahar - it was not imported by DataGrip and I can also confirm that the constraint names are all unique. We just went live and the duplicate fields are not a good look. Any insight would be greatly appreciated!

**Comment by azrikahar** [comment] 2022-02-15 03:02
Hi, personally I'm not actively looking into this per se, but perhaps you can share the info below so that it'll be helpful for others that are/will look into this:

- Can you try with the latest version `v.9.5.1`? There has been quite a number of DB related commits since 9.5.0 so I'm not entirely does that resolve it for you already.

- Related to above point, I gave it a try in an attempt to replicate this issue on PostgreSQL with 2 tables & a foreign key, but I wasn't able to reproduce it. Perhaps you help provide a minimal (no sensitive data) dump, preferably with the least amount of tables/relationships that still reproduces this issue? It'll definitely be helpful for others when they do check this out 👍

**Comment by rijkvanzanten** [comment] 2022-04-18 23:22
I'll close this for now, as we haven't been able to reproduce the issue 👍🏻

**Closed by rijkvanzanten** 2022-04-18 23:22 UTC
Labels: Can't Reproduce
