### ISSUE TITLE
Many to any relation - with sort; not sorting correctly

### ISSUE THREAD

**Issue by aliemba** [directus/directus#3750] opened 2021-01-19 20:08 UTC
Hi,

A M2A relationship + adding a sort in the interface, does not sort as expected.

![image](https://user-images.githubusercontent.com/44196248/105086888-f31a1100-5a99-11eb-9a60-46956f8f1a2b.png)

When altering the sort order via dragging; then saving - the rows revert to the original order thus ignoring the newly sorted values.

The sorting values are though updated in the database, after dragging.

Ubuntu, mysql, v9.0.0-rc.30

**Comment by rijkvanzanten** [comment] 2021-01-19 22:02
Duplicate of https://github.com/directus/directus/issues/3315

**Closed by rijkvanzanten** 2021-01-19 22:02 UTC
Labels: App, Bug
